### ISSUE TITLE
Searchbox is spread when creating a new folder

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18736] opened 2015-09-01 10:01 UTC
### Steps to reproduce

1. Click on new button, and then on 'text file'
2. Write down the name of the new file
3. Press enter key

### Expected behaviour

The file is created

### Actual behaviour
The file is created, but the searchbox is spread. Maybe is not the effect desired.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
  - activity: 2.1.2
  - admin_audit: 0.6
  - enterprise_key: 0.1.0
  - files: 1.1.11
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.2
  - files_sharing_log: 0.5
  - files_texteditor: 0.4
  - files_versions: 1.0.6
  - files_videoviewer: 0.1.3
  - firewall: 0.91.2
  - firstrunwizard: 1.1
  - gallery: 14.0.0
  - provisioning_api: 0.2
  - templateeditor: 0.1
  - updater: 0.6
  - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by karlitschek** [comment] 2015-09-01 10:05
@jancborchardt

**Comment by jancborchardt** [comment] 2015-09-08 10:58
Duplicate of https://github.com/owncloud/core/issues/18674

**Closed by jancborchardt** 2015-09-08 10:58 UTC
Labels: design, enhancement - proposed
