### ISSUE TITLE
Argument 3 passed to OC\Hooks\BasicEmitter::listen() must be callable

### ISSUE THREAD

**Issue by localguru** [owncloud/core#21350] opened 2015-12-23 10:34 UTC
Hi,

after upgrading this morning from 8.1.4 to 8.1.5.2 I get the following error in the log:

Argument 3 passed to OC\Hooks\BasicEmitter::listen() must be callable, array given, called in /var/www/owncloud/apps/files/ajax/scan.php on line 50 and defined at /var/www/owncloud/lib/private/hooks/emittertrait.php#36

System: Ubuntu 14.04 LTS
Webserver: apache2 2.4.7-1ubuntu4.8
PHP: php5 5.5.9+dfsg-1ubuntu4.14
Database: mysql 5.5.46-0ubuntu0.14.04.2

Apps:
Enabled:
 - activity: 2.0.2
 - calendar: 0.7.3
 - contacts: 0.4.0.1
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

Disabled:
 - direct_menu
 - encryption
 - external
 - files_external
 - ownbackup
 - storagecharts2
 - updater
 - user_external
 - user_ldap
 - user_otp
 - user_webdavauth

Installation from: http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/

Ciao!

**Comment by PVince81** [comment] 2015-12-23 11:35
@icewind1991 please have a look, potential regression

**Comment by localguru** [comment] 2015-12-23 17:25
Upgrade to 8.2.2, error gone.
Repository: http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/

**Comment by christianlx** [comment] 2015-12-30 15:22
I've ugrade to 8.1.5 yesterday and I have exactly the same issue. This message appear each time an user login in the web interface. Anyway, I haven't notice any errors in my current usage for the moment.

System: Centos 6.7
Webserver: apache
PHP: php 5.5.30
Database: mysql

**Comment by MorrisJobke** [comment] 2016-01-05 09:35
Fix is in https://github.com/owncloud/core/pull/21457

**Comment by MorrisJobke** [comment] 2016-01-05 15:03
Fix went in via #21463 - for 8.2 we don't support PHP 5.3 anymore which was the cause of this issue.

**Closed** 2016-01-05 15:02 UTC
Labels: 3 - To Review, bug, comp:core, in progress

**Comment by danduk82** [comment] 2016-03-22 16:20
Hello,
I also get this issue, I'm using php5.6 on a debian jessie. I use the official owncloud repository, owncloud version: owncloud_8.1.5-15.1 . Will the repository be upgraded to 8.2 ?

Cheers
