### ISSUE TITLE
Undelete Files from Recycler on Encrypted Server Error

### ISSUE THREAD

**Issue by OliverTempel** [owncloud/core#20890] opened 2015-12-02 10:41 UTC
### Steps to reproduce
1. Upload a file on a encrypted OC Server
2. Delete File
3. Go to recycler an undelete file
4. File is visible

### Expected behaviour
File can be downloaded and you see file content

### Actual behaviour
File Can be downloaded, filesize is "0"

### Server configuration
Debian Wheezy

**Web server: Apache 2.2

**Database: MySQL

**PHP version: 5.5.30

**ownCloud version: 8.0.8

**Updated from an older ownCloud or fresh install: Update

**List of activated apps:
 - activity
 - calendar
 - files
 - files_encryption
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - firstrunwizard

**The content of config/config.php:**
OCC Command results in error: InvalidArgumentException
$CONFIG = array (
  'instanceid' => 'ocf916c94a4e',
  'passwordsalt' => '3838a02a45d7db91080acb736112e9',
  'hashingCost' => 5,
  'trusted_domains' =>
  array (
    0 => 'oc.olivertempel.de',
  ),
  'datadirectory' => '/var/www/clients/client1/web80/web/data',
  'dbtype' => 'mysql',
  'version' => '8.0.8.0',
  'dbname' => 'c1_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'c1_oc',
  'dbpassword' => '',
  'installed' => true,
  'default_language' => 'de',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => false,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => true,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'cloudserver',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => ',
  'mail_smtpport' => '25',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'trashbin_retention_obligation' => 7,
  'trashbin_auto_expire' => true,
  'loglevel' => 3,
  'log_rotate_size' => 104857600,
  'theme' => '',
  'maintenance' => false,
  'preview_max_scale_factor' => 1,
  'custom_csp_policy' => '',
  'secret' => '',
);

**Are you using external storage, if yes which one:
No.

**Are you using encryption: yes

Are you using an external user-backend, if yes which one:
Windows OC Client

### Client configuration
Firefox / Chrom

**Operating system:
Windows 10 / Windows 8.1 / Windows 7

### Logs
[Wed Dec 02 00:55:09 2015] [error] [client xxx.xxx.xxx.xxx] File does not exist: /var/www/oc.olivertempel.de/web/_asterisk
[Wed Dec 02 08:31:05 2015] [warn] [client xxx.xxx.xxx.xxx] (104)Connection reset by peer: mod_fcgid: can't get data from http client
[Wed Dec 02 08:31:05 2015] [warn] [client xxx.xxx.xxx.xxx] (104)Connection reset by peer: mod_fcgid: can't get data from http client
[Wed Dec 02 08:36:06 2015] [warn] [client xxx.xxx.xxx.xxx] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Dec 02 09:37:28 2015] [error] [client xxx.xxx.xxx.xxx] File does not exist: /var/www/oc.olivertempel.de/web/favicon.ico
[Wed Dec 02 09:37:28 2015] [error] [client xxx.xxx.xxx.xxx] File does not exist: /var/www/oc.olivertempel.de/web/favicon.ico
[Wed Dec 02 09:39:12 2015] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: read data timeout in 600 seconds, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin
[Wed Dec 02 09:39:12 2015] [error] [client xxx.xxx.xxx.xxx] Premature end of script headers: index.php, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin
[Wed Dec 02 09:39:24 2015] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: read data timeout in 600 seconds, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793%2FSalzgitter%202015&view=trashbin
[Wed Dec 02 09:39:24 2015] [error] [client xxx.xxx.xxx.xxx] Premature end of script headers: index.php, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793%2FSalzgitter%202015&view=trashbin
[Wed Dec 02 09:43:47 2015] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: read data timeout in 600 seconds, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin
[Wed Dec 02 09:43:47 2015] [error] [client xxx.xxx.xxx.xxx] Premature end of script headers: index.php, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin
[Wed Dec 02 09:44:01 2015] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: read data timeout in 600 seconds, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793%2FSalzgitter%202015&view=trashbin
[Wed Dec 02 09:44:01 2015] [error] [client xxx.xxx.xxx.xxx] Premature end of script headers: index.php, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793%2FSalzgitter%202015&view=trashbin
[Wed Dec 02 09:44:40 2015] [error] [client 144.76.147.86] client denied by server configuration: /var/www/oc.olivertempel.de/web/data/htaccesstest.txt
[Wed Dec 02 09:44:40 2015] [error] [client 144.76.147.86] client denied by server configuration: /var/www/oc.olivertempel.de/web/data/htaccesstest.txt
[Wed Dec 02 09:47:22 2015] [warn] [client xxx.xxx.xxx.xxx] (70008)Partial results are valid but processing is incomplete: mod_fcgid: can't get data from http client
[Wed Dec 02 10:01:53 2015] [warn] [client xxx.xxx.xxx.xxx] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Dec 02 10:01:53 2015] [warn] [client xxx.xxx.xxx.xxx] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Dec 02 10:01:53 2015] [warn] [client xxx.xxx.xxx.xxx] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Dec 02 11:40:49 2015] [error] [client 144.76.147.86] client denied by server configuration: /var/www/oc.olivertempel.de/web/data/htaccesstest.txt
[Wed Dec 02 11:40:49 2015] [error] [client 144.76.147.86] client denied by server configuration: /var/www/oc.olivertempel.de/web/data/htaccesstest.txt

#### ownCloud log (data/owncloud.log)
Fatal: Webdav
 Exception: {"Message":"The destination node is not found","Code":0,"Trace":"#0 \/var\/www\/clients\/client1\/web80\/web\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(991): Sabre\\DAV\\Server->getCopyAndMoveInfo()\n#1 [internal function]: Sabre\\DAV\\Server->httpMove('M\\xC3\\xBCtterzentrum ...')\n#2 \/var\/www\/clients\/client1\/web80\/web\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'M\\xC3\\xBCtterzentrum ...')\n#3 \/var\/www\/clients\/client1\/web80\/web\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('MOVE', 'M\\xC3\\xBCtterzentrum ...')\n#4 \/var\/www\/clients\/client1\/web80\/web\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/clients\/client1\/web80\/web\/remote.php(54): require_once('\/var\/www\/client...')\n#6 {main}","File":"\/var\/www\/clients\/client1\/web80\/web\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php","Line":1330}

**Comment by MorrisJobke** [comment] 2015-12-02 12:03
> The destination node is not found

This line in the logs looks fishy. I can't reproduce this with stable8 branch. What is the file size of that file? Is it pretty huge? Does this also happen to small (a few hundred KB) files? 

All the logs indicate that some request timed out during execution and got killed what could be the cause of this.

**Comment by MorrisJobke** [comment] 2015-12-02 12:08
As an alternative: Can you try to upgrade to 8.1 or even 8.2. In 8.2 we introduced additional locking which prevents concurrent file access on the server side that also could be a cause for such an issue. 

cc @schiesbn for additional input here.

Generally speaking: I would love to see if this still is a problem on a 8.2 instance or not.

**Comment by OliverTempel** [comment] 2015-12-02 13:08
All Files smaller then 10MB, most files are small like 300-500kb
PHP-Error Log produces this error in fcgi mode when an error in php occures

Cant make an update, the last time i tried i had to recover from backup cause, to much files in cloud. (200GB) during upgrade encryption brakes.

**Comment by blizzz** [comment] 2016-03-01 15:30
>  [Wed Dec 02 09:43:47 2015] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: read data timeout in 600 seconds, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin
[Wed Dec 02 09:43:47 2015] [error] [client xxx.xxx.xxx.xxx] Premature end of script headers: index.php, referer: https://oc.olivertempel.de/index.php/apps/files/?dir=%2FBV-Treffen.d1448452793&view=trashbin

You should increase the execution time limit. Closing as config issue, please reopen if still valid after adjusting your fcgid configuration.

**Closed by blizzz** 2016-03-01 15:30 UTC
Labels: app:files_encryption, needs info
