### ISSUE TITLE
public cannot use `If:` header to perform operations on self-locked items

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34341] opened 2019-01-31 10:13 UTC
### Steps to reproduce
1. create a public link of a folder with a file and give write permissions
2. as public lock the file
3. as public try to overwrite the file using the `If: ` header and giving the own opaquelocktoken

### Expected behaviour
file can be overwritten

### Actual behaviour
HTTP status code 423
file cannot be changed

#### ownCloud log (data/owncloud.log)
```
PUT","url":"\/owncloud-core\/public.php\/webdav\/parent.txt","message":"Exception: HTTP\/1.1 423 Locked: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Locked\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\Locks\\\\Plugin->validateTokens(Object(Sabre\\\\HTTP\\\\Request), Array)\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1448): Sabre\\\\DAV\\\\Server->emit('validateTokens', Array)\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(458): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(309): Sabre\\\\DAV\\\\Server->start()\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(103): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/public.php(85): require_once('\\\/home\\\/artur\\\/www...')\\n#7 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Locks\\\/Plugin.php\",\"Line\":518}"}

```

**Comment by ownclouders** [comment] 2019-01-31 10:39
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/33847 (Persistent lock: cannot unshare from self), https://github.com/owncloud/core/issues/34302 (public cannot unlock locks set by the public), https://github.com/owncloud/core/issues/4511 (PUT: Support optimistic locking using E-Tag in the If-Match header), https://github.com/owncloud/core/issues/29554 (overwriting a file with a folder and a folder with a file needs better error reporting), and https://github.com/owncloud/core/issues/33479 (moving files in public folder is not possible).

**Comment by PVince81** [comment] 2019-01-31 13:58
keeping for known issue: when accessing public webdav endpoint, public user can lock resources but cannot access said resources with the lock token.

I wonder if we should just forbid locking from public then until this is fixed...

@pmaier1

**Comment by PVince81** [comment] 2019-01-31 14:06
duplicate of https://github.com/owncloud/core/issues/34304

**Closed by PVince81** 2019-01-31 14:06 UTC
Labels: bug, feature:persistent-locking, p3-medium
