### ISSUE TITLE
occ dav:sync-birthday-calendar fails for old people (tries to insert negative timestamps)

### ISSUE THREAD

**Issue by startaq** [owncloud/core#23232] opened 2016-03-14 15:25 UTC
### Steps to reproduce
1. occ dav:sync-birthday-calendar $USER
2.
3.

### Expected behaviour
Sync birthday calendars.

### Actual behaviour
SQL Error: "SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'firstoccurence' at row 1"

The birthday is 1952-08-07 and it tries to insert the value "-549158400".

### Server configuration
**Operating system**: Debian Jessie

**Web server:** NGINX 1.9.9

**Database:** MySQL 5.7.11

**PHP version:** 7.0.0

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Update from 8.3.3

**Where did you install ownCloud from:** Owncloud website, archive file

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "61f681c8dbb4d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/share\/nginx\/html\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "mysql",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "apps_paths": [
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "appcodechecker": false,
        "updatechecker": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 1,
        "log_rotate_size": 104857600,
        "trusted_domains": [
            "oc.x.info"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "postfix",
        "mail_from_address": "webmaster",
        "mail_domain": "x.info",
        "mail_smtpauth": false,
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "appframework": {
            "enabled": "no",
            "installed_version": "0.102",
            "ocsid": "158433",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "12"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.0",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.0.0.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "queued_tasks",
            "backgroundjobs_task": "",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "yes",
            "global_cache_gc_lastrun": "1457689802",
            "installedat": "1375111065.5267",
            "lastcron": "1457968208",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1457967663",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "umgmt_show_last_login": "true"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "yes",
            "installed_version": "0.12.0",
            "ocsid": "168711",
            "types": ""
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "masterKeyId": "master_db8490ac",
            "publicShareKeyId": "pubShare_b7d63d53",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "recovery_b53a24d0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "1060",
            "backgroundwatcher_previous_folder": "2564",
            "cronjob_scan_files": "500",
            "default_quota": "30 GB",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_antivirus": {
            "enabled": "no",
            "installed_version": "0.4",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3"
        },
        "news": {
            "enabled": "no",
            "installed_version": "1.202",
            "ocsid": "158434",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "superlog": {
            "enabled": "no",
            "installed_version": "0.5.15",
            "superlog_lifetime": "21",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "user_photo": {
            "enabled": "no",
            "installed_version": "0.5",
            "ocsid": "154679",
            "types": ""
        },
        "157439": {
            "enabled": "no"
        },
        "158433": {
            "enabled": "no"
        },
        "158434": {
            "enabled": "no"
        }
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45

**Operating system:** Linux

#### Web server error log
```
Nothing here.
```

#### ownCloud log (data/owncloud.log)
```
Nothing here.
```

#### Browser log
```
Nothing here.
```

**Comment by LukasReschke** [comment] 2016-03-14 15:31
Dupe of https://github.com/owncloud/core/issues/23004. Fix should also be linked there :)

**Closed by LukasReschke** 2016-03-14 15:31 UTC
