### ISSUE TITLE
[6.0.5] Sync large file to SFTP external storage file not complete

### ISSUE THREAD

**Issue by ser72** [owncloud/core#11432] opened 2014-10-06 12:45 UTC
**Expected Behavior**
File to be reassembled and be proper size

**Actual Behavior** 
File is reassembled and improper size

**Steps**
Create large file (11+ gig)
Configure SFTP external storage
Place large file in SFTP external storage folder on client
Watch client sync to server

All chunks are sent to the files/<user>/cache folder
File is placed on oC server in /tmp folder:

```
root@ubuntu:/var/www/owncloud605/data# ls -al /tmp
total 15668204
drwxrwxrwt  6 root     root            4096 Oct  6 08:27 .
drwxr-xr-x 24 root     root            4096 Aug 21 14:10 ..
-rw-r--r--  1 www-data www-data 16044208328 Oct  6 08:15 5667bc43f249d3944c97c6796e881781.part
```

After that, file is moved to SFTP server as .part file.
Once file hits 4GB, the size of the file stops increasing, however, the mtime continues to change:

```
root@ubuntu14:/home/ser72# ls -al
total 4194336
drwxr-xr-x 3 ser72 ser72       4096 Oct  6 07:49 .
drwxr-xr-x 3 root  root        4096 Sep 29 13:42 ..
-rw-rw-r-- 1 ser72 ser72 4294967296 Oct  6 08:22 15gig.ocTransferId747568740.part
```

```
root@ubuntu14:/home/ser72# ls -al
total 4194336
drwxr-xr-x 3 ser72 ser72       4096 Oct  6 07:49 .
drwxr-xr-x 3 root  root        4096 Sep 29 13:42 ..
-rw-rw-r-- 1 ser72 ser72 4294967296 Oct  6 08:24 15gig.ocTransferId747568740.part
```

```
root@ubuntu14:/home/ser72# ls -al
total 4194336
drwxr-xr-x 3 ser72 ser72       4096 Oct  6 07:49 .
drwxr-xr-x 3 root  root        4096 Sep 29 13:42 ..
-rw-rw-r-- 1 ser72 ser72 4294967296 Oct  6 08:29 15gig.ocTransferId747568740.part
```

Notice the mtime is 8:22, 8:24, then 8:29 but the file size remains 4GB

The file eventually gets totally reassembled and the .part is removed and the file is still 4GB.  Should be 11GB

**Notes**
Testing the file and Linux server, I did an FTP from the PC to the Linux server directly to verify the file is in fact 11GB:

```
root@ubuntu14:/home/ser72# ls -al /root
total 11718796
drwx------  4 root root        4096 Oct  3 14:38 .
drwxr-xr-x 22 root root        4096 Sep 29 14:16 ..
-rw-r--r--  1 root root 12000000000 Oct  3 11:36 15gig
```

Notice file size

```
root@ubuntu14:/home/ser72# ls -al
total 4194336
drwxr-xr-x 3 ser72 ser72       4096 Oct  6 08:38 .
drwxr-xr-x 3 root  root        4096 Sep 29 13:42 ..
-rw-rw-r-- 1 ser72 ser72 4294967296 Oct  6 08:38 15gig
```

![capture](https://cloud.githubusercontent.com/assets/5174383/4525673/8de68b62-4d56-11e4-9a99-83fdb977095e.PNG)

**Logs**
```
root@ubuntu:/var/www/owncloud605/data# more owncloud.log
{"reqId":"5432771d78166","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T11:03:57+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"543277328a8ab","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T11:04:18+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"5432773cdf9a8","app":"admin_audit","message":"User ser72 attempted to log into ownCloud from IP address: 192.168.1.123","level":1,"time":"2014-10-06T11:04:28+00:00","method":"PROPFIN
D","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"5432773cdf9a8","app":"admin_audit","message":"User ser72 logged into ownCloud from IP address: 192.168.1.123","level":1,"time":"2014-10-06T11:04:28+00:00","method":"PROPFIND","url":"
\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"54327dca5bc00","app":"PHP","message":"Undefined index: mountpoint at \/var\/www\/owncloud605\/apps\/files_external\/templates\/settings.php#20","level":3,"time":"2014-10-06T11:32:26+
00:00","method":"GET","url":"\/owncloud605\/index.php\/settings\/admin"}
{"reqId":"54327dca5bc00","app":"PHP","message":"Undefined index: mountpoint at \/var\/www\/owncloud605\/apps\/files_external\/templates\/settings.php#27","level":3,"time":"2014-10-06T11:32:26+
00:00","method":"GET","url":"\/owncloud605\/index.php\/settings\/admin"}
{"reqId":"54327dca5bc00","app":"PHP","message":"Undefined index: mountpoint at \/var\/www\/owncloud605\/apps\/files_external\/templates\/settings.php#29","level":3,"time":"2014-10-06T11:32:26+
00:00","method":"GET","url":"\/owncloud605\/index.php\/settings\/admin"}
{"reqId":"54327dca5bc00","app":"PHP","message":"Undefined index: mountpoint at \/var\/www\/owncloud605\/apps\/files_external\/templates\/settings.php#111","level":3,"time":"2014-10-06T11:32:26
+00:00","method":"GET","url":"\/owncloud605\/index.php\/settings\/admin"}
{"reqId":"54327dfe7aa0d","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T11:33:18+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"54327e0192f8d","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T11:33:21+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"543281d9e3998","app":"admin_audit","message":"Create \"\/ser72\/files\/SFTP\/15gig.ocTransferId747568740.part\" by user ser72, owner: ser72","level":1,"time":"2014-10-06T11:49:45+00:
00","method":"PUT","url":"\/owncloud605\/remote.php\/webdav\/SFTP\/15gig-chunking-747568740-1145-1143"}
{"reqId":"543281d9e3998","app":"admin_audit","message":"Write \"\/ser72\/files\/SFTP\/15gig.ocTransferId747568740.part\" by user ser72, owner: ser72","level":1,"time":"2014-10-06T11:49:46+00:0
0","method":"PUT","url":"\/owncloud605\/remote.php\/webdav\/SFTP\/15gig-chunking-747568740-1145-1143"}
{"reqId":"543286fedf2dc","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T12:11:42+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"543281d9e3998","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '15gig' is not readable !!!","level":0,"time":"2014-10-06T12:15:26+00:00","method":"PUT","url":"\/owncloud605\/re
mote.php\/webdav\/SFTP\/15gig-chunking-747568740-1145-1143"}
{"reqId":"5432891907c89","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T12:20:41+00:0
0","method":"POST","url":"\/owncloud605\/index.php\/heartbeat"}
{"reqId":"543289ab93739","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T12:23:07+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"54328b95cd08c","app":"PHP","message":"Comments starting with '#' are deprecated in \/etc\/php5\/apache2\/php.ini on line 1787 at Unknown#0","level":3,"time":"2014-10-06T12:31:17+00:0
0","method":"PROPFIND","url":"\/owncloud605\/remote.php\/webdav\/"}
{"reqId":"543281d9e3998","app":"admin_audit","message":"Write \"\/ser72\/files\/SFTP\/15gig\" by user ser72, owner: ser72","level":1,"time":"2014-10-06T12:38:17+00:00","method":"PUT","url":"\/owncloud605\/remote.php\/webdav\/SFTP\/15gig-chunking-747568740-1145-1143"}
```

Client logs on  S3   support/github-issues/core/11432

**Environment**
Ubuntu 12.04
PHP 5.4.33

SFTP server on Ubuntu 14.0.4

**Comment by DeepDiver1975** [comment] 2015-01-07 12:56
@cdamken @jnfrmarks what's the status on testing/reproducing this issue? THX

**Comment by DeepDiver1975** [comment] 2015-01-07 12:57
removing OC8 milestone - there are no actions required for OC8

**Comment by jnfrmarks** [comment] 2015-01-07 14:07
@DeepDiver1975 

I haven't looked at this since my last comment above.

**Comment by gig13** [comment] 2015-02-20 13:25
@bantu 
Still seeing this issue
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F11432

**Comment by bantu** [comment] 2015-02-20 14:48
@gig13 "owncloud605" indicated this is ownCloud 6. For that see https://github.com/owncloud/core/issues/11432#issuecomment-59217651 and following.

**Comment by gig13** [comment] 2015-02-20 14:50
@bantu 
Correct the log still shows OC6-- I will recheck we were testing an upgrade to OC7

**Comment by bantu** [comment] 2015-02-20 14:53
@DeepDiver1975 This ticket is against oC6 and the problem at hand is defined as a will not fix as per https://github.com/owncloud/core/issues/11432#issuecomment-59217651 and following. Hence I am closing this.

@gig13 Feel free to create a new ticket against oC7 or 8.

**Closed by bantu** 2015-02-20 14:53 UTC
Labels: app:files_external, blue-ticket, bug

**Comment by gig13** [comment] 2015-02-20 15:29
@DeepDiver1975 @bantu 
Correction from above, the log is for OC7 NOT OC6 -- I will create a new case for OC7.0.4
