### ISSUE TITLE
Error on update of antivirus 0.15

### ISSUE THREAD

**Issue by mazzofab** [owncloud/core#34780] opened 2019-03-15 20:02 UTC
### Steps to reproduce
1. Update antivirus from admin when notification appears

### Expected behaviour
Should update and work as normal

### Actual behaviour
owncloud ceases working and cannot login anymore.  The logs in the index page show as follows:
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq... ^

### Server configuration
**Operating system**: Debian 9.8

**Web server:** nginx

**Database:** postgresql

**PHP version:** 7.0

**ownCloud version:** 10.0.10

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** source

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc4s1rantg96",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fsm.co.tz"
        ],
        "datadirectory": "\/opt\/owncloud_data",
        "overwrite.cli.url": "https:\/\/cloud.fsm.co.tz",
        "dbtype": "pgsql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:** Antivirus

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.14.0
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.4.0
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox

**Comment by ho4ho** [comment] 2019-03-15 20:34
Duplicate by https://github.com/owncloud/core/issues/31320

ownCloud doesen't like PostgreSQL 10: https://github.com/owncloud/core/issues/34026

**Comment by VicDeo** [comment] 2019-06-21 21:00
@mazzofab 
https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html
>PostgreSQL 9 (versions 10 and above are not yet supported)

due to Doctrine/dbal dependencies support of postgre 10 means dropping php 7.0. This is planned by the end of this year.

Closing as a duplicate of https://github.com/owncloud/core/issues/34026

**Closed by VicDeo** 2019-06-21 21:00 UTC
