### ISSUE TITLE
Upgrade failed from 8.0.2 to 8.0.3

### ISSUE THREAD

**Issue by MLWALK3R** [owncloud/core#16089] opened 2015-05-05 23:49 UTC
### Steps to reproduce
1.Run upgrade

### Expected behaviour
Upgrades

### Actual behaviour
Fails

### Server configuration
**Operating system**:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

**Web server:**
nginx version: nginx/1.8.0

**Database:**
mysql  Ver 15.1 Distrib 10.1.4-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)

**ownCloud version:** (see ownCloud admin page)
8.0.2
**Updated from an older ownCloud or fresh install:**
.2 > .3
**List of activated apps:**

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using encryption:** yes/no 
no

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
 sudo -u root php occ upgrade
An unhandled exception has been thrown:
exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOSt
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#4 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#5 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#7 /var/www/owncloud/lib/base.php(1026): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to bnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#1 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#3 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#4 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#5 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(1026): OC::init()
#7 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#8 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#9 {main}

Next exception 'Doctrine\DBAL\Exception\DriverException' with message 'An exception occurred while executing 'DELETE FROM oc_appconfig WHERE appid = ? A

SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table s READ COMMITTED or READ UNCOMMITTED.' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exc
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(996): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctri
#2 /var/www/owncloud/lib/private/db/connection.php(132): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM oc_...', Array, Array)
#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(595): OC\DB\Connection->executeUpdate('DELETE FROM *PR...', Array, Array)
#4 /var/www/owncloud/lib/private/appconfig.php(220): Doctrine\DBAL\Connection->delete('*PREFIX*appconf...', Array)
#5 /var/www/owncloud/lib/private/allconfig.php(152): OC\AppConfig->deleteKey('core', 'cronErrors')
#6 /var/www/owncloud/lib/base.php(579): OC\AllConfig->deleteAppValue('core', 'cronErrors')
#7 /var/www/owncloud/lib/base.php(1026): OC::init()
#8 /var/www/owncloud/console.php(12): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.



d properly, aborting.","level":1,"time":"2015-05-05T20:15:01+00:00","method":"--","url":"--"}
{"reqId":"916dae479c7a7bb06d3d773b22330295","remoteAddr":"","app":"user_ldap","message":"Run background job \"updateGroups\"","level":0,"time":"2015-05-05T21:15:02+00:00","method":"--","url":"--"}
{"reqId":"916dae479c7a7bb06d3d773b22330295","remoteAddr":"","app":"user_ldap","message":"bgJ \"updateGroups\" \u2013 groups do not seem to be configured properly, aborting.","level":1,"time":"2015-05-05T21:15:02+00:00","method":"--","url":"--"}
{"reqId":"01d1ed93bc64e98a29753cc2bb06b107","remoteAddr":"","app":"user_ldap","message":"Run background job \"updateGroups\"","level":0,"time":"2015-05-05T22:15:03+00:00","method":"--","url":"--"}
{"reqId":"01d1ed93bc64e98a29753cc2bb06b107","remoteAddr":"","app":"user_ldap","message":"bgJ \"updateGroups\" \u2013 groups do not seem to be configured properly, aborting.","level":1,"time":"2015-05-05T22:15:03+00:00","method":"--","url":"--"}
{"reqId":"482d1440f74e415bb8c13cef44c90846","remoteAddr":"","app":"user_ldap","message":"Run background job \"updateGroups\"","level":0,"time":"2015-05-05T23:30:02+00:00","method":"--","url":"--"}
{"reqId":"482d1440f74e415bb8c13cef44c90846","remoteAddr":"","app":"user_ldap","message":"bgJ \"updateGroups\" \u2013 groups do not seem to be configured properly, aborting.","level":1,"time":"2015-05-05T23:30:02+00:00","method":"--","url":"--"}
{"reqId":"d45449fb220909d15ada7ea7d3457a57","remoteAddr":"141.101.99.5","app":"core","message":"starting upgrade from 8.0.2.0 to 8.0.3.4","level":0,"time":"2015-05-05T23:40:46+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=QjTMnhGlLwG52qAVrTSGdlF.\/\/mgUM"}
{"reqId":"c94de5adf69cce6530be92289517bf1a","remoteAddr":"","app":"cron","message":"An exception occurred while executing 'DELETE FROM oc_appconfig WHERE appid = ? AND configkey = ?' with params [\"core\", \"cronErrors\"]:\n\nSQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.","level":4,"time":"2015-05-05T23:45:01+00:00","method":"--","url":"--"}

```

**Comment by RealRancor** [comment] 2015-05-06 03:50
Dup of https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16008

**Comment by nickvergessen** [comment] 2015-05-06 14:03
Duplicate of https://github.com/owncloud/core/issues/7769
See the documentation change: https://github.com/owncloud/documentation/pull/1109

**Closed by nickvergessen** 2015-05-06 14:03 UTC

**Comment by RealRancor** [comment] 2015-05-07 04:10
Its a dup of https://github.com/owncloud/core/issues/16008
