### ISSUE TITLE
"Upload Cancel" blinking If you cancel upload file

### ISSUE THREAD

**Issue by zVerdomorez** [owncloud/core#19353] opened 2015-09-25 03:57 UTC
If have upload 100 files and you cancel upload at 50th file. Warning message will blinking 50 times 
![upload](https://cloud.githubusercontent.com/assets/14266988/10092779/3a57ac8a-6374-11e5-9280-bee1fffb4214.jpg)

**Comment by PVince81** [comment] 2015-09-25 09:11
When raising issues, please first if there is a matching one. A search with the keywords "upload blink" pointed to https://github.com/owncloud/core/issues/8433

Also in general you should use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Closing as duplicate of https://github.com/owncloud/core/issues/8433

**Closed by PVince81** 2015-09-25 09:11 UTC
