### ISSUE TITLE
[8.2] Call to a member function processAttributes() on a non object at apps\user_ldap\lib\access.php#698

### ISSUE THREAD

**Issue by musaa32** [owncloud/core#21256] opened 2015-12-17 12:02 UTC
After the upgrate, I couldn't see my files in the files app, so i started the filescan in the console.
this is the error I get:

PHP Fatal error:  Call to a member function processAttributes() on a non-object in /owncloud/apps/user_ldap/lib/access.php on line 698

Is this similar to https://github.com/owncloud/core/issues/20090?
I have upgraded from 8.0.3 to 8.2. 
![owncloud.log](http://i.xomf.com/fwmlv.png)

# Server configuration
Operating system: Linux
Web server: nginx
Database: mariadb-10.0.22
PHP version: PHP 5.6.14-pl0-gentoo
ownCloud version: 8.2.0.12
Updated from an older ownCloud or fresh install: upgrade from 8.0.3
List of activated apps:
standard apps
user_ldap !

**Comment by PVince81** [comment] 2015-12-21 10:01
Duplicate of https://github.com/owncloud/core/issues/20090.

Please try again with 8.2.1 where this was fixed already https://github.com/owncloud/core/pull/20245

**Comment by musaa32** [comment] 2015-12-21 10:19
it's similar but not the same error.
Anyway seems to work in 8.2.1

**Comment by PVince81** [comment] 2015-12-21 10:21
Yeah, there might be multiple code paths leading to the same error.
Glad to hear the fix worked for you.

CC @blizzz

**Comment by musaa32** [comment] 2015-12-21 10:35
but I got an error in the admin page in 8.2.1 (504 Gateway Timeout with nginx) and fixet it with this change in the config file:
```
    check_for_working_webdav=false
```
I can't see anything in the log files too? is there a fix for this issue?

**Comment by PVince81** [comment] 2015-12-21 10:42
@musaa32 different issue => please raise a separate ticket

**Comment by PVince81** [comment] 2015-12-21 10:43
you might want to search the forums first as it might be a known setup issue with nginx, see https://owncloud.org/support/

**Comment by musaa32** [comment] 2015-12-21 13:49
sorry but I still get the error in the console if I want to rescan my files with
```
php console.php files:scan
```
PHP Fatal error:  Call to a member function processAttributes() on a non-object in /owncloud/apps/user_ldap/lib/access.php on line 717

**Comment by PVince81** [comment] 2015-12-21 13:55
Okay, I'll reopen it then.
Is there more to the error message like a stack trace ?

CC @blizzz

**Comment by blizzz** [comment] 2015-12-21 14:01
@musaa32 this is fixed with https://github.com/owncloud/core/pull/20804 but needs to be tested and reviewed (→ you are invited :) )

**Comment by musaa32** [comment] 2015-12-21 14:01
No only the Exception below.
owncloud.log
```
{"reqId":"yw08A5I+voRLzCb6Iif7","remoteAddr":"","app":"PHP","message":"Call to a member function processAttributes() on a non-object at \/owncloud\/apps\/user_ldap\/lib\/access.php#717","level":3,"time":"December 21, 2015 14:45:41"}
```

**Comment by musaa32** [comment] 2015-12-21 14:09
@blizzz 

https://github.com/owncloud/core/commit/9487cb95f385f249a6aaa1912f425c002b780a83

I guess I only need the changes in apps/user_ldap/user_ldap.php and apps/user_ldap/lib/access.php
right?

**Closed** 2016-02-18 13:43 UTC
Labels: app:user_ldap, bug
