### ISSUE TITLE
Feature Request: Add events counter api

### ISSUE THREAD

**Issue by Loki3000** [owncloud/core#23418] opened 2016-03-21 06:54 UTC
It's to be good to give applications the ability to return the number of unread events.
![menu](https://cloud.githubusercontent.com/assets/12333165/13912126/1fd4218e-ef53-11e5-9dff-e913c201459a.png)
Now I have to switch between apps during work or keep opened several apps at same time.

**Comment by MorrisJobke** [comment] 2016-03-21 08:51
cc @owncloud/designers is this actually wanted?

cc @nickvergessen @PVince81

**Comment by nickvergessen** [comment] 2016-03-21 09:54
Duplicate of https://github.com/owncloud/core/issues/15309

**Closed by nickvergessen** 2016-03-21 09:54 UTC
Labels: dev:ocp, enhancement, triage
