### ISSUE TITLE
Trashbin is not cleared with 100% full FS

### ISSUE THREAD

**Issue by EvgeniySpinov** [owncloud/core#27412] opened 2017-03-17 16:45 UTC
### Steps to reproduce
1. Create a OC folder mounted to a different disk, than /
2. Fill it with user data
3. Set trashbin_retention_obligation and versions_retention_obligation to 'auto, 180'
4. Make sure you have no empty space in OC folder
5. Add/update 1 file into the cloud.

### Expected behaviour
Trashbin should start to expire and then delete files due to low disk space condition as described in docs, i.e. till 50% of user quota will be reached. Probably important: I do not have user quota set.

### Actual behaviour
Trashbin have files 180 days old. More space is not freed. Only files that are older than 180 days are expired and deleted.

### Server configuration
**Operating system**:
CentOS 6
**Web server:**
Apache2 + PHP as Apache module
**Database:**
MySQL
**PHP version:**

PHP 5.4.42 (cli) (built: Jun 24 2015 13:41:14)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.5, Copyright (c) 1999-2015, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)

ownCloud 8.2.10 (production)

**Updated from an older ownCloud or fresh install:**

Live system with older updates since 8.0

**Where did you install ownCloud from:**

From official website zip.

**List of activated apps:**

```
Enabled:
  - activity: 2.1.4
  - announcementcenter: 1.0.3
  - bookmarks: 0.6.2
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - documents: 0.11.2
  - external: 1.2
  - files: 1.2.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - search_lucene: 0.7.0
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6
  - user_webdavauth: 1.1.0.2
Disabled:
  - calendarplus
  - encryption
  - files_antivirus
  - files_locking
  - files_w2g
  - mail
  - tasksplus
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocq65gr67ygm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*** ACTUAL DOMAIN ***"
        ],
        "datadirectory": "\/mnt\/500_GB\/SharedFolder",
        "overwrite.cli.url": "https:\/\/*** ACTUAL DOMAIN ***",
        "dbtype": "mysql",
        "version": "8.2.10.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_from_address": "me",
        "mail_smtpmode": "php",
        "mail_domain": "*** ACTUAL DOMAIN ***",
        "loglevel": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "*** ACTUAL DOMAIN ***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 180",
        "trashbin_auto_expire": true,
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ]
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

I'm using webdav.

### Client configuration
**Browser:**

Vivaldi 1.7.735.46 (Stable channel) (64-bit)

**Operating system:**

Windows 10.

#### Web server error log
```
No particular error in the log files.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Mark to expire *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html next version should be 1489432089 or smaller. (prevTimestamp: 1489518489; step: 86400","level":1,"time":"2017-03-17T16:15:05+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489518466","level":1,"time":"2017-03-17T16:15:06+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489518395","level":1,"time":"2017-03-17T16:15:07+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489518194","level":1,"time":"2017-03-17T16:15:08+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489518109","level":1,"time":"2017-03-17T16:15:09+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489518027","level":1,"time":"2017-03-17T16:15:10+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517929","level":1,"time":"2017-03-17T16:15:11+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517803","level":1,"time":"2017-03-17T16:15:12+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517482","level":1,"time":"2017-03-17T16:15:12+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517352","level":1,"time":"2017-03-17T16:15:14+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517234","level":1,"time":"2017-03-17T16:15:15+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517170","level":1,"time":"2017-03-17T16:15:16+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489517102","level":1,"time":"2017-03-17T16:15:16+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489516955","level":1,"time":"2017-03-17T16:15:17+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489516818","level":1,"time":"2017-03-17T16:15:18+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489516702","level":1,"time":"2017-03-17T16:15:19+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489516613","level":1,"time":"2017-03-17T16:15:20+00:00"}
{"reqId":"VWpKbFzzsvqLCuNHm\/nT","remoteAddr":"","app":"files_versions","message":"Expire: *** PATH TO LOCAL FOLDER HERE ***\/nowItemDetailed.html.v1489516447","level":1,"time":"2017-03-17T16:15:21+00:00"}
```

#### Browser log
```
Not applicable
```

The logs represented above when 1 file has been updated via ownCloud desktop client. Free disk space data:
```
/dev/sda1       73780888  21019212  49693516  30% /
tmpfs             963660         4    963656   1% /dev/shm
/dev/sdb1      488101616 487895292    205924 100% /mnt/500_GB
/dev/sdb1      488101616 487895292    205924 100% /var/ftp
```

Disk with OC folder is 100% occupied.

**Comment by PVince81** [comment] 2017-03-20 08:51
Is cron running properly ? Because that's what should do the expiration.

**Comment by EvgeniySpinov** [comment] 2017-03-20 09:09
Cron is running without issues ( no errors in logs and records in cron logs that it started and finished ), otherwise even 180 days old data won't be evicted, but it is expiring correctly and in time.

I also have proper values in jobs table, i.e. Trashbin and Version expire tasks. I remember some issues while migrating were highlighted that those tasks are not carried in DB. 

My feeling is that free space is checked against partition where OC is hosted, i.e. root partition in my case, which have plenty of space. 

Could this be the case?

**Comment by PVince81** [comment] 2017-03-20 09:16
Normally it will use the storage API's `free_space` method which itself calls PHP's `disk_free_space` using the path of the user, so it's unlikely.

> otherwise even 180 days old data won't be evicted, but it is expiring correctly and in time.

What do you mean by this ? Are there user accounts where trashbin expiration works correctly but not others ?

**Comment by EvgeniySpinov** [comment] 2017-03-20 09:22
> What do you mean by this ? Are there user accounts where trashbin expiration works correctly but not others ?

I've set trashbin_retention_obligation and versions_retention_obligation to 'auto, 180'. However, only second part of this configuration works. I.e. in trashbin I have seen deleted files not older than 180 days. And I see in logs, that OC expires and deletes files older than 180 days. Which proves that cron works.

My expectation is that "auto", as the first part, will start evicting files whenever there is low space condition ( like in my case ) every time I add or remove file in ownCloud. 

But somehow it doesn't happen and no activity in logs when I add/delete files via ownCloud desktop client.

**Comment by PVince81** [comment] 2017-03-20 09:29
Looking at https://github.com/owncloud/core/blob/v9.1.4/apps/files_trashbin/lib/Trashbin.php#L279 in the `move2trash` method, when a user deletes a file it will create a new one-shot background job to handle expiry. So if you have a user with a lot of trashed files, if that user deletes another file it will schedule that job which will take care of the cleanup during cron runs.

The trouble with this logic is that it doesn't take into account when space is being filled outside of the trashbin. Maybe `scheduleExpire` should be run for any file operation that adds new files into the user's home storage (upload, put_file_contents, move into storage).

**Comment by EvgeniySpinov** [comment] 2017-03-20 09:43
Just to dig it a bit deeper:

What about `Trashbin::resizeTrash()`? According to comment it should do expiry on adding files as well, but condition if `($freeSpace < 0)` is a bit hard to predict, and looks like in my case it is never fired.

Also if you look into `Tashbin:: calculateFreeSpace()`, it will contain 
`$quota = $userObject->getQuota();
		if ($quota === null || $quota === 'none') {
			$quota = Filesystem::free_space('/');
`

This what makes me to think, that free space is calculated on root FS, not the user folder. I do not have quota set per user, so I believe for me getQuota() will return null.

Is it how it should be?

**Comment by PVince81** [comment] 2017-03-20 09:50
> Filesystem::free_space('/');

What?!
This is clearly a bug. Great find.

This needs to be changed to take the user's home folder, something like `'/' . $userObject->getUID() . '/`.

**Comment by PVince81** [comment] 2017-03-20 09:51
WAIT, no.

**Comment by PVince81** [comment] 2017-03-20 09:53
The `Filesystem` class' filesystem calls should already operate on the user's home because its internal `$defaultInstance` is initialized with the user's home as root, so that's correct.

The bug is likely what I said: the expiry is only triggered when adding files to the trashbin but not to the user's home.

**Comment by EvgeniySpinov** [comment] 2017-03-20 10:11
If `Filesystem::free_space('/');` is correct, then we're back to question about function `Trashbin::resizeTrash()`, which states, that it is called on adding new files to OC. 

So seems like functionality is there, but somehow is not fired.

**Comment by EvgeniySpinov** [comment] 2017-03-20 10:31
I've also made a test just now: 
1. Created file via web interface in my local folder
2. Deleted it.

As per code it should expire files. Just after deleting file PHP process fired up with 100% cpu consumption and was doing something ( no errors in logs ). After that cron ran. No space was freed.

So probably issue is with `scheduleExpire()`?

**Comment by PVince81** [comment] 2017-03-20 10:35
Seems you're right, `resizeTrash` should be called after a file is written (upload) as there is a post_write_hook handler here: https://github.com/owncloud/core/blob/v9.1.4/apps/files_trashbin/lib/Hooks.php#L50

You could try adding some log statements like:
```
\OC::$server->getLogger()->debug('### DEBUG free space' . $freeSpace, array('app' => 'DEBUG'));
```

Add in various places in the trashbin code to see if they're fired on your env.
I suggest to put one in `resizeTrash` and also one to check what `$freeSpace` is returned that is supposed to be `< 0`.

**Comment by EvgeniySpinov** [comment] 2017-03-20 10:51
Good point, will do a bit later and will write back with results.

**Comment by EvgeniySpinov** [comment] 2017-03-20 17:10
Ok, I did some debugging and figured that:
1. Whenever the file is add to OC folder resizeTrash() is called. Which is expected.
2. `self::calculateFreeSpace()` in that function returns amount in bytes free on partition if quota for user is not set, like in my case, which also makes sense. 
3. The check `$freespace < 0` can never be true when quota is not set.

Seems to me that block in `calculateFreeSpace()` where we say `if ($softQuota)` should be always calculated, not only when quota is set. In this case this function would return me negative value, which would be correct, since my free space is much less that trashbin size.

**Comment by EvgeniySpinov** [comment] 2017-03-20 17:18
And one more thing: `move2trash()` supposed to schedule expire. It does reach this point, but nothing happens. I mean files are not expired and space is not freed. No errors in logs.

I've traced it till call of `\OC::$server->getCommandBus()->push(new Expire($user));`. It reaches it.

**Comment by EvgeniySpinov** [comment] 2017-03-20 17:39
Ok, it figured that expiring of items also depends on `calculateFreeSpace()`. So only question regarding this condition `if ($softQuota)` remains. Commenting it out triggers cleanup and proper log messages:

`{"reqId":"+VAeKxdzFQfhBiFb+Hho","remoteAddr":"","app":"files_trashbin","message":"remove \"IMG_20161216_142959.jpg\" (5416322B) to meet the limit of trash bin size (50% of available quota)","level":1,"time":"2017-03-20T17:39:08+00:00"}`

**Comment by EvgeniySpinov** [comment] 2017-03-21 06:18
There is also definitely an issue in `deleteFiles()` and probably `deleteVersions()` in a way how quota meeting is calculated.

Issue is that free space and trashbin size is calculated before entering this function and then just deleted file size is added each time file is deleted until threshold is met. While the whole calculation should be made again.

Example: 
Let's say we have 200 bytes free, 150 bytes our trashbin size and we have 50% of quota ( BTW https://github.com/owncloud/core/blob/v9.1.4/apps/files_trashbin/lib/Trashbin.php#L698 have hardcoded 50% in log message, which is wrong ). In this case before entering function we will have:

`200 * 0.5 - 150 = -50`. Means we have -50 bytes free space, so we need to delete files.

We enter the function `deleteFiles()`. Let's say we delete the file of 10 bytes. Function will keep deleting files, while the value will be negative, i.e. it will delete 50 bytes of files. Which is wrong, cause free space is also acquired in deletion, which is not accounted.

When we delete 10 bytes, if space calculated properly we will have:
`(200 - 10)*0.5 - 140 = -45`

Calculated by `deleteFiles()`:
`200 * 0.5 - 140 = -40`.

**Comment by PVince81** [comment] 2017-03-21 07:51
Nice find. So it seems that when no quota is applied the trashbin never applies the 50% logic.

There might have been a reason for this a few years ago, see https://github.com/owncloud/core/issues/2936#issuecomment-16438489. So I'm not sure we can change it the way you proposed.

Maybe there's a middle ground to be found that covers both situations.

**Comment by EvgeniySpinov** [comment] 2017-03-21 16:51
Thanks for the reference, didn't find it myself. 

Implementation contains the same error, even though the code is different. It has the same condition regarding cleanup start and when quota is not set it cannot become negative, cause it always returns available free space in such case.

I do not understand the meaning of the flag softQuota and why logic is different for set and non-set quota users. It should be the same, but when quota is set - it should be accounted, when no quota is set - free space is quota.

BTW, thanks to that guy for deleting even distribution of space between users. This was a right thing. 

TBH, I'd refactor those functionality responsible for free space tracking and decision making to delete or to not delete file, cause the logic is scattered ( some of the functions calculate space themselves ) and it's very hard to understand what values you will deal with without compiling and debugging it in your head. Very time consuming.

I can do that in PR if you give a green light or a simpler solution comes to your mind.

**Comment by ownclouders** [comment] 2017-12-21 01:13
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by EvgeniySpinov** [comment] 2017-12-21 08:19
Doesn't look like there was any action on this one. I'm still running patched version.

**Comment by PVince81** [comment] 2017-12-21 08:58
@VicDeo can you have a look at the proposed patch ?

**Comment by VicDeo** [comment] 2017-12-21 17:22
@EvgeniySpinov could you submit your patch in PR with a reference to this issue?

**Comment by EvgeniySpinov** [comment] 2017-12-21 22:43
Done. I'm not sure that proposed changes in patch are correct way to resolve the issue, thus I didn't publish PR before. However the change allowed OC to operate properly. Also probably seeing the change will allow to understand how to fix it better.

**Comment by VicDeo** [comment] 2017-12-28 23:42
The whole expiration process has several design flaws
The description `automatically deletes anytime after that if space is needed` looks like  the space should be freed *before* upload depending on the space that will be potentially occupied by the uploaded file. 

How it is designed instead:
1. We scanning  FS within postWrite hook when upload is done
2. Uploaded file size is unknown and *not* taken into account at all
3. Even if the space is needed - we  push an expiration command via asyncCommandBus -  we just ask to free the space on the next cron execution.

But let's move it aside and get back to the issue
there is a requirement of 50% of available quota to be free.
According to the constant description https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Trashbin.php#L50
it should also be applied to the disk free space. 

But it doesn't. This was done on purpose see
https://github.com/owncloud/core/commit/a3999036f720e73727dac07a337578f3e25f92aa#diff-0dc914768208fc24b2aa2f2a369bb684
https://github.com/owncloud/core/issues/2936

And this fix introduced a regression:
>  in case user has no quota he should hit exactly 0 bytes of free space for the expiration to be scheduled. 

@PVince81  May be we need just another constant for that case (e.g. 10% instead of 50%)?
I think https://github.com/owncloud/core/issues/2936 is a valid report -  there is no sense to delete files in trashbin for 1Tb storage unlit it hit 100Gb limit or so.

**Comment by PVince81** [comment] 2018-01-08 11:34
@VicDeo adding a setting for that 50% value makes sense, yes.

**Comment by VicDeo** [comment] 2018-01-09 15:47
@pvince81 How do think - should it be an internal config option buried in config.php or we need to add it into the admin settings?

**Comment by PVince81** [comment] 2018-01-09 17:47
@VicDeo config.php since the other settings are also there

**Comment by VicDeo** [comment] 2018-02-07 13:53
50% of free space will be used for users without a quota
With ability to adjust this value using `trashbin_purge_limit` config.php option

**Comment by VicDeo** [comment] 2018-02-15 18:11
Fix and backport are merged. Close.

**Closed by VicDeo** 2018-02-15 18:11 UTC
Labels: app:files_trashbin, bug
