### ISSUE TITLE
Support rich content in app descriptions

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15449] opened 2015-04-07 22:53 UTC
Currently, app descriptions look like one massive paragraph or several smaller ones. It's not very user friendly.
While we certainly don't need support for colours or crazy fonts, it would be appreciated to be able to structure text a bit or to emphasize/highlight words or sentences.

Maybe ~~BBCODE~~ Markdown should be supported?

I'm using this library in Gallery+
https://github.com/chjj/marked

**Comment by MorrisJobke** [comment] 2015-04-08 00:33
> BBCODE

No. I would say Markdown or nothing ... but not any crappy old markup language that nobody knows ;)

**Comment by oparoz** [comment] 2015-04-08 01:28
I agree :)

**Comment by PVince81** [comment] 2015-04-10 11:24
Duplicate of https://github.com/owncloud/core/issues/5322

**Closed by PVince81** 2015-04-10 11:24 UTC
Labels: enhancement
