### ISSUE TITLE
Update problem 8.2.2 to 9.0.0 

### ISSUE THREAD

**Issue by orefimi** [owncloud/core#23194] opened 2016-03-13 08:46 UTC
Hallo , 

after update from 8-2-2 to 9 , I got this message , please HELP!!!

I read that I should drop some database table but I don't know how and I have MariaDB. Can someone help? 

Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_notifications" ("notification_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "app" VARCHAR(32) NOT NULL, "user" VARCHAR(64) NOT NULL, "timestamp" INTEGER DEFAULT 0 NOT NULL, "object_type" VARCHAR(64) NOT NULL, "object_id" VARCHAR(64) NOT NULL, "subject" VARCHAR(64) NOT NULL, "subject_parameters" CLOB DEFAULT NULL, "message" VARCHAR(64) DEFAULT NULL, "message_parameters" CLOB DEFAULT NULL, "link" VARCHAR(4000) DEFAULT NULL, "actions" CLOB DEFAULT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_notifications" already exists

 
### Steps to reproduce
1.Update from 8.2.2 to 9
2.Maintenance mode off
3.go to owncloud mainpage with browser and start update

### Expected behaviour
Tell us what should happen

### Actual behaviour
it is always in maintenance mode

### Server configuration
**Operating system**: Ubuntu 14.04 

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here. --> not found
```

**List of activated apps:**
Enabled:
  - dav: true
  - federatedfilesharing: true
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
Disabled:
  - activity
  - bak_music
  - bookmarks
  - calendar
  - comments
  - contacts
  - delete_confirmation
  - direct_menu
  - documents
  - encryption
  - external
  - federation
  - files_embeddedvideo
  - files_excel_reader
  - files_videoplayer
  - gallery
  - galleryplus
  - notifications
  - ocDashboard
  - ownnote
  - ownnote_old
  - provisioning_api
  - search_lucene
  - systemtags
  - tal
  - tasks
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
  - vids
  - weather

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

{
    "system": {
        "instanceid": "oc2f3a7603a9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.14",
            "inviaggioversolaltro.ddns.net"
        ],
        "datadirectory": "\/mnt\/sdd1\/ocdata\/ata-Hitachi_HDT725040VLAT80_VF1300R3C0ADJA-part2",
        "overwrite.cli.url": "https:\/\/192.168.0.14",
        "dbtype": "sqlite3",
        "version": "8.2.2.2",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "mail_from_address": "orefice.michele",
        "mail_smtpmode": "php",
        "mail_domain": "yahoo.it",
        "forceSSLforSubdomains": true,
        "loglevel": 3,
        "ldapIgnoreNamingRules": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}



```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-03-13 09:24
Probably related or even a duplicate of: #22993 (Even if its another table).

**Comment by orefimi** [comment] 2016-03-13 09:27
How can I remove a table?????

Michele Orefice
+49 172 1825933

**Comment by RealRancor** [comment] 2016-03-13 09:34
@orefimi It should be easy to open your browser and search how to remove a table in mysql. Short hint with a 5 seconds search: https://dev.mysql.com/doc/refman/5.7/en/drop-table.html

**Closed** 2016-03-13 10:00 UTC

**Comment by orefimi** [comment] 2016-03-13 10:42
Sorry I don 't have too much experience : I have MariaDB not Mysql. Which are the differences? In MariaDB I listed the DB but owncloud DB is empty! 

 

    Il Domenica 13 Marzo 2016 10:34, RealRancor <notifications@github.com> ha scritto:
 

 @orefimi It should be easy to open your browser and search how to remove a table in mysql. Short hint with a 5 seconds search: https://dev.mysql.com/doc/refman/5.7/en/drop-table.html—

**Comment by orefimi** [comment] 2016-03-13 10:46
Here : 

MariaDB [mysql]> use owncloudDatabase changed
MariaDB [owncloud]> show tables
    -> ;
Empty set (0.00 sec)

MariaDB [owncloud]> 

 

    Il Domenica 13 Marzo 2016 11:42, Michele Orefice <orefice.michele@yahoo.it> ha scritto:
 

 Sorry I don 't have too much experience : I have MariaDB not Mysql. Which are the differences? In MariaDB I listed the DB but owncloud DB is empty! 

 

    Il Domenica 13 Marzo 2016 10:34, RealRancor <notifications@github.com> ha scritto:
 

 @orefimi It should be easy to open your browser and search how to remove a table in mysql. Short hint with a 5 seconds search: https://dev.mysql.com/doc/refman/5.7/en/drop-table.html—

**Comment by RealRancor** [comment] 2016-03-13 11:20
Please use the option listed at https://owncloud.org/support/ for such support questions and watch https://github.com/owncloud/core/issues/22993 if a solution is provided there.

**Comment by pipiche38** [comment] 2016-03-19 19:49
+1

**Comment by jdpipe** [comment] 2017-06-02 05:24
I have had the same problem every time I upgrade ownCloud for several recent upgrades. I always get something like the following. It appears to be something to do with a 'notifications' app that I am not aware that I use (but I haven't really investigated). In any case, the upgrade completes each time.

```
[...earlier bits removed...]
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: bookmarks
Disabled 3rd-party app: calendar
Disabled 3rd-party app: documents
notifications: An exception occurred while executing 'CREATE TABLE `oc_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_notifications' already exists
Drop old database tables
 Done                                            
 28/28 [============================] 100%       
Remove old (< 9.0) calendar/contact shares
 Done                                            
 4/4 [============================] 100%         
Fix permissions so avatars can be stored again
 Done                                            
 2/2 [============================] 100%         
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level
```
