### ISSUE TITLE
Scrolling in mobile view opens menu to easy

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#17821] opened 2015-07-22 17:30 UTC
If you want scroll just up and down the side menu is opened to easy. If u dont scroll in a perfect y-axis the side menu is opened. Would be nice to implement a bigger tolerance in x-axis

The "proplem" is in all apps, so I post it here in core.

**Comment by karlitschek** [comment] 2015-07-22 17:48
@jancborchardt What do you think?

**Comment by jancborchardt** [comment] 2015-07-22 17:50
Duplicate of #11193  – @Bullnados please search existing issues before opening new ones. :) See the fix attempt at https://github.com/owncloud/core/pull/17785 and please review that.

**Closed by jancborchardt** 2015-07-22 17:50 UTC
Labels: enhancement

**Comment by Bullnados** [comment] 2015-07-22 18:14
Oh sorry :( Will do that
