### ISSUE TITLE
Limit admin access based on different networks

### ISSUE THREAD

**Issue by joeplus** [owncloud/core#10574] opened 2014-08-21 13:14 UTC
Hello there,

since I wasn't able to find a similar enhancement request or issue I am proposing a new one. Consider the following situation:
There is an owncloud installation on a nas/server in a private LAN, connected to the internet over DDNS. Would it be possible to limit the admin users access to clients inside the LAN but not to clients on the internet. Therefore the admin accounts would not be exposed on the internet adding another level of security.

Let me know what you think!

Best regards
Jörg

**Comment by PVince81** [comment] 2017-12-14 16:23
closing as duplicate of https://github.com/owncloud/core/issues/5558

**Closed by PVince81** 2017-12-14 16:23 UTC
Labels: enhancement
