### ISSUE TITLE
Unexpected response 423 Locked in

### ISSUE THREAD

**Issue by tomptomp** [owncloud/core#33170] opened 2018-10-12 08:02 UTC
Hello,
our client sometimes can't download a file because of below error:

"Unexpected response (423 Locked). Please contact your web hosting service provider for assistance."

Our client uses webDav Cyberduck and on the server ownlcloud: the latest version 10.0.10

To temporarly solve the issue I go to database and truncate table oc_file_locks
This step helps but after some time problem returns and again I have to truncate table oc_file_locks

Please investigate the issue.

**Comment by ho4ho** [comment] 2018-10-14 07:03
Could be indeed a duplicate of https://github.com/owncloud/core/issues/24737 or https://github.com/owncloud/core/issues/20380 like @ownclouders has pointed out.

**Comment by PVince81** [comment] 2018-10-15 12:17
please use the issue template when reporting https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

most important is to make sure that cron is configured to run on the server and not ajax to make sure the locks get cleared properly

**Closed by PVince81** 2018-10-15 12:17 UTC
