### ISSUE TITLE
Owncloud Android App cant see Thumbnails in 8.1 - Server Log shows OC_Image->fixOrientation() Image is not a JPEG.

### ISSUE THREAD

**Issue by TheBR** [owncloud/core#17713] opened 2015-07-17 14:33 UTC
Steps to reproduce

- Browse photo directories in Owncloud official app 1.7.2 
  -  Only placeholder is shown 
  - Not Thumbnails - Works fine directly from Firefox etc

Expected behaviour

there is a thumbnail.

Actual behaviour

Placeholder icon is shown

Operating system:

Centos 7

Web server:
nginx

Database:
MySQL

PHP version:
5.5.9

ownCloud version: 8.1.0 (stable) 
```
Owncloud.log entries:-
{"reqId":"Qh+ePTDLQB4Gyh0s+K72","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-17T14:29:28+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0045.jpg"}
{"reqId":"Qh+ePTDLQB4Gyh0s+K72","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-17T14:29:28+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0045.jpg"}
{"reqId":"GgKiK8p6E6hA9YpjWMcT","remoteAddr":"192.168.0.1","app":"core","message":"Generating preview for \"files\/Public Pictures\/Arisaig\/IMG_0046.jpg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2015-07-17T14:29:28+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0046.jpg"}
{"reqId":"GgKiK8p6E6hA9YpjWMcT","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-17T14:29:28+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0046.jpg"}
{"reqId":"GgKiK8p6E6hA9YpjWMcT","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-17T14:29:28+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0046.jpg"}
```

**Comment by LukasReschke** [comment] 2015-07-17 18:23
Does `http://mycloud.org/index.php/apps/files/api/v1/thumbnail/50/50/Public%20Pictures/Arisaig/IMG_0046.jpg` return an image for you?

**Comment by TheBR** [comment] 2015-07-17 18:44
Initially no, i got "{"message":"File not found."}" 

So i logged into Owncloud normally using my desktop web browser and went into the directory Public Pictures/Arisaig.

It then generated thumbnails for all the pictures in the directory, including MG_0046.jpg.

I then put the link in above again in the desktop browser and the picture was shown this time, however if i then go to the Android app and go back to this directory then refresh, i still get placeholders for all the files AND the log still shows the error message:-

{"reqId":"iK2DtXXXA0zZEnJYWTYk","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-17T18:42:50+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0046.jpg"}

I suspect its because, as this is a relatively new install, i simply hadn't been in that directory to generate the thumbnail in the first place with anything other than the Android App.

**Comment by LukasReschke** [comment] 2015-07-17 18:46
If you request http://mycloud.org/index.php/apps/files/api/v1/thumbnail/384/384/Public%20Pictures/Arisaig/IMG_0046.jpg and then try it in the Android app does it work? – This looks like a very strange potential bug.

**Comment by TheBR** [comment] 2015-07-17 18:49
On Desktop - works fine,
On Android - No Thumbnail but i can download and view the picture.

**Comment by LukasReschke** [comment] 2015-07-17 18:51
And the error in the log is thrown for both accesses or only the one done by the android app?

**Comment by TheBR** [comment] 2015-07-17 19:03
Ok,
No error for Desktop, there is a log entry but its not an error, only access from the Android app throws the errors...

Desktop looks ok at both sizes:-

{"reqId":"KAEQy2zhPUgrk2vE8GfR","remoteAddr":"192.168.0.1","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/admin\/thumbnails\/4438\/384-384.png","level":0,"time":"2015-07-17T18:52:33+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0046.jpg"}

{"reqId":"84vyE+Xs7+IJw1+7p8lk","remoteAddr":"192.168.0.1","app":"files_locking","message":"INFO: Read lock requested for \/data\/admin\/thumbnails\/4438\/36-36.png","level":0,"time":"2015-07-17T18:53:53+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPublic+Pictures%2FArisaig%2FIMG_0046.jpg&c=c2b7c3b085b3a89b3ea90c4d64f0707c&x=36&y=36&forceIcon=0"}

Incidentally, I can now see the thumbnail ONLY for IMG_0046.jpg in that directory, probably because i downloaded it as mentioned in my previous post - all other pictures in the same directory still throw that error and still are ok on Desktop - e.g. Image 45

Desktop:-
{"reqId":"GWjj51zQI+exQpF9LbPq","remoteAddr":"192.168.0.1","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/admin\/thumbnails\/4437\/384-384.png","level":0,"time":"2015-07-17T19:01:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0045.jpg"}
{"reqId":"GWjj51zQI+exQpF9LbPq","remoteAddr":"192.168.0.1","app":"files_locking","message":"INFO: Incrementing lock type 1 count for \/data\/admin\/thumbnails\/4437\/384-384.png","level":0,"time":"2015-07-17T19:01:39+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0045.jpg"}

Android:-
{"reqId":"TL1iq0H5PsgXow+zw\/PU","remoteAddr":"192.168.0.1","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-07-17T19:03:03+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/384\/384\/Public%20Pictures\/Arisaig\/IMG_0045.jpg"}

Note the timestamps for verification.

**Comment by PVince81** [comment] 2015-07-27 16:12
I saw this in my server logs too.

**Comment by oparoz** [comment] 2015-08-01 11:26
The solution is in https://github.com/owncloud/core/issues/17855

**Comment by TheBR** [comment] 2015-08-01 14:26
Ok, this is a step forward as i can now see thumbnails in the Android app that have been created by browsing using the directories of pictures using the Web Interface BUT the android app itself will not initiate the auto generation of the thumbnails.

As a result, if i havent been into a directory in the Web Browser, it wont show a thumbnail.

Another observation i noticed when trying all this here which seems wasteful, say you have User1 and User2.

User 1 logs in (Web Browser) visits a directory and thumbnails are generated in directory /data/User1/thumbnails
User 2 logs in (Web Browser) visits the same directory and again thumbnails are generated but in directory /data/User2/thumbnails

Why not just have a directory /data/thumbnails?

**Comment by oparoz** [comment] 2015-08-01 15:31
@theBR - Did you refresh the folders in the Android app (pull down)? If that doesn't solve it, maybe @davitol knows something.
Regarding the other issues, they've all been documented already. A quick search should give you what's been discussed so far.

**Comment by TheBR** [comment] 2015-08-01 15:34
I did use the pull down to refresh. It didn't help unfortunately.

**Comment by utack** [comment] 2015-08-13 15:39
I have the problem that pre-generated thumbnails are displaying fine, but generation of new thumbnails needed for the mobile app is not triggered. Is this a seperate issue or does it go in here?

**Comment by oparoz** [comment] 2015-08-13 23:54
@utack - I would open a separate issue in the Android app repo, so that this can be investigated properly by that team.

**Comment by utack** [comment] 2015-09-29 12:17
Still having that issue. 
Should #17855 be in server 8.1.3?

**Comment by PVince81** [comment] 2015-10-09 14:29
@utack no, the fix https://github.com/owncloud/core/pull/18076 is only in 8.2RC1.

**Comment by tigermick** [comment] 2015-12-09 20:19
Hi,

I have the same problem with my owncloud 8.2.1.
All works fine on web interface but, no thumbnails in android app.
I have these errors :
Debug 	core 	OC_Image->fixOrientation() Orientation: -1 	2015-12-09T20:18:03+00:00
Debug 	core 	OC_Image->fixOrientation() Image is not a JPEG. 	2015-12-09T20:18:03+00:00
Debug 	core 	Generating preview for "files/DonneesReseaux/Photos/2015/Timeo/20150602_055039.jpeg" with "OC\Preview\JPEG" 

Any news about this problem please ?

**Comment by tigermick** [comment] 2015-12-13 08:22
I have this problem just with an external storage ...
Anyone have the same problem please ?

**Comment by PVince81** [comment] 2016-03-07 19:07
Possibly duplicate of https://github.com/owncloud/core/issues/21173

**Comment by enoch85** [comment] 2016-05-24 12:01
@TheBR Do you still see this behaviour?

**Comment by PVince81** [comment] 2016-08-15 17:37
Please try again with 8.2.6, the fix of the linked ticket made it in and is likely related.

**Closed by PVince81** 2016-08-15 17:37 UTC
Labels: app:files, bug
