### ISSUE TITLE
OC 8.2 With Openstack swift as primary storage does not remove deleted files from the container

### ISSUE THREAD

**Issue by hyperbaba** [owncloud/core#19971] opened 2015-10-22 09:50 UTC
Hi,
Just tried with latest 8.2 build. Clean install of the service.
Upon setting the swift container as a primary storage user can upload files to owncloud.
The file gets uploaded in the container as binary blob + two other objects are created in the container (did not look what they are)
When user deletes a file in owncloud, two additional corresponding objects in the container are deleted but the object containing the file itself does not.
No errors reported in owncloud.log

Vladimir

**Comment by MorrisJobke** [comment] 2015-10-22 09:51
What objectstore and which version do you use?

**Comment by MorrisJobke** [comment] 2015-10-22 09:51
cc @butonic @icewind1991

**Comment by MorrisJobke** [comment] 2015-10-22 09:53
> Just tried with latest 8.2 build.

This means https://download.owncloud.org/community/daily/owncloud-daily-stable8.2.tar.bz2 of today.

**Comment by hyperbaba** [comment] 2015-10-22 09:53
Objectstore is Openstack ceph which has radosgw in front emulating swift. Version of the cloud is icehouse. Version of the owncloud build is 8.2-daily from last night build

**Comment by hyperbaba** [comment] 2015-10-22 09:54
yes. Download and install is done one hour ago

**Comment by butonic** [comment] 2015-10-22 10:44
closing as duplicate of https://github.com/owncloud/core/issues/19125

**Closed by butonic** 2015-10-22 10:44 UTC
Labels: app:objectstore, bug
