### ISSUE TITLE
Search overlay broken on settings page

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#15297] opened 2015-03-29 08:58 UTC
and probably in a lot of other pages too

![bug](https://cloud.githubusercontent.com/assets/867445/6884802/7ef3db2a-d602-11e4-88cd-8960b93555a5.jpg)

**Comment by karlitschek** [comment] 2015-03-29 08:58
@butonic Can you have a look?

**Comment by nickvergessen** [comment] 2015-04-01 10:29
Could be related to #15142
Will investigate

**Comment by nickvergessen** [comment] 2015-04-01 13:19
Okay, it is somewhat related. Previously "No search result in other places" was displayed at the bottom of the page. But the question is, why does it display this message instead of some useful results at all, instead of presenting the search results from other places

**Comment by nickvergessen** [comment] 2015-04-01 13:22
@jancborchardt can you help here?

**Comment by jancborchardt** [comment] 2015-04-07 11:25
@nickvergessen can’t really help … @butonic needs to look at this.

**Comment by nickvergessen** [comment] 2015-04-07 11:27
@jancborchardt well in the mean time we could add some background to the search div so it doesnt look that odd, no?

**Comment by PVince81** [comment] 2015-04-22 07:46
@jancborchardt design-wise, what happened to the list of non-local results ?
In the past the results were showing in a dropdown under the search field and contained local and non-local results. Then the result list was moved to be embedded in the file list.

Does it mean that search is now restricted to the current view and should not show results from other apps like calendar/contacts ?

**Comment by LukasReschke** [comment] 2015-04-28 11:53
Activity app: https://github.com/owncloud/activity/issues/287

**Comment by jancborchardt** [comment] 2015-05-20 21:02
Duplicate of https://github.com/owncloud/core/issues/14544

**Closed by jancborchardt** 2015-05-20 21:02 UTC
Labels: app:search, bug, sev2-high
