### ISSUE TITLE
Shared with you screen does not show the files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13729] opened 2015-01-28 11:40 UTC
### Steps to reproduce

1. Go to files
2. Click share
3. Share file to an user of another server (e.g. USERNAME@domain.tld/owncloud )
4. Open owncloud in another server
5. Click in Shared with you screen

### Expected behaviour

Files shared should appear in this screen

### Actual behaviour

Shared with you screen does not show any file

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

![captura de pantalla 2015-01-28 a las 12 26 47](https://cloud.githubusercontent.com/assets/10596560/5936987/8a9e56ea-a6ea-11e4-9e9f-6d05ae6130ac.png)

![captura de pantalla 2015-01-28 a las 12 38 36](https://cloud.githubusercontent.com/assets/10596560/5936995/acf91b30-a6ea-11e4-82c6-6c459217f11c.png)

**Comment by davitol** [comment] 2015-01-28 11:56
Maybe #9098 issue is the same

**Comment by PVince81** [comment] 2015-01-28 12:03
Yes, duplicate of that one.
That part isn't implemented yet unfortunately.

**Comment by PVince81** [comment] 2015-01-28 12:03
Still, thanks for your bug reports :smile:

**Closed by PVince81** 2015-01-28 12:03 UTC
Labels: bug
