### ISSUE TITLE
Cross deletion of 'expiration date for user' shows the calendar using Safari as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36735] opened 2020-01-09 17:07 UTC
### Steps to reproduce
1. Create a file/folder 
2. Share the file/folder with a user
3. Set an expiration date for user (behavior included in PR https://github.com/owncloud/core/pull/36573)
4. Delete the date clicking on the cross

### Expected behaviour
Calendar should not be shown

### Actual behaviour
Calendar is shown even when finally the expiration date is deleted

![safaridate](https://user-images.githubusercontent.com/10596560/72088623-dc7b9e80-330a-11ea-888e-6523a2b08fb6.gif)

### Server configuration

**ownCloud version:**  10.4.0 RC1

### Browser version

Safari Version 13.0.4 (13608.4.9.1.4)

@felixheidecke @phil-davis JFYI

**Comment by phil-davis** [comment] 2020-01-10 03:34
On Chrome 79 and Firefox 72 on Ubuntu 18.04:
1) a) have an expiration date already entered
b) click the "x" to remove the expiration date
c) the calendar coses (good)
d) the whole share settings "panel" closes
e) (and the expiration date has been removed, as expected).

2) a) have no expiration date entered
b) click the "x" to remove the expiration date
c) nothing happens (correct expected behaviour)

Item 1 (d) is the weird thing - you have to then open the share settings again to enter a new expiration date. But that is not a really bad thing, just a bit unexpected.

But I can't reproduce the behaviour reported on Safari.

**Comment by davitol** [comment] 2020-01-10 07:34
> But I can't reproduce the behaviour reported on Safari.

Yes. I had also tried in Chrome and Firefox and everything went fine. That's why I set Safari label to the ticket

**Comment by micbar** [comment] 2020-01-28 11:16
@davitol I can confirm the behavior on Safari

And I found a new problem on both Firefox and Safari
![Expiration-Bug](https://user-images.githubusercontent.com/4378513/73259397-09afc400-41c8-11ea-868f-3ae14bbd5b50.gif)

**Comment by micbar** [comment] 2020-01-28 11:18
@felixheidecke @mrow4a @VicDeo 
Who could take care?
Thisd is blocking 10.4

**Comment by phil-davis** [comment] 2020-01-28 11:27
For me, the sharing date/permissions dropdown sometimes quickly opens and closes when I open the sharing panel of a folder. But other times it comes up open and stays that way, and other times it comes up closed and stays that way.

**Comment by phil-davis** [comment] 2020-01-28 11:30
Next clue - for a share with a user I see the "quick open and close" behaviour, and it ends up with the dropdown closed.

- for a share with a group, the dropdown is open

**Comment by mrow4a** [comment] 2020-01-28 11:32
@phil-davis @micbar is this still present after the expiry fix in https://github.com/owncloud/core/pull/36766 ?

**Comment by phil-davis** [comment] 2020-01-28 11:39
Yes, I am trying with current core master.

I did think that the hover thing happened to me twice, but I am struggling to reproduce it.

However there does seem to be a clear difference between user and group shares - so looking for differences in the JS of those might be a good place to start.

**Comment by phil-davis** [comment] 2020-01-28 11:44
For groups, it starts open. When I hover over the contents of the settings (expire date filed, permissions checkboxes) then nothing happens. When I hover over the actual group name (where it says e.g. "Finance (group)") then the settings auto-closes.

**Comment by VicDeo** [comment] 2020-01-28 11:48
@micbar For me after clocking share icon

Chrome
Share details view loaded with expanded share options. 
After loading options are hidden

Firefox
Share details view loaded with expanded share options. 
Options are hidden on hover

**Comment by davitol** [comment] 2020-01-28 11:56
> And I found a new problem on both Firefox and Safari

@micbar It looks like a regression produced by https://github.com/owncloud/core/pull/36766

It cannot reproduce the behaviour **The dropdown is closing when you are hovering over it** in oC 10.4.0. RC1 but it happens applying the PR https://github.com/owncloud/core/pull/36766

**Comment by VicDeo** [comment] 2020-01-28 12:14
I did a clean install from release-10.4.0 branch, https://github.com/owncloud/core/issues/36735#issuecomment-579208415 is not reproducible there.

**Comment by phil-davis** [comment] 2020-01-28 12:37
Note: release-10.4.0 branch is old and does not contain the latest code.
We are working from master, and some day when master is "ready" it will become "the new 10.4.0"

**Comment by mrow4a** [comment] 2020-01-28 12:49
@phil-davis make sure also to run in incognito mode. You might have a js cached in browser that causes problems. @micbar please add me in relevant reviews to fix it. I can help also investigating, will have a look later.

**Comment by VicDeo** [comment] 2020-01-28 12:57
Checked with a clean master install. Both FF and Chrome display share options  and then hide this block

**Comment by micbar** [comment] 2020-01-28 13:40
@VicDeo Can confirm this too on Safari.

Safar is in  addition showing the second bug if you click on the cross, the calendar pops up.

**Comment by phil-davis** [comment] 2020-01-28 14:29
With chrome 79 incognito.

For a share with a user: opening the sharing panel, the detailed expiration/permissions block opens and quickly closes.

For a share with a group: opening the sharing panel, the detailed expiration/permissions block opens and stays open. Hover over the group name, the  detailed expiration/permissions block closes itself.


![output](https://user-images.githubusercontent.com/1535615/73272431-76e44900-420a-11ea-8cca-641030de70b4.gif)

**Comment by mrow4a** [comment] 2020-01-28 22:44
Fixes for both problems in https://github.com/owncloud/core/pull/36847. Please make sure while testing to logout and open new tab to clear css/js caches.

**Comment by micbar** [comment] 2020-02-20 11:43
closing

**Closed by micbar** 2020-02-20 11:43 UTC
Labels: browser:firefox, browser:safari, bug, p2-high
