### ISSUE TITLE
php_max_upload_filesize = 2mb - owncloud 9 htaccess does not cater for php7

### ISSUE THREAD

**Issue by wararjey** [owncloud/core#23614] opened 2016-03-28 18:12 UTC
### Steps to reproduce
1. run owncloud on a debian unstable server with php7 (no php5) installed
2. see that max upload filesize is 2MB
3. cry

### Expected behaviour
max upload filesize should be 512mb by default, as when running owncloud with php5

### Actual behaviour
excerpt from htaccess:
`<IfModule mod_php5.c> `

This ifmodule clause gets processed for php5 only, but not for php7, none of the options in there get set, leaving max_upload_filesize at 2mb, which is the default in debian for the apache php7 config.ini

Obvious workaround is duplicating or renaming the IfModule section
`<IfModule mod_php7.c>`

### Server configuration
**Operating system**:
debian unstable
**Web server:**
apache
**Database:**
does not matter
**PHP version:**
7.x (pulled as dependency installing owncloud-deps-php7.0
**ownCloud version:** (see ownCloud admin page)
9.0.0-2.1 (from your debian repo)
**Updated from an older ownCloud or fresh install:**
does not matter
**Where did you install ownCloud from:**
debs for debian 8 from your repo
**Signing status (ownCloud 9.0 and above):**
whatever

Regards,

**Comment by RealRancor** [comment] 2016-03-28 18:59
Duplicate ofhttps://github.com/owncloud/core/issues/21146 Fix gets included in 9.0.1

**Closed** 2016-03-29 05:50 UTC

**Comment by Wikinaut** [comment] 2016-04-02 09:20
@wararjey are you running a self-compiled PHP 7 version ?

**Comment by wararjey** [comment] 2016-04-02 11:07
No, I'm using the standard debs from debian unstable.
