### ISSUE TITLE
Cannot share a folder with a group and a user with the same name

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36280] opened 2019-10-15 17:15 UTC
### Steps to reproduce
1. As admin, create 1 users (e.g. Alice) 
3. Log in as Alice and share a folder with ```admin``` user
5. Try to share the same folder with ```admin``` group

### Expected behaviour

Folder should be shared

### Actual behaviour

A warning related that the folder was already shared is shown

Note: Same behavior happens 10.2.1, so no regression

**Database:**
MySQL

**ownCloud version:** (see ownCloud admin page)

oC 10 10.3.0

It happens in webUI, desktop and Mobile clients. Screenshots from Desktop client provided:

![Screen Shot 2019-10-15 at 18 48 14](https://user-images.githubusercontent.com/10596560/66853600-f57ce980-ef7f-11e9-94c7-b0eb1c4111ad.png)
![Screen Shot 2019-10-15 at 18 48 03](https://user-images.githubusercontent.com/10596560/66853601-f57ce980-ef7f-11e9-8f33-629540d60417.png)

(@pmaier1 @mbarz jfyi) As said above it is not a regression from 10.2.1.

**Comment by phil-davis** [comment] 2019-10-16 01:57
Duplicate of issue #35488

**Closed** 2019-10-16 06:26 UTC
Labels: QA-team, bug
