### ISSUE TITLE
Proper design guidelines

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19186] opened 2015-09-19 11:51 UTC
There are lots of design changes happening in 8.2, but developers are left in the dark.

We need:
* Walk-through of the [design language](https://en.wikipedia.org/wiki/Design_language)
* Full design specifications
* Mock ups of **all** UI elements
* Links between each element and the CSS or JS class developers can use

I realise this is a lot of work, but the changes did not come out of thin air. There must be a solid basis for such drastic changes and it would be good if it could be shared with all. I'm sure designers interested in the project could help put the finishing touch.

@jancborchardt @owncloud/designers @Henni @raghunayyar @tomneedham 

I was tempted to ping all developers, because they need to be kept in the loop, but that's what the mailing list is for.

This is to help apps be in line with core and get answers to some questions:
* Why is the font so thin?
* Why so little contrast?
* Which background colour to pick for this or that element?
* When is a shadow applied and when is it not allowed?
* How much transparency? Where?
* Where should we add borders?
* Which icon do I use?
* Which style for disabled checkboxes? https://github.com/owncloud/core/issues/19191

**Comment by jancborchardt** [comment] 2015-09-21 09:07
Good point, we need to make this clear. Thanks for bringing up specific questions and points! cc @owncloud/designers

**Comment by michaelstingl** [comment] 2015-09-21 09:56
@jancborchardt Tools like https://github.com/pattern-lab/patternlab-php could help here to make designers and frontend-devs happy…

**Comment by jancborchardt** [comment] 2015-09-22 10:12
@oparoz this is a duplicate of https://github.com/owncloud/core/issues/309 – can you add your original post as a comment there? Thanks!

**Closed by jancborchardt** 2015-09-22 10:12 UTC
Labels: design, enhancement

**Comment by oparoz** [comment] 2015-09-22 11:44
@jancborchardt What about 8.2? People are supposed to guess or is this going to become available in the coming weeks as part of the 9.0 dev cycle?

@michaelstingl Great stuff :) Could defo be a first step

**Comment by jancborchardt** [comment] 2015-09-22 11:57
@oparoz it’s going to become available in the coming weeks. I need to focus on bugfixes for 8.2 before I go on vacation. Also, except the right sidebar there weren’t really any changes to what was there before, documented at https://doc.owncloud.org/server/8.2/developer_manual/app/css.html
