### ISSUE TITLE
[external storage] OC doesn't refresh the list of files in the external storage

### ISSUE THREAD

**Issue by NuxRo** [owncloud/core#21160] opened 2015-12-11 15:23 UTC
Hello,

I've added a local FTP account as external storage for a user and except for the files in there indexed after adding the storage originally, no subsequently added files are listed.
I've tried playing with the settings, but nothing has made a difference.

The logs don't show anything broken and tcpdump shows FTP traffic when I am accessing this external storage, it's just that none of the new files appear in the list.

I have checked the FTP account manually and all the files are there as it should be (that's a SyncThing stor).

Thoughts? Perhaps some caching issues?

**Comment by PVince81** [comment] 2015-12-11 16:23
@NuxRo I suspect that it's the usual problem that the PHP FTP functions do not return the mtime given by the FTP server. Or the FTP server doesn't provide mtimes, so change detection is not possible.

Duplicate of https://github.com/owncloud/core/issues/16407

**Closed by PVince81** 2015-12-11 16:23 UTC
