### ISSUE TITLE
Warning Fatigue - integrity check

### ISSUE THREAD

**Issue by arr0n** [owncloud/core#26467] opened 2016-10-24 18:02 UTC
This is not so much as an issue in code, but a problem in general.  

Please, add something so i can turn off your integrity check on a specific file.  I have a personal app, in a specific folder, that does a bespoke job for me an my users.  What i don't need is to be constantly told (nagged) the same message time and time again.  I got the message the first time, and the second time. and the other billion times after that.  I get it, owncloud thinks i have some hinky code there, but i don't.  So now this feature is absolutely worthless, because heaven forbid someone actually does change the integrity of a core file i'm so damn used to seeing a pointless and unwarranted warning, that i'm never going to notice it anyway, in fact the only time i'm going to notice anything is when the warning isn't there.  In the end you've managed to actually build into the owncloud the same well thought idea that constantly has Europeans clicking blindly on cookie-warnings whenever they visit a site, without ever reading them.

Now they may be a way to add the file to an internal signature list, but not that i could see amongst the FAQs.

So please, either update the FAQ with the way to turn this off for a specific file or folder, or a way to disable integrity checking, because its not going to be any use if owncloud consistently warns people about something they already know about.  This is basically the web app equivalent of the boy who cried wolf. 

I'm also guessing i'll about to get hit with a ton of responses about how i'm wrong, or stupid or something along those lines.  Seriously though, once you've informed someone of something, its not an app's job to keep on doing it.

**Comment by PVince81** [comment] 2016-10-24 18:27
Closing as duplicate of https://github.com/owncloud/core/issues/24218 which is about providing exclusion patterns

**Closed by PVince81** 2016-10-24 18:27 UTC

**Comment by arr0n** [comment] 2016-10-24 18:39
its not a duplicate, at all of that.  and i'm not sure if you're telling me i need to rename my app to .webapp or what.

**Comment by PVince81** [comment] 2016-10-24 18:47
See https://github.com/owncloud/core/issues/23186 which is about making it possible to configure excluded folders. Unfortunately this is currently not yet possible.

**Comment by arr0n** [comment] 2016-10-24 18:49
right, so is there one for disabling integrity checking then because its doesn't work for me in its current format

**Comment by PVince81** [comment] 2016-10-24 19:08
The purpose of the integrity check is to make sure no one modified files because doing so is likely to cause issues. It is also a way to check whether users patched their installs when they report bugs, because we can't help with custom modifications.

Now looking at your report again, you say that you have "have a personal app, in a specific folder, that does a bespoke job for me an my users". If your app is inside the "apps" folder, then you shouldn't receive any integrity warnings for it. If you do then it's a bug.

Can you confirm ?

**Comment by arr0n** [comment] 2016-10-24 19:26
wow, i know what an integrity check is but its not the purpose of integrity check to constantly alert for a known change that administrator of the deployment is fully aware.  There is absolutely no granularity in this 'security' check whatsoever.  Basically you're saying, that you guys know what is good and what isn't good for my deployment, even though you're not here.

A lot of times that may very well be right, but ultimately you have built a security control with no method of tuning false-positives out of it.  Surely one-size fits all isn't always going to fit.  That being said, i have moved my code to the apps folder as suggested, and the error has now gone.  This is far from ideal imho as you'll considered this resolved no doubt, and we'll be back to warning-fatigue with no means of the administrator being able to resolve it again soon   

I'll stop bitching now, and i would also say i do appreciate that at least i have lost the 'Yellow-Banner' of nags :D 

Cheers, and thanks 
A

**Comment by PVince81** [comment] 2016-10-24 19:34
Yeah, I know that the current way isn't ideal and you have valid points. That's why I hope we can get https://github.com/owncloud/core/issues/23186 implement for admins who know what they're doing.

In general the ownCloud code should be considered as a platform and stay unchanged and apps are developed on top of it, like you did. If something is missing in the core platform (APIs, etc), best is to send a feature request or a PR to this repo to add it so that the app can use it.
