### ISSUE TITLE
Restoring a modified picture is not possible.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18946] opened 2015-09-10 08:12 UTC
### Steps to reproduce

1. Upload a picture.
2. Upload a modified version of the picture.
3. Restore first version of picture.

### Expected behaviour
Picture is in its original aspect.

### Actual behaviour
Picture is not restored.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition..

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome.

**Comment by oparoz** [comment] 2015-09-10 21:48
I think that's because Preview is missing hooks, right @georgehrke ?

**Comment by PVince81** [comment] 2015-09-22 09:45
@SergioBertolinSG are you saying the preview is not updated ? Did you try downloading the file itself ?
The file should be reverted properly, but the preview might not, possibly duplicate of https://github.com/owncloud/core/issues/10559

**Comment by SergioBertolinSG** [comment] 2015-09-23 08:41
@PVince81 tested with today's master (23/09/2015) downloading the file it is reverted.
The preview is not reverted. But not only the thumbnail, the big preview.
So it makes you think that the actual file wasn't reverted.

**Comment by PVince81** [comment] 2015-09-23 09:04
Thanks for the info. So it's a duplicate of https://github.com/owncloud/core/issues/10559

**Closed by PVince81** 2015-09-23 09:04 UTC
Labels: bug, sev3-medium
