### ISSUE TITLE
OwnCloud App Store URL / .org / Directly add to your Instance

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#18201] opened 2015-08-11 11:28 UTC
Hi,

I think the AppStore (apps.owncloud.com) is more used by the .org-Version, because in the .com-Version are not all apps from apps.owncloud.com.

I think a redesign of apps.owncloud.com (owncloud.org-Logo) and a new URL apps.owncloud.org would be nice :)

Another cool thing would be, that you can directly add apps from apps.owncloud.com in your OwnCloud Instance. You could realize this with the Instance ID. 

Like: Type in your Federated Cloud ID and your Password!

**Comment by jancborchardt** [comment] 2015-11-11 16:51
Duplicate of https://github.com/owncloud/appstore-issues/issues/30

**Closed by jancborchardt** 2015-11-11 16:51 UTC
Labels: enhancement
