### ISSUE TITLE
Upload image to owncloud through webdav 

### ISSUE THREAD

**Issue by trinhvanhuy** [owncloud/core#21276] opened 2015-12-18 09:03 UTC
Hello, 
I'm using ng-file-upload to owncloud, the upload is successful for other files type except image
All images .png, .jpg are boken when i'm uploading ( for example, i uploaded images 900KB, but the image on server is just 800KB, thats why it's broken.  ) 
here is my code 
```js
$scope.uploadFiles = function (files) {
        $location.hash('bottom');
        $anchorScroll();
        $scope.uploadingFile = files[0];
        $scope.uploadingFile.mtime = new Date();
        $scope.uploadingFile.percent = 0;
        angular.forEach(files, function (file) {
            //blockUI.start();
            Upload.upload({
                url:  $window.serverPath + 'owncloud/remote.php/webdav/' + $rootScope.currentDir.path + '/' + file.name,
                file: file,
                method: 'PUT'
            }).then(function (resp) {
                $scope.uploadingFile = null;
            }, function (resp) {
                console.log('Error status: ' + resp);
                $scope.uploadingFile = null;
            }, function (evt) {
                var progressPercentage = parseInt(100.0 * evt.loaded / evt.total);
                $scope.uploadingFile.percent = progressPercentage;
                console.log('progress: ' + progressPercentage + '% ');
            });
        });
    };
```

**Comment by karlitschek** [comment] 2015-12-18 12:10
what is ng-file-upload ? A third party upload app?

**Comment by trinhvanhuy** [comment] 2015-12-18 12:41
https://github.com/danialfarid/ng-file-upload
its a lib for AngularJS

**Comment by PVince81** [comment] 2015-12-21 09:51
@trinhvanhuy please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Important missing information: your ownCloud version and also the matching logs.

Uploading through Webdav PUT in the browser should work already, so not sure why your files aren't fully uploaded.

**Comment by PVince81** [comment] 2016-03-01 15:44
Uploading with Webdav PUT should work as per my prototype here: https://github.com/owncloud/core/pull/21237
It uses blueimp's upload.

You might want to check how the PUT request looks like in my PR compared to yours, it is likely that you are missing something in your code.

This is not a bug in ownCloud, closing.

**Closed by PVince81** 2016-03-01 15:44 UTC
Labels: needs info
