### ISSUE TITLE
Admin page down after update to 9.0

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#22960] opened 2016-03-08 16:59 UTC
After update to 9.0 the admin page are down.
Only an white page will show.
OS: CentOS7
Log(journal):
 {PHP} Can't use method return value in write context at /var/www/html/owncloud/apps/files_external/lib/google.php#268

**Comment by LukasReschke** [comment] 2016-03-08 17:00
Can you fill otu the whole issue template? THX.

**Comment by LukasReschke** [comment] 2016-03-08 17:01
Ok. Damn. it's https://github.com/owncloud/core/commit/075dd54f6c4633237e2eef5fe808632c591aef4b …

**Comment by LukasReschke** [comment] 2016-03-08 17:02
@karlitschek  @cmonteroluque @PVince81  This means that Google Drive integration is broken under PHP 5.4

**Comment by tuxmaster** [comment] 2016-03-08 17:05
Temporary to get the site back:
runuser -s /bin/bash - apache -c "/var/www/html/owncloud/occ app:disable files_external"

**Comment by LukasReschke** [comment] 2016-03-08 17:07
@tuxmaster Could you test the patch from https://github.com/owncloud/core/pull/22961?

**Comment by tuxmaster** [comment] 2016-03-08 17:12
Yes it will fix it.
After apply it, I call runuser -s /bin/bash - apache -c "/var/www/html/owncloud/occ app:enable files_external"
An I can use the admin page.

**Comment by RealRancor** [comment] 2016-03-08 17:14
Also a duplicate of https://github.com/owncloud/core/issues/22958

But the issue here has currently more info

**Comment by LukasReschke** [comment] 2016-03-08 17:16
> Also a duplicate of #22958

Different issue probably. `empty` on arbitrary expressions works with PHP 5.5, #22958 uses PHP 5.5. See also http://php.net/manual/en/migration55.new-features.php :)

**Comment by nickvergessen** [comment] 2016-03-09 00:27
Should set up a lint task that checks for php 5.4 compatibility on CI?
This is the 3+ time we have this exact message

**Comment by PVince81** [comment] 2016-03-09 09:04
Does scrutinizer do that ?

**Comment by LukasReschke** [comment] 2016-03-09 09:08
> Does scrutinizer do that ?

No. But we could run PHPStorm once before the release. It's analyzer's can do that :see_no_evil:

**Comment by nickvergessen** [comment] 2016-03-09 09:20
Well we can do it on travis: https://github.com/owncloud/core/pull/22994 or we do something similar on jenkins (multiple checks, instead of only one red mark)

**Closed** 2016-03-09 11:20 UTC
Labels: app:files_external, bug, in progress, sev1-critical

**Comment by jacob-israel** [comment] 2016-04-07 18:34
Hello ,

Im having the same problem enabling external storage and then getting admin blank page om OWC 9 , someone could tell me where can I update google lib php files ?

thanks in advance 

Jacob

**Comment by RealRancor** [comment] 2016-04-07 18:36
@j-c-dando Just update to oC 9.0.1: https://owncloud.org/blog/owncloud-9-0-1-available/
