### ISSUE TITLE
[user_ldap] Config GUI should provide a way to disable TLS

### ISSUE THREAD

**Issue by shtrom** [owncloud/core#20517] opened 2015-11-16 00:16 UTC
I'm using ownCloud 8.2.0 on an OpenBSD server, authenticating users over lo0 against ldapd(8). As this is a loopback connection, TLS is disabled.

For some reason, the LDAP wizard convinced itself that it was, however, a TLS-secured connection, and set the parameter accordingly in the database (`oc_appconfig/(user_ldap,ldap_tls)`=1).

There doesn't seem to be any way to change this setting from the configuration interface, so I manually change it back to 0 in the database, which fixed my issue.

It would probably make sense for an option to en/disable TLS to be available in the configuration GUI, at least when connection to localhost.

**Comment by PVince81** [comment] 2015-11-16 10:51
@blizzz

**Comment by blizzz** [comment] 2015-11-16 11:19
It's possible to change it back using the occ command line tool, see https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#ldap-commands-label (set-config).

Unfortunately this false positives happen at times :( Not having the option to disable TLS in the GUI is not a bug (it's possible via CLI), but a valid feature request. I won't work on that but would happily accept PRs.

**Comment by PVince81** [comment] 2017-12-12 13:33
Won't fix unless someone is willing to send a PR to the user_ldap repo.

**Closed by PVince81** 2017-12-12 13:33 UTC
Labels: app:user_ldap, enhancement, junior job
