### ISSUE TITLE
Can't use custom wizard template for own theme

### ISSUE THREAD

**Issue by Commenter123** [owncloud/core#21689] opened 2016-01-13 12:56 UTC
https://doc.owncloud.org/server/8.1/admin_manual/operations/theming.html#theming-the-first-run-wizard

This doesn't work. I copied over `apps/firstwunwizard/templates/wizard.php` to my theme dir, but new users still see the default wizard.

**Comment by PVince81** [comment] 2016-01-14 10:06
@jancborchardt

**Comment by jancborchardt** [comment] 2016-01-15 08:57
Calling @schiesbn because this is PHP.

**Comment by PVince81** [comment] 2016-11-30 16:05
@PhilippSchaffrath

**Comment by PVince81** [comment] 2017-04-11 14:07
@phisch is this still valid ?

**Comment by ownclouders** [comment] 2018-01-13 01:08
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment] 2018-01-15 11:09
@VicDeo is it still possible the theme the wizard using a theme app ?

**Comment by VicDeo** [comment] 2018-01-15 16:47
@PVince81 reproduced

**Comment by VicDeo** [comment] 2018-01-15 17:02
ouch. there is a typo in documentation `apps/firstwunwizard/templates/wizard.php`
first**w**unwizard

**Comment by VicDeo** [comment] 2018-01-15 17:12
@Commenter123 sorry, the correct path  is `apps/firstrunwizard/templates/wizard.php` 
moving to docs

**Closed by VicDeo** 2018-01-15 17:12 UTC
Labels: bug, feature:theming
