### ISSUE TITLE
Calendar Events are not Privat from IOS to Outlook

### ISSUE THREAD

**Issue by Gexxinator** [owncloud/core#29170] opened 2017-10-08 19:02 UTC
Hi,

i use Owncloud 10 on a Iphone 5, Ipad 4 and 2 Windows PC with Office 2016.
Only 1 Windows PC shouldn´t see the private or busy events from the boss (he is using all the other devices).
When i set a event as busy on Iphone or Ipad, the event is coming up on Outlook as a Event with a visible event description, but it should be private. 
I set up the Outlook CalDav sync privacy settings (ticked all on) but it doesn´t work.

Pls help me. TY

**Comment by kdslkdsaldsal** [comment] 2017-10-09 05:42
Thanks for your report. I'm closing this as a duplicate of https://github.com/owncloud/core/issues/26161

**Closed by kdslkdsaldsal** 2017-10-09 05:42 UTC
