### ISSUE TITLE
Feature Request: OC9 Administration -> Users -> Display Storage Usage of each User

### ISSUE THREAD

**Issue by apg1980** [owncloud/core#23339] opened 2016-03-17 05:46 UTC
It would be very cool to see a feature within the users overview to see how much storage is each user consuming. is something of this planned?

**Comment by aspdye** [comment] 2016-03-17 08:40
There are some apps for ownCloud which show charts about the usage:

https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746
https://apps.owncloud.com/content/show.php/Usage+Charts?content=164956
https://apps.owncloud.com/content/show.php/Storage+Charts+2?content=165528

Please keep in mind, that all these apps are unmaintained, and are only compatible up to ownCloud 8.1 (some of them are only compatible with older versions of ownCloud).

I also think it would be a nice idea, to get something like this maintained - or official. Maybe we can also integrate this in the user administration :wink:

**Comment by DeepDiver1975** [comment] 2016-03-17 09:02
> Maybe we can also integrate this in the user administration

I'd be rather careful with integration into the user management - the storage usage cannot be computed by the admin online because some mounted storages are only available if the user is logged in.
Online computing the storage usage for thousands of users is anyhow a pain.

It wold be necessary to compute the usage for every user within his session - on login? on logout? on each file operation?
Login and logout will not work with the sso integrations which are out there.
On each file operation: waste of cpu cycles.

And these are only a few points in this area ....

No idea if this is really worth the effort - in addition if the admin is concerned about the quota being used on the physical server he can still use os tools to find out.

**Comment by PVince81** [comment] 2016-03-17 10:08
Duplicate of https://github.com/owncloud/core/issues/1344

**Closed by PVince81** 2016-03-17 10:08 UTC
