### ISSUE TITLE
[Thumbnails api] No thumbnail is returned if the name contains +

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#18074] opened 2015-08-05 10:56 UTC
### Steps to reproduce
1. There is an image called +.JPG
2. Using curl, it is possible to see that no thumbnail is returned

```curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG```

neither

 ```curl -u user server/index.php/apps/files/api/v1/thumbnail/25/25/+.JPG```

It is possible to check it coping the url in the browser
	server/index.php/apps/files/api/v1/thumbnail/25/25/%2B.JPG

What it is received is {"message":"File not found."}

### Expected behaviour
thumbnail is returned

### Actual behaviour
This message is shown {"message":"File not found."} instead of the thumbnail

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:**  apache 2.4.7

**Database:** mysql

**PHP version:**  5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1"}

This affect the android app.

**Comment by DeepDiver1975** [comment] 2015-08-05 11:20
confirmed

**Comment by oparoz** [comment] 2015-08-05 12:13
Duplicate of https://github.com/owncloud/core/issues/17855

**Comment by DeepDiver1975** [comment] 2015-08-05 12:28
THX @oparoz I was not aware of this - THX

**Comment by DeepDiver1975** [comment] 2015-08-05 12:32
duplicate

**Closed** 2015-08-05 12:31 UTC
Labels: bug, duplicate
