### ISSUE TITLE
Manipulation with a federated share leads to an orphaned share entry

### ISSUE THREAD

**Issue by mirekys** [owncloud/core#24927] opened 2016-05-31 13:28 UTC
### Steps to reproduce
1. On server "A": share folder "F"  to remote user "X" on server "B"
2. On server "B": accept federated share of folder "F"
3. On server "B": reshare folder "F" to local user "Y"
4. On server "A": unshare folder "F"

### Expected behaviour
- Share entries should be deleted both from server "A" and "B".
- Unshare action should be propagated on the local reshare of the folder
- Folder "F" should completely disappear from "Shared with [you|others]" of both users "X" and "Y".

### Actual behaviour
- Local share entry and filecache entry remains on server "B".
- User "X" sees a folder entry without any path/name in "Shared with others".
- User "Y" sees a folder with proper name, in "Shared with me". Clicking on it redirects back to /.
- There is no way of removing the orphaned share. Even the cleanup cron job seems that it doesn't pick it up.

### Server configuration
**Operating system**:
RHEL 6.4

**Web server:**
Apache/2.4.12

**Database:**
PostgreSQL 9.2

**PHP version:**
5.6.5

**ownCloud version:**
8.2.5

**Updated from an older ownCloud or fresh install:**
from 8.2.2

**Where did you install ownCloud from:**
https://owncloud.org/changelog/

**List of activated apps:**
  - activity: 2.1.3
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - user_shib: 0.1

**The content of config/config.php:**
  // unrelated items omitted //
  'dbtype' => 'pgsql',
  'version' => '8.2.5.2',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'enable_previews' => false,
  'singleuser' => false,
  'share_folder' => '/Shared',
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'allow_user_to_change_display_name' => true,
  'asset-pipeline.enabled' => true,
  'session_keepalive' => true,

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Shibboleth (user_shib)

### Logs

Shared folder name was 'Pisa2'.

#### Web server error log
```
x.x.x.x - User "X" [31/May/2016:14:00:00 +0200] "GET /index.php/apps/files/ajax/list.php?dir=%2FShared%2FPisa2&sort=name&sortdirection=asc HTTP/1.1" 404 - "-" "Mozilla/
5.0 (X11; Linux x86_64....
```
#### ownCloud log (data/owncloud.log)
This is logged after user "Y" clicks on orphaned share of folder "F":
```
{"reqId":"xxx","remoteAddr":"xxx","app":"files_sharing","message":"Unable to get mount for shared storage '13763' user 'X'","level":3,"time":"2016-05-31T14:00:07+02:00"}
```

#### oc_share entries
```
  id  | share_type |    share_with    |    uid_owner    | parent | item_type | item_source |   item_target    | file_source |              file_target               | permissions |   stime    | accepted | expiration | token | mail_send
------+------------+------------------+-----------------+--------+-----------+-------------+------------------+-------------+----------------------------------------+-------------+------------+----------+------------+-------+-----------
 7413 |          0 | User 'Y'         | User 'X'        |        | folder    | 46013824    | /Shared/46013824 |    46013824 | /Shared/Pisa2                          |          31 | 1464693588 |        0 |            |       |         0
```

#### oc_filecache entries
```
  fileid  | storage | path |            path_hash             | parent | name  | mimetype | mimepart |   size    |   mtime    | storage_mtime | encrypted | unencrypted_size |     etag      | permissions
----------+---------+------+----------------------------------+--------+-------+----------+----------+-----------+------------+---------------+-----------+------------------+---------------+-------------
 46013824 |   13763 |      | d41d8cd98f00b204e9800998ecf8427e |     -1 | Pisa2 |        2 |        1 | 170151793 | 1445775971 |    1445775971 |         0 |                0 | 562cca63de4b2 |          31
(1 row)
```

#### oc_storages entries
```
                    id                    | numeric_id | available | last_checked
------------------------------------------+------------+-----------+--------------
 shared::00b3eadb0e29208211e08ef158563969 |      13763 |         1 |
```

#### HTML dump
```
<tr data-icon="/core/img/filetypes/folder-shared.svg" data-share-recipients="User X" data-share-permissions="31" data-share-id="7413" data-path="" data-mounttype="shared" data-permissions="31" data-mtime="1464693588000" data-mime="httpd/unix-directory" data-file="" data-type="dir" data-id="46013824">
        <td class="filename">
                <div class="thumbnail" style="background-image: url(&quot;/core/img/filetypes/folder-shared.svg&quot;); background-size: 32px auto;"></div>
                <a href="/index.php/apps/files?dir=/" class="name">
                        <span class="nametext"><span class="innernametext"></span></span>
                        <span currentuploads="0" class="uploadtext"></span>
                        <span class="fileactions">
                                <a title="" data-original-title="" class="action action-share permanent shared-style" href="#" data-action="Share">
                                        <img class="svg" alt="" src="/core/img/actions/share.svg">
                                        <span>Shared with User X</span>
                                </a>
                                <a title="" data-original-title="" class="action action-menu permanent" href="#" data-action="menu">
                                        <img class="svg" alt="Actions" src="/core/img/actions/more.svg">
                                </a>
                        </span>
                </a>
        </td>
...
</tr>
```

**Comment by nickvergessen** [comment] 2016-05-31 13:33
Duplicate of https://github.com/owncloud/core/issues/16751

**Comment by PVince81** [comment] 2016-06-01 08:23
So upgrading to 9.0.2 would fix that. Not sure if that fix is backportable.

**Comment by nickvergessen** [comment] 2016-06-01 08:40
Woot, no. It's more a design decision to be like that.

**Comment by nickvergessen** [comment] 2016-06-01 08:40
#16751 has no PR attached (apart from smashbox to expect a different result)

**Comment by PVince81** [comment] 2016-06-01 08:44
Ah yes, indeed. And the orphaned share entry will get removed later through background jobs.

**Closed by PVince81** 2016-06-01 08:44 UTC
Labels: feature:federated-cloud-sharing
