### ISSUE TITLE
Faulty session handling (creating massive amount of sessions when webdav-interface is in use) - workaround

### ISSUE THREAD

**Issue by Cymaphore** [owncloud/core#5383] opened 2013-10-17 10:33 UTC
ownCloud 5.0.11
lighttpd/1.4.28 (via reverse proxy)
Linux 3.8.0-31-generic #46~precise1-Ubuntu SMP Wed Sep 11 18:21:16 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Many (most?) WebDAV-Clients don't support cookie-handling very well, since session credentials are handled using HTTP Authentication. ownCloud however enforces the creation of sessions, even if they are not needed.

This causes the creation of a MASSIVE amount of useless session files when using caldav, carddav, etc. ... In my personal instance approx. 20000 files are created per week. That means a serious performance impact.

I created a workaround as well as a suggestion to resolve this issue permanently, if you provide me with proper feedback.

Workaround - Remove session after remote.php-query is done:

--- remote.php     2013-10-17 12:12:35.797631235 +0200
+++ remote.php  2013-10-17 12:12:40.365631235 +0200
@@ -38,3 +38,6 @@
 }
 $baseuri = OC::$WEBROOT . '/remote.php/'.$service.'/';
 require_once $file;
+
+session_unset();
+session_destroy();

This is a safe way to resolve the issue, however:

There is a performance gain possible but not creating the session when involving remote.php at all. Is there already a way to suppress session-creation? If not, it could be supressed using a variable like $RUNTIME_NOAPPS (for example set $RUNTIME_NOSESSION = true; at the top of remote.php, in base.php don't create session when it is set).

If you like that solution I could implement it. However, I highly recommend to do something about it.

Best regards,
Martin

**Comment by drsavoye** [comment] 2015-01-20 00:24
I know this is a very old thread, but I am using ownCloud 7.0.4 and have been having this issue. With a mere 5-6 clients, I still get upwards of 10K sessions created per day. I am not using the calendar or any other apps; only the file syncing. None of the suggestions above made any difference. Hopefully this is fixed in OC8.

In the meantime, for a quick hack, the only workaround I could find was modifying lib/private/session/internal.php.

```php
    public function __construct($name) {
                session_name($name);
                session_start();

+                if(preg_match("/(csyncoC|mirall)/", $_SERVER['HTTP_USER_AGENT'])) {
+                        session_unset();
+                        session_destroy();
+                }
                
                if (!isset($_SESSION)) {
                        throw new \Exception('Failed to start session');
                }
                $this->data = $_SESSION;
        }
```
Making 'session_start()' only run if the preg_match returns false makes Mac OS X clients unable to sync, returning "Internal Server Error 500". Allowing it to actually create the session, and then destroying it immediately, was the only thing that worked to control the massive session spawning.

**Comment by PVince81** [comment] 2015-02-04 19:00
@LukasReschke

**Comment by LukasReschke** [comment] 2015-02-28 23:42
Best from my PoV would be to have multiple endpoints. One with session support and one without…

**Comment by DeepDiver1975** [comment] 2015-03-02 11:05
from my understanding this is could be a parameter which is kind of injected into the initialization code.

basically @Cymaphore initial approach is valid - with exception that I don't want to rely on magic defines. A ctor parameter to the boostrapping object might be reasonable - in addition a session should anyhow only be created if really requested ....

8.2 from my POV

**Comment by MorrisJobke** [comment] 2015-06-03 10:06
@dragotin Wasn't there a fix in the client that handles the session properly? I remind a bug in the client with a `;` at the end of the HTTP header which is wrong.

**Comment by dragotin** [comment] 2015-06-03 11:53
@MorrisJobke current clients send both the Cookie as well as the Authorization header. The ```;``` should not be an error btw as it's a valid char (delimiter).

**Comment by PVince81** [comment] 2015-09-21 10:08
@MorrisJobke any update ? Is there anything that needs fixing or is this resolved ?

**Comment by DeepDiver1975** [comment] 2015-09-22 11:42
> Is there anything that needs fixing or is this resolved ?

not fixed from my pov - we are still creating a session for basic authenticated requests

@LukasReschke or do I miss anything? THX

**Comment by LukasReschke** [comment] 2015-09-22 12:49
Correct. - Some token based auth such as for example OAuth alike approaches as we aim for anyways in one way or another will solve this though…

**Comment by DeepDiver1975** [comment] 2015-09-22 13:18
@cmonteroluque @MTRichards moving to 9.0 - nothing we can do in the scope of 8.2

**Comment by cmonteroluque** [comment] 2015-09-22 23:18
ok

**Comment by bboule** [comment] 2016-01-05 16:55
@gig13 is this impacting a customer?

**Comment by gig13** [comment] 2016-01-05 17:04
@michaelstingl @cdamken 
SF Case 2212 -- Could you follow up with originator if this is still an issue/feature request?

**Comment by guruz** [comment] 2016-01-06 11:12
(note we have the other way round as server bug in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 ... the server does not accept DAV with a proper session cookie but without HTTP auth)

**Comment by cdamken** [comment] 2016-01-07 16:09
> @michaelstingl @cdamken
> SF Case 2212 -- Could you follow up with originator if this is still an issue/feature request?

As you pointed in SFDC, The solution should be in 8.2 -  They still need the solution

**Comment by bboule** [comment] 2016-01-07 16:51
OK so it looks like this s set for 9 @gig13 could I ask you to set the expectation with the user?

**Comment by gig13** [comment] 2016-01-07 16:55
@michaelstingl @cdamken 
This is an EMEA related user, could you please follow up?

**Comment by cdamken** [comment] 2016-01-07 17:11
> OK so it looks like this s set for 9 @gig13 could I ask you to set the expectation with the user?

It would be good if @gig13 provide us the background from the case, there is no information in SFDC besides the 2 emails.

**Comment by gig13** [comment] 2016-01-07 17:19
@cdamken 
This is from almost 1 year ago and was suggested by the user as a feature request, not sure what else you need. Should just be a matter of communication that this is now targeted for 9.0

**Comment by cdamken** [comment] 2016-01-07 17:51
@gig13 I already informed.

**Comment by MorrisJobke** [comment] 2016-01-19 09:14
I don't want to be the party pooper here, but https://github.com/owncloud/core/pull/21592 which addresses this issue too was moved to 9.1 with the reason to fix this properly with a completely different approach.

cc @bboule @karlitschek @DeepDiver1975

**Comment by LukasReschke** [comment] 2016-01-19 10:03
I have been told there is not a stable user agent within our Android or iOS app. It can be completely modified by ownBrander.

Otherwise I'd have suggested to do a check if the user agent is a supported ownCloud client and if yes use sessions. Otherwise not. So maybe we should somehow unify the user agents? For desktop we have a suitable one as it contains stable parts.

**Comment by guruz** [comment] 2016-01-19 11:33
Branching code by user-agent is not nice. Can we use a HTTP header instead/additionally?

Also an idea would be to start the session only when ```status.php``` or capabilities (for desktop) or ```...``` (for mobile) was requested. Then in WebDAV only use session, don't start it(?)

IMHO the approach by @MorrisJobke sounded also OK.

**Comment by LukasReschke** [comment] 2016-01-19 12:30
As far I get @MorrisJobke's approach this will still suffer from the fact that there will still be a pollution from what I get.

Having an additional HTTP header makes sense. Using status.php sounds like a bit of magic since we likely would need to set a cookie and be sure the client always send it.

Also reading a session without starting one requires AFAIK quite some hacks.

**Comment by MorrisJobke** [comment] 2016-01-19 12:43
> As far I get @MorrisJobke's approach this will still suffer from the fact that there will still be a pollution from what I get.

But it gives us the possibility to delete orphaned sessions properly and not rely on php internal GC.

**Comment by LukasReschke** [comment] 2016-01-19 12:53
Yeah. But how do you know what is an orphaned session? How do you detect this on a scale of 10k sessions per user?

**Comment by DeepDiver1975** [comment] 2016-01-19 13:59
From an architectural pov we should stop using sessions and walk the token based approach.
Sessions should only be used in the web app itself - any client should make use of client specific tokens which will allow us to explicit revoke connections.

But this is a long term project ...

What can we do now?

No matter what we do we have to stay backward compatible - older clients still need to be capable to connect and properly use sessions.

Did we recently measure the overhead of requests using sessions vs. requests using basic auth?

**Comment by LukasReschke** [comment] 2016-01-19 14:58
> Did we recently measure the overhead of requests using sessions vs. requests using basic auth?

DB users are around 70ms per request. (BCrypt etc)

Will probably also have quite some impact on LDAP setups? cc @blizzz

**Comment by karlitschek** [comment] 2016-01-19 15:01
i think not using seasions is out of the question for now. this would basically mean that we fire x times more request against the usermanagement and other systems. i wouldn't be surprised if y is bigger then 10. this would kill big installations.  we have to find a better solution somehow

**Comment by blizzz** [comment] 2016-01-19 21:18
> > Did we recently measure the overhead of requests using sessions vs. requests using basic auth?

> Will probably also have quite some impact on LDAP setups? cc @blizzz

Would do a bind against LDAP on every request. I assume this would slow down bulk file operations. Otherwise, LDAP relies on it's caching, so no other effects to be expected. Anyway, no sessions at all will be edgy on big installations (given that it halfway works right now, did not read up all the way back).

**Comment by karlitschek** [comment] 2016-01-20 20:54
Idea from @LukasReschke:
We do a cookie detection first and check if the WebDAV client supports cookies. And we start the session only if cookies are supported.
1. request: We set a YOLO=42 cookie if no session exists
2. request: If no session exists and cookie YOLO exist then we do start_session
3. request: If a session exists then we use the session.

Should fix the problem IMHO.
Opinions?

**Comment by MorrisJobke** [comment] 2016-01-21 00:33
> 1. request: We set a YOLO=42 cookie if no session exists
> 2. request: If no session exists and cookie YOLO exist then we do start_session
> 3. request: If a session exists then we use the session.
> 
> Should fix the problem IMHO.

Sounds good, but only if we actually use `YOLO` as cookie name and `42` as value :stuck_out_tongue_winking_eye:

**Comment by guruz** [comment] 2016-01-21 12:00
@karlitschek @LukasReschke You can optionally shortcut this by checking if the request sends any cookies at all. (because our sync clients will already send some because they got them from request ```status.php``` and capabilities)

**Comment by MorrisJobke** [comment] 2016-01-21 13:10
> @karlitschek @LukasReschke You can optionally shortcut this by checking if the request sends any cookies at all. (because our sync clients will already send some because they got them from request status.php and capabilities)

This would then be even better. Because it doesn't involve any additional stuff that needs to be documented why we send an unused cookie.

**Comment by karlitschek** [comment] 2016-01-21 15:20
O.K. Would be good to simplify.  @DeepDiver1975 @LukasReschke Can you confirm?

**Comment by LukasReschke** [comment] 2016-01-21 15:28
Would be possible, would however only work for our own clients. I didn't check our mobile apps though but they may be negligible considering that they don't sync files all at once.

This means that other clients that support cookies (there are some) will not profit from our cookies and need to re-authenticate on each request. I'd rather prefer the YOLO cookie as it will be supported by any client that supports cookies as per the spec while the other one will only work for clients that do a status.php request which is also some kind of magic.

**Comment by PVince81** [comment] 2016-01-21 15:40
Note that the outcome of this also has the potential to accelerate federated shares, see https://github.com/owncloud/core/issues/12228

**Comment by guruz** [comment] 2016-01-21 15:59
@LukasReschke Yes that's why I wrote _optionally_ shortcut :-)

**Comment by PVince81** [comment] 2016-02-12 10:01
We're past feature freeze, what to do with this issue ?

**Comment by PVince81** [comment] 2016-06-13 13:47
@ChristophWurst mind linking to the ticket/PR with the workaround we talked about ?

**Comment by PVince81** [comment] 2016-07-06 09:49
From what I understand, if you use token-based auth (aka application passwords) in 9.1 it should not create any additional sessions now. To be confirmed.

**Comment by PVince81** [comment] 2017-01-27 16:22
@PhilippSchaffrath @butonic for session handling for clients that do not support cookies.
Not sure if OAuth2 can help there.

**Comment by PVince81** [comment] 2017-04-11 14:28
YOLO cookie as mentionned in https://github.com/owncloud/core/issues/5383#issuecomment-173356034 might be the "cookie_test" cookie that was added in 9.1 and which apparently doesn't work correctly.

See https://github.com/owncloud/core/issues/26651 and https://github.com/owncloud/core/pull/27549

**Comment by PVince81** [comment] 2017-12-13 15:35
Closing in favor of https://github.com/owncloud/core/issues/29779

**Closed by PVince81** 2017-12-13 15:35 UTC
Labels: enhancement, enhancement-PM, in progress, technical debt
