### ISSUE TITLE
404 Not Found issue after updating ownCloud 10.3.2.

### ISSUE THREAD

**Issue by utsav1-cyber** [owncloud/core#40487] opened 2022-11-11 09:23 UTC
While upgrading the ownCloud from 10.3.0 to 10.3.2 but it redirects to this URL 
http://***/****/index.php/login
and shows 404 Not Found.

I remove all the files and directories of ownCloud version 10.3.0, except data and config files, and extract the 10.3.2 files and directories. After clicking on the Start update button. It shows an update complete and redirected to the login page but shows 404 Not Found
![Screenshot_8](https://user-images.githubusercontent.com/77831507/201308716-8e19b4cb-b2a9-4696-8adf-5d51cefcf21f.png)
.

**Comment by cortho** [comment] 2022-11-11 11:32
This is not a bug but a support question. I see you already had opened your question at https://github.com/owncloud/core/issues/40487 - closing here

**Closed by cortho** 2022-11-11 11:32 UTC
