### ISSUE TITLE
settings/admin is or is not hanging depending on the loglevel

### ISSUE THREAD

**Issue by hengels7** [owncloud/core#16317] opened 2015-05-13 08:00 UTC
### Steps to reproduce
1. Set loglevel to 2, 3 or 4
   (if loglevel is set to 0, then the error doesn't occur!)
2. Load the settings/admin page in a browser

### Expected behaviour
Page should show

### Actual behaviour
After a long time, the browser reports, that the page cannot be loaded.
During this time, top shows an apache process running at 100% cpu usage

### Server configuration
**Operating system**: ubuntu server 14.04
**Web server:** apache 2.4.7
**Database:** mysql 5.5
**PHP version:** php 5.5.9
**ownCloud version:** 8.0.3 updated from 8.0.1 .. 8.0.2 ..

**List of activated apps:** documents, ldap user and group management, standard apps 

**The content of config/config.php:**
<?php
define("DEBUG", true);
$CONFIG = array (
  'instanceid' => 'oc0or2ahuorl',
  'passwordsalt' => 'no',
  'secret' => 'neither',
  'trusted_domains' => 
  array (
    0 => '10.1.1.23',
    1 => '10.1.1.4',
    2 => 'lalala',
    3 => 'lalalala',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://10.1.1.23/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'ownCloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ownCloud',
  'dbpassword' => 'none',
  'installed' => true,
  'loglevel' => 1,
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

### Client configuration
**Browser:**
chrome

**Operating system:**
linux

#### Web server error log

access.log:
10.1.1.4 - - [13/May/2015:08:21:19 +0200] "GET /owncloud/index.php/settings/admin HTTP/1.1" 302 789 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
10.1.1.4 - - [13/May/2015:08:21:20 +0200] "GET /owncloud/index.php?redirect_url=%2Fowncloud%2Findex.php%2Fsettings%2Fadmin HTTP/1.1" 302 1097 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
10.1.1.4 - - [13/May/2015:08:21:48 +0200] "GET /owncloud/core/vendor/jquery/dist/jquery-migrate.min.map HTTP/1.1" 404 549 "http://www.enteredu.de/owncloud/index.php/settings/admin" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"

error.log:
nothing

#### ownCloud log (data/owncloud.log)
nothing

#### Browser log
nothing

**Comment by Xenopathic** [comment] 2015-05-13 13:30
Check your permissions on data/owncloud.log - this might be caused by ownCloud being unable to write to the log file, which it has no need to do when the log level is set low.

**Comment by tflidd** [comment] 2015-05-13 14:16
Loglevel 0 is debug mode, in this case his setup works.

**Comment by hengels7** [comment] 2015-05-13 14:39
Hm .. I didn't know, that there were two files called owncloud.log on my machine .. one in /var/log another one in the data subfolder .. the latter was about 400 MB in size .. I backed it up and deleted it in the data folder .. now its working independently on the loglevel!

I guess, the problem was, that the log section of the admin page had a problem with the huge log file!?

**Comment by Henni** [comment] 2015-05-14 14:44
I see the same issue. Calling the admin page with debugging enabled results in a CPU usage of 100% for around a minute even though my log file has 'just' a size of 7 MB.

Deleting the log file resolved the issue.

I would guess that this has something to do with the parsing of the log.

**Comment by PVince81** [comment] 2015-05-15 14:36
I wonder if the code that reads the look is just dumbly reading in all lines and moving to the end.

Does the admin page stay completely white for a while ? Not sure if the first log snippet is ajax-loaded. If not, it should be changed to be ajax loaded instead, so at least the admin page can appear first.

**Comment by hengels7** [comment] 2015-05-15 15:17
complete page stays white .. i suppose, that not a single byte gets
delivered .. definitely no ajax .. i know nothing about the implementation,
but i think the loop takes place in the logic phase before the page is
rendered ..
Am 15.05.2015 4:36 nachm. schrieb "Vincent Petry" <notifications@github.com

**Comment by PVince81** [comment] 2015-08-03 16:24
In any case, the log file should always be ajax loaded by default instead of preloading the first rows in the PHP template.

**Comment by Xenopathic** [comment] 2015-08-03 18:35
I just ran a quick benchmark with `fseek()` - it seems independent of file size, and running it 1 million times (e.g. reading the last 1MB of a file) took about 3 seconds on a tmpfs. I doubt it's the source of the issues.

**Comment by blizzz** [comment] 2016-03-01 14:29
So, anything to do here, or which information is missing?

**Comment by PVince81** [comment] 2016-05-30 15:22
@hengels7 is this still happening with more recent OC and PHP versions ?

**Comment by PVince81** [comment] 2016-08-15 15:12
Closing due to lack of feedback

**Closed by PVince81** 2016-08-15 15:12 UTC
Labels: bug, needs info
