### ISSUE TITLE
Corrupt zip folder downloads

### ISSUE THREAD

**Issue by gig13** [owncloud/core#18905] opened 2015-09-08 15:20 UTC
### Steps to reproduce
1. Unable to reproduce -- suspecting environment related
2.
3.

### Expected behaviour
When selecting a folder to download from the Web UI, the file should be archived into a zip file and downloaded to a local folder. The file should be successfully extracted without errors or file corruption.

### Actual behaviour
After downloading a Folder from the Web UI the zip file passes initial CRC checks, but every file within the archive has a bad CRC. When viewing some of the files, some are noticeably corrupt -- for example when viewing a jpg file, it had a grey bar of lost data at the bottom.

### Server configuration
**Operating system**: Ubuntu 14.0.4

**Web server:** Apache

**Database:** MySQL 5.5.43

**PHP version:** 5.5.9-1ubuntu4.11

**ownCloud version:** 7.0.6.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** See Config Report on s3 https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18905

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

### Client configuration
**Browser:** Firefox, Internet Explorer, Chrome

**Operating system:** Windows

#### ownCloud log
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F18905

Not sure if this is relevant, but at one point the system had "pigz" installed. Was not able to reproduce in a test environment, I suspect this is environment related.

@MorrisJobke

**Comment by MorrisJobke** [comment] 2015-09-09 09:28
This looks odd
```
{"app":"PHP","message":"session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' at \/var\/www\/hosted\/owncloud\/lib\/private\/session\/internal.php#21","level":3,"time":"2015-08-13T19:41:04+00:00"}
{"app":"PHP","message":"session_write_close(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' at \/var\/www\/hosted\/owncloud\/lib\/private\/session\/internal.php#52","level":3,"time":"2015-08-13T19:41:04+00:00"}
{"app":"PHP","message":"session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (\/var\/lib\/php5) at \/var\/www\/hosted\/owncloud\/lib\/private\/session\/internal.php#52","level":3,"time":"2015-08-13T19:41:04+00:00"}
```

**Comment by MorrisJobke** [comment] 2015-09-09 09:30
This looks like some broken shares:

```
{"app":"files","message":" Backends provided no user object for ","level":3,"time":"2015-08-13T01:17:41+00:00"}
{"app":"hook","message":"error while running hook (\\OC\\Files\\Cache\\Shared_Updater::writeHook): ","level":3,"time":"2015-08-13T01:17:41+00:00"}
```

**Comment by MorrisJobke** [comment] 2015-09-09 09:31
@gig13 Does this happen on file list or on the public folder share?

**Comment by gig13** [comment] 2015-09-10 14:04
@MorrisJobke 
It happens on shares or non shares, same results.

**Comment by gig13** [comment] 2015-09-11 14:32
@bboule

**Comment by bboule** [comment] 2015-09-11 15:43
@MorrisJobke Any thoughts here?

**Comment by gig13** [comment] 2015-09-14 13:42
@MorrisJobke @bboule 
Who can assist with the archiving functionality?

**Comment by PVince81** [comment] 2015-09-17 09:11
The archiving itself is done by a third party library.
Can the files from this shared folder be downloaded individually ?
What ZIP client was used when extracting ? Does the corruption happen for other files ?

Also: are there people concurrently modifying the files while the ZIP file is being created ? (see https://github.com/owncloud/core/issues/16960)

**Comment by PVince81** [comment] 2015-09-17 09:11
When redownloading the ZIP several times, are the files corrupted in the same way every time ? Or is the corruption random ?

**Comment by gig13** [comment] 2015-09-17 12:20
@PVince81 
The files can be downloaded individually fine, the issue has been with zipping them up.

There are no other individuals modifying the files during the download.

**Comment by gig13** [comment] 2015-09-22 16:02
It seems the ZIPs are always the same, the tail end of each extracted file and our standard unzip tool is PowerArchiver running on Windows.

**Comment by PVince81** [comment] 2015-09-23 08:17
Good, so this information completely excludes randomness and concurrency.

**Comment by DeepDiver1975** [comment] 2015-09-23 08:52
We might want to retry this with master - we did update zip streamer ... maybe this helps ....

**Comment by McNetic** [comment] 2015-09-23 09:49
PowerArchiver seems to have issues with either the Zip64 extension or with the streamed zip feature. I also get CRC errors on perfectly valid zip files in PowerArchiver. I can not reproduce the corrupted contents; could you provide an example of a zip file where content is corrupted?

**Comment by gig13** [comment] 2015-09-23 11:58
@McNetic 
I should be able to obtain one.

**Comment by gig13** [comment] 2015-09-23 17:06
@McNetic @DeepDiver1975 
File uploaded to s3 (InstantUpload.zip) https://s3.owncloud.com/owncloud/index.php/apps/files?dir=/Shared/owncloud/support/github-issues/core/18905

I opened the file using 7zip without issue and the images appear to be fine -- no visible corruption or gray lines at the bottom of the files.

**Comment by DeepDiver1975** [comment] 2015-09-23 21:40
> @McNetic @DeepDiver1975
> File uploaded to s3 (InstantUpload.zip) https://s3.owncloud.com/owncloud/index.php/apps/files?dir=/Shared/owncloud/support/github-issues/core/18905

@gig13 FYI: @McNetic is a community contributor who has no access to s3 - please add a public link - THX

**Comment by McNetic** [comment] 2015-09-28 09:43
So this appears to be purely a PowerArchiver issue?

**Comment by DeepDiver1975** [comment] 2015-09-28 10:25
> So this appears to be purely a PowerArchiver issue?

looks like ...

**Comment by MorrisJobke** [comment] 2015-09-28 11:59
@DeepDiver1975 Is it possible that this is fixed by #19318 ?

**Comment by LukasReschke** [comment] 2015-09-28 20:00
> @DeepDiver1975 Is it possible that this is fixed by #19318 ?

No. #19318 will make oC deliver TAR files for OS X. It will however not change anything with regard to the ZIP implementation. PowerArchiver seems to be a Windows utility.

**Comment by DeepDiver1975** [comment] 2015-09-30 14:00
> PowerArchiver seems to have issues with either the Zip64 extension or with the streamed zip feature. I also get CRC errors on perfectly valid zip files in PowerArchiver. I

@gig13 is there an opportunity to get in touch with PowerArchiver support and get some questions answered? Like do they support Zip64 and streamed zips? THX

**Comment by cmonteroluque** [comment] 2015-10-01 20:01
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by gig13** [comment] 2015-10-07 18:40
Exploring options with the end user to see if the end user can use a different archiver (7zip) etc.

**Comment by MTRichards** [comment] 2015-10-07 21:38
issue is being tested for 8.2 and  backported https://github.com/owncloud/core/pull/19466

**Comment by LukasReschke** [comment] 2015-10-08 07:20
@MTRichards No. That PR is as stated above completely unrelated. The PR fixes only a problem on OS X.

In this issue we're talking about problemy with a non-default Windows application. Personally I'd say the vendor is to blame. That said this seems like an upstream issue and I didn't see yet the required information that was requested in https://github.com/owncloud/core/issues/18905#issuecomment-142738165

Until this is done we or @MCNetic can do *nothing* about this issue.

**Comment by DeepDiver1975** [comment] 2015-10-08 08:53
I'm voting for close as won't fix - it's a problem within PowerArchiver

**Closed** 2015-10-14 21:06 UTC
Labels: app:files, blue-ticket, bug
