### ISSUE TITLE
Owncloud Authentication does not work with PHP CGI

### ISSUE THREAD

**Issue by chicobico** [owncloud/core#15883] opened 2015-04-27 11:43 UTC
Owncloud does not work on a server configuration which uses php as cgi and not as fcgi. These configuration is often used in Shared Hosting environments.
The error occurs if you try to access your installation through webdav with the owncloud clients.
```
No basic authentication headers were found
```

The error occurs because the htaccess file only sets the XAuthorization Header if mod_fcgid.c is loaded.

To fix this problem change this line to check if mod_cgi.c is loaded.
```
  <IfModule mod_cgi.c>
    <IfModule mod_setenvif.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
  </IfModule>
```
Or add a additional check to the htaccess
```
  <IfModule mod_fcgid.c>
    <IfModule mod_setenvif.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
  </IfModule>
  <IfModule mod_cgi.c>
    <IfModule mod_setenvif.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
  </IfModule>
```

**Comment by LukasReschke** [comment] 2015-04-27 12:45
Duplicate of https://github.com/owncloud/core/issues/776,

**Closed by LukasReschke** 2015-04-27 12:45 UTC
