### ISSUE TITLE
When selecting unlimited storage quota it should be configurable to display "unlimited" OR the actual number of available storage

### ISSUE THREAD

**Issue by gig13** [owncloud/core#19988] opened 2015-10-22 19:56 UTC
### Steps to reproduce
1. Set a users quota to unlimited
2. Check the Web UI available storage and it calculates based on what is actually available
3. Check the desktop client available storage -- it polls from the sever the actual amount.

### Expected behaviour
When unlimited is selected, the admin should be able to select the display option for the users to show the actual available space OR just display the text "unlimited".

### Actual behaviour
The actual value of the quota and percentage is displayed.

### Server configuration
**Operating system**: Ubuntu

**Web server:** apache 2.4

**Database:** MariaDB Galera Cluster

**PHP version:** 5.5.9-1ubuntu4.7

**ownCloud version:** 8.1.1.3

**Updated from an older ownCloud or fresh install:** upgrade

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

@MTRichards @bboule

**Comment by PVince81** [comment] 2015-10-26 11:18
Tagged as enhancement as this isn't a bug.
Assuming that the display in question is for both the web UI (personal page) and sync clients ?

**Comment by PVince81** [comment] 2015-10-26 11:18
@cmonteroluque @DeepDiver1975 @karlitschek

**Comment by MTRichards** [comment] 2015-10-26 11:51
Yes, the problem is that the sync clients have a number while the web interface says unlimited. Sync clients seem to show the remaining disk space, which must be the server API reporting the free disk space as the quota. While in reality this is the limit for an upload, the web and client interfaces should show the same thing.

**Comment by PVince81** [comment] 2015-10-26 11:58
Reading the rfc: https://www.ietf.org/rfc/rfc4331.txt regarding the "quota-available-bytes" attribute:
```
If a resource has no quota enforced or unlimited storage ("infinite
   limits"), the server MAY choose not to return this property (404 Not
   Found response in Multi-Status), although this specification
   RECOMMENDS that servers return some appropriate value (e.g., the
   amount of free disk space).  A client cannot entirely assume that
   there is no quota enforced on a resource that does not have this
   property, but might as well act as if there is no quota.
```

@DeepDiver1975 do we want to go this route and discard that propery when quota is unlimited ?

CC @dragotin @guruz as the client would need to be adjusted as well.
CC @rperezb not sure if changing this response would affect mobile as well

**Comment by gig13** [comment] 2015-11-06 16:02
@PVince81 
Any updates? Trying to communicate back appropriately a potential timeline.

**Comment by PVince81** [comment] 2015-11-06 16:12
We still need to decide the way to go.

After re-reading the ticket I have identified many points of confusion.

@MTRichards mentions upload limit, I think this ticket has nothing to do with upload limit on the "upload button". I think we're talking about the personal page.

Let's make some screenshots to illustrate.

**Comment by gig13** [comment] 2015-11-06 16:19
@PVince81 
Yes we are talking about the Personal Page and any limits displayed in the desktop sync client (and I guess mobile as well).

**Comment by PVince81** [comment] 2015-11-06 16:22
Tested on 8.1.4.
My data folder is on a partition that only has 1 GB. So whenever you see 1 GB it is the exact disk space, not the quota.

Here we go:
#### Without quota set (unlimited)
##### Personal page
![Uploading noquota-perso.png…]()
##### Desktop client 2.0.2
![noquota-desktopclient](https://cloud.githubusercontent.com/assets/277525/11001985/77a10f9e-84aa-11e5-88cb-0528c4599239.png)

#### With quota set
Here I set the user's quota to 128 MB.
##### Personal page
![quota-perso](https://cloud.githubusercontent.com/assets/277525/11002025/a1a1bf14-84aa-11e5-8b84-c94e8792ae00.png)
##### Desktop client 2.0.2
![quota-desktopclient](https://cloud.githubusercontent.com/assets/277525/11002035/b75c76aa-84aa-11e5-89c4-5fbfc90abda1.png)

Ok, good thing I double checked. There is no situation where we show the text "Unlimited".
We always show whatever is on disk.

So the requirement here is: whenever no quota is set for a user, show the text "Unlimited" on both the web UI and desktop client. @gig13 is that correct ?

In that case my proposal https://github.com/owncloud/core/issues/19988#issuecomment-151111362 still applies.

**Comment by gig13** [comment] 2015-11-06 16:23
> So the requirement here is: whenever no quota is set for a user, show the text "Unlimited" on both the web UI and desktop client. @gig13 is that correct ?

Yes sir.

**Comment by PVince81** [comment] 2015-11-06 16:25
@MTRichards @cmonteroluque in the light of the mighty screenshots, do we agree on this enhancement ?
This will need coordination to provide the same behavior in the clients.

Note: I don't think we should provide an extra option for display (too many options aren't good in general), so this would rather be a change of behavior, not an addition.

CC @jancborchardt

**Comment by PVince81** [comment] 2015-11-06 16:38
Whichever the solution is, it is likely that it will only be done in future versions of ownCloud as an enhancement, so that will be 9.0 or later ddepending on the schedule (and whether we want to do it).
Furthermore all clients will need to be adjusted as well, which means that the changes would also only be in the next versions of every client.

That is, if we agree to go this route.

**Comment by guruz** [comment] 2015-11-06 16:50
I remember there was an issue somewhere mentioning magic values (like -2, -3) for quota (in WebDAV) which mean "Unlimited" or similar.. ? I don't find it now..


Semi-Related issue in client: https://github.com/owncloud/client/issues/3652

**Comment by jancborchardt** [comment] 2015-11-09 12:11
I don’t think having this option is a good idea. Several reasons:
* it’s an option for really quite a small thing where we should much rather decide. And we did do so for showing it in GB/MB.
* what’s the issue with just showing the exact space? Showing the exact space is precise, and people know exactly how much is left.
* »unlimited« does not exist. Just the other week Microsoft removed their unlimited plans, so we shouldn’t start giving people the wrong idea.
* what do we display in the quota bar? Nothing at all? Again, unlimited doesn’t exist so it’s better to state the truth here.

**Comment by guruz** [comment] 2015-11-09 14:09
(I found the client issue I meant.. it is https://github.com/owncloud/client/issues/3940 by @icewind1991 @ogoffart  )

**Comment by icewind1991** [comment] 2015-11-09 15:21
Note that we have 2 different unlimited here: 

- "unlimited" quota, meaning no limit except phyisical ones (hdd space)
- "unlimited" free space on the storage backend (object stores, etc)

Both should be concidered seperatly since one is much more "unlimited" than the other

> what do we display in the quota bar?

For "unlimited" free space:

![unlimited quota](http://i.imgur.com/bJXLOZ3.jpg)

Is what I get currently, the sync client (master, see owncloud/client#3940) says nothing about available space, only used space showing no bar.

**Comment by icewind1991** [comment] 2015-11-09 15:24
Maybe is makes most sense to rename "unlimited" quota to "no quota" since that seems closer to what it means

**Comment by icewind1991** [comment] 2015-11-09 15:25
Since any quota set for a user can only lower the free space we report for the user

**Comment by cmonteroluque** [comment] 2015-11-10 10:00
@icewind1991 I was thinking the same thing as I read through the issue. No quota gets the point across better in my opinion

**Comment by gig13** [comment] 2015-11-18 20:05
@MTRichards 
Has this been targeted for any release mlestone?

**Comment by PVince81** [comment] 2015-11-19 08:57
@icewind1991 how to reproduce the "unlimited" case with the question mark ? In my environment it always shows some value.

**Comment by icewind1991** [comment] 2015-11-20 13:14
You need to use a storage for `/user/files` that has unlimited/unkown free space

Easiest way to test would be to change the return value of `free_space` for the local backend to -2

**Comment by bboule** [comment] 2015-12-22 15:15
@PVince81 @MTRichards Thoughts?  I had added a milestone but it looks unassigned to anyone how shall we proceed?

**Comment by PVince81** [comment] 2015-12-22 15:25
It is still not clear what exactly should be done.
Is there a final decision which approach we want to implement ?

I need to take some time to understand the thread, it is very confusing due to the many different possible combinations of scenarios and different client behaviors.

@icewind1991 do I understand it correctly that in the case of "unlimited (no quota)" the value will be -1 and in the case of "unlimited (free space unknown/unavailble)" the value will be -2 ?
Is that value exposed as is to the clients ?

**Comment by MTRichards** [comment] 2015-12-22 15:26
@cmonteroluque Question is one of capacity. Do we have capacity?

I would say unlimited quota, rather than no quota. It is better grammar:
 You have used 176 MB of the available unlimited quota.
or
 176MB of the available unlimited quota.

This will work in both desktop and server.

**Comment by PVince81** [comment] 2015-12-22 15:30
So at least 4 scenarios: (on the top of my head, not tested)
1) Storage does not report free disk space, no quota set => reports as unknown
2) Storage does not report free disk space, quota set to 100 MB => reports as 100 MB
3) Storage reports free disk space, no quota set => so far the actual free disk space is reported. So if the HDD has 100 GB free, OC will report 100 GB free
4) Storage reports free disk space, quota is set to 100MB: => report as 100 MB

From the comments I had the feeling that there were more combinations ? Or just these 4 ?

Do I understand it well that this request is to cover case 3), admins not wanting users to know the actual free disk space but want "no quota" be displayed instead ?

**Comment by icewind1991** [comment] 2015-12-24 16:05
@icewind1991 do I understand it correctly that in the case of "unlimited (no quota)" the value will be -1 and in the case of "unlimited (free space unknown/unavailble)" the value will be -2 ?
Is that value exposed as is to the clients ?

Correct and yes, clients handle it correct since 2.1 iirc

**Comment by cmonteroluque** [comment] 2015-12-28 11:51
@PVince81 I think the idea is to report on the quota, that's it. With unlimited quota as the wording, as per @MTRichards. Regarding the question of bandwidth, I am not sure we have it but as this is a blue ticket, we will prioritize this during bug fixing

**Comment by PVince81** [comment] 2016-01-07 09:38
> Do I understand it well that this request is to cover case 3), admins not wanting users to know the actual free disk space but want "no quota" be displayed instead ?

@cmonteroluque @MTRichards ok, so if I understand well the answer to my question above is: yes, never show the actual free disk space but show the text "unlimited quota" instead in all cases.

**Comment by MTRichards** [comment] 2016-01-07 13:45
<MTRICHARDS presses PAUSE.>

Need to investigate the best answer here, so we don't create more blue tickets.

@gig13 please indicate a ticket so I can look into details.

**Comment by gig13** [comment] 2016-01-07 17:35
@MTRichards 
SF 00004022

**Comment by MTRichards** [comment] 2016-01-11 16:02
As said above, the resolution is to implement:
You have used 176 MB of the available unlimited quota. (server side)
and
176MB of the available unlimited quota. (client side)

Need to make this in for 9.0 on the server side as selected.

@dragotin linked in client issue.

**Comment by PVince81** [comment] 2016-01-11 16:19
Okay, this will also need server side changes: whenever a user has "unlimited" set as quota, instead of returning the actual physical free disk space it will have to return -1 instead. This means that from this point the server will never display the actual physical free disk space again.

To clarify, an example:
- main partition has total 100 GB space
- main partition has 20 GB space used and 80 GB free (20 + 80 = 100)
- user "user1" has no quota set in OC
- user "user1" has "7 GB" of files in their OC storage (part of the 20 GB)
- current behavior: UI and Webdav will return the value 80 GB because that's what the partition has available
- after the requested change: UI and Webdav will return the value -1 which will be displayed as "Unlimited quota".

This also means that people using the community edition will not see any free space by default, it will always show the text "Unlimited quota". If they want to see an actual value, they will have to set a quota for all their users (as I did on my own server).

So the required changes are as follows:
- [ ] make Webdav return -1 when no quota is set
- [ ] make desktop client display "Unlimited space" if -1 was received as quota value
- [ ] make mobile client display "Unlimited space" if -1 was received as quota value
- [ ] make web UI display "Unlimited space" if -1 was received as quota value
    - [ ] personal page
    - [ ] files app (the value is stored in a variable, need to make sure upload still works when it's -1)

**Comment by MTRichards** [comment] 2016-01-11 21:49
@PVince81 Thank you.

**Comment by cmonteroluque** [comment] 2016-02-23 17:49
@bboule @MorrisJobke moving to 9.1 unless there's an objection

**Comment by MTRichards** [comment] 2016-02-23 17:55
Objection! Commitment made to customer, and customer rated it as critical for production. They were (I think) committed for 9.0 and 2.2.

@gig13 Correct?

**Comment by gig13** [comment] 2016-02-23 17:59
Correct -- at least two customers

**Comment by PVince81** [comment] 2016-02-23 18:31
So do we all agree on this change of behavior as described in https://github.com/owncloud/core/issues/19988#issuecomment-170602297 ? @MTRichards @gig13

**Comment by cmonteroluque** [comment] 2016-02-23 18:41
yes, we're going to have to pick a behavior and run with it. So, as far as I'm concerned we can't argue about behavior any longer. Take one and implement

**Comment by PVince81** [comment] 2016-02-23 18:48
Ok, I'll give this a try and see how it behaves

**Comment by PVince81** [comment] 2016-02-24 09:22
From the RFC:
```
   If a resource has no quota enforced or unlimited storage ("infinite
   limits"), the server MAY choose not to return this property (404 Not
   Found response in Multi-Status), although this specification
   RECOMMENDS that servers return some appropriate value (e.g., the
   amount of free disk space).  A client cannot entirely assume that
   there is no quota enforced on a resource that does not have this
   property, but might as well act as if there is no quota.
```

@dragotin @jesmrec which way do you prefer ?
Returning a negative value doesn't match the standard.

I played around with Sabre and I can either make the "quota-available-bytes" property disappear from the response when quota is unlimited, or make it an empty element.

**Comment by PVince81** [comment] 2016-02-24 09:31
I also noticed that if I return "-3" (the internal server value for "UNLIMITED STORAGE"), the desktop client shows "123 bytes used" without a max value.

But returning a negative value isn't very standard-compliant.

Note that -1 would be "SPACE_NOT_COMPUTER" when the space hasn't been computed yet, so we might not want to reuse that one. https://github.com/owncloud/core/blob/v8.2.2/lib/public/files/fileinfo.php#L47

**Comment by rperezb** [comment] 2016-02-24 09:33
@PVince81 do you have a pr/branch for mobile apps to test what happens?
FTM, we are not taking advantage of this property, however, we have to make sure that this does not affect the parser

**Comment by PVince81** [comment] 2016-02-24 09:35
I will push a branch soon. Am currently testing for potential side effects in other parts of the server.

**Comment by PVince81** [comment] 2016-02-24 09:40
@rperezb here is a branch that can be used for testing: https://github.com/owncloud/core/pull/22613

**Comment by PVince81** [comment] 2016-02-25 09:30
Any update on testing @rperezb @jesmrec @dragotin @guruz ?

We need to know in what format the clients want to have the information.
Currently this PR https://github.com/owncloud/core/pull/22613 returns "-3" for "quota-available-bytes" when no quota is set. (-3 is the value for "unlimited" on the server).

**Comment by PVince81** [comment] 2016-02-25 12:48
@MTRichards @gig13 is it correct that the user story for this is "admin wants to prevent users to find out how much actual free disk space is available when they have unlimited quota" ?

**Comment by PVince81** [comment] 2016-02-25 12:59
I'm asking because I'm trying to find a compromise to not have a change of behavior, knowing that adding a config switch is not acceptable. One idea could be to show both "Unlimited" and the actual free storage. But if the story is about hiding the actual free storage, then this is not acceptable.

**Comment by gig13** [comment] 2016-02-25 13:12
@PVince81 Yes, consider the service provider viewpoint. They say that there is "unlimited" storage, then the user should not see any limit and is oblivious of actual available storage on the back end.

**Comment by PVince81** [comment] 2016-02-25 13:20
Okay, that makes sense.

So we need to reuse the "quota-available-bytes" and not introduce a new property, to prevent people finding out about the free space over webdav.

@ogoffart just told me that the desktop client 2.1.1 will accept the -3 value as per the PR.
Older clients would show "125 MB used of 125 MB" in such situation (to be confirmed). Would that be acceptable ?

Note that we cannot easily change the older client versions to comply with this behavior change in 9.0.

**Comment by ogoffart** [comment] 2016-02-25 14:19
Clients from 2.1.0 will accept -3
(was fixed for https://github.com/owncloud/client/issues/3940 )

**Comment by rperezb** [comment] 2016-02-25 14:43
I have checked this with both android and iOS clients, working fine.
FTM, we are not taking into account the quota value.
@davivel or @javiergonzper in case I missed anything

**Comment by davivel** [comment] 2016-02-25 15:36
Is there any other "special value"? Any other negative value with a specific meaning? Why -3 and not -1 or -2? Just curiosity.

**Comment by PVince81** [comment] 2016-02-25 15:39
@davivel see https://github.com/owncloud/core/blob/v8.2.2/lib/public/files/fileinfo.php#L47 as mentionned above
- -1: pending / not computed yet (for example when ext storage has been mounted, folder sizes need scanning)
- -2: unknown / storage doesn't tell (ex: shared hosters or ext storages that have no free_space API)
- -3: unlimited

So does it mean we can move forward and merge that PR ?

**Comment by davivel** [comment] 2016-02-26 16:42
Thanks!

> I have checked this with both android and iOS clients, working fine.

I'd say that's a :+1:  for mobile :)

**Comment by PVince81** [comment] 2016-02-29 10:21
The 1.8.4 client shows "X bytes of X bytes", I hope it's ok...
![oldclient-negative-quota](https://cloud.githubusercontent.com/assets/277525/13391747/6fbfccda-ded6-11e5-9ed7-eb39dae78571.png)

**Comment by PVince81** [comment] 2016-03-02 15:46
This was implemented in 9.0 RC1: https://github.com/owncloud/core/issues/22613

If you didn't follow the discussion, please note that there is no config switch as we were against that.

The behavior is that now if someone has unlimited quota the web UI will show "Unlimited" in the personal page and the desktop client (2.1+) will not display any "total size" value.

**Closed by PVince81** 2016-03-02 15:46 UTC
Labels: blue-ticket, enhancement, feature:quota, in progress

**Comment by PVince81** [comment] 2016-03-07 09:30
Regression, fed sharing needs to be adjusted as well as it uses Webdav too: https://github.com/owncloud/core/issues/22882

**Comment by PVince81** [comment] 2016-03-07 10:19
Forgot to ping you @jospoortvliet about this behavior change. See https://github.com/owncloud/core/issues/19988#issuecomment-191294819

**Comment by PVince81** [comment] 2016-03-24 10:20
More regressions: when connecting from an older OC instance to 9.0.0 with fed share, it doesn't understand the "-3" as being "unlimited" and thinks there is no space left :frowning:

**Comment by PVince81** [comment] 2016-03-24 10:58
Raised here https://github.com/owncloud/core/issues/23547

**Comment by MTRichards** [comment] 2016-03-24 12:42
Since this is going to get worse over time as we expand federated sharing capabilities (the oC instance interoperation with Federated sharing) is there a way to introduce either a versioned API, or a "I am oC 9" mechanism when connecting and federating? Probably better that it is not static because static assumes instances wouldn't upgrade, but something to help avoid the issue?

**Comment by PVince81** [comment] 2016-03-24 13:20
Good point, raised here to discuss: https://github.com/owncloud/core/issues/23554

Webdav currently doesn't have API version numbers.
