### ISSUE TITLE
Server do not support X-OC-MTime

### ISSUE THREAD

**Issue by Xilentura** [owncloud/core#22268] opened 2016-02-10 10:50 UTC
**Configuration**
- FreeBSD 10.2 (Latest stable version)
- Owncloud 8.2.2 (Latest stable version)
- Apache
- Client: 2.1.0 (Latest stable version)
- OS for Clients: ArchLinux ( 2.1.0, ownCloud client based on mirall)
- OS for Clients: MacOSX and Windows (Client 2.1.0)
- Owncloud shares are mounted via SMB/CIFS

**Problem**
1. If I want to upload several files, the client shows the correct upload files and sizes. Status: Uploading
2. Some files are uploaded correctly
3. Some files are not uploaded (Response: `Server does not support X-OC-MTime`)
4. The upload is canceled
5. Already uploaded files were downloaded from server with error: `Server does not support X-OC-MTime`
6. Sync protocol shows at every downloaded file: `Downloaded, renamed conflicting file`
7. Back to step 1 till all files are uploaded correctly

File names are correct without special chars or fancy freaky names.

**Comment by RealRancor** [comment] 2016-02-10 11:43
Seems two of you guys have now reported this at different places:

https://github.com/owncloud/client/issues/4452

**Comment by nickvergessen** [comment] 2016-02-10 11:50
2.1.1 has been released yesterday, mind testing if that helps?
https://owncloud.org/install/#install-clients

**Comment by nickvergessen** [comment] 2016-02-10 11:57
Okay, it was released just some minutes ago:
https://mailman.owncloud.org/pipermail/devel/2016-February/002040.html

But the "retest please" stands

**Comment by Xilentura** [comment] 2016-02-10 12:31
I will check the new client - stay tuned!

**Comment by Pisoko** [comment] 2016-02-10 12:34
> I will check the new client - stay tuned!

I will test the new client, too.

**Comment by dragotin** [comment] 2016-02-10 14:09
The client show the error message "Server does not support X-OC-MTime" if the HTTP reply does not have a header `X-OC-MTime` header with the value `accepted`. Make sure that the headers are not removed out of the HTTP traffic.

**Comment by Xilentura** [comment] 2016-02-10 14:15
@dragotin Thanks for your fast reply! Is it important to mention I have a secure HTTPS connection? How can I influence the header messages or filtering of the traffic? Is there a config file somewhere?

**Comment by dragotin** [comment] 2016-02-10 14:29
No https is fine, different layer. It should not happen that the header is filtered, that only happens with aggressive proxies or load balancers or such. Not in a normal installation. 

You should try to take a look at the HTTP traffic directly, best using mitmproxy or such, to see if the request/replies are complete.

**Comment by RealRancor** [comment] 2016-02-10 14:32
@Xilentura Thats not related to the HTTPS connection. Headers could be manipulated / removed by non-standard webserver configs or by security modules like mod_security.

**Comment by Xilentura** [comment] 2016-02-10 14:44
@dragotin and @RealRancor Thanks again! I will check the traffic, the webserver config and the load balancer as well and will reply soon!

**Comment by Xilentura** [comment] 2016-02-10 16:33
@dragotin I checked the configuration and I neither have a load balancer nor an aggressive proxie. Are there any other possibilities, why this error occurs? I don't want to trifle with user data.

**Comment by RealRancor** [comment] 2016-02-10 16:51
> Headers could be manipulated / removed by non-standard webserver configs or by security modules like mod_security.

https://github.com/owncloud/core/issues/22268#issuecomment-182398401

**Comment by Xilentura** [comment] 2016-02-10 17:51
@RealRancor Sorry I didn't want to offend you - I will try this as well and just replied to the other post to move on with this topic.

**Comment by Xilentura** [comment] 2016-02-13 09:42
Okay same problem with the new client 2.1.1.

**Comment by RealRancor** [comment] 2016-02-13 11:07
@Xilentura Thats an issue somewhere in your webserver setup / environment so updating the client won't help.

**Comment by blizzz** [comment] 2016-03-01 17:10
Closing, because 

> @Xilentura Thats very likely an issue somewhere in your webserver setup / environment so updating the client won't help.

**Closed by blizzz** 2016-03-01 17:10 UTC
Labels: needs info

**Comment by abrahamsthmicro** [comment] 2016-04-27 08:09
Hi, I have the same problem "server does not support x-oc-mtime" when uploading files to external dropbox account.
Sorry I am new to this. And I have checked the forum and github and all posts leads me to here.
But why this is close? Any solutions? 
Hi, @Xilentura , can you give me some directions or examples about the "somewhere" you have mentioned?
> @Xilentura Thats very likely an issue somewhere in your webserver setup / environment so updating the client won't help.

**Comment by Xilentura** [comment] 2016-04-27 09:39
@abrahamsthmicro 

> But why this is close? Any solutions? 

My settings changend to:

- FreeBSD 10.3 (Latest stable version)
- Owncloud 9.0.1 (Latest stable version)
- Apache 2.4
- Clients: Latest stable versions

Problems are gone even under FreeBSD.

**Comment by RealRancor** [comment] 2016-04-27 11:01
@abrahamsthmicro 
> But why this is close? Any solutions? 

Because this is an environmental issue where your environment is stripping off/removing the mentioned header. If this is the case there can't be a solution in here as  this issue tracker is used for bugreporting within ownCloud, not for giving support for webservers issues / configurations.

**Comment by corvancrowing** [comment] 2016-12-29 16:02
But at least you could provide information on how to configure webservers, that they are working as you expect them to

**Comment by CommonFailure** [comment] 2017-03-12 16:23
Hi all,

I have the same issue now and I can confirm there is no proxy or any interrupting security device between me and my own ownloud installation.

My environment:
Ubuntu 16.04.2 LTS
Apache 2.4.18
owncloud 9.1.4
owncloud Client 2.3.0

Can you please tell us on how to make sure the header is not removed?

Thanks!

**Comment by kdslkdsaldsal** [comment] 2017-03-14 07:26
> But at least you could provide information on how to configure webservers, that they are working as you expect them to

IMHO something like this can't be documented in the scope of a web application. There are too many environments, webservers and modules out there which could be responsible for that. It is just overkill and not maintainable (even if only Apache is documented) to document this.

> Can you please tell us on how to make sure the header is not removed?

Personally i would suggest to get some help from some of the apache support options at https://httpd.apache.org/support.html
