### ISSUE TITLE
Encrypt File and Folder Names

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16722] opened 2015-06-03 13:10 UTC
As an ownCloud admin, I want to ensure that all file names and folders names are also encrypted when the encryption app is enabled, so that I do not expose sensitive information contained in file and folder names to admins on the server.

Acceptance Criteria:
•	File and Folder names are encrypted and cannot be viewed by an admin browsing the server files
•	Encryption of file names / folder names hides the names
•	Clearly paths can't be encrypted or a posix file system can't be used
•	The object store implementation currently provides a similar capability that could be a similar related interface
•	The meta data in the database is not to be encrypted at this time
•	If encryption is on, filenames and folder names are encrypted from that point forward
•	Migration will be a real challenge, so an upgrade needs to 1) provide a facility to migrate existing users to encrypted filenames 2) a capability to turn off the encryption and migrate

**Comment by LukasReschke** [comment] 2015-06-03 13:16
Duplicate of https://github.com/owncloud/core/issues/11814 which is still open, then also of https://github.com/owncloud/core/issues/3685 which is closed

**Comment by LukasReschke** [comment] 2015-06-03 13:19
Will also be not really reliable unless we really come up with an actual threat model. As in: Against what are we defending? Against who do we want to hide data?

If it is "an external storage provider" this is fine, if it is "the ownCloud admin or sysadmin" then we honestly need to come up with a documented expected behaviour. There will still be a ton of other metadata in the ownCloud instance stored anyways – also on the FS.

**Comment by MTRichards** [comment] 2015-06-03 18:44
@LukasReschke Good discussion top have here. Thanks for linking the two issues together, I could not find the other older encrypt filename issues.

There are two sides to this, the attack vector and the policy check box requirement. 

The attack vector is, for example, a backup admin who can find information about what is contained in a file after taking a backupof ownCloud and perusing the backup, or searching, because the filename is front and center. This is the worry, the file name divulges sensitive info "Matt will be fired.doc" as an example. 

The policy requirement is a check box, that the filename and folder are in fact encrypted so that even this small risk (who names files that way anyway?) are avoided by the company, and the company policy requires it. Whether it is real or not, it is a perception that it is important. 

Note: this is not currently prioritized, so not super high priority.

**Comment by RealRancor** [comment] 2015-06-04 11:14
Hi,

> The attack vector is, for example, a backup admin who can find information about what is contained in a file after taking a backupof ownCloud and perusing the backup, or searching, because the filename is front and center.

Is this really an attack vector? The backup of oC also consist of the database where the original filename probably needs to be saved as a metadata?

**Closed** 2016-03-01 21:58 UTC
Labels: app:encryption, enhancement - proposed
