### ISSUE TITLE
Self-mounting an OC site via an ownCloud external storage cripples the site

### ISSUE THREAD

**Issue by ops-cc** [owncloud/core#23906] opened 2016-04-11 10:25 UTC
### Steps to reproduce
1. Login to an OC instance and access Personal settings
2. Create an external share of type ownCloud using as URL the OC host name.

Example: 
An OC site accessed as owncloud.site -> create OC external storage with owncloud.site as URL.

Note: this happens on a haproxy + keepalived + web servers cluster installation, not tested on a standard single server.
### Expected behaviour

An error message of the type "Cannot mount myself."
### Actual behaviour

The php processes on the back-end servers explode (reach pm.max_children) + MySQL max connections reached via an infinite http requests loop and the OC service get crippled.
### Server configuration

**Operating system**:
Debian 7

**Web server:**
Nginx 1.2.1

**Database:**
MySQL 5.5.40

**PHP version:**
php5-fpm 5.4.39

**ownCloud version:** (see ownCloud admin page)
8.0.3

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
This is a haproxy (2 head nodes) + keepalived (IP floating address) + cluster of 3 web servers + 1 MySQL server
OC code installed from sources.

**The content of config/config.php:**

Note: masked some data.

<?php
$CONFIG = array (
  'instanceid' => '525d0b8a7de4c',
  'datadirectory' => '/srv/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'oc1.int.site',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxx',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'xxxxxxxxxxx',
  'log_type' => 'owncloud',
  'loglevel' => '1',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'owncloud.site1',
    1 => 'owncloud.site2',
    2 => 'ow01.oc.int.site',
    3 => 'ow02.oc.int.site',
    4 => 'ow03.oc.int.site',
    5 => 'ha-site1.oc.int.site',
    6 => 'ha-site2.oc.int.site',
  ),
  'ldapIgnoreNamingRules' => false,
  'share_folder' => '/Shared',
  'mail_from_address' => 'operator',
  'mail_domain' => 'xxxxxxxxxx',
  'logfile' => '/var/log/owncloud/owncloud.log',
  'forcessl' => false,
  'check_for_working_webdav' => true,
  'cron_log' => true,
  'log_rotate_size' => 1048576000,
  'appstoreenabled' => true,
  'enable_previews' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
owncloud, sftp, cifs, webdav

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
OpenLDAP
#### LDAP configuration (delete this part if not used)

Not relevant.
#### PHP error log

php-fpm started to report "execution timed out" and started to crash:
php5-fpm[19269] general protection ip:67eea5 sp:7ffc97957bf0 error:0 in php5-fpm[400000+75a000]
php5-fpm[19268]: segfault at 18 ip 000000000067ed66 sp 00007ffc97957be0 error 4 in php5-fpm[400000+75a000]
#### ownCloud log (data/owncloud.log)

OC logs started to report MySQL access errors:
"message":"An exception occured in driver: SQLSTATE[08004] [1040] Too many connections","level":4
### Bug and fix description

We scanned users' mount.json files and found 2 with an external OC storage defined with our OC instance hostname as URL.
Once removed the mount.json files and restarted the php-fpm processes all went back to normal.
We tried to redefine such external storage which immediately triggered the infinite loop(s): php-fpm processes spawned to the pm.max_children limit + MySQL connection overload.
### Suggestion

Check the entered URL in the OC external storage definition and prevent the self-mount.
Might be already implemented in a more recent version of OC.

Cheers!

**Comment by Xenopathic** [comment] 2016-04-11 11:38
Ah, the inception mount. As noted at #23330, the problem seems to be with file locking

**Comment by ops-cc** [comment] 2016-04-11 12:34
In my case no error reported with file locking (I checked the OC logs). Only php processes spawned to the pm.max_children value.

**Comment by PVince81** [comment] 2017-01-13 15:08
closing as duplicate of https://github.com/owncloud/core/issues/23330

**Closed by PVince81** 2017-01-13 15:08 UTC
Labels: app:files_external, bug
