### ISSUE TITLE
Username is case sensitive for password reset email

### ISSUE THREAD

**Issue by ckowarzik** [owncloud/core#24102] opened 2016-04-19 16:05 UTC
### Steps to reproduce
1. Create User "User1"
2. Weblogin: Username is not case sensitive. "User1" or "user1" will work!
3. When you want to do a password reset by email, the username has to be case sensitive.
If you type the username "user1" you get the message: "Could not send reset email because there is no email address for this username. Please contact your administrator."
If you type "User1" it will work fine.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
updated from 8.2.2

**Where did you install ownCloud from:**
rpm repository at http://download.owncloud.org/download/repositories/stable/CentOS_7

**Comment by MorrisJobke** [comment] 2016-04-20 20:38
Duplicate of https://github.com/owncloud/core/issues/15433

**Closed by MorrisJobke** 2016-04-20 20:38 UTC
