### ISSUE TITLE
Properly handle uploads of files ending in ".part"

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#15788] opened 2015-04-21 16:44 UTC
* Upload a file named `a.part` via webdav
* No error message - just a success message is send back.

### Expected

Having this file in the file list

### Actual

File is gone

This cause data loss!

cc @PVince81 @DeepDiver1975

**Comment by PVince81** [comment] 2015-04-21 16:47
Duplicate of https://github.com/owncloud/core/issues/7496

**Closed by PVince81** 2015-04-21 16:47 UTC
Labels: bug, sev2-high
