### ISSUE TITLE
remove app icon from app menue without deactivate the app or group-permissions

### ISSUE THREAD

**Issue by stefkey** [owncloud/core#20822] opened 2015-11-29 22:32 UTC
Hi,

where can I control the icons from the app-menue?
I would like one oder two icons remove from the liste without deactivate the app.
In styles.css the apps are not width id for display: none :-(

Thanks a lot!

**Comment by karlitschek** [comment] 2015-11-30 01:40
thanks for your question. this is not a bug and not a feature request. So I'm closing this. I recommend to ask your question on the developer mailinglist or in the forum. thanks

**Closed by karlitschek** 2015-11-30 01:40 UTC
