### ISSUE TITLE
Accessibility is worse in version 8.2.0

### ISSUE THREAD

**Issue by jmdaweb** [owncloud/core#20312] opened 2015-11-04 20:20 UTC
Hello.
I have installed Owncloud 8.2.0, and I have noticed that it has several accessibility problems for screen reader users. There are many dynamic combo boxes, and most checkboxes have disappeared for blind users. We can only see them disabling the style in the browser.
In previous versions, at least the checkboxes could be used. Can you fix these bugs so everyone can use this cloud? Accessibility is very important and must be taken into account!

**Comment by karlitschek** [comment] 2015-11-04 20:31
@jancborchardt What do you think?

**Comment by MorrisJobke** [comment] 2015-11-05 08:19
Duplicate of https://github.com/owncloud/core/issues/19898

**Closed by MorrisJobke** 2015-11-05 08:19 UTC
Labels: bug
