### ISSUE TITLE
Undefined index error in Files scan

### ISSUE THREAD

**Issue by fjcuberos** [owncloud/core#29128] opened 2017-09-30 11:00 UTC
### Steps to reproduce
sudo -u www-data php occ files:scan local_user_name

### Expected behaviour
Normal scan of files and chache update

### Actual behaviour
Starting scan for user 1 out of 1 (local_user_name)

Exception during scan: Undefined index: size
#0 /var/www/html/owncloud/lib/private/Files/Cache/Scanner.php(421): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/var/www/html/o...', 421, Array)
#1 /var/www/html/owncloud/lib/private/Files/Cache/Scanner.php(382): OC\Files\Cache\Scanner->handleChildren('contacts/import...', true, 3, '166', true, 442)
#2 /var/www/html/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('contacts/import...', true, 3, '166', true)
#3 /var/www/html/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('contacts', true, 3, '165', true)
#4 /var/www/html/owncloud/lib/private/Files/Cache/Scanner.php(316): OC\Files\Cache\Scanner->scanChildren('', true, 3, 1, true)
#5 /var/www/html/owncloud/lib/private/Files/Utils/Scanner.php(235): OC\Files\Cache\Scanner->scan('', true, 3)
#6 /var/www/html/owncloud/apps/files/lib/Command/Scan.php(159): OC\Files\Utils\Scanner->scan('/cloudgrupoidad...')
#7 /var/www/html/owncloud/apps/files/lib/Command/Scan.php(228): OCA\Files\Command\Scan->scanFiles('cloudgrupoidadm...', '/cloudgrupoidad...', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#8 /var/www/html/owncloud/lib/composer/symfony/console/Command/Command.php(262): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/owncloud/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(826): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/owncloud/lib/composer/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/owncloud/lib/private/Console/Application.php(160): Symfony\Component\Console\Application->run(NULL, NULL)
#14 /var/www/html/owncloud/console.php(106): OC\Console\Application->run()
#15 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#16 {main}

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 3730    | 17764 | 00:10:13     |
+---------+-------+--------------+

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
apache
**Database:**
MSQL 5.5.57
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
Same behaviour in 10.0.2 and 10.0.3

**Updated from an older ownCloud or fresh install:**
Update from 9.1.2 to 10.0.2 and then to 10.0.3

**Where did you install ownCloud from:**
From https://download.owncloud.org/community/owncloud-10.0.3.tar.bz2

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**
 "config": {
        "instanceid": "ocb08946ac0f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.mydomain.es"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/owncloud.mydomain.es",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "cloudmydomain",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 3,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto"
    },

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chromer Versión 61.0.3163.100 (Build oficial) (64 bits)
**Operating system:**
W10
#### Web server error log

[Sat Sep 30 00:59:39.725477 2017] [:error] [pid 15218] [client 136.243.13.84:59925] script
 '/var/www/html/wp-login.php' not found or unable to stat
[Sat Sep 30 02:00:47.472865 2017] [:error] [pid 15750] [client 136.243.13.84:44892] script
 '/var/www/html/wp-login.php' not found or unable to stat
[Sat Sep 30 07:11:17.980340 2017] [:error] [pid 15750] [client 91.196.50.33:53873] script
'/var/www/html/testproxy.php' not found or unable to stat
[Sat Sep 30 10:52:19.125785 2017] [mpm_prefork:notice] [pid 18781] AH00169: caught SIGTERM
, shutting down
[Sat Sep 30 10:53:09.116770 2017] [mpm_prefork:notice] [pid 23997] AH00163: Apache/2.4.7 (
Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Sat Sep 30 10:53:09.116823 2017] [core:notice] [pid 23997] AH00094: Command line: '/usr/s
bin/apache2'
[Sat Sep 30 10:53:58.926078 2017] [mpm_prefork:notice] [pid 23997] AH00169: caught SIGTERM
, shutting down
[Sat Sep 30 12:23:27.155260 2017] [mpm_prefork:notice] [pid 24692] AH00163: Apache/2.4.7 (
Ubuntu) OpenSSL/1.0.1f configured -- resuming normal operations
[Sat Sep 30 12:23:27.155305 2017] [core:notice] [pid 24692] AH00094: Command line: '/usr/s
bin/apache2'
[Sat Sep 30 12:32:23.593359 2017] [authz_core:error] [pid 24727] [client 83.32.128.245:477
4] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstes
t.txt
[Sat Sep 30 12:43:03.192720 2017] [authz_core:error] [pid 24708] [client 83.32.128.245:488
1] AH01630: client denied by server configuration: /var/www/html/owncloud/data/htaccesstes
t.txt

#### ownCloud log (data/owncloud.log)
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:16+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:16+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:17+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#416"}
{"reqId":"Sk4sdDeRt3mJPnLKr4ye","level":3,"time":"2017-09-30T08:16:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: size at \/var\/www\/html\/owncloud\/lib\/private\/Files\/Cache\/Scanner.php#419"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment] 2017-09-30 11:15
This is either an issue with wrong permissions (https://github.com/owncloud/core/issues/28031#issuecomment-305234240) or a duplicate of https://github.com/owncloud/core/issues/28181 so closing here for now.

**Closed by kdslkdsaldsal** 2017-09-30 11:15 UTC
