### ISSUE TITLE
Sharing: Problem creating public links (Uncaught TypeError: this.$el.find(...).select2 is not a function)

### ISSUE THREAD

**Issue by woeterman94** [owncloud/core#31850] opened 2018-06-21 08:15 UTC
### Steps to reproduce
1. Click on the share icon of a folder or file
2. Head to public links and click create public link
3. A dialog shows up but nothing happens. In the dev console of Google Chrome I get the error message:

```
Uncaught TypeError: this.$el.find(...).select2 is not a function
    at child._afterRender (sharedialogmailview.js?v=9fcfb4dc628a64773dff191ce16cda01:197)
    at child.<anonymous> (sharedialogmailview.js?v=9fcfb4dc628a64773dff191ce16cda01:62)
    at executeBound (underscore.js?v=9fcfb4dc628a64773dff191ce16cda01:701)
    at child.bound [as render] (underscore.js?v=9fcfb4dc628a64773dff191ce16cda01:733)
    at child.render (sharedialoglinkshareview.js?v=9fcfb4dc628a64773dff191ce16cda01:270)
    at Object.adjustDialog (sharedialoglinkshareview.js?v=9fcfb4dc628a64773dff191ce16cda01:367)
    at Object.<anonymous> (jquery.min.js?v=9fcfb4dc628a64773dff191ce16cda01:sourcemap:2)
    at j (jquery.min.js?v=9fcfb4dc628a64773dff191ce16cda01:sourcemap:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=9fcfb4dc628a64773dff191ce16cda01:sourcemap:2)
    at Object.<anonymous> (jquery.min.js?v=9fcfb4dc628a64773dff191ce16cda01:sourcemap:2)
```

![image](https://user-images.githubusercontent.com/5755057/41706559-67ab3cec-753c-11e8-81bf-29bf03fe4f86.png)
(When I click 'share' the error reappears) 

### Expected behaviour
There should be a way to create a public link / url and to set the expiry date, password etc...

### Actual behaviour
Nothing. Unable to create a shareable link

![image](https://user-images.githubusercontent.com/5755057/41706451-2ec87138-753c-11e8-8752-9b8738eabaff.png)

### Server configuration
Hosting owncloud in shared hosting

**PHP version:*ea-php72*

**ownCloud version:*ownCloud 10.0.8 (stable) * 

**Updated from an older ownCloud or fresh install:*updated*

**Where did you install ownCloud from:*used the updater in the web interface*

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

https://gist.github.com/woeterman94/08b501789a012b1e5dfcaa74a58f6c56
```

**List of activated apps:*Marked, Share Files (0.10.1) *

**Are you using external storage, if yes which one:*No* local/smb/sftp/...

**Are you using encryption:*No* 

**Are you using an external user-backend, if yes which one:*No* LDAP/ActiveDirectory/Webdav/...

**Comment by ownclouders** [comment] 2018-06-21 08:40
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/31454 (Problems with public shares), https://github.com/owncloud/core/issues/18737 (share link problem), https://github.com/owncloud/core/issues/18251 (Create Links for Shared Files or Folders (not a public share)), https://github.com/owncloud/core/issues/3540 (TypeError on sharing via link), and https://github.com/owncloud/core/issues/16224 (Sharing problem and typecasting if i share a link for public e.g. calendar).

**Comment by PVince81** [comment] 2018-06-21 10:10
duplicate of https://github.com/owncloud/core/issues/31454
see there for a workaround

**Closed by PVince81** 2018-06-21 10:10 UTC
