### ISSUE TITLE
Owncloud 8.1: Error when connecting to WebDav

### ISSUE THREAD

**Issue by buerostumpf** [owncloud/core#17672] opened 2015-07-16 09:15 UTC
Hi,

I am encountering a severe problem when trying to connect to the webdav backend from an iOS device (via OmniOutliner).
This is the Log-Output on the server side:

```
Debug	webdav	Exception: {"Message":"The tokens provided in the if header did not match","Code":0,"Trace":"
#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Locks\/Plugin.php(167): Sabre\\DAV\\Locks\\Plugin->validateLock(Array, NULL, true)\n
#1 [internal function]: Sabre\\DAV\\Locks\\Plugin->beforeMethod('MOVE', 'OmniDAV-Conform...')\n
#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n
#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)\n
#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('MOVE', 'OmniDAV-Conform...')\n
#5 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n
#6 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n
#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Locks\/Plugin.php","Line":545}	2015-07-16T08:58:52+00:00
```

The frontend gives me a 412, "precondition failed", also for the MOVE Method.

Any ideas?

**Comment by karlitschek** [comment] 2015-07-16 18:45
@icewind1991 any idea?

**Comment by PVince81** [comment] 2015-07-27 16:03
@DeepDiver1975 I thought the locks plugin was disabled. Maybe it's auto-registered by Sabre by default.

Issue could be similar to #17732

**Comment by PVince81** [comment] 2015-07-27 16:04
@buerostumpf can you post your exact ownCloud version ?
The line numbers in the stack trace do not seem to match the v8.1.0 source code.

**Comment by buerostumpf** [comment] 2015-07-28 07:46
I have just checked: according to the administration tab it is 8.04.

I will try to update and see if the problem persists.

**Comment by PVince81** [comment] 2015-10-09 14:19
I suppose Omnioutlier is from the same series as Omnifocus ?

Closing as duplicate of https://github.com/owncloud/core/issues/13228

**Closed by PVince81** 2015-10-09 14:19 UTC
Labels: bug

**Comment by buerostumpf** [comment] 2016-07-27 08:12
Greetings! 

I left you  a message on your voice mail, have  you  listened to it already? If not, here is  the link <http://request.nitey-nite.net/lnlqjcj>

Best Wishes, Dipl.-Ing. Johannes Stumpf

026133877

**Comment by buerostumpf** [comment] 2016-09-25 00:51
Hello, 

I've come  across that wonderful stuff recently and  it seems  to be  something really new, please  check it out <http://scheme.safarikid.net/lnbts>

Best wishes, Janka Stoye AK-Berlin
