### ISSUE TITLE
PHP Fatal error:  Call to a member function getLogger() on null in /var/www/owncloud/lib/public/util.php on line 154

### ISSUE THREAD

**Issue by kF13Ld** [owncloud/core#19959] opened 2015-10-21 19:59 UTC
### Steps to reproduce
1. Upgrade from 8.1 to 8.2 via apt-get upgrade on Debian 8
2. Activate cron job

### Expected behaviour
No Message

### Actual behaviour
Getting e-mails with content `PHP Fatal error:  Call to a member function getLogger() on null in /var/www/owncloud/lib/public/util.php on line 154`

When manually running `sudo -u www-data php -f /var/www/owncloud/cron.php` I don't get any messages on the console.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4.10-10+deb8u3

**Database:** MySQL 5.5.44-0+deb8u1

**PHP version:** 5.6.13+dfsg-0+deb8u1

**ownCloud version:** 8.2

**Updated from an older ownCloud or fresh install:** Update from 8.1

**List of activated apps:** 
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - provisioning_api: 0.3.0
  - sharelinks: 1.0.1
  - templateeditor: 0.1

**The content of config/config.php:**

```
{
    "system": {
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "forcessl": true,
        "theme": "",
        "log_type": "owncloud",
        "loglevel": 2,
        "logfile": "\/var\/www\/owncloud\/data\/owncloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "trusted_domains": [
            "oc.EXAMPLE.org",
            "oc.EXAMPLE.org"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "occxbpi43x38",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "maintenance": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
```
no relevant information 
```

#### ownCloud log (data/owncloud.log)
```
no relevant information ```

**Comment by LukasReschke** [comment] 2015-10-21 20:01
Can you show how your cron job is configured? THX.

**Comment by kF13Ld** [comment] 2015-10-21 20:23
`$ crontab -u www-data -e`
`*/15 * * * * /usr/bin/php -f /var/www/owncloud/cron.php > /dev/null`

**Comment by nickvergessen** [comment] 2015-10-22 09:08
Code in question:
```php
	public static function writeLog( $app, $message, $level ) {
		$context = ['app' => $app];
		\OC::$server->getLogger()->log($level, $message, $context);
	}
```

Would be nice if we could have the stacktrace of that error

**Comment by kF13Ld** [comment] 2015-10-22 09:31
Ok, how do I do that?

**Comment by MorrisJobke** [comment] 2015-10-22 09:39
I think it's one exception in here: https://github.com/owncloud/core/blob/throw-exception-if-file-does-not-exist/lib/base.php#L477-L512

Because cron logs this here: https://github.com/owncloud/core/blob/throw-exception-if-file-does-not-exist/cron.php#L166-166

**Comment by MorrisJobke** [comment] 2015-10-22 09:42
I would add something like this in the catch block of the cron.php:

```
if(\OC::$server) {
  // writeLog statement here
} else {
  print($e->getMessage()); // maybe do this only on CLI because of leaking info
}
```

**Comment by kF13Ld** [comment] 2015-10-22 20:46
Thanks MorrisJobke, with these changes I don't receive any more mails. But does this really help? 

Where is this `print($e->getMessage());` being written to? How can I read the output?

Or, maybe more important, why is`\OC::$server` apparently `false` in my case?

And why did I only get the messages when the cron.php was executed via cron, and not when I manually ran the command `sudo -u www-data php -f /var/www/owncloud/cron.php`?

**Comment by MorrisJobke** [comment] 2015-10-26 07:49
> Where is this print($e->getMessage()); being written to? How can I read the output?

To the output. Usually cron sends all the output to a given email address and writes it to the system log.

**Comment by MorrisJobke** [comment] 2015-10-26 07:49
> Or, maybe more important, why is\OC::$server apparently false in my case?

I think there is a problem very early in the code -> see the log message ;)

**Comment by MorrisJobke** [comment] 2015-10-26 07:50
> And why did I only get the messages when the cron.php was executed via cron, and not when I manually ran the command sudo -u www-data php -f /var/www/owncloud/cron.php?

How do you run the cron command?

**Comment by kF13Ld** [comment] 2015-10-26 12:51
Ok, I didn't receive the cron-mails with error-information, because I added a `> /dev/null` in the crontrab, which apparently was not useful in this case ;-)

Without it, cron sends mails with this content:
`Autoload path not allowed: /var/www/config.php`
which is odd, as owncloud lies in /var/www/owncloud/ (because I installed it via apt-get install in Debian).

Why does it want to load the config.php from the wrong path? How do I change it?

**Comment by MorrisJobke** [comment] 2015-10-26 16:07
> Why does it want to load the config.php from the wrong path? How do I change it?

I guess it wants to load the class `OC_Config` which result in the filename `config.php`.

@rullzer Autoloader stuff - AFAIK

**Comment by rullzer** [comment] 2015-10-27 10:05
So we have at least 3 files called config.php...

@kF13Ld could you add:

`var_dump($e->getTrace());`

To that catch block so we can (hopefully) see where things go wild?

**Comment by kF13Ld** [comment] 2015-10-27 13:19
@rullzer: Ok, here is the output:
```
array(6) {
  [0]=>
  array(6) {
    ["file"]=>
    string(36) "/var/www/owncloud/lib/autoloader.php"
    ["line"]=>
    int(158)
    ["function"]=>
    string(11) "isValidPath"
    ["class"]=>
    string(13) "OC\Autoloader"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(1) {
      [0]=>
      string(19) "/var/www/config.php"
    }
  }
  [1]=>
  array(4) {
    ["function"]=>
    string(4) "load"
    ["class"]=>
    string(13) "OC\Autoloader"
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(1) {
      [0]=>
      string(9) "OC\Config"
    }
  }
  [2]=>
  array(4) {
    ["file"]=>
    string(30) "/var/www/owncloud/lib/base.php"
    ["line"]=>
    int(133)
    ["function"]=>
    string(17) "spl_autoload_call"
    ["args"]=>
    array(1) {
      [0]=>
      string(9) "OC\Config"
    }
  }
  [3]=>
  array(6) {
    ["file"]=>
    string(30) "/var/www/owncloud/lib/base.php"
    ["line"]=>
    int(485)
    ["function"]=>
    string(9) "initPaths"
    ["class"]=>
    string(2) "OC"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(0) {
    }
  }
  [4]=>
  array(6) {
    ["file"]=>
    string(30) "/var/www/owncloud/lib/base.php"
    ["line"]=>
    int(1061)
    ["function"]=>
    string(4) "init"
    ["class"]=>
    string(2) "OC"
    ["type"]=>
    string(2) "::"
    ["args"]=>
    array(0) {
    }
  }
  [5]=>
  array(4) {
    ["file"]=>
    string(26) "/var/www/owncloud/cron.php"
    ["line"]=>
    int(35)
    ["args"]=>
    array(1) {
      [0]=>
      string(30) "/var/www/owncloud/lib/base.php"
    }
    ["function"]=>
    string(12) "require_once"
  }
}
```
I hope this helps.

**Comment by kF13Ld** [comment] 2015-10-27 13:53
I just noticed that on my server the file /var/www/config.php indeed existed. I think I copied it there some time ago (in august) as a backup from /var/www/owncloud/config/config.php. For some reason it just now messed with the owncloud installation.

After renaming the file, I don't receive any more erroneous cron mails.

Question is, why it just messed up my owncloud with version 8.2.0, but not before?

**Comment by rullzer** [comment] 2015-10-27 21:26
@kF13Ld well because we restircted the autoloader to not allow malicious code to load arbitrary stuff.

However it is bad that our own code generates such paths. Let me look into a fix.

**Comment by PVince81** [comment] 2015-11-04 16:24
@rullzer any update ?

**Comment by PVince81** [comment] 2015-11-04 16:24
So does it mean the autoloader should not look for classes outside of the root ?

**Comment by rullzer** [comment] 2015-11-04 19:31
@PVince81  Ah yes. I have a local branch to start fixing this. However the issue is not that severe. But is basically happens because we rely on some autoloader magic. If you put a file config.php in the root stuff break.

Beacuse we want to load OC\Settings. Then the autoloader will say well stuff starting with `OC\` can be either in `private/config.php` or `config.php`. Now `private/config.php` resolves to `lib/private/config.php` (since we have `lib` set as include path). And `config.php` will fail. 

That is unless you have a file called config.php in your root. Then we will try to include it and it will break now because the root is not one of the places we can include from.

This is required for example by the settings stuff. `OC\Settings\Foo` should include `settings/foo.php`

So acutally the autoloader is doing its job by saying no you can't load `config.php` from the root. But, we should not try to either ;) In short. I don't want to risk breaking the autoloader to fix something most likely will not happen.

**Comment by PVince81** [comment] 2015-11-05 09:27
What bothers me is why is the autoloader even looking at the root ? Unless I misunderstood :smile:

**Comment by kF13Ld** [comment] 2015-11-05 09:36
@PVince81: Exactly, why is it looking in /var/www which is outside of the owncloud folder (/var/www/owncloud)?
Ok, it seems as if the user www-data has its home directory in /var/www under Debian, but still I think, owncloud shouldn't be looking for internal files outside the owncloud directory.

**Comment by PVince81** [comment] 2015-11-05 09:38
I wonder if it's old rusty code from that ghostly past. I seem to remember that at some point it was possible to have the 3rdparty folder outside of "owncloud". Woooo, spooky!

**Comment by rullzer** [comment] 2015-11-05 09:39
@PVince81 because we want to be able to include `OC\Setting\FOO` from `/settings/foo.php`. So if we tell the autoloader to look at:

`OC\Settings\Foo` if will construct two paths:

`private/settings/foo.php` and 'settings/foo.php`

Then we will this look in `<root>/private/settings/foo.php`, `<root>/settings/foo.php` and (because of include path magic) in `<root>/lib/private/settings/foo.php`.

Now if you just include `OC\<CLASS>` it will thus look for: 
* `<root>/private/class.php`
* `<root>/class.php`
* `<root>/lib/private/class.php`

It is basically because we do not do do our namespacing handling properly. Maybe for 9.1 it would be good to make a start with cleaning that up a bit.

**Comment by rullzer** [comment] 2015-11-05 09:39
o mmm even outside of the root... let me test that... that should be fixed...

**Comment by rullzer** [comment] 2015-11-05 09:45
This could very well be the same inlcude path magic. I can't reproduce it but @kF13Ld  could you get me the phpinfo from inside your (owncloud) root directory?

Just put a file foo.php there with
```php
<?php

phpinfo();
```

and then navigate to that file in your browser. And then report what `include_path` is set to?

**Comment by kF13Ld** [comment] 2015-11-05 10:02
Output of phpinfo():

Directive	| Local Value | Master Value
--------------|----------------|---------------------
include_path | .:/usr/share/php:/usr/share/pear | .:/usr/share/php:/usr/share/pear

**Comment by rullzer** [comment] 2015-11-05 19:44
I can't reproduce this with a config.php outside of the root.

**Comment by rullzer** [comment] 2015-11-06 12:53
Fix in #20365

**Closed** 2015-11-06 13:59 UTC
Labels: bug, sev3-medium

**Comment by MorrisJobke** [comment] 2015-11-06 14:37
@cmonteroluque Just to keep you updated: This was initially scheduled to 8.2.1 -> the fix is bigger and has huge impact on the whole system. Therefore it's better not to backport this - see https://github.com/owncloud/core/pull/20365#issuecomment-154416796

**Comment by cmonteroluque** [comment] 2015-11-10 09:56
@MorrisJobke Thanks! Point well taken

**Comment by timreeves** [comment] 2015-12-06 10:20
I had the same problem and found an easy and pragmatic fix:

Change your cron job to cd to the OC root directory and then execute the job:

/15 * * * * {oc-user} cd {oc-root} && {path-to-your-php} ./cron.php

**Comment by roman2025** [comment] 2015-12-19 05:01
Big thanks timreeves!

Your solution seems to have done the trick in fixing the pathing issues apparently introduced in 8.2 (excuse my ignorance, I am not a php pro)

My final crontab entry looked something like this (based on default oc install): 

*/15  *  *  *  *  cd /var/www/owncloud/ && php -f ./cron.php

I had a bit of trouble getting it right based on what you provided so I am providing mine to help others.

The default apache user on ubuntu distributions is www-data so for most people it is probably a matter of running the following to edit that user's crontab:
crontab -u www-data -e

Big thanks!

**Comment by MorrisJobke** [comment] 2015-12-19 08:18
Ah...I guess what went wrong: We should also check if the cron.php is run with the correct user. I will open a ticket for this.

**Comment by MorrisJobke** [comment] 2015-12-19 08:23
> Ah...I guess what went wrong: We should also check if the cron.php is run with the correct user. I will open a ticket for this.

see #21303

**Comment by roman2025** [comment] 2015-12-19 15:43
I think cron.php does check if the correct user is running it because if I try to run it from the root user account it barks at me and tells me it will only run from the account used by my web server.

**Comment by timreeves** [comment] 2015-12-19 15:59
I agree with @roman2025 - I got my problem solved without changing the user id being used, which was and remains correct. Looks more to me like a relative path is being used somewhere rather than an absolute one, making things dependent on the CWD which the job is called with.

**Comment by skycube** [comment] 2016-02-14 23:38
I had the same bug and when I looked into the config directory, the permission after the upgrade been wrong:
-rw-r----- 1 root     root     632 Feb 15 09:28 config.php

just execute:
chown www-data:www-data config.php
and
chmod o+r config.php

-rw-r--r-- 1 www-data www-data   676 Feb 15 09:34 config.php

**Comment by kwoxer** [comment] 2016-06-05 06:36
Just also wanted to say that I had this issue here. I got something like 

> Fatal error: Uncaught Error: Call to a member function getLogger() 

To fix this I just like a chown www-data on the folder. Like @skycube Fixed it.
