### ISSUE TITLE
shares gone after upgrading to 9.0

### ISSUE THREAD

**Issue by atroxix** [owncloud/core#23049] opened 2016-03-09 17:22 UTC
### Expected behaviour
All shares remain intact after upgrade.

### Actual behaviour
I had loads of shares both with OwnCloud users and by link, but after upgrading all of those are gone (ie. there's only one thing under both "Shared with others" and "Shared by link" - its sharing dialog doesn't open either).

### Server configuration
**Operating system**: FreeBSD

**Web server:** Apache 2.4

**Database:** MariaDB 10.0

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2.2 (through 9.0.0RC1)

**Where did you install ownCloud from:** FreeBSD ports

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium

**Operating system:** Linux

**ownCloud log (data/owncloud.log)**

Nothing besides errors described in #22987.

**Comment by LukasReschke** [comment] 2016-03-09 17:28
cc @owncloud/sharing

**Comment by rullzer** [comment] 2016-03-09 18:30
Can you see if https://github.com/owncloud/core/pull/23016 fixes the issue?

**Comment by atroxix** [comment] 2016-03-09 19:00
No, it didn't.

**Comment by rullzer** [comment] 2016-03-09 19:06
Can you post the output of

`curl -u <USER>:<PASS> http://<SERVER>/ocs/v2.php/apps/files_sharing/api/v1/shares`

`curl -u <USER>:<PASS> http://<SERVER>/ocs/v2.php/apps/files_sharing/api/v1/shares?share_with_me=true`

**Comment by rullzer** [comment] 2016-03-09 19:06
O. and do you have federated shares?

**Comment by atroxix** [comment] 2016-03-09 19:11
As per the referenced bug report, I do have federated shares, but those are not working.

I wouldn't post the direct output of those commands, but the contents is the same one share that I already mentioned. Anything specific of interest from the output?

**Comment by rullzer** [comment] 2016-03-09 19:14
Nah just if there would be more there...

Can you still see all the shares in your oc_share table?

**Comment by rullzer** [comment] 2016-03-09 19:15
Ah yes. Let me fix this... PR incomming...

**Comment by atroxix** [comment] 2016-03-09 19:17
Yes, oc_share table seems to be populated OK.

**Comment by rullzer** [comment] 2016-03-09 19:39
And nothing in your logs?

What does
`SELECT * FROM oc_share WHERE uid_initiator IS NULL AND share_type <> 2;`
give you?

**Comment by atroxix** [comment] 2016-03-09 20:29
Nothing in logs besides the federated share server not being reachable.

That SQL query gives an "empty set".

**Comment by rullzer** [comment] 2016-03-09 20:34
Ok well it is good that set is empty... but still strange.

@LukasReschke is this similar behaviour to what you have observed with federated shares?

**Comment by rullzer** [comment] 2016-03-10 10:04
@atroxix if you disable federated sharing in the admin settings. Is everything back the way it should be?

If not could you send me a dump of your share table? (e-mail is in my profile).

**Comment by carlu93** [comment] 2016-03-10 10:46
Hi everyone. Got the same problem as @atroxix. Tried disabling federated sharing. Didn't help, but i got the following error in the logfile on disabling and on enabling it again:

Error 	PHP 	OC\Share20\Exception\InvalidShare: at /srv/www/htdocs/owncloud/lib/private/share20/defaultshareprovider.php#783 

Hope this helps!? :)

**Comment by rullzer** [comment] 2016-03-10 10:52
@carlu93 that is most likely fixed with https://github.com/owncloud/core/pull/23016

**Comment by carlu93** [comment] 2016-03-10 10:54
Awesome thanks! Does this also fix the issue not being able to see what is shared by me and what is shared by others?

**Comment by rullzer** [comment] 2016-03-10 10:59
It *should*

**Comment by atroxix** [comment] 2016-03-10 13:08
Nothing changed after I disabled both sending and receiving federated shares.

Sent my oc_share table dump to your e-mail.

**Comment by rullzer** [comment] 2016-03-10 14:34
@atroxix thanks for the mail. You share table looks clean to me.

I'm going to think further why this might be happening...

**Comment by rullzer** [comment] 2016-03-14 14:58
@atroxix are there any entries in your oc_share_external table?

**Comment by atroxix** [comment] 2016-03-14 15:10
Yes, that one bogus entry from the other server which I don't have access to anymore. Can I just delete that entry there?

**Comment by rullzer** [comment] 2016-03-14 15:18
yes you can

**Comment by atroxix** [comment] 2016-03-14 15:20
Web UI started listing my files much faster now. But shares are still not listed.

**Comment by rullzer** [comment] 2016-03-14 15:26
> I had loads of shares both with OwnCloud users and by link, but after upgrading all of those are gone (ie. there's only one thing under both "Shared with others" and "Shared by link" - its sharing dialog doesn't open either).

Mmm somehow I missed this. More questions:

1. Which share are you actually seeing?
2. Are there any errors in your javascript log (since the share dialog does not open).

**Comment by atroxix** [comment] 2016-03-14 15:30
There is the following JS error:
> jquery.min.js?v=266fea8…:6 GET https://myowncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?subfiles=true&path=%2Fnull&format=json 404 (Not Found)

I see only one folder I've shared with one other user. And one folder from that user shared with me.

**Comment by rullzer** [comment] 2016-03-14 15:35
> https://myowncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?subfiles=true&path=%2Fnull&format=json 404 

In which directory are you?

**Comment by rullzer** [comment] 2016-03-14 19:00
@atroxix ok so basically the `&path=%2Fnull` part is weird. Which suggests that https://github.com/owncloud/core/blob/master/core/js/share.js#L57 is nul... which is something I don't get.

@PVince81 any idea here?

**Comment by atroxix** [comment] 2016-03-14 21:23
The thing is that there is this one folder that the other user has shared with me. I have then shared one subfolder from there by link. I see this subfolder from under "Shared with others" and under "Shared by link". The former doesn't actually make sense (and I don't see it being true from the Sharing dialog) because I have only 2 users in that OwnCloud, so sharing it back to the same user doesn't sound like something logical I may have done (but maybe it's the way it's meant to be, I don't know) :)

I got the above error when I entered the folder shared with me.

I get the following errors when being in either "Shared with others" or "Shared by link" and clicking on the sharing icon:
> https://myowncloud/core/vendor/jquery/jquery.min.js?v=266fea8098cf12e5923c3f1bce481c24:6
> GET https://myowncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2Fdocuments%2FRaamatud%2FPeaceful%20Parent&shared_with_me=true 404 (Not Found)
> https://myowncloud/core/vendor/jquery/jquery.min.js?v=266fea8098cf12e5923c3f1bce481c24:6
> GET https://myowncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2Fdocuments%2FRaamatud%2FPeaceful%20Parent&reshares=true 404 (Not Found)

When I navigate to the shared folder and click on the subfolder that I've shared by link, and click on the Sharing icon, I see the sharing information find and don't get any errors.

**Comment by rullzer** [comment] 2016-03-15 06:50
I still don't get those 404's. Those imply that the path passed is invalid. Which is very strange... because the only place that can happen is at https://github.com/owncloud/core/blob/master/apps/files_sharing/api/share20ocs.php#L434.

**Comment by rullzer** [comment] 2016-03-15 06:51
Can you run the followin query?

```sql
SELECT * 
FROM oc_share AS s 
LEFT JOIN oc_filecache AS f 
WHERE s.file_source = f.fileid;
```

**Comment by atroxix** [comment] 2016-03-15 08:21
>ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE s.file_source = f.fileid' at line 1

**Comment by rullzer** [comment] 2016-03-15 08:26
Ah try:

```sql
SELECT * 
FROM oc_share AS s 
LEFT JOIN oc_filecache AS f ON s.file_source = f.fileid 
```

**Comment by atroxix** [comment] 2016-03-15 08:31
That's better :)

There's quite a bit of lines though. Are you interested in anything specific?

**Comment by rullzer** [comment] 2016-03-15 08:33
Ah mmm it was to early. let me write the query i actually want..

**Comment by rullzer** [comment] 2016-03-15 08:34
```sql
SELECT *
FROM oc_share
WHERE file_source NOT IN (
    SELECT fileid
    FROM oc_filecache
)
```

**Comment by atroxix** [comment] 2016-03-15 08:37
Still quite a bit of lines. Anything specific? :)

PS. You have my oc_share table dump still, I guess, so you could possibly be quite specific?

**Comment by rullzer** [comment] 2016-03-15 08:37
How many lines? Since those are shares that have no 'file' associated with them...

**Comment by atroxix** [comment] 2016-03-15 08:38
35 lines, both folder and file shares.

**Comment by rullzer** [comment] 2016-03-15 08:41
Ok so... 35 of your 37 shares are somehow invalid. I'm not sure how this happend all of a sudden. Since the share migration did not touch the file_source...

Basically you have all the shar entries. But are missing the part of where they point to...

@icewind1991 any idea why after the migration fileids might have changed?

**Comment by PVince81** [comment] 2016-03-15 09:20
Not sure, but if those are orphaned shares (from deleted files), running cron should automatically clean these up. Maybe the upgrade went fine and these were indeed old deleted shares but the new code doesn't cope properly with these ?

@rullzer it should be possible to simulate orphaned shares as follows:

1. As admin, create a folder "test/sub"
1. Create/upload a file "test/sub/test.txt"
1. Share "sub" with another user "user1"
1. Check that "user1" received the share
1. Delete "test" as admin (the parent folder)
1. Check the DB, the share entry still exists
1. Check as "user1" that the folder is gone

I tried this on a local v9.0.0 instance and it works correctly. So either it's a red herring or @atroxix's shares are "invalid" in a different way.

**Comment by rullzer** [comment] 2016-03-15 09:23
@atroxix could you send me your whole db dump?

**Comment by atroxix** [comment] 2016-03-15 09:27
Sent.

**Comment by rullzer** [comment] 2016-03-15 09:41
@atroxix it seems that your cronjob has not been run since march 8th... (at least not the DeleteOrphanedShareJob)... And it is weird that there is no 'ExpireSharesJob' in there...

**Comment by rullzer** [comment] 2016-03-15 09:44
Manually running the cleanup job:

```sql
DELETE FROM oc_share
WHERE `item_type` in ('file', 'folder')
AND NOT EXISTS (SELECT fileid FROM oc_filecache WHERE file_source = fileid)
```

Does indeed leave me with 2 shares.
So that 'seems' right.

However you claim that you had more shares before.

Do you have a db backup of your 8.2 setup before your upgraded?

**Comment by atroxix** [comment] 2016-03-15 09:45
The only cronjob I've every run in there was:
> sudo -u www php /usr/local/www/owncloud/occ files:scan --path="silver/files/GoogleDrive"

But I disabled it because I removed my GoogleDrive remote share.

> Do you have a db backup of your 8.2 setup before your upgraded?
Yes, I do, you want it?

**Comment by rullzer** [comment] 2016-03-15 09:47
@atroxix that is not a cron job. That is an occ command. 

See https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/background_jobs_configuration.html#cron-jobs

Yes please send it to me so i can verify if the shares were already invalid back then.

**Comment by atroxix** [comment] 2016-03-15 09:50
Well, I ran that occ command through cron :D
Anyhow, then I haven't run cronjob ever, I think.

Sent pre-9.0 dump to your e-mail.

**Comment by rullzer** [comment] 2016-03-15 09:59
O sure... but do you run the owncloud cron jobs?

**Comment by atroxix** [comment] 2016-03-15 10:00
No, I don't/haven't.

**Comment by rullzer** [comment] 2016-03-15 10:06
Ok so it seems this is not a sharing issue. Because the share code basically does what is expected.

I can see you have more 'valid' shares in your 8.2 dump. But for some reason the fileid of some files changed. @icewind1991 @PVince81 any idea?

**Comment by PVince81** [comment] 2016-03-15 10:15
I don't think the file id changed at all, the only situation where a fileid changes is when using external storage and the remote file got renamed/moved outside of ownCloud.

The first thing to clear out is whether the web UI works correctly after clearing the orphaned shares.
If it does, then the problem was related to the orphaned shares.
Else it might be something else.

**Comment by atroxix** [comment] 2016-03-16 06:11
It would certainly be great if you found the reason why this happened.

My question though is that what can I do to fix it now? Shall I just remove all the share rows and replace them with the ones from pre-9.0 dump?

**Comment by PVince81** [comment] 2016-03-16 06:34
It is still not clear to me what is causing your problem in the web UI.

@rullzer mentionned some orphaned shares. Did you run cron.php and did the orphans get cleared ?
You might want to set "last_run" to 0 in oc_jobs for the row that has "OCA\Files_sharing\Lib\DeleteOrphanedSharesJob", then run cron.php again.

Then the question is whether your web UI is still failing to display shares ?
If yes, then it means there are other broken shares we need to look at.

**Comment by PVince81** [comment] 2016-03-16 06:35
In addition, orphaned shares should not cause any issues and should already be ignored properly. So I suspect that after clearing them the problem will still persist.

**Comment by atroxix** [comment] 2016-03-16 06:41
I've not run cron.php as I suspect it will delete all those "invalid" shares (which are not in fact invalid in the sense of their relevancy etc).
What do you mean by "orphaned" shares? @rullzer did not actually say that I have those, did he?

BTW, I hope "display shares" means also displaying shares I have shared with others (as this is the issue because I'm the main user of that OwnCloud).

**Comment by PVince81** [comment] 2016-03-16 06:43
I also see other reports about orphaned shares breaking stuff: https://github.com/owncloud/core/issues/23052 with the following workaround https://github.com/owncloud/core/pull/23039

**Comment by atroxix** [comment] 2016-03-16 06:45
Well, for me it's not breaking anything. Those shares are just not listed as they should, and they don't work for other users.

**Comment by PVince81** [comment] 2016-03-16 06:47
Orphaned shares are share entries that either:
- have oc_share.file_source point to a oc_filecache.fileid that doesn't exist any more (deleted)
or
- have oc_share.uid_owner point to a user that was deleted
or
- have oc_share.share_with point to a user/group that was deleted

**Comment by atroxix** [comment] 2016-03-16 06:49
OK, in that case it would happen that those "invalid" shares really are taken as "orphaned", but in fact they should not be. So I'd like to fix them instead of removing them :)

PS. I suspect my comment about those shared not breaking anything is invalid as I get those JS errors.

**Comment by PVince81** [comment] 2016-03-16 06:50
@atroxix invalid/orphaned shares should be safely ignored by the code already. But it seems that yours are a bit special, or broken in a special way.

> But for some reason the fileid of some files changed

@rullzer can you clarify what you mean with this ? Did you find the same target file in oc_filecache but with a different fileid ?

**Comment by rullzer** [comment] 2016-03-16 06:55
@PVince81 so yeah there were orphaned shares (by bad for calling them invalid). But the strange thing is I have his 2 dumps (8.2 and 9.0). If I run the cleanup query in 8.2 there are 20 valid shares. But if I run it on 9.0 there are only 2.

So what I did:

1. on 8.2
2. Grab the file_source of one of those 18 shares
3. Get the path_hash from the filecache
4. go to 9.0 db
5. Search for the path_hash

I find an entry that has the same path etc.

But it in 9.0 it has a size of -1 and a different mtime.
That is why I suspected some external storage thing at work.

**Comment by atroxix** [comment] 2016-03-16 06:58
So could I just replace all those invalid lines in 9.0 DB with lines from 8.2 DB dump?

**Comment by rullzer** [comment] 2016-03-16 06:59
@atroxix no that won't work. We modified that table a bit. And they will still point to invalid filecache entries..

**Comment by PVince81** [comment] 2016-03-16 07:05
Indeed, fileid should not magically change like this, and especially not during the upgrade process.

@atroxix can you confirm that you're not using external storages and also you did NOT disable file locking ?

**Comment by PVince81** [comment] 2016-03-16 07:09
@atroxix also you didn't manually truncate the oc_filecache table by any chance ? Never ever do that by the way.

**Comment by atroxix** [comment] 2016-03-16 07:13
> can you confirm that you're not using external storages

Well, I just added one external storage (GoogleDrive) back today :)

> and also you did NOT disable file locking

I didn't change anything in this regard when upgrading to 9.0. When looking at "Transactional File Locking" part in manual, I say I don't have it enabled - there's no 'filelocking.enabled' => 'true' and neither is there File Locking app.

> also you didn't manually truncate the oc_filecache table by any chance ?

No.

**Comment by atroxix** [comment] 2016-03-16 07:16
Heh, sorry, as file locking is not disabled it's enabled (as per manual) :)

**Comment by PVince81** [comment] 2016-03-16 07:17
That's fine, thanks. @rullzer might be onto something (chatting with him), it looks like something mysterious reindexed the storages/filecache entries which would have caused the bogus fileid change.

**Comment by PVince81** [comment] 2016-03-16 07:34
@atroxix did you move the "data" folder before doing the upgrade ?

So far it looks like something reindexed your storage.
If you do `select * from oc_filecache where storage=1 and name='';` before and after the update, the fileid is different.

**Comment by PVince81** [comment] 2016-03-16 07:41
@atroxix looking further, it looks like your storage (home:silver) is the only one that suffered from the fileid reindexation. Other storages look fine.

Did you at any point run "occ files:scan silver" after the update ?
Would be good if you could remember what you did exactly during the update.
So far there is no logical explanation to why your storage entries would get fully reindexed.

**Comment by atroxix** [comment] 2016-03-16 07:41
I did move data folder at some point, but not before doing upgrade.

**Comment by rullzer** [comment] 2016-03-16 07:43
If you data folder by any change on an NFS mount or something?

**Comment by atroxix** [comment] 2016-03-16 07:44
No, it's on a ZFS.

**Comment by PVince81** [comment] 2016-03-16 07:50
Since 8.1, changes made directly inside the "data" folder are not detected any more and should not trigger reindexation of a storage/home. The only way to force reindexation and change the fileids would be to manually delete all entries in oc_filecache for that storage and then run "occ files:scan $user" for that user. That would cause the fileids to change.

Still not clear what part of the update would have a bug that could trigger such logic.

**Comment by PVince81** [comment] 2016-03-16 09:28
@icewind1991 can you think of other places in the code where such symptoms could be triggered (storage fully reindexed, changed fileids) ? It only happened for a single storage.

**Comment by PVince81** [comment] 2016-03-16 09:29
Another clue is that the size of the root folder is "-1" in the reindexed version, which looks like the entries were inserted from somewhere but not fully scanned. This is usually the behavior of the scanner when scanning an external storage. It first goes through all entries and then updates the sizes. For some reason it seems it didn't finish.

**Comment by atroxix** [comment] 2016-03-16 09:48
> no that won't work. We modified that table a bit. And they will still point to invalid filecache entries..

Can I try fixing some columns of some of those invalid shared manually?

**Comment by PVince81** [comment] 2016-03-16 09:51
@atroxix if you still have the share entries (not cleant up by cron) then you can try setting "file_source" and "item_source" to the correct $fileid. To find the correct file id, look at "oc_filecache" and find the entry for the folders/files that were previously shared. You might also find this information in your 8.2 dump.

This would rewire the shares to point to the correct files.

**Comment by atroxix** [comment] 2016-03-16 11:09
Great success. I updated those fields of one of my main shared folders and it's listed now. 'size' of this row in oc_filecache is -1 though.

**Comment by PVince81** [comment] 2016-03-16 11:59
@atroxix now run "occ files:scan silver"

**Comment by atroxix** [comment] 2016-03-16 12:31
```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Starting scan for user 1 out of 1 (silver)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 13568   | 60253 | 00:17:53     |
+---------+-------+--------------+
```

And now? :)

**Comment by PVince81** [comment] 2016-03-16 13:41
That's it. Did it fix the sizes ?

**Comment by atroxix** [comment] 2016-03-16 14:11
Yes it did. It also caused the client to re-download all the files (or at least very many of them).

**Comment by PVince81** [comment] 2016-03-16 14:19
The scan shouldn't. The reason it redownloads is because the file ids changed.

**Comment by atroxix** [comment] 2016-03-16 14:54
The svan changes IDs every time? Because before it everything was in sync ok. Or wasn't it in fact?

**Comment by PVince81** [comment] 2016-03-16 14:55
The scan must NOT change the ids. If it does, then maybe you managed to somehow retrigger the bug we're looking for. Can you check ?

**Comment by atroxix** [comment] 2016-03-16 17:19
If you mean in filecache table then it seems IDs have not changed - latest added files are still with the biggest IDs.

Weird that the client re-downloaded the bunch of files then...

**Comment by PVince81** [comment] 2016-03-16 17:21
Hmmm, can you check whether the "etag" value changes ? Because that's what the client looks at to decide whether files are changed and require redownload.

Does the redownload happen again if you rescan ?

**Comment by atroxix** [comment] 2016-03-16 18:18
Scanned again and only 2 rows changed: a GoogleDrive share and something empty. And no re-downloading.

**Comment by PVince81** [comment] 2016-03-17 09:47
Ok thanks... Would you be able to put your 8.2 backup on a separate test server and re-run the update, to see whether the fileid changes situation happens again ?

At this point it is close to impossible to find out what went wrong and why.
If the test update fails again then at least there might be hope debugging it.

**Comment by atroxix** [comment] 2016-03-17 10:38
Tried the upgrade again both with the patches applied to 9.0, and without them. On both occasion the shares remained intact.

**Comment by atroxix** [comment] 2016-03-17 10:40
So maybe it was upgrade to 9.0-RC1 which broke those shares... Because after that I couldn't actually use OwnCloud for a few days because of the unresponsiveness.

**Comment by PVince81** [comment] 2016-03-17 10:44
Okay, thanks. Then I'll close this, it is likely that it was caused by the upgrade to RC1 which had some issues with shares and FS stuff.

**Closed by PVince81** 2016-03-17 10:44 UTC
Labels: bug, feature:sharing, sev1-critical
