### ISSUE TITLE
Unable to upload any size file in webGUI with memcached enabled

### ISSUE THREAD

**Issue by BradPhillips** [owncloud/core#12652] opened 2014-12-06 00:13 UTC
I am unable to upload any size file in the webGUI, I receive the error:

Upload error: 1 - The uploaded file exceeds the upload_max_filesize directive in php.ini: 1GB

Disabling memcached fixes the issue but causes other issues with other programs on the server so that is not a solution.

**Comment by Xenopathic** [comment] 2015-03-28 12:46
Since the problem has resolved itself, and is unable to be reproduced, I'm closing this. If you still get this issue feel free to reopen.

**Closed by Xenopathic** 2015-03-28 12:46 UTC
Labels: bug
