### ISSUE TITLE
Directories with name "*.part" do not get copied over DavFS.

### ISSUE THREAD

**Issue by tYYGH** [owncloud/core#17661] opened 2015-07-15 13:42 UTC
I have this old PHP program that I wrote years ago, where parts of the final HTML output are kept as "modules" in directories named "xxxx**.part**". I wanted to store all my dev projects, including this program's source files, in my local Owncloud. The directories named "xxxx.part" were not copied over.

Steps to reproduce
1. Mount (mount.davfs) Owncloud (https://my_server.org/OC/remote.php/webdav) on ```~/OC/```.
2. copy directory ```path/to/directory.part``` to ```~/OC/path/to/directory.part```
3. look for ```directory.part``` in ```~/OC/path/to/```: not there.

### Expected behaviour
```~/OC/path/to/directory.part``` should get copied.

### Actual behaviour
```~/OC/path/to/directory.part``` does not exist.

### Server configuration
**Operating system**: 3.16.0-4-kirkwood #1 Debian 3.16.7-ckt11-1 (2015-05-24) armv5tel GNU/Linux

**Web server:** nginx-full                     1.6.2-5                      armel

**Database:** postgresql-9.4                 9.4.3-0+deb8u1               armel

**PHP version:** php5-fpm                       5.6.9+dfsg-0+deb8u1          armel

**ownCloud version:** 8.1

**Updated from an older ownCloud or fresh install:** updated from older

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.1
 - contacts: 0.4.0.0
 - files: 1.1.9
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - files_pdfviewer
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
  'instanceid' => 'fake instance id',
  'passwordsalt' => 'fake password salt',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'my_server.org:443',
  'trusted_domains' =>
  array (
    0 => 'my_server.org',
  ),
  'datadirectory' => '/var/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.1.0.8',
  'dbname' => 'fake db name',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'fake db user',
  'dbpassword' => 'fake db password',
  'enable_previews' => false,
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'OwnCloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'my_server.org',
  'loglevel' => 2,
  'secret' => 'fake secret',
  'forcessl' => true,
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Browser:** davfs2                         1.5.2-1                      armel

**Operating system:** 3.16.0-4-kirkwood #1 Debian 3.16.7-ckt11-1 (2015-05-24) armv5tel GNU/Linux

#### Web server error log
No error.

#### ownCloud log (data/owncloud.log)

```
{"reqId":"9yHEFH8sqZXQH1jdRQ8O","remoteAddr":"192.168.1.10","app":"PHP","message":"filesize(): stat failed for \/var\/owncloud\/data\/me\/files\/path\/to\/news.part at \/var\/www\/owncloud\/lib\/private\/largefilehelper.php#196","level":3,"time":"2015-07-14T13:04:48+00:00"}
{"reqId":"9yHEFH8sqZXQH1jdRQ8O","remoteAddr":"192.168.1.10","app":"PHP","message":"filemtime(): stat failed for \/var\/owncloud\/data\/me\/files\/path\/to\/news.part at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#166","level":3,"time":"2015-07-14T13:04:48+00:00"}
{"reqId":"nAaN9qe4HEbx5pzcMOeY","remoteAddr":"192.168.1.10","app":"PHP","message":"filesize(): stat failed for \/var\/owncloud\/data\/me\/files\/path\/to\/profile.part at \/var\/www\/owncloud\/lib\/private\/largefilehelper.php#196","level":3,"time":"2015-07-14T13:04:49+00:00"}
{"reqId":"nAaN9qe4HEbx5pzcMOeY","remoteAddr":"192.168.1.10","app":"PHP","message":"filemtime(): stat failed for \/var\/owncloud\/data\/me\/files\/path\/to\/profile.part at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#166","level":3,"time":"2015-07-14T13:04:49+00:00"}
```

#### Browser log
No visible error while ```cp -a``` is running on these directories.

**Comment by LukasReschke** [comment] 2015-07-16 20:24
Looks like some bug in the chunking route? cc @DeepDiver1975

**Comment by PVince81** [comment] 2015-07-27 15:59
No.
ownCloud doesn't support any file operations on "*.part" files or folders.
This is because ownCloud already uses such files internally so there could be confusion.

It would be difficult to make it work because many code paths have special handling when they detect that the path has ".part" at the end. Those code paths would need to be rewritten to use a completely different approach.

**Comment by tYYGH** [comment] 2015-07-28 06:09
@PVince81 Thank you for the explanation. I expected such a situation.
Please tell me: is this limitation linked to the way the ownCloud client works, or the server? In other words, is it a problem (data loss, integrity, etc.) if I sync such files/directories using a regular webdav client (cadaver, davfs, etc.)?
Also, are there other "reserved" paths/names?

**Comment by PVince81** [comment] 2015-07-28 08:13
It is a limitation in the way how the server works. Having ".part" files that aren't OC part files would confuse the code and cause unpredictable behavior. Because a file ".part" is a special file that triggers different code paths. For example, ".part" files do not get indexed in the oc_filecache table because they are supposed to be temporary files. This means such files would be completely invisible in the web UI or WebDAV.

**Comment by PVince81** [comment] 2015-10-09 14:17
Also see https://github.com/owncloud/core/pull/7514 and https://github.com/owncloud/core/issues/7496

I'll close this ticket, part files aren't synced, this is by design.

**Closed by PVince81** 2015-10-09 14:17 UTC
Labels: bug
