### ISSUE TITLE
Default Photos folder does not duplicate when previous sharing and never log in before

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16899] opened 2015-06-12 09:45 UTC
### Steps to reproduce
1. Create a user
2. Share default Photos Folder with the user created (your own photos folder can have other files than the default ones)
3. Log in the new users account for the first time.

### Expected behaviour
Photos and Photos(1) folder should appear

### Actual behaviour
The Photos default folder of the new user appears shared

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Comment by PVince81** [comment] 2015-06-12 10:11
Slightly related: https://github.com/owncloud/core/issues/16450

@davitol we call the initial files that are created in the account "skeleton files"

**Comment by PVince81** [comment] 2015-08-18 15:49
I'll close this as duplicate of https://github.com/owncloud/core/issues/16450

**Closed by PVince81** 2015-08-18 15:49 UTC
Labels: bug, sev4-low, sharing
