### ISSUE TITLE
Unicode unit test fail on local machine with mysql

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#11506] opened 2014-10-09 16:53 UTC
Not sure if anyone else is getting this, but this is what I get when running unit tests locally with mysql:

Run: `./autotest.sh mysql lib/files/cache/cache.php`

```
1) Test\Files\Cache\Cache::testFolder with data set #2 ('<U+1F610>, NEUTRAL_FACE, UTF-8 hex F09F9890')
Doctrine\DBAL\DBALException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`size`, `mtime`, `mimepart`, `mimetype`, `path_hash`, `path`, `parent`, `nam
e`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)':

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x98\x90, ...' for column 'path' at row 1

/srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:47
/srv/www/htdocs/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:138
/srv/www/htdocs/owncloud/lib/private/db/statementwrapper.php:63
/srv/www/htdocs/owncloud/lib/private/db.php:229
/srv/www/htdocs/owncloud/lib/private/files/cache/cache.php:244
/srv/www/htdocs/owncloud/tests/lib/files/cache/cache.php:108
```

It doesn't happen for sqlite, so possible specific to MySQL.

### Versions
ownCloud git master 0474a20ab9d21327a9fab8e463eb74b91a198c31
mariadb-5.5.33-2.2.x86_64
PHP 5.4.20
openSUSE 13.1 x86_64

I don't think it's an issue with the collation since the database was created from scratch and ownCloud is supposed to set the collation correctly at start.

`show table status` shows InnoDB and `utf8_bin` for all tables.

@icewind1991 @DeepDiver1975 @bantu

**Comment by butonic** [comment] 2015-07-28 10:32
@PVince81 any update on your mariadb / mysql regarding running the testsuite locally?

**Comment by MorrisJobke** [comment] 2015-07-30 09:04
https://github.com/owncloud/core/pull/17978 <- fails on mariadb too, because it uses 4 byte characters.

I would like to close this as duplicate of #4513

**Closed** 2015-07-30 09:06 UTC
Labels: bug
