### ISSUE TITLE
Missing 'New' button in shared folders

### ISSUE THREAD

**Issue by Skywalker-11** [owncloud/core#16690] opened 2015-06-02 14:56 UTC
## Steps to reproduce
* UserA creates a folder and shares a link via mail 
* UserB (no logged in user) opens the link 

## Actual behaviour
There is no 'New' button to create new files or subfolders only the 'upload' button. 

![clipboard01](https://cloud.githubusercontent.com/assets/11180862/7938831/d0e75f60-0947-11e5-8b2b-e902e50a73bf.png)

## Expected behaviour
Because UserB can still upload folders and files via drag-and-drop he should also be able to create files/folders only using the web-gui (no drag-and-drop needed). It should look like this:

![clipboard02](https://cloud.githubusercontent.com/assets/11180862/7938926/7830c5c2-0948-11e5-8a49-bbf7435e4e7b.png)

## Server configuration
Owncloud version 8.0.3 (installed from sources)
Apache 2.2.22
PHP  5.4.39
OS: Debian Wheezy

**Comment by MorrisJobke** [comment] 2015-06-04 07:32
Duplicate of #6635

**Closed by MorrisJobke** 2015-06-04 07:32 UTC
Labels: enhancement, sharing
