### ISSUE TITLE
Upgrade 8.1.3 ==> 8.2+ not working New install of 8.2+ not working

### ISSUE THREAD

**Issue by kwstone** [owncloud/core#20976] opened 2015-12-06 18:32 UTC
### Steps to reproduce
1.  Install owncloud 8.2+ or upgrade from 8.1.3 to 8.2+ version.
2.
3.

### Expected behaviour

I expect the install to work or the upgrade to complete and the site to be operable.

### Actual behaviour

The upgrade makes the backup then gets the files for the new version but when the upgrade process is started I get a blank white screen.  Or and Error 500 on edge browser.

A new install after expanding the files and making sure all the owners / permissions are correct for my system I attempt to load the site and get the white screen.

### Server configuration
**Operating system**:
 Ubuntu 14.04
**Web server:**
 Apache 2.4.7
**Database:**
 MySQL 5.5.46
**PHP version:**
 5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
 I have several sites running 8.1.3 and have attepted to update one and also do a clean install to 8.2.1.4
**Updated from an older ownCloud or fresh install:**
 Both
**List of activated apps:**
 Only the default apps are activated
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => '****',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '*****.biz',
  ),
  'datadirectory' => '/mnt/oc_stonecloud/BLS',
  'overwrite.cli.url' => 'https://*****.biz/bls',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'oc_BLS',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'logfile' => '/mnt/oc_*****/BLS/owncloud.log',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
 local/smb
**Are you using encryption:** yes/no
  No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
  No

### Client configuration
**Browser:**
  Chrome, Firefox, Edge, 
**Operating system:**
  Win 10, Android, Linux
#### Web server error log
```
There are hundreds of the first line.  When I try to reload the site with the blank page I get the following error.
tdb(__NULL__): tdb_open_ex: called with name == NULL
[Sun Dec 06 09:36:29.559657 2015] [:error] [pid 15926] [client *.*.*.*:30732] PHP Fatal error:  Class 'InterfaSys\\LogNormalizer\\Normalizer' not found in /var/wwws/bls/lib/private/log.php on line 78

```

#### ownCloud log (data/owncloud.log)
```

{"reqId":"uF5YOU0mIgtxSvOSVGqJ","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:28:35+00:00"}
{"reqId":"5vhnXOwhruTnsB6H+98M","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:29:28+00:00","method":"--","url":"--"}
{"reqId":"5vhnXOwhruTnsB6H+98M","remoteAddr":"","app":"core","message":"starting upgrade from 8.1.3.0 to 8.2.1.4","level":0,"time":"2015-12-05T18:29:28+00:00","method":"--","url":"--"}
{"reqId":"5vhnXOwhruTnsB6H+98M","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:29:30+00:00","method":"--","url":"--"}
{"reqId":"5vhnXOwhruTnsB6H+98M","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:29:30+00:00","method":"--","url":"--"}
{"reqId":"5vhnXOwhruTnsB6H+98M","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:29:31+00:00"}
{"reqId":"Nys8iaX8yY71qZ+V\/bff","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:29:46+00:00"}
{"reqId":"DVr7BYB7Bj+4RgNH6ty1","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:30:10+00:00"}
{"reqId":"DVr7BYB7Bj+4RgNH6ty1","remoteAddr":"","app":"core","message":"XCache opcode cache will not be cleared because \"xcache.admin.enable_auth\" is enabled.","level":2,"time":"2015-12-05T18:30:10+00:00"}
```

#### Browser log
```
I don't have browser logs
```

**Comment by RealRancor** [comment] 2015-12-06 18:58
Seems another user at the forums had reported the same about the missing Normalizer class but havn't managed to report an issue here:

https://forum.owncloud.org/viewtopic.php?t=31172&p=99886

**Comment by kwstone** [comment] 2015-12-06 19:14
That was my post a while back when 8.2 first came out.  I had problems then so I waited a while to see if the problems would be resolved and they are not.

**Comment by MorrisJobke** [comment] 2015-12-07 06:57
```
tdb(__NULL__): tdb_open_ex: called with name == NULL
```

Wasn't this mentioned recently together with a samba mount - cc @icewind1991 @jmaciasportela Do you know what this means?

**Comment by PVince81** [comment] 2015-12-07 14:07
> upgrade makes the backup 

Only the updater app makes a backup, so this means the update was done with that. CC @VicDeo 

Error: `InterfaSys\\LogNormalizer\\Normalizer`.
This almost looks like the PHP code hasn't been properly updated. This library was introduced in 8.2.

**Comment by PVince81** [comment] 2015-12-07 14:08
I wonder if maybe you ran into a timeout while the code was being updated.

@VicDeo does the updater do the backup and the code update within the same call or are they different calls ? If different, then maybe the update code took a while to download the new package and PHP ran into a timeout more quickly than expected.

**Comment by kwstone** [comment] 2015-12-07 20:04
I have had the same problem both when I run the updater from 8.1.3 and also when I expand the tar file and try to set up new.  Both will not work.  8.1.3 is working fine on my server but I can't get 8.2 to work.  Is there some new server requirements that I may not have covered?

**Comment by VicDeo** [comment] 2015-12-07 20:15
@PVince81 
> does the updater do the backup and the code update within the same call or are they different calls ? 

every upgrade step (download | backup | replace) is done with different AJAX request currently

**Comment by VicDeo** [comment] 2015-12-07 20:17
@kwstone does `3rdparty/interfasys/lognormalizer/src/Normalizer.php` exist?

**Comment by kwstone** [comment] 2015-12-07 20:37
yes it's there @VicDeo

**Comment by kwstone** [comment] 2015-12-07 20:43
Just a little more info:

I just un-tarred 8.2.1 changed permissions and ownership for my machine and tried to go to the url.  Blank screen.  Get the same apache error /var/wwws/demo/lib/private/log.php on line 78  from the attempt.  I am adding this because I instance I was trying over the weekend I had to roll back to 8.3.1 and have it working this morning.  I have 6 instances of owncloud running on this server all of them at 8.1.3 and all working just fine.  I added the /demo with 8.2.1 and blank screen.

**Comment by capnjb** [comment] 2015-12-08 17:10
I too have numerous problems since the upgrade to 8.2+ on two systems with identical problems everything was working perfectly prior to upgrade from 8.1.4.
Summary of issues found thus far:
- Updater App kills the ownCloud Admin webpage (If disabled all is OK)
- SMB shares don't reindex when changes are made (The SMB shares are not updated on ownCloud) in the shared directory
- Text Editor 2.0 creates a file OK on an SMB share and the very first auto save works after that they all fail including when closing/exiting the file.  If you attempt to delete the file it will not delete.
- Text Editor 2.0 creates a file OK in the ownCloud local data directory.  It works for a while.. eventually you can open the file but cannot edit it anymore. If you attempt to delete the file it will not delete as complains that the file is locked.

Systems:
OS: Centos 6.5
PHP: 5.4.45
Webserver: Apache 2.2.15
MySQL: 5.1.73

OS: CentOS 7
PHP: 5.6.16
Webserver: Apache 2.4.6
MySQL: MariaDB 5.5.44      

Neither system has https access enabled
Neither system has memcache enabled yet
Neither system has Server side Encryption enabled 

CentOS 6.5 ownCloud Log
Debug	files_versions	Expire: /!Test/text.txt.v1448649014	2015-12-08T16:18:50+00:00
Debug	files_versions	Expire: /!Test/text.txt.v1448649035	2015-12-08T16:18:50+00:00
Debug	files_versions	Expire: /!Test/text.txt.v1448649069	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00

CentOS 7 ownCloud Log
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud/lib/private/files/storage/wrapper/encryption.php#525	2015-12-08T15:36:42+00:00
Error	PHP	fopen(/var/www/html/owncloud/data/jon/files_trashbin/files/Test.txt.d1449589002): failed to open stream: No such file or directory at /var/www/html/owncloud/lib/private/files/storage/local.php#247	2015-12-08T15:36:42+00:00
Error	files_texteditor	File: /!NAS ownCloud/Temp/Test.txt modified since opening.	2015-12-08T15:36:31+00:00
Error	files_texteditor	File: /!NAS ownCloud/Temp/Test.txt modified since opening.	2015-12-08T15:36:23+00:00
Error	index	Exception: {"Exception":"Exception","Message":"\\OC_Image::_output(): \"image\/x-ms-bmp\" is not supported when forcing a specific output format","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/image.php(193): OC_Image->_output(NULL, 'image\/x-ms-bmp')\n#1 \/var\/www\/html\/owncloud\/lib\/private\/preview.php(803): OC_Image->show(NULL)\n#2 \/var\/www\/html\/owncloud\/core\/ajax\/preview.php(63): OC\\Preview->showPreview()\n#3 \/var\/www\/html\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#4 [internal function]: __lambda_func(Array)\n#5 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(282): call_user_func('\\x00lambda_74', Array)\n#6 \/var\/www\/html\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/core\/preview.p...')\n#7 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/image.php","Line":260}	2015-12-08T15:35:16+00:00
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud/lib/private/files/storage/wrapper/encryption.php#199	2015-12-08T15:35:16+00:00

CentOS 6.5 - Admin page Warning
You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.
Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.
Your PHP version (5.4.45) is no longer supported by PHP. We encourage you to upgrade your PHP version to take advantage of performance and security updates provided by PHP.

CentOS 7 - Admin page Warning
You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips.
Transactional file locking is using the database as locking backend, for best performance it's advised to configure a memcache for locking. See the documentation ↗ for more information.
No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.

CentOS 6.5 Apps Installed
-bash-4.1$ php occ app:list
Enabled:
  - activity: 2.1.3
  - documents: 0.11.0
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - firstrunwizard: 1.1
Disabled:
  - encryption
  - external
  - files_videoviewer
  - gallery
  - notifications
  - provisioning_api
  - templateeditor
  - user_external

MySQL: MariaDB 5.5.44      MySQL: 5.1.73
Neither system has https access enabled
Neither system has memcache enabled yet
Neither system has Serverside Encryption enabled 

CentOS 6.5 ownCloud Log
Debug	files_versions	Expire: /!Test/text.txt.v1448649014	2015-12-08T16:18:50+00:00
Debug	files_versions	Expire: /!Test/text.txt.v1448649035	2015-12-08T16:18:50+00:00
Debug	files_versions	Expire: /!Test/text.txt.v1448649069	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00
Debug	files_versions	Mark to expire /!Test/text.txt next version should be 1448562691 or smaller. (prevTimestamp: 1448649091; step: 86400	2015-12-08T16:18:50+00:00

CentOS 7 ownCloud Log
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud/lib/private/files/storage/wrapper/encryption.php#525	2015-12-08T15:36:42+00:00
Error	PHP	fopen(/var/www/html/owncloud/data/jon/files_trashbin/files/Test.txt.d1449589002): failed to open stream: No such file or directory at /var/www/html/owncloud/lib/private/files/storage/local.php#247	2015-12-08T15:36:42+00:00
Error	files_texteditor	File: /!NAS ownCloud/Temp/Test.txt modified since opening.	2015-12-08T15:36:31+00:00
Error	files_texteditor	File: /!NAS ownCloud/Temp/Test.txt modified since opening.	2015-12-08T15:36:23+00:00
Error	index	Exception: {"Exception":"Exception","Message":"\\OC_Image::_output(): \"image\/x-ms-bmp\" is not supported when forcing a specific output format","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/lib\/private\/image.php(193): OC_Image->_output(NULL, 'image\/x-ms-bmp')\n#1 \/var\/www\/html\/owncloud\/lib\/private\/preview.php(803): OC_Image->show(NULL)\n#2 \/var\/www\/html\/owncloud\/core\/ajax\/preview.php(63): OC\\Preview->showPreview()\n#3 \/var\/www\/html\/owncloud\/lib\/private\/route\/route.php(154) : runtime-created function(1): require_once('\/var\/www\/html\/o...')\n#4 [internal function]: __lambda_func(Array)\n#5 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(282): call_user_func('\\x00lambda_74', Array)\n#6 \/var\/www\/html\/owncloud\/lib\/base.php(851): OC\\Route\\Router->match('\/core\/preview.p...')\n#7 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/html\/owncloud\/lib\/private\/image.php","Line":260}	2015-12-08T15:35:16+00:00
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud/lib/private/files/storage/wrapper/encryption.php#199	2015-12-08T15:35:16+00:00

This is very frustrating as each upgrade has been a struggle and it appears that some steps ahead are actually steps back.  In the last 2 or 3 upgrades things break and I try to get them fixed before the next update.  ownCloud is an awesome tool and we love the features but it is getting very difficult to keep it running.

Any light that can be shed on fixing the problems I have would be greatly appreciated.  For instance rolling back to the previous version of the text editor... would that fix some of the problem?  BTW, I tried to locate the older version without success.

da Capn

**Comment by RealRancor** [comment] 2015-12-08 17:13
@capnjb Those are completely unrelated issues. Please avoid hijacking an issue like this and (if you think you're hitting bugs here) create a new bugreport (using the issue template) for each.

**Comment by VicDeo** [comment] 2015-12-08 18:10
@kwstone does `./occ check` show anything interesting?

**Comment by jmaciasportela** [comment] 2015-12-09 08:08
Samba uses a lightweight database called Trivial Database (tdb) in which it stores persistent and transient data. Some tdb files can be disposed of before restarting Samba, but others are used to store information that is vital to Samba configuration and behaviour. The following information is provided to help administrators who are seeking to better manage their Samba installations.

Those who package Samba for commercial distribution with operating systems and appliances would do well to take note that tdb files can get corrupted, and for this reason ought to be backed up regularly. More info (https://www.samba.org/samba/docs/man/Samba-HOWTO-Collection/tdb.html)

WND app uses @icewind1991 library that wraps operating system samba calls. In this case it seems to be an error related with operating system SMB process

cc @MorrisJobke

**Comment by RealRancor** [comment] 2015-12-09 08:16
@jmaciasportela How is this related to the issue of the OP getting a ``PHP Fatal error:  Class 'InterfaSys\\LogNormalizer\\Normalizer'`` error during upgrades?

**Comment by jmaciasportela** [comment] 2015-12-09 08:25
@RealRancor it was about https://github.com/owncloud/core/issues/20976#issuecomment-162431667

**Comment by RealRancor** [comment] 2015-12-09 08:47
Ah, have missed this. Thanks.

**Comment by kwstone** [comment] 2015-12-09 21:00
@VicDeo 
```
kstone:~$ sudo -u www-data php /var/wwws/demo/occ check
An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /home/kstone/config.php' in /var/wwws/demo/lib/autoloader.php:138
Stack trace:
#0 /var/wwws/demo/lib/autoloader.php(158): OC\Autoloader->isValidPath('/home/kstone/co...')
#1 [internal function]: OC\Autoloader->load('OC\Config')
#2 /var/wwws/demo/lib/base.php(133): spl_autoload_call('OC\Config')
#3 /var/wwws/demo/lib/base.php(497): OC::initPaths()
#4 /var/wwws/demo/lib/base.php(1081): OC::init()
#5 /var/wwws/demo/console.php(42): require_once('/var/wwws/demo/...')
#6 /var/wwws/demo/occ(11): require_once('/var/wwws/demo/...')
#7 {main}kstone@stonecloud:~$ 
```

**Comment by VicDeo** [comment] 2015-12-09 21:04
@kwstone do you use symlinks on this installation?

cc @LukasReschke

**Comment by VicDeo** [comment] 2015-12-09 21:08
`/home/kstone/config.php` looks fishy since it is pretty unrelated to oc instance in `/var/www`

**Comment by kwstone** [comment] 2015-12-09 21:10
Not that I know of.  I have just taken the tar file and un-tarred it in the web directory and then run the set up program.  This is the first version that has not worked for me.  I have been using Owncloud since version 6 I believe.  I was not sure what it's trying to find in my home directory.  I do have an old config file that is no longer used in my home directory.  It's from one of the first installations I did on this box.

**Comment by VicDeo** [comment] 2015-12-09 21:18
@kwstone ah. Looks like I have an idea.
 Can you add a line 
set_include_path();
as per (https://gist.github.com/VicDeo/a30cd69af1ac16b9d88d#file-occ-L11)
 into occ
and rerun `./occ check`?

**Comment by kwstone** [comment] 2015-12-09 21:19
@VicDeo 
Just a little more info.  I just ran through all my other installations that are at 8.1.3 and the the ./occ check and they all came up with nothing.  I'll look at the instructions you posted.

**Comment by VicDeo** [comment] 2015-12-09 21:25
I guess this config.php is unrelated, but it exists and is resolved as first due to its position in include path.
A new security mechanism prevents autoloader to load the content of this file

**Comment by kwstone** [comment] 2015-12-09 21:52
I added your line to the /demo/occ file and it looks the same @VicDeo 
```
kstone@stonecloud:~$ sudo -u www-data php /var/wwws/demo/occ check
An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /home/kstone/config.php' in /var/wwws/demo/lib/autoloader.php:138
Stack trace:
#0 /var/wwws/demo/lib/autoloader.php(158): OC\Autoloader->isValidPath('/home/kstone/co...')
#1 [internal function]: OC\Autoloader->load('OC\Config')
#2 /var/wwws/demo/lib/base.php(133): spl_autoload_call('OC\Config')
#3 /var/wwws/demo/lib/base.php(497): OC::initPaths()
#4 /var/wwws/demo/lib/base.php(1081): OC::init()
#5 /var/wwws/demo/console.php(42): require_once('/var/wwws/demo/...')
#6 /var/wwws/demo/occ(12): require_once('/var/wwws/demo/...')
```

**Comment by kwstone** [comment] 2015-12-09 21:56
@VicDeo 
I renamed the config.php to .old in my home directory.  Then I have re-run the occ check.

```
kstone@stonecloud:~$ sudo -u www-data php /var/wwws/demo/occ check
ownCloud is not installed - only a limited number of commands are available
{"reqId":"1zqhZNTsO+XZIRH6izyM","remoteAddr":"","app":"PHP","message":"touch(): Unable to create file \/var\/wwws\/demo\/data\/owncloud.log because No such file or directory at \/var\/wwws\/demo\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-12-09T21:54:42+00:00"}
```

**Comment by VicDeo** [comment] 2015-12-09 21:59
@kwstone renaming is just a workaround. 
Can you put `return false;` 
before this line
https://github.com/owncloud/core/blob/master/lib/autoloader.php#L154 ?

**Comment by kwstone** [comment] 2015-12-09 22:03
@VicDeo 
Can you show me exactally where?
```
/**
	 * @param string $fullPath
	 * @return bool
	 */
	protected function isValidPath($fullPath) {
		foreach ($this->validRoots as $root => $true) {
			if (substr($fullPath, 0, strlen($root) + 1) === $root . '/') {
				return true;
			}
		}
		throw new AutoloadNotAllowedException($fullPath);
	}
```

**Comment by VicDeo** [comment] 2015-12-09 22:03
@kwstone before (or instead of)
throw new AutoloadNotAllowedException($fullPath);

**Comment by kwstone** [comment] 2015-12-09 22:10
@VicDeo 
I am looking at my copy of the file and my line numbers do not corespond to what you are asking me to change.  The line in question in my file is nm: 138 while you pointed me to nm: 154

The tar file I used was owncloud-8.2.1.tar.bz2

Could I be missing a few other things?  I can replace the line and try it if you want to go ahead with that.

**Comment by VicDeo** [comment] 2015-12-09 22:14
@kwstone yes, it's master version, yours is https://github.com/owncloud/core/blob/stable8.2/lib/autoloader.php#L138

anyway, exception is thrown there. It needs to be replaced with `return false;`
and rename `config.php.old` back just to test that it works now.

**Comment by kwstone** [comment] 2015-12-09 22:20
@VicDeo  I replaced the line with ```return false;``` and renamed the config in my home directory back to .php  This is the results of the occ command.

```
ownCloud is not installed - only a limited number of commands are available
{"reqId":"yppgxzDY3GglDOfWe654","remoteAddr":"","app":"PHP","message":"touch(): Unable to create file \/var\/wwws\/demo\/data\/owncloud.log because No such file or directory at \/var\/wwws\/demo\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-12-09T22:18:04+00:00"}
```

Keep in mind that this instance has not been installed because I can't get past the white screen.

**Comment by VicDeo** [comment] 2015-12-09 22:25
@kwstone you should be able to install it now (with patched autooader.php)

**Comment by kwstone** [comment] 2015-12-09 22:26
@VicDeo I still have a blank white screen or error 500

**Comment by kwstone** [comment] 2015-12-09 22:26
Chrome from remote computer and on server using localhost both the same

**Comment by VicDeo** [comment] 2015-12-09 22:40
@kwstone with the same messages in webserver error log but regarding `demo` subdirectory?

**Comment by kwstone** [comment] 2015-12-09 22:44
Here is the apache log:
```[Wed Dec 09 16:41:49.020597 2015] [:error] [pid 4512] [client *.*.*.*:5349] PHP Fatal error:  Class 'InterfaSys\\LogNormalizer\\Normalizer' not found in /var/wwws/demo/lib/private/log.php on line 78
```

**Comment by smarek** [comment] 2015-12-29 11:03
This happened to me with GIT installation. What fixed it was to go into `3rdparty` and do `git checkout v8.2.2` (with `core` checked out in same tag, `v8.2.2`), after that it started instantly

**Comment by kwstone** [comment] 2016-01-08 01:44
@smarek  Can you explain with a little more detail what you are saying.  I have not used GIT much so I need a bit more detail.

**Comment by smarek** [comment] 2016-01-10 10:59
@kwstone I don't know what type of installation you do use, however I do use GIT. GIT clone core repository and upgrade versions only through that. If you do use GIT installation, you should check if the subfolder (submodule) `3rdparty` is correctly checked out the same version as is the version of core repository.

If you do not use GIT installation, then simply check if your folder `3rdparty` is up-to-date with your latest installation package/procedure

**Comment by idenkov** [comment] 2016-01-15 11:26
I am having problem updating from 8.1.5. 
Raspbian, owncloud installed from the Suse repo, ran apt-get upgrade then the occ upgrade - got stuck in maintenance, I disabled the maintenance then I got the update banner again. 
After that ran the script for the file ownership and permissions, then ran again the occ update - same result. The banner for the update is still there.

occ check didn't return anything.

**Comment by RealRancor** [comment] 2016-01-15 11:29
@idenkov Very unlikely that you have the same issue here.

**Comment by edgeHB** [comment] 2016-01-20 09:14
Just tried to update from 8.1.1 and ran into the same error. Any news on how to fix this?

**Comment by VicDeo** [comment] 2016-01-20 09:26
@edgeHB IIRC it was caused by files that duplicate OC core files in the former case.
These  files should be located in directories that are listed before '.' in `include_path`.
So let's start with `php -i | grep include_path`

**Comment by edgeHB** [comment] 2016-01-20 09:31
@VicDeo Thanks for your quick reply!

```
include_path => .:/usr/share/php:/usr/share/pear => .:/usr/share/php:/usr/share/pear
```

**Comment by PVince81** [comment] 2016-02-12 15:15
What's the next step ? Is there anything that needs fixing in the code ?

**Comment by PVince81** [comment] 2016-06-17 14:06
Closing due to lack of feedback.

If this problem still occurs for you, please reopen.

**Closed by PVince81** 2016-06-17 14:06 UTC
Labels: bug, feature:update
