### ISSUE TITLE
userExists($user) not case sensitive

### ISSUE THREAD

**Issue by Rello** [owncloud/core#26727] opened 2016-11-26 12:27 UTC
### Steps to reproduce
1. \OCP\IUserManager $userManager
2. $this->userManager->userExists($user)
3. $user = admin
4. $user = Admin

### Expected behaviour
3.: False
4.: True

### Actual behaviour
3.: True
4.: True

This leads to problems later - in my case the Audio Player because occ will start the scanner even when mistyping the user
https://github.com/Rello/audioplayer/blob/master/command/scan.php#L81

A subsequent issue is, that an empty skeleton is created for the mistyped user - but this will be part of a separate Issue.

Is there a reason for this behavior

**Comment by PVince81** [comment] 2016-11-28 15:46
This is the behavior of the local user backend.

What you need to do:
```
    $user = $this->userManager->get($userIdFromInput)`
    if ($user === null) {
       // user does not exist, jump out the window
       ...
    }
    $userId = $user->getUID(); // use this id, not the one given as input
```

We fixed core to also use this logic for the same reason you mentionned, see: https://github.com/owncloud/core/blob/master/lib/private/AvatarManager.php#L83

This is "by design" of whoever designed the local case-insensitive DB user backend many years ago.
Closing.

**Closed by PVince81** 2016-11-28 15:46 UTC

**Comment by Rello** [comment] 2016-11-28 21:21
thank you for the simple workaround!
