### ISSUE TITLE
Add thumbnail view to the file app

### ISSUE THREAD

**Issue by thenamelessthing** [owncloud/core#17572] opened 2015-07-10 15:54 UTC
For managing pictures it's a MUST to see a thumbnail of each picture. Unfortunatly in the galery apps we can't manage them. So can we have a way to see them and manage the file at the same time.

**Comment by oparoz** [comment] 2015-07-11 11:03
Duplicate of https://github.com/owncloud/core/issues/17357

**Closed by oparoz** 2015-07-11 11:03 UTC
Labels: duplicate
