### ISSUE TITLE
very frequent and useless loading of huge table (150K rows) from db by appconfig.

### ISSUE THREAD

**Issue by schnidrig** [owncloud/core#26900] opened 2017-01-05 17:32 UTC
### Steps to reproduce

OC installation with many thousand users. (we have 23k)

### Expected behaviour
Don't stress the db. It's busy already ;-)

### Actual behaviour
OC constantly loads a huge table (150k rows) from the db after a sequential scan.
That leads to lots of slow queries and a high CPU load (for the sequential scan)

**ownCloud version:** 

we use 8.1 on our production system. However the problem persists in 9.0

**Database:**

mariadb 10.1.16 with galera

### Description 

I noticed that I get lots of slow query logs from the db. Most of them look like this:

    # User@Host: owncloud[owncloud] @  [10.0.23.108]
    # Thread_id: 759006  Schema: owncloud  QC_hit: No
    # Query_time: 0.503455  Lock_time: 0.001687  Rows_sent: 146291  Rows_examined: 146291
    # Rows_affected: 0
    #
    # explain: id	select_type	table	type	possible_keys	key	key_len	ref	rows	r_rows	filtered	r_filtered	Extra
    # explain: 1	SIMPLE	oc_appconfig	ref	PRIMARY,appconfig_appid_key	PRIMARY	98	const	66926	146291.00	100.00	100.00Using where
    #
    SET timestamp=1483632031;
    SELECT `configvalue`, `configkey` FROM `oc_appconfig` WHERE `appid` = 'files_sharing';

--

That means OC loads about once per second this huge table (146291 rows) from the db. 
All it would actually need is just a couple of rows.

--

Most of the rows in oc_appconfig belong to the app 'files_sharing':

    MariaDB [owncloud]> select count(*) from oc_appconfig where appid='files_sharing';
    +----------+
    | count(*) |
    +----------+
    |   146291 |
    +----------+
    1 row in set (0.12 sec)

    MariaDB [owncloud]> select count(*) from oc_appconfig;
    +----------+
    | count(*) |
    +----------+
    |   146443 |
    +----------+
    1 row in set (0.04 sec)

    MariaDB [owncloud]> select * from oc_appconfig where appid='files_sharing' limit 10;
    +---------------+-----------+-----------------+
    | appid         | configkey | configvalue     |
    +---------------+-----------+-----------------+
    | files_sharing |           | 1473188998.9676 |
    | files_sharing | 1000000   | 1481746824.6325 |
    | files_sharing | 1000004   | 1481746824.6345 |
    | files_sharing | 1000008   | 1481746824.6362 |
    | files_sharing | 1000012   | 1481746824.6382 |
    | files_sharing | 1000016   | 1481746824.6398 |
    | files_sharing | 1000020   | 1481746824.6419 |
    | files_sharing | 1000024   | 1481746824.6435 |
    | files_sharing | 1000028   | 1481746824.6454 |
    | files_sharing | 1000032   | 1481746824.6475 |
    +---------------+-----------+-----------------+

--

so whenever the app needs a config value, it will load the whole table:

See class AppConfig line 118 and following:

	public function getValue($app, $key, $default = null) {
		$this->loadConfigValues();

		if ($this->hasKey($app, $key)) {
			return $this->cache[$app][$key];
		}

		return $default;
	}

**Comment by DeepDiver1975** [comment] 2017-01-07 13:35
> so whenever the app needs a config value, it will load the whole table:

this is done my intention - the problem in your case is that there are a lot of entries regarding files-sharing.

@PVince81 @butonic starting which version they are no longer needed and can be killed? THX

**Comment by PVince81** [comment] 2017-01-09 11:33
These should be gone in 9.1 as etag propagation was reworked and uses a better approach that doesn't require such entries.

**Comment by PVince81** [comment] 2017-01-09 11:33
the rework isn't backportable unfortunately

**Comment by PVince81** [comment] 2017-01-09 11:34
Ref https://github.com/owncloud/core/pull/23157.

Closing as duplicate of https://github.com/owncloud/core/issues/22720

**Closed by PVince81** 2017-01-09 11:34 UTC
