### ISSUE TITLE
Explicit PROPFIND of getcontenttype returns 404 on folders

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13313] opened 2015-01-13 12:08 UTC
### Previous requirements

Have installed curl and optionally xmllint

Create a file called propfind.txt with this content:
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
<a:prop><a:getcontenttype/></a:prop>
<a:prop><oc:favorite/></a:prop>
</a:propfind>
```

### Steps to reproduce

1. Use curl to make a propfind request

Use your own credentials and host

```
curl -X PROPFIND -H "Content-Type: text/xml" http://USER:PASSWORD@HOST/owncloud/remote.php/webdav/FOLDER | xmllint --format -
```

### Expected behaviour
to be detailed

### Actual behaviour
getcontenttype returns a 404 not found in every folder always.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes

### Client configuration
**Browser:**
Chrome

**Comment by DeepDiver1975** [comment] 2015-01-13 12:25
@PVince81 some webdav fun for you? :speak_no_evil:

**Comment by PVince81** [comment] 2015-01-13 12:46
Yes, already discussed with @SergioBertolinSG on IRC.

It seems that folders do not have content types.

When doing a PROPFIND on a folder without a body (no explicitly requested attributes), you'll get the contents of the folder. For every file, there will be a "getcontenttype" attribute containing the mime type. However, folders do not have that attribute.

However if you explicitly request the "getcontenttype" attribute through PROPFIND, you'll get it for files as before, but for folders it will put it in the 404 block. Not sure if this is expected or whether we should add code to prevent this case.
Normally for any attribute that does not exist for an entity, the attribute would be put in the 404 block.

@evert any clue what route to go here ?

**Comment by evert** [comment] 2015-01-13 14:28
This is expected behavior. Collections don't have a content-type, because a content-type only relates to the `Content-Type` header of what a `GET` request would return. Collections don't need to respond to `GET` requests.

**Comment by PVince81** [comment] 2015-01-13 15:06
Okay, so the client should simply ignore the fact that "a:getcontenttype" appears in the 404 block, which shouldn't hurt.

Does it mean that if no attributes were requested explicitly (default case), a:getcontenttype should also appear in a 404 block for consistency ?

**Comment by evert** [comment] 2015-01-13 15:09
No, it doesn't make sense for the 'allprop' case.

**Comment by PVince81** [comment] 2015-01-13 15:10
Okay, thanks for the clarification.
Closing this as this is the expected behavior.

**Closed by PVince81** 2015-01-13 15:10 UTC
Labels: bug
