### ISSUE TITLE
Warning appears when trying to uncheck can share checkbox in sharing menu on the sidebar when we have 2 mountpoints with the same backend

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36801] opened 2020-01-21 17:19 UTC
### Steps to reproduce
1. Having oC server 10.4.0. RC1 enable external storage
2. Allow users to mount external storage
3. Configure a Global Mount point and check option enable sharing
4. Configure a personal Mount point with the same configuration data and DO NOT check option enable sharing
5. In Files View browse into Global MountPoint folder
6. Share a file/folder
7. Try to uncheck can share checkbox in sharing menu on the sidebar.

### Expected behaviour
Can share permission is disabled

### Actual behaviour

An error is shown in Files View 

<img width="960" alt="Screen Shot 2020-01-21 at 11 10 20" src="https://user-images.githubusercontent.com/10596560/72826789-c8745d00-3c79-11ea-9b07-89c8d89e3bc1.png">

![Screen Shot 2020-01-21 at 13 22 42](https://user-images.githubusercontent.com/10596560/72826774-c14d4f00-3c79-11ea-8ee5-bb70e8619e32.png)

No logs are spotted in owncloud.log

### Server configuration
ownCloud 10.4.0. RC1

**Note** Tested in oC 10.3.2 and it works fine. So it seems to be a regression

@HanaGemela @mbarz JFYI

**Comment by davitol** [comment] 2020-01-21 17:22
![exterSHAHA](https://user-images.githubusercontent.com/10596560/72827359-ee4e3180-3c7a-11ea-89e5-c768872f75ce.gif)

**Comment by phil-davis** [comment] 2020-01-22 01:31
There are changes/fixes coming for that sharing permissions/expiration date panel - PR https://github.com/owncloud/core/pull/36766
So we should test with that to see if the problem is already getting fixed.
Assigning myself so I notice this when I get to the office, and manually test.

**Comment by phil-davis** [comment] 2020-01-22 06:29
I have tried with both the current core master, and the branch for PR #36766 
I am trying with external storage type "ownCloud" that point to a different federated server.
I can't reproduce this problem.

@davitol I see that you are using WND. Is it specific to that?
Or can you reproduce this with current core master?
(Or maybe we get PR #36766 merged, and anything else for 10.4 and then start the process of making 10.4RC2... and test with that - RC1 is quite old now)

**Comment by davitol** [comment] 2020-01-22 07:46
> @davitol I see that you are using WND. Is it specific to that?

I reproduced with WND and with SFTP at least. And as mentioned core version was 10.4.0.RC1

**Comment by mbarz** [comment] 2020-01-22 07:46
@davitol I think you added the wrong one for JFYI (not the first time).
I think you wanted to link @micbar instead ;)

**Comment by davitol** [comment] 2020-01-22 07:48
> @davitol I think you added the wrong one for JFYI (not the first time).
> I think you wanted to link @micbar instead ;)

You are completely right! Sorry for the noise

**Comment by mrow4a** [comment] 2020-01-22 19:01
@davitol can you try reproducing this and see in the `owncloud.log` what is the exact line with the exception on the server side?

**Comment by davitol** [comment] 2020-01-23 08:51
> @davitol can you try reproducing this and see in the `owncloud.log` what is the exact line with the exception on the server side?

No logs in owncloud.log

**Comment by micbar** [comment] 2020-02-20 11:40
@davitol @mrow4a this is fixed now?

**Comment by mrow4a** [comment] 2020-02-20 11:57
@micbar did not work on it as @phil-davis is assigned. Should I?

**Comment by micbar** [comment] 2020-02-20 12:01
@mrow4a no, i was just asking.

@phil-davis @davitol Does this issue still exist?

**Comment by davitol** [comment] 2020-02-20 12:17
> @phil-davis @davitol Does this issue still exist?

Tested again in 10.4.0. RC4 and i was able to reproduce it

**Comment by micbar** [comment] 2020-02-20 12:25
@pmaier1 @phil-davis @HanaGemela We need to decide on this issue.
I was not aware of it, that it persists. There was a discussion that it could have been fixed by several other PRs.

I have a first estimate that this will require 1-2 md of work.

**Comment by HanaGemela** [comment] 2020-02-20 13:44
@micbar we can work on apps releases for 10.4 meanwhile

**Comment by phil-davis** [comment] 2020-02-20 14:50
Apologies - I had assigned myself just so that I would try this back in January.
I should have unassigned myself - it misled people into thinking that I was working on it.
I tooks off my assignment.

**Comment by micbar** [comment] 2020-02-20 15:40
@jvillafanez will investigate. Any help is welcome.

**Comment by VicDeo** [comment] 2020-02-20 15:45
Strange.
`git checkout v10.4.0RC3`

<img width="792" alt="admin" src="https://user-images.githubusercontent.com/991300/74951871-18794780-5411-11ea-8d88-b1e5c71dc794.png">
<img width="755" alt="personal" src="https://user-images.githubusercontent.com/991300/74951648-0bf4ef00-5411-11ea-98d6-b3c661750712.png">

<img width="763" alt="sharing" src="https://user-images.githubusercontent.com/991300/74950781-aef93900-5410-11ea-82fd-8798ea90c4ae.png">

**Comment by davitol** [comment] 2020-02-21 09:08
@VicDeo Same mountpoint configuration but different Name. Just in case you named both mountpoints with the same name. Sorry for the unclear info

**Comment by jvillafanez** [comment] 2020-02-21 09:23
The error is thrown in https://github.com/owncloud/core/blob/master/lib/private/Share20/Manager.php#L294.
Weird thing is that the share isn't the expected one (also shown in the ticket's screenshots). You're trying to share "/WND/Folder" but the error refers to "/WND1/Folder" (the other endpoint, which actually doesn't have share permissions). So somehow, we're fetching a wrong share.

**Comment by jvillafanez** [comment] 2020-02-21 11:20
Not sure if good or bad, but it's also reproducible with 10.3.2.
It doesn't "fully" happen in demo.owncloud.com because the response to the updates throws a 404 with a web page, causing the js code to crash without being able to show the popup. On my local environment, it throws a json response which handled properly in js, so the popup shows.

I'm not sure if related, but I've seen demo.owncloud.com configured with HTTP/2 but my local environment uses HTTP/1.1

**Comment by davitol** [comment] 2020-02-21 11:31
> Not sure if good or bad, but it's also reproducible with 10.3.2.
> It doesn't "fully" happen in demo.owncloud.com because the response to the updates throws a 404 with a web page, causing the js code to crash without being able to show the popup.

removing regression label

**Comment by davitol** [comment] 2020-02-21 11:57
@jvillafanez tested in 10.2.0.5 and also reproducible, so there is a hurry at all to fix this (cc @micbar)
As mentioned i thought i was a regression due to it was not reproducible in demo instance

**Comment by davitol** [comment] 2020-02-21 11:58
I have decreased the priority due to this bug has been here since long time ago

**Comment by jvillafanez** [comment] 2020-02-21 13:18
> I'm not sure if related, but I've seen demo.owncloud.com configured with HTTP/2 but my local environment uses HTTP/1.1

Doesn't seem to be related. Same popup error is shown in my local environment with HTTP/2
(for future reference: https://gist.github.com/GAS85/990b46a3a9c2a16c0ece4e48ebce7300 to setup HTTP/2)

**Comment by jvillafanez** [comment] 2020-02-21 13:37
Not sure how we can handle the problem in demo.owncloud.com. It might be a problem caused by an app, or maybe a "wrong" apache configuration.

**Comment by jvillafanez** [comment] 2020-02-24 13:24
Regarding the ticket, the problem seems to be big.
![Screenshot from 2020-02-24 13-49-16](https://user-images.githubusercontent.com/1477829/75153962-ea478080-570c-11ea-9acd-dbaea12b5537.png)

You can see the request being made to get the shares with a "/SFTP/bar.zip" path in the request. However, the response contains a "/SFTP1/bar.zip" path.

Although the POST request contains the path, that path seems to be lost. There is no reference connecting the share with the path because it's connected through the fileid. Both mounts (SFTP and SFTP1) have the same configuration, so the storage is the same and the fileids of both "/SFTP/bar.zip" and "/SFTP1/bar.zip" files are the same.

The main problem is that the shareManager assumes there is only one node connected to that share even though the code can return multiple nodes (https://github.com/owncloud/core/blob/master/lib/private/Share20/Share.php#L176)
Adjusting the code code on top of that seems quite a lot of work even if it's just for core and the files_sharing app.

**Comment by jvillafanez** [comment] 2020-02-25 09:34
Unless someone have a better idea, I'd vote for an unsupported scenario and won't fix this issue.

As said above, there are quite some code assuming that it will get only one node from the share, which isn't true for this scenario. The problem is in core, which means that the same assumption could have been spread over other apps (at least the ones dealing with shares)
In addition to these changes, we might need to refactor the code because we don't really have any information about which mount point the share is attached to. Basically, we have several nodes but we don't know which one to pick. I don't think we can make this change without breaking things.

**Closed** 2020-10-28 08:51 UTC
Labels: bug, p4-low
