### ISSUE TITLE
Owncloud upgrade 7 to 8; Could not automatically fix legacy storage

### ISSUE THREAD

**Issue by itwam** [owncloud/core#14124] opened 2015-02-11 19:42 UTC
OS: Debian 7 (wheezy)
Php version: 5.4.36
Owncloud installed by repository: deb http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/ /
Owncloud last working version: 7.0.4
User backend: Openldap
Third party apps: none

I Upgraded owncloud from 7.04 to 8.0.0-5 using "apt-get upgrade". I use this method for a long time without errors. This time I get the following errors during the apt-get upgrade (this probably doesn't have anything to do with the error, but I meantion it just in case)  
dpkg: warning: unable to delete old directory '/var/www/owncloud/config': Directory not empty
dpkg: warning: unable to delete old directory '/var/www/owncloud/themes': Directory not empty
dpkg: warning: unable to delete old directory '/var/www/owncloud/lib/private': Directory not empty
dpkg: warning: unable to delete old directory '/var/www/owncloud/lib': Directory not empty
dpkg: warning: unable to delete old directory '/var/www/owncloud/data': Directory not empty
dpkg: warning: unable to delete old directory '/var/www/owncloud': Directory not empty
dpkg: warning: unable to delete old directory '/etc/apache2/conf-available': Directory not empty

When I now click on the upgrade button in the webinterface I get the following error:
Maintenance enabled
Database schema-update checked
Database schema-update for apps checked
Database updated
Could not automatically fix legacy storage "local::/data/user@example.com/" => "home::user@example.com" because they both have data.
The update was unsuccessful. Please report this issue to the ownCloud community.

For the user management I use a ldap backend. This user was first a owncloud user but some time ago it was removed from the ldap backend. So the data folder is still there, but the user is not in the userlist anymore. 

Question now is, what should I do to fix this issue? I suppose I should manually delete the legacy storage from the mysql database. 

Is it enough when I run:
delete from oc_storages where numeric_id=<id_of_legacy_storage>;

Thanks in advance for helping me out.

**Comment by RealRancor** [comment] 2015-02-11 19:53
Hi,

could be a duplicate of: https://github.com/owncloud/core/issues/14088 which points to https://github.com/owncloud/core/issues/13980

**Comment by itwam** [comment] 2015-02-11 20:13
It seems to be a duplicate yes, thanks for the link.

deleting the local oc_storage id does fix this problem.

Though there is still one local entry called "local::/data/   |         16 |". I didn't need to delete this entry to finalize the upgrade succesfully. This /data/ is my mount point where all storages are located.

**Comment by VicDeo** [comment] 2015-02-11 20:52
Closing as a duplicate of https://github.com/owncloud/core/issues/13980

**Closed by VicDeo** 2015-02-11 20:52 UTC
