### ISSUE TITLE
scanFile event gets triggered on directories

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19711] opened 2015-10-12 13:27 UTC
I am currently working on a PR on core/apps/files/command/scan.php
When testing the original code, I have seen an interesting output which was wondering me.

Why do we get, when using ``$scanner->listen('\OC\Files\Utils\Scanner', 'scanFile'``, an event triggered for a directory? IMHO this should not be the case, or do I have missed something...
(Ubuntu, clone from master, no external mounts, no encryption)

sudo -u www-data ./occ files:scan --all

````
Scanning file   /user_name/							<-- ?
Scanning folder /user_name/
Scanning file   /user_name/files					<-- ?
Scanning file   /user_name/thumbnails				<-- ?
Scanning file   /user_name/cache					<-- ?
Scanning file   /user_name/files_trashbin			<-- ?
Scanning folder /user_name/files
Scanning file   /user_name/files/welcome.txt
Scanning file   /user_name/files/New text file.txt
Scanning file   /user_name/files/New text file1.txt
Scanning file   /user_name/files/New text file2.txt
Scanning file   /user_name/files/New folder			<-- ?
Scanning file   /user_name/files/New folder1		<-- ?
Scanning folder /user_name/files/New folder	
Scanning folder /user_name/files/New folder1
Scanning folder /user_name/thumbnails
Scanning folder /user_name/cache
Scanning folder /user_name/files_trashbin
Scanning file   /user_name/files_trashbin/files		<-- ?
Scanning folder /user_name/files_trashbin/files
````

core/apps/files/command/scan.php

````
$scanner->listen('\OC\Files\Utils\Scanner', 'scanFile', 
	function ($path) use ($output) {$output->writeln("Scanning file   <info>$path</info>");	});
$scanner->listen('\OC\Files\Utils\Scanner', 'scanFolder', 
	function ($path) use ($output) {$output->writeln("Scanning folder <info>$path</info>"); });
````

**Comment by MorrisJobke** [comment] 2015-10-12 14:25
Duplicate of #19458

**Closed by MorrisJobke** 2015-10-12 14:25 UTC
