### ISSUE TITLE
LDAP users / password changing 

### ISSUE THREAD

**Issue by abdallah-dhaou** [owncloud/core#21383] opened 2015-12-28 10:23 UTC
Hello Owncloud Team,

Importing users from LDAP is working perfectly, but the owncloud admin is "able" to change the password by typing the password field EVEN nothing will change and the password will be always the same. I guess is better to give the option to change password to users created only on owncloud , for LDAP users we have to make the password field read-only or  not existing.

I have installed owncloud 8.0.5 and while trying to change ldap users's password it show "enable to change password" , while with owncloud 8.2.1 it didn't show any message.

srv-test:~# php -v
PHP 5.4.4-14+deb7u9 (cli) (built: Apr 18 2014 14:34:31) 

srv-test:~# lsb_release -a
Description:    Debian GNU/Linux 7.5 (wheezy)
Release:        7.5
Codename:       wheezy

srv-test:~# apachectl -V
Server version: Apache/2.2.22 (Debian)

**Comment by LukasReschke** [comment] 2015-12-28 18:37
@owncloud/ldap

**Comment by davitol** [comment] 2016-01-04 09:22
I think it is dupe of https://github.com/owncloud/core/issues/18732

**Comment by LukasReschke** [comment] 2016-01-04 09:27
Agreed.

**Closed by LukasReschke** 2016-01-04 09:27 UTC
Labels: app:user_ldap
