### ISSUE TITLE
Error: Call to a member function acquireLock() on a non-object

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#21674] opened 2016-01-13 07:46 UTC
### Steps to reproduce
1. Clone master to a local repository
2. Set access rights 
3. Try to finalize install 

### Expected behaviour
Install should pass and the main sceen should open

### Actual behaviour
Install seems to pass, but you get a blank white screen.
./occ tells that the instance has not been installed.
owncloud.log shows an error.

Note: I tried it 3 times with the same result. The database was always cleared and there were no file leftovers.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.6

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
```
Last commit:
commit eac5d9fb3a52932fafdb200a2cf5d50fe9f1c759
Merge: 2493cfe 0d0377e
Author: Thomas Müller <thomas.mueller@tmit.eu>
Date:   Tue Jan 12 15:01:46 2016 +0100

    Merge pull request #21336 from owncloud/system-root-certs
```

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:** --

**The content of config/config.php:** --

**Are you using external storage, if yes which one:** local/smb/sftp/... --

**Are you using encryption:** yes/no --

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... --

### Client configuration
**Browser:** FireFox

**Operating system:** Ubuntu 14.04

#### ownCloud log (data/owncloud.log)
```
tail -f data/owncloud.log 
{"reqId":"wFPr+crYb2C1FDThLOqy","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/core\/lib\/private\/setup\/mysql.php#45","level":3,"time":"2016-01-12T17:04:09+00:00"}
{"reqId":"wFPr+crYb2C1FDThLOqy","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function acquireLock() on a non-object at \/var\/www\/owncloud\/core\/lib\/private\/files\/view.php#1838","level":3,"time":"2016-01-12T17:04:10+00:00"}
```
```
The following is from: lib\/private\/files\/view.php#1838
$mount->getStorage()->acquireLock(
	$mount->getInternalPath($absolutePath),
	$type,
	$this->lockingProvider
); 
```

**Comment by RealRancor** [comment] 2016-01-13 07:59
Looks to me like https://github.com/owncloud/core/issues/21657

**Comment by PVince81** [comment] 2016-01-13 08:54
Closing as duplicate of https://github.com/owncloud/core/issues/21657

**Closed by PVince81** 2016-01-13 08:54 UTC
Labels: bug
