### ISSUE TITLE
Error during transfer, sql duplicate entry

### ISSUE THREAD

**Issue by ThomDietrich** [owncloud/core#28461] opened 2017-07-21 11:42 UTC
Hello,
I've started with a fresh owncloud 10.0.2 installation based on the owncloud docker image, see https://github.com/owncloud-docker/server/issues/17

I'm in the process to upload 100GB of files and am occasionally am seeing the following error in the desktop sync client:

```
Error transferring https://xxx.tld/remote.php/dav/files/th/Fotos/DCIM/2016/2016-01-01_19.59.52.jpg - server replied: Internal Server Error (An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`checksum`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["1", "2", 1500547390, -1, "5970893eda4cc", 1500547390, 31, "", 360243, "2624f7444256c086dac0fb12be623c91", "files_encryption\/keys\/files\/Fotos\/DCIM\/2016", "2016", 4, 4, "2624f7444256c086dac0fb12be623c91"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-2624f7444256c086dac0fb12be623c91' for key 'fs_storage_path_hash')
```

My setup follows the standard config of the image, I've activated no additional apps but am using the encryption module.

I can confirm, that the files are successfully transferred at the next sync run. Still that seems like a bug. Thanks for looking into it!

**Comment by kdslkdsaldsal** [comment] 2017-07-21 13:16
Hi,

thanks for your report. This is a duplicate of https://github.com/owncloud/core/issues/22563 according to another duplicate in https://github.com/owncloud/core/issues/27369#issuecomment-292146275

Closing here for now, please watch https://github.com/owncloud/core/issues/22563 for any updates.

**Closed by kdslkdsaldsal** 2017-07-21 13:16 UTC
