### ISSUE TITLE
Are FileDrop Public Shares working with webdav utilities

### ISSUE THREAD

**Issue by christianlx** [owncloud/core#33069] opened 2018-10-08 13:30 UTC
10.0.0.8
### Steps to reproduce
1. Share a folder by public FileDrop link, get the link and the ID
2. Use a tool like cadaver to browse it
3.

### Expected behaviour
Access to the share

### Actual behaviour
Error 404

### Server configuration
**Operating system**: Centos7

**Web server:**Apache

**Database:**MariaDB

**PHP version:**7

**ownCloud version:** 10.0.0.8
**Updated from an older ownCloud or fresh install:**Updated from 9.1

**Where did you install ownCloud from:**Owncloud Repo for Centos

```
Hi,
I test Files Drop shares now availables with the 10 version. I just wonder if this kind of shares are readable and writables by command line like cadaver.
I ask the question because on a classic RW share, I can access by command line like :

cadaver https://myserver/owncloud/public.php/webdav/
Authentication required for ownCloud on server myserver': Username: my public ID dav:/owncloud/public.php/webdav/> ls Listing collection/owncloud/public.php/webdav/’: succeeded.
1.txt 1 oct. 8 08:52
2.txt 1 oct. 8 08:52
3.txt 1 oct. 8 08:52

If I do the same on a FileDrop Share (which is working with a browser), I have a 404 error like this as soon as I tried to connect:

Could not access /owncloud/public.php/webdav/ (not WebDAV-enabled?):
404 Not Found
Connection to `myserver’ closed.

And If I use remote.php instead ou public.php, the public ID does not work

So is it a bug or is it a normal behaviour of the FileDrop share ?

Thanks,
Christian.

**Comment by ownclouders** [comment] 2018-10-08 13:54
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/1477 (test working WebDAV), https://github.com/owncloud/core/issues/22735 (CalDAV: support public sharing), https://github.com/owncloud/core/issues/10132 (WebDAV did not work), https://github.com/owncloud/core/issues/31454 (Problems with public shares), and https://github.com/owncloud/core/issues/181 (Writing to WebDAV shared folder is not working).

**Comment by DeepDiver1975** [comment] 2018-10-08 18:13
@tomneedham :wave:

**Comment by hodyroff** [comment] 2018-10-08 18:33
FileDrops have no listing right. Therefor when you want to read=browse it a 404 is correct. A put however should work.

**Comment by PVince81** [comment] 2018-10-08 20:39
The purpose of file drop is to hide the listing, so letting it be accessed by cadaver or any Webdav tool would be a security breach.

This works by design, closing.

@christianlx not sure what your actual use case is, but if you wanted to programmatically access the FS and files you might need to write an app and use the PHP APIs for access.

**Closed by PVince81** 2018-10-08 20:39 UTC

**Comment by christianlx** [comment] 2018-10-09 06:16
OK thanks for your answers.
