### ISSUE TITLE
Folder Size does not get calculated

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#13876] opened 2015-02-04 10:05 UTC
Ubuntu 14.04, nginx, MySQL, PHP5.5.9, ownCloud git/Master 8.0.2

I created a new dev instance and added one SMB mount point (files external) successfully.

Problem:
when I go to the Files App, the size of the added external mount point never gets calculated, even not after a day of waiting time.
Logout/relogin, rebooting ect does not change the status. I always get "Ausstehend".

I can access the folder and its contents, I even can use gallery, but the Files App keeps staying on "Ausstehend".

There are no log entries

Info. This worked before on 8.x and works on 7.0.4 stable

**Comment by PVince81** [comment] 2015-02-04 10:34
What if you navigate into that SMB folder and sync it ?
From what I remember it only starts scanning the SMB folder once it is accessed at least once.

**Comment by mmattel** [comment] 2015-02-04 16:48
Here are some tests / things I did:

1. I added the SMB share and watched with htop the cpu load which was immediately high after leaving the admin page, like it would start to scan.
2. changing to the files app showed "Ausstehend" but it never finished. Remember, I waited for a full day.
3. As suggested I navigated thru the new folder. When I came back some time later, the folder size was shown.
4. To do a comparison, I mounted a smb share to a local ubuntu folder and mounted this folder with owncloud/local. Again, It showd "Ausstehend", but shortly after, **without diving thru the folder content like before** I got the size presented.
5. I retested it with a different smb share in the same way as above, but the result was the same.

What I have seen is, that the performance of scanning local (but mounted to smb) compared to mount smb by owncloud was **significant different where local was much faster**. 210GB local was done counted in seconds while the same mounted as smb took about many many minutes. Maybe the scanning speed difference can cause misthinking that it will never finish. And when you log off it seems that the size evaluation gets interrupted. A user then thinks it gets never done...

My interpretation:
- it is not necessary to dive into the mountpoints first to get the size evaluation (scanning?) started.
- it is a huge difference for the size evaluation (scanning?) if you mount local or smb.
- size evaluation (scanning?) never gets finished if the user who creates the mountpoint logges off before the run passes at least once.

**Comment by PVince81** [comment] 2015-02-04 17:05
A few points:
- mounting SMB on filesystem level will always be much faster than the PHP adapter/code that ownCloud uses (which wraps around the "smbclient" command line). If you can use FS level mount in your use case/setup, please do so
- scanning a huge folder might take a lot of time until it can tell the size. There is a risk that the PHP process runs into a timeout, so it might not continue running
- depending on your setup, the PHP process of the scanner might get killed if the connection is closed (when using php-fpm). From my experience, when using mod_php, the PHP process continues running even if the network connection is closed

**Comment by mmattel** [comment] 2015-02-07 09:41
ad 1:
local vs non local: this is what I also expected, but not that big difference...
I will do a short notice in the documentation about.

ad 2: 
oohhh. not good. how can that prevented? ownCloud can not predict any size/quantity of the share mounted.

ad 3:
I am using php-fpm and that would explain why after logging out scanning never finishes.
question: how is that managed when there is a cron job running? a cron job is, as far I understand it, assigned to a user, but can run independent if the user is logged on or not. if this is the case, why can´t the scanner run like a cron job?

from an admin/user point of view, you mount an external storage, but up to the point the scanner finishes and shows a result, you have no feedback where the scanning process is.

**Comment by mmattel** [comment] 2015-02-07 18:34
I just have seen that things could change when #10673 (New SMB Storage Backend) gets merged, at least from the point of scanning time. this would bring local and smb processing time closer (item 1 above)

**Comment by PVince81** [comment] 2015-02-09 09:58
for point 2) you cannot prevent PHP timeouts. That's how PHP works unfortunately. You could increase the timeout to bigger values.
In the future we will look into making long running operations be run as cron jobs or async tasks.
There are quite a few challenges regarding the background job approach (and a bunch of code to be rewritten)

for 3) I believe that cron jobs are run on the command line and might have different timeout values, or no timeout at all. I believe they might not even fall under php-fpm stuff since they don't go through Apache/Nginx.

**Comment by PVince81** [comment] 2016-01-21 15:28
@mmattel are you still observing this on the latest master ?
From what I remember there is now a background job that would do the scanning.

**Comment by mmattel** [comment] 2016-01-21 16:01
Funny, I just setup a new test instance and gave this a try.

When I added a big smb picture share (successfully), scanning did NOT start automatically. Not after changing from the admin page to the files page nor when I logged off/logged on. I had to start scanning manually.
I also got no hint that it has started scanning (would be good to have a info at least in th log), I have also not seen any cpu load difference - which is a good indicator for scanning...

Maybe related. Gallery was not able to "see" that there are now pictures present. I had to logoff/logon that gallery was able to present pictures. (https://github.com/owncloud/gallery/issues/499).

For me the internal process of: let´s scan, provide results is not fully working.

**Comment by mmattel** [comment] 2016-01-21 16:03
Forgot to mention: when manual scanning has finished, the size result at the files page was correct.

**Comment by PVince81** [comment] 2016-01-21 16:03
Okay, thanks :disappointed:

**Comment by PVince81** [comment] 2016-01-22 15:46
Just tested with a SMB mount, I had to run cron a few times to make the background scan work.
I cheated and set `last_run` to 0 for the background scan.

After that, the SMB mount had the correct size.

But not sure why occ files:scan wouldn't find the size too ? @icewind1991

**Comment by PVince81** [comment] 2016-03-21 16:03
I tried with "occ files:scan --all" on stable9 (upcoming 9.0.1) and the sizes were properly calculated.

Then I tried again with the background job: the scanning did NOT start.

@icewind1991 the problem is that `backgroundScan` ignores the storage if it has zero entries. Even the root entry is missing, so it didn't bother to go inside. Normally it would look for "-1" values.

Can we make it work in such cases ?

**Comment by PVince81** [comment] 2016-03-21 16:05
I tried manually inserting a root entry with size -1, then the background scan did its job.

**Comment by icewind1991** [comment] 2016-03-24 13:39
This seems to be fixed with the 9.0 "background scanner in cron"

- added a new external storage
- checked that it's size was unknown in the web ui
- ran cron
- checked that the size in the webui was fixed

**Comment by PVince81** [comment] 2016-03-24 13:57
@icewind1991 please read my comments https://github.com/owncloud/core/issues/13876#issuecomment-199356858

**Comment by PVince81** [comment] 2016-03-24 13:57
Maybe remove the step "checked that size was unknown" to avoid triggering implicit scan through the web UI. Maybe create the ext storage on the CLI.

**Comment by icewind1991** [comment] 2016-03-24 14:19
ok, can reproduce by removing all cache entries for the storage and than running the background scan

fix is here https://github.com/owncloud/core/pull/23561

**Closed** 2016-04-14 19:23 UTC
Labels: 3 - To Review, bug, in progress, sev2-high, triage
