### ISSUE TITLE
SQLSTATE[40001]:Serialization failure with deadlock causes files to stay locked

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#26980] opened 2017-01-19 17:06 UTC
Hello,

On a small owncloud 9.0.1 instance (running with PHP7 on Debian and MySQL) we regularily see this problem: files uploaded from a desktop client get locked and server reports 423 error back. Out of 200 files, some 10% fail to upload (locked), client retries many times until all completes.

This problem was originally described here: https://github.com/owncloud/core/issues/20380#issuecomment-273440702

This seems to be correlated with these errors:

`
[Thu Jan 19 10:24:43.038781 2017] [:error] [pid 29927] [client ip.address:53376] PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when tryi
ng to get lock; try restarting transaction in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/D
octrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)\n#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\\DBAL\\Driver\\PDOStatement->exec
ute()\n#2 /var/www/owncloud/lib/private/DB/Connection.php(209): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctr
ine/DBAL/Query/QueryBuilder.php(208): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#4 /var/www/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php(141): Doctrine\\DBAL\
\Query\\QueryBuilder->execute()\n#5 /var/www/owncloud/lib/private/Lock/DBLockingProvider.php(277): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 [internal function]: in /var/www/owncloud/3rdpa
rty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
`

Transactional file locking is enabled (as per default). No redis.

**Comment by moscicki** [comment] 2017-01-19 20:07
Actually, disabling the transactional locking in the config file makes the problem go away. That's very disturbing...

**Comment by PVince81** [comment] 2017-01-19 21:36
How about trying with redis for file locking ?

If disabling locking makes it work, then some concurrency problem is happening when dealing with DB based locks.

**Comment by moscicki** [comment] 2017-01-20 05:51
I have a gut feeling that this is likely in the code path for external mounts. The problem appears for a folder which is "External Mount" pointing to the local disk on the same server and then shared with a user by administrator. That should be easy to check on your side.

**Comment by PVince81** [comment] 2017-01-23 20:01
I wanted to try this but it seems v9.0.1 doesn't even let itself be setup with PHP 7.

I'd recommend upgrading to v9.0.7 or so. 9.0.1 is already quite old and many bugs were fixed since then.

My steps on v9.0.7:

1. Setup OC with DB locking (no memcache) on PHP 7.0.14, openSUSE 42.2 and MariaDB 10
1. Enable files_external app
1. Create an external storage mounted on "/local" with the type local and pointing at "/srv/www/ocdata" (this folder is empty and gives the web server all perms)
1. Go to the advanced options and set "Enable sharing"
1. Create a user "user1"
1. Go to the files list
1. Share "/local" with "user1" using sharing panel
1. Log out
1. Setup sync client with user "user1"
1. Genrate 200+ files into the local "/local" folder: `for I in $(seq 1 200); do echo "test$I" > test$I.txt; done`
1. Wait for sync.

I also tried again with 1000+ files.

There were no locking issues during the upload.

**Comment by PVince81** [comment] 2017-04-06 11:35
closing as not reproducible or not enough info to reproduce

**Closed by PVince81** 2017-04-06 11:35 UTC
Labels: bug, feature:locking, needs info

**Comment by hamburml** [comment] 2018-01-03 00:43
I have the same error. My owncloud runs inside a docker swarm. I am using owncloud 10.0.4-apache and mariadb 10.3.3. Owncloud instance connects to the database via docker network. I use the desktop client on windows to synchronize my files. After some hours the error is shown in the client.

```
03.01.2018 01:22:05,Arbeit/Fun/Assets/Gamemaster Audio - Pro Sound Collection - 24bit 96k/Voice/Human Female A/voice_female_a_growl_01.wav,
<FILE TO SYNCHRONIZE>,Error downloading <SERVER>remote.php/webdav/Arbeit/Fun/Assets/Gamemaster Audio - Pro Sound Collection - 24bit 96k/Voice/Human Female A/voice_female_a_growl_01.wav - server replied: Internal Server Error (An exception occurred while executing 
'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`checksum`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` 
WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["15", "21", 1514938927, 460844, "4c81ba1ee961c30ecc1e761fa08d49e6", 1514938927, 27, "", 4337, "68c63adc458184be33ba4172c606a938", "files\/Arbeit\/Fun\/Assets\/Gamemaster Audio - Pro Sound Collection - 24bit 96k\/Voice\/Human Female A\/voice_female_a_growl_01.wav", "voice_female_a_growl_01.wav", 3, 3, "68c63adc458184be33ba4172c606a938"]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction)
```

To create the docker services I used:

```
docker network create --driver overlay owncloud

docker service create --name mariadb-owncloud \
    -e MYSQL_ROOT_PASSWORD=secretPw \
    --network owncloud \
    --mount type=bind,source=/swarmdata/owncloud/mariadb,destination=/var/lib/mysql \
    --constraint 'node.id==463tr6oglx56yedwwdyfoz501' \
    --replicas 1 mariadb:latest

docker service create --name owncloud \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.serviceDomain=<URL> \
    --label com.df.port=80 \
    --network owncloud \
    --network proxy \
    --mount type=bind,source=/swarmdata/owncloud/ownclouddata,destination=/var/www/html \
    --constraint 'node.id==463tr6oglx56yedwwdyfoz501' \
    --replicas 1 owncloud:latest
```

Don't mind the label com.df.stuff I am using docker flow which is a project which uses HAProxy as a reverse proxy and is reconfigured everytime a new service is created. And I use constraints because I mount a volume inside the service.

Any help is appreciated.

**Comment by PVince81** [comment] 2018-01-08 11:31
@hamburml Maria DB 10.3 is still beta and ownCloud doesn't support it yet as it might require bigger changes. See https://github.com/owncloud/core/issues/29483.
