### ISSUE TITLE
Web Installer Error

### ISSUE THREAD

**Issue by MeCias** [owncloud/core#16211] opened 2015-05-09 04:56 UTC
Hello,

since I noticed that 8 days ago OC8.0.3 was released and it seems to be my installation (8.0.2) is still up to date ... 

![untitled3](https://cloud.githubusercontent.com/assets/4476171/7548751/ffd6b2be-f617-11e4-9ecf-602a201c7e03.jpg)
![untitled2](https://cloud.githubusercontent.com/assets/4476171/7548752/08a63158-f618-11e4-9457-850dba42b5ea.jpg)

... I thought I am going to do an update/installation via Web Installer. I did that before and worked well until today. I get following error messages

![untitled](https://cloud.githubusercontent.com/assets/4476171/7548753/153b5e34-f618-11e4-9520-abb36b8f888d.jpg)

I am just not sure what to do with this two messages?

The error log of my current 8.0.2 installation (maybe not related to the Web Installer issue, but to the 8.0.2 still up to date problem) is just saying this:

Error 	PHP 	curl_setopt() expects parameter 2 to be long, string given at /home/www/web/html/cloud/lib/private/httphelper.php#72 	2015-05-09T04:16:28+00:00
Error 	PHP 	Use of undefined constant CURLPROTO_HTTPS - assumed 'CURLPROTO_HTTPS' at /home/www/web/html/cloud/lib/private/httphelper.php#72 	2015-05-09T04:16:28+00:00
Error 	PHP 	Use of undefined constant CURLPROTO_HTTP - assumed 'CURLPROTO_HTTP' at /home/www/web/html/cloud/lib/private/httphelper.php#72 	2015-05-09T04:16:28+00:00
Error	PHP	Use of undefined constant CURLPROTO_HTTP - assumed 'CURLPROTO_HTTP' at /home/www/web/html/cloud/lib/private/httphelper.php#72	2015-05-09T04:43:06+00:00
Error	PHP	Use of undefined constant CURLOPT_REDIR_PROTOCOLS - assumed 'CURLOPT_REDIR_PROTOCOLS' at /home/www/web/html/cloud/lib/private/httphelper.php#72	2015-05-09T04:43:06+00:00
Error	PHP	curl_setopt() expects parameter 2 to be long, string given at /home/www/web/html/cloud/lib/private/httphelper.php#71	2015-05-09T04:43:06+00:00
Error	PHP	Use of undefined constant CURLPROTO_HTTPS - assumed 'CURLPROTO_HTTPS' at /home/www/web/html/cloud/lib/private/httphelper.php#71	2015-05-09T04:43:06+00:00
Error	PHP	Use of undefined constant CURLPROTO_HTTP - assumed 'CURLPROTO_HTTP' at /home/www/web/html/cloud/lib/private/httphelper.php#71	2015-05-09T04:43:06+00:00
Error	PHP	Use of undefined constant CURLOPT_PROTOCOLS - assumed 'CURLOPT_PROTOCOLS' at /home/www/web/html/cloud/lib/private/httphelper.php#71	2015-05-09T04:43:06+00:00
Error	PHP	curl_setopt() expects parameter 2 to be long, string given at /home/www/web/html/cloud/lib/private/httphelper.php#72

**Comment by RealRancor** [comment] 2015-05-09 07:40
Hi,

the PHP errors where reported here: https://github.com/owncloud/core/issues/16179

**Comment by MeCias** [comment] 2015-05-09 17:48
Hi and thank you for the hint with the curl version. I just checked and indeed it is an old version. In my case 7.15.5.
I have to ask my provider if they might update it.

**Comment by LukasReschke** [comment] 2015-05-11 06:49
Other errors are dupe of https://github.com/owncloud/core/issues/16179#issuecomment-100788857

**Closed by LukasReschke** 2015-05-11 06:49 UTC
