### ISSUE TITLE
Encryption problem - Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.

### ISSUE THREAD

**Issue by mislav-eu** [owncloud/core#22042] opened 2016-02-01 10:32 UTC
**Note**: there are some similar topics on this subject, but all problems are closed, thus I'm opening a new one.

### Steps to reproduce
1. When encryption is enabled, I've created backup of the user X
2. User X has deleted folder "test123"
3. I've restored folder "test123" from backup
4. At first I didn't see this folders inside owncloud, thus I've ran the command: 
# sudo -u www-data php console.php files:scan userX

and then folders were visible
5. When I tried to access to some of the files inside this folder, I receive error: 
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.

Please note that meanwhile, there was no user password change.

### Expected behaviour
Since I couldn't find proper way/documentation on how to backup/restore files when encryption is enabled, I simply tar.gz-ed files and restored them - expected behaviour would be of course when this files are restore owner can access them.

### Actual behaviour
Restored files as mentioned are not accessible.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** MariaDB

**PHP version:** PHP 5.6.14

**ownCloud version:** (see ownCloud admin page) 8.2.2

**Updated from an older ownCloud or fresh install:** there was fresh install 8.1.1, but I was updating meanwhile up to current 8.2.2

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
- I automatically get redirected to http://mydomain.com/index.php/apps/files/ - it doesn't work for me

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.1.3
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
Disabled:
  - files_trashbin
  - firstrunwizard
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.com"
        ],
        "datadirectory": "\/opt\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/mydomain.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "test_do_ownc_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "defaultapp": "files",
        "check_for_working_htaccess": false,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "enable_previews": false,
        "singleuser": false,
        "maintenance": false,
        "theme": "",
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "auto"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/... no external sstorage

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no external user-backend

```

### Client configuration
**Browser:** Mozilla Firefox (latest)

**Operating system:** Ubuntu 14.04 LTS

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"rKDme2Gqks7+p8mwAVIJ","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-02-01T10:02:21+00:00"}
{"reqId":"YYZkvFFDsrON4ZduTQOG","remoteAddr":"","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-02-01T10:02:28+00:00"}

I've tried to run also the following command:
$ sudo -u www-data php occ encryption:decrypt-all userX

 [-->-------------------------]PHP Fatal error:  Call to a member function get() on null in /var/www/owncloud/apps/files_sharing/lib/updater.php on line 76

owncloud log:
{"reqId":"zUQOrO8dOGtNiV6ksPvF","remoteAddr":"","app":"PHP","message":"Call to a member function get() on null at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/updater.php#76","level":3,"time":"2016-02-01T10:00:16+00:00"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

GET https://mydomain.com/index.php/app...r/ajax/loadfile?filename=test2.txt&dir=%2Ftest12
	
400 Bad request
		248ms	
fb1bf5b...1351.js (line 6)
"NetworkError: 400 Bad request - https://mydomain.com/index.php/apps/files_texteditor/ajax/loadfile?filename=test2.txt&dir=%2Ftest12"
loadfil.../test12
"NetworkError: 404 Not Found - https://mydomain.com/index.php/core/preview.png?file=%2Ftest12%2Ftest2.txt&c=5477&x=32&y=32&forceIcon=0"
```

Please help - advise!

**Comment by DeepDiver1975** [comment] 2016-02-01 14:25
Looks like the keys for that folder (better for the files inside the folder) are not found.
Did you backup the files_encryption folder of the user within the data directory?

Try to restore the keys.

**Comment by DeepDiver1975** [comment] 2016-02-01 14:26
> Since I couldn't find proper way/documentation on how to backup/restore files when encryption is enabled, I simply tar.gz-ed files and restored them - expected behaviour would be of course when this files are restore owner can access them.

@schiesbn @carlaschroder do we have documentation about this somewhere? THX

**Comment by mislav-eu** [comment] 2016-02-01 14:30
I will check it out and let you know.

Also about documentation - there is explanation, but only for non-encryption related stuff. I'll also test it out how it is when:
- user changes password and how is it with restore then (I guess password changes encryption keys)
- if user is deleted, how to restore it and his data from backup
- if I want to migrate everything to new server

And this is all when encryption is enabled.

**Comment by mislav-eu** [comment] 2016-02-02 08:23
Update: 
> Did you backup the files_encryption folder of the user within the data directory?

No, as I didn't knew. I've tried now and there is some progress. After I've done the same thing as above, I was getting this shared file error, however when I placed back also folder inside of files_encryption situation was the following:
- I was able to read .txt files
- nothing else was possible, this includes .pdfs - error:
PDF.js v1.0.712 (build: 6969ed4)
Message: Unexpected server response (0) while retrieving PDF "https://mydomain.com/index.php/apps/files/ajax/download.php?dir=%2Ftest_folder&files=ownCloud_Server_Administration_Manual.pdf".

- also docs and images were also throwing errors:
/tmp/mozilla_mislav/kQbY7AVM.jpg.part could not be saved, because the source file could not be read.
/tmp/mozilla_mislav/sTarsMf6.docx.part could not be saved, because the source file could not be read.

Also, if I try to run decrypt command I receive error:
$ sudo -u www-data php occ encryption:decrypt-all userX

{"reqId":"LL648SrdZN5+XJ8gsYBU","remoteAddr":"","app":"PHP","message":"Call to a member function get() on null at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/updater.php#76","level":3,"time":"2016-02-02T07:47:26+00:00"}

Is there anything else that must be done for other-related-stuff?

**Comment by PVince81** [comment] 2016-02-02 09:52
@mislav-eu I suspect that the file size in the database doesn't match the unencrypted size but it's the encrypted size. So far it's not clear how the file size could become wrong, maybe it was a result of running "occ files:scan".

Since you're on 8.2.2 you could try with this patch: https://github.com/owncloud/core/pull/22008
This should automatically fix the wrong file sizes when downloading a file twice. (first download fixes it but fails, second one should work)

**Comment by PVince81** [comment] 2016-02-02 09:52
CC @MorrisJobke another case of restored encrypted files from backup

**Comment by mislav-eu** [comment] 2016-02-02 10:25
@PVince81 how exactly should I test this? I've changed the script /my_owncloud/lib/private/files/stream/encryption.php

and tried to do the same as above + download it few times, same problem

Am I doing something wrong?

**Comment by PVince81** [comment] 2016-02-02 10:26
How did you change the script ? Did you use the `patch -p1 < patchfile.patch` command ?

Please try redownloading it, we just found a bug in that PR so needs repatching.

**Comment by PVince81** [comment] 2016-02-02 10:26
Download as patch: https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/22008.patch

**Comment by mislav-eu** [comment] 2016-02-02 10:35
I did like you said, result is:

# patch -p1 < 22008.patch 
patching file lib/private/files/stream/encryption.php
patching file lib/private/files/stream/encryption.php

and same problem, I keep getting messages: 
/tmp/mozilla_mislav0/1umyztOX.jpg.part could not be saved, because the source file could not be read.

However, if I try to download e.g. image + doc or image + pdf together, then it's working (multiple files). I'm not sure if this is because of the patch, as I didn't test this before, but when you want to download few files, owncloud creates a .zip file and once this is downloaded, I can open files and they're not corrupted - downloading them one by one - then they're corrupted.

**Comment by PVince81** [comment] 2016-02-02 11:05
If a zip file works, then it's very likely to be the file size issue.
Because a zip file doesn't need to know the size in advance.

The reason why Firefox doesn't manage to download it is because the "Content-Length" header (the size the server says) doesn't match the number of bytes the server returned.

Have you tried downloading the same file twice ? The second time it should work.

**Comment by mislav-eu** [comment] 2016-02-02 11:13
> Have you tried downloading the same file twice ? The second time it should work.
Yes, 5-10 times, same problem.

I've tested it with chrome and no problems. So I guess this is firefox related problem? Please note that in both browsers pdf preview is not working, it stops at around 80% - but if you download it from chrome, it works. (zip file works normal there also)

I will test other things mentioned and get back here if I found some problems with encryption app.

**Comment by PVince81** [comment] 2016-02-02 11:18
Something to try: find the entry of one of the broken files in the "oc_filecache" table, then manually set its size to "-1". Then download that file twice. It should trigger the repair.

**Comment by PVince81** [comment] 2016-02-02 11:18
So far I'm assuming that you're running 8.2.2 by the way.

**Comment by mislav-eu** [comment] 2016-02-02 12:52
Yes, I'm running 8.2.2.

Here is the result:
> update oc_filecache set size="-1" where name="3923511_187678037986761_228371050_n1.jpg";
Query OK, 2 rows affected (0.00 sec)
Rows matched: 2  Changed: 2  Warnings: 0

MariaDB [test_do_ownc_db]> select * from oc_filecache where name="3923511_187678037986761_228371050_n1.jpg" \G
*************************** 1. row ***************************
          fileid: 5554
         storage: 55
            path: files/test_folder/3923511_187678037986761_228371050_n1.jpg
       path_hash: 4ce666741b14ef360bc0b5cbdcc932a6
          parent: 5549
            name: 3923511_187678037986761_228371050_n1.jpg
        mimetype: 4
        mimepart: 3
            size: -1
           mtime: 1454398485
   storage_mtime: 1454398485
       encrypted: 0
unencrypted_size: 0
            etag: a5cdb042fe19f2159b64d1cb3cf746db
     permissions: 27
*************************** 2. row ***************************
          fileid: 5560
         storage: 55
            path: files_encryption/keys/files/test_folder/3923511_187678037986761_228371050_n1.jpg
       path_hash: 1139af1f5be29baf5a3911a9b9ad4456
          parent: 5555
            name: 3923511_187678037986761_228371050_n1.jpg
        mimetype: 2
        mimepart: 1
            size: -1
           mtime: 1454417392
   storage_mtime: 1454398485
       encrypted: 0
unencrypted_size: 0
            etag: 56b0a5f0dffe2
     permissions: 31
2 rows in set (0.00 sec)

After that I've tried to download file few times and same problem - size is updated in "oc_filecache" table after that, but problem persist.

**Comment by PVince81** [comment] 2016-02-02 12:57
Hmm, ok let's try this.
Download the file using the ZIP technique. Then check the exact size of this file and compare it to the value that was set in the database. Are they the same ?

**Comment by mislav-eu** [comment] 2016-02-02 13:05
>  select * from oc_filecache where name="3923511_187678037986761_228371050_n1.jpg" \G
*************************** 1. row ***************************
          fileid: 5554
         storage: 55
            path: files/test_folder/3923511_187678037986761_228371050_n1.jpg
       path_hash: 4ce666741b14ef360bc0b5cbdcc932a6
          parent: 5549
            name: 3923511_187678037986761_228371050_n1.jpg
        mimetype: 4
        mimepart: 3
            size: 42969
           mtime: 1454398485
   storage_mtime: 1454398485
       encrypted: 0
unencrypted_size: 0
            etag: a5cdb042fe19f2159b64d1cb3cf746db
     permissions: 27
*************************** 2. row ***************************
          fileid: 5560
         storage: 55
            path: files_encryption/keys/files/test_folder/3923511_187678037986761_228371050_n1.jpg
       path_hash: 1139af1f5be29baf5a3911a9b9ad4456
          parent: 5555
            name: 3923511_187678037986761_228371050_n1.jpg
        mimetype: 2
        mimepart: 1
            size: 1068
           mtime: 1454418284
   storage_mtime: 1454398485
       encrypted: 0
unencrypted_size: 0
            etag: 56b0a96d0a2d7
     permissions: 31
2 rows in set (0.01 sec)

- local file size 43,0 kB (42969 bytes)

It's the same, question is only if this encrypted version should have size 1068 ?

**Comment by PVince81** [comment] 2016-02-02 13:08
1068 is the size of the key, ignore it.

The file's size is 42060 bytes.
But I also see that the column "encrypted" is 0, so looks like the file is not considered as encrypted ?

Can you check in "data/$user/files/..." the size of the file on disk ?

**Comment by mislav-eu** [comment] 2016-02-02 13:13
Size of that file on disk is 64k

**Comment by mislav-eu** [comment] 2016-02-03 08:58
Owncloud client seems to have some issues as well with this restored files. Most of the restored encrypted files are fine and I can read them without any issues (just like through chrome), but e.g. pdf downloading is keep failing and failing with message:
3.2.2016. 9:35:42test_folder/ownCloud_Server_Administration_Manual.pdf           ownCloud                      Error downloading https://mydomain.com/remote.php/webdav/test_folder/ownCloud_Server_Administration_Manual.pdf - server replied: Requested Range Not Satisfiable

Also, OC client itself does not see this test_folder, however it somehow sync it once I restore it. After download failed few times, now pdf is downloaded successfully and I can open it - it is not corrupted.

In oc log file on the server I've also found this, maybe it helps:

> Error	PHP	Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#58	2016-02-03T08:50:55+00:00

> Fatal webdav	Exception: {"Message":"HTTP\/1.1 416 The start offset (10254068) exceeded the size of the entity (9246452)","Exception":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":157}	2016-02-03T08:36:35+00:0

**Comment by PVince81** [comment] 2016-02-03 09:08
@mislav-eu this is probably because at the time where the sync client downloaded the file, it received the wrong size. Now the wrong size is cached in the client and it's trying to resume download from a piece in the middle, but cannot reach it because the size was wrong.

You might be able to make the sync client re-start the download of this file from scratch by changing the etag of that PDF file. To change the etag, reupload the file once with another client or the web UI and overwrite it.

**Comment by mislav-eu** [comment] 2016-02-03 10:22
@PVince81 I get all this, but take an example if I would need to restore multiple folders for few clients, I can't do all this manually - I would need some automated way or something similar

Also, about the first problem - I'm using firefox for years and now I would need to switch to chrome - fine, I can adapt, but can't tell that to clients. 

For me, this encryption is still not working properly as expected/as it should - and it's not described anywhere how to do proper restore/what to backup. Standard procedure with rsync/tar and mysqldump is explained, but that's standard procedure when you backup anything (when encryption is disabled). Maybe I'm doing something wrong, if so, kindly refer me to some docs or point me in right direction.

I've tried now the following:
- create folder, put some files/folders inside (txt files, docx, pdfs, images)
- change user password, delete this folder
- restore the folder from backup and it's working, but same problems as mentioned above - pdf is not getting loaded, txt files are working in both firefox/chrome, pdf preview in OC is not working in both browsers, download of pdf/images/docx not possible in firefox, in chrome everything working and files are not corrupted once downloaded

Next scenario:
- create folder, put some files/folders inside (txt files, docx, pdfs, images)
- backup everything, files and files_encrypted
- delete this user, create new one
- restore files from backup, both files and files_encrypted - error "Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."

Is the above not possible or something else must be done? I gave user the same name as it had before, e.g. MislavTestUser but I guess since new private/public keys are generated and previous files are encrypted with last private/public key and it fails? In other words, once user is deleted, there is no way to restore his data?

**Comment by PVince81** [comment] 2016-02-03 10:29
Raised documentation ticket: https://github.com/owncloud/documentation/issues/2131

When doing a backup, you need to back up the database and also the whole "data" folder  which also contains every user's private/public keys. If you restore the whole data folder from backup, then everything should already work.

If you try to restore individual files/folders, then it's more tricky: you need to restore not only the files, but also the matching keys. Then I suppose you ran "occ files:scan", but that won't work properly because it will find the wrong size and also it won't automatically set the "encrypted" flag to true. I agree that there is a bug here, I'll raise one separately.

If you lose the users's private/public keys, there is no way to get access to their data.
Unless the admin and the user enabled the recovery key mode.

**Comment by PVince81** [comment] 2016-02-03 10:32
One problem though is that restoring single files, with or without encryption, isn't very well supported I believe as it requires to run "occ files:scan" as workaround to make ownCloud recognize the file.

In general it is not recommended to manipulate anything directly inside the "data" folder.

Maybe there should be a better/official way to be able to restore individual files/folders from backups.

**Comment by PVince81** [comment] 2016-02-03 10:45
@mislav-eu I raised https://github.com/owncloud/core/issues/22096 with reproduction steps to look into the case about restoring single files/folders from backup with encryption.

Have you been able to restore all broken files so far ? If yes, then we can close this ticket in favor of #22096

**Comment by mislav-eu** [comment] 2016-02-03 10:56
@PVince81 

> If you try to restore individual files/folders, then it's more tricky: you need to restore not only the files, but also the matching keys. Then I suppose you ran "occ files:scan", but that won't work properly because it will find the wrong size and also it won't automatically set the "encrypted" flag to true. I agree that there is a bug here, I'll raise one separately.

Thanks, but I'm only one having this problems? I know you have many users, even those using enterprise version, none of them noticed this problems? Or they just don't do restore of encrypted data? 
Anyway, it somehow worked, occ files:scan does scan all data and it is visible in the OC again, but there are problems mentioned above.

> If you lose the users's private/public keys, there is no way to get access to their data.
Unless the admin and the user enabled the recovery key mode.

Recovery key is enabled under both user/admin - would there be a way then to restore data if user is deleted and I want to restore it? I have both keys/recovery keys/data before it was deleted.

> In general it is not recommended to manipulate anything directly inside the "data" folder.

If user(s) delete files/folders, then it's required and this will happen sooner or later, so that's why I went to test everything out. 
I'm also worried now about you saying backup all data before doing upgrade - what if I have 100GB + data, how exactly would I backup that or if something goes wrong with encryption? Users would use all data then or files would be corrupted. Maybe now, if we have all keys and recovery ones, but that is backuped on regular basics, together with the database.

> Have you been able to restore all broken files so far ? If yes, then we can close this ticket in favor of #22096

Not all. ".txt" extension files are working without issues in both firefox/chrome and in OC client. e.g. docx, images, pdf download is not working in firefox, but it's working in chrome. It only works in firefox if you try to download multiple files, then it's downloaded as .zip and it works. Next, pdf preview of files is not working in both browsers, but as mentioned, you can download them in chrome. Restored folder is not visible in OC client (only default Documents/Pictures are visible), but OC client is somehow aware of this folder and it syncs files - pdf download as mentioned failed, but I guess thanks to your patch above after few time re-try, it successfully downloaded. Files synced with OC client are not corrupted, same as if you try to do in chrome, but files downloaded from firefox are corrupted.

**Comment by PVince81** [comment] 2016-02-03 10:59
So far for you, for every file you restored from backup, you need to set the "encrypted" flag to 1 in the database. Then with the patch from https://github.com/owncloud/core/pull/22008, let the sync client of users redownload the files. Or the files will need to be downloaded at least once to have the size fix itself automatically. (the size only fixes itself if the encrypted flag is set to 1)

That's inconvenient but the only way so far.

**Comment by mislav-eu** [comment] 2016-02-03 14:39
@PVince81  Ok, I will test it out. Do I need to change this encrypted flag to 1 only on the file located under files/path or also in files_encryption/keys/files/path ?

**Comment by PVince81** [comment] 2016-02-03 14:42
only for the files under "files/path". That flag tells the encryption app that the file is encrypted and needs to be processed.

**Comment by mislav-eu** [comment] 2016-02-05 15:12
@PVince81 It works! 

Once I set encrypted flag to 1, I was able to download files, even through firefox and I didn't have to re-try few times, it worked in very first try. However, please note that size did not get updated in table oc_filecache, it stills differ from local file size. But yeah...it works.

**Comment by mislav-eu** [comment] 2016-02-10 15:42
@PVince81 I want to confirm also this this is also working in the following scenario:

1) user have some files
2) user change his password
3) I delete one folder and restore it from backup
4) I change flag in database and I'm able to download files through both firefox/chrome and owncloud desktop client don't have any problems

**Comment by PVince81** [comment] 2016-03-04 17:46
I think this is correct. The password of the user is only used to encrypt the user's private key.
But the private key itself stays the same, and is used to decrypt the file keys, etc.

I'll close this ticket. The file size auto-repair has been merged and more work is required to provide a more streamlined way to restore from backups: https://github.com/owncloud/documentation/issues/2131

Also related: https://github.com/owncloud/core/issues/18225

**Closed by PVince81** 2016-03-04 17:46 UTC
Labels: app:encryption

**Comment by PVince81** [comment] 2018-06-13 08:21
Setting encrypted flag to 1 will only work if you're lucky and for files that were only ever written once.
You need to check the oc_filecache.encrypted value for each file in the backup DB and set that value.
This cannot be automated, leaving closed.

See https://github.com/owncloud/documentation/issues/4201 for adjustment to documentation. (the encrypted > 1 thing exists since OC 9.1 at least)
