### ISSUE TITLE
Duplicate folders when users is added to more than one group

### ISSUE THREAD

**Issue by SMITR1** [owncloud/core#25559] opened 2016-07-21 19:12 UTC
### Steps to reproduce
1. Created few users
2. Added users to applicable groups
3. Shared files with with groups with different privileges

### Expected behaviour
As with Owncloud 9.0.1, If file X is shared with three different groups and user 1 is assigned those three different groups, user 1 would only have seen the file once when he logs in.

### Actual behaviour
With the current updates from 9.0.4, If file X is shared with three different groups and user 1 is assigned those three different groups, user 1 sees 3 file X's (etc.file  X, file X(1) and file X(2)).

### Server configuration
**Operating system**: Ubuntu Linux 16.04

**Web server**: Apache version 2.4.18

**Database**: MySQL version 5.7.12

**PHP version:** PHP 7.0.4-7ubuntu2.1 

**ownCloud version:** (see ownCloud admin page)
9.1

**Updated from an older ownCloud or fresh install:**
9.0.1

**Where did you install ownCloud from:*
Owncloud Website .tar download

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: true
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - music: true
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - direct_menu
  - encryption
  - external
  - files_external
  - rainloop
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocu99kn2juhm',
  'passwordsalt' => 'Ws1P9IPvcBaXTVkALF3E9vXrrOWf6j',
  'secret' => 'OvK+Pie9JMtk7YyDEKZJbhJxgZYQh49PLvoLmZyK8JhykSU0',
  'trusted_domains' => 
  array (
    0 => '10.0.0.5',
    1 => 'linux-server',
    2 => '25.57.97.88',
  ),
  'datadirectory' => '/Disk1/data',
  'overwrite.cli.url' => 'http://10.0.0.8/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Administrator',
  'dbpassword' => '*******************************',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'outlook.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.live.com',
  'mail_from_address' => 'owncloud.linux-server',
  'mail_smtpport' => '587',
  'mail_smtpname' => '**************************************************',
  'mail_smtppassword' => '***********',
  'mail_smtpsecure' => 'tls',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 8

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-07-21 20:19
@SMITR1 Duplicate of https://github.com/owncloud/core/issues/25555 and / or https://github.com/owncloud/core/issues/24575

**Comment by PVince81** [comment] 2016-07-22 05:46
Thanks for the report. Yes, it's a known issue. Please follow up in https://github.com/owncloud/core/issues/24575

**Closed by PVince81** 2016-07-22 05:46 UTC
