### ISSUE TITLE
Fix placement of div#notification-container in DOM

### ISSUE THREAD

**Issue by strehlst** [owncloud/core#17072] opened 2015-06-22 10:59 UTC
In public.php (browser) and template core/templates/layout.user.php
Don't know if change there would affect any other notifications within the application.

`div#notification-container` is child of `div#body-login > div.wrapper > div.v-aling`
![current notification](https://cloud.githubusercontent.com/assets/545960/8280442/8f128696-18dd-11e5-8f18-b82f0750df50.jpg)

`div#notification-container` should be direct child of `div#body-login`
![how it should be](https://cloud.githubusercontent.com/assets/545960/8280447/949cc7de-18dd-11e5-9792-4d009d70a316.jpg)

**Comment by DeepDiver1975** [comment] 2015-06-22 11:31
@strehlst thanks a lot - you can submit a pull request to fix it right away if you like.

@jancborchardt FYI

**Comment by strehlst** [comment] 2015-06-22 11:54
@DeepDiver1975 The placement in layout.user.php (or layout.guest.php) seems correct. I don't know the code well enough (and currently don't have that much time to dive into it) to see why this happens and thus how to fix it.

**Comment by jancborchardt** [comment] 2015-06-22 14:27
@strehlst didn’t you state the solution in your original post? :)

Otherwise we’ll look into it, cc @owncloud/designers

**Comment by strehlst** [comment] 2015-06-23 14:11
@jancborchardt In my initial post, I only proposed what I supposed should be done after manipulating the DOM within the browser to fix the problem. :)
The `div#notifcation-container` placed as child element of `div#body-login > div.wrapper > div.v-align` is contradictory to what is defined in layout.user.php (or layout.guest.php?). As I don't have a profound understanding of the entire architecture*  and cannot take the time to get deeper into it, someone who's familiar with it should have a look :)

* I am not even sure if I am looking at the correct files, just searched for "notification-container" using grep in my personal ownCloud 8.0.4 instance

**Comment by DeepDiver1975** [comment] 2015-06-25 11:59
postponing this to 8.2 - 8.1 should be closed these days

**Comment by DeepDiver1975** [comment] 2015-06-25 11:59
pull requests to fix this are welcome any time

**Comment by raghunayyar** [comment] 2015-08-01 11:44
I can fix this, can you tell me how to reproduce it? cc @jancborchardt self assigning.

**Comment by strehlst** [comment] 2015-08-03 12:41
@raghunayyar I can't reproduce it instantly as my instance does not load documents into the editor at the moment and I don't have the time to fix it right now. Try to open a document in the document editor, share it publicly. Then use the share link after you revoked the public access. You should get the warning mentioned above.

**Comment by davitol** [comment] 2017-02-27 08:06
I cannot reproduce this issue in master, maybe it is already fixed. Let's close it? @PVince81

**Closed** 2017-02-27 09:11 UTC
Labels: bug, comp:core, design, junior job, sev4-low
