### ISSUE TITLE
Problem in activity notifications by email

### ISSUE THREAD

**Issue by colomailbe** [owncloud/core#15381] opened 2015-04-02 15:12 UTC
System info: OC 8.0.2 / Apache2 / MySQL 5.6.17 / PHP 5.6.1
cron.php: run by crond
mail system: smtp with TLS

Here's the scenario to explain what happens:
(with all notifications enabled in mail and stream for both users):

On Day1, UserA creates a folder "ToUserB" and share it with UserB
-> UserA receive notification (mail body: * You created "ToUserB" * You shared "ToUserB")
-> UserB don't receive any notification
On Day 5, UserA decide to add files in folder ToUserB
-> UserA is notified that he added files (mail body: * You created "ToUserB\file1.txt")
-> UserB does not receive anything

So for the moment it seems that notifications sent by email are only self changes ?! which in my opinion is completely useless. UserA of course knows what it has done... it's UserB that should be notified that now he have files in the folder that has been shared to him !!

The stream makes a lot more sense. Activity will show every actions where UserB is involved (his own activity but also and especially what UserA has shared to him).

Can you suggest me, what I could do to fix this ? (or even better provide us with a patch?).

Thanks, regards,
Colo

[EDIT] Forgot to say that nothing special is logged in the log file (even in debug mode), only entries are that app:"mail" has sent something.

**Comment by nickvergessen** [comment] 2015-04-02 16:31
Does UserB have a email address set as well as selected the relevant types in the personal section?

**Comment by colomailbe** [comment] 2015-04-02 16:45
Yes UserB have email address set (and like UserA, he also receive by email only his own changes).
Both have under "Login > Personal > Notifications" everything checked except "Notify about your own actions via email". I admit, I haven't test yet with that option enabled, maybe that'll do the trick and will "Notify about others actions via email" :-) I'll keep you posted.

**Comment by colomailbe** [comment] 2015-04-02 20:48
And funily enough enabling "Notify about your own actions", enables the notification of what other people shared to you. So there's already a quick workaround but the code should be adapted to work the other way around (read as intended ;-) Anyway thanks nice open-source dev!

**Comment by nRaecheR** [comment] 2015-05-12 20:18
Same here with OC8.0.3, updated from 7.0.x. 

After updating the OC installation email notifications have stopped for files that another user is uploading to a folder I shared with him. That worked with all older versions without a glitch. Uploading a file myself triggers a notification mail but this is useless as said in the original post.

Just for the record : All notification options are enabled.

**Comment by nickvergessen** [comment] 2015-05-13 07:56
Duplicates:
https://github.com/owncloud/activity/issues/289

Fixed with:
https://github.com/owncloud/activity/pull/291/files
https://github.com/owncloud/activity/pull/297/files

**Closed by nickvergessen** 2015-05-13 07:56 UTC
Labels: bug, duplicate

**Comment by nRaecheR** [comment] 2015-05-13 17:54
@nickvergessen I don't think that this is a duplicate of the bug mentioned. This one is about notifications that won't be received when other users are uploading files to a share of yoursel not about unwanted notifications of our actions. Are you sure the patched actually fix this problem too ?

**Comment by nickvergessen** [comment] 2015-05-15 08:04
I'm pretty sure, because it compared `$selfAction = substr($subject, -5) !== '_self';` instead of `$selfAction = substr($subject, -5) === '_self';` but that was still black magic. So it wrongly marked non-self actions as self-actions and the otherway around.
