### ISSUE TITLE
Do not allow to share objects mounted with SMB/CIFS using OC login

### ISSUE THREAD

**Issue by rasos** [owncloud/core#23095] opened 2016-03-10 14:13 UTC
One can not share objects in case of authentication with "SMB/CIFS using OC login"
(see https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/external_storage/auth_mechanisms.html#password-based-mechanisms  and 
discussion on https://github.com/owncloud/documentation/issues/1927)

Thus there should be no sharing icon and entry form at objects mounted this way, currently it shows "Share with users, groups or remote users" and throws an error notification. 

Disabling sharing completely is not an option either. 

We are on OC 8.1.5 - any hope that link sharing will be possible with "SMB/CIFS using OC login"? Meanwhile we will step back and will allow only SMB/CIFS mounts to be defined individually by users.

**Comment by PVince81** [comment] 2016-03-14 10:42
Note that starting with 9.0 it will be possible to disable sharing for individual external storages.

But you're right that sharing should be automatically disabled when not supported due to storing login in session.

@Xenopathic didn't we have this before ? Maybe it was implemented in 8.2 but not 8.1 ?

**Comment by Xenopathic** [comment] 2016-03-14 12:02
In stable8.1 we have the necessary code: https://github.com/owncloud/core/blob/stable8.1/apps/files_external/lib/smb_oc.php#L94-L100 so there must be some GUI stuff that is breaking. As the OP mentioned, actually trying to create a share throws an error, so the check is doing what it is supposed to, the problem is the GUI is still displaying that sharing is possible

**Comment by PVince81** [comment] 2016-12-08 18:42
Duplicate of https://github.com/owncloud/core/issues/23322

**Closed by PVince81** 2016-12-08 18:42 UTC
Labels: bug, sev3-medium
