### ISSUE TITLE
Unable to generate a URL for the named route "calendar_index" as such route does not exist.

### ISSUE THREAD

**Issue by lukas-schulze** [owncloud/core#18317] opened 2015-08-14 14:25 UTC
I'm using ownCloud 8.1.1 on a Debian 7 server with nginx and php-fpm.
If I try to update apps like calendar or contacts, I get the following error message:

__Unable to generate a URL for the named route "calendar_index" as such route does not exist.__

I thought It might be related to the use of nginx. However, I cannot find any related information to fix this problem.
Does anyone know, how to solve this?

![image](https://cloud.githubusercontent.com/assets/820580/9262402/f9d9c786-4214-11e5-9509-b7dba5259295.png)

**Comment by MorrisJobke** [comment] 2015-08-14 15:05
Duplicate of #18224

**Closed by MorrisJobke** 2015-08-14 15:05 UTC

**Comment by jonathannz** [comment] 2015-08-25 03:30
How is this a duplicate of #18224 ? 
I also have this issue. I successfully used the Admin update system to go from 8.1.0.8 to 8.1.1.3. No errors, no apparent issues.
But when I try to now update the Calendar app to 0.7.3 I get the error the OP has cited. But the duplicate posts you refer to, as far as I can tell, are related to the core update having issues.
So do I post a repeat of this OPs post, and have it marked as duplicate? Or is there another way forward?
