### ISSUE TITLE
OC8 cron.php creates massive Server-Load

### ISSUE THREAD

**Issue by tchara** [owncloud/core#14087] opened 2015-02-11 07:10 UTC
Just updated from 7.0.4 to 8 and my hosting provider complained about cron.php putting massive load on the server. Checking the 44.5GB ./data/owncloud.log, I got the following:

### Steps to reproduce
1. Have OwnCloud 7.0.4 over at all-inkl.com
2. Update to OwnCloud 8
3. Make cron.php be called from KAS-CronJob every 5 minutes

### Expected behaviour
Normal server load

### Actual behaviour
cron.php creates server load to an extend that other customers complain and that the hosting provider terminates your OwnCloud instance.

### Server configuration
**Operating system**:
no clue
**Web server:**
Apache httpd
**Database:**
MySQL
**PHP version:**
5.something
**ownCloud version:** (see ownCloud admin page)
8
**Updated from an older ownCloud or fresh install:**
updated from 7.0.4
**List of activated apps:**
default after update as well as Calender and Contacts
**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'isthisthesecretfromthetemplate?',
  'passwordsalt' => 'salty',
  'datadirectory' => '/www/htdocs/hostinguser/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.8',
  'dbname' => 'd017ad03',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'd017ad03',
  'dbpassword' => 'password',
  'installed' => true,
  'overwritehost' => 'ssl-account.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/cloud.example.com',
  'overwritecondaddr' => '^123.123.123.123$',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail.example.com:587',
  'mail_smtpport' => '587',
  'mail_smtpauth' => true,
  'mail_smtpname' => 'gotone',
  'mail_smtppassword' => 'password',
  'mail_smtpauthtype' => 'LOGIN',
  'forcessl' => true,
  'maxZipInputSize' => 524288000,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '4',
  'trusted_domains' => 
  array (
    0 => 'ssl-account.com',
  ),
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'example.com',
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Problem is independent of the used client. Don’t know what the hosting provider uses... I use Firefox 31.4.0 ESR on Windows and OwnCloud Android App 1.6.2
**Operating system:**
Problem is independent of the used client. Don’t know what the hosting provider uses... I use Windows 7 SP1 and Android 4.4.4
#### Web server error log
Don’t have access to that.
Insert your webserver log here
Don’t have access to that.
#### ownCloud log (data/owncloud.log)
It is 44.5GB in size! I’ll give you the tail...
...
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"8d3b846370a16341f54c5403b918a080","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
{"reqId":"dfaa296cf015f6cebf322b44166c2a33","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/hostinguser\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-11T06:11:31+00:00"}
```
#### Browser log
```
Don’t have access to the hosting provider’s browser log. By the time I had tried to access my OC, it has had been terminated by the hosting provider.
```

**Comment by RealRancor** [comment] 2015-02-11 08:42
Hi,

the posted error message itself are a duplicate of: https://github.com/owncloud/core/issues/13953

No idea if they are causing this high load.

**Comment by DeepDiver1975** [comment] 2015-02-11 09:14
Is search lucene enabled? Its cron jobs are quite intense

**Comment by AW-UC** [comment] 2015-02-11 11:36
Had same cron issue when dealing with #13953. Went away after patching tempmanager.php. Try the hotfix I posted there: https://github.com/owncloud/core/issues/13953#issuecomment-73430406 (or look at the fixing commit: https://github.com/owncloud/core/commit/45e3cbefc9e069d5c904ed8961504551a51ce735).

**Comment by tchara** [comment] 2015-02-11 14:03
The suggested bug fix / feature addition seems to work for now. The logfile does not grow and the creation of a temp directory within my shared hosting folder (in combination with the modifications to base.php and config.inc.php) makes the cron.php at least run without errors. - Currently, I am testing how the server load is behaving (i.e. waiting and seeing if the hosting provider complaons again).

**Comment by DeepDiver1975** [comment] 2015-02-11 14:09
> Having a setting for the error log (like the 'tempdirectory' setting) would be handy for shared hosting...
> 
> {"reqId":"921b5cb6bf462e982c448beda1e67add","remoteAddr":"123.123.123.123","app":"PHP","message":"Unknown: open_basedir restriction in effect. File(\/logs\/errors\/PHP_errors.log) is not within the allowed path(s): (\/www\/htdocs\/hostinguser\/:\/tmp:\/usr\/bin:\/www\/htdocs\/hostinguser:\/bin:\/usr\/local\/bin:\/usr\/share\/php:\/dev\/urandom) at Unknown#0","level":3,"time":"2015-02-11T14:00:25+00:00"}

hmm - I really wonder if this is related to the owncloud code base - we don't try to write to that file afaik

**Comment by protree** [comment] 2015-02-20 17:50
I'm experiencing the same issue. once cron.php is started it runs forever, leading to a 100% server load. I already patched tempmanager.php, without any luck.

I don't get any error messages when running cron.php from console and I don't get any log-entries.

**Comment by tchara** [comment] 2015-02-20 19:50
Have you tried the return suggested by all-ink.com in #14153 ?

**Comment by protree** [comment] 2015-02-21 00:39
Yes I did this, but this wasn't the failure for me. I fixed the issue by disabling search_lucene, it ran out of memory when indexing some very big PDF-ebooks.

**Comment by enoch85** [comment] 2015-07-06 23:01
@tchara Still an issue? Please close this otherwise. Thank you.

**Closed** 2015-07-07 05:02 UTC
Labels: needs info
