### ISSUE TITLE
No option to move or copy selected items without drag and drop

### ISSUE THREAD

**Issue by strugee** [owncloud/core#19569] opened 2015-10-05 02:55 UTC
When you select multiple items in the web interface, a bar appears at the top with the option to download or delete the items. It should also be possible to move and copy them.

**Comment by RealRancor** [comment] 2015-10-05 05:07
Hi,

there is an app providing both functionalities available here:

https://apps.owncloud.com/content/show.php/Files+move?content=150271

**Comment by strugee** [comment] 2015-10-06 03:07
@RealRancor thanks. This should really be in core, though.

**Comment by PVince81** [comment] 2016-07-11 09:04
Closing as duplicate of https://github.com/owncloud/core/issues/10656

**Closed by PVince81** 2016-07-11 09:04 UTC
Labels: enhancement
