### ISSUE TITLE
User created groups

### ISSUE THREAD

**Issue by Helios07** [owncloud/core#24825] opened 2016-05-25 07:41 UTC
I would like to propose a feature request regarding the sharing function. 
In bigger installations, users tend to share data with large user numbers (100+). With autocompletion deactivated (as in our case), this can become a lot of work. I would like to have a function where users you have shared with once are stored, so they can be reused more easy.
In addition it would be extremely helpful if one could create groups out of these list to facilitate sharing even further. LDAP groups are of no help here because the users cannot create those.

**Comment by Xenopathic** [comment] 2016-05-25 08:11
Duplicate of #8201

**Closed by Xenopathic** 2016-05-25 08:11 UTC
