### ISSUE TITLE
Sabre/dav - Upgrade to version 3.x

### ISSUE THREAD

**Issue by osos** [owncloud/core#17039] opened 2015-06-19 08:17 UTC
Next Sabre/Dav has been released.

To ensure support from Sabre, it should be upgraded: http://sabre.io/blog/2015/sabredav-3-release/

**Comment by PVince81** [comment] 2015-06-19 08:35
Thanks for the reminder, let's have a look for 8.2.

**Comment by PVince81** [comment] 2015-07-02 08:44
http://sabre.io/dav/upgrade/2.1-to-3.0/

**Comment by PVince81** [comment] 2015-07-02 08:52
- [ ] 3rd party update: https://github.com/owncloud/3rdparty/pull/182
- [ ] core + regression test
- [ ] calendar + regression test
- [ ] contacts + regression test

**Comment by DeepDiver1975** [comment] 2015-07-02 09:07
hmm .. I just spent two days on fixing carddav in the contacts app - do we want to invest into this again? now?

**Comment by PVince81** [comment] 2015-07-02 09:08
I hoped it would go quicker this time, but am now meeting issues with authentication.
So it looks like it will indeed take more time.

**Comment by phsc** [comment] 2015-07-20 07:53
SabreDAV 3.1 is coming closer:
https://github.com/fruux/sabre-dav/releases

But probably this is out of scope, due to the required minimum PHP Version, which will be 5.5 (Owncloud needs to support PHP 5.4):
https://github.com/fruux/sabre-dav/issues/647

**Comment by PVince81** [comment] 2015-09-22 08:41
@DeepDiver1975 move to 9.0 ?
As stated above the upgrade wasn't smooth so there are risks of regressions/breakage at this point. (and we're past feature freeze)

**Comment by PVince81** [comment] 2015-11-19 09:05
Upgrading to Sabre 3 should also fix range request + streaming: https://github.com/owncloud/core/issues/15321

**Comment by jospoortvliet** [comment] 2015-11-19 09:27
@select you were asking about this last night - the streaming thing. This doesn't solve your entire problem but it would help the user experience... Perhaps upgrading Sabre/DAV is something to sink your teeth in ;-)

**Comment by select** [comment] 2015-11-20 15:53
@jospoortvliet thanks, will look into it

**Comment by jospoortvliet** [comment] 2015-11-23 14:09
@select go review https://github.com/owncloud/core/issues/20636 ;-)

**Comment by DeepDiver1975** [comment] 2015-11-24 15:21
> @select go review #20636 ;-)

merged

**Closed** 2015-11-24 15:21 UTC
Labels: technical debt
