### ISSUE TITLE
user dropdown menu doesn't work with Safari/Chrome App on iPad (iOS 8)

### ISSUE THREAD

**Issue by finius** [owncloud/core#14639] opened 2015-03-02 11:30 UTC
When logging into ones ownCloud account using the build in Safari App or Google Chrome App on Apples iPads running iOS 8, the menu pane in the upper right corner (I mean the dropbox panel that shows the users displayname) is not "popping down"/opening. So one can't access these personal menues on this kind of tablet device - i.e. the administrator can't access the user list or the admin page using the browser apps above.

**Comment by nickvergessen** [comment] 2015-03-02 12:12
does the menu on the left side work?

**Comment by finius** [comment] 2015-03-02 12:39
@nickvergessen If you're talking about the app-dropdown (Files, Activities, etc) right beside of the owncloud logo then yes, this is working fine.

**Comment by tflidd** [comment] 2015-03-02 15:38
Left menu also broken on OC 7.0.4 with Safari on iOS 8 (iPad). Can as well confirm that the App-Menu on the left opens.

**Comment by finius** [comment] 2015-03-02 22:43
@tflidd you mean right menu is also broken, right? 
@nickvergessen could determine same behaviour on iPhone 6

**Comment by LukasReschke** [comment] 2015-03-03 09:00
Works here on my iPhone 5S: https://i.imgur.com/R7MN4LL.jpg

**Comment by tflidd** [comment] 2015-03-03 10:56
@finius Yes it's the right menu. 
@LukasReschke The demo.owncloud.org works for me as well.
On my setup, I found out that the menu on the right opens in the Picture and Document app, but not on the Files, Activity, Calendar, or Contact app! I have the impression that it "wants" to open but is closed again instantly. Opera Mini behaves the same.

My apps installed on OC 7.0.4:
Enabled:
 - activity
 - admin_dependencies_chk
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_encryption
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - gallery

**Comment by nickvergessen** [comment] 2015-03-03 11:05
Sounds like the loading order of the JS files is important.
Can you try to get the network overview from your browser?

**Comment by jancborchardt** [comment] 2015-03-27 14:52
I'm pretty sure this was a z-index CSS issue which has been resolved. Should work with latest ownCloud 8.

**Comment by finius** [comment] 2015-03-27 15:06
@jancborchardt: yes, Problem seems to be solved. Now the problem is the main file/folder list which now is nearly unable to get scrolled on iOS 8 on iPhone 6. Can someoone commit this new issue with ownCloud 8?

**Comment by jancborchardt** [comment] 2015-03-27 15:17
@finius does it work on http://demo.owncloud.org for you? Or can you test with a new ownCoud 8 instance?

**Comment by finius** [comment] 2015-03-27 15:23
@jancborchardt  just tested it with the demo site - same behaviour as om my Installation. seems to be associated with slide effect that shows up the link list with the sharing/favorites menue

**Comment by jancborchardt** [comment] 2015-03-27 15:41
So basically this is a duplicate of https://github.com/owncloud/core/issues/11193 then? ;)

**Comment by finius** [comment] 2015-03-27 15:53
@jancborchardt hm, not quite sure. this problem hasn't been existed before upgrading to oc8.

**Comment by finius** [comment] 2015-04-12 09:32
it definitely worked on owncloud 7 with iOS8 devices.

**Comment by jancborchardt** [comment] 2015-04-12 09:48
The original issue is solved though so I’ll close this. @finius can you either comment on #11193 or open a new issue for the separate problem?

**Closed by jancborchardt** 2015-04-12 09:48 UTC
Labels: bug
