### ISSUE TITLE
Bug on public links

### ISSUE THREAD

**Issue by ITMaya** [owncloud/core#28299] opened 2017-07-04 17:39 UTC
Hi Support,

I'd like to report a bug I'm able to reproduce on release 10.0.2.
This happens in our case but I don't know if you can reproduce it on your side.

When you create a new public link and check option "Allow editing", you go on Save to create your link, but option "Allow editing" is not saved. I have to go back on the public link configuration, check it again (wouldn't appear checked) and then Save again to get it working.

I was getting Forbidden 403 errors until I noticed this setting wasn't save at first link creation.

I hope this can help.

Regards,
John

**Comment by phil-davis** [comment] 2017-07-05 04:01
I can't reproduce the problem on a first try.
Please fill out the full issue template so we might be better able to try and replicate.
(e.g. exactly which browser/version you are trying this from will be useful to know)

**Comment by SergioBertolinSG** [comment] 2017-07-05 07:31
### Steps to reproduce

1. Create a folder 'shared'.
2. Share by link 'shared' folder. Enable "Allow editing".
3. Close the sidebar.
4. Open the link configuration

### Expected behaviour
"Allow editing" checkbox is enabled.

### Actual behaviour
"Allow editing" checkbox is disabled.


### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}


**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```
```

**Comment by SergioBertolinSG** [comment] 2017-07-05 07:46
Hmm doesn't happen in CE in current master.

**Comment by phil-davis** [comment] 2017-07-05 07:47
When you say "Share by link", do you mean the Public Links tab, and click on "Create public link"?
and
"Open the link configuration" - you mean click on the work "shared" to open the sharing sidebar, then click on "Public Links" and then click the "gear" icon to display the public link settings?

Because I can;t make it happen on Chrome or Firefox with current master.

**Comment by SergioBertolinSG** [comment] 2017-07-05 07:57
Yeah, me neither. Only happening in 10.0.2. It is fixed in stable10 and master, so closing.

**Closed by SergioBertolinSG** 2017-07-05 07:57 UTC
Labels: bug, sev2-high

**Comment by ITMaya** [comment] 2017-07-05 16:20
I meant regardless the folder name I want to share. And yes using "Create public link" as specified in my previous message.
Yes, the link configuration by using the gear icon on the sharing sidebar.

So anyway, looks like a 10.0.2 problem then, I thought this version was a stable one?! Is there any version upper I could go to get it fixed?

John

**Comment by SergioBertolinSG** [comment] 2017-07-05 16:23
@ITMaya stable10 is the name of the branch. The fix for this issue will be included in the next maintenance release (10.0.3).

**Comment by ITMaya** [comment] 2017-07-05 16:25
Cool, thanks Sergio!
