### ISSUE TITLE
Sharing via group does not work in all cases

### ISSUE THREAD

**Issue by tps800** [owncloud/core#11295] opened 2014-09-25 10:51 UTC
Assume some groups with users:
 Group A holds users a, b, c
 Group B holds users c, d, a, z

Now one shares files
 Files I, II are shared to group A
 Files II, III are shared to group B
 Files IV, II are shared to user b and group B

Now in theory
  Users a, c can access files I, II
  Users b can access files I, II, III, IV
  Users a, c, d, z can access files II, III, IV

Doing the very same with ownCloud leads to
  Users c can access files I, II
  Users a, b can access no files
  Users c, d, z can access files II, III, IV

Now my question: is there any way to printout what is shared by a specific user to which other users and which files these have access to?

I would like to tell apart if this is an "user error" or a "system error" (at the moment I am tending to a system error, since checking carefully it really looks like there is a problem having users in two different groups, sharing shared files between these groups.

--
Environment: Oracle Linux 6.5 (likely to be migrated to 7.x)
Server: Apache 2.2.15
Database: PostgreSQL 9.3.5
Client: ownCloud-Client 1.6.3
OC-Version: ownCloud 7.0.2 (nightly builds)
PHP-Version: PHP 5.5.16

**Comment by PVince81** [comment] 2015-03-28 11:49
@tps800 does it mean that the issue is fixed now for you in 7.0.3 ? If not you could try 7.0.5 too.

If it still happens, please let us know how it behaves now.

Closing it now, please reopen if still having issues. Thanks.

**Closed by PVince81** 2015-03-28 11:49 UTC
Labels: bug, sharing
