### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate during upgrade to 8.1

### ISSUE THREAD

**Issue by gergles** [owncloud/core#18293] opened 2015-08-13 17:27 UTC
When upgrading owncloud using the FreeBSD pkg package from version 8.0.4 to 8.1, I see the following message in the upgrader web UI:
```
Updating ownCloud to version 8.1.0, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "activity" to 2.0.1
Updated "files_sharing" to 0.6.2
Updated "files_trashbin" to 0.6.3
Updated "files_versions" to 1.0.6
GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate
The update was unsuccessful. Please report this issue to the ownCloud community.
```

However, refreshing the page and attempting the upgrade again appears to work with no ill effects.

**Comment by karlitschek** [comment] 2015-08-13 23:56
@LukasReschke any idea what can be done of freebsd?

**Comment by LukasReschke** [comment] 2015-08-14 06:24
Well, to be honest we should just stop supporting any kind of external package as they are often wrongly done.

Please do a ls over the config folder and report the resultd back.

**Comment by gergles** [comment] 2015-08-14 16:35
It was calendar & contacts (the only other apps I had enabled.)

I had to blow them away from the owncloud apps dir and then manually download them (the app store download buttons were also broken with that same cURL error, despite setting the CA path in php.ini) and install the new versions. It went into upgrade mode then everything started working again.

**Comment by alvar-freude** [comment] 2015-08-16 08:20
The same with owncloud-8.1.1_1 via pkg on FreeBSD.

Maybe the execution of curl does not use the configured Proxy? Owncloud is running here in a jail without network access because ugly insecure PHP stuff, and maybe it's not the packaging but a wrong call to curl in Owncloud?

**Comment by alvar-freude** [comment] 2015-08-16 08:28
Repeating the update helps, but when i try to update "Documents" app, the same error appears:
cURL error 60: SSL certificate problem: unable to get local issuer certificate

**Comment by alvar-freude** [comment] 2015-08-16 08:48
There is a problem with the certificates. Sadly owncloud does no loggen, even after setting log level to 0 (debug, to syslog), the is no log message about this. 
Direct usage of curl (CLI) works as intended: it complains about he certificate when it is self-signed; when accessing owncloud.com it accepts the cert.

So: what's the URL for the download? Is there a „valid“ certificate? Why is there no logging?

**Comment by alvar-freude** [comment] 2015-08-16 08:56
Info about Curl errors (error 60): 
http://curl.haxx.se/libcurl/c/libcurl-errors.html

Description: http://flwebsites.biz/posts/how-fix-curl-error-60-ssl-issue

**Comment by alvar-freude** [comment] 2015-08-16 11:39
It seems, that the code uses the wrong cert file for downloading apps:

According to the proxy logs, OwnCloud accesses GitHub when downloading/updating e.g. the "Documents" app.
Using curl manually with the default certificate file it works fine:

`curl -x my.proxy:3128 https://github.com`

There are the following cert bundles in the owncloud distribution:

```
apps/files_external/3rdparty/aws-sdk-php/Guzzle/Http/Resources/cacert.pem
apps/files_external/3rdparty/google-api-php-client/src/Google/IO/cacerts.pem
apps/files_external/3rdparty/Dropbox/OAuth/ca-bundle.pem
3rdparty/rackspace/php-opencloud/tests/OpenCloud/Tests/Common/cacert.pem
3rdparty/guzzle/http/Guzzle/Http/Resources/cacert.pem
```

Using curl manually with them, it works with all but not with `./apps/files_external/3rdparty/google-api-php-client/src/Google/IO/cacerts.pem`:

```
curl -x 10.23.42.111:32451 --cacert apps/files_external/3rdparty/google-api-php-client/src/Google/IO/cacerts.pem https://github.com > /tmp/tmp.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by alvar-freude** [comment] 2015-08-16 11:43
When replacing apps/files_external/3rdparty/google-api-php-client/src/Google/IO/cacerts.pem with an other cert file, the same error persists. So, this is not the used file.

**Comment by alvar-freude** [comment] 2015-08-16 12:08
`config/ca-bundle.crt`is fine, too.

**Comment by blitz** [comment] 2015-08-19 08:26
I have the same issue here upgrading owncloud 8.0.3 to 8.1.1 in a FreeBSD jail. Is there a good workaround?

**Comment by blitz** [comment] 2015-08-20 20:43
Manually downloading and replacing the apps seems to restore normal operation. Would be good to know what the actual problem is, so this doesn't hit again during the next update.

**Comment by rahra** [comment] 2015-09-06 20:19
Today I upgraded to 8.1.1 from 7.0.4 and I have the same issue. When trying to enable Contacts or Calender I get the error message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate'. I updated all CA bundles (and there are a lot within ownCloud) to the latest version (2nd of Septemer). Curl and OpenSSL work fine on this server -- I verified a hundred times.

WIth tcpdump I could narrow down the problem more specifically: when enabling Contacs the ownCloud core tries to connect to s3.amazonaws.com. A DNS lookup then returns a CNAME to s3-1.amazonaws.com to which it tries to connect. But it seems that the SSL certificate verification fails. This can simply be verified with Firfox. Just connect to https://s3-1.amazonaws.com .

The question is "Why does it connect to Amazon at all?"

I redirected the DNS lookup for this host which immediately changes the error message depending on what you do with the redirected packets.

**Comment by rahra** [comment] 2015-09-06 21:00
I could now solve this issue. The reason is that s3-1.amazonaws.com is signed by A VeriSign Generation 1 Class 3 certificate which was removed from the Mozilla CA bundle because it is only a 1024 bit RSA certificate. You can download the certificate from here https://www.symantec.com/content/en/us/enterprise/verisign/roots/Class-3-Public-Primary-Certification-Authority.pem and add it to the CA bundle manually (just cat it to the end of the file).

**Comment by alvar-freude** [comment] 2015-09-18 22:49
When rahra is true (and I think he is!), then it is no bug in FreeBSD. The Bug is in Linux, because it uses an old CA Bundle, that it does NOT complain about insecure certificates …

**Comment by alvar-freude** [comment] 2015-09-18 23:18
Works fine when adding the mentioned certificate to owncloud/config/ca-bundle.crt.

**Comment by h-2** [comment] 2015-09-21 21:55
Yikes, what a bumpy upgrade. Thanks for the instructions here, but @owncloud-gods please fix the certificates!

**Comment by hmeine** [comment] 2015-09-22 14:00
Same problem here; if ca-bundle.crt does not exist yet in config, do I need to fetch it from somewhere (where?), or is the above Amazon certificate sufficient?

**Comment by rahra** [comment] 2015-09-28 05:11
At the beginning of the file you find the date of the file and its original URL. It is nothing else than a storage for all certificates you trust. It is the same as the built-in certificates of the Mozilla browser which is considered to be some kind of "standard".

**Comment by PVince81** [comment] 2015-10-09 17:11
Is this still happening with 8.1.3 ? I thought cert issues had been fixed

**Comment by hmeine** [comment] 2015-10-09 17:34
@rahra: Your answer sounds like you assume the file was there, but that was my problem in the first place – I did not have *any* ca-bundle in the config directory, and obviously there was no sufficient default in the hoster's OS.

**Comment by h-2** [comment] 2015-10-28 19:26
With 8.2.0 it has gotten even worse: the workaround doesn't work anymore :(

After upgrade the contacts and calendar apps get deactivated. They show that they have upgrade, but the upgrades fail with the known error message. The ca-bunde.crt disappeared from config and has apparently moved to resources/config/, but appending the amazon cert to that file won't help. Instead it even makes the upgrade button disappear.

Using the ca-bundle.crt from KDE (as mentioned above) actually works, but it is wrong! Owncloud should ship a ca-bundle that includes all the certificates that it needs. Whats the point of not including it?

edit: Great now I am stuck with #18224

**Comment by PVince81** [comment] 2015-10-29 06:32
I'm not familiar with the ca-bundle.crt, maybe @LukasReschke can check ?

I looked at my own server OC 8.2.0 updated from RPM on openSUSE 13.2 and I can see a "ca-bundle.crt" inside of "resources/config" but not "config".

Is everyone here using FreeBSD ? Whoever made the package might have forgotten to include that file ?

**Comment by PVince81** [comment] 2015-10-29 06:37
@GuillaumeBibaut are you able to help to check the FreeBSD package ? (you did a long time ago as I remember :smile:) Thanks.

**Comment by Chillibear** [comment] 2015-11-16 11:57
Fixed on my FreeBSD install by removing the OwnCloud `/usr/local/www/owncloud/resources/config/ca-bundle.crt` file and instead symlinking the file to the cert bundle installed by `ca_root_nss` freebsd package, i.e.

`ln -s /usr/local/share/certs/ca-root-nss.crt /usr/local/www/owncloud/resources/config/ca-bundle.crt

**Comment by alexandreteles** [comment] 2015-11-17 10:44
Fixed on Ubuntu 14.04 migrating from 8.1.3.0-b8c0250e to 8.1.4.2 symlinking to the cert bundle distributed with the system:

`ln -s /etc/ssl/certs/ca-certificates.crt /var/www/owncloud/config/ca-bundle.crt`

**Comment by DeepDiver1975** [comment] 2015-11-17 10:54
looks like we can close this issue?

**Comment by alexandreteles** [comment] 2015-11-17 11:03
I don't think so, it's not solved as we just provided a workaround. Owncloud should ship with a updated ca-bundle.crt or state in the documentation that you need to symlink system's ca-bundle to your owncloud config dir.

**Comment by alvar-freude** [comment] 2015-11-17 15:21
No, I don't think we can close this issue.
OwnCloud should provide the correct certificate(s), on only the correct one.
Or do you trust … let's say 'TÜBİTAK UEKAE Kök Sertifika Hizmet Sağlayıcısı - Sürüm 3' to install Software on your Server? Or CA 沃通根证书? This both are examples from the Mozilla CA.

**Comment by zparihar** [comment] 2015-11-19 06:48
Chillibear 's work around worked for me (Thanks!). 

I'm running FreeNAS, but did not install the Owncloud Plugin.  I installed a Jail and I Installed Owncloud from the repositories and configured it with MySQL.  I had this problem and tried the work around and was now able to install the "Documents" App.

Please make the Fix Owncloud Guys.

**Comment by RealRancor** [comment] 2015-11-19 07:51
Ref: https://github.com/owncloud/core/issues/20028

**Comment by WN1188** [comment] 2015-11-21 20:00
Have a setup matching the one described by @zparihar .  The symlink suggestion from @Chillibear did not work in my case. I'm upgrading apps by manually downloading from http://apps.owncloud.com/. Not the smoothest upgrade.

**Comment by Chillibear** [comment] 2015-11-21 22:04
@WN1188 THat's interesting and a pity.  I had hoped to submit a PR for the FreeBSD port to implement my fix.  So just to confirm you do have the `ca_root_nss` package installed so the cert bundle is present at `/usr/local/share/certs/ca-root-nss.crt`?  Also are you using the port/package of  OwnCloud (i.e version 8.2.0)?

**Comment by WN1188** [comment] 2015-11-21 22:47
@Chillibear - Yeah, I have the ca_root_nss package installed, and I've verified the presence of the symlink you'd suggested.

When attempting to update any ownCloud Apps under Apps->Not Enabled, I get the following:
`cURL error 60: SSL certificate problem: unable to get local issuer certificate`

Installed as packages on a FreeBSD  9.3-RELEASE-p28 jail:
`owncloud-8.2.0`
`ca_root_nss-3.20`

**Comment by tobiasKaminsky** [comment] 2015-12-05 10:47
For me executing "c_rehash" as root helped!

Ubuntu 14.04.3 LTS
ow 8.2.

**Comment by sonologic** [comment] 2015-12-17 17:40
I just upgraded to 8.2.1 on a FreeBSD 10.1 host that is completely up to date. I don't use the owncloud freebsd package, but have installed owncloud manually. 

There's an app i have installed, bookmarks, that says it has an update available. However, when I try to update I get the dreaded 'cURL error 60: SSL certificate problem: unable to get local issuer certificate'.

I tried the work-around of symlinking to the /usr/local/share/certs/ca-root-nss.crt file from the ca_root_nss package, but no luck with that either (even after stopping and restarting the web server just in cache some cache is holding old values somewhere).

**Comment by Tr4sK** [comment] 2016-02-15 13:21
Hi,
I had the same issue, me and my friend are using cacert.org authority.
I had some issue when he tried to share some files over federated cloud.
Got this when triyen to open a shared file:

```
{"reqId":"aXneseXidNlU\/qEolLUJ","remoteAddr":"192.168.0.101","app":"index","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\RequestException\",\"Message\":\"Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:\\nerror:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed\\n[file] \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] fopen(): Failed to enable crypto\\n[file] \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] fopen(https:\\\/\\\/cloud.guisse.me\\\/owncloud\\\/public.php\\\/webdav\\\/): failed to open stream: operation failed\\n[file] \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] Undefined variable: http_response_header\\n[file] \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 407\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\RingException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(24): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(232): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(192): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/http\\\/client\\\/client.php(123): GuzzleHttp\\\\Client->get('https:\\\/\\\/cloud.g...', Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/dav.php(347): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/cloud.g...', Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\DAV->fopen('', 'r')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'r')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('', 'r')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1021): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('', 'r')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(871): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/comptes_coloc....', Array, 'r')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview\\\/txt.php(47): OC\\\\Files\\\\View->fopen('\\\/comptes_coloc....', 'r')\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview.php(1136): OC\\\\Preview\\\\TXT->getThumbnail('\\\/comptes_coloc....', 2048, 2048, false, Object(OC\\\\Files\\\\View))\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview.php(770): OC\\\\Preview->generatePreview(264866)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/preview.php(795): OC\\\\Preview->getPreview()\\n#19 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/preview.php(63): OC\\\\Preview->showPreview()\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#21 [internal function]: __lambda_func(Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_1407', Array)\\n#23 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/core\\\/preview.p...')\\n#24 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":51}","level":3,"time":"2016-02-15T14:04:08+01:00"}
```

This did the trick:
`ln -sf  /etc/ssl/certs/ca-certificates.crt /var/www/owncloud/resources/config/ca-bundle.crt`

**Comment by PVince81** [comment] 2016-06-14 10:30
Is anyone still having these issues with a recent FreeBSD and ownCloud 8.2.5 or 9.0.2 ?
If yes, please reopen.

**Closed by PVince81** 2016-06-14 10:30 UTC
Labels: bug
