### ISSUE TITLE
Moving files and folders function in WebUI

### ISSUE THREAD

**Issue by faulix** [owncloud/core#24586] opened 2016-05-12 03:57 UTC
I think there should be a feature in the WebUI to move files and folder in the structure. Currently it's only possible to move files and folders into a subfolder, but not upwards or to a different part of the tree.

**Comment by RealRancor** [comment] 2016-05-12 04:17
There is an app allowing exactly this:

https://apps.owncloud.com/content/show.php/Files+move?content=150271

**Comment by faulix** [comment] 2016-05-12 04:29
This app has several serious issues, which don't get commented/solved. Therefore I assume there is no active development anymore and therefore not an option.

Just one example: Moving files/folders changes the modified date of the file/folder, that's a no-go.

**Comment by despens** [comment] 2016-05-12 05:40
Also, the move plugin does not regard external storage. Even noer :)

**Comment by RealRancor** [comment] 2016-05-12 06:12
Ok, that sounds bad. However this also looks to me like a duplicate of https://github.com/owncloud/core/issues/10656

**Comment by faulix** [comment] 2016-05-12 07:23
It does. But there is nothing moving and no plan for implementation. Maybe the developer can reconsider the priority.

**Comment by RealRancor** [comment] 2016-05-12 07:32
Having a second issue about the same issue won't help moving things faster.

**Comment by MorrisJobke** [comment] 2016-05-12 07:38
> Ok, that sounds bad. However this also looks to me like a duplicate of #10656

Closing as duplicate of https://github.com/owncloud/core/issues/10656

**Closed by MorrisJobke** 2016-05-12 07:38 UTC
