### ISSUE TITLE
cancel and share again, still favorite

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#13216] opened 2015-01-09 19:29 UTC
### Steps to reproduce
1. log in with admin
2. create a folder "lol"
3. go into "lol" and create a text file "lol_lol.txt"
4. share the folder "lol" with user1
5. log in with user1
6. tag folder "lol" and file "lol_lol.txt" as favorite
7. log in with admin
8. cancel sharing "lol" with user1
9. log in user1, and check --"lol" is gone
10. log in with admin and share "lol" with user1 again
11. log in as user1 and check

### Expected behaviour
neither "lol" nor "lol_lol.txt" are not tagged as favorite

### Actual behaviour
both "lol" and "lol_lol.txt" are tagged as favorite

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** owncloud 8 git master

**Updated from an older ownCloud or fresh install:** 

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 34.0.5

**Operating system:** ubuntu 13.10

**Comment by dttpy** [comment] 2015-01-09 19:29
@PVince81

**Comment by PVince81** [comment] 2015-01-12 09:36
@SergioBertolinSG @jnfrmarks another one for the test plan ?

**Comment by PVince81** [comment] 2015-01-12 09:37
This issue is due to the tags not being automatically deleted when a file is unshared.
See https://github.com/owncloud/core/issues/12858

**Comment by DeepDiver1975** [comment] 2015-01-12 09:58
@PVince81 8.0? 8.1?

**Comment by PVince81** [comment] 2015-01-12 10:06
I've set it to 8.1

**Comment by PVince81** [comment] 2015-05-15 09:13
With a bit of luck this might work already on 8.1 thanks to the recent trashbin/deletion fixed.

@dttpy mind to retest this on master / 8.1 beta ? Thanks.

**Comment by dttpy** [comment] 2015-05-18 18:43
tested on master, and this problem is still there, sorry

**Comment by PVince81** [comment] 2015-09-21 13:26
This is because orphaned tags aren't cleant up automatically.
We'd need to add background job that clears orphaned tags: https://github.com/owncloud/core/issues/12858#issuecomment-93461945

**Comment by nickvergessen** [comment] 2015-10-27 15:54
Closing as duplicate of #12858

And it is also arguably intended behaviour. The file is still the same, becuase favorites are based on file ID. So why shouldn't the tag be there anymore?

**Closed by nickvergessen** 2015-10-27 15:54 UTC
Labels: bug, feature:tags, sev4-low
