### ISSUE TITLE
Trying to activate app on production stable9, doesn’t work (dependency analyzer)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23668] opened 2016-03-30 17:27 UTC
It seems to be enabled, but doesn’t show in the app switcher. (News app in this case) owncloud.log:

```json


[
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 1 passed to OC\\App\\DependencyAnalyzer::analyze() must be of the type array, null given, called in \/lib\/private\/app.php on line 1100 and defined at \/lib\/private\/app\/dependencyanalyzer.php#52",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  },
  {
    "reqId": "G4dZm8Xq\/Ayl5vyBzPgc",
    "remoteAddr": "93.202.88.105",
    "app": "PHP",
    "message": "Argument 2 passed to OC\\App\\DependencyAnalyzer::analyzeOC() must be of the type array, null given, called in \/lib\/private\/app\/dependencyanalyzer.php on line 66 and defined at \/lib\/private\/app\/dependencyanalyzer.php#280",
    "level": 3,
    "time": "2016-03-30T16:41:44+00:00",
    "method": "POST",
    "url": "\/index.php\/settings\/ajax\/enableapp.php",
    "user": "jan"
  }
]


```

@DeepDiver1975 @BernhardPosselt any idea?

**Comment by BernhardPosselt** [comment] 2016-03-30 17:35
Dunno, maybe database versions https://github.com/owncloud/news/blob/master/appinfo/info.xml#L27 ?

**Comment by BernhardPosselt** [comment] 2016-03-30 19:22
Can't reproduce btw

**Comment by jancborchardt** [comment] 2016-03-30 19:51
@BernhardPosselt well … I use ownCloud with MySQL. And core as well as all the other apps work. News should support the normal setup as well.

**Comment by BernhardPosselt** [comment] 2016-03-30 19:53
I'm using postgres and sqlite, did not check on MySql but I doubt that the issue

**Comment by BernhardPosselt** [comment] 2016-03-30 20:03
@jancborchardt the issue is that the argument https://github.com/owncloud/core/blob/master/lib/private/app/dependencyanalyzer.php#L52 here is not an array but null

**Comment by BernhardPosselt** [comment] 2016-03-30 20:05
Which is passed in here: https://github.com/owncloud/core/blob/stable9/lib/private/app.php#L1100

**Comment by BernhardPosselt** [comment] 2016-03-30 20:07
Here is the statement that breaks it: https://github.com/owncloud/core/blob/stable9/lib/private/app.php#L618 which was added by @MorrisJobke https://github.com/owncloud/core/commit/ef49f6ef5de3cd5321083a5be392caee1b6e6cdc ;)

**Comment by BernhardPosselt** [comment] 2016-03-30 20:08
@jancborchardt probably related to the issue it fixes, aka open_basedir ;) yw

**Comment by BernhardPosselt** [comment] 2016-03-30 20:17
BTW, this is the reason why mixing booleans, nulls and other types sucks. It is not obvious after various levels of nesting which values can actually be returned where and less often used paths in your program lead to bugs. Furthermore it makes no sense to return false when running a method called getAppPath(). 

What's that even supposed to mean? The app path is false? If it means that it could not be calculated because an error occured, throw an exception. If the app path does not exist on the filesystem there are multiple solutions: throw an exception (like a file not found exception or io error which is pretty common in other languages) or *maybe* return null or an empty Optional. But please don't return false ;D \</rant>

Although PHP is a weakly typed language you should add some rules for having only one return type, add static analysis and maybe take a look at the Optional pattern. cc @DeepDiver1975

**Comment by MorrisJobke** [comment] 2016-03-30 20:36
> What's that even supposed to mean? The app path is false? If it means that it could not be calculated because an error occured, throw an exception. If the app path does not exist on the filesystem there are multiple solutions: throw an exception (like a file not found exception or io error which is pretty common in other languages) or maybe return null or an empty Optional. But please don't return false ;D </rant>

It's not that we don't know it. It's only not simply possible to fix everything from instant. We are working on this, but it's not a easy one-shot task.

**Comment by BernhardPosselt** [comment] 2016-03-30 20:38
@MorrisJobke i know ;)

**Comment by MorrisJobke** [comment] 2016-03-30 21:37
Fix is in https://github.com/owncloud/core/pull/23676

**Closed** 2016-03-31 20:21 UTC
Labels: bug, in progress
