### ISSUE TITLE
User email adresses not saved

### ISSUE THREAD

**Issue by Etienne5131** [owncloud/core#32057] opened 2018-07-16 13:26 UTC
Hi everyone !

I use a OC version 10.0.3 stable. 
My operating system is Raspbian GNU/Linux 9 (stretch).
My web server is Apache 2 v2.4.25.
Php version PHP 7.0.30.
Database is MySql MariaDB 10.1.

I configured my notification mail as a personal external hotmail mail xxx@hotmail.fr (by defining smtp). The test button send the mail to check the notification mail works. This part works.

1st case:
I saved a mail address (which is the same as the previous notification mail xxx@hotmail.fr) to my non-admin user (and the confirmation link has been clicked). When I try the forgotten password link of the login page, the page tell a mail has been sent. But the mail does not come (not in reception nor undesirable mail).

The log file of OC gives me
```
"url":"\/index.php\/lostpassword\/email","message":"Could not send reset email because there is no email address for this username. User: ***"}
```

This shows that the user email address has not been saved. 

2nd case:
When I was logged in with my personal account, I shared a folder with another user. I tried to check the email notification checkbox in the sharing pannel, but it displayed me that was impossible to send a notification mail to the other user with log message
```{"reqId":"gBcF1ktXu85Nan5N9Epy","level":3,"time":"2018-07-16T15:17:26+02:00","remoteAddr":"x.x.x.x","user":"x","app":"PHP","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Undefined offset: 1 at \/var\/www\/owncloud\/lib\/private\/Mail\/Message.php#59"}
{"reqId":"gBcF1ktXu85Nan5N9Epy","level":3,"time":"2018-07-16T15:17:26+02:00","remoteAddr":"x.x.x.x","user":"x","app":"sharing","method":"POST","url":"\/index.php\/core\/ajax\/share.php","message":"Can't send mail to inform the user about an internal share: Address in mailbox given [@] does not comply with RFC 2822, 3.6.2."}
```

Configuration info:

```
{
    "system": {
        "instanceid": "occyrzl2hec3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.251",
            "owncloud.xxx.fr",
            "www.owncloud.xxx.fr"
        ],
        "datadirectory": "\/home\/etienne\/dataowncloud",
        "overwrite.cli.url": "owncloud.xxx.fr",
        "overwritehost": "owncloud.xxx.fr",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "default_language": "fr_FR",
        "installed": true,
        "forcessl": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "log_authfailip": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp-mail.outlook.com",
        "mail_from_address": "xxx",
        "mail_domain": "hotmail.fr",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 60,
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "theme": ""
    }
}
```

I have put the info that was useful for me. If you need more, do not hesitate.

Thanks!

**Comment by ownclouders** [comment] 2018-07-16 13:48
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/18825 (Admin user interface does not save email adresses), https://github.com/owncloud/core/issues/27000 (User email not saved), https://github.com/owncloud/core/issues/2905 (FreeBsd - Recovery Email is not being saved), https://github.com/owncloud/core/issues/15318 (Admin email not saving), and https://github.com/owncloud/core/issues/17789 (User details not saved unless click Enter).

**Comment by PVince81** [comment] 2018-07-17 15:03
Duplicate of https://github.com/owncloud/core/issues/27667

Please upgrade to 10.0.8 or wait a few days for 10.0.9

**Closed by PVince81** 2018-07-17 15:03 UTC
