### ISSUE TITLE
LDAP wizard configuration, status from Configuration incorrect to Configuration OK is not being updated using active directory. 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15944] opened 2015-04-29 16:12 UTC
### Steps to reproduce
1. In assisted mode configure a complete configuration using active directory.
2. Set on the before mentioned settings to a wrong value.
3. Status switch to incorrect / red
4.  Set on the before mentioned settings to a right value again.

### Expected behaviour
Status should switch to correct / green

### Actual behaviour
Status keeps switched to incorrect / red

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by blizzz** [comment] 2015-05-07 18:11
Cannot reproduce. Tried to set port to a wrong value and back, worked, and the same with login filter (removed username, so %uid was missing, and back).

**Comment by blizzz** [comment] 2015-05-07 18:13
The other thing that comes to mind could have been caused by what was fixed by https://github.com/owncloud/core/pull/16122, OTOH then it should not have been green at all….

**Comment by blizzz** [comment] 2015-05-07 18:13
@davitol can you check again with current master, and if this fails with a new configuration?

**Comment by davitol** [comment] 2015-05-08 08:58
@blizzz Now the bahaviour iis different. It behaves as it is described in #16192 

ownCloud version: OC 8.1 beta 1

**Comment by blizzz** [comment] 2015-05-08 11:41
@davitol then i close this one here in favor of #16192

**Closed by blizzz** 2015-05-08 11:41 UTC
Labels: app:user_ldap, bug, sev2-high
