### ISSUE TITLE
Federated Shares don´t show up in the "shared with you" folder

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17407] opened 2015-07-06 09:06 UTC
### Steps to reproduce
1. Have two Owncloud-Servers running 
2.Share a file or folder from on to the other ownCloud

### Expected behaviour
The File shared via Federated share should appear in the "shared with you folder"
### Actual behaviour
Federated Shares are not in the "shared with you folder"

### Server configuration
Ubuntu 14.04

LAMP Stack 

**ownCloud version: 8.04 community and Enterprise** (see ownCloud admin page)

**fresh install:**

Browser : Goodle Chrome

**Comment by PVince81** [comment] 2015-07-06 13:23
Duplicate of https://github.com/owncloud/core/issues/9098

**Closed by PVince81** 2015-07-06 13:23 UTC
