### ISSUE TITLE
update to 8.0.3 fails

### ISSUE THREAD

**Issue by jakobo99** [owncloud/core#16381] opened 2015-05-16 14:49 UTC
After updating my ubuntu 14.04 server I went to the webinterface to login and install the update.

The update fails giving the following error message:

```
An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
```

What can I do?

**Comment by RealRancor** [comment] 2015-05-16 16:52
Hi,

Duplicate of: https://github.com/owncloud/core/issues/16008 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097 , https://github.com/owncloud/core/issues/16157 , https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218 , https://github.com/owncloud/core/issues/16280

Documentation for this is also available here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

**Comment by MorrisJobke** [comment] 2015-05-18 07:31
Solution: https://github.com/owncloud/core/issues/16008#issuecomment-98889298

**Closed by MorrisJobke** 2015-05-18 07:31 UTC
Labels: duplicate
