### ISSUE TITLE
560 is not a valid Directory resource

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#25292] opened 2016-06-28 14:42 UTC
### Steps to reproduce
Don't know.

### Expected behaviour
No error.

### Actual behaviour
owncloud.log is full of 560 is not a valid Directory resource errors

### Server configuration
**Operating system**: CentOS 7.2

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page)
latest stable 9.x release

**Updated from an older ownCloud or fresh install:**
Update from 8.2

**Where did you install ownCloud from:**
Open Build Repo

**Signing status (ownCloud 9.0 and above):**

Can't check server status as I have another error related to that.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_mv
  - gallery
  - galleryplus
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocagvsml5uip",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": [
            "xxxxxx",
            "xxxxx"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "proxy": "10.244.9.34",
        "trusted_domains": [
            "owncloud.lcsb.uni.lu",
        ],
        "theme": "",
        "debug": "false",
        "datadirectory": "\/mnt\/data\/oc-data",
        "overwrite.cli.url": "https:\/\/owncloud.lcsb.uni.lu\/",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "lcsb-oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_from_address": "lcsb-sysadmins",
        "mail_domain": "uni.lu",
        "mail_smtphost": "smtp.uni.lu",
        "mail_smtpport": "25",
        "maintenance": false,
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "preview_libreoffice_path": "\/bin\/libreoffice",
        "updatechecker": false
    }
}
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### ownCloud log (data/owncloud.log)
```
{"reqId":"V3KMsXG9vlDMT-zSuGCiUQAAAEI","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:53+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/HC02214.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
{"reqId":"V3KMsSP@NoDaxE-Zy5tLzwAAAE4","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:54+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/HC02213.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
{"reqId":"V3KMsV76foc9Qf@KGm3BFwAAACg","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:54+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/HC02217.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
{"reqId":"V3KMsYV-IKonOukj3hVmRgAAAEk","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:54+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/HC02216.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
{"reqId":"V3KMsXG9vlDMT-zSuGCiUgAAAEI","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:54+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/L2aadp.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
{"reqId":"V3KMsl76foc9Qf@KGm3BGAAAACg","remoteAddr":"10.244.9.34","app":"PHP","message":"rewinddir(): 560 is not a valid Directory resource at \/var\/www\/html\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-06-28T16:41:54+02:00","method":"GET","url":"\/remote.php\/webdav\/programModelling\/projects\/atomMapping\/results\/Summer15\/data\/Recon2\/molfiles_implicit_H\/L_dpchrm.mol","user":"8c81828a-320211e6-994aa42e-df26fa49"}
```

**Comment by RealRancor** [comment] 2016-06-28 16:58
Looks like a duplicate of https://github.com/owncloud/core/issues/25289

**Comment by PVince81** [comment] 2016-06-28 17:28
yes

**Closed by PVince81** 2016-06-28 17:28 UTC

**Comment by Trefex** [comment] 2016-06-28 17:51
Thanks for that. I wasn't sure as the error code was slightly different.

**Comment by PVince81** [comment] 2016-06-28 18:06
It's not an error code, it's just the directory id :smile:

**Comment by Trefex** [comment] 2016-06-28 18:19
Haha ok. Well that settles that!
