### ISSUE TITLE
CSP blocking unsafe-inline contect on default installation

### ISSUE THREAD

**Issue by monreal** [owncloud/core#10314] opened 2014-08-09 17:30 UTC
### Steps to reproduce
1. on a default OC7 installation, visit any page (files module for example)
2. see firefox' or firebug's javascript console

### Expected behaviour
No CSP errors

### Actual behaviour
Some content seems to be blocked:

Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src $mypageurl 'unsafe-eval'").

### Server configuration
**Operating system**: CentOS 7
**Web server:** nginx 1.6.1
**Database:** MariaDB 5.5.37
**PHP version:** 5.4.16
**ownCloud version:** 7.0.1
**Updated from an older ownCloud or fresh install:** updated from a fresh 7.0.0 installation
**List of activated apps:** files, calendar, news, contacts, pictures, notes
**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'datadirectory' => '/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'knowledgebaseenabled' => false,
  'check_for_working_htaccess' => false,
  'enable_avatars' => true,
  'trusted_domains' => 
  array (
    0 => '...',
  ),
);

```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 33

If I add 'unsafe-inline' to the default CSP script settings, the error disappears. I am not aware of any functional problems even without 'unsafe-inline' so maybe this is something very minor and can be fixed easily on the application side?

**Comment by Bugsbane** [comment] 2015-01-06 05:51
I'm getting this too, if any data on this issue is needed.

**Comment by LukasReschke** [comment] 2015-01-06 08:15
Smells for me like an FF bug - not a that big problem at the moment since only an error is thrown but nothing happens.

I will dig into this once I have some more time - filing bugs upstream to Mozilla is not my favourite activity ;-)

**Comment by arm2arm** [comment] 2015-01-12 21:00
It looks like a FF goes too secure with Content Security Policy: this is an experimental for the moment one can stop it by: about:config -> security.csp.experimentalEnabled false.

**Comment by LukasReschke** [comment] 2015-01-12 21:06
> In OC there are some inline scripts in the CSP it is not allowed if there is no tag: unsafe-inline

Mhm? – We're actually not using inline scripts anywhere as far I know. Do you have any examples ready or am I misunderstanding you?

**Comment by arm2arm** [comment] 2015-01-12 21:50
After littlebit digging the trouble is comming from jquery-1.10.0.min.js
If you update it to recent one the warning is dissapearing.

**Comment by arm2arm** [comment] 2015-01-12 22:02
what is the proper way to upgrade the jquery in OC??

**Comment by devurandom** [comment] 2015-02-09 13:02
Same issue here. Is a fix known already?

**Comment by LukasReschke** [comment] 2015-02-09 13:03
Well, this is pretty much a false positive and as long as nothing is broken this is pretty much low priority. If something is broken then file a new issue as this is pretty much unrelated to this issue.

**Comment by devurandom** [comment] 2015-02-09 13:06
I just looked at the files: There seem to be various versions of jquery in use: 1.5.1, 1.8.14 and 1.10.0, all of which are outdated.

@arm2arm: Did you figure out how to update all these properly?

**Comment by arm2arm** [comment] 2015-02-10 11:28
@devurandom i copy simply recent one over, but probably this is not a solution for the production server.

**Comment by RealRancor** [comment] 2015-04-13 13:29
Could this be also caused by some 3rdparty apps installed?

https://apps.owncloud.com/content/show.php/Reader+%28ebook+reader%29?content=167127

for example (and IIRC some other apps too) are describing that the custom_csp_policy of ownCloud needs to be overwritten.

**Comment by LukasReschke** [comment] 2015-04-13 13:46
> Could this be also caused by some 3rdparty apps installed?

Sure. They can do all kind of voodoo. And *ewww*, THAT'S a bad and ugly workaround they describe here. However, with ownCloud 8.1 developers can specify custom policies for applications so this workaround will be gone (and don't do anything anymore anyway). Basically the policy they recommend there does make the whole CSP thing useless ;-)

**Comment by MorrisJobke** [comment] 2015-08-03 10:00
See #17758 for more info about `l10n.js` that is maybe causing this.

![bildschirmfoto am 2015-08-03 um 11 59 24](https://cloud.githubusercontent.com/assets/245432/9035343/42aeae54-39d7-11e5-9b5c-2af4ca887dec.png)

**Comment by szepeviktor** [comment] 2015-08-06 17:42
Chrome 44 says:
```
Refused to load the image 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==' because it violates the following Content Security Policy directive: "img-src 'self'".
```

**Comment by MorrisJobke** [comment] 2015-08-07 09:38
@LukasReschke ^

**Comment by szepeviktor** [comment] 2015-08-07 09:43
Sorry, this is in the `audios` app.
https://github.com/libasys/audios/blob/1a07a986bc0d4d9839bdee6a82e0387c1f29cb13/css/360player.css#L143

**Comment by LukasReschke** [comment] 2016-03-07 18:57
Custom policies are possible now. Plus this is a false positive in FF without any impact => Closing. Once jQuery 2.0 is used in core this will completely be gone.

**Closed by LukasReschke** 2016-03-07 18:57 UTC
Labels: bug, sev4-low
