### ISSUE TITLE
Bugs encoding Russian Cyrillic letters when downloading zip files through the web interface, owncloud 9.1

### ISSUE THREAD

**Issue by kalinkin-43** [owncloud/core#26251] opened 2016-09-29 14:15 UTC
The description of fixes encoding problems

[b]Steps to reproduce[/b]
to correct the problem with the coding we need to make changes to the file / var / www / owncloud / lib / private / Streamer.php
Line 66
Original:    $this->streamerInstance->addEmptyDir($rootDir);
Change:    $this->streamerInstance->addEmptyDir(iconv("utf-8", "cp866", $rootDir));
Line 69
Original:    $this->addFileFromStream($fh, $internalDir . $filename, $filesize);
Change:    $this->addFileFromStream($fh, iconv("utf-8", "cp866", $internalDir.$filename), $filesize);

[b]Expected behaviour[/b]
downloaded zip files through the web interface with rus cyrillic letters in names of files and folders without coding bugs

[b]Actual behaviour[/b]
downloaded zip files with rus cyrillic letters heve unreadeble names of files and folders

[b]Server configuration[/b]
Operating system: Ubuntu 16.04.01 TLS
Web server: apache
Database: mysql
PHP version: 7
ownCloud version (see ownCloud admin page): 9.1
Updated from an older ownCloud or fresh install: fresh install
ownCloud log: no problems

configuration:  simply config, 50 users, no encryption

**Comment by dergilb99** [comment] 2016-09-29 14:27
I cannot reproduce this behavior with OC 9.2 pre alpha.

**Comment by dergilb99** [comment] 2016-09-30 12:59
I cannot reproduce this behavior with OC 9.1.1 either.

I get this:

![3](https://cloud.githubusercontent.com/assets/13220171/18992422/7cedf008-871e-11e6-817a-61cc24ce2948.png)

:-D

**Comment by dergilb99** [comment] 2016-09-30 13:56
With 8.2.8 it works, but the the zip file's cyrillic characters get encoded:

"Россия - священная наша держава.zip"

to

"%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%20-%20%D1%81%D0%B2%D1%8F%D1%89%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F%20%D0%BD%D0%B0%D1%88%D0%B0%20%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%B0.zip"

(Tested with Firefox 49.0.1)

**Comment by PVince81** [comment] 2016-10-04 14:26
Which tool are you using to open the zip File ?
I believe that Windows zip folder doesn't work correctly with UTF-8 encoding but any other client should work fine

**Comment by dergilb99** [comment] 2016-10-04 16:10
> Which tool are you using to open the zip File ?

As for my part, I use 7zip. But that's when the download already has happened.

> I believe that Windows zip folder doesn't work correctly with UTF-8 encoding but any other client should work fine

No problems with windows zip Folder here (Windows 10 Pro (64 bit), us-en)

**Comment by kalinkin-43** [comment] 2016-10-04 19:58
(iconv("utf-8", "cp866", *****) - help us to use Windows 7 standart options to read cyrillic correctly.

**Comment by PVince81** [comment] 2016-10-04 20:46
@kalinkin-43 what client are you using ?
The Windows 7 built-in ZIP folder might also not work with UTF-8 ZIP files as it's old and incompatible.
Try with third party clients like 7Zip or Winzip or Winrar.

Closing as won't fix as we can't hard-code different encodings.

**Closed by PVince81** 2016-10-04 20:46 UTC

**Comment by dergilb99** [comment] 2016-10-05 12:19
> I cannot reproduce this behavior with OC 9.1.1 either.

I works now. Don't ask, I don't know.
