### ISSUE TITLE
"config_is_read_only = true" setting is ignored.

### ISSUE THREAD

**Issue by Equidamoid** [owncloud/core#14451] opened 2015-02-24 10:03 UTC
### Steps to reproduce
1. Revoke write permissions to /config
2. Set config_is_read_only to true
3. Try to login

### Expected behaviour
Login/password form appears

### Actual behaviour
```Cannot write into "config" directory
This can usually be fixed by giving the webserver write access to the config directory.```

### Server configuration
**Operating system**:
Linux
(remaining fields are irrelevant, IMHO)

**ownCloud version: 8.0.0.7, was upgraded from 7.x**

**The content of config/config.php:**

```
  'dbtype' => 'pgsql',
  'version' => '8.0.0.7',
  'installed' => true,
  'instanceid' => 'xxx',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '3',
  'config_is_read_only' => true,
  'appstoreenabled' => false,
  'trusted_domains' =>
  array (
    0 => 'xxx',
  ),
  'forcessl' => true,
```

The error comes from **lib/private/util.php**, line **514** (now it's [line 564](https://github.com/owncloud/core/blob/1fd1b355e46aba83917c81ddc91a369598f9e6e1/lib/private/util.php#L564)). The check sets the error flag regardless of **config_is_readonly** value. Commenting out the check fixes the issue.

**Comment by DeepDiver1975** [comment] 2015-02-24 10:11
> Revoke write permissions to /config

try to keep write permissions on config but revoke them on config/config.php

**Comment by LukasReschke** [comment] 2015-02-24 10:13
Confirmed. This seems to be indeed a bug when the session does not pass the server check… Preparing PR…

**Comment by LukasReschke** [comment] 2015-02-24 10:14
Ah no…

**Comment by LukasReschke** [comment] 2015-02-24 10:15
I did use `config_is_readonly` without `_` in the last sentence. Works fine here that way…

**Comment by Equidamoid** [comment] 2015-02-24 10:20
@LukasReschke maybe you need to logout for the error to appear. For me everythng worked fine yesterday but today I've got the error. Is the check performed before login or when session expires?

**Comment by LukasReschke** [comment] 2015-02-24 10:24
What I did:

1. Setting `'config_is_read_only' => true,` in the config.php
2. `chown root:wheel config.php`
3. `chmod 744 config.php`
4. Clean my cookies
5. Access my ownCloud instance

**Comment by Equidamoid** [comment] 2015-02-24 10:26
@LukasReschke try `chown root` and `chmod 644` for the config dir

**Comment by LukasReschke** [comment] 2015-02-24 10:27
https://github.com/owncloud/core/issues/14451#issuecomment-75730283

**Comment by LukasReschke** [comment] 2015-02-24 10:27
You can't do that on the config dir.

**Comment by DeepDiver1975** [comment] 2015-02-24 10:28
> try to keep write permissions on config but revoke them on config/config.php

@Equidamoid

**Comment by Equidamoid** [comment] 2015-02-24 10:28
@DeepDiver1975 What for?

**Comment by LukasReschke** [comment] 2015-02-24 10:33
No. This config was *never* introduced for security reasons. It was introduced for some obscure OS's not properly behaving on file locks.

**Comment by LukasReschke** [comment] 2015-02-24 10:34
If you want to have this also working on the whole config directory please file an enhancement request. Thanks!

**Comment by LukasReschke** [comment] 2015-02-24 10:34
(Closing this one for now)

**Comment by Equidamoid** [comment] 2015-02-24 10:34
@LukasReschke  ok, thanks

**Closed by LukasReschke** 2015-02-24 10:34 UTC
Labels: bug, needs info
