### ISSUE TITLE
[OC6Beta] Windows and sync client -- strange log message

### ISSUE THREAD

**Issue by ser72** [owncloud/core#5872] opened 2013-11-14 14:41 UTC
**Expected results**
all files sync

**Actual results**
Only 1 or 2 files sync and client log gets strange output

**Steps**
Create a folder with 200 files in it
Move that folder to the client sync folder
Start the sync client with logging enabled

Notice only 1 or 2 files will sync

**CLIENT LOG**

11-14 09:29:34:125 _csync_push_file: file: C:/Documents and Settings/Administrator/Desktop/Yogi/ONE/file37.txt, command: sendfile, error: Input/output error from errno 5
11-14 09:29:34:125 _csync_push_file: remember chunk: 0  (transfer id 1305647634 )
11-14 09:29:34:125 _csync_report_parent_error: Mark parent directoy `ONE` as an error
11-14 09:29:34:125 csync_vio_stat: Win32: STAT-inode for C:/Documents and Settings/Administrator/Desktop/Yogi/ONE/file123.txt: 35291
11-14 09:29:34:125 _csync_push_file: Remote repository atomar push enabled for owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file123.txt (0).
11-14 09:29:34:125 oc_module: => open called for owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file123.txt
11-14 09:29:34:125 oc_module: Stating directory owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE
11-14 09:29:34:125 oc_module: Dir owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE is there, we know it already.
11-14 09:29:34:125 oc_module: PUT request on /owncloud/remote.php/webdav/ONE/file123.txt!
11-14 09:29:34:125 oc_module: Sendfile handling request type PUT. fd 3
11-14 09:29:34:125 hbf_splitlist: hbf_splitlist: block_size: 10485760 threshold: 10485760 st_size: 100000

11-14 09:29:34:125 hbf_splitlist: hbf_splitlist: num_blocks: 1 rmainder: 100000 blk_size: 10485760

11-14 09:29:34:140 hbf_splitlist: hbf_splitlist: created block 0   (start: 0  size: 100000)
11-14 09:29:34:140 oc_module: about to send 1 block
11-14 09:29:34:140 _hbf_dav_request: HBF: Block: 0 , Start: 0 and Size: 100000
11-14 09:29:34:187 oc_module: Chunk upload completed for 'owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file123.txt' (100000 bytes out of 100000)
11-14 09:34:34:187 _csync_push_file: file: C:/Documents and Settings/Administrator/Desktop/Yogi/ONE/file123.txt, command: sendfile, error: Input/output error from errno 5
11-14 09:34:34:187 _csync_push_file: remember chunk: 0  (transfer id 1306985809 )
11-14 09:34:34:187 _csync_report_parent_error: Mark parent directoy `ONE` as an error
11-14 09:34:34:187 csync_vio_stat: Win32: STAT-inode for C:/Documents and Settings/Administrator/Desktop/Yogi/ONE/file15.txt: 35320
11-14 09:34:34:187 _csync_push_file: Remote repository atomar push enabled for owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file15.txt (0).
11-14 09:34:34:187 oc_module: => open called for owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file15.txt
11-14 09:34:34:187 oc_module: Stating directory owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE
11-14 09:34:34:187 oc_module: Dir owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE is there, we know it already.
11-14 09:34:34:187 oc_module: PUT request on /owncloud/remote.php/webdav/ONE/file15.txt!
11-14 09:34:34:187 oc_module: Sendfile handling request type PUT. fd 3
11-14 09:34:34:187 hbf_splitlist: hbf_splitlist: block_size: 10485760 threshold: 10485760 st_size: 100000

11-14 09:34:34:187 hbf_splitlist: hbf_splitlist: num_blocks: 1 rmainder: 100000 blk_size: 10485760

11-14 09:34:34:187 hbf_splitlist: hbf_splitlist: created block 0   (start: 0  size: 100000)
11-14 09:34:34:187 oc_module: about to send 1 block
11-14 09:34:34:187 _hbf_dav_request: HBF: Block: 0 , Start: 0 and Size: 100000
11-14 09:34:34:250 oc_module: Chunk upload completed for 'owncloud://192.168.1.101/owncloud/remote.php/webdav/ONE/file15.txt' (100000 bytes out of 100000)
11-14 09:34:41:546 ownCloudInfo Network Error 299 : "Error downloading http://192.168.1.101/owncloud/status.php - server replied: Internal Server Error" 
11-14 09:34:41:546 status.php returns:  "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>500 - Internal server error.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>
 </fieldset></div>
</div>
</body>
</html>
"   299  Reply:  QNetworkReplyImpl(0x465d8b8) 
11-14 09:34:41:546 No proper answer on  "http://192.168.1.101/owncloud/status.php" 
11-14 09:34:41:562 ownCloudInfo Network Error 299 : "Error downloading http://192.168.1.101/owncloud/status.php - server replied: Internal Server Error" 
11-14 09:34:41:562 status.php returns:  "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>500 - Internal server error.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>500 - Internal server error.</h2>
  <h3>There is a problem with the resource you are looking for, and it cannot be displayed.</h3>
 </fieldset></div>
</div>
</body>
</html>
"   299  Reply:  QNetworkReplyImpl(0x46a6dc8) 
11-14 09:34:41:562 No proper answer on  "http://192.168.1.101/owncloud/status.php"

**Comment by nickvergessen** [comment] 2015-02-19 15:14
Without further information I'm unable to reproduce this.
Syncing works just fine for me on windows, so I'm closing this (as the report is against oC6)
If that is still an issue, please open a new one.

**Closed by nickvergessen** 2015-02-19 15:14 UTC
Labels: bug, EE, windows server
