### ISSUE TITLE
Cannot sync files that are in remote folders.

### ISSUE THREAD

**Issue by ISibboI** [owncloud/core#18146] opened 2015-08-08 19:48 UTC
### Steps to reproduce
1. Create file F on server A
2. Share folder X from server B with server A
3. Move folder X around through As directory structure
4. Move file F into X on server A

### Expected behaviour
Sync client is able to download the folder and file from server A.

### Actual behaviour
Internal server error:

`PHP Fatal error:  Class 'SecurityLib\\Strength' not found in /srv/www/htdocs/owncloud/apps/files_sharing/lib/external/scanner.php on line 121`

### Server configuration
**Operating system**: OpenSUSE 12.2

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** PHP 5.4.20 (cli)

**ownCloud version:** ownCloud 8.1.0 (stable) 

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** 
Enabled:
 - calendar: 0.7.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - gallery: 0.6.0
 - news: 5.3.8
 - notes: 0.9
Disabled:
 - activity
 - appframework
 - documents
 - encryption
 - external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - mozilla_sync
 - provisioning_api
 - templateeditor
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'xxx',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 0,
  'theme' => '',
  'trusted_domains' =>
  array (**xxx**
  ),
  'appcodechecker' => false,
  'secret' => **xxx**
);

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
PHP Fatal error:  Class 'SecurityLib\\Strength' not found in /srv/www/htdocs/owncloud/apps/files_sharing/lib/external/scanner.php on line 121

#### ownCloud log (data/owncloud.log)
{"reqId":"mNCGp4m3VehBLI6ecmTW","remoteAddr":"xxx","app":"PHP","message":"Class 'SecurityLib\\Strength' not found at \/srv\/www\/htdocs\/owncloud\/apps\/files_sharing\/lib\/external\/scanner.php#121","level":3,"time":"2015-08-08T19:46:37+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Files\/Studium\/Nightline\/Schulung%20Psychologensuche"}

**Comment by karlitschek** [comment] 2015-08-09 19:15
@LukasReschke any idea where this error comes from?

**Comment by LukasReschke** [comment] 2015-08-09 19:35
How was the instance installed? Was this an update? Can you do a md5 hash over the 3rdparty folder?

**Comment by LukasReschke** [comment] 2015-08-09 19:47
If you updated: There may be a valid chance that some Opcache has cached invalid cache entries. In such cases please try to restart your web server.

If this helps then we might need to take a look why our autoloader behaves wrongly.

**Comment by ISibboI** [comment] 2015-08-09 21:04
First of all, thanks four your interest in solving this.

I restarted apache, but problem persists.

The installation was an update, it is older than a year.

Here's the output of `md5deep -r 3rdparty/`: http://pastebin.com/ug2B7mvP

**Comment by DrDamnit** [comment] 2015-09-14 11:58
I've got the same issue here. Has this been resolved? Or, in the alternative, can I just remove this one shared folder from a user's account until it is resolved?

**Comment by DrDamnit** [comment] 2015-09-14 12:06
Definitely related to external shares. Because I needed this client's account back online, and usable, AND they only had one external share, I removed all entries (there was only one) from oc_share_external. This resolved the problem that you could not access the files in owncloud.

(well... first, I set accepted = 0, then refreshed teh page. It prompted me if I wanted to accept the share, and I clicked cancel, and all the files popped right up).

So, having confirmed that this was the problem, I then dumped that table to a backup, and removed the entries from it.

**Comment by DrDamnit** [comment] 2015-09-14 12:07
@PVince81 If you can tell me approximately what the issue is here, without me having to trace it, I'll fork it, fix it, and do a pull request...

**Comment by timm2k** [comment] 2015-09-17 06:19
Same problem here.

**Comment by michaelstingl** [comment] 2015-09-18 09:16
@LukasReschke @PVince81 Other users reported this bug too:

> several of our users reported an error with "add to your ownCloud" function. 

> If a user adds a link-share with "add to your ownCloud" following message appears: 

> ``This directory is unavailable, please check the logs or contact the administrator ``

> At next login the user is not able to access his data. The message appears again. 

> Sync client fails also with an "internal server error". 

> When I perform a files:scan PHP reports following error: 
```
> PHP Fatal error: Class 'SecurityLib\Strength' not found in /var/www/html/owncloud/apps/files_sharing/lib/external/scanner.php on line 121 
```

Environment: 
- OC EE 8.1.1 
- PHP 5.4 
- RHEL 7

I asked for the logs and more information about the setup. Is there something else you want to know?

/cc @MorrisJobke 

00003840

**Comment by MorrisJobke** [comment] 2015-09-23 14:19
```
PHP Fatal error: Class 'SecurityLib\Strength' not found in /var/www/html/owncloud/apps/files_sharing/lib/external/scanner.php on line 121
```

Weird: https://github.com/owncloud/core/blob/v8.1.1/apps/files_sharing/lib/external/scanner.php#L121 There is nothing. cc @LukasReschke

**Comment by PVince81** [comment] 2015-09-23 14:29
also grepping the whole source tree for 8.1.1 for "SecurityLib" doesn't show any results.
The only occurrence is in the "3rdparty" folder where the lib is defined and the "3rdparty/composer/autoload_namespaces.php".

**Comment by PVince81** [comment] 2015-09-23 14:30
Do you guys all have the same enabled third party apps ?
Could you post the list ? (`./occ app:list`)

**Comment by michaelstingl** [comment] 2015-09-23 14:49
@MorrisJobke @PVince81 I'm still waiting for the list of activated apps. Sorry.

**Comment by DrDamnit** [comment] 2015-09-23 15:13
@PVince81 , Grepping through the source tree does show results. Lots of them.  Additionally, I am only showing matches that also have "Strength" in them, since that seems to be more specific to the problem:
https://gist.github.com/DrDamnit/d5c1f4bb7588dc09c416

Here are all the results for the previous version (that I had handy) for comparison.
https://gist.github.com/DrDamnit/f155ad2150c1aebce18e

**Comment by DrDamnit** [comment] 2015-09-23 15:14
@michaelstingl 
App List:

owncloud@cloud:~/www$ php occ app:list
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.1
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - documents
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**Comment by PVince81** [comment] 2015-09-23 15:39
@DrDamnit right, that's the same as I see. It's only the third party libraries, but they aren't used anywhere in the OC source code (everything except the "3rdparty" folder)

**Comment by DrDamnit** [comment] 2015-09-23 15:41
@PVince81 - ah, now I see what you were saying. It's not in core. Gotcha.

**Comment by timm2k** [comment] 2015-09-24 05:46
@michaelstingl @PVince81
```
[xxx@XXX owncloud]# grep -Rli securitylib *
3rdparty/composer/autoload_namespaces.php
3rdparty/composer/installed.json
3rdparty/composer.lock
3rdparty/ircmaxell/random-lib/lib/RandomLib/AbstractMixer.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Factory.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Generator.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Mixer/Hash.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/CAPICOM.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/MTRand.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/MicroTime.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/OpenSSL.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/Rand.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/Random.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/URandom.php
3rdparty/ircmaxell/random-lib/lib/RandomLib/Source/UniqID.php
3rdparty/ircmaxell/security-lib/composer.json
3rdparty/ircmaxell/security-lib/lib/SecurityLib/AbstractFactory.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/BaseConverter.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/BigMath/BCMath.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/BigMath/GMP.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/BigMath/PHPMath.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/BigMath.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/Enum.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/Hash.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/Strength.php
3rdparty/ircmaxell/security-lib/lib/SecurityLib/composer.json
3rdparty/ircmaxell/security-lib/test/Mocks/Enum.php
3rdparty/ircmaxell/security-lib/test/Mocks/Factory.php
3rdparty/ircmaxell/security-lib/test/Mocks/Strength.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/AbstractFactoryTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/BaseConverterTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/BigMath/BCMathTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/BigMath/GMPTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/BigMath/PHPMathTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/BigMathTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/EnumTest.php
3rdparty/ircmaxell/security-lib/test/Unit/Core/StrengthTest.php
3rdparty/ircmaxell/security-lib/test/bootstrap.php
[xxx@XXX owncloud]#
```
```
[xxx@XXX owncloud]# su - apache --shell=/bin/bash -c "/var/www/html/owncloud/occ app:list"
PHP Warning:  Module 'libsmbclient' already loaded in Unknown on line 0
Enabled:
 - activity: 2.0.1
 - documents: 0.10.2
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.1
 - user_ldap: 0.6.1
 - windows_network_drive: 0.1.1
Disabled:
 - admin_audit
 - encryption
 - external
 - files_antivirus
 - files_drop
 - files_ldap_home
 - files_locking
 - files_sharing_log
 - firewall
 - objectstore
 - provisioning_api
 - sharepoint
 - templateeditor
 - user_external
 - user_shibboleth
 - user_webdavauth
[xxx@XXX owncloud]# 
```

**Comment by timm2k** [comment] 2015-09-24 06:46
@michaelstingl @PVince81
I've updated our test system to 8.1.3 and the error with share_external has gone.

**Comment by ISibboI** [comment] 2015-09-27 10:26
Updated to 8.1.3 too. Seems to work.

**Comment by michaelstingl** [comment] 2015-09-28 07:54
@timm2k Thank you for let us know.

**Comment by PVince81** [comment] 2015-10-09 16:49
@DrDamnit how about you ? Still having issues with 8.1.3 ?

**Comment by DrDamnit** [comment] 2015-10-09 17:16
@PVince81 I'll update one of my client's installs and mine, and see if it breaks. Will advise.

**Comment by DrDamnit** [comment] 2015-10-15 17:56
It appears I always had 8.1.3 on both sides. I have just re-shared a folder from the remote site to my cloud (to crash mine if there was to be a crash), and it appears to work. What's interesting, is that I don't recall changing anything on either side that would have fixed this except I added the tasks app on my side, which (of course) required some updates. Not sure what fixed it...

**Comment by bboule** [comment] 2016-01-05 18:54
@michaelstingl is this closed from your perspective do you need anything else on this ticket?

**Comment by MorrisJobke** [comment] 2016-01-06 06:59
> @michaelstingl is this closed from your perspective do you need anything else on this ticket?

Yes. The instance was upgraded to 8.1.3 and the error was gone then.

**Comment by MorrisJobke** [comment] 2016-01-06 07:00
An upgrade to 8.1.3 seems to work here for all and therefore I will close this ticket.

**Closed by MorrisJobke** 2016-01-06 07:00 UTC
Labels: bug
