### ISSUE TITLE
LDAP Port field not fully shown in Opera

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#15444] opened 2015-04-07 16:06 UTC
ownCloud 8.1 pre alpha (git), Ubuntu 14.04, MySQL, nginx 1.7.11

After enabling LDAP, I have seen that the Port field is not fully shown when using Opera 28 as browser (Opera 28 uses the Blink based Chromium engine)

Windows 7 FireFox 35 (``Port`` fully shown)

![image](https://cloud.githubusercontent.com/assets/3321281/7027439/b99212fc-dd4f-11e4-9389-62967f3a99f3.png)

Windows 7 Opera 28 (``Port`` partially shown)
![image](https://cloud.githubusercontent.com/assets/3321281/7027465/da94cfd0-dd4f-11e4-8b07-fbe080c6e083.png)

**Comment by MorrisJobke** [comment] 2015-04-08 00:33
cc @owncloud/designers

**Comment by jancborchardt** [comment] 2015-04-08 10:48
@mmattel does making the field a bit wider via CSS fix the issue?

**Comment by mmattel** [comment] 2015-04-08 12:14
If you let me know where I can tune this, I will try it and post the result.

**Comment by jancborchardt** [comment] 2015-04-08 14:32
@mmattel right click on the field -> inspect element. Then in the CSS section of the dev tools for that element put in something like `width: 50px;`, or 100px.

**Comment by mmattel** [comment] 2015-04-08 16:54
Maybe I am too stupid, but I was not able to change the width setting, so I made a screenshot of the element inspection of the browsers. You can see that FF has a higher width 26x18 than Opera 20.870x18.972. The missing px are those causing the problems

FF:
![image](https://cloud.githubusercontent.com/assets/3321281/7050051/e8e3bc70-de1e-11e4-9345-231f1dc4f673.png)

Opera:
![image](https://cloud.githubusercontent.com/assets/3321281/7050059/f71423fc-de1e-11e4-871a-425cb05d7153.png)

**Comment by blizzz** [comment] 2015-04-09 10:10
Could you check whether the issue is fixed with https://github.com/owncloud/core/pull/15492 ?

**Comment by mmattel** [comment] 2015-04-09 14:53
FF:
![image](https://cloud.githubusercontent.com/assets/3321281/7069175/91a001e4-ded7-11e4-8d18-df774fba4bc9.png)


Opera:
![image](https://cloud.githubusercontent.com/assets/3321281/7069187/a0534854-ded7-11e4-926e-8ea0c2941403.png)

Whyever Opera (Chromium) does not align the end of the port number field, at least it is visible completely.

When 15492 gets merged, we can close this issue

**Comment by blizzz** [comment] 2015-04-09 15:43
Part of the problem might be that i am using relative sizes. Not sure this can work out at all. Pixel perfectness would help, I guess.

**Comment by MorrisJobke** [comment] 2015-04-09 21:56
#15492 is merged

**Closed by MorrisJobke** 2015-04-09 21:56 UTC
Labels: app:user_ldap, bug, design, junior job, sev4-low
