### ISSUE TITLE
Show warning if IE below 11 is used

### ISSUE THREAD

**Issue by ghost** [owncloud/core#25901] opened 2016-08-22 12:52 UTC
Based on the discussion in https://github.com/owncloud/documentation/pull/2580 and https://github.com/owncloud/core/issues/15567#issuecomment-166754301 it would really make sense if users are getting a warning shown that IE below 11 is unsupported.

Most likely that this won't get noticed in the documentation...

**Comment by PVince81** [comment] 2016-08-22 14:27
I suppose a yellow notification at the top once per login should be enough ?

**Comment by yasirunilan** [comment] 2016-12-11 06:52
Is this issue resolved? can I work on this

**Comment by RealRancor** [comment] 2016-12-11 08:05
@yasirunilan I don't think that someone has picked this up as the issue is still open and no Pull Request is referencing it. So feel free to work on it :+1:

**Comment by yasirunilan** [comment] 2016-12-11 08:16
Okay I'll work on it

**Comment by yasirunilan** [comment] 2016-12-11 13:16
Is it required to display the notification even if the user logs in from different browser other than  IE below 11 ? or only if he uses a browser below IE 11

**Comment by RealRancor** [comment] 2016-12-11 13:21
Mhhh, the current supported browsers are:

> Web browser: IE11+ (except Compatibility Mode), Firefox 14+, Chrome 18+, Safari 5+

https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#supported-platforms

Don't know how wide-spread the other browsers are

**Comment by yasirunilan** [comment] 2016-12-11 14:12
Any idea on how the message should appear the text content and location

**Comment by PVince81** [comment] 2017-01-27 17:30
Fixed by @DeepDiver1975 here https://github.com/owncloud/core/pull/26967

**Closed by PVince81** 2017-01-27 17:30 UTC
Labels: Hacktoberfest, junior job
