### ISSUE TITLE
[OS X CAPITAN] Owncloud client under OS X sync-problem (stops) #3945

### ISSUE THREAD

**Issue by peterporta** [owncloud/core#19807] opened 2015-10-15 12:17 UTC
Hi,
after upgrading my OS X to El Capitan 10.11 The sync-client begins to sync and than stops after some time showing the red circle with the white cross. 
In the meantime I updated the by hosteurope hosted owncloud to 8.1.3 (from 8.0.2) without success. The sync-client can be started but stops after some time.

I got the error-messages:
Error no app in context Error while running background job: Backends provided no user object for

Error files Backends provided no user object for
Error PHP Array to string conversion at /is/htdocs/.../lib/private/template/functions.php#36

One more note: It seems to be something with the external files from another owncloud. Removing the connection the sync works fine.

i thought, it could be a php-problem, but both (different) provider are on the same php-version 5.5

I already told that at https://github.com/owncloud/core/issues/3945 in a "wrong" area.

**Comment by MorrisJobke** [comment] 2015-11-04 13:22
> Error PHP Array to string conversion at /is/htdocs/.../lib/private/template/functions.php#36

Dup of https://github.com/owncloud/core/issues/17468

**Comment by MorrisJobke** [comment] 2015-11-04 13:24
> One more note: It seems to be something with the external files from another owncloud. Removing the connection the sync works fine.

Can you explain this a bit more detailed?

> Error files Backends provided no user object for

Can you check the owncloud.log for this line - because it contains more info.

**Comment by peterporta** [comment] 2015-11-04 14:01
Hello,
because I use since my notification the possibility to sync a second owncloud in my Client I have no more Logs at The Moment. I will try to reproduce that and send you The wanted log.
---
Peter Wienczny
(von meinem iPhone gesendet)

**Comment by peterporta** [comment] 2015-11-04 17:41
Hi,
now I have the log file created. Is it important to tell, that I have two sync-clients (on iMac and MacBook) syncing at the same time?

--
Viele Grüße

Peter Wienczny
Unter dem Holzweg 28
32457 Porta Westfalica
0571-7989416

**Comment by MorrisJobke** [comment] 2015-11-05 08:01
> now I have the log file created.

Can you send it somehow over? Or paste it here on gist.github.com ;)

**Comment by peterporta** [comment] 2015-11-05 17:26
??? I did send it to you in my last mail.
--
Viele Grüße

Peter Wienczny

**Comment by MorrisJobke** [comment] 2015-11-05 18:13
> ??? I did send it to you in my last mail.

You responded directly to github and it doesn't show up here.

**Comment by Xilentura** [comment] 2016-01-13 20:35
@MorrisJobke Are there some news or is there any progress? I still have this issue on owncloud 8.2.2 on FreeBSD with several clients on Ubuntu Linux, Windows and Mac OS X.

"app":"files","message":" Backends provided no user object for ","level":3
"app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3

The users get extra "file space" via SMB Share.

**Comment by peterporta** [comment] 2016-01-13 21:09
Because owncloud now can manage a second account without „forwarding“, the issue is obsolete.
--
Viele Grüße

Peter Wienczny
6

**Comment by Xilentura** [comment] 2016-01-13 21:17
@peterporta Thank you for your fast reply. Would you be so kind to explain what you mean with "forwarding" or paste me a link for a website?

**Comment by MorrisJobke** [comment] 2016-01-14 08:17
@Xilentura Can you paste the content of you oc_jobs table? This maybe helps to spot the failing background job. I will try to improve the error message.

**Comment by Xilentura** [comment] 2016-01-14 08:43
@MorrisJobke There is no oc_jobs on my server, just "owncloud/apps/user_ldap/lib/jobs" with the entry:

./
cleanup.php

Thanks for your fast reply!

**Comment by MorrisJobke** [comment] 2016-01-14 08:51
> @MorrisJobke There is no oc_jobs on my server, just "owncloud/apps/user_ldap/lib/jobs" with the entry:

I meant the table in the database ;)

**Comment by Xilentura** [comment] 2016-01-14 11:50
@MorrisJobke Here we go:

*1      OC\Cache\FileGlobalGC	null	1445505150
*2	 OCA\Activity\BackgroundJob\EmailNotification	null	1445504238
*3	 OCA\user_ldap\lib\Jobs	null	1445504252
*167	 \OCA\User_LDAP\Jobs\CleanUp	null	1445505091
*168	 OCA\Activity\BackgroundJob\ExpireActivities	null	1445434047

**Comment by MorrisJobke** [comment] 2016-01-14 12:48
Those entries look fine.

**Comment by Xilentura** [comment] 2016-01-15 10:49
All right - I've tested several owncloud clients (Apple, Ubuntu, Android) and all threw this error message 

    "app":"files","message":" Backends provided no user object for ","level":3
    "app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3

Sometimes you can upload files (small files work almost every time e.g. a picture), but when it comes to huge data files (200+ Megabyte) the client drops the connection. There is an upload limit (2 Gigabyte). What make things even harder is the point, that the upload interrupts at different times (3, 8, 25 minutes for example) and at different percentage values (e.g. 34 %, 75 % or even 96 %).

Additional error log:

    "app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 1024000 got 0\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #349)\\n#1 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #349)\\n#2 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('cm-13.0-2016011...', Resource id #349)\\n#3 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('TU-Home\\\/Musik\\\/c...', Resource id #349, NULL)\\n#4 
    [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 
    \\\/usr\\\/local\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#10 
    {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":361}","level":4,"time":" ...

**Comment by blizzz** [comment] 2016-03-01 16:07
Closing as a duplicate of https://github.com/owncloud/core/issues/9832 respectively https://github.com/owncloud/client/issues/4421

**Closed by blizzz** 2016-03-01 16:07 UTC
Labels: bug, needs info
