### ISSUE TITLE
Can not share link when in admin group

### ISSUE THREAD

**Issue by check-ict** [owncloud/core#13608] opened 2015-01-22 16:01 UTC
Hello,

I have created 2 users, Admin and Test1.

Both users are admin, so they have full control in Owncloud.

When Admin shares a folder with Test1 (or a group where Test1 is member of), the Test1 user can not share folders or files by link (external users with password). When I change Test1 user to be a non-admin, everything works fine.

This only happens if Test1 tries to share folders that are shared to him by Admin.

So for example:
Company with 10 users
1 Admin account shares 5 folders (general, sales, administration etc.)
1 user is also admin, the other 9 users are normal users
The user with admin rights can't share within the shared folders (general, sales etc.)
The user with admin right CAN share his own folders
All other users can share both their own folders as well as the admin shared folders

Hopefully this is enough information :-)

We are on the latest Owncloud (7.0.4).

**Comment by karlitschek** [comment] 2015-01-22 16:04
@schiesbn

**Comment by PVince81** [comment] 2015-01-23 11:28
Please be more precise about what you mean with "cannot share".
I assume you mean that "share with link" works, but opening the link results in a broken share.

Very likely to be a duplicate of: https://github.com/owncloud/core/issues/12475
Please try with this patch: https://github.com/owncloud/core/pull/13470

**Comment by PVince81** [comment] 2015-08-03 10:24
Please try again with 7.0.7, 8.0.5 or 8.1.

If you still see the issue there, feel free to reopen and provide more information.
Thanks.

**Closed by PVince81** 2015-08-03 10:24 UTC
Labels: sharing, triage
