### ISSUE TITLE
Expire Internal Shares

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11642] opened 2014-10-17 14:53 UTC
As a user, I want to be able to set expiration dates on internal shares in ownCloud, separate from an expiration for external share links, so that I can control who can access my files for how long.

**Comment by derekblankmccoy** [comment] 2015-04-17 09:31
Expiry on internal shares is something that is desired. Could it be an option that is toggled in the admin panel?

**Comment by jancborchardt** [comment] 2015-04-17 10:19
We will consider it with an upcoming rework of the sharing dialog. cc @rullzer

**Comment by tlhonmey** [comment] 2015-04-24 19:09
To avoid cluttering the control too much, it could enforce the same expiration date for internal and external shares and just add a checkbox for if it should apply to both of them or not.

**Comment by PVince81** [comment] 2016-05-24 18:21
Added to planning ticket https://github.com/owncloud/core/issues/24684#issuecomment-221359143

**Comment by PVince81** [comment] 2017-12-18 10:05
@felixheidecke @pmaier1 need some design work as the current UI doesn't have room.

I'd suggest having the list just showing the summary info of the shares and have a "edit" button for advanced/detail edit. Creating a link would create with defaults first. If a user wants more, the "edit" button could open a dialog/panel/whatever for said share for detail editing of permissions + expiration.

**Comment by PVince81** [comment] 2017-12-18 10:07
Assigning self for backend and API work, if required.

I can also help with JS impl if needed.

**Comment by ittrend4710** [comment] 2018-02-21 13:39
regarding "Share too Group or User option expiration date is missing" #30396 
is there a release date?
best,
mike

**Comment by ittrend4710** [comment] 2018-03-08 15:16
#30396 was closed as duplicate of #11642
feature was implemented in older versions, has gone in actual versions, no release date for it ... what should I tell my users?

**Comment by PVince81** [comment] 2018-03-08 15:25
As far as I remember the feature was not implemented in any past versions, unless we are talking about a different thing. This is why this is marked as feature request.

I've setup OC 8.1.9 locally and as you can see there is no "expiration date" function for local user shares:
![image](https://user-images.githubusercontent.com/277525/37159131-4b035a1c-22ed-11e8-9a27-1975203d644e.png)

Maybe did you use a third party app that added such feature ?

**Comment by ittrend4710** [comment] 2018-03-08 15:32
Yes, we're talking about the same thing.

User's are telling me another story ... they're missing the feature.

I cann't check it because our system is running version x now.

no third party tool installed.

best,
mike

**Comment by PVince81** [comment] 2018-03-09 14:19
@ittrend4710 often times user are confused between local shares and public link shares. Public link shares is the feature that always had expiration date and currently still have. The difference is that the user interface changed a bit: they need to click on the "Share" icon and in the sidebar on the right click on the "Public link share" tab and then "Create link". That's where they can create a link and add expiration. Please note that such links can be opened by anyone even without having an account on the system. (this was always the case).

**Comment by ittrend4710** [comment] 2018-03-12 11:47
I'll discuss it with our users ... thanks a lot

**Comment by PVince81** [comment] 2018-05-28 16:09
prerequisite for UI: https://github.com/owncloud/core/issues/30779

**Comment by PVince81** [comment] 2018-05-29 09:04
I'm putting this to backlog for now, will move it to development once we start directly adressing this.

**Comment by pmaier1** [comment] 2020-04-20 09:07
Implemented with Server 10.4.0.

**Closed by pmaier1** 2020-04-20 09:07 UTC
Labels: enhancement, enhancement-PM, feature:sharing
