### ISSUE TITLE
[oC7.0.1][Server to server sharing] Re-sharing a shared file between servers.

### ISSUE THREAD

**Issue by fernandoruiz** [owncloud/core#10375] opened 2014-08-12 18:23 UTC
### Expected behaviour:
I think that the file should be synchronized with the other user or group of oC_Instance_B.

### Actual behaviour:
The file isn't synced in the other user or group of oC_Instance_B.

### Steps to reproduce:
Share a file (File1.txt) between servers (from user1@oC_Instance_A to user1@oC_Instance_B).
Then from oC_Instance_B, I try to share the file (File1.txt) with another user or group of this server.

### Note:
The same happens when I try to re-share a folder.

**Operating system:** Ubuntu 14.04
**Web server:** Apache/2.4.7
**PHP version:** PHP Version 5.5.9-1ubuntu4.3
**ownCloud version:** ownCloud 7.0.1

**Comment by PVince81** [comment] 2015-01-22 09:27
@jnfrmarks another one for the test plan

**Comment by PVince81** [comment] 2015-08-21 15:47
Closing as duplicate of https://github.com/owncloud/core/issues/15116 (still happening on 8.2 master)

**Closed by PVince81** 2015-08-21 15:47 UTC
Labels: bug, feature:federated-cloud-sharing, sharing
