### ISSUE TITLE
Parameter problem in manager.php file

### ISSUE THREAD

**Issue by valentin8709** [owncloud/core#23262] opened 2016-03-15 14:11 UTC
### Steps to reproduce
I don't really know the steps to reproduce, I just have a php error in my log every minute but everything seems to be working fine (except email notifications, but it's in another issue). I just would like to know how to fix this error.

### Server configuration
**Operating system**: Linux Mint 17.3

**Web server:** Apache 2

**Database:** Mysql

**PHP version:** 5.6

**ownCloud version:** 9.0

**Updated from an older ownCloud or fresh install:** updated from 8.2.3

**Where did you install ownCloud from:** app "updater"

**List of activated apps:**

  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - conversations: 0.2.3
  - dav: 0.1.5
  - direct_menu: 0.7.0
  - documents: true
  - external: 1.2
  - fbsync: 1.8.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_gpxviewer_extended: 1.5
  - files_locking: true
  - files_mv: true
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - gallery: 14.5.0
  - html5_videoplayer: true
  - mail: true
  - news: true
  - notes: true
  - notifications: 0.2.3
  - pinit: 1.0.1
  - polls: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'oc3be3xe5gbf',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'XXX',
    1 => 'XXX',
    2 => 'XXX',
  ),
  'datadirectory' => '/media/DATA',
  'overwrite.cli.url' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'XXX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'XXX',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => 'imap.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'XXX',
  'mail_smtppassword' => 'XXX',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
 array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '',
  ),
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => true,
);

**Are you using external storage, if yes which one:** SFTP & Google Drive

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

#### ownCloud log (data/owncloud.log)
Error 	PHP 	array_map(): Argument #2 should be an array at /var/www/owncloud/lib/private/group/manager.php#283 

Error 	PHP 	array_keys() expects parameter 1 to be array, boolean given at /var/www/owncloud/lib/private/group/manager.php#283

**Comment by PVince81** [comment] 2016-03-15 14:25
Duplicate of https://github.com/owncloud/core/issues/22931

**Closed by PVince81** 2016-03-15 14:25 UTC

**Comment by valentin8709** [comment] 2016-03-15 14:50
Thank you very much, and sorry for the duplicated post, I didn't see it.
