### ISSUE TITLE
File picker thumbnails broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#36201] opened 2019-09-17 13:44 UTC
### Steps

1. Upload a few files in the root folder
1. Open browser console
1. Run `OC.dialogs.filepicker()`

### Expected result
Thumbnails look fine.

### Actual result
Thumbnails have the broken picture icon.
The URL looks like `http://server/owncloud/index.php/core/preview.png?file=%2Florem.txt` and receive a 302 redirect that points to the files app root `http://server/owncloud/index.php/apps/files/`

### Versions
ownCloud 10.3.0 (and earlier)

This used to work, not sure when. It is possible that it started breaking when we moved to the new previews endpoint.

Mentioned to me by @LinneyS

@micbar FYI this dialog is used by file editors like OnlyOffice and also the avatar selection

**Comment by PVince81** [comment] 2019-09-17 14:23
Fix is here: https://github.com/owncloud/core/pull/36202

**Comment by LinneyS** [comment] 2019-09-23 15:32
The problem is still relevant

**Comment by JanAckermann** [comment] 2021-09-21 09:30
Fixed with: https://github.com/owncloud/core/pull/39067

**Closed by JanAckermann** 2021-09-21 09:30 UTC
Labels: Type:Bug, regression
