### ISSUE TITLE
themes filetype icons ignored

### ISSUE THREAD

**Issue by SpiGAndromeda** [owncloud/core#25379] opened 2016-07-06 10:55 UTC
Hi,

i created a theme and i wanted to change the icons for folder etc.
I placed the icons (png and svg) in owncloud/themes/fancy/core/img/filetypes. As fas as i know they should be considered but the normal blue icons are shown. 
I already executed occ maintenance update-js.

Is there anaything else to modfiy or execute?

Best regards
SpiGAndromeda

**Comment by PVince81** [comment] 2016-07-06 13:34
Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by SpiGAndromeda** [comment] 2016-07-06 15:50
### Expected behaviour
The icons from the filetypes folder (core/img/filetypes) should be replaced by the ones existing in the theme folder (theme/core/img/filetypes).

### Actual behaviour
The original icons are used.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** MySQL 5.6.30

**PHP version:** 7.0.8-3

**ownCloud version:** 9.0.3 (stable)

**Updated from an older ownCloud or fresh install:** updated from 9.0.2

**Where did you install ownCloud from:** archive

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.2
  - bookmarks: true
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - direct_menu: 0.8.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.1.0
  - mail: 0.5.2
  - music: 0.3.11
  - news: 8.8.0
  - notifications: 0.2.3
  - ownbackup: true
  - ownnote: 1.08
  - provisioning_api: 0.4.1
  - spreedme: 0.1.6
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_privacyidea: 0.2
Disabled:
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc42b8zohyfj",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/Cloud\/Owncloud",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.3.2",
        "dbname": "c0ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtphost": "smtp.gmail.com",
        "mail_from_address": "owncloud.spigomaniac",
        "mail_domain": "gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "fancy",
        "loglevel": 2,
        "maintenance": false,
        "singleuser": false,
        "htaccess.RewriteBase": "\/owncloud"
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome/Firefox (Cache disabled and cleaned)

**Operating system:** Windows 10/Ubuntu 14.04 Server

### Logs
#### Web server error log
nothing relevant here

#### ownCloud log (data/owncloud.log)
nothing relevant here

#### Browser log
dont know if relevant:
GET https://owncloud.spigomaniac.de/index.php/core/preview.png?file=%2FStandard.kdbx&c=228e83158b3ee4a74da091c48bc162d7&x=32&y=32&forceIcon=0 404 (Not Found)
GET https://owncloud.spigomaniac.de/index.php/core/preview.png?file=%2FMinecraft+1.8.exe&c=8d3fe52c9d392f62b13a517d8df5d716&x=32&y=32&forceIcon=0 404 (Not Found)
GET https://owncloud.spigomaniac.de/index.php/core/preview.png?file=%2FTI-Conne…_DE-4.0.0.218.exe&c=2a534c7559ffb9bd146a2ee1a2a719f6&x=32&y=32&forceIcon=0 404 (Not Found)

**Comment by PVince81** [comment] 2016-07-06 15:52
Ah, 9.0.3. I think this used to work, could be a regression.

**Comment by SpiGAndromeda** [comment] 2016-07-06 16:18
I dont know if it was working in 9.0.2 because i created this theme when I already was on 9.0.3.

**Comment by PVince81** [comment] 2016-07-07 14:12
### Steps:

1. Create a folder "themes/example/core/img/filetypes"
1. Set the theme to "example" in config.php
1. Copy the file "core/img/filetypes/video.svg" to "themes/example/core/img/filetypes/application-pdf.svg"
1. Copy the file "core/img/filetypes/video.png" to "themes/example/core/img/filetypes/application-pdf.png"
1. Upload a PDF file
1. Clear cache
1. Refresh the page

### Expected:
PDF file must now have video icon

### Actual:
Still using the old PDF file icon.
Icon request still goes to http://localhost/owncloud/core/img/filetypes/application-pdf.svg

@rullzer @MorrisJobke @Xenopathic are filetype icons even themeable ?

**Comment by PVince81** [comment] 2016-07-07 14:14
Running `occ maintenance:mimetype:update-js` did not help either.

**Comment by MorrisJobke** [comment] 2016-07-07 14:14
> Running occ maintenance:mimetype:update-js did not help either.

Then I have no idea 😢

**Comment by tipichris** [comment] 2016-07-12 13:28
Has running `occ maintenance:mimetype:update-js` updated `core\js\mimetypelist.js`? If not, have you checked the permissions on `core\js\mimetypelist.js`?

I found that `occ maintenance:mimetype:update-js` issues no warning or errors if the permissions on `mimetypelist.js` don't allow it write access. It simply reports that it has updated things, but it hasn't.

**Comment by PVince81** [comment] 2016-11-30 09:10
@PhilippSchaffrath any idea since you touched theming recently ?

**Comment by PhilippSchaffrath** [comment] 2016-12-01 06:43
Running `occ maintenance:mimetype:update-js` should work in older versions, but definitely not in master.
This command iterates over all theme folders in the theme directory and generates information for the available icons. This generates unnecessary overhead when multiple themes are present.

Since it is possible to provide themes through apps now, we should use the theme object to generate a list of its available mimetype icons. Iterating over all available icons on the filesystem for each request seems bad too.

Ideally we would be able to detect whenever a theme is enabled, and then generate the themes mimetypes. This approach would be quite bloated though because we are currently (master) allowing both, themes through apps and the legacy way (theme directory).

**Comment by DeepDiver1975** [comment] 2016-12-01 08:45
I'd adjust the command to handle the enabled theme app as well.

**Comment by PhilippSchaffrath** [comment] 2017-01-24 11:16
Issue closed since #26805 has been merged.

**Closed by PhilippSchaffrath** 2017-01-24 11:16 UTC
Labels: bug, feature:theming, regression
