### ISSUE TITLE
[oC 8.2.0.12] Problem changing users email adresses

### ISSUE THREAD

**Issue by dajusc** [owncloud/core#20227] opened 2015-11-02 14:26 UTC
Hi everyone,

i just experienced an issue while changing/adding users email adresses. They don't get saved, unless you press return within the corresponding text-input-box.

Here is how to reproduce it: Log in as an admin user. Go to "dropdown menu (upper right corner) -> users -> setting-symbol (lower left corner)" and enable "Show email adress". Choose a user without and try to add or change the email adress. Leave the user-settings-site, eg. by going to your files. Return to the user-settings-site and the email adresses are set to their previous values. 

As stated above, the only way to actually change the email adresses is to press return within the text-input-box. Owncloud.log as well as apache and mysql error.log apparently do not contain any related entries. 

Kind regards
David

**Comment by karlitschek** [comment] 2015-11-02 14:45
What do you think @blizzz ?

**Comment by MorrisJobke** [comment] 2015-11-02 14:49
There was a discussion about this with @jancborchardt

**Comment by MorrisJobke** [comment] 2015-11-02 14:50
ref https://github.com/owncloud/core/pull/17154

**Comment by jancborchardt** [comment] 2015-11-08 22:02
Duplicate of https://github.com/owncloud/core/issues/15176 (Confirm function for text fields)

**Closed by jancborchardt** 2015-11-08 22:02 UTC
