### ISSUE TITLE
Log message about new folder (no such file or directory)

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#16039] opened 2015-05-04 11:32 UTC
Freshly installed via zip, 8.1 alpha2. I get this log error message for a new folder I created:
```
mime_content_type(\/Nouveau dossier): failed to open stream: No such file or directory at \/home\/jan\/owncloud-8.1alpha2\/lib\/private\/files\/type\/detection.php#120
```

cc @nickvergessen

**Comment by karlitschek** [comment] 2015-05-04 12:03
@nickvergessen Can you look into that? :-) Thanks

**Comment by nickvergessen** [comment] 2015-05-04 14:53
Well I can't reproduce to get this error. Although I can see it in that method, I'm not sure where we should catch the case (non-existing file)

**Comment by karlitschek** [comment] 2015-05-06 20:20
@jancborchardt Can you check if it still exists?

**Comment by deMattin** [comment] 2015-07-08 22:39
I actually updated from 8.0.4 to 8.1 (suse repo) on Debian 8 and am seeing many of errors like this in log:
> {"reqId":"66oFq5sY1tICGdi++7Y\/","remoteAddr":"192.168.1.20","app":"PHP","message":"mime_content_type(\/SofortUpload): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/type\/detection.php#120","level":3,"time":"2015-07-09T00:24:08+02:00"}

The errors are produced, when navigating in activities to Shares (Freigaben) or favorites (Favoriten).
In shared activities only the activities on sharing are shown as expected.
But in favorite activities there are also files shown, that never have been tagged as favorites!

Another error is also in there:
> {"reqId":"Y6qLICWdH8SzFiBMv\/4B","remoteAddr":"192.168.1.20","app":"PHP","message":"unserialize(): Error at offset 72 of 73 bytes at \/var\/www\/owncloud\/apps\/activity\/lib\/datahelper.php#141","level":3,"time":"2015-07-09T00:28:47+02:00"}

Don't know, if this is related.

Can you please help, to investigate or fix this?

The "requested id" is sometimes equal for different files!
![image](https://cloud.githubusercontent.com/assets/5565503/8583993/77b4d0b0-25d2-11e5-9922-b456297b97da.png)

**Comment by jancborchardt** [comment] 2015-07-09 09:55
@nickvergessen ^

**Comment by deMattin** [comment] 2015-07-10 03:51
Recognized, that this also affects new files and not depends on calling activities for favorites or shares.
What did go wrong during update to Owncloud 8.1 if this is caused by the update?
How can I fix it if this is not a general issue?

My Owncloud 8.1 works well without any errors or warnings besides this one.

**Comment by enoch85** [comment] 2015-07-13 19:50
Same here: 

```
mime_content_type(/ownCloud files/Owncloud VMDK/Use these programs to MOUNT the VM and login/VMDK_MOUNTER_FOR_MAC.dmg): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120
```

100s of them.

**Comment by nickvergessen** [comment] 2015-07-16 10:24
I still fail to reproduce this. Would be nice if one of you can post direct steps to reproduce it.

**Comment by deMattin** [comment] 2015-07-16 10:57
I purged all my activities to have no error messages on every view of activities.
It is related to deleted files/folders and it is a situation, where activities in owncloud 8.0 had no problem with.
Do you have no idea, where it possibly comes from by checking the code changes?

But what do you need more? (btw: you did not comment my different looking database entries)
Displaying an old activity listed in activities app tries to access a file, that does no longer exist (to show the preview pic?). This is "normal".
And I think, this produces the "error". But this is no error - the file is now gone! But scrolling in activities is scrolling in history and days ago "folder x" has been created ...

So, all in all I don't see any sense in this message as an error message!
I think/thought, it is an internal message (debug (0) or info (1)) and simply should be classified as that and not as an error coming up in the logs with log level 3!
Maybe it is used in code to show a cached preview (if it exists) or the default filetype picture for that.

But I will try to reproduce the create/delete situation that produces the error in 8.1.

As I wrote before, the activities have been shown as expected - only the message at log level 3 have been (or are) the error.

**Comment by enoch85** [comment] 2015-07-16 18:24
@nickvergessen 

Got it: 
1. Download from public link (https://en0ch.se/index.php/s/MUl79ovm7Ifo4kG)
2. Error appears.

```
Error 	PHP 	mime_content_type(/ownCloud files/Owncloud VMDK/Use these programs to MOUNT the VM and login): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120 	2015-07-16T20:19:37+02:00
Error 	PHP 	mime_content_type(/ownCloud files/Owncloud VMDK): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120 	2015-07-16T20:19:37+02:00
Error 	PHP 	mime_content_type(/ownCloud files/Owncloud VMDK): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120 	2015-07-16T20:19:37+02:00
Error	PHP	mime_content_type(/Foldersync Mobiler/Kellys 1+1/Screenshots/Screenshot_2015-07-16-15-09-57.png.tacitpart): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120	2015-07-16T20:19:25+02:00
```

Like @deMattin says, could it be related to deletions? 

Also, how do I safely purge all the activity entries? Maybe the error disappears if I start from the beginning...

**Comment by nickvergessen** [comment] 2015-07-17 10:27
> Also, how do I safely purge all the activity entries? Maybe the error disappears if I start from the beginning...

Clear the oc_activity table

I tried everything (deleting files, upload files, public download, ...) I never get this log entry.

**Comment by enoch85** [comment] 2015-07-17 20:01
@nickvergessen Strange. Maybe this is triggered by something else?

When is detection.php used?

**Comment by enoch85** [comment] 2015-07-17 21:38
I TRUNCATED the oc_activity table, and it happened again:

```
Error 	PHP 	mime_content_type(/ownCloud files/Owncloud VMDK/Use these programs to MOUNT the VM and login/VMDK_MOUNTER_FOR_MAC.dmg): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/files/type/detection.php#120 	2015-07-17T23:28:44+02:00
```

After a closer investigation I didn't find anything in error.log, but this was in my access.log:

```
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php HTTP/1.1" 302 823 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/apps/files/ HTTP/1.1" 200 5591 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/core/js/oc.js?v=93b986ab71301cc7323142c7960b6c12 HTTP/1.1" 200 2763 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/apps/documents/ajax/mimes.php HTTP/1.1" 200 888 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/apps/galleryplus/config?slideshow=1 HTTP/1.1" 200 1043 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/apps/files/ajax/scan.php?force=false&dir=&requesttoken=qQyb4n5LRwaMs7ecvmy%2FdWApypxq1N HTTP/1.1" 200 1074 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:42 +0200] "GET /index.php/apps/files_sharing/api/externalShares HTTP/1.1" 200 761 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/avatar/daniel%40en0ch.se/192?requesttoken=qQyb4n5LRwaMs7ecvmy%2FdWApypxq1N HTTP/1.1" 200 847 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:42 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1023 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:41 +0200] "GET /index.php/apps/files/ajax/list.php?dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 5493 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:42 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 1023 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:42 +0200] "GET /index.php/core/ajax/share.php?fetch=getItemsSharedStatuses&itemType=file HTTP/1.1" 200 1227 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - daniel@en0ch.se [17/Jul/2015:23:28:42 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1224 "-" "Mozilla/5.0 (Windows) mirall/1.8.4"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:43 +0200] "GET /index.php/apps/activity/ HTTP/1.1" 200 3499 "https://en0ch.se/index.php/apps/files/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:44 +0200] "GET /index.php/core/js/oc.js?v=93b986ab71301cc7323142c7960b6c12 HTTP/1.1" 200 2763 "https://en0ch.se/index.php/apps/activity/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:44 +0200] "GET /index.php/avatar/daniel%40en0ch.se/192?requesttoken=qQyb4n5LRwaMs7ecvmy%2FdWApypxq1N HTTP/1.1" 200 847 "https://en0ch.se/index.php/apps/activity/" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:44 +0200] "GET /index.php/apps/activity/activities/fetch?filter=all&page=1 HTTP/1.1" 200 1562 "https://en0ch.se/index.php/apps/activity/?filter=all" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:44 +0200] "GET /index.php/apps/activity/activities/fetch?filter=all&page=2 HTTP/1.1" 200 723 "https://en0ch.se/index.php/apps/activity/?filter=all" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:44 +0200] "GET /index.php/core/preview.png?file=/DirektUppladdning/Bilder+%C3%B6vrigt/elis_farsan.png&y=150&x=150 HTTP/1.1" 200 47869 "https://en0ch.se/index.php/apps/activity/?filter=all" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
en0ch.se:443 192.168.1.1 - daniel@en0ch.se [17/Jul/2015:23:28:46 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1273 "-" "Mozilla/5.0 (Windows) mirall/1.8.4"
en0ch.se:443 192.168.1.1 - - [17/Jul/2015:23:28:51 +0200] "GET /index.php/settings/admin HTTP/1.1" 200 7955 "https://en0ch.se/index.php/apps/activity/?filter=all" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
```

**Comment by nickvergessen** [comment] 2015-07-18 08:04
Okay, I now found the code path (I looked at the stable8 instead of stable8.1 all the time :tada: ).
However `mime_content_type()` does not throw/log an error.

Anyway, for 8.1 I will revert back to the private helper class, for 8.2 we need to add a public method for it.

**Comment by nickvergessen** [comment] 2015-07-20 15:25
Fixed with https://github.com/owncloud/activity/pull/336 in the activity app for the time being, until a public API method is there that does the same.

**Closed by nickvergessen** 2015-07-20 15:25 UTC
Labels: app:files, bug
