### ISSUE TITLE
Sorting by file name is case sensitive 

### ISSUE THREAD

**Issue by zinks-** [owncloud/core#14170] opened 2015-02-12 18:08 UTC
When sorting files by name, the names starting with uppercase are at the top of the list instead of being integrated with other files. It makes it harder to find a file.

![screenshot - 02122015 - 07 06 17 pm](https://cloud.githubusercontent.com/assets/8377141/6173731/46e42644-b2ea-11e4-8588-2ab0dd711895.png)

**Comment by LukasReschke** [comment] 2015-02-12 19:47
Duplicate of https://github.com/owncloud/core/issues/13982, please install `php5-intl`.

**Closed by LukasReschke** 2015-02-12 19:47 UTC
