### ISSUE TITLE
Sharing doesn't worked anymore [8.2.1]

### ISSUE THREAD

**Issue by bmap1cari** [owncloud/core#20723] opened 2015-11-25 06:49 UTC
After Upgrading 8.1.4 => 8.2.1 i can't share files in the cloud via names or groups anymore. With the activated option to share files via a link username autocompletion and sharing via groups and names works but without this option not.

I use LDAP, but also the local user Admin doesn't appear.

I roll back the whole machine(Hyper-V) it works again, then i make a clean install after database upgrade it happens again, i talked with several users from other owncloud instances, they reported me the same.

**Comment by rullzer** [comment] 2015-11-25 06:55
Duplicate of https://github.com/owncloud/core/issues/20642

**Closed by rullzer** 2015-11-25 06:55 UTC
