### ISSUE TITLE
Owncloud 7 - missing files

### ISSUE THREAD

**Issue by sprbra** [owncloud/core#12357] opened 2014-11-21 14:24 UTC
Mostly folders on my owncloud have physically more files then is listed on web (Chrome, Firefox, I.E.), i'm had already TRUNCATE the oc_filescache and oc_pictures_images_cache but the issue persists. I'm also tried to verify if in android official owncloud app this issue happens too, and for my unhappy surprise this issue happens too.

**Comment by karlitschek** [comment] 2015-01-06 20:03
ok. I agree that this should work automatically. 
Closing for now because the issue is resolved for now

**Closed by karlitschek** 2015-01-06 20:03 UTC
Labels: bug
