### ISSUE TITLE
Owncloud: After Rename Folders Files are missing in the WebGUI

### ISSUE THREAD

**Issue by Zachi777** [owncloud/core#12605] opened 2014-12-04 09:34 UTC
Hello, 

i have a issue when users rename folders in the Webgui and Reload the Browsertab the renamed folders are be empty.
The files are only missing in the WebGUI...
When switch to Filepath  (with terminal) all Files are existing....

System:
Ubuntu 14.04 
Onwcloud 7.0.3

**Comment by Zachi777** [comment] 2015-02-27 08:39
Hi , 
i have reproduce the issue with some users. Files are disappeared only in the WebGUI. Its happend when users refresh the browser while rename process is running. After i used the "file rescan"-script  the files appeared again in the webgui. 

(same can be reproduce on the demo.owncloud server)

**Comment by tapete** [comment] 2015-03-16 14:16
I encountered the same problem with 7.0.3 and 8.0.2. 
"Its happend when users refresh the browser while rename process is running." 
Same for me but it can also happen without refresh.

**Comment by Tedster** [comment] 2015-03-16 14:35
Is this still outstanding in the 7.0.4 stable release? I have exactly this scenario after renaming a folder. The new folder doesn't exists and the old folder is empty. This shows in the web GUI and also on webdav. And if I synch down the folders aren't there. I am using a hosting company for this so don't have access to the machine. How do I ask them to run the script [php occ files:scan [--all/etc]]?

**Comment by Zachi777** [comment] 2015-03-23 09:30
Hi, 
i think that i have sovled my issue form my server. I changed the memory_limit @ ..,/owncloud/.htaccess from 512M to 5G.

**Comment by PVince81** [comment] 2015-04-13 09:18
Likely to be a duplicate of https://github.com/owncloud/core/issues/13391

Does it happen for any folder or just that one ? Did the folder contain lots of files ?

**Comment by kisppaul** [comment] 2015-05-17 06:46
We have the same issue with server 8.0.3 on ubuntu 14.04 both via webinterface as with client 1.8.1. Renaming a folder with lots of files and subdirectories takes a while. After renaming, folder appears to be empty (0 K). Via the webinterface you can then delete the folder, go to the trash and restore the folder: all files are back as if nothing happens.

**Comment by PVince81** [comment] 2015-05-18 09:16
Closing as duplicate of https://github.com/owncloud/core/issues/13391

**Closed by PVince81** 2015-05-18 09:16 UTC
Labels: bug, needs info
