### ISSUE TITLE
Upgrade to 8.0 broke CalDav/CardDav sync for DavDroid

### ISSUE THREAD

**Issue by nroach44** [owncloud/core#14085] opened 2015-02-11 04:53 UTC
Unsure where to file this, but there's been no change on the client side so I suppose here is best.

Since the upgrade, DavDroid has been unable to sync. Visiting the remote.php urls work fine in Firefox.

On the client (android 4.4, davdroid):
```
D/davdroid.DavResourceFinder( 4564): Looking up SRV records for _carddavs._tcp.sync.haven
V/davdroid.URIUtils( 4564): Normalized URL /.well-known/carddav -> /.well-known/carddav
V/davdroid.URIUtils( 4564): Normalized URL https://sync.haven/remote.php/carddav -> https://sync.haven/remote.php/carddav
I/davdroid.WebDavResource( 4564): Redirection on PROPFIND; trying again at new content URL: https://sync.haven/remote.php/carddav
V/davdroid.URIUtils( 4564): Normalized URL /remote.php/carddav/ -> /remote.php/carddav/
D/davdroid.WebDavResource( 4564): Processing multi-status element: https://sync.haven/remote.php/carddav/
D/davdroid.URIUtils( 4564): Appended trailing slash to collection https://sync.haven/remote.php/carddav -> https://sync.haven/remote.php/carddav/
E/davdroid.DavResourceFinder( 4564): HTTP error when querying principal
E/davdroid.DavResourceFinder( 4564): at.bitfire.davdroid.webdav.HttpException: 405 Method Not Allowed
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:419)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:393)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:286)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:263)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:61)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:119)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:97)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
E/davdroid.DavResourceFinder( 4564): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/davdroid.DavResourceFinder( 4564): 	at java.lang.Thread.run(Thread.java:811)
I/davdroid.DavResourceFinder( 4564): Couldn't find current-user-principal for service carddav
D/davdroid.DavResourceFinder( 4564): Looking up SRV records for _caldavs._tcp.sync.haven
V/davdroid.URIUtils( 4564): Normalized URL /.well-known/caldav -> /.well-known/caldav
V/davdroid.URIUtils( 4564): Normalized URL https://sync.haven/remote.php/caldav -> https://sync.haven/remote.php/caldav
I/davdroid.WebDavResource( 4564): Redirection on PROPFIND; trying again at new content URL: https://sync.haven/remote.php/caldav
V/davdroid.URIUtils( 4564): Normalized URL /remote.php/caldav/ -> /remote.php/caldav/
D/davdroid.WebDavResource( 4564): Processing multi-status element: https://sync.haven/remote.php/caldav/
D/davdroid.URIUtils( 4564): Appended trailing slash to collection https://sync.haven/remote.php/caldav -> https://sync.haven/remote.php/caldav/
E/davdroid.DavResourceFinder( 4564): HTTP error when querying principal
E/davdroid.DavResourceFinder( 4564): at.bitfire.davdroid.webdav.HttpException: 405 Method Not Allowed
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:419)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:393)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:286)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.resource.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:263)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:101)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:119)
E/davdroid.DavResourceFinder( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:97)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
E/davdroid.DavResourceFinder( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
E/davdroid.DavResourceFinder( 4564): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/davdroid.DavResourceFinder( 4564): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/davdroid.DavResourceFinder( 4564): 	at java.lang.Thread.run(Thread.java:811)
I/davdroid.DavResourceFinder( 4564): Couldn't find current-user-principal for service caldav
E/davdroid.ServerInfoLoader( 4564): DAV error while querying server info
E/davdroid.ServerInfoLoader( 4564): at.bitfire.davdroid.webdav.DavIncapableException: Invalid DAV response: No CalDAV-/CardDAV service is available at this location.
E/davdroid.ServerInfoLoader( 4564): 	at at.bitfire.davdroid.resource.DavResourceFinder.findResources(DavResourceFinder.java:147)
E/davdroid.ServerInfoLoader( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:119)
E/davdroid.ServerInfoLoader( 4564): 	at at.bitfire.davdroid.syncadapter.QueryServerDialogFragment$ServerInfoLoader.loadInBackground(QueryServerDialogFragment.java:97)
E/davdroid.ServerInfoLoader( 4564): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
E/davdroid.ServerInfoLoader( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
E/davdroid.ServerInfoLoader( 4564): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
E/davdroid.ServerInfoLoader( 4564): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/davdroid.ServerInfoLoader( 4564): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/davdroid.ServerInfoLoader( 4564): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/davdroid.ServerInfoLoader( 4564): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/davdroid.ServerInfoLoader( 4564): 	at java.lang.Thread.run(Thread.java:811)
```

On the server (apache2, debian jessie):
```
192.168.0.64 - - [11/Feb/2015:12:50:32 +0800] "PROPFIND /.well-known/carddav HTTP/1.1" 301 859 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:12:50:32 +0800] "PROPFIND /remote.php/carddav HTTP/1.1" 401 1210 "-" "DAVdroid/0.6.11"
192.168.0.64 - nroach44 [11/Feb/2015:12:50:32 +0800] "PROPFIND /remote.php/carddav HTTP/1.1" 207 1450 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:12:50:33 +0800] "PROPFIND / HTTP/1.1" 405 666 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:12:50:33 +0800] "PROPFIND /.well-known/caldav HTTP/1.1" 301 859 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:12:50:33 +0800] "PROPFIND /remote.php/caldav HTTP/1.1" 401 1210 "-" "DAVdroid/0.6.11"
192.168.0.64 - nroach44 [11/Feb/2015:12:50:33 +0800] "PROPFIND /remote.php/caldav HTTP/1.1" 207 1514 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:12:50:33 +0800] "PROPFIND / HTTP/1.1" 405 666 "-" "DAVdroid/0.6.11
```

**Comment by RealRancor** [comment] 2015-02-11 07:07
Hi,

seems you're getting an:

> 405 Method Not Allowed

for the PROPFIND to remote.php/carddav which often shows that this is causef by a server configuration not allowing this needed method.

**Comment by nroach44** [comment] 2015-02-11 09:13
I enabled the rewrite, dav and dav_fs module (as per stackexchange posts), and configured the dav module and this is the result on the server:

```
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND /.well-known/carddav HTTP/1.1" 301 3057 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND /remote.php/carddav HTTP/1.1" 400 586 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND / HTTP/1.1" 405 827 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND /.well-known/caldav HTTP/1.1" 301 859 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND /remote.php/caldav HTTP/1.1" 400 586 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND / HTTP/1.1" 405 827 "-" "DAVdroid/0.6.11"
```

i.e. No difference

**Comment by RealRancor** [comment] 2015-02-11 09:18
Hi,

the dav modules are not needed and shouldn't be enabled for ownCloud. Maybe you could also find some hints here: http://forum.owncloud.org/viewtopic.php?f=17&t=7536

**Comment by nroach44** [comment] 2015-02-11 09:26
I've tried most of the things in that post and nothing has helped. I'm fairly certain it's not an apache configuration issue because it worked before the upgrade, and nautilus'/GVFS' webdav works on the server.

```
192.168.0.52 - nroach44 [11/Feb/2015:17:24:36 +0800] "PROPFIND /remote.php/webdav/01660-97022.pdf HTTP/1.1" 404 1002 "-" "gvfs/1.22.2"
192.168.0.52 - nroach44 [11/Feb/2015:17:24:36 +0800] "PUT /remote.php/webdav/01660-97022.pdf HTTP/1.1" 201 795 "-" "gvfs/1.22.2"
192.168.0.52 - nroach44 [11/Feb/2015:17:24:36 +0800] "PROPFIND /remote.php/webdav/01660-97022.pdf HTTP/1.1" 207 1552 "-" "gvfs/1.22.2"
```

**Comment by RealRancor** [comment] 2015-02-11 09:38
Ah, just seen that the 405 is only caused by a call of davdroid to the root folder of OC:

```
192.168.0.64 - - [11/Feb/2015:17:10:12 +0800] "PROPFIND / HTTP/1.1" 405 827 "-" "DAVdroid/0.6.11"
```

Then it is normal that you're getting an 405 for this.

**Comment by nroach44** [comment] 2015-02-11 09:39
So then it's probably bad behaviour that probably broke due to the update? If so I'll go ask over at davdroid's page.

**Comment by RealRancor** [comment] 2015-02-11 09:45
Mhhh, don't think that this is a real problem of davdroid. Probably just a "discovery" run to detect existing calendars.

**Comment by nroach44** [comment] 2015-02-11 09:47
I just took a peek at another device that I hadn't cleared the configuration to test with:

```
192.168.0.65 - - [11/Feb/2015:17:40:38 +0800] "PROPFIND /remote.php/caldav/calendars/NRoach44/events/ HTTP/1.1" 401 3569 "-" "DAVdroid/0.6.11"
192.168.0.65 - nroach44 [11/Feb/2015:17:40:38 +0800] "PROPFIND /remote.php/caldav/calendars/NRoach44/events/ HTTP/1.1" 207 1498 "-" "DAVdroid/0.6.11"
192.168.0.65 - nroach44 [11/Feb/2015:17:40:38 +0800] "PROPFIND /remote.php/caldav/calendars/NRoach44/events/ HTTP/1.1" 207 1514 "-" "DAVdroid/0.6.11"
192.168.0.65 - nroach44 [11/Feb/2015:17:40:39 +0800] "GET /remote.php/caldav/calendars/NRoach44/events/events HTTP/1.1" 404 1210 "-" "DAVdroid/0.6.11"
```
The 404 is what the client is complaining about, and the fact that it's going to events/events does seem like a client issue.

So, what's the recommended course of action?

**Comment by nroach44** [comment] 2015-02-11 11:19
Okay, I did some more testing, and GNOME cannot access the calendar or contacts now either.

Even when authenticated properly, the response given to firefox is:
```
-----https://sync.haven/remote.php/carddav/addressbooks/nroach44/-----

<d:error><s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception><s:message>User did not have the required privileges ({DAV:}read) for path "addressbooks/nroach44"</s:message><s:sabredav-version>1.8.12</s:sabredav-version><d:need-privileges><d:resource><d:href>/remote.php/carddav/addressbooks/nroach44</d:href><d:privilege><d:read/></d:privilege></d:resource></d:need-privileges></d:error>
```

The log on the server:

```
192.168.0.62 - - [11/Feb/2015:19:15:58 +0800] "GET /remote.php/carddav/addressbooks/nroach44/ HTTP/1.1" 401 1234 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Icewea
sel/31.4.0"
192.168.0.62 - nroach44 [11/Feb/2015:19:15:58 +0800] "GET /remote.php/carddav/addressbooks/nroach44/ HTTP/1.1" 403 1301 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
 Iceweasel/31.4.0"
```

**Comment by oeves** [comment] 2015-02-11 11:27
can you try, creating a new test user and then configure your sync. we discuss a similar topic here #14048

**Comment by nroach44** [comment] 2015-02-11 11:34
I'm getting unable to create user. There's no messages apperaing in the logs...

Unless there's a simple fix for this issue I'm going to nuke and pave.

**Comment by RealRancor** [comment] 2015-02-11 11:39
Hi,

have you accidentially enabled an external user backend? Those are causing such messages like "unable to create user":

http://forum.owncloud.org/viewtopic.php?f=17&t=20221

**Comment by nroach44** [comment] 2015-02-11 11:43
Okay, thanks. I had accidentally enabled the WebDAV user backend, and that solved the user issue.

I created a new account and davdroid connects to that account fine:
```
192.168.0.64 - - [11/Feb/2015:19:40:52 +0800] "PROPFIND /.well-known/carddav HTTP/1.1" 301 859 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:19:40:52 +0800] "PROPFIND /remote.php/carddav HTTP/1.1" 401 1210 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:52 +0800] "PROPFIND /remote.php/carddav HTTP/1.1" 207 1482 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:56 +0800] "PROPFIND /remote.php/carddav/principals/nazara/ HTTP/1.1" 207 1658 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:56 +0800] "OPTIONS /remote.php/carddav/addressbooks/nazara/ HTTP/1.1" 200 1125 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:56 +0800] "PROPFIND /remote.php/carddav/addressbooks/nazara/ HTTP/1.1" 207 3547 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:19:40:57 +0800] "PROPFIND /.well-known/caldav HTTP/1.1" 301 698 "-" "DAVdroid/0.6.11"
192.168.0.64 - - [11/Feb/2015:19:40:57 +0800] "PROPFIND /remote.php/caldav HTTP/1.1" 401 1210 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:57 +0800] "PROPFIND /remote.php/caldav HTTP/1.1" 207 1546 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:57 +0800] "PROPFIND /remote.php/caldav/principals/nazara/ HTTP/1.1" 207 1706 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:57 +0800] "OPTIONS /remote.php/caldav/calendars/nazara/ HTTP/1.1" 200 1157 "-" "DAVdroid/0.6.11"
192.168.0.64 - nazara [11/Feb/2015:19:40:57 +0800] "PROPFIND /remote.php/caldav/calendars/nazara/ HTTP/1.1" 207 5771 "-" "DAVdroid/0.6.11"
```

**Comment by RealRancor** [comment] 2015-02-11 11:45
Hi,

then i think this is a duplicate of: https://github.com/owncloud/core/issues/14048

**Comment by nroach44** [comment] 2015-02-11 11:47
Yup, definitely sounds like it. If you want to go ahead and close this as such I'll subscribe to the other issue.

**Comment by RealRancor** [comment] 2015-02-11 11:56
I don't have the permissions to do so

**Closed** 2015-02-11 11:57 UTC
