### ISSUE TITLE
pdf.js toolbar broken

### ISSUE THREAD

**Issue by bibabu512** [owncloud/core#14110] opened 2015-02-11 15:06 UTC
### Steps to reproduce
1. Open a PDF in OwnCloud

### Expected behaviour
pdf.js toolbar elements dont overlap with eachother. 

### Actual behaviour
![screenshot 2015-02-11 15 52 17](https://cloud.githubusercontent.com/assets/3902676/6149016/0647efe2-b206-11e4-9c92-13ea2ca75794.png)

see close button or zoom selector.

### Server configuration
**Operating system:** Debian Wheezy

**Web server:** Apache2

**Database:** SQLite

**PHP version:** PHP 5.4.36-0+deb7u3

**ownCloud version:** 8.0.0.7

**Updated from an older ownCloud or fresh install:** minor update from 8.0.0-2 to 8.0.0-5

**List of activated apps:** Activity, Deleted files, PDF Viewer, Pictures, Shared Files, Text Editor, Versions, Updater, Video Viewer 

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'domain',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://domain/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.0.0.7',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 40.0.2214.111

**Operating system:** Yosemite 10.10.2

#### Browser log
```
GET https://domain/owncloud/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
```

**Comment by karlitschek** [comment] 2015-02-11 15:10
@LukasReschke

**Comment by LukasReschke** [comment] 2015-02-11 15:17
Close button is a duplicate of https://github.com/owncloud/files_pdfviewer/issues/38, the other one is an upstream bug… Let me see what I can do here…

**Closed by LukasReschke** 2015-02-11 15:17 UTC

**Comment by sbowenwilliams** [comment] 2015-03-13 20:28
I'm getting this problem with an app I wrote for owncloud where the jquery event handler fails and my log is:
GET https://ocdev.sesp.northwestern.edu/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
