### ISSUE TITLE
Not able to lookup user on AD server2 and AD server 3 when share a file / folder

### ISSUE THREAD

**Issue by psdrndm** [owncloud/core#25071] opened 2016-06-12 08:59 UTC
### Steps to reproduce
1. Configure ownCloud 8.2.5 to talk with a Active Directory Server1
2. Add another Active Directory Server2 and Active Directory server3 on ADMIN > LDAP configuration
3. go to Admin > Users, able to lookup all user on Active Directory server 1, Active Directory server2, Active Directory server3
4. go to files > share file/folder to user on Active Directory Server1 is successfully, able to lookup users
5. go to files > share file/folder to user on Active Directory Server2, can't lookup user
6. go to fiiles> share file/folder to user on Active Directory Server3, can't lookup user

### Expected behaviour
User can lookup all users (Active Directory Server 1, Active Directory Server 2, Active Directory Server 3) when sharing a file/folder

### Actual behaviour
go to files > share file/folder to user on Active Directory Server1 is successfully, able to lookup users
 go to files > share file/folder to user on Active Directory Server2, can't lookup user
 go to fiiles> share file/folder to user on Active Directory Server3, can't lookup user

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
5.5.9-1ubuntu4.16

**ownCloud version:** (see ownCloud admin page)
8.2.5

**Where did you install ownCloud from:**
Packages

**List of activated apps:**

Enabled:
  - activity: 2.1.4
  - files: 1.2.1
  - files_antivirus: 0.8.0.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - documents
  - encryption
  - external
  - firstrunwizard
  - shorten
  - user_external

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocsw3f7zjhyy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/drives\/data",
        "dbtype": "mysql",
        "version": "8.2.5.2",
        "dbname": "drives",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Jakarta",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": 14
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

#### LDAP configuration (delete this part if not used)

please find attached
[ldap.txt](https://github.com/owncloud/core/files/310691/ldap.txt)

**Comment by DeepDiver1975** [comment] 2016-06-13 12:14
@psdrndm maybe a caching issue - can you rety without redis being connected?

**Comment by PVince81** [comment] 2016-06-13 13:46
@owncloud/ldap

**Comment by scolebrook** [comment] 2016-06-14 16:25
We only have 2 AD directories connected and searching for users in either works fine. My guess is that this is caused because you're using a non unique attribute for the internal username, samAccountName. That means that you can't have more than 1 user between the 3 directories with a given samAccountName. You have to guarantee uniqueness yourself because ownCloud is expecting the directory to do that. But you've directed ownCloud to use an attribute where the directory doesn't guarantee uniqueness across multiple directories

It's better to leave the username field in the expert tab empty and let ownCloud use objectGUID or set it to use UPN which should be unique across directories.

We leave it blank and use objectGUID for the internal username but use UPN for the naming of home directories which is easier from a support perspective when we need to do something at the file system level.

We use samAccountName and UPN for the login filter (along with membership of a group) and we use it together with email and displayname for user searches. We train our users to use the upn format and don't tell them about samAccountName.

It's planned that this will be removed from our login filter at some point. There's no overlap in this attribute between our 2 directories currently but there will be and at that point samAccountName won't be a good choice for logging in as there'll be no guarantees about which account in which directory to authenticate against.

**Comment by PVince81** [comment] 2016-06-15 07:52
@scolebrook thanks a lot for your explanation. Do I understand it correctly that this is expected behavior and not a bug in ownCloud ? Expected as in "the admin needs to make sure the values are unique in LDAP".

**Comment by scolebrook** [comment] 2016-06-15 14:47
Yes. I think the first thing is that @psdrndm needs to have an attribute for the internal username that is unique across directories. That would be what I'd call a "supported configuration". Then we can see what works and what doesn't and go from there.

**Comment by psdrndm** [comment] 2016-06-18 17:53
Sorry for late reply.
@scolebrook Thanks for the hints :+1: , currently I change the LDAP configuration as below

Users - LDAP Filter: (&(|(objectclass=person)))
Login Attributes - LDAP Filter: (&(&(|(objectclass=person)))(samaccountname=%uid))
Groups - LDAP Filter: (&(|(objectclass=group)))
Advances - Group-Member association "uniqueMember"

Now I'm able to lookup all users on all AD

**Comment by PVince81** [comment] 2016-06-22 15:26
Cool, so I think we can close this

**Closed by PVince81** 2016-06-22 15:26 UTC
Labels: app:user_ldap, bug
