### ISSUE TITLE
UI is not updated correctly when deleting a lot of items

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36177] opened 2019-09-10 06:03 UTC
### Steps to reproduce
1. have a user with the testing skeleton folder
2. mark all files/folder
3. unmark some folder
4. delete all marked

### Expected behaviour
files folders should be deleted and the UI should be updated correctly

### Actual behaviour
items are correctly deleted but UI is not correctly updated

![test](https://user-images.githubusercontent.com/2425577/64587902-1eb6c280-d3a1-11e9-8fda-5a9db612f006.gif)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache 2
**Database:**
MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.3.0alpha2
**Updated from an older ownCloud or fresh install:**
fresh

### Client configuration
**Browser:**
FF
**Operating system:**
Ubuntu 18.04

#### Browser log
```
TypeError: fileEl is null  filelist.js:2445:5
```

**Comment by individual-it** [comment] 2019-09-10 06:04
need to  find out if its regression

**Comment by individual-it** [comment] 2019-09-10 07:50
same issue in 10.2.1, not a regression

**Comment by JammingBen** [comment] 2021-09-28 11:29
Cannot reproduce in 10.8.0, therefore closing.

**Closed by JammingBen** 2021-09-28 11:29 UTC
Labels: Type:Bug
