### ISSUE TITLE
Limited general use when files are stored with their "real names"

### ISSUE THREAD

**Issue by despens** [owncloud/core#18998] opened 2015-09-13 21:59 UTC
Storing files and folders on the server with exactly the same names as on the client seems to limit the usefulness of owncloud:

When backing up a home directory, the hidden files is where the most interesting information is saved.

File names with "special characters" like `:` are not uploaded to owncloud, the notification announcing this is very easy to miss. I suspect `:` should not be used in file names on Macintosh, but that should prevent the download on a Mac, not the upload from Linux.

`.htaccess` files are blocked since they might cause trouble on an Apache server, but are typically vital files for web projects.

I suggest that names of file and folders should be optionally hashed per storage, and by this lifting all restrictions on their naming.

If not everything is synced, and the list of rules what is not synced is as long as it is, my confidence in the sync process is not exactly high. How can I predict which files are synced? Am I supposed to weed through the logs to see if every file has made it to the server, amongst hundreds of entries, without knowing what to look for?

Sync all or nothing please! :smile_cat:

**Comment by RealRancor** [comment] 2015-09-14 05:14
Hi,

there is a larger discussion about this available here https://github.com/owncloud/client/issues/854

I think that was throughly discussed there.

**Comment by despens** [comment] 2015-09-14 06:27
Thanks for pointing to the discussion.

I think the problem is two parts, the server and the client. My suggestion is to start with the server not storing the files not with their actual names on its file system to get rid of problems with Apache or other web server reserved file names.

At the moment there are four limitations for file names in place:

1. Limitations of the Server, so its operating system + apparently Apache
2. Limitations of NTFS file system (Windows)
3. Limitations of the HFS+ file system (Macintosh)
4. Limitations of any possible *nix file system (typically ext4 probably)

And these are imposed to every user.

While individual clients have to deal with the limitations of their respective file systems, I guess that the first limitation, the server's file system, should be priority. And this problem can be solved by hashing the file names I think.

**Comment by RealRancor** [comment] 2015-09-14 06:50
Hi,

just see the comment here https://github.com/owncloud/client/issues/854#issuecomment-77575766:

> fyi: This is being worked on for ownCloud Server 8.1 on a broader scope.

No clue about the status so you might want to have a search if there are any existing issues here in core tracked.

**Comment by MorrisJobke** [comment] 2015-10-09 07:30
This is a duplicate of #13640 where the storage should define what characters are allowed.

**Closed by MorrisJobke** 2015-10-09 07:30 UTC
