### ISSUE TITLE
[Beta 2] Text mimetype not recognized when renamed by recipient for a shared file

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#11572] opened 2014-10-14 14:56 UTC
When I share only a file with a user without a mimetype, the rename to add a mimetype by the recipient is not recognized by ownCloud (in this case a text file). If the file owner renames it, the mimetype is recognized. 

This only happens when only a file is shared, and only if the file that is shared is in the root folder. If a file is placed within a shared directory with the proper privelages, then it all works.

Steps to reproduce:
- Create a (text-) file without suffix in your root-directory
- Share it with another user
- Let the user rename it to text.txt
-> The file is not recognized by the GUI as a text file and will not be opened by the editor
- Note: this rename works if the file owner renames the file
- The problems also does not appear, if the file is inside a shared folder
- The user you shared the file with cannot delete the file
- Sharing files is possible, if they are inside a shared (and writeable) folder

ownCloud 7 EE beta 2

**Comment by nickvergessen** [comment] 2015-03-24 12:15
Well the problem is, that there is only one file cache entry for the file. When the share receiver renames the file, only the `file_target` of the share entry is updated, not the filecache entry.

So I don't think this is resolvable atm, closing as will not fix.

**Closed by nickvergessen** 2015-03-24 12:15 UTC
Labels: bug, sev4-low, triage
