### ISSUE TITLE
Refresh loop when accessing a public folder protected with password

### ISSUE THREAD

**Issue by DylannCordel** [owncloud/core#23754] opened 2016-04-02 21:17 UTC
### Steps to reproduce
1. Share a folder by public link **with password** (and modification allowed : not required)
2. Disconnect
3. Go to this public link
4. Enter the password

### Expected behaviour

Display the content of the folder

### Actual behaviour
Infinite reload + 401 in HTTP responses for those requests : 

* `/index.php/apps/gallery/config.public?extramediatypes=1&token=xxx` if gallery app is activated
* `/public.php/webdav/` with gallery app deactivated, even if external storage app is deactivated

### Server configuration
**Operating system:** Debian Jessie

**Web server:** Apache 2 + PHP5-FPM

**Database:** PostgreSQL

**PHP version:** 5.6.17

**ownCloud version:** 9.0.0.19

**Updated from an older ownCloud or fresh install:** updating from last debian update

**Where did you install ownCloud from:** apt-get from official owncloud repository

**List of activated apps:**

```
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
    "system": {
        "instanceid": "oc08ebfb9ae0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.dedidream.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.dedidream.com",
        "dbtype": "pgsql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "dedidream.com",
        "theme": "",
        "maintenance": false,
        "forceSSLforSubdomains": true,
        "allow_user_to_change_display_name": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF"
        ],
        "loglevel": 0,
        "asset-pipeline.enabled": true,
        "enable_avatars": true,
        "appstoreenabled": true,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
```

#### ownCloud log (data/owncloud.log)
```
 Debug 	webdav 	Exception: {"Message":"HTTP\/1.1 401 Username or password was incorrect","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php(82): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/public.php(74): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false} 	2016-04-02T21:09:53+00:00
Debug 	no app in context 	[TokenCheckException] JSON response 	2016-04-02T21:09:53+00:00
Debug 	no app in context 	[TokenCheckException] Missing password 	2016-04-02T21:09:53+00:00
Error	gallery	Exception: Missing password (401)	2016-04-02T21:09:53+00:00
```

**Comment by enoch85** [comment] 2016-04-03 02:34
Refs: https://github.com/owncloud/core/issues/22977

**Comment by nickvergessen** [comment] 2016-04-04 14:21
@georgehrke

**Comment by georgehrke** [comment] 2016-04-04 14:35
also cc @oparoz

**Comment by oparoz** [comment] 2016-04-05 12:34
Yet another problem with a page using the wrong template

**Comment by inpos** [comment] 2016-04-07 17:15
Same here
`Apr  7 20:14:40 cloud ownCloud[5151]: {gallery} Exception: Missing password (401)`

**Comment by inpos** [comment] 2016-04-07 18:31
if disable password protection everything ok.

**Comment by ownbug** [comment] 2016-04-07 19:01
If I disable password authentication, owncloud behaves normally. I am able to view the files.

**Comment by RealRancor** [comment] 2016-04-14 19:05
Duplicate of https://github.com/owncloud/core/issues/23066  which is still open?

**Closed** 2016-04-15 09:42 UTC
Labels: bug
