### ISSUE TITLE
Failed upgrade from Owncloud 10.0.0.1 to Owncloud 10.0.1

### ISSUE THREAD

**Issue by jerryjharrison** [owncloud/core#28015] opened 2017-05-26 09:53 UTC
### Steps to reproduce
1.  Used PKG to update components
2.  Logged into web access
3.  selected upgrade

### Expected behaviour
Upgrade proceeds

### Actual behaviour
Upgrade fails when updating the database schema

### Server configuration
freebsd v 11

**Web server:**
Apache 2.3

**Database:**
Mariadb/sqllite

**PHP version:**
5.6.3

**ownCloud version:** (see ownCloud admin page)
10.0.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
pkg

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc3utla48am4',
  'passwordsalt' => '4LDgzsSLtAPHFYulorr6tePAKz+TsX',
  'secret' => 'QUZM/gomWpEdBDaWINKgWlXE61R3zEkknMGzVOcHJfi63/7L',
  'trusted_domains' =>
  array (
    0 => '10.0.1.78',
    1 => 'jerryharrison.net',
    2 => 'share.dyndns.biz',
  ),
  'datadirectory' => '/mnt/ocdata',
  'overwrite.cli.url' => 'http://10.0.1.78/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.0.0.12',
  'dbname' => 'jjhoc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_jerryjharriso',
  'dbpassword' => 'Y9h94ISVnEpTK/wg70yzOUk0PtM78K',
  'logtimezone' => 'UTC',
  'installed' => true,
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'rockcreekequity.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.fatcow.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'jerry.harrison@rockcreekequity.com',
  'mail_smtppassword' => 'Rockcr33k',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"TgqOoCMokEFlhdgbY03I","level":3,"time":"2017-05-26T09:33:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"UXnYNDs4SkfQ4oulY8B1","level":3,"time":"2017-05-26T09:33:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"KvutK1cuATrZqalqYD1Q","level":3,"time":"2017-05-26T09:33:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"1LpCP6vJAESFWEUDCuPp","level":3,"time":"2017-05-26T09:33:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"eqss6fqG1tBt9tjNiH35","level":3,"time":"2017-05-26T09:34:15+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"7kgF7c7giyYg7IOaZriT","level":3,"time":"2017-05-26T09:34:15+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"dcj0kn7foLfgs7OBTTpx","level":3,"time":"2017-05-26T09:34:47+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"cCgH2FDZpf2Oh7mP57F8","level":3,"time":"2017-05-26T09:34:47+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"2btSaR54RPv7Y0hTyjQr","level":3,"time":"2017-05-26T09:35:19+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"6oO6pQwXng1ZMjST5hr2","level":3,"time":"2017-05-26T09:35:19+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"3coJrmzkO3egWFWVJTbV","level":3,"time":"2017-05-26T09:35:51+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"4KiK3dRb44kXwH6Codbs","level":3,"time":"2017-05-26T09:35:51+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"122HlbNLoAVyqcR1ihZk","level":3,"time":"2017-05-26T09:36:23+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"PlwMPmZeDKscJknUMZQx","level":3,"time":"2017-05-26T09:36:23+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"Hrx45s86EWS9eIvgOn9F","level":3,"time":"2017-05-26T09:36:55+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"XdXZI4otiBMmzS4ddnGq","level":3,"time":"2017-05-26T09:36:55+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"L9cvCdYxC9ViORSHDzkN","level":3,"time":"2017-05-26T09:37:27+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"ZlRqJKweK17h1jruF3b0","level":3,"time":"2017-05-26T09:37:27+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"QYbeUU0Cm6Vyem8knLYf","level":3,"time":"2017-05-26T09:37:59+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"pWu7fxGApPhsLbE533yR","level":3,"time":"2017-05-26T09:37:59+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"AApCikSg6C0dJ00DWcfM","level":3,"time":"2017-05-26T09:38:31+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"Iz2AVHfQbfsIIpckBFaK","level":3,"time":"2017-05-26T09:38:31+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"dfBJBklZdIzf10NcngQi","level":3,"time":"2017-05-26T09:39:03+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"ivyoWgiaooqpf2jYy28s","level":3,"time":"2017-05-26T09:39:03+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"beKDZH8XVnflVlThchbL","level":3,"time":"2017-05-26T09:39:35+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"DzVdQY0RZP9AyjNmBH6c","level":3,"time":"2017-05-26T09:39:35+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"VG9PyW0okwLq1DiHGVc7","level":3,"time":"2017-05-26T09:40:07+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"DmUA7b7LckGfcQvia0w7","level":3,"time":"2017-05-26T09:40:07+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"l4UQglE7UnPsdkPkKWkg","level":3,"time":"2017-05-26T09:40:39+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"FX8ooeyTyOJqXqaafv8Q","level":3,"time":"2017-05-26T09:40:39+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"3N9kgUfZ5D6n8SnNoUWt","level":3,"time":"2017-05-26T09:41:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"AO71iuU4Ub5WrtU8Zp0j","level":3,"time":"2017-05-26T09:41:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"Vj7wkH6Am41tHio50bHi","level":3,"time":"2017-05-26T09:41:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"DoryicXlH6MootZJnGdA","level":3,"time":"2017-05-26T09:41:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"71dQCck37SQLGqNhhfnz","level":3,"time":"2017-05-26T09:42:15+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"urrLUCmuChi9UwJovVlJ","level":3,"time":"2017-05-26T09:42:15+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"aHgcQc8wo3BmUZQCDCbm","level":3,"time":"2017-05-26T09:42:47+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"KBn0iyYxGYaR8QA8Xpqt","level":3,"time":"2017-05-26T09:42:47+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"BA4CdHWoW2Es1FZ9cCAk","level":3,"time":"2017-05-26T09:43:19+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"sQ47YDONFSzOUdX7Pjn2","level":3,"time":"2017-05-26T09:43:19+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"TK3re8aJrOKPLs8ciENf","level":3,"time":"2017-05-26T09:43:51+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"Y7v6zJdqU0dTdc1oB5gM","level":3,"time":"2017-05-26T09:43:51+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"Rwn0OiEw6MO5vWaPZaU1","level":3,"time":"2017-05-26T09:44:23+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"0MNf5IubYC1t37JgogVB","level":3,"time":"2017-05-26T09:44:23+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"mI23y3Bp3h6nbRcMc2P7","level":3,"time":"2017-05-26T09:44:55+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"BrFextabUkM8W6sF7bRX","level":3,"time":"2017-05-26T09:44:55+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"VamYpsZZcg8xNuZp00aI","level":3,"time":"2017-05-26T09:45:27+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"rwolshA97zjXBlSGARFQ","level":3,"time":"2017-05-26T09:45:27+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"fnCfxTadjEidt8LyJDpS","level":3,"time":"2017-05-26T09:45:59+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"jMvTefpFevUNhZxXf1F9","level":3,"time":"2017-05-26T09:45:59+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"uZgrxx0TLMFXEChL0gxq","level":3,"time":"2017-05-26T09:46:27+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/heartbeat","message":"You are using a fallback implementa$
{"reqId":"dTC7wui3fdtBh4v7vYOd","level":3,"time":"2017-05-26T09:46:31+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"eUcQzuX4AchyaMuVBHzW","level":3,"time":"2017-05-26T09:46:31+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"7c5wK94Ol4AXAgWxBW7o","level":3,"time":"2017-05-26T09:47:03+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"rrdAfLN6bXA9rrgPvwNB","level":3,"time":"2017-05-26T09:47:03+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"2QSRX4u0P6PCLpfrudAW","level":3,"time":"2017-05-26T09:47:35+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"DnblDwpVQjiEajKR5Pvz","level":3,"time":"2017-05-26T09:47:35+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"RTItrlHG2tjBJZvY0wpb","level":3,"time":"2017-05-26T09:48:07+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"ssO6c7wXSZtXkPjHOqbB","level":3,"time":"2017-05-26T09:48:07+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"EzsRGHokkGj9qpndxPOv","level":3,"time":"2017-05-26T09:48:39+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"OQIrfeR269klzPGhCjqw","level":3,"time":"2017-05-26T09:48:39+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"sOg09eXeSJJz1VZ0DwSF","level":3,"time":"2017-05-26T09:49:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"42Qrgp9S3a5MZtREMOCT","level":3,"time":"2017-05-26T09:49:11+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$
{"reqId":"JxGtxvZcPqZhRENIlcgX","level":3,"time":"2017-05-26T09:49:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/status.php","message":"You are using a fallback implementation of the$
{"reqId":"WjnhgZ0JEK8SVFnhFerQ","level":3,"time":"2017-05-26T09:49:43+00:00","remoteAddr":"10.0.1.20","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/danaharrison\/","message":"You are using$

**Comment by jerryjharrison** [comment] 2017-05-26 09:55
sorry...  The upgrade fails with this error:
Updating database schema
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by PVince81** [comment] 2017-05-26 10:20
@DeepDiver1975 another one about index size.

Closing as duplicate of https://github.com/owncloud/core/issues/28007

**Closed by PVince81** 2017-05-26 10:20 UTC
