### ISSUE TITLE
[Experimental locking] Some smashbox locking tests fail for ownCloud 8.1.1beta1

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17909] opened 2015-07-27 13:51 UTC
Tests that failed when run all together caused by an unexpected locked exception (probably due to a stray redis key) but passed when run one by one:
* download + move file (test_downloadFilePlusAction.py t3)
* download + move folder (test_downloadFilePlusAction.py t7)
* overwrite + delete folder (test_overwriteFilePlusAction.py t5)

Tests that failed when run all together caused by a failed check but passed when run one by one:
* overwrite + overwrite (test_overwriteFilePlusAction.py t0)
* overwrite + delete file (test_overwriteFilePlusAction.py t4)

Tests that failed in both cases caused by an unexpected locked exception (all together and one by one)
* overwrite + download file (test_overwriteFilePlusAction.py t1)
* overwrite + download directory (test_overwriteFilePlusAction.py t3)

For the first and third set of tests, the locked exception is thrown in the first action (download or overwrite) when there shouldn't be any lock active.
The second set fail due to the extra checks: overwrite + overwrite reports a wrong filesize, and the overwrite + delete file doesn't delete the file for 2 of the 3 accounts.

I'd appreciate a second run in order to confirm.

**Comment by DeepDiver1975** [comment] 2015-07-27 14:11
@jvillafanez your fix should be there : https://github.com/owncloud/core/pull/17911

**Comment by PVince81** [comment] 2015-07-27 15:37
@jvillafanez I ran the tests:
`bin/smash -a lib/oc-tests/new_locking/test_downloadFilePlusAction.py` from the locking_tests branch

All passed without and with transactional locking enabled (redis) on stable8.1 e8cbfd16a2ae0f697222b57b3114fb8b989199c5

**Comment by PVince81** [comment] 2015-07-27 15:41
on the v8.1.1beta1 tag it also works fine.
I even have the files_locking app enabled.

So either it's because I tested the git version and the tarball is the one that have issues, or race conditions.

@jvillafanez please tell us what exact version you were testing (tarball, enterprise, etc)

**Comment by PVince81** [comment] 2015-07-27 15:43
and my laptop has an SSD, so maybe too fast to be able to reproduce the issue reliably.

**Comment by PVince81** [comment] 2015-07-27 17:31
https://github.com/owncloud/core/issues/17911 has been merged into stable8.1. With a bit of luck the issue you observed might be fixed. @jvillafanez can you rerun the tests on your environment ?

**Comment by jvillafanez** [comment] 2015-07-28 09:18
I've checked again against today's stable8.1 8.1.1 beta1 (daily) Build:2015-07-28T04:52:11+00:00 a949f6c5762c12f53559fb4329a9ec9e7ce5b415 

The download tests passed fine this time.

There are some problems with the overwrite tests:
* overwrite + download file (test_overwriteFilePlusAction.py t1)
* overwrite + download directory (test_overwriteFilePlusAction.py t3)

This time it was different than the previous one: from what I look in the trace, the extra checks failed due to a locked exception. While the overwrite is being made, the downloads fail with a locked exception (this is expected), but when the overwrite finish and retry the download, we still get the locked exception.

**Comment by PVince81** [comment] 2015-07-28 09:20
@icewind1991

**Comment by DeepDiver1975** [comment] 2015-07-28 09:39
@jvillafanez basicSync test are failing for me as well ... https://ci.owncloud.org/job/smashbox/

**Comment by DeepDiver1975** [comment] 2015-07-28 10:12
@jvillafanez can you please test basicSync as well? THX

**Comment by jvillafanez** [comment] 2015-07-28 12:30
Tests for basicSync passed fine against today's stable8.1

**Comment by PVince81** [comment] 2015-07-29 09:16
test_basicSync works for me when run repeatedly without XDebug.

@DeepDiver1975 when I enable XDebug, I get random errors.
Note that since I have PHP 5.6 an XDebug bug sometimes causes PHP to run out of file handles (see https://github.com/owncloud/core/issues/10392#issuecomment-64249533)

Do we have XDebug enabled on smashbox-CI too ?

**Comment by DeepDiver1975** [comment] 2015-07-29 09:38
> Do we have XDebug enabled on smashbox-CI too ?

no

**Comment by PVince81** [comment] 2015-07-29 09:54
Ok, without XDebug now.

Ran tests several times:
- without encryption: :white_check_mark: tests pass
- with encryption: :no_entry_sign: getting errors
- with locking: TODO

Result with encryption:
```
SUMMARY:smash.:runid: 150729-114915
SUMMARY:smash.:URL: http://test:***@127.0.0.1/owncloud/remote.php/webdav/
SUMMARY:smash.:Running iteration 1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #0 {'basicSync_filesizeKB': 1, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #1 {'basicSync_filesizeKB': 5000, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #2 {'basicSync_filesizeKB': 15000, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #3 {'basicSync_filesizeKB': 50000, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #4 {'basicSync_filesizeKB': 1, 'basicSync_rmLocalStateDB': True}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #5 {'basicSync_filesizeKB': 5000, 'basicSync_rmLocalStateDB': True}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #6 {'basicSync_filesizeKB': 15000, 'basicSync_rmLocalStateDB': False}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
SUMMARY:smash.:running lib/test_basicSync.py in /home/vincent/work/smashdir/test_basicSync as test testset #7 {'basicSync_filesizeKB': 50000, 'basicSync_rmLocalStateDB': True}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
2015-07-29 11:52:55,518 - ERROR - checker - expected 2 got 1 deleted files error_check(len(expected_deleted_files) == len(actual_deleted_files), "expected %d got %d deleted files"%(len(expected_deleted_files),len(actual_deleted_files))) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 70]
2015-07-29 11:52:55,524 - ERROR - checker - expected deleted file for TEST_FILE_DELETED_WINNER.dat not found error_check(any([fn in dfn for dfn in actual_deleted_files]), "expected deleted file for %s not found"%fn) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 73]
2015-07-29 11:52:55,533 - ERROR - creator - expected 2 got 1 deleted files error_check(len(expected_deleted_files) == len(actual_deleted_files), "expected %d got %d deleted files"%(len(expected_deleted_files),len(actual_deleted_files))) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 70]
2015-07-29 11:52:55,536 - ERROR - creator - expected deleted file for TEST_FILE_DELETED_WINNER.dat not found error_check(any([fn in dfn for dfn in actual_deleted_files]), "expected deleted file for %s not found"%fn) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 73]
2015-07-29 11:52:55,547 - ERROR - winner - expected 2 got 1 deleted files error_check(len(expected_deleted_files) == len(actual_deleted_files), "expected %d got %d deleted files"%(len(expected_deleted_files),len(actual_deleted_files))) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 70]
2015-07-29 11:52:55,549 - ERROR - winner - expected deleted file for TEST_FILE_DELETED_WINNER.dat not found error_check(any([fn in dfn for dfn in actual_deleted_files]), "expected deleted file for %s not found"%fn) failed in expect_deleted_files() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 73]
md5sum: /home/vincent/work/smashdir/test_basicSync/checker/TEST_FILE_DELETED_WINNER.dat: No such file or directory
2015-07-29 11:52:55,690 - ERROR - checker - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/checker/TEST_FILE_DELETED_WINNER.dat: expected 863f3ed728e4ef9afa7de307f09f1bd1, got NO_CHECKSUM_ERROR error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
md5sum: /home/vincent/work/smashdir/test_basicSync/winner/TEST_FILE_DELETED_WINNER.dat: No such file or directory
md5sum: /home/vincent/work/smashdir/test_basicSync/creator/TEST_FILE_DELETED_WINNER.dat: No such file or directory
2015-07-29 11:52:55,703 - ERROR - winner - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/winner/TEST_FILE_DELETED_WINNER.dat: expected 863f3ed728e4ef9afa7de307f09f1bd1, got NO_CHECKSUM_ERROR error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
2015-07-29 11:52:55,704 - ERROR - creator - inconsistent md5 of /home/vincent/work/smashdir/test_basicSync/creator/TEST_FILE_DELETED_WINNER.dat: expected 863f3ed728e4ef9afa7de307f09f1bd1, got NO_CHECKSUM_ERROR error_check(actual_md5 == md5, "inconsistent md5 of %s: expected %s, got %s"%(fn,md5,actual_md5)) failed in expect_content() ["/home/vincent/work/workspace/smashbox/lib/test_basicSync.py" at line 61]
2015-07-29 11:52:56,727 - ERROR - winner - 3 error(s) reported
2015-07-29 11:52:56,732 - ERROR - creator - 3 error(s) reported
2015-07-29 11:52:56,736 - ERROR - checker - 3 error(s) reported
CRITICAL:smash.:Aborting run -- non-zero exit code (2)
```

**Comment by PVince81** [comment] 2015-07-29 09:55
@schiesbn see above

**Comment by PVince81** [comment] 2015-07-29 11:57
Locking tests ran fine (without encryption)

I'll raise a separate ticket for basicsync + encryption failures.

Closing.

**Closed by PVince81** 2015-07-29 11:57 UTC
Labels: feature:locking, sev2-high, smashbox

**Comment by PVince81** [comment] 2015-07-29 12:04
Raised encryption issue here: https://github.com/owncloud/core/issues/17956
