### ISSUE TITLE
invalid_hash .htaccess .user.ini

### ISSUE THREAD

**Issue by eemirtekin** [owncloud/core#23765] opened 2016-04-04 08:52 UTC
### Steps to reproduce
1. Install OwnCloud 9.0 from the https://download.owncloud.org/community/owncloud-9.0.0.zip
2. Convert the database from sqlite to mysql
3. Login as admin

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: CentOS Linux release 7.2.1511 (Core)

**Web server: nginx version: nginx/1.8.1**

**Database**:mysql  Ver 14.14 Distrib 5.7.11, for Linux (x86_64) using  EditLine wrapper

**PHP version**:PHP 7.0.4 (cli)

**ownCloud version:** ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.0.0.zip

**Signing status (ownCloud 9.0 and above):**

```
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)

No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.

Please double check the installation guides ↗, and check for any errors or warnings in the log.
```

**List of invalid files:**
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => cea2aac862c5b888ffcb8a1dd938e9db728d049e77f69082ca8e809393f32453297e8c9382e4da26e4b29b58055f804060aff1c6a2b916b917be42b4603e56f3
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

        )

)
```
**List of activated apps:**

```
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc09oq57e40i",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.yasar.edu.tr"
        ],
        "datadirectory": "\/home\/cloud\/public_html\/data",
        "overwrite.cli.url": "https:\/\//owncloud.example.net",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "au_cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
{"reqId":"+eLvJq8NNTup5n2yJyq3","remoteAddr":"10.1.241.240","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_admin\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'au_user'@'localhost' for table 'user'","level":3,"time":"2016-04-04T08:37:03+00:00"}
{"reqId":"+eLvJq8NNTup5n2yJyq3","remoteAddr":"10.1.241.240","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `au_cloud` . * TO 'au_user'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'au_user'@'localhost' to database 'au_cloud'","level":3,"time":"2016-04-04T08:37:03+00:00"}
{"reqId":"+eLvJq8NNTup5n2yJyq3","remoteAddr":"10.1.241.240","app":"PHP","message":"Undefined offset: 0 at \/home\/cloud\/public_html\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-04-04T08:37:03+00:00"}
{"reqId":"+eLvJq8NNTup5n2yJyq3","remoteAddr":"10.1.241.240","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/cloud\\\/pub...')\\n#4 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/cloud\\\/pub...')\\n#5 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/cloud\\\/public_html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/cloud\\\/public_html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-04T08:37:04+00:00"}
{"reqId":"+eLvJq8NNTup5n2yJyq3","remoteAddr":"10.1.241.240","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/cloud\\\/pub...')\\n#4 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/cloud\\\/pub...')\\n#5 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/cloud\\\/public_html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/cloud\\\/public_html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-04T08:37:04+00:00"}
{"reqId":"P+QrGOo3LCoLByjv6jiL","remoteAddr":"10.1.241.240","app":"PHP","message":"Undefined index: newVersionString at \/home\/cloud\/public_html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-04T08:37:14+00:00"}
{"reqId":"L3dKeSoLaNkVoK\/jXDp1","remoteAddr":"10.1.241.240","app":"PHP","message":"Undefined index: newVersionString at \/home\/cloud\/public_html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-04T08:38:56+00:00"}
{"reqId":"F01Xao5V8CUYDvySwXh1","remoteAddr":"10.1.241.240","app":"PHP","message":"Undefined index: newVersionString at \/home\/cloud\/public_html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-04T08:45:29+00:00"}
{"reqId":"p3Ny1XKl4GbK9rNGf4Zu","remoteAddr":"10.1.241.240","app":"PHP","message":"Undefined index: newVersionString at \/home\/cloud\/public_html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-04T08:45:35+00:00"}
 
```

**Comment by RealRancor** [comment] 2016-04-04 09:26
Duplicate of https://github.com/owncloud/core/issues/23144 (and i think some more) which gets fixed with https://github.com/owncloud/core/pull/23250 in the upcoming oC 9.0.1 (released tomorrow).

**Closed** 2016-04-04 09:49 UTC

**Comment by FreshMarv** [comment] 2016-06-13 15:43
I accedently deleted the original .user.ini - how can I restore it?

**Comment by RealRancor** [comment] 2016-06-13 15:47
@FreshMarv From the download packages at https://owncloud.org/changelog

For further support questions please use the forums or the users mailinglist (https://owncloud.org/support/)

**Comment by redoverture** [comment] 2016-08-17 03:36
This issue was not fixed in oC 9.0.1 . I am running the latest stable release and I am experiencing the same issue.

**Comment by bartatgithub** [comment] 2016-08-18 14:03
Same here, i got the invalid_hash .htaccess since upgrade to 9.0.4, now same issue with upgrade to 9.1.

**Comment by TheFonix** [comment] 2017-03-27 11:33
Me too

**Comment by kdslkdsaldsal** [comment] 2017-03-29 16:25
Make sure that you're extracting/copying over the new ``.htaccess`` and ``.user.ini`` files during the upgrade. People are missing this and then you get the issue seen here... There is most likely nothing what can be done here from ownCloud side.

**Comment by TheFonix** [comment] 2017-03-29 17:52
Yup the .user.ini messed mine up, it didn't copy over, fixed by the moving
