### ISSUE TITLE
Doctrine\DBAL\DBALException: Unknown database type  requested, OC\DB\OCSqlitePlatform may not support it. Update failed

### ISSUE THREAD

**Issue by philthephatman** [owncloud/core#24610] opened 2016-05-12 23:10 UTC
### Steps to reproduce
1. Update Owncloud 9.0.1>9.0.2

### Expected behaviour
Update successful

### Actual behaviour
Error: Doctrine\DBAL\DBALException: Unknown database type  requested, OC\DB\OCSqlitePlatform may not support it.
Update failed

### Server configuration
Linux Mint Rosa 17.3

Apache 2.4.20

SQlite3

PHP 5.6.21

Updated to 9.0.2
Updated from 9.0.1

trusty repo

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: true
  - mail: 0.4.2
  - news: 8.7.4
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - shorten: 0.0.15
  - systemtags: 0.2
  - templateeditor: 0.1
  - transmission: 0.2
  - updatenotification: 0.1.0
Disabled:
  - files_embeddedvideo
  - files_pdfviewer
  - files_videoviewerplus
  - gallery
  - html5_videoplayer
  - libreonline
  - mobilecomp
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

<?php
$CONFIG = array (
  'instanceid' => 'secret',
  'passwordsalt' => 'secret',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => '127.0.0.1',
    1 => '192.168.2.111',
    2 => 'ukle-MCP73',
    3 => secret
    4 => secret
    5 => '192.168.1.111',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://127.0.0.1/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'secret',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'secret',
  'mail_smtpauthtype' => 'LOGIN',
  'ldapIgnoreNamingRules' => false,
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpauth' => 1,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No external storage

**Are you using encryption:** yes/no

No encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/..

No external user-backend.

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
Firefox 46.0
Linux Mint 17.3

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```

{"reqId":"secret","remoteAddr":"127.0.0.1","app":"core","message":"starting upgrade from 9.0.1.3 to 9.0.2.2","level":0,"time":"2016-05-12T22:31:14+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=secret","user":"--"}
{"reqId":"56RlijVZ+91ElGtXeCMm","remoteAddr":"127.0.0.1","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Unknown database type  requested, OC\\\\DB\\\\OCSqlitePlatform may not support it.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(288): Doctrine\\\\DBAL\\\\Platforms\\\\AbstractPlatform->getDoctrineTypeMapping('')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(820): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnDefinition(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SqliteSchemaManager.php(228): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->_getPortableTableColumnList('sqlite_stat1', '\\\/var\\\/www\\\/ownclo...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(175): Doctrine\\\\DBAL\\\\Schema\\\\SqliteSchemaManager->_getPortableTableColumnList('sqlite_stat1', '\\\/var\\\/www\\\/ownclo...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(281): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableColumns('sqlite_stat1')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(268): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTableDetails('sqlite_stat1')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/AbstractSchemaManager.php(1040): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->listTables()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/repair\\\/sqliteautoincrement.php(60): Doctrine\\\\DBAL\\\\Schema\\\\AbstractSchemaManager->createSchema()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\SqliteAutoincrement->run()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(313): OC\\\\Repair->run()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.2.2', '9.0.1.3')\\n#11 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Platforms\\\/AbstractPlatform.php\",\"Line\":423}","level":3,"time":"2016-05-12T22:31:14+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=secret","user":"--"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-05-13 04:03
Duplicate of https://github.com/owncloud/core/issues/24313

**Closed** 2016-05-13 07:44 UTC

**Comment by philthephatman** [comment] 2016-05-13 11:43
Two reasons (actually three):

1. I'm brand new. Never really even posted in a forum before (true story), so I have no clue what is polite, or right, or courteous, etc.
2. The issue was never resolved. Wanted to let everyone know it still exists after the RC.
3. I believe I had provided more details here.

**Comment by RealRancor** [comment] 2016-05-13 11:52
Sure, but it still won't help to have two issues open about the same problem. It just fills the open issues and won't make things going faster. If you have more details you can also post those at the still open issues.
