### ISSUE TITLE
Large File Upload Issue with ownCloud Client and 32-bit server

### ISSUE THREAD

**Issue by NathanZepol** [owncloud/core#6973] opened 2014-01-27 22:35 UTC
Hello,

I seem to be having issues uploading files above 2GB with the Windows OwnCloud client. I have tested using a zip file, and during the upload process, the OwnCloud client says it's uploading the whole zip file (2.71 GB), but when you view the zip file through the Owncloud browser UI after the upload has been completed, it shows the file is only 2GB.

I have adjusted all my settings according to the guide here; http://doc.owncloud.org/server/5.0/admin_manual/configuration/configuring_big_file_upload.html

Current settings in PHP.ini:
memory_limit	512M
upload_max_filesize	15G
post_max_size	15G
output_buffering = 16384

"Admin" section of OwnCloud browser UI:
Maximum upload size: 15 GB

I have removed the PHP_values from the .htaccess file that OwnCloud provides after installing. If I were to add those PHP_values back, and change them from the default 512M, I am no longer able to log into the OwnCloud browser UI, as it rejects my username and password even though the credentials are correct. After learning that those values cannot be changed inside of the .htaccess from the default 512M, I have removed them and changed them directly within the PHP.ini.

Server Information:
CentOS - Linux 2.6.32-431.3.1.el6.i686
OwnCloud - 6.0.1 (stable)
OwnCloud Windows Client - 1.5.0 (build 1913)
Windows 7 - 64bit

OwnCloud Sync App Screenshot: https://dl.dropboxusercontent.com/u/10571366/Capture.PNG

**Comment by bantu** [comment] 2015-03-25 16:10
@DeepDiver1975 The root cause for this here is likely the same as in https://github.com/owncloud/core/issues/11270#issuecomment-86079640 Even if it is not exactly the same issue, this issue becomes irrelevant if the environment is Apache + mod_php5 as there is basically no way we can support that on 32-bit PHP.

@NathanZepol Can you confirm that you were using Apache + mod_php5 ?

**Comment by NathanZepol** [comment] 2015-10-12 22:07
Correct, at the time I was using Apache + mod_php5.

**Comment by MorrisJobke** [comment] 2015-12-11 12:38
> Even if it is not exactly the same issue, this issue becomes irrelevant if the environment is Apache + mod_php5 + 32-bit as there is basically no way we can support large files on that.

-> we can't do anything

Additional 32 bit support for large files is tracked in #7138 -> closing

**Closed by MorrisJobke** 2015-12-11 12:38 UTC
Labels: enhancement
