### ISSUE TITLE
Allow login using email address with app passwords

### ISSUE THREAD

**Issue by jas4711** [owncloud/core#25550] opened 2016-07-21 11:17 UTC
This is a request for an enhancement.  With OC 9.1 it is possible to login using email address using your standard password.  If you use an app password, it is not possible to use that for login with the email address, only the normal username.  It would be nice if it was possible to authenticate using email address and an app password.

The use case for this is DAVDroid: if you configure it with email address + password, it would automatically locate and discover and login to your ownCloud instance if you have the proper DNS records redirecting the client to your ownCloud CalDAV/CardDAV server.  Using an app password is appropriate for a DAVDroid client.

Thanks!

**Comment by gruentee** [comment] 2016-07-21 20:58
This is probably a duplicate of [#21537](https://github.com/owncloud/core/issues/21537)

**Comment by PVince81** [comment] 2016-07-22 06:50
@jas4711 I think this should work in 9.1 with one condition: when you generate the token, you need to login with the email address into ownCloud. Then upon generating the token, it should tell you which user name you can use with it. That user name is usually the one used for login.

If that doesn't work then it's a bug.

**Comment by PVince81** [comment] 2016-07-22 06:51
CC @ChristophWurst

**Comment by ChristophWurst** [comment] 2016-07-22 07:09
> @jas4711 I think this should work in 9.1 with one condition: when you generate the token, you need to login with the email address into ownCloud. Then upon generating the token, it should tell you which user name you can use with it. That user name is usually the one used for login.

Nope, because we *convert* the email of the user to its UID, which is then used to log in. This is related to the discussion we had in https://github.com/owncloud/core/issues/25392.

**Comment by jas4711** [comment] 2016-07-22 07:40
@gruentee Not quite -- the #21537 issue is about the ability to login using email address and your normal password, and that was fixed by https://github.com/owncloud/core/issues/2927 and I can confirm that works fine.  This bug is about doing the same with an app-specific password.

@PVince81 As far as I can tell @ChristophWurst is correct that this doesn't work.  After login with email address, my normal username is still shown in the app-specific username field.

I believe the use case for this bug is "allow username and email address to be used interchangeably for authentication with an app-specific password".

**Comment by DeepDiver1975** [comment] 2016-08-29 17:35
works for me with master/9.2 ....

**Comment by DeepDiver1975** [comment] 2016-08-29 17:36
works for my in stable9.1 as well ...

**Comment by DeepDiver1975** [comment] 2016-08-29 17:41
I did generate an app password and used that one together with the email address is cadaver

@jas4711 mind testing this again? THX

**Comment by PVince81** [comment] 2016-09-20 10:07
Closing due to lack of feedback

**Closed by PVince81** 2016-09-20 10:07 UTC
Labels: bug, comp:authentication, needs info

**Comment by mmccarn** [comment] 2017-04-03 11:37
For anyone else who finds this conversation (not to reopen the issue):

I'm using a modified version of the IMAP auth that requires '@' in the username during login, and adds a default domain if there is not any '@'.

Everything in my instance works great -- except app passwords didn't quite work right.

This comment from @PVince81 got me working:
> @jas4711 I think this should work in 9.1 with one condition: when you generate the token, you need to login with the email address into ownCloud. Then upon generating the token, it should tell you which user name you can use with it. That user name is usually the one used for login.

Apparently, my owncloud can still tell if my browser login username was "username" or "username@mailserver.tld" -- even though everything else in Owncloud sees and uses only "username@mailserver.tld".

If I'm logged in to the browser session as "username", I get an app password tied to the shorter user name (without '@mailserver.tld'), which doesn't work with my desktop client's existing account that was originally configured using the full username.

However, if I logout and log back in in my browser as "username@mailserver.tld", the resulting app password works great.

Owncloud: 9.1.4.2
Client: 2.3.0 (build 4097) / mac

**Comment by ownclouders** [comment] 2017-12-21 01:05
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
