### ISSUE TITLE
Unable to connect after upgrade from 9.0.2 to 9.1.0.15

### ISSUE THREAD

**Issue by falco22** [owncloud/core#25833] opened 2016-08-17 08:56 UTC
### Steps to reproduce
1. Have a running Owncloud in 9.0.2
2. pkg upgrade 
3. su www -c "/usr/local/www/owncloud/occ upgrade"
4. try to login as an user to owncloud webui

### Expected behaviour
owncloud should open the first windows

### Actual behaviour
I stay on the "login"  page eternally
If I try to login with "admin" user, it works. But if I try to use the "Users" button, it's also never end

### Server configuration
**Operating system**:
FreeBSD 9.3-RELEASE-p13
**Web server:**
lighttpd-1.4.41
**Database:**
mysql56-server-5.6.30
**PHP version:**
php56-5.6.24_1
**ownCloud version:** (see ownCloud admin page)
9.1.0.15
**Updated from an older ownCloud or fresh install:**
upgrade from 9.0.2
**Where did you install ownCloud from:**
official FreeBSD package
**Signing status (ownCloud 9.0 and above):**
No errors have been found.
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.


**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.3.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - documents: 0.13.1
  - encryption: 1.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - bookmarks
  - calendarplus
  - files_antivirus
  - notes
  - ownnote
  - tasks
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc46c7ded0e6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "calypso.recusses.org"
        ],
        "datadirectory": "\/usr\/local\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_from_address": "owncloud",
        "mail_domain": "recusses.org",
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "appstore.experimental.enabled": false,
        "trashbin_retention_obligation": "auto",
        "cipher": "AES-256-CFB"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "31"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.3.2",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "calendarplus": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "ocsid": "170560",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.3.1.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "no",
            "global_cache_gc_lastrun": "1438240366",
            "installedat": "1411490925.431",
            "lastcron": "1471424230",
            "lastupdateResult": "[]",
            "lastupdatedat": "1471424222",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_calendarplus": "calendarplus\/share.php",
            "public_calendarplusevent": "calendarplus\/shareevent.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendarplus": "calendarplus\/appinfo\/remote.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "no",
            "shareapi_allow_public_upload": "yes",
            "shareapi_exclude_groups": "no",
            "shareapi_only_share_with_group_members": "no",
            "umgmt_show_backend": "false"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.5",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "yes",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "masterKeyId": "master_f78623eb",
            "publicShareKeyId": "pubShare_cd51d500",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "recoveryKey_d04a1d82",
            "types": "filesystem"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.07",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.5",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 48.0
**Operating system:**
Kubuntu 16.04
### Logs
#### Web server error log
```
2016-08-17 10:24:23: (mod_fastcgi.c.2694) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in /usr/local/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php on line 823
2016-08-17 10:33:05: (mod_fastcgi.c.2694) FastCGI-stderr: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 632 bytes) in /usr/local/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91

Notes that it's the same issue if I set memory_limit to -1 in php.ini : php-cgi process grow and grow to more than 800M but after a long time, I can see also "Allowed memory size of 536870912 bytes exhausted ..."
 
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-08-17 09:34
@falco22 This is a duplicate of https://github.com/owncloud/core/issues/25557 which gets fixed with the upcoming 9.1.1

**Closed** 2016-08-18 07:51 UTC
