### ISSUE TITLE
File Locking results in slowing down stuff massively

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#19888] opened 2015-10-20 10:16 UTC
This makes some stuff _really_ cumbersome to use, just a decent example:

![2015-10-20_11-46-30](https://cloud.githubusercontent.com/assets/878997/10603872/f35066fe-7720-11e5-97f7-83550cb6dd78.png)

![2015-10-20_12-15-02](https://cloud.githubusercontent.com/assets/878997/10604382/33549772-7724-11e5-8584-c3da92588c13.png)

Profile is at https://blackfire.io/profiles/f1d6349f-4ab3-4190-beab-ccbd59527844/graph

Ref https://github.com/owncloud/core/issues/10077#issuecomment-149499679

**Comment by LukasReschke** [comment] 2015-10-20 10:18
Note that I personally don't consider "Use Redis-based cache" a feasible solution, just in case before somebody brings that up :speak_no_evil:

**Comment by LukasReschke** [comment] 2015-10-20 10:19
22 `getDirectoryContent` calls result in 638 (!!!) queries on the database.

**Comment by LukasReschke** [comment] 2015-10-20 10:20
@cmonteroluque @icewind1991 @karlitschek THX

**Comment by DeepDiver1975** [comment] 2015-10-20 10:58
> 22 getDirectoryContent calls result in 638 (!!!) queries on the database.

Nice - how does the folder structure look like?

**Comment by LukasReschke** [comment] 2015-10-20 10:59
> Nice - how does the folder structure look like?

15 files and 55 folders, one of those being the gigantic "Shared" folder on S3. But I assume that rather reflects regular business useage.

**Comment by DeepDiver1975** [comment] 2015-10-20 11:03
> But I assume that rather reflects regular business usage.

sure - I just wanted to get the relation between files system and calls ...

@icewind1991 please fire up your analysis modules :wink:

**Comment by icewind1991** [comment] 2015-10-20 11:07
Will look into reducing the amount of lock calls we make

I have some ideas for it

**Comment by DeepDiver1975** [comment] 2015-10-20 11:07
> I have some ideas for it

This is the answer I was expecting - THX

**Comment by karlitschek** [comment] 2015-10-20 11:20
Thanks guys for looking into that. I think I don't have to stress how important this is.

**Comment by DeepDiver1975** [comment] 2015-10-20 11:43
> I think I don't have to stress how important this is.

for sure not - @icewind1991  work on this already

**Comment by icewind1991** [comment] 2015-10-20 12:11
Re-using shared locks within a request: https://github.com/owncloud/core/pull/19890

**Comment by PVince81** [comment] 2015-10-20 13:13
This is the gallery app, so I expect getDirectoryContents to be called several times recursively for every folder. It's basically scanning all subfolders to generate thumbnails. (or at least the next level, because the folder icon itself is constructed based on thumbnails of the contents)

**Comment by LukasReschke** [comment] 2015-10-20 15:28
Yup. But also affects stuff such as the regular list endpoint of the files app which on S3 now takes 711ms for me: https://blackfire.io/profiles/71104df0-140a-4bbf-bbc7-251f940246b5/graph

This is also after applying @icewind1991's patch.

**Comment by LukasReschke** [comment] 2015-10-21 17:37
This makes the activity app also unbearable slow. 5 seconds for a request on S3.

**Comment by oparoz** [comment] 2015-10-22 19:25
> This is the gallery app, so I expect getDirectoryContents to be called several times recursively for every folder. It's basically scanning all subfolders to generate thumbnails. 

Yes and the wider the tree, the longer it takes. Deep trees are normally not much of an issue, unless you've got an image buried very deep. In any case, during this phase, we're only scanning the tree, so the cache should return answers really quickly.

**Comment by guruz** [comment] 2015-10-23 12:44
So if it is possibly the gallery app and not file locking, maybe this could be background'ized somehow?
Wild guess: And not triggered for uploads via sync/WebDAV (which is what @ogoffart might have seen when complaining about slow upload?)

**Comment by LukasReschke** [comment] 2015-10-23 12:46
> So if it is possibly the gallery app and not file locking, maybe this could be background'ized somehow?
> Wild guess: And not triggered for uploads via sync/WebDAV (which is what @ogoffart might have seen when complaining about slow upload?)

This has nothing to do with the gallery app. The gallery app is just one piece that gets slowed down as well by locking.

**Comment by icewind1991** [comment] 2015-10-23 13:13
Don't look the home folder since we never delete/rename it: #20004

**Comment by oparoz** [comment] 2015-10-23 13:32
> Don't look the home folder since we never delete/rename it: #20004

Good call :)

**Comment by LukasReschke** [comment] 2015-10-25 21:43
https://github.com/owncloud/core/issues/20027 is a case where a simple folder listing takes 610ms due to locking.

![2015-10-25_22-42-47](https://cloud.githubusercontent.com/assets/878997/10718052/b865b5a6-7b69-11e5-8f66-c921c26891d4.png)

**Comment by jospoortvliet** [comment] 2015-10-29 11:46
For my info. The 'normal' cache home users have, apc(u), doesn't solve this? It takes me about 10 seconds to switch to the gallery in my home folder at home, and half a minute before it shows the folders. Subsequently going into my pictures folder isn't as terrible as it used to be, takes about half a minute again to load the first bunch of pics and progresses reasonably quick after that.

But still - painful, considering I have a quad core i5 and 16 gb ram on that server, with the database residing on a SSD. Would a home user have to install Redis, too, to get better performance?

**Comment by oparoz** [comment] 2015-10-29 12:06
> It takes me about 10 seconds to switch to the gallery in my home folder at home

@jospoortvliet That's the app loading. I could speed it up by loading all the JS files in Files, so that they're cached, but people are going to hate it ;)

> and half a minute before it shows the folders

You need to f-twelve it to figure out which ajax call is taking so long. It must be what's described in this thread as folders are now shown as soon as the list of what to show has been retrieved, before loading the thumbnails.
Now if that can't be solved via the standard DB cache, I don't think it's a problem to recommend everyone uses Redis. It's widely available, even in the official VM.

**Comment by jospoortvliet** [comment] 2015-10-29 12:11
@oparoz well, thing is that Redis requires quite some more work and config than acp(u) - that's increasing the barrier to using ownCloud, which is already raised significantly since we started to require people to manually enable acp(u) rather than auto-detecting it.

**Comment by oparoz** [comment] 2015-10-29 13:06
> well, thing is that Redis requires quite some more work and config than acp(u)

Ah, it's true that I didn't take into consideration the pecl extension, but it's usually super easy to install on something like Linux since extensions come pre-packaged and are auto-enabled, no?

**Comment by jospoortvliet** [comment] 2015-11-02 15:41
Depends on the distribution and I bet some sacrifical chickens will be involved in some situations...

**Comment by oparoz** [comment] 2015-11-02 17:46
:)

**Comment by PVince81** [comment] 2015-11-03 17:13
Is there anything left here to be done for 8.2.1 regarding performance ?
@icewind1991 Any ideas where to optimize further ?

**Comment by icewind1991** [comment] 2015-11-03 17:17
> Is there anything left here to be done for 8.2.1 regarding performance ?

#20053

> @icewind1991 Any ideas where to optimize further ?

Not atm, would like to see some more blackfire traces with everything applied

**Comment by LeCoyote** [comment] 2015-11-04 09:25
#20277 was indeed a duplicate of this one. May I suggest that this issue be openly advertised to people upgrading to 8.2? It can be quite unnerving to track down a IO issue like this :) Thanks!

**Comment by PVince81** [comment] 2015-11-04 09:27
CC @jospoortvliet

**Closed by PVince81** 2015-11-04 09:27 UTC
Labels: bug, feature:locking, performance, regression

**Comment by jospoortvliet** [comment] 2015-11-04 11:49
@PVince81 seems something for the release notes, that's where we should put caveats. 8.2.1 is out soon and should solve it, of course.

Want me to add it to the release notes?

**Comment by PVince81** [comment] 2015-11-04 11:54
@jospoortvliet yes you can add a note in the 8.2.1 release notes that it improves performance.
Or did you want to edit the 8.2.0 release notes to add a hint ?
