### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException

### ISSUE THREAD

**Issue by walkenreaper** [owncloud/core#20516] opened 2015-11-15 19:02 UTC
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "music.page.index" as such route does not exist.

**Comment by RealRancor** [comment] 2015-11-15 19:10
Hi,

@walkenreaper Thats an duplicate of https://github.com/owncloud/core/issues/19145

You can close this and re-run the update again which should work.

**Closed** 2015-11-15 22:32 UTC
