### ISSUE TITLE
423 Locked when upload a file after a disconnection

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/core#17254] opened 2015-06-30 10:42 UTC
Server version: 

```
    {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":""}
```

Steps:
1- Upload a file with curl
curl -X PUT -v --progress-bar -u user:pass "http://SERVER/remote.php/webdav/file.MOV" -F myfile=@"/Users/Javi/file.MOV"
2- Remove the connection (disconnect ethernet cable) and wait untile time out of curl.
3- Connect again the computer
4- Upload the same file with curl

Current behavior:
Once the file finish the upload we receive a 423 response and the file not appear in the list of files:
        < HTTP/1.1 423 Locked

Expected behavior:
File should be upload

It works fine with the Files_Locking App enable or disable. It does not work when the transactional File Locking is active.

Logs:

```
Exception: {"Message":"HTTP\/1.1 423 \"file.MOV\" is locked","Code":0,"Trace":"
#0 \/opt\/owncloud\/lib\/private\/connector\/sabre\/directory.php(111): OC\\Connector\\Sabre\\File->put(Resource id #28)\n
#1 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('file.MOV', Resource id #28)\n
#2 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('file.MOV', Resource id #28, NULL)\n
#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#4 \/opt\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#5 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n
#6 \/opt\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#7 \/opt\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n
#8 \/opt\/owncloud\/remote.php(84): require_once('\/opt\/owncloud\/a...')\n#9 {main}","File":"\/opt\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":198}
```

**Comment by DeepDiver1975** [comment] 2015-06-30 10:55
same scenario as with https://github.com/owncloud/files_locking/issues/39

**Comment by DeepDiver1975** [comment] 2015-06-30 10:56
Is there a shutdown handler on php side missing? @icewind1991

**Comment by javiergonzper** [comment] 2015-06-30 11:03
Sorry @DeepDiver1975 @icewind1991 
It works fine with the Files_Locking App enable or disable. It does not work when the transactional File Locking is active.

**Comment by DeepDiver1975** [comment] 2015-06-30 11:15
> It works fine with the Files_Locking App enable or disable. It does not work when the transactional File Locking is active.

 owncloud/files_locking#39 is telling a different story - please keep in mind that encryption being enabled or disabled has an impact.

**Comment by javiergonzper** [comment] 2015-06-30 11:21
@DeepDiver1975 encryption is disabled. If you want I can check it with encryption enabled

**Comment by PVince81** [comment] 2015-06-30 12:48
>It works fine with the Files_Locking App enable or disable. It does not work when the transactional File Locking is active.

Are you sure ? In the original ticket you said you disabled "Files_Locking" and it worked fine.
Now you are saying disabling Transactional locking to make it work.

The former would match https://github.com/owncloud/files_locking/issues/39

**Comment by rperezb** [comment] 2015-06-30 13:17
@PVince81 sorry for the confusion.
Yes, this bug is related to the transactional_file locking, with it is enable it leads to this behavior.

We though that it could be related to the fact of having enable the files_locking, disable it, nothing changes, it still fails.

**Comment by PVince81** [comment] 2015-06-30 13:19
Thanks.

I cannot explain this issue.
Normally I'd expect Apache to keep the PHP request running even if the connection was closed.

Because there are shutdown handlers that automatically unlock files at the end of a request.

Now maybe that PHP request is also running into a timeout situation, in which case there is no wait to automatically unlock files, because the request is killed. No further code can be executed. The solution for this would be to have a TTL for locks: #16966

**Comment by PVince81** [comment] 2015-06-30 13:38
Hmm if the file list is not browseable then it's an additional issue. In general a lock shouldn't block that.

**Comment by PVince81** [comment] 2015-06-30 14:12
@javiergonzper if I understand well the folder is still browseable here, is that correct ? (in the other ticket it isn't)

**Comment by PVince81** [comment] 2015-06-30 15:59
@javiergonzper you're on Apache, right ? Do you use php-fpm ?

**Comment by PVince81** [comment] 2015-06-30 16:01
@icewind1991 and I did some tests on Apache and nginx + php-fpm and saw that even if the connection is lost, the PHP request continues running.

So for now the only explanation would be that the PHP request runs for so long that it reaches PHP timeout.

**Comment by PVince81** [comment] 2015-06-30 16:10
I cannot reproduce this issue.

I tried monitoring with redis-cli, type `monitor`.

When the transfer starts, I see:
```
1435680490.667382 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.670019 [0 127.0.0.1:57475] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.670089 [0 127.0.0.1:57475] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.670193 [0 127.0.0.1:57475] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.670254 [0 127.0.0.1:57475] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.670360 [0 127.0.0.1:57475] "UNWATCH"
1435680490.676345 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.676715 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.677713 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.677982 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.686812 [0 127.0.0.1:57475] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.686920 [0 127.0.0.1:57475] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.687067 [0 127.0.0.1:57475] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.687205 [0 127.0.0.1:57475] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.687353 [0 127.0.0.1:57475] "UNWATCH"
1435680490.695016 [0 127.0.0.1:57475] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.695143 [0 127.0.0.1:57475] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.695271 [0 127.0.0.1:57475] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.695430 [0 127.0.0.1:57475] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.695544 [0 127.0.0.1:57475] "UNWATCH"
1435680490.712253 [0 127.0.0.1:57475] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.712340 [0 127.0.0.1:57475] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.712422 [0 127.0.0.1:57475] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.712492 [0 127.0.0.1:57475] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680490.712560 [0 127.0.0.1:57475] "UNWATCH"
1435680490.712858 [0 127.0.0.1:57475] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.712926 [0 127.0.0.1:57475] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.712999 [0 127.0.0.1:57475] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.713061 [0 127.0.0.1:57475] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.713120 [0 127.0.0.1:57475] "UNWATCH"
1435680490.717830 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/570083c83ca8f9fffd22dd3da4e9d31c"
1435680490.718171 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680490.718476 [0 127.0.0.1:57475] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
```

After I disconnect the VM's network, after a second or so I see:
```
1435680506.872874 [0 127.0.0.1:57471] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680506.872989 [0 127.0.0.1:57471] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680506.873107 [0 127.0.0.1:57471] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680506.873182 [0 127.0.0.1:57471] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680506.873246 [0 127.0.0.1:57471] "UNWATCH"
1435680506.873338 [0 127.0.0.1:57471] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680506.873456 [0 127.0.0.1:57471] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680506.873592 [0 127.0.0.1:57471] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680506.873652 [0 127.0.0.1:57471] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/28a23ef7d2b67cd904d21af0e32e9aad"
1435680506.873713 [0 127.0.0.1:57471] "UNWATCH"
1435680506.873807 [0 127.0.0.1:57471] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/570083c83ca8f9fffd22dd3da4e9d31c"
1435680506.873860 [0 127.0.0.1:57471] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/570083c83ca8f9fffd22dd3da4e9d31c"
1435680506.873938 [0 127.0.0.1:57471] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/570083c83ca8f9fffd22dd3da4e9d31c"
1435680506.873995 [0 127.0.0.1:57471] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/570083c83ca8f9fffd22dd3da4e9d31c"
1435680506.874051 [0 127.0.0.1:57471] "UNWATCH"
1435680517.521291 [0 127.0.0.1:57479] "INCR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680517.523871 [0 127.0.0.1:57479] "EXISTS" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680517.523959 [0 127.0.0.1:57479] "DECR" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680517.524045 [0 127.0.0.1:57479] "WATCH" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680517.524130 [0 127.0.0.1:57479] "GET" "cc729126482099a8571d51be5c15b233/lockfiles/2a2694688f159d7d04bd51bd0534851f"
1435680517.524204 [0 127.0.0.1:57479] "UNWATCH"
```

And if I restart the transfer, it works.

Could be a difference in setup/environment ?

I have this:
- openSUSE Factory
- apache2-2.4.12-7.1.x86_64 with mod_php
- php5-5.6.9-1.1.x86_64

**Comment by icewind1991** [comment] 2015-06-30 16:17
According to the comments on https://secure.php.net/manual/en/function.register-shutdown-function.php the shutdown function should work correctly if we hit the max execution time

**Comment by cmonteroluque** [comment] 2015-06-30 18:22
Moving to 8.1.1, not enough information to stop RC

**Comment by javiergonzper** [comment] 2015-07-01 07:14
@PVince81 our enviroment is:
owncloud-8.1.0RC1.tar.bz2
ubuntu_lamp_redis:late
Server version: {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":""}

If you want I can provide you an account and also an access by ssh

**Comment by PVince81** [comment] 2015-07-01 07:24
Is it the old RC1 from two weeks ago ?

@icewind1991 and I tested on master which is more recent.

If you still see this issue in RC2 we'll need ssh credentials.

**Comment by javiergonzper** [comment] 2015-07-01 09:12
Ok, I will check it on RC2 :+1:

**Comment by javiergonzper** [comment] 2015-07-01 09:50
@PVince81 on RC2 it works... but I created this bug to simulate other bug that we have on the iOS App that still happening... funny.

**Comment by nasli** [comment] 2016-07-26 17:08
Happens again within 9.1.0.15
1.Upload a file inside a folder "/a" and while it is uploading network connection lost
2.Network connection back
3.Try to upload again same file
4.Try to delete the folder "/a" 

Current behavior:
3.  error file locked 423
>Logs CURL:
< HTTP/1.1 423 Locked
< Date: Tue, 26 Jul 2016 17:00:41 GMT
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.13
...
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"a/file.MOV" is locked</s:message>
</d:error>


4.  It is not possible to delete the folder

**Comment by PVince81** [comment] 2016-08-08 07:51
Yes, if there is a disconnection it is likely that the PHP process got killed and could not clear the lock.
The file will auto-unlock after an hour when the TTL is reached.

This is a known issue. I hope we'll find a good solution one day...

**Comment by PVince81** [comment] 2016-08-08 07:51
@rperezb why was this tagged as regression ? In which version did it work in the past ? (it might have worked in very old OC that had no locking)

**Comment by PVince81** [comment] 2016-12-07 10:23
This PR might fix it https://github.com/owncloud/core/pull/26775 as it will prevent the PHP request to be killed and let it do its cleanup.

**Comment by PVince81** [comment] 2017-02-06 10:35
Please try again with 9.1.4 or 9.0.8 where the locks should be freed properly upon disconnection

**Closed by PVince81** 2017-02-06 10:35 UTC
Labels: bug, feature:locking, regression
