### ISSUE TITLE
work through the trashbin tests and see which ones need tests for both webdav versions

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36108] opened 2019-08-28 09:19 UTC
the trashbin API only works on the "new" webdav path
Check the current tests and eliminate those that do not really need be run on both old/new webdav API path

**Comment by phil-davis** [comment] 2019-11-04 03:41
@dpakach did we review these trashbin API combinations already in another issue?

**Comment by dpakach** [comment] 2019-11-04 04:17
> @dpakach did we review these trashbin API combinations already in another issue?

@phil-davis I'm currently working on it. The issue is #36302. I think we can close this one.

**Closed** 2019-11-04 05:11 UTC
Labels: 1 - To develop, QA-team
