### ISSUE TITLE
[feature request] Ability to add comment when sharing files

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/core#11313] opened 2014-09-26 10:30 UTC
When sharing files with others, it would often useful to be able to add a short comment to explain the context of what's being shared, explain the file or just add a friendly note.

I would expect that it would be entered in the same popup (with "notify by email / can share / can edit) and that it would be visible at least in the email notification.

If possible, it would be useful to also have it show on the share link page and maybe as a hover bubble notification when the cursor hovers over the file icon / filename in the files app.

**Comment by jancborchardt** [comment] 2015-11-11 15:27
Duplicate of https://github.com/owncloud/core/issues/9253

Otherwise, comments will be implemented for 9.0

**Closed by jancborchardt** 2015-11-11 15:27 UTC
Labels: enhancement
