### ISSUE TITLE
Get CI running on forks + older branches

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21346] opened 2015-12-23 08:07 UTC
We have now successfully managed to break different master and stable unit tests by not executing the tests properly against forks or older branches in under 24 hours.

Ref https://github.com/owncloud/core/issues/21345 and https://github.com/owncloud/core/issues/21339

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment] 2015-12-23 09:10
My statement is clear on this: reading helps!

Why are prs with fail status merged?

**Comment by RealRancor** [comment] 2015-12-23 10:12
Ref: https://github.com/owncloud/core/issues/19885

**Comment by PVince81** [comment] 2015-12-23 11:39
This ticket was already raised for CI on forks: https://github.com/owncloud/core/issues/19885

**Comment by MorrisJobke** [comment] 2016-01-06 07:26
Duplicate of #19885

**Closed by MorrisJobke** 2016-01-06 07:26 UTC
Labels: jenkins
