### ISSUE TITLE
ownCloud calculates Quota wrong

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#22765] opened 2016-03-01 22:21 UTC
### Steps to reproduce
1. Set up a computer with a small and a big hdd (e.g. 20gb and 500gb)
2. Install operating system, server and ownCloud at the small hdd
3. move data directory to big hdd

### Expected behaviour
Quota should be (x mb / 500gb)

### Actual behaviour
Quota is (x mb / 18gb) - i think the quota is calculated from the hdd where the instance is running instead of the data directory (i think it says only 18 gb instead of 20 gb for the operating system)

### Server configuration
**Operating system**: debian netinstall without gui

**Web server:** apache2

**Database:** mysql5.5

**PHP version:** php5

**ownCloud version:** (see ownCloud admin page) 8.2.2

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** ??? well, downloaded from the website...

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

-> Redirects to files app

**List of activated apps:** default

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - external
  - files_external
  - user_external

```

**The content of config/config.php:**
Nothing special except the data-directory which points to the mounted 500 gb ext4-formatted hdd
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

{
    "system": {
        "datadirectory": "\/mnt\/datahdd\/owncloud",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.102"
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

contains too much sensitive data - if needed please ask, otherwise its too much work currently.
```

### Client configuration
**Browser:** any

**Operating system:** any

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by blizzz** [comment] 2016-03-02 00:25
@icewind1991

**Comment by PVince81** [comment] 2016-03-02 09:28
> i think the quota is calculated from the hdd where the instance is running instead of the data directory

`disk_free_space` should already be called on the data directory. Not sure why this doesn't work properly. You could try adding a debug statement here: https://github.com/owncloud/core/blob/v8.2.2/lib/private/files/storage/local.php#L255 and check the return value of `$this->getSourcePath($path)`.

On my local dev instance I mounted a tmpfs 1GB ramdisk on the "data" folder and the total always shows as 1GB. My root partion where the ownCloud source is has 60 GB free.

**Comment by nickvergessen** [comment] 2016-03-02 11:27
Since I have the same issue on my cloud, I can have a look

**Comment by nickvergessen** [comment] 2016-03-02 11:37
Okay, just tested:
I have the home of a user on a separate disc
> Du verwendest 338.2 GB der verfügbaren 2.7 TB

A user that is on the source disc has
> Du verwendest 1.6 MB der verfügbaren 167.2 GB

Can you give more information about your setup?
Which path is your data dir, and which path the is mount of the external drive?

**Comment by stefan-niedermann** [comment] 2016-03-03 12:27
Err, not sure what you mean, @nickvergessen 
Path to ownCloud installation is `/var/www/html/owncloud` (small "main" hdd)
Path of the data dir is `/mnt/datahdd/owncloud` (big "data" hdd)

> A user that is on the source disc has

What does mean "A user that is on the source disc"? Since i changed the data dir i expected that the data of *every* user is now on `/mnt/datahdd/owncloud` ?

@PVince81:
> You could try adding a debug statement

Will try when i have more time...

**Comment by PVince81** [comment] 2016-03-09 17:49
@stefan-niedermann please post the relevant entries of your "mtab", just in case.

I'll try and reproduce this locally when I find some time.

**Comment by PVince81** [comment] 2016-03-09 17:50
and also `df -h` with the mount points :smile:

**Comment by PVince81** [comment] 2016-03-15 09:53
I just created a similar setup locally:

1. Create a folder "/srv/www/ocdata"
1. `mount -t tmpfs -o size=1024M tmpfs /srv/www/ocdata`
1. Setup OC 8.2.2 in "/srv/www/htdocs/owncloud"
1. Move "data" folder contents to "/srv/www/ocdata" (make sure to also move the hidden dot files)
1. In the web UI as admin, go to the personal page

It shows "You have used 163 B of the available 1023.9 MB" (the small file is welcome.txt)

This is correct. If I do the same without the tmpfs then it shows my root partitions total space instead.

Seems to work correctly.

Maybe you PHP version's "disk_free_space" doesn't work as expected ?

**Comment by stefan-niedermann** [comment] 2016-03-15 10:28
I have currently no access to the computer, i will post more information when i have.

**Comment by PVince81** [comment] 2016-03-21 14:38
You can also try running this script:
```php
var_dump(disk_free_space('/mnt/datahdd/owncloud/'));
```

**Comment by PVince81** [comment] 2016-03-23 13:47
@cmonteroluque moving this to 9.0.2 until we have more info

**Comment by cmonteroluque** [comment] 2016-03-24 10:21
@PVince81 I agree

**Comment by PVince81** [comment] 2016-06-02 17:33
Closing due to lack of feedback.

**Closed by PVince81** 2016-06-02 17:33 UTC
Labels: bug, feature:quota, needs info, sev2-high
