### ISSUE TITLE
Bulk move of files in web view

### ISSUE THREAD

**Issue by dickerpulli** [owncloud/core#29859] opened 2017-12-15 08:27 UTC
I have a feature request for web view.

I often move files from one directory to another. It is very laborious to do this at the moment. You have to move the files by drag&drop but this is limited by moving them into a subfolder of there current position or into a direct parent directory.

I see something like a move button nearby the download and delete button in the header of the file list. With a click it opens a new view in wich you can choose the directory to move the selected files to.

Thanks in advance.

**Comment by ownclouders** [comment] 2017-12-15 08:35
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment] 2017-12-15 11:04
Duplicate of https://github.com/owncloud/core/issues/8570, extended by "drag and hold on folders or breadcrumbs" https://github.com/owncloud/core/issues/8570#issuecomment-42955394.

**Closed by PVince81** 2017-12-15 11:04 UTC
Labels: app:files, enhancement

**Comment by dickerpulli** [comment] 2017-12-15 14:41
@PVince81 I don't see the duplication with #8570 because this is no drag&drop issue.

**Comment by PVince81** [comment] 2017-12-15 14:52
You're right... There are too many tickets with similar topics. The ticket I meant is this one: https://github.com/owncloud/core/issues/10656
