### ISSUE TITLE
AWS SDK should be updated

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#23923] opened 2016-04-11 15:43 UTC
AWS S3 experience is painful in many ways in ownCloud.
Currently I'm having exactly issue described in https://github.com/owncloud/core/issues/10501 with ownCloud 8.2.3 (stable).
However, before posting anything I decided that it is necessary to upgrade AWS SDK from very old 2.7.5 to modern version 3.17.5 (at the time of writing) and I think this should be better done sooner than later.

Otherwise random errors will appear again and again with very high probability that they were already fixed upstream long time ago.

**Comment by LukasReschke** [comment] 2016-04-11 17:26
Dupe of https://github.com/owncloud/core/issues/14893

**Closed by LukasReschke** 2016-04-11 17:26 UTC
