### ISSUE TITLE
Single file in folder - file not found

### ISSUE THREAD

**Issue by hhaeb** [owncloud/core#24272] opened 2016-04-26 09:34 UTC
Downloading a file which is the only file in this folder is impossible. When there are more files in this folder, downloading of this file is possible.

### Steps to reproduce
1. make a new folder
2. copy one file into folder
3. go to this folder
4. click checkbox of this single file
5. click on "Download"

### Expected behaviour
OS window for downloading this file should appear.

### Actual behaviour
Screen displays the following text:
"File not found
The specified document has not been found on the server.
You can click here to return to ownCloud."

########################## WORKAROUND
copy another file in the same folder
click checkbox of this single file
click on "Download"
=> OS window for downloading this file should appear.
### Server configuration
Ubuntu 14.04.4 LTS

**Web server:**
Apache/2.4.7

**Database:**
MySQL 5.5.49 

**PHP version:**
PHP Version 5.5.9-1ubuntu4.16

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
updated from 7.x

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - documents
  - encryption
  - external
  - files_external
  - notes
  - notifications
  - ownnote
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'oc3f7f39cb42',
  'passwordsalt' => '8f16ab646ea1003620a39b8f9f4eb8',
  'trusted_domains' => 
  array (
    0 => 'promedia-online.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_haeb',
  'dbpassword' => '18e213b2e2422d7742858d840d7de9',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'Zq3PbhBHyjnSLAdaKdDldIfXx40MPhL87CD/6oKEfAXT',
  'loglevel' => 0,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => 'auto',
  'mail_from_address' => 'haeb',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'promedia-sds.de',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'promedia-online.net',
  'mail_smtpport' => '587',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'haeb@promedia-sds.de',
  'mail_smtppassword' => 'xxxxxxx',
  'updatechecker' => false,
  'overwrite.cli.url' => '/owncloud',
);
```

```json
    "system": {
        "instanceid": "oc3f7f39cb42",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "promedia-online.net"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "haeb",
        "mail_smtpmode": "smtp",
        "mail_domain": "promedia-sds.de",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "promedia-online.net",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "overwrite.cli.url": "\/owncloud"
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

#### LDAP configuration
--

### Client configuration
**Browser:**
Firefox 38.7.1 / CHrome  38.7.1 -> same behvior
**Operating system:**
Win7 x64

#### Web server error log WITH SINGLE FILE
promedia-online.net 79.229.76.187 - - [26/Apr/2016:10:26:13 +0200] "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=Dokument2.txt&downloadStartSecret=wbhka67qls HTTP/1.1" 404 10826 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
#### Web server error log WITH MORE FILES in the same directory
promedia-online.net 79.229.76.187 - - [26/Apr/2016:10:26:52 +0200] "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2FTEST2&files=Dokument2.txt&downloadStartSecret=h5cb2mnq8a6 HTTP/1.1" 200 51 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0"
###

#################### 
Both log snipplets are displaying the successful/failed download of the SAME FILE in the SAME FOLDER the file is located in "/TEST2" ("/TEST/Dokument2.txt" notice the different path in log files)
The only difference was: in the second trial there was another file in the folder "/TEST2"
####################

#### ownCloud log (data/owncloud.log)
no log entry for the specific time

**Comment by nickvergessen** [comment] 2016-04-26 11:00
PS: You need to be two folders deep, and that already shows the problem:

I couldn't reproduce with `test/welcome.txt`,
but when you upload `test/test1/welcome.txt` you see the error message on `/index.php/apps/files/ajax/download.php?dir=%2Ftest&files=welcome.txt`
so it is missing `test1` in there...

**Comment by hhaeb** [comment] 2016-04-26 12:20
The bug appears in my installation, as you can see in the error log snipplet 'with a single file', in folder TEST2 which is no subfolder:
`GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=Dokument2.txt&downloadStartSecret=wbhka67qls `

The snipplet 'with more files' shows this first level folder:
`GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2FTEST2&files=Dokument2.txt&downloadStartSecret=h5cb2mnq8a6`

While playing i found an entry in ownCloud log (data/owncloud.log):
delete Dokument1.txt
placed a new file Dokument4.txt in TEST2
try to downlod it
=> not working
here it is the log snipplet
`[...]message":"Generating preview for \"\/TEST2\/Dokument4.txt\" with \"OC\\Preview\\TXT\"","level":0,"time":"2016-04-26T12:15:16+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2FTEST2%2FDokument4.txt[...]`

You see, it is the first level folder.

**Comment by PVince81** [comment] 2016-04-28 12:19
I thought this was fixed already, can you check with 9.0.2 RC1 ?

Somehow I can't find find any matching PR, so maybe it's a duplicate of a not yet fixed bug.

**Comment by nickvergessen** [comment] 2016-04-28 12:36
I used latest stable9 when I tagged it 2 days ago

**Comment by kgulti** [comment] 2016-05-13 13:17
Error still exist in ownCloud version 9.0.2.2 can someone copy who hast still also the failure?

**Comment by PVince81** [comment] 2016-05-13 13:21
@kgulti thanks for the confirmation. I remembered it wrong. This is still to be fixed.

**Comment by PVince81** [comment] 2016-05-13 13:21
Tagged as junior job if someone wants to have a go at fixing this.
Else this will be looked at in the bugfix phase of 9.1 (after feature freeze)

**Comment by RealRancor** [comment] 2016-05-23 15:26
@PVince81 Also looks like a duplicate of https://github.com/owncloud/core/issues/23613 ?

**Comment by popov-d** [comment] 2016-05-24 09:09
Sorry for duplicates again, and pull request #24800 is my fix.

**Comment by PVince81** [comment] 2016-06-02 16:52
Fixed by https://github.com/owncloud/core/issues/24800

**Closed by PVince81** 2016-06-02 16:52 UTC
Labels: app:files, bug, comp:core-js, junior job, sev3-medium
