### ISSUE TITLE
Modified date is not same using desktop-client or browser for uploading files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19503] opened 2015-10-01 11:28 UTC
If I upload a file via desktop client folder, in my browser appears the date when the file was modified locally, but if i drag & drop the file from my computer to the browser tab, last modified date is current date.

The desktop client syncs up the mtime of the file. I don't know if it is possible for the browser to know the mtime of a to-be-uploaded file or the current behaviour is the one desired

**Comment by PVince81** [comment] 2015-10-02 06:20
This is because the desktop client sends the mtime from the local file. I'm not sure the web browser APIs provide the mtime of the local time, but might be possible in modern browers (not IE)

**Comment by SergioBertolinSG** [comment] 2015-10-02 07:53
I think the behaviour should be the same as uploading files with the web ui, putting the date and time when the file is uploaded. Not sure if desktop client would have problems with this.
If client sends the time, I understand that the change should be done in the client. So no need to change anything in the server right?

@guruz What do you think?

**Comment by PVince81** [comment] 2015-10-02 08:01
@SergioBertolinSG I think it's by design for any file syncing solution to keep the mtime of the original files. The question is rather whether it would be possible to make the same happen for web UI uploads (if modern browsers permit)

**Comment by PVince81** [comment] 2015-10-02 08:03
From what I see here in Chromium, looks like the API tells us about the file's mtime:
![upload-fileinfo](https://cloud.githubusercontent.com/assets/277525/10241857/ca6818c8-68ec-11e5-8656-486393cbda9f.png)

**Comment by SergioBertolinSG** [comment] 2015-10-02 09:18
I've checked with mobile app, it puts the upload date and time like the web ui.

**Comment by rullzer** [comment] 2015-12-12 13:34
@SergioBertolinSG well then the mobile clients should be patched. If I move a bunch of documents to ownCloud I want see the same time as I see on my machine. Not the time they were uploaded.

**Comment by PVince81** [comment] 2016-02-12 10:35
The Webdav PUT improvement that will come in 9.1 will use the modern APIs to get the mtime and will set it. Also in 9.1 IE8-IE10 won't be supported any more, so with a bit of luck maybe all supported browsers will already provide this "lastModified" field :smile: 

Moving to 9.1 to match https://github.com/owncloud/core/pull/21237

**Comment by PVince81** [comment] 2016-10-14 15:43
Starting with 9.2, when uploading with the web browser it will use the original mtime. (unless using an older browser that doesn't expose that value)

**Closed by PVince81** 2016-10-14 15:43 UTC
Labels: discussion, enhancement
