### ISSUE TITLE
Deleted remote share file is not deleted from original sharing system

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13573] opened 2015-01-21 18:55 UTC
### Steps to reproduce

1. Install owncloud on two systems
2. On system one, remote share a directory that contains a file in it
3. On system two, accept the share and then delete the file
4. On system two, validate the file is deleted
5. On system one, validate the file is deleted

### Expected behaviour

The file is deleted from both systems

### Actual behaviour

The file is only deleted from system two; it is still present on system one.

I verified that this works as expected when sharing with local users.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by karlitschek** [comment] 2015-01-21 19:42
@schiesbn

**Comment by PVince81** [comment] 2015-01-21 20:06
Duplicate of https://github.com/owncloud/core/issues/13557

**Closed by PVince81** 2015-01-21 20:06 UTC
Labels: bug
