### ISSUE TITLE
cron.php fails with error 

### ISSUE THREAD

**Issue by bboule** [owncloud/core#24156] opened 2016-04-21 11:45 UTC
### Steps to reproduce
1. Run cron.php
2. Monitor the oc log file
3.

### Expected behaviour
Cron should run successfully 

### Actual behaviour
Cron job fails with the following error:

 PHP Fatal error: Call to a member function getQuota() on a non-object in /var/www/owncloud/apps/files_versions/lib/storage.php on line 691

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
Upgrade
**Where did you install ownCloud from:**
Tar
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**Comment by cmonteroluque** [comment] 2016-04-21 12:03
possibly related to https://github.com/owncloud/core/issues/23621

**Comment by cmonteroluque** [comment] 2016-04-21 12:05
also https://github.com/owncloud/core/issues/23534

@PVince81 high priority. Moving to 9.0.2

**Comment by PVince81** [comment] 2016-04-21 12:16
getQuota issue is duplicate of https://github.com/owncloud/core/issues/23513.

Closing in favor of https://github.com/owncloud/core/issues/23513, will move the labels and raise seveirty.

**Closed by PVince81** 2016-04-21 12:16 UTC
Labels: green-ticket, sev1-critical

**Comment by PVince81** [comment] 2016-04-21 13:10
@bboule do you have more information about what user management they are using ?
I could not reproduce the issue neither with local users nor LDAP users, even with simulated race conditions (see https://github.com/owncloud/core/issues/23513#issuecomment-212899844)

Maybe shibboleth ?
