### ISSUE TITLE
move the last user in a group and group disappear

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#12794] opened 2014-12-11 17:33 UTC
### Steps to reproduce
1. go to user management page
2. create a new group "abc" and add a new user "123" in this group 

   > *at this moment, sidebar shows that there is 1 user in the group abc*

3. open the drop down of group of user "123" and unselect the group "abc"
4. refresh the page

### Expected behaviour
User "123" is in the user list, but without group, Group "abc" is still in the group list, but with no user in it

### Actual behaviour
User "123" is in the user list, but without group, Group "abc" disappears.
**To compare**: after step 2, delete the user "123". The user "123" is gone, but the group "abc" is still there, with no user in it.

### Server configuration
Operating system: Ubuntu 13.10

Web server: apache 2.4.6 (Ubuntu)

Database: SQLite

PHP version: 5.5.3-1ubuntu2.3

ownCloud version: 7.0.4 & master

Updated from an older ownCloud or fresh install: owncloud 7.0.3

List of activated app:standard apps of owncloud and encryption

The content of config/config.php: (Without the database password and passwordsalt)
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),

);

Are you using external storage, if yes which one: no

### Client configuration
Browser: firefox 34.0.5

Operating system: ubuntu 13.10

**Comment by MadEgg** [comment] 2015-01-05 11:46
I'm experiencing more-or-less the same issue on OwnCloud 7.0.4, but even simpler:

To reproduce:
- Create a new group, do not add any user to it.
- Reload page. Notice that the new group is gone

Expected result:
- The newly added empty group is still there

Actual result:
- The newly added empty group is gone

Apparently, OwnCloud seems keen on not keeping groups around that are empty, but this is not intuitive and quite disappointing when this behaviour is discovered after adding 50 groups before starting adding users to these groups and the 50 groups have gone.

**Comment by Xenopathic** [comment] 2015-04-18 19:05
Unable to reproduce on oC 8.0.0. @dttpy @MadEgg Could you retry with the latest oC 7.0.*?

**Comment by MadEgg** [comment] 2015-04-21 09:22
I'm sorry, I just upgrade to OwnCloud 8.0.2 which does not show this problem. So it seems to be fixed. I cannot try this on 7.0.5 anymore because I already upgraded beyond that version.

**Comment by Xenopathic** [comment] 2015-04-21 10:15
Excellent - marking as solved

**Closed by Xenopathic** 2015-04-21 10:15 UTC
Labels: bug, settings:users
