### ISSUE TITLE
Proper error message on remote share with the same user twice

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#14799] opened 2015-03-11 13:37 UTC
1. Add a remote share via the share dropdown "user@remote.server.org/owncloud"
2. Add for the same file another share to the same user but with the protocol "user@https://remote.server.org/owncloud"

## Expected

This is already shared to this user

## Actual

Freigabe von welcome.txt fehlgeschlagen, da user@remote.server.org/owncloud nicht gefunden wurde. Möglicherweise ist der Server nicht erreichbar.

```
{"reqId":"fcd95516be9c54d620c93b977bcd7dab","remoteAddr":"127.0.0.1","app":"files_sharing","message":"server can not add remote share, An exception occurred while executing '\n\t\t\t\tINSERT INTO \"oc_share_external\"\n\t\t\t\t\t(\"remote\", \"share_token\", \"password\", \"name\", \"owner\", \"user\", \"mountpoint\", \"mountpoint_hash\", \"accepted\", \"remote_id\")\n\t\t\t\tVALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\n\t\t\t' with params [\"http:\\\/\\\/localhost\\\/master\\\/\", \"Ez51SMBUJebE3bb\", \"\", \"\\\/welcome (2).txt\", \"mjob\", \"muha\", \"\\\/welcome (2).txt\", \"3c5955c737575cfed3b0534eca80f0ba\", 0, 3]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_share_external.user, oc_share_external.mountpoint_hash","level":3,"time":"2015-03-11T13:34:38+00:00","method":"POST","url":"\/master\/ocs\/v1.php\/cloud\/shares?format=json"}
```

noticed while testing #13839

**Comment by MorrisJobke** [comment] 2015-03-11 13:38
cc @schiesbn @PVince81

**Comment by MorrisJobke** [comment] 2015-03-11 13:39
cc @nickvergessen

**Comment by nickvergessen** [comment] 2015-03-11 13:44
Duplicate of #13765

**Comment by nickvergessen** [comment] 2015-03-11 13:44
Related to https://github.com/owncloud/core/pull/14580

**Closed by nickvergessen** 2015-03-11 13:44 UTC
Labels: bug, feature:federated-cloud-sharing, sev4-low, Sharing
