### ISSUE TITLE
Toogle show/hidden system files, temporary, .DS_Store,.... in the web client...

### ISSUE THREAD

**Issue by aqxavier** [owncloud/core#14602] opened 2015-02-27 22:13 UTC
I'm looking for some option to perform this task, but can not find ..
I think it would be extremely importance can hide these file types to prevent the listing becoming dirty.

Regards,
Alexandre

**Comment by nickvergessen** [comment] 2015-02-28 08:50
You can also change your client to ignore those files, so they are not synced at all.

**Comment by LukasReschke** [comment] 2015-02-28 23:23
Looks like a duplicate of https://github.com/owncloud/core/issues/2589 to me

**Closed by LukasReschke** 2015-02-28 23:23 UTC
Labels: Enhancement

**Comment by aqxavier** [comment] 2015-03-01 12:11
The modification to clients (Mac / Pc) and mobiles. I had accompanied the discussion.
I'm referring to web clients ....
Did not find any solution to the case.
