### ISSUE TITLE
[User Management] Settings not saved

### ISSUE THREAD

**Issue by stonerl** [owncloud/core#16112] opened 2015-05-06 10:03 UTC
### Steps to reproduce
1. Go to the User Management page.
2. Click on the Settings-Cog and select an option. e.g. "Send email to new user"
3. Reload the User Management Page

### Expected behaviour
The selected options should be saved.

### Actual behaviour
Except for the "default quota", the options are not saved an have to be set each time the page gets opened. 

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.9

**ownCloud version:** (see ownCloud admin page)
8.0.3

**Updated from an older ownCloud or fresh install:**
updated from 7.0.4 but error appeared also with this Version

**List of activated apps:**
- Activity
- Calendar
- Contacts
- Deleted Files
- Documents
- External User Support
- File Locking
- First Run Wizard
- Full Text Search
- PDF Viewer
- Provisioning
- Share Files
- Text Editor
- Versions

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'oc91218af27b',
  'passwordsalt' => '###',
  'trusted_domains' => 
  array (
    0 => '###',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '###',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'sendmail',
  'loglevel' => 0,
  'logtimezone' => 'Europe/Berlin',
  'log_type' => 'owncloud',
  'log_authfailip' => true,
  'mail_domain' => '###',
  'default_language' => 'de_DE',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{###:993/imap/ssl/novalidate-cert}',
      ),
    ),
  ),
  'maintenance' => false,
  'overwritewebroot' => '/owncloud',
  'forcessl' => true,
  'appcodechecker' => false,
  'session_keepalive' => true,
  'remember_login_cookie_lifetime' => 2592000,
  'secret' => '###',
  'theme' => '',
  'skeletondirectory' => '',
  'overwrite.cli.url' => '###',
  'asset-pipeline.enabled' => true,
  'allowZipDownload' => true,
  'xframe_restriction' => true,
);
```

**Are you using external storage, if yes which one:**
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:**
OC_User_IMAP

### Client configuration
**Browser:** 
Firefox 37.0.2
Chrome 42.0.2311.135

**Operating system:** 
OS X 10.10.3

**Comment by MorrisJobke** [comment] 2015-05-06 11:03
Duplicate of #12727

**Closed by MorrisJobke** 2015-05-06 11:03 UTC
