### ISSUE TITLE
Group/Quta Multi-Selector Bug

### ISSUE THREAD

**Issue by dampfklon** [owncloud/core#20816] opened 2015-11-28 23:18 UTC
### Steps to reproduce
1. Have some more users
2. Go to users panel
3. Scroll down
4. Try to change assigned groups

### Expected behaviour
The multiselector shows up above/below the selected user

### Actual behaviour
The multiselector shows up somewhere on the page

### Server configuration
**Operating system**: CentOS

**Web server:** Apache/2.2.15

**Database:** MySQL

**PHP version:** 5.6.12

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** yes

### Client configuration
**Browser:** FF 42 & Chromium

**Operating system:** Ubuntu & Win10
![screenshot - 29 11 2015 - 00 11 21](https://cloud.githubusercontent.com/assets/1733625/11454510/65b82b2e-962e-11e5-8b96-f96abc77266b.png)
![screenshot - 29 11 2015 - 00 13 29](https://cloud.githubusercontent.com/assets/1733625/11454509/65b3b3aa-962e-11e5-98a8-687e8c11c8b3.png)

**Comment by PVince81** [comment] 2015-11-30 10:30
Duplicate of https://github.com/owncloud/core/issues/20503

**Closed by PVince81** 2015-11-30 10:30 UTC
Labels: bug, design, junior job, settings:users
