### ISSUE TITLE
After upgrade to 8.0.3 cannot enable activity app

### ISSUE THREAD

**Issue by jpschewe** [owncloud/core#16220] opened 2015-05-11 00:05 UTC
After I upgraded to 8.0.3 I tried to enable the activity plugin and got this response.
```
An exception occurred while executing 'CREATE TABLE "oc_activity" ("activity_id" SERIAL NOT NULL, "timestamp" INT DEFAULT 0 NOT NULL, "priority" INT DEFAULT 0 NOT NULL, "type" VARCHAR(255) NOT NULL, "user" VARCHAR(64) NOT NULL, "affecteduser" VARCHAR(64) NOT NULL, "app" VARCHAR(255) NOT NULL, "subject" VARCHAR(255) NOT NULL, "subjectparams" VARCHAR(255) NOT NULL, "message" VARCHAR(255) DEFAULT NULL, "messageparams" VARCHAR(255) DEFAULT NULL, "file" VARCHAR(255) DEFAULT NULL, "link" VARCHAR(255) DEFAULT NULL, PRIMARY KEY("activity_id"))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_activity" already exists
```

**Comment by nickvergessen** [comment] 2015-05-11 06:51
Duplicate of #11047

**Closed by nickvergessen** 2015-05-11 06:51 UTC
Labels: bug
