### ISSUE TITLE
OCP\Files\NotFoundException when copying skeleton on install

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22603] opened 2016-02-23 16:15 UTC
https://ci.owncloud.org/job/core-ci-linux-swift-primary-storage/database=mysql,label=SLAVE/52386/console

The exception happens on `occ maintenance:install`:
```
16:53:42 Installing ....
16:53:43 ownCloud is not installed - only a limited number of commands are available
16:53:47 
16:53:47                                  
16:53:47   [OCP\Files\NotFoundException]  
16:53:47                                  
16:53:47 
16:53:47 Exception trace:
16:53:47  () at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/files/node/node.php:84
16:53:47  OC\Files\Node\Node->getFileInfo() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/files/node/node.php:221
16:53:47  OC\Files\Node\Node->getPermissions() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/files/node/node.php:104
16:53:47  OC\Files\Node\Node->checkPermissions() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/files/node/file.php:89
16:53:47  OC\Files\Node\File->fopen() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/util.php:336
16:53:47  OC_Util::copyr() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/util.php:314
16:53:47  OC_Util::copySkeleton() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/files/node/root.php:347
16:53:47  OC\Files\Node\Root->getUserFolder() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/server.php:738
16:53:47  OC\Server->getUserFolder() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/user.php:171
16:53:47  OC_User::login() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/setup.php:367
16:53:47  OC\Setup->install() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/core/command/maintenance/install.php:84
16:53:47  OC\Core\Command\Maintenance\Install->execute() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/3rdparty/symfony/console/Command/Command.php:259
16:53:47  Symfony\Component\Console\Command\Command->run() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/3rdparty/symfony/console/Application.php:840
16:53:47  Symfony\Component\Console\Application->doRunCommand() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/3rdparty/symfony/console/Application.php:192
16:53:47  Symfony\Component\Console\Application->doRun() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/3rdparty/symfony/console/Application.php:123
16:53:47  Symfony\Component\Console\Application->run() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/lib/private/console/application.php:143
16:53:47  OC\Console\Application->run() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/console.php:86
16:53:47  require_once() at /ssd/jenkins/workspace/core-ci-linux-swift-primary-storage/database/mysql/label/SLAVE/occ:11
```

@icewind1991

**Comment by DeepDiver1975** [comment] 2016-02-24 13:54
@cmonteroluque I'd like to get this sorted out for 9.0 - kind of spooky to see no unit tests passing for objectstore

**Comment by DeepDiver1975** [comment] 2016-02-24 13:56
@butonic @Xenopathic any idea on this? THX

**Comment by PVince81** [comment] 2016-02-25 09:24
Looks like a temporary glitch ? The subsequent builds went through: https://ci.owncloud.org/job/core-ci-linux-swift-primary-storage/database=mysql,label=SLAVE/52441/console

**Comment by PVince81** [comment] 2016-02-25 09:26
Likely related to the swift docker not always starting ? https://github.com/owncloud/core/issues/22588

Because if it doesn't start, there is no home/data folder available.

**Comment by nickvergessen** [comment] 2016-02-25 09:47
Well it happens as a glitch yes, but it also happens in 20% of the cases as a glitch.
So instead of ignoring I created an issue to make sure that is not a problem on our end.
And maybe when a file that does not exist is trying to be copied as a skeleton, the exception should be caught?

**Comment by cmonteroluque** [comment] 2016-02-26 20:47
True. We need to have a "fail gracefully" approach to the code. @PVince81 let's talk on Monday, if we can get it before 9.0 that's great. I'd hate to not have it in 
(https://github.com/owncloud/core/issues/22603#issuecomment-18826481) but it's also going to be hard to stop the release because of it

**Comment by PVince81** [comment] 2016-02-29 16:58
If the home storage / object store is not available, then ownCloud cannot work properly. The only thing that could be done here would be to throw a proper exception that tells what's wrong, maybe an exception that results in 503 service not available.

I suppose this could also happen in a running system if the SWIFT object store connection is lost or the server is unreachable.

**Comment by nickvergessen** [comment] 2016-03-01 09:15
Well the skeleton files are in the owncloud source tree and can not be copied from there.
Also we have a check if the folder exists and that works :exclamation: 
https://github.com/owncloud/core/blob/7abb8693a16f96c3bcb252afce39fbd29ec0ed57/lib/private/util.php#L328-L329
```php
		$dir = opendir($source);
		while (false !== ($file = readdir($dir))) {
```
So I'm not really sure what happens with our CI there.

But no, this is not a real world scenario

**Comment by PVince81** [comment] 2016-03-01 09:19
Analysis seems to show that it's an env issue with the SWIFT docker, not a bug in ownCloud.

Closing in favor of https://github.com/owncloud/core/issues/22588

**Closed by PVince81** 2016-03-01 09:19 UTC
Labels: comp:filesystem, in progress, sev2-high
