### ISSUE TITLE
"File not found" when try to download a file

### ISSUE THREAD

**Issue by kgulti** [owncloud/core#24618] opened 2016-05-13 10:00 UTC
### Steps to reproduce
1. Create a folder with one file in it
2. Mark the file first
3. Click on download

### Expected behaviour
Download file.

### Actual behaviour
If there is a folder with only one file in it the direct download works fine. But if I mark the file first and then click on download I get an error message with file not found in directory. 

if there are more files in that folder I can mark the file and download it. 

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** NGINX

**ownCloud version:** 9.0.2

Updated from an older ownCloud 9.0.1

Where did you install ownCloud from: Directly from ownCloud

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

Activity  2.2.1
Collaborative tags  0.2
Comments  0.2
Deleted files  0.8.0
Federation  0.0.4
First Run Wizard  1.1
Gallery  14.5.0
LDAP user and group backend  0.8.0
Notifications  0.2.3
PDF Viewer  0.8.1
Provisioning API  0.4.1
Share Files  0.9.1
Text Editor  2.1
Update notification  0.1.0
Versions  1.2.0
Video player  0.9.8

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocvwnf5btm39',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'drive',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '',
  'ldapIgnoreNamingRules' => false,
  'logtimezone' => 'Europe/Berlin',
  'mail_smtpport' => '25',
  'theme' => '',
  'knowledgebaseenabled' => false,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updater.secret' => '',
  'mail_smtphost' => '',
);

Are you using external storage, if yes which one: no

Are you using encryption: no

Are you using an external user-backend, if yes which on: LDAP and local
Problem exists on boths accounts.

**Comment by PVince81** [comment] 2016-05-13 13:06
Duplicate of https://github.com/owncloud/core/issues/24272

**Closed by PVince81** 2016-05-13 13:06 UTC
