### ISSUE TITLE
Can't delete the ldap config with an empty id

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15104] opened 2015-03-23 10:40 UTC
### Steps to reproduce

1. Install owncloud
2. configure ldap 
3. create an empty config - this returns an empty configid
4. delete the empty config

### Expected behaviour

The config should be deleted

### Actual behaviour

The delete config command fails:

```
root@ubuntu-14-lts:/var/www/html/owncloud#  sudo -su www-data ./occ ldap:create-empty-config
Created new configuration with configID ''
root@ubuntu-14-lts:/var/www/html/owncloud# sudo -su www-data ./occ ldap:delete-config ''



  [RuntimeException]
  Not enough arguments.



ldap:delete-config configID



```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
MySQL DB

ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-03-19T03:27:00+00:00 fe8002a7db0ccfec3a96def4f889c265b52ace53

**Comment by DeepDiver1975** [comment] 2015-03-23 10:47
@blizzz

**Comment by blizzz** [comment] 2015-03-23 11:21
seems to be an regression with symfony updates in master, as it works with stable8. Need to confirm it yet.

**Comment by blizzz** [comment] 2015-03-23 12:47
Um… now I can only partly reproduce it. Still fails (and I know why) but with a different message.

**Comment by blizzz** [comment] 2015-03-23 13:13
The main issue remains. You pass an empty string and symfony will turn it to NULL :-/

**Comment by blizzz** [comment] 2015-03-23 14:13
I am stuck and looking for an explanation for the different output:

![occ](https://cloud.githubusercontent.com/assets/2184312/6781532/a27f742a-d16e-11e4-9445-ec34a5b87b2a.png)

here, the argument input array does not contain the empty string parameter. The $argv /$_SERVER variable is not modified.

![script](https://cloud.githubusercontent.com/assets/2184312/6781551/ca12c0aa-d16e-11e4-9154-785314daa659.png)

here, the argument input array does contain the empty string parameter.

Both is running on cli, i.e. PHP config is the same.

**Comment by blizzz** [comment] 2015-03-23 14:22
At, least I fixed few warnings, but that does not solve this issue: https://github.com/owncloud/core/pull/15120

**Comment by PVince81** [comment] 2015-11-03 17:18
@blizzz how about simply preventing to create a config with an empty id in the first place ?

**Comment by blizzz** [comment] 2015-11-03 21:42
Have this in mind, requires migration of the prefix-less config, but that's not a problem.

**Comment by PVince81** [comment] 2015-11-05 16:05
Discussed with @blizzz and while it's a regression, it's only a minor annoyance, so not critical.
There is no proper quickfix for it, so suggest to move to 9.0 instead for a more extensive and adequate fix. @cmonteroluque 

As a workaround, the admin can still delete it in the GUI or directly in the database.

**Comment by Schroeffu** [comment] 2016-01-13 19:50
Workarround: php occ ldap:delete-config ""

It does delete the "empty" ID successfully, at least in my case.

**Comment by PVince81** [comment] 2016-06-23 08:41
Ok, so apparently it works now. Closing.

**Closed by PVince81** 2016-06-23 08:41 UTC
Labels: app:user_ldap, bug, regression, sev3-medium
