### ISSUE TITLE
update error 10.4.1 -> 10.5

### ISSUE THREAD

**Issue by DrFAlbrecht** [owncloud/core#37778] opened 2020-08-05 12:50 UTC
### Steps to reproduce
1. opensuse 15.1 owncloud 10.4.1
2. manual update to oc 10.5
3. occ upgrade

### Expected behaviour
update to 10.5
### Actual behaviour
2020-08-05T11:54:35+00:00 Updating <dav> ...
2020-08-05T11:54:36+00:00 Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_dav_properties ADD propertytype SMALLINT DEFAULT 1 NOT NULL':

SQLSTATE[HY000]: General error: 1005 Can't create table `owncloudDB`.`#sql-5c4_18` (errno: 13 "Permission denied")
2020-08-05T11:54:36+00:00 Update failed

### Server configuration
**Operating system**:
opensuse leap 15.1

**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
7.2.5
**ownCloud version:** (see ownCloud admin page)
10.5
**Updated from an older ownCloud 10.4.1*

**Where did you install ownCloud from:**
https://owncloud.org/download/
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

Sicherheits- & Einrichtungswarnungen

Alle Überprüfungen bestanden.

```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
space Support": "active",
            "libxml2 Version": "2.9.7"
        },
        "xmlreader": {
            "XMLReader": "enabled"
        },
        "xmlwriter": {
            "XMLWriter": "enabled"
        },
        "zip": {
            "Zip": "enabled",
            "Zip version": "1.15.2",
            "Libzip headers version": "1.5.1",
            "Libzip library version": "1.5.1"
        },
        "zlib": {
            "Stream Wrapper": "compress.zlib:\/\/",
            "Stream Filter": "zlib.inflate, zlib.deflate",
            "Compiled Version": "1.2.11",
            "Linked Version": "1.2.11",
            "zlib.output_compression": "Off",
            "zlib.output_compression_level": "-1",
            "zlib.output_handler": "no value"
        },
        "Environment": {
            "APACHE_SERVER_FLAGS": "SSL ssl",
            "APACHE_CONF_INCLUDE_FILES": "no value",
            "HTTPD_MODULE_PATHS": " \/usr\/lib64\/apache2-prefork\/mod_authz_host.so \/usr\/lib64\/apache2-prefork\/mod_actions.so \/usr\/lib64\/apache2-prefork\/mod_alias.so \/usr\/lib64\/apache2-prefork\/mod_authz_groupfile.so \/usr\/lib64\/apache2-prefork\/mod_auth_basic.so \/usr\/lib64\/apache2-prefork\/mod_authn_file.so \/usr\/lib64\/apache2-prefork\/mod_authz_user.so \/usr\/lib64\/apache2-prefork\/mod_autoindex.so \/usr\/lib64\/apache2-prefork\/mod_cgi.so \/usr\/lib64\/apache2-prefork\/mod_dir.so \/usr\/lib64\/apache2-prefork\/mod_env.so \/usr\/lib64\/apache2-prefork\/mod_expires.so \/usr\/lib64\/apache2-prefork\/mod_include.so \/usr\/lib64\/apache2-prefork\/mod_log_config.so \/usr\/lib64\/apache2-prefork\/mod_mime.so \/usr\/lib64\/apache2-prefork\/mod_negotiation.so \/usr\/lib64\/apache2-prefork\/mod_setenvif.so \/usr\/lib64\/apache2-prefork\/mod_status.so \/usr\/lib64\/apache2-prefork\/mod_userdir.so \/usr\/lib64\/apache2-prefork\/mod_asis.so \/usr\/lib64\/apache2-prefork\/mod_imagemap.so \/usr\/lib64\/apache2-prefork\/mod_info.so \/usr\/lib64\/apache2-prefork\/mod_ssl.so \/usr\/lib64\/apache2-prefork\/mod_authz_core.so \/usr\/lib64\/apache2-prefork\/mod_socache_shmcb.so \/usr\/lib64\/apache2-prefork\/mod_reqtimeout.so \/usr\/lib64\/apache2-prefork\/mod_authn_core.so \/usr\/lib64\/apache2-prefork\/mod_version.so \/usr\/lib64\/apache2-prefork\/mod_headers.so \/usr\/lib64\/apache2\/mod_php7.so",
            "INVOCATION_ID": "d13706d857c14c28baf8484e430a5f76",
            "HTTPD_MODULE_IDS": " authz_host_module actions_module alias_module authz_groupfile_module auth_basic_module authn_file_module authz_user_module autoindex_module cgi_module dir_module env_module expires_module include_module log_config_module mime_module negotiation_module setenvif_module status_module userdir_module asis_module imagemap_module info_module ssl_module authz_core_module socache_shmcb_module reqtimeout_module authn_core_module version_module headers_module php7_module",
            "HTTPD_MPM": "prefork",
            "APACHE_SERVERADMIN": "no value",
            "NOTIFY_SOCKET": "\/run\/systemd\/notify",
            "APACHE_ACCESS_LOG": "\/var\/log\/apache2\/access_log combined",
            "APACHE_USE_CANONICAL_NAME": "off",
            "SYSCONFIG_FILE": "\/etc\/sysconfig\/apache2",
            "APACHE_SERVERTOKENS": "OS",
            "APACHE_LOGLEVEL": "warn",
            "APACHE_SERVERNAME": "no value",
            "PWD": "\/",
            "LC_CTYPE": "de_DE.UTF-8",
            "JOURNAL_STREAM": "9:49222",
            "APACHE_HTTPD_CONF": "no value",
            "APACHE_EXTENDED_STATUS": "off",
            "APACHE_SERVERSIGNATURE": "on",
            "APACHE_MPM": "no value",
            "APACHE_CONF_INCLUDE_DIRS": "no value",
            "APACHE_START_TIMEOUT": "2",
            "SHLVL": "0",
            "APACHE_MODULES": "authz_host actions alias authz_groupfile auth_basic authn_file authz_user autoindex cgi dir env expires include log_config mime negotiation setenvif status userdir asis imagemap info ssl authz_core socache_shmcb reqtimeout authn_core version headers php7",
            "sysconfig_loaded": "true",
            "mpm_found": "true"
        }
    }
}
**List of activated apps:**
Enabled:
  - audioplayer: 2.8.4
  - calendar: 1.6.4
  - comments: 0.3.0
  - configreport: 0.2.0
  - contacts: 1.5.5
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.2
  - files_sharing: 0.12.0
  - files_textviewer: 1.0.3
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
firefox
**Operating system:**
opensuse 15.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment] 2020-08-05 13:18
> Can't create table owncloudDB.#sql-5c4_18 (errno: 13 "Permission denied")

Problem by database not allowing permissions? Not bug in ownCloud but configuration problem by database?

**Comment by VicDeo** [comment] 2021-02-12 08:48
@DrFAlbrecht did you check if the issue is related to the lack of the free space as suggested by @ho4ho above?

**Comment by VicDeo** [comment] 2021-05-19 10:25
I'm closing this issue as it is rather MySQL-related and caused by the lack of permissions or free space.
Feel free to reopen once you are ready to provide more details for investigation.

**Closed by VicDeo** 2021-05-19 10:25 UTC
Labels: Type:Bug
