### ISSUE TITLE
Doubled folders when receiving shares through two groups

### ISSUE THREAD

**Issue by jonasheinisch** [owncloud/core#24575] opened 2016-05-11 13:23 UTC
### Steps to reproduce
1. Create two usergroups G1 and G2
2. Share a folder F with both groups
3. Create a user U belonging to both groups G1 and G2
4. Log in with U

### Expected behaviour
User U will have folder F in his files.

### Actual behaviour
User U has folder F two times in his files (one is named "F (2)").

### Server configuration
**Operating system**: Debian 8.0

**Web server:** Apache 2.0

**Database:** MySQL

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** via official aptitude repo

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:**
```

  - activity: 2.2.1
  - activitydefaults: 0.1.0
  - comments: 0.2
  - dav: 0.1.6
  - direct_menu: 0.7.1
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - ownbackup: 0.3.8
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'qwerty',
  'passwordsalt' => '0815',
  'secret' => 'thisissecret',
  'trusted_domains' =>
  array (
    0 => 'www.xxx.de',
    1 => 'xxx.de',
  ),
  'datadirectory' => '/var/www/vhosts/xxx.de/httpdocs/data',
  'overwrite.cli.url' => 'https://www.xxx.de',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'dbpass',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxx.de',
  'theme' => 'mytheme',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by PVince81** [comment] 2016-05-11 13:31
Are you using different permissions ? If the permissions are the same, there is an algo that will merge the two folders.

**Comment by PVince81** [comment] 2016-05-11 13:31
@rullzer

**Comment by jonasheinisch** [comment] 2016-05-11 13:35
@PVince81 Yes, the permissions are identical.

**Comment by PVince81** [comment] 2016-05-11 13:40
Hmm, then it could be a regression

**Comment by rullzer** [comment] 2016-05-11 13:42
I most likely broke it then.
Thinking now why and if I had a reason.

**Comment by PVince81** [comment] 2016-06-01 15:17
@rullzer any update ?

**Comment by PVince81** [comment] 2016-06-14 15:55
> I most likely broke it then.

@rullzer can you fix it then ?

**Comment by rullzer** [comment] 2016-06-15 07:54
PR incomming... but I actually don't know why this grouping isn't happening properly on 9.0 since I did not touch the mountpoint stuff then...

**Comment by PVince81** [comment] 2016-07-06 10:50
The PR in question is here https://github.com/owncloud/core/pull/25113

**Comment by vssware** [comment] 2016-07-11 02:16
The problem happened when I upgrade from 9.0.2 to 9.0.3,It does not exist in my 9.0.2.

**Comment by jochenwezel** [comment] 2016-07-11 11:02
what can / should I do in the meantime safely until the patch is availble with build 9.0.4?

1. delete these duplicated folders and just keep the very first, correct one in my list?
2. keep everything untouched

PLEA: In both cases, the provided update should correct all wrong data (so that the many users of our instance don't have to waste additional time to get a cleanup of their directory/share structure)

**Comment by PVince81** [comment] 2016-07-11 11:32
@jochenwezel I just tested the PR and you're right that this needs a repair step, the duplicate folders aren't automatically deleted :disappointed: 

This is likely because it creates an additional entry in the "oc_share" table as if the user had removed it.

Had a local test with the doubled folder, if I "unshare from self" one of the duplicate folders it will exclude it from view and the non-duplicate one remains. It looks fine as a workaround but so far I can't tell whether this will have side effects.

One visible side effect so far is that when opening the share panel for the remaining entry, it will only show that it was shared through one group instead of multiple.

**Comment by PVince81** [comment] 2016-07-12 09:05
@felixboehm @cdamken @pako81 FYI

**Comment by PVince81** [comment] 2016-07-19 16:06
Let's keep it open until the backports are merged:
- [ ] stable9.1: https://github.com/owncloud/core/issues/25534
- [ ] stable9: TODO

**Comment by PVince81** [comment] 2016-07-21 17:06
- [ ] check whether the fix also fixes https://github.com/owncloud/core/issues/25555

**Comment by PVince81** [comment] 2016-07-22 05:45
- [ ] add more integration tests about renaming/moving received grouped shared folders

**Comment by PVince81** [comment] 2016-07-22 07:18
- [ ] TODO: fix repair routine to also cover https://github.com/owncloud/core/issues/25555 properly

**Comment by PVince81** [comment] 2016-07-22 08:53
Just to clarify, now using this ticket to track any kind of "folder shared through multiple ways to the same user" resulting in the "recipient sees the folders multiple times" issue.

**Comment by PVince81** [comment] 2016-07-22 09:46
- [ ] another case that needs to be covered: https://github.com/owncloud/core/pull/25568

**Comment by SMITR1** [comment] 2016-07-25 20:20
Hi I ran into another issue, I applied the temporary fix for the sharing issue but now my owncloud doesn't want to sync with my mobile devices(Webdav or mobile app). Gives a HTTP error... can you please advise?

**Comment by PVince81** [comment] 2016-08-08 07:40
@SMITR1 which ownCloud version do you have and which exact fix did you apply ? Depending on your ownCloud version, the fix is different. It is likely that you applied an incomplete fix.

**Comment by PVince81** [comment] 2016-08-12 10:12
The PR is ready for testing: https://github.com/owncloud/core/pull/25543

Please help testing if you have a test system. (don't do it on a productive system as it increases the version)
The PR can be downloaded as patch: https://github.com/owncloud/core/pull/25543.patch

To test:
- the repair routine must properly repair the duplicate shares using a "best guess" approach in case users decided to keep the duplicates
- all newly created shares targetting the same user must be properly deduplicated.

**Comment by PVince81** [comment] 2016-08-12 10:16
Regarding the workaround while waiting for 9.0.5: you can safely delete the duplicates. The repair routine will still be able to figure out what to do.

**Comment by PVince81** [comment] 2016-08-16 11:49
Fix will be in 9.0.5 and 9.1.1.

**Closed by PVince81** 2016-08-16 11:49 UTC
Labels: bug, feature:sharing, regression, sev1-critical

**Comment by vssware** [comment] 2016-08-16 13:13
Great, Tks a lot!

On Aug 16, 2016, at 7:50 PM, Vincent Petry <notifications@github.com <mailto:notifications@github.com>> wrote:

Closed #24575 <https://github.com/owncloud/core/issues/24575>.

**Comment by PVince81** [comment] 2016-08-18 12:57
You can help testing with the 9.0.5 RC1: http://download.owncloud.org/community/owncloud-9.0.5RC1.tar.bz2

**Comment by tavinus** [comment] 2017-01-17 22:25
Sorry to reopen this, but I am still facing this problem on OC 9.1.2 (stable). Any ideas?

**Comment by PVince81** [comment] 2017-01-18 09:43
@tavinus please make a new ticket and post reproduction steps and details about the sharing scenario. Use the issue template for that: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by craftyInstigator** [comment] 2017-02-22 20:09
I can still reproduce this problem in 9.1.4.2. This issue needs to be reopened.

**Comment by PVince81** [comment] 2017-02-23 09:39
@craftyInstigator please make a new ticket and post reproduction steps and details about the sharing scenario. Use the issue template for that: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md.

Most important is to know what exact sharing scenario you are using and the order in which the shares were created as it might affect the outcome. There is one known issue: https://github.com/owncloud/core/issues/25564, please check if it matches your scenario exactly.
