### ISSUE TITLE
[10.0.0.12] Uncaught InvalidArgumentException: Identifier "command.dbUpgrade" is not defined

### ISSUE THREAD

**Issue by guruz** [owncloud/core#28494] opened 2017-07-26 13:08 UTC
```
[Wed Jul 26 11:37:36.712792 2017] [php7:error] [pid 28607] [client 192.168.0.1:56754] PHP Fatal error:  Uncaught InvalidArgumentException: Identifier "command.dbUpgrade" is not defined. in /usr/share/webapps/owncloud/updater/vendor/pimple/pimple/src/Pimple/Container.php:96\nStack trace:\n
#0 /usr/share/webapps/owncloud/updater/app/config/container.php(152): Pimple\\Container->offsetGet('command.dbUpgra...')\n
#1 /usr/share/webapps/owncloud/updater/vendor/pimple/pimple/src/Pimple/Container.php(113): {closure}(Object(Pimple\\Container))\n
#2 /usr/share/webapps/owncloud/updater/app/config/container.php(171): Pimple\\Container->offsetGet('commands')\n
#3 /usr/share/webapps/owncloud/updater/vendor/pimple/pimple/src/Pimple/Container.php(113): {closure}(Object(Pimple\\Container))\n
#4 /usr/share/webapps/owncloud/updater/src/Controller/IndexController.php(97): Pimple\\Container->offsetGet('application')\n
#5 /usr/share/webapps/owncloud/updater/index.php(29): Owncloud\\Updater\\Controller\\IndexController->dispatch()\n#6 {main}\n  thrown in /usr/share/webapps/owncloud/updater/vendor/pimple/pimple/src/Pimple/Container.php on line 96

```

Not sure if fixed with newer versions.

It leads to a Internal Server Error in Chrome inspector, but the web UI does not change at all. **It should at least display some error dialog in the web UI?** (no matter if fixed already or not)

**Comment by PVince81** [comment] 2017-07-26 13:23
@VicDeo please have a look and confirm

**Comment by guruz** [comment] 2017-07-26 13:50
I guess this is https://github.com/owncloud/updater/commit/bf5f7e95eb1c3226332b7aa49617ec003ef87c2f ?

**Comment by guruz** [comment] 2017-07-26 13:51
(but still it should show some ajax error and not eat it?)

**Comment by VicDeo** [comment] 2017-07-26 15:36
@guruz know issue with 10.0 
please apply a patch https://central.owncloud.org/t/patches-for-known-update-issues-from-versions-10-0-0-10-0-2-updated-on-june-13/7911

**Comment by VicDeo** [comment] 2017-07-27 18:43
Closing as a duplicate of https://github.com/owncloud/updater/issues/429

**Closed by VicDeo** 2017-07-27 18:43 UTC
Labels: feature:update
