### ISSUE TITLE
webdav: Could not rename part file to final file

### ISSUE THREAD

**Issue by raiffeisennet** [owncloud/core#13926] opened 2015-02-05 15:53 UTC
# Expected behaviour
Uploading a file without "update" permission works.
# Actual behaviour
When i upload a file via webdav in a shared folder without the "update" permission i receive this error:
Feb  5 16:41:35 vcloud-be2 ownCloud[28337]: {webdav} \OC\Files\Filesystem::rename() failed
Feb  5 16:41:35 vcloud-be2 ownCloud[28337]: {webdav} Sabre\DAV\Exception: Could not rename part file to final file
When i do it via the web frontend it works.
# Server Configuration
php -v PHP 5.4.36-0+deb7u3 (cli) (built: Jan  9 2015 08:07:06) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
mysql 5.1
OC Server 7.0.4
# Steps to reproduce:
1) Create group A
2) Create folder "test"
3) Give group A write permissions without update and delete on folder "test"
4) Upload a file into "test" with webdav

**Comment by PVince81** [comment] 2015-02-05 18:32
Duplicate of https://github.com/owncloud/core/issues/13193

**Closed by PVince81** 2015-02-05 18:32 UTC
Labels: bug
