### ISSUE TITLE
Internal server error while syncing up

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#10578] opened 2014-08-21 14:32 UTC
on stable7 (c4fd3dbd2aeda1bbf849956903e705bb32c8c625) I tried to upload a tree of 1000 small files, each only a couple of kB, using sync client 1.7.0 beta1.

Most of the files went ok, but to one of them, the server returned a *500 internal server error*, see access_log:
```
::1 - kf [20/Aug/2014:19:17:39 +0200] "PUT /oc7/remote.php/webdav/bosses%20stuff/tiles/16/4350/2791.png HTTP/1.1" 201 - "-" "Mozilla/5.0 (Linux) mirall/1.7.0"
::1 - kf [20/Aug/2014:19:17:40 +0200] "PUT /oc7/remote.php/webdav/bosses%20stuff/tiles/16/4351/2788.png HTTP/1.1" 500 - "-" "Mozilla/5.0 (Linux) mirall/1.7.0"
::1 - kf [20/Aug/2014:19:17:40 +0200] "PUT /oc7/remote.php/webdav/bosses%20stuff/tiles/16/4351/2789.png HTTP/1.1" 201 - "-" "Mozilla/5.0 (Linux) mirall/1.7.0"
```
Corresponding is this in the owncloud.log:
```
{"app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-40cbb98ec6b71fade22f0f8ad86de04c' for key 'fs_storage_path_hash'","level":4,"time":"2014-08-20T17:17:40+00:00"}
{"app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/home\/kf\/oC\/stable7\/core\/lib\/private\/session\/memory.php#80","level":3,"time":"2014-08-20T17:17:40+00:00"}
```
What's happening?

**Comment by dragotin** [comment] 2015-03-05 19:58
maybe same problem: #14701

**Comment by PVince81** [comment] 2015-03-26 23:32
Should hopefully be fixed by several PRs with the keyword "insertIfNotExists" (so, duplicate of https://github.com/owncloud/core/issues/14701)

**Closed by PVince81** 2015-03-26 23:32 UTC
Labels: bug, needs info, sev3-medium
