### ISSUE TITLE
Restored shared files don't vanish from all trashbins

### ISSUE THREAD

**Issue by patrick1990** [owncloud/core#16652] opened 2015-06-01 09:53 UTC
I'm playing around with the trashbin feature of Owncloud at the moment and have noticed a strange behavior when I try to delete and restore a file in a shared folder between two users.

### Steps to reproduce
1. Create a folder as user A.
2. Share it with user B of your Owncloud.
3. Delete the file as user B. Owncloud moves the file to the trashbin of user A and B as described [here](https://doc.owncloud.org/server/7.0/user_manual/files/deletedfiles.html#what-happens-when-shared-files-are-deleted).
4. Restore the file as user A.

### Expected result
Owncloud removes the file from the trashbins of user A and user B after restoring the file.

### Actual result
Owncloud removes the file from the trashbin of user A but it still remains in the trashbin of user B. From there you can restore it again, what overwrites the restored file again (see also #16246).

### Versions
Owncloud: 8.0.3 (stable)

**Comment by PVince81** [comment] 2015-06-01 11:41
I think this is by design.

Also at the time the file is restore, ownCloud has no information about who has the same file in their trashbin. It cannot rely solely on the file name, as the user could have deleted another file with the same name.

Tagging as enhancement for further discussion.

**Comment by PVince81** [comment] 2016-03-01 22:25
@nickvergessen @schiesbn as discussed last week.

**Comment by PVince81** [comment] 2016-10-10 08:57
Related to the fact that the trashbins are different for every user.
Closing in favor of https://github.com/owncloud/core/issues/24053 which contains an explanation/discussion of what would need to change to make this possible

**Closed by PVince81** 2016-10-10 08:57 UTC
Labels: app:files_trashbin, enhancement, feature:sharing
