### ISSUE TITLE
S2S sharing: edit made by sharee user is not saved

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13487] opened 2015-01-19 21:05 UTC
### Steps to reproduce

1. Install master on two separate boxes (I installed on ubuntu and centos)
2. upload a file to the centos box and share with a user on the ubuntu box
3. edit the file on centos and verify the change locally
4. verify that the change is seen on ubuntu
5. edit the file on ubuntu and verify the change locally

### Expected behaviour

The edit made in step 5 would be saved 

### Actual behaviour

The edit is not saved

### Server configuration

ownCloud 8.0 beta 1 (daily) Build:2015-01-19T04:12:55+00:00

**Comment by karlitschek** [comment] 2015-01-19 21:09
@schiesbn

**Comment by jnfrmarks** [comment] 2015-01-19 21:27
A bit more info:

The version of the file on the shared system shows the edit being made.

**Comment by nickvergessen** [comment] 2015-01-26 14:18
Sounds like a duplicate of #13617 and #11722 
Right @jnfrmarks

**Comment by karlitschek** [comment] 2015-03-26 13:23
closing as duplicate

**Closed by karlitschek** 2015-03-26 13:23 UTC
Labels: bug, feature:federated-cloud-sharing
