### ISSUE TITLE
Share links have error that the Address in mailbox given does not comply with RFC 2822, 3.6.2

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20504] opened 2015-11-13 21:57 UTC
### Steps to reproduce
1. Set the Sharing to allow users to send email notifications for shared files
2. Share a files with two users via the dialog using valid emails
3. An error pops up and there is an error in the oc log

### Expected behaviour
Multiple emails should be entered in the dialog, and they should be sent just like previous versions of ownCloud.

### Actual behaviour
When attempting to share a file with multiple individuals via emails using the share dialog box an error pops up "Couldn't send mail to following users:"
The owncloud log has an error that the emails do not comply with does not comply with RFC 2822, 3.6.2.

### Server configuration
**Operating system**: CentOs 7

**Web server:** apache

**Database:** mariadb

**PHP version:** 5.4

**ownCloud version:** 8.1.3 and 8.1.4

**Updated from an older ownCloud or fresh install:** New Install

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VkZWeB4qaIEEQ3x9x2OPegAAAAQ","remoteAddr":"172.12.12.12","app":"sharing","message":"Can't send mail with public link to joe@fallout4.com biff@fallout4.com: Address in mailbox given [joe@fallout4.com biff@fallout4.com] does not comply with RFC 2822, 3.6.2.","level":3,"time":"2015-11-13T21:30:33+00:00"}
```
The dialog
![20151113_share_dialog](https://cloud.githubusercontent.com/assets/4803385/11158595/50a5ec2a-8a27-11e5-9db8-61dfe172f881.PNG)

Error pop up

![20151113_share_emails](https://cloud.githubusercontent.com/assets/4803385/11158560/126b7cfe-8a27-11e5-8045-76d8e6bb0ec2.PNG)

@MorrisJobke @tariqsiddiqui

**Comment by rullzer** [comment] 2015-11-14 08:38
I think this is a duplicate of https://github.com/owncloud/core/issues/19848

**Comment by MorrisJobke** [comment] 2015-11-16 08:56
> I think this is a duplicate of #19848

Correct.

**Comment by MorrisJobke** [comment] 2015-11-16 08:57
Moving this over -> close

**Closed by MorrisJobke** 2015-11-16 08:57 UTC
Labels: blue-ticket
