### ISSUE TITLE
Cannot upload a file to a SMB storage with encryption enabled

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16356] opened 2015-05-14 13:32 UTC
### Steps to reproduce
1. Install and enable external storage and encryption
2. Create a new SMB mount in the external storage, with a correct configuration available for all users
3. Upload a file inside the SMB mount (bigger than 1MB)

### Expected behaviour
The file is uploaded correctly in the external storage

### Actual behaviour
Only a part of the file is uploaded. It's being cut at 16kB. Smaller files can be uploaded correctly.

![screenshot from 2015-05-14 15 27 12](https://cloud.githubusercontent.com/assets/1477829/7632469/cf134d74-fa4d-11e4-8bc3-f5f467c66e00.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 - encryption: 1.0.0
 - files: 1.1.9
 - files_external: 0.2.3
 - files_locking: 
 - files_sharing: 0.6.1
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5

#### ownCloud log (data/owncloud.log)
```
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u16\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u17\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u18\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u19\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u2\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u20\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u3\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u4\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u5\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u6\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u7\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u8\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}
{"reqId":"dloJ1jRrYoP1sJmvECYh","remoteAddr":"10.40.30.21","app":"encryption","message":"no public key found for user \"u9\", user will not be able to read the file","level":2,"time":"2015-05-14T13:13:49+00:00"}

{"reqId":"JCsAkBwa3TtV3patra2+","remoteAddr":"10.40.30.21","app":"PHP","message":"imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: \b\n at \/home\/jvillafanez\/src\/owncloud\/owncloud2\/lib\/private\/image.php#512","level":3,"time":"2015-05-14T13:27:01+00:00"}

```

### Notes
I've also checked with the storage only available for the current user in order to prevent the "key not found" logs. Those logs doesn't appear, but the behaviour is the same

**Comment by LukasReschke** [comment] 2015-05-15 07:40
cc @schiesbn Encryption related

**Comment by jvillafanez** [comment] 2015-05-15 12:53
FTP external storage is also affected by this bug

**Comment by schiesbn** [comment] 2015-05-18 08:45
I can't reprduce it with current master (state: https://github.com/owncloud/core/commit/73a3086945b41afa39debd89481c021934dedb67 ). I tried it with a local Samba server (on a Debian system). Tested upload and download with a small text file and a ~6MB image. The storage was mounted by the admin for all users.

Can you try it again? Does it work for you without encryption? Are you sure that encryption is correctly set-up. Can you write/read files on the local storage at the same time it fails for the samba mount?

**Comment by jvillafanez** [comment] 2015-05-18 09:35
It still happening in https://github.com/owncloud/core/commit/73a3086945b41afa39debd89481c021934dedb67

I've checked with another mount, same storage configuration but without encryption, and it works fine: the file can be downloaded from both mounts (the one with encryption too)

Files can be uploaded and downloaded normally in the root folder and in any other tested storage except FTP. I've also checked that the files are encrypted in their respective backends.

**Comment by schiesbn** [comment] 2015-05-18 10:03
Hm, does the Samba server also runs on Ubuntu or do you use a real windows server as samba storage? Maybe different samba implementations behave differently?

Who else has a samba storage and could give it a try? Maybe @PVince81 or @nickvergessen ? Thanks!

**Comment by jvillafanez** [comment] 2015-05-18 10:32
Checked with samba Version 4.1.6-Ubuntu and also with windows 2008, with the same results

**Comment by PVince81** [comment] 2015-05-18 10:53
Happens to me as well on master (85f500f07037cab21757fffcae7a5cd78db43bd1) against a local Linux Samba server samba-4.2.1-1.1.x86_64 (running on openSUSE Factory x86_64)

**Comment by PVince81** [comment] 2015-05-18 10:56
Strangely, text files seem to be uploaded properly. A preview also appears.

But picture files fail.

**Comment by PVince81** [comment] 2015-05-18 11:01
I'll try and debug this...

**Comment by PVince81** [comment] 2015-05-18 11:02
SFTP upload works, so it's specific to SMB

**Comment by jvillafanez** [comment] 2015-05-18 11:08
FTP is also affected. The only storages that I haven't tested yet are s3 and openstack.

**Comment by PVince81** [comment] 2015-05-18 11:10
All uploaded files have the size 16384 as if it would abort after two blocks.

**Comment by PVince81** [comment] 2015-05-18 11:11
that might explain why the small text files were uploaded fine: they were less than 16k.

**Comment by PVince81** [comment] 2015-05-18 11:15
Something very weird is happening: normally we are reading from a temp file (the one to upload) and then write to a SMB stream wrapper. But here I see that readCache() is actually using the SMB wrapper to read the input file ?!

**Comment by PVince81** [comment] 2015-05-18 11:19
@schiesbn @th3fallen @jknockaert why are we calling stream_read on the target file in readCache() from stream_write ? Do we really need to re-decrypt every time ?

Or maybe it's a bug and readCache is not supposed to be called at all here.

**Comment by PVince81** [comment] 2015-05-18 11:20
Here is the stack:
```
0  OC\Files\Stream\Encryption->readCache() /srv/www/htdocs/owncloud/lib/private/files/stream/encryption.php:429
1  OC\Files\Stream\Encryption->stream_write() /srv/www/htdocs/owncloud/lib/private/files/stream/encryption.php:306
2  fwrite()        /srv/www/htdocs/owncloud/lib/private/helper.php:617
3  OC_Helper::streamCopy() /srv/www/htdocs/owncloud/lib/private/helper.php:617
4  OC\Files\View->file_put_contents() /srv/www/htdocs/owncloud/lib/private/files/view.php:538
5  OC\Files\View->fromTmpFile() /srv/www/htdocs/owncloud/lib/private/files/view.php:840
6  OC\Files\Filesystem::fromTmpFile() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:700
7  require_once()  /srv/www/htdocs/owncloud/apps/files/ajax/upload.php:191
8  __lambda_func() /srv/www/htdocs/owncloud/lib/private/route/route.php%28153%29%20:%20runtime-created%20function:1
9  call_user_func:{/srv/www/htdocs/owncloud/lib/private/route/router.php:272}() /srv/www/htdocs/owncloud/lib/private/route/router.php:272
10 OC\Route\Router->match() /srv/www/htdocs/owncloud/lib/private/route/router.php:272
11 OC::handleRequest() /srv/www/htdocs/owncloud/lib/base.php:862
12 {main}          /srv/www/htdocs/owncloud/index.php:40
```

In the case of SMB, the parent::stream_read operation will fail.

**Comment by PVince81** [comment] 2015-05-18 11:23
especially here we are only linearly writing/encrypting stuff at the end of the stream, so I don't see a reason to re-read the written stream and decrypt it.

SFTP goes through the same code path, but doesn't mind having stream_read being called on it. It just returns an empty string.

It seems to do the readCache() logic only in the 2nd iteration (not in subsequent ones).

**Comment by schiesbn** [comment] 2015-05-18 11:26
Hm, I still can't reproduce it. But I also see that we try to read the file while writing. The first time we skip the write operation because position and file size are '0' but then position and file size get out of sync.

But in my case position is always larger then the current unencrypted size so I always read a empty string which works without any failure.

**Comment by PVince81** [comment] 2015-05-18 11:29
Can we get rid of that bogus read operation ? Or is it needed for anything ?

**Comment by jknockaert** [comment] 2015-05-18 11:29
@PVince81 the logic of the encryption is to call readCache() upon every read/write. But in the scenario of a linear write, the tests at the beginning of readCache() https://github.com/owncloud/core/blob/master/lib/private/files/stream/encryption.php#L429 should avoid that anything happens in readCache().

**Comment by PVince81** [comment] 2015-05-18 11:31
Thanks, so the readCache is mostly for random access ? "w+" or "a+" modes ?

**Comment by jknockaert** [comment] 2015-05-18 11:32
Yes.

**Comment by schiesbn** [comment] 2015-05-18 11:40
@jknockaert this works for the first time we call readCache() when position and unencryptedSize are both '0'. But in the next iterations of stream_write() for larger files both values seems to get out of sync.

In the second round 'size' is 16384bytes, which is OK (header + first block, each are 8192bytes large) but we compare it with position which is after writing the first block only 6129.

Do you think you could have a look at it and try to get it in sync?

**Comment by jknockaert** [comment] 2015-05-18 11:41
Yes I will have a look at it.

**Comment by jknockaert** [comment] 2015-05-18 12:01
OK, I singled it out. I will file a PR. Could we pls first merge #15973 so it doesn't need rebase?

**Comment by jknockaert** [comment] 2015-05-18 12:18
Sorry I meant #15980 that I would like to be merged first.

**Comment by schiesbn** [comment] 2015-05-18 13:02
@jknockaert I just merged the other PR. Thanks for taking care of it, looking forward to your pull request.

**Comment by jknockaert** [comment] 2015-05-18 13:08
Check #16412.

**Comment by jknockaert** [comment] 2015-05-18 13:19
@PVince81 Could you test if it solves the Samba issue?

**Comment by PVince81** [comment] 2015-05-18 13:23
I will. Currently struggling with some other issue.

**Comment by schiesbn** [comment] 2015-05-18 13:54
@jvillafanez can you try the PR above by @jknockaert  if it solved the issue? Thanks!

**Comment by jknockaert** [comment] 2015-05-18 17:29
Reopening this issue as we first need confirmation that fix #16356 (which does fix an issue that may be unrelated) does fix the original issue reported here.

**Comment by PVince81** [comment] 2015-05-18 19:37
It did for me, but would be good if @jvillafanez could confirm

**Comment by jvillafanez** [comment] 2015-05-19 07:38
Uploads to SMB works now in master f0e7ae5da803b4fc77f362b70e86b27e9b77f001, but sharing (https://github.com/owncloud/core/issues/16358) stopped working. I'm not sure if it's because of the changes made here or other changes affecting SMB storage.

FTP storage still has this issue

**Comment by jknockaert** [comment] 2015-05-19 08:11
@jvillafanez Do I understand correctly from your earlier comment that the issue with FTP is different in the sense that FTP also doesn't work without encryption enabled?

**Comment by PVince81** [comment] 2015-05-19 08:24
@jvillafanez what FTP server are you using ?

**Comment by jvillafanez** [comment] 2015-05-19 08:30
I'm using vsftpd as server. Uploads work fine without encryption, but with encryption the symptoms are the same as described for this issue.

**Comment by jknockaert** [comment] 2015-05-20 08:51
@jvillafanez Can you try the fix in #16452?

**Comment by jvillafanez** [comment] 2015-05-22 10:15
I'm having issues after sharing a file:

1. Upload a file inside an FTP external storage
2. Share the file with another user
3. Login with the other user and edit the file

At that point the file downloaded for the user shows an HTML page. The original user has the file updated correctly and the file can be downloaded fine.

The upload seems to be working fine, but I've also had some issues downloading the same file; I don't have steps to reproduce though, sometimes worked fine, others downloads an HTML page.

**Comment by PVince81** [comment] 2015-05-22 10:17
@jvillafanez this is likely to be a separate issue related to sharing and sharing keys. Can you raise separately ?

If uploading to FTP as owner works, then we can close this ticket here.

**Comment by jvillafanez** [comment] 2015-05-22 10:21
@PVince81 you're right.

**Comment by PVince81** [comment] 2015-05-22 10:25
So you confirm that it works as owner ?

**Comment by jvillafanez** [comment] 2015-05-22 10:28
:+1:

**Comment by PVince81** [comment] 2015-05-22 14:00
@jvillafanez ok, I thought the PR was merged already but it wasn't. Reopening.

**Closed** 2015-05-26 10:02 UTC
Labels: 3 - To Review, app:encryption, app:files_external, approved by qa, bug, sev1-critical
