### ISSUE TITLE
Can't remove file

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#13176] opened 2015-01-08 14:40 UTC
### Expected behaviour
File removed locally removed on server

### Actual behaviour
File removed on client still present on server, moreover, I can't remove it with web interface and after some time it appears locally again (even after multiple deletion).

### Steps to reproduce
I'm using ownCloud for some months, and it happens from time to time. The only solution I found that actually deletes that file - to remove it from server filesystem.

During removing with web interface 2 requests are sent: one with `dir` and `files` parameters, other without any parameters, both die in 1 minute with 504 Gateway Time-out (CloudFlare reports that).

My network connection to ownCloud server is like `me > ... > CloudFlare > Docker host with Nginx > Docker container with Nginx (here is ownCloud)`

### Server configuration
**Operating system**: Ubuntu 14.04 with latest updates (Docker container)

**Web server:** Nginx 1.4.6

**Database:** MariaDB 10.0.15

**PHP version:** PHP-FPM 5.5.9

**ownCloud version:** 7.0.4

**Updated from an older ownCloud or fresh install:** most likely updated from 7.x (do not remember exactly)

**List of activated apps:**
> Activity
ATNotes
Calendar
Contacts
Deleted files
Documents
External storage support
First Run Wizard
Full Text Search
Mail Template Editor
ocSafe
ownCloud dependencies info
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer
Diagram Editor (3rd Party)
Files Counter (3rd Party)
Files move (3rd Party)
Music (3rd Party)
ocPassman (3rd Party)

**The content of config/config.php:**

```
  'instanceid' => '****',
  'passwordsalt' => '****',
  'trusted_domains' => 
  array (
    0 => '****',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '****',
  'dbuser' => '****',
  'dbpassword' => '****',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '****',
  'mail_domain' => '****',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => '****',
  'mail_smtpport' => '587',
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '****',
  'forcessl' => true,
  'loglevel' => '1',
  'blacklisted_files' => 
  array (
  ),
  'theme' => '',
  'maintenance' => false,
  'secret' => '****',
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** Forced HTTPS

### Client configuration
Client version: 1.7.1

Operating system: Ubuntu 15.04 x64 (I know, unstable, but was the same on 14.10 also before upgrade)

OS language: Ukrainian (uk_UA)

Installation path of client: as default in Ubuntu, from repository on download.opensuse.org

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
~$ owncloud --logwindow
SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket" 
==== added system ignore list to socketapi: "/etc/ownCloud/sync-exclude.lst" 
==== added user defined ignore list to csync: "/home/nazar-pc/.local/share/data/ownCloud/sync-exclude.lst" 
setting remote poll timer interval to 30000 msec 
Sys Info size:  108 
int main(int, char**) Already running, exiting... 
SocketApi:  dtor 
```
2. Web server error log:
```
2015/01/08 14:25:26 [error] 333#0: *458209 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.42.1, server: ****, request: "DELETE /remote.php/webdav/web/cscms.org/www/includes/html/polymer-same-name-extending/polymer.js HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock", host: "****"
```
3. ownCloud log (data/owncloud.log):
Nothing (even after removing from web interface)
4. ownCloud client log

Applicable line is (after file removal):
```
|0|cscms.org/www/includes/html/polymer-same-name-extending/polymer.js|INST_REMOVE|Up|1420634871|W/"54ad2b86aa46f"|0|01024839oc5ccb4a7b3c|2|504 Gateway Time-out|0|0|0|||INST_NONE|
```

**Comment by PVince81** [comment] 2015-01-09 10:59
Is there a common pattern for the non-deletable files ?
Are these big files ? (which maybe take too long to be copied to the trashbin and run into a timeout that kills the process)

**Comment by nazar-pc** [comment] 2015-01-09 13:52
No, this is small source code file few kiB, sometimes few bytes, all files are of such size.

**Comment by hugoboss2014b** [comment] 2015-02-06 09:20
I have the same problem.
Ubuntu 12:04, nginx. php5-fpm, mysql, ownCloud version: 7.0.4

**Comment by hugoboss2014b** [comment] 2015-02-06 09:24
I found something out:
When I deactivate the Deleted files 0.6.2 App, then I can delete files!

**Comment by hugoboss2014b** [comment] 2015-02-06 16:11
I reactivated this App again, and then deleted all deleted files in the recycle bin. Then I can delete files again even if the App is activated.

**Comment by PVince81** [comment] 2015-02-06 16:34
So, possibly a bug in the trashbin app

**Comment by PVince81** [comment] 2015-02-06 16:35
Note that the trashbin app has some logic to auto-clean itself when full (if using about 50% of the user's quota storage). Maybe that logic got triggered when you deleted a file but failed for some reason and made the whole deletion fail.

**Comment by PVince81** [comment] 2015-03-02 11:53
I suspect it could be due to the auto-clean taking too long, found a bottleneck here: https://github.com/owncloud/core/issues/11240#issuecomment-76696808

**Comment by PVince81** [comment] 2015-03-06 09:56
The expiration code in the trashbin has been found to be slow.

If you'd clear your trashbin before deleting the file, it should then always work.

The problem is that when deleting a file and the trashbin is full, it tries to auto-expire files. That code was discovered to be slow.

Closing. See https://github.com/owncloud/core/issues/13974#issuecomment-77531761

**Closed by PVince81** 2015-03-06 09:56 UTC
Labels: app:files_trashbin, bug
