### ISSUE TITLE
KEYEXPIRED or old for OwnCloud Ubuntu Package 16.04

### ISSUE THREAD

**Issue by 00tau** [owncloud/core#26020] opened 2016-09-02 13:35 UTC
Hi,

following the instructions on

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

for Ubuntu 16.04, the release key seems to be expired or old or not working.

```
% sudo apt-get update
[...]
W: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg: Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)
```

```
% sudo apt-get install owncloud-client
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Die folgenden zusätzlichen Pakete werden Installiert
  libowncloudsync0 libqt5keychain1 owncloud-client-l10n
Die folgenden NEUEN Pakete werden installiert:
  libowncloudsync0 libqt5keychain1 owncloud-client owncloud-client-l10n
0 aktualisiert, 4 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 1.712 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 6.627 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n]
WARNUNG: Die folgenden Pakete können nicht authentifiziert werden!
  libqt5keychain1 libowncloudsync0 owncloud-client-l10n owncloud-client
Diese Pakete ohne Überprüfung installieren? [j/N]
E: Einige Pakete konnten nicht authentifiziert werden.
```

**Comment by RealRancor** [comment] 2016-09-02 13:43
@00tau Duplicate of https://github.com/owncloud/client/issues/5055 where already some preparations done to provide a pgp key without a weak signature algorithm.

You can close here and follow the still open issue above.

**Closed** 2016-09-02 14:04 UTC
