### ISSUE TITLE
No uploads via browser since upgrading to 9.1.4. WebDAV is OK.

### ISSUE THREAD

**Issue by JoeatMJ** [owncloud/core#27156] opened 2017-02-14 21:39 UTC
### Steps to reproduce
1. Update from from owncloud.org ubuntu repos
2. Follow upgrade procedure
3. Web browser uploads no longer work.

### Expected behaviour
Tell us what should happen

You should be able to upload via browsers using the upload button or dragging and dropping.

### Actual behaviour
Tell us what happens instead

Icon changes on the file being dragged, but nothing happens after you release.

### Server configuration
**Operating system**: Ubuntu 16.04 Server LTS

**Web server:** Apache2

**Database:** MySql

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) 9.1.4 (stable)

**Updated from an older ownCloud or fresh install:** 9.1.3 (stable)

**Where did you install ownCloud from:** owncloud repos for Ubuntu hosted at owncloud.org

**Signing status (ownCloud 9.0 and above):** Good

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome
Firefox
IE
Safari
You name it.

**Operating system:**
Windows 10
MacOS 10, 11, 12

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment] 2017-02-14 21:59
@JoeatMJ your report holds not enough information about your issue. Please provide information like log entries and browser console output. THX

**Comment by JoeatMJ** [comment] 2017-02-15 01:39
_Here are some sample log entries of note:

This one, I have loads of:_

Fatal	remote	Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.4.2 to 9.1.3.1)

_I upgraded using APT and using the repositories at owncloud.com. I have done it several times with no issues at all. I would have reverted back to a backup, but we had files that needed to get out and the links have already been sent to the end users._

_This one I am getting a good deal as well:_ 

Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 503 System in maintenance mode.","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/MaintenancePlugin.php","Line":84,"User":"thatguy"}

**Comment by PVince81** [comment] 2017-02-15 08:22
Are these log entries appear exactly after performing an upload ?

It should be impossible to do anything in the web UI when in maintenance mode. There is no such thing as partial maintenance mode.

**Comment by LalaBen** [comment] 2017-02-15 15:57
Hi, i have the same problem, i open a topic here : 
https://central.owncloud.org/t/upload-through-web-dont-work-since-9-1-4/5786/7

The problem is log in firebug : 
`TypeError: OC.Util.isIE11 is not a function
if (OC.Util.isIE11()) {
file-up...2277a96 (ligne 340, col. 10)`

And in chrome : 
`Uncaught TypeError: OC.Util.isIE11 is not a function
    at HTMLInputElement.add (https://*****)
    at $.(anonymous function).(anonymous function)._trigger (https://****)
    at File.<anonymous> (https://****)
    at Function.each (https://****)
    at $.(anonymous function).(anonymous function)._onAdd (https://****)
    at $.(anonymous function).(anonymous function)._onAdd (https://****)
    at Object.<anonymous> (https://*****)
    at j (https://****)
    at Object.add [as done] (https://****)
    at Object.always (https://****)`

**Comment by PVince81** [comment] 2017-02-15 16:03
Try typing this in your browser console:
`OC.Util.isIE8()`
then
`OC.Util.isIE11()`

What's the result ?

I tried my own 9.1.4 instance and uploading works fine.
Maybe the file core/js/js.js did not get updated properly ?

**Comment by LalaBen** [comment] 2017-02-15 16:28
Hi, i have this : 

OC.Util.isIE8()
false
OC.Util.isIE11()
TypeError: OC.Util.isIE11 is not a function
OC.Util.isIE11()

**Comment by LalaBen** [comment] 2017-02-16 14:37
@PVince81 can i help you with an other thing ? 

Thanks :)

**Comment by PVince81** [comment] 2017-02-16 14:40
Try taking the file core/js/js.js from the original tarball and compare it with yours.
Something likely went wrong when replacing the source code in your updates

**Comment by LalaBen** [comment] 2017-02-16 14:41
Thank you, i'll do it right now :)

**Comment by LalaBen** [comment] 2017-02-16 14:59
Same sha256sum : ad305aa40c0be809abec45a56481377786f019abb047e4bd6e74382a38383a59

:(

**Comment by PVince81** [comment] 2017-02-16 15:04
@LalaBen clear browser cache ?

If it still doesn't work, open the developer console and check the "js.js" file. At line 1882 you should see the `isIE11` function, like here: https://github.com/owncloud/core/blob/v9.1.4/core/js/js.js#L1882

**Comment by LalaBen** [comment] 2017-02-16 15:12
oh wait !
I have a js.js in my personnal theme folder ! May be it is the problem ??

**Comment by PVince81** [comment] 2017-02-16 15:14
Very likely.

**Comment by LalaBen** [comment] 2017-02-16 15:26
I copy js.js in my theme and it works...

It's really problematic for future updates. How can i will know files i need to change or not ??

**Comment by PVince81** [comment] 2017-02-16 15:27
Why do you copy js.js into your theme ? You don't need to do that.

**Comment by LalaBen** [comment] 2017-02-16 15:30
I have : 
owncloud/core/js/js.js
AND
owncloud/themes/MY-THEME/core/js/js.js

So i just did : 
cp owncloud/core/js/js.js owncloud/themes/MY-THEME/core/js/.

And uploads works now

**Comment by LalaBen** [comment] 2017-02-16 15:33
I just reading : https://doc.owncloud.org/server/9.0/developer_manual/core/theming.html#notes-for-updates

**Comment by LalaBen** [comment] 2017-02-16 15:42
So what does Owncloud recommend to update my theme (the folder) without broke it ? :/

Merge what ? 

Thank you again for your help

**Comment by PVince81** [comment] 2017-02-16 15:57
Repeating the question:

Why do you copy js.js into your theme in the first place ?
You don't need to do that.

Just remove js.js from the theme.

**Comment by PVince81** [comment] 2017-02-16 15:58
and also remove any other file that you have copied there.

The theme should only contain custom additional files.

**Comment by LalaBen** [comment] 2017-02-16 16:12
> Why do you copy js.js into your theme in the first place ?
if your question is why there is a js.js into my theme ?
honestly i dont fucking know and it does not reassure me...
I just modify css and images in my theme, and i have never seen all this files in core... i don't understand oO

**Comment by tomaaa** [comment] 2017-02-17 19:02
Hello, 
I have exactly the same problem but I didn't modify the theme folder. I don't find a solution for now. Uploading with apps works.

**Comment by PVince81** [comment] 2017-02-17 19:10
@tomaaa follow the same path: https://github.com/owncloud/core/issues/27156#issuecomment-280347752

**Comment by tomaaa** [comment] 2017-02-17 20:58
It's a new installation, I ran both functions :
OC.Util.isIE8()
false
OC.Util.isIE11()
false

core/js/js.js  my js.js file and yours are the same.

**Comment by PVince81** [comment] 2017-02-20 08:21
@tomaaa then your problem is not exactly the same as @LalaBen but show similar symptoms.

Can you fill out the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md especially the parts about logs ? It might help find out what's going on on your setup.

**Comment by tomaaa** [comment] 2017-02-22 16:23
#PVince81 It's seems a firewall issue...

**Comment by PVince81** [comment] 2017-04-06 11:47
env issue, not an OC bug -> closing

**Closed by PVince81** 2017-04-06 11:47 UTC
Labels: needs info
