### ISSUE TITLE
Don't systematically close all backlog ideas

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#29944] opened 2017-12-21 08:08 UTC
I think this is a good idea for some old issues of error which were reported once in an old version and never have been reproduced. However, it also starts to close backlogged topics with many small ideas for improvement. Obviously, some of them were not so interesting to be implemented by anyone yet. But I'd rather prefer a developer to judge if the idea is useful and if the implementation is doable (in a reasonable amount of time).

**Comment by PVince81** [comment] 2017-12-21 08:30
I already went through all enhancement tickets last week and closed most which I think were not doable or won't fix. So maybe you're right and we don't need the bot to do the same now.

@DeepDiver1975 can we exclude "tech debt" and "enhancement" from the bot ?

**Comment by PVince81** [comment] 2017-12-21 08:31
also it seems the bot is trying to close already closed issues ?! https://github.com/owncloud/core/issues/26086#event-901819943

**Comment by phil-davis** [comment] 2017-12-21 08:34
I have >300 github notifications for core today - makes it difficult to find the ones that I should really look at. The bot needs to be nobbled.

**Comment by PVince81** [comment] 2017-12-21 08:38
Turns out the bot is already configured to ignore "enhancement" and "technical debt" (well, it's set to 2555 days as there is no disable feature).

I think I'll just disable it for now and we can look into this after the holidays... need to contact the Gitmate folks...

**Comment by DeepDiver1975** [comment] 2017-12-21 08:46
> Turns out the bot is already configured to ignore "enhancement" and "technical debt" (well, it's set to 2555 days as there is no disable feature).

this setting was wrong - since yesterday it is possible to define labels which need to be ignored.

**Comment by PVince81** [comment] 2017-12-21 08:47
ok I'll adjust and report a bug about the "already closed" closing

**Comment by PVince81** [comment] 2017-12-21 08:51
Raised here. https://gitlab.com/gitmate/open-source/gitmate-2/issues/273

I've reenabled the bot for now and we'll see if it correctly excludes enhancements now.

**Comment by PVince81** [comment] 2017-12-21 08:55
I was just told in the ticket that they released a fix for this as well an hour ago

**Comment by sils** [comment] 2017-12-21 09:49
Hi,

We are sorry that this happened and fixed the problem as soon as we were aware (such that the problem did not occur anymore since we knew about it). We are also introducing new measures to improve our stability with a new QA stage in addition to our existing ones so those kinds of issues don't happen again.

We will soon release a script to undo the actions that have happened wrongly. You will be able to manually apply it to your repository - or not if you decide that you don't want those events to pop up in your activity and rather leave it with that.

Please let us know if we can do anything further to help with this.

**Comment by PVince81** [comment] 2017-12-21 10:47
@sils thanks, we already went through all tickets and reopened what made sense.

**Comment by sils** [comment] 2017-12-21 11:31
@PVince81 us closing those tickets was not a bug to my knowledge because the exclude feature only exists since our release yesterday evening. (We included it for you because @DeepDiver1975 asked for it yesterday.) I assume the closures you talk about were before yesterday evening and only the "gitmate commenting on closed issues" was today night (which was a bug).

GitMate will do it's 12-hourly round of adding stale labels in half an hour and the closing issue one in 1.5 hours. This time with the exclude set up and configured :+1:

**Comment by PVince81** [comment] 2017-12-21 14:25
@sils before you introduced this feature today, we had set "enhancement" tickets to 2555 days but still the bot closed issue. So I thought there was a bug related to the delay. Anyway, glad there's the exclude feature now 👍

**Closed** 2017-12-21 14:26 UTC
