### ISSUE TITLE
File changes not syncing from client to external smb storage - No e-tag were present error

### ISSUE THREAD

**Issue by stmgit** [owncloud/core#16853] opened 2015-06-10 01:15 UTC
### Steps to reproduce
0. configure external storage connection to smb share
1. create testing1.txt file on external storage location
2. wait for sync to Mac or Win client
3. edit file in client file system
4. wait for sync of changes back to server
5. sync fails

(sync works to local server file system)
### Expected behaviour
Modified files should should be updated/sync'ed with server. 

### Actual behaviour
OC client sync fails with error: The item is not synced because of previous errors: The server did not acknowledge the last chunk. (No e-tag were present) 
Server log shows: Semicolon not supported in commands at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#116
In target directory on server multiple new files in format: "testing1.txt.ocTransferId14745558.part" get created on every sync attempt.

### Server configuration
**Operating system**:
Ubuntu 14.04.2 LTS with Apache2, MySQL, PHP
Client: OSX 10.10.3 OC 1.8.2 (build 2416), Win7 OC 1.8.2 (build 5166)

**Web server:**
Apache2
**Database:**
MySql
**PHP version:**
5.5.9-1
**ownCloud version:** (see ownCloud admin page)
8.0.4
**Updated from an older ownCloud or fresh install:**
new install
**List of activated apps:**
-Activity
-External Storage Support
-File Locking
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocfnvh5pfy7d',
  'passwordsalt' => 'xxxxx',
  'secret' => 'xxxxx',
  'trusted_domains' =>
  array (
    0 => 'cloud.xxxxx.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://cloud.xxxxx.com',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxx',
  'installed' => true,
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Client App:**
Windows and Mac client v1.8.2 (Win build 5166), (Mac build 2416) 
**Browser:**
not a problem in browser
**Operating system:**
Windows7 and OSX
#### Web server error log
[Tue Jun 09 20:50:43.111439 2015] [:error] [pid 8816] [client 10.10.10.113:62668] {"reqId":"bd8c1f1ec9b895d588ff148718bda8a5","remoteAddr":"10.10.10.113","app":"PHP","message":"Semicolon not supported in commands at \\/var\\/www\\/owncloud\\/apps\\/files_external\\/3rdparty\\/smb4php\\/smb.php#116","level":3,"time":"2015-06-10T00:50:43+00:00"}
[Tue Jun 09 20:50:43.111838 2015] [:error] [pid 8816] [client 10.10.10.113:62668] {"reqId":"bd8c1f1ec9b895d588ff148718bda8a5","remoteAddr":"10.10.10.113","app":"PHP","message":"chmod(): Operation not permitted at \\/var\\/www\\/owncloud\\/lib\\/private\\/log\\/owncloud.php#85","level":3,"time":"2015-06-10T00:50:43+00:00"}

#### ownCloud log (data/owncloud.log)
no entry 

#### Browser log
n/a

**Comment by DeepDiver1975** [comment] 2015-06-10 12:21
> Semicolon not supported in commands at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/smb4php\/smb.php#116"

@LukasReschke please have a look - THX

**Comment by LukasReschke** [comment] 2015-06-10 12:25
> [Tue Jun 09 20:50:43.111439 2015] [:error] [pid 8816] [client 10.10.10.113:62668] {"reqId":"bd8c1f1ec9b895d588ff148718bda8a5","remoteAddr":"10.10.10.113","app":"PHP","message":"Semicolon not supported in commands at \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/smb4php\/smb.php#116","level":3,"time":"2015-06-10T00:50:43+00:00"}

Do any of your files contain a `;`?

**Comment by LukasReschke** [comment] 2015-06-10 12:28
Also for debugging purposes it would help if you change at https://github.com/owncloud/core/blob/c391f74c2e80e6237526631020c775dd87d33010/apps/files_external/3rdparty/smb4php/smb.php#L116 the line from:

```
trigger_error('Semicolon not supported in commands');
```

to 

```
trigger_error('Semicolon not supported in commands: '. $command);
```

If the error reappears then please provide back the error message. You can find the file in `apps/files_external/3rdparty/smb4php/smb.php`.

**Comment by stmgit** [comment] 2015-06-10 12:36
No semicolon in the file name, here's the log output of the failing command. Thx.

[Wed Jun 10 08:32:28.424163 2015] [:error] [pid 8816] [client 209.104.244.242:7182] {"reqId":"9e75475161ad0b33bcf9515a33299bb8","remoteAddr":"209.104.244.242","app":"PHP","message":"Semicolon not supported in commandsdel \\"\\\\stm\\\\Test\\\\testing1.txt\\"; rename \\"\\\\stm\\\\Test\\\\testing1.txt.ocTransferId91965412.part\\" \\"\\\\stm\\\\Test\\\\testing1.txt\\" at \\/var\\/www\\/owncloud\\/apps\\/files_external\\/3rdparty\\/smb4php\\/smb.php#116","level":3,"time":"2015-06-10T12:32:28+00:00"}
[Wed Jun 10 08:32:28.424686 2015] [:error] [pid 8816] [client 209.104.244.242:7182] {"reqId":"9e75475161ad0b33bcf9515a33299bb8","remoteAddr":"209.104.244.242","app":"PHP","message":"chmod(): Operation not permitted at \\/var\\/www\\/owncloud\\/lib\\/private\\/log\\/owncloud.php#85","level":3,"time":"2015-06-10T12:32:28+00:00"}

**Comment by LukasReschke** [comment] 2015-06-10 12:47
```
del \\"\\\\stm\\\\Test\\\\testing1.txt\\"; rename \\"\\\\stm\\\\Test\\\\testing1.txt.ocTransferId91965412.part\
```

Ewww. https://github.com/owncloud/core/blob/429fb8738641bd090bcc49923c5391e8bc3dcb45/apps/files_external/3rdparty/smb4php/smb.php#L331: 

```php
$cmd = '';
// check if target file exists
if (smb::url_stat($url_to)) {
	// delete target file first
	$cmd = 'del "' . $to['path'] . '"; ';
	$replace = true;
}
$cmd .= 'rename "' . $from['path'] . '" "' . $to['path'] . '"';
$result = smb::execute($cmd, $to);
```

Apparently that library uses command concatenation when a file already exists on the "rename" action.  

Can you try the changes from https://github.com/owncloud/core/pull/16862 ?

**Comment by PVince81** [comment] 2015-06-11 12:48
Fixed by https://github.com/owncloud/core/pull/16862

**Closed by PVince81** 2015-06-11 12:48 UTC
Labels: app:files_external, bug, needs info

**Comment by adrianoafonso** [comment] 2015-07-15 17:22
Having exactly the same problem here. Configuration is somehow equal, with Debian 7 and PostGresSQL syncing to a Win2008R2 Server share.

Error 	PHP 	Semicolon not supported in commands at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#116 	2015-07-15T17:19:05+00:00

Is this already pached @PVince81? When the update comes?

**Comment by PVince81** [comment] 2015-07-16 08:04
@adrianoafonso this should be in OC 8.0.5 and 8.1.1. Did you upgrade ?

**Comment by adrianoafonso** [comment] 2015-07-21 15:56
@PVince81 After a day of bug tracking and trying to understand why DAV wasn't working after 8.1.0 update, he always gives me **"Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken."** , so desperately I disable the **External storage support**, and suddenly he starts to work. But now I cant re-enable the app and he gives me this error.
```
Exception: {"Message":"HTTP\/1.1 409 Parent node does not exist","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(583): Sabre\\DAV\\Server->createCollection('Servidor\/PHC\/An...', Array, Array)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1138}
```

Please help me :(

**Comment by PVince81** [comment] 2015-07-27 12:36
@adrianoafonso I don't understand why the external storage would prevent MKCOL to work.
Can you try using a Webdav client like cadaver and create a folder ?
Try this with external storage disabled, and then enabled.

Maybe something is trying to create a folder using an invalid path ? Are you able to identify what path is being used when creating that folder ? Maybe the client activity log shows it.

**Comment by adrianoafonso** [comment] 2015-07-28 15:36
Hello @PVince81, I used to use **curl** over windows:
```
curl.exe -k --anyauth --url https://mycloud.no-ip.info/owncloud/remote.php/webdav/Folder --user <username:passord> -l
```
But now whit the same parameters, it gives me:
```
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.
```
Is this because of the webdav server redesign?

The connection whit **cadaver** (also over windows) gives me an error possibly related whit my self signed SSL certificate:
```
WARNING: Untrusted server certificate presented for `mycloud':
Certificate was issued to hostname `mycloud' rather than `mycloud.no-ip.info'
This connection could have been intercepted.
Issued to: FTCB, Futurcabo, Lda, S. Domingos de Rana, Lisboa, PT
Issued by: FTCB, Futurcabo, Lda, S. Domingos de Rana, Lisboa, PT
Certificate is valid from Thu, 16 Jul 2015 17:25:14 GMT to Fri, 15 Jul 2016 17:25:14 GMT
Do you wish to accept the certificate? (y/n) y
Authentication required for ownCloud on server `mycloud.no-ip.info':
Username: <username>
Password:
Could not open collection:
SSL handshake failed: SSL error: unexpected message
```
Could it be from this? Self signed certificates?
PS: Changed some details, like urls.

**Comment by PVince81** [comment] 2015-07-28 15:38
@adrianoafonso no, you cannot do a "GET" on a folder in general, only on files.
Add `-X PROPFIND` to your command to change the verb.

**Comment by adrianoafonso** [comment] 2015-09-02 10:27
Hello there again @PVince81.
After some failed tests, I decide to migrate to Debian 8. The difference after install is the External storage support is enabled and working, but whit the SMB / CIFS options disabled. And that's makes me ring a bell! I could test that earlier, if I had remember :P.
Anyway, I think the problem is a conflict in some package that Debian installs by default when I install de SMB client, because I keep receiving the **"Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken."** error when I activate the **SMB / CIFS** option. Any of this packages makes sense to you that may cause a conflict?

```
## SAMBA packages
root@cloud:~# apt-get install smbclient
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  dbus libasn1-8-heimdal libavahi-client3 libavahi-common-data
  libavahi-common3 libcap-ng0 libcups2 libdbus-1-3 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libkrb5-26-heimdal libldb1 libntdb1 libpython2.7
  libroken18-heimdal libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0
  libwind0-heimdal python-crypto python-ldb python-ntdb python-samba
  python-talloc python-tdb samba-common samba-common-bin samba-libs
Suggested packages:
  dbus-x11 cups-common python-crypto-dbg python-crypto-doc heimdal-clients
  cifs-utils
The following NEW packages will be installed:
  dbus libasn1-8-heimdal libavahi-client3 libavahi-common-data
  libavahi-common3 libcap-ng0 libcups2 libdbus-1-3 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libkrb5-26-heimdal libldb1 libntdb1 libpython2.7
  libroken18-heimdal libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0
  libwind0-heimdal python-crypto python-ldb python-ntdb python-samba
  python-talloc python-tdb samba-common samba-common-bin samba-libs smbclient

```

**Comment by PVince81** [comment] 2015-09-02 10:32
@adrianoafonso is this related to the original issue ? If not, please raise as a separate ticket.

**Comment by adrianoafonso** [comment] 2015-09-02 10:53
@PVince81 it started whit the **No e-tag were present error**, and escalated to the **"Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken."** as I have been posting!
But yes, you're right. Now is a different problem. Any issue you may suggest where I can attach my case?

**Comment by PVince81** [comment] 2015-09-02 11:10
@adrianoafonso I'm not aware of any such issue. You seem to mention packaging issues.

**Comment by adrianoafonso** [comment] 2015-09-02 13:11
@PVince81 https://github.com/owncloud/core/issues/18772 if you can help!
