### ISSUE TITLE
Update to 8.1.4 failed

### ISSUE THREAD

**Issue by whoosename** [owncloud/core#20237] opened 2015-11-02 18:40 UTC
The update gave this output:
Updating ownCloud to version 8.1.4, this may take a while.

Set log level to debug - current level: "Warning"
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files_sharing" to 0.6.3
Exception: Failed to open archive when installing app
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by whoosename** [comment] 2015-11-02 18:44
Tried the update again (both via  firefox) and this time worked without problems.

**Comment by DeepDiver1975** [comment] 2015-11-02 21:58
Anything in the logs?
Please follow our guidelines on how to report issues: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by deMattin** [comment] 2015-11-03 03:28
Had the same problem.
In my case, also reloading the Browserpage does "fix" it and update worked.
The message:
`Exception: Failed to open archive when installing app
The update was unsuccessful. Please report this issue to the ownCloud community.`
seems to be because of update the bookmarks app.
If you try to update from 0.4 to 0.5 you get this message,
I deleted Bookmarks app and tried to reinstall and the message comes again and no installation of bookmarks app is possible.

**Comment by whoosename** [comment] 2015-11-03 04:16
In my case it was the contacts app. Trying to activate it I've got the message: The folder for this app already exists.
So I went to the "Not activated" site and saw there was an update available. Clicked "update" logged out, closed Browserpage, relogged in and the contact app worked.
@DeepDiver1975 
I'v got about 100 lines how to submit? copy and paste?

**Comment by RealRancor** [comment] 2015-11-03 05:39
The bookmarks issue is reported here: https://github.com/owncloud/bookmarks/issues/202 which is caused by https://github.com/owncloud/core/pull/20196

**Comment by MorrisJobke** [comment] 2015-11-10 13:03
@LukasReschke This is fixed with https://github.com/owncloud/core/pull/20196, correct?

**Comment by MorrisJobke** [comment] 2015-11-10 13:03
Backport to stable8.1: https://github.com/owncloud/core/pull/20307

**Comment by LukasReschke** [comment] 2015-11-10 13:15
Looks likely. Can't tell 100% if this is really the case.

**Comment by MorrisJobke** [comment] 2015-11-10 15:01
Will be fixed in 8.1.5 -> close

**Closed by MorrisJobke** 2015-11-10 15:01 UTC
Labels: bug, update
