### ISSUE TITLE
Apps not working after update from 8.02 to 8.03.

### ISSUE THREAD

**Issue by hydrosIII** [owncloud/core#16546] opened 2015-05-23 22:03 UTC
Hi im using owncloud in Debian Jessie, and when i upgraded from the 8.02 version to the 8.03  recognizing the app directory. I ve got these errors from the owncloud log.
````
array_map(): Argument #2 should be an array at /srv/http/owncloud/settings/controller/appsettingscontroller.php#175 
````
I have reinstalled owncloud completely to be sure that i had not a corrupted installation, i just moved the data and config.php.

I have installed owncloud 8.03 via the OpenSuse build service.

PHP version:

PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

Using Apache 2.4

I have already ensured that the apps folder is readable by the web server.

I really need the documents app. Hope there is some solution.

**Comment by RealRancor** [comment] 2015-05-23 22:26
Hi,

could be related to https://github.com/owncloud/core/issues/14185

**Comment by RealRancor** [comment] 2015-05-24 14:15
@hydrosIII 
Feel free to close this issue as it is a duplicate of the one posted above.

**Closed** 2015-05-25 07:06 UTC
