### ISSUE TITLE
upgrade from 8.1 to 8.1.1 fails

### ISSUE THREAD

**Issue by dmnk** [owncloud/core#18296] opened 2015-08-13 18:38 UTC
Updating ownCloud to version 8.1.1, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
```Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.```
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by dmnk** [comment] 2015-08-13 18:45
after re-starting the upgrade at the terminal, it runs through without further error messages.

**Comment by MorrisJobke** [comment] 2015-08-14 09:41
Duplicate of #18224

**Closed by MorrisJobke** 2015-08-14 09:41 UTC
