### ISSUE TITLE
Update Error Owncloud 10.0.1

### ISSUE THREAD

**Issue by chihaya167** [owncloud/core#28036] opened 2017-05-30 11:50 UTC
### Steps to reproduce
1.Access Owncloud
2.Select Update button
3.Wait until the end

### Expected behaviour
Displayed following Messages.

Doctrine\DBAL\Exception\DriverException:
An exception occurred while executing
'CREATE TABLE oc_account_terms (id BIGINT
UNSIGNED AUTO_INCREMENT NOT NULL,
account_id BIGINT UNSIGNED NOT NULL,
term VARCHAR(256) NOT NULL, INDEX
account_id_index (account_id), INDEX
term_index (term), PRIMARY KEY(id))
DEFAULT CHARACTER SET utf8 COLLATE
utf8_bin ENGINE = InnoDB':
SQLSTATE[42000]: Syntax error or access
violation: 1071 Specified key was too long;
max key length is 767 bytes

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
FreeBSD 9.3 Release x86_64

**Web server:**
apache24-2.4.25_1
 
**Database:**
mysql56

**PHP version:**
php56

**ownCloud version:** (see ownCloud admin page)
10.0.1

**Updated from an older ownCloud or fresh install:**
not fresh

**Where did you install ownCloud from:**
Chrome and Firefox

**Comment by kdslkdsaldsal** [comment] 2017-05-30 12:23
@chihaya167 This is a duplicate of https://github.com/owncloud/core/issues/28015 and https://github.com/owncloud/core/issues/28007 so you can close this and keep an eye on #28007 for now.

**Closed** 2017-05-30 12:55 UTC
