### ISSUE TITLE
Error during upgrading Debian packages to 8.0.3-1

### ISSUE THREAD

**Issue by wolfgangkarall** [owncloud/core#16007] opened 2015-05-02 05:01 UTC
```
Unpacking replacement owncloud-server ...
dpkg: error processing /var/cache/apt/archives/owncloud-server_8.0.3-1_all.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud-config-apache 8.0.2-8
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

Another run of apt (i.e. apt-get -f install) fixes the issue (since owncloud-config-apache is then at 8.0.3-1 already), but moving files from one Debian package to another package should be handled differently I guess.

**Comment by jsalatiel** [comment] 2015-05-02 11:26
Another run of apt (i.e. apt-get -f install)  DOES NOT fix the issue.

sudo apt-get -f install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  owncloud-server
The following packages will be upgraded:
  owncloud-server
1 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
20 not fully installed or removed.
Need to get 0 B/11.0 MB of archives.
After this operation, 16.4 kB of additional disk space will be used.
Do you want to continue? [Y/n] yes
(Reading database ... 328580 files and directories currently installed.)
Preparing to unpack .../owncloud-server_8.0.3-1_all.deb ...
Unpacking owncloud-server (8.0.3-1) over (8.0.2-8) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-server_8.0.3-1_all.deb (--unpack):
 trying to overwrite '/var/www/owncloud/.htaccess', which is also in package owncloud-config-apache 8.0.2-8
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-server_8.0.3-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Running ubuntu 14.04 , unattended-upgraded failed.

**Comment by benurb** [comment] 2015-05-02 13:54
For me on Ubuntu 14.10 another `apt-get -f install` did the trick. You might be able to fix our problem with `dpkg -r --force-depends "owncloud-config-apache "`, but no guarantee for that.

**Comment by jsalatiel** [comment] 2015-05-02 14:37
I did that, and it worked, thanks !

**Comment by starak** [comment] 2015-05-02 19:34
For me on Ubuntu 14.04 another `apt-get -f install` did the trick as vel. Thanks!

**Comment by brendanpuck** [comment] 2015-05-03 01:48
@benurb Thanks the dpkg force-depends was necessary on my Ubuntu 14.04 - much appreciated!

**Comment by boltronics** [comment] 2015-05-03 08:47
I got this too on Wheezy. Luckily ```apt-get -f install`` worked.

**Comment by RalfJung** [comment] 2015-05-03 09:50
The Debian packaging guide has all the information for how to move files from one package to another: <https://www.debian.org/doc/debian-policy/ch-relationships.html#s-replaces>.

**Comment by pascalBokBok** [comment] 2015-05-04 10:21
running `apt-get -f install` alone did not solve the problem on Debian for me. It has to have the `dpkg -r --force-depends "owncloud-config-apache"` first.

**Comment by DeepDiver1975** [comment] 2015-05-04 11:37
@jnweiger

**Comment by ls960** [comment] 2015-05-04 19:32
solved in debian 7 running # apt-get install owncloud-server  insetad of apt-get dist-upgrade.

**Comment by midimarcus** [comment] 2015-05-06 13:19
I can confirm error in Ubuntu 14.04.2 LTS.
I solved with suggested commands in following order:
```
dpkg -r --force-depends "owncloud-config-apache"
apt-get -f install
```

**Comment by Genjo** [comment] 2015-05-06 16:33
Like @ls960 said, 
```ShellSession
apt-get install owncloud-server
```
did the trick for me too!
And
```ShellSession
apt-get dist-upgrade
```
succeed after.

But I didn't understand why :/ Somebody knows?
Thanks!

**Comment by jnweiger** [comment] 2015-05-06 17:16
Hmmm, debian control file
    
    Package: owncloud-server
    ...
    Replaces: owncloud-config-apache (<= 8.0.2)
    Breaks: owncloud-config-apache (<= 8.0.2)
    ...

does not help, while

    Package: owncloud-server
    ...
    Replaces: owncloud-config-apache (<< 8.0.3)
    Breaks: owncloud-config-apache (<< 8.0.3)
    ...

fixes the issue. Anybody to explain the difference?

**Comment by benurb** [comment] 2015-05-06 17:22
Because the last version of `owncloud-config-apache` was `8.0.2-8` which is newer (aka. greater) than `8.0.2`.

**Comment by jnweiger** [comment] 2015-05-06 18:19
thanks @benurb , I see. So a build release number is considered part of the version number for DEB, but is not for RPM. Sigh.

Pushed the fix to isv:ownCloud:community:8.0 owncloud 
Updates to 8.0.3-2 should have no issues with the .htaccess file any more.

**Closed** 2015-05-06 18:20 UTC
Labels: bug, packaging

**Comment by wolfgangkarall** [comment] 2015-05-06 21:06
@jnweiger in case of doubt, use dpkg --compare-versions

**Comment by etiess** [comment] 2015-05-09 14:47
Hello @jnweiger 
I tried to update to 8.0.3 on Ubuntu 15.04, and I get this error message:

Dépend: owncloud-server (= 8.0.3-2) mais 8.0.2-4 devra être installé
Dépend: owncloud-config-apache (= 8.0.3-2) mais 8.0.2-4 devra être installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».

Translation:
Depend: owncloud-server (= 8.0.3-2) but 8.0.2-4 will have to be installed
Depend: owncloud-config-apache (= 8.0.3-2) but 8.0.2-4 will have to be installed
E: Impossible to correct the problems, deffect packages are in mode "keep in state".

Is this related? Or do I open a new issue?

Config: Ubuntu 15.04
3.19.0-16-generic
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Mar  9 2015 11:53:48
PHP 5.6.4-4ubuntu6 (cli) (built: Apr 17 2015 15:47:51)
mysql  Ver 14.14 Distrib 5.6.24

**Comment by finius** [comment] 2015-05-11 09:07
I am still facing the same error´when trying "sudo sudo apt-get -f install"


...
Entpacken von owncloud-server (8.0.3-2) über (8.0.2-5) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/owncloud-server_8.0.3-2_all.deb (--unpack):
 Versuch, »/var/www/owncloud/.htaccess« zu überschreiben, welches auch in Paket owncloud-config-apache 8.0.3-2 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Daylights** [comment] 2015-05-11 09:11
I'm running Ubuntu 12.02 LTS, I have upgraded OwnCloud using the Admin console as I thought that was the new (and only) way, now I keep having issues running apt-get -f install:
 owncloud-app-files-videoviewer depends on owncloud-server (= 8.0.3-1); however:
  Version of owncloud-server on system is 8.0.3-2.
dpkg: error processing owncloud-app-files-videoviewer (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already

**Comment by finius** [comment] 2015-05-11 11:21
Update: could resolve it manually by...
1) dropping the SuSE OC sources from apt update list
2) updating the system with the regular Ubuntu updates first
3) Then purging/removing all old content/pakets
4) Readding the SuSE OC-sources back into the Ubuntu sources list
5) Reinstall owncloud

**Comment by Daylights** [comment] 2015-05-12 09:28
After some fiddling around the apt-get upgrade is now asking me to install various ownCloud packets that require 8.0.3-2 while 8.0.3-2 is installed? How can I clean this up? apt-get update doesn't seem to fix it and apt-get -f install doesn't allow me to install it:

You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 owncloud : Depends: owncloud-server (= 8.0.3-1) but 8.0.3-2 is installed
            Depends: owncloud-config-apache (= 8.0.3-1) but 8.0.3-2 is installed
 owncloud-3rdparty : Depends: owncloud-server (= 8.0.3-1) but 8.0.3-2 is installed
 owncloud-app-activity : Depends: owncloud-server (= 8.0.3-1) but 8.0.3-2 is installed
 owncloud-app-external : Depends: owncloud-server (= 8.0.3-1) but 8.0.3-2 is installed

**Comment by finius** [comment] 2015-05-12 09:33
try to put out the owncloud repository of the apt sources list. After updating the resources and autoremove the old stuff, owncloud should be gone. update your System and then readd the owncloud repositories to the apt sources. then reinstall owncloud. because the old config files and the mysql database should stille be on the system (for only owncloud sources have been removed) it should be able to reestablish your configuration immediately after reinstalling oc

**Comment by Daylights** [comment] 2015-05-12 10:52
Seemed like a lot of work to fix a repository issue, but it did solve the problem. I created a backup to be safe, but the original owncloud/config/config.php, database and data files where kept in place, so all is back to normal now :) Thanks Finius!

**Comment by mandrappa** [comment] 2015-05-13 15:21
@benurb thanks a lot. It worked on Debian 7.0 for me

**Comment by sulliwane** [comment] 2015-08-15 15:47
@benurb thanks a lot, it worked for me on Ubuntu 14.04 with owncloud 8.0 to 8.1

**Comment by daromotica** [comment] 2015-08-16 19:33
Good job idiots
![nerds](https://cloud.githubusercontent.com/assets/11424761/9294984/780faaa8-445e-11e5-91dc-360a8799c793.png)

**Comment by benurb** [comment] 2015-08-16 19:48
Uhm, ok. You must have too much time. But for the "good job", thank you :smile:
