### ISSUE TITLE
Updating from V8.02 tp 8.03 creates exeption error

### ISSUE THREAD

**Issue by lucode** [owncloud/core#16217] opened 2015-05-10 10:47 UTC
When I start the upgrade the following error occurs:  

An exception occurred while executing 'CREATE TABLE oc_ownc_appconfig_z8u5i2f1bqcdz (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_2thc0u2wvho90 (`configkey`), INDEX oc_495l45frwx8hp (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ownc_appconfig_z8u5i2f1bqcdz' already exists

Apache-Version 	2.4.12
PHP-Version 	5.4.38
DB: MySQL     5.5.42-cll

**Comment by RealRancor** [comment] 2015-05-10 12:24
Hi,

looks like a duplicate of https://github.com/owncloud/core/issues/14916 and several others like https://github.com/owncloud/core/issues/15323 , https://github.com/owncloud/core/issues/15416 , https://github.com/owncloud/core/issues/15493 , https://github.com/owncloud/core/issues/15872

**Closed** 2015-05-11 06:50 UTC
Labels: duplicate
