### ISSUE TITLE
Windows Office files via SMB mount through WebDAV is prompting for authentication

### ISSUE THREAD

**Issue by gig13** [owncloud/core#22596] opened 2016-02-23 13:07 UTC
### Steps to reproduce
1. Place Windows Office files ( .doc, .docx, ..) on a Windows Share
2. Setup an ownCloud External Storage - SMB/CIF mount to the Windows Share
3. Attempt to open the files via a WebDAV mount through the OC mount

### Expected behavior
The user should be able to open the Windows Office files just as if they were using a standard Windows mount.

### Actual behavior
The user is prompted to authenticate when trying to open the files through WebDAV

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** MySQL

**PHP version:** to obtain

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** AD

### Client configuration
**Browser:** IE

**Operating system:** Windows

#### ownCloud log (data/owncloud.log)
Attached on s3

@MorrisJobke

**Comment by gig13** [comment] 2016-02-23 13:11
Log file on https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F22596
Does not have much info...

Other information from MS -- https://support.microsoft.com/en-us/kb/2019105

**Comment by MorrisJobke** [comment] 2016-02-23 16:22
It seems that Office tries to get a LOCK:

```
{"reqId":"VstiPqm3gBbJXhCzxe5B9gAAAAg","remoteAddr":"10.11.250.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"LOCK\\\" method\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/misc\\\/osdataprod\\\/prod\\\/mycloud.northcarolina.edu\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/misc\\\/osdataprod\\\/prod\\\/mycloud.northcarolina.edu\\\/htdocs\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/misc\\\/osdataprod\\\/prod\\\/mycloud.northcarolina.edu\\\/htdocs\\\/remote.php(137): require_once('\\\/misc\\\/osdatapro...')\\n#3 {main}\",\"File\":\"\\\/misc\\\/osdataprod\\\/prod\\\/mycloud.northcarolina.edu\\\/htdocs\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2016-02-22T19:32:15+00:00","method":"LOCK","url":"\/remote.php\/webdav\/Home\/macguide.docx"}
```



@PVince81 @LukasReschke  Aren't LOCK requests ignored and just "simulated" in 8.2? Or am I wrong here. The log indicates, that the LOCK verb is not implemented.

@LukasReschke You implemented this for One Note: https://github.com/owncloud/core/pull/21926 for 9.0

@gig13 Could you checkout which office version they use?

**Comment by gig13** [comment] 2016-02-23 20:50
@MorrisJobke 
They tried it with 2010 and 2013. With 2010 if you click cancel on the prompt it does not open the file. With 2013 if you click cancel it will open the file.

**Comment by MorrisJobke** [comment] 2016-02-23 20:54
@LukasReschke Any idea what this could be?

**Comment by LukasReschke** [comment] 2016-02-23 20:59
@MorrisJobke Probably indeed the locking. We would likely need to enable fake locking there as well, do we have user agents?

**Comment by LukasReschke** [comment] 2016-02-23 21:00
From http://sabre.io/dav/clients/msoffice/

> Locks are required for saving, otherless MS Word will open the file as read only.

> If a file is locked, Office 2007 and 2010 will ask you if you want to open the file as read only, download and modify it only in your computer or allow editing while in background the lock is checked at an interval (usually less than 20 seconds) until the file is released.

> Once Office 2003 and 2007 gets the lock, it is updated at the "x" minutes interval you specify in your SabreDav locks plugin (30 minutes by default), but this time cannot be less than 180 seconds.

> Office 2010 (Beta) has some kind of bug which makes the program don't update the lock anymore, so if another client checks the lock after the timeout, the lock will be released. This behaviour was observed in the Beta, so it may be corrected by the final product version.

Can we confirm the user agent "Microsoft Data Access Internet Publishing Provider DAV" from there as well?

**Comment by LukasReschke** [comment] 2016-02-23 21:02
> @PVince81 @LukasReschke Aren't LOCK requests ignored and just "simulated" in 8.2? Or am I wrong here. The log indicates, that the LOCK verb is not implemented.

It needs manually whitelisting of user agents and hope that clients are dumb enough to ignore the fact that we lie :wink: 

That's why we need the user agents. Then we can whitelist it as done in https://github.com/owncloud/core/pull/21926

**Comment by MorrisJobke** [comment] 2016-02-24 08:35
I only could test Office 2007 (I don't own any other version and it's pure pain to get a trail version without selling your soul to Microsoft)

```
127.0.0.1 - - [24/Feb/2016:09:33:38 +0100] "OPTIONS /remote.php/webdav/ HTTP/1.1" 200 0 "-" "Microsoft Office Protocol Discovery" 159677
127.0.0.1 - - [24/Feb/2016:09:33:38 +0100] "PUT /remote.php/webdav/Dok1.docx HTTP/1.1" 201 0 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 109719
127.0.0.1 - - [24/Feb/2016:09:33:38 +0100] "LOCK /remote.php/webdav/Dok1.docx HTTP/1.1" 501 247 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 49131
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "PROPPATCH /remote.php/webdav/Dok1.docx HTTP/1.1" 207 553 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 65623
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "HEAD /remote.php/webdav/Dok1.docx HTTP/1.1" 401 0 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 41315
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "HEAD /remote.php/webdav/Dok1.docx HTTP/1.1" 200 0 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 47758
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "PUT /remote.php/webdav/Dok1.docx HTTP/1.1" 204 0 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 113946
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "PROPPATCH /remote.php/webdav/Dok1.docx HTTP/1.1" 207 553 "-" "Microsoft-WebDAV-MiniRedir/6.3.9600" 57795
127.0.0.1 - - [24/Feb/2016:09:33:39 +0100] "HEAD /remote.php/webdav/Dok1.docx HTTP/1.1" 200 0 "-" "Microsoft Office Existence Discovery" 45753
```

And I also got the pope up that asked for credentials.

**Comment by gig13** [comment] 2016-02-29 15:50
@LukasReschke @MorrisJobke What is the summary for the customer? Do we need to make some enhancements? Is this the expected behavior (at this point in time)?

**Comment by MorrisJobke** [comment] 2016-02-29 17:21
@gig13 Could they try following patch:

```
diff --git a/lib/private/connector/sabre/serverfactory.php b/lib/private/connector/sabre/serverfactory.php
index a558a61..35b44f6 100644
--- a/lib/private/connector/sabre/serverfactory.php
+++ b/lib/private/connector/sabre/serverfactory.php
@@ -108,7 +108,11 @@ class ServerFactory {
 
        // Finder on OS X requires Class 2 WebDAV support (locking), since we do
        // not provide locking we emulate it using a fake locking plugin.
-       if($this->request->isUserAgent(['/WebDAVFS/'])) {
+       if($this->request->isUserAgent([
+           '/WebDAVFS/',
+           '/Microsoft Office Existence Discovery/',
+           '/Microsoft-WebDAV-MiniRedir/',
+       ])) {
            $server->addPlugin(new \OC\Connector\Sabre\FakeLockerPlugin());
        }
```

Best would be to test this in a test instance first. I could give this tomorrow a test.

**Comment by gig13** [comment] 2016-03-02 18:44
Please test first before I provide it to the customer.

**Comment by MorrisJobke** [comment] 2016-03-03 06:56
> Please test first before I provide it to the customer.

I don't own those office versions - so I couldn't test this :cry:

**Comment by gig13** [comment] 2016-03-03 13:41
@MorrisJobke This patch is for 822, the customer is on 821, can I provide the 822 serverfactory, or do they need to upgrade to 822?

**Comment by MorrisJobke** [comment] 2016-03-03 14:41
> @MorrisJobke This patch is for 822, the customer is on 821, can I provide the 822 serverfactory, or do they need to upgrade to 822?

It's not yet in there. It's a separate patch, that is not yet in any version.

**Comment by gig13** [comment] 2016-03-03 14:54
@MorrisJobke @bboule So we can't test it, and I can't send to the customer. Is it being scheduled for another milestone/maintenance release?

**Comment by MorrisJobke** [comment] 2016-03-03 16:06
@bboule How to proceed here? Do you have a lab machine with Office 2010 or 2013? Then I will create a PR, run tests and take care of this. But without the Office suites I'm not able to reproduce this.

**Comment by gig13** [comment] 2016-03-09 19:19
@bboule @MorrisJobke Any chance on testing this?

**Comment by MorrisJobke** [comment] 2016-03-10 09:36
> @bboule @MorrisJobke Any chance on testing this?

I still don't have any Office version available.

**Comment by MorrisJobke** [comment] 2016-03-10 12:43
> I still don't have any Office version available.

I now got a Office 2013 - I will test and fix this for Windows 7,8 and 10 with 2010 and 2013 office.

**Comment by MorrisJobke** [comment] 2016-03-10 14:06
I tested this with Office 2013 on Windows 10 and Windows 8.1

**Comment by MorrisJobke** [comment] 2016-03-10 14:06
@gig13 Fix is in https://github.com/owncloud/core/pull/23094

**Closed** 2016-03-10 22:07 UTC
Labels: app:dav, app:files_external, blue-ticket, in progress

**Comment by MorrisJobke** [comment] 2016-03-11 07:57
@gig13 Backports are created - waiting for review. Then I could provide you a patch

**Comment by rtjdamen** [comment] 2016-04-08 16:31
Tried the fake lock and it is working on windows. When i try webdrive it still has the same problem. Same for OSX

**Comment by vondrt4** [comment] 2016-04-29 11:02
I'd just like to chime in that a problem is also on Microsoft's side. I couldn't overwrite files with Word even with the discussed patch applied and this hotfix from Microsoft fixed it:
https://support.microsoft.com/en-us/kb/2479169?sd=rss&spid=14019
