### ISSUE TITLE
Renamed shared folder is deleted when renamed twice

### ISSUE THREAD

**Issue by qrof** [owncloud/core#15655] opened 2015-04-15 18:23 UTC
### Steps to reproduce
1. Login as user, upload files to a folder, for example, "Documents"
2. Share "Documents" folder with a user group, for example "Users"
3. Logout, Login as a user in the "Users" group
4. Rename "Documents" to "Documents 2"
At this point, everything is fine, the folder will rename okay
5. Rename "Documents 2" back to "Documents"

### Expected behaviour
Folder is renamed back, it is still shared by id and not name

### Actual behaviour
Folder will appear to rename but after a short while will disappear.
If you login at the user who originally uploaded the files, the folder will be gone from there also.

### Server configuration
**Operating system**: 
Ubuntu 12.04.1 LTS

**Web server:**
Nginx

**Database:**
Mysql 5.5.41-0ubuntu0.12.04.1

**PHP version:**
5.5.23-1+deb.sury.org~precise+2

**ownCloud version:** 
8.0.2

**Updated from an older ownCloud or fresh install:**
upgrade from 7.x

**Are you using external storage, if yes which one:** local/smb/sftp/...
local storage

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

**Operating system:**
OSX

#### Web server error log
```
"time": "2015-04-15T19:57:46+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "95", "request_time": "0.055", "status": "200"
, "request": "GET /index.php/core/ajax/share.php?fetch=getItemsSharedStatuses&itemType=file HTTP/1.1", "request_method": "GET", "http_referrer": "https:/
/cloud.zdis.si/index.php/apps/files/?dir=%2F", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Geck
o) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:57:56+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "5", "request_time": "0.651", "status": "500", "request": "GET /index.php/apps/files/ajax/rename.php?dir=%2F&newname=DI&file=DI2 HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/?dir=%2F", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
"time": "2015-04-15T19:58:21+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "4533", "request_time": "0.057", "status": "200", "request": "GET /index.php/apps/files/?dir=%2F HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php?redirect_url=%2Findex.php%2Fapps%2Ffiles%2F%3Fdir%3D%252F", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:21+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "741", "request_time": "0.049", "status": "200", "request": "GET /index.php/core/js/oc.js?v=4875b3810d4238e2fcac3eedd0b7fc6e HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/?dir=%2F", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "304", "request": "GET /core/img/actions/caret.svg HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "304", "request": "GET /settings/img/personal.svg HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "304", "request": "GET /settings/img/help.svg HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "304", "request": "GET /core/img/actions/logout.svg HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.000", "status": "304", "request": "GET /core/img/places/files.svg HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
"time": "2015-04-15T19:58:22+02:00", "remote_addr": "89.142.57.17", "remote_user": "-", "body_bytes_sent": "0", "request_time": "0.049", "status": "304", "request": "GET /index.php/avatar/zdis/32?requesttoken=UtoNsfUMtv4wZg5pdTBJOIy97aESb9 HTTP/1.1", "request_method": "GET", "http_referrer": "https://cloud.zdis.si/index.php/apps/files/?dir=%2F", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"99188c1daaa7e90979ab79c4e52587f6","remoteAddr":"89.142.57.17","app":"PHP","message":"Argument 1 passed to OCA\\Files\\Helper::formatFileInfo() must implement interface OCP\\Files\\FileInfo, boolean given, called in \/var\/www\/zdiscloud\/apps\/files\/lib\/app.php on line 108 and defined at \/var\/www\/cloud\/apps\/files\/lib\/helper.php#107","level":3,"time":"2015-04-15T18:57:56+01:00"}
{"reqId":"99188c1daaa7e90979ab79c4e52587f6","remoteAddr":"89.142.57.17","app":"PHP","message":"Call to a member function getMimetype() on a non-object at \/var\/www\/cloud\/apps\/files\/lib\/helper.php#49","level":3,"time":"2015-04-15T18:57:56+01:00"}
{"reqId":"12168e01aae4d81caea15c7b65ab43fe","remoteAddr":"","app":"PHP","message":"Only variables should be passed by reference at \/var\/www\/cloud\/lib\/private\/cache\/fileglobalgc.php#50","level":3,"time":"2015-04-15T19:00:02+01:00"}
{"reqId":"dc0c7da6b126601134579bf980028061","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/cloud\/lib\/private\/files\/cache\/scanner.php#226","level":3,"time":"2015-04-15T19:06:14+01:00"}
```

Also posted on forums https://forum.owncloud.org/viewtopic.php?f=31&t=27641

**Comment by karlitschek** [comment] 2015-04-15 18:33
@schiesbn

**Comment by PVince81** [comment] 2015-04-16 12:36
Know issue, duplicate of https://github.com/owncloud/core/issues/15340

You can use this patch if you like: https://github.com/owncloud/core/pull/15572

**Closed by PVince81** 2015-04-16 12:36 UTC
Labels: bug

**Comment by PVince81** [comment] 2015-04-16 12:37
@qrof you should be able to make the folder appear again by running `./occ files:scan sharinguser` (replace "sharinguser" with the name of the user who created the share)

**Comment by qrof** [comment] 2015-04-16 20:48
Many thanks!
