### ISSUE TITLE
Tags and flexible sharing

### ISSUE THREAD

**Issue by asieriko** [owncloud/core#16427] opened 2015-05-18 22:03 UTC
We are using owncloud every day, and I've found a limitation for us.
I want to share some files/folder in my folder structure with another users, but I don't want to share all my folders so I've to share file by file and it makes a mess in the shared folder of the other users.
So we think it could be interesting to be able to tag files and folders and then share those files/folders under a tag with certain users. This way a user would have all the files shared by me in only one folder.
Structure:
FolderaA/
* File1
* File2
* File3

FolderB/
* File4
* File5
* File6

If i want to share files1-2-4-6 with a user, now i've to do it for the 4 files. And the user will see:
Shared/
* File1
* File2
* File4
* File6

And those are only mine, with more from other users it would be worse.
But if I was able to tag those files and then share that tag it will be easier, for sharing with the same user(s) I only need to add the tag, and the user should see:

Shared/
      asieriko/
               * File1
               * File2
               * File4
               * File6
       OtherUser/

....
      
I hope I've explained well.

Thank you!

**Comment by oparoz** [comment] 2015-05-19 00:27
I agree, we need virtual folders.
You can join the discussion here:
https://github.com/owncloud/core/issues/3812

**Comment by MorrisJobke** [comment] 2015-05-19 07:07
I would close this as a duplicate of #3812

**Closed by MorrisJobke** 2015-05-19 07:07 UTC
Labels: enhancement, feature:tags

**Comment by asieriko** [comment] 2015-05-19 08:08
Thanks! I didn't find it.
