### ISSUE TITLE
Moving files: ability to undo

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#15174] opened 2015-03-24 21:28 UTC
Next to the notification of where the files were moved (see https://github.com/owncloud/core/issues/15173), it should be possible to undo the move if it was made accidentally.

cc @DeepDiver1975 @PVince81 @schiesbn

**Comment by jancborchardt** [comment] 2015-05-01 22:33
This relates to undo for deletion: https://github.com/owncloud/core/pull/15002

**Comment by PVince81** [comment] 2015-12-18 10:47
Duplicate of https://github.com/owncloud/core/issues/7058

**Closed by PVince81** 2015-12-18 10:47 UTC
Labels: 1 - To develop, app:files, design, enhancement
