### ISSUE TITLE
Redis Exception when upgrading to 8.2.1

### ISSUE THREAD

**Issue by Bubu** [owncloud/core#20572] opened 2015-11-18 13:26 UTC
System: ```Debian 7.9```
php: ```5.4.45-0+deb7u2```
php5-redis: ```2.2.5-1~bpo70+1```
redis-server: ```2:2.4.14-1```
apache: ``` 2.2.22-13+deb7u6```
mysql: ```5.5.46-0+deb7u1```

Config excerpt:
```
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
  ),
  'theme' => '',
  'maintenance' => true,
  'asset-pipeline.enabled' => true,
  'log_rotate_size' => 104857600,
```
The following appeared when executing ```occ upgrade```:
```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Set log level to debug - current level: 'Info'
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
RedisException: protocol error, got 'R' as reply type byte

Update failed
Maintenance mode is kept active
Reset log level to 'Info'
```

Log file:
```
{"reqId":"zpUGugavBRsRYQY4Eaas","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.0.12 to 8.2.1.4","level":0,"time":"2015-11-18T14:12:11+01:00","method":"--","url":"--"}
{"reqId":"zpUGugavBRsRYQY4Eaas","remoteAddr":"","app":"PHP","message":"file_put_contents(\/var\/www\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#456","level":3,"time":"2015-11-18T14:12:11+01:00","method":"--","url":"--"}
{"reqId":"zpUGugavBRsRYQY4Eaas","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"protocol error, got 'R' as reply type byte\\n\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php(74): Redis->get('eb7c5390a9882f5...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(150): OC\\\\Memcache\\\\Redis->get('OCP\\\\\\\\UserInterfa...')\\n#2 [internal function]: OC\\\\Autoloader->load('OCP\\\\\\\\UserInterfa...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_sql\\\/user_sql.php(35): spl_autoload_call('OCP\\\\\\\\UserInterfa...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_sql\\\/appinfo\\\/app.php(24): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(160): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(141): OC_App::requireAppFile('user_sql')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(436): OC_App::loadApp('user_sql', false)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(320): OC\\\\Updater->doAppUpgrade()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.2.0.12')\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/upgrade.php(213): OC\\\\Updater->upgrade()\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Command\\\/Command.php(253): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(874): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(195): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Symfony\\\/Component\\\/Console\\\/Application.php(126): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(97): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#16 \\\/var\\\/www\\\/owncloud\\\/console.php(69): OC\\\\Console\\\\Application->run()\\n#17 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php\",\"Line\":74}","level":3,"time":"2015-11-18T14:12:28+01:00","method":"--","url":"--"}
```

**Edit:** After trying ```occ upgrade``` again it completed with no errors.

**Comment by RealRancor** [comment] 2015-11-18 18:26
@karlitschek @nickvergessen Very likely a duplicate of https://github.com/owncloud/core/issues/20509

**Comment by nickvergessen** [comment] 2015-11-19 08:29
Closing as such

**Closed by nickvergessen** 2015-11-19 08:29 UTC
Labels: bug, comp:core
