### ISSUE TITLE
Filepicker: Can't select multiple files on Mac OS X

### ISSUE THREAD

**Issue by petermueller87** [owncloud/core#18282] opened 2015-08-13 13:11 UTC
Reopening #18228

https://github.com/owncloud/core/blob/eb13cb8d75634c0423dbcde4b0f55239c0dfb1e7/core/js/oc-dialogs.js#L720
### Steps to reproduce
1. Open the Filepicker using `OC.dialogs.filepicker`
2. Try to select multiple files on Mac OS X
3. It doesn't work. As Ctrl+click shows the browser's context menu on OS X, one should rely on another meta key to select multiple files instead.
### Expected behaviour

You should be able to select multiple files
### Actual behaviour

You can't select multiple files
### Client OS

Mac OS X
### ownCloud version

8.1

**Comment by LukasReschke** [comment] 2015-08-13 15:47
Which browser etc.?

**Comment by petermueller87** [comment] 2015-08-17 08:54
At least Chrome and Firefox are affected. I'm pretty sure __all__ browsers on OS X are affected.

**Comment by SergioBertolinSG** [comment] 2015-08-17 09:09
I've check this, oC 8.1 using firefox, works perfectly (also using the picker of files drop).
Perhaps the problem is that in OS X for selecting files the command is cmd+click instead of ctrl+click.

**Comment by Kawohl** [comment] 2015-10-08 09:50
I think i get it, 

multiple select only works if you click on the Icons, or Checkboxes in the Icons. This seems odd.
It should also work by clicking on the filename holding the cmd key.

![bildschirmfoto 2015-10-08 um 11 45 11](https://cloud.githubusercontent.com/assets/12275313/10363073/854a03b2-6db2-11e5-98d2-fb9253c5db2b.png)

Tested with Chrome, Firefox and Safari.

**Comment by SergioBertolinSG** [comment] 2015-10-08 10:45
For me that is not a bug, it is designed this way. For selecting elements you should click in the icon or checkbox, not in the name. That opens/downloads the file.

**Comment by Kawohl** [comment] 2015-10-08 11:29
It works as designed but i think it is misleading. 

I would expect from a multiselect to be able to click on the filenames or on the free space in the lines next to them. imho the current situation is a usability bug.

Also
Clicking on multiple files with the "command button" pressed works with both of our big Competitors and the majority of users is probably accustomed to this.

**Comment by jancborchardt** [comment] 2015-10-12 01:51
As @Kawohl said, we should support the Cmd+click shortcut for multiselect as is known from desktop file managers. cc @PVince81 @MorrisJobke

**Comment by petermueller87** [comment] 2015-11-19 11:59
Guys! I'm not talking about the file picker at /index.php/apps/files
I'm talking about the JavaScript file picker in core/js/oc-dialogs.js which can be opened via `OC.dialogs.filepicker`

**Comment by PVince81** [comment] 2015-11-19 12:43
@Kawohl there's another issue for shift on the regular file list: https://github.com/owncloud/core/issues/15157

**Comment by PVince81** [comment] 2017-04-06 11:05
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580

**Closed by PVince81** 2017-04-06 11:05 UTC
Labels: bug, design
