### ISSUE TITLE
[Fedora] Php-gd dependency isn't satisfied

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13944] opened 2015-02-06 12:27 UTC
### Steps to reproduce
Install owncloud package in Fedora 20:

cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:community:8.0/Fedora_20/isv:ownCloud:community:8.0.repo
yum install owncloud

### Expected behaviour
All dependencies are satisfied.

### Actual behaviour
Owncloud needs php-gd module and it wasn't installed/enabled with owncloud package.

**Comment by karlitschek** [comment] 2015-02-06 15:18
@jnweiger

**Comment by jnweiger** [comment] 2015-02-06 21:09
@SergioBertolinSG do you happen to know if php-gd is needed by core or needed by an app?
I'd like to move the dependency in the right place. 
Putting it in the main owncloud-server package for now.

Committed revision 72. project:isv:ownCloud:community:8.0

**Closed by jnweiger** 2015-02-06 21:09 UTC
Labels: packaging

**Comment by LukasReschke** [comment] 2015-02-06 21:12
> @SergioBertolinSG do you happen to know if php-gd is needed by core or needed by an app?

Everything in there is required by core: https://github.com/owncloud/core/blob/b4b45a1a521b68ac7931621af652055e1ce131e8/lib/private/util.php#L570-L595

**Comment by jnweiger** [comment] 2015-02-07 21:16
@LukasReschke Thanks for the pointer. This reminds me of https://github.com/owncloud/core/issues/13357 Should php-posix be listed in util.php too?

**Comment by LukasReschke** [comment] 2015-02-07 21:29
@jnweiger Posix is only a soft-dependency for the ownCloud command line utility – other parts of oC will still run without it. If we would add it there oC would be broken on a lot of platforms ;-)

**Comment by jnweiger** [comment] 2015-02-07 23:58
@LukasReschke I am testing against posix_getuid() on all Linux systems. Did not explode so far.
DEB systems include posix in php-common, RPM systems provide php-posix, which I require.

**Comment by LukasReschke** [comment] 2015-02-08 00:14
> DEB systems include posix in php-common, RPM systems provide php-posix, which I require.

Yup. But it would break support for any not linux distribution as well as a lot of webhosters. Those checks in util.php are enforced for all platforms :-)
(That's why the getuid check is also not running on Windows in console.php)

**Comment by jnweiger** [comment] 2015-02-08 18:26
@LukasReschke  Missing php-pdo causes a blank page and Class 'PDO' not found at /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php#172 errors.

That happened to me today, while trying to get scl-php54 right for centos6.

Is this a candidate for util.php check?

**Comment by LukasReschke** [comment] 2015-02-08 18:27
It is already there but the problem is that the dependency check is running pretty late in the bootstrapping process thus if a fatal error is encountered it will never even reach the check :-/

Let me see why this happens here … digging …

**Comment by SergioBertolinSG** [comment] 2015-02-10 09:40
Installed 8.0.0-9.1 version in fedora using package, working correct.
