### ISSUE TITLE
LDAP Default Quota doesn't get applied

### ISSUE THREAD

**Issue by winpat** [owncloud/core#23858] opened 2016-04-08 10:55 UTC
### Steps to reproduce
1. Set "Quota Default" Field  according to [documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_user/user_auth_ldap.html#special-attributes) to e.g. 16 GB
2. Login with a new LDAP User that **hasn't set a value in the ldap quota field**

### Expected behaviour
You should now see the specified quota when opening up the preferences in the webinterface.
```
You're using X of 16GB
```
### Actual behaviour
The default quota doesn't get applied, resulting in:
```
You're using X of $SizeOfTotalStorage
```
The quota was updated correctly in the "oc_appconfig" table.
```
mysql> select * from oc_appconfig where configkey="s01ldap_quota_def";
+-----------+-------------------+-------------+
| appid     | configkey         | configvalue |
+-----------+-------------------+-------------+
| user_ldap | s01ldap_quota_def | 16 GB       |
+-----------+-------------------+-------------+
1 row in set (0.01 sec)
```

However the "quota" configkey in the "oc_preferences" table is missing for the user
```
mysql> select * from oc_preferences where userid LIKE "user.test";
+---------------+-----------+------------------------+--------------------------------------+
| userid        | appid     | configkey              | configvalue                          |
+---------------+-----------+------------------------+--------------------------------------+
| user.test | core      | timezone               | Europe/Test                       |
| user.test | login     | lastLogin              | 1460112000                           |
| user.test | settings  | email                  | test@domain.com               |
| user.test | user_ldap | displayName            | test@domain.com               |
| user.test | user_ldap | firstLoginAccomplished | 1                                    |
| user.test | user_ldap | homePath               | /var/lib/owncloud/data/user.test |
| user.test | user_ldap | lastFeatureRefresh     | 1460112000                           |
| user.test | user_ldap | uid                    | user.test                        |
+---------------+-----------+------------------------+--------------------------------------+
8 rows in set (0.00 sec)
```

### Server configuration
**Operating system**: Debian 8.3 Jessie

**Web server:** Apache 2.4.10

**Database:** MySQL 

**PHP version:** PHP 5.6.17

**ownCloud version:** 8.2.2

**Updated from an older ownCloud Version**

**Installed from official ownCloud Repositories**

**Integrity check didn't return anything**

**List of activated apps:**
```
Enabled:
  - activity: 2.1.3
  - documents: 0.11.1
  - external: 1.2
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - notifications: 0.1.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - files_antivirus
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_videoviewer
  - firstrunwizard
  - gallery
  - provisioning_api
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "t23t23t23t2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "domain.com",
        "mail_smtpport": "25",
        "mail_smtphost": "mail.domain.com",
        "theme": "CUSTOM",
        "default_language": "de_DE",
        "enable_previews": true,
        "trashbin_retention_obligation": "5, auto",
        "enable_avatars": false,
        "allow_user_to_change_display_name": false,
        "check_for_working_htaccess": true,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe",
        "log_query": false,
        "log_authfailip": true,
        "log_rotate_size": false,
        "remember_login_cookie_lifetime": 0,
        "session_lifetime": 300,
        "maintenance": false,
        "singleuser": false,
        "knowledgebaseenabled": false,
        "ldapUserCleanupInterval": 48,
        "preview_max_filesize_image": 10,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "mail_from_address": "owncloud",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+----------------------------------------------------------------------+
| Configuration                 | s01                                                                  |
+-------------------------------+----------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                    |
| hasPagedResultSupport         |                                                                      |
| homeFolderNamingRule          | attr:uid                                                             |
| lastJpegPhotoLookup           | 0                                                                    |
| ldapAgentName                 | uid=user=users,dc=domain,dc=com                            |
| ldapAgentPassword             | ***                                                                  |
| ldapAttributesForGroupSearch  | cn                                                                   |
| ldapAttributesForUserSearch   | displayname;sn;uid                                                   |
| ldapBackupHost                | ldaps://ldapbackup.local                                    |
| ldapBackupPort                | 7636                                                                 |
| ldapBase                      | dc=domain,dc=com                                                       |
| ldapBaseGroups                | dc=domain,dc=com                                                       |
| ldapBaseUsers                 | dc=domain,dc=com                                                       |
| ldapCacheTTL                  | 15                                                                   |
| ldapConfigurationActive       | 1                                                                    |
| ldapEmailAttribute            | mailPrimaryAddress                                                   |
| ldapExperiencedAdmin          | 1                                                                    |
| ldapExpertUUIDGroupAttr       | gidNumber                                                            |
| ldapExpertUUIDUserAttr        | uidNumber                                                            |
| ldapExpertUsernameAttr        | uid                                                                  |
| ldapGroupDisplayName          | cn                                                                   |
| ldapGroupFilter               | (& (OwnCloudGroup=1)(objectClass=Group)) |
| ldapGroupFilterGroups         |                                                                      |
| ldapGroupFilterMode           | 0                                                                    |
| ldapGroupFilterObjectclass    |                                                                      |
| ldapGroupMemberAssocAttr      | uniqueMember                                                         |
| ldapHost                      | ldaps://ldapserver.local                                   |
| ldapIgnoreNamingRules         |                                                                      |
| ldapLoginFilter               | (& (!(shadowExpire=1)) (OwnCloud=1) (uid=%uid) )   |
| ldapLoginFilterAttributes     |                                                                      |
| ldapLoginFilterEmail          | 0                                                                    |
| ldapLoginFilterMode           | 0                                                                    |
| ldapLoginFilterUsername       | 1                                                                    |
| ldapNestedGroups              | 0                                                                    |
| ldapOverrideMainServer        |                                                                      |
| ldapPagingSize                | 20000                                                                |
| ldapPort                      | 7636                                                                 |
| ldapQuotaAttribute            | OwnCloudQuota                                      |
| ldapQuotaDefault              | 4 GB                                                                 |
| ldapTLS                       | 0                                                                    |
| ldapUserDisplayName           | mailprimaryaddress                                                   |
| ldapUserFilter                | (& (!(shadowExpire=1)) (ownCloud=1))               |
| ldapUserFilterGroups          |                                                                      |
| ldapUserFilterMode            | 0                                                                    |
| ldapUserFilterObjectclass     |                                                                      |
| ldapUuidGroupAttribute        | auto                                                                 |
| ldapUuidUserAttribute         | auto                                                                 |
| turnOffCertCheck              | 1                                                                    |
| useMemberOfToDetectMembership | 1                                                                    |
+-------------------------------+----------------------------------------------------------------------+
```

### Client configuration
**Browser:** Iceweasel 38.7 && Chromium 49.0

**Operating system:** Debian 8.3 Jessie

#### Web server error log
```
Empty (Except some ssl warnings)
```

#### ownCloud log (data/owncloud.log)
Syslog:
```
Apr  8 12:00:02 host ownCloud[12360]: {cli} Memcache \OC\Memcache\APCu not available for local cache
Apr  8 12:00:02 host ownCloud[12360]: {cli} Memcache \OC\Memcache\APCu not available for distributed cache
```

**Comment by PVince81** [comment] 2016-04-21 10:46
@winpat I assume you already waited 15-30 minutes for the LDAP sync to happen ?
You can also set the TTL to "60" temporarily to make it happen faster.

**Comment by PVince81** [comment] 2016-04-21 10:47
CC @blizzz

**Comment by blizzz** [comment] 2016-04-21 10:55
Also, can you update to the most recent 8.2.3 and check whether the issues happens there as well?

**Comment by winpat** [comment] 2016-04-23 20:22
@PVince81 I did wait up to 24 hours... however no luck.
AFAIK the LDAP Default Quota isn't set in LDAP itself, so lowering the Cache TTL won't help.

**Comment by PVince81** [comment] 2016-06-01 15:28
Confirmed broken on v8.2.2 and v8.2.5.

I have input the value string "600 MB" for the LDAP quota.

At what time does the quota apply ? The first time a new user from LDAP logs in ? Or at the time where the server discovers new users from LDAP ?

**Comment by PVince81** [comment] 2016-06-01 15:39
Hmmm, I was able to force it to refresh by doing this:
`delete from oc_preferences where configkey='lastFeatureRefresh';`

It seems every user has this key and it seems to be independent from the TTL (which I set to 60)

So I guess there must be a moment where the LDAP refresh will happen, not sure when that is. @blizzz

**Comment by PVince81** [comment] 2016-06-06 12:27
@winpat have the quotas still not appeared ?

**Comment by winpat** [comment] 2016-06-10 07:39
@PVince81 Sorry, we're currently in the process of updating ownCloud to 9.x. I'm unable to test your workaround anymore :-/

**Comment by PVince81** [comment] 2016-06-15 16:00
I'm closing this then. It looks like it works as expected, but with a delay.

**Closed by PVince81** 2016-06-15 16:00 UTC
Labels: app:user_ldap, bug, feature:quota, sev2-high
