### ISSUE TITLE
"undefined index" and "file_exists() on a non-object" messages OC 8.0.3

### ISSUE THREAD

**Issue by fbassas** [owncloud/core#16740] opened 2015-06-04 09:01 UTC
Environment: Virtual Machina in a XenServer 6.5
Server: ubuntu 14.04
Database:mysql 5.5
Client:1.8.1
OC-Version:8.0.3
PHP-Version: 5.5.9

I'm getting this messages periodically and seems related to cron job.

{"reqId":"caa1ab294f0a77d8ed752e0c3a14e8e9","remoteAddr":"","app":"PHP","message":"Undefined index: owner at \/var\/www\/owncloud\/lib\/private\/share\/hooks.php#64","level":3,"time":"2015-06-04T06:30:04+00:00"}
{"reqId":"caa1ab294f0a77d8ed752e0c3a14e8e9","remoteAddr":"","app":"PHP","message":"Call to a member function file_exists() on a non-object at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#630","level":3,"time":"2015-06-04T06:30:04+00:00"}

Our current OC comes from several upgrades and I'm afraid some indexes could be missing. Is there any way to check all indexes?

**Comment by fbassas** [comment] 2015-06-04 09:51
Also this email is sent sometimes after cron execution:

PHP Fatal error:  Call to a member function file_exists() on a non-object in /var/www/owncloud/lib/private/files/filesystem.php on line 630
Unexpected error!

**Comment by karlitschek** [comment] 2015-06-04 12:13
@icewind1991 Can you have a look?

**Comment by PVince81** [comment] 2015-06-15 09:40
@fbassas are you still seeing this with 8.0.4 ?
I vaguely remember some fixes that might be related to this.

**Comment by fbassas** [comment] 2015-06-15 10:45
Tanks for your comment @PVince81 
I didn't know 8.0.4 was out. I will try it tomorrow morning before users coming.

**Comment by RealRancor** [comment] 2015-06-15 16:23
@PVince81 At least cron seems to still throw this error on OC 8.0.4: https://github.com/owncloud/core/issues/16945

**Comment by belzebubek** [comment] 2015-06-15 16:26
Debian wheezy, ownCloud 8.0.4-0 stable.
Cron started to send me below messages, help would be appreciated:

PHP Fatal error: Call to a member function file_exists() on a non-object in /var/www/owncloud/lib/private/files/filesystem.php on line 630
PHP Stack trace:
PHP 1. {main}() /var/www/owncloud/cron.php:0
PHP 2. OC\BackgroundJob\TimedJob->execute() /var/www/owncloud/cron.php:138
PHP 3. OC\BackgroundJob\Job->execute() /var/www/owncloud/lib/private/backgroundjob/timedjob.php:38
PHP 4. OCA\user_ldap\lib\Jobs->run() /var/www/owncloud/lib/private/backgroundjob/job.php:36
PHP 5. OCA\user_ldap\lib\Jobs::updateGroups() /var/www/owncloud/apps/user_ldap/lib/jobs.php:43
PHP 6. OCA\user_ldap\lib\Jobs::handleKnownGroups() /var/www/owncloud/apps/user_ldap/lib/jobs.php:59
PHP 7. OCP\Util::emitHook() /var/www/owncloud/apps/user_ldap/lib/jobs.php:97
PHP 8. OC_Hook::emit() /var/www/owncloud/lib/public/util.php:365
PHP 9. call_user_func() /var/www/owncloud/lib/private/hook.php:78
PHP 10. OC\Share\Hooks::post_addToGroup() /var/www/owncloud/lib/private/hook.php:78
PHP 11. OC\Share\Helper::generateTarget() /var/www/owncloud/lib/private/share/hooks.php:64
PHP 12. OC_Share_Backend_File->generateTarget() /var/www/owncloud/lib/private/share/helper.php:74
PHP 13. OCA\Files_Sharing\Helper::getShareFolder() /var/www/owncloud/apps/files_sharing/lib/share/file.php:69
PHP 14. OC\Files\Filesystem::file_exists() /var/www/owncloud/apps/files_sharing/lib/helper.php:262
Unexpected error!

**Comment by fbassas** [comment] 2015-06-16 05:33
Confirmed. Still getting this error related to cron on 8.0.4

PHP Fatal error:  Call to a member function file_exists() on a non-object in /var/www/owncloud/lib/private/files/filesystem.php on line 630
Unexpected error!

**Comment by PVince81** [comment] 2015-06-16 07:56
@belzebubek thanks for the stack trace, it seems to be related to LDAP

@fbassas are you also using LDAP ?

@blizzz can you have a look ?

**Comment by fbassas** [comment] 2015-06-16 10:06
Yes, we use LDAP.

**Comment by MorrisJobke** [comment] 2015-06-16 11:26
@fbassas Can I ask you to provide an anonymized ldap config? `./occ ldap:show-config` should show you all relevant stuff.

**Comment by fbassas** [comment] 2015-06-16 11:52
Of course. Here it is:

$ php occ ldap:show-config
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                |                                                                                                                                                                                                                                                                                                                                                                |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport     |                                                                                                                                                                                                                                                                                                                                                                |
| hasPagedResultSupport        |                                                                                                                                                                                                                                                                                                                                                                |
| homeFolderNamingRule         |                                                                                                                                                                                                                                                                                                                                                                |
| lastJpegPhotoLookup          | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapAgentName                |
cn=smbldaptools,ou=DSA,dc=ct,dc=upc,dc=es                                                                                                                                                                                                                                                                                                                     |
| ldapAgentPassword            | ***                                                                                                                                                                                                                                                                                                                                                            |
| ldapAttributesForGroupSearch | cn                                                                                                                                                                                                                                                                                                                                                             |
| ldapAttributesForUserSearch  | uid;displayname                                                                                                                                                                                                                                                                                                                                                |
| ldapBackupHost               | ldap-----------------------                                                                                                                                                                                                                                                                                                                                    |
| ldapBackupPort               | 636                                                                                                                                                                                                                                                                                                                                                            |
| ldapBase                     | dc=ct,dc=upc,dc=es                                                                                                                                                                                                                                                                                                                                             |
| ldapBaseGroups               | ou=Groups,dc=ct,dc=upc,dc=es                                                                                                                                                                                                                                                                                                                                   |
| ldapBaseUsers                | ou=Users,dc=ct,dc=upc,dc=es                                                                                                                                                                                                                                                                                                                                    |
| ldapCacheTTL                 | 600                                                                                                                                                                                                                                                                                                                                                            |
| ldapConfigurationActive      | 1                                                                                                                                                                                                                                                                                                                                                              |
| ldapEmailAttribute           | mail                                                                                                                                                                                                                                                                                                                                                           |
| ldapExperiencedAdmin         | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapExpertUUIDGroupAttr      |                                                                                                                                                                                                                                                                                                                                                                |
| ldapExpertUUIDUserAttr       |                                                                                                                                                                                                                                                                                                                                                                |
| ldapExpertUsernameAttr       |                                                                                                                                                                                                                                                                                                                                                                |
| ldapGroupDisplayName         | cn                                                                                                                                                                                                                                                                                                                                                             |
| ldapGroupFilter              | (&(|(objectclass=posixGroup))(|(cn=cd6)(cn=plataforma)(cn=370-cpermanent)(cn=370-junta)(cn=370-direccio)(cn=370-sict)(cn=ac)(cn=sbasics)(cn=labson)(cn=intexter)(cn=sict)(cn=sict220)(cn=sict320)(cn=sict370)(cn=sictserveis)(cn=noupc)(cn=som)(cn=som170)(cn=telematica)(cn=telesom)(cn=biblioteca)(cn=ugct)(cn=ec)(cn=mmt)(cn=direccio-ct)(cn=fen)(cn=ugt))) |
| ldapGroupFilterGroups        | cd6;plataforma;sbasics;sict;sict220;sict320;sict370;sictserveis;som;som170;telematica;telesom;ugct;ugt                                                                                                                                                                                                                                                         |
| ldapGroupFilterMode          | 1                                                                                                                                                                                                                                                                                                                                                              |
| ldapGroupFilterObjectclass   | posixGroup                                                                                                                                                                                                                                                                                                                                                     |
| ldapGroupMemberAssocAttr     | memberUid                                                                                                                                                                                                                                                                                                                                                      |
| ldapHost                     | ldaps://ldap-ct.upc.edu                                                                                                                                                                                                                                                                                                                                        |
| ldapIgnoreNamingRules        |                                                                                                                                                                                                                                                                                                                                                                |
| ldapLoginFilter              | (&(objectclass=inetOrgPerson)(|(uid=%uid)(|(uid=%uid))))                                                                                                                                                                                                                                                                                                       |
| ldapLoginFilterAttributes    | uid                                                                                                                                                                                                                                                                                                                                                            |
| ldapLoginFilterEmail         | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapLoginFilterMode          | 1                                                                                                                                                                                                                                                                                                                                                              |
| ldapLoginFilterUsername      | 1                                                                                                                                                                                                                                                                                                                                                              |
| ldapNestedGroups             | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapNoCase                   | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapOverrideMainServer       | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapPagingSize               | 500                                                                                                                                                                                                                                                                                                                                                            |
| ldapPort                     | 636                                                                                                                                                                                                                                                                                                                                                            |
| ldapQuotaAttribute           | ownCloudQuota                                                                                                                                                                                                                                                                                                                                                  |
| ldapQuotaDefault             | 2 G                                                                                                                                                                                                                                                                                                                                                            |
| ldapTLS                      | 0                                                                                                                                                                                                                                                                                                                                                              |
| ldapUserDisplayName          | uid                                                                                                                                                                                                                                                                                                                                                            |
| ldapUserFilter               | (&(objectclass=inetOrgPerson)(!(sambaAcctFlags=[DUX]))(!(gidNumber=1079)))                                                                                                                                                                                                                                                                                     |
| ldapUserFilterGroups         |                                                                                                                                                                                                                                                                                                                                                                |
| ldapUserFilterMode           | 1                                                                                                                                                                                                                                                                                                                                                              |
| ldapUserFilterObjectclass    | inetOrgPerson                                                                                                                                                                                                                                                                                                                                                  |
| ldapUuidGroupAttribute       | auto                                                                                                                                                                                                                                                                                                                                                           |
| ldapUuidUserAttribute        | auto                                                                                                                                                                                                                                                                                                                                                           |
| turnOffCertCheck             | 0                                                                                                                                                                                                                                                                                                                                                              |
+------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
+------------------------------+--------------------------------------------+
| Configuration                | s01                                        |
+------------------------------+--------------------------------------------+
| hasMemberOfFilterSupport     | 0                                          |
| hasPagedResultSupport        |                                            |
| homeFolderNamingRule         |                                            |
| lastJpegPhotoLookup          | 0                                          |
| ldapAgentName                | cn=smbldap-too------------- |
| ldapAgentPassword            | ***                                        |
| ldapAttributesForGroupSearch |                                            |
| ldapAttributesForUserSearch  |                                            |
| ldapBackupHost               |                                            |
| ldapBackupPort               |                                            |
| ldapBase                     | dc=--------------                         |
| ldapBaseGroups               |                                            |
| ldapBaseUsers                |                                            |
| ldapCacheTTL                 | 600                                        |
| ldapConfigurationActive      | 0                                          |
| ldapEmailAttribute           |                                            |
| ldapExperiencedAdmin         | 0                                          |
| ldapExpertUUIDGroupAttr      |                                            |
| ldapExpertUUIDUserAttr       |                                            |
| ldapExpertUsernameAttr       |                                            |
| ldapGroupDisplayName         | cn                                         |
| ldapGroupFilter              |                                            |
| ldapGroupFilterGroups        |                                            |
| ldapGroupFilterMode          | 0                                          |
| ldapGroupFilterObjectclass   |                                            |
| ldapGroupMemberAssocAttr     | uniqueMember                               |
| ldapHost                     | ldaps://ldap--------------                    |
| ldapIgnoreNamingRules        |                                            |
| ldapLoginFilter              |                                            |
| ldapLoginFilterAttributes    |                                            |
| ldapLoginFilterEmail         | 0                                          |
| ldapLoginFilterMode          | 0                                          |
| ldapLoginFilterUsername      | 1                                          |
| ldapNestedGroups             | 0                                          |
| ldapNoCase                   | 0                                          |
| ldapOverrideMainServer       |                                            |
| ldapPagingSize               | 500                                        |
| ldapPort                     | 636                                        |
| ldapQuotaAttribute           |                                            |
| ldapQuotaDefault             |                                            |
| ldapTLS                      | 0                                          |
| ldapUserDisplayName          | displayname                                |
| ldapUserFilter               |                                            |
| ldapUserFilterGroups         |                                            |
| ldapUserFilterMode           | 0                                          |
| ldapUserFilterObjectclass    |                                            |
| ldapUuidGroupAttribute       | auto                                       |
| ldapUuidUserAttribute        | auto                                       |
| turnOffCertCheck             | 0                                          |
+------------------------------+--------------------------------------------+

**Comment by cmonteroluque** [comment] 2015-06-25 22:38
@blizzz can you check this please?

**Comment by blizzz** [comment] 2015-06-30 16:13
@belzebubek thank you for the backtrace, that's very helpful as I would not know how to reproduce.

> PHP 7. OCP\Util::emitHook() /var/www/owncloud/apps/user_ldap/lib/jobs.php:97

Tells us that a new LDAP user was found in a group and an according hook was emitted for sharing to act on it. Sharing caught it, proceeded on it  and subsequently ran the file_exists check when generating a new target. Or so. I need to reproduce it and debug, at least  i have a little idea what the conditions are.

Meanwhile, @schiesbn does anything look strange?

**Comment by schiesbn** [comment] 2015-06-30 17:37
I didn't try to re-rpdouce it but by looking at the code I have a idea. https://github.com/owncloud/core/blob/master/lib/private/share/hooks.php#L66, here we get a undefined index 'owner', by looking at the database the column is called 'uid_owner'. Maybe by replacing all the ````$item['owner']```` with ````$item['uid_owner']```` would already solve the problem.

@blizzz if you can re-produce it, can you try my suggestion solves the problem?

**Comment by blizzz** [comment] 2015-07-01 16:19
@schiesbn in that case it should be possible to  reproduce it with local users as well. gonna try.

**Comment by blizzz** [comment] 2015-07-01 16:48
@schiesbn I created two local users and put them in a group, shared a file with that group, and added another user to that group. In the assumption to reproduce it,  but I could not. Actually that code path was not  followed. post_addToGroup does not appear to be called at all, although  the share is updated properly (tried this on master though).

**Comment by schiesbn** [comment] 2015-07-01 18:26
At the moment I'm also not sure how to re-produce it. That's why I asked you @blizzz to test my idea in case you can reproduce it.

I will try to find a way tomorrow

**Comment by blizzz** [comment] 2015-07-01 19:31
Yeah, that's what I attempted. Are there different ways to update shares?

**Comment by blizzz** [comment] 2015-07-01 19:58
Tried with  8.0.4 and it was not reproducible like this either. 

To me it looks like the hook is never caught via user management.

So, after some more tests, I have as small script that I put  into  my root dir:

```
<?php

require_once 'lib/base.php';
\OC_App::loadApps('filesystem');

\OC\Share\Hooks::post_addToGroup(['uid' => 'jana', 'gid' => 'botschaft']);
```

(replace user and group id to  your test users)

In the hooks file I let $item write into  a file. Your assumption turns out right, there is no 'owner', but 'uid_owner':

```
Array
(
    [id] => 6
    [share_type] => 1
    [share_with] => botschaft
    [uid_owner] => stable8
    [parent] => 
    [item_type] => file
    [item_source] => 219
    [item_target] => /219
    [file_source] => 219
    [file_target] => /lxc.html
    [permissions] => 19
    [stime] => 1435779318
    [accepted] => 0
    [expiration] => 
    [token] => 
    [mail_send] => 0
)
```

The else branch was not executed so i did not run into the error,  but that should not make any difference.  Also later "uid_owner" is used: https://github.com/owncloud/core/blob/v8.0.3/lib/private/share/hooks.php#L78

My conclusions:

1. @schiesbn is right,  the index is "uid_owner", not "owner"
2. The hook is not  executed while it should in theory (user management)

My questions about 2.:

1. This does not need to seem necessary at all anymore?
2. The LDAP backend checks groups membership regularly and throws hooks if necessary. When 1 is true, it means we would not need to do it either, anymore?

**Comment by schiesbn** [comment] 2015-07-02 08:43
Hm, the hook is registered here: https://github.com/owncloud/core/blob/v8.0.3/lib/base.php#L710. The question is why the user management no longer emit the hooks? Was it lost during the last re-design of the user management?

I'm not sure if the method is still needed. It makes sure that if the new user gets a unique target for the group share if needed. For file sharing this is no longer necessary, we check the mount point every time we mount a share and generate a unique target if needed https://github.com/owncloud/core/blob/v8.0.3/apps/files_sharing/lib/sharedmount.php#L25 but most likely it is still needed for contacts and calendar.

Personally I prefer the solution implemented for files. I think it makes much more sense in creating unique targets on demand instead of checking it for all users on every share or group changes. But this needs to be implemented for contacts and calendar first... Probably something for the next sharing clean-up round.

Completely independent from that. I will prepare a pull request which fixes the index and we should check why the user management no longer emit this hook, maybe other apps also rely on this hook? @blizzz can you check the user management? Afaik you already worked on it in the past.

**Comment by blizzz** [comment] 2015-07-02 11:17
@schiesbn as I followed the code yesterday,  the user management throws the hook. I will verify however, and check what goes wrong.

**Comment by blizzz** [comment] 2015-07-02 11:49
Eureka! The method was registered to listen to the wrong class/sender. While i am  pretty sure it was correct,  once upon a time.

**Comment by blizzz** [comment] 2015-07-02 11:51
I.e. OC_User was changed to OC_Group somewhere along the way, but not everywhere. Which is nasty. Especially wrt 3rd party apps.

**Comment by blizzz** [comment] 2015-07-02 13:50
post_removeFromGroup still goes with OC_User, and also post_deleteGroup still runs with that. 

It is a mess, I tend to bring post_addToGroup back to OC_User.

@schiesbn do you mind adding

```diff
diff --git a/lib/private/server.php b/lib/private/server.php
index 6a65895..98cf32e 100644
--- a/lib/private/server.php
+++ b/lib/private/server.php
@@ -149,7 +149,7 @@ class Server extends SimpleContainer implements IServerContainer {
                \OC_Hook::emit('OC_Group', 'pre_addToGroup', array('run' => true, 'uid' => $user->getUID(), 'gid' => $group->getGID()));
            });
            $groupManager->listen('\OC\Group', 'postAddUser', function (\OC\Group\Group $group, \OC\User\User $user) {
-               \OC_Hook::emit('OC_Group', 'post_addToGroup', array('uid' => $user->getUID(), 'gid' => $group->getGID()));
+               \OC_Hook::emit('OC_User', 'post_addToGroup', array('uid' => $user->getUID(), 'gid' => $group->getGID()));
            });
            return $groupManager;
        });
```

to your  PR, to make the hooks work again?

**Comment by schiesbn** [comment] 2015-07-02 13:52
@blizzz I will add it to my PR. Thanks for debugging it!

**Comment by MorrisJobke** [comment] 2015-07-02 21:27
This was only fixed in master. backports pending.

**Comment by SergioBertolinSG** [comment] 2015-07-03 07:36
Can we have some steps to reproduce here?

**Comment by schiesbn** [comment] 2015-07-03 09:38
@SergioBertolinSG It is not that easy to reproduce the original bug report because there it get triggered by some cron job.

But something like this should work:

- create admin, user2 and user3
- add user2 to group "users"
- admin shares a file test.txt with the group "users"
- login as user3
- user3 also creates a test.txt
- admin adds user3 to the group "users"

Now check the oc_share table in the database. With this patch you should see a extra row for the group share for user3 with a target "test.txt (2)" or similar because we created a unique name for him. Without this patch the unique name will not be created. On stable7 you might even see a error message directly after adding user3 to the group.

Note: It is important that you check the db directly after adding user3 to the group. If user3 log-in we will detect the name collision and create a unique target for him. So after login everything will look the same with or without the patch.

**Comment by schiesbn** [comment] 2015-07-03 10:02
@SergioBertolinSG I just tried it... The steps above doesn't work. Let me try to come up with some other steps

**Comment by MorrisJobke** [comment] 2015-07-17 11:55
Backports are merged -> closing this

**Closed by MorrisJobke** 2015-07-17 11:55 UTC
Labels: 8.0.6-current, 8.1.1-current, app:user_ldap, bug, sev1-critical, sharing, triage

**Comment by jvillafanez** [comment] 2015-07-20 07:59
We'll need steps to reproduce at some point in order to validate this :sweat:
