### ISSUE TITLE
Sharing folder with other local users takes too much time (> 1 minute)

### ISSUE THREAD

**Issue by DaDenniX** [owncloud/core#19488] opened 2015-09-30 21:27 UTC
Hi there,

this issue is similar to this one: #19370 and #19372 

### Steps to reproduce
1. Create a folder and upload at least 1 file with at least 1 MB
2. Share a folder (or file) with another local user on the same OC domain

### Expected behaviour
Sharing a folder should be done in a few seconds

### Actual behaviour
Sharing a folder to local users takes too long (> 1 minute). Removing the user takes too long, too.

### Server configuration
**Operating system**: Debian 7.8
**Web server:** Apache 2.2.22
**Database:** MySQL 5.5.43
**PHP version:** PHP 5.4.41
**ownCloud version:** 8.1.3
**Updated from an older ownCloud or fresh install:** Updated from OC 8.1.0 (8.1.0 was a fresh install. 8.1.0 is/was affected also from this issue).
**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - encryption: 1.0.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '*********',
  'passwordsalt' => '*********',
  'secret' => '*********',
  'trusted_domains' => 
  array (
    0 => 'cloud.*********',
    1 => 'owncloud.*********',
  ),
  'datadirectory' => '/home/www/cloud.*********/httpdocs/data',
  'overwrite.cli.url' => 'https://cloud.*********',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => '*********',
  'logtimezone' => 'UTC',
  'installed' => true,
  'enable_previews' => true,
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'preview_max_scale_factor' => 10,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'no-reply',
  'mail_domain' => '*********',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '*********',
  'mail_smtpport' => '465',
  'mail_smtpname' => '************',
  'mail_smtppassword' => '******',
  'loglevel' => 3,
  'asset-pipeline.enabled' => true,
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Google Chrome Version 45.0.2454.93 (64-bit)
**Operating system:** Linux Mint 17
- client configuration doesn't matter, it affects all clients

#### ownCloud log (data/owncloud.log)
the following error is shown up when sharing a folder:
{"reqId":"*****","remoteAddr":"*******","app":"PHP","message":"Array to string conversion at \/home\/www\/cloud.********\/httpdocs\/core\/ajax\/share.php#311","level":3,"time":"2015-09-30T20:57:48+00:00"}

thanks for having a look.
cheers,
dennis

**Comment by PVince81** [comment] 2015-10-02 06:23
How many users have access to that share ?
From what I know it will regenerate all the share keys every time users are added/removed.

@schiesbn

**Comment by stormsh** [comment] 2015-10-02 15:31
At my share its just 2 or 3 that have access to the same folder. But the folder(s) has/have 500+ files which explains why it takes so long when oc has to generate all keys new.

**Comment by schiesbn** [comment] 2015-10-05 09:25
duplicate of https://github.com/owncloud/core/issues/18359

Please follow up there, thanks!

**Closed by schiesbn** 2015-10-05 09:25 UTC
Labels: app:encryption, bug, performance, sharing

**Comment by DaDenniX** [comment] 2015-10-05 09:33
ah, perfect. Thanks! :+1:
