### ISSUE TITLE
Integrity checker: exclude .webapp file

### ISSUE THREAD

**Issue by GreatEmerald** [owncloud/core#24218] opened 2016-04-23 16:02 UTC
Currently, the integrity checker complains when there is a .webapp file in the root of the OwnCloud installation directory. This file is generated, and required, by the webapp-config tool used to install all web apps on Gentoo.
### Steps to reproduce
1. Install OwnCloud using webapp-config into the root of a subdomain (suggested method):

``` bash
webapp-config -h cloud.example.com -d / -I owncloud 9.0.0
```
### Expected behaviour

The integrity checker should not complain.
### Actual behaviour

The integrity checker gives the following error:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - EXTRA_FILE
        - .webapp

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```
### Server configuration

**Operating system**: Gentoo Linux

**Web server:** nginx 1.8.1

**Database:** MariaDB 10.0.23

**PHP version:** 5.6.20

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** webapp-config

**Signing status (ownCloud 9.0 and above):** see above

**Comment by RealRancor** [comment] 2016-04-23 16:14
In https://github.com/owncloud/core/pull/22756#issuecomment-199016878 @akhokhlushin has referred two two files created by that tool?

**Comment by GreatEmerald** [comment] 2016-04-23 16:26
Hm, that's true:
```bash
$ ls -a
.             core              lib           settings
..            cron.php          occ           status.php
3rdparty      data              ocs           themes
apps          db_structure.xml  ocs-provider  updater
AUTHORS       .htaccess         public.php    .user.ini
config        index.html        remote.php    version.php
console.php   index.php         resources     .webapp
COPYING-AGPL  l10n              robots.txt    .webapp-owncloud-9.0.0
```

I'm not sure why the integrity log doesn't list the second one. But both should be excluded, in any case.

**Comment by noci2012** [comment] 2016-05-22 20:47
I second that request.

**Comment by jaakristioja** [comment] 2016-06-03 18:02
As a temporary workaround, is it possible to make the ownCloud integrity check ignore certain extra files or all extra files?

**Comment by rsa4046** [comment] 2016-06-12 15:43
I have near identical results as @GreatEmerald:
    Technical information
	=====================
	The following list covers which files have failed the integrity check. Please read
	the previous linked documentation to learn more about the errors and how to fix
	them.

	Results
	=======
	- core
		- EXTRA_FILE
			- .webapp

	Raw output
	==========
	Array
	(
	    [core] => Array
	        (
	            [EXTRA_FILE] => Array
	                (
	                    [.webapp] => Array
	                        (
	                            [expected] => 
	                            [current] => 
	                        )

	                )

	        )

	)

OS:	Funtoo/Gentoo Linux 4.6.1-gentoo #1 SMP
Webserver:	apache (2.4.20)
Database:	mysql (5.6.30)
PHP (5.5.36/7.0.7)
owncloud (9.0.2)

**Comment by RealRancor** [comment] 2016-06-12 18:58
@rsa4046 Well, this issue is still open so its normal that you're getting the same result.

To exclude the .webapp folder anyone is welcome to create a Pull Request with the .webapp folder added to this file:

https://github.com/owncloud/core/blob/v9.0.2/lib/private/integritycheck/iterator/excludefilebynamefilteriterator.php#L41

**Comment by RealRancor** [comment] 2016-07-11 10:23
Fix will be included in oC 9.1: https://github.com/owncloud/core/issues/25184

**Comment by DeepDiver1975** [comment] 2016-07-11 10:46
thx @RealRancor

**Comment by kaindl** [comment] 2016-08-11 01:50
@GreatEmerald wondered, why only one of the webapp-files was shown in the result.. Now, after the "fix", the first one is gone, but the other appeared :(
Could you reopen the issue?
```
Results
=======
- core
	- EXTRA_FILE
		- .webapp-owncloud-9.1.0

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp-owncloud-9.1.0] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```

**Comment by GreatEmerald** [comment] 2016-08-11 09:23
Yea, looks like the commit only took care of one file, not both.
But I don't seem to have a way to reopen this issue, sorry.

**Comment by kaindl** [comment] 2016-08-11 14:33
This seems more complicated to me, than I thought..
We can't just have .webapp*, because it is compared with `in_array`, so it does only look for exact matches..
As the file contains the version number, I don't think it would be reasonable to put the exact filename into the list, as it would have to be changed in every release.. :(

**Comment by okias** [comment] 2016-09-17 00:25
Why am I seeing : ?
> - core
>	- EXTRA_FILE
>		- .webapp-nextcloud-10.0.0

**Comment by RealRancor** [comment] 2016-09-17 06:23
See https://github.com/owncloud/core/issues/24218#issuecomment-239179096

**Comment by PVince81** [comment] 2016-10-24 09:38
would also be useful for zfs snapshots as reported here https://github.com/owncloud/core/issues/26400

**Comment by PVince81** [comment] 2016-10-24 18:29
another report for adding exceptions: https://github.com/owncloud/core/issues/26467
but also for adding a FAQ entry

**Comment by arr0n** [comment] 2016-10-24 18:42
have no idea why @PVince81 add #26467 as duplicate of this, its nothing like this at all.

**Comment by PVince81** [comment] 2016-10-24 18:45
@arr0n okay sorry, must be another one. There's a ticket about "allow excluding arbitrary files".
Let me search again...

**Comment by PVince81** [comment] 2016-10-24 18:46
here we go: https://github.com/owncloud/core/issues/23186

Will relink the original ticket.

**Closed** 2016-12-07 08:33 UTC
Labels: enhancement, feature:code-signing-integrity
