### ISSUE TITLE
Action menu in Files is unreachable when at the bottom of the screen

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#18830] opened 2015-09-04 11:32 UTC
### Steps to reproduce
1. Open a folder containing more images that the viewport
2. Click on the action menu of the last item
### Expected result

Interface scrolls up and menu items are reachable
### Actual result

Menu items are not reachable

@jancborchardt @PVince81

**Comment by jancborchardt** [comment] 2015-09-08 11:16
Can not reproduce. There is whitespace at the bottom of the list for this purpose:
![capture du 2015-09-08 13-15-29](https://cloud.githubusercontent.com/assets/925062/9733458/c219e0bc-562b-11e5-8584-89ec742f41e3.png)

**Comment by oparoz** [comment] 2015-09-08 11:58
Of course, if you go all the way down and then click, you won't have the problem, but take a normal use case, where the row is near the bottom.

**Comment by jancborchardt** [comment] 2015-09-08 12:37
Right, it should move down a bit. Needs to animate though since otherwise the interface moves around in ways not expected.

**Comment by oparoz** [comment] 2015-09-08 15:16
You can re-use the closed PR I did for the share dialogue which had the exact same problem :)

**Comment by oparoz** [comment] 2015-09-08 15:17
https://github.com/owncloud/core/pull/15817

**Comment by jancborchardt** [comment] 2015-09-08 19:17
@oparoz can you adjust it and open a new pull request? :)

**Comment by PVince81** [comment] 2015-09-14 18:27
It almost looks like we need some kind of library or reusable code for any dropdowns instead of having each dropdown implement its own positioning logic.

**Comment by oparoz** [comment] 2015-09-14 19:08
I agree. Looking at the method I wrote, it seems it could take the element to watch and the element to scroll into view as arguments. Maybe it should live in js.js?

**Comment by cmonteroluque** [comment] 2015-10-01 19:59
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment] 2015-10-05 14:46
I just tried to build a generic "move this menu into view" that would work for any menu but it cannot work reliably because every menu can be built differently. Some inside the body, some inside the row... makes everything quite complicated.

Let's have a look at @oparoz's approach instead.

**Comment by individual-it** [comment] 2017-03-17 08:57
here a PR to solve this #27404
Please review

**Closed** 2017-03-28 07:27 UTC
Labels: app:files, bug, regression, sev3-medium
