### ISSUE TITLE
Recovery key is not updated after updating file content

### ISSUE THREAD

**Issue by mike-troms2468** [owncloud/core#20942] opened 2015-12-04 09:27 UTC
Steps to reproduce:
0. encryption & recovery feature are enabled
1. create a new group: groupA
2. create a group admin: groupA_admin
3. create a group user: groupA_user1
4. groupA_admin create a text file named file1.txt & give it some text content & enable public link sharing & share with groupA users & save
5. fileKey, shareKey created (including shareKey for public link sharing and recovery)
6. groupA_user1 updates the file

Excepted behaviour
after file update by groupA_user1, fileKey and all shareKey should be updated

Actual behaviour
All key files updated except the one for recovery. Then, after ownCloud admin changing groupA_admin's password using recovery feature successfully, file1.txt content is all gibberish and encrypted text.

Server configuration

Operating system:
RHEL6

Web server:
Apache 2

Database:
MySQL

PHP version:
5.4.4

ownCloud version:
8.1.3

**Comment by PVince81** [comment] 2015-12-04 10:08
I cannot reproduce this issue following your steps. After changing the password, "groupA_admin" is still able to read "test1.txt"

However you seem to have missed something: after creating the users, you need to login as "groupA_admin" and "user1" and go to the personal page and click "Enable recovery".

CC @schiesbn

**Comment by mike-troms2468** [comment] 2015-12-04 10:22
I did login groupA_admin after users creation but not for groupA_user1. And also I enabled recovery after login as groupA_admin.

I just get off work so I need to retest the scenario on coming Monday morning. Thanks for your reply, dude.

**Comment by PVince81** [comment] 2015-12-04 10:29
I'll close this then. If it doesn't work when enabling recovery for all users, feel free to reopen.
Thanks!

**Closed by PVince81** 2015-12-04 10:29 UTC
Labels: app:encryption, bug, needs info

**Comment by mike-troms2468** [comment] 2015-12-07 03:30
After retest, it works when enabling recovery for all users (i.e. groupA_admin and groupA_user1). However, the file belongs to groupA_admin, why enabling recovery for groupA_user1 is a must? Thanks

**Comment by PVince81** [comment] 2015-12-07 09:31
Recovery is an opt-in feature for users. This was originally designed mostly because every user needs to decide whether they agree that the admin can potentially access their files through the recovery key.

However some might say that this doesn't fit all use cases, so have a look at https://github.com/owncloud/core/issues/11948 which suggests having a way to enabling the recovery key automatically.
