### ISSUE TITLE
[Sidebar][Versions] 500 Internal Server Error is shown trying to restore a version of a deleted file.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19403] opened 2015-09-28 10:33 UTC
### Steps to reproduce

1. Create a file, edit and save it
2. Edit it again and save (a new file version is created)
3. Click on share icon (sidebar is shown)
4. Move the file to the trashbin
5. Restore a version of the file

### Expected behaviour
It should not be possible to restore a version of the deleted file.

### Actual behaviour
A 500 Internal Server Error is shown.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-28T03:08:56+00:00 fe54d76e3dd047876847cebb63ed469c3273cf0a

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

**Comment by PVince81** [comment] 2015-09-28 10:51
You probably still had the sidebar open with the old file information before deleting ?

This PR https://github.com/owncloud/core/pull/19365 will de-highlight the sidebar contents as soon as the file disappears, which should make it impossible to touch versions for that file.

**Comment by davitol** [comment] 2015-09-28 10:54
@PVince81 Yes, I still had the sidebar open, so as you said the PR #19365  will solve the problem

**Comment by PVince81** [comment] 2015-09-28 11:05
Don't test it yet, there is a discussion in progress about details.
Let's keep this ticket here to verify later after it has been merged.

**Comment by schiesbn** [comment] 2015-10-01 09:28
There is a similar error if you try to restore a versions twice. After a version was restored we should update the versions list. The restored version should no longer be in the list instead we should add the new version created during restore.

Should we track this here or should I create a independent issue for it?

**Comment by PVince81** [comment] 2015-10-01 09:36
@schiesbn the versions list should already re-render automatically. If it doesn't then it's a bug.

**Comment by PVince81** [comment] 2015-10-01 09:36
@schiesbn separate issue please.

This ticket here is about restoring a version while being inside the trashbin (where the sidebar still focusses on the deleted file)

**Comment by PVince81** [comment] 2015-10-01 09:37
@davitol please retest master, you should not be able to reproduce this issue any more.

**Comment by davitol** [comment] 2015-10-01 09:47
:+1: WFM, now the behaviour is to hide the sideba after deleting a file

**Comment by PVince81** [comment] 2015-10-01 09:55
> now the behaviour is to hide the sideba after deleting a file

@davitol cannot reproduce. Please raise a separate ticket with details steps. Thanks

**Closed by PVince81** 2015-10-01 09:55 UTC
Labels: app:files_trashbin, app:files_versions, approved by qa, bug, feature:sidebar, sev2-high
