### ISSUE TITLE
Cannot restore versions for single file share when source located in subdir

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31681] opened 2018-06-07 13:59 UTC
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create folder "test"
1. Create file "test/test.txt" with web UI text editor
1. Edit several times and close it for saving. This will create multiple versions
1. Share "test/test.txt" with "user2"
1. Login as "user2"
1. Open the versions panel for "test.txt"
1. Try restoring any version

### Expected result
Version restored

### Actual result
Error message saying unable to restore version.
Nothing in logs.

### Versions
ownCloud 10.0.8 and stable10 baba1201654c00fee98e7d733b48e2b2680d2e9d

**Comment by PVince81** [comment] 2018-06-07 14:00
@phil-davis's PR to add tests to reproduce the issue: https://github.com/owncloud/core/pull/31680

**Comment by PVince81** [comment] 2018-06-07 14:02
also broken in 10.0.5 (randomly picked old version)

**Comment by PVince81** [comment] 2018-06-07 14:06
Seems to be fixed on https://github.com/owncloud/core/pull/31050, this is the object store backport branch which contains changes and fixes for versions. We cannot deliver this PR as a quick patch.

**Comment by PVince81** [comment] 2018-06-07 14:08
So we have a dilemma now:

1) Let the customer wait for 10.0.9 in which the problem is fixed. No patch possible as it's a huge change in the versions API / code. This doesn't qualify as a fast fix.

or

2) Invest extra time to provide a throwaway patch that is specific to 10.0.8.

Considering that this is only p3 I'd rather go for 1.

Before communicating anything let's wait for the PR to be merged and @phil-davis's tests to confirm the fix.

**Comment by phil-davis** [comment] 2018-06-07 14:27
PR #31680 just tests API endpoints. Maybe the webUI still has a problem (maybe it uses some other endpoint underneath) so that needs to be checked also.

**Comment by phil-davis** [comment] 2018-06-08 16:10
Confirmed (by manual testing) fixed in ``master`` an #31050 backport of objectstore changes. Only current ``stable10`` has the issue.

**Comment by PVince81** [comment] 2018-07-17 12:56
@phil-davis should be solved now on 10.0.9, close ?

**Comment by phil-davis** [comment] 2018-07-17 15:16
@individual-it can you test this instable10 or 10.0.9 release?
If not then assign me to check it next week.

**Comment by individual-it** [comment] 2018-07-19 03:41
tested on current stable10 branch and it works

**Comment by individual-it** [comment] 2018-07-19 04:06
what kind of tests do we want to write, looks like we have API tests https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/dav-versions.feature#L133 but I cannot see any UI tests for file versions, only trashbin restores

**Comment by phil-davis** [comment] 2018-07-19 10:24
There are no files versions UI tests yet. We could make a separate issue for remaining areas that need UI tests. And close thisvspecigic issue.

**Comment by individual-it** [comment] 2018-07-23 09:47
opened a new issue for UI tests here #32124

**Closed by individual-it** 2018-07-23 09:47 UTC
Labels: bug, p3-medium
