### ISSUE TITLE
Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in filesystem.php

### ISSUE THREAD

**Issue by d3xt3r01** [owncloud/core#23804] opened 2016-04-05 13:15 UTC
### Steps to reproduce
1. share a directory with some .mp4 files
2. play on iphone

### Expected behaviour
The video should play 

### Actual behaviour
Nothing happens when clicking the play video

### Server configuration
**Operating system**:
centos 7.2.1511

**Web server:**
apache 2.4.6-40.el7

**Database:**
mariadb-5.5.47-1.el7_2

**PHP version:**
php-7.0.5-1.el7.remi

**ownCloud version:** (see ownCloud admin page)
owncloud-files-9.0.0-3.1.noarch

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
ce:stable.repo
baseurl=http://download.owncloud.org/download/repositories/stable/CentOS_7

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4d6xg6wamc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "thepostoffice.ro"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/93.114.160.82\/cloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "forcessl": true,
        "mail_from_address": "office",
        "mail_smtpmode": "php",
        "mail_domain": "thepostoffice.ro",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "mail.thepostoffice.ro",
        "mail_smtpport": "143",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "has_internet_connection": true,
        "updatechecker": false,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Iphone

**Operating system:**
IOS9

#### Web server error log
```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/html/owncloud/lib/private/files/filesystem.php:804
Stack trace:
#0 /var/www/html/owncloud/lib/private/files/view.php(1973): OC\\Files\\Filesystem::normalizePath('/dan/files/Serb...')
#1 /var/www/html/owncloud/lib/private/files/view.php(1091): OC\\Files\\View->unlockFile('/Serbanica/Diab...', 1)
#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()
#3 /var/www/html/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()
#5 {main}
  thrown in /var/www/html/owncloud/lib/private/files/filesystem.php on line 804, referer: https://thepostoffice.ro/cloud/index.php/.....
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VwOzeVEhHfZSV6mwnxC2EAAAAAE","remoteAddr":"93.114.160.26","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/html\/owncloud\/lib\/private\/files\/filesystem.php:804\nStack trace:\n#0 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1973): OC\\Files\\Filesystem::normalizePath('\/dan\/files\/Serb...')\n#1 \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php(1091): OC\\Files\\View->unlockFile('\/Serbanica\/Diab...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/html\/owncloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/html\/owncloud\/lib\/private\/files\/filesystem.php#804","level":3,"time":"2016-04-05T12:45:45+00:00","method":"GET","url":"\/cloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json"}
```

#### Browser log
No idea on how I could get that on IOS

**Comment by d3xt3r01** [comment] 2016-04-05 18:48
As soon as I deleted a 2nd apps dir in config.php that I didn't have anymore and allowed "apps" to be updatable, everything worked !

**Comment by alerque** [comment] 2016-04-19 10:30
I'm seeing this error trying to connect a (Linux) sync client on a new machine to an existing account on a Linux ownCloud server. It gets a ways through the process of looking for what to sync and them bombs out.

**Comment by sprnza** [comment] 2016-04-19 14:44
I've got the same issue, don't know what causes it.

**Comment by tfmm** [comment] 2016-04-28 16:22
I can confirm this.  Issue appeared for me when updating PHP-FPM and related packages from 7.0.5 to 7.0.6 on CentOS 7.  Downgrading back to 7.0.5 resolved the issue.

**Comment by alerque** [comment] 2016-04-29 07:04
My error went away when I upgraded the ownCloud server from sqllite to mysql and added redis as a memory cache. I don't know if this is direct (e.g. an error that is only in the sqlite code somewhere) or secondary (e.g. some sort of race condition and redis is fast enough I'm not hitting it any more) but the correlation is pretty solid. I was getting the error on _every_ sync operation for weeks, then upgraded the above two items and now for a week all my syncs have succeed.

**Comment by tfmm** [comment] 2016-04-29 13:44
I've always used a MySQL backend.  I currently have no caching setup, redis or otherwise.  When I updated PHP to 7.0.6 I was unable to login at all.

**Comment by JoshHarmon** [comment] 2016-04-30 22:43
I am experiencing the same issues as @tfmm. Upgraded from PHP 7.0.5 to 7.0.6 from ondrej's PPA and have observed the following behavior:

1. Little to no information is reaching the log, even at the DEBUG level. Only cronjob completions reached the file. No user login events or anything reached the file.
2. All DAV resources are returning 404s to clients.
3. I am unable to log in, and am immediately redirected back to the same URI with a login page and no displayed error messages.

**ownCloud version**:
9.0.1 (same version as before issue occurred) - integrity OK

**OS**:
Ubuntu 15.10

**Apache**:
Apache/2.4.12 (Ubuntu)

**MySQL version**:
Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version**:
PHP 7.0.6-1+donate.sury.org~wily+1 (cli) ( NTS ) from ondrej PPA

**Redis (compiled) version**:
Redis server v=3.0.7 malloc=jemalloc-3.6.0 bits=64 build=fd6caf34ab0dc5e7

**Client**: 
Appears irrelevant. OS X and iOS Contacts app are failing. Chrome (latest) and Firefox are failing. ownCloud client Version 2.1.1 (build 3107) (OS X) failing.

**Comment by enoch85** [comment] 2016-05-10 20:56
I still see this in 9.0.2:

```
Error	PHP	Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/owncloud/lib/private/files/filesystem.php:807 Stack trace: #0 /var/www/owncloud/lib/private/files/view.php(1977): OC\Files\Filesystem::normalizePath('/daniel@en0ch.s...') #1 /var/www/owncloud/lib/private/files/view.php(1095): OC\Files\View->unlockFile('/Use these prog...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/owncloud/lib/private/files/filesystem.php#807
``` 

**MySQL**
5.7

**Webserver**
Apache 2.4

**OS**
Ubuntu 16.04

**PHP**
7

**Redis**
3.0.6 (Ubuntu)

@LukasReschke any thoughts?

**Comment by alerque** [comment] 2016-05-11 05:52
@tfmm and @JoshHarmon, you guys have a different issue than the one listed here, see #24343 for information on the issues caused by PHP upgrade.

**Comment by JoshHarmon** [comment] 2016-05-12 01:09
@alerque Noticed that once someone linked me to that PR, as I noted in my comment! I assumed it was related just because of the PHP version involved, but evidently that was not a correct assumption.

**Comment by RealRancor** [comment] 2016-06-11 10:13
Duplicate of https://github.com/owncloud/core/issues/22370

**Comment by MorrisJobke** [comment] 2016-06-26 21:25
> Duplicate of #22370

Closing as duplicate.

**Closed by MorrisJobke** 2016-06-26 21:25 UTC
Labels: bug, comp:filesystem

**Comment by plabong** [comment] 2016-09-25 14:19
**ownCloud 9.1.1.3**:
Exactly same behaviour as described by OP (but line number changes from 804 to 772)

**triggered by event**:
Click on MP4-File in ownCloud web interface to play the movie
The fatal PHP error is randomly thrown once, twice, ... up to 5 times

Selecting a MP4 file and downloading it DOES NOT triggers the error
