### ISSUE TITLE
Database Error after normal Upgrade :-(

### ISSUE THREAD

**Issue by j4mb4l4j4** [owncloud/core#14309] opened 2015-02-17 20:34 UTC
Got this after Upgrading from the latest 7 to 8.

An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_va5yk4gsao3qm RENAME INDEX appconfig_config_key_index TO oc_ixcl4blbaoaxe': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_ixcl4blbaoaxe' at line 1

**Comment by VicDeo** [comment] 2015-02-17 20:51
@j4mb4l4j4 Closing as a duplicate of https://github.com/owncloud/core/issues/14003

If you are not on MariaDB v10 feel free to reopen.

And please use issue template when reporting issues https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Closed by VicDeo** 2015-02-17 20:51 UTC
