### ISSUE TITLE
Upgrade from 9.1.6 to 10.0.3 complains about missing CHANGELOG.md

### ISSUE THREAD

**Issue by gtirloni** [owncloud/core#29140] opened 2017-10-03 14:03 UTC
### Steps to reproduce
1. Install 9.1.6
2. Use the Upgrader app to upgrade to 10.0.3
3. File integrity check

### Expected behaviour
File integrity should not have warnings after upgrade
Tell us what should happen

### Actual behaviour
File integrity complains about missing CHANGELOG.md file

### Server configuration
**Operating system**: CentOS
**Web server:** Apache
**Database:** SQLite
**PHP version:** 7.0.24
**ownCloud version:** 10.0.3
**Updated from an older ownCloud or fresh install:** 9.1.6
**Where did you install ownCloud from:** Docker image

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- CHANGELOG.md

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [CHANGELOG.md] => Array
                        (
                            [expected] => 1b1ce4226543ae79917a49ad7fbb1557f6368e3598b27232b4df3b1adf0ef29d2e2e47dbc2455757254c5bf38e3d728d5d010ecfd83762210d707f10ebe0b152
                            [current] => 
                        )

                )

        )

)
```

**Comment by kdslkdsaldsal** [comment] 2017-10-04 06:29
Closing as a duplicate of https://github.com/owncloud/updater/issues/436

**Closed by kdslkdsaldsal** 2017-10-04 06:29 UTC
