### ISSUE TITLE
Creating a new user using via occ and email keeps asking the password

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32743] opened 2018-09-18 08:46 UTC
### Steps to reproduce

1. As admin run occ command ```occ user:add davitol --email davitol@mymail.es```

### Expected behaviour

An email is sent to the mail set for user for joining ownCloud

### Actual behaviour

The password is asked even when we set a email via CLI

![screen shot 2018-09-18 at 10 38 06](https://user-images.githubusercontent.com/10596560/45675437-a58ae380-bb2f-11e8-94eb-4b16635cad4d.png)

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.10 
**Updated from an older ownCloud or fresh install:**
fresh

**Comment by davitol** [comment] 2018-09-18 08:55
current ```--email``` option is just for setting the email to the user. We should implement adding users via email feature to the occ commands in the future

![screen shot 2018-09-18 at 10 53 37](https://user-images.githubusercontent.com/10596560/45676152-6067b100-bb31-11e8-9535-96fddc1521e3.png)

**Comment by ownclouders** [comment] 2018-09-18 09:11
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32569 (Expand occ user reset password email validation), https://github.com/owncloud/core/issues/22991 (Send password to new users), https://github.com/owncloud/core/pull/32245 (create user with default password), https://github.com/owncloud/core/issues/17374 (occ should be able  to create new user), and https://github.com/owncloud/core/issues/12628 (asked by browser to save password while creating a new user).

**Comment by phil-davis** [comment] 2018-09-18 09:17
Ref: comment https://github.com/owncloud/enterprise/issues/2831#issuecomment-421372923

**Comment by JanAckermann** [comment] 2021-09-29 09:37
The referenced command does not send an email. So the password is mandatory, closing as everything is working as designed for now, not a bug.

**Closed by JanAckermann** 2021-09-29 09:37 UTC
Labels: Type:Bug, p3-medium
