### ISSUE TITLE
Syncing via SFTP External Storage fails for files with hash character

### ISSUE THREAD

**Issue by nwl** [owncloud/core#21301] opened 2015-12-19 00:00 UTC
Server: 8.2.1 on Ubuntu 14.04
Client: 2.1.0 OSX 10.10

I have user-mounted external storage via SFTP.

On the external storage server, there is a file which contains a # in the filename:

Radio_#1.txt

On the client, it reports Service Unavailable while trying to download it:

Error downloading https://...../webdav/Radio_%231.txt - server replied: Service Unavailable

Removing the # from the filename and restarting the client sync allows the file to download as normal.

**Comment by Xenopathic** [comment] 2015-12-19 01:07
Confirmed on current master

cc @bantu

**Comment by karlitschek** [comment] 2015-12-20 18:49
@icewind1991

**Comment by nwl** [comment] 2015-12-20 21:19
Also, as a separate issue, the failure is blocking too. It won't progress on any other file syncing once it hits the error.

**Comment by PVince81** [comment] 2015-12-21 09:44
It's not special characters, it's the **hash** character.
Umlauts and co should work fine.

See https://github.com/owncloud/core/issues/11692#issuecomment-147755904

Let's keep this ticket open to track the issue, because the linked issue is more about unit tests.

**Comment by PVince81** [comment] 2015-12-21 09:45
This is an upstream issue in phpseclib: https://github.com/phpseclib/phpseclib/issues/778
Unfortunately no workaround on ownCloud side works because if we pre-encode the hash the file name will stay encoded when arriving on the SFTP storage.

**Comment by nwl** [comment] 2015-12-21 18:04
@PVince81 Thanks for the update. 

However, It does sound like an ownCloud issue that it blocks on this failure, rather than continues and just logs the sync on those specific files as having failed.

**Comment by PVince81** [comment] 2015-12-21 18:10
Right, the problem here with "blocking the next files after error" is that it returns "Service unavailble", probably internally a `StorageNotAvailable` exception.

It should probably return a proper error instead, like NotFound or something. Seems like a case of "error is mistakenly interpreted as StorageNotAvailable".

**Comment by nwl** [comment] 2015-12-21 18:13
Should I file a separate bug for that?

**Comment by PVince81** [comment] 2015-12-21 18:14
I'm fine with keeping this current ticket to track that. Thanks.

**Comment by nwl** [comment] 2016-01-06 23:59
Looks like the upstream issue has been fixed. Will the latest version of phpseclib get included with the next release of owncloud?

**Comment by nwl** [comment] 2016-01-07 17:41
Also, found a silent failure in syncing a file with the Icelandic character í

SyncLog shows no failure or error and the client just doesn't sync the file.

**Comment by PVince81** [comment] 2016-01-08 09:28
@nwl is this only on SFTP storage or also on local storage ? (the Icelandic char issue)

**Comment by nwl** [comment] 2016-01-08 23:26
Only on the SFTP-mounted storage. Same thing for a file with various French characters too.
BTW, I applied the phpseclib patch which fixes the issue with hashes.

**Comment by PVince81** [comment] 2016-02-12 13:45
We're past feature freeze, not a good time to update libraries. Moving to 9.1

**Comment by PVince81** [comment] 2016-05-31 10:20
Still not solved in 9.1 beta1.

Seems we missed upgrading the library... hopefully next opportunity is 9.2.

Assigning to self.

**Comment by PVince81** [comment] 2016-07-01 15:04
PR to update phpseclib to 2.0.2: https://github.com/owncloud/core/pull/25339

**Comment by PVince81** [comment] 2016-10-04 13:26
Fixed on master thanks to phpseclib update! Fix will be in 9.2

**Closed by PVince81** 2016-10-04 13:26 UTC
Labels: app:files_external, bug, sev3-medium
