### ISSUE TITLE
After Debian upgrade from 7.0.4-3 => 8.0.0-5 - Error

### ISSUE THREAD

**Issue by berni123** [owncloud/core#14203] opened 2015-02-13 14:02 UTC
After dist-upgrade on Debian from 7.0.4-3 => 8.0.0-5 an perfoming the upgrade via the gui page I got the error: 
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external': SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL

The update was unsuccessful. Please report this issue to the ownCloud community.

Well, done here. Please investigate and fix it.

**Comment by LukasReschke** [comment] 2015-02-13 14:27
@schiesbn As far I can remember you added that stuff? :)

**Comment by berni123** [comment] 2015-02-13 14:32
I just did a regular apt-get dist-upgrade with deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ / on Debian wheezy - perhaps that was the mistake ... any hints to fix this issue to get it working again?

**Comment by berni123** [comment] 2015-02-13 14:55
I fixed it, via sqlite3 owncloud.db / select * from oc_share_external (backing up the data) / delete from oc_share_external - redoing the upgrade task via the web interface - now my owncloud is running again. But please fix the issue ...

**Comment by LukasReschke** [comment] 2015-02-13 14:57
Dupe of https://github.com/owncloud/core/issues/13970 - let's track this there.

**Closed by LukasReschke** 2015-02-13 14:57 UTC
Labels: bug, feature:federated-cloud-sharing, Regression, update
