### ISSUE TITLE
Updating ownCloud to version 8.0.3, failed

### ISSUE THREAD

**Issue by johnnyu2bad** [owncloud/core#16218] opened 2015-05-10 17:49 UTC
An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ

**Comment by workinghard** [comment] 2015-05-10 19:01
I'm using mysql and have the same error.
Solution was to change the binlog_format to mixed:
https://dev.mysql.com/doc/refman/5.1/en/binary-log-setting.html
http://dba.stackexchange.com/questions/58459/mysql-error-impossible-to-write-to-binary-log

**Comment by RealRancor** [comment] 2015-05-10 19:38
Duplicate of: https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16008, https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097, https://github.com/owncloud/core/issues/16214

**Comment by nickvergessen** [comment] 2015-05-11 06:55
Please update to the 8.0.3

**Closed by nickvergessen** 2015-05-11 06:55 UTC
