### ISSUE TITLE
tempmanager error msg after upgrading from 7.0.4 -> 8.0.0

### ISSUE THREAD

**Issue by theumi** [owncloud/core#14290] opened 2015-02-17 13:29 UTC
After upgrading my ownCloud 7.0.4 instance to 8.0.0 it became really unstable. I first turned off all apps in the database appconfig-table and switched my PHP version to 5.6.2 before ownCloud raised to life again.

After turning some apps back on again the owncloud.log file explodes with following messages: 

```
{"reqId":"cdb949b0455a1ceb59ca0979a93331d0","remoteAddr":"123.123.123.123","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/www\/htdocs\/xxxxxxxx\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-17T11:14:30+00:00"}
```

Do you have any idea how to turn this off? I even have no idea what's the cause for this error message.

Thanks for your help.

**Comment by LukasReschke** [comment] 2015-02-17 13:33
Duplicate of https://github.com/owncloud/core/issues/13953. Please try to apply https://github.com/owncloud/core/pull/13977 and if that works the fix will be included within 8.0.1

**Closed by LukasReschke** 2015-02-17 13:33 UTC
