### ISSUE TITLE
Update failure from 8.0.4.2 to 8.1.1

### ISSUE THREAD

**Issue by valir** [owncloud/core#18322] opened 2015-08-14 20:30 UTC
Here is the output displayed by the main page after clicking the "update" button:

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "updater" to 0.6
Updated "files" to 1.1.10
Updated "activity" to 2.0.1
Updated "files_sharing" to 0.6.2
Updated "files_trashbin" to 0.6.3
Updated "files_versions" to 1.0.6
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by valir** [comment] 2015-08-14 20:36
When reloading the page, the server redisplayed the "update" button and this time procedure worked as expected and now the server is online again.

My setup is : nginx => php-fpm => owncloud => mariadb

During the upgrade, I only restarted php-fpm as I have other sites on nginx.

**Comment by valir** [comment] 2015-08-14 20:44
Oh! I have new information.

After upgrading, applications need to be re-activated. I'm using the standard calendar and contacts applications. The former activated without problems. The latter displayed an "cannot enable application" error next to the activate button. After that, the applications page went blank when clicking on the left-side sections. When returning to my main owncloud page, the server returned to the upgrade process, presented the "upgrade" button, and the output showed that the contacts applications got updated to 0.4.0.

OK, I think that's because I missed an intermediate update.

**Comment by MorrisJobke** [comment] 2015-08-14 21:42
Duplicate of #18224

**Closed by MorrisJobke** 2015-08-14 21:42 UTC
