### ISSUE TITLE
OC8.0 beta - Shared folder is not removed from "shared with you" listing.

### ISSUE THREAD

**Issue by arm2arm** [owncloud/core#13445] opened 2015-01-18 18:20 UTC
### Steps to reproduce
1. OC8.0.0-betta-1 clean install 
2. create 2 users A and B
3. User A shares own Documents folder to B as can edit but cannot delete
4. User B renames the folder to DocumentsfromA
5. User A unshare folder
6. User B see still DocumentsfromA in the "shared with you" 

### Expected behaviour
DocumentsfromA in the "shared with you" should wanish as well.

### Actual behaviour
User B see still DocumentsfromA in the "shared with you" 

### Server configuration
**Operating system**: Ubuntu 14.04LTS 

**Web server:** Apache/2.4.10 (Ubuntu)

**Database:** MySQL

**PHP version:** 5.5.20-1+deb.sury.org~trusty+1

**ownCloud version:** (see ownCloud admin page)
8.0.0 beta 1

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default 
**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'oc80.aip.de',
  ),
  'datadirectory' => '/var/www/testoc/oc80/owncloud/data',
  'overwrite.cli.url' => 'http://oc80.aip.de',
  'dbtype' => 'mysql',
  'version' => '8.0.0.1',
  'dbname' => 'oc80',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc80',
  'dbpassword' => 'xxxxxxx',
  'installed' => true,
   'asset-pipeline.enabled' => true,
);
```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

### Client configuration
**Browser:** FF34.x

**Operating system:**
Ubuntu LTS14.01

#### ownCloud log (data/owncloud.log)
Error 	files_sharing 	No owner found for reshare 	2015-01-18T18:07:58+00:00
Error 	files_sharing 	No owner found for reshare 	2015-01-18T18:07:58+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare	2015-01-18T18:07:39+00:00
Error	files_sharing	No owner found for reshare

**Comment by PVince81** [comment] 2015-01-19 10:33
Hmmmmmmmm that's not good.
Possibly a regression.

Will have a look.

**Comment by PVince81** [comment] 2015-01-19 10:48
Some ideas to optimize the web UI workflow:
1) Call json_encode() only on every file, then string concat into the final array
2) After converting a file with json_encode(), remove it from the original array, with `shift()` (if that doesn't cause additional perf issues for PHP...)
3) Rely on DB sort (but might cause trouble with UTF-8 chars)

Ideally we should resort to pagination, but that will cause trouble with WebDAV...

**Comment by PVince81** [comment] 2015-01-19 15:05
Works for me on master (cd4c7fd11fb119846757345681425d776e6abbea)
and also on 8.0.0beta1.

@arm2arm can you give more details about the share ?
Are you able to reproduce this from scratch with two new users ? Is it a reshare (the error message seem to imply so) ? Is there a group share involved ?
Please check the oc_share table: `select * from oc_share where share_with='B'`.

In your case something must have prevented the proper deletion of the database entry for the share.

**Comment by PVince81** [comment] 2015-01-19 15:06
It could be similar to https://github.com/owncloud/core/issues/13361#issuecomment-70136056 if you upgraded from 7.0.2, etc and reshared from an existing group share.

**Comment by arm2arm** [comment] 2015-01-19 15:46
Hi,
no it is not an upgrade, clean iunstall as reported.
User a has a name: arm2arm, user B has a name arm2arm80.
here is my select from db:
mysql> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+------------------------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target                  | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+------------------------------+-------------+------------+----------+------------+-------+-----------+
|  2 |          2 | arm2arm    | arm2arm80 |      1 | folder    | 8           | /8          |           8 | /Documents/Documentfromarman |          23 | 1421603945 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+------------------------------+-------------+------------+----------+------------+-------+-----------+
1 row in set (0.00 sec)

hope it helps.
PS
nothing is shared, clean install, arm2arm share /Documents with group admin.
arm2arm80 see the share and rename it to /Documentfromarman
arm2arm unshare folder. arm2arm80n see it still in "shared with me"

**Comment by PVince81** [comment] 2015-01-19 15:52
Very strange. I can see that the `parent` is still set to 1, which was probably the main share entry.

When I tested this locally, there was only a single entry (the one with id 1), and after renaming the target, the value of `file_target` changed. There was always only one entry.

Not sure why in your case it creates two entries. Having two entries also makes sense but it is usually for when shares are created for groups.

Needs further research.

**Comment by arm2arm** [comment] 2015-01-19 16:11
again one test:
truncate  table oc_share;
arm2arm shared Documents 
arm2arm80 renames Documents(2) to Documentfromarman
Database:
mysql> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target         | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
|  1 |          1 | admin      | arm2arm   |   NULL | folder    | 28          | /28         |          28 | /Documents          |          31 | 1421683562 |        0 | NULL       | NULL  |         0 |
|  2 |          2 | arm2arm80  | arm2arm   |      1 | folder    | 28          | /28         |          28 | /Documentsfromarman |          23 | 1421683562 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
2 rows in set (0.00 sec)

After Unshare:
mysql> select * from oc_share;
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target         | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
|  2 |          2 | arm2arm80  | arm2arm   |      1 | folder    | 28          | /28         |          28 | /Documentsfromarman |          23 | 1421683562 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------------+-------------+------------+----------+------------+-------+-----------+
1 row in set (0.00 sec)

It should remove all sourceID=28 but it doesnot.

**Comment by PVince81** [comment] 2015-01-19 16:18
I edited your output to make it look better. In the future you can use the triple backquote to wrap console output: :smile: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting.

Are your test users in any groups ? (it could affect some code paths)

I'll try again to reproduce it.

**Comment by PVince81** [comment] 2015-01-19 16:19
Okay I see, so "user2" already had a folder called "Documents" before sharing. That's why you're getting "Documents (2)".
I'll try that.

**Comment by PVince81** [comment] 2015-01-19 16:25
Also works for me.
I did the following:
1. Create "user1"
2. Create "user2"
3. Login as "user2", create folder "Documents"
4. Login as "user1", create folder "Documents"
5. Share "Documents" with "user2" but remove the delete permission
6. Login as "user2", rename "Documents (2)" to "Documentsfromuser1"
7. Login as "user1", unshare "Documents"

All the time there's only a single entry.

I had another look at your DB dump. I think in your case step 5 is: Share "Documents" with group "admin" (see that `share_with` is set to `admin`). So this is a group share.

**Comment by PVince81** [comment] 2015-01-19 16:28
Ok I got it.
Here are the exact steps from an empty OC 8.0.0beta1:
1. Create "user1"
2. Create "user2", add this user to the "admin" group
3. Login as "user2", create folder "Documents"
4. Login as "user1", create folder "Documents"
5. Share "Documents" with "admin" group but remove the delete permission
6. Login as "user2", rename "Documents (2)" to "Documentsfromuser1"
7. Login as "user1" and unshare "Documents".

At this point I also have the stray entry.

**Comment by PVince81** [comment] 2015-01-19 16:37
Also happens on master (4894a2c458f49b2c6b49b18cc0055ae087bff1b2) so not fixed by the ticket I mentioned before. :frowning: 

I'll have a look.

CC @schiesbn FYI

**Comment by PVince81** [comment] 2015-01-19 16:38
@DeepDiver1975 @karlitschek tagging as showstopper.

**Comment by arm2arm** [comment] 2015-01-19 16:38
Ok If I am not renaming shared folder it works as expected.
There are some problems with can edit options.

**Comment by PVince81** [comment] 2015-01-19 16:42
In my case I don't even need to rename it (can remove step 6).

**Comment by PVince81** [comment] 2015-01-19 16:53
So, this it the table just before the deletion:
```
MariaDB [owncloud]> select * from oc_share;                                                                                    +----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
| id | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target    | permissions | stime      | accepted | expiration | token | mail_send |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
|  7 |          1 | admin      | user1     |   NULL | folder    | 23          | /23         |          23 | /Documents     |          31 | 1421685458 |        0 | NULL       | NULL  |         0 |
|  8 |          2 | root       | user1     |      7 | folder    | 23          | /23         |          23 | /Documents     |          31 | 1421685458 |        0 | NULL       | NULL  |         0 |
|  9 |          2 | user2      | user1     |      7 | folder    | 23          | /23         |          23 | /Documents (2) |          31 | 1421685459 |        0 | NULL       | NULL  |         0 |
+----+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+----------------+-------------+------------+----------+------------+-------+-----------+
```

and after debugging I find that this query is executed to try and find the child elements:
`SELECT `id`, `share_with`, `item_type`, `share_type`, `item_target`, `file_target`, `parent`, `uid_owner` FROM `oc_share` WHERE `parent` IN (7) AND `share_type` != 2;`

It must be wrong because the children DO have the share type 2, but the code in question seems to want to exclude them: https://github.com/owncloud/core/blob/master/lib/private/share/helper.php#L104

@schiesbn do you have an idea why ?

**Comment by PVince81** [comment] 2015-01-19 16:56
Regression introduced by this PR https://github.com/owncloud/core/pull/13016
Before that one, it works fine.

The PR states that it solves an issue when reshare is not allowed. Yet there is no if block to check for that condition. That part might be missing.

**Comment by arm2arm** [comment] 2015-01-19 18:42
BTW on OC7.0. 4 no sucha issue...It works as expected.

**Comment by PVince81** [comment] 2015-01-20 09:43
Yes, thanks. That issue was introduced recently in OC 8.

**Comment by PVince81** [comment] 2015-01-20 12:11
Fix is here: https://github.com/owncloud/core/pull/13509

**Comment by PVince81** [comment] 2015-01-20 12:46
The workaround for now: clean the orphaned shares with `delete from oc_share where parent not in (select id from oc_share)`

**Closed** 2015-01-22 09:40 UTC
Labels: 5 - To review, bug, ownCloud 8.0 Showstoppers, Regression
