### ISSUE TITLE
User Lost old Password  can not view encrypted file file/folder(Encryption issue)

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#15286] opened 2015-03-27 20:37 UTC
### Actual behavior

One of our customer created one group then assign two user to that group. Out of two user,  user1 share file & folder with User 2,User 2 can see share  & view file & folder contents
Admin change User2 password, Now when user 2 logging with new password User 2 can see file folder but cannot see contents; User 2 see  Yellow banner message pop-up at  Top of header
“Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.”

Also error message pop-up

“An error occurred! 
Your private key is not valid! Likely your password was changed outside of ownCloud (e.g. your corporate directory). You can update your private key password in your personal settings to recover access to your encrypted files.”

Problem is in-order to decrypt file required old-password which user2 forgot.

Now, how can user2 view file if user2 forgot old password and encryption on.

### Expected behavior
User 2 should able to  view file/Folder 

### Steps to reproduce
1) Build system mirror of customer
2) install oC
3) Create group
4) Create two user
5) User 1 share file/folder with user 2
6) User 2 see file/folder
7) As admin change password of User2
8) Login as USer2 with new password
9) User two can can see file folder but can not view conytets
10) login as USER1 unser file/folder with User2
12) as User1 re-share file/folder with USer2
13) login as User2 try access file /folder 
same result

### Server configuration

Operating system:
Ubuntu Server 14.04.1 LTS

Web server:
lighttpd/1.4.35

Database:
mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39)

ownCloud version:
branded 7.0.3 (stable)

Storage backend:
Local storage:
/dev/sda1 on / type ext4

Client configuration

We only allow access to OwnCloud via the Web Interface.  We run Google Chrome web browser on all of our laptops.

#### Log/Image location : 
S3/Shared/owncloud/support/gihub-issues/15286

**Comment by PVince81** [comment] 2015-03-27 21:24
This is by design and technically correct. The private key of the user is encrypted using the password. This means that without password, the key is unusable.

Did the admin setup a recovery key ? Recovery key is a bit like an internal share with a virtual user that also gets access to all files. With a recovery key the admin can reset that user's password.

Cc @schiesbn

**Comment by PVince81** [comment] 2015-03-28 10:22
As long as user2 doesn't have access to their key (due to the different password), they won't be able access files, even shared ones.

Works as expected (technical limitation)

**Comment by PVince81** [comment] 2015-03-28 10:22
But still, thanks for the detailed report :smile:

**Comment by RealRancor** [comment] 2015-03-28 11:15
Btw. this is also documented here:

https://doc.owncloud.org/server/8.0/user_manual/files/encrypting_files.html#recovery-key-password
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/encryption_configuration.html#enabling-a-file-recovery-key

**Comment by iliyasbasir** [comment] 2015-04-02 15:52
@PVince81 : If user lost their old password ...they lost there share forever  ...they can not get back there share in encrypted world?

**Comment by DeepDiver1975** [comment] 2015-04-02 15:59
> @PVince81 : If user lost their old password ...they lost there share forever ...they can not get back there share in encrypted world?

if key recovery is not enabled - no - as stated: this is the way it is with encryption

https://doc.owncloud.org/server/8.0/user_manual/files/encrypting_files.html#recovery-key-password
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/encryption_configuration.html#enabling-a-file-recovery-key

**Comment by PVince81** [comment] 2015-04-07 08:33
As discussed before with @MTRichards and @schiesbn we might want to enable the recovery key by default to make sure that this doesn't get forgotten.

**Comment by PVince81** [comment] 2015-04-07 08:42
This was suggested in this ticket: https://github.com/owncloud/core/issues/11948

**Comment by MTRichards** [comment] 2015-04-07 11:51
Yes please, a default enabled recovery key helps admins avoid a problem by default. Failure to have a recovery key becomes an act of commission then, which is much better.

**Comment by PVince81** [comment] 2015-04-07 12:24
@iliyasbasir was the password changed on LDAP or in the user management page ?

I'll try and see what happens in 7.0.3. According to @schiesbn it is likely that the old private key is still preserved. So to "reactivate" the user's account one would need to delete the private+public key of that user. But don't try anything just now, I'll have a try locally. Goal is to make it possible for the user to recover the account and get rid of the "invalid private key" message.

**Comment by PVince81** [comment] 2015-04-07 12:25
Reopening for now, in the search of a quickfix to make it again possible to share files with that user.

**Comment by PVince81** [comment] 2015-04-07 12:26
CC @bboule

**Comment by PVince81** [comment] 2015-04-07 12:39
Here are my test steps to reproduce this on 7.0.3 from scratch:
1. Enable encryption
2. Create two users "user1" and "user2" with the password "test"
3. Login as "user1"
4. Create a folder "test"
5. Upload a bunch of pics in "test"
6. Share "test" with "user2"
7. Login as "user2" and check that the pics can be viewed/downloaded
8. Check/save/md5 the keyfiles of user2 (I did `md5sum data/public-keys/user2.public.key data/user2/files_encryption/user2.private.key`)
9. Login as admin
10. Go to the users management page
11. Change the password of "user2" to "changedpw"
12. Recheck the md5 of the keys (like in 8): I see that the keys are unchanged
13. Login as "user2" with the password "changedpw"
14. See message "Invalid private key"
15. Trying downloading files inside the "test" dir: doesn't work. This is expected so far.
16. Backup then delete the keys from "user2": `rm data/public-keys/user2.public.key data/user2/files_encryption/user2.private.key`
17. Log out then login as "user2" again: note that the error notification is gone
18. Try downloading files: doesn't work. This is expected (shared keys still invalid).
19. Now login as "user1"
20. Unshare then reshare "test" with "user2"
21. Login as "user2"
22. Try downloading files: success!

This is only for the record, I will write up the steps for @iliyasbasir to manually "repair" that user.

**Comment by PVince81** [comment] 2015-04-07 12:49
@iliyasbasir @bboule here are the steps to fix "User 2" (from the original report).

The goal here is to get rid of the error "Invalid private key" and recreate a valid key pair for "User 2" to make the account usable again (including sharing files with that user). Please note that **all local private files from "User 2" are not recoverable**. But after making the account usable again, it will be possible to re-share files with that user which were already shared before.

Here are the steps:
1. Make a backup copy of the user's public key and private key, from here `data/public-keys/user2.public.key` and `data/user2/files_encryption/user2.private.key`
2. Now delete these two keys
3. Login as "User 2" with the new password. This will automatically regenerate a new keypair for "User 2".
4. As "User 2" click "unshare from self" for the files/folders that were shared with that user (User 2 being the recipient)
5. Login as the owner of any of the shared folders
6. Share those folders again with "User 2"

Please let me know if you have further questions.

**Comment by PVince81** [comment] 2015-04-07 12:50
Note: ideally we should provide a button "reset private/public keys" on a user's personal page to avoid having the admin manually delete these keys from the server. The scenario "User has forgotten password, admin sets a new one (with no recovery key enabled)" is valid and should be made easier to recover from.

**Comment by bboule** [comment] 2015-04-07 13:07
Vincent  this is AWESOME!!!  @iliyasbasir can you please be sure you also set this up so that you will be in a position to help the user with this.

Thanks again for the help here guys!!!!

Bob

**Closed** 2015-04-29 21:12 UTC
Labels: app:files_encryption, blue-ticket, bug

**Comment by jeremyclarke** [comment] 2015-12-16 20:03
FWIW +1 to being able to reset the keys from inside the UI, and also that it be doable by an admin. This is made very hard by the fact that there's currently no way to edit a user's profile for them, which also makes it impossible to set the recovery option to true for them upon creation (so we can't work around the lack of way to enable recovery by default).
