### ISSUE TITLE
Right menu doesn't open when clicking on the surroundings of the arrow.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28770] opened 2017-08-22 11:00 UTC
### Steps to reproduce

1. Set a profile picture.
2. Try to open the right folder.
3. Click close to the little arrow, but not inside it.

### Expected behaviour
Right menu opens when clicking on the arrow, profile pic and surroundings. 

### Actual behaviour
Only clicking on the profile pic, little arrow and top of the arrow opens the right menu.

![right-menu-clicks](https://user-images.githubusercontent.com/9048796/29562449-a9261328-8739-11e7-9485-f2212ca525c2.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3beta1
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Chrome

cc @felixheidecke

**Comment by PVince81** [comment] 2017-08-22 11:15
duplicate of https://github.com/owncloud/core/issues/28690

**Closed by PVince81** 2017-08-22 11:15 UTC
Labels: bug, p2-high, sev3-medium
