### ISSUE TITLE
Owncloud 8.1 upgrade broken on debian (and probably also ubuntu and other linuxes)

### ISSUE THREAD

**Issue by sergiocallegari** [owncloud/core#17523] opened 2015-07-09 09:12 UTC
Running owncloud on a debian machine, using the official owncloud packages from the opensuse build factory.

Just upgraded my packages to 8.1.  The upgrade process has issues...

1) After having installed the new packages everybody sees on the web page a big button saying start-update.  This should not be shown in this way, otherwise anybody connecting to my host can start the upgrade with a timing unknown to the admin.

2) The same page also says To avoid timeouts with larger installations, you can instead run the following command from your installation directory: ./occ upgrade
However this command cannot be run.  In fact

occ is not set executable

even if one sets the x permission bit, it will error out because it cannot read config.php if run as the current user

if run as root it will stop immediately saying that it is being run by root while it should be run by the owner of config.php, but the owner of config.php is the www-data user who has no login shell on debian.

**Comment by RealRancor** [comment] 2015-07-09 09:19
Hi,

1) Refs for existing issues: https://github.com/owncloud/core/issues/14229 and https://github.com/owncloud/core/issues/14219

2) You need to run this as the www-data user, there is no other way of doing this. If you want to use the ./occ command line tool you need to set a login shell for www-data

**Comment by giancarlobi** [comment] 2015-07-09 09:55
On Ubuntu 14.04 worked well.
Yes, you have to use sudo -u www-data php occ upgrade from within owncloud dir.

**Comment by IzzySoft** [comment] 2015-07-10 11:30
My OC server runs Ubuntu 12.04. Here I'm offered the upgrade via the package manager (using the ppa) – but the packages seem to be missing. The GUI updater always warns about "incomplete update" multiple days now. Guess that's related (packages temporarily withdrawn until issue fixed)? Shouldn't it be cleared in the repo's `packages.xml` as well (as on my end, an `apt-get update` doesn't fix it either)? Or is it just me, and the problem somewhere on my end?

**Comment by sergiocallegari** [comment] 2015-07-12 13:49
OK, correct, I missed that, notwithstanding the fact that I used the `sudo -u www-data php occ` command before... So the issue is that the screen that appears after an update is misleading in saying run `./occ upgrade`: by providing the precise path it makes you think that the command must be typed in verbatim, regardless of your actual configuration. IMHO the message should be either better adapted to your particular environment or be made more generic (e.g. run the occ script with the 'upgrade' option).

In any case the **biggest issue** remains the 'start upgrade' button that is shown to anybody and can be pressed by anybody. Is there a way to disable it or to make it only available to the owncloud admin?

**Comment by RealRancor** [comment] 2015-07-12 15:05
@sergiocallegari See https://github.com/owncloud/core/issues/17523#issuecomment-119884388

**Comment by sergiocallegari** [comment] 2015-07-13 09:06
Thanks for the pointer, although the content there really does not provide a feasible solution yet.

- The password block via the apache config looks like a hack, at least until there is proper integration with owncloud (works only with apache, if the path of the update script is changed in the owncloud development the thing breaks, etc).

- Providing an option to disable the update script in the admin config page seems the best option to me in the short term. An alternative would be letting admin configure IP addresses which can run the update script.

- In the long term, changing the admin authentication mechanism so that update actions can be protected seems the sensible thing to do. E.g. have admins load a public key that goes in config and let authentication be based on the private part of the the key.

Also note that if anyone who loads the page can press the update button there is no reason to have an update button at all. Would be better to have the action automatically triggered, before waiting someone totally unrelated to you who casually jumps on the page to press the button for you...

As of the current state of the art, someone could make a robot crawling web pages while looking for owncloud installations with the update button just to "press" it...

**Comment by RealRancor** [comment] 2015-07-13 09:09
Please follow or post your concerns in https://github.com/owncloud/core/issues/14229

It makes no sense to discuss this on two places

**Comment by MorrisJobke** [comment] 2015-08-03 09:57
Closing this as duplicate of #14229

**Closed by MorrisJobke** 2015-08-03 09:57 UTC
