### ISSUE TITLE
Allow folder creation in public share

### ISSUE THREAD

**Issue by labkode** [owncloud/core#17486] opened 2015-07-08 12:51 UTC
If you share by public link a folder and you allow public upload/editing then you have a button to upload files but not to create folders.

The only way to create a folder is using drag and drop.

The possibility to create folders in this mode is very useful and should be there, the implementation already allows it, so it is just a matter of UI + Ajax call.

Cheers

**Comment by PVince81** [comment] 2015-07-09 11:41
Duplicate of https://github.com/owncloud/core/issues/6635

**Comment by PVince81** [comment] 2015-07-09 11:42
It's not as easy as you think. The problem is that ajax calls all work for the logged in user, but are not suitable for the public link.

I already have a working alternative where we use WebDAV and the "publicwebdav" endpoint instead of ajax in the files app, see https://github.com/owncloud/core/issues/12353

**Closed by PVince81** 2015-07-09 11:41 UTC
Labels: enhancement

**Comment by PVince81** [comment] 2015-07-09 11:43
I actually meant the PR matching that ticket: https://github.com/owncloud/core/pull/16902

**Comment by labkode** [comment] 2015-07-09 12:27
@PVince81 at leats creating folders works without being logged in, you can check it sharing a editable public share and accessing it from another browser/incognito session and try to drag and drop the folder
