### ISSUE TITLE
Accounts mixed on webdav sync

### ISSUE THREAD

**Issue by pluijm** [owncloud/core#11400] opened 2014-10-02 18:59 UTC
This bug is tested on two different servers. This bug seems to be introduced between oc6.0.4 and oc7.0.1. oc6 seems not affected. If a different alias is used for each account, everything works as expected.

### Steps to reproduce
1. Create 2 accounts on an owncloud server
2. Create a text file test1.txt in account A and test2.txt in account B
3. Create both accounts in PDFexpert
4. Sync account A in PDFexpert
5. Sync account B in PDFexpert

### Expected behaviour
Account A contains a file test1.txt, account B contains a file test2.txt

### Actual behaviour
Both accounts are equal. Account A has a file test2.txt and there is no test1.txt. Account B is correct. The incorrect file list of A is not synced back to owncloud.

### Server configuration
**Operating system**: Ubuntu 14.04 / Ubuntu 12.04

**Web server:** Apache/2.4.7 (Ubuntu) / Apache/2.2.22 (Ubuntu)

**Database:** MySQL 5.5.38 / Postgresql

**PHP version:**  5.5.9-1ubuntu4.4 / 5.3.10-1ubuntu3.14 with Suhosin-Patch

**ownCloud version:** 7.0.1 (ubuntu) / 7.0.2 (git)

**Updated from an older ownCloud or fresh install:** updated from oc7.0.0 / updated from oc6.0.4

**List of activated apps:** Uppon request

**The content of config/config.php:** Uppon request

**Are you using external storage, if yes which one:** local storage / local storage

**Are you using encryption:** no / disk encryption

### Client configuration
**Browser:** PDFexpert 4.7.8, 5.2 and Documents 5

**Operating system:** iOS 7 and iOS 8

#### Web server error log
```
10.74.0.203 - test1 [02/Oct/2014:20:45:32 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 2181 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:45:50 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 1302 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test1 [02/Oct/2014:20:45:51 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 965 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test1 [02/Oct/2014:20:45:51 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3562 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:46:03 +0200] "OPTIONS /remote.php/webdav HTTP/1.1" 200 1158 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
10.74.0.203 - test2 [02/Oct/2014:20:46:03 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3562 "-" "ReaddleDAV PDFExpert/4.7.7.2 (redirects)"
```

#### ownCloud log (data/owncloud.log)
```
No entries
```

#### Browser log
```
Not available
```

**Comment by kwillems** [comment] 2015-01-09 12:58
Is there any news on this one? The problem still occurs and is very annoying.

**Comment by kwillems** [comment] 2015-01-10 14:49
For good understanding: this bug is NOT limited to PDFExpert or any app from Readdle.
I've just installed an app called 'Webdav Navigater' (https://itunes.apple.com/nl/app/webdav-navigator/id382551345?mt=8) and the same bug occurs.

**Comment by LukasReschke** [comment] 2015-01-11 14:15
Seems to be related to the cookie handling. I've scheduled a patch for 8.0 – stay tuned…

**Comment by PVince81** [comment] 2015-01-12 11:09
Is this related to https://github.com/owncloud/core/issues/13245 ?

**Comment by LukasReschke** [comment] 2015-01-12 11:39
Yes

**Comment by LukasReschke** [comment] 2015-01-16 13:35
Fix is at https://github.com/owncloud/core/pull/13416 – please test and report back.

**Comment by cosenal** [comment] 2015-01-20 00:17
OP's issue is still there

**Comment by LukasReschke** [comment] 2015-01-20 09:07
That's confusing. Because I use "PDFExpert 5.2.3.9" (probably a beta version since I got access to their beta software testing pool) and it just works fine here.

What did you do exactly? – Does it help if you remove and re-add the account? (maybe some cache)
Or can you force-close the application, does that help?

If not it would be cool if you could reset the PDFExpert oC accounts and reset-up them and post steps to reproduce. Because it locally works just fine for me :(

**Comment by cosenal** [comment] 2015-01-23 00:34
I did try removing and adding the account, and force-close the app, but the problem is still there.

The exact steps are the one reported by the OP and then:
- Add account1 on Documents or PDFExpert, log in with user1.
- Add account2 on Documents or PDFExpert, and no matter what user you log in with, it goes to user1's home folder.

@pluijm @kwillems A possible fix is in master now, can you check if it solves the issue on your machines?

**Comment by LukasReschke** [comment] 2015-01-23 00:36
Are those accounts on the same oC instance / domain or a different one?

**Comment by cosenal** [comment] 2015-01-23 00:38
same instance

**Comment by pluijm** [comment] 2015-01-27 09:10
@cosenal I will check, but at this moment, there are some issues in our personal lives. Will check in when I've checked with master.

**Comment by DeepDiver1975** [comment] 2015-01-27 10:59
how to continue on this one? I'd vote for moving this to 8.1 and mark as needs-more-info
@LukasReschke agreed?

**Comment by LukasReschke** [comment] 2015-01-27 11:04
Let me test again later today with that client… If I can't reproduce 8.1

**Comment by LukasReschke** [comment] 2015-01-27 11:22
So, what I did here was the following:

1. I setup a new ownCloud instance on current master running at "192.168.0.17/core/"
2. I logged-in as user "admin" and deleted the default folder structure and created a file "admin.txt"
3. I create an user "test", I login as that user and delete the default folder structure and create a file "test.txt"
4. I open "PDFExpert" on my iPhone and delete all existing accounts
5. I click on the "Network" tab in "PDFExpert"
6. I add a WebDAV account to "192.168.0.17/core/remote.php/webdav" with the "admin" credentials
7. I add a WebDAV account to "192.168.0.17/core/remote.php/webdav" with the "test" credentials
8. When clicking on the "admin" connection I see the file "admin.txt"
9. When clicking on the "test" connection I see the file "test.txt"
10. When repeating above steps it still behaves as expected

I can really not reproduce this behaviour. If you do it exactly that way does it work for you? If so what is different from my steps? – Let's move this to 8.1 for now.

**Comment by cosenal** [comment] 2015-01-27 15:43
The steps are exactly the same, one by one. I have just tried the beta version of the client and it does works. At this point I am blaming the stable version of PDFexpert and closing this. Thanks @LukasReschke for thorough testing ;)

**Closed by cosenal** 2015-01-27 15:43 UTC
Labels: bug, needs info
