### ISSUE TITLE
thoughts on general things -> Update 8.0.2 -> 8.0.3 fails due InnoDB usage

### ISSUE THREAD

**Issue by githubrsys** [owncloud/core#16352] opened 2015-05-14 09:06 UTC
ocurred while executing 'INSERT INTO `oc_oc_appconfig_ygs14216armp6` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

##### By scanning though the issues I found out that there are multiple doubles on this issue. So then I ask myself: 

* why the heck doesn't the update script run a pre compatibility test on the server?
* why the heck isn't there a rollback button in the udpate userinterface if something went wrong?
* and why the heck does the updatescript does not resprect filepermissions set on the server? Every Update suPHP faces me a "owncloud/index.php" is writeable by others when running the update script in webinterface. So I have to manually set something. Come on: This is a nobrainer which should be fluid in the fingers while writing the code. Just set them into the settings file if you are really lazy. But you could determine  by the existing file structure. 

AND to be honest: I wont change my db server to mixed mode as it is absolutely not comprehendable to do that.

# In MySQL 5.5, the default binary logging format is STATEMENT.

Why do you force the users to change that? That makes no sense as a lot of users do not have the right to change the  db logging. And 5.5 is a standard these days.

**Comment by LukasReschke** [comment] 2015-05-15 06:40
Duplicate of https://github.com/owncloud/core/issues/16008, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218, https://github.com/owncloud/core/issues/16285, https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16157, https://github.com/owncloud/core/issues/16097, https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/7769, https://github.com/owncloud/core/issues/16066, https://github.com/owncloud/core/issues/16063

Final tracking of this issue is at https://github.com/owncloud/core/issues/16008 and targeted for 8.0.4 – please use the search function when filing this issues. THX.

**Closed by LukasReschke** 2015-05-15 06:40 UTC
