### ISSUE TITLE
Moving items in the web interface is extremely difficult

### ISSUE THREAD

**Issue by strugee** [owncloud/core#19570] opened 2015-10-05 02:59 UTC
It's actually extremely difficult to move items around in the web interface. If the folder you're trying to move items to is in the current view, it's no problem, but if the folder is off the screen - which is a problem if, like me, you have a lot of folders - it becomes AFAICT impossible to move files.

The viewport should scroll up when the user drags files to the top of the screen. Same on the bottom.

I'm on Firefox Nightly, built 10/2/15.

**Comment by strugee** [comment] 2015-10-05 03:00
Also, I have e10s disabled.

**Comment by despens** [comment] 2015-10-05 03:25
This is true. Noticed these problems:

- In some situations it is impossible to see into what folder I am moving something since the folder I'm actually hovering over is not highlighted in any way. Can lead to moving stuff into the wrong folder and "losing" it.

Suggested solution: highlight target folder during drag&drop operations 

- To move something horizontally the directory tree is really painful. I can drag a folder upwards to the breadcrumb navigation, then it is dropped into that directory. Then I have to change into that directory, find my folder there, and move it downwards again.

Suggested solution: when dragging over the breadcrumb or a folder will, after a little timeout, change into that directory. Once the mouse button is released, items are moved to this target, then the view returns to the path where the drag operation started.

**Comment by RealRancor** [comment] 2015-10-05 05:08
Maybe also something for https://apps.owncloud.com/content/show.php/Files+move?content=150271 ?

**Comment by PVince81** [comment] 2015-10-05 08:00
Duplicate of https://github.com/owncloud/core/issues/8570#issuecomment-42955348

Also, for auto-scrolling the list when dragging up/down: https://github.com/owncloud/core/issues/12329

**Closed by PVince81** 2015-10-05 08:00 UTC
Labels: enhancement
