### ISSUE TITLE
File listing in public shares truncated

### ISSUE THREAD

**Issue by codebfu** [owncloud/core#22303] opened 2016-02-11 08:29 UTC
### Steps to reproduce
1. Create a new folder with a large amount of files (tried with 1000 text files)
2. Create a public share link for the folder
3. Log out
4. Browse the link with IE (firefox and chrome works fine)

### Expected behaviour
I should be able to scroll down the whole file list

### Actual behaviour
I can only see the files that fits in the browser window, scrolling down will just show the footer.

### Server configuration
**Operating system**:
Ubuntu 14.04.3 (Host OS and Docker base image)

**Packages installed:**
apache2 php5 php5-gd php-xml-parser php5-mysql php5-json php5-mcrypt smbclient curl libcurl3 php5-curl php5-ldap

**Database:**
MariaDB 10.0.21 (galera cluster)

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:**
Database upgraded with each release, webserver docker image freshly built with owncloud archive download.

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.1
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - mail: 0.2.1
  - provisioning_api: 0.3.0
  - tasks: 0.8.1
  - templateeditor: 0.1
  - user_ldap: 0.7.1

Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - firstrunwizard
  - notifications
  - updater
  - user_external

### Client configuration
**Browser:**
IE  11.0.28

**Operating system:**
Windows 7 x64

#### Browser log

a) The javascript console log
No logs

**Comment by RealRancor** [comment] 2016-02-11 08:33
Very likely a duplicate of #21373 and #21203 which gets fixed in oC 8.2.3 with owncloud/files_pdfviewer#92

If disabling the files_pdfviewer is not solving this then its a duplicate of https://github.com/owncloud/core/issues/22289 and https://github.com/owncloud/core/issues/20044

**Comment by codebfu** [comment] 2016-02-11 08:46
I've updated the ticket with apps list, desactivating files_pdfviewer didn't fix the issue.

**Comment by RealRancor** [comment] 2016-02-11 08:47
@codebfu Then please close here on your own (close button below the comments field) and follow https://github.com/owncloud/core/issues/20044 which is still open and about this issue.

**Closed** 2016-02-11 08:49 UTC
