### ISSUE TITLE
Client halts syncing at directory with name containing special character : (colon)

### ISSUE THREAD

**Issue by fnadde42** [owncloud/core#23740] opened 2016-04-01 17:20 UTC
### Steps to reproduce
1. Install OwnCloud on laptop (no existing files on it)
2. Connect it to a ownCloud-instance (9.0.0.19)
3. Create a directory (probably also same error with a file) with special character `:` in it.
4. Sync will go until it hits the specific directory and then stops with the server returning an Internal Server Error.
### Expected behaviour

Client should be able to sync to the server and then proceed to download missing files.
### Actual behaviour

Client syncs for a couple of minutes but then halts at the directory containing the special character with the server giving the client an Internal Server Error. Client waits for a couple of minutes and then starts over from the beginning.
### Server configuration

**Operating system**: 
Raspbian GNU/Linux 8 
Linux 4.1.19-v7+ # 853 SMP armv7l GNU/Linux 

**Web server:** 
Server version: Apache/2.4.10 (Raspbian)
Server built:   Jan 23 2016 22:26:49

**Database:**
MySQL  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (armv7l) using readline 6.3

**PHP version:**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 24 2016 12:25:22) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
ownCloud 8.2.2 (stable) (if I remember correctly)

**Where did you install ownCloud from:**
Repository.

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc3fc4a5r31r',
  'passwordsalt' => 'notpepper',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'someexamplecloud.com',
    1 => 'someexamplecloud.com',
  ),
  'datadirectory' => '/owncloud-data',
  'overwrite.cli.url' => 'http://someexamplecloud.com:9999/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'dbname',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'noneofyourbeezwax',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.
#### Apache server error log

```
[Fri Apr 01 16:26:16.277097 2016] [:error] [pid 2063] [client 192.168.1.1:53388] PHP Fatal error:  Unsupported operand types in /var/www/owncloud/3rdparty/sabre/uri/lib/functions.php on line 181
[Fri Apr 01 18:21:30.515568 2016] [:error] [pid 2511] [client 192.168.1.1:41928] PHP Fatal error:  Unsupported operand types in /var/www/owncloud/3rdparty/sabre/uri/lib/functions.php on line 181

```
#### ownCloud log (data/owncloud.log)

**Note:** The OC log is two hours behind (UTC) where the Apache log is local time (UTC+2).

```
{"reqId":"RjkW34t1LziVZ9TVj\/G+","remoteAddr":"192.168.1.1","app":"PHP","message":"Unsupported operand types at \/var\/www\/owncloud\/3rdparty\/sabre\/uri\/lib\/functions.php#181","level":3,"time":"2016-04-01T14:26:16+00:00"}
{"reqId":"YvAIsDYiHQd3OKQtbdKX","remoteAddr":"192.168.1.1","app":"PHP","message":"Unsupported operand types at \/var\/www\/owncloud\/3rdparty\/sabre\/uri\/lib\/functions.php#181","level":3,"time":"2016-04-01T16:21:30+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documents\/Skola\/Termin%203\/Statistik%20A1\/Grupp%202:4"}
```
### Comments

The two instances where I, from two different computers, attempted to install and download all files via the client are visible in the logs.

I have client logs from both of the computers I tried with.

> EDIT: Bug seems to be due to special character `:`(colon) so renaming  the issue from _Client halts syncing at the same directory (Unsupported operand types at functions.php#181) OC 9.0.0_ to _Client halts syncing at directory with name containing special character : (colon)_
> 
> EDIT 2: Solved this by renaming directory and excluding special character `:`. Changing steps to reproduce to fit the problem.

**Quickfix:** Rename file/directory causing the problem to a name not containing special characters

**Comment by Xenopathic** [comment] 2016-04-01 21:47
Reproduced locally with master. Looks like it might be something to do with the colon `:` in the folder name, which should be URL encoded in DAV operations?

**Comment by fnadde42** [comment] 2016-04-01 22:33
I have restarted syncing on both computers and, while they are not done, they have passed the directory with the `:` in the name. Changing the name the did the trick.

**Comment by mpellegrin** [comment] 2016-04-18 14:19
@Xenopathic : If the encoding is wrong, is it possible that the bug is from client side, and not from DAV app ?

On the other hand, in [that other thread](https://github.com/fruux/sabre-dav/issues/374), they were arguing that the colon is a valid character for DAV URLs so it may not be a client issue but a Sabre issue ?

Viewing the code at ```owncloud/3rdparty/sabre/uri/lib/functions.php``` on line ```181``` the main problem seems to be the call to ```parse_url``` that identifies the colon as a separator for the scheme and returns ```false``` because that scheme is irrelevant, leading to an impossible use of ```+``` for array fusion (boolean + array = wrong):

```
    return
        parse_url($uri) + [
            'scheme'   => null,
            'host'     => null,
            'path'     => null,
            'port'     => null,
            'user'     => null,
            'query'    => null,
            'fragment' => null,
        ];
```

**Comment by Xenopathic** [comment] 2016-04-18 14:28
@mpellegrin Report this upstream, looks like the changes in Sabre DAV broke it.

**Comment by e-alfred** [comment] 2016-08-10 11:33
This bug still exists in 9.0.4. If a file is called test:213 the sync doesn't work because it is somehow interpreted as a port number as the upstream bug report says. If the file is called test:test for example, everything works. Will this be fixed anytime soon?

**Comment by craigrholmes** [comment] 2016-08-22 08:45
Indeed this is causing problems with Mac clients

**Comment by PVince81** [comment] 2016-12-01 17:01
Closing in favor of https://github.com/owncloud/core/issues/25479

**Closed by PVince81** 2016-12-01 17:01 UTC
Labels: app:dav, bug
