### ISSUE TITLE
Large file on CIFS backend get truncated when downloading from sharing link

### ISSUE THREAD

**Issue by dragon2611** [owncloud/core#21171] opened 2015-12-13 17:38 UTC
Steps to reproduce

Share a 4.1GB+ file that's located on an CIFS share via the owncloud webUI

No exceptions in log

Actual behaviour

When downloading via share link, file is truncated to ~120MB (Web interface reports correct size) yet the owncloud user who the file belongs to can browse to it and download it from the web interface without issue, problem only seems to manifest itself when accessing via share link.

Server configuration

Operating system:
ubuntu 14.04
Web server:
Apache / Behind Caddy reverse proxy  (Was also happening behind nginx)
Database:
mysql
PHP version:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 

ownCloud version: (see ownCloud admin page)
oc 8.2.1.

ownCloud log (data/owncloud.log)
Nothing recent in log

**Comment by dragon2611** [comment] 2015-12-13 17:59
I tried creating several large test files and it looks like something has a problem with files at 4GB+ I think this file just happened to be right on a limit.

The problem affects the web interface rather than just the sharing module.

Files slightly over 4GB tend to truncate, I expect some kind of wrapping occurring as it depends on how much over 4GB the files are depending on what size download you are getting.

I'm also confident it's not likely caddy (the server i'm using for the proxying) as i've just proxied a much larger 10GB file from a different backend through it without issue.

**Comment by PVince81** [comment] 2015-12-14 10:53
Is your server running on a 32-bit server or 64-bits ? 

CC @icewind1991

**Comment by dragon2611** [comment] 2015-12-14 11:20
It's a 64bit ubuntu 14.04 LXC container.

**Comment by PVince81** [comment] 2016-02-12 14:01
Ok, so if I understand well it's not sharing, but downloading on the regular file list also truncates the file ?

Could be a SMB / smbclient / Samba version issue ?
Do you have the php5-libsmbclient module installed ?

@icewind1991 does the SMB backend support transfering large files ?

**Comment by icewind1991** [comment] 2016-02-12 14:31
I was able to download a 4.2gb file just fine from an smb mount

**Comment by tlhonmey** [comment] 2016-04-25 19:54
I'm seeing something similar since I upgraded to 8.2, but in my case it's showing the truncated size in the file list.  The file that gets downloaded appears to be correct, but is truncated to the improperly-detected length.

Attaching to the samba share directly reports the correct length and transferring the file over it results in the entire file arriving properly.  

I've tried upgrading apache and php on the owncloud host to no effect.  I'll try upgrading samba at some point, but there's currently a dependency snarl going from samba3 to samba4 that will take me a little while to iron out.

**Comment by PVince81** [comment] 2016-06-30 16:27
@jvillafanez have you observed such issues before ?

**Comment by jvillafanez** [comment] 2016-07-01 07:36
No, I don't think we've tested downloads with such a big file.

I found some links that might be interesting to check if the SMB server is in windows:
* https://discussions.apple.com/thread/4781793?tstart=0
* http://answers.microsoft.com/en-us/windows/forum/windows_vista-networking/large-file-transfer-over-home-network-freezes-and/94ec122d-6b9f-4bf8-bbc6-324db79e05c8?page=2

**Comment by PVince81** [comment] 2016-12-22 08:56
Is the returned size always exactly the same 120 MB value at the byte level or does it vary between say 119 MB and 121 MB during each try ? If the value is random, it could be related to timeouts.

**Comment by PVince81** [comment] 2016-12-22 08:57
@dragon2611 please confirm, see previous comment

**Comment by PVince81** [comment] 2017-02-06 10:29
@davitol can you try reproducing this ?

**Comment by Witmann** [comment] 2017-02-09 11:41
@PVince81 I'm facing the same problem since month, on a 6.7 GB file, only 2 GB are downloaded, always 2 GB. When I put the same file in an Owncloud user's directory (so out of the samba share) the download is done proprely. So it's only when I request SMBclient that it doesn't work.

**Comment by ghetto-ch** [comment] 2017-03-21 23:29
Looks like I have the same problem, Ubuntu 16.04, oc running in lxc, smb shared from lxc host. Running latest oc installed via apt-get, php7.
If you need any info please let me know

**Comment by jvillafanez** [comment] 2017-03-22 07:43
@ghetto-ch include your server configuration. Any additional information is appreciated.

**Comment by jvillafanez** [comment] 2017-03-22 08:03
If you're using the php-libsmbclient library, could you try the 0.9.0 version? it might have a fix for this issue (https://github.com/eduardok/libsmbclient-php/commit/f66fafa7a379de3ea3d60d7ce07385c312704ed5)

**Comment by ghetto-ch** [comment] 2017-03-22 18:15
@jvillafanez here is my configuration:

Host: Ubuntu 16.04 server with LXC. All packages from standard repos updated to latest version. Folders shared via samba 4.3.11 to owncloud LXC guest.

LXC guest: Ubuntu 16.04. OC installed via apt-get form OC repos, latest version. All dependencies installed from standard packages. Configured with SSL and TLS (letsencrypt cert).
PHP 7.0.15
Apache 2.4.18
mysql 5.7.17
smbclient 4.3.11
libsmbclient 4.3.8

php-libsmbclient is not installed, therefore shouldn't be the problem?

**Comment by Witmann** [comment] 2017-03-22 23:29
@ghetto-ch 

Same config as you, just the web server is an nginx. With php-libsmbclient it's worth.

**Comment by jvillafanez** [comment] 2017-03-23 11:28
Are both of you connecting to a "native" samba or windows? I mean, not to a VM with samba o windows.
```
|------------              -----
|------      |            |
|| VM | host | ---------> | windows / samba
|------      |            |
|------------              -----
```

I'm aware of connection issues if the samba server is inside a docker container, but I haven't seen any problem if the target of the connection is the host.

It's recommended that php-libsmbclient is installed and being used. I've detected an issue downloading a file in a slow connection using the smbclient wrapper, which shouldn't happen with the native php-libsmbclient library. Make sure the php-libsmbclient version is 0.9.0 or greater.

**Comment by ghetto-ch** [comment] 2017-03-23 12:05
@Witmann
thank you for the information!

@jvillafanez
the ubuntu host is on bare metal and the lxc with owncloud is running on it.
I will try to install php-libsmbclient form source. Is there anything I should do to tell owncloud to use it? Just have it in the path is enough?

**Comment by jvillafanez** [comment] 2017-03-23 12:33
I think https://github.com/eduardok/libsmbclient-php has enough information to build the library from source. The library should be available for apache (or any other websever). You can create the usual phpinfo file and check the library is properly loaded.

ownCloud will use the native library if available, falling back to the smbclient wrapper otherwise. There is no change needed.

You can set the log level to debug add in the config/config.php:
```
'wnd.logging.enable' => true
```
you should see a `using native libsmbclient` in the logs when you're connecting to the SMB server. Note that these log are for debugging and will likely flood the log file so revert the changes once you're done.

**Comment by ghetto-ch** [comment] 2017-03-23 17:44
@jvillafanez 

I installed the library version 0.9.0 via PECL and it did wonders! I could download a 8.2GB file without problems. I will do some more tests (upload and download) and report the results.

**Comment by ghetto-ch** [comment] 2017-03-25 07:24
After multilple tests I confirm the problem is solved.
@jvillafanez @Witmann  thank you for your help

**Comment by PVince81** [comment] 2017-04-13 12:46
how about the others ?

**Comment by Witmann** [comment] 2017-04-26 17:44
Almost solved :). 80% of files are "downloadable" proprely, 20% are not, I think there is nothing to do about it, I guess it's a bad "communication" between PHP and Samba.

**Comment by jvillafanez** [comment] 2017-04-27 06:49
As usual, I recommend to check with smbclient. If it can't download the file for whatever reason (corrupted file, network connection cut, etc) ownCloud won't be able to download it neither.

**Comment by Witmann** [comment] 2017-04-27 13:17
Yes sir, I use a lot my smb shares with Windows clients, and that work great (never had a prob.).

**Comment by jvillafanez** [comment] 2017-04-27 14:30
Install the smbclient (if not already installed) in the same host ownCloud is running and test from there. Using other tools isn't a good idea because it might use they're own implementation (such is the case of windows), so you might be able to connect from windows because it's doing black magic, but not from smbclient because of misconfiguration, network issues or whatever.

The closest the tests you're doing to what ownCloud is doing, the better to know what's happening. As an example, you could have dns issues in the ownCloud's host and you might not able to connect to the target SMB server, but you could access from any other windows. That's why checking from windows isn't valid. It might be possible to detect bigger problems if you can't connect from there, but that's all.

**Comment by PVince81** [comment] 2017-12-12 15:41
Closing due to lack of feedback. Likely an environment issue.

**Closed by PVince81** 2017-12-12 15:41 UTC
Labels: app:files_external, bug, sev2-high
