### ISSUE TITLE
An exception occurred while executing ' DELETE FROM `oc_lucene_status`

### ISSUE THREAD

**Issue by dhuyvetter** [owncloud/core#17011] opened 2015-06-18 10:44 UTC
I'm trying to update my ownCloud to version 8.0.4, I had trouble with my install, showing an error concerning config folder not being writeable, even though it had been running fine for a while. So I downloaded and unpacked the latest version, put that in my web root, changed the data folder to a separate directory and updated my config file accordingly.

Now when I run the update I get the error message:

> An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

I'm not sure which version of ownCloud I had before. If anyone can tell me how to check, I'll gladly report it here.

**Comment by DeepDiver1975** [comment] 2015-06-18 10:50
duplicate of #16008

**Closed by DeepDiver1975** 2015-06-18 10:50 UTC

**Comment by RealRancor** [comment] 2015-06-18 11:05
Ref to the documentation part:

https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting
