### ISSUE TITLE
Problems with apps after installing ubuntu package.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13903] opened 2015-02-04 17:42 UTC
### Steps to reproduce
Install owncloud package in Ubuntu >14.XX:

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud

Deal manually with #13900, #13901 and #13902 if they aren't fixed yet.

**Logs**
```
{"reqId":"1df174bc75edf7e64f48a53f16da3313","remoteAddr":"10.40.40.84","app":"PHP","message":"Class 'OCA\\Files\\App' not found at \/var\/www\/html\/owncloud\/apps\/files_sharing\/appinfo\/app.php#37","level":3,"time":"2015-02-04T17:28:24+00:00"}
{"reqId":"1e36b9ac12ca6fc95491c395d9babede","remoteAddr":"10.40.40.84","app":"PHP","message":"Class 'OCA\\Files\\App' not found at \/var\/www\/html\/owncloud\/apps\/files_sharing\/appinfo\/app.php#37","level":3,"time":"2015-02-04T17:29:19+00:00"}
```

### Expected behaviour
Owncloud opens in the browser.

### Actual behaviour
A white screen appears and those logs appear on owncloud.log.

**Comment by karlitschek** [comment] 2015-02-04 17:54
@jnweiger

**Comment by SergioBertolinSG** [comment] 2015-02-06 08:59
Hi @LukasReschke, Do you know what is missing here?

**Comment by LukasReschke** [comment] 2015-02-06 11:00
That shouldn't happen with a normal master checkout. Best bet is that the autoloader can't find those things because of a package mixup?

**Comment by jnweiger** [comment] 2015-02-06 21:24
@SergioBertolinSG Is this still reproducable with current RC2 packages?

**Comment by atitarenko** [comment] 2015-02-07 15:40
The issue is observed with both RC2 and recent 8.0.0-1 packages (taken from  http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.04/)

**Comment by jnweiger** [comment] 2015-02-08 18:20
I see a white page when php-pdo is not installed.

**Comment by twouters** [comment] 2015-02-09 09:37
`php-pdo` is installed and enabled on my Debian (7.0) system.
I'm getting this error when running `su - www-data -c 'php /var/www/owncloud/occ upgrade'`

    Turned on maintenance mode
    Checked database schema update
    Updated database
    PHP Fatal error:  Class 'OCA\Files\App' not found in /var/www/owncloud/apps/files_sharing/appinfo/app.php on line 37

**Comment by SergioBertolinSG** [comment] 2015-02-09 10:30
Tested with 8.0.0-1 version, still happening

```
{"reqId":"cc66967e35f629ad88880ca2b47449ec","remoteAddr":"10.40.40.77","app":"PHP","message":"Class 'OCA\\Files\\App' not found at \/var\/www\/owncloud\/apps\/files_sharing\/appinfo\/app.php#37","level":3,"time":"2015-02-09T10:24:10+00:00"}
```

**Comment by atitarenko** [comment] 2015-02-09 18:50
With 8.0.0-2, issue is no longer observed.

**Comment by jnweiger** [comment] 2015-02-09 19:13
This is a duplicate of https://github.com/owncloud/core/issues/13991 -- fixed.

**Closed by jnweiger** 2015-02-09 19:13 UTC
Labels: packaging

**Comment by SergioBertolinSG** [comment] 2015-02-10 10:26
Working fine after installing 8.0.0-5 packages version.
