### ISSUE TITLE
Shared Link - Public (Anon) Upload - Not Working (8.2)

### ISSUE THREAD

**Issue by dhxgit** [owncloud/core#20143] opened 2015-10-29 11:03 UTC
Owncloud Version: 8.2
OS: Ubuntu 14.04.3

Configuration:
Public Upload in shared links is allowed, no password.

Issue:
After upgrading to Owncloud 8.2 uploading a file to a shared link does not work anymore. (It did work fine with 8.1.x)

There is no communication between the clientbrowser (Chromium) and the http-server during file-selection... There is only a JavaScript exception within the clientborwser:

Uncaught TypeError: Cannot read property 'fileList' of undefined
OC.Upload.checkExistingFiles @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:977
o.add @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:977
t.Widget._trigger @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:23
(anonymous function) @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:1019
x.extend.each @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:4
e.widget._onAdd @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:1019
(anonymous function) @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:16
(anonymous function) @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:1023
c @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:4p.add @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:4
r.always @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:4
e.widget._onChange @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:1023
(anonymous function) @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:16
r @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:22
x.event.dispatch @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:5
v.handle @ a1efc74e66b7fa8bf271e8c5dd4e683d.js:5

**Comment by nickvergessen** [comment] 2015-10-29 11:33
Works for me, but seeing that you have asset pipeline enabled, mind purging the assets directory?
I assume the files still contain old content.

**Comment by nickvergessen** [comment] 2015-10-29 11:35
@MorrisJobke what do you think, I have two things on my mind:
1. Purge the asset directory on update
2. Disable asset pipelining on the update screen

**Comment by RealRancor** [comment] 2015-10-29 11:57
Might be a dup of https://github.com/owncloud/core/issues/20112 and https://github.com/owncloud/core/issues/19922 which seems to get fixed with 8.2.1

**Comment by dhxgit** [comment] 2015-10-29 12:03
Purging the assets did the trick.

It might be a good idea to add this to "maintenance:repair" in occ.

Thanks.

**Comment by RealRancor** [comment] 2015-10-29 12:07
Mhhh, schould be already done according to the docs:

> and will be automatically refreshed whenever ownCloud or one of its apps is updated.

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/js_css_asset_management_configuration.html

**Comment by MorrisJobke** [comment] 2015-10-29 13:02
Will be fixed in 8.2.1 https://github.com/owncloud/core/pull/19956

**Comment by MorrisJobke** [comment] 2015-10-29 13:03
Duplicate of https://github.com/owncloud/core/issues/19922

**Closed by MorrisJobke** 2015-10-29 13:02 UTC
Labels: needs info
