### ISSUE TITLE
The options/permissions in federated sharing are not visible

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16436] opened 2015-05-19 09:37 UTC
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Send a file to a user of another server

### Expected behaviour
The different permissions should be visible

### Actual behaviour
Only 'Can edit' is visible. This behaviour only happens in federated sharing

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9 & Firefox
![captura de pantalla 2015-05-19 a las 11 24 58](https://cloud.githubusercontent.com/assets/10596560/7699766/a3c399e6-fe1a-11e4-853b-6671606bcffe.png)
![captura de pantalla 2015-05-19 a las 11 27 00](https://cloud.githubusercontent.com/assets/10596560/7699773/a9c92dd8-fe1a-11e4-8719-70cee750a0a1.png)

**Comment by DeepDiver1975** [comment] 2015-05-19 11:43
I guess this is by intention @schiesbn @jancborchardt @MTRichards THX

**Comment by PVince81** [comment] 2015-05-20 10:42
This is by design for now.

Federated sharing is based on public links which only had "read-only" or "read-write" permissions.

So here would rather be the question: do we want to have extended permissions too ?
I'd personally rather we remove the extra permissions from the regular shares to simplify everything and make it more obvious: https://github.com/owncloud/core/issues/12970

Tagging as enhancement for now.

**Comment by PVince81** [comment] 2015-05-20 10:43
Also, moving to 8.2. Even if we were to add these, this is not something that can easily be done in 8.1

**Comment by jancborchardt** [comment] 2015-05-21 14:13
> I'd personally rather we remove the extra permissions from the regular shares to simplify everything and make it more obvious: #12970

@PVince81 yes please. I was always against adding this clusterf$%& in the first place. :)

**Comment by rperezb** [comment] 2015-05-22 13:14
ey @carlaschroder could it be worthy to document this?
thx

**Comment by schiesbn** [comment] 2015-06-29 09:04
Let's close it. This is the intended behavior and it was documented by @carlaschroder

**Closed by schiesbn** 2015-06-29 09:04 UTC
Labels: documentation, enhancement - proposed, feature:federated-cloud-sharing, sev2-high
