### ISSUE TITLE
External storage sharing options not easily found

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23348] opened 2016-03-17 11:31 UTC
It appears it is not always clear to users that we now by default disable sharing of files on external storages. And also not that clear how to enable it.

I suggest we add a note to the bottom of the sharing stating that sharing options per external storage can be configured in the external storage settings.

Or maybe we should open the configs by default when dding a new storage.

CC: @owncloud/designers

**Comment by PVince81** [comment] 2016-03-17 11:35
Similar to https://github.com/owncloud/core/issues/23316

**Comment by RealRancor** [comment] 2016-03-19 18:28
> It appears it is not always clear to users that we now by default disable sharing of files on external storages. And also not that clear how to enable it.

Raised: https://github.com/owncloud/documentation/issues/2281

But how should a user knows that if its not documented somewhere?

**Comment by PVince81** [comment] 2017-12-18 13:52
duplicate of https://github.com/owncloud/core/issues/17795

**Closed by PVince81** 2017-12-18 13:52 UTC
Labels: app:files_external, design, enhancement, feature:sharing
