### ISSUE TITLE
upgrading owncloud 8.2 when installed from web installer

### ISSUE THREAD

**Issue by bah0071** [owncloud/core#21158] opened 2015-12-11 15:11 UTC
after installing ownlcoud using the web installer it seems that using the update tool in admin panel does not work as it is not able to transfer the files from the tmp folder (after download an extract) to the existing ownloud folder locations...

seems there is an ownership issue where the ownership is set to "apache"

there should be a method to upgrade owncloud using  a web installer for those who installed owncloud using the web installer (where it would ask for your admin login and password before proceeding to the upgrade) 

if this issue is fixed onthe next update where we can use the updater app then the web installer upgrade is not needed

**Comment by karlitschek** [comment] 2015-12-11 15:38
Please check owncloud.org/support for different option where to ask this question. Thanks. The updater will be rewritten for 9.0 anyways.

**Comment by PVince81** [comment] 2015-12-14 11:03
For people who used the web installer, they should upgrade using the updater app.
Now if you say that there are permissions issue, maybe the web installer did not set permissions properly ?

@VicDeo

**Comment by VicDeo** [comment] 2015-12-14 11:17
> For people who used the web installer, they should upgrade using the updater app.

@PVince81 
true. But there is  https://github.com/owncloud/updater/pull/192 that is to be released with 8.2.2

@bah0071 might be  a duplicate of  https://github.com/owncloud/updater/issues/189

**Closed** 2016-03-04 18:02 UTC
Labels: feature:update
