### ISSUE TITLE
Moving a file with versions into an external storage folder and restoring a previous version can't be decrypted.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16351] opened 2015-05-14 08:57 UTC
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create a file "versions.txt"
5. Edit and save the file multiple times to create versions
6. Open the "Versions" dropdown and see that versions exist
7. Mount a SFTP external storage to "/sftp"
8. Move "/versions.txt" to "/sftp"
9. Open the "Versions" dropdown again
10. Restore a previous version.
11. Open the file.

### Expected behaviour
File can be opened an text is still readable.

### Actual behaviour
File can't be decrypted.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by karlitschek** [comment] 2015-05-14 16:15
@schiesbn FYI

**Comment by nickvergessen** [comment] 2015-05-15 09:20
Looks like we need to decryption all versions when moving a file Oo?

**Comment by PVince81** [comment] 2015-05-15 14:29
Duplicate of https://github.com/owncloud/core/issues/13668

**Closed by PVince81** 2015-05-15 14:29 UTC
Labels: app:encryption, app:files_external, app:files_versions, bug, sev1-critical
