### ISSUE TITLE
[Share api] The path of a shared by link file is not correct inside a shared folder when it was shared by link in root

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#9401] opened 2014-07-03 07:24 UTC
### Steps to reproduce
1. login as user1
2. There is a folder “a” which has two pictures inside: “Photo.PNG” and “Photo2.PNG”
3. Share “Photo.PNG” with user2
4. Then, share folder “a” with user2
5. Login as user2, and share by link “Photo.PNG” which is in root
In the web, if you access to shared folder “a”, “Photo.PNG” is shown as shared by link.
But using share api, the path is not correct (so in mobile device it’s not possible to shown that file as shared by link). 
It can be checked using poster
	Url: server/ocs/v1.php/apps/files_sharing/api/v1/shares?path=a&subfiles=true
	User Auth: user2/user2
	Click on GET

The path is <path>/Photo.PNG</path> and it should be <path>/folder/Photo.PNG</path>

If user2 share by link “Photo2.PNG” inside folder “a”, you can see that the path is <path>/folder/Photo2.PNG</path>. 

### Expected behaviour
The path in the share api is <path>/folder/Photo.PNG</path>
 instead of <path>/Photo.PNG</path>

### Actual behaviour
The path is <path>/Photo.PNG</path>

### Client configuration
Operating system: MacOs 10.7.5
Owncloud version: It was tested in daily
{"installed":"true","version":"7.0.0.3","versionstring":"7.0 beta 1","edition":""}

**Comment by enoch85** [comment] 2015-03-20 17:50
ping @schiesbn

**Comment by PVince81** [comment] 2015-10-27 11:03
@enoch85 please don't assign people, it won't magically make them look at the ticket. Furthermore it will discourage other people who might be able to help to also look at the ticket, because they'd think someone is already investigating.

@rullzer @schiesbn

**Comment by PVince81** [comment] 2015-10-27 11:07
I think this is expected behavior and I see this happening on 8.2.0 too. The originally linked file was "/Photo.PNG" and not "a/Photo.PNG".
I don't think we can add both paths.

The web UI uses the file id instead of the path to recognize shares.

@schiesbn @rullzer what do you think ?

**Comment by rullzer** [comment] 2016-03-03 08:05
With the new resharing behaviour it is always the owner that is sharing the file. (In case of a reshare that user is just initiating). So now showing the path for the owner makes sense.

This `bug` is about how we internally share stuff. We don't really share a path. We share a fileid. So we don't have to do a gazillion updates when we move a folder with lots of shares in it. However because of this the only real path we can efficiently resolve to is the path of the data owner.

Closing this as it is expected behaviour.

**Closed by rullzer** 2016-03-03 08:05 UTC
Labels: bug, dev:ocs, feature:sharing
