### ISSUE TITLE
the log has error when sharing files by "Email link to person"

### ISSUE THREAD

**Issue by kenyang001** [owncloud/core#24503] opened 2016-05-09 10:08 UTC
### Steps to reproduce

1.on owncloud 9.0.2, when you sharing a folder/files by "Email link to person"
the owncloud logs has an error log,"Error   PHP Undefined index: id at /var/www/owncloud/core/ajax/share.php#229",
meanwhile, the email function(send/receive) works
### Expected behaviour

Tell us what should happen
no error log
### Actual behaviour

he owncloud has an error log,"Error PHP Undefined index: id at /var/www/owncloud/core/ajax/share.php#229"
### Server configuration

**Operating system**:
ubuntu14.04
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
from 8.2.4
**Where did you install ownCloud from:**
manually upgrade from 8.2.4
**Signing status (ownCloud 9.0 and above):**
9.0.2

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

everything is ok. no integrity files

**List of activated apps:**

```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

```

**The content of config/config.php:**

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```

Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)
```

Insert your ownCloud log here

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by bcutter** [comment] 2016-05-22 17:03
Same here on OC v9.0.2.2. OC-Log is flooded with those messages when sharing a file by link:

```
Level	App	Message	Time
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
Error	PHP	Undefined index: id at /var/www/owncloud/core/ajax/share.php#229	7 minutes ago
```

**Comment by JSoko** [comment] 2016-06-02 08:15
Hello,

same Errors in Log here on 9.02...

Ciao,
Joachim

**Comment by ageru** [comment] 2016-06-07 13:35
I can confirm this as well. I didn't send the link via mail: I just fiddled with the email  field (testing autocomplete) but didn't send a notification. Still got the error.

Gentoo x86, Nginx 1.10, MariaDB 10, PHP 5.6 with APCu.

Owncloud 9.02, upgraded from 8.2.5.

**Comment by PVince81** [comment] 2017-01-13 15:23
Can you guys check if this is still happening in 9.0.7 or 9.1.3 ?

**Comment by JSoko** [comment] 2017-01-13 17:33
Sorry, I'm now on Nextcloud, where this error does't exist (anmimore?), so I can't check it for owncloud...

**Comment by kenyang001** [comment] 2017-01-14 01:44
Hi, i am still using 9.0.4. will upgrade it later to see if it works.

**Comment by ageru** [comment] 2017-01-16 11:38
Hi,

I'm on 9.0.7. I tried to reproduce the issue, both by using my steps and those of the parent. Nothing showed up in the logs and the functionality worked as expected.

Looks like it's fixed to me.

Many thanks.

**Comment by PVince81** [comment] 2017-01-16 13:07
Thanks for the feedback, closing

**Closed by PVince81** 2017-01-16 13:07 UTC
Labels: bug, feature:sharing

**Comment by creol** [comment] 2017-02-11 01:32
I am still experiencing this issue on 9.1.3. Did anyone find a resolution?


Operating system:
Ubuntu 15.10
Web server:
apache2
Database:
mysql
PHP version:
PHP 5.6.29
ownCloud version: (see ownCloud admin page)
9.1.3
Updated from an older ownCloud or fresh install:
from 8.2.7
Where did you install ownCloud from:
docker owncloud:913
Signing status (ownCloud 9.0 and above):
??

**Comment by kdslkdsaldsal** [comment] 2017-02-11 12:29
@creol Please create a new issue and make sure that you're filling out the full issue template shown when creating a new issue.
