### ISSUE TITLE
filelist.js, condition result depends on browser used

### ISSUE THREAD

**Issue by tyrylu** [owncloud/core#24211] opened 2016-04-22 17:02 UTC
In filelist.js (files app) in the handler for file clicks, the condition at line 583:
`if (!this._detailsView || $(event.target).is('.nametext') || $(event.target).closest('.nametext').length)`
depends on the current browser. In Ie, during a simple click on a subfolder the correct (e. g. the first) branch is taken, in Chrome and Firefox 45 the second and the content is not displayed, the title not changed etc.
I could not investigate more, because the current state of javascript debuggers in browsers is horrible, at least from the accessibility point of view. Tried on owncloud master, latest commit as of this time.
Browser versions: Ie 11, Firefox 45, Chrome 50.
Os: Windows 10 64-bit, if that matters and more variables are at play there.

**Comment by PVince81** [comment] 2016-04-25 10:03
Can you be more high level ? Do you mean that clicking on a row in IE11 on master is broken ?

It works for me in Chromium 49.0 at least.

**Comment by tyrylu** [comment] 2016-04-25 13:08
No, i meant to say that in Ie 11 it works fine, Firefox and Chrome is broken. There's a negligible probability of the screen reader interfering somewhat (but not blocking the click event altogether). The initial debugging was quite crude - putting an alert in both branches and seeing what happens.

**Comment by PVince81** [comment] 2017-04-06 10:17
still not clear what the problem is or what needs to do.

either clarify or submit a PR to fix this.
Closing for now.

**Closed by PVince81** 2017-04-06 10:17 UTC
Labels: app:files, bug, sev4-low
