### ISSUE TITLE
Deleted Folders on Client not showing in Trash

### ISSUE THREAD

**Issue by asy32x** [owncloud/core#15009] opened 2015-03-18 16:34 UTC
Simple as it is, i delete a folder with one file in it on the windows7 filesystem, it is deleted on the website and not showing in the trashbin. when i delete just the file without the folder, the file shows in the trash.

version server: 8.0.2
version client: 1.8

deleting a folder on the webinterface works like it should, folder is in trashbin and can be restored.

at which point is the delete process, i maybe can fix this bymyself and commit.

**Comment by karlitschek** [comment] 2015-03-18 17:52
Can you please  post a full bug report using the issue template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by PVince81** [comment] 2015-03-19 21:03
Was the trash full ? The trash auto-expires files if its size would be > 50% of the total space.
This means that if the files would not have fit (too big), then they would be deleted directly.

**Comment by DeepDiver1975** [comment] 2015-03-23 10:28
not reproducible - as soon as a file is deleted via WebDAV the file is moved to the trash

**Comment by asy32x** [comment] 2015-03-24 01:13
are there different calls for the api when i synchronize a file via the client (deleted folder) and the website (because there its working)

**Comment by DeepDiver1975** [comment] 2015-03-24 06:44
Client uses webdav. The webui has its own call.

**Comment by aleishman01** [comment] 2015-04-08 13:28
I have this same issue.  This is not a delete via the web interface...  it's a delete via the file system (e.g.: Windows Explorer=>delete files). They are not moved to the ownCloud trash.

This is a serious issue as we are using ownCloud to sync 10's of thousands of images from clients all over the United States every week.

I can contact them and have them put the images back but I don't want that as my full time job.

**Comment by PascalAnimateur** [comment] 2015-04-08 17:47
Same issue, the files in the root folder are present in the trashbin and can be restored, but the folders and their files are nowhere to be found ! But in my case, maybe the trash was full as suggested by @PVince81 ...

**Comment by asy32x** [comment] 2015-04-08 19:24
i have installed the latest version of client / server - still happening when you delete something in the windows file system. server is Ubuntu 14.04 LTS 64bit - i have 380gb free disk space

**Comment by Peac** [comment] 2015-04-11 13:20
Got the same issue, if I delete a folder on my local system (Win 7 x64, Client 1.8.0) it won't appear in the trashbin of ownCloud (ownCloud 8.0.2 (stable)). If i delete the folder via webinterface it appears in the trashbin.

Log:
Error 	PHP 	opendir(/XXX/owncloud/data/XXX/files_trashbin/files): failed to open dir: No such file or directory at /XXX/owncloud/lib/private/files/storage/local.php#78

**Comment by PVince81** [comment] 2015-04-13 08:12
Hmmm, that error says that the trashbin folder hasn't been created locally for that user. Can you check if the "files_trashbin/files" folder exists ? If not, try creating it manually, make sure it has the permissions for the web server like other folders.

Still, that doesn't explain why the one works but not the other.

**Comment by Peac** [comment] 2015-04-13 16:59
The "files_trashbin/files" folder exists and has the same permissions like the other folders of owncloud.

**Comment by ether0** [comment] 2015-04-21 06:59
Same thing with us. New Owncloud server install and new Windows client install from yesterday. Deleted folders from the Windows client do not show in the Trash. They do show if we delete from web interface.

Error log shows

Error	PHP	Undefined index: /mnt/datadisk/owncloud/data/dd/files_trashbin/versions/dig.d1429556717 at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140

**Comment by jptechnical** [comment] 2015-05-08 23:49
DeepDiver1975, please consider reopening this bug. As you can see, and with a bit of googling, there are a ton of people reporting this. I have recently installed two separate ownCloud instances, and have tried the windows client versions 1.70, 1.80, 1.81 and the all result in the same thing. 

Basically, a bunch of us are screwed, because we have to come up with some way of manually backing up stuff and somehow discovering when someone inadvertently deletes a folder from their windows machine. Please reconsider.

**Comment by rickepnet** [comment] 2015-05-11 03:05
Yes please DeepDiver1975, please consider reopening this bug. This was a shocker when I found out about it.

**Comment by rickepnet** [comment] 2015-05-11 03:13
This only happens if you delete the whole folder if you delete a file out of the folder it does show up in the Deleted Files on the web interface. But if you delete a folder they are gone with no way to get them back.

**Comment by rickepnet** [comment] 2015-05-11 03:26
One other thing that is interesting. I set the server Log level to Everything. When i deleted a single file I see that in the log no problem but when I delete a whole folder from my Windows 8 machine I sync to the log show nothing. But in Activity it shows I deleted it. Strange

**Comment by PVince81** [comment] 2015-05-11 11:40
This ticket was never closed. The closed one you might have seen in the history was another duplicate ticket.

Would you guys care filling out the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md to provide more info about your environments ? This could help reproduce the issue.

Thanks.

Does it also happen if you select multiple files using the checkboxes and delete them ?
Does it happen when deleting a folder with a small 1Kb file inside it ? (because big folders would trigger trash expiration)

**Comment by DeepDiver1975** [comment] 2015-05-11 12:10
The ability to read can help - sorry to everybody in this thread.

Deleting files works as expected - but deleting a FOLDER does not!

@schiesbn maybe related to the trashbin storage wrapper?

@nickvergessen can I ask you to have a look? THX

@karlitschek @MTRichards I'm setting this to 8.1 with high sev - we shall not eat data .....

**Comment by MTRichards** [comment] 2015-05-11 13:08
agreed.

**Comment by karlitschek** [comment] 2015-05-11 13:17
yes please

**Comment by PVince81** [comment] 2015-05-11 13:35
Does a WebDAV DELETE (not sync client) on a folder moves it to trash for you guys ?

I wonder if the sync client is deleting every file one by one instead of doing a DELETE call directly on the folder. Because doing that would put all files into the root of the trashbin instead of inside a folder.

**Comment by DeepDiver1975** [comment] 2015-05-11 13:39
Well - I just reproduced the issue using cadaver.

Deleting a folder with cadaver doesnot not move the folder to the trash.
In the past I was testing this with files only - which works

**Comment by PVince81** [comment] 2015-05-11 13:41
Damn, I guess it means bisect time.

**Comment by DeepDiver1975** [comment] 2015-05-11 13:42
> Damn, I guess it means bisect time.

No need I'd say - it's the trash storage wrapper I'd guess ....

**Comment by PVince81** [comment] 2015-05-11 13:42
I can have a look later today.

**Comment by rickepnet** [comment] 2015-05-11 13:46
Using WebDAV if you delete the folder it does put the files in the root of the delete files. It would be nice if it keep them in a folder but it is better that what the sync client does.

**Comment by PVince81** [comment] 2015-05-11 13:48
Hmmm, but the sync client is supposed to do exactly the same: do a DELETE on the folder itself.

Anyway, in all cases the expected behavior is to keep the folder structure in the trashbin.

**Comment by DeepDiver1975** [comment] 2015-05-11 13:51
> Using WebDAV if you delete the folder it does put the files in the root of the delete files. It would be nice if it keep them in a folder but it is better that what the sync client does.

with which version?

**Comment by DeepDiver1975** [comment] 2015-05-11 13:57
> Well - I just reproduced the issue using cadaver.
> 
> Deleting a folder with cadaver doesnot not move the folder to the trash.
> In the past I was testing this with files only - which works

this was tested on master branch ...

**Comment by PVince81** [comment] 2015-05-11 14:51
Confirmed happening on v8.0.3 :frowning: 

I'll try and debug this.

**Comment by PVince81** [comment] 2015-05-11 14:58
Ok got it. When deleting over the web UI, it uses `unlink($folder)` but over WebDAV it does `rmdir($folder)`.

And the trashbin wrapper only implements `unlink()`. The other one, `rmdir()` passes through.

**Comment by DeepDiver1975** [comment] 2015-05-11 15:02
refs https://github.com/owncloud/core/issues/15999 @PVince81

**Comment by DeepDiver1975** [comment] 2015-05-11 15:02
> And the trashbin wrapper only implements unlink(). The other one, rmdir() passes through.

we need to kill all that no webdav operations in the files app

**Comment by PVince81** [comment] 2015-05-11 16:08
Fix is here: https://github.com/owncloud/core/pull/16247

**Comment by rickepnet** [comment] 2015-05-11 23:33
Please excuse my ignorance where does this leave us?

**Comment by PVince81** [comment] 2015-05-12 08:30
So far the best is to wait for the pull requests to be merged.
Then once it is done you can either wait for 8.0.4 or 8.1 to be released.
If not, then you can patch your install with it.

But for now, the fixes need to be reviewed first.

**Comment by jptechnical** [comment] 2015-05-13 22:16
@PVince81, where is the best place to watch for this update? I gather that it is on the server side, not a client side release update?

**Comment by PVince81** [comment] 2015-05-15 09:22
The 8.1 fix was merged: https://github.com/owncloud/core/pull/16247

Now the 8.0 backport needs to be reviewed https://github.com/owncloud/core/pull/16248
@jptechnical you could subscribe to the PR above to get updates.

**Closed** 2015-05-15 13:28 UTC
Labels: app:files_trashbin, bug, regression, sev2-high

**Comment by SergioBertolinSG** [comment] 2015-05-28 11:07
Tested in stable8, working fine.

**Comment by jospoortvliet** [comment] 2015-06-09 19:11
FYI, dear users, this will be released as part of 8.0.4, today or tomorrow.
