### ISSUE TITLE
install an app if directory is still there.

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#14711] opened 2015-03-05 14:54 UTC
When upgrading to a new owncloud version via the packages you can end up with the situation that an old app is still siting in the apps directory. This is deactivated correctly but a new and compatible apps can´t be installed from the app store because the old directory is still in the apps directory.
See here for the error:
https://www.bitblokes.de/2015/03/das-upgrade-auf-owncloud-8-0-1-hat-echt-nicht-alle-latten-am-zaun

If we detect during installation of an app that there is already a directory with the same name than we have to create an "legacy" directory (if it is not already there) and move the old directory into it.

**Comment by PVince81** [comment] 2015-03-05 15:10
I guess @georgehrke isn't around ?

**Comment by PVince81** [comment] 2015-03-05 15:12
@nickvergessen said he'll have a look. I'll support him where needed. (none of us know anything about that part)

**Comment by georgehrke** [comment] 2015-03-05 15:14
> I guess @georgehrke isn't around ?

I'm around, will check.

**Comment by PVince81** [comment] 2015-03-05 15:16
Great, thanks.

What should the "legacy" folder look like ? Is it just a backup folder ?
Should all apps be moved there ? What if someone installs the "encryption" app from the app store (if that is every possible at some point), should it also replace and rename the shipped encryption app ?

**Comment by georgehrke** [comment] 2015-03-05 15:18
> If we detect during installation of an app that there is already a directory with the same name than we have to create an "legacy" directory (if it is not already there) and move the old directory into it.

In some installations (installed via packages) the preinstalled apps are in a read-only directory and we can't move them. What should we do in this case?

**Comment by karlitschek** [comment] 2015-03-05 15:23
i would call it legacy or backup or apps_backup. should be outside the apps directory of course. the current idea is to do this only for collisions aka if the directory is there when a new app should be installed. 
does this make sens?

**Comment by PVince81** [comment] 2015-03-05 15:24
I believe that the ones from the packages would automatically delete those apps too (like it did for me for the RPM upgrade). This is mostly about people upgrading with tarballs and who "forget" to manually delete the apps. Not 100% sure though.
Also, such people using tarballs might have locked the apps directory too.

**Comment by georgehrke** [comment] 2015-03-05 15:24
> does this make sens?

yes, I see what you mean.

**Comment by PVince81** [comment] 2015-03-05 15:25
@karlitschek you mentionned "package" in the first post, did you mean "OBS package"  or tarball ?

**Comment by jnfrmarks** [comment] 2015-03-05 15:36
@PVince81 

Does the server delivery method matter in this case?  If I install via tarball, copy over my 7.x app, can't I run into the same situation?

**Comment by karlitschek** [comment] 2015-03-05 15:37
@PVince81 good idea that the linux packages should delete this old apps too. I had the same idea. But this doesn´t work because of 1. possible not enough permissions and 2. we might remove too many apps. So I suggest to do it on demand when we have a collision but not earlier

**Comment by karlitschek** [comment] 2015-03-05 15:38
@PVince81 I meant linux package. But also zip package if a user doesn't follow the documentation.

**Comment by PVince81** [comment] 2015-03-05 15:40
No, I mean when you remove a RPM package, if the package itself bundled apps, it will automatically remove them. The old RPM packages had calendar+contacts inside, so upgrading/removing it would automatically delete these apps. If it didn't, then it was probably not a RPM package. Not sure about DEB.
@jnweiger can you clarify?

**Comment by karlitschek** [comment] 2015-03-05 15:41
@georgehrke If they can´t be moved than we should output a proper error message. something like "can´t activate new app because a directory with the same name already exists and it can´t be moved. please move it manually"
does this make sense?

**Comment by DeepDiver1975** [comment] 2015-03-05 15:43
> "can´t activate new app because a directory with the same name already exists and it can´t be moved. please move it manually"
> does this make sense?

hmm - what about using this error message right away instead of adding some "magic copy around' approach?

**Comment by DeepDiver1975** [comment] 2015-03-05 15:44
> No, I mean when you remove a RPM package, if the package itself bundled apps, it will automatically remove them. The old RPM packages had calendar+contacts inside, so upgrading/removing it would automatically delete these apps. If it didn't, then it was probably not a RPM package. Not sure about DEB.
> @jnweiger can you clarify?

a very interesting point - if the apps have been installed via the obs packages - they should have been removes by the packages as well

**Comment by DeepDiver1975** [comment] 2015-03-05 15:44
> hmm - what about using this error message right away instead of adding some "magic copy around' approach?

I mean especially as we are talking about a hot-fix - the less code we add/change the less risk we have to break anything else

**Comment by karlitschek** [comment] 2015-03-05 15:46
@DeepDiver1975  We _have_ to try to fix the problem that owncloud created in the first place. The error message so that someone have to fix this manually is only plan b.

**Comment by nickvergessen** [comment] 2015-03-05 15:48
Okay, so an example to trigger this is:
1. Install oC7 (with calendar and contacts)
2. Mark the apps directory read only
3. Update to oC8 leaving the old apps in place
4. Try to install the new versions from the app store

Is that about right?

**Comment by nickvergessen** [comment] 2015-03-05 15:50
> I mean especially as we are talking about a hot-fix - the less code we add/change the less risk we have to break anything else

I agree with this.

**Comment by DeepDiver1975** [comment] 2015-03-05 15:55
> 2. Mark the apps directory read only

no - owncloud will scream at you in a very early stage

create a folder named 'calendar' in apps and mark that as read only

**Comment by nickvergessen** [comment] 2015-03-05 16:58
proposal: https://github.com/owncloud/core/pull/14716

**Comment by PVince81** [comment] 2015-03-05 17:46
I suspect that this situation is limited to the 8.0.0 to 8.0.1 upgrade, like stated here: https://github.com/owncloud/core/issues/14708

Here is the deducation logic for the several scenarios:

#### Scenario 1a: tarball upgrade 7.0.4 -> 8.0.1 with proper cleanup

Admin deletes ALL files except config, data. Update succeeds because all apps are good.
Fine.

### Scenario 1b: tarball upgrade 7.0.4 -> 8.0.1 with stray calendar/contacts

Admin deletes ALL files except config, data but ALSO leaves the calendar/contacts present.

Run the update: because calendar/contacts (OC 7 version) are SHIPPED, these are not auto-disabled (as per https://github.com/owncloud/core/issues/14677).
This means that after the upgrade, the user gets an exception because the calendar/contacts apps are still from OC 7 and not compatible. (to be confirmed)
In any case, this is not a situation where the admin would see a "Enable" button because the apps are ALREADY enabled.

### Scenario 2: RPM upgrade from 7.0.4 -> 8.0.1

The RPM should delete everything that was bundled, this includes the contacts/calendar apps too.
The new RPMs are split into several RPMs. If the admin installed the owncloud-calendar and owncloud-contacts too, they should get the new version of the apps.
When running the upgrade, the new apps are already there and don't have the "shipped" flag, so they will be auto-disabled on upgrade. They should enable fine afterwards, since they're already there (no need for download).

### Scenario 3a: tarball upgrade from 8.0.0 -> 8.0.1

Same as scenario 1b, all files replaced so no stray calendar/contacts app.

### Scenario 3b: tarball upgrade from 8.0.0 -> 8.0.1 with stray calendar/contact apps

During this upgrade, calendar/contacts are NOT shipped apps, so they will be auto-disabled.
This means the admin will get an "Enable" button in the apps page.
This seems to match this ticket somewhat.

### Scenario 4: RPM upgrade from 8.0.0 -> 8.0.1

The RPMs were split in piece for 8.0.0 and also for 8.0.1.
Normally the rpm command will automatically delete the "owncloud-calendar-8.0.0" and "owncloud-contacts-8.0.0" packages and also delete the apps, then replace them with the new ones from the new packages "owncloud-calendar-8.0.1" and "owncloud-contacts-8.0.1".

During this upgrade routine, calendar/contacts are NOT shipped apps, so they will be auto-disabled.
The admin can then re-enable them from the apps page.
This should work fine because these apps are already on the latest code.

Now if something is wrong with the packages, it could happen that the owncloud-calendar and owncloud-contacts packages are STILL on the old version, which could explain why the UI doesn't let them be enabled.


Note: everything I wrote here is pure theory.

**Comment by PVince81** [comment] 2015-03-05 17:49
Sorry... wrong... there are no owncloud-app-calendar or owncloud-app-contact packages...

**Comment by PVince81** [comment] 2015-03-05 17:51
Okay, so if there are no packages:

If you upgrade from 7.0.4 to 8.0.1 with RPM: the RPM should kill the old apps/calendar and apps/contacts folders.

If you upgrade from 8.0.0 to 8.0.1 with RPM: the OLD apps/calendar and apps/contacts will STILL be there because the RPM doesn't care (they were not bundled). So you'll have the old version and need to reenable + update.

Good... so that's our scenario.

**Comment by LukasReschke** [comment] 2015-03-05 19:56
Another patch for that: https://github.com/owncloud/core/pull/14719 – all fame to @PVince81 and @nickvergessen…

And we really have to stop this crap where we add yet more static code to already existing code… – The time we wasted on such an issue!!!!!!

**Comment by PVince81** [comment] 2015-03-05 20:16
Just now I remember that @DeepDiver1975 put a fix on master with a similar title: https://github.com/owncloud/core/commit/39d84069337d7d6ddcaed7b1daba37cfeb26dcc7#diff-34e065ae305e501c5b8d33de1300f2a1R150

But in that PR it seems to just not display the broken app entries at all ?

**Comment by PVince81** [comment] 2015-03-05 20:26
Looks like this exact same issue was already known here: https://github.com/owncloud/core/issues/13945 (which is the one of @DeepDiver1975's PR)

**Comment by PVince81** [comment] 2015-03-05 20:45
So, here is a summary: the core issue is that when upgrading from 8.0.0 to 8.0.1 with calendar/contact apps enabled, something goes wrong with the ocsid and the apps cannot be enabled from the recommended page, which says "app cannot be installed, folder already exists". This is because the apps were not recognized.

Three different fixes have been proposed:
- Fix 1: @DeepDiver1975 fixed this on master for https://github.com/owncloud/core/issues/13945 with the PR https://github.com/owncloud/core/pull/14009 (don't allow installation of already installed apps): the fix seems to hide the non-compatible apps from the "Recommended" page. This fix was not backported.
- Fix 2: @nickvergessen proposed this PR https://github.com/owncloud/core/pull/14716 which renames the existing folder to a backup folder if it already exists.
- Fix 3: @LukasReschke went deeper with https://github.com/owncloud/core/pull/14719 and managed to resolve the apps from "Recommended" back to their proper OCSID, which makes it possible to simply enable the apps instead of download+overwrite.

I vote for @LukasReschke's fix https://github.com/owncloud/core/pull/14719 as it seems to address the core issue properly instead of just working it around.

@DeepDiver1975 @nickvergessen @georgehrke @karlitschek what do you think ?

**Comment by LukasReschke** [comment] 2015-03-05 20:48
@DeepDiver1975's fix on master does not seem to work for all cases on master as far I can tell. Apps like "Imprint" are still shown wrongly in the "Tool" section and throws those errors (to verify that behaviour you need to change the ownCloud version back to 8 in version.php)

**Comment by LukasReschke** [comment] 2015-03-05 20:49
If my patch gets merged in 8 I'll create a PR for master as well.

**Comment by karlitschek** [comment] 2015-03-05 21:08
agreed. Thanks a lot guys.

**Comment by PVince81** [comment] 2015-03-05 22:49
@LukasReschke provided a follow up patch, I hope you didn't miss it: https://github.com/owncloud/core/pull/14721

**Comment by LukasReschke** [comment] 2015-03-05 23:17
Master port is at https://github.com/owncloud/core/pull/14722

**Closed** 2015-03-06 17:52 UTC
Labels: bug, showstopper
