### ISSUE TITLE
Unable to share with users from Client or Web

### ISSUE THREAD

**Issue by esarakaitis** [owncloud/core#27474] opened 2017-03-23 18:06 UTC
### Steps to reproduce
1. Click share
2. Type user id
3. nothing happens

### Expected behaviour
it should auto-complete

### Actual behaviour
nothing at all, the progress circle thing happens but then nothing

this appears in log:

"RuntimeException: Starting sabre\/vobject 4.0 the children property is now protected. You should use the children() method instead at \/usr\/share\/php\/Sabre\/VObject4\/Component.php

### Server configuration
**Operating system**:
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Web server:**
httpd-tools-2.4.6-45.el7.x86_64
httpd-2.4.6-45.el7.x86_64

**Database:**
Server version: 5.5.52-MariaDB MariaDB Server
**PHP version:**
PHP 5.6.30

**ownCloud version:** (see ownCloud admin page)
owncloud-httpd-9.1.4-3.el7.noarch
**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
RPM

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'log_type' => 'owncloud',
  'logfile' => '/var/lib/owncloud/data/owncloud.log',
  'loglevel' => 1,
  'datadirectory' => '/var/lib/owncloud/data',
  'updatechecker' => false,
  'check_for_working_htaccess' => false,
  'asset-pipeline.enabled' => false,
  'assetdirectory' => '/var/lib/owncloud',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => true,
  'forcessl' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/lib/owncloud/apps',
      'url' => '/apps-appstore',
      'writable' => true,
    ),
  ),

  'trusted_domains' =>
  array (
    0 => 'owncloud.encore.tech',
  ),
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpdebug' => true,
  'mail_smtptimeout' => 30,
  'mail_from_address' => 'owncloud',
  'mail_domain' => '',
  'mail_smtphost' => '',
  'mail_smtpport' => '25',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);


**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WNQLU8GMPomXLXsMAzKwKQAAAAQ","remoteAddr":"172.16.110.140","app":"PHP","message":"RuntimeException: Starting sabre\/vobject 4.0 the children property is now protected. You should use the children() method instead at \/usr\/share\/php\/Sabre\/VObject4\/Component.php#466","level":3,"time":"2017-03-23T17:52:20+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=rick.&perPage=200&itemType=folder","user":"eric.sarakaitis"}
{"reqId":"WNQLVcGMPomXLXsMAzKwKgAAAAQ","remoteAddr":"172.16.110.140","app":"PHP","message":"RuntimeException: Starting sabre\/vobject 4.0 the children property is now protected. You should use the children() method instead at \/usr\/share\/php\/Sabre\/VObject4\/Component.php#466","level":3,"time":"2017-03-23T17:52:22+00:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=rick+dobson&perPage=200&itemType=folder","user":"eric.sarakaitis"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment] 2017-03-23 18:12
> /usr/share/php/Sabre/VObject4/Component.php

Most likely caused by this where your used "owncloud-http" (which is not an official package) is using the SabreDAV shipped with your distribution and not the SabreDAV version included in the official packages from owncloud.org.

I think you should report this issue to the packager of your distribution instead of here. An alternative would be to use the official packages from https://owncloud.org/install/#edition which are not showing this issue.

**Comment by esarakaitis** [comment] 2017-03-23 18:14
As soon as i disabled the federated sharing, it started working again

**Comment by kdslkdsaldsal** [comment] 2017-03-23 18:22
Still it worth to report that to you packager. ownCloud heavily relies on the correct used Sabre/* version. If your distro is shipping a newer or older versions this might break at any time.

**Comment by kdslkdsaldsal** [comment] 2017-03-23 18:30
Just to show the issue: Your system is currently using sabre/vobject 4.0:

``Starting sabre/vobject 4.0``

however ownCloud 9.1.4 needs sabre/vobject 3.5:

https://github.com/owncloud/3rdparty/blob/3b3d908e9b1124cb1dd7d2224b6ba6a58f2e2fe9/composer/installed.json#L1641-L1642

Nothing what can be done here from ownCloud side. Please close here and report this issue to your distro / package provider.

**Comment by kdslkdsaldsal** [comment] 2017-03-23 18:38
@hodyroff @PVince81 @DeepDiver1975 FYI if further of that kind of reports are coming in here

**Comment by hodyroff** [comment] 2017-03-23 18:41
Great catch @kdslkdsaldsal 
@esarakaitis where is the .rpm package from?
Closing, you can continue to comment.

**Closed by hodyroff** 2017-03-23 18:41 UTC

**Comment by esarakaitis** [comment] 2017-03-23 18:44
looks like its an EPEL package

**Comment by hodyroff** [comment] 2017-03-23 19:09
@jnweiger @crrodriguez FYI Don't know what we can do with wrong packages out there.

**Comment by kdslkdsaldsal** [comment] 2017-11-28 15:45
Another one with the mix between sabre/vobject 3.5 and 4.0: https://github.com/owncloud/core/issues/29663
