### ISSUE TITLE
files downloaded as ZIP has only read-only permission

### ISSUE THREAD

**Issue by dttpy** [owncloud/core#14900] opened 2015-03-15 16:19 UTC
### Steps to reproduce
1. create a folder "test"
2. upload serval files in "test" folder
3. choose some of these files or all files, or go back to root and choose folder "test"
4. download the chosen files/folder
5. find the downloaded zip file "test" in local computer
6. extract "test"

### Expected behaviour
All extracted files have "read & write" permission, as if they were downloaded one by one

### Actual behaviour
The extracted files have "read-only" permission. In order to edit those files, the permission should be changed manuelly

### Server configuration
**Operating system:** Ubuntu 13.10

**Web server:** apache 2.4.6 (Ubuntu)

**Database:** SQLite

**PHP version:** 5.5.3-1ubuntu2.3

**ownCloud version:** 8.0.2 & 7.0.4 & master

**Updated from an older ownCloud or fresh install:** 8.0.0-beta2

**List of activated apps:** standard apps of owncloud

**The content of config/config.php:**

```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc6d9cda6e26',

  'datadirectory' => '/var/ocdata/.../owncloud/data8',
  'dbtype' => 'sqlite3',
  'version' => '8.0.2.0',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'trusted_domains' => 
  array (
    0 => '192.168.1.80',
  ),
  'appcodechecker' => false,


  );



```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes

### Client configuration
**Browser:** firefox 35.0.1

**Operating system:** ubuntu 13.10

**Comment by PVince81** [comment] 2015-03-16 09:44
@karlitschek I think this is a bug (probably an oversight) from when we switched to ZipStreamer.

**Comment by karlitschek** [comment] 2015-03-16 12:11
@pvince81 agreed. can you help with that?

**Comment by PVince81** [comment] 2015-03-16 13:05
Yes probably, but already quite busy with other stuff, so setting to 8.2.

**Comment by rullzer** [comment] 2015-03-26 21:15
Problem seems to be at https://github.com/owncloud/3rdparty/blob/master/mcnetic/phpzipstreamer/ZipStreamer.php#L100-L107

We should just extend the file and dir attributes. Unfortunately there is no function to just extend this.

Easiest is to modify the 3rdparty file. But not very clean. Other option would be to extend the class and override the attributes ourself.

**Comment by PVince81** [comment] 2015-05-18 13:03
Duplicate of https://github.com/owncloud/core/issues/12505

**Closed by PVince81** 2015-05-18 13:03 UTC
Labels: bug
