### ISSUE TITLE
error when trying to update from 10.0.9.5 to 10.4.1.3

### ISSUE THREAD

**Issue by schrottili** [owncloud/core#37364] opened 2020-05-08 11:06 UTC
### Steps to reproduce
I tried to manually update the system. Having had some update-issues before, I unfortunately disabled a few apps (including market...) before backing up. Backed up config.php (changing to maintenance=true), then removed all files, then downloaded new files and restored config.php.
Opening page in browser looked promising (going to update...). I started the update and ist told me, that with market disabled I cannot continue.

So I thought, go back to previous version, enable market and then try again. Unfortunately, after installing old version again, there was no page any more, only empty pages in the browser (no errors neither).

So I had to try it a different way, went back to 10.4.1.3 (still offering to update on the index.php in the browser). I searched for, how the app-data is stored in the mysql-db, found table 'oc_appconfig', took phpMyAdmin to enable all disabled apps. Retried to update (four apps not found, disabled them again) and now I come to the problem I have no solution for.

### Expected behaviour
Well, I'd like to run the update successfully.

### Actual behaviour
When I try to update now I get the message:
**Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'ALTER TABLE oc_persistent_locks ADD CONSTRAINT FK_F0C3D55B93CB796C FOREIGN KEY (file_id) REFERENCES oc_filecache (fileid) ON DELETE CASCADE': SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'xxxxxxxxx'@'localhost' for table 'oc_filecache'.**

When I rerun the update (reload page, run update), I get the message:
Doctrine\DBAL\Schema\SchemaException: The table with name 'xxxxxxxxxx.oc_persistent_locks' already exists.

When I drop/delete table 'oc_persistent_locks' with phpMyAdmin I get the first message again.

### Server configuration
I mainly use the following three apps: calendar, contacts and files.
I share files from two windows-computer and an android-phone.
I edit the contacts and calendar mainly from the server-app/in the browser and read them on the phone.
I cannot run these occ commands on the webserver, there is no telnet/ssh-access for me.

**Web server:**

**Database:**
mySQL 5.7.20-log
myPhpAdmin 4.7.5

**PHP version:**
php 7.2 stable

**ownCloud version:** (see ownCloud admin page)
changing from 10.0.9.5 to 10.4.1.3

Has there anybody an idea on how to properly get around this error (I don't see a reason for the user to not access the table as everything has been done by this user and there was no change to user/name nor password).

Thanks for your help! :-)

**Comment by schrottili** [comment] 2020-05-08 11:21
the (new started) owncloud log looks like:
`{"reqId":"XrU8YiUR4C4AAA7jm6IAAAAA","level":3,"time":"2020-05-08T11:02:58+00:00","remoteAddr":"12.345.678.90","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=6b86a66ac44f28561117dfdf63093eec","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp('dav')\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/base.php(915): OC_Util::setupFS()\\n#3 \\\/home\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":188}"}
{"reqId":"XrU8ZiUR4C4AAFsvo8QAAAAH","level":0,"time":"2020-05-08T11:03:02+00:00","remoteAddr":"12.345.678.90","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=IgcNYwkZBTw8Cy9pKFpRJxVDdyMaYR4JIj0OJBInZVs%3D%3AVkI3ycskfRE9QjbfDsDou0KsTvFheHVkzgElISjdnqE%3D","message":"starting upgrade from 10.0.9.5 to 10.4.1.3"}
{"reqId":"XrU8ZiUR4C4AAFsvo8QAAAAH","level":0,"time":"2020-05-08T11:03:03+00:00","remoteAddr":"12.345.678.90","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=IgcNYwkZBTw8Cy9pKFpRJxVDdyMaYR4JIj0OJBInZVs%3D%3AVkI3ycskfRE9QjbfDsDou0KsTvFheHVkzgElISjdnqE%3D","message":"Migrations: starting 20180607072706 from app core"}
{"reqId":"XrU8ZiUR4C4AAFsvo8QAAAAH","level":3,"time":"2020-05-08T11:03:03+00:00","remoteAddr":"12.345.678.90","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=IgcNYwkZBTw8Cy9pKFpRJxVDdyMaYR4JIj0OJBInZVs%3D%3AVkI3ycskfRE9QjbfDsDou0KsTvFheHVkzgElISjdnqE%3D","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE oc_persistent_locks ADD CONSTRAINT FK_F0C3D55B93CB796C FOREIGN KEY (file_id) REFERENCES oc_filecache (fileid) ON DELETE CASCADE':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'xxxxxxxx'@'localhost' for table 'oc_filecache'\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(169): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(145): Doctrine\\\\DBAL\\\\DBALException::wrapException(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'An exception oc...')\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1014): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE oc_...')\\n#3 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(198): Doctrine\\\\DBAL\\\\Connection->query('ALTER TABLE oc_...')\\n#4 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(80): OC\\\\DB\\\\Migrator->applySchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#5 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(434): OC\\\\DB\\\\Migrator->migrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#6 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(417): OC\\\\DB\\\\Connection->migrateToSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#7 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(371): OC\\\\DB\\\\MigrationService->executeStep(20180607072706)\\n#8 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(307): OC\\\\DB\\\\MigrationService->migrate()\\n#9 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(261): OC\\\\Updater->doCoreUpgrade()\\n#10 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.4.1.3', '10.0.9.5')\\n#11 \\\/home\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(189): OC\\\\Updater->upgrade()\\n#12 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":93}"}
{"reqId":"XrU8ZiUR4C4AAFsvo8QAAAAH","level":3,"time":"2020-05-08T11:03:03+00:00","remoteAddr":"12.345.678.90","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=IgcNYwkZBTw8Cy9pKFpRJxVDdyMaYR4JIj0OJBInZVs%3D%3AVkI3ycskfRE9QjbfDsDou0KsTvFheHVkzgElISjdnqE%3D","message":"Caused by: {\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOException\",\"Message\":\"SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'xxxxxxxx'@'localhost' for table 'oc_filecache'\",\"Code\":\"42000\",\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1012): Doctrine\\\\DBAL\\\\Driver\\\\PDOConnection->query('ALTER TABLE oc_...')\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(198): Doctrine\\\\DBAL\\\\Connection->query('ALTER TABLE oc_...')\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(80): OC\\\\DB\\\\Migrator->applySchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#3 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(434): OC\\\\DB\\\\Migrator->migrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(417): OC\\\\DB\\\\Connection->migrateToSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#5 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(371): OC\\\\DB\\\\MigrationService->executeStep(20180607072706)\\n#6 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(307): OC\\\\DB\\\\MigrationService->migrate()\\n#7 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(261): OC\\\\Updater->doCoreUpgrade()\\n#8 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.4.1.3', '10.0.9.5')\\n#9 \\\/home\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(189): OC\\\\Updater->upgrade()\\n#10 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOConnection.php\",\"Line\":90}"}
{"reqId":"XrU8ZiUR4C4AAFsvo8QAAAAH","level":3,"time":"2020-05-08T11:03:03+00:00","remoteAddr":"12.345.678.90","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=IgcNYwkZBTw8Cy9pKFpRJxVDdyMaYR4JIj0OJBInZVs%3D%3AVkI3ycskfRE9QjbfDsDou0KsTvFheHVkzgElISjdnqE%3D","message":"Caused by: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[42000]: Syntax error or access violation: 1142 REFERENCES command denied to user 'xxxxxxxx'@'localhost' for table 'oc_filecache'\",\"Code\":\"42000\",\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOConnection.php(88): PDO->query('ALTER TABLE oc_...')\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1012): Doctrine\\\\DBAL\\\\Driver\\\\PDOConnection->query('ALTER TABLE oc_...')\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(198): Doctrine\\\\DBAL\\\\Connection->query('ALTER TABLE oc_...')\\n#3 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Migrator.php(80): OC\\\\DB\\\\Migrator->applySchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(434): OC\\\\DB\\\\Migrator->migrate(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#5 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(417): OC\\\\DB\\\\Connection->migrateToSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#6 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(371): OC\\\\DB\\\\MigrationService->executeStep(20180607072706)\\n#7 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(307): OC\\\\DB\\\\MigrationService->migrate()\\n#8 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(261): OC\\\\Updater->doCoreUpgrade()\\n#9 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.4.1.3', '10.0.9.5')\\n#10 \\\/home\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(189): OC\\\\Updater->upgrade()\\n#11 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOConnection.php\",\"Line\":88}"}
{"reqId":"XrU9gyUR4C4AAFsvo8UAAAAH","level":0,"time":"2020-05-08T11:07:47+00:00","remoteAddr":"12.345.678.90","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"REPORT","url":"\/remote.php\/dav\/calendars\/XXXX\/pppppppp\/","message":"invalidating token 6cbc5fe30129583f28b74efe75e6fd6b544f72da29755565008d6a96c4013ca213b1dd27d96dffdbc4f61a422c0a92ff63d29ffb82b955688680a083fa05017b"}
{"reqId":"XrU9hCUR4C4AAA7jm6sAAAAA","level":0,"time":"2020-05-08T11:07:48+00:00","remoteAddr":"12.345.678.90","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"REPORT","url":"\/remote.php\/dav\/calendars\/XXXX\/yyyyyyyyy\/","message":"invalidating token 98d44d703bd232cd312a2de8aa1033fbfc3e3deae87884d9b69a55f6057a4785f3b3eb227cd4212ed76d0fdaf6f5fa30ec11f848c86831e762235ab020bce44e"}
{"reqId":"XrU9hSUR4C4AAE-0ZBcAAAAD","level":0,"time":"2020-05-08T11:07:49+00:00","remoteAddr":"12.345.678.90","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"REPORT","url":"\/remote.php\/dav\/calendars\/XXXX\/yyyyyyyyyyyyyyyyyyyyyyyics\/","message":"invalidating token b1a9154f5f7b76643a381fad986df78fe0a897a38ff07143d7eef6b0ff156521d972b755cdd2b5c4fc92a4715f45c0765a702ff8b5ca5d9b1d6fcee6d878deb7"}
{"reqId":"XrU9hyUR4C4AAFsvo8YAAAAH","level":0,"time":"2020-05-08T11:07:51+00:00","remoteAddr":"12.345.678.90","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"REPORT","url":"\/remote.php\/dav\/calendars\/XXXX\/xxxxxxxx\/","message":"invalidating token 9e9321a4a5266d085c9132ee06a31a29236c10b4616ff39283894c977f849aee183a18abb39eb514d6ed930fd3286abab39b3a070586f89b4700a367df3a9085"}
{"reqId":"XrU9iCUR4C4AAEhno48AAAAF","level":0,"time":"2020-05-08T11:07:52+00:00","remoteAddr":"12.345.678.90","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"REPORT","url":"\/remote.php\/dav\/calendars\/XXXX\/yyyyyyyyyyyyyyyyyyyy\/","message":"invalidating token 108ba261024079f69df0bce23af365a954e6ba9b47ef763876f016abb9a0708f3461fd8e38d0badbaead808845b207fdd36e68976705c3ec6821fad344ffae9e"}
{"reqId":"XrU@eiUR4C4AAA7jm68AAAAA","level":3,"time":"2020-05-08T11:11:54+00:00","remoteAddr":"12.345.678.90","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=6b86a66ac44f28561117dfdf63093eec","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(124): OC_App::loadApp('dav')\\n#1 \\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/home\\\/www\\\/owncloud\\\/lib\\\/base.php(915): OC_Util::setupFS()\\n#3 \\\/home\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":188}"}
`

**Comment by VicDeo** [comment] 2020-05-11 10:22
duplicate of https://github.com/owncloud/core/issues/34598
@schrottili  most likely you need to start with updating permissions for your DB user:
https://github.com/owncloud/core/issues/34598#issuecomment-468445671

**Closed by VicDeo** 2020-05-11 10:22 UTC
