### ISSUE TITLE
Possibility to undo deletion from »Deleted Files«

### ISSUE THREAD

**Issue by schmunk42** [owncloud/core#7050] opened 2014-02-03 09:11 UTC
I know about the general guidelines from http://alistapart.com/article/neveruseawarning 

But if you're in the **Deleted Files** section and mark some files for final deletion aka. empty trash, you should ask the user to confirm this action, since there's no undo for that.

oC Version: 6.0.1

**Comment by Xenopathic** [comment] 2015-08-30 10:03
Duplicate of #119

**Closed by Xenopathic** 2015-08-30 10:03 UTC
Labels: app:files_trashbin, design, enhancement
