### ISSUE TITLE
Renaming a shared folder back to its previous name removes the folder

### ISSUE THREAD

**Issue by taurhine** [owncloud/core#14908] opened 2015-03-15 21:39 UTC
Running ownCloud 8.0.2 stable with windows client 1.7.1

Steps to reproduce the problem:
- In my case I've had a folder named Fotos which was shared with 5 users.
- I've renamed the folder to Cloud_Fotos  (via windows explorer, not via web interface) which didn't change the folder name for the users.
- After a while I've renamed the shared folder back to it's previous name "Fotos" (again via windows explorer)
- and put a new file in Fotos folder (I doubt this step will be necessary but anyway)
- client tried to sync and the folder disappeared

I see two fatal webdav errors in the log

Exception: {"Message":"The resource you tried to create already exists","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(964): Sabre\\DAV\\Server->createCollection('Fotos\/2014\/Sari...', Array, Array)\n#1 [internal function]: Sabre\\DAV\\Server->httpMkcol('Fotos\/2014\/Sari...')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'Fotos\/2014\/Sari...')\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('MKCOL', 'Fotos\/2014\/Sari...')\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php","Line":1714} 

Exception: {"Message":"The resource you tried to create already exists","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(964): Sabre\\DAV\\Server->createCollection('Fotos\/2014', Array, Array)\n#1 [internal function]: Sabre\\DAV\\Server->httpMkcol('Fotos\/2014')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'Fotos\/2014')\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('MKCOL', 'Fotos\/2014')\n#4 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php","Line":1714}

**Comment by karlitschek** [comment] 2015-03-15 21:52
@schiesbn can you have a look?

**Comment by PVince81** [comment] 2015-03-16 09:48
@taurhine when you renamed the folder back, was the sync client still running ? Maybe the sync process wasn't finished with your first rename ?

**Comment by taurhine** [comment] 2015-03-16 22:23
I've renamed the folder after 3-4 hours so sync for the folder itself it should be ok. 
However I've done this renaming for another folder as well. That folder didn't disappear that's why I haven't mention it earlier.

So to sum up the whole renaming thing:

Renamed Fotos -> Cloud_Fotos
------ immediately after
Renamed Videos -> Cloud_Videos
------ After 3-4 hours
(this time renamed Video folder first)
Renamed Cloud_Videos -> Videos 
------ immediately after
Renamed Cloud_Fotos -> Fotos

Videos folder has been renamed properly but Fotos folder has disappeared.
I don't recall seeing the cloud icon syncing but it might be that the client has started syncing right after the renaming Cloud_Videos and I've renamed the Cloud_Fotos folder during the sync.

Maybe it worked the first time because I've managed to rename both folders before the client started syncing.

**Comment by PVince81** [comment] 2015-03-17 09:12
Hmmm if you waited 3-4 hours between the operations, I don't see any possible conflict.
Unless the first renames (Fotos -> Cloud_Fotos, Videos -> Cloud_Videos) failed silently for some reason.

**Comment by taurhine** [comment] 2015-03-17 20:29
I have tried to reproduce the bug with some other folders but so far no luck.
Renaming shared folders locally make no difference on the server side. Even after local rename folders keep on syncing without a problem. 

What is really weird is the error message "The resource you tried to create already exists". It somehow has seen that the folder Fotos already exists on the server and but then removed it from the server client synced and the folder is removed locally as well.

Can we say in general that it is "safer" to rename the folders via the web interface?

**Comment by PVince81** [comment] 2015-03-18 09:54
It is not necessarily safer in the web interface.

The reason you're not able to reproduce it is because there was probably some kind of race condition the first time it happened. Not sure why the server would still be processing stuff during 3-4 hours, unless you have encryption enabled + many share recipients + a huge amount of files.

**Comment by taurhine** [comment] 2015-03-18 20:28
I can't think of any reason for the server to process for that long. The folders are not big (Fotos ~200MB, Videos ~800MB) and I have no encryption and share it with 5 users.
I also believe that this was due to a race condition and I think it was caused because I've renamed two folders without waiting for the client to finish syncing the first one. But it has to be a very unfortunate timing...

**Comment by PVince81** [comment] 2015-03-19 09:41
In that case the only part that is known to take longer is updating the index, which contains the full path of every file. The full path needs to be adjusted to the new path. This should hopefully improve thanks to https://github.com/owncloud/core/pull/13948

**Comment by PVince81** [comment] 2015-04-13 09:10
Liekly duplicate of https://github.com/owncloud/core/issues/13391

**Closed by PVince81** 2015-04-13 09:10 UTC
Labels: bug

**Comment by PVince81** [comment] 2015-04-13 09:34
Problem can be reproduced consistently, actually a duplicate of https://github.com/owncloud/core/issues/14908

**Comment by taurhine** [comment] 2015-04-13 15:41
Thanks for the info. I hope that this issue is also caused by the same bugs, because in my case, unlike #15340, the issue was caused only by 1 user. All other users have read only access to the folder so they can not rename anything. 
Difference to  #15343 is that the renamed folder also got removed, not just the folder contents.

**Comment by PVince81** [comment] 2015-04-13 15:48
In my test case the renamed folder also got completely removed in https://github.com/owncloud/core/issues/15340
