### ISSUE TITLE
Owncloud deleted all files - cannot restore from trash

### ISSUE THREAD

**Issue by erlendd** [owncloud/core#22824] opened 2016-03-03 15:45 UTC
### Steps to reproduce
1. I left a MacOSX with updated owncloud client to upload files
2. Next day all files were in trash
3. From trash, try to restore but cannot due to error (from owncloud.log: "trash bin database inconsistent!"

### Expected behaviour
Files shouldn't have been deleted in the first place.
Should be possible to restore files from trash.

### Actual behaviour
Cannot restore the files from trash due to the error message "trash bin database inconsistent!".
The files are in the trash in a hidden holder as such: ./files_trashbin/files/.d1456875723/

### Server configuration
**Operating system**:
Raspbian based on debian wheezy

**Web server:**
Nginx 1.2.1

**Database:**
Mysql 5.5.47

**PHP version:**
PHP 5.4.45

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from older version.

**Where did you install ownCloud from:**
Via owncloud downloads.

**Signing status (ownCloud 9.0 and above):**
N/A

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_encryption
  - notifications
  - user_external
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Linux

#### ownCloud log (data/owncloud.log)
```
{"reqId":"2TtxGdHCFYsEv+YGYGfI","remoteAddr":"155.198.39.88","app":"files_trashbin","message":"trash bin database inconsistent!","level":3,"time":"2016-03-03T14:48:59+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php"}
{"reqId":"2TtxGdHCFYsEv+YGYGfI","remoteAddr":"155.198.39.88","app":"trashbin","message":"can't restore files","level":3,"time":"2016-03-03T14:48:59+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php"}
{"reqId":"7iscSzujOZZ1fIzPgW\/1","remoteAddr":"155.198.39.88","app":"PHP","message":"Array to string conversion at \/usr\/share\/nginx\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-03-03T14:49:17+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"7iscSzujOZZ1fIzPgW\/1","remoteAddr":"155.198.39.88","app":"PHP","message":"Undefined index: Please double check the <a target=\"_blank\" href=\"%s\">installation guides \u2197<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>. at \/usr\/share\/nginx\/www\/owncloud\/lib\/private\/l10n\/string.php#64","level":3,"time":"2016-03-03T14:49:17+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
{"reqId":"7iscSzujOZZ1fIzPgW\/1","remoteAddr":"155.198.39.88","app":"PHP","message":"Undefined index: Please double check the <a target=\"_blank\" href=\"%s\">installation guides \u2197<\/a>, and check for any errors or warnings in the <a href=\"#log-section\">log<\/a>. at \/usr\/share\/nginx\/www\/owncloud\/lib\/private\/l10n\/string.php#70","level":3,"time":"2016-03-03T14:49:17+00:00","method":"GET","url":"\/index.php\/settings\/admin"}
```

**Comment by erlendd** [comment] 2016-03-03 15:47
{"reqId":"TrHwYK\/D94WedidLrxX8","remoteAddr":"155.198.39.88","app":"PHP","message":"Undefined index: permissions at \/usr\/share\/nginx\/www\/owncloud\/lib\/private\/files\/fileinfo.php#177","level":3,"time":"2016-03-03T15:46:24+00:00","method":"GET","url":"\/index.php\/apps\/files_trashbin\/ajax\/list.php?dir=%2F&sort=mtime&sortdirection=desc"}
{"reqId":"d6gxZ7odw4QbEmLdqYy0","remoteAddr":"155.198.39.88","app":"files_trashbin","message":"trash bin database inconsistent!","level":3,"time":"2016-03-03T15:46:37+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php"}
{"reqId":"d6gxZ7odw4QbEmLdqYy0","remoteAddr":"155.198.39.88","app":"trashbin","message":"can't restore files","level":3,"time":"2016-03-03T15:46:37+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php"}

**Comment by PVince81** [comment] 2016-03-04 11:56
Can you confirm that you didn't disable file locking ? (post your config.php)
Because the locking was developed to prevent this kind of situations.

**Comment by PVince81** [comment] 2016-03-04 11:57
`files_trashbin/files/.d1456875723/` ouch. That sounds like a bad race condition.

Last time I saw this it was a race condition in OC 8.0 or so I believe, the locking should already prevent this.

**Comment by erlendd** [comment] 2016-03-04 13:24
I haven't disabled file-locking. Here's the output of config:list..
/nginx/www/owncloud/occ config:list
{
    "system": {
        "instanceid": "ockmu5qf1x1y",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ******
        ],
        "datadirectory": "\/mnt\/WDslim1\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.16\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.googlemail.com",
        "mail_from_address": "erlend.davidson",
        "mail_domain": "gmail.com",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.1.3",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "global_cache_gc_lastrun": "1444383902",
            "installedat": "1425150702.8381",
            "lastcron": "1457097302",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1457038178",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "files_sharing\/publicwebdav.php",
            "remote_files": "files\/appinfo\/remote.php",
            "remote_webdav": "files\/appinfo\/remote.php",
            "repairlegacystoragesdone": "yes"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_external": {
            "\/Dropbox": "1425334759",
            "\/Local": "1425660293",
            "\/SFTP": "1425660322",
            "enabled": "yes",
            "installed_version": "0.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\DAV"
        },
        "files_locking": {
            "enabled": "yes",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.7",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "27": "1456067246.5242",
            "29": "1456420191.7351",
            "3": "1456839122.4194",
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.0",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_videoviewer": {
            "enabled": "yes",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.2.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "filesystem"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updater": {
            "enabled": "yes",
            "installed_version": "0.6",
            "types": ""
        }
    }
}

**Comment by PVince81** [comment] 2016-03-04 13:26
Thanks for the details. I see you have external storages, were you uploading files to one of the external storages ?

**Comment by PVince81** [comment] 2016-03-04 13:32
@erlendd and when you say "all files were in trash" do you mean all uploaded files or all files you had inside ownCloud ? (possibly excluding external storages)

Problem looks similar to https://github.com/owncloud/core/issues/8101

**Comment by PVince81** [comment] 2016-03-04 13:34
@schiesbn can you analyze the trashbin code paths to find which ones would cause the name of the files to be truncated and produce names like ".d1234567" ? Very likely to be due to a race condition.

Also suspicious:
- database entries do not match filesystem entries (possibly due to the bogus file/folder names in the trash)
- **something** seems to be deleting several files after upload and moves them to trash (the answer to https://github.com/owncloud/core/issues/22824#issuecomment-192285131 could help pinpoint the code path)

**Comment by PVince81** [comment] 2016-03-04 13:34
@icewind1991 do we have proper locking in regards to the trashbin ?

**Comment by PVince81** [comment] 2016-03-04 13:40
@erlendd another info: you can check the following:
- "oc_files_trash" that maps deleted file names to their original locations
- `select * from oc_filecache where path like 'files_trashbin/%' order by path;`
- "data/$user/files_trashbin/"

These have to be consistent for restoration to work.
I suspect that the folder name got truncated when the folder was created on disk, but the database contains the real names.

**Comment by PVince81** [comment] 2016-03-04 14:11
This would be the code path that moves to trash: https://github.com/owncloud/core/blob/v8.2.2/apps/files_trashbin/lib/trashbin.php#L200

There is already a check at the top: https://github.com/owncloud/core/blob/v8.2.2/apps/files_trashbin/lib/trashbin.php#L183

Two theories:
- Maybe in two parallel processes, the existence check ran at exactly the same time, and returned `true` for both
- Or the existence check is wrong. If `$fileName` is empty, it means `$ownerPath` was empty too. And `files/` always exists for the user.

If @erlendd with "all files deleted" meant "all files from the cloud", then this fits with this theory. The "files" folder would get deleted in this case.

We might need an additional check whether "ownerPath" is empty...

It still doesn't explain why OC would try and delete these in the first place.

**Comment by PVince81** [comment] 2016-03-04 14:18
Okay, I got something very close reproduced.

If you set `$ownerPath` manually after this line https://github.com/owncloud/core/blob/v8.2.2/apps/files_trashbin/lib/trashbin.php#L181 then delete any file in the web UI, it will delete the "files" folder.
Then you need to clear the cookies/cache to be able to login again, and get the skeleton copied.

And then the database:
```
*************************** 2. row ***************************
          fileid: 2
         storage: 1
            path: files_trashbin/files/.d1457100895
       path_hash: 50845edc100b33da3d3ebb2c1c796bd3
          parent: 13
            name: .d1457100895
        mimetype: 2
        mimepart: 1
            size: 163
           mtime: 1457100250
   storage_mtime: 1457100249
       encrypted: 0
unencrypted_size: 0
            etag: 56d995dac3130
     permissions: 31
*************************** 3. row ***************************
          fileid: 10
         storage: 1
            path: files_trashbin/files/.d1457100895/sub
       path_hash: c6ba6523b44e66b5ae4554b997c6eec8
          parent: 2
            name: sub
        mimetype: 2
        mimepart: 1
            size: 0
           mtime: 1457100250
   storage_mtime: 1457100250
       encrypted: 0
unencrypted_size: 0
            etag: 56d995dabb276
     permissions: 31
```

I'll fix that `if` statement...

I suspect that the deletion had nothing to do with the upload and was only a "very simultaneous double deletion" issue of some sorts. The uploads only aborted because the "files" folder was suddenyl gone.

**Comment by PVince81** [comment] 2016-03-04 14:26
@cmonteroluque another one for 9.0 and backports.
Will submit the PRs soon

**Comment by PVince81** [comment] 2016-03-04 14:32
PR here https://github.com/owncloud/core/pull/22860

**Comment by erlendd** [comment] 2016-03-04 14:59
> Thanks for the details. I see you have external storages, were you uploading files to one of the external storages ?

I wasn't uploading to an external storage when this happened.

> If @erlendd with "all files deleted" meant "all files from the cloud", then this fits with this theory. The "files" folder would get deleted in this case.

Yes, all files and folders within my owncloud (server) were deleted.

> @erlendd another info: you can check the following:
"oc_files_trash" that maps deleted file names to their original locations
select * from oc_filecache where path like 'files_trashbin/%' order by path;
"data/$user/files_trashbin/"
These have to be consistent for restoration to work.
I suspect that the folder name got truncated when the folder was created on disk, but the database contains the real names.

Ok, if I run the SQL command:
select * from oc_filecache where path like 'files_trashbin/%' order by path;
then I get 22430 rows.

SELECT * FROM `oc_files_trash`
then I get 38 rows.

**Comment by PVince81** [comment] 2016-03-04 15:27
@erlendd did you have a lot of outgoing shares or files marked as favorite as part of the deleted files ?

If not, then you could restore the files by copying them back on the filesystem:

1. On the filesystem, move all files from inside the hidden folder "$user/files_trashbin/files/.d1456875723/*" back into the files folder here "$user/files/"
1. Run `occ files:scan $userId` with your user id

The files should appear again in your account.

Note that this will make you lose outgoing shares or favorite flags set on the files.
Keeping them is a much more complex operation.

**Closed** 2016-03-04 18:33 UTC
Labels: app:files_trashbin, bug, in progress, needs info, sev1-critical
