### ISSUE TITLE
Don't disable encryption app on upgrades

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16904] opened 2015-06-12 12:22 UTC
The encryption "app" is not a 3rd party app. It's provided by the core team and thus should always work. It can be disabled temporarily when doing an upgrade, but it should immediately be re-enabled so that users can use their cloud right away.

### Env
8.0.3 to 8.0.4
Updated via Installatron
PHP 5.5
APCu
PHP sessions in Redis

### Logs
Nothing relevant. There is only a message about the upgrade taking place and then nothing

**Comment by karlitschek** [comment] 2015-06-12 12:24
@schiesbn This shouldn't happen because it is a shipped app. 
Any idea?

**Comment by schiesbn** [comment] 2015-06-15 10:12
I never saw this happen. I just tried a update from 8.0.3 to 8.0.4 and couldn't reproduce it.
Can you use the issue template to provide more information about your setup, log messages, etc.

Did you saw any messages during upgrade regarding the files_encryption app?

**Comment by oparoz** [comment] 2015-06-16 13:30
I've added a bit more info, but I think what's happening is that 8.0 does not work well with APCu since PHP is crashing every time oC has new files. So the upgrade process must simply be interrupted.

Here is the process:
1. Installatron updates oC
2. I go to the WebGUI and I'm told PHP has gone away
3. I restart php-fpm
4. I log in
5. I'm told my files are encrypted, but there is no key
6. I enable encryption again

**Comment by PVince81** [comment] 2016-03-01 21:58
@oparoz has this happened again or was it only on those older versions ?

**Comment by schiesbn** [comment] 2016-04-08 09:56
I close it because I could never re-produce it... If this is still a issue feel free to re-open it.

**Closed by schiesbn** 2016-04-08 09:56 UTC
Labels: app:files_encryption, feature:update
