### ISSUE TITLE
Activation of files_external or files_mv after upgrade to oc8 lead to blank page

### ISSUE THREAD

**Issue by benedetto** [owncloud/core#14409] opened 2015-02-20 21:53 UTC
### Steps to reproduce
1. upgrade to oc8 (with all apps disabled)
2. reenable files_mv or files_external
3. reload page -> site does no longer load but shows a blank page. The error message popping up in the apache and owncloud logs (see log section below) is the same no matter if the move or the external files app is enabled.

### Server configuration
**Operating system**:
Ubuntu 12.04
**Web server:**
apache 2.4.7
**Database:**
mysql
**PHP version:**
5.5.19-1+deb.sury.org~precise+1
**ownCloud version:** (see ownCloud admin page)
8.0.0.7
**Updated from an older ownCloud or fresh install:**
yes
**List of activated apps:**
```
Enabled:
 - activity
 - appframework
 - bookmarks
 - calendar
 - contacts
 - documents
 - files
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - firstrunwizard
 - gallery
 - news
 - search_lucene
```
**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'log_type' => 'owncloud',
  'logfile' => '/var/log/owncloud.log',
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 10485760,
  'overwritewebroot' => '/owncloud',
  'trusted_domains' => 
  array (
    0 => 'xxx',
  ),
  'secret' => 'xxx',
  'overwrite.cli.url' => '/owncloud',
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
### Client configuration
**Browser:**
Firefox 
**Operating system:**
Ubuntu 12.04
#### Web server error log
```
[Fri Feb 20 21:37:42.806170 2015] [:error] [pid 13962] [client xxx] PHP Fatal error:  Class 'OC_Filestorage_local' not found in /var/www/owncloud/apps/files_external/lib/config.php on line 927, referer: https://xxx/owncloud/index.php/apps/files/?dir=%2F
[Fri Feb 20 21:43:07.708526 2015] [:error] [pid 14068] [client xxx] PHP Fatal error:  Class 'OC_Filestorage_local' not found in /var/www/owncloud/apps/files_external/lib/config.php on line 927, referer: https://xxx/owncloud/index.php/settings/apps
[Fri Feb 20 21:43:11.834482 2015] [:error] [pid 14134] [client xxx] PHP Fatal error:  Class 'OC_Filestorage_local' not found in /var/www/owncloud/apps/files_external/lib/config.php on line 927, referer: https://xxx/owncloud/index.php/apps/activity/?filter=all
[Fri Feb 20 21:50:40.810546 2015] [:error] [pid 14170] [client xxx] PHP Fatal error:  Class 'OC_Filestorage_local' not found in /var/www/owncloud/apps/files_external/lib/config.php on line 927, referer: https://xxx/owncloud/index.php/apps/activity/?filter=all
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"33d9652a573cacf753208e42da81a4ed","remoteAddr":"93.135.138.135","app":"PHP","message":"Class 'OC_Filestorage_local' not found at \/var\/www\/owncloud\/apps\/files_external\/lib\/config.php#927","level":3,"time":"2015-02-20T21:50:40+01:00"}
```

**Comment by RealRancor** [comment] 2015-02-21 07:28
Hi,

have you done the manual upgrade like described in the docs and deleted all files and folders except /data/ and /config/ ? 

To me it looks that you're using the old OC7 versions of files_external and files_mv which are not compatible with OC8.

**Comment by RealRancor** [comment] 2015-02-21 09:08
@benedetto 
Seems the files_mv is even not compatible with OC8:

https://apps.owncloud.com/content/show.php?content=150271&forumpage=10

So there are two things to do:
1. Make sure you're running version 0.2.3 of files_external
2. Report an issue to the issue tracker of the files_mv tracker: https://github.com/eotryx/oc_files_mv/issues

**Comment by benedetto** [comment] 2015-02-21 12:19
@RealRancor I use the opensuse build service repo and upgraded via apt, so I guess this should have done the upgrade process the right way. On a second server that I administer the upgrade went fine this way and I can use the files_external app as intended. According to the Apps interface in the owncloud installation the version of files_external is 0.2.3, so this shoud be OK.

**Comment by RealRancor** [comment] 2015-02-21 12:49
The problem is tge upgrade is not dobe correctly when using the opensuse build service:

https://github.com/owncloud/core/issues/14026 , https://github.com/owncloud/documentation/issues/839

**Comment by benedetto** [comment] 2015-02-21 15:15
@RealRancor As written in my initial post, I had *all* apps disabled, so this seams not to be the reason here.

**Comment by RealRancor** [comment] 2015-02-21 15:31
Ah, sorry. Missed that one.

**Comment by fxshpac** [comment] 2015-02-23 08:10
I have the same issue with files_mv app after new installation of OC8. Any one can help make it compatible again? Really miss this function in web interface.

**Comment by RealRancor** [comment] 2015-02-23 09:32
@fxshpac
Thats something you should ask/request in the bugtracker of the app.

**Comment by PVince81** [comment] 2015-02-24 13:39
Thanks guys, closing as this is an issue in the files_mv app.

**Closed by PVince81** 2015-02-24 13:39 UTC
Labels: needs info

**Comment by benedetto** [comment] 2015-02-24 14:20
@PVince81 Maybe you got that wrong. To me it's not just an issue of files_mv but also of files_external. Enabling either of them did trigger the behaviour and log entries posted in my initial post.

**Comment by PVince81** [comment] 2015-02-24 14:21
@benedetto sorry, I mixed it up with someone having a similar issue.

The class "OC_Filestorage_local" doesn't exist any more, so it is likely that your mount.json contained a very old entry from an older OC version that got ignored so far. In the new version, it would fail with an exception. So in your case you should manually delete that entry.

**Comment by benedetto** [comment] 2015-02-24 14:47
@PVince81 Thx, that was indeed the clue!
