### ISSUE TITLE
Federated Cloud Sharing settings info icon not on same line

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28964] opened 2017-09-10 14:53 UTC
### Steps to reproduce
1. Go to settings, admin, sharing.
2. Observe the "i" info icon after the "Federated Cloud Sharing" heading.

### Expected behaviour
The info icon should be directly after the heading text.

### Actual behaviour
The info icon appears on the next line.
![federated-cloud-sharing-info-icon-1](https://user-images.githubusercontent.com/1535615/30250033-fa656ecc-9667-11e7-8cba-208a3d188b95.png)

### Server configuration
Dev environment from git master in a VM.

**Comment by davitol** [comment] 2017-09-11 07:26
Close due to is a dupe of https://github.com/owncloud/core/issues/28936

**Closed by davitol** 2017-09-11 07:26 UTC
