### ISSUE TITLE
updateapp.php not working correctly with news app

### ISSUE THREAD

**Issue by paroj** [owncloud/core#24453] opened 2016-05-05 17:04 UTC
### Steps to reproduce
1. update the news app using the owncloud updater
2. check the log

### Expected behaviour
Temporary files correctly deleted

### Actual behaviour
Temporary files not correctly deleted

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:**

**PHP version:** 7.0.5

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** updated from 8

**Where did you install ownCloud from:** debian repository

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**Are you using encryption:** no

#### ownCloud log (data/owncloud.log)
```json
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"unlink(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/helper.php#227","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news\/vendor\/bin): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news\/vendor): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder\/news): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#225","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
{"reqId":"qrODXNeGf59YH0Hh67UI","remoteAddr":"192.168.178.xx","app":"PHP","message":"rmdir(\/tmp\/oc_tmp_56egK8-folder): Directory not empty at \/var\/www\/owncloud\/lib\/private\/helper.php#231","level":3,"time":"2016-05-05T16:36:50+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"me"}
```

### ls /tmp/oc_tmp_56egK8-folder/news/vendor/bin/

```
picofeed
```

**Comment by RealRancor** [comment] 2016-05-05 17:36
Have noticed the same in the past but completely forgot to report it here. It seems this is caused because the ``vendor/bin/picofeed`` is a symlink to ``vendor/fguillot/picofeed/picofeed``

**Comment by BernhardPosselt** [comment] 2016-05-06 10:32
I guess the install/update script does not remove symlinks proplery

**Comment by RealRancor** [comment] 2016-05-12 08:24
@paroj Btw. are you able to update the news app via the GUI at all? I'm still having the issue described in https://github.com/owncloud/core/issues/18391 so just wondering if you're also facing the same issue?

**Comment by paroj** [comment] 2016-05-12 13:43
the update itself succeeds - I just have to remove the `/tmp/oc_tmp_56egK8-folder/news/vendor/bin/` folder manually afterwards

**Comment by PVince81** [comment] 2016-06-23 16:48
@VicDeo

**Comment by VicDeo** [comment] 2016-06-23 17:15
yep. This will unlink target and not symlink itself.
https://github.com/owncloud/core/blob/stable9/lib/private/helper.php#L227

**Comment by VicDeo** [comment] 2016-06-23 17:34
@PVince81 should be fixed in master with https://github.com/owncloud/core/pull/24899
Backport changes in helper.php only?

**Comment by PVince81** [comment] 2016-07-04 15:02
Fix is here https://github.com/owncloud/core/issues/25255

**Closed by PVince81** 2016-07-04 15:02 UTC
Labels: bug

**Comment by Pazu** [comment] 2016-11-08 12:51
Sorry to post in an old issue, but I've seen these messages in my log for a long time and still see them after upgrading to 9.1.1. Shouldn't these be gone as of 9.1 if this is fixed?

` rmdir(/tmp/oc_tmp_XS146u-folder): Operation not permitted at /home/foo/public_html/lib/private/legacy/helper.php#218 `

According to my shared hosting provider:

>the RM errors are not related to anything with ownCloud. you dont have access to TMP and its not needed for ownCloud

**Comment by RealRancor** [comment] 2016-11-08 13:05
@Pazu I think this is unrelated to this issue here. The issue discussed here was about the symlink which wasn't removed correctly caused the posted error in the initial report.

Your issue / error is different and is caused by your environment setting the /tmp folder as a temp directory for PHP.

**Comment by VicDeo** [comment] 2016-11-08 13:31
@Pazu you can create a dedicated `tmp` for your owncloud, e.g.  `/home/foo/tmp` and `tempdirectory` in config.php to use it:
https://github.com/owncloud/core/blob/stable9.1/config/config.sample.php#L1093
