### ISSUE TITLE
'Exclude groups from sharing'  doesn't work if user belongs to more groups

### ISSUE THREAD

**Issue by sirio81** [owncloud/core#25320] opened 2016-07-01 06:37 UTC
Steps to reproduce
1. create a user 'test01' and add it to group 'noshare'
2. test01 now can't create any share
3. add test01 to another group
4. test01 now can share files and folders

Expected behaviour
the user that belongs to **any** of the group listed in 'Exclude groups from sharing', it should unable to create shares.

Actual behaviour
As of now, **all** the groups the user belongs to, have to be listed in 'Exclude groups from sharing' before I'm able to deny him the possibility of sharing files.
Otherwise the user has to belong to a single group (the one I'm excluding).

Server configuration
Operating system: debian 8
Web server: apache2
Database: mariadb
PHP version: 5.6
ownCloud version (see ownCloud admin page): tested on 8.2.2 and 9.0.3
Updated from an older ownCloud or fresh install: update from 9.0.1

**Comment by PVince81** [comment] 2016-07-04 07:50
Duplicate of https://github.com/owncloud/core/issues/16346

**Closed by PVince81** 2016-07-04 07:50 UTC
