### ISSUE TITLE
Group menu bar in user page will show in all parts of the page 

### ISSUE THREAD

**Issue by rroseselavy42** [owncloud/core#21321] opened 2015-12-22 06:52 UTC
### Steps to reproduce
1. Open user page
2. Scroll down
3. click group menu

### Expected behaviour
Tell us what should happen
menu options should appear above or below where clicked on menu
### Actual behaviour
Tell us what happens instead
Menu appears in semi random places on screen
### Server configuration
**Operating system**:
 Debian 8.1
**Web server:**
 Apache 2.4
**Database:**
 MariaDB
**PHP version:**
 5.6.14
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
updated from older
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - notifications: 0.1.0
  - ownbackup: 0.3.7
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap
                

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocq67yknqyn2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domesticworkers.org"
        ],
        "datadirectory": "\/srv\/owncloud\/",
        "overwrite.cli.url": "http:\/\/cloud.domesticworkers.org\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "domesticworkers.org",
        "mail_smtphost": "smtp-relay.gmail.com",
        "mail_smtpport": "587",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "loglevel": 2,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "trashbin_retention_obligation": "auto"
    }
}
               
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chromium Version 47.0.2526.106 (64-bit)  (also confrimed on firefox 42 and Chrome)
**Operating system:**
Arch Linux, (Also confirmed on Windows 10)
#### Web server error log
```
[Mon Dec 21 06:25:28.799629 2015] [mpm_prefork:notice] [pid 30211] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Mon Dec 21 06:25:28.799691 2015] [core:notice] [pid 30211] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 21 18:05:20.823060 2015] [ssl:error] [pid 22478] AH02032: Hostname 45.63.9.164 provided via SNI and hostname cloud.domesticworkers.org provided via HTTP are different
[Tue Dec 22 01:28:27.528834 2015] [authz_core:error] [pid 2258] [client 127.0.0.1:48172] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

```

#### ownCloud log (data/owncloud.log)
```
"reqId":"vULZQ45H\/PID5xsoDGL\/","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/srv\/owncloud\/\/jessie\/files\/Documents\/Example.odt): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"vULZQ45H\/PID5xsoDGL\/","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":268}","level":4,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"\/4yTz\/FIxSykV0XO9+aL","remoteAddr":"127.0.0.1","app":"no app in context","message":"Encryption module \"OC_DEFAULT_MODULE\" not found, file will be stored unencrypted (Module with id: OC_DEFAULT_MODULE does not exist.)","level":2,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"\/4yTz\/FIxSykV0XO9+aL","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/srv\/owncloud\/\/jessie\/files\/Photos\/Paris.jpg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"\/4yTz\/FIxSykV0XO9+aL","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":268}","level":4,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"hm6cfSKMtJMzFIKaf19e","remoteAddr":"127.0.0.1","app":"no app in context","message":"Encryption module \"OC_DEFAULT_MODULE\" not found, file will be stored unencrypted (Module with id: OC_DEFAULT_MODULE does not exist.)","level":2,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"hm6cfSKMtJMzFIKaf19e","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/srv\/owncloud\/\/jessie\/files\/Photos\/San Francisco.jpg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"hm6cfSKMtJMzFIKaf19e","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":268}","level":4,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"x4BFwJPEqeGi+ffH0o+m","remoteAddr":"127.0.0.1","app":"no app in context","message":"Encryption module \"OC_DEFAULT_MODULE\" not found, file will be stored unencrypted (Module with id: OC_DEFAULT_MODULE does not exist.)","level":2,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"x4BFwJPEqeGi+ffH0o+m","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/srv\/owncloud\/\/jessie\/files\/Photos\/Squirrel.jpg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"x4BFwJPEqeGi+ffH0o+m","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(82): OC\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":268}","level":4,"time":"2015-12-06T06:24:58+00:00"}
{"reqId":"9UQifw4EJzJ8ark3\/AWR","remoteAddr":"74.71.135.123","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-12-06T19:52:16+00:00"}
{"reqId":"YnINsqZw5PJB5rwnOLB+","remoteAddr":"74.71.135.123","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-12-06T19:55:03+00:00"}
{"reqId":"8UFK0srVCSC4qbrMqKlw","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:40:35+00:00"}
{"reqId":"C0FncaWoMHtwk1lLwnUC","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:40:52+00:00"}
{"reqId":"VGuqNQVs7QmnI0DmAEnG","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:41:06+00:00"}
{"reqId":"j6jZ+B22\/4DfmK073Liw","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:41:15+00:00"}
{"reqId":"IFxt4lHd1qFwIlcvu++6","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:41:20+00:00"}
{"reqId":"c\/iQOVy32bwjnhJtU1Qv","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:43:24+00:00"}
{"reqId":"4vGHotCSSo5ozmjNEsxr","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:45:19+00:00"}
{"reqId":"uC+meMZYIYwansbBG\/vO","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T16:47:28+00:00"}
{"reqId":"j4qlLzk8sy3Y8+NCSMGI","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T17:05:38+00:00"}
{"reqId":"7mSu2jWVyuVIlFSgGx6M","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-15T17:05:50+00:00"}
{"reqId":"uSCqnC\/3XjBCYGG7AbmK","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-16T06:11:35+00:00"}
{"reqId":"iR6kfpvfFTnpEH4nr0IG","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-16T06:13:50+00:00"}
{"reqId":"mSr7W9qaIATmW39iphxt","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-16T06:18:14+00:00"}
{"reqId":"3NfhSFjL3LRZn9q4pTGR","remoteAddr":"82.238.200.58","app":"core","message":"Login failed: 'mhart' (Remote IP: '82.238.200.58')","level":2,"time":"2015-12-16T13:54:48+00:00"}
{"reqId":"Y1CfV2pNugy0Ggtnmwhy","remoteAddr":"98.14.98.50","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-12-22T06:28:24+00:00"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

I don't have anything good to add here.
screenshot


```
example:
![example](http://i.imgur.com/wBSaLEY.png)

**Comment by MorrisJobke** [comment] 2015-12-22 08:51
cc @blizzz for user management

@PVince81 @rullzer This is afaik our own implementation of a selection drop down which is quite hard to maintain.

**Comment by PVince81** [comment] 2015-12-22 08:56
Yes, that's the multiselect... doesn't behave properly on scroll.

Duplicate of https://github.com/owncloud/core/issues/20503

**Closed by PVince81** 2015-12-22 08:56 UTC
Labels: bug, settings:users, sev3-medium
