### ISSUE TITLE
Owncloud not upgrading

### ISSUE THREAD

**Issue by Brun084** [owncloud/core#18305] opened 2015-08-14 08:39 UTC
### Steps to reproduce
1. Update owncloud by "yum update"
2. Go to web interface
3. Start update

### Expected behaviour
Owncloud runs its update successfully.

### Actual behaviour
Owncloud throws an error:
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

When using the command line "./occ upgrade"
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)

### Server configuration
**Operating system**:
CentOS release 6.7 (Final)

**Web server:**
Apache/2.2.15 (Unix)
Server built:   Jul 24 2015 11:52:28

**Database:**
?
**PHP version:**
PHP 5.4.44 (cli) (built: Aug  6 2015 07:41:49) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**ownCloud version:** (see ownCloud admin page)
Updating ownCloud to version 8.1.1

**Updated from an older ownCloud or fresh install:**
In the process of updating

**List of activated apps:**
Tasks
Calendar
some more,...

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occ14856d912',
  'passwordsalt' => '******',
  'trusted_domains' => 
  array (
    0 => '****.de',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.8',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --invisible ',
  'forcessl' => true,
  'secret' => '****',
  'memcache.local' => '\\OC\\Memcache\\APC',
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APC for local cache (Is the matching PHP module installed and enabled ?)

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' => 'occ14856d912',
  'passwordsalt' => '******',
  'trusted_domains' => 
  array (
    0 => '****.de',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.8',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --invisible ',
  'forcessl' => true,
  'secret' => '****',
  'memcache.local' => '\\OC\\Memcache\\APC',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Activated but not actively used.

**Are you using encryption:** yes/no
I think that I used it in a version before 8.0 but it got deactivated after some upgrade?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Mozilla Firefox 40.0

**Operating system:**
Ubuntu 14.04 LTS

#### Web server error log
Nor errors referring to owncloud

Insert your webserver log here
12.34.56.78 - bruno [14/Aug/2015:06:26:03 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:06:26:03 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:06:26:03 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:07:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:07:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
80.82.70.24 - - [14/Aug/2015:07:20:55 +0200] "GET http://httpheader.net HTTP/1.1" 403 4961 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.28) Gecko/20120306 Firefox/3.6.28 (.NET CLR 3.5.30729)"
89.248.160.192 - - [14/Aug/2015:07:52:45 +0200] "GET / HTTP/1.0" 403 4961 "-" "Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0"
12.34.56.78 - bruno [14/Aug/2015:07:55:42 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:07:55:54 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:08:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:08:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:08:36:11 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:08:36:18 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:09:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:09:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:10:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.78 - bruno [14/Aug/2015:10:02:21 +0200] "REPORT /owncloud/remote.php/caldav/calendars/bruno/privat/ HTTP/1.1" 503 5670 "-" "Evolution/3.10.4"
12.34.56.90 - - [14/Aug/2015:10:14:43 +0200] "HEAD / HTTP/1.1" 403 - "-" "HTTPClient/1.0 (2.6.0.1, ruby 1.9.3 (2015-01-29))"
12.34.56.90 - - [14/Aug/2015:10:14:43 +0200] "GET /?Connection=close&follow_redirect=true HTTP/1.1" 403 4961 "-" "HTTPClient/1.0 (2.6.0.1, ruby 1.9.3 (2015-01-29))"
12.34.56.90 - - [14/Aug/2015:10:14:44 +0200] "HEAD / HTTP/1.1" 403 - "-" "HTTPClient/1.0 (2.6.0.1, ruby 1.9.3 (2015-01-29))"
12.34.56.90 - - [14/Aug/2015:10:14:44 +0200] "GET /?Connection=close&follow_redirect=true HTTP/1.1" 403 4961 "-" "HTTPClient/1.0 (2.6.0.1, ruby 1.9.3 (2015-01-29))"
127.0.0.1 - - [14/Aug/2015:10:17:09 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.2.15 (CentOS) (internal dummy connection)"

#### ownCloud log (data/owncloud.log)
{"reqId":"L4xFJ2uN9wYiQN\/6pNWt","remoteAddr":"109.45.0.235","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:33:35+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/principals\/Martin\/"}
{"reqId":"o0Nq5uoema3ISXhsHHKP","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:33:47+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"7vdGmvGw6hA6zuOIUJmz","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:34:19+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"OWItuwOPvnoNAnoJeIVN","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:34:51+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"NnDOaGobPinBhHHpok+q","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:35:23+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"FZsePtM4iJuTbVIMPdPb","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:35:57+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"M605yMnCFeQs25WsERWT","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:36:27+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"PO28GCBVwzQSIgTLV8Y4","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:36:59+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"t9\/58nyOeWIZvfns5PGX","remoteAddr":"95.90.249.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-08-14T08:37:31+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

**Comment by MorrisJobke** [comment] 2015-08-14 09:42
Duplicate of #18224

**Closed by MorrisJobke** 2015-08-14 09:42 UTC
