### ISSUE TITLE
Encoding issue on tar and zip names

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#19862] opened 2015-10-19 08:14 UTC
![bildschirmfoto von 2015-10-19 10-13-50](https://cloud.githubusercontent.com/assets/1005065/10572597/223b8f52-764a-11e5-823a-789046fa31db.png)

**Comment by DeepDiver1975** [comment] 2015-10-19 08:14
summoning encoding overlord @LukasReschke  .... THX

**Comment by LukasReschke** [comment] 2015-10-19 11:17
Ah. Great. Firefox and Chrome behave differently here as well. Let me see how we can improve this whole encoding magic. But still better than Safari :see_no_evil:

**Comment by butonic** [comment] 2015-10-21 10:18
@LukasReschke for file downloads we added some magic in https://github.com/owncloud/core/pull/929/files. Maybe that is a pointer
.

**Comment by PVince81** [comment] 2015-11-03 17:15
If it's a regression maybe a bisect could help ?

**Comment by DeepDiver1975** [comment] 2015-11-04 11:15
> If it's a regression maybe a bisect could help ?

It's a regression in terms of user expectation is broken - the code is new and never properly handled this situation.

**Comment by LukasReschke** [comment] 2015-11-04 16:52
Broken since ages for ZIP as well and requires some upstream magic to get fixed. I'd propose to move this to 9.0.

- PHPZipStreamer: https://github.com/McNetic/PHPZipStreamer/pull/28
- TarStreamer: https://github.com/owncloud/TarStreamer/pull/7

Also then we need to remove https://github.com/owncloud/core/blob/05359e384e7b33b6928ab239f4d7f518d250c236/lib/private/streamer.php#L54-L57 after merging this.

**Comment by PVince81** [comment] 2015-11-04 16:59
@cmonteroluque in the light of @LukasReschke's comments, can we move this to 9.0 ? (usually not a good idea to update upstreams/libs in backports)

**Comment by PVince81** [comment] 2016-02-15 10:44
Looks like the upstream fix wasn't merged yet. :frowning:

**Comment by DeepDiver1975** [comment] 2016-02-15 10:53
> TarStreamer: owncloud/TarStreamer#7

merged

**Comment by DeepDiver1975** [comment] 2016-02-16 08:20
> PHPZipStreamer: McNetic/PHPZipStreamer#28

merged as well now

**Comment by MorrisJobke** [comment] 2016-02-16 08:25
It is fixed with the latest merge. (before: reproducible, after: fixed)

**Comment by DeepDiver1975** [comment] 2016-02-16 08:29
@MorrisJobke we still need to update ZipStreamer

**Comment by MorrisJobke** [comment] 2016-02-16 12:27
> @MorrisJobke we still need to update ZipStreamer

Ah ... sorry - thought this was only about the tarstreamer

**Comment by LukasReschke** [comment] 2016-02-17 23:06
3rdparty at https://github.com/owncloud/3rdparty/pull/250
core at https://github.com/owncloud/core/pull/22489

**Closed** 2016-02-18 10:22 UTC
Labels: bug, in progress, regression, sev2-high
