### ISSUE TITLE
second Googledrive does not open window to authenticate

### ISSUE THREAD

**Issue by op6sie** [owncloud/core#31154] opened 2018-04-16 23:27 UTC
### Steps to reproduce
1. Add Google drive as in the instructions
2. 
3.

### Expected behaviour
when pressing "sta toegang toe" (allow access) 
i expect to get a google sheet where the site requests access.

### Actual behaviour
nothing get a red square in frond of the drive name

### Server configuration
**Operating system**: Ubuntu server 16.04.4 LTS

**Web server:**  Apache2

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** (see ownCloud admin page)
10.0.7 stable

**Updated from an older ownCloud or fresh install:**
Fresh with 
https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html

**Where did you install ownCloud from:** apt-get

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
https://op6sie.myqnapcloud.com/owncloud/index.php/settings/integrity/failed
No errors have been found.

**The content of config/config.php:**

[config_report_20180416.zip](https://github.com/owncloud/core/files/1917632/config_report_20180416.zip)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
root@owncloud:/var/www/owncloud# sudo -u www-data php ./occ app:list
Enabled:
  - audioplayer: 2.2.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_pdfviewer: 0.8.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - ownbackup: 17.7.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.6
  - templateeditor: 0.3
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_sharing
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
**Are you using encryption:** no
**Are you using an external user-backend, no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7/Ubuntu Desktop 16.04.4 LTS

Please tell me where to find the logs.
owncloud log has been found but unclear if there is sencitive data in?

Cheers Tonny

**Comment by ownclouders** [comment] 2018-04-16 23:33
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9284 (Mobile sidebar doesn’t animate when opening), https://github.com/owncloud/core/issues/16100 (ownCloud filepicker does not resize according to window), https://github.com/owncloud/core/issues/12326 (User menu doesn’t close on opening Apps menu), https://github.com/owncloud/core/issues/24741 ("Open documentation" button does not work in Updater section), and https://github.com/owncloud/core/issues/11353 (Search doesn't open folder directly but only parent folder).

**Comment by hodyroff** [comment] 2018-04-18 11:28
You say second Google Drive ... so this means the first one for this user works. Can you try with another user?

**Comment by op6sie** [comment] 2018-04-18 11:54
I can try, but i have 8 Google drive total.
And i like to have them all.

Also on another account it will not open the authentication screen.

Thx doe the Idea tho

Cheers
Tonny

Op wo 18 apr. 2018 13:28 schreef hodyroff <notifications@github.com>:

**Comment by ownclouders** [comment] 2018-05-03 01:00
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by collaorodrigo7** [comment] 2019-04-03 06:04
What is the status of this?
I am experiencing (I think) the same problem.
Basically you can add only one google drive account.
When you try to add a second one you only get this error on the console:
`POST https://cloud.rodrigocollao.com/index.php/apps/files_external/globalstorages 422 (Unprocessable Entity)`
```
{message: "Unsatisfied authentication mechanism parameters"}
message: "Unsatisfied authentication mechanism parameters" 
```

And no window for authentication opens or anything.
Is it expected to support more than one google drive account?

I spent a couple of hours trying to figure this out. To discard that the problem was any of my accounts I try with multiple accounts. I was able to add any one of them when there were NO OTHER GDrive accounts linked.
Once I have one GDrive setup, then I can not add any other one.

I can provide more info you need.
Thanks! (Own Cloud is great!)

**Comment by collaorodrigo7** [comment] 2019-04-03 07:26
I was able to add multiple Google Drive Accounts!!!! (So excited)

The way I was able to do it was as following:

1. I deleted all the external storages.
2. I added one google drive as normal, and everything worked fine. (Keep this page open)
3. I updated the database manually, and delete the record that was just created in table `oc_external_mounts` (update `mount_id` based on your data)

       DELETE from oc_external_mounts where mount_id=1;

4. I refresh the page where I added the external storage config page, and no external storage showed up. (Even though the external storage was still linked)
5. I added the new google account just like the first one, and everything worked just fine!
6. Update `oc_external_mounts` to put back the record we deleted on step **3**
  insert into oc_external_mounts (mount_id, mount_point, storage_backend,auth_backend, priority, type) (again update the mount_id based on what you had before)

       insert into oc_external_mounts (mount_id, mount_point, storage_backend,auth_backend, priority, type) VALUES (1,'/G', 'googledrive', 'oauth2::oauth2', 100,1);

7. That is it.. repeat as needed. I repeated it 2 times, so on step 3 I had 2 delete to records, then create the new one and then on 6 I inserted the 2 records again.

I think this should give a pretty good idea of where the problem is in the client, I would be happy to contribute and help fixing it, but I would definetly need help/guidence from someone.


Here is a scrensshot of my final setup:

![image](https://user-images.githubusercontent.com/24518083/55460162-db1c8900-55b6-11e9-953d-f0f8b7f622cb.png)

**Comment by hodyroff** [comment] 2019-04-03 07:37
Wow, thanks for looking into this. I was about to write that a second one is not supported this morning ... you solved it and I really appreciate it. Lets see that somebody helps with enabling it generally.

**Comment by collaorodrigo7** [comment] 2019-04-03 07:40
Glad to know it helped! :)
And thanks for reopening

**Comment by PVince81** [comment] 2019-04-05 10:35
not sure if related, there was a patch proposal here: https://github.com/owncloud/core/issues/31497

@karakayasemi can you investigate and fix ? I suggest to work on stable10 as the app isn't decoupled yet there. we can port the change to the separate app later on

**Comment by karakayasemi** [comment] 2019-04-12 13:48
fixed with https://github.com/owncloud/core/pull/34987

**Closed by karakayasemi** 2019-04-12 13:48 UTC
Labels: bug
