### ISSUE TITLE
Web: When opening/reload a URL with index.app/apps/files/?dir=/somesubdir&fileid=123 I see the ROOT directory contents for a split second and only then somesubdir

### ISSUE THREAD

**Issue by guruz** [owncloud/core#28399] opened 2017-07-14 13:52 UTC
Server 10.0.2
Normal storage
Google Chrome

Easier to reproduce by reloading or pressing enter on URL
harder to see when opening new window
Maybe check web inspector to see actual flow?

Could/Should be avoided probaby.

**Comment by PVince81** [comment] 2017-07-17 07:39
duplicate of https://github.com/owncloud/core/issues/27890

**Closed by PVince81** 2017-07-17 07:39 UTC
Labels: performance
