### ISSUE TITLE
Owncloud Upgrade 10.0.10.4 to 10.2.1 fails due to incompatible polls app

### ISSUE THREAD

**Issue by mister23** [owncloud/core#36591] opened 2019-12-14 13:50 UTC
### Steps to reproduce
1. click start upgrade
2. error message is shown
3.

### Expected behaviour
I expected that the upgrade routine works even if the polls app is not compatible with version 10.2.1

### Actual behaviour
Tell us what happens instead
Upgrade to 10.2.1

_"OC\RepairException: Upgrade is not possible
        Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable polls
        Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.2/go.php?to=admin-marketplace-apps"_

-> the problem here is, that I dont have ssh access to this machine.

### Server configuration
**Operating system**:

**Web server:**

**Database:**
mySQL

**PHP version:**
-> 7.1

**ownCloud version:** (see ownCloud admin page)
-> 
[config_cleaned-php.log](https://github.com/owncloud/core/files/3963880/config_cleaned-php.log)

10.0.10.4

**Updated from an older ownCloud or fresh install:**
-> updated from an older ownCloud version 10.0.10.4

**Where did you install ownCloud from:**
-> "Community" ?!

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
[config_cleaned-php.log](https://github.com/owncloud/core/files/3963884/config_cleaned-php.log)
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
[owncloud.log](https://github.com/owncloud/core/files/3963872/owncloud.log)

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment] 2019-12-17 19:42
Not fail installation, only need manual thing?

> Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable polls
Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.2/go.php?to=admin-marketplace-apps"

Everything explained already by above?

**Comment by VicDeo** [comment] 2019-12-19 14:53
> the problem here is, that I dont have ssh access to this machine.

duplicate of https://github.com/owncloud/core/issues/32388
```
UPDATE oc_appconfig SET configvalue = 'no' WHERE configkey = 'enabled' AND appid IN ('polls');
```

**Closed by VicDeo** 2019-12-19 14:53 UTC

**Comment by mister23** [comment] 2019-12-19 22:16
That worked! Thank you!
