### ISSUE TITLE
upgrade disables all apps and removes enabled-for-group settings

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/core#21654] opened 2016-01-12 14:14 UTC
### Steps to reproduce
1. OC installation, e.g. 8.2.1
1. enable some apps, some of which for specific groups only
2. upgrade to v8.2.2, run ./occ upgrade

### Expected behaviour
during upgrade, all apps get disabled. after the upgrade, apps should be enabled again, maintaining the permission settings. If an app should fail to be enabled, then it should remain disabled and a notice given.

### Actual behaviour
during the upgrade, all apps get disabled. the list of disabled apps also include the ones that have not been enabled in the first place. this makes it difficult to know which apps have to be re-enabled manually. here, at least the already-disabled apps should not be listed.

after upgrade, no apps that have been enabled, get automatically re-enabled.

when re-enabling the apps, also the settings regarding whether or not the app shall be available to specific groups and the selection of groups is lost and has to be re-entered.

### Server configuration
**Operating system**:

    # uname -a
    Linux jackal 3.19.0-41-generic #46~14.04.2-Ubuntu SMP Tue Dec 8 17:46:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Server Version: **Apache/2.4.7** (Ubuntu) (...) mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.14 (...) OpenSSL/1.0.1f (...)
Server MPM: prefork
Server Built: Oct 14 2015 14:20:21
Apache API Version 	20120211 

**Database:**
Server type: **MySQL**
Server version: **5.5**.46-0ubuntu0.14.04.2 - (Ubuntu)

**PHP version:**
**5.5**.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
8.2.1 -> **8.2.2**

**Updated from an older ownCloud or fresh install:**
updated

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "support.metaworx.ch"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "installed": true,
        "forcessl": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps.auto",
                "url": "\/apps.auto",
                "writable": true
            },
            {
                "path": "\/var\/www\/owncloud\/apps.manual",
                "url": "\/apps.manual",
                "writable": false
            }
        ],
        "appstoreenabled": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "metaworx.ch",
        "loglevel": "0",
        "logfile": "\/var\/log\/owncloud.log",
        "theme": "",
        "maintenance": false,
        "dbname": "owncloud_metaworx",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by RealRancor** [comment] 2016-01-12 14:31
From my PoV a duplicate of https://github.com/owncloud/core/issues/18721 where "Non-disruptive Upgrades" are discussed. If that is implemented apps don't need to be disabled during the upgrade.

**Comment by karlitschek** [comment] 2016-01-12 14:35
Yes. This is a duplicate

**Closed by karlitschek** 2016-01-12 14:35 UTC
