### ISSUE TITLE
db:convert-type: Comumn not found 'execution_duration'

### ISSUE THREAD

**Issue by frantsch** [owncloud/core#29594] opened 2017-11-16 10:28 UTC
### Steps to reproduce
1. Installed Owncloud Version 10.0.3.3
2. Created a fresh, empty MySQL-Database for my Owncloud to be used
3. Executed _php ./occ db:convert-type --password="***password***" -all-apps mysql ***user*** ***host*** ***database***_

### Expected behaviour
Creation of Owncloud-specific tables in MySQL and migration of Owncloud to use MySQL instead of SQLite

### Actual behaviour
_[Soctrine/DBAL/Driver/PDOException]
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'execution_duration' in 'field list'_
The MySQL-column in quention is missing, because it is not generated by the conversion-tool

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
10.0.3.3

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
Download from owncloud.org

**Comment by kdslkdsaldsal** [comment] 2017-11-16 11:18
Closing as a duplicate of https://github.com/owncloud/core/issues/27075

As explained in the release notes of 10.0 the migration doesn't work at all:

https://doc.owncloud.org/server/latest/admin_manual/release_notes.html#converting-the-database-type-doesn-t-work

**Closed by kdslkdsaldsal** 2017-11-16 11:18 UTC
Labels: bug

**Comment by scorninpc** [comment] 2019-06-23 01:30
I just could convert add the column in the db_structure.xml

```
<field>
	<name>execution_duration</name>
	<type>integer</type>
	<default>-1</default>
	<notnull>TRUE</notnull>
</field>
```

Any other method fail
