### ISSUE TITLE
Allow uploading of folders in the upload dialog.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16235] opened 2015-05-11 11:32 UTC
Now when you open the upload dialog you are not able to choose folders, only files.
Uploading folders is possible using drag and drop in chrome and using webdav. But not in the dialog.

I suggest to add this feature to uploading dialog.

**Comment by PVince81** [comment] 2015-05-11 13:57
@SergioBertolinSG it is not technically possible to change the upload dialog (which belongs to Chrome) to allow selecting multiple files. There is however the possibility to only allow selecting folders by adding a special attribute (and it only works in Chrome), but in that case the user cannot select files, so we'd need two buttons... I don't think we want this as it would clutter the UI.

So until the browsers catch up and provide such possibility, there isn't much we can do.

**Comment by SergioBertolinSG** [comment] 2015-05-12 07:11
Firefox expects to have it in the future:
https://bugzilla.mozilla.org/show_bug.cgi?id=846931
Perhaps we can vote importance to have it.

**Comment by RealRancor** [comment] 2016-09-11 09:49
@PVince81 @SergioBertolinSG Duplicate of https://github.com/owncloud/core/issues/16235

**Comment by PVince81** [comment] 2016-10-21 12:05
Closing as dupe of https://github.com/owncloud/core/issues/10997

**Closed by PVince81** 2016-10-21 12:05 UTC
Labels: app:files, enhancement
