### ISSUE TITLE
traffic limitation per user / group

### ISSUE THREAD

**Issue by thowen** [owncloud/core#12787] opened 2014-12-11 14:03 UTC
### Expected behavior
* Option to set traffic (transferred amount of data per month) limitation per user / group.
* When the traffic limitation is reached, the service of the group / user should be suspended.
* Possibility to set the start-day (registration date) of the month. On this day ownCloud should reset the used traffic, like internet volume in smartphone contracts. For example the registration date was the 30th of January, so the default set start-day is the "30"th. In months (e. g. February) with less days, it resets the traffic on the last day of the month. But for example in March again on the set day (30th).
* When the traffic amount had a reset, the service of the group / user should be unsuspended.

### Actual behavior
No possibility of traffic limitation.

**Comment by PVince81** [comment] 2016-10-07 15:25
duplicate of https://github.com/owncloud/core/issues/7705

**Closed by PVince81** 2016-10-07 15:25 UTC
Labels: enhancement
