### ISSUE TITLE
wrong .htaccess hash after disabling Options -MultiViews

### ISSUE THREAD

**Issue by Skippidar** [owncloud/core#24051] opened 2016-04-18 08:32 UTC
i'm using php 5.5 as FastCGI and it has no option MultiViews, so i disabled it in .htaccess
now it says that .htaccess has invalid hash. it's annoying =)
### Server configuration

**Operating system**:

**Web server:** 

**Database:** MysqL 5.1.73

**PHP version:** 5.5 FastCGI

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** official website

```
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 451fd1fa17239d8d1fa31c5b22dce5ef6710b93ff90a4705416e452d3f4cf22f387b49e98bd01a69ce2a2da8a2613298c37cd306955ed16808755afbbc32d38f
                            [current] => d76776b697ae33057cfc9dcce8a390491203bcafe08cac3baa9de6f4b9cd6b0462cd02294c0f330edb0770155322d7b5a84f55f46fe193128c039e6a47c09a8e
                        )

                )

        )

)
```

**Comment by DeepDiver1975** [comment] 2016-04-18 08:48
@LukasReschke

**Comment by LukasReschke** [comment] 2016-04-18 09:26
Some more information required:

1. What is the error you see with the original `.htaccess` file.
2. How did you install and configure your Apache server and PHP? Which mod do you use? (mod_fcgid / mod_fastcgi / …?)
3. What do you mean by "disabled it"?

**Comment by Skippidar** [comment] 2016-04-18 13:55
1. With the original .htaccess i see 500 server error: 
'[Mon Apr 18 03:59:55 2016] [alert] [client 188.162.64.7] /var/www/user/data/www/site_url/.htaccess: Option MultiViews not allowed here, referer: http://site_url/'
2. I'm using web hosting, i don't know which mod they use.
3. Just added '#' at the beginning of the line

**Comment by LukasReschke** [comment] 2016-04-18 14:02
That's then caused by your web hoster disabling `MultiViews`, the probably have something like this in the configuration:

>   AllowOverride AuthConfig FileInfo Indexes Limit Options=All,MultiViews

instead of

>   AllowOverride All

**Comment by Skippidar** [comment] 2016-04-18 15:47
AllowOverride isn't allowed too =(

**Comment by Skippidar** [comment] 2016-04-18 16:00
As hoster said, MultiViews is disabled by default.

**Comment by PVince81** [comment] 2016-04-19 09:53
Setting to medium as there is a workaround.
Also, moving to 9.0.3. @cmonteroluque

**Comment by PVince81** [comment] 2016-04-19 09:54
One idea would be to remove that line permanently and "hope" that people have configured their servers properly as per the documentation which states that MultiViews must always be disabled: https://doc.owncloud.org/server/8.1/admin_manual/release_notes.html#disable-apache-multiviews

Then another idea would be to try and add a warning in the admin page in case it isn't.

**Comment by Skippidar** [comment] 2016-04-19 17:12
What if create file named "multiviews.html" printing only "enabled" and if "site_dir/multiviews" returns "enabled" - show error message.

**Comment by PVince81** [comment] 2016-12-08 18:22
I'd like to close this as the documentation says that Multiviews must be disabled, so this case is not officially supported.

However if someone wants to contribute a PR to provide a solid workaround for this then feel free to submit one.

**Closed by PVince81** 2016-12-08 18:22 UTC
Labels: bug, feature:code-signing-integrity, sev3-medium
