### ISSUE TITLE
Endless refresh loop when file not found (owncloud 9.0.1)

### ISSUE THREAD

**Issue by sahsanu** [owncloud/core#23888] opened 2016-04-10 00:30 UTC
### Steps to reproduce
1. Share a folder/file
2. Copy the link created by owncloud
3. Remove the share
4. Try to access that removed link `https://yoursite/s/whatever `

Indeed there is no need to create anything, just try to access url `https://yoursite/s/xyz` or `https://yoursite/index.php/s/xyz`

### Expected behaviour
A quiet page saying that the requested file is not found.

### Actual behaviour
You get the page saying that the requested file is not there but the page starts to refresh in a loop, once and again and again and...

### Server configuration
**Operating system**:
Debian 8.2 64 bits
**Web server:**
Apache 2.4.10
**Database:**
mysql 5.5.44
**PHP version:**
php 5.6.19
**ownCloud version:**
9.0.1.3

**Updated from an older ownCloud or fresh install:**
1. Tested after upgrade from 8.2.3 to 9.0.0 and 9.0.1.
2. Fresh install 

**Where did you install ownCloud from:**
1. When upgrading I used the owncloud official debian repo.
2. When fresh install I used the tarball version, downloaded from official page.

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ochacvj7jk6e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.222"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.222\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
No.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Firefox 45, Chrome 49.0.2623.112 m and IE 11
**Operating system:**
Windows 7 SP1 64bits

#### Web server error log
Apache error log shows nothing.

Apache access log shows the refresh loop, I left the file here:
https://gist.github.com/sahsanu/bca948ff85346da78963c1058ab44524#file-gistfile1-txt

#### ownCloud log (data/owncloud.log)
There is nothing.

**Comment by oparoz** [comment] 2016-04-10 00:59
It's a duplicate of an existing report, but while you're there, do you still experience the issue when you disable Gallery?

**Comment by sahsanu** [comment] 2016-04-10 01:31
Hello @oparoz,

Sorry, I've found a similar issue but it was related to a share that was requesting once and again the password but not the same issue.

Anyway, disabling the gallery resolves this issue, once disabled no more refresh loops ;).

Thank you.

**Closed** 2016-04-11 05:52 UTC
