### ISSUE TITLE
Admin page reload every second when Owncloud thinks it's running without HTTPS

### ISSUE THREAD

**Issue by SudoHenk** [owncloud/core#24293] opened 2016-04-26 17:34 UTC
### Steps to reproduce
1. Use Owncloud without SSL and go the admin page.
2. Or use a reverse proxy without proper headers.

### Actual behaviour
Admin page keeps reloading every second. Same as reported in https://github.com/owncloud/core/issues/22977 

### Server configuration
**Operating system**:
Newest Docker image with Nginx as reverse proxy.

**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
Just Updated

I don't know if this issue is the same as previous mentioned issues, but I've figured out that the refresh in 9.0.1 explicitly is caused by the Security Notice on the admin page about missing HTTPS usage. 

Once i've set the correct headers in my reverse proxy (since I was using HTTPS), the problem went away.

This is what i've added in Nginx:
```
proxy_set_header  X-Forwarded-Proto https;
proxy_set_header  X-Forwarded-Ssl   on;
```

**Comment by PVince81** [comment] 2016-05-02 09:05
Likely an env issue, moving to 9.0.3 as it would still be good to find out what is going on

CC @cmonteroluque

**Comment by PVince81** [comment] 2016-06-02 17:17
Closing as duplicate of https://github.com/owncloud/core/issues/24309

**Closed by PVince81** 2016-06-02 17:17 UTC
Labels: bug
