### ISSUE TITLE
Update 6.0.4 -> 7.0.1 fails at LDAP mapping tables

### ISSUE THREAD

**Issue by fdrtom** [owncloud/core#10798] opened 2014-09-01 11:45 UTC
### Steps to reproduce
1. install oc 6 
2. set up ldap mapping
3. (optional) delete ldap config in admin web interface
4. start update

### Expected behaviour
ownCloud web updater should alter all tables and import its contents

### Actual behaviour
The updater terminates unsuccessfully with the error

```
An exception occurred while executing 'ALTER TABLE `oc_oc_ldap_user_mapping_26dc95731c3b7` DROP PRIMARY KEY': SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column/key exists
```

Of course, that table does not exist. Dropping the LDAP config before the update makes no difference. If I reload and restart the update, the hex string at the end will change, yet I cannot find it in my tables.

### Server configuration
**Operating system**:
Debian jessie

**Web server:**
apache 2.4

**Database:**
MySQL 5.5

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
6.0.4

**Updated from an older ownCloud or fresh install:**
update

**List of activated apps:**
calendar, files, contacts, documents, ldap and some viewers

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocXXXXX',
  'trusted_domains' => 
  array (
    0 => 'XXXX',
  ),
  'datadirectory' => '/srv/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.4.1',
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXX',
  'installed' => true,
  'forcessl' => false,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'theme' => '',
  'maintenance' => false,
);
```
(after failed backup)

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

#### Web server error log
```
<empty>
```

#### ownCloud log (data/owncloud.log)
```
{"app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'ALTER TABLE `oc_oc_ldap_user_mapping_26dc95731c3b7` DROP PRIMARY KEY':\n\nSQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'PRIMARY'; check that column\/key exists' in \/usr\/share\/owncloud\/lib\/private\/db\/migrator.php:117\nStack trace:\n#0 \/usr\/share\/owncloud\/lib\/private\/db\/migrator.php(75): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/usr\/share\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(111): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/usr\/share\/owncloud\/lib\/private\/db.php(337): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/usr\/share\/ownc...')\n#3 \/usr\/share\/owncloud\/lib\/private\/updater.php(195): OC_DB::simulateUpdateDbFromStructure('\/usr\/share\/ownc...')\n#4 \/usr\/share\/owncloud\/lib\/private\/updater.php(137): OC\\Updater->doUpgrade('7.0.1.1', '6.0.4.1')\n#5 \/usr\/share\/owncloud\/core\/ajax\/update.php(35): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2014-09-01T11:33:20+00:00"}
```

**Comment by DeepDiver1975** [comment] 2015-01-07 12:41
duplicate of #9893 -> closing

**Closed by DeepDiver1975** 2015-01-07 12:41 UTC
Labels: app:user_ldap, bug, sev2-high, Update

**Comment by silk** [comment] 2015-03-16 13:08
I had the same error, when trying to update from 6.0.4.1 from owncloud packages to 7.0.4+dfsg-2 from debian repository. 
I switched and used https://download.owncloud.org/community/owncloud-7.0.5.tar.bz2 - now the update finished without problems.
