### ISSUE TITLE
Select the default app for each user in a large, corporate environment

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#18828] opened 2015-09-04 09:03 UTC
Hi,
Especially in large and very large organizations it might be a user friendly option, that every user can select its own default app after opening OC! In this cases, ordinary users do not have and should not have access to config.php, where admin cat set global options!

However, users might have preferences if they want to have the calendar, or News or contact app in front of her eyes, after login into OwnmCloud!

I suggest this menu item should be available in the User section of the administration app, to be accessible by each user him- or herself!

Have a nice & successful day!

regards, hitam4450

**Comment by menedas** [comment] 2015-09-10 07:59
I need that feature too :+1:

**Comment by Xenopathic** [comment] 2015-09-10 08:26
Duplicate of #8160

**Closed by Xenopathic** 2015-09-10 08:26 UTC
Labels: enhancement

**Comment by Xenopathic** [comment] 2015-09-10 08:27
@hitam4450 This is your second duplicate issue with a nearly identical title and text, please see the linked duplicate issue and comment there.
