### ISSUE TITLE
Allow the use of email address for password recovery

### ISSUE THREAD

**Issue by mdigit5** [owncloud/core#27111] opened 2017-02-08 13:05 UTC
### Steps to reproduce
1. Create a new account and assign an email address
2. Go to the login form and use the email address to initiate a password recovery (enter a wrong password and click "Wrong password. Reset it?" link

### Expected behaviour
If the correct email address is specified the password reset should be accepted.

### Actual behaviour
The login UI complains that the username is invalid (i.e. it expects a username, not an email address)

### Why email address should be permitted for password reset/recovery
An important use case is the initial login. If you're moving forward with email based login for user convenience, it's likely that the first automatic email to the end user when the account is created will say something like:

"You now have an account, go ahead and log in with your email address and do a password recovery"

This is an easy way to get around the initial password issue.

The problem is that you can't say that. It gets more complicated. You would need to say something like:

"You now have an account. Here is your username. You don't really need the username because you can log in with your email address, but you'll need to use it to do your password recovery, but once you've done that you can just log in with your email address. But, if you ever need to do a password recovery again you'll need to use your username again, so don't forget it."

Yes, I'm being a bit silly with that last paragraph. The point is that if logging in with email address is supported, resetting/recovering your password with email address should also be supported.

I'm not sure if this is bug, or just a feature that was never implemented.

### Server configuration
**Operating system**: Ubuntu 14.04.5 LTS

**Web server:** Apache 2.4.25

**Database:** MySQL

**PHP version:** 5.6.29

**ownCloud version:** 9.1.3 (stable)

**Updated from an older ownCloud or fresh install:** No

**Comment by PVince81** [comment] 2017-02-10 11:10
Makes sense.

@mdigit5 are you versed in PHP and could submit a PR for this ?

**Comment by mdigit5** [comment] 2017-02-10 13:08
@PVince81 

Thanks for the quick reply.

Unfortunately not. I wish I was versed in PHP because I really like ownCloud and would be glad to help.

**Comment by imujjwal96** [comment] 2017-02-11 20:07
@PVince81 Since the email address is not unique for a single user, I don't think it would be wise to implement it. 
Also for that matter, if two users have the same email addresses, logging in via email shows invalid password.

**Comment by mdigit5** [comment] 2017-02-11 20:29
Didn't realize email address wasn't unique! This is probably why password reset by email address wasn't implemented in the first place.

It begs the question, should email address be unique? I realize that opens up a can of worms.

In any case, thanks for the quick investigation.

**Comment by PVince81** [comment] 2017-02-13 06:25
It might still be possible to do, but internally the code needs to check if the email address is unique and only send the password reset link if it is. Else it doesn't. (the response message must still be the same as before to avoid telling the user about such internals)

**Comment by imujjwal96** [comment] 2017-02-13 07:42
Ok. I can try to implement it.

One more thing. If two users have the same email address, logging in via email shows invalid password. Can anything be done with it or that is how it will be?

**Comment by PVince81** [comment] 2017-02-13 08:07
> If two users have the same email address, logging in via email shows invalid password

This is by design.

For security reasons the visible error message must always be the same regardless of the error to avoid people guessing user names or email addresses.

**Comment by radhefa** [comment] 2017-02-13 19:35
radhefa@localehost

**Comment by nervehammer** [comment] 2017-02-21 16:21
Is the PR to this issue still being reviewed. If not, then I'll like to resolve it.

**Comment by PVince81** [comment] 2017-02-23 08:22
@nervehammer seems the PR is almost there

**Comment by noveens** [comment] 2017-02-27 11:16
@PVince81 ,
Close this?

**Closed** 2017-02-27 11:22 UTC
Labels: enhancement, junior job
