### ISSUE TITLE
Cannot move received federated share mount

### ISSUE THREAD

**Issue by piflixe** [owncloud/core#27072] opened 2017-02-01 17:53 UTC
Sorry if this is explained somewhere else, but I couldn't find any information on that.

When signing up to a federated share location via a share link, I would like to add it not in the root folder of my owncloud, but in a custom location somewhere in my folder tree. 

### Steps to reproduce
1. Create share link 
2. add remote share to your owncloud
3. federated share is in the root folder of your owncloud and can't be moved

### Expected behaviour
When adding a federated share to your owncloud, it would be nice to be able to choose a location as a "mounting point"

It would be nice if the federeted share folder could be moved via drag and drop, just like normal folders

### Actual behaviour
location of federated share is / by default

federated share folder cannot be moved

### Server configuration
**Operating system**: ubuntu 14.04 server

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** mysql 5.5.53-0ubuntu0.14.04.1

**PHP version:** PHP 5.5.9-1ubuntu4.20

**ownCloud version:** 9.1.3

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** download repository from website via wget

**Signing status (ownCloud 9.0 and above):** yes

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
  - activity: 2.3.2
  - bookmarks: true
  - calendar: true
  - comments: 0.3.0
  - contacts: true
  - dav: 0.2.7
  - documents: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: true
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external
  - user_ldap


**The content of config/config.php:**

{
    "system": {
        "instanceid": "oce7mgbju8mb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.11.35",
            "konstruktiv.selfhost.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.11.35\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "OC",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "konstruktiv-berlin.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "server20.webgo24.de",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "share_folder": "\/",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
N/A

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:** firefox 50.1

**Operating system:**
win 10

**Comment by PVince81** [comment] 2017-02-02 19:01
> can't be moved

That's not correct. You can rename and move received shares anywhere you want after having accepted it.

What happens if you move it ? Do you get an error message ? If yes then it's a bug.

**Comment by piflixe** [comment] 2017-02-04 11:53
HI PVince81! 

Thanks for your reply. When trying to drag and drop the federated share folder in the web frontend, I receive the error message "Datei konnte nicht verschoben werden "<folder name>"" - I guess that would be translated to "folder can't be moved". I tried drag and drop of folders with folders I created myself and this works fine. 

In older Versions, I had the extension "Files move" installed but I guess that is obsolete now since it is supported by the owncloud core?

Do you have any suggestions on how to debug that?

I have a self hosted environment behind a normal DSL line using portforwarding from a custom port and a self-signed SSL certificate. Do you think this could cause the error?

**Comment by PVince81** [comment] 2017-02-06 06:50
Hmm, is the mounted federated share read-only ? Maybe there's a permission mix-up.

Does it work moving it if you mount a read-write federated share ?

Did you disable files_move when trying ?

Potentially a bug.

**Comment by PVince81** [comment] 2017-02-06 13:18
I can't reproduce this issue with two 9.1.3.

My steps:

1. Setup two OC instances OC_A and OC_B with version 9.1.3
1. Login as admin on OC_B
1. Create two folders "testrw" and "testro"
1. Create link shares for "testrw" (read-write) and "testro" (read-only)
1. Login as admin on OC_A
1. Open both links
1. Add them to OC_A
1. Create a folder "sub"
1. Move both received "testrw" and "testro" to "sub"

This works fine.

**Comment by PVince81** [comment] 2017-04-06 11:48
Cannot reproduce.
Also see https://github.com/owncloud/core/issues/27072#issuecomment-277598881

Closing due to lack of feedback

**Closed by PVince81** 2017-04-06 11:48 UTC
Labels: bug, feature:federated-cloud-sharing, needs info
