### ISSUE TITLE
The update was unsuccessful.

### ISSUE THREAD

**Issue by MLWALK3R** [owncloud/core#14037] opened 2015-02-10 10:29 UTC
### Steps to reproduce
1. Run web UI updater
2.
3.

### Expected behaviour
An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_4onwr4y3vyn2q RENAME INDEX appconfig_config_key_index TO oc_dhrhry3r27gv6': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_dhrhry3r27gv6' at line 1

### Server configuration
**Operating system**: Ubuntu 14.10

**Web server:** nginx-full_1.6.2-5+utopic0_amd64

**Database:** mysql  Ver 15.1 Distrib 10.1.2-MariaDB

**PHP version:**  PHP 5.5.9-1ubuntu4.5 

**ownCloud version:**    'version' => '7.0.4.2'

**Updated from an older ownCloud or fresh install:** Old to new

**List of activated apps:** IDK

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocba331e4d4e',
  'passwordsalt' => '0000',
  'trusted_domains' =>
  array (
    0 => 'domain.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://domain.com',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud1db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud1',
  'dbpassword' => 'lepassword',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'smtp.sendgrid.net',
  'mail_domain' => 'domain.com',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.sendgrid.net',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'username',
  'mail_smtppassword' => 'lepassword',
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'secret' => '00013337',
  'ldapIgnoreNamingRules' => false,
  'user_webdavauth_url' => 'https://domain.com',
);

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
**Are you using encryption:** yes

#### ownCloud log (data/owncloud.log)
```
https://p.ftwnet.co.uk/1423563987
```

**Comment by PVince81** [comment] 2015-02-10 10:39
Duplicate of https://github.com/owncloud/core/issues/14003

**Closed by PVince81** 2015-02-10 10:39 UTC
