### ISSUE TITLE
Resharing is not allowed

### ISSUE THREAD

**Issue by davidericardo** [owncloud/core#26892] opened 2017-01-02 10:13 UTC
Sharing options enabled
- Allow apps to use the Share API
- Allow users to share via link
- Allow resharing
- Allow sharing with groups
- Restrict users to only share with users in their groups
- Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.

Federated Cloud Sharing options enabled
- Allow users on this server to send shares to other servers

### Steps to reproduce
1. User A creates an folder and share it with other user
2. User B tries to share the same folder to user C
3. User B receives the following result: "Resharing is not allowed"

### Expected behaviour
The user B should be able to share the same folder or file with the user C

### Actual behaviour
Resharing is not allowed

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
9.1.3 (the same issue happens on 8.1.x - that's why I tried to update to the latest version

**Updated from an older ownCloud or fresh install:**
updated from 8.1.x -> 8.2 -> 9.0.6 versions

**Where did you install ownCloud from:**
Downloaded the package installation from the owncloud official page

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => ab5f4c44ba2f9c66f2ed25c3ad3d84660b2808cca11ffa8fe2778a648a054d8ada495a0bf4715dc873aac1efe8dfd92a72f9a24441d8f5240834e639325fd892
                            [current] => 
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => 
                        )

                )

        )

)

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

Disabled:
  - calendar
  - documents
  - encryption
  - external
  - federation
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocvno22jln7b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxx.com"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/xxxxxx.com",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "clouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "mail_from_address": "yyyyyy",
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxxxx.com",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "theme": "load"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2115"
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "core": {
            "": "de",
            "incoming_server2server_share_enabled": "no",
            "installedat": "1461063452.1971",
            "lastcron": "1483351326",
            "lastupdateResult": "[]",
            "lastupdatedat": "1483307644",
            "oc.integritycheck.checker": "{\"core\":{\"FILE_MISSING\":{\".htaccess\":{\"expected\":\"ab5f4c44ba2f9c66f2ed25c3ad3d84660b2808cca11ffa8fe2778a648a054d8ada495a0bf4715dc873aac1efe8dfd92a72f9a24441d8f5240834e639325fd892\",\"current\":\"\"},\".user.ini\":{\"expected\":\"0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f\",\"current\":\"\"}}}}",
            "outgoing_server2server_share_enabled": "yes",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_group_sharing": "yes",
            "shareapi_allow_links": "yes",
            "shareapi_allow_mail_notification": "no",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "yes",
            "shareapi_default_expire_date": "no",
            "shareapi_enabled": "yes",
            "shareapi_enforce_links_password": "no",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"dev\",\"design\"]",
            "shareapi_only_share_with_group_members": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.7",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_path": "\/usr\/bin\/clamscan",
            "enabled": "yes",
            "installed_version": "0.9.0.0",
            "ocsid": "157439",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "0.10.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "14.4.0",
            "ocsid": "169116",
            "signed": "true",
            "types": ""
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "169914",
            "signed": "true",
            "types": ""
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ojsxc": {
            "enabled": "no",
            "installed_version": "3.0.1",
            "ocsid": "162257",
            "types": "prelogin"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.08",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "user_external": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "user_ldap": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "types": "authentication"
        },
        "user_webdavauth": {
            "enabled": "no",
            "installed_version": "",
            "types": "authentication"
        }
    }
}

Insert your config.php content here
$CONFIG = array (
  'instanceid' => 'ocvno22jln7b',
  'passwordsalt' => 'xxxxxxxx',
  'secret' => 'xxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'cloud.xxxxxxxx.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.xxxxxxxx.com',
  'dbtype' => 'mysql',
  'version' => '9.1.3.1',
  'dbname' => 'xxxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxx',
  'dbpassword' => 'xxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'mail_from_address' => 'yyyyyyy',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxxxxxxx.com',
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'theme' => 'load',
);

**Are you using encryption:** no

[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ldap" namespace.

### Client configuration
**Browser:**
Chrome, Safari

**Operating system:**
Windows, Mac

**Comment by PVince81** [comment] 2017-01-10 17:42
Works for me on a local test.

Does it work with newly created "test" folder ? Is that test folder an old one that went through the upgrades ? I'm asking because it could be a permission issue in the oc_filecache table.

**Comment by hodyroff** [comment] 2017-02-20 12:50
Closing as reproduction was not successful and further info not provided.

**Closed by hodyroff** 2017-02-20 12:50 UTC
Labels: bug, feature:sharing, needs info
