### ISSUE TITLE
Sharing only works if the option "Allow users to share via link" is active

### ISSUE THREAD

**Issue by rolandbu** [owncloud/core#21126] opened 2015-12-10 16:02 UTC
Hi

*Debian 8
*Owncloud 8.1.3 update to 8.2.1
*LDAP user settings activ

Everything worked fine under 8.1.3 but after the upgrade to 8.2.1 the sharing isn't possible. 

If I actived the option "Allow users to share via link" the sharing dialog with the LDAP-user autocompletion works very well. Without this option, I can search after user at the sharing dialog without any anser. In the logs, I can see all the correct ldap querys and results.

Any ideas about this problem?

**Comment by RealRancor** [comment] 2015-12-10 17:08
@rolandbu Duplicate of https://github.com/owncloud/core/issues/20642 which gets fixed with the upcoming 8.2.2

**Closed** 2015-12-10 17:09 UTC
