### ISSUE TITLE
Another SQL error while upgrade

### ISSUE THREAD

**Issue by nbkgroup** [owncloud/core#14064] opened 2015-02-10 17:57 UTC
Database upgrade failed with message

An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_7fy7nhok7kyzu RENAME INDEX appconfig_config_key_index TO oc_lebiruh2u496z': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_lebiruh2u496z' at line 1

Owncloud installed on Debian Wheezy/nginx/mariadb 10, updated from http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/

**Comment by RealRancor** [comment] 2015-02-10 18:11
Hi,

this is an duplicate of: https://github.com/owncloud/core/issues/14003 and some others.

**Comment by nbkgroup** [comment] 2015-02-10 18:17
Thanks for the hint

**Comment by RealRancor** [comment] 2015-02-10 18:57
@nbkgroup 
Feel free to close this. I don't have the permissions.

**Closed** 2015-02-10 19:00 UTC
