### ISSUE TITLE
rescan external storage not triggered

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#11764] opened 2014-10-24 15:02 UTC
### Steps to reproduce
1. Setup a external storage, here s3
2. add file in owncloud to s3
3. delete this file in s3

### Expected behaviour
owncloud should not show the deleted file.

### Actual behaviour
owncloud doesn't deletes the file, and file is shown in the owncloud web interface and can't be openend (error) because is removed in the backend.
Even if in the config file is  'filesystem_check_changes' => 2,

### Server configuration
**Operating system**:
linux
**Web server:**
apache
**ownCloud version:** (see ownCloud admin page)
7.0.2

**Updated from an older ownCloud or fresh install:**
fresh install

#### ownCloud log (data/owncloud.log)
```
tbd.
```

**Comment by PVince81** [comment] 2015-01-20 12:29
Possibly related: https://github.com/owncloud/core/issues/11797

**Comment by PVince81** [comment] 2015-08-03 13:11
Closing as duplicate of https://github.com/owncloud/core/issues/13507

**Closed by PVince81** 2015-08-03 13:11 UTC
Labels: triage
