### ISSUE TITLE
Issues with logging in and encryption

### ISSUE THREAD

**Issue by thystra** [owncloud/core#12316] opened 2014-11-20 04:43 UTC
I upgraded to 7.0.3 and had no issues. Then I decided to enable encryption. That seemed to work. However, the page asked me to log out and back in, as expected. 

Upon logging back in, the page errored out with the following message:

Fatal error: Call to a member function getUID() on a non-object in /home/path/to/owncloud/lib/private/user.php on line 241

There is a message on the owncloud login page that 'Initial encryption is running, please try again later, then goes to the Fatal Error message.  I've left it 'running' for a day now, and still no change. Open to suggestions. There is about 4.5 GB of data in the cloud, and a couple files I've checked so far are still unencrypted on the server.

**Comment by PVince81** [comment] 2015-01-13 15:25
Closing as duplicate of https://github.com/owncloud/core/issues/12412

**Closed by PVince81** 2015-01-13 15:25 UTC
Labels: app:files_encryption, bug
