### ISSUE TITLE
Give user choice to encrypt their files or not

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#25475] opened 2016-07-14 03:38 UTC
Hi OC team,

Because once I enable encryption module, it will cause extra time after uploading file especially large files.
I'm wondering if owncloud support such feature?
If there is a checkbox that allow user to choose encryption on files in their setting page.
Or if there is a checkbox in file detail page

Thanks!

**Comment by PVince81** [comment] 2016-07-14 07:23
Due to sharing it is quite complex to provide a mix of encrypted and unencrypted files in the same environment, considering that encryption was designed to be either the full system or nothing at all.

Tagging as enhancement.

**Comment by PVince81** [comment] 2016-07-14 07:23
@owncloud/encryption

**Comment by RealRancor** [comment] 2016-07-14 08:46
@PVince81 Duplicate of https://github.com/owncloud/core/issues/24982 ?

**Comment by jknockaert** [comment] 2016-07-14 08:49
Honestly, I don't really see the use case. The encryption wrapper is now fully transparent. There's no file-size related penalty All encryption (and decryption) should be hardware accelerated on most common platforms, so its performance impact should be absolutely minimal.

**Comment by DeepDiver1975** [comment] 2016-07-14 11:35
> @PVince81 Duplicate of #24982 ?

yes!

@RealRancor thanks for noticing!

**Closed by DeepDiver1975** 2016-07-14 11:35 UTC
Labels: app:encryption, enhancement
