### ISSUE TITLE
Lost all my files when I updated owncloud 7.0.4 to 8.0 

### ISSUE THREAD

**Issue by SRWieZ** [owncloud/core#14011] opened 2015-02-09 22:12 UTC
I updated my owncloud on debian 7.8 with APT and finished the update with occ upgrade. 

When I logged in my account, there was only defaults files of ownloud.

```./occ files:scan -all```

fail with 
```
Scanning file   /MyUser/
Scanning folder /MyUser/
Scanning file   /MyUser/files
Scanning file   /MyUser/cache
Scanning folder /MyUser/files
Scanning file   /MyUser/files/ownCloudUserManual.pdf
Scanning file   /MyUser/files/Photos
Scanning file   /MyUser/files/Documents
Scanning folder /MyUser/files/Photos
Scanning file   /MyUser/files/Photos/Paris.jpg
Scanning file   /MyUser/files/Photos/Squirrel.jpg
Scanning file   /MyUser/files/Photos/San Francisco.jpg
Scanning folder /MyUser/files/Documents
Scanning file   /MyUser/files/Documents/Example.odt
Scanning folder /MyUser/cache

[OCA\Files_Encryption\Exception\EncryptionException]
  Could not determine user

files:scan [-p|--path="..."] [-q|--quiet] [--all] [user_id1] ... [user_idN]
```
after cache directory of the first user.

**Comment by DeepDiver1975** [comment] 2015-02-09 22:15
Where are you users coming from? LDAP?

@blizzz @PVince81 UID magic?? :speak_no_evil:

**Comment by SRWieZ** [comment] 2015-02-09 22:18
Not external users, only local.

**Comment by DeepDiver1975** [comment] 2015-02-09 22:21
What does your data folder looks like?

**Comment by SRWieZ** [comment] 2015-02-09 22:27
root@myserv:~# ls /var/www/owncloud/data/MyUser/files/ -all
drwxr-xr-x 4 www-data www-data    4096 Feb  9 21:55 .
drwxr-xr-x 4 www-data www-data    4096 Feb  9 21:55 ..
drwxr-xr-x 2 www-data www-data    4096 Feb  9 21:55 Documents
-rw-r--r-- 1 www-data www-data 1771241 Feb  9 21:55 ownCloudUserManual.pdf
drwxr-xr-x 2 www-data www-data    4096 Feb  9 21:55 Photos
root@myserv:~# 

Notice that I tried to unload/load encryption plugin but nothing changes.

**Comment by schiesbn** [comment] 2015-02-09 23:11
The encryption exception gets thrown if we try to determine the user from the path in case no user is logged in. In regular cases this happens if you access public shared files. I need to have a look at "./occ files:scan -all" but I assume that it also runs with no user logged in but works on paths relative to "data/user/files". This would explain why we can't read the user from the path. But what I don't understand why scanning the file system should trigger reading/writing files?

**Comment by PVince81** [comment] 2015-08-03 12:59
@schiesbn any update ? "Could not determine user", did we find this in a separate issue too ?

**Comment by MorrisJobke** [comment] 2016-01-06 07:33
Duplicate of #16310

**Closed by MorrisJobke** 2016-01-06 07:33 UTC
Labels: app:files_encryption, feature:update
