### ISSUE TITLE
Broken row highlight after renaming a file/folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19722] opened 2015-10-12 21:19 UTC
### Env 

Firefox 41
Windows

### Steps to reproduce

1. Click the 3 dots on any row, preferably a folder row
2. Find "Rename" and click on it
3. Don't move the mouse
4. Type in something
5. Hit "Enter"

*Note: you can move the mouse, just make sure it's not on the same row*

### Expected result

A renamed element and a grey row

### Actual result

A renamed element and grey areas behind text elements of that row.
If you roll over, then most of the grey comes back, but it's uneven.

![css](https://cloud.githubusercontent.com/assets/323220/10463961/b58849a6-71e7-11e5-83f6-e4cfe45f4932.png)

----
@jancborchardt @PVince81

**Comment by PVince81** [comment] 2015-10-13 08:27
Works for me. Uneven highlight reminds me of the layout glitch that @LukasReschke mentionned in https://github.com/owncloud/core/issues/19698

Here are my steps:

1. Create four files "abc.txt", "def.txt", "ghi.txt", "jkl.txt"
1. Refresh the page and make sure nothing is highlighted
1. On the row for "def.txt", click the three dots
1. Move to "Rename", click it, then leave the mouse where it is
1. Rename the file to "def2.txt" then hit enter. This will leave it inside the current position.
1. Move the mouse and check highlight.

In my case the hover and highlight still look correct. This is with Chromium 45 and Firefox 41 on master (1cb4f1080a57bfffe5d71d7496b61184434ff84d) after clearing the cache + cookies.

The symptoms almost sounds like older IE hover CSS glitches.

Can you provide more detailed steps ? How are your files called and what names did you give them ? Note that when renaming a file it might get re-sorted into the list and might move to a different location.
Also, did you use the checkboxes before renaming ? Can you post a screenshot ?

**Comment by PVince81** [comment] 2015-10-13 08:31
Now I wonder if it's caused by enabled apps, I don't have any apps enabled, just core's git.

**Comment by oparoz** [comment] 2015-10-13 09:51
![css](https://cloud.githubusercontent.com/assets/323220/10451455/a883330c-71a0-11e5-9948-f1ac045211cd.png)

And after disabling all apps it's gone... So investigating further...

**Comment by oparoz** [comment] 2015-10-13 09:53
And the winner is... Gallery!

**Comment by oparoz** [comment] 2015-10-13 10:01
Nope, spoke too soon. Poor Gallery. It happens with all apps disabled.

**Comment by oparoz** [comment] 2015-10-13 10:05
Must have something to do with the anchor CSS. All goes back to normal if the tooltip is triggered

**Comment by oparoz** [comment] 2015-10-13 10:15
OK, so for me it's easily reproducible when using folders. Just have a bunch of them and follow the steps in the OP. It seems to be harder to to get it to fail with files. Maybe because the filenames are longer.

**Comment by PVince81** [comment] 2015-10-13 10:22
Can you evaluate the grey elements, do they have the "highlighted" class ?
If yes it could be a sign that somewhere in the row updating code either the wrong selector is used or the assumption about the jquery element is wrong ("tr" element vs children elements)

**Comment by oparoz** [comment] 2015-10-13 10:36
![tr-909](https://cloud.githubusercontent.com/assets/323220/10452701/e73821b0-71a6-11e5-9aab-c13fa7eebbaa.png)

> do they have the "highlighted" class ?

No, but all the painting glitches make me think that it's a compositing but which could come from the browser itself or perhaps a missing CSS extension.

**Comment by oparoz** [comment] 2015-10-13 10:43
I think I've found the problem

**Comment by oparoz** [comment] 2015-10-13 10:49
Nope... I did find some conflicting CSS, but that didn't help when making the change.
![css conflict](https://cloud.githubusercontent.com/assets/323220/10452945/c6942736-71a8-11e5-8e07-459b59251ba3.png)

Things break when the busy class is removed.

**Comment by PVince81** [comment] 2016-02-10 15:37
@oparoz are you still seeing this in the latest master and the most recent Firefox ?

**Comment by oparoz** [comment] 2016-02-12 14:30
Yep, still happening. Firefox 44

**Comment by nickvergessen** [comment] 2016-06-07 10:13
Can't reproduce with FF46 and current master. Maybe it was fixed with sidebar stuff or the "drag n drop" highlight thing.

**Closed by nickvergessen** 2016-06-07 10:13 UTC
Labels: bug, design, regression, sev3-medium
