### ISSUE TITLE
Thumbnails not generated if folder name contains parenthesis or apostrophes

### ISSUE THREAD

**Issue by philfry** [owncloud/core#14180] opened 2015-02-12 21:47 UTC
### Steps to reproduce
1. place a jpg in /foo/bar/abc/baz/image.jpg
2. place a jpg in /foo/bar/abc (def)/baz/image.jpg
3. place a jpg in /foo/bar/abc (def (ghi)/baz/image.jpg
4. place a jpg in /foo/bar/abc's baz/image.jpg
5. open folders in file view, take a look at the thumbnails

### Expected behaviour
All four jpgs should show a thumbnail

### Actual behaviour
Only the jpgs from steps 1 and 2 have thumbnails

### Server configuration
**Operating system**: Linux RHEL 6.5 x86_64

**Web server:** Apache httpd 2.2.29

**Database:** mysql

**PHP version:** 5.4.16

**ownCloud version:** 8.0.0.7

**Updated from an older ownCloud or fresh install:** updated from 7.0.4

**List of activated apps:** bookmarks, calendar, contacts, deleted files, external storage support, file locking, ldap user and group backend, pdf viewer, pictures, share files, text editor, versions

**The content of config/config.php:**

```
  'datadirectory' => '/var/lib/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '1',
  'log_authfailip' => true,
  'maintenance' => false,
  'theme' => '',
  'forcessl' => true,
  'filesystem_check_changes' => 0,
  'trusted_domains' => 
  array (
  ),
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
```

**Are you using external storage, if yes which one:** webdav

**Are you using encryption:** no

### Client configuration
**Browser:** firefox 35.0.1

**Operating system:** fedora 21

**Comment by LukasReschke** [comment] 2015-02-12 21:49
Duplicate of https://github.com/owncloud/core/issues/14149

**Closed by LukasReschke** 2015-02-12 21:49 UTC
