### ISSUE TITLE
List of users, Listbox group column does not open

### ISSUE THREAD

**Issue by jgrete** [owncloud/core#20503] opened 2015-11-13 21:24 UTC
As admin opening the user management I'm getting a list of users with a column showing which groups the user is member of and in which he/she is groupadmin. 
In both columns often it is impossible to open the listbox if it has more than 2 or 3 entries.
Sometimes the listbox opens on a complete different location (much too high or too low), mostly
the listbox does not open at all.
Browser: Firefox 42
Owncloud 8.2
Apache 2.4
PHP 5.6

**Comment by PVince81** [comment] 2015-11-16 10:57
Can you post a screenshot ?

CC @blizzz

**Comment by jgrete** [comment] 2015-11-16 11:51
On the screenshot you see the red circle araound the listbox and the blue one around the listbox button I hit. I've got that behaviour on both Windows 8 and Linux Kubuntu (15.04)
Regards
Jürgen

![2015_11_16_12_38_45_error](https://cloud.githubusercontent.com/assets/14105933/11181170/7353536c-8c60-11e5-9491-8a08abccfaa4.png)

**Comment by PVince81** [comment] 2015-11-16 12:27
Hmm that looks strange.
When you say "impossible to open", do you mean that when you click on the row, nothing happens ?
Maybe something is wrong with the position calculation.

I see you seem to be using themes, are you sure the CSS from the theme isn't influencing the layout of this page ? I suspect that there might be some theme CSS that changes properties like "position: xxx" or so which would affect the calculation of the dropdown position.

Is there any error in the Javascript console ?

**Comment by jgrete** [comment] 2015-11-17 07:41
I meant, if there are already 2 or three entries shown on the listbox button, nothing happens when I'm clicking on it. But thinking about it now it could also be a side effect and the shown list just was far away and not within the viewable part of the screen.
At the moment I'm not able to look into the CSS code, but I'm pretty sure that I changed only some colors, gradients and the icons on the login screen.
When I'm back home I'll change the them to default to see if the effect disappears.
I'll drop you a note accordingly

Regards
Juergen

**Comment by jgrete** [comment] 2015-11-17 19:31
I checked that the problem does not depend on the theme used.
Furthermore I've seenthat the problem only exists on the second, third, fourth ... pages. 
On the first page the list on a proper position below or above the Button. 
Maybe there's a problem with the pagination?

Regards 
Juergen

**Comment by PVince81** [comment] 2015-11-18 09:34
You're right, I was able to reproduce it.
Have at least 3 pages of users and then open the dropdown for the users in the 2nd or 3rd page:

![dropdown-calculation](https://cloud.githubusercontent.com/assets/277525/11237394/ee9a69f4-8ddf-11e5-9352-b2745ce12be4.png)

Looks like the dropdown position calculation doesn't take scrolling into account.

**Comment by jgrete** [comment] 2015-11-18 10:03
Ok, thanks. 
I assume there will be no patch for 8.2? 
Would be nice 😊... 

Regards
Juergen

**Comment by PVince81** [comment] 2015-11-18 10:08
Not sure yet.

There is work in progress to replace the dropdown with a new one (different library) here: https://github.com/owncloud/core/pull/16902 for 9.0.

**Comment by MorrisJobke** [comment] 2016-01-07 12:11
Just as a side note: We should backport a fix for this to stable8.2 - with this it's not possible to remove group membership of a user. 

@blizzz You also looked into this topic - any ideas, why this happens?

**Comment by PVince81** [comment] 2016-01-07 13:35
This will need a 8.2 specific fix. I can have a look to see why the dropdown position calculation doesn't take scrolling into account.

**Comment by PVince81** [comment] 2016-01-07 13:41
>  with this it's not possible to remove group membership of a user. 

It is, but it's cumbersome:  use the search field to avoid any scrolling. The dropdown should appear as long as you're on the first page.

**Comment by PVince81** [comment] 2016-01-07 14:28
Fix is here https://github.com/owncloud/core/pull/21507, almost one-liner :smile:

**Closed** 2016-01-07 15:18 UTC
Labels: backport-request, bug, in progress, settings:users, sev2-high

**Comment by PVince81** [comment] 2016-01-11 11:54
This works fine on stable8 and stable8.1 but not stable8.2 marking as regression. Possibly due to the recent styling changes.

**Comment by jgrete** [comment] 2016-01-11 18:41
Works on 8.2.2 stable!
Thanks a lot!
Regards
Juergen

**Comment by rroseselavy42** [comment] 2016-01-18 21:20
I'm still seeing the problem in Firefox on 8.2.2

**Comment by blizzz** [comment] 2016-01-19 11:21
@jgrete fix comes with 8.2.3
