### ISSUE TITLE
An index with name 'keyid_index' was already defined on table 'oc_privatedata'

### ISSUE THREAD

**Issue by Pantek59** [owncloud/core#14827] opened 2015-03-12 13:40 UTC
First the update to 8.0 seemed to be OK. I re-enable some apps and, logged out and then had the same problem already mentioned by somebody else here: https://github.com/owncloud/core/issues/14715

### Steps to reproduce
1. Update to OC 8.0
2. Re-enable app documents
3. Log out -> Update screen
4. Click on "Start Update" --> Error Message

### Expected behaviour
Run the update, I guess. :)

### Actual behaviour
The update is aborted with the error message "An index with name 'keyid_index' was already defined on table 'oc_privatedata'"

### Server configuration
**Operating system**: Ubuntu 12.04

**Web server:** Apache 2.4.12

**Database:** MySQL 14.14

**PHP version:** 5.5.22-1+deb.sury.org~precise+1

**ownCloud version:** 8.0

**Updated from an older ownCloud or fresh install:** Update from OC 7.4

**List of activated apps:** 
 - activity
 - appframework
 - bookmarks
 - calendar
 - contacts
 - conversations
 - documents
 - external
 - files
 - files_external
 - files_mv
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - music
 - news
 - ownnote
 - tasks
 - updater

**The content of config/config.php:**
```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => '51c9dc1bd1d61',
  'datadirectory' => '/srv/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'loglevel' => '1',
  'theme' => '',
  'maintenance' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'trusted_domains' => 
  array (
    0 => 'balrog.rudel.locale',
    1 => 'cbm2mh5i6ptruulo.onion',
  ),
  'mail_domain' => 'pantek.org',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'sendmail',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'appcodechecker' => false,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-inline\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
);
```

**Are you using external storage, if yes which one:** local folders

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 36.0.1

**Operating system:** Linux Mint 17

**Comment by sisyphosloughs** [comment] 2015-03-12 14:10
My owncloud got stucked by this issue as well. Does someone know any workarounds?

**Comment by DeepDiver1975** [comment] 2015-03-12 14:14
> Does someone know any workarounds?

Try to remove these lines :+1: https://github.com/owncloud/core/blob/master/db_structure.xml#L1244-L1252

**Comment by Pantek59** [comment] 2015-03-12 14:30
@DeepDiver1975 
I removed the lines you indicated, now the error message is:
"An index with name 'seq_pkey' was already defined on table 'oc_documents_op'."

**Comment by DeepDiver1975** [comment] 2015-03-12 14:33
> "An index with name 'seq_pkey' was already defined on table 'oc_documents_op'."
let me have a look .....

**Comment by DeepDiver1975** [comment] 2015-03-12 14:34
kill these lines - https://github.com/owncloud/documents/blob/master/appinfo/database.xml#L164-L171

**Comment by DeepDiver1975** [comment] 2015-03-12 14:35
@VicDeo might this be caused by ignoring existing indices - remember the BC in doctrine dbal 2.5.1.

I'm curious why this did not happen for us while testing the migration?

**Comment by sisyphosloughs** [comment] 2015-03-12 15:08
@DeepDiver1975: Thanks, it worked. In my case activation of Tasks (https://github.com/owncloud/tasks) was the reason why owncloud got stucket

**Comment by Pantek59** [comment] 2015-03-12 15:19
@DeepDiver1975 Worked here as well, as soon as I removed the lines in database.xml of the documents apps. Thanks!!

**Comment by VicDeo** [comment] 2015-03-16 19:20
@Pantek59 is you MySQL version is  14.14 indeed?

**Comment by Pantek59** [comment] 2015-03-17 10:23
@VicDeo "mysql -- version" returns:
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.2

**Comment by VicDeo** [comment] 2015-03-18 20:09
@Pantek59 this is a mysql client version. Please try `mysqld -V` instead.

**Comment by VicDeo** [comment] 2015-03-18 20:14
@Pantek59 nevermind,  it's probably 5.5.41

**Comment by VicDeo** [comment] 2015-03-19 17:12
@sisyphosloughs  @Pantek59 Did you migrate to mysql from sqlite by any chance?

**Comment by VicDeo** [comment] 2015-03-19 17:20
Sadly I can not reproduce it neither with clean oc8.0.2 install, nor with upgrade from OC7 to OC8 and enabling Documents afterwards.

I even tried bumping Documents version and adding other indexes/fileds to the oc_documents_member table and some other wild ways to force DB changes. Works :(

**Comment by droghio** [comment] 2015-03-20 03:23
Had the same issue trying to update from 8.0.0->8.0.2. Killing those lines worked like a charm (1244-1252). Had a small hangup after that where I got the following error: 

```PHP Fatal error:  Call to undefined method OC\AllConfig::setValue() in /var/www/html/owncloud/lib/private/updater.php on line 232```

I ended up commenting it out and the update seemed to work just fine.
Anyway thanks!

**Comment by Pantek59** [comment] 2015-03-20 09:51
@VicDeo It is 5.5.41 indeed. Sorry, my bad.
And no, I had OC running on mysql right from the start.

**Comment by karlitschek** [comment] 2015-05-06 18:32
So can someone else reproduce this?

**Comment by PVince81** [comment] 2015-05-19 10:30
I'll have a look.

**Comment by PVince81** [comment] 2015-05-19 11:01
I cannot reproduce this so will need to guess based on all info provided on this ticket.
So the more info, the better.

**Comment by VicDeo** [comment] 2015-05-19 14:35
@Pantek59 a wild guess? Do you have several OC instances with different prefixes sharing the same database?

**Comment by PVince81** [comment] 2015-05-20 08:51
I tried the following steps with Mariadb 10.0.17:
1) Setup OC v7.0.4
2) Enable the documents app (also v7.0.4 version)
3) Create a document, type something, close
4) Update to 8.0.3
5) Enable the documents app (the v8.0.3 version)

It worked fine.

**Comment by PVince81** [comment] 2015-05-20 08:55
Updating 7.0.4->8.0.2 also works (which seems to be the version reported here)

**Comment by PVince81** [comment] 2015-05-20 08:56
@VicDeo does the documents app do anything with the privatedata table ? I don't really see the correlation.

**Comment by PVince81** [comment] 2015-05-20 09:01
From what I remember, indices are not namespaced, they have no table prefix. See https://github.com/owncloud/core/pull/14658

Do you guys @Pantek59 @sisyphosloughs @droghio have multiple ownCloud instances using the same database but different table prefixes ?

If yes, then the index names will clash.

**Comment by nickvergessen** [comment] 2015-05-20 10:25
> Do you guys @Pantek59 @sisyphosloughs @droghio have multiple ownCloud instances using the same database but different table prefixes ?
>
> If yes, then the index names will clash.

Well they should crash on install already and also it happens without any apps. So that should not be the problem with the update. but other then that I can not reproduce it aswell.

**Comment by VicDeo** [comment] 2015-05-20 13:18
@PVince81 >does the documents app do anything with the privatedata table ? 

No, it doesn't. But it had an autoincrement column for `oc_documents_op` table (keys  such columns are created automatically) and an explicitly declared index on this column, just like the `privatedata` table does.

**Comment by Pantek59** [comment] 2015-05-21 12:34
@VicDeo No, there has always been just one instance of OC running with a database on its own.

**Comment by cmonteroluque** [comment] 2015-05-22 10:07
@Pantek59 @sisyphosloughs Any additional info you could send would be helpful. We're having trouble reproducing the issue

**Comment by Pantek59** [comment] 2015-05-30 13:24
@cmonteroluque We are currently moving, so my OC server is offline. As soon as its back online, I'll try to reproduce the error message by re-inserting the lines I removed for it to work properly again.

**Comment by PVince81** [comment] 2015-09-21 14:51
@Pantek59 did you manage to reproduce it ?

**Comment by Pantek59** [comment] 2015-09-22 12:57
@PVince81 No, unfortunately not. I reinserted the lines the lines I was told to remove before but the error messages did not show up. I set up a VM with OC 7.4 but could not reproduce it there either.
Then I wanted to update OC all the way from 7 to 8 to reproduce it, but that apparently slipped from my mind at some point. Sorry for not reporting back.

**Comment by PVince81** [comment] 2015-09-24 12:39
Closing hence. If the problem appears again with more recent versions, feel free to reopen.

**Closed by PVince81** 2015-09-24 12:39 UTC
Labels: bug, sev1-critical, triage
