### ISSUE TITLE
Double folders when user has a different permission in a group and outside of it

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#25555] opened 2016-07-21 14:46 UTC
### Steps to reproduce
1. Use ownCloud 9.0.4
2. Have a group (from LDAP) with couple users and a user X
3. Share a folder F with the group and remove write permissions
4. Share the folder F with the user X and give him write permissions

### Expected behaviour

User X should see 1 folder F with permissions merged

### Actual behaviour

User X sees 1 folder F and 1 folder "F (2)".

### Server configuration
**Operating system**: CentOS 7.2

**Web server:** Apache 2.4

**Database:** mysql  Ver 15.1 Distrib 5.5.50-MariaDB

**PHP version:** PHP 5.6.23

**ownCloud version:** (see ownCloud admin page) 9.0.4

**Updated from an older ownCloud or fresh install:** Updated from 9.0.2 directly.

**Where did you install ownCloud from:** owncloud repositories

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - gallery
  - galleryplus
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocagvsml5uip",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxxx",
        ],
        "theme": "",
        "debug": "false",
        "datadirectory": "\/mnt\/xxxxxx",
        "overwrite.cli.url": "https:\/\/xxxxxx\/",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "xxxxx",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_from_address": "lcsb-sysadmins",
        "mail_domain": "uni.lu",
        "mail_smtphost": "xxxxxx",
        "mail_smtpport": "xx",
        "maintenance": false,
        "loglevel": 3,
        "ldapIgnoreNamingRules": false,
        "preview_libreoffice_path": "\/bin\/libreoffice",
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "singleuser": false,
        "htaccess.RewriteBase": "\/"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration

Latest Mac client. Windows same problem.

**Comment by Trefex** [comment] 2016-07-21 14:46
I believe this is related to https://github.com/owncloud/core/issues/24575

Pinging @PVince81 as requested in the mailing list.

**Comment by PVince81** [comment] 2016-07-21 17:06
It might be related, yes. I'll test your use case there and with the fix to see if it solves it.

Thanks for the report.

**Comment by PVince81** [comment] 2016-07-22 07:22
Yes, the PR I'm working on will fix it. Also will be covered by automated test: https://github.com/owncloud/core/pull/25543/files#diff-b4888b15e6a7d80fe706602129494bfbR609

**Comment by PVince81** [comment] 2016-07-22 08:52
Closing this as duplicate of https://github.com/owncloud/core/issues/24575

**Closed by PVince81** 2016-07-22 08:52 UTC
Labels: bug, feature:sharing
