### ISSUE TITLE
"Failed to request notifications. Please try to refresh the page manually"

### ISSUE THREAD

**Issue by ghost** [owncloud/core#26665] opened 2016-11-21 08:50 UTC
### Steps to reproduce
1. Login
2. Wait indefinitely the content of the center pane to be loaded, but it never comes...

### Expected behaviour
The files are displayed.

### Actual behaviour
The files never load and the center pane is always empty. IN FIREFOX ONLY. Internet Explorer is OK

It's happenning with the files app, the Calendar app, the admin page....

Error message displayed on the page is : 
`
Failed to request notifications. Please try to refresh the page manually`

When refreshing the page manually (or just wait), nothing is loaded.

The error in the javascript console is  

`Uncaught Exception : CalDAV Client could not been initialized. Querying current-user-principal failed.`

Owncloud files is therefore unacessible and the files and never displayed. It worked for 2 years before and this happening since last update(s).

### Server configuration
**Operating system**:  Linux Raspbian

**Web server:** Lighttpd

**Database:** mysql

**PHP version:** 5.4.45

**ownCloud version:** ownCloud 9.1.1

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** owncloud repository debian

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

```

**List of activated apps:**
Files, calendars, contact, activity, gallery, tasks.
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** **FIREFOX 50.0**

**Operating system:** **Windows 7**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log

There is one error in the javascript console

```

**Comment by stephane84** [comment] 2016-11-21 08:51
![1](https://cloud.githubusercontent.com/assets/8068395/20476197/04914896-afd0-11e6-9071-aa3681c29614.png)
![2](https://cloud.githubusercontent.com/assets/8068395/20476198/0491c17c-afd0-11e6-987d-c852f95f2cf3.png)
![3](https://cloud.githubusercontent.com/assets/8068395/20476199/04950c56-afd0-11e6-99e9-167ae67e131b.png)
![4](https://cloud.githubusercontent.com/assets/8068395/20476200/0498d37c-afd0-11e6-9a10-e42a54349a30.png)

**Comment by stephane84** [comment] 2016-11-21 08:53
@dvergeylen

**Comment by RealRancor** [comment] 2016-11-21 09:59
> Web server: Lighttpd

Some limitations in lighttpd which now happens with 9.1 because that is using the *DAV backend? In the past it was agreed in https://github.com/owncloud/core/issues/13642 that lighttpd is unsupported because of various bugs and limitations in that webserver.

**Comment by PVince81** [comment] 2016-11-22 14:03
Notifications are part of the notification app. As a workaround you could disable that app for now.

AFAIK notifications doesn't use Webdav, so not sure why the call would fail. You should be able to find the matching call in the network console.

**Comment by renaudallard** [comment] 2016-11-26 17:40
I have exactly the same problem with nginx

**Comment by stephane84** [comment] 2016-11-28 15:55
I've found a new error message related to the same error.

16:53:10,228 Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src https://example.com 'unsafe-eval' »). 1 tasks

which can be translated to something like : 

The parameters of the page have blocked the loading of one resource to self : (« script-src https://example.com 'unsafe-eval' »). 1 tasks

**Comment by stephane84** [comment] 2016-12-20 15:08
Any news on this bug ? It is still not working... Can I provide more info ?

**Comment by PVince81** [comment] 2016-12-20 15:16
lighttpd is not supported https://doc.owncloud.org/server/9.0/admin_manual/issues/general_troubleshooting.html, you might want to try with Apache or nginx instead.

I suspect that this issue is related to the lighttp config somehow but I don't know anything about lighttpd and don't have time to dig into it, sorry.

**Comment by sjash** [comment] 2017-02-11 12:50
I'm too stuck with this!I'm not able to login with my LDAP users. Only admin is able to login but again not able to do anything.
Any solutions of the bug ???

**Comment by kdslkdsaldsal** [comment] 2017-02-11 17:08
@sjash Did you had a look at the previous comments providing a few suggestions / workarounds?

**Comment by luckydonald** [comment] 2017-02-21 21:07
And I got this with apache. 
ownCloud 9.1.4 (production)

**Comment by luckydonald** [comment] 2017-02-21 21:19
Interestingly, the favorites list still work.
![image](https://cloud.githubusercontent.com/assets/2737108/23185385/91bf4e9c-f883-11e6-8187-22bf284a04cc.png)
Clicking gets me there:
![image](https://cloud.githubusercontent.com/assets/2737108/23185442/bbf5e89c-f883-11e6-9cef-4f1c7b774e92.png)

**Comment by kdslkdsaldsal** [comment] 2017-03-18 19:21
@luckydonald Are you also running nginx as @renaudallard? I've noticed the same today at my nginx instance with oC 9.1.4 so this might be related to a not working nginx/lighttpd configuration and not ownCloud itself.

If i'm opening e.g.:

https://example.com/ocs/v2.php/apps/notifications/api/v1/notifications

i'm getting repeatedly asked for Basic Auth credentials and my existing / known credentials are not accepted there. If i'm doing the same at the demo.owncloud.org:

User:test
Pass:test
URL: https://demo.owncloud.org/ocs/v2.php/apps/notifications/api/v1/notifications

the credentials are accepted there without such issues. So nginx / lighttpd might be the source of this issue as shown above.

**Comment by kdslkdsaldsal** [comment] 2017-03-19 10:40
So had another look here. I have added the following to the /ocs/v1.php:

``echo('/ocs'.\OC::$server->getRequest()->getRawPathInfo());``

after: https://github.com/owncloud/core/blob/v9.1.4/ocs/v1.php#L54 which leads to the following output when cancelling the Basic Auth popup:

``/ocs/apps/notifications/api/v1/notifications``

We can see here, that the v1.php/v2.php is missing in between on my environment. Putting that URL into the browser like:

https://example.com/ocs/apps/notifications/api/v1/notifications

gives the repeated Basic Auth Request. On the Demo this is giving a "File not found" instead.

https://demo.owncloud.org/ocs/apps/notifications/api/v1/notifications

Conclusion:

It seems the ``/ocs'.\OC::$server->getRequest()->getRawPathInfo()`` got filled incorrectly by nginx (most likely also on lighttpd and apache with php-fpm/php-fcgi) causing this issue.

**Comment by LeoVerto** [comment] 2017-03-19 14:05
I'm having the same problem with nginx, after a ton of debugging yesterday I came to a similar conclusion: There is definitely something fishy going on with the recommended nginx config splits paths.

I also see failed requests to paths like:
`/owncloud/apps/files/core/img/breadcrumb.svg`
`/owncloud/apps/files/ocs/v2.php/apps/notifications/api/v1/notifications`
which should obviously be
`/core/img/breadcrumb.svg`
`/ocs/v2.php/apps/notifications/api/v1/notifications`
instead.

But these may also be a seperate problem with me using a nginx alias for the /owncloud directory.

**Comment by kdslkdsaldsal** [comment] 2017-03-19 16:27
@LeoVerto Yes, this looks indeed more like a general issue within your nginx config concerning the used subdirectory (AFAIK the nginx example at the documentation was never really tested for this).

**Comment by LeoVerto** [comment] 2017-03-28 03:03
@kdslkdsaldsal The following regex should split the path info for files in `/ocs` the way owncloud expects it:
`^(.+\/ocs|.+\.php)(\/.*)$`

I can't really test this as my setup seems to be broken for some other reason but let me know if it works for you.

**Comment by kdslkdsaldsal** [comment] 2017-04-23 20:17
I didn't had the time to test the regex until but just wanted to have a look now. Few days before i've updated from 9.1.4 to 9.1.5 and now the request to:

> https://example.com/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 

doesn't give the repeated Basic Auth popup after entering the login credentials but the following expected response:

``{"ocs":{"meta":{"status":"ok","statuscode":200,"message":null},"data":[]}}``

So it seem something in 9.1.4 vs. 9.1.5 (there was no other changes on this system) got fixed which is also solving this issue here (at least for me).

@LeoVerto @sjash @renaudallard @luckydonald Could anyone confirm this?

**Comment by luckydonald** [comment] 2017-05-08 09:52
Upgraded from 9.1.4.2 to 9.1.5, still got no files displayed.

**Comment by kdslkdsaldsal** [comment] 2017-05-08 10:10
@luckydonald Wrong issue chosen here? The one here is not about files which are not displayed 😃

**Comment by luckydonald** [comment] 2017-05-08 13:35
@kdslkdsaldsal Not quite. 
If you scroll to the toplevel post, It says `Expected behaviour: The files are displayed.`.
This is why I'm here. 

I think the error message was coincidentally there, but the only thing visble to the user.

**Comment by kdslkdsaldsal** [comment] 2017-05-08 13:52
@luckydonald 

Ok, then it seems the issue here drifted away far to much from the original issue. Such issues with missing files not displayed are mostly environmental issues (misconfiguration on webserver side with webservers blocking required WebDAV methods and similar). They normally can't be fixed by ownCloud so you most likely will see the same issue on every newer release.

As the OP had used lighttpd which is not supported and shouldn't be used at all this issue probably should be just closed. Especially as that user is not there anymore (ghost user).

If you still have similar issues like the OP its probably the best to dig your way through FAQs at the forums like https://central.owncloud.org/t/how-to-fix-caldav-carddav-webdav-problems/852

**Comment by kdslkdsaldsal** [comment] 2017-05-08 13:58
Adding to this the OP (ghost) got a "CalDAV Client could not been initialized"  where you got a "Service Unavailable". Two different messages which might have two completely different reasons / issues.

**Comment by luckydonald** [comment] 2017-05-08 20:04
Oh, okey.
Anyway as a follow up:
After said upgrade, `/webdav` s again shows  `503 Service Unavailable`. This time I checked the content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>System in single user mode.</s:message>
</d:error>
```
So setting `"singleuser"=> false` in ` config/config.php` brought back my files.

**Comment by kdslkdsaldsal** [comment] 2017-05-09 06:17
@luckydonald No need to say sorry 😄 Just had a short search and it seems this is a known limiation: https://github.com/owncloud/core/issues/16597

**Comment by fsantiago07044** [comment] 2017-09-26 16:05
so this is still a thing, in owncloud 10? i receive it all the time until i disable the notifications app. in centos and nginx.

**Comment by kdslkdsaldsal** [comment] 2017-09-26 16:32
@fsantiago07044 For me it started to work with 9.1.5 and continued to work with a current installed 10.0.3.

**Comment by fsantiago07044** [comment] 2017-09-26 18:37
ok @kdslkdsaldsal . i installed owncloud 10 from oc_Stable via yum from scratch and started seeing the error message immediately without even being done with configuration. final config later continued the error message. 

what information can i provide to help diagnose it? Thanks.

**Comment by PVince81** [comment] 2017-10-09 14:12
@fsantiago07044 check the network console for failed calls and post the "Response" part of the failed response. Maybe some env issue is preventing the call to go through.

Also ownlcoud.log.

@fsantiago07044 a full bug report would be appreciated with config, logs, etc, see https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by fsantiago07044** [comment] 2017-10-17 20:07
i would collect your requested data but after having kept the notifications app disabled for some time and only now just re-enabling it, the issue does not occur anymore. i've had it re-enabled since you posted this response and have still not seen the error message re-occur.

**Comment by PVince81** [comment] 2017-10-18 12:32
I'm closing this issue then.

If anyone is seeing this again, please use the issue template and post logs.

**Closed by PVince81** 2017-10-18 12:32 UTC
Labels: bug

**Comment by revoltown** [comment] 2023-05-03 21:58
i have the same problem, any solution ?

**Comment by gstrauss** [comment] 2023-05-03 23:31
@revoltown 
> i have the same problem, any solution ?

@revoltown did you bother to read the last comment before posting?
