### ISSUE TITLE
Fatal Error on Cron Execution

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#16557] opened 2015-05-25 12:33 UTC
Hi, i'm using OC 8.0.2. On every Cron Execution i get the following error:

```

Exception: {"Message":"\\OC_Image::_output(): \"image\/x-ms-bmp\" is not supported when forcing a specific output format","Code":0,"Trace":"#0 \/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/private\/image.php(170): OC_Image->_output(NULL, 'image\/x-ms-bmp')\n#1 \/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/private\/preview.php(568): OC_Image->show(NULL)\n#2 \/var\/www\/*********\/htdocs\/*********\/owncloud\/core\/ajax\/preview.php(44): OC\\Preview->showPreview()\n#3 \/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/var\/www\/*********...')\n#4 [internal function]: __lambda_func(Array)\n#5 \/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_119', Array)\n#6 \/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/core\/preview.p...')\n#7 \/var\/www\/*********\/htdocs\/*********\/owncloud\/index.php(36): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/*********\/htdocs\/*********\/owncloud\/lib\/private\/image.php","Line":237} 
```

this happens for 3 days. before it all worked well. i have nothing changed on my installation.
the news app does not fetch new items anymore, so i think the error crashes the whole cronjob.

any ideas or further information needed?

**Comment by PVince81** [comment] 2015-05-26 09:44
Hmm, I think a failing job in the queue should fail gracefully and move on to the next one after logging the error.

**Comment by PVince81** [comment] 2015-05-26 09:44
CC @georgehrke @oparoz for the error which seems to be related to previews.

**Comment by PVince81** [comment] 2015-05-26 09:46
@stefan-niedermann could you please use the issue template or at least tell us what ownCloud version you are using ?

From the code on master I see that exceptions should be catched as expected and would move on to the next job: https://github.com/owncloud/core/blob/master/lib/private/backgroundjob/job.php#L53
Strangely your error message doesn't contain the string "Error while running background job"

**Comment by PVince81** [comment] 2015-05-26 09:47
@stefan-niedermann ok I see, it's 8.0.2.

**Comment by PVince81** [comment] 2015-05-26 09:47
8.0.2 has the check too: https://github.com/owncloud/core/blob/v8.0.2/lib/private/backgroundjob/job.php#L37

**Comment by stefan-niedermann** [comment] 2015-05-26 11:35
Hm, any hotfix or workaround i could use? This is spamming my logfile and i am not able to use News-App.
Or any Idea what App causes this crash so i could at least deactivate it?

Further Information:
PHP 5.5.22
MySQL libmysql - 5.5.41
Apache/2.2.22 (Debian)

**Comment by PVince81** [comment] 2015-05-26 11:39
You could try adding this:
```
\OCP\Util::writeLog('cron', 'executing job: ' . get_class($this) . ' job id=' . $this->id, \OCP\Util::DEBUG);
```

before https://github.com/owncloud/core/blob/v8.0.2/lib/private/backgroundjob/job.php#L36

This would log the jobs that are getting executed and might help pinpoint which one is failing.

**Comment by PVince81** [comment] 2015-05-26 11:39
(and set loglevel to 0 in your config.php)

**Comment by oparoz** [comment] 2015-05-29 02:17
Probably related to https://github.com/owncloud/core/issues/16461

**Comment by stefan-niedermann** [comment] 2015-06-17 07:32
I have new information:
It happens only on System-Cron-Execution - if i switch to AJAX-based Cron-Execution, it works.

**Comment by enoch85** [comment] 2015-07-03 10:50
I don't know if my issue is exactly the same, but I have the same error. 

Since 8.0.4 cron.php is not executed every 15 minutes as it should be. I have tried several different instances with 8.0.4 and it's the same error - works with AJAX-cron, but not System-cron every 15 minutes.

This is my crontab:

```
root@en0ch:~# crontab -l
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

# crontab -u www-data -e
*/15  *  *  *  * php -f /var/www/owncloud/cron.php

@weekly rm /var/www/owncloud/data/owncloud.log

@weekly /var/scripts/owncloud_update.sh

@monthly /var/scripts/virus-scan.sh
```

@PVince81 Why has this issue no milestone?

**Comment by jzee** [comment] 2015-07-20 19:40
if I may, I believe this is a dupe of https://github.com/owncloud/core/issues/16461 -identical error message and related to the ambiguous bmp mimetype.

**Comment by stefan-niedermann** [comment] 2015-07-20 21:40
seems to work again after upgrade from OC 8.0 to 8.1.

Close this issue if you want :)

**Closed** 2015-07-20 22:07 UTC
Labels: bug, sev2-high
