### ISSUE TITLE
File versioning seems broken

### ISSUE THREAD

**Issue by Peac** [owncloud/core#20234] opened 2015-11-02 17:53 UTC
### Steps to reproduce
1. Create a local file (tested with docx and pdf, txt files seems to work fine)
2. Let the client sync, write something, save...produce some versions on the server
3. Login into the webinterface, click on the file -> versions
4. Try to download or restore it

### Expected behaviour
Versions should be downloadable and restorable.

### Actual behaviour
Download won't start, the restore brings a broken file to the client or a "Verbindung beendet" / "Broken webserver returning empty content length for non-empty file on resume".

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS

**Web server:**
Apache  2.4.7
**Database:**
MySQL 5.5.46
**PHP version:**
PHP5 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.2.0
**Updated from an older ownCloud or fresh install:**
updated
**List of activated apps:**
Enabled:
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - mozilla_sync: 1.4

**The content of config/config.php:**
<?php
$CONFIG = array (
  'logtimezone' => 'Europe/Berlin',
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'datadirectory' => ''/var/www/owncloud/data'',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'trusted_domains' =>
  array (
    0 => 'XXX',
    1 => 'XXX',
  ),
  'mail_from_address' => 'donotreply',
  'mail_domain' => 'XXX',
  'secret' => 'XXX',
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => 'auto',
  'versions_retention_obligation' => '90, auto',
  'appcodechecker' => true,
  'enabledPreviewProviders' => array(
        'OC\Preview\PNG',
        'OC\Preview\JPEG',
        'OC\Preview\GIF',
        'OC\Preview\BMP',
        'OC\Preview\XBitmap',
        'OC\Preview\MP3',
        'OC\Preview\MarkDown'
  ),
  'cipher' => 'AES-256-CFB',
  'filelocking.enabled' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/
no

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/
no

### Client configuration
**Browser:**
Mozilla Firefox 41.0.2 (x86)

**Operating system:**
Windows 7 64bit
#### Web server error log
---

#### ownCloud log (data/owncloud.log)
Debug	files_locking	PASS: Acquired read lock for /var/www/owncloud/data/USER/files_encryption/keys/files/Public/test.docx/OC_DEFAULT_MODULE/fileKey	2015-11-02T18:23:52+01:00
Debug	files_locking	INFO: Read lock requested for /var/www/owncloud/data/USER/files_encryption/keys/files/Public/test.docx/OC_DEFAULT_MODULE/fileKey	2015-11-02T18:23:52+01:00
Debug	files_locking	INFO: Incrementing lock type 1 count for /var/www/owncloud/data/USER/files/Public/test.docx	2015-11-02T18:23:52+01:00

#### Browser log
---

**Comment by volp3** [comment] 2015-11-02 23:21
i face the same problem, only diff is ownCloud 8.1.0 (stable) on Debian 7
i run the server and didn't change anything on it for the last 2 weeks, on the other hand the error appeared with the new win client, so i guess the problem might be there. Hope it helps

**Comment by MorrisJobke** [comment] 2015-11-03 08:37
@schiesbn

**Comment by volp3** [comment] 2015-11-03 11:57
some addional infos now that i could get my hands on the clients notebook

Snippet of .owncloudsync.log :
=#=#=# Syncrun started 2015-11-03T12:09:21 until 2015-11-03T12:16:00 (399620 msec)
11:15:53|489<XXX>/PRR06.doc|INST_NEW|Down|1438612688|1acd123647b9af06d65f37cf0277bc12|369040|00056445oc07zpmte964|2|Broken webserver returning empty content length for non-empty file on resume|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-11-03T12:16:59 until 2015-11-03T12:22:45 (346566 msec)
|0|<XXX>/PRR06.doc|INST_NEW|Down|1438612688|1acd123647b9af06d65f37cf0277bc12|369040|00056445oc07zpmte964|1|Verbindung beendet|200|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-11-03T12:23:29 until 2015-11-03T12:27:51 (261743 msec)
11:27:45|424<XXX>/PRR06.doc|INST_NEW|Down|1438612688|1acd123647b9af06d65f37cf0277bc12|369040|00056445oc07zpmte964|2|Broken webserver returning empty content length for non-empty file on resume|0|0|0|||INST_NONE|

NO warning/error in /data/owncloud.log, last entry is 2015-11-02

**Comment by schiesbn** [comment] 2015-11-03 13:21
Didn't tried it with the sync client, but edited a text file multiple times with the text editor, downloaded versions and restored them. Everything worked just fine for me.

@Peac please disable the file_locking app and try again. This was replaced by another locking mechanism in 8.2, so maybe the old locking app gets in the way for the new locking

**Comment by Peac** [comment] 2015-11-03 21:06
As I mentioned "txt files seems to work fine" ;) I can reproduce this one with docx/pdf/...

I disabled the file_locking app and removed the entry "'filelocking.enabled' => true," from the config.php. The problem remains.

I also tried a older Windown Client Version (2.0.1.5446).

**Comment by schiesbn** [comment] 2015-11-04 08:31
> As I mentioned "txt files seems to work fine" ;) I can reproduce this one with docx/pdf/...

ah, ok didn't saw it. Let me re-try with some other file types

**Comment by schiesbn** [comment] 2015-11-04 10:09
@Peac I could re-produce it. This should fix it, maybe you can give it a try? https://github.com/owncloud/core/pull/20288

**Comment by volp3** [comment] 2015-11-04 10:46
tried to downgrade win64client to former working version (2.0.0), had no effect, even tho the error appeared right after update to 2.0.2

**Comment by schiesbn** [comment] 2015-11-04 10:51
@volp3 it is not a client issue, it is a server issue, as said above the fix is here https://github.com/owncloud/core/pull/20288 if you want to patch your server manually. Otherwise it will be released with the next bugfix release. (Note: It doesn't fix already created versions, only new one)

**Comment by Peac** [comment] 2015-11-04 17:47
I tried the fix (the first file).

After a few test this is the result:
- Create a docx document, create 4 versions --> all versions are downloadable
- If I restore a version --> the versions gets broken (error in the client as above, download via webinterface is not possible any more)
It seems that the newest version will survive one restore. But with all other versions it can be reproduced multiple times.

**Comment by schiesbn** [comment] 2015-11-04 19:07
@Peac thanks for the feedback, I will try to re-produce it.

**Comment by schiesbn** [comment] 2015-11-04 19:15
After a quick test on the branch of the PR I couldn't reproduce it. I can restore and download all versions.
I will try it tomorrow on a 8.2.0 branch...

**Comment by schiesbn** [comment] 2015-11-05 09:47
Now I also tested it with 8.2.0 + the patch from https://github.com/owncloud/core/pull/20288

I can download and restore every version

**Comment by Peac** [comment] 2015-11-05 16:29
I created a new new testfile after the patch. The patch is only one file? The second one seems to be a testfile.

I made a new test with log in debug mode, got this little one (before the patch the log was empty, when I tried to restore something):
Debug 	webdav 	Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(148): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(121): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70} 	2015-11-05T17:20:36+01:00

**Closed** 2015-11-06 10:17 UTC
Labels: 3 - To Review, app:encryption, app:files_versions, sev2-high

**Comment by schiesbn** [comment] 2015-11-06 13:34
@Peac the issue sounds like a authentication issue of the client which should be unrelated to encryption. Could you try to upload the same file multiple times with the web interface, revert the versions and try to download it with the web interface without any client interaction.

**Comment by Peac** [comment] 2015-11-06 16:05
I changed the file to https://github.com/owncloud/core/pull/20331.
The error remains (3 versions, all downloadable, restore second version --> broken, restore third version --> downloadable, try to download second version again --> broken.)
Same with first version. As long as I don't restore them, I can download them (newest version never gets broken).

If I use the webinterface only --> same behavior, but no entrys in the logfile
If I use the client with this patchversion I get a different entry in the log file:

Fatal	webdav	Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/7c796b2a2924aa68b1e8d841db9d073e\", 1, 1446826966, \"files\\\/7c796b2a2924aa68b1e8d841db9d073e\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/7c796b2a2924aa68b1e8d841db9d073e' for key 'lock_key_index'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(242): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/var\/www\/owncloud\/lib\/private\/lock\/dblockingprovider.php(72): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/lock\/dblockingprovider.php(108): OC\\Lock\\DBLockingProvider->initLockField('files\/7c796b2a2...', 1)\n#7 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(639): OC\\Lock\\DBLockingProvider->acquireLock('files\/7c796b2a2...', 1)\n#8 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Common->acquireLock('files\/Privat\/FH...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Privat\/FH...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Privat\/FH...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1801): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Privat\/FH...', 1, Object(OC\\Lock\\DBLockingProvider))\n#12 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1900): OC\\Files\\View->lockPath('\/Privat\/FH Bonn...', 1)\n#13 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1191): OC\\Files\\View->lockFile('Privat\/FH Bonn ...', 1)\n#14 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\\Files\\View->getFileInfo('Privat\/FH Bonn ...')\n#15 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/lockplugin.php(71): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Privat\/FH Bonn ...')\n#16 [internal function]: OC\\Connector\\Sabre\\LockPlugin->getLock(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#18 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#21 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#22 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66}	2015-11-06T16:22:46+01:00

**Comment by PVince81** [comment] 2015-11-06 16:58
@schiesbn is there are situation where the files are already in the broken state (wrong size values) ?
The fix is only to prevent files to get into this broken state in the first place.

Might require a repair step like https://github.com/owncloud/core/issues/18225 ?

**Comment by schiesbn** [comment] 2015-11-09 09:48
> is there are situation where the files are already in the broken state (wrong size values) ?
The fix is only to prevent files to get into this broken state in the first place.

All versions which are already are broken will stay broken. The PR fixes it only for new files. At the moment there is no repair script to fix wrong file sizes.
