### ISSUE TITLE
Feature Request: Send email notification if file is downloaded

### ISSUE THREAD

**Issue by novij** [owncloud/core#13683] opened 2015-01-26 17:04 UTC
We often send a share link to our customers and would like to know if the file is downloaded. It would be nice to have a checkbox for a email notification to the file owner.

**Comment by RealRancor** [comment] 2015-01-26 22:52
Very likely a duplicate of those: https://github.com/owncloud/core/issues/8765, https://github.com/owncloud/core/issues/7812

**Comment by DeepDiver1975** [comment] 2015-01-27 07:04
> Very likely a duplicate of those: #8765, #7812
> Thomas Müller

indeed - THX @RealRancor

**Closed** 2015-01-27 07:04 UTC
Labels: Enhancement
