### ISSUE TITLE
disable external storages

### ISSUE THREAD

**Issue by zanglerecke** [owncloud/core#23277] opened 2016-03-15 18:45 UTC
It would be a nice feature to just deactivate an external storage, but keep all settings. so eg a temp. unaccessable storage can be mainternanced while it is disabled and quickly reinstalled.

for admin as well as for users.

**Comment by zanglerecke** [comment] 2016-03-15 18:46
ok that response is realy fast...

**Comment by PVince81** [comment] 2016-10-10 15:06
duplicate of https://github.com/owncloud/core/issues/11518

**Closed by PVince81** 2016-10-10 15:06 UTC
Labels: app:files_external, enhancement
