### ISSUE TITLE
PHP-FPM clients can't  login

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/core#27086] opened 2017-02-04 15:22 UTC
Let OC running via php-fpm it self will work.
Access via web are possible, but the official oc client can't log in.
Using mod_php will work for both, but fpm only for the website.

**Operating system**: CentOS 7.3
**Web server:** Apache 2.4
**Database:** MariDB 10.1
**PHP version:** 7.0 (FPM) 5.4.16(mod_php)
**ownCloud version:**  9.1.4

Debug log when an client try to log in on fpm mode:
system ownCloud[7560]: {webdav} Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/html\/owncloud\/remote.php(164): require_once('\/var\/www\/html\/o...')\n#6 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}

On https://doc.owncloud.org/server/9.1/admin_manual/installation/source_installation.html#php-fpm-tips-label 
No special requirements for fpm mode are documented.

**Comment by kdslkdsaldsal** [comment] 2017-02-04 15:43
@tuxmaster This is a duplicate of https://github.com/owncloud/core/issues/7719

My recommendation: Either use Apache2 + mod_php or nginx + mod_fpm. Both are known to work.

**Comment by tuxmaster** [comment] 2017-02-04 17:08
Adding this line was it:
> SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
I think this should be added to the manual at the fpm part.
Or better add the link to the documentation.

**Comment by kdslkdsaldsal** [comment] 2017-02-04 17:40
Nice. So i think you can close this issue.

There is a note about the "No authorization" message available at the documentation:

https://doc.owncloud.org/server/latest/admin_manual/issues/general_troubleshooting.html#common-problems-error-messages

If you think this should be also documented at the fpm link you have posted you could either create a new issue at https://github.com/owncloud/documentation/issues or even create a new Pull Request adding that to the documentation there.

**Closed** 2017-02-04 17:45 UTC

**Comment by kdslkdsaldsal** [comment] 2017-02-05 10:07
Thanks, here is the reference: https://github.com/owncloud/documentation/issues/2842
