### ISSUE TITLE
Any files in home page aren't displayed after deleting shared user

### ISSUE THREAD

**Issue by tazuke** [owncloud/core#18005] opened 2015-07-31 07:47 UTC
### Steps to reproduce
1. "A" shares some files with "B"
2. Inactivate (or delete) A's accound from LDAP. Sharing informatin is already stored in the database.
3. B login and opens ownCloud top page.

### Expected behaviour
Displayed shared files.

### Actual behaviour
Any files aren't displayed.

### Server configuration
**Operating system**:
CentOS 6.4

**Web server:**
Apache/2.2.21

**Database:**
MariaDB 5.5.35

**PHP version:**
5.5.21

**ownCloud version:** (see ownCloud admin page)
8.0.4

**Updated from an older ownCloud or fresh install:**
from 7 to 8.0.4

**The content of config/config.php:**

```
  'datadirectory' => '/usr/local/apache/vhosts/drive.abc.com/htdocs/data/',
  'has_internet_connection' => false,
  'appstoreenabled' => false,
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'rdrive',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'drive.abc.com',
  ),
  'loglevel' => '3',
  'logtimezone' => 'Asia/Tokyo',
  'log_rotate_size' => 3221225472,
  'enable_previews' => true,
```

**Are you using external storage, if yes which one:** 
s3fs

**Are you using encryption:**

**Are you using an external user-backend, if yes which one:** 
LDAP

#### LDAP configuration (delete this part if not used)

```
| user_ldap         | cleanUpJobOffset                     | 1150                                                                                                          | 
| user_ldap         | enabled                              | yes                                                                                                           | 
| user_ldap         | installed_version                    | 0.5.0                                                                                                         | 
| user_ldap         | ocsid                                | 166061                                                                                                        | 
| user_ldap         | s01has_memberof_filter_support       | 1                                                                                                             | 
| user_ldap         | s01home_folder_naming_rule           |                                                                                                               | 
| user_ldap         | s01last_jpegPhoto_lookup             | 0                                                                                                             | 
| user_ldap         | s01ldap_attributes_for_group_search  |                                                                                                               | 
| user_ldap         | s01ldap_attributes_for_user_search   |                                                                                                               | 
| user_ldap         | s01ldap_backup_host                  |                                                                                                               | 
| user_ldap         | s01ldap_backup_port                  |                                                                                                               | 
| user_ldap         | s01ldap_cache_ttl                    | 600                                                                                                           | 
| user_ldap         | s01ldap_configuration_active         | 1                                                                                                             | 
| user_ldap         | s01ldap_display_name                 | samaccountname                                                                                                | 
| user_ldap         | s01ldap_email_attr                   | mail                                                                                                          | 
| user_ldap         | s01ldap_experienced_admin            | 0                                                                                                             | 
| user_ldap         | s01ldap_expert_username_attr         |                                                                                                               | 
| user_ldap         | s01ldap_expert_uuid_group_attr       |                                                                                                               | 
| user_ldap         | s01ldap_expert_uuid_user_attr        |                                                                                                               | 
| user_ldap         | s01ldap_group_display_name           | cn                                                                                                            | 
| user_ldap         | s01ldap_group_filter_mode            | 1                                                                                                             | 
| user_ldap         | s01ldap_group_member_assoc_attribute | member                                                                                                        | 
| user_ldap         | s01ldap_groupfilter_groups           |                                                                                                               | 
| user_ldap         | s01ldap_groupfilter_objectclass      |                                                                                                               | 
| user_ldap         | s01ldap_login_filter_mode            | 1                                                                                                             | 
| user_ldap         | s01ldap_loginfilter_attributes       |                                                                                                               | 
| user_ldap         | s01ldap_loginfilter_email            | 0                                                                                                             | 
| user_ldap         | s01ldap_loginfilter_username         | 1                                                                                                             | 
| user_ldap         | s01ldap_nested_groups                | 0                                                                                                             | 
| user_ldap         | s01ldap_nocase                       | 1                                                                                                             | 
| user_ldap         | s01ldap_override_main_server         | 0                                                                                                             | 
| user_ldap         | s01ldap_paging_size                  | 500                                                                                                           | 
| user_ldap         | s01ldap_port                         | 389                                                                                                           | 
| user_ldap         | s01ldap_quota_attr                   |                                                                                                               | 
| user_ldap         | s01ldap_quota_def                    |                                                                                                               | 
| user_ldap         | s01ldap_tls                          | 0                                                                                                             | 
| user_ldap         | s01ldap_turn_off_cert_check          | 0                                                                                                             | 
| user_ldap         | s01ldap_user_filter_mode             | 1                                                                                                             | 
| user_ldap         | s01ldap_userfilter_groups            |                                                                                                               | 
| user_ldap         | s01ldap_userfilter_objectclass       |                                                                                                               | 
| user_ldap         | types                                | authentication                                                                                                | 
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"84f00659fb01fcf1df9b3758be729312","remoteAddr":"133.237.7.94","app":"files","message":" Backends provided no user object for AD93E318-DE5F-41A2-BFEF-F6EAD0BD08E5","level":3,"time":"2015-07-30T09:45:31+09:00"}
{"reqId":"84f00659fb01fcf1df9b3758be729312","remoteAddr":"133.237.7.94","app":"files","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(56): OC\\\\Files\\\\Filesystem::initMountPoints('AD93E318-DE5F-4...')\\n#1 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/apps\\\/files_sharing\\\/lib\\\/cache.php(89): OC\\\\Files\\\\Cache\\\\Shared_Cache->getSourceCache('')\\n#2 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/private\\\/files\\\/view.php(1003): OC\\\\Files\\\\Cache\\\\Shared_Cache->get('')\\n#3 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/private\\\/files\\\/filesystem.php(802): OC\\\\Files\\\\View->getFileInfo('\\\/', true)\\n#4 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/apps\\\/files\\\/ajax\\\/list.php(12): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/')\\n#5 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/usr\\\/local\\\/rms\\\/...')\\n#6 [internal function]: __lambda_func(Array)\\n#7 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/private\\\/route\\\/router.php(252): call_user_func('\\\\x00lambda_327', Array)\\n#8 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/base.php(824): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#9 \\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/index.php(36): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/usr\\\/local\\\/rms\\\/evt\\\/rdrive\\\/releases\\\/core_201507300859_de037a0\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":347}","level":4,"time":"2015-07-30T09:45:31+09:00"}
```

#### Browser log
![capture 2015-07-05 at 16 34 51](https://cloud.githubusercontent.com/assets/11423070/9003224/246b9cfe-37a7-11e5-8dd6-59e431d4316b.png)

From ownCloud 8, `lib/private/files/filesystem.php` is changed and emit exception on line 347. It makes loading top page stop. Now we added `return` before the exception and it looks working well.

**Comment by PVince81** [comment] 2015-07-31 13:47
@blizzz

**Comment by PVince81** [comment] 2015-07-31 13:48
@MorrisJobke is this similar to know issues ?

**Comment by blizzz** [comment] 2015-07-31 22:03
Works as intended.

**Comment by blizzz** [comment] 2015-07-31 22:08
To elaborate: if any user is deleted, the user's owned files are not accessible by others. If the user is still available on LDAP (login may be prohibited), this is also supposed to work. It would rather be an feature request to keep shared files before totally deleting a user (which for external user backend is getting more tricky). Wasn't there even one?

**Comment by tazuke** [comment] 2015-08-03 00:47
If only deleted user's files are not displayed, it is OK. But now login user's (in this exapmle, user "B") own files are not displayed either. Just shown error message "Unknown error". Because ownCloud emit exception during creating home page. Is it intended behavior?

**Comment by MorrisJobke** [comment] 2015-08-03 07:21
Pretty error message:
```
{
	"reqId":"84f00659fb01fcf1df9b3758be729312",
	"remoteAddr":"133.237.7.94",
	"app":"files",
	"message":"
		Exception: {"Message":"","Code":0,"Trace":"#0 apps/files_sharing/lib/cache.php(56): OC\Files\Filesystem::initMountPoints('AD93E318-DE5F-4...')
		#1 apps/files_sharing/lib/cache.php(89): OC\Files\Cache\Shared_Cache->getSourceCache('')
		#2 lib/private/files/view.php(1003): OC\Files\Cache\Shared_Cache->get('')
		#3 lib/private/files/filesystem.php(802): OC\Files\View->getFileInfo('/', true)
		#4 apps/files/ajax/list.php(12): OC\Files\Filesystem::getFileInfo('/')
		#5 lib/private/route/route.php(135) : runtime-created function(1): require_once('/usr/local/rms/...')
		#6 [internal function]: __lambda_func(Array)
		#7 lib/private/route/router.php(252): call_user_func('\x00lambda_327', Array)
		#8 lib/base.php(824): OC\Route\Router->match('/apps/files/aja...')
		#9 index.php(36): OC::handleRequest()
		#10 {main}
	",
	"File":"lib/private/files/filesystem.php",
	"Line":347
}

```

**Comment by blizzz** [comment] 2015-08-03 10:55
@tazuke I tried to reproduce with help of your instructions (giving A and B are two LDAP users). For me it works like expected: A shared to B, B could see everything, then I deleted A, B still could login and see its files.

Could you please upgrade to a recent OC 8 version (8.0.6 will be released tomorrow) and try again?

**Comment by MorrisJobke** [comment] 2015-08-03 11:31
> 8.0.6 will be released tomorrow

I guess this is delayed because no RC is released yet.

**Comment by blizzz** [comment] 2015-08-03 11:38
Oops, I only checked with my calendar.

**Comment by tazuke** [comment] 2015-08-04 01:42
Thank you for trying to reproduce.
From the error log
`#0 apps/files_sharing/lib/cache.php(56): OC\Files\Filesystem::initMountPoints('AD93E318-DE5F-4...')`

`initMountPoints("USER A")` is called when User B opens own home. Is it wrong behavior?
Or, is it wrong that ownCloud can't find A's user object?

**Comment by PVince81** [comment] 2015-10-09 16:25
@tazuke still having issues with 8.0.8 or 8.1.3 ?

**Comment by silk** [comment] 2015-10-29 10:58
I just encountered this issue on 8.2.0

**Comment by blizzz** [comment] 2016-03-01 23:06
Um, still anyone experiences such a behaviour?

**Comment by ssp819** [comment] 2016-04-11 16:18
Owncloud 9.0 -- yes I have the exact error as described by tazuke.

All users are from LDAP. A shared a folder with B. A left the organization and was eventually deleted from the directory server, so does not show up on LDAP anymore. As soon as that happened, B can still log in but gets the error: "The Directory is unavailable. Please check the logs or contact an administrator." The backend shows a fatal error. This does not seem to be expected behaviour. Let the original sharer's files be inaccessible, but don't break the interface for the users he/she shared files with!

Relevant log entries from cron:

{"reqId":"EGTlZjSi7Y6LuPdXetOM","remoteAddr":"","app":"files","message":" Backends provided no user object for fjbrinkman","level":3,"time":"2016-04-11T11:59:08+00:00","method":"--","url":"--"}
{"reqId":"EGTlZjSi7Y6LuPdXetOM","remoteAddr":"","app":"core","message":"Error while running background job (class: OC\\Command\\CommandJob, arguments: O:33:\"OCA\\Files_Trashbin\\Command\\Expire\":1:{s:39:\"\u0000OCA\\Files_Trashbin\\Command\\Expire\u0000user\";s:11:\"dolmacroder\";}): {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for fjbrinkman\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(81): OC\\\\Files\\\\Filesystem::initMountPoints('fjbrinkman')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(570): OC\\\\Files\\\\Storage\\\\Shared->init()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(381): OC\\\\Files\\\\Storage\\\\Shared->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/node.php(81): OC\\\\Files\\\\View->getFileInfo('\\\/dolmacroder\\\/fi...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/node.php(204): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(608): OC\\\\Files\\\\Node\\\\Node->getSize()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(644): OCA\\\\Files_Trashbin\\\\Trashbin::calculateFreeSpace(0, 'dolmacroder')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/command\\\/expire.php(56): OCA\\\\Files_Trashbin\\\\Trashbin::expire('dolmacroder')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/command\\\/commandjob.php(34): OCA\\\\Files_Trashbin\\\\Command\\\\Expire->handle()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\Command\\\\CommandJob->run('O:33:\\\"OCA\\\\\\\\Files...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/queuedjob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 \\\/var\\\/www\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":387}","level":3,"time":"2016-04-11T11:59:08+00:00","method":"--","url":"--"}


Relevant log entries from userB's login attempt:

{"reqId":"jQuyTaQ97IpcxD48veJE","remoteAddr":"119.2.103.47","app":"files","message":" Backends provided no user object for UserA","level":3,"time":"2016-04-11T15:49:05+00:00"}
{"reqId":"jQuyTaQ97IpcxD48veJE","remoteAddr":"119.2.103.47","app":"webdav","message":"Exception: {\"Message\":\"Backends provided no user object for UserA\",\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(81): OC\\\\Files\\\\Filesystem::initMountPoints('UserA')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(570): OC\\\\Files\\\\Storage\\\\Shared->init()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(381): OC\\\\Files\\\\Storage\\\\Shared->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(124): OC\\\\Files\\\\View->getFileInfo('')\\n#5 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php\",\"Line\":387,\"User\":\"UserB\"}","level":4,"time":"2016-04-11T15:49:05+00:00"}

**Comment by PVince81** [comment] 2016-04-18 10:29
@ssp819 can you try with 9.0.1 ? Some issues related to invalid/obsolete shares have been resolved there

**Comment by ssp819** [comment] 2016-04-18 12:27
@PVince81 Thank you for the update - As our server is in production, we will try the 9.0.1 upgrade at an opportune time or set up a separate testing environment.

**Comment by blizzz** [comment] 2016-05-17 12:28
@ssp819 did you upgrade to 9.0.1 meanwhile?

**Comment by PVince81** [comment] 2016-08-15 17:32
Please reopen if the problem still exists in 9.0.4

**Closed by PVince81** 2016-08-15 17:32 UTC
Labels: app:user_ldap, bug, feature:sharing
