### ISSUE TITLE
Adding files to folder symlinked in data folder requires occ files:scan for them to be shown

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#21414] opened 2016-01-01 22:45 UTC
Admittedly this might be a strange use-case, but here we go:
I’m exploring how to best dogfood a local development instance of ownCloud. Essentially I’m trying to replace my local file manager, text editor, music player, video player etc with my local ownCloud install. Hardcore, I know.

Currently the best approach seems to be to symlink a folder (say »Notes«) from my local synced ownCloud folder into the data/user/files folder of my user on the local development instance.

This works well when the permissions are set correctly – `user:www-data` for the folder and files, it seems. It’s just that any file created via the file manager (instead of the local dev instance file adding functionality) will not show up in the local dev instance. It necessitates running the occ files:scan command.

Can we improve this? Like checking for new files on a refresh, or folder open, or log in/out? Not sure if that’s too much of a performance hit, that’s why I said it’s a strange use-case.

**Comment by jancborchardt** [comment] 2016-01-01 23:05
And especially when after deleting a file, this is shown on trying to open it from the web interface:
![capture du 2016-01-02 00-04-29](https://cloud.githubusercontent.com/assets/925062/12072558/6e53dc4e-b0e4-11e5-8390-46f67129f721.png)
ownCloud should automatically rescan, no?

**Comment by RealRancor** [comment] 2016-01-02 12:43
Hi,

you shouldn't manually fiddel around in the datadir as this can cause various issues. Have a look at this FAQ for an alternative:

https://forum.owncloud.org/viewtopic.php?f=17&t=32183

I'm also not quite sure if this is still valid:

https://doc.owncloud.org/server/8.2/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks

If you still want to put stuff manually into the datadir have a look at that config option:

https://github.com/owncloud/core/blob/v8.2.2/config/config.sample.php#L1052-L1066

**Comment by MorrisJobke** [comment] 2016-01-02 21:35
Syncing the data dir was disabled for local folders. The file system is only scanned nowadays if it is an external mount. This use case is also very rare and hard to implement.

If you want to dig into how hard it is to detect changes please read https://github.com/owncloud/core/issues/11797 - I will close this ticket as a duplicate of #11797 

As this is also a very uncommon use case I don't think that this will be implemented. And it will add the performance penalty we just removed successfully months ago.

**Closed by MorrisJobke** 2016-01-02 21:35 UTC
Labels: app:files, clarification request, comp:filesystem, enhancement
