### ISSUE TITLE
Option to encrypt just external storage

### ISSUE THREAD

**Issue by aaschmid** [owncloud/core#13073] opened 2015-01-01 17:31 UTC
As internal storage is already secure, encrypted etc. etc. But to increase performance it would maybe be sensful to just encrypt the additonal external disk storage.

If you like this idea and have some high level concept of implementation, I think about contributing a pull request for it. What do you think?

**Comment by karlitschek** [comment] 2015-01-01 22:03
Yes. This is a planed feature. @schiesbn

**Comment by MorrisJobke** [comment] 2015-01-05 09:09
Duplicate of #10731 - there is also already a discussion about a per folder/external mount option ;)

**Closed by MorrisJobke** 2015-01-05 09:09 UTC
Labels: Enhancement

**Comment by aaschmid** [comment] 2015-01-05 09:52
sorry, haven't found that using github search (maybe due to the big amount of tickets).

**Comment by MorrisJobke** [comment] 2015-01-05 10:13
@aaschmid No problem :) Thanks for reporting this anyway :)
