### ISSUE TITLE
Use of Settings/Admin from Normal User Breaks LDAP Avatar image for Normal User

### ISSUE THREAD

**Issue by johntwillis** [owncloud/core#12633] opened 2014-12-05 07:47 UTC
OC 7.0.3
 # vi /var/www/html/owncloud/apps/user_ldap/lib/user/user.php
 line 210 'change false to true'

 //TODO make interval configurable
                 if((time() - intval($lastChecked)) < 86400 ) {
                         return true;
                 }

monitor the users avatar.jpg file, watch file size 

 # cd /var/www/html/owncloud/data/FAFC4E94-6F8F-434D-9068-C89E355F1D4D
 # watch ls -l
 drwxr-xr-x  5 apache apache 4096 Dec  5 01:28 .
 drwxrwx--- 14 apache apache 4096 Dec  5 00:31 ..
 -rw-r--r--  1 apache apache ***5059*** Dec  5 01:28 ***avatar.jpg***
 drwxr-xr-x  2 apache apache 4096 Dec  1 16:25 cache
 drwxr-xr-x  3 apache apache 4096 Dec  5 00:35 files
 drwxr-xr-x 34 apache apache 4096 Dec  4 16:43 thumbnails

 this normal ldap user is a member of the owncloud local [admin] group
 login as normal ldap user > go to > Settings\Admin page

 drwxr-xr-x  5 apache apache 4096 Dec  5 01:29 .
 drwxrwx--- 14 apache apache 4096 Dec  5 00:31 ..
 -rw-r--r--  1 apache apache    ***0*** Dec  5 01:29 ***avatar.jpg***
 drwxr-xr-x  2 apache apache 4096 Dec  1 16:25 cache
 drwxr-xr-x  3 apache apache 4096 Dec  5 00:35 files
 drwxr-xr-x 34 apache apache 4096 Dec  4 16:43 thumbnails

 NOTE: filesize immediately drops to ***Zero*** < this is the BUG >

 Upon logout and login the ***normal ldap user*** Avatar is a broken image and does not update, it stays broken, unless the following procedure is performed.

 login as the  ***oc admin user*** > go to > Settings\Admin page > logout of ***oc admin user***

 login as the broken ***normal ldap user*** > avatar immediately updates with "correct" LDAP image

 drwxr-xr-x  5 apache apache 4096 Dec  5 01:43 .
 drwxrwx--- 14 apache apache 4096 Dec  5 00:31 ..
 -rw-r--r--  1 apache apache ***5059*** Dec  5 01:43 ***avatar.jpg***
 drwxr-xr-x  2 apache apache 4096 Dec  1 16:25 cache
 drwxr-xr-x  3 apache apache 4096 Dec  5 00:35 files
 drwxr-xr-x 34 apache apache 4096 Dec  4 16:43 thumbnails

if the ***normal ldap user*** with admin privileges uses Settings\Admin page again, the avatar will be zero'd out again and will no longer be updated

**Comment by blizzz** [comment] 2015-03-24 12:57
Interesting finding. The cause might be fixed within stable7 (so not in a released version yet). Would it be possible for you to retry it?

**Comment by johntwillis** [comment] 2015-03-25 01:38
Where we use OC we eventually chose to completely disable the feature (Avatars) and I haven't checked it since that time. I work on a lot of projects and it will take a period of time to get my mind back in that space. If / when I do I'll try to setup a test scenario and recheck it. But I can make no promises of when that will be.

**Comment by blizzz** [comment] 2015-03-25 11:49
@johntwillis Alright. Since I think it likely the root cause was fixed and I am not able to reproduce it, I close it for now. If you find time to test it and be able to reproduce, please feel free to reopen.

On another note, it might also be the following: If a user logs in for the first time, the avatar can be only set after the first interval, because the users directory is not set up at the moment the avatar can be set.

**Closed by blizzz** 2015-03-25 11:49 UTC
Labels: app:user_ldap, bug
