### ISSUE TITLE
Send password to new users

### ISSUE THREAD

**Issue by Glassback** [owncloud/core#22991] opened 2016-03-09 08:39 UTC
Hi guys, 

When creating a new user, I can check the checkbox "Send e-mail". After creating a user, the e-mail containing the connection informations will be sent to the new user.

I'm trying to modify the file _core/settings/templates/email.new_user.php_ to add the password field.

I change

`15. 						
print_unescaped($l->t('Hey there,<br><br>just letting you know that you now have an %s account.<br><br>Your username: %s<br>Access it: <a href="%s">%s</a><br><br>', array($theme->getName(), $_['username'], $_['url'], $_['url'])));`

To

`print_unescaped($l->t('Hey there,<br><br>just letting you know that you now have an %s account.<br><br>Your username: %s<br>Your password: %s<br>Access it: <a href="%s">%s</a><br><br>', array($theme->getName(), $_['username'],$_['password'], $_['url'], $_['url'])));`

When the user receive the e-mail, the password field is blank... can someone help me?

Thanks

**Comment by LukasReschke** [comment] 2016-03-09 08:41
> When the user receive the e-mail, the password field is blank... can someone help me?

You can't do it simply like that. You also need to modify https://github.com/owncloud/core/blob/4d69e562a065a79461343444a842ada025f3643c/settings/controller/userscontroller.php#L383-L387

**Comment by RealRancor** [comment] 2016-03-09 08:47
Shouldn't be development specific stuff asked at the developers mailinglist instead of the bugtracker?

If this is also a feature request its also a duplicate of https://github.com/owncloud/core/issues/17398

**Comment by LukasReschke** [comment] 2016-03-09 08:48
> Shouldn't be development specific stuff asked at the developers mailinglist instead of the bugtracker?

Yes.

> If this is also a feature request its also a duplicate of #17398

Thanks. I thought it was but couldn't find the original issue :see_no_evil:

**Comment by Glassback** [comment] 2016-03-09 08:48
Thanks @LukasReschke for the quick aswer. Problem solved.

@RealRancor It's also a feature request, sory for the duplicate

**Closed** 2016-03-09 08:48 UTC
Labels: enhancement
