### ISSUE TITLE
  [User Management] Extra click is necessary in the deletion of several users in a row

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13562] opened 2015-01-21 15:52 UTC
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Write down user/password.
4. Click create new user.
5. Repeat steps 3 and 4 with another user.
6. Click on the trashbin icon to delete one user
7. Click on the trashbin icon 

### Expected behaviour
Only one click should be necessary

### Actual behaviour

It is necessary a second click to delete the second user created.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

![captura de pantalla 2015-01-21 a las 16 38 58](https://cloud.githubusercontent.com/assets/10596560/5839138/77a907c8-a18c-11e4-8db0-3557a25358f6.png)

**Comment by jancborchardt** [comment] 2015-03-17 17:49
Yeah, this seems to be a bug. @raghunayyar can you have a look at it?

**Comment by jvillafanez** [comment] 2015-04-22 15:25
It's still reproducible in 8.1 alpha 1

I don't think you need to click twice, but wait a bit of time

![screenshot from 2015-04-22 16 58 09](https://cloud.githubusercontent.com/assets/1477829/7278224/529329e4-e914-11e4-9b9e-05c5396a0eae.png)

**Comment by jancborchardt** [comment] 2015-04-22 17:25
@raghunayyar @blizzz can you look into this? Thanks!

**Comment by blizzz** [comment] 2015-04-22 18:51
The first attempt returns forbidden. @LukasReschke ?

**Comment by PVince81** [comment] 2015-09-21 13:51
Any update ?

**Comment by hutchic** [comment] 2015-11-07 00:45
I can't reproduce this on 9.0.0.2

**Comment by raghunayyar** [comment] 2015-11-07 08:13
Jesus, I just noticed I was tagged in this. Will have a look asap.

**Comment by PVince81** [comment] 2016-06-14 08:32
Works properly in 9.1.0 beta2, also no forbidden issue.

Closing.

**Closed by PVince81** 2016-06-14 08:32 UTC
Labels: bug, junior job, settings:users
