### ISSUE TITLE
Notification container doesn't hide properly

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19097] opened 2015-09-16 15:17 UTC
![notification](https://cloud.githubusercontent.com/assets/323220/9909029/abadb3e6-5c96-11e5-9ae6-710a9a06a8e2.png)

After seeing a message about some files being locked, the notification area doesn't completely disappear.

#### Scenario 1

1. Break your system so that you get ghost locked files
2. Upload files with the same name as the ghost ones

#### Scenario 2

1. Upload a lot of files
1. Cancel upload
1. Wait for disco blinking to stop
1. A wild empty bar appears

You may be able to reproduce the issue with a different uploading issue

**Comment by jancborchardt** [comment] 2015-09-16 15:47
@schiesbn @nickvergessen @PVince81 maybe? This is not a design but a JS issue.

**Comment by PVince81** [comment] 2015-09-16 15:50
Weird, this has always worked for me before. Regression ?

**Comment by oparoz** [comment] 2015-09-16 16:00
Seen on both Firefox and Chrome

Message fades down, then re-appears briefly and then is probably flattened out.

**Comment by PVince81** [comment] 2015-09-16 16:05
Works for me on master.

Can be tested by typing this in the JS console:
```
OC.Notification.showTemporary('hello');
```

Does your browser have a different zoom level maybe ?

**Comment by oparoz** [comment] 2015-09-16 16:59
> Can be tested by typing this in the JS console

The first time I ran it, I got the same flashing message and it instantaneously disappeared
The second time it worked as expected

> Does your browser have a different zoom level maybe ?

Just checked as I play with it to make sure @jancborchardt's design is pixel perfect, but no I was already at 0

It must be specific to the upload mechanism.

**Comment by oparoz** [comment] 2015-09-16 17:08
OK, I think I've figure out what's happening.

It happens when you have queued notifications, like when 2 uploads fail in one batch.

First notification is shown and when it fades away, the new one is quickly shown and then the whole thing collapses.

**Comment by PVince81** [comment] 2015-09-17 07:44
Okay, I'll try again with this then. Maybe the notification cancelling isn't working properly or there is a conflict.

**Comment by cmonteroluque** [comment] 2015-10-01 20:08
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by PVince81** [comment] 2015-10-13 08:56
Ok, got it reproduced:

1. Upload a lot of files
1. Cancel upload
1. Wait for disco blinking to stop
1. A wild empty bar appears

**Comment by PVince81** [comment] 2015-10-13 08:59
It's a glitch when trying to hide multiple notifications at the same time, for some reason it stays displayed but is empty.

**Comment by PVince81** [comment] 2015-10-13 09:02
Not worth spending time to fix this glitch.

- First: the notification system itself isn't designed to properly handle several notifications in cascade.
- Second: the upload cancelling will be fixed here https://github.com/owncloud/core/pull/19710 and make this rare happening disappear

**Comment by PVince81** [comment] 2016-04-29 14:45
I think it does now, at least when I last touched it for OC 9.
Please reopen if you still see it in v9.0.1.

**Closed by PVince81** 2016-04-29 14:45 UTC
Labels: bug, sev4-low
