### ISSUE TITLE
LDAP user list not working with 389DS

### ISSUE THREAD

**Issue by alexweirig** [owncloud/core#11292] opened 2014-09-25 09:44 UTC
Unfortunately every new release of OC breaks the LDAP support a little bit more. Now with 7.0.2 I'm no longer able to scroll through the list of the LDAP users.
Previously, at least with OC 6, it was still possible to scroll down the list, even if it was an extremely tedious and painful experience, now with 7.x the list get's stuck after the first 30-40 entries.

If I had a choice I would absolutely prefer a paged list where I have a next/previous page button rather than this (bad UX) scrolling list.

### Steps to reproduce
1. Bind OC 7.0.2 to 389DS
2. Go to users list
3. Scroll down to retrieve next set of users

### Expected behaviour
When I scroll down in the list, I would expect the next set of users to show up.

### Actual behaviour
I see the spinning wheel show up for about a second but I don't get any new users added to the list. I have 780 users in LDAP but only about 30-40 get displayed.

### Server configuration
**Operating system**: RHEL 3.10.0-123.6.3.el7.x86_64

**Web server:** Apache 

**Database:** MySQL

**PHP version:** 5.4.16
 
**ownCloud version:** (see ownCloud admin page) ownCloud 7.0.2 (stable)

**Updated from an older ownCloud or fresh install:** Update

**List of activated apps:** 
Activity
Deleted files
Documents
LDAP user and group backend
ownCloud dependencies info
PDF Viewer
Share files
Text Editor
Updater
Versions

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
<?php
$CONFIG = array (
  'datadirectory' => '/Volumes/OWNCLOUD_DA/ocdata/',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => 'technolink',
  'loglevel' => '0',
  'instanceid' => '509bc38c0058a',
  'maintenance' => false,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_domain' => 'technolink.lu',
  'trusted_domains' =>
  array (
    0 => 'owncloud.technolink.lu',
  ),
  'share_folder' => '/Shared',
);


**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Any

**Operating system:**
OS X 10.9.5

#### ownCloud log (data/owncloud.log)
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"getUsers: Options: search  limit 10 offset 65 Filter: (&(objectclass=kolabInetOrgPerson)(uid=*))","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 65","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/55","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 55","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/45","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 45","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/35","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 35","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/25","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 25","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/15","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 15","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/5","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 5","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Looking for cookie L\/O 10\/0","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=kolabInetOrgPerson)(uid=*)) base Array\n(\n    [0] => ou=People,dc=technolink,dc=lu\n)\n attr Array\n(\n    [0] => cn\n    [1] => dn\n)\n limit 10 offset 0","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 5","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 15","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 25","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 35","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 45","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 55","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"No paged search for us, Cpt., Limit 10 Offset 65","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"getUsers: 10 Users found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"readAttribute: uid=bibliobogel,ou=people,dc=technolink,dc=lu found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"readAttribute: uid=biblioeimue,ou=people,dc=technolink,dc=lu found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"readAttribute: uid=biblioliweb,ou=people,dc=technolink,dc=lu found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"readAttribute: uid=birgitroller,ou=people,dc=technolink,dc=lu found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122177cd4b","app":"user_ldap","message":"readAttribute: uid=birgittemolitor,ou=people,dc=technolink,dc=lu found","level":0,"time":"2014-07-24T15:11:19+00:00","method":"GET","url":"\/index.php\/settings\/ajax\/userlist?offset=65&limit=10&gid=&pattern="}
{"reqId":"53d122184a614","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2014-07-24T15:11:20+00:00","method":"GET","url":"\/index.php\/avatar\/bibliobogel\/32?requesttoken=821c9f1cf51bc704d2ef"}
{"reqId":"53d122185c9fc","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2014-07-24T15:11:20+00:00","method":"GET","url":"\/index.php\/avatar\/biblioeimue\/32?requesttoken=821c9f1cf51bc704d2ef"}
{"reqId":"53d122186e11c","app":"user_ldap","message":"No group filter is specified, LDAP group feature will not be used.","level":1,"time":"2014-07-24T15:11:20+00:
#### Browser log
```

**Comment by averi** [comment] 2015-01-03 17:21
We (at the GNOME Foundation) are experiencing the same issue as reported here, LDAP logins works just fine but the users list does not show LDAP users at all which makes configuring ACLs impossible. 

'Everyone' on the users list correctly shows the amount of local + LDAP users but just the local users are shown on the list. Is there any update on this?

**Comment by karlitschek** [comment] 2015-01-03 17:22
@blizzz What do you think?

**Comment by averi** [comment] 2015-01-03 18:11
Also while this get investigated more deeply it would be interesting to find out how to map LDAP users to OC local groups directly on MySQL, what tables are involved, how the 'owncloud_name' field on oc_ldap_user_mapping maps to locally created groups so that we can ideally add the ACLs manually.

Is oc_group_users used to map LDAP accounts and local groups? seems the answer is a no as I tried to either map LDAP uids (under the uid field) or 'owncloud_name's under the same field with no luck. 

Pointers are very much appreciated.

**Comment by alexweirig** [comment] 2015-02-09 16:36
Hello,

the good news are owncloud 8 is out, the bad news are, still no improvement on user handling in LDAP.

The scrolling still doesn't work ... I wonder how the guys in Germany handle the 300.000 users if the tool can't even work correctly with 800 ??

**Comment by karlitschek** [comment] 2015-02-09 16:52
@blizzz @MorrisJobke What do you think?

**Comment by alexweirig** [comment] 2015-03-12 12:50
Hello,

8.0.2 is out but nothing changed, users management still not working.

Regards,

Alex

**Comment by blizzz** [comment] 2015-03-12 14:57
OK, I set up a 389 server via [docker](https://github.com/jtgasper3/docker-images/tree/master/docker-389-ds) and could reproduce it. Will investigate.

**Comment by alexweirig** [comment] 2015-03-12 14:59
Great !!!

Thank you very much.

Alex

**Comment by blizzz** [comment] 2015-03-12 17:59
Thank you 389ds for always returning an empty cookie :angry:

**Comment by alexweirig** [comment] 2015-03-12 19:41
Hello,

congrats on finding the origin of the problem. Do you think there is a way to work-around this problem?

**Comment by blizzz** [comment] 2015-03-12 21:12
Still debugging, needed to switch tasks inbetween, might be a false positive though.

**Comment by blizzz** [comment] 2015-03-12 21:42
so it's returning a string "0" which empty() considers to be empty. So we need to allow it. Finishing fix :)

**Comment by blizzz** [comment] 2015-03-12 21:58
Please test https://github.com/owncloud/core/pull/14849 :)

@alexweirig also since this issue is open for so long, thank you for not only for bringing it up, but especially for your patience and keeping it rolling!

**Comment by alexweirig** [comment] 2015-03-13 06:51
@blizzz Congratulations, this fixes the problems !!!

The users list is now working.

Thanks a lot

Alex

**Comment by blizzz** [comment] 2015-03-17 13:41
Fixed by https://github.com/owncloud/core/issues/14849

**Closed by blizzz** 2015-03-17 13:41 UTC
Labels: app:user_ldap, bug
