### ISSUE TITLE
OC Client not syncing in time with external storage SMB with OC Login

### ISSUE THREAD

**Issue by aives1291** [owncloud/core#20695] opened 2015-11-24 05:16 UTC
### Steps to reproduce
1. Use owncloud with a „smb share with oc login“ and with „ldap login“ with a M$ Active Directory and on a windows servers 2012R2 Share
2. Change some files with a Windows Client directly on the network drive/filesystem (no OwnCloud)
3. Sync with the own cloud client on mac or windows

### Expected behaviour
The changed data will be synced at least when the following command is used: sudo -u www-data php occ files:scan --all occ files:scan

### Actual behaviour
The data won’t be synced. Sometimes it takes up to 2 days.
It works if you use:
- WebGui instead of Client
- Clear OC Filecache

The command in cron: sudo -u www-data php occ files:scan --all occ files:scan
gives some errors: 
[OCP\Files\StorageNotAvailableException]  
  No session credentials saved  
[OCA\Files_External\Lib\InsufficientDataForMeaningfulAnswerException]  
  No session credentials saved

### Server configuration
**Operating system**: Ubuntu 14.04.3 LTS

**Web server:**
Apache
**Database:**
MySQL 14.14
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
8.2.0.12
**Updated from an older ownCloud or fresh install:**
From OC 7
**List of activated apps:**
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_trashbin: 0.7.0
  - updater: 0.6
  - user_external: 0.4
  - user_ldap: 0.7.0

**The content of config/config.php:**

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** OC Client

**Operating system:** Windows or Mac

### Logs
There is no log which could help except the message of the oc command mentioned above.
#### Web server error log
-

#### ownCloud log (data/owncloud.log)
-

**Comment by RealRancor** [comment] 2015-11-24 06:42
Very likely a duplicate of https://github.com/owncloud/core/issues/11797

**Comment by PVince81** [comment] 2015-11-24 09:23
Yes, duplicate.

A workaround is to setup a cron job that runs `./occ files:scan --all` or `./occ files:scan --path ...` to trigger a full rescan of the remote storage to be able to detect changes deep inside folders.

**Comment by PVince81** [comment] 2015-11-24 09:24
... which might have a performance impact depending on how many folders need to be rescanned every time.

**Comment by PVince81** [comment] 2015-11-24 09:25
Ok, I see you tried it out but got
```
The command in cron: sudo -u www-data php occ files:scan --all occ files:scan
gives some errors:
[OCP\Files\StorageNotAvailableException]
```

Reopening to investigate.

**Comment by PVince81** [comment] 2015-11-24 09:26
The errors looks like you might have SMB mounts that were improperly configured.
Can you check your `oc_storages` table to see if only the configured ones are present ?

@icewind1991 @Xenopathic does occ files:scan skip unavailable storages ?

**Comment by Xenopathic** [comment] 2015-11-24 14:53
`./occ fies:scan` will not work in this case since the OP is using SMB with session credentials, so the data is only available when the user is logged in. That doesn't explain the `StorageNotAvailableException` issue though.

**Comment by aives1291** [comment] 2015-11-24 16:39
Thanks for all answers and investigations.
@Xenopathic session credentials are the thing what I thought as well. But when the owncloud client open a connection it should be like a logged in user and it should work... am I right? So I should see some folders which work cause of logged in user and some where I get the error.

TheStorageNotAvailableException I think i have a idea. I'll test that and have a look to oc_storages.

@PVince81 I'm intrested in your question as well: does occ files:scan skip unavailable storages ?

**Comment by icewind1991** [comment] 2015-11-27 13:03
> I'm intrested in your question as well: does occ files:scan skip unavailable storages ?

It does now #20789

**Closed** 2016-03-07 19:00 UTC
Labels: app:files_external, bug
