### ISSUE TITLE
[6.0.4] Plays video streaming without video viewer or additional apps

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#9878] opened 2014-07-24 19:16 UTC
### Expected behavior 
Users has to be forced to download the video over the share link

### Actual behavior
Users steams video direct from ownCloud.

### Steps to reproduce:
1.Install only the ownCloud core, without the video features.
2. upload a video
3. share video with link
4. use the link in the browser and the video start to be played directly.

### version
ownCloud 6.0.4 only core

**Comment by cdamken** [comment] 2015-02-04 10:53
@MTRichards That will help to the network performance. can we put it in some milestone?

**Comment by MTRichards** [comment] 2015-02-04 12:20
Is this in the browser? Dopes the video viewer solve this problem if it is supported? Otherwise, no - not possible to put it in a milestone.

**Comment by cdamken** [comment] 2015-03-12 12:56
@MTRichards  The request is that the download box appears, but the video preview not:
![video](https://cloud.githubusercontent.com/assets/7264495/6618014/22667dea-c8bf-11e4-8395-cf99a448cec9.png)

Even if the video can't be previewed, the box (where the video should be shown) appears:
![no video](https://cloud.githubusercontent.com/assets/7264495/6618034/469cbad0-c8bf-11e4-915a-71222c19e81c.png)

Sharing without preview is what is needed.

BTW: the "video viewer" app is disabled! and even the video preview is shown

**Comment by DeepDiver1975** [comment] 2015-03-12 14:09
> Sharing without preview is what is needed.

quick fix might be to use a theme which uses a different template for sharing.

**Comment by DeepDiver1975** [comment] 2015-03-12 14:11
Basically copy this file to the theme - https://github.com/owncloud/core/blob/stable6/apps/files_sharing/templates/public.php and remove these lines https://github.com/owncloud/core/blob/stable6/apps/files_sharing/templates/public.php#L39-L43

**Comment by cdamken** [comment] 2015-05-12 14:26
Removing the lines provided by @DeepDiver1975 works, but the point here is another: If I set the video-preview to false, I don't want to do something manually to disable the video preview function. I hope the engineers will understand this logic point and fix this error in the code.

**Comment by cdamken** [comment] 2015-05-18 13:49
@MTRichards When will be this feature request done?

**Comment by MTRichards** [comment] 2015-05-20 07:58
To be honest, if video viewer is disabled, it should not show up.and force the video stream. 
Perhaps I missed something, but this is non-intuitive, and a bug in my book.
@DeepDiver1975 what am I missing? (not worrying about timelines - just verifying)

**Comment by cdamken** [comment] 2015-05-26 08:28
@MTRichards The fix from @DeepDiver1975 https://github.com/owncloud/core/issues/9878#issuecomment-78486280 is a workaround and should be manually made in every upgrade.

The solution is if the video streamer is disabled, then the stream should not appear.

**Comment by MTRichards** [comment] 2015-05-26 14:02
@cdamken 
>The solution is if the video streamer is disabled, then the stream should not appear.

I agree!
It still think this is a bug. How can an app that is disabled still trigger a video preview?

All I can do is say *maybe* we can do something in 8.2, if this is a feature. 8.2 is really busy though.
If a bug, we can look at a sooner release. 

What version is this affecting?

**Comment by cdamken** [comment] 2015-05-27 12:26
@MTRichards Now is affecting the 6.0.6 , we are trying to upgrade to 7.0.6 when it comes out.

**Comment by MTRichards** [comment] 2015-06-05 21:54
7.0.6 is nearly here. @DeepDiver1975 @LukasReschke is this fixed in 7.0.6?

If not, we may have to slide it into consideration for 8.2 I guess. I still don't understand how it is not a bug...

**Comment by LukasReschke** [comment] 2015-06-05 22:10
No.

Because this is a totally different feature that is unrelated to previews or the files_videoviewer app. This is not a preview but the actual video file served via the HTML5 <video> tag - Cluttering the public sharing file with yet another switch will only make things worse in term of maintainability. From my PoV the complete sharing code needs an overhaul.

That said, ugly hacks are always possible but if issues actually have assigned the milestone backlog then it doesn't help to get things moved ;-) - It is not the technical changes that are required which make me feel unhappy but the fact that we add even more to the public sharing magic code that nobody is going to test properly :see_no_evil: 

Note however that we provided a workaround for the issue.

**Comment by MTRichards** [comment] 2015-06-05 22:13
Ok, then I will consider it a feature (well, a fug) and track it accordingly.
Workaround above, and then we will see if we can get something ... but it will be a long while, as this may not make 8.2.

**Comment by MTRichards** [comment] 2015-06-08 22:42
@DeepDiver1975 What would it take to get this into 8.0.5 or 6? Can that be done?

**Comment by MorrisJobke** [comment] 2015-06-09 14:36
Okay guys: Here is the 1.5 line fix: #16840

**Closed** 2015-06-09 20:32 UTC
Labels: 3 - To Review, blue-ticket, enhancement
