### ISSUE TITLE
Feature Request - E-Mail with shared link should include set password

### ISSUE THREAD

**Issue by Froster** [owncloud/core#15509] opened 2015-04-09 11:49 UTC
Hello,

if i share a file with someone else by sending an email within the share context menu, there should be an option that could be set to send the given password in the e-Mail. 

Actually i must send a second mail by myself containing the Password.

share context Menu
- if password is set
- option checkbox should appear
- variable available in the email template ##email##

kindly
chris

**Comment by nickvergessen** [comment] 2015-04-09 13:11
While this is a nice idea and I understand the usecase, it is not possible once you closed the share dropdown/page. Because we only store a one-way hash in the database so we can't get the plain text version of the password later again, right? @LukasReschke

**Comment by LukasReschke** [comment] 2015-04-09 13:12
That is correct, we could address this with a proper sharing dialog as pointed out at https://github.com/owncloud/core/issues/3224. Then we know before hashing the password that we have to mail it and can mail it :-)

**Comment by karlitschek** [comment] 2015-04-09 13:13
I´m also not sure why someone would use this. Isn´t it the point of the password to give someone the link and the password via different channels? Is you put both in one email then why set a password in the first place?
Maybe I´m missing something here.

**Comment by tflidd** [comment] 2015-04-09 13:46
@Froster If the sharing token is random enough (=it can't be guessed), an additional password sent by mail will not provide more security.

**Comment by Froster** [comment] 2015-04-09 14:25
@karlitschek  , it's nothing about security it's only about usibility and a user getting an email with shared content would ever need to save his password next to the link so this couldn't be an argument. But access from browser history would be prohibitet and the user should think more about resend the mail to others

@tflidd  so the hole password context is sensless ? i don't think so. If a download is protected by password and you prohibit the user to give this pass to other users it is very usefull. And as i said before i never wrote about security

**Comment by tflidd** [comment] 2015-04-09 15:47
@Froster : Using a sharing password only makes sense if you use different communication channels for password and link.
Just treat the sharing link like a password. You can as well prohibit users to give the link to others: Without sharing link, you can't download anything. If you are afraid that someone intercepts the mail (with your link), a password only helps if you don't send it per mail as well.

**Comment by Froster** [comment] 2015-04-09 16:05
@tflidd maybe you start a thread withyourself to discuss it for your self with you own theories and you can come to a conclusion with you self , but this thread started by myself was never opened to discuss the sense of passwords and sharing links neither than discuss security by it self but only to request a feature.

**Comment by tflidd** [comment] 2015-04-09 16:37
@Froster : You are requesting a new feature. I just wanted to point out why it does not make sense in my opinion. But there are of course different opinions and you can bring up yours. Probably I didn't get your point. Actually these are not even my own stupid theories, Lukas already brought them up (perhaps more understandable: https://github.com/owncloud/core/issues/11682#issuecomment-59892537 in addition to the thread Lukas mentioned above). 

Duplicate of https://github.com/owncloud/core/issues/11682 ?

**Comment by LukasReschke** [comment] 2015-04-09 16:39
Yup. Duplicate… I wondered the whole time if there wasn't already an issue but couldn't remember who opened it :)

**Closed by LukasReschke** 2015-04-09 16:39 UTC
Labels: Enhancement, sharing

**Comment by Froster** [comment] 2015-04-09 16:57
@tflidd  don't ever said stupid *ty
