### ISSUE TITLE
Undefined variable on view.php

### ISSUE THREAD

**Issue by dpauso** [owncloud/core#18119] opened 2015-08-07 11:18 UTC
### Steps to reproduce
Normal usage of owncloud

### Expected behaviour
running with no error messages

### Actual behaviour
OC is working (about 70 Users with Desktop Clients), but the the log of OC 8.1 is running full with errors since i upgraded from oc 8 to 8.1.
then i made a fresh install, but the error is still there. 

the only app is user_sql app, which i used sind oc 7 an is heavily based on user_imap, user_ldap, user_pwauth and user_redmine. 

### Server configuration
GNU/Linux 2.6.18-prep-xenU-static-i686-he+1

**Web server:**
Apache/2.2.16 (Debian)

**Database:**
mySQL 5.5.44-37.3

**PHP version:**
5.5 stable

**ownCloud version:** 
8.1

**Updated from an older ownCloud or fresh install:**
Update frist, then fresh (=same problem)

**List of activated apps:**

```
Activity  2.0.1
Deleted files  0.6.3
File Locking  
First Run Wizard  1.1
Mail Template Editor  0.1
Provisioning API  0.2
Share Files  0.6.2
Updater  0.6

Experimentell:
SQL user backend  2.0
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxxx.de',
  ),
  'datadirectory' => '/data',
  'overwrite.cli.url' => 'http://xxxx.de',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logdateformat' => 'j. F Y @ G:i.s',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'loglevel' => 2,
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'xxxx.de',
  'appstore.experimental.enabled' => true,
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes => user_sql 2.0 (for OC 8.1)
sync username, passwort from joomla 2.5.28 
(used since OC 7)


### Client configuration
Chrome 44, MS Edge, ...

**Operating system:**
Windows 7, 8.1 and 10
### Logs
#### Web server error log
```
Insert your webserver log here
Error	PHP	Undefined variable: content at /lib/private/files/view.php#1357	7. August 2015 @ 12:52.02
Error	PHP	Undefined variable: content at /lib/private/files/view.php#1357	7. August 2015 @ 12:51.59
Error	PHP	Undefined variable: content at /lib/private/files/view.php#1357	7. August 2015 @ 12:51.57

#### ownCloud log (data/owncloud.log)
```
{"reqId":"tRDF6sKOpOo1Q+AUaRQW","remoteAddr":"178.202.x.x","app":"PHP","message":"Array to string conversion at \/lib\/private\/template\/functions.php#36","level":3,"time":"7. August 2015 @ 12:51.45"}
{"reqId":"lH2faBYGpHdekDzINETC","remoteAddr":"93.214.x.x","app":"PHP","message":"Undefined variable: content at \/is\/htdocs\/wp1150066_SDSEG0OCN1\/www\/cloud\/lib\/private\/files\/view.php#1357","level":3,"time":"7. August 2015 @ 12:51.57"}
{"reqId":"KkYR8stHXI2CYCcxIl+J","remoteAddr":"93.129.x.x","app":"PHP","message":"Undefined variable: content at \/lib\/private\/files\/view.php#1357","level":3,"time":"7. August 2015 @ 12:51.59"}
{"reqId":"VhpsA+7RQ2panclEx8wn","remoteAddr":"80.136.145.8","app":"PHP","message":"Undefined variable: content at \/lib\/private\/files\/view.php#1357","level":3,"time":"7. August 2015 @ 12:52.02"}
{"reqId":"u3VTHzoFTdHFxM0pq6Hm","remoteAddr":"178.202.x.x","app":"PHP","message":"Array to string conversion at \/lib\/private\/template\/functions.php#36","level":3,"time":"7. August 2015 @ 12:52.07"}

```

#### Browser log

**Comment by PVince81** [comment] 2015-08-07 13:20
Ah yes, this one.
Duplicate of https://github.com/owncloud/core/issues/13306

**Closed by PVince81** 2015-08-07 13:20 UTC
