### ISSUE TITLE
Changes on external storage SMB get not synced to owncloud client

### ISSUE THREAD

**Issue by fhdummy** [owncloud/core#20499] opened 2015-11-13 17:03 UTC
### Steps to reproduce
1. Add an external SMB storage with existing data to your owncloud server.
2. Download owncloud client and make an initial synchronization of the external storage.
3. Delete a file directly on the SMB storage.
4. Observe the client.

### Expected behaviour
When a file directly on the external SMB storage gets deleted, it should be synchronized to the web interface of the owncloud server. Furthermore it should be synchronized to the owncloud client of the specific user. All this should happen from my point of view in less than 5 minutes.

### Actual behaviour
The change gets synchronized immediately to the web interface of the owncloud server but NOT to the owncloud client. 
It only gets synchronized to the owncloud client after initiating an 'occ files:scan --all' on the owncloud server, which is not the preferred method as it takes very long for many users (it took me 17 minutes for 1 user).

### Server configuration
**Operating system**: Ubuntu 14.04 (Kernel 3.19.0-33-generic)

**Web server:** Apache/2.4.7

**Database:** Mysql 5.5

**PHP version:** PHP 5.5.9-1ubuntu4.14 (cli)

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc3d48wyno6x',
  'trusted_domains' =>
  array (
    0 => 'some_public_ip',
    1 => 'localhost',
    2 => 'some_domain'
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'some_domain',
  'dbtype' => 'mysql',
  'version' => '8.2.0.12',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_stefan',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
);
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 46 64-bit

**Operating system:** Windows 7 64-bit

### Logs

Please contact me if you need further log information because I currently don't know which information is needed and I can't post all of the logs, would be a bit confusing.

Thanks very much in advance.

**Comment by Xenopathic** [comment] 2015-11-13 21:33
Duplicate of #11797

**Closed by Xenopathic** 2015-11-13 21:33 UTC
