### ISSUE TITLE
amount of files does not match in shared link

### ISSUE THREAD

**Issue by criegerde** [owncloud/core#20388] opened 2015-11-09 09:25 UTC
I am running owncloud 8.2 based on php 5.6.13, mysql 5.6.24 and apache 2.x on Linux 3.13.0-67-generic #110-Ubuntu hosted by all-inkl.com / business tarif.

The issue: 
i share a folder containing 27 files. 
![01](https://cloud.githubusercontent.com/assets/12971682/11030090/fce1b4b0-86cb-11e5-9e07-e0592e618672.PNG)
when opening the link sent by the share dialog, only 20 files appear in the browser (even after refresh F5 or STRG+R). 
![02](https://cloud.githubusercontent.com/assets/12971682/11030137/4cb4c3e2-86cc-11e5-8cf9-c575eb2ce583.PNG)
if i select "Herunterladen/Download" all 27 files were zipped.
Very confusing. Is this a known issue?

...:::Cheers - Carsten

**Comment by criegerde** [comment] 2015-11-09 09:32
In Firefox only 20 files and in IE11 only 16 files are shown in the browser.
press "select all" will download "27 files"

**Comment by RealRancor** [comment] 2015-11-09 09:47
@criegerde Thats a duplicate of https://github.com/owncloud/core/issues/19886 which gets fixed with oC 8.2.1

**Closed** 2015-11-09 09:47 UTC
Labels: duplicate
