### ISSUE TITLE
Owncloud external storage doesn't provide access to Shared folders/files

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#16115] opened 2015-05-06 10:33 UTC
### Steps to reproduce
User One shares files/folders with user Two on server One (not link sharing). User Two creates external storage to server One (external storage created on server Eleven).

### Expected behaviour
User Two can access his/her files and also files/folders shared to him/her over external storage.

### Actual behaviour
Shared files/folders are not accessible.

### Server configuration
**Operating system**:
Debian 7.8

**Web server:**
NGINX (1.2.1-2.2)

**Database:**
MySQL (5.5.43-0)

**PHP version:**
PHP (5.4.4-14)

**ownCloud version:**
ownCloud 8.0.2-8 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Activity, Deleted files, External storage support, First Run Wizard, LDAP user and group backend, Mail Template Editor, PDF Viewer, Pictures, Server-side Encryption, Share Files, Text Editor, Versions, Video Viewer

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'instanceid',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '11.11.11.4',
    1 => 'my.owncloud',
  ),
  'datadirectory' => '/var/ownclouddata/',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'prefix',
  'dbuser' => 'dbuser',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'loglevel' => '0',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtphost',
  'mail_smtpport' => '25',
  'logtimezone' => 'Europe',
  'theme' => '',
  'share_folder' => '/Shared',
  'maintenance' => false,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'secret' => '',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
owncloud

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
AD

#### LDAP configuration (delete this part if not used)

```
|appid|configkey|configvalue|
|user_ldap|cleanUpJobOffset|600|
|user_ldap|enabled|yes|
|user_ldap|has_memberof_filter_support|1|
|user_ldap|home_folder_naming_rule||
|user_ldap|installed_version|0.5.0|
|user_ldap|last_jpegPhoto_lookup|0|
|user_ldap|ldap_agent_password||
|user_ldap|ldap_attributes_for_group_search||
|user_ldap|ldap_attributes_for_user_search||
|user_ldap|ldap_backup_host||
|user_ldap|ldap_backup_port||
|user_ldap|ldap_base|DC=example,DC=local|
|user_ldap|ldap_base_groups|DC=example,DC=local|
|user_ldap|ldap_base_users|DC=example,DC=local|
|user_ldap|ldap_cache_ttl|600|
|user_ldap|ldap_configuration_active|1|
|user_ldap|ldap_display_name|displayname|
|user_ldap|ldap_dn|CN=Comp-Ownc,OU=COM,OU=Company,DC=example,DC=local|
|user_ldap|ldap_email_attr|mail|
|user_ldap|ldap_experienced_admin|0|
|user_ldap|ldap_expert_username_attr|sAMAccountName|
|user_ldap|ldap_expert_uuid_group_attr||
|user_ldap|ldap_expert_uuid_user_attr||
|user_ldap|ldap_group_display_name|cn|
|user_ldap|ldap_group_filter|(&(|(objectclass=group))(|(cn=Dev)(CN=Comp-Ownc)(cn=Comp-admis)))|
|user_ldap|ldap_group_filter_mode|0|
|user_ldap|ldap_group_member_assoc_attribute|member|
|user_ldap|ldap_groupfilter_groups|Comp-DevComp-Owncloud Comp-admis|
|user_ldap|ldap_groupfilter_objectclass|group|
|user_ldap|ldap_host|dc300|
|user_ldap|ldap_login_filter|(&(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-admis,OU=DL,OU=Company,DC=example,DC=local)))(samaccountname=%uid))|
|user_ldap|ldap_login_filter_mode|0|
|user_ldap|ldap_loginfilter_attributes||
|user_ldap|ldap_loginfilter_email|0|
|user_ldap|ldap_loginfilter_username|1|
|user_ldap|ldap_nested_groups|0|
|user_ldap|ldap_nocase|1|
|user_ldap|ldap_override_main_server|0|
|user_ldap|ldap_paging_size|500|
|user_ldap|ldap_port|389|
|user_ldap|ldap_quota_attr||
|user_ldap|ldap_quota_def||
|user_ldap|ldap_tls|0|
|user_ldap|ldap_turn_off_cert_check|1|
|user_ldap|ldap_user_filter_mode|1|
|user_ldap|ldap_userfilter_groups||
|user_ldap|ldap_userfilter_objectclass||
|user_ldap|ldap_userlist_filter|(&(|(objectclass=person))(|(memberof=CN=Comp-Ownc,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-Dev,OU=DL,OU=Company,DC=example,DC=local)(memberof=CN=Comp-SystemAdministrators,OU=DL,OU=Company,DC=example,DC=local)))|
|user_ldap|ocsid|166061|
|user_ldap|types|authentication|

```

### Client configuration
**Browser:**
Any (chrome, ff, opera)

**Operating system:**
Ubuntu 14.04 LTS

#### ownCloud log (data/owncloud.log)
No logs

**Comment by PVince81** [comment] 2016-03-01 17:45
Sorry I missed this report.

> User Two creates external storage to server One (external storage created on server Eleven).

Can you elaborate ? Best would be to express the steps with examples.
How is the external storage related to the share ?

Possibly a duplicate of https://github.com/owncloud/core/pull/20953, but depends whether your scenario matches

**Comment by PVince81** [comment] 2016-05-30 15:22
Closing due to lack of feedback.

I'll assume that you meant this use case: https://github.com/owncloud/core/issues/20990

**Closed by PVince81** 2016-05-30 15:22 UTC
Labels: enhancement, needs info
