### ISSUE TITLE
Updated to 9.0.1 via updater; problems with code integrity check

### ISSUE THREAD

**Issue by mikebabb** [owncloud/core#23965] opened 2016-04-13 09:05 UTC
### Steps to reproduce
1. Update to ownCloud 9.0.1 stable from 9.0 stable via the admin panel

### Expected behaviour
Successful update, no errors

### Actual behaviour
Update to 9.0.1 is successful, but integrity check fails and error message is displayed in admin panel

### Server configuration
**Operating system**: Ubuntu 12.04

**Web server:** Apache

**Database:** mysql

**PHP version:** Unknown

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** Updated from 9.0

**Where did you install ownCloud from:** Admin panel updater

**Signing status (ownCloud 9.0 and above):** Failed

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/composer.json
		- 3rdparty/composer.lock
		- 3rdparty/composer/autoload_classmap.php
		- 3rdparty/composer/installed.json
		- 3rdparty/sabre/dav/CHANGELOG.md
		- 3rdparty/sabre/dav/lib/CardDAV/Backend/PDO.php
		- 3rdparty/sabre/dav/lib/DAV/CorePlugin.php
		- 3rdparty/sabre/dav/lib/DAV/Version.php
	- FILE_MISSING
		- 3rdparty/icewind/streams/src/DirectoryFilter.php
		- 3rdparty/icewind/streams/src/DirectoryWrapper.php
		- 3rdparty/icewind/streams/src/RetryWrapper.php
		- 3rdparty/icewind/streams/src/SeekableWrapper.php
	- EXTRA_FILE
		- updater/update.log

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/composer.json] => Array
                        (
                            [expected] => a6a9174f672638566a53d43a82503872795c536fbc5e4562a9a43028542c33ecb2419749a393132d00f9518f0cb0c82cc81383073d697acb615026211e0d3293
                            [current] => 534affabb50793a7efe6648b4e2c441a58d0ef7c9e995889038c2932a10f82f89d6ec75ef8d14517311831a5510e037e0001c39eedd0662725cc522be378f3a3
                        )

                    [3rdparty/composer.lock] => Array
                        (
                            [expected] => 8e82a37d2aa9b511306d51f2782c0b03f9bdc1ebd31856e576932d73cd8b9fe49b2c787a02a7ae122992c60a23dfad0e744c116b1db5622041f2498852677b4f
                            [current] => 4fd71780a32f1451a3c483698fdbde5ad488afba526af8d3e59ef3bb403242aeaf5c349fcb5efc29746297d10e5670233800243744d0e204dd6ac542d63a20f0
                        )

                    [3rdparty/composer/autoload_classmap.php] => Array
                        (
                            [expected] => 4de95285a99044d62773dca1f7014a647ed8c6e08cfa587d1c8b865f49e9df776aa02c2d3b80939daf0eb0f497121757c499667938de17bbb2deb1c03f0090f0
                            [current] => ac7fecbc8051472797b734d3f97c6671357f3a5d9a48a01de8cba7e93e58a69e89f7aaf88b7c8ba3ff12faece759e7db9ad0a16b2501af8c1ecd0f384a7f2e36
                        )

                    [3rdparty/composer/installed.json] => Array
                        (
                            [expected] => 043dd72279d7bf65b8cf755620f4db22500a5c826ad770ce18d08bfd1fe961f72550f6d73fae38c0f6c37a69553ba223316ff1b8ac798809decf212d85afb056
                            [current] => 7ebafd711756744930933b1812bc505dfa656fa403669d37cdd9baa5db8da6e4cd4e21964832eff54000bdc3ac554d6ba7603e82f66db59493bf8e76143509b3
                        )

                    [3rdparty/sabre/dav/CHANGELOG.md] => Array
                        (
                            [expected] => 1680660bf8eeba002066fa0299dd99b85052d8d5d78fe5549539160e8c71cac5e69e304232c8be824ae5a3484b7f4ec1a6e5ea39b8c4a5954d153bd94d5158ff
                            [current] => ea148ccd8e4216a2b28a857d77c4dbc57051ac1e920b202a26924a3d702e0ac5c4eb45e2848af48a4c77f3952a26e71c1efa0d3a2e880af2f472c88bd4d138bb
                        )

                    [3rdparty/sabre/dav/lib/CardDAV/Backend/PDO.php] => Array
                        (
                            [expected] => a38c07bdb0922b2621ac72e09c3cb29455acc0d11a832cd5c0bbbafad49bf7dc1f8fc067342d36c4317d6910155beb9deb0cca6f1d8ca89d67d85aebe47f0587
                            [current] => 25c9bedc627958fde15657ddc8654f7148d2d4f35d5f62aad6b4636c1cce1dec1ed33360474da4abffb39c0c6ab280dbf95f91da2328c0dc0f4126ae5d98a6e2
                        )

                    [3rdparty/sabre/dav/lib/DAV/CorePlugin.php] => Array
                        (
                            [expected] => 721190b942a2510b363983d37c7e302e837f75f70213716b9e76bb6ea50203d6fce45147431a8f61ea7e290f8b5a11aaa8c1726fdaa2a5157d262e32bfc2fbd3
                            [current] => e882caac3ad5d53a0ec0b9988cf225ec0a88585c758db344e7f69ef39e80e81b7026026468bd5626abb9d788e5e07b37550bb673bb0e891b1511053115d91064
                        )

                    [3rdparty/sabre/dav/lib/DAV/Version.php] => Array
                        (
                            [expected] => 753a49f006305bb42c811aab2a8ea2fdd4d97e4697065e76781fdb632001b9f3776ba9223baa2fbf9cf2ad52ca00972f8ff97d1aaa8d9d894629e10dff61a617
                            [current] => ccf4f9e85f9e4e16246a1951a992405b866aee2dfd21ec9c1462878759724176d3c396d399d6c462d0594d91611bd8660eecc876e72a9f2a8665cc4de6024d28
                        )

                )

            [FILE_MISSING] => Array
                (
                    [3rdparty/icewind/streams/src/DirectoryFilter.php] => Array
                        (
                            [expected] => 6d927bc6597a91de70dee7e488c7530ce331d7a18ca68559cfb0e036006063b22559694c83200f7335e5b166fb83487bd85a6a44121f45792f3a15da26bb376f
                            [current] => 
                        )

                    [3rdparty/icewind/streams/src/DirectoryWrapper.php] => Array
                        (
                            [expected] => fab56240b611a22d8530da0179b0b563c0e24ccee636022d30ec68558fb029812012bf0e29d0b14783f81083fbbffa59766614bec01288808fbf18ee0f261bc9
                            [current] => 
                        )

                    [3rdparty/icewind/streams/src/RetryWrapper.php] => Array
                        (
                            [expected] => 8c7c2b905d97a300234db0d7e4ddb70afa9ea1b40e0997445a040394e5ad8d32f8f665006ce6d667fbd54a70ce8bc06d25dcfb4ee0d7ea5629fa69efd4e8f3e8
                            [current] => 
                        )

                    [3rdparty/icewind/streams/src/SeekableWrapper.php] => Array
                        (
                            [expected] => aebbf573646de8e3da93929c720e2158bf3e906118a8b291671b37c256bb691eef7ee11f11014d98a939d7d1e19708a32f2f2a847543cd2b77f34b192e32898c
                            [current] => 
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [updater/update.log] => Array
                        (
                            [expected] => 
                            [current] => 54df53ba3060360d099e7f39aedb4a85258b667f55f5f5419b82aa41cf2b5be67dbe103dd66ec54eeaea78bc530b7a29da8022f3cfd9bab5e41cdceb2715a684
                        )

                )

        )

)
```

**List of activated apps:**

- ownNote 1.07

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 49.0.2623.112

**Operating system:** Ubuntu 14.04

**Comment by nickvergessen** [comment] 2016-04-13 09:26
Duplicate of https://github.com/owncloud/core/issues/23857

**Closed by nickvergessen** 2016-04-13 09:26 UTC
