### ISSUE TITLE
Upgrade to 8.0.3 fails from 8.0.2 (debian 7)

### ISSUE THREAD

**Issue by ewook** [owncloud/core#16384] opened 2015-05-17 14:19 UTC
Error message:

An exception occurred while executing 'ALTER TABLE oc_contacts_cards ENGINE=InnoDB;': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT'

version.php:
<?php
$OC_Version = array(8,0,3,4);
$OC_VersionString = '8.0.3';
$OC_Channel = 'stable';
$OC_Build = '2015-04-23T19:59:50+00:00 3f2069bd66669414d529cbdf2208635f27c85288';

**Comment by RealRancor** [comment] 2015-05-17 18:00
Hi,

Hi,

Duplicate of: https://github.com/owncloud/core/issues/16008 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097 , https://github.com/owncloud/core/issues/16157 , https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218 , https://github.com/owncloud/core/issues/16280, https://github.com/owncloud/core/issues/16381

Documentation for this is also available here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

**Comment by MorrisJobke** [comment] 2015-05-18 07:32
Possible solution: https://github.com/owncloud/core/issues/16008#issuecomment-98889298

**Closed by MorrisJobke** 2015-05-18 07:32 UTC
Labels: duplicate
