### ISSUE TITLE
Failing to share encrypted files

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#12413] opened 2014-11-25 11:24 UTC
I've create a user on owncload 7.0.3 (running on centos 7)
encryption is activated on this server.
Sync it's local folder (about 7.1 GB of data)
Create another user, Shared the first user's files with the 2nd user. 
IN the process of sharing I see it takes a lot of time to set it up.
I'm not sure it ends correctly. MAX_EXECUTION_TIME on the server is 30000

Anyway - After that I try to sync the files to the 2nd user's computer - and they all downloaded at 0 size (opened a bug on the client folder).
I've tried to open a file from the web interface and I got this:
Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.	

Tried with a 3rd user and got the same results.

**Comment by PVince81** [comment] 2015-07-31 15:30
@schiesbn I guess with encryption 2.0 it might still take as much time ?
We probably need a bkg job for sharing.

**Comment by PVince81** [comment] 2015-10-08 12:41
Closing as duplicate of https://github.com/owncloud/core/issues/18145

**Closed by PVince81** 2015-10-08 12:41 UTC
Labels: app:files_encryption, bug, sharing
