### ISSUE TITLE
Public link page conflict dialog preview broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17618] opened 2015-07-13 16:01 UTC
### Steps

1. Share folder "test" with public link and allow editing
1. Open public link
1. Upload a picture "test.jpg"
1. Upload the same picture again "test.jpg"

### Expected result
Conflict dialog appears, previews both render

### Actual result
Conflict dialog appears, but the previews are blank.
The preview URL seems to be missing the share token:
`http://localhost/owncloud/index.php/core/preview.png?file=%2F%2Ftest.jpg&x=96&y=96&c=dd80e088d5e87aa5eb29b802a23df093&forceIcon=0`

### Versions
Broken on stable8.1, master.
Stable8 is fine.

So this is a regression from stable8.

@georgehrke @oparoz

**Comment by oparoz** [comment] 2015-07-13 16:36
Confirmed.
It's not a token issue afaics
I get nothing in the logs, so it seems the system really can't find the file. Probably a virtual root issue.

**Comment by oparoz** [comment] 2015-07-13 16:37
Ah, no, the method is using the wrong endpoint. It should be using publicpreview.png

**Comment by oparoz** [comment] 2015-07-13 16:39
And I'm responsible! https://github.com/owncloud/core/commit/4e364311f1a07e2359eff2a4412ac90140059076

**Comment by oparoz** [comment] 2015-07-13 16:52
Not sure how to fix this since this happens in a lib. It doesn't make sense to introduce a check for public vs private URLs there.

The alternative is to introduce a method in files and to duplicate it in files_sharing.
That doesn't sound ideal either, but that's how things are done currently.

**Comment by PVince81** [comment] 2015-07-13 16:59
Ah yes, the lazyLoadPreview was barbarically overriden in public.js the way you said.

Maybe we can add preview URL loading to the future "OC.Files.Client" (#16902) and pass the correct preview URL to its constructor. Then make the conflict dialog use the client. Well, we'd need to inject the client at some point anyway.

**Comment by oparoz** [comment] 2015-07-13 20:44
OC.Files.Client is probably fine for 8.2, but what about 8.1 then?

**Comment by PVince81** [comment] 2015-07-14 05:16
Bring back the horrible hack ? :see_no_evil:

**Comment by oparoz** [comment] 2015-07-14 11:14
You mean creating a duplicated method, just for the stable8.1 branch?

**Comment by DeepDiver1975** [comment] 2015-07-17 10:21
> You mean creating a duplicated method, just for the stable8.1 branch?

sounds reasonable to me - @oparoz can I ask you to submit a PR? THX a lot!

**Comment by oparoz** [comment] 2015-07-17 10:54
@DeepDiver1975 - I just looked at the release schedule and I guess this is too late for 8.1.1?

**Comment by DeepDiver1975** [comment] 2015-07-17 10:58
I'm willing to accept a PR to be merged until Monday for this

**Comment by DeepDiver1975** [comment] 2015-07-20 13:13
@oparoz @georgehrke anyting in the pipe to address this issue? THX

**Comment by oparoz** [comment] 2015-07-20 14:22
@DeepDiver1975 I should have something in a few minutes

**Comment by oparoz** [comment] 2015-07-20 15:20
I might not be able to fix this on time.
What I broke is fixed with https://github.com/owncloud/core/pull/17753

But I think  @butonic might have broken the left side with this commit
https://github.com/owncloud/core/commit/c615b3527f7c472afbc93d3293c7f467a99cbd0b

I'm not familiar enough with the HTML/CSS structure to be able to quickly find a solution

**Comment by oparoz** [comment] 2015-07-20 15:39
@butonic had nothing to do with the problem.

The CSP policy of the public page is too restrictive. Plenty of problems have been reported already because of it, so a decision has to be made whether it can be loosened up a bit or if the file comparison feature has to be dropped. @DeepDiver1975 @LukasReschke

**Comment by LukasReschke** [comment] 2015-07-20 15:40
What is the exact CSP exception?

**Comment by oparoz** [comment] 2015-07-20 15:42
`Content Security Policy: The page's settings blocked the loading of a resource at blob:https://domain.com/68f20cd9-9c4c-4ead-ba03-0f2d2582fe4a ("img-src https://domain.com").`

**Comment by oparoz** [comment] 2015-07-20 15:43
The alternative is of course to upload the file to a temp location, get a preview and then move it to its final destination.

**Comment by rperezb** [comment] 2015-07-24 12:29
Hey @DeepDiver1975 , is this expected to be fixed within 8.1.1 version, thx

**Comment by DeepDiver1975** [comment] 2015-07-24 14:18
fix is in #17753 - to be merged into master for 8.2 - backport will be done afterards

**Comment by georgehrke** [comment] 2015-09-20 10:40
[OC.Files.Client](https://github.com/owncloud/core/pull/16902) was rescheduled to ownCloud 9.0.
Do we want to go with #18517 for ownCloud 8.2 and fix it like @PVince81 suggested with ownCloud 9.0?

**Comment by PVince81** [comment] 2015-09-21 09:10
Yeah, whichever works for 8.2. The cleaner fix would be for 9.0.

**Comment by oparoz** [comment] 2015-09-26 14:33
Milestones are wrong. The right side was fixed in 8.1.2 and @georgehrke has ported the same solution to 8.2.

So, the only thing left is to fix the left side, but that can't be done with the current CSP policy and should probably be opened as a separate issue.
There are 2 solutions:
- Change the CSP policy. 8.2
- Get rid of the canvas based solution and generate new previews from temp storage (dangerous). 9.0

I'll let @LukasReschke decide.

**Comment by oparoz** [comment] 2015-09-29 12:37
Fix for the left side is here: https://github.com/owncloud/core/pull/19440

**Comment by oparoz** [comment] 2015-09-29 14:51
The last piece of the puzzle:
https://github.com/owncloud/core/pull/19449

**Comment by cmonteroluque** [comment] 2015-10-01 19:50
reminder: This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by oparoz** [comment] 2015-10-02 16:35
This has been fixed on both 8.1 and 8.2. 8.2 also now has better previews.

**Closed by oparoz** 2015-10-02 16:35 UTC
Labels: bug, feature:previews, regression, sev3-medium
