### ISSUE TITLE
Cache cleanup not running

### ISSUE THREAD

**Issue by jasonbayton** [owncloud/core#16397] opened 2015-05-18 09:31 UTC
Hi, 

As I write this I have 1.9TB worth of cache files in the cache folder. These files have been accruing since installation (going back as far as the first few days) but most of the cache has built up in the last week whilst syncing PST/OST files between computers; a task that regularly errors out as they're in use most of the day. 

As an aside as I don't know if it's related, I'm seeing many fatal errors

![error oc](https://cloud.githubusercontent.com/assets/3178412/7677918/f7c60e58-fd47-11e4-9e6c-595b15aaac16.png)

Version: 8.0.3
Ubuntu 14.04.2
Apache2: 2.4.7
PHP: 5.5.9
MySQL: 5.5.43

The cron settings are on the default AJAX.

It looks like this - https://github.com/owncloud/core/pull/14500 - was created to address something like this, but I'm up to date on ownCloud so if it's supposed to "just work" it doesn't at the moment.

**Comment by jasonbayton** [comment] 2015-05-19 08:26
I've been playing around with the file scan command today after deleting some redundant folders.

This pops up in the terminal: 

[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'DELETE FROM `oc_filecache` WHERE `fileid` = ?' with params [477345]
  :
  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

  [PDOException]
  SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

**Comment by PVince81** [comment] 2015-05-19 16:20
In OC <= 8.0 the cleanup routine runs in the login hook. Which means it happens only when the user logs in. It can be rare when using the "remember me cookie" or using an always running sync client that pings the server often.

In OC >= 8.1 it should happen in cron (still to be confirmed)
Marking as duplicate of https://github.com/owncloud/core/issues/14646

**Closed by PVince81** 2015-05-19 16:20 UTC
Labels: bug
