### ISSUE TITLE
Public view is never refreshed when changes happen in the original share

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16486] opened 2015-05-20 23:16 UTC
### Env
master, browser

### Steps to reproduce
1. Share a folder as user A
2. Open that share in another tab. You're user B
3. As user A, add a file in the shared folder
4. As user B, look at your list of files

### Expected results
As user B, I should be seeing the new file

### Actual result
Nothing happens until I refresh the browser window or click on a folder (if there is one) and come back

This is bad for users, because the sharer will need to teach all his recipients to frequently hit F5, just to see if there are new files.

**Comment by oparoz** [comment] 2015-05-20 23:19
@jancborchardt Thoughts?
@RealRancor Is this a duplicate? ;)

**Comment by nickvergessen** [comment] 2015-05-21 08:02
Well this also happens without sharing. Just open the same folder in two tabs. Upload a file in one of them.

**Comment by nickvergessen** [comment] 2015-05-21 08:03
And yes, I think it's a duplicate of https://github.com/owncloud/core/issues/983 (open issue with 3 digits Oo)

**Comment by nickvergessen** [comment] 2015-05-21 08:05
And also https://github.com/owncloud/core/issues/9474

**Closed by nickvergessen** 2015-05-21 08:05 UTC
Labels: design, duplicate, enhancement
