### ISSUE TITLE
OC 8.0.4 Invalid OCS content returned for app .....

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#17307] opened 2015-07-02 02:44 UTC
OC 8.0.4 fresh install, only default application enabled, when you clic on +Apps to see the application list, you get sistematically the following error in the log:

Fatal 	core 	Invalid OCS content returned for app 166049 	2015-07-02T02:39:00+00:00
Fatal 	core 	Invalid OCS content returned for app 166055 	2015-07-02T02:39:00+00:00
Fatal 	core 	Invalid OCS content returned for app 166059 	2015-07-02T02:39:00+00:00
Fatal	core	Invalid OCS content returned for app 166053	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166052	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166038	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166056	2015-07-02T02:38:59+00:00
Fatal	core	Invalid OCS content returned for app 166051	2015-07-02T02:38:59+00:00

**Comment by RealRancor** [comment] 2015-07-02 05:29
Very likely a dup of https://github.com/owncloud/core/issues/16136

**Comment by LukasReschke** [comment] 2015-07-02 05:30
Seems like we need to remove the OCS IDs as well. Stupid mistake of mine, error is non-fatal and will be fixed with the next releases.

**Comment by LukasReschke** [comment] 2015-07-02 05:34
@RealRancor Nope. This one is happening because I cleaned up the AppStore and deleted placeholders :-/

**Comment by RealRancor** [comment] 2015-07-02 06:05
@LukasReschke 

Isn't this the same then:

> That leads to "Invalid OCS content returned for app xyz" messages in the log for apps which don't exist in the app store.

**Comment by LukasReschke** [comment] 2015-07-02 06:13
That one is a bug when an app has no OCS ID specified. Then it does a lookup with the App Name which fails. In this case the OCS ID is specified but points to a not existing entry. Same message, different root cause :smiley:

**Comment by RealRancor** [comment] 2015-07-02 06:17
Ahh, got it :)

**Comment by LukasReschke** [comment] 2015-07-02 07:05
Will be fixed once all of the linked PRs are merged.

**Comment by MorrisJobke** [comment] 2015-07-02 12:46
This is now fixed

**Closed by MorrisJobke** 2015-07-02 12:46 UTC
Labels: bug

**Comment by zubanst** [comment] 2015-08-10 13:19
This is not fixed in owncloud 8.0.5
Fatal 	core 	Invalid OCS content returned for app 166048 	2015-08-10T12:45:59+00:00
Fatal 	core 	Invalid OCS content returned for app 166049 	2015-08-10T12:45:59+00:00
Fatal 	core 	Invalid OCS content returned for app 166055 	2015-08-10T12:45:58+00:00 
...

**Comment by Megachip** [comment] 2015-08-11 13:50
@MorrisJobke @zubanst same here:

**Comment by MorrisJobke** [comment] 2015-08-12 09:08
@LukasReschke Are all apps are updated in the appstore?

**Comment by blue-bean** [comment] 2015-09-07 22:02
Also in 8.0.7 it's not fixed.

**Comment by disy-mk** [comment] 2015-09-21 08:29
And also present in 7.0.10

**Comment by blue-bean** [comment] 2015-09-22 18:25
+1 (for 8.0.8)

**Comment by koumdros** [comment] 2016-02-15 21:55
+1 for 8.0.10

**Comment by RealRancor** [comment] 2016-02-16 07:05
Just upgrade to 8.1.5 or 8.2.2 and the messages will disappear
