### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

### ISSUE THREAD

**Issue by ghost** [owncloud/core#20697] opened 2015-11-24 08:44 UTC
Hi,

owncloud 8.2 upgrade version 8.2.1

PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress

thanks

**Comment by PVince81** [comment] 2015-11-24 09:21
issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by iacopodeenosee** [comment] 2015-12-20 09:18
same issue here, upgrade OC from 8.1.4 to 8.2.1
### Steps to reproduce
1. open in th broswer the web interface of OC
2. try to upgrade to version 8.2.1 by cliccking start the upgrade
3. send me to this error message page

### Expected behaviour
it should be upgrade to verion 8.2.1

### Actual behaviour
upgrade fails and i can not access to the admin page anymore

### Server configuration
**Operating system**:
QNAP TS-231 firmware 4.2.0 build 20151118
Linux QNAP-TS-231 3.2.26 #2 SMP Wed Nov 18 07:58:14 CST 2015 armv7l unknown
**Web server:**
apache
**Database:**
sqlite3
**PHP version:**
[~] # /mnt/ext/opt/apache/bin/php --version
PHP 5.5.29 (cli) (built: Nov 18 2015 07:29:39) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
**ownCloud version:** (see ownCloud admin page)
8.1.4
**Updated from an older ownCloud or fresh install:**
fresh install from qpkg app center
**List of activated apps:**
---
**The content of config/config.php:**
```
[/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud] # cat config/config.php 
<?php
$CONFIG = array (
  'instanceid' => 'ocjmfhc340mw',
  'passwordsalt' => 'blabla',
  'secret' => 'blabla',
  'trusted_domains' => 
  array (
    0 => '192.168.1.140',
  ),
  'datadirectory' => '/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud/data',
  'overwrite.cli.url' => 'nas:8081/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.4.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
**Browser:**
firefox 43.1
**Operating system:**
arch linux 64bit
### Logs
#### Web server error log
---
#### ownCloud log (data/owncloud.log)
```
{"reqId":"\/bjKQzdOriJ81A2hApDO","remoteAddr":"192.168.1.102","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-12-20T08:14:57+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"Smphly6tvsdMBKdoBVg+","remoteAddr":"192.168.1.102","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-12-20T08:15:04+00:00","method":"OPTIONS","url":"\/owncloud\/remote.php\/caldav\/calendars\/iacopodeenosee\/personale\/"}
{"reqId":"8kd6zLeUdbQs\/Vt4pI+d","remoteAddr":"192.168.1.102","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-12-20T08:15:05+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"f7WqBfbS2GQErAyXbV2\/","remoteAddr":"192.168.1.102","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-12-20T08:19:27+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"T+LayqxA7BoJjhNaiIQr","remoteAddr":"192.168.1.102","app":"core","message":"starting upgrade from 8.1.4.2 to 8.2.1.4","level":0,"time":"2015-12-20T08:23:02+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=FloMamAZAiV3Q3snGRcULDdZXCAPF2Q2DxQTIAYG%3Ap1kA7IKU019AxUAbA79XfBPWfXcTMO"}
{"reqId":"T+LayqxA7BoJjhNaiIQr","remoteAddr":"192.168.1.102","app":"core","message":"Exception: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress\",\"Code\":\"HY000\",\"Trace\":\"#0 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1216): PDO->commit()\\n#1 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/repair\\\/repairlegacystorages.php(250): Doctrine\\\\DBAL\\\\Connection->commit()\\n#2 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/repair.php(87): OC\\\\Repair\\\\RepairLegacyStorages->run()\\n#3 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(329): OC\\\\Repair->run()\\n#4 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '8.1.4.2')\\n#5 \\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#6 {main}\",\"File\":\"\\\/share\\\/CACHEDEV1_DATA\\\/.qpkg\\\/owncloud\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php\",\"Line\":1216}","level":3,"time":"2015-12-20T08:23:04+00:00","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=FloMamAZAiV3Q3snGRcULDdZXCAPF2Q2DxQTIAYG%3Ap1kA7IKU019AxUAbA79XfBPWfXcTMO"}
```
#### Browser log
---

**Comment by PVince81** [comment] 2015-12-21 09:35
@iacopodeenosee thanks for the details.
I see it happens when repairing legacy storages. Strange.

Can you post your "oc_storages" table from before the upgrade ?
It looks like it was trying to repair old entries but the commit failed.

**Comment by iacopodeenosee** [comment] 2015-12-21 16:04
> Can you post your "oc_storages" table from before the upgrade ?


something like that?
![schermata del 2015-12-21 16-58-54](https://cloud.githubusercontent.com/assets/4881584/11934792/87897eb4-a804-11e5-88ab-adf6f8f374bf.png)
how can i solve this kind of problem? reset all of this field? thx

**Comment by PVince81** [comment] 2015-12-21 16:17
Hmm, your storages table looks fine. The legacy storage repair code shouldn't actually do anything.

As a workaround you could mark the repair as already done:
`insert into oc_appconfig (appid, configkey, configvalue) values ('core', 'repairlegacystoragesdone', 'yes');`

Which OC version did you start with ? Did you ever upgrade to OC 8.0 before ? That's the moment where this repair step was supposed to run.

**Comment by iacopodeenosee** [comment] 2015-12-21 17:04
> Which OC version did you start with ? 

i don't know:
```
[/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud] # /mnt/ext/opt/apache/bin/php occ -V
Console has to be executed with the user that owns the file config/config.php
Current user: admin
Owner of config.php: httpdusr
[/share/CACHEDEV1_DATA/.qpkg/owncloud/owncloud] # su - httpdusr /mnt/ext/opt/apache/bin/php occ -V
-sh: su: command not found
```
> Did you ever upgrade to OC 8.0 before ?

NO

after i do your workaround, the upgrade works well, but i lost all the files and the apps I had previously loaded, not a drama because I have a backup but it seems fair to write it. thx

**Comment by PVince81** [comment] 2015-12-21 18:13
Third party apps are disabled by default, you need to reenable them manually in the admin page. That's expected behavior.

I only wonder why the repair step failed even though there was no data to commit.
Leave this ticket open to investigate.

**Comment by PVince81** [comment] 2015-12-21 18:14
and actually that repair step doesn't even need to run if the OC instance was never in a pre-OC-8.0 state, because that's the place where the old entries were created.

Maybe we should just discard this repair step in all versions above 8.0.

**Comment by PVince81** [comment] 2016-06-01 14:34
So far it is not clear why the legacy storage upgrade hasn't worked and also there isn't enough information to infer this, so I'm closing this for now.

If this issue reappears, please reopen.

**Closed by PVince81** 2016-06-01 14:34 UTC
Labels: bug, feature:update, sev2-high
