### ISSUE TITLE
Missing Avatar after upgrade from 8.2.3 to 9.0.0

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#22978] opened 2016-03-09 00:45 UTC
### Steps to reproduce
1. Have an avatar set in ownCloud. Mind: in the user home directory, there is only avatar.jpg, but no avatar.32.jpg
2. Do the upgrade
3. Login, or go to Personal or Users page

### Expected behaviour
Avatar is visible as it was before

### Actual behaviour
No Avatar in the header (but also no display name), placeholders in other places.

Copying the avatar.jpg file to avatar.32.jpg brings it back.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Update from 8.2.3

**Where did you install ownCloud from:** Tarball

**Signing status (ownCloud 9.0 and above):** awesome

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/var/lib/owncloud/ovin-data',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'installedat' => '1326327271.69',
  'lastupdatedat' => '1338667774.87',
  'dbname' => 'foobar',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'barfoo',
  'dbpassword' => 'foo',
  'installed' => true,
  'instanceid' => '123456',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 1,
  'trusted_domains' => 
  array (
    0 => 'foo.de',
    1 => 'bar.de',
    2 => 'foobar.cu',
  ),
  'secret' => 'sadf',
  'share_folder' => '/Shared',
  'asset-pipeline.enabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/minion/ovin/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/var/www/minion/apps-extra',
      'url' => '/../apps-extra',
      'writable' => true,
    ),
  ),
  'appstoreenabled' => true,
  'trashbin_retention_obligation' => 'auto',
);

```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FF 44

**Operating system:** Antergos Linux

#### ownCloud log (data/owncloud.log)

Nothing wrt Avatars

**Comment by Psy-Virus** [comment] 2016-03-09 03:19
Hey,
I've a similar issue with my theme background image after the 8.2.2 -> 8.2.3 -> 9.0 upgrade.
Maybe the info helps.
If it's file ending is set to jpg, it won't load in the browser. The web server says a 302, also if I rename the file-name without the file type and change the related css.
If I change the file type to .png (with or without real conversion) and change the related css it is shown in the browser and the server gives a 200...

I tried to update the mimetypes with the related occ commands. But this changed nothing.

Btw. The owncloud logs do not say anything related the background image.

That's strange

:-)

**Comment by rullzer** [comment] 2016-03-09 06:57
Does updating the avatar help? (So setting it again?).

**Comment by oxivanisher** [comment] 2016-03-09 07:21
I have the same issue and updating the avatar does not help.

**Comment by jmit79** [comment] 2016-03-09 09:35
same here, I can't save a new avatar and the existing ones were broken. There's a NotPermittedException in the owncloud.log:

`{"reqId":"dpEgL\/oljUh+SCCNTZRa","remoteAddr":"192.168.2.26","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/avatar.php(121): OC\\\\Files\\\\Node\\\\Folder->newFile('avatar.png')\\n#1 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/avatarcontroller.php(315): OC\\\\Avatar->set(Object(OC_Image))\\n#2 [internal function]: OC\\\\Core\\\\Controller\\\\AvatarController->postCroppedAvatar(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\AvatarController), 'postCroppedAvat...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\AvatarController), 'postCroppedAvat...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('AvatarControlle...', 'postCroppedAvat...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/avatar\\\/cropped')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php\",\"Line\":171}","level":3,"time":"2016-03-09T09:29:24+00:00"}`

**Comment by PVince81** [comment] 2016-03-09 14:36
My avatar still worked after updating. I seem to have multiple in owncloud/data/vincent:
```
-rw-r--r--   1 wwwrun www  695 Mar  3 10:09 avatar.1.jpg
-rw-r--r--   1 wwwrun www 5.0K Mar  4 11:42 avatar.145.jpg
-rw-r--r--   1 wwwrun www 6.1K Mar  3 10:09 avatar.175.jpg
-rw-r--r--   1 wwwrun www 1.1K Mar  4 10:07 avatar.32.jpg
-rw-r--r--   1 wwwrun www 1.8K Mar  3 10:09 avatar.64.jpg
-rw-r--r--   1 wwwrun www  46K Oct 24  2013 avatar.jpg
```

**Comment by blizzz** [comment] 2016-03-09 15:43
@PVince81 yes, because you have the avatar.$SIZE.jpg files. If you had only avatar.jpg, you'd run into the problem. I believe somewhere on the go, avatars were made to create and use files with size. Apparently, no miration of "old" avatars happened.

**Comment by rullzer** [comment] 2016-03-09 16:00
@blizzz no there is no migration because they used to be created on the fly. They still are... but now we just store the result so the next requests takes the precreated one (if it is there).

**Comment by rullzer** [comment] 2016-03-09 16:00
@PVince81 to double check... could your remove all of your avatar.*.jpg files? (so all but avatar.jpg) and see if they get recreated? (They do here).

**Comment by blizzz** [comment] 2016-03-09 16:12
@rullzer on my dev system, if i remove the avatar it will be recreated. On the production system however, not.

**Comment by oxivanisher** [comment] 2016-03-09 16:30
I also tried deleting the avatar.jpg and it did not regenerate files after choosing a new file.

**Comment by PVince81** [comment] 2016-03-09 17:45
@rullzer I deleted all of them, then logged in again in the web UI. No avatar was generated.

Then I reselected a jpg file directly from my OC and it generated those:
```
-rw-r--r--   1 wwwrun www 6.0K Mar  9 18:45 avatar.175.jpg
-rw-r--r--   1 wwwrun www 1.2K Mar  9 18:45 avatar.39.jpg
-rw-r--r--   1 wwwrun www  29K Mar  9 18:45 avatar.jpg
```

**Comment by rullzer** [comment] 2016-03-09 18:41
@blizzz @oxivanisher do you get a 404 or a different error code? (in the transfer console)

**Comment by rullzer** [comment] 2016-03-09 18:45
@jmit79 that not permitted exception looks :fish:-y... Altough I have no clue where it comes from...

**Comment by blizzz** [comment] 2016-03-09 22:38
> @blizzz @oxivanisher do you get a 404 or a different error code? (in the transfer console)

nope, always 200

**Comment by blizzz** [comment] 2016-03-10 10:21
@rullzer  with removed catches I get this three times on the personal page (3 sizes are requested)

```
{"reqId":"2KMqS/AzeGgF4NWhulqu","remoteAddr":"109.45.2.130","app":"index","message":"Exception: {\"Exception\":\"OCP\Files\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/avatar.php(163): OC\Files\Node\File->getContent()\
#1 \/var\/www\/minion\/ovin-9.0.0\/core\/controller\/avatarcontroller.php(117): OC\Avatar->getFile(1)\
#2 [internal function]: OC\Core\Controller\AvatarController->getAvatar('arthur', 1)\
#3 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\
#4 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\AvatarController), 'getAvatar')\
#5 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/appframework\/app.php(110): OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\AvatarController), 'getAvatar')\
#6 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('AvatarControlle...', 'getAvatar', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
#7 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\
#8 \/var\/www\/minion\/ovin-9.0.0\/lib\/private\/route\/router.php(273): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\
#9 \/var\/www\/minion\/ovin-9.0.0\/lib\/base.php(873): OC\Route\Router->match('\/avatar\/arthur\/...')\
#10 \/var\/www\/minion\/ovin-9.0.0\/index.php(39): OC::handleRequest()\
#11 {main}\",\"File\":\"\/var\/www\/minion\/ovin-9.0.0\/lib\/private\/files\/node\/file.php\",\"Line\":42}","level":3,"time":"2016-03-10T09:20:27+00:00"}
```

**Comment by rullzer** [comment] 2016-03-10 11:02
Ok so it boils down to https://github.com/owncloud/core/blob/master/lib/private/files/node/file.php#L57 Which to me looks like invalid permissions in the oc_filecache table. @blizzz confirmed that they are 0.

Now this only happens now since I switched over the avatar code to the Node API.

@icewind1991 any idea how we can fix the broken entries?

**Comment by blizzz** [comment] 2016-03-10 11:04
setting permissions to 27 did not make it work.

Users with issues had two entries about the avatar in the filecache table. One tied to their own storage, one to the data-dir-storage. 

However, fixing permissions and removing the avatar entry belonging to the data-dir-storage did not make it work either.

**Comment by icewind1991** [comment] 2016-03-11 12:31
> setting permissions to 27 did not make it work.

It should be 31

**Comment by blizzz** [comment] 2016-03-11 12:35
@icewind1991 setting them to 31 does not have any impact either.

**Comment by icewind1991** [comment] 2016-03-11 12:50
https://github.com/owncloud/core/pull/23154 should keep avatars visible even when we cant save the resized one

**Comment by rullzer** [comment] 2016-03-11 12:54
> It should be 31

No it is a file... so there are no create permissions right?

**Comment by blizzz** [comment] 2016-03-11 12:57
The entry with empty name and path (parent -1) of my storage has permissions of 0. Is it how it should be? Maybe that should be 31 as well?

**Comment by icewind1991** [comment] 2016-03-11 13:02
Yes, that's the one that's actually important, that folder needs create permissions

**Comment by blizzz** [comment] 2016-03-11 13:06
My data dir storage has almost 17k entries in the filecache. And most of them belong to users. Is this correct? if I exclude all the user related paths, I am down to 29 entries (inlcuding user folders).

**Comment by blizzz** [comment] 2016-03-11 13:10
> The entry with empty name and path (parent -1) of my storage has permissions of 0. Is it how it should be? Maybe that should be 31 as well?

Changing this fixes it for me.

**Comment by rullzer** [comment] 2016-03-11 13:33
@icewind1991 so actually we would need a repair step to set the correct permissions on the parent?

**Comment by PVince81** [comment] 2016-03-16 15:26
Not sure if that's really a "high" issue if it only occurs when permissions were wrong.

The question is how could the permissions be wrong in the first place ?

**Comment by rullzer** [comment] 2016-03-16 15:32
@PVince81 yeah that is the question indeed. I know it happened to a few users at least (@dragotin was also affected). So it might be that it is mostly older installations.

**Comment by icewind1991** [comment] 2016-03-21 14:20
imo we can lower the priority on this or maybe even close this in favor of a "check why the home folder permissions can get messed up" issue

**Comment by PVince81** [comment] 2016-03-21 14:25
Agreed. How about adding an additional setup check to find out whether permissions are wrong ? Or improve the existing one ?

**Comment by oxivanisher** [comment] 2016-03-21 14:27
Or even a administrative task to "fix permissions" (executable from the admin gui).

**Comment by PVince81** [comment] 2016-03-24 13:22
Reducing severity now that the regression was fixed.
Also moving to 9.0.2 to look for a better check for messed up permissions, possibly in the setup checks.

CC @cmonteroluque

**Comment by Wikinaut** [comment] 2016-03-26 20:49
I have the same problem after upgrading to oc 9.0.0.

In my three-user owncloud, two avatars are missing (and cannot be set, I tried jpg and png), one is present and could be updated (changed).

**Comment by cmonteroluque** [comment] 2016-03-28 18:50
@PVince81 ok, I had my doubts about the severity drop, but 9.0.2 makes sense. Thanks

**Comment by Wikinaut** [comment] 2016-04-09 09:17
Not fixed in OC 9.0.1

**Comment by DeepDiver1975** [comment] 2016-04-10 20:06
refs #ava

> Not fixed in OC 9.0.1

indeed - https://github.com/owncloud/core/issues/23892

**Comment by oxivanisher** [comment] 2016-05-14 20:05
Can at least someone post a way to fix this? Since it is still not fixed in 9.0.2.
(changing the permission to 23 or 31 did not help)

**Comment by gig13** [comment] 2016-05-23 13:45
@bboule @PVince81 Any updates?

**Comment by atnexxt** [comment] 2016-05-26 08:59
I did a rescan of my user files `php occ  files:scan [user-id]` on the console and got my avatar image back visible.

**Comment by oxivanisher** [comment] 2016-05-26 09:26
@atnexxt thanks! that worked :+1:

**Comment by gig13** [comment] 2016-05-26 17:55
@bboule @PVince81 Could this be added to OC8.2.x maintenance release?

**Comment by Wikinaut** [comment] 2016-05-26 18:08
@atnexxt GREAT! 

```sudo -u www-data php occ files:scan --all```

solved the problem.

**Comment by axel-dd** [comment] 2016-05-26 20:03
Thx works for me too.

For users on all-inkl shared webspace do the follwing...
1. use all-inkl WebFTP to chown owncloud folder permissions to ftp user (e.g. w123456) recursively
2. temporary move the .htaccess file out of the owncloud root folder (e.g move it resources folder)
3. create a run.phpx file in the owncloud root folder with the following content 
`<?php echo exec('php occ files:scan --all'); ?>`
4. now run in https://myowncloud.url/run.phpx and wait until it is finished
5. move the .htaccess file back to the owncloud root folder
6. use all-inkl WebFTP to chown owncloud folder permissions back to php user recursively

Now your avatar images should be back.

**Comment by rullzer** [comment] 2016-05-27 10:05
A awesome that there is a fix.
Still I think it would be good to have a repair step to fix the permissions on the root and users roots. @icewind1991 do you agree? (I can write such a repair step)

**Comment by icewind1991** [comment] 2016-05-27 11:36
A repair step would make the most sense

**Comment by rullzer** [comment] 2016-05-27 18:40
Ok I'll fix that somewhere next week

**Comment by rullzer** [comment] 2016-05-30 13:06
PR in #24898

**Closed** 2016-06-10 15:02 UTC
Labels: 3 - To Review, backport-request, blue-ticket, bug, feature:avatars, sev2-high
