### ISSUE TITLE
Fedora repo files titled "Fake 10.2 repository"

### ISSUE THREAD

**Issue by Taomyn** [owncloud/core#35310] opened 2019-05-23 07:15 UTC
## Steps to reproduce
1. Visit http://download.owncloud.org/download/repositories/production/Fedora_30/ce:stable.repo
2. View file

### Expected behaviour
A sensible name

### Actual behaviour
Says "Fake 10.2 repository (Fedora_30)"

**ownCloud version:** 10.2

**Comment by crrodriguez** [comment] 2019-05-27 15:01
Fake 10.2 repository (Fedora_30) was intended as an internal -only description, but it appears it went used elsewhere, fixed now

**Closed by crrodriguez** 2019-05-27 15:01 UTC
