### ISSUE TITLE
Shared by me - empty with ldap users

### ISSUE THREAD

**Issue by TheReal1604** [owncloud/core#24521] opened 2016-05-09 18:51 UTC
Hey guys,

My owncloud version is 9.0.2. 

The filters "shared by me" and "shared with link" are empty after the update to owncloud 9.0. 

Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() at /var/www/owncloud/apps/user_ldap/user_ldap.php#381

Is permanently in my logfile then i try to show the "shared by me" view.

Anyone have an idea?

Thanks
Greets
Thereal

**Comment by LukasReschke** [comment] 2016-05-10 05:45
Please fill out the issue template. Thanks.

cc @owncloud/ldap

**Comment by TheReal1604** [comment] 2016-05-10 06:32
**Steps to reproduce**

    Create an LDAP User
    Share a File
    Look into the shared by me filter -> empty

**Expected behaviour**

The shared file should be in this filter view.

**Actual behaviour**

The filtered views "shared by me" and "shared with link" are empty.

**Server configuration**

Operating system: Ubuntu 14.04 LTS

Web server: Apache

Database: MySQL

PHP version: 7

ownCloud version: 9.0.2

Updated from an older ownCloud or fresh install: issue happens since upgrade from 8.2 to 9.0

Where did you install ownCloud from: apt repos (https://download.owncloud.org/download/repositories/stable/owncloud/)

Signing status (ownCloud 9.0 and above): all fine

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - ldap user backend: 0.8.0



Are you using external storage, if yes which one: No

Are you using encryption: No

Are you using an external user-backend, if yes which one: LDAP (Active Directory)
Client configuration

Browser: Google Chrome

Operating system: Windows 10

**Logs**
Web server error log

Nothing unusual here

ownCloud log (data/owncloud.log)

Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() at /var/www/owncloud/apps/user_ldap/user_ldap.php#381

**Comment by PVince81** [comment] 2016-05-10 11:17
Thanks for the detail. the other report https://github.com/owncloud/core/issues/22997#issuecomment-217926772 was about an `InvalidShare` error and you said you're having it too.

Mind posting more information about this ? Or was it a misunderstanding ?

Is this happening for all users or just one ? Is that user recipient of a possibly broken share ? Do other users receiving the same share (if applicable) also have this issue ?

**Comment by PVince81** [comment] 2016-05-10 11:17
CC @rullzer @blizzz

**Comment by blizzz** [comment] 2016-05-10 12:39
Cannot reproduce with the given steps.

``Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() at /var/www/owncloud/apps/user_ldap/user_ldap.php#381``

suggests that one of the users was marked as deleted. This is a track to follow.

**Comment by TheReal1604** [comment] 2016-05-10 13:32
@pvince81 Sry, i got only the same Symptoms, Not the exactly same error.

in the next hours I will try this for another user.  

@blizzz: The user exists in active directory. Just for the info, is there a way to convert a ad user to an owncloud "non ldap" user? That could be the way for my lab.. 

Thanks guys

**Comment by TheReal1604** [comment] 2016-05-10 13:37
Ok, tried this with another user. I mind we have done some freaky things with my user. My friend recreated my user in AD, with the same SamAccountname, but this user has a other SID and so on.. Can this cause the error?

**Comment by blizzz** [comment] 2016-05-11 10:57
@TheReal1604 might. Key point is whether the UUID changed. It's taken either from the ObjectGUID by default, or if you have a different attribute specified on the experts page. However, then you what have noticed a blank ownCloud. Btw, did you try to logout and login again? :)

**Comment by TheReal1604** [comment] 2016-05-11 13:27
@blizzz I tried to remove and add the user to the OwnCloud Users Group.. this is not resolving my problem.

To clarify the issue, this is what I see:
![screenshot](https://cloud.githubusercontent.com/assets/5877910/15182437/b71cd944-178c-11e6-9224-4c9a84c1dcab.png)

In another ldap users account this view is okay.

Where i can search for different UUID? I have no to little knowledge where i have to start in the database.

**Comment by TheReal1604** [comment] 2016-05-11 17:27
Hey @blizzz,

i checked the UUID of my user in my database, its the same that is in the AD. So, this seems to work. 

I checked some other things and my share links / sharing function with this users of some files are broken too. 

![unbenannt](https://cloud.githubusercontent.com/assets/5877910/15190095/6552f284-17ae-11e6-8bca-83efba626088.png)


Suggestions?

**Comment by TheReal1604** [comment] 2016-05-11 18:33
Okay solved the issue.. downloaded all files, delete all files, upload them again. All is fine now.

**Comment by PVince81** [comment] 2016-07-13 07:50
Possibly some bogus/invalid shares. In 9.0.3 and later we've added more repair steps to repair such shares.

**Closed by PVince81** 2016-07-13 07:50 UTC
Labels: app:user_ldap, bug, needs info

**Comment by ownclouders** [comment] 2017-12-21 01:10
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
