### ISSUE TITLE
Order of icons in the app selection menu

### ISSUE THREAD

**Issue by raid1** [owncloud/core#17298] opened 2015-07-01 15:02 UTC
Hi, is there a way to change the place of the app icons in the selection menu?

It seems to be pretty random order to me but maybe it just feels so and there is a deeper meaning to it?
I'd like to understand it and - if possible - change it.

Thanks! Andy.

(Attached you find the way it looks right now on my OC8 server)

![gkrellshoot_06-30-15_190530](https://cloud.githubusercontent.com/assets/1580206/8457646/ed07a5ce-2012-11e5-8917-21f3c29b7c3b.png)

**Comment by LukasReschke** [comment] 2015-07-01 15:04
Duplicate of https://github.com/owncloud/core/issues/10654

**Closed by LukasReschke** 2015-07-01 15:04 UTC

**Comment by karlitschek** [comment] 2015-07-01 15:06
Yay. Someone is using my awesome pong app   :-) :-)
