### ISSUE TITLE
User of remaining capacity limit at the time of the 0 byte, not be able to delete the files on the shared folder.

### ISSUE THREAD

**Issue by pomu0326** [owncloud/core#16187] opened 2015-05-08 02:48 UTC
### Steps to reproduce
1. Create a USER_A, and set the quota to 5GB.
1. Create a USER_B, and set the quota to 0.
1. USER_A create a folder, you will share the folder to USER_B.
1. USER_B Upload the file of something in a shared folder.
1. USER_B deletes the file.

### Expected behaviour
I expect that the file can be deleted.

### Actual behaviour
owncloud will cause an error.
```
Could not delete: [target file]
```
### Server Host info
Ubuntu 14.04
PHP 5.5.9
MariaDB 10.0.17

### Server configuration
The default setting of owncloud 8.0.3

**Comment by MorrisJobke** [comment] 2015-05-08 08:07
I guess, this is because of the file should be moved to its trashbin and because of an quota of 0 this isn't possible.

cc @icewind1991 @schiesbn @PVince81

**Comment by Octopus2** [comment] 2015-05-08 08:24
Perhaps a duplicate of this one: https://github.com/owncloud/client/issues/3010

You can´t delete a shared file if the quota is smaler than the filesize

**Comment by MorrisJobke** [comment] 2015-05-08 08:28
@nickvergessen Maybe you want to dig into this? :D

**Comment by Octopus2** [comment] 2015-05-26 09:11
@MorrisJobke Any news on this?

This is an annoying error when you mainly use ownCloud for working togeter on shared files (Userquota only 10MB) and you can´t delete bigger files any more...

**Comment by pomu0326** [comment] 2015-05-26 14:01
@Octopus2 Hi, It is my workaround.

/lib/private/files/storage/wrapper/quota.php
```php
	public function fopen($path, $mode) {
		$source = $this->storage->fopen($path, $mode);
		$free = $this->free_space('');
		if ($source && $free >= 0 && $mode !== 'r' && $mode !== 'rb') {
                        //remove origin code
                        //return \OC\Files\Stream\Quota::wrap($source, $free);
 
                        // add code. when move trashbin then, ignore the quota.
                        if (strpos($path, 'files_trashbin/', 0) === 0) {
                                return $source;
                        } else {
                                return \OC\Files\Stream\Quota::wrap($source, $free);
                        }
		} else {
			return $source;
		}
	}
```

**Comment by PVince81** [comment] 2015-05-28 15:57
I'd like to increase severity. There are use cases where people share folders with other users, and those users can only work on the shared folders but not have any local files. This is achieved by setting their quota to 0, see https://github.com/owncloud/core/issues/16599#issuecomment-106434488

When deleting a shared file as recipient, usually that file will land in the recipient's trashbin and **also** in the owner's trashbin. If the recipient doesn't have enough space, I'd expect the file to not reach the recipient's trashbin, but still reach the one from the owner.

Seems to be a bug.

I don't think @pomu0326's workaround is the right way, because I suspect it might happen if the quota is set to low values like a few bytes, or whenever that user's free space is very low.

**Comment by PVince81** [comment] 2015-05-28 15:58
@mattrandallbecker mentionned here https://github.com/owncloud/core/issues/16599#issuecomment-106434488 that it used to work in OC 6/7, so this is a regression.

**Comment by PVince81** [comment] 2015-05-28 15:58
It is likely that the regression is due to the fact that the trashbin is now using a storage wrapper since OC 8.0

**Comment by PVince81** [comment] 2015-05-28 16:05
Confirmed that it works on stable7 (upcoming 7.0.6).
The file does not appear in the recipient's trashbin, but it appears in the owner's trashbin.
However, the file in the trashbin has a size of zero bytes :frowning: 

On stable8 (upcoming 8.0.4), I cannot delete the file.
This confirms this bug report and is indeed a regression.

**Comment by PVince81** [comment] 2015-05-28 16:07
@pomu0326 you got a point: from reading your change it looks like the quota storage wrapper was getting applied to the trashbin, which is wrong.

I'll see if I can provide a fix a bit higher in the call stack.

**Comment by PVince81** [comment] 2015-05-28 16:08
not saying that your fix is wrong, but it shows very well what is wrong in the original code :smile:

**Comment by PVince81** [comment] 2015-05-28 16:11
Hmmm on master (upcoming 8.1) the behavior is slightly different: I do get a "Could not delete" error, but after refresh the file is gone. But it's not even in the owner's trashbin! :frowning:

**Comment by PVince81** [comment] 2015-05-28 16:20
This is the call stack that leads to the quota wrapper for trashbin:
```
0  OC\Files\Stream\Quota::wrap() /srv/www/htdocs/owncloud/lib/private/files/stream/quota.php:68
1  OC\Files\Storage\Wrapper\Quota->fopen() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/quota.php:144
2  OC\Files\Storage\Wrapper\Encryption->fopen() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/encryption.php:406
3  OC\Files\Storage\Wrapper\Encryption->copyBetweenStorage() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/encryption.php:476
4  OC\Files\Storage\Wrapper\Encryption->moveFromStorage() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/encryption.php:424
5  OC\Files\Storage\Wrapper\Wrapper->moveFromStorage() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/wrapper.php:534
6  OCA\Files_Trashbin\Trashbin::move2trash() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:199
7  OCA\Files_Trashbin\Storage->doDelete() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:125
8  OCA\Files_Trashbin\Storage->unlink() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/storage.php:89
9  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:938
10 OC\Files\View->unlink() /srv/www/htdocs/owncloud/lib/private/files/view.php:573
11 OC\Files\Filesystem::unlink() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:677
12 require_once()  /srv/www/htdocs/owncloud/apps/files/ajax/delete.php:59
13 __lambda_func() /srv/www/htdocs/owncloud/lib/private/route/route.php%28153%29%20:%20runtime-created%20function:1
14 call_user_func:{/srv/www/htdocs/owncloud/lib/private/route/router.php:272}() /srv/www/htdocs/owncloud/lib/private/route/router.php:272
15 OC\Route\Router->match() /srv/www/htdocs/owncloud/lib/private/route/router.php:272
16 OC::handleRequest() /srv/www/htdocs/owncloud/lib/base.php:862
17 {main}          /srv/www/htdocs/owncloud/index.php:40
```

Now one thing I don't yet understand is how could this have ever worked ?

I found out that stable7 also wraps the storage, but it doesn't seem to disturb the trashbin in the same way:
```
0  OC\Files\Storage\Wrapper\Quota->fopen() /srv/www/htdocs/owncloud/lib/private/files/storage/wrapper/quota.php:127
1  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:778
2  OC\Files\View->fopen() /srv/www/htdocs/owncloud/lib/private/files/view.php:665
3  OC\Files\View->copy() /srv/www/htdocs/owncloud/lib/private/files/view.php:603
4  OCA\Files_Trashbin\Trashbin::copy_recursive() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:866
5  OCA\Files_Trashbin\Trashbin::move2trash() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:127
6  OCA\Files_Trashbin\Hooks::remove_hook() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/hooks.php:42
7  call_user_func:{/srv/www/htdocs/owncloud/lib/private/hook.php:78}() /srv/www/htdocs/owncloud/lib/private/hook.php:78
8  OC_Hook::emit() /srv/www/htdocs/owncloud/lib/private/hook.php:78
9  OC\Files\View->runHooks() /srv/www/htdocs/owncloud/lib/private/files/view.php:853
10 OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:774
11 OC\Files\View->unlink() /srv/www/htdocs/owncloud/lib/private/files/view.php:433
12 OC\Files\Filesystem::unlink() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:633
13 require_once()  /srv/www/htdocs/owncloud/apps/files/ajax/delete.php:31
14 OC::loadAppScriptFile() /srv/www/htdocs/owncloud/lib/base.php:809
15 call_user_func:{/srv/www/htdocs/owncloud/lib/private/route/router.php:227}() /srv/www/htdocs/owncloud/lib/private/route/router.php:227
16 OC\Route\Router->match() /srv/www/htdocs/owncloud/lib/private/route/router.php:227
17 OC::handleRequest() /srv/www/htdocs/owncloud/lib/base.php:717
18 {main}          /srv/www/htdocs/owncloud/index.php:28
```
Well... it does produce a zero-sized file in the trashbin.

So I could say, basically this was broken in previous versions too, but in a different way...

**Comment by PVince81** [comment] 2015-05-28 16:24
One idea would be to adapt @pomu0326's idea but only apply the quota wrapper if the path is in "/files/". Because we also do not want to apply the quota on "files_encryption", "thumbnails", etc.

**Comment by PVince81** [comment] 2015-05-28 16:33
Fix is here: https://github.com/owncloud/core/pull/16613

**Closed** 2015-05-28 17:44 UTC
Labels: app:files_trashbin, bug, quota, regression, sev3-medium, sharing

**Comment by pomu0326** [comment] 2015-06-01 08:31
@PVince81 thank you. I was able to resolve the issue.
