### ISSUE TITLE
Problem with .htacess

### ISSUE THREAD

**Issue by rkaldung** [owncloud/core#27765] opened 2017-04-28 07:12 UTC
### Steps to reproduce
1. Upgrade owncloud and keep original .htaccess
2. Open login

### Expected behaviour
Login page should be shown

### Actual behaviour
Internal server error is generated

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache httpd 2.2

**Database:** MySQL 5.5.55

**PHP version:** 5.6

**ownCloud version:** 10.0.0.12

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** yum repositories (CE stable)

**Signing status (ownCloud 9.0 and above):** https://gist.github.com/rkaldung/3f0bcf7147b5220feb934ccd6658f304 (.htacess manually fixed)

**The content of config/config.php:**

```
{
    "system": {
        "overwritewebroot": "\/owncloud",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "kaldung.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Memcached",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{***REMOVED SENSITIVE VALUE***:993\/imap\/ssl\/validate-cert}"
                ]
            },
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{***REMOVED SENSITIVE VALUE***:993\/imap\/ssl\/validate-cert}"
                ]
            }
        ],
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "noreply",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "\/owncloud",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**List of activated apps:**

```
  - activity: 2.3.3
  - calendar: 1.4.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.2
  - dav: 0.2.8
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** OC_User_IMAP

### Client configuration
**Browser:** Firefox 53, Google Chrome latest

**Operating system:** macOS 10.12.4

#### Web server error log
```
[Fri Apr 28 08:09:54 2017] [alert] /var/www/html/owncloud/.htaccess: Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration
```

**Comment by kdslkdsaldsal** [comment] 2017-04-28 13:13
This is a duplicate of https://github.com/owncloud/core/issues/27553 with a PR open addressing this issue at https://github.com/owncloud/core/pull/27748

**Closed** 2017-04-28 13:46 UTC
