### ISSUE TITLE
Accessibility/UX: Why adding maximum-scale=1.0?

### ISSUE THREAD

**Issue by Volker-E** [owncloud/core#15024] opened 2015-03-19 09:46 UTC
Currently the viewport meta tag is at layout.base.php: 

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">

and at the two other layout* files:

    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0>

What are the reasons for not letting users zoom in on smartphones/tablets? Was it some old, unreliabled iOS behavior?

See https://github.com/dhg/Skeleton/issues/173 for a collection of pro and con arguments in a similar. I'm clearly strongly for the accessibility/less native app approach, allowing users to zoom in.

**Comment by MorrisJobke** [comment] 2015-03-19 12:16
cc @jancborchardt

**Comment by jancborchardt** [comment] 2015-03-19 12:34
It’s added to prevent accidental zooming. For example native apps can’t be zoomed either (except by built-in 3rd party accessibility apps) so web apps should not be either, just because they live in a browser.

**Comment by DeepDiver1975** [comment] 2015-03-20 11:30
case closed? @jancborchardt @Volker-E

**Comment by Volker-E** [comment] 2015-03-22 19:50
@DeepDiver1975  With the input of @jancborchardt it seems that the decision was made earlier.
In detail the decision between being a website or trying to get close to a web app living in a browser. 

My standpoint is, that people are used to zooming in the browser on the smartphone and the case of accidentally zooming is far more uncommon than the wish to zoom in, in order to have ease of interaction.
That applies not only to users with visual disabilities or impairment, let's take for example the ownCloud Demo at https://demo.owncloud.org/index.php/apps/files/#//Demo%20Image%20-%20ccc.jpg 

With the current settings you're not able to zoom in on the image, although that's a very common usecase of image apps.
Therefore I'd propose to try a higher maximum-scale setting/getting rid of maximum scale setting and see how many users giving feedback on that as bug rather than feature.

**Comment by jancborchardt** [comment] 2015-03-23 10:42
I totally agree with the zooming in for images usecase – and we should do that rather than allow zooming in general. I think @oparoz implemented that in the new Gallery app. @oparoz does that work on mobile?

**Comment by oparoz** [comment] 2015-03-23 12:15
Pinch to zoom works on iPads only unfortunately. I'd love it if someone could make it work on more devices.
Zooming and Fullscreen modes are available via keyboard shortcuts. It works on mobile, but you need a keyboard... and zooming mode alternates between filling the screen and real-size, so you can't zoom in on a panoramic picture which is filling the screen on a mobile device which is not an iPad.
Requests can be filled here: https://github.com/interfasys/galleryplus/issues

**Comment by jancborchardt** [comment] 2015-03-23 14:00
@oparoz aren’t there other js zoom/gesture libraries which work on other devices as well?

**Comment by oparoz** [comment] 2015-03-23 14:04
@jancborchardt - the problem is that it's the bigshot library which is controlling the gestures and it's apparently not detecting all possible events. I played with the library once, but couldn't figure it out.
It's also possible there is a conflict between the standard controls and the library.

**Comment by jancborchardt** [comment] 2015-05-01 22:35
I’m closing this since the general interface should just not be zoomable. However, the Gallery or other viewers should make it possible to zoom images.

**Closed by jancborchardt** 2015-05-01 22:35 UTC
Labels: design, needs info
