### ISSUE TITLE
Can't upgrade database from OC8.0.2 to OC8.0.3

### ISSUE THREAD

**Issue by foux** [owncloud/core#16157] opened 2015-05-07 11:52 UTC
### Steps to reproduce
1. Upgrade Owncloud from 8.02 to 8.03
2. Launch upgrade procedure on website

### Expected behaviour
The database should be upgraded and I should be prompted to log in

### Actual behaviour
SQL error while upgrading :

```An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_hsa7jxqes66dz` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.```

### Server configuration
**Operating system**: Linux

**Web server:** NGinx

**Database:** MySQL

**PHP version:** 5.5.24

**ownCloud version:** 8.0.3

**Updated from an older ownCloud or fresh install:** Updated from 8.0.2

**List of activated apps:** N.A.

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => '52a6f655cc69b',
  'passwordsalt' => 'xxxxx',
  'datadirectory' => '/home/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mailserv.tfdn.org:993/imap/ssl}',
      ),
    ),
  ),
  'loglevel' => '0',
  'log_rotate_size' => 104857600,
  'trusted_domains' => 
  array (
    0 => 'owncloud.tfdn.org',
  ),
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tfdn.fr',
  'secret' => 'xxxxx',
);
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Safari

**Operating system:** OS X

**Comment by LukasReschke** [comment] 2015-05-07 11:53
Duplicate of https://github.com/owncloud/core/issues/16008, see https://github.com/owncloud/core/issues/16008#issuecomment-99198576 and https://github.com/owncloud/documentation/pull/1109 ("Files changed") for a work-around.

**Closed by LukasReschke** 2015-05-07 11:53 UTC
