### ISSUE TITLE
[QA] sharing sidebar: social sharing icons are partially obscured

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38956] opened 2021-07-08 01:02 UTC
Seen in 10.8.0 beta2

![image](https://user-images.githubusercontent.com/1108546/124846244-b20ab000-df98-11eb-8525-5c15feeea993.png)

----
In 10.7.0 the icons were properly raised to be completely visible:

![image](https://user-images.githubusercontent.com/1108546/124846312-d6668c80-df98-11eb-85be-2c003a5c6d0b.png)

**Comment by JanAckermann** [comment] 2021-07-08 12:46
@jnweiger which browser do you use? cant reproduce in chrome
![image](https://user-images.githubusercontent.com/26169327/124923924-368e1a80-dffb-11eb-8076-95f0962d9647.png)

**Comment by JanAckermann** [comment] 2021-07-08 21:28
@phil-davis can you confirm this is an existing issue? Struggling with reproducing

**Comment by phil-davis** [comment] 2021-07-09 03:13
![Screenshot from 2021-07-09 08-58-06](https://user-images.githubusercontent.com/1535615/125017961-dbf4cd00-e093-11eb-87d7-006a804d4349.png)

**Comment by JanAckermann** [comment] 2021-07-09 08:02
That's kind of weird, I can't see this UI glitch on Version 91.0.4472.114 (Official Build) for Linux Mint (64-bit)

**Comment by JanAckermann** [comment] 2021-07-09 08:24
Fixed via: https://github.com/owncloud/core/pull/38948

**Closed by JanAckermann** 2021-07-09 08:24 UTC
