### ISSUE TITLE
Make it possible to configure additional parameters over autoconfig.php

### ISSUE THREAD

**Issue by duritong** [owncloud/core#13295] opened 2015-01-12 21:01 UTC
Hi

to automate installations it should be possible to configure a broad range of configs over autoconfig.php

As discussed here: http://forum.owncloud.org/viewtopic.php?f=26&t=20507

**Comment by LukasReschke** [comment] 2015-01-12 21:02
I guess this is a duplicate of https://github.com/owncloud/core/issues/8022 - right?

**Closed by LukasReschke** 2015-01-12 21:02 UTC

**Comment by duritong** [comment] 2015-01-12 21:25
Jeez, I was searching for autoconf, but should have searched for autoconfig. Sorry for the noise...
