### ISSUE TITLE
exclude the temporary directory from the integrity check

### ISSUE THREAD

**Issue by wolkenschieber** [owncloud/core#29079] opened 2017-09-22 07:14 UTC
### Description

Owncloud reports code integrity problems. The list of invalid files shows following entries:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- temp/oc_tmp_zNnxpv-folder/.htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [temp/oc_tmp_zNnxpv-folder/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => b3167848ffb3a55bdaf4b5617436bfa53442f0026507e51c706b7720f021524b4ead31f8a2f545188f4af0b00928bee67b0110a4637dba3990a08e6472cd7a0d
                        )

                )
        )
)
```

Interesstingly the `oc_tmp` directory is only cretaed and used during the integrity check. It is immediately removed after the check completes. Nevertheless the temp file is reported.

So basically the integrity check is failing itself.

### Server configuration
**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache 2.4.23

**Database:**
Postgresql 9.5

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3.3

**Updated from an older ownCloud or fresh install:**
Updated from 9.2

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04

**Signing status (ownCloud 9.0 and above):**
unknown

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "515b25c0ad050",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "hashingCost": 10,
        "datadirectory": "\/var\/www\/owncloud\/data",
        "tempdirectory": "\/var\/www\/owncloud\/temp",
        "version": "10.0.3.3",
        "dbtype": "pgsql",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 7200,
        "session_keepalive": true,
        "mail_smtpdebug": false,
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "auto, auto",
        "versions_retention_obligation": "auto",
        "appcodechecker": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "log.condition": {
            "shared_secret": "***REMOVED SENSITIVE VALUE***",
            "users": [
                "sample-user"
            ],
            "apps": [
                "files"
            ]
        },
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": true,
        "cron.lockfile.location": "",
        "log_rotate_size": false,
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "maintenance": false,
        "singleuser": false,
        "cache_path": "",
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "1.7.0",
        "filesystem_check_changes": 1,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/www\/owncloud",
        "mount_file": "data\/mount.json",
        "filesystem_cache_readonly": false,
        "theme": "",
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "debug": false,
        "trusted_domains": [
            "DOMAIN.TLD",
            "DOMAIN2.TLD"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_domain": "DOMAIN.TLD"
    }
}

```

**List of activated apps:**
```
Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by kdslkdsaldsal** [comment] 2017-09-22 07:21
Hi,

this is caused by your used:

``"tempdirectory": "\/var\/www\/owncloud\/temp",``

I guess you shouldn't put the temp directory within the ownCloud directory itself.

Additionally a short hint:

It seems you have copied over large parts of the config.sample.php to config.php. This is strongly discouraged:

``
Only manually add configuration parameters to config/config.php if you need to use a special value for a parameter. Do not copy everything from config/config.sample.php . Only enter the parameters you wish to modify!``

-> https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html

**Comment by wolkenschieber** [comment] 2017-09-22 07:35
@kdslkdsaldsal thanks for your fast reply. I set the temporary directory to `/tmp/owncloud` and the message is gone. Nevertheless I'd recommend to exclude the temporary directory from the integrity check.

Regarding the configuration file: Yes it's a copied sample from the initial installation version ~8. For excuse I've to say that copying and adjusting is much easier than only adding what's needed. Though I guess I should adjust the file though.

**Comment by wolkenschieber** [comment] 2017-09-22 07:35
Closing as caused by misconfiguration.

**Comment by kdslkdsaldsal** [comment] 2017-09-22 08:47
> Nevertheless I'd recommend to exclude the temporary directory from the integrity check.

I think this is a valid point so re-opening here.

> For excuse I've to say that copying and adjusting is much easier than only adding what's needed. Though I guess I should adjust the file though.

The main issue here is, that defaults might change here. E.g. you currently won't get a connection to the new marketplace as you're pointing the appstoreurl to an outdated API:

``"appstoreurl": "https:\/\/api.owncloud.com\/v1",``

**Comment by individual-it** [comment] 2017-09-22 10:00
changed the title as the new topic actually is a request to change that behaviour

**Comment by kdslkdsaldsal** [comment] 2017-09-30 07:00
Closing for now as there is already a pull request which allows to configure excluded folders in the config.php: https://github.com/owncloud/core/pull/29126

If some one ever need to have the tempdirectory within the ownCloud directory it can be added there.

**Closed by kdslkdsaldsal** 2017-09-30 07:00 UTC
