### ISSUE TITLE
Do not trust domain name

### ISSUE THREAD

**Issue by kmg76** [owncloud/core#40256] opened 2022-07-29 09:00 UTC
nginx:1.18.0
mysql:10.5.15-MariaDB-0+deb11u1 Debian 11
php:7.4.30
我在config.php的trusted_domains中添加了信任域名，但访问依旧提示【您正在访问来自不信任域名的服务器。】

'trusted_domains' =>
  array (
    0 => '192.168.31.254',
    1 => '192.168.31.29',
  ),

**Comment by cortho** [comment] 2022-08-01 13:56
@kmg76 this is a support case and not a bug (plus you did not fill out the issue template) -> closing.

I think you mixed up your IP and the server IP, see this post as a reference: https://central.owncloud.org/t/trusted-domains/12913/2

For further questions visit https://central.owncloud.org/, if you really find a bug file it here and fill out the issue template.

**Closed by cortho** 2022-08-01 13:56 UTC
