### ISSUE TITLE
[7.0.0] user_ldap: Wizard detects start_tls, but doesn't get used.

### ISSUE THREAD

**Issue by ManoftheSea** [owncloud/core#9872] opened 2014-07-24 17:16 UTC
Upgrade to 7.0.0 on Debian 7 under Nginx in a subdirectory: Working fine with 5.0.3.

### Steps to Reproduce:
* Try to delete old LDAP config and set up a new one.  
* When the server is configured as "ldap://server.notreal.org", the wizard seems to detect the proper port (389) and tls options.
* However, even though the username for login is correct, the bind fails ("Confidentiality Required").  
* Attempt to test connection or log in as user.  Claims to be a password failure.

### Expected Behaviour:
LDAP Connection will upgrade to TLS, user or proxy account will be able to bind, and the spice will flow.  Usernames and groups will be populated, users will be able to authenticate/authorize.

### Actual Behaviour:
During the configuration, LDAP connects.  Then it starts TLS.  Then it ends TLS and tears down the connection.  Then it connects again.  User/password are sent in cleartext.  Server refuses due to "confidentiality required".

### Update
This may only happen during the configuration with the wizard.  I went through the settings again, and although it was telling me configuration incorrect, and Connect worked but Bind failed, I was able to log in as my normal user.

ownCloud log in next comment.

**Comment by blizzz** [comment] 2015-03-24 16:32
Sounds like a duplicate of https://github.com/owncloud/core/issues/7908, please follow up there.

**Closed by blizzz** 2015-03-24 16:32 UTC
Labels: app:user_ldap, bug
