### ISSUE TITLE
Unsharp sidemenu text in Windows 7/8.1 OC8.2

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#20114] opened 2015-10-28 11:54 UTC
This picture was made with demo.owncloud.org. But also happens with my own OC. Dis/Enabling Cleartype doesn't change anything.
![2015_10_28_12_40_42_files_owncloud_opera](https://cloud.githubusercontent.com/assets/11041576/10787614/8f81d95c-7d72-11e5-9093-c6b0d9f43c0e.png)

With Windows 8.1 Firefox 42.0b9 and Opera Beta 33
With Windows 7 Older Chrome Version ~42
Linux Mint Firefox 41

**Comment by PVince81** [comment] 2015-10-28 12:03
@owncloud/designers

**Comment by Bullnados** [comment] 2015-10-28 12:37
Ok i found two of the problems my laptop monitor was set to 50Hz. Second one was disabling Control Panel->All Control Panel Items->Display "Let me choose one scaling level for all my displays"
It was smallest value, after disabling i set it to 100%.

But in Windows it still looks like a different font. Later i wanna take a pic with my DSLR i Hope the difference will be more visible.

**Comment by MorrisJobke** [comment] 2015-10-28 12:54
Let's close this as duplicate of #18954

**Closed by MorrisJobke** 2015-10-28 12:54 UTC
Labels: bug, design
