### ISSUE TITLE
Updating a public share with all parameters removes fields of the share.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#20464] opened 2015-11-11 17:43 UTC
### Steps to reproduce

1.- Create a share of a folder 'Documents' using path and shareType:
```
curl -X POST http://USER:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares -d "path=Documents&shareType=3" 
```
2.- Upload the share
```
curl -X PUT http://USER:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares/SHARE_ID -d "permissions=7&publicUpload=true&password=publicpw&expireDate=2015-12-02"
```
3.- Get info about the share

```
curl -X GET http://USER:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/shares/SHARE_ID  
```
## Expected behaviour
Field "expiration" has a value.

### Actual behaviour
Field "expiration" is empty.

Same with share_with_displayname and share_with, but for public shares this fields has extrange values like  1|$2y$10$97a.nPTUDNJOcy5PwHQrq.kDS4/AI6wkpqnCoFAiYd0g.Idv53cTe , not sure if they are needed as well.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

Happening also in master branch.

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Server logs**
```

```

cc @rullzer

**Comment by PVince81** [comment] 2015-11-12 08:55
The strange value is actually the encoded password for link shares.

@rullzer @schiesbn can you have a look at the missing expiration date ?

**Comment by PVince81** [comment] 2015-11-12 08:56
@SergioBertolinSG looks like you are still testing on RC1 ? Please make sure to test on RC2 instead.
Or did you copy the wrong version string ?

**Comment by rullzer** [comment] 2015-11-12 08:57
This is expected behaviour. As it says on the API page:

```
Note

Only one of the update parameters can be specified at once.
```

**Comment by SergioBertolinSG** [comment] 2015-11-12 08:58
@PVince81 yes sorry, RC2.

**Comment by rullzer** [comment] 2015-11-12 08:58
And indeed the weird sting is the password. We store that internally in the share_with (which is a bit weird). I would like to remove it but that would break the API. So for now it needs to stay :(

**Comment by SergioBertolinSG** [comment] 2015-11-12 09:02
> This is expected behaviour. As it says on the API page:

Oh really? But the request is accepted anyway and removes the other fields.

I find more useful to be able to update all parameters at once instead of rejecting requests with more than one.

**Comment by rullzer** [comment] 2015-11-12 09:32
@SergioBertolinSG ok yeah you are right we should throw an error if we don't support it I agree. But we won't fix that for 8.2.1 (this will be 9.0 stuff).

I agree that it would be better to update everything. But that is just not how the API was designed way back. This is on my todo for a possible future v2 of the API. But it is not in the current scope.

**Comment by SergioBertolinSG** [comment] 2015-11-12 09:47
Ok thanks @rullzer I'll modify the failing test then.

**Comment by rullzer** [comment] 2015-11-12 09:48
Awesome thanks!

**Comment by rullzer** [comment] 2016-02-02 09:26
In 9.0 this should no longer happen. As the webUI now also just posts all values.

**Comment by rullzer** [comment] 2016-03-23 11:36
Closing as this is fixed

**Closed by rullzer** 2016-03-23 11:36 UTC
Labels: enhancement, feature:sharing
