### ISSUE TITLE
Thumbnail of shared file not updated on change

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18633] opened 2015-08-28 16:22 UTC
1. Upload a picture
2. Share it with someone
3. Other person edits file
4. You still see the initial thumbnail image, even in the detail view

@oparoz @georgehrke

**Comment by oparoz** [comment] 2015-08-29 14:04
On master, you shouldn't get the old one in the slideshow. If that's the case ,then it's a regression in Gallery.

Regarding the thumbnail, there is already a ticket about it. I think a hook is missing in Preview.

**Comment by PVince81** [comment] 2015-09-22 09:40
Wasn't there a recent fix for this ?

**Comment by PVince81** [comment] 2015-09-22 09:42
Might or might not be related: https://github.com/owncloud/core/issues/18759

**Comment by PVince81** [comment] 2015-09-22 10:47
Still happening on master (67231ed9a75eafe5b417e4525e3d80b1a3f8826b)

**Comment by oparoz** [comment] 2015-09-26 14:45
Duplicate of https://github.com/owncloud/core/issues/14572

**Closed** 2015-09-26 14:46 UTC
Labels: 1 - To develop, app:files, bug, feature:previews, sharing
