### ISSUE TITLE
[Login screen] Login Arrow  should be located in the same box in both OC server versions

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18628] opened 2015-08-28 14:37 UTC
Login arrow appears next to Password textbox in community version

![captura de pantalla 2015-08-28 a las 16 09 14](https://cloud.githubusercontent.com/assets/10596560/9548774/b2c79c30-4da2-11e5-8ef7-2d6b1c5f4afb.png)

"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""

Login arrow appears next to username textbox in EE version

![captura de pantalla 2015-08-28 a las 16 06 15](https://cloud.githubusercontent.com/assets/10596560/9548842/076b16b8-4da3-11e5-9562-4a4e100f8554.png)

"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"

**Comment by PVince81** [comment] 2015-08-30 10:35
@jancborchardt

**Comment by jancborchardt** [comment] 2015-08-30 13:56
Closing as duplicate of https://github.com/owncloud/core/issues/18629

**Comment by davitol** [comment] 2015-08-30 14:00
I do not consider it duplicated, one is about the location inside/outside the box. This one is about why the arrow appears in different boxes depending on OC server version (User name or Password textbox)

**Comment by jancborchardt** [comment] 2015-08-30 16:59
It’s still basically the same problem, so let’s please keep it to one issue. :)

**Closed by jancborchardt** 2015-08-30 16:59 UTC
Labels: bug, design, sev4-low
