### ISSUE TITLE
File is not synced

### ISSUE THREAD

**Issue by kalletabur** [owncloud/core#11159] opened 2014-09-18 14:28 UTC
File is not synced from client to server. Client error message
11:35 AM se/only.xlsx Documents The server did not acknowledge the last chunk. (No e-tag were present). File previous version is 2 weeks old

### Steps to reproduce / Expected/Actual behaviour
Don't know how to reproduce. Should be ordinary sync usage

#### ownCloud log (data/owncloud.log)
Because earlier log entries are strange so I'll put these in order they appear in owncloud.log file - first entries of that file to last one (duplicated entries are not included)

```{"reqId":"54080ae200e70","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Documents\/se\/~$only.xlsx' is not readable !!!","level":0,"time":"2014-09-04T06:46:58+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/~$only.xlsx"}
{"reqId":"54080ae315d76","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Documents\/se' !!! \ncache: Array\n(\n    [fileid] => 6001\n    [storage] => home::x.user\n    [path] => files\/Documents\/se\n    [parent] => 105\n    [name] => se\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 4779140\n    [mtime] => 1409813218\n    [storage_mtime] => 1409813218\n    [encrypted] => \n    [unencrypted_size] => 3573504\n    [etag] => 54080ae2c6d13\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1409813219\n    [size] => -1\n    [etag] => 54080ae30f1fd\n    [storage_mtime] => 1409813219\n    [parent] => 105\n)\n","level":0,"time":"2014-09-04T06:46:59+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/only.xlsx"}
{"reqId":"54080ae315d76","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Documents\/se\/only.xlsx' is not readable !!!","level":0,"time":"2014-09-04T06:46:59+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/only.xlsx"}
{"reqId":"54080ae315d76","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Documents\/se\/only.xlsx' !!! \ncache: Array\n(\n    [fileid] => 13177\n    [storage] => home::x.user\n    [path] => files\/Documents\/se\/only.xlsx\n    [parent] => 6001\n    [name] => only.xlsx\n    [mimetype] => application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\n    [mimepart] => application\n    [size] => 20896\n    [mtime] => 1409813219\n    [storage_mtime] => 1409813219\n    [encrypted] => 1\n    [unencrypted_size] => 15617\n    [etag] => 54080ae425498\n)\n \ndata: Array\n(\n    [mimetype] => application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\n    [mtime] => 1409813217\n    [size] => 20896\n    [etag] => 54080ae42edfe\n    [storage_mtime] => 1409813217\n    [parent] => 6001\n)\n","level":0,"time":"2014-09-04T06:47:00+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/only.xlsx"}
{"reqId":"54080b1c38539","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Documents\/se\/~$only.xlsx' !!! \ncache: Array\n(\n    [fileid] => 13176\n    [storage] => home::x.user\n    [path] => files\/Documents\/se\/~$only.xlsx\n    [parent] => 6001\n    [name] => ~$only.xlsx\n    [mimetype] => application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\n    [mimepart] => application\n    [size] => 244\n    [mtime] => 1409813276\n    [storage_mtime] => 1409813276\n    [encrypted] => 1\n    [unencrypted_size] => 165\n    [etag] => 54080b1e09b51\n)\n \ndata: Array\n(\n    [mimetype] => application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\n    [mtime] => 1409813275\n    [size] => 244\n    [etag] => 54080b1e160c5\n    [storage_mtime] => 1409813275\n    [parent] => 6001\n)\n","level":0,"time":"2014-09-04T06:47:58+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/~$only.xlsx"}
{"reqId":"54080b4875a9d","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Documents\/se\/.~lock.only.xlsx#' is not readable !!!","level":0,"time":"2014-09-04T06:48:40+00:00","method":"PUT","url":"\/remote.php\/webdav\/Documents\/se\/.~lock.only.xlsx%23"}
{"reqId":"54080b927c7d4","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_versions\/Documents\/se' !!! \ncache: Array\n(\n    [fileid] => 6050\n    [storage] => home::x.user\n    [path] => files_versions\/Documents\/se\n    [parent] => 725\n    [name] => se\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 2505264\n    [mtime] => 1409813381\n    [storage_mtime] => 1409813381\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 54080b86970ab\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1409813384\n    [size] => -1\n    [etag] => 54080b927c36b\n    [storage_mtime] => 1409813384\n    [parent] => 725\n)\n","level":0,"time":"2014-09-04T06:49:54+00:00","method":"DELETE","url":"\/remote.php\/webdav\/Documents\/se\/.~lock.only.xlsx%23"}
{"reqId":"5408282eeaec8","app":"files_sharing","message":"File source not found for: \/files\/Documents\/se\/only.xlsx","level":0,"time":"2014-09-04T08:51:59+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Shared\/se"}

{"reqId":"541ac7ffb6252","app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_versions\/Documents\/se' !!! \ncache: Array\n(\n    [fileid] => 6050\n    [storage] => home::x.user\n    [path] => files_versions\/Documents\/se\n    [parent] => 725\n    [name] => se\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 2500184\n    [mtime] => 1411036713\n    [storage_mtime] => 1411036713\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 541ab649bf218\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1411036747\n    [size] => -1\n    [etag] => 541ac7ffb5fb0\n    [storage_mtime] => 1411036747\n    [parent] => 725\n)\n","level":0,"time":"2014-09-18T11:54:39+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/ajax\/getVersions.php?source=%2FDocuments%2Fse%2Fonly.xlsx&start=0"}
{"reqId":"541ac80137794","app":"core","message":"Generating preview for \"\/Documents\/se\/only.xlsx.v1409814055\" with \"OC\\Preview\\Unknown\"","level":0,"time":"2014-09-18T11:54:41+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview.png?file=%2FDocuments%2Fse%2Fonly.xlsx&version=1409814055"}
{"reqId":"541ac80137794","app":"core","message":"OC_Image->fixOrientation() No readable file path set.","level":0,"time":"2014-09-18T11:54:41+00:00","method":"GET","url":"\/index.php\/apps\/files_versions\/preview.png?file=%2FDocuments%2Fse%2Fonly.xlsx&version=1409814055"}
```

### Server configuration
Debian 7.5 + nginx + php5-fpm (5.4.4-14+deb7u11) + MySQL + ownCloud 6.0.4 (stable)

### Client configuration
OpenSUSE 13.1, ownCloud v. 1.6.3, file created using Excel over Crossover

**Comment by Moiwouam** [comment] 2015-01-26 02:43
Same issue here.
I confirm the workaround given by @simonclausen is working (file renaming).

**Comment by michielappelman** [comment] 2015-01-26 21:15
Having the same issue. Turning off GZIP did not work, renaming a file did. Moving the directory containing non-syncable files does not work either. Would appreciate any pointers on how to debug this further, the logs remain silent except for some mention of "Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found" but not at the same rate as the errors in the client.

**Comment by michielappelman** [comment] 2015-01-30 10:53
Funny thing that this caused as well: my ownCloud client says I have only used 943 MB of my storage on the server but the actual size of the data directory for my user has grown to >5GB. The biggest directories are the ones with files in them that have run into this issue and apparently are getting synced over and over again without being confirmed.

I have now renamed all the files with a 'new_' prefix and all are syncing correctly now. Only thing that's left is to clean up the dir's on the server....

**Comment by PVince81** [comment] 2015-03-28 11:19
Note: for the GZIP issue an additional header will be introduced in 8.1 (#15168)

**Comment by PVince81** [comment] 2015-08-03 14:24
Is this still happening in 7.0.7, 8.0.5 or 8.1 ?

**Comment by MorrisJobke** [comment] 2015-12-11 13:46
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!

**Closed by MorrisJobke** 2015-12-11 13:46 UTC
Labels: bug
