### ISSUE TITLE
User mail address can not be changed

### ISSUE THREAD

**Issue by terfendail** [owncloud/core#19193] opened 2015-09-19 16:58 UTC
In case user ability to change full name is disabled in the config file there is no way to update email address for existing user.

User unable to update email in personal tab (that looks WAD)
But administrator also unable to update email since email field isn't showed in admin panel due to CSS property.

**Comment by RealRancor** [comment] 2015-09-19 18:09
Please fill out the issue template:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "Guidelines for Contributing" which are linked in the yellow box when creating a new issue.

**Comment by terfendail** [comment] 2015-09-22 09:51
### Steps to reproduce
1.Disable user's ability to change account full name in owncloud/config/config.php
2.Login as administrator
3.Try to change email at "Personal" settings panel
4.Try to change email for the same user at "Users" panel

### Expected behaviour
There should be way to change email in "Users" panel or at least in "Personal" panel

### Actual behaviour
There is no visible email field in "Users" panel at all.
In "Personal" panel email field is shown as active. But if one tries to update the email error message  "unable to change mail address" appears(it looks inconsistent, cause if user can't update email the field shouldn't be editable).

### Server configuration
**Operating system**:Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** Postgres 9.3

**PHP version:** 5.5

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** manually updated from 8.0.4(docroot content unpacked from tar file, database converted with owncloud on first access)

**List of activated apps:**
Enabled: - activity: 2.0.2
 - calendar: 0.7.3
 - chat: 0.4.0.0
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - music: 0.3.7
 - roundcube: 2.6.1
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - bookmarks
 - encryption
 - external
 - files_locking
 - gallery
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**
 'overwriteprotocol' => 'https',
 'dbtype' => 'pgsql',
 'version' => '8.1.3.0',
 'installed' => true,
 'forcessl' => true,
 'forceSSLforSubdomains' => true,
 'mail_smtpmode' => 'smtp',
 'mail_smtpsecure' => 'tls',
 'blacklisted_files' =>
 array (
   0 => '.htaccess',
 ),
 'default_language' => 'en',
 'defaultapp' => 'files',
 'trashbin_retention_obligation' => 30,
 'trashbin_auto_expire' => true,
 'check_for_working_webdav' => true,
 'check_for_working_htaccess' => true,
 'config_is_read_only' => false,
 'enable_avatars' => true,
 'allow_user_to_change_display_name' => false,
 'appcodechecker' => false,
 'appstoreenabled' => true,
 'appstoreurl' => 'https://api.owncloud.com/v1',
 'apps_paths' =>
 array (
   0 =>
   array (
     'path' => '...',
     'url' => '...',
     'writable' => true,
   ),
 ),
 'knowledgebaseenabled' => true,
 'theme' => '',
 'maintenance' => false,
 'singleuser' => false,
 'loglevel' => 2,
 'log_query' => false,
 'cron_log' => true,
 'log_rotate_size' => false,
 'logdateformat' => 'F d, Y H:i:s',
 'filesystem_check_changes' => 1,
 'enable_previews' => true,
 'preview_max_x' => 1600,
 'preview_max_y' => 1200,
 'preview_max_scale_factor' => 10,
 'preview_max_filesize_image' => 50,

**Are you using external storage, if yes which one:** Smb storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 40

**Operating system:**
Ubuntu 14.04

**Comment by RealRancor** [comment] 2015-09-22 10:36
@terfendail I can't help you with your current issue but please notice the recent discussion about using copied over defaults from config.sample.php into your config.php here: https://github.com/owncloud/core/issues/19187#issuecomment-141895518

At least the following can be removed from your config.php:

```
'blacklisted_files' =>
array (
0 => '.htaccess',
),
'defaultapp' => 'files',
'trashbin_retention_obligation' => 30,
'trashbin_auto_expire' => true,
'check_for_working_webdav' => true,
'check_for_working_htaccess' => true,
'config_is_read_only' => false,
'enable_avatars' => true,
'knowledgebaseenabled' => true,
'appstoreenabled' => true,
'appstoreurl' => 'https://api.owncloud.com/v1',
'apps_paths' =>
array (
0 =>
array (
'path' => '...',
'url' => '...',
'writable' => true,
),
),
```

**Comment by Rocologo** [comment] 2015-10-14 19:11
I have the sane problem. I cant change the email address. The error message is "Unable to change mail address" ?

I dont get any errors in the owncloud.log /nginx-owncloud.log

**Comment by RealRancor** [comment] 2015-10-14 19:15
@Rocologo Then remove the 'allow_user_to_change_display_name' => false, from your config.php until this is fixed.

**Comment by Rocologo** [comment] 2015-10-14 20:41
Thank you, that worked :-)

**Comment by Bugsbane** [comment] 2015-12-12 16:16
Admins no beng able to change a users email address because the option to not let users change their display name is selected in the config file would have to count as a bug. We have multiple users confirming this (which I can, too). It's reproducible. Why is this not tagged as a bug?

**Comment by RealRancor** [comment] 2015-12-12 21:54
@Bugsbane Easy answer: Either no one cares or no one have noticed that this is a bug :-)

**Comment by Bugsbane** [comment] 2015-12-12 22:00
Lol. Touché!

Any idea who would make the most sense to ping?

**Comment by RealRancor** [comment] 2015-12-14 11:16
Mhhh, maybe @PVince81 can help to ping the people.

**Comment by PVince81** [comment] 2015-12-14 12:23
Duplicate of https://github.com/owncloud/core/issues/14127

**Closed by PVince81** 2015-12-14 12:23 UTC
Labels: needs info
