### ISSUE TITLE
Delting huge directory (25GB, 50 000 files) over webinterface impossible

### ISSUE THREAD

**Issue by e-alfred** [owncloud/core#21337] opened 2015-12-22 18:20 UTC
### Steps to reproduce
1. Sync huge directory (for example Git or SVN-Repository, 20+ GB, 50 000 Files) into Owncloud.
2. Try to delete this directory in the Webinterface using a browser.
3. (Not exactly necessary) Log out or close the session in the browser while deletion is still ongoing.
4. (Just for error confirmation) The problem exists even after disabling the trashbin app.
### Expected behaviour

Huge directory should be deleted after some time after clicking "Delete" in the webinterface.
### Actual behaviour

The directory isn't deleted and the circle symbol is active all the time in the current browser session. After some time (days?), the complete directory is still there. The processes of Apache and Mysql consume loads of CPU power (multiple cores on 100%).
### Server configuration

**Operating system**: Debian 8 "Jessie"

**Web server:** Apache 2.4.10 (from default repository)

**Database:** Mysql 5.5.46 (from default repository)

**PHP version:** 5.6.14 (from default repository)

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** 8.1

**List of activated apps:**
Enabled:
- activity: 2.1.3
- bookmarks: 0.6
- calendar: 0.8.1
- contacts: 0.5.0.0
- documents: 0.11.0
- encryption: 1.1.0
- external: 1.2
- files: 1.2.0
- files_clipboard: 0.4.1
- files_external: 0.3.0
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- imprint: 0.2.5
- notifications: 0.1.0
- provisioning_api: 0.3.0
- search_lucene: 0.7.0
- templateeditor: 0.1
  Disabled:
- files_trashbin
- updater
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8bj094mu3d",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_REMOVED SENSITIVE VALUE**_""
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "**_REMOVED SENSITIVE VALUE**_"",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_from_address": "**_REMOVED SENSITIVE VALUE**_",
        "mail_domain": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtphost": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtpport": "25",
        "loglevel": 0,
        "memcache.local": "\OC\Memcache\Redis",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        }
    }
}

**Are you using encryption:** yes
### Client configuration

**Browser:** Firefox 43, Chrome 47

**Operating system:** Kubuntu 14.04.3 LTS

**Comment by rullzer** [comment] 2015-12-22 18:50
Basically this happens because we do a synchronous delete. Which well just times out.

CC: @icewind1991 @PVince81 something we eventually have to look into

**Comment by e-alfred** [comment] 2015-12-22 21:22
Well, how am I supposed to delete something like that? Sync everything onto the client and then deleting everything so the deletion gets synced back to the server? This would be a huge time- and bandwidth-consuming process that makes things really complicated from a user perspective and for an admin explaining that as well.

**Comment by rullzer** [comment] 2015-12-23 06:45
@e-alfred do you have cli access?

If so remove it from the filesystem and then do a `./occ files:scan`

**Comment by PVince81** [comment] 2015-12-23 10:37
This is probably due to the trashbin.
A one shot trial would be to first disable the "Deleted files" app, then delete the folder in the web UI, then reenable the app.

I suspect it might be moving all files to the trashbin and that's what takes time.

**Comment by PVince81** [comment] 2015-12-23 10:38
@schiesbn

**Comment by e-alfred** [comment] 2016-01-04 11:10
@rullzer I have CLI access, so I can do it that way. But if I have to do that every time a user wants to delete a big folder it is just annoying. 

@PVince81 I mentioned in the initial post already that I tried to disable the trashbin app, but the problem didn't go away.

**Comment by e-alfred** [comment] 2016-01-12 12:44
I thought about two solutions to this problem:

1. Only mark deleted files in the database, but leave them where they are without moving. If they get deleted permanently by the user, remove them from the disk.

2. Show a progress bar for any file operations (would be useful for cut, copy, paste as well) including deletion of files to the user on the web interface, maybe with a time estimate and a "cancel" button.

**Comment by PVince81** [comment] 2016-06-14 14:52
Another approach: async file operations https://github.com/owncloud/core/issues/24509

**Comment by PVince81** [comment] 2016-06-14 14:53
Nothing that can be done as part of a bugfix. Moving to 9.2

**Comment by icewind1991** [comment] 2016-06-14 15:22
https://github.com/owncloud/core/pull/25102 improves delete performance if thumbnails are enabled

It should be doable to make deleting thousands of folders work speedly without async operations with more optimizations

**Comment by hodyroff** [comment] 2017-02-28 12:12
Can you retest with 9.1.4 and also with 10.0 Master? I hope some improvement is already there ...
Stupid question: Why would somebody but a git / svn folder into ownCloud? (I get that it can be done, but whats the use case/benefit for that?)

**Comment by PVince81** [comment] 2017-04-20 20:03
improving delete performance is pointless, what we need is a way to push file operations to the background when they are likely to take too long, closing as duplicate of https://github.com/owncloud/core/issues/24509

**Closed by PVince81** 2017-04-20 20:03 UTC
Labels: app:files_trashbin, bug, needs info, performance
