### ISSUE TITLE
Ghost tooltips appear when removing tags.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25183] opened 2016-06-20 08:07 UTC
### Steps to reproduce:

1. Create and assign some tags to a file.
2. Edit tags and click on trashbin icon. (delete them).
3. Click on another file.

### Expected behaviour:
No tooltips appear.

### Actual behaviour
A tooltip appears where it shouldn't.

<img width="297" alt="screen shot 2016-06-20 at 09 57 27" src="https://cloud.githubusercontent.com/assets/9048796/16187053/7357f23c-36ce-11e6-98d6-ac82cf01c09e.png">

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Chrome, Firefox.

**Comment by PVince81** [comment] 2016-06-21 10:46
duplicate of https://github.com/owncloud/core/issues/23639

**Closed by PVince81** 2016-06-21 10:46 UTC
Labels: bug, design, sev4-low
