### ISSUE TITLE
oc 8.2 wont display shared by url files overflowing the browser window size

### ISSUE THREAD

**Issue by krodelabestiole** [owncloud/core#22619] opened 2016-02-24 11:46 UTC
### Steps to reproduce
1. share (by url) a folder containing many files
2. open the url
2. resize the height of the browser window so it is smaller than the file list
3. you won't be able to access the overflowed files just using the scrolling bars

This is particulary annoying when the file list is longer than the screen height because there's no solution to access some files.

### Server configuration
**Operating system**: debian 8.0

**Web server:** apache 2

**PHP version:** 5.6.17

**ownCloud version:**  8.2.2

**Updated from an older ownCloud or fresh install:** updated

**Comment by LukasReschke** [comment] 2016-02-24 11:46
Dupe of https://github.com/owncloud/core/issues/22616

**Closed by LukasReschke** 2016-02-24 11:46 UTC
