### ISSUE TITLE
Can´t change display name as admin

### ISSUE THREAD

**Issue by Bobgermany** [owncloud/core#28516] opened 2017-07-27 20:06 UTC
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
Tell us what should happen
In the User Admin Panel change the display name
### Actual behaviour
Tell us what happens instead
I can´t change the display name
### Server configuration
**Operating system**:
Raspbian
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP5
**ownCloud version:** (see ownCloud admin page)
10.0.2
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nas",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "default_language": "de",
        "trashbin_retention_obligation": "auto, 30",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 2,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "smtp.strato.de",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "overwriteprotocol": "https",
        "updatechecker": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "enable_avatars": true,
        "asset-pipeline.enabled": true,
        "activity_expire_days": 365,
        "quota_include_external_storage": false,
        "versions_retention_obligation": "auto, 7",
        "allow_user_to_change_display_name": false,
        "knowledgebaseenabled": false
    }
}
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Bobgermany** [comment] 2017-07-27 20:09
> "allow_user_to_change_display_name": false,

if i change this setting to:
`"allow_user_to_change_display_name": true,`

i can change the display name in the admin panel

**Comment by phil-davis** [comment] 2017-07-28 01:58
With:
```
"allow_user_to_change_display_name": false
```
1. Login as admin to the webGUI
2. Go to Users page
3. Edit the Full Name of any user and press enter - the edited name is displayed, no error is given.
4. Refresh the page - the old name is shown

Attempted edits do not "stick", but also no error is shown.

Now the question is, what is the requirement when allow_user_to_change_display_name is false:
a) Even the admin role cannot change the display name on the Users page, or
b) The admin role is the only one that can change the display names for users - e.g. via the Users page (or an occ command or directly by API or by whatever interfaces are available)

After defining the requirement, the code can be fixed to meet the requirement.

**Comment by kdslkdsaldsal** [comment] 2017-07-28 07:37
Closing as a duplicate of https://github.com/owncloud/core/issues/27442. Please follow up in there.

**Closed by kdslkdsaldsal** 2017-07-28 07:37 UTC
