### ISSUE TITLE
Password reset is case sensitive

### ISSUE THREAD

**Issue by derekblankmccoy** [owncloud/core#15433] opened 2015-04-07 11:39 UTC
When logging in, the username is not case sensitive. However, when resetting the password, it does take capitalization into account. This is inconsistent and can trip users up.

**Comment by nickvergessen** [comment] 2015-04-07 13:11
@DeepDiver1975 what is actually the intended behaviour here. I see various `LOWER(uid) = LOWER(?)` in the database user backend, but not on:
1. Password update
2. User delete
3. User create

But select, set display name, ... all use lower. Should we just change it to lower on delete and password update aswell?
Changing the create is a bit more critical, since it might be used in several other places later in the code, so the name would be needed to be passed by reference or be lowered always.

**Comment by MorrisJobke** [comment] 2015-10-29 13:01
> But select, set display name, ... all use lower. Should we just change it to lower on delete and password update aswell?

Yep. Needs to be lowered everywhere.

**Comment by michag86** [comment] 2015-11-30 20:59
But I think this is not the source of the Problem.
I have tried this:
```
$iuser = $this->userManager->get($user);
$username = $iuser->getUID();
```

If the username in the database is "user1" and $user is "UsEr1" then $username is always the same as user.
I could not find a way to get the case sensitive userid from the entered userid with the usermanager.

Any idea?

**Comment by MorrisJobke** [comment] 2016-04-20 20:53
Let's close this as a duplicate of #10102 (general case sensitivity user id issue)

**Closed by MorrisJobke** 2016-04-20 20:53 UTC
Labels: bug, sev3-medium
