### ISSUE TITLE
IE 11: Pagination doesn't work on Public Link

### ISSUE THREAD

**Issue by five-team** [owncloud/core#20044] opened 2015-10-26 11:39 UTC
ownCloud 8.2.0
Internet Explorer 11 doesn't shows the pagination.
Also this fixed didn't solved the problem:
https://github.com/owncloud/core/pull/19895

**Comment by yannick67** [comment] 2015-12-14 19:29
have you got a solution ? I have the same problem

**Comment by amlima70** [comment] 2016-02-03 14:01
I've just setup my server and noticed the scroll problem. After disable the pdfviewer (suggested workaround), IE11 still unable to scroll down long shared lists. This ticket is opened since October 2015 without any response to the problem. Are you going to fix it some point in time, or ignoring IE users?

**Comment by LukasReschke** [comment] 2016-02-10 15:06
@owncloud/javascript @MorrisJobke Any IE users?

**Comment by RealRancor** [comment] 2016-02-10 15:18
> or ignoring IE users? 

Best way to motivate people to get something like this fixed :see_no_evil:

**Comment by MorrisJobke** [comment] 2016-02-10 15:49
@Henni Another victim of your fixes ;)

With 3413b76 all works fine - ccfd052 has the broken state. I can confirm that this is broken in current stable8.2 and master.

Removing the `overflow: hidden` in https://github.com/owncloud/core/pull/19611/files#diff-b145bf1a735fa4639d561f4352a0b45fR4 partly solves the issue.

@Henni Could you have a look at this?

**Comment by rcaia** [comment] 2016-02-18 19:24
I have no scroll bars for file lists on public links : ownCloud version 8.2.2, IE, Firefox, Chrome. I have my own theme so I edited styles.css in my theme folder...

Modified hsm-berlin's fix from item #21203 to ::

#body-public #content {
height: initial;
min-height: calc(100vh - 120px);
overflow: visible;
}
footer .info {
display: none;
}

This should fix it?  ... worked for me.

**Comment by Henni** [comment] 2016-02-18 21:57
@MorrisJobke I'm currently working on contacts. I'll take a look when I have time, but it may take a while.

**Comment by LukasReschke** [comment] 2016-02-22 06:56
@MorrisJobke Should we just remove the `overflow: hidden` to address this for now? I myself have no idea at all about CSS...

**Comment by MorrisJobke** [comment] 2016-02-22 07:06
But we then need to test for regressions... Maybe @oparoz or @jancborchardt has a nice idea

**Comment by MorrisJobke** [comment] 2016-02-22 08:00
Fix is in https://github.com/owncloud/core/pull/22548

**Closed** 2016-02-22 09:29 UTC
Labels: browser:ie, bug, in progress, junior job
