### ISSUE TITLE
Time stamps of uploaded files point to the future

### ISSUE THREAD

**Issue by despens** [owncloud/core#19556] opened 2015-10-03 19:28 UTC
### Steps to reproduce
1. Set up owncloud server (CET)
2. Move to different time zone (EST)
3. Upload file via web interface
### Expected behaviour

Time stamps for uploaded files should show a time stamp from the past, like "seconds ago" or "one minute ago".
### Actual behaviour

The time stamps point to the future.
### Server configuration

**ownCloud version:** ownCloud 8.1.3 (stable) 

**Updated from an older ownCloud or fresh install:** Updated from 8.1.1
### Illustration

![selection_728](https://cloud.githubusercontent.com/assets/571494/10264744/533632c4-69e3-11e5-83a3-6e6dc1cec782.png)

**Comment by aspdye** [comment] 2015-10-04 06:12
Ok. This is a bug. Just reproduced that :)

**Comment by oparoz** [comment] 2015-10-04 09:39
Can anyone reproduce on master?

cc @nickvergessen @PVince81 @rullzer

**Comment by PVince81** [comment] 2015-10-05 08:16
Did you log out then logged in again after switching the web UI timezone ?

**Comment by DeepDiver1975** [comment] 2015-10-05 09:05
> Move to different time zone (EST)

Can you please elaborate on what has been changed? THX

**Comment by despens** [comment] 2015-10-10 03:49
@DeepDiver1975: I logged out of OC and one day later changed my computer's time zone setting. After logging in again, these timestamps happened.

**Comment by MorrisJobke** [comment] 2016-02-14 19:26
I don't think we could do much here. If the mtime of the uploaded file is in the future then it is like this. @jancborchardt proposed to show then "seconds ago" but I don't think this is good, because if you messed somewhere with the date it will always show "seconds ago" even if there didn't happened anything.

We just show the time that was told us. Feel free to reopen this if this is still a problem and the clocks of your computers all are fine. I only could reproduce this when manipulating the time in the file cache.

**Comment by jancborchardt** [comment] 2016-02-15 09:39
Sorry @MorrisJobke this is a real issue beyond »fix your clocks« and »we just display what happened«.

Fact of the matter is that stuff like this happens, and showing »in a few seconds« or something like that is highly confusing. Hovering will still expose the real date.

**Comment by nickvergessen** [comment] 2016-02-15 09:45
Not, don't break usages, where the future is used correctly. So if you modify the method, it needs to be an argument defaulting to the old behaviour

**Comment by MorrisJobke** [comment] 2016-02-15 09:49
> Fact of the matter is that stuff like this happens, and showing »in a few seconds« or something like that is highly confusing. Hovering will still expose the real date.

From my point of view the data users supply to us are holy - we should never fix them on our behalf. Even if they are wrong. We should not fix the data or the representation of data just because it looks weird. We are not god - we need to provide maybe the user a way to avoid this in the first place, but not displaying "a few seconds ago" if this is not what they told us. If the user uploads a file with a mtime in the future: that's it.

**Comment by DeepDiver1975** [comment] 2016-02-15 10:21
> Sorry @MorrisJobke this is a real issue beyond »fix your clocks« and »we just display what happened«.

Definitely the real issue is a broken setup - we cannot fix a broken clock setup.

I understand that from an UX pov this is ugly - but the fix is not to fake the data.

**Comment by jancborchardt** [comment] 2016-02-15 10:27
We do not fake the data, we make it human readable/comprehensible.

In most cases (as you can see from above screenshot, as well as what I had in my personal experiences) the clock is just a few seconds or at most minutes off. This results in the »in a few seconds« and »in a minute« display, which is just unnecessary.

Even if it is a broken setup, we should instead show a proper warning (to the admin only, most probably) and not confuse people by showing impossible elements.

**Comment by PVince81** [comment] 2017-04-06 16:36
Closing as "works as designed".

@felixheidecke please reopen if you have a better idea

**Closed by PVince81** 2017-04-06 16:36 UTC
Labels: app:files, bug, design, sev3-medium
