### ISSUE TITLE
Multiple entries in the "Contact Birthdays" calendar 

### ISSUE THREAD

**Issue by robin13** [owncloud/core#26197] opened 2016-09-23 09:37 UTC
### Steps to reproduce
1. Using Contacts 1.4.0.0 and Calendar 1.4.0
2. Add contacts, delete contacts, add (same) contacts again
3. For every time added there is an entry in the Contacts Birthdays calendar
### Expected behaviour

When an address book is deleted with all contacts, the entry in the Contacts Birthdays calendar should be removed.
### Actual behaviour

Every time a contact is added, an additional birthday is added, when a contact is deleted the corresponding calendar entry is deleted, but when an address book is deleted (removing many contacts), the corresponding calendar birthday entries are not removed.
### Server configuration

**Operating system**: Debian 8

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.0.10-1

**Server version:** ownCloud 9.1.0 (stable)

**Calendar version:** 1.4.0

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocwnxfdxv934',
  'passwordsalt' => '***************************',
  'secret' => '********************',
  'trusted_domains' => 
  array (
    0 => '*****************.net',
  ),
  'datadirectory' => '/mnt/data/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'min 5, max 30, auto',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => '*************',
  'updatechecker' => false,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by RealRancor** [comment] 2016-09-23 10:48
@robin13 @tcitworld Duplicate of https://github.com/owncloud/core/issues/25834 ?

**Comment by tcitworld** [comment] 2016-09-23 11:29
Seems so. @robin13 can you post your scenario on #25834 ? Will close here afterwards.

**Comment by RealRancor** [comment] 2016-11-03 16:30
@tcitworld It seems @robin13 already posted in https://github.com/owncloud/core/issues/25834 so this could be closed.

**Closed** 2016-11-03 16:42 UTC
Labels: app:dav, bug
