### ISSUE TITLE
OC6 beta3 - External storage - Google Drive - handling of duplicate files need to be fixed/improved

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#5793] opened 2013-11-10 17:46 UTC
## Expected behavior

ownCloud should be able to handle duplicate files properly, which can be uploaded to a Google Drive.

## Actual behavior

Once files with duplicate names exist on a Google Drive, ownCloud could not handle it properly nor is at least one of these files displayed. 

![20131110_oc_google_drive_file_comparission](https://f.cloud.github.com/assets/2572764/1509041/d2b2b95e-4a2e-11e3-8fa7-6f0a9889e276.png)

The following error message can be found in the log file multiple times:

```php
{"app":"files_external","message":"Ignoring duplicate file name: Photo-10-11-13-17-04-45-0.JPG on Google Drive for Google user:...
```

Additionally this PHP notice is displayed when accessing a mounted Google Drive, a moment before the folder content is shown:

```php
Notice: Undefined offset: 0 in /var/www/htdocs/owncloud/lib/private/files/stream/dir.php on line 29
```

Please also check out the following issue which initially pointed me to that problem: https://github.com/owncloud/ios-issues/issues/141

## Steps to reproduce

1. Upload multiple files with the same name to a Google Drive by using e.g. the Google Web-GUI
2. Check how ownCloud displays the Google Drive content and which files are shown.

#### Server Configuration

OS: Linux 2.6.24-24
Web server: Apache2 2.4.6
Database: MySQL 5.1.72
PHP version: 5.4.21
ownCloud version: 6.0 beta3

#### Client Configuration

Browser: Firefox 25.0
Operating system: Windows 7

**Comment by Xenopathic** [comment] 2015-11-11 17:55
@DeepDiver1975 @PVince81 You need to teach your bots some manners :laughing:

**Comment by PVince81** [comment] 2016-04-29 14:48
Duplicate files are ignored by design. There is no way for ownCloud to represent this files locally with the current architecture as we don't have local to remote mappings.

Closing.

**Closed by PVince81** 2016-04-29 14:48 UTC
Labels: app:files_external, bug
