### ISSUE TITLE
Priorise apps with update

### ISSUE THREAD

**Issue by awikatchikaen** [owncloud/core#14520] opened 2015-02-26 08:10 UTC
The new display of apps in the admin menu is great, but like in the 'play store', it would be useful to have the apps to update in the first result.

Or have a special category

**Comment by nickvergessen** [comment] 2015-02-26 08:52
Also the categories dont add an entry to the browser history and a F5 always brings you back to the "installed" list

**Comment by MorrisJobke** [comment] 2015-02-26 16:35
I labelled this as junior job because it is a good possibility to get in touch with the core code and shouldn't be that hard, because the information is already available.

**Comment by jancborchardt** [comment] 2015-06-29 14:03
Closing this as duplicate of https://github.com/owncloud/core/issues/17230 – there’s more discussion in there. @awikatchikaen thanks for reporting, and thanks @RealRancor for pointing me to this issue!

**Closed by jancborchardt** 2015-06-29 14:03 UTC
Labels: enhancement, junior job, settings:apps
