### ISSUE TITLE
Versions app doesn't work

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16653] opened 2015-06-01 10:22 UTC
### Steps to reproduce
0. Change the language of the interface to another language (go to the user's personal page and change the setting there)
1. Upload a file
2. Upload another version of the file
3. Click in the versions link (hovering over the file)

### Expected behaviour
A dropdown with the versions of the file appears

### Actual behaviour
Nothing happens. Versions are created in the FS but don't appear in the web interface

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.6RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by DeepDiver1975** [comment] 2015-06-01 10:49
@jvillafanez can you test this with 7.0.5 as well please? Anything in logs/browser console? THX

**Comment by jvillafanez** [comment] 2015-06-01 11:48
I cannot reproduce the issue neither in 7.0.6RC1 nor 7.0.5 now. The only thing I can figure out is that files_locking app is blocking the access to the file and the web interface gets stuck or doesn't get the response. :confused:

**Comment by DeepDiver1975** [comment] 2015-06-01 11:49
> files_locking app

hmm - was that part of oc7 already? We might want/need to double check if there are some backports required.

Log entries might help in case they are present

**Comment by jvillafanez** [comment] 2015-06-02 08:27
Unless we have a way to force the failure in the files_locking app to check if it's causing this issue, we can close it. If there are no clear steps to reproduce the bug (as it's the case), then it's not a bug.

**Comment by PVince81** [comment] 2015-06-02 15:58
Works for me with 7.0.6RC2 (core + files_locking + files_texteditor).
I picked "French" as the language. What did you use ?
Creating versions work properly (uploaded with both web UI and WebDAV)

@jvillafanez which language (tell me the exact string) did you pick in your initial test ? We had cases in the past where languages caused JS issues and broke functionality.

Are you sure this was just a simply file, or was it shared / encrypted ?

**Comment by PVince81** [comment] 2015-06-02 15:59
Was it a small file or a big file ?
Did you have two browser tabs and have one upload a big file (web UI) while trying to retrieve versions in another tab ? (this might cause a locking situation)

**Comment by jvillafanez** [comment] 2015-06-03 08:23
@PVince81 I was using "castellano" as language.

About the file, I cannot guarantee much: I usually use small files so I'd say less than 1MB and I'm sure that it was less than 10MB. I'm not sure if it was shared or not.

Encryption was disabled, but there might be some previously encrypted files in an external storage that might be causing some other errors. I've tried forcing this, but still can't reproduce the issue.

I was using several browsers with different accounts on the same server.

**Comment by PVince81** [comment] 2015-06-03 09:01
Was the versioned file on external storage ?

**Comment by jvillafanez** [comment] 2015-06-03 10:07
I can't say for sure. I've also checked that without any luck.

**Comment by PVince81** [comment] 2015-06-03 10:09
Hmm... also without any log entries there isn't much we can do but guess.

I you saw the versions on disk but the dropdown didn't show them, maybe something got in the way of retrieving versions.

I suggest we close this for now as it is not reproducible.

**Comment by jnfrmarks** [comment] 2015-06-03 19:32
based on comments, closing for now.  @jvillafanez please reopen if you see this again.

**Closed by jnfrmarks** 2015-06-03 19:32 UTC
Labels: app:files_versions, bug, sev1-critical
