### ISSUE TITLE
Impossible to show all users at once

### ISSUE THREAD

**Issue by crysman** [owncloud/core#24595] opened 2016-05-12 09:53 UTC
### Steps to reproduce
1. go to Users admin panel as an admin account
2. having like 200 users there
3. try to scroll down to somebody beginning with Z - it takes a lot of time and a lot of async loading iterations

### Expected behaviour
Possibility to show all users at once. Personally, I would suggest some "show all" button or similar

### Actual behaviour
Having to scroll down via unpleasant repeated loading iterations

### Server configuration
**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.5.x

**ownCloud version:** (see ownCloud admin page) latest 8.x available

**Updated from an older ownCloud or fresh install:** updated

Related issue: https://github.com/owncloud/core/issues/22401

**Comment by RealRancor** [comment] 2016-05-12 10:03
Looks like similar to here: https://github.com/owncloud/core/issues/24578 which was closed as a duplicate.

**Comment by PVince81** [comment] 2016-05-13 08:08
Duplicate of https://github.com/owncloud/core/issues/14480

**Closed by PVince81** 2016-05-13 08:08 UTC
