### ISSUE TITLE
List of shared folders

### ISSUE THREAD

**Issue by axenta** [owncloud/core#22423] opened 2016-02-16 12:20 UTC
If I share directory which contain 25 subfolders or more then 15 files via email link when I open the link only first 15 directories or files is diplayed in all browsers Chrome, Firefox, IE11. If I click to download all a could download all 25 subdirectories. Please could you fix to to see all shared objects.

ownCloud 8.2.2 (stable) , centos 6.7, Firefox 44.0.2

**Comment by RealRancor** [comment] 2016-02-16 12:31
Very likely a duplicate of #21373 and #21203 which gets fixed in oC 8.2.3 with owncloud/files_pdfviewer#92

If disabling the files_pdfviewer is not solving this then its a duplicate of https://github.com/owncloud/core/issues/22289, https://github.com/owncloud/core/issues/20044 and https://github.com/owncloud/core/issues/22303 where https://github.com/owncloud/core/issues/20044 is still open.

**Closed** 2016-02-16 12:33 UTC

**Comment by axenta** [comment] 2016-02-16 12:54
Thank's a lot.
Disable pdfviewer solved my problem
