### ISSUE TITLE
php /var/www/owncloud/console.php  files:scan broken on 8.1

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#17579] opened 2015-07-11 11:08 UTC
### Steps to reproduce
1. SSH to the server
2. su - www-data -s /bin/bash
3.   php /var/www/owncloud/console.php  files:scan SOMEUSER

### Expected behaviour
Tell us what should happen
it should rescan files from that user

### Actual behaviour
Tell us what happens instead
It will rescan files from ALL users 

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:**
apache 2.4.7-1ubuntu4.4
**Database:**
mysql 5.5.43-0ubuntu0.14.04.1
**PHP version:**
5.5.9+dfsg-1ubuntu4.11

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.0 (stable)  [8.1.0-2]

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.4
**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - files: 1.1.9
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 12
 - templateeditor: 0.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No

**Comment by karlitschek** [comment] 2015-07-11 14:14
@icewind1991 any idea?

**Comment by PVince81** [comment] 2015-07-13 05:48
Duplicate of https://github.com/owncloud/core/issues/17414

**Closed by PVince81** 2015-07-13 05:48 UTC
Labels: bug
