### ISSUE TITLE
Issue with list of mixed users (local and LDAP)

### ISSUE THREAD

**Issue by Resquer** [owncloud/core#20040] opened 2015-10-26 10:22 UTC
I have sucessfully upgraded from 8.1.3 to 8.2, and now I can not to see users in the "Users" panel. I have both local and LDAP users, and some of them are included in additional groups. If I choose some group directly, everything is OK, I can see users, but if I try to see ALL users, the spinner rotates continiously and never ends. In the error log I see "Error PHP Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at /var/www/apps/user_ldap/lib/access.php#698".
System works normally, but I can not see and manage some accounts (which is not included to any additional group).

Server configuration

Operating system:  Ubuntu 14.04.3 LTS

Web server: Apache/2.4.7 (Ubuntu)

Database: 5.5.44-0ubuntu0.14.04.1 

PHP version: PHP 5.5.9-1ubuntu4.13 (cli) (built: Sep 29 2015 15:24:49)

ownCloud version: 8.2

Updated from an older ownCloud or fresh install: update (from 8.1.3)

**Comment by mark0n** [comment] 2015-10-27 01:01
I'm seeing the same error message since upgrading to 8.2 whenever LDAP users try to log on. The web interface presents a blank page to them making OC unusable for them.

Debian Wheezy, NGINX

php occ ldap:show-config
+-------------------------------+----------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                        |
| hasPagedResultSupport         |                                                                                                          |
| homeFolderNamingRule          |                                                                                                          |
| lastJpegPhotoLookup           | 0                                                                                                        |
| ldapAgentName                 |                                                                                                          |
| ldapAgentPassword             | ***                                                                                                      |
| ldapAttributesForGroupSearch  |                                                                                                          |
| ldapAttributesForUserSearch   |                                                                                                          |
| ldapBackupHost                |                                                                                                          |
| ldapBackupPort                |                                                                                                          |
| ldapBase                      | ou=people,dc=mydomain,dc=net                                                                        |
| ldapBaseGroups                | ou=people,dc=mydomain,dc=net                                                                        |
| ldapBaseUsers                 | ou=people,dc=mydomain,dc=net                                                                        |
| ldapCacheTTL                  | 600                                                                                                      |
| ldapConfigurationActive       | 1                                                                                                        |
| ldapEmailAttribute            | mail                                                                                                     |
| ldapExperiencedAdmin          | 0                                                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                                                          |
| ldapExpertUUIDUserAttr        |                                                                                                          |
| ldapExpertUsernameAttr        |                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                       |
| ldapGroupFilter               |                                                                                                          |
| ldapGroupFilterGroups         |                                                                                                          |
| ldapGroupFilterMode           | 0                                                                                                        |
| ldapGroupFilterObjectclass    |                                                                                                          |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                             |
| ldapHost                      | ldap.mydomain.net                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                          |
| ldapLoginFilter               | (&(&(objectclass=inetOrgPerson)(memberOf=cn=owncloudusers,ou=groups,dc=mydomain,dc=net))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                          |
| ldapLoginFilterEmail          | 0                                                                                                        |
| ldapLoginFilterMode           | 0                                                                                                        |
| ldapLoginFilterUsername       | 1                                                                                                        |
| ldapNestedGroups              | 0                                                                                                        |
| ldapOverrideMainServer        |                                                                                                          |
| ldapPagingSize                | 500                                                                                                      |
| ldapPort                      | 389                                                                                                      |
| ldapQuotaAttribute            |                                                                                                          |
| ldapQuotaDefault              |                                                                                                          |
| ldapTLS                       | 0                                                                                                        |
| ldapUserDisplayName           | displayname                                                                                              |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(memberOf=cn=owncloudusers,ou=groups,dc=mydomain,dc=net))              |
| ldapUserFilterGroups          |                                                                                                          |
| ldapUserFilterMode            | 0                                                                                                        |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                     |
| ldapUuidUserAttribute         | auto                                                                                                     |
| turnOffCertCheck              | 0                                                                                                        |
| useMemberOfToDetectMembership | 1                                                                                                        |
+-------------------------------+----------------------------------------------------------------------------------------------------------+

**Comment by d-tamm** [comment] 2015-11-05 10:28
Same here in 8.1.4. Selcting All Users shows the spinner but no entries. Selecting specific groups shows the group members. Error message:
> Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() at /var/www/owncloud/apps/user_ldap/lib/access.php#709

However, everything else works, including login of LDAP members.

**Comment by camerondw** [comment] 2015-11-06 08:50
I'm getting the same thing as @d-tamm when look at all users. Groups show the users too. Same error message when doing an occ ldap:search.

Running on Ubuntu 14.04.3 LTS, apache2 2.4.7-1ubuntu4.8, php 5.5.9-1ubuntu4.14, mysql 5.5.46, ownCloud 8.1.4.

I have mixed users (ldap and local) but this was not an issue prior to 8.1.4. Something that is complicating matters is there are a dozen ldap users that ownCloud thinks are deleted. If I ldap:search for a current user known to be working, the search returns a result.If I search for an unknown user, the search returns nothing. However if I search for a current user that's in the ldap:show-remnants results then ldap:search spits out a fatal error as per what @d-tamm has. No idea why ldap thinks the user doesn't exist anymore.

**Comment by mark0n** [comment] 2015-11-07 22:36
#20090 seems to be a duplicate of this issue - and it has been fixed :-) I was able to fix this issue by installing the current nightly and setting the configvalue=0 as described above by @camerondw. I'm assuming that this fixes the issue for everyone. Please reopen if that is not the case.

**Closed by mark0n** 2015-11-07 22:36 UTC
Labels: app:user_ldap, bug
