### ISSUE TITLE
[7.0.5] Link in error message is escaped

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#15134] opened 2015-03-23 23:09 UTC
Steps to reproduce:
install OC 7.0.5 with non writable config

Expected result:
Link to a manual displayed properly

Actual result
![link](https://cloud.githubusercontent.com/assets/991300/6792591/a5cb8fd6-d1ca-11e4-8634-73d3d9d1406e.png)

**Comment by PVince81** [comment] 2015-03-28 12:24
duplicate of https://github.com/owncloud/core/issues/11464

**Closed by PVince81** 2015-03-28 12:24 UTC
Labels: bug
