### ISSUE TITLE
Feature Request: Restrict syncing but keep some sharing

### ISSUE THREAD

**Issue by promotion** [owncloud/core#11976] opened 2014-11-05 18:09 UTC
Hi , 
We're planning to use ownCloud for files directory . The main archive of files is located on the server . We have 20 users, however we want to restrict users getting files (syncing) on client machines. All files must be only browsable and viewable when client logs in via WEB interface. Thus even if he installs client - he would be not able to sync(download) any files to his client.  

The other point - sharing via url must remain . 

Is it somehow achievable ? Thanks

**Comment by PVince81** [comment] 2016-10-07 13:58
duplicate of https://github.com/owncloud/core/issues/25873

**Closed by PVince81** 2016-10-07 13:58 UTC
Labels: enhancement
