### ISSUE TITLE
Error in owncloud.log

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#14702] opened 2015-03-05 09:12 UTC
Hi @ all,

I get this error in the owncloud log:

{"reqId":"786793c0e32a64e961e0f1941e201ea6","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:37+00:00"} {"reqId":"41c5dafeb9c76393fb5d3931acca48e6","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:37+00:00"} {"reqId":"1945264c5df40e32b8d086b4a48f3355","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:41+00:00"} {"reqId":"9c0647c577cf6686e4821c15f3873070","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:49+00:00"} {"reqId":"fa7f3ea28c9cec640fd37b8c1b7b509c","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:51+00:00"} {"reqId":"644813f707054ba0cbcb90690a9e29d1","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:54+00:00"} {"reqId":"159707d45d369208592391ae0e28e32b","remoteAddr":"x.x.x.x","app":"core","message":"","level":3,"time":"2015-03-05T09:06:59+00:00"}

This occured in Version 7.0.4 and now on 8.0.1. I cannot see a reason but It must be related to the owncloud client, but from all. Error happens periodically.

Any Ideas how I can determine more details?

Thank you in advance

Cheers,

Pierre

**Comment by PVince81** [comment] 2015-03-05 11:59
@pierrejochem things to try:
1. Install and enable the XDebug module
2. Set "loglevel" to 0
3. Add `define('DEBUG', true);` in config.php

then see whether these log entries contain more info. (don't forget to redisable DEBUG and XDebug afterwards if this is a production server)

**Comment by pierrejochem** [comment] 2015-03-05 12:48
What do you mean with loglevel?

Point 1 + 3 is done, but can't see more details

**Comment by pierrejochem** [comment] 2015-03-05 13:06
I will try this and will post the details.

**Comment by pierrejochem** [comment] 2015-03-05 13:09
Result is:

{"reqId":"367f7e02c4a33b22e37555511e154703","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:28+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"60ef0d66caf57235f5430b007d7395df","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:37+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"bd30efc3e9d7329e0c6e0dd82d664502","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:40+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"1875cad90dfc948058ea4517a603da99","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:41+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"a19e7831c81a6702576e7f3436b87d4d","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:46+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"6d8f090dd6ee53e27c30f0214b54ce76","remoteAddr":"X.X.X.X","app":"core","message":"","level":3,"time":"2015-03-05T13:08:47+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}

**Comment by PVince81** [comment] 2015-03-05 13:59
Thanks... Looks like we'll need to find any exception in the code that has no message, and triggered without message.

Can you provide more info about your setup? Using encryption, quota, external storage ?

**Comment by pierrejochem** [comment] 2015-03-06 07:02
Encryption is disabled, Default Quota is 512MB but this happens with all profiles and I increase the amout if it is not enough. The error happens also with my account and I have enough space.
my user is the only user who is using a samba share at the moment. I see this message @ all users and it is fillig the logfile very fast.

**Comment by pierrejochem** [comment] 2015-03-09 07:40
Any Ideas how I can get more details about the error?

**Comment by pierrejochem** [comment] 2015-03-23 11:49
@nickvergessen Any ideas?

**Comment by nickvergessen** [comment] 2015-03-23 13:49
@PVince81 you changed stuff regarding errors with PROPFIND, iirc?

**Comment by PVince81** [comment] 2015-03-23 15:28
This somewhat reminds me of the missing "quota exceeded" error message, possibly duplicate of https://github.com/owncloud/core/issues/14516

**Comment by pierrejochem** [comment] 2015-03-24 13:23
@PVince81 Does it mean there will be a fix in one of the next updates?

**Comment by PVince81** [comment] 2015-03-24 14:10
There's a fix for https://github.com/owncloud/core/issues/14516 but I'm not 100% sure whether it's the same

**Comment by pierrejochem** [comment] 2015-03-29 13:30
@PVince81 Do you mean this one:

https://github.com/owncloud/core/commit/0f3e36fdfd1c57f5212c495d59b0e5964df8a4ac

?

**Comment by PVince81** [comment] 2015-04-07 09:27
Yes, that one

**Comment by pierrejochem** [comment] 2015-04-07 15:12
Okay, but my problem is that I cannot try this on our production system. Will it be included in one of the next releases?

**Comment by PVince81** [comment] 2015-04-07 15:24
It will be in 8.1.

You can get a patch by appending ".patch" in the URL: https://github.com/owncloud/core/pull/14791.patch

**Comment by pierrejochem** [comment] 2015-04-07 19:32
I will try it tomorrow and let you know the result. Thank you :-)

**Comment by pierrejochem** [comment] 2015-04-08 08:08
Okay, I cannot try this on the production system. It is not cloned via git :-( I tried in manually and this causes an internal server error. So there are dependencies. I have to wait for 8.1 and then I can report whether it is solved or not.

**Comment by MorrisJobke** [comment] 2015-04-21 11:05
@pierrejochem Can I ask you to reopen this ticket if it isn't solved in 8.1. Thanks

**Closed by MorrisJobke** 2015-04-21 11:05 UTC
Labels: bug

**Comment by pierrejochem** [comment] 2015-04-22 09:51
Yes, sure, when is the release date (approximate)?

**Comment by MorrisJobke** [comment] 2015-04-22 10:31
roughly in the beginning of June

**Comment by pierrejochem** [comment] 2015-04-22 11:40
Okay, thank you and I will give feedback after it is installed.
