### ISSUE TITLE
[8.2] Problem on share by link and upload from non user

### ISSUE THREAD

**Issue by jackyes** [owncloud/core#20112] opened 2015-10-28 11:41 UTC
### Steps to reproduce
1. Share by link a folder
2. Enable the ability to others (not logged, ecc) to upload files to this share (checkbox)
3. Try to upload a file on that link (as not logged)

### Expected behaviour
Upload a selected file on the share as not logged in.

### Actual behaviour
Can't upload file as not logged in. 
I can select file by the Arrow button or drag and drop it but nothing happen

### Server configuration
**Operating system**: Debian 8

**Web server:** apache

**Database:** My sql

**PHP version:** PHP 5.6.14

**ownCloud version:** 8.2.0.12

**Updated from an older ownCloud or fresh install:**
Updated from 8.1.3

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - gallery: 14.2.0
  - updater: 0.6

**The content of config/config.php:**

    "system": {
        "instanceid": "***********************",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*******************",
            "*****************",
            "************"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***********",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "*****",
        "mail_domain": "********",
        "mail_smtphost": "******",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Rome",
        "logfile": "\/var\/www\/owncloud\/data\/owncloud.log",
        "loglevel": 0,
        "log_authfailip": true,
        "theme": "",
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

Sorry for my english :(

**Comment by PVince81** [comment] 2015-10-28 12:07
Duplicate of https://github.com/owncloud/core/issues/19922

Fix is here https://github.com/owncloud/core/pull/19956 and will be in 8.2.1

**Closed by PVince81** 2015-10-28 12:07 UTC

**Comment by jackyes** [comment] 2015-10-28 13:32
i have replaced the old files with the ones in #19956 but the problem still occurs. I wait for the 8.2.1 :)

**Comment by PVince81** [comment] 2015-10-28 14:14
Can you check the javascript console in the browser ? Just to make sure you applied the patch correctly

**Comment by jackyes** [comment] 2015-10-28 15:19
javascript console say:
"TypeError: OCA.Files.App is undefined"

**Comment by PVince81** [comment] 2015-10-28 15:22
I guess you probably misapplied the patch.

**Comment by Peac** [comment] 2015-10-30 18:37
I needed a restart of my apache to let the fix work.
