### ISSUE TITLE
Translation of "share" in Webif missinG?

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/core#14730] opened 2015-03-06 13:02 UTC
I have OC 8.01 on Debian ranning in german language. In the wWebif under files i see, that the "share" is not translated:
http://i.imgur.com/iwRZypC.png

I can not find it on teh transifex site. Is it already translated there?

**Comment by MorrisJobke** [comment] 2015-03-06 14:17
I can confirm this.

**Comment by MorrisJobke** [comment] 2015-03-06 14:31
Registered here: https://github.com/owncloud/core/blob/d11f040720b2142bc158d6cd3db63bb977bf937a/apps/files_sharing/js/share.js#L88-L93

**Comment by MorrisJobke** [comment] 2015-03-06 14:33
Yes. It was translated wrong in transifex. https://www.transifex.com/projects/p/owncloud/translate/#de/files_sharing/39506186?q=Share

**Comment by MorrisJobke** [comment] 2015-03-06 14:34
I fixed it in transifex. Should be fixed in master this night.

@DeepDiver1975 Should I backport this fix to stable8?

**Comment by DeepDiver1975** [comment] 2015-03-06 14:58
> @DeepDiver1975 Should I backport this fix to stable8?

yes please - thx

**Comment by MorrisJobke** [comment] 2015-03-06 15:26
I reopened to track this, because the backport is possible tomorrow.

**Comment by MorrisJobke** [comment] 2015-03-09 15:32
Backport is in #14765

**Comment by MegaV0lt** [comment] 2015-03-09 15:48
For me it looks good...

**Comment by MorrisJobke** [comment] 2015-03-11 15:17
Merged

**Closed by MorrisJobke** 2015-03-11 15:17 UTC
Labels: L10n
