### ISSUE TITLE
Cannot delete file by webinterface

### ISSUE THREAD

**Issue by unlimited101-otto** [owncloud/core#25457] opened 2016-07-12 14:24 UTC
I have a file in my cloud which I cannot delete. I tried to rename it first but then I was told that it is locked. I don't know how to reproduce this for another file. Here are my logs:

> Exception: {"Message":"HTTP\/1.1 423 \"anonymized_folder\/anonymized_file.ext\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OC\\Connector\\Sabre\\File->delete()\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(287): Sabre\\DAV\\Tree->delete('verwaltungen\/pa...')\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":320}

How to fix that?

**Comment by RealRancor** [comment] 2016-07-12 15:22
@unlimited101-otto Please fill out the shown issue template providing all necessary infos. Up to now its not even known which ownCloud version you're running and when this error happened.

**Comment by PVince81** [comment] 2016-07-13 07:28
Duplicate of https://github.com/owncloud/core/issues/23679

You might want to post your issue template there instead, but I think the problem is already understood and explained there.

**Closed by PVince81** 2016-07-13 07:28 UTC
