### ISSUE TITLE
Remember file list sorting, show newest first

### ISSUE THREAD

**Issue by NuxRo** [owncloud/core#20836] opened 2015-11-30 13:52 UTC
Hello,

Each and every time I want to check the files in a folder (usually photos) I am interested in the newest ones, yet ownCloud starts with the oldest. If I sort by "last modified" it's OK, but it does not remember the setting. Can this be fixed?

Can also the default behaviour be changed so it shows the most recent files first?

**Comment by PVince81** [comment] 2015-12-02 10:15
I'm pretty sure there was already a ticket with a long discussion on how to do this. Somehow I can't find it any more. @jancborchardt do you remember ?

**Comment by jancborchardt** [comment] 2015-12-02 13:55
I totally agree on this. Is probably a duplicate of https://github.com/owncloud/gallery/issues/197 – cc @oparoz @owncloud/designers

**Comment by jancborchardt** [comment] 2015-12-07 18:13
@PVince81 @MorrisJobke can we make the Files app remember the last sort order?

**Comment by MorrisJobke** [comment] 2015-12-07 23:15
> @PVince81 @MorrisJobke can we make the Files app remember the last sort order?

Per folder or per user?

**Comment by Bugsbane** [comment] 2015-12-08 01:53
I would personally prefer per folder, but with newest first being the default. According to https://github.com/owncloud/core/issues/9243 it seems that this issue was relegated to https://github.com/owncloud/core/issues/17357 although I don't see any discussion of remembering sort order there.

**Comment by PVince81** [comment] 2015-12-08 07:14
> Per folder or per user?

and should it be remembered between different computers or just the one browser ? (cookies vs localStorage vs appconfig)

**Comment by PVince81** [comment] 2015-12-08 07:14
this will also need proper usability testing. I'm not sure everyone will like to have "newest first" by default.

**Comment by Henni** [comment] 2015-12-08 07:27
**In my opinion** a folder should be sorted alphabetically instead of "newest first" by default as most file explorers do it this way.
Furthermore I would like owncloud to share my sorting preferences across browsers/computers (-> appconfig).

**Comment by MorrisJobke** [comment] 2015-12-08 07:31
> Furthermore I would like owncloud to share my sorting preferences across browsers/computers (-> appconfig).

just to sum up:

 * default: alphabetical
 * save the order per folder and per user (so shared folders have the order each user specified)
 * save the order in a cross-browser setting (preferences table)

**Comment by jancborchardt** [comment] 2015-12-08 11:29
Yep @MorrisJobke with more reasoning:

- The default should still be alphabetical. This will not confuse people as being totally different from other file managers. Remembering the change to different sort order will easily accomodate others though.
- The order should be saved per folder. There are folders which make sense sorting by modification date (photos, projects etc) and others which are easier to browse alphabetically.
- The setting should be saved per-user. I don’t want to fiddle with my preferences every time I change a device or log in from another browser. We should not do that anywhere as it’s a strange UX for a web app.

**Comment by jancborchardt** [comment] 2015-12-08 12:44
Is this possible for 9.0?

**Comment by NuxRo** [comment] 2015-12-08 12:47
Thanks

**Comment by oparoz** [comment] 2015-12-08 13:34
- [ ] Include the public API so that apps can either use the setting or offer a better way to manage the setting

**Comment by deMattin** [comment] 2015-12-08 13:35
I like the behaviour in files app like it is now with setting a sorting by session, inherit sorting to subfolder if you navigate and reset on next visit. It's clean and clear.
I personally only sometimes switch sorting in files app for special reasons but usually won't like to see this changed sorting for this single folder on next visit.
It can be confusing, if you as an example only switched to reverse date to search latest file once and go back to the folder a week later.

So a solution for all or more use cases and workflows could be:
1. Leave behaviour like it is (remember sorting during session and folder navigation)
2. give the user the possibility to set his own global default sorting
3. give possibility to remember the sortings per folder - but only as a per user setting!
4. and additional (or at least) give the possibility to reset the settings to default for all folders.
These also are (some of) the possibilities you also have in file browsers on desktops.

Saving a sorting by folder and user as the only possibility is a usecase only some user would prefer and in difference to actual behaviour it can be very confusing and might disturb workflow if you revisit folder some days later - even more, if you don't know about this.

**Comment by jancborchardt** [comment] 2015-12-08 14:54
@deMattin sorry but no. As discussed in this thread and previously before, remembering the last sort order is the most sensible way of working.

A global setting is not »clean and clear« as you mention, no one will want to fiddle with it. Also because this is not a use-case for a global setting because you want to switch it on the fly. And since we have the sorting via the headers already, it would be very strange if we don’t integrate there.

Again – we aim to make ownCloud simply work as expected, not that you need to configure everything manually. Cause people don’t like spending so much time fiddling with minutia like that.

**Comment by deMattin** [comment] 2015-12-08 15:49
I wrote, that the __actual__ behaviour is clean and clear!
There's no real need to change that.

Really simple would be, to leave it, as it is.
And also a really simple and smooth enhancement could be, to only save the sorting order not by file app session like now but save it permanent by user.

Please think of the cases, where this saving sort order different for any folder is really needed and if this should be default for all users!
I know people always sorting by date and users always sorting by name but noone, sorting any folder (permanent) different.

But as always/often, we seem to use computers very different and seem to know very different computer user. ;)

And also as always, you think options does make all complicated. Options are options and no needs. Defaults should fit most needs. But if not, it's always nicer to have options, than to have to live with the workflow some developer think to be the best only because they think, the user is to dump to set some optional options!

**Comment by jancborchardt** [comment] 2015-12-08 17:28
@deMattin this clearly isn’t the case, otherwise this issue wouldn’t be open. I agree with @NuxRo and wanted to have the sorting be remembered since a long time. In case you don’t know, desktop file managers like Nautilus etc also do that.

> But as always/often, we seem to use computers very different and seem to know very different computer user. ;)

Seemingly yes. But then keep in mind I did a lot of the work to design ownCloud the way it is today. And there’s a bunch of people using it, so our direction can’t be all wrong, eh? Besides, I don’t decide based on my own usage, but a mix of what I observe is usable, what looks good, what works well and a bit of future thinking.

> Options are options and no needs. 

However, unnecessary options drown out the really important ones. So it’s not just »always nicer to have options«. Because then when someone wants to really adjust something they can’t find it because it’s not findable in a sea of messy checkboxes and it feels like a half-assed product made by people who couldn’t decide what they wanted to build.

Hope this makes it clear.

**Comment by Bugsbane** [comment] 2015-12-08 17:31
It's not that the user is dumb. It's that every piece of UI you add, is
something more that people have to dig through to find what they need. Just
because I'm smart enough to use a feature, doesn't mean that I want to spend
time searching for it.

> On Dec 8 2015, at 10:49 am, Martin &lt;notifications@github.com&gt; wrote:  

>

> I wrote, that the **actual** behaviour is clean and clear!  
There's no real need to change that.

>

> Really simple would be, to leave it, as it is.  
And also a really simple and smooth enhancement could be, to only save the
sorting order not by file app session like now but save it permanent by user.

>

> Please think of the cases, where this saving sort order different for any
folder is really needed and if this should be default for all users!  
I know people always sorting by date and users always sorting by name but
noone, sorting any folder (permanent) different.

>

> But as always/often, we seem to use computers very different and seem to
know very different computer user. ;)

>

> And also as always, you think options does make all complicated. Options are
options and no needs. Defaults should fit most needs. But if not, it's always
nicer to have options, than to have to live with the workflow some developer
think to be the best only because they think, the user is to dump to set some
optional options!

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/ownclou
d/core/issues/20836#issuecomment-162923738).![](https://github.com/notificatio
ns/beacon/AAYhRWpcQRe0iCFaNo3_N-oy3pmsTHD2ks5pNvOegaJpZM4GrcSU.gif)

**Comment by jospoortvliet** [comment] 2015-12-08 17:51
Agreed with @Bugsbane - and on top of that, options need code, need UI work, need to be maintained too. I'm not super against an option in the config file but I doubt more than 0.001% of the users will ever touch it.

How about this: let's not add an option. If we get requests from users (not in this thread, obviously) to configure it, we can re-open the conversation.

**Comment by deMattin** [comment] 2015-12-08 23:10
@jancborchardt: Most user live with an all in all good software like it is and don't discuss on git or boards. The feature is no problem for me and for others recognizing very fast the "logic" of this feature. I "only" have to remember to reset sorting after each temporary sorting ...
But I know that this is irritating for a group of people like my mom, my older neighbour or colleagues at work (no IT job). And you will never read a post of these users in forums, on git or elsewhere.

What I know are questions, people are asking to me, if they don't understand their computers, And in most cases, I can set something for them and make it working more "simple" or logical for them.
But in this case, I only can explain, but have no chance to set it to a simple and "non intelligent" method.

I also don't like _unnecessary_ options.
I've written a public and free software very long in the past and the most and annoying work has been the "easy" configuration and documentation.
But here there will be implemented a feature to a filemanager, that should be optional, I think.

Who exactly needs it and what usecase is it needed for?

Pictures or videos?
I also __sometimes__ like to sort it reverse date. But if you implement this like described, on later revisit some folders are date sorted (if you set it once for this folder) and others and new folders are sorted by fle name.

Documents or other files?
You sometimes change sorting for different purposes. But do you want to see this (temporary) different sorting next time you revisit this folder?
It has a reason, why name sorting is default and you also think, it should be default.

Further more:
There's no chance to "reset" all folders to default sorting.
There's no way to set another sorting default for all and new folder for people always like to sort (some sort of folders like pictures) different. For them this new feature would be a sort of workaround but not the real solution. So they would like it - but more as a "better this, than nothing".

I really think, you are planning a feature (with code and db entries), that only for some people and usecases is really needed and useful. But you make it as a forced default for all.
And further more it's an behaviour you have no chance to switch it off or at least reset.

Why no single configuration option like "remember folder sorting permanently" for users, who want to have it?

**Comment by Bugsbane** [comment] 2015-12-09 09:39
> Why no single configuration option like "remember folder sorting permanently" for users, who want to have it?

What percentage of users are likely to want and expect an option to throw out changes they've explicitly chosen to make, repeatedly and without any warning?

Doesn't sound like a popular use case to me, compared to say "Hey, that change I made... please keep it until I say otherwise."

**Comment by jospoortvliet** [comment] 2015-12-09 14:05
@deMattin I think you hugely over-estimate how this is confusing or causes extra work. Remembering what the user picks is as non-confusing as it gets and in almost no case (certainly no likely case) does it cause extra work. Adding settings adds barely anything, certainly nothing which helps in a common case, which is why @jancborchardt opposes it and I agree.

You try to think of a case where you want to do something - but you need to analyse these scenario's: ask yourself how much work is is it and how often does it happen.

Let's go over your last two examples:
* there's no chance to reset all folders to default sorting
 Why in $DEITY's name would you want that? Sorry, but that's like the most remote, unlikely thing EVER.
* You can't set a default sorting
 This is probably the only thing I would remotely *consider* as a setting. Some people (like myself) always sort date-descending to always see their most recent files on top. Without this setting, I have to set that for every folder - *once*. Not a big deal, but sure, it'd be nice to have. I'm not sure if it is worth adding, though, as the effort of setting it per folder is minimal and - settings are bad.

And should 'remember sorting per folder' be configurable - let's see when it helps:
* if you want to use a specific sorting in one folder
* if you want a specific sorting in all folders
When is it bad:
* if you want to use a specific sorting in a folder one time but another the other time and the first one again the next time and so on, **alternating**.

Only in the 'bad' scenario do you get to click extra, and that is only assuming the sort you want every other time is the default one by name. If you wanted to alternate between descending-name and ascending-date, the saving per folder would make no difference. Note that if you randomly want a different sorting between two, neither of which is current default, the saving would at least increase your chance of getting what you want.

I think the 'bad' scenario is so insanely unlikely that adding an option is just madness.

And this reply is way too long, as is this conversation. Saving sorting per folder saves the user time in the 99% scenario. Settings can, at best, save a tiny amount of time in 1% of use cases - let's please not add that.

**Comment by oparoz** [comment] 2015-12-09 14:25
> As discussed in this thread and previously before, remembering the last sort order is the most sensible way of working.

Works as long as the setting is kept per user, otherwise it's a disaster as it would have an impact on all users having access to a folder.

> Remembering what the user picks is as non-confusing as it gets and in almost no case (certainly no likely case) does it cause extra work

It only works for very simple, flat hierarchies.

> Without this setting, I have to set that for every folder - once. Not a big deal,...

It is a big deal if you have a large filesystem to manage.

----

So let's go into more details why there are missing pieces.

1. The current proposal doesn't offer any sort of inheritance, meaning that in case of a change to the order of the Design folder, the user has to go through all sub-folders and change the order there too

2. There is no way to share a sorting order, since the setting is per user, meaning that a shared photo album will have the default order for sharees

3. If you decide to let sharees get the sharer's default order, then every time sharers change the order while browsing their file collection, it has a direct, live impact on the sharees' collections

For these reasons, making any change the default is a bad idea. There should be a clear separation between the defaults and the current session's preferences and there should be an easy way to make changes permanent.
Of course, this means offering a UI letting users configure the "view", but that's very common, so I don't see a problem here.

**Comment by deMattin** [comment] 2015-12-09 19:42
I might have been undestood wrong: I proposed a single checkbox as a file app setting to activate this rememberence of sorting for folders in general (not a checkbox for every folder seperate) - a single option in files app to have old behaviour or saving each folders sorting.

The actual sorting logic has another advantage: If you like to have another sorting in general, you select it once and this is active for complete folder navigation in this session until you change it again.
So especially for a usecase, where a user likes to sort all folders by date, it's only one click away for this session. With this planned saving behaviour all folders are reset to name sorting and have to be switched once.
And if you enhance this session behaviour to be autosaved for this user for next session, you have a folder sorting preference for these users who like sorting by date general as an example without any option to be set.
This simple enhancement would fit more usecases or user than autosaving each folder sorting setting separate, I think.

@jospoortvliet: Resetting folder would be needed with this autosave dorting for the users, who like name sorting in general and messed up there sorting for some folder because of switching and forgetting to reswitch.

**Comment by jospoortvliet** [comment] 2015-12-10 12:52
@oparoz 
> Works as long as the setting is kept per user, otherwise it's a disaster as it would have an impact on all users having access to a folder.
Oh, absolutely, per user, per folder.
> It only works for very simple, flat hierarchies.
I guess you assume I meant to have this as a global option? I think it should be a per user/per folder thing.

You have a certain default (right now sorting by name, sane I guess), and if you have a particular need in a specific folder to change it, you do. It will be remembered for that folder as you are likely to use that view for a reason. If it was a one time thing, worst case you have to set the sorting the next time you go to the folder compared to having it revert to default without remembering anything, best case, you save a click every time you go to the folder. So potential savings are many, many clicks, potential downside is tiny. I think it clearly improves the behavior for 99% of ownCloud users 99% of the time.

I honestly see no reason to share these settings between users.

@deMattin I must admit I had not discovered the current state is to remember the setting per session and have it global. I personally are quite good with that, too. Perhaps it would be possible to get the best of both worlds by doing this:
Remember setting per folder which trumps
Remember setting per session

So you set a sort in a folder, all folders *without any specific sorting* will follow this. If you decide on a different sorting in another folder, it will change for that folder (and store your preference) and change for the entire session.

This changes almost nothing compared to the current behavior except that it 'learns' what sorting you prefer in each folder. Have your cake and eat it too, what do you think?

**Comment by jancborchardt** [comment] 2015-12-10 13:39
> Perhaps it would be possible to get the best of both worlds by doing this:
> Remember setting per folder

This is what we’re talking about the whole time.

Sorry but at some point I gotta say that I don’t find reading and replying to giant comment threads the best use of our time. We had a clear decision above, so @deMattin please respect what seasoned contributors to the project see as a good solution and keep your comments shorter.

**Comment by oparoz** [comment] 2015-12-10 14:03
> I think it clearly improves the behavior for 99% of ownCloud users 99% of the time.

There is 0% chance of verifying that statement ;), but as stated before, it's important to try and figure out what the most common use cases are and this is probably one of them. 
It will still be a problem for people with large collection as they will have to go into every photo album and change the order. A lot of those users will find it ridiculous to have to do that. That's the main reason I think inheritance is important. On the plus side, if there is an API for it, other apps can be made aware of that order and not to have to change it for every app.

> I honestly see no reason to share these settings between users.

Because you never had to, but it's true that it mainly affects apps. Think about sharing an upload folder. Every user will have to adjust the sort order. It's much more elegant if everything is properly configured from the get go.

**Comment by jancborchardt** [comment] 2015-12-10 14:08
Of course when you change the order for a folder, it should be applied to all subfolders as well. And when the order of a subfolder is changed again, do the same, but of course only for that subfolder.

Also, these settings should absolutely _not_ be shared between users when having a shared folder. The view of the folder has nothing to do with the share.

**Comment by deMattin** [comment] 2015-12-10 14:08
@jospoortvliet Won't you think, that your proposal could irritate users, that want to have different sorting in some folders?
Example: You have a picture root folder and switch in this session and in this folder to sort by date. If you navigate in this session to deeper folders, they all will have the same date sorting and this is, what user wants. User thinks: "Ok, fine!"
Next session this users navigates in picture folder, which is sorted by date (saved setting, because sorting has been set in this folder in last session). But if you navigate deeper now, the global sorting for this session (mostly name) will be used. User thinks: "Why that, last time I switched ...?!" ;)

Now we have the problem, @oparoz already mentioned: inheritance of sorting, if sorting for a folder is saved ...

Personally, I think, user mostly want's to have (saved) sorting inherited. But the problem here could be, that user doesn't know or see, which folder has a saved sorting or an inheritated sorting.

It seems to have a reason, why filemanagers on desktops have so many options for sorting and views here inkl. saving/presetting sorting by folder content or type (music, pictures, files), taking over a sorting for all folders, resetting sorting to defaults, ...
To say, 99% of users will have a separate saved sorting for each folder is a statement, that can't be true. Why are these options given, if noone needs them?
And why are so less complains about sorting in files app?

I think, the simple solution to change session saving of sorting to a per user saving will fit more users.
Or/and a per folder saving but with the option to switch this off ...

@jancborchardt 
Short answer? You plan to change basic behaviour of a basic app!
1. Per folder saving isn't elaborated enough
2. Features (actual interited behaviour is often useful), won't work transparent any more
3. Contributors decide on exactly what facts of usablitity and needs to replace behaviour?
4. No chance to get back old and good working behaviour, if new one won't fit
5. Good and maybe best argument: "Shut up, contributors decide ..."

Saving (different) sorting may be a need for __some__ usecases but to simply activate it in general __for each single folder__ seems not to be the best solution for the general needs.

__Why the hell is it a problem to give a checkbox in fileapp settings (where only webdav link there is as "setting" by now) to activate this saving, if user wants it?__
With a choice, you can do or enhance, what you want - but please as an option to switch it off!

**Comment by deMattin** [comment] 2015-12-10 14:12
@jancborchardt Your last propoasal won't work such simple. Setting sorting in a main folder should reset all subfolders then or only for the folders, that aren't set individual?
May be user want's to set it for all folders sub or not? No app can guess this.
You see, there isn't a simple solution ...

**Comment by jancborchardt** [comment] 2015-12-10 16:55
Sorry, I’m out of replying to such long comments, I need to do actual work. The perfect solution is the enemy of the good, and the current state of not saving anything is clearly bad for people who want to sort their stuff by modified date.

**Comment by deMattin** [comment] 2015-12-10 20:43
I don't need replies. I only want the decision makers to see problems, they seem not to have considered, yet.
Changing such basics in used and established workflow has to be thinked over very thoroughly, especially:
- if this will have some disadvantages and break some workflow,
- will be a forced changing for all
- is not simply an additional enhancement you can decide to only use, if you want or need it.

**Comment by oparoz** [comment] 2015-12-11 00:10
What would be great is simply a list of use cases/user stories, ordered by priority. That way specs can be defined and there will be a reference, living, document anybody can go back to when things need to be adjusted. It also helps with the documentation.

**Comment by jancborchardt** [comment] 2015-12-11 09:16
Really folks? There seems to be a misunderstanding of how many people work on ownCloud and how much time we can invest.

This is clearly overthinking such a small detail – it doesn’t »change [a] basic«, all it does is fix something which we should have done long ago, and that is remembering what people choose for their view. All the arguments have been brought in very early in the thread.

I gotta refer to our [Code of Conduct here: **Be pragmatic**](https://doc.owncloud.org/server/8.2/developer_manual/general/code-of-conduct.html#be-pragmatic)

> ownCloud is a pragmatic community. We value tangible results over having the last word in a discussion. We defend our core values like freedom and respectful collaboration, but we don’t let arguments about minor issues get in the way of achieving more important results. We are open to suggestions and welcome solutions regardless of their origin. When in doubt support a solution which helps getting things done over one which has theoretical merits, but isn’t being worked on. Use the tools and methods which help getting the job done. Let decisions be taken by those who do the work.

**Comment by oparoz** [comment] 2015-12-11 11:28
If the title of the issue was "Add a way to remember file list sorting options", then yes, there is no need for much discussion, but you want to change a default behaviour, so some resistance is expected.

You don't always save time by just getting things done, au contraire. We've seen it plenty of times recently (login, new flat design, sidebar). Specification and design documents are important, because as you've mentioned, this is a community effort and people need to understand where some of the decisions come from. On top of that, it doesn't need to be the same people taking care of writing the specs and implementing them, so hardcore devs don't necessarily need to take part of the discussion in the early stages unless they want to (they do use the system as well).

The current proposal is messy. Let me give you an example with the revised specs as I understand them (always save, inheritance included).

Pictures: change to date
Pictures -- Album1: reverse order to look for something
Pictures: go back to alpha

Now Album1 is an exception, so the next time I change the order of Pictures, expecting all sub-folders to follow suit, it won't happen. All sub-folders which have one day been touched will have their own order, which might not necessarily be meaningful. This can lead to frustration when looking for something per example, before realising that the sorting order is not what you expect.

Now in reality, this might be a very minor annoyance compared to the benefits, but it might not and at some point people will want a way to reset everything because it's a mess. Then what?

**Comment by jospoortvliet** [comment] 2015-12-31 20:34
@oparoz if it really turns out to be messy we can revert or change it. In general, though, we improve behavior in most common scenario's and the times it isn't better are very rare corner cases so I doubt we'll get complaints.

And I agree with Jan it is tiring to discuss for too long - at some point, we spend more time talking than fixing problems. If the basic solution doesn't work we can improve later on.

**Comment by jancborchardt** [comment] 2016-03-09 15:41
Closing as duplicate of https://github.com/owncloud/core/issues/10788 because it’s already discussed there.

**Closed by jancborchardt** 2016-03-09 15:41 UTC
Labels: app:files, design, enhancement
