### ISSUE TITLE
Feature/Service Request: Provide an offical ownCloud docker container

### ISSUE THREAD

**Issue by Pantos** [owncloud/core#10615] opened 2014-08-24 21:55 UTC
There are many Linuxer outside using ownCloud on many different distributions. It would be great to get an offical ownCloud docker container to provide a stable and secure package for easy using this great software.

Thx for your work!

**Comment by jnweiger** [comment] 2015-02-18 14:43
We already use docker inhouse for testing server and client. 
Getting this going is a great junior job!

@craigpg fyi

**Comment by DeepDiver1975** [comment] 2015-02-18 16:55
Is that something we officially want to support? 
I mean: we already have a hell of tasks to take care of.

**Comment by jnweiger** [comment] 2015-02-18 17:06
The images that I have are a by-product from testing. For official support that would need some extra effort. I can only provide as is, and subject to change without notice. etc...

He did not directly ask for 'supported', so mabye we can discuss away 'official' and find that 'as is' is already helpful... 

It needs some Infrastructure. Do we have inhouse usecases to motivate that part?

**Comment by AdamHepner** [comment] 2015-02-18 19:35
Well, you could provide a dockerfile in a separate repository, untangled from the main development. Then taking merge requests for the docker would be independent from all other things, and more people would be able to participate and/or submit issues. I would gladly at least test it!

**Comment by jnweiger** [comment] 2015-02-20 15:31
@AdamHepner please have a look here: http://download.owncloud.org/test/docker/
This is far from an official repo, but this is what I have. 
Each directory has 

* a fluffy name, that tells what was used during docker build. 

* a Dockerfile for you to reproduce the docker image

* a docker.log as a reference, what you can expect.

Please note, the Dockerfiles are autogenerated and will be overwritten without warning.
The tooling for generating them is over here: https://build.opensuse.org/package/show/isv:ownCloud:devel/obs-docker-install

**Comment by pierreozoux** [comment] 2015-07-22 15:08
Hey, yes this is still outstanding. I agree it would be really great to have one!

Look at the list of software, it is a shame that owncloud is missing from that list :) https://github.com/docker-library/official-images/tree/master/library (actually as web application there is just wordpress and ghost, but still, owncloud should be there.)

I'm already in the process of submitting [another app](https://github.com/docker-library/official-images/pull/888). I'd be glad to help on owncloud image.

I already did the job, it is ready to be submitted:
https://github.com/indiehosters/ownCloud
(The job is based on the wordpress image to be as close as possible to the way docker like it.)

There is a nice branch on this repo with TLS and memcached support: https://github.com/indiehosters/ownCloud/tree/TLS-memcached

A separate repo is a huge win IMHO.

I'm really wiling to help on that as you can see already.

I think next steps are:
 - somebody test/read that and validate
 - creation of the owncloud/dockerfile repo
 - I submit a PR to this repo

Once done I can take care of the official submit if you want.

**Comment by sils1297** [comment] 2015-08-14 19:10
Actually there is an owncloud image there, so you probably want to close this bug: https://github.com/docker-library/official-images/tree/master/library

IMO you'll want to open a new bug instead to make the image over there better, i.e. configurable via environment variables and automatically performing an upgrade if started with a data container from an old version. Setting up an owncloud container *can* be made really easy with this container if done appropriately but I don't think the official image is there yet.

**Comment by sils1297** [comment] 2015-08-14 19:11
Just for reference, I've written my own image because of those shortcomings: https://github.com/sils1297/docker-centos-owncloud - feel free to reuse that stuff, although it's not perfectly tested nor bugfree (as nothing ever is) nor feature complete.

**Comment by pierreozoux** [comment] 2015-08-15 10:18
Yes, please close this issue as there is an official image.

**Comment by yosifkit** [comment] 2015-09-10 17:52
Sorry we (the maintainers of [docker official images](https://github.com/docker-library/official-images)) missed this thread :disappointed:.  We would love if you wanted to take over the owncloud official image and make it better for your users :smile:.  We can even transfer the current repo so that issues and PRs are kept: https://github.com/docker-library/official-images#maintainership.

**Comment by mahnunchik** [comment] 2015-11-04 11:40
Hi,

It would be great to have a docker image with the following features:
* Configuration via environment variables
* *or/and*
* Configuration by shared (mounted) config file
* Declared data volumes
* Way to link owncloud to database

**Comment by pierreozoux** [comment] 2015-11-04 17:23
@mahnunchik so there is already an official image that you can find [here](https://hub.docker.com/_/owncloud/).

There is this project that wraps it together in a nice way: [IndieHosters/ownCloud](https://github.com/indiehosters/ownCloud).

ownCloud is not involved in neither project, but as already stated, I'd love to help on facilitating this :)

If you want to help on any of these project, feel free to open an issue :)

**Comment by mahnunchik** [comment] 2015-11-07 11:45
Hi @pierreozoux 

As mentioned @yosifkit authors of ownCloud are able to manage docker `official` image https://hub.docker.com/_/owncloud/

I think that packaging `ownCloud` as docker image in addition to the packages for operation systems is a good idea for distribution application.

Features that I have not found in the current image I listed above.

**Comment by pierreozoux** [comment] 2015-11-08 16:14
@mahnunchik I'm not sure I understand you well.

But yes, official images should be managed by application maintainer (as other packaging work, debian doesn't maintain ownCloud debian package). And this is what @yosifkit proposed, and I said I could help ownCloud team in the process. Docker team is maintaining it in the mean time to also promote Docker.

About the features, I think they are already present in the official image.
 - you can mount the data volume (as I do [here](https://github.com/indiehosters/ownCloud/blob/master/docker-compose.yml#L13-L16).
 - you can mount the config file, as I do [here](https://github.com/indiehosters/ownCloud/blob/master/docker-compose.yml#L15)
 - you can link the database, as I do [here](https://github.com/indiehosters/ownCloud/blob/master/docker-compose.yml#L11-L12)

If you think this is not exactly what you need, please open an issue at the [official docker image repo](https://github.com/docker-library/owncloud). This thread is more about how to switch ownership of this repo to ownCloud, and whether ownCloud team wants this responsibility.

**Comment by butonic** [comment] 2016-06-24 13:20
Do we want to ship ownCloud as Docker Images for production?

What is needed? Design? Requirements?

Who can help create Docker Images with high quality? Are eg. these production ready:
- ownCloud with automatic updates, https://github.com/dockhippie/owncloud
- mariaDB, https://github.com/dockhippie/mariadb
- redis, https://github.com/dockhippie/redis
- mod_php or fpm? fpm has no added value if all the container executes is a single owncloud instance. And there are timeout issues
- php7?
- can a set of apps be added by adding another container?

What about orchestration, like coreOS, kubernetes?
- support different networkings
- storage: glusterfs, gpfs, cephfs ar posix and should be assembled outside the container?

There are a ton of questions ... but not doing it will bind our energy to supporting multiple distros with their packaginq quirks and even unavailable packages.

Interesting Links:
- Docker Networking, https://docs.google.com/presentation/d/1bvb8U4Kib-jnvMupQGUAiZKHLgRGEEKmSfTuvHQCcAM/edit#slide=id.p13
- Discourse has a docker only strategy: https://samsaffron.com/archive/2013/11/07/discourse-in-a-docker-container They also have a multiple container version: https://github.com/discourse/discourse_docker#single-container-vs-multiple-container

**Comment by pierreozoux** [comment] 2016-06-24 14:26
@butonic didn't you read my previous post?

It is already done, and the image is a [docker official image](https://github.com/docker-library/owncloud).

Please, don't follow the discourse strategy, it is terrible to host with any orchestration tools (like swarm, kubernetes or...) https://meta.discourse.org/t/can-discourse-ship-frequent-docker-images-that-do-not-need-to-be-bootstrapped/33205/66

Let me know if you have any further question?

**Comment by SergioBertolinSG** [comment] 2016-06-27 13:08
From a QA perspective that will equalize the OS part of all environments, which reduces some maintenance on upgrade tests. Also having everyone the same environment can make easier to find and fix bugs.

Data folder should be out of containers, a volume perhaps, inside containers data can be lost.

This approach can make easier to change cache options available, having them in different containers. Same with databases.

Concerns: Security in containers, not idea if it can be as good as without containers. Scalability, it is a good idea have oracle in containers for example?

I've read that even if docker recommends to have one process per container, the real situation is more useful to have several in one container, and separate them in roles. Like one for database, one for cache server and one for web server, php and actual code.

**Comment by jmaciasportela** [comment] 2016-06-28 07:24
My thoughts:

1- coreOS as base system
2- Alpine Linux a Docker base images (why?? https://www.brianchristner.io/docker-is-moving-to-alpine-linux/)
3- Docker compose to define the ownCloud stack. It is easy to have different YAML files to define different environment.
4- No orchestration is needed. This tools are complex to deploy on premise. It is better to have

Starting with easiest architecture you will realize if it covers your initial requirements

**Comment by hodyroff** [comment] 2017-06-22 18:35
Right now there is the official one from dockerhub from the docker community and one ownCloud maintains and uses for its installations and customers, that one is here: https://github.com/owncloud-docker/server
and will soon be mentioned in the documentation as another recommended path.
We have chose Ubuntu LTS. And will eventually offer RHEL and SLES based docker files to customers.

**Closed by hodyroff** 2017-06-22 18:35 UTC
Labels: enhancement, packaging
