### ISSUE TITLE
Downloading  a folder with special characters, .tar file name created is corrupt

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20607] opened 2015-11-19 12:46 UTC
### Steps to reproduce

1. Create a new folder named Àragoñóç
2. Download it using Firefox or Safari as browsers

### Expected behaviour

The folder should be downloaded in a .tar file with the same name

### Actual behaviour

The folder is downloaded in a .tar file with a corrupted name

Note: It works fine with IE and Chrome

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-19T04:29:14+00:00 da5285dc23dc88d8f570409a8d7ed1296b95f407

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-19 at 13 34 55](https://cloud.githubusercontent.com/assets/10596560/11271013/a0cc5590-8ec3-11e5-811c-8eb8ffe62ef2.png)

**Comment by PVince81** [comment] 2015-11-19 12:48
It's not really corrupt, just url encoded :wink: 

Duplicate of https://github.com/owncloud/core/issues/19862 
CC @LukasReschke

**Closed by PVince81** 2015-11-19 12:48 UTC
Labels: bug, sev3-medium
