### ISSUE TITLE
Checkbox settings in "Users" App are not persistent

### ISSUE THREAD

**Issue by JohnDoe42** [owncloud/core#13467] opened 2015-01-19 14:12 UTC
Server: nginx 1.6.2
OS: linux 3.18.2
PHP: 5.6.4
OC: 7.0.4

Reproduce:
Go to "User" app
klick on the gear in the lower left corner
activate any checkbox you like
see, that the checkbox applies to the current view
switch to any other app
switch back to "User" app
see, that the checkbox settings were not commited

What should happen:
settings made by the checkboxes should be persistent (saved)

**Comment by LukasReschke** [comment] 2015-01-19 14:13
Dupe of https://github.com/owncloud/core/issues/12727

**Closed** 2015-01-19 14:14 UTC
