### ISSUE TITLE
8.2.1 external local file system - delete directory

### ISSUE THREAD

**Issue by ferdiga** [owncloud/core#20940] opened 2015-12-04 08:50 UTC
### Steps to reproduce
mount external local file system  with only read permissions for www-data
delete a directory on the external file system 

### Expected behaviour
should disappear in the web gui

### Actual behaviour
does not disappear - is not accessible - but can/must be deleted in WEB - GUI

### Server configuration
**Operating system**:
Debian 8
**Web server:**
apache2                               2.4.10-10+deb8u1
**Database:**
mariadb-server                        10.0.22-0+deb8u1

**PHP version:**
php5                                  5.6.14+dfsg-0+deb8u1 
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
updated from 8.1.1
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - files_w2g: 0.8.1.0
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - updater: 0.6
Disabled:
  - encryption
  - gallery
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
-- public keyword is unknown in 8.2.1

{
    "system": {
        "instanceid": "ocde8d3204fb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud_data",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 3,
        "share_folder": "\/Shared",
        "trusted_domains": [
            "service.chricar.at"
        ],
        "mail_from_address": "xenon",
        "mail_domain": "strakosch.at",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "false"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local, Google Drive
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome current
**Operating system:**
Ubuntu 15.04
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Xenopathic** [comment] 2015-12-04 08:57
Duplicate of #11797

**Closed by Xenopathic** 2015-12-04 08:57 UTC
