### ISSUE TITLE
user management different drop down box

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#18672] opened 2015-08-30 12:22 UTC
I just saw this in master (Iceweasel 40.0.3):

![1](https://cloud.githubusercontent.com/assets/1589737/9567191/4cf5f998-4f22-11e5-9e49-9efbe8fc46f5.png)

Why does the quota checkbox looks different than the "groups" and "group admin" check boxes?

cc @jancborchardt

**Comment by raghunayyar** [comment] 2015-08-30 12:30
the behavior of both the select boxes is different. The first one is a multi-select where you can add groups within the select box and the other is the default one. I think, this was intended.

Open if still an issue.

**Comment by jancborchardt** [comment] 2015-08-30 13:44
It’s not intended, it’s a Firefox design issue. We should fix it and style over it if we can. @raghunayyar do you want to take that up?

**Comment by raghunayyar** [comment] 2015-08-30 13:48
sure. assigned to self.

**Comment by raghunayyar** [comment] 2015-08-30 13:51
Just to be clear: 
Chrome it looks like
<img width="627" alt="screen shot 2015-08-30 at 3 51 27 pm" src="https://cloud.githubusercontent.com/assets/992488/9567531/01b09fbc-4f2f-11e5-8076-9420cd4c7cce.png">

So, in both cases it should look like how it does in Chrome? @jancborchardt

**Comment by jancborchardt** [comment] 2015-08-30 17:00
In both cases both dropdowns should use the same style / arrow. That is, quota should ideally also just use the single arrow. But that might be too much work, so the initial step is to just fix the ugliness in Firefox.

**Comment by raghunayyar** [comment] 2015-08-30 17:35
Not too much work @jancborchardt :dancer:. check the PR.

**Closed** 2015-09-02 22:36 UTC
Labels: 1 - To develop, design, enhancement
