### ISSUE TITLE
[8.2] Folder listing in Shared-Link View limited to 25

### ISSUE THREAD

**Issue by five-team** [owncloud/core#19994] opened 2015-10-23 08:13 UTC
If there is a folder shared by a link the listing limit of folders is 25 and there is no possibility to see more folders.

This problem only happens in the Shared-Link View.

**Comment by nickvergessen** [comment] 2015-10-23 09:04
Duplicate of #19886

The fix is https://github.com/owncloud/core/pull/19895 so you can adjust that yourself in the meantime

**Closed** 2015-10-23 09:05 UTC
Labels: duplicate
