### ISSUE TITLE
Crusty clowns everywhere :(

### ISSUE THREAD

**Issue by lordamot** [owncloud/core#23280] opened 2016-03-15 21:37 UTC
ubuntu 14.04, nginx, memcached

### Steps to reproduce
1. install and run it
2. oh, upgrade for 9
3. shiiiiiiii......

### Expected behaviour
"run occ upgrade and be happy"

### Actual behaviour
"Exception: Error 16 interacting with memcached : NOT FOUND
Update failed"

Really, what should I do with this message? (BTW, I'm a skilled PHP programmer)

### Server configuration
**Operating system**: 14.04.04 LTS

**Web server:** NGINX

**Database:** MYSQL

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 8.2.2, currently (thanks for forever maintaing mode)

**Updated from an older ownCloud or fresh install:** ok, I tried to update from 8.2.2 to 9

**Where did you install ownCloud from:** from your site

**Signing status (ownCloud 9.0 and above):** no clues for what it is

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"your owncloud instance is in maintenance mode" - are you kidding me?) lol)
```

**List of activated apps:** none

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
again: none

**The content of config/config.php:**
contact daemon.user@gmail.com if you are really interested in :/ I'll try to help as much as I can.

Guys, why you can't handle the simplest task: write stable update script? I am very disappointed, it's my second big owncloud update (and I think, it will be second "erase all - resync" :( )

**Comment by LukasReschke** [comment] 2016-03-15 21:41
> Guys, why you can't handle the simplest task: write stable update script?

Because we need the help of the skilled PHP developer that you are on helping on that.

But unfortunately you didn't handle the simplest task: [Test the RCs / Betas / etc.](https://owncloud.org/faq/#upgrade). 

Anyways, dupe of https://github.com/owncloud/core/issues/23132

**Closed by LukasReschke** 2016-03-15 21:41 UTC

**Comment by lordamot** [comment] 2016-03-15 21:48
Wooah. Really operative. Okay, I'll read that bug tomorrow. Sorry if it
looks like troll attack
16 марта 2016 г. 12:41 AM пользователь "Lukas Reschke" <
notifications@github.com> написал:
