### ISSUE TITLE
Can't set "delete" permissions on "Shared with others" view

### ISSUE THREAD

**Issue by lawl** [owncloud/core#16709] opened 2015-06-03 10:04 UTC
Steps to reproduce:
1. Create a folder.
2. Share it with a user on the same instance
3. Go to the "Shared with others" view
4. Edit the permissions for the user (expand "can edit")
5. "delete" flag is missing

Expected behavior:
Delete flag should be available the same way it is on the "All Files" view.

Version: 8.0.3

Additional Information:

PVince81 helped me debug this in IRC as I thought I couldn't set delete permissions at all.
He asked me to open this ticket, I'll just copy paste what he said here:

    <PVince81> it's because we disallow deleting the folder directly in this view, using permissions trickery
    <PVince81> but that seems to affect the dialog too
    <PVince81> just provide the steps to reproduce, and specify the version. then mention me
    <PVince81> that should be enough
    <PVince81> thanks

**Comment by PVince81** [comment] 2015-06-03 10:07
Confirmed. Also happens 8.1 / master.

Need to find a another way to remove the delete icon in this view without touching the permissions.

**Comment by PVince81** [comment] 2015-06-03 10:07
Setting to medium as there is a workaround: going to the "All files" view and share from there.

**Comment by PVince81** [comment] 2015-08-18 16:00
also related: permissions mess https://github.com/owncloud/core/issues/13202

**Comment by cmonteroluque** [comment] 2015-09-22 19:19
move forward to 9.0 because of #13202

**Comment by cdamken** [comment] 2015-10-09 17:51
I have it on 8.1.3 too

**Comment by rullzer** [comment] 2015-12-12 13:37
This seems to be fixed on master. @PVince81 can you verify?

**Comment by PVince81** [comment] 2015-12-14 09:56
It's fixed with https://github.com/owncloud/core/pull/20160 on master and will be backported to 8.2.2.

**Closed by PVince81** 2015-12-14 09:56 UTC
Labels: bug, feature:sharing, sev3-medium
