### ISSUE TITLE
Two-step Authentication Needed

### ISSUE THREAD

**Issue by Nitroxaddict** [owncloud/core#20977] opened 2015-12-07 08:04 UTC
Owncloud needs to include some "two-step authentication" feature in the core of the product. 

A previous feature request "Add native support for One time password [OTP] #16309" was closed because you thought that this could be handled by third party apps, it can't. Today this is not an option, and you cannot rely on others to deliver security on your product. Take a look on the internet, everyone is offering this feature, DropBox, Amazon, Paypal, even Synology in its DSM...

You should walk the walk on your promise for "A safe home for all your data"

**Comment by MorrisJobke** [comment] 2015-12-07 08:04
Duplicate of https://github.com/owncloud/core/issues/12102

**Closed by MorrisJobke** 2015-12-07 08:04 UTC
