### ISSUE TITLE
display bug: files -> mark many -> <tr> too wide

### ISSUE THREAD

**Issue by Af0x** [owncloud/core#18960] opened 2015-09-10 17:03 UTC
hello,

if you mark many files and look at the top of the table <tr> (line where you can delete or download the marked files). The width of the named line is too wide so that it reaches into the scrollbar.

Tested with Firefox on Win10.

Regards,

Af0x

**Comment by PVince81** [comment] 2015-10-12 10:05
@Af0x next time please use the issue template: https://raw.github.com/owncloud/core/master/issue_template.md

A bug report should always at least state which ownCloud version you are using.

Duplicate of https://github.com/owncloud/core/issues/19057. Fix will appear in 8.2RC2

**Closed by PVince81** 2015-10-12 10:05 UTC
Labels: bug
