### ISSUE TITLE
incomplete occ commands are shown as exception not as nice list of suggestion

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35554] opened 2019-06-17 08:15 UTC
### Steps to reproduce
1. type an incomplete command like `./occ app`

### Expected behaviour
before #35362:
![image](https://user-images.githubusercontent.com/2425577/59588821-349d4a00-9108-11e9-9db7-49f8623959c5.png)

### Actual behaviour
now 
![image](https://user-images.githubusercontent.com/2425577/59588859-47b01a00-9108-11e9-8763-8e96104b4141.png)

**Comment by individual-it** [comment] 2019-06-17 08:18
similar other error messages
![image](https://user-images.githubusercontent.com/2425577/59589021-b3928280-9108-11e9-88c4-a015778b8157.png)

**Comment by karakayasemi** [comment] 2019-11-24 18:22
@individual-it I could not reproduce this issue. I got exactly the expected behavior when I run an undefined app. It may be resolved.

**Comment by karakayasemi** [comment] 2019-11-24 18:28
The cause PR #35362 looks reverted in https://github.com/owncloud/core/pull/35873. I guess we can close this issue also.

**Closed** 2019-11-26 04:30 UTC
