### ISSUE TITLE
ERROR: No app in context OC_9.0.0

### ISSUE THREAD

**Issue by Echse27** [owncloud/core#23343] opened 2016-03-17 09:50 UTC
### Steps to reproduce
1. When a user upload a file, this error appiers in log file...
2. The file ist uploades successfully
3.

### Server configuration
**Operating system**:
UbuntuServer 14.04 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.47
**PHP version:**
PHP 5.5.9-1ubuntu4.14 
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2
**Where did you install ownCloud from:**
from owncloud.org Downloadsektion
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - libreonline: 0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - registration: 0.1.3
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "oc4ymjyh19zr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.110",
            "my-domain.de",
            "sub.my-domain.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/192.168.0.110\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "ralflange83",
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "theme": "",
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false
    }
}


**Are you using external storage, if yes which one:** local/smb/sftp/...
no external storage in use
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no external userbackaned only Webinterface, the official app for Android and Windows

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "ldap" namespace.

### Client configuration
**Browser:**
Google Chrome Version 49.0.2623.87 m
**Operating system:**
Windows 7, Ubuntu 14.04.3 LTS Client
#### Web server error log
```
Insert your webserver log here
```
[Thu Mar 17 06:14:07.349051 2016] [:error] [pid 11572] [client 51.255.65.90:58101] script '/var/www/index.php' not found or unable to stat
[Thu Mar 17 08:30:40.266289 2016] [authz_core:error] [pid 12855] [client 195.36.71.204:61057] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Thu Mar 17 08:34:22.950779 2016] [authz_core:error] [pid 12855] [client 195.36.71.204:22755] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Thu Mar 17 08:35:05.798504 2016] [authz_core:error] [pid 15551] [client 195.36.71.204:42364] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Thu Mar 17 08:37:12.634802 2016] [authz_core:error] [pid 15579] [client 195.36.71.204:30379] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Thu Mar 17 10:30:48.099414 2016] [authz_core:error] [pid 16902] [client 195.36.71.204:61222] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"7TTzFAFnyYrqoeOC6Jy+","remoteAddr":"84.57.165.232","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/Musik\\\/Es gibt ein Ziel\\\/Instrumental.mp3 not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(913): OC\\\\Files\\\\View->getOwner('\\\/Musik\\\/Es gibt ...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(191): OC\\\\Files\\\\Filesystem::getOwner('\\\/Musik\\\/Es gibt ...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(145): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/Musik\\\/Es gibt ...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooks.php(101): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/Musik\\\/Es gibt ...', 'file_created', 'created_self', 'created_by')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/fileshooksstatic.php(60): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/Musik\\\/Es gibt ...')\\n#5 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/hook.php(105): call_user_func(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/filechunking.php(224): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(436): OC_FileChunking->file_assemble(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/Musik\\\/Es ...', '\\\/Silas\\\/files\\\/Mu...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #52)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #52)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('Instrumental.mp...', Resource id #52)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Musik\\\/Es gibt e...', Resource id #52, NULL)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1583}","level":3,"time":"2016-03-17T09:48:11+00:00"}

I don´t know, where this error can come from...

**Comment by PVince81** [comment] 2016-03-17 10:06
Duplicate of https://github.com/owncloud/core/issues/23212

**Closed by PVince81** 2016-03-17 10:06 UTC
