### ISSUE TITLE
[DAV] Call to a member function getUID()

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#23581] opened 2016-03-25 12:33 UTC
### Steps to reproduce
N/A

### Expected behaviour
No errors with dav

### Actual behaviour
Error shows in log every 30 minutes

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.5
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2
**Where did you install ownCloud from:**
ownCloud repos
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.3.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocdd06e12069",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fsgo.se",
            "cloud.fsgo.eu",
            "fsgo.se",
            "www.fsgo.se"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.fsgo.se\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "default_language": "sv",
        "allow_user_to_change_display_name": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.fsgo.se",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "admin",
        "mail_domain": "fsgo.se",
        "forcessl": true,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "theme": "fsgo",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "loglevel": 2,
        "app.mail.server-side-cache.enabled": true,
        "app.mail.imaplog.enabled": true,
        "logtimezone": "Europe\/Stockholm",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "30",
        "updatechecker": false
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 49
**Operating system:**
Deepin 15 and Windows (tested both)
#### Web server error log
```
No error log
```

#### ownCloud log (data/owncloud.log)
```
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T12:00:07+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T11:30:07+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T11:00:10+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T10:30:01+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T10:00:02+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T09:30:07+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T09:00:01+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T08:30:02+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T08:15:01+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T07:45:02+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T07:30:01+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T07:00:01+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T06:30:02+00:00
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-03-25T06:00:02+00:00
```

#### Browser log
```
No error log
```

**Comment by RealRancor** [comment] 2016-03-25 13:07
A user reported the same at the forums: https://forum.owncloud.org/viewtopic.php?f=38&t=34585

**Comment by DeepDiver1975** [comment] 2016-03-25 13:43
already fixed - will be shipped with 9.0.1

**Comment by adamoutler** [comment] 2016-04-02 04:05
I'm experiencing this as well.  The log clutter made me log in to request the new version be pushed sooner.

**Comment by enoch85** [comment] 2016-04-07 20:20
@DeepDiver1975 I still see this.

**Comment by Buzut** [comment] 2016-04-08 19:46
I've just made the upgrade to 9.0.1 and I have the issue as well. It's cron related:

    sudo -su www-data php -f /var/www/owncloud/cron.php
    PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/apps/dav/appinfo/app.php on line 49

**Comment by adamoutler** [comment] 2016-04-09 13:42
I can confirm the fix worked.  I had the following error on each run which is now fixed.  


`PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/apps/dav/appinfo/app.php on line 49
PHP Stack trace:
PHP   1. {main}() /var/www/owncloud/cron.php:0
PHP   2. OC\BackgroundJob\TimedJob->execute() /var/www/owncloud/cron.php:141
PHP   3. OC\BackgroundJob\Job->execute() /var/www/owncloud/lib/private/backgroundjob/timedjob.php:53
PHP   4. OCA\Activity\BackgroundJob\EmailNotification->run() /var/www/owncloud/lib/private/backgroundjob/job.php:52
PHP   5. OCA\Activity\BackgroundJob\EmailNotification->runStep() /var/www/owncloud/apps/activity/lib/backgroundjob/emailnotification.php:94
PHP   6. OCA\Activity\MailQueueHandler->sendEmailToUser() /var/www/owncloud/apps/activity/lib/backgroundjob/emailnotification.php:134
PHP   7. OCA\Activity\DataHelper->translation() /var/www/owncloud/apps/activity/lib/mailqueuehandler.php:244
PHP   8. OCA\Activity\Parameter\Parameter->format() /var/www/owncloud/apps/activity/lib/datahelper.php:87
PHP   9. OCA\Activity\Formatter\CloudIDFormatter->format() /var/www/owncloud/apps/activity/lib/parameter/parameter.php:82
PHP  10. OCA\Activity\Formatter\CloudIDFormatter->getDisplayNameFromContact() /var/www/owncloud/apps/activity/lib/formatter/cloudidformatter.php:63
PHP  11. OC\ContactsManager->search() /var/www/owncloud/apps/activity/lib/formatter/cloudidformatter.php:86
PHP  12. OC\ContactsManager->loadAddressBooks() /var/www/owncloud/lib/private/contactsmanager.php:41
PHP  13. OC_App::{closure:/var/www/owncloud/apps/dav/appinfo/app.php:48-51}() /var/www/owncloud/lib/private/contactsmanager.php:184`

**Comment by DeepDiver1975** [comment] 2016-04-09 19:07
Looks like the fix did not make it into 9.0.1 - it'll be in 9.0.2

**Closed by DeepDiver1975** 2016-04-09 19:07 UTC
Labels: bug

**Comment by adamoutler** [comment] 2016-04-09 20:28
I can confirm its fixed in the apt-add Debian repository installation method.   It's fixed for me.

**Comment by kajla** [comment] 2016-04-11 14:26
I have got same problem.
ownCloud version: 9.0.1
Update method: Debian repository (Debian 8)

 Error 	PHP 	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49 	2016-04-11 16:00:02
Error 	PHP 	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49 	2016-04-11 15:30:02
Error 	PHP 	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49 	2016-04-11 15:15:02
Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-04-11 14:45:02
... and so on.

**Comment by RealRancor** [comment] 2016-04-11 14:29
@kajla 
> Looks like the fix did not make it into 9.0.1 - it'll be in 9.0.2

**Comment by kajla** [comment] 2016-05-01 18:28
Hi, 

I upgraded yesterday to 9.0.1.3. 

Error	PHP	Call to a member function getUID() on null at /var/www/owncloud/apps/dav/appinfo/app.php#49	2016-05-01 20:00:02
...

When it will be available this fix???!

**Comment by RealRancor** [comment] 2016-05-01 20:40
With 9.0.2 as written above
