### ISSUE TITLE
Accessing password protected shared file via Web interface results in additional basic auth and infinite redirect loop

### ISSUE THREAD

**Issue by mgla** [owncloud/core#24018] opened 2016-04-15 08:34 UTC
### Steps to reproduce
1. Share file publicly using, i.e., owncloud desktop client as password protected.
2. Open share link in browser. Enter password.

### Expected behaviour
File should available via Browser.

### Actual behaviour
File is available via Browser, _if_ you are fast enough. Additionally a HTTP basic auth opens:

Title: Authentication Required
Text: https://owncloud.example.org requires a username and a password.

You can cancel the request, but will be redirected to the same page, resulting in the basic auth opening again. If you are fast enough, you can click on the file really fast to download it.

### Server configuration
**Operating system**:
Debian Jessie 8.4, with up to date patches.

**Web server:**
Apache 2.4 with mod_ssl, no basic auth configured whatsoever. Normal file sharing, web interface works fine.

`AllowOverride All` is set on owncloud `Directory `directive

**Database:**
Postgres 9.4 on another server, also Debian Jessie 8.4 with up to date patch level.

**PHP version:**
```
PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
**ownCloud version:** (see ownCloud admin page)
> ownCloud 9.0.1 (stable)

Installed via deb file from owncloud server.

**Updated from an older ownCloud or fresh install:**
Updated two weeks ago from Owncloud 9.0.0, which was the oldest version used.
**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oclypgga0i4c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REDACTED.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/REDACTED.example.com",
        "dbtype": "pgsql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "10.10.112.12",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_from_address": "no_reply",
        "mail_domain": "example.com",
        "mail_smtphost": "MAILSERVER.example.com",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
No on disk-encryption, but HTTPS/SSL
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, LDAP. Works fine as far as I can tell

#### LDAP configuration (delete this part if not used)

```]
+-------------------------------+-----------------------------------------------------------------------------------+
| Configuration                 |                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                 |
| hasPagedResultSupport         |                                                                                   |
| homeFolderNamingRule          |                                                                                   |
| lastJpegPhotoLookup           | 0                                                                                 |
| ldapAgentName                 | CN=svc_owncloud,OU=service,OU=Users,OU=EXAMPLE,DC=int,DC=example,DC=com                |
| ldapAgentPassword             | ***                                                                               |
| ldapAttributesForGroupSearch  |                                                                                   |
| ldapAttributesForUserSearch   |                                                                                   |
| ldapBackupHost                |                                                                                   |
| ldapBackupPort                |                                                                                   |
| ldapBase                      | OU=EXAMPLE,DC=int,DC=example,DC=com                                                    |
| ldapBaseGroups                | OU=Groups,OU=EXAMPLE,DC=int,DC=example,DC=com                                          |
| ldapBaseUsers                 | OU=regular,OU=Users,OU=EXAMPLE,DC=int,DC=example,DC=com                                |
| ldapCacheTTL                  | 601                                                                               |
| ldapConfigurationActive       | 1                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                   |
| ldapEmailAttribute            | mail                                                                              |
| ldapExperiencedAdmin          | 1                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                   |
| ldapExpertUUIDUserAttr        |                                                                                   |
| ldapExpertUsernameAttr        |                                                                                   |
| ldapGroupDisplayName          | cn                                                                                |
| ldapGroupFilter               | (objectClass=group)                                                               |
| ldapGroupFilterGroups         |                                                                                   |
| ldapGroupFilterMode           | 1                                                                                 |
| ldapGroupFilterObjectclass    |                                                                                   |
| ldapGroupMemberAssocAttr      | member                                                                            |
| ldapHost                      | 10.10.112.11                                                                      |
| ldapIgnoreNamingRules         |                                                                                   |
| ldapLoginFilter               | (&(|(objectclass=organizationalPerson)(objectclass=person))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                 |
| ldapLoginFilterMode           | 0                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                 |
| ldapNestedGroups              | 1                                                                                 |
| ldapOverrideMainServer        |                                                                                   |
| ldapPagingSize                | 500                                                                               |
| ldapPort                      | 389                                                                               |
| ldapQuotaAttribute            |                                                                                   |
| ldapQuotaDefault              |                                                                                   |
| ldapTLS                       | 0                                                                                 |
| ldapUserDisplayName           | displayname                                                                       |
| ldapUserDisplayName2          |                                                                                   |
| ldapUserFilter                | (&(|(objectclass=organizationalPerson)(objectclass=person)))                      |
| ldapUserFilterGroups          |                                                                                   |
| ldapUserFilterMode            | 0                                                                                 |
| ldapUserFilterObjectclass     | organizationalPerson;person                                                       |
| ldapUuidGroupAttribute        | auto                                                                              |
| ldapUuidUserAttribute         | auto                                                                              |
| turnOffCertCheck              | 0                                                                                 |
| useMemberOfToDetectMembership | 1                                                                                 |
+-------------------------------+-----------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**

Google Chrome, Firefox, I have also reports for Safari, but not verified that.
Firefox also ignores reopening http basic auths, apparently, which makes the problem slightly less annoying.

**Operating system:**

#### Web server error log

No entries in Apache error.log
Access log has no interesting entries, just resource loading after this (Accessing the shared file):
```
 [15/Apr/2016:10:27:40 +0200] "GET /index.php/s/iZe0WHFBYFm1HWr
```

#### ownCloud log (data/owncloud.log)

On entering the password in the web interface, owncloud.log logs this:
```
{"reqId":"KolWhbXPe97lSxF8EYxk","remoteAddr":"11.22.33.44","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-04-15T08:30:12+00:00","method":"GET","url":"\/public.php\/webdav","user":"--"}
{"reqId":"KolWhbXPe97lSxF8EYxk","remoteAddr":"11.22.33.44","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-04-15T08:30:12+00:00","method":"GET","url":"\/public.php\/webdav","user":"--"}
{"reqId":"KolWhbXPe97lSxF8EYxk","remoteAddr":"11.22.33.44","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-04-15T08:30:12+00:00","method":"GET","url":"\/public.php\/webdav","user":"--"}
```

#### Browser log
No javascript console log.
Network log shows a request to https://owncloud.example.com/public.php/webdav as "pending" initiated by `https://owncloud.example.com/core/vendor/jquery/jquery.min.js?v=2b652bf0f98e341a445d06738c349657`

**Comment by RealRancor** [comment] 2016-04-15 09:08
Duplicate of https://github.com/owncloud/core/issues/23754

**Closed** 2016-04-15 09:08 UTC

**Comment by inpos** [comment] 2016-05-06 12:45
upgrade to 9.0.2-1.1 on Debian Jessie.
Same issue

**Comment by RealRancor** [comment] 2016-05-06 12:49
@inpos https://github.com/owncloud/core/issues/23066
