### ISSUE TITLE
Update error oc 8.1.1

### ISSUE THREAD

**Issue by heavymanto** [owncloud/core#19208] opened 2015-09-21 07:53 UTC
Update from 8.0.1 to 8.1.1 I have this error

Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

![screenshot 623](https://cloud.githubusercontent.com/assets/6449169/9987265/9a2a4f22-6046-11e5-98c2-8997a150e1e1.png)

**Comment by Xenopathic** [comment] 2015-09-21 09:05
Duplicate of #19145

Try the upgrade again, it will succeed the second time.

**Closed by Xenopathic** 2015-09-21 09:05 UTC
