### ISSUE TITLE
[8.1.3][LDAP] several problems when one ldap server is not avaiable.

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#19855] opened 2015-10-19 07:18 UTC
We have 5 domain controllers integrated in our cloud server, but if one of them is not available then the user search (sharing area) is not working and others stuff like the activity app. Is there a way to improve this because it is a thing what can happen sometimes.

**Comment by PVince81** [comment] 2015-10-19 08:47
@blizzz @MorrisJobke

**Comment by MorrisJobke** [comment] 2015-10-19 08:55
Ref https://github.com/owncloud/core/issues/18701

**Comment by MorrisJobke** [comment] 2015-10-19 08:56
Ref https://github.com/owncloud/core/issues/19336

**Comment by MorrisJobke** [comment] 2015-10-19 08:57
I would rate this as duplicate of #18701 -> move the discussion to that thread and close this one here

**Closed by MorrisJobke** 2015-10-19 08:57 UTC
Labels: app:user_ldap
