### ISSUE TITLE
Google drive mounted folder expires after some days

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15768] opened 2015-04-21 07:27 UTC
### Steps to reproduce

1. Mount a google drive folder using a google account and giving access to it on google console.
2. While working correctly, upload some files.
3. Wait a few days.
4. Try to access again the google drive folder. 

### Expected behaviour
You can still access your google drive folder.

### Actual behaviour
An unknown error happens, and in admin page the connection to google drive is marked red as disconnected.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.3.0","versionstring":"8.0.3 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise version plus:
External Storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, google drive.

**Are you using encryption:** 
No.

**Logs**
```
Fatal	remote	The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.	2015-04-21T07:03:13+00:00
Fatal	files_external	Exception: {"Message":"The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.","Code":0,"Trace":"#0 \/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\n#1 \/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Drive.php(1283): Google_Service_Resource->call('get', Array, 'Google_Service_...')\n#2 \/opt\/owncloud\/apps\/files_external\/lib\/google.php(510): Google_Service_Drive_About_Resource->get()\n#3 \/opt\/owncloud\/apps\/files_external\/lib\/google.php(547): OC\\Files\\Storage\\Google->free_space('')\n#4 \/opt\/owncloud\/apps\/files_external\/lib\/config.php(457): OC\\Files\\Storage\\Google->test(false)\n#5 \/opt\/owncloud\/apps\/files_external\/lib\/config.php(392): OC_Mount_Config::getBackendStatus('\\OC\\Files\\Stora...', Array, false)\n#6 \/opt\/owncloud\/apps\/files_external\/settings.php(47): OC_Mount_Config::getSystemMountPoints()\n#7 \/opt\/owncloud\/lib\/private\/app.php(720): include('\/opt\/owncloud\/a...')\n#8 \/opt\/owncloud\/settings\/admin.php(93): OC_App::getForms('admin')\n#9 \/opt\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/opt\/owncloud\/s...')\n#10 [internal function]: __lambda_func(Array)\n#11 \/opt\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_78', Array)\n#12 \/opt\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/settings\/admin')\n#13 \/opt\/owncloud\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Auth\/OAuth2.php","Line":240}	2015-04-21T07:03:10+00:00
Fatal	files	Exception: {"Message":"The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.","Code":0,"Trace":"#0 \/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\n#1 \/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Service\/Drive.php(1729): Google_Service_Resource->call('get', Array, 'Google_Service_...')\n#2 \/opt\/owncloud\/apps\/files_external\/lib\/google.php(86): Google_Service_Drive_Files_Resource->get('root')\n#3 \/opt\/owncloud\/apps\/files_external\/lib\/google.php(560): OC\\Files\\Storage\\Google->getDriveFile('')\n#4 \/opt\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(357): OC\\Files\\Storage\\Google->hasUpdated('', 1429172050)\n#5 \/opt\/owncloud\/lib\/private\/files\/cache\/watcher.php(67): OC\\Files\\Storage\\Wrapper\\Wrapper->hasUpdated('', 1429172050)\n#6 \/opt\/owncloud\/lib\/private\/files\/view.php(978): OC\\Files\\Cache\\Watcher->checkUpdate('', Array)\n#7 \/opt\/owncloud\/lib\/private\/files\/filesystem.php(793): OC\\Files\\View->getFileInfo('\/GoogleDrive', true)\n#8 \/opt\/owncloud\/apps\/files\/ajax\/list.php(12): OC\\Files\\Filesystem::getFileInfo('\/GoogleDrive')\n#9 \/opt\/owncloud\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/opt\/owncloud\/a...')\n#10 [internal function]: __lambda_func(Array)\n#11 \/opt\/owncloud\/lib\/private\/route\/router.php(250): call_user_func('?lambda_213', Array)\n#12 \/opt\/owncloud\/lib\/base.php(782): OC\\Route\\Router->match('\/apps\/files\/aja...')\n#13 \/opt\/owncloud\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/opt\/owncloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src\/Google\/Auth\/OAuth2.php","Line":240}
```

### Client configuration

**browser**
Chrome 41

**Comment by DeepDiver1975** [comment] 2015-04-21 08:40
> Fatal remote The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved. 2015-04-21T07:03:13+00:00

LOL - brilliant user experience - especially with syncing.

This is so hilarious - I did point out that this could happen years back as this was implemented.

@karlitschek @MTRichards seriously - let's drop gdrive support - this will eat data.
In order to fix this the gdrive implementation we would need to store the refresh_token - which is used to regenerate an expired token.

**Comment by rperezb** [comment] 2015-04-21 08:45
Just FYI some Android clients are complaining that 
"Working great If you do not see your folders remove google drive link you have and readd. Worked for me!"

**Comment by DeepDiver1975** [comment] 2015-04-21 08:54
FYI: dropbox uses oauth as well - their token never expire (unless the user revokes the token)

**Comment by karlitschek** [comment] 2015-04-21 12:50
This is an important feature than we can´t just drop. We should look into that later. On the webui users should see the option to relogin. via webdav we have to mark a mounted folder as something like "currently not available" we might need this for other storage backends anyways.

**Comment by zubanst** [comment] 2015-04-22 17:53
I wonder how could this be so difficult to fix and got a late milestone as this was working in 7.0.4.

**Comment by DeepDiver1975** [comment] 2015-04-22 17:58
Feel free to digg into the code and find out how to make it work. Pull requests are welcome anytime. Thx for your support.

**Comment by DeepDiver1975** [comment] 2015-04-22 17:58
Feel free to digg into the code and find out how to make it work. Pull requests are welcome anytime. Thx for your support.

**Comment by htschannerl** [comment] 2015-07-20 18:36
Hello,

After update to 8.1 i'ts was solved but today I updated to owncloud-8.1.0-16.1 and stop to work again.

**Comment by schmel** [comment] 2015-08-13 14:16
Not work.
$OC_Version = array(8,1,1,3);
$OC_VersionString = '8.1.1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_Build = '2015-08-08T00:57:40+00:00 ca66a705ec59cce1ac60c2fb92ec543e296c23f9';


remoteAddr":"192.168.123.16","app":"webdav","message":"Exception: {\"Message\":\"The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Drive.php(1729): Google_Service_Resource->call('get', Array, 'Google_Service_...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(97): Google_Service_Drive_Files_Resource->get('root')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(571): OC\\\\Files\\\\Storage\\\\
.............................
bre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Auth\\\/OAuth2.php\",\"Line\":240}","level":4,"time":"2015-08-13T14:10:34+00:00"}

**Comment by AdamWill** [comment] 2015-09-02 15:51
FWIW I ran into this when doing the PHP API 1.x port, and setting the access type to 'offline' is what fixed it: https://developers.google.com/identity/protocols/OAuth2WebServer?hl=en#offline

I have no idea what the frack is wrong with it now, but I've been getting similar reports downstream. It may be that Google's messed it up on their end?

**Comment by ZacharyDuBois** [comment] 2015-10-15 10:26
Oh boy. Just ran into this one.

**Comment by PVince81** [comment] 2015-11-03 17:22
How long does it usually take for a token to expire ? It might take a while to reproduce this (need to keep mount.json aside with the old token for a few days)

**Comment by ZacharyDuBois** [comment] 2015-11-03 22:24
Mine took less than a day. Set it up one night and the next morning it didn't work.

**Comment by PVince81** [comment] 2015-11-04 07:00
I just tried setting it up on stable8.2 / 8.2.0 and noticed that the token JSON looks like this:
```
"token": "{\"access_token\":\"REMOVED\",\"token_type\":\"Bearer\",\"expires_in\":3598,\"created\":1446620053}"
```

So it looks like GDrive might have gotten stricter lately and expires the token an hour later!

Now we need to either:
1) Try the offline flag solution
or
2) Implement a mechanism to refresh the auth token by contacting the Google servers (oauth style)

**Comment by ZacharyDuBois** [comment] 2015-11-04 10:08
Well, re-authorizing the same app over and over agin isn't really an option. Your best bet and probably the easiest one is just to schedule ownCloud to fetch a new one every 30-45 minutes.

**Comment by PVince81** [comment] 2015-11-04 10:12
Yes, that's what I was thinking. But then it might require a background job that will refresh the token of all oauth storages (not reauthorize the app) in a regular manner. Might be tricky...

My understanding of oauth is limited, and from what I understand an API consumer is supposed to request a new token using the refresh token, which isn't the same as re-authenticating the app. So, possibly a different endpoint. @LukasReschke did I get this right ?

**Comment by PVince81** [comment] 2015-11-04 10:13
in my past experience with oauth there were two tokens: access token and refresh token, but here there seems to be only a single token. Might need to dive into the Google Drive APIs docs.

**Comment by ZacharyDuBois** [comment] 2015-11-04 22:21
Well, OAuth is limited but not *that* limited.

**Comment by PVince81** [comment] 2015-11-05 10:27
Confirmed, I tried my mount.json from yesterday:
```
{"reqId":"4ECCNsN4MoCRxe9m9BF1","remoteAddr":"127.0.0.1","app":"files_external","message":"Exception: {\"Exception\":\"Google_Auth_Exception\",\"Message\":\"The OAuth 2.0 access token has expired, and a refresh token is not available. Refresh tokens are not returned for responses that were auto-approved.\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Resource.php(176): Google_Auth_OAuth2->sign(Object(Google_Http_Request))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Service\\\/Drive.php(1283): Google_Service_Resource->call('get', Array, 'Google_Service_...')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(521): Google_Service_Drive_About_Resource->get()\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/google.php(558): OC\\\\Files\\\\Storage\\\\Google->free_space('')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(261): OC\\\\Files\\\\Storage\\\\Google->test(false)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(237): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/controller\\\/storagescontroller.php(257): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig))\\n#7 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(1)\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(282): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#14 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(831): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#15 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/google-api-php-client\\\/src\\\/Google\\\/Auth\\\/OAuth2.php\",\"Line\":240}","level":3,"time":"2015-11-05T10:26:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files_external\/globalstorages\/1"}
```

**Comment by PVince81** [comment] 2015-11-05 11:14
possible idea about how to refresh the token: http://stackoverflow.com/a/15393022

**Comment by ajhepple** [comment] 2015-11-05 12:15
When I followed the guide to set up Drive external storage on OwnCloud I was surprised, when creating the credentials via the Google dev console, to be instructed to select the "Web application" as the application type.  I have a some experience of accessing Google APIs (although not with PHP, sadly) and I expected to need credentials for "Service account" authorisation. 

[Google service accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) allow user-less servers to access Google APIs and seems the most appropriate for enabling an OwnCloud server to maintain a sync with Google Drive when the user is not present.  

Perhaps I'm misunderstanding the intent of external storage.  Is it only intended to be accessed via the OwnCloud web application? I.e. Only when the user is present and able to give consent via a browser.

I've looked at core/apps/files_external/lib/google.php and it does not appear to use server to server authentication. Google has a [guide](https://developers.google.com/api-client-library/php/auth/service-accounts) that should help someone if this change is necessary.

Hope this helps.

**Comment by PVince81** [comment] 2015-11-05 12:21
@ajhepple thanks for the infos. The purpose of GDrive external storage is to have ownCloud show the GDrive folder inside the virtual file tree. There are situations where the ownCloud sync client operates and would access these GDrive folders to sync them up or down to the local machine.

I believe this ext storage is quite old, so it might be using old API already or an older approach. Maybe service account count work, but not sure how many changes would be needed to make this work.

From the doc of the service account approach, it looks like receiving a new token after expiration should just be a matter of querying a new one, possibly without any user interaction.

Not sure in what way refreshing tokens differs from the "webapp" approach ?

**Comment by PVince81** [comment] 2015-11-05 12:23
Ok let's have a look at the webapp mode doc: https://developers.google.com/api-client-library/php/auth/web-app

**Comment by PVince81** [comment] 2015-11-05 12:25
Hmmm, the docs say this:
```
If your application needs offline access to a Google API, set the API client's access type to offline:

$client->setAccessType("offline");

After a user grants offline access to the requested scopes, you can continue to use the API client to access Google APIs on the user's behalf when the user is offline. The client object will refresh the access token as needed.
```

This is what the code already does, so the question is why the PHP client lib doesn't properly refresh the access token.

**Comment by Xenopathic** [comment] 2015-11-05 13:04
Another point about our implementation - we currently require the user to go into the developer console and set up an ownCloud 'app', then copy in the client ID and secret. From what I understand, it might be possible for the system administrator to do this step once for the server, then any users who want a GDrive mounted get the 'Allow this application to access ...' authorization page which grants access. It would massively streamline the process of setting up GDrive if it works as I think it does.

**Comment by PVince81** [comment] 2015-11-05 17:22
I still have the feeling that something is wrong with either google's servers, or something must have changed in the way the request is done. For some reason there is no "refresh_token" in the returned JSON (and googling for missing refresh token google api yields some results).

Does anyone have a very old GDrive mount.json and could check whether in the past it used to have a refresh token ?

Not having a refresh token might explain why the library isn't attempting to do any refresh.

**Comment by PVince81** [comment] 2015-11-05 17:23
- investigate possibly missing refresh_token case
- update the php library ? (maybe it fixes that already)

**Comment by AdamWill** [comment] 2015-11-05 22:16
i'm pretty sure there was a refresh token when I first did the port.

(what the hell is up with random two letter combinations turning into arrows? am I the only one seeing this?)

**Comment by PVince81** [comment] 2015-11-06 08:15
Oh, look what I found: http://stackoverflow.com/a/10220362

If I understand well this means that if a user U and a domain D had a past approval for the app, it will not send the refresh token again. It's probably assuming that the refresh token is already known and stored somewhere. In my local test case I'm always testing with the same domain name, user and app.

I added this:
```php
	$client->setApprovalPrompt('force');
```

in apps/files_external/ajax/oauth2.php

and now google asks me for permissions again, and after that: refresh token appears in mount.json!

Now let's see if the thing refreshes properly in the next hours...

**Comment by AdamWill** [comment] 2015-11-06 08:30
that still somehow sounds like the wrong answer, though. you shouldn't need the user to keep re-accepting the approval prompt, and that post is from 2012 and this was working more recently than that, or at least seemed to be. still, I can't say I know what the right answer is for sure; store the refresh token? and we still don't know what changed (or if this was somehow broken all along and we didn't notice).

**Comment by PVince81** [comment] 2015-11-06 08:48
The refresh token is always stored in mount.json. I suspect that the people who are experiencing this issue are those who deleted their GDrive mount and recreated it later / separately (and losing the refresh token in the process).

I think for the people in this situation the user will only have to accept the approval prompt once. Once the refresh token is stored, no further approval will be needed.

**Comment by PVince81** [comment] 2015-11-06 08:48
Will confirm this in a few hours when I reach the timeout :smile:

**Comment by PVince81** [comment] 2015-11-06 09:36
- [ ] check whether de-authorizing the app with the current code makes it receive refresh-token (as a workaround)

**Comment by PVince81** [comment] 2015-11-06 11:24
Test successful! When the refresh token exists in mount.json, the library is able to properly refresh the session.

Let's clarify again a little bit:

When using Google Drive we have two situations:
1) Someone sets up a Google Drive from the very first time (brand new!) and authorizes the app for a user+domain once. In this situation the API will properly deliver a refresh_token and Google Drive will continue to work properly.

2) In some cases, people might delete the storage and/or reinstall ownCloud, whatever. After that they want to re-setup the Google Drive mount. Since the app (user+domain) was already authorized before, the API doesn't deliver the refresh token any more.

I think what we are observing here is situation 2.

This can be reproduced as follows:

1. Delete all Google Drive storages in ownCloud
1. First, login into google with the user for which you mounted the storage / authorized the app
1. Go to https://security.google.com/settings/security/permissions?pli=1
1. Remove access to your OC Google Drive app (mine is called "OC Storage Access)
1. Setup Google Drive storage in ownCloud, grant access
1. Check "data/mount.json", see that it contains "refresh_token"
1. Delete the storage again
1. And mount the storage again, grant access
1. Check "data/mount.json" again => no more "refresh_token"

This might explain why not everyone is having this issue.

The fix for this is to always force the "Grant access" procedure to re-request the permission. This will only happen when setting up the storage **again**.

**Comment by PVince81** [comment] 2015-11-06 11:47
So for now the workaround is to deauthorize the app in the user's google account, then your storage will work again. But every time you remount it, you'll have to deauthorize. So the workaround only work if there is only a single GDrive account.

PR will follow soon

**Comment by PVince81** [comment] 2015-11-06 12:22
PR here https://github.com/owncloud/core/issues/20361

**Comment by PVince81** [comment] 2015-11-06 15:28
@SergioBertolinSG can you retest?

**Comment by Undeadhunter** [comment] 2015-11-09 08:45
I had the same issue. This did indeed resolve it.

**Comment by htschannerl** [comment] 2015-11-09 10:27
Hello,

I'm having this problem but few days ago I'm testing again and discovery
something interesting.

I'm using a VM with Fedora 22 with owncloud-server-8.2.0-2.1.noarch.
If I use a old credential of google drive api the application don't create
on the file mount.json the parameter to refresh the token, but if I create
a new credential for web application e use for the first time on the
owncloud after appear the page to authorization of owncloud to access
offline my credential I saw in the file mount.json the parameter of refresh
token.

Now I'm waiting more than one hour to see if works.

Thanks.

Em seg, 9 de nov de 2015 às 06:45, Undeadhunter <notifications@github.com>
escreveu:

**Comment by PVince81** [comment] 2015-11-09 12:04
Fix was confirmed by @SergioBertolinSG and will be in the upcoming 8.2.1.

Closing.

**Closed by PVince81** 2015-11-09 12:04 UTC
Labels: 3 - To Review, app:files_external, bug, discussion
