### ISSUE TITLE
[10.0] after admin enables the encryption recovery key, users don't see the encryption section in the settings

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27398] opened 2017-03-16 09:52 UTC
### Steps to reproduce
1. as admin enable encryption
2. as admin add recovery
3. as user try to opt in to recovery key

cc @tomneedham 

### Expected behaviour
there should be an encryption section in the settings with a checkbox to opt in to recovery

### Actual behaviour
```json
{
  "reqId": "4mLwfKUAMQ2Vmjb01llj",
  "remoteAddr": "127.0.0.1",
  "app": "no app in context",
  "message": "Failed to load panel: OCA\\Encryption\\Panels\\Personal with error: Could not resolve OCP\\ILogger! Class can not be instantiated",
  "level": 3,
  "time": "2017-03-16T10:53:29+00:00",
  "method": "GET",
  "url": "/oc/core/index.php/settings/personal?sectionid=general",
  "user": "admin"
}
```

Trying to fiddle with the url doesn't help:
```json
{
  "reqId": "rDkr6xVYyal9lZ0ELOF0",
  "remoteAddr": "127.0.0.1",
  "app": "no app in context",
  "message": "Failed to load panel: OCA\\Encryption\\Panels\\Personal with error: Could not resolve OCP\\ILogger! Class can not be instantiated",
  "level": 3,
  "time": "2017-03-16T09:37:45+00:00",
  "method": "GET",
  "url": "/oc/core/index.php/settings/personal?sectionid=encryption",
  "user": "admin"
}
```
Using a non admin user gives the same error.
### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** sqlite

**PHP version:** 5.6

**ownCloud version:** git master

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**Comment by butonic** [comment] 2017-03-16 10:28
meybe @settermjd can confirm?

**Comment by settermjd** [comment] 2017-03-20 09:42
I can confirm. 
<img width="190" alt="screen shot 2017-03-20 at 10 42 20" src="https://cloud.githubusercontent.com/assets/196801/24094662/f7973faa-0d59-11e7-87a9-b7bd21d88135.png">

**Comment by tomneedham** [comment] 2017-03-27 11:53
@DeepDiver1975 can you take a look at this. It appears the DI magic is not loading ILogger. yet the AdminPanel seems to load just fine

**Comment by PVince81** [comment] 2017-04-11 15:59
Is this still happening with 10.0 beta2 ? @tomneedham or did you fix it ?

**Comment by PVince81** [comment] 2017-04-12 16:05
still happening on master (0505659123ab5111bc7c755a713cf1a85e2c48a4)

**Comment by PVince81** [comment] 2017-04-12 16:07
indeed, that DI issue is really weird... but this surely isn't the first app that adds personal panels ?

**Comment by PVince81** [comment] 2017-04-12 16:13
Did a quick debug session and I saw more exceptions than what was logged.
Strangly `IStorage` wasn't found but it seems the exception says another interface was not found.

I can imagine that `IStorage` cannot be resolved through regular DI because the core container doesn't have that one declared.

So possibly there are two bugs:
- exceptions from resolving do not always correctly match the problem
- PersonalPanel needs another way to access the encryption's IStorage instance

**Comment by PVince81** [comment] 2017-04-12 16:21
Fix is here https://github.com/owncloud/core/pull/27637

Needed to add the `OCP\Encryption\Keys\IStorage` into the app's container because else the DI container has no way to find out what instance to get. (in the future we should fix the server container to work more with interface names than aliases)

**Closed** 2017-04-13 14:28 UTC
Labels: app:encryption, bug, regression, sev1-critical
