### ISSUE TITLE
Change request: emails sent by CalDAV (invites) should be sent From: user

### ISSUE THREAD

**Issue by zzgab** [owncloud/core#29093] opened 2017-09-25 10:03 UTC
Currently, the ReplyTo: field is set as the user's address, and the From: field is the system's address (general settings).

When sending a calendar invite, some users would prefer that the recipients receive the invite email as sent from the event's owner, instead of the organization's global postmaster contact.

https://github.com/owncloud/core/blob/cd837fc5eaf33698e3d5d738e358b8e36d6da6ce/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L111

**Comment by kdslkdsaldsal** [comment] 2017-09-25 10:07
Closing as a duplicate of https://github.com/owncloud/core/issues/25470.

However it looks to me that it its unlikely to bee implemented for the reasons explained in https://github.com/owncloud/core/issues/25470#issuecomment-278371950

**Closed by kdslkdsaldsal** 2017-09-25 10:07 UTC

**Comment by zzgab** [comment] 2017-09-25 10:16
@kdslkdsaldsal All right for the duplicate -- sorry.
I don't fully agree with some of the reasons explained in #25470.
At the very least, it could be an option in the settings. Most OC admins will know to configure properly their MTA to correctly send mail on behalf of registered users of the OC instance.
If they can't, they would uncheck the "send event invites from owner's email" checkbox that we could put in the settings.
Still rejected?

**Comment by kdslkdsaldsal** [comment] 2017-09-25 10:23
@zzgab #25470 is still open so its possible to give your feedback in there. :)
