### ISSUE TITLE
IE9 Finish setup button not visible when selecting MySQL or others

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16605] opened 2015-05-28 12:54 UTC
### Steps
1. Open the setup page of ownCloud
2. Select "MySQL"

### Expected result
Button "Finish setup" visible and clickable

### Actual result
The button "Finish setup" disappears.
If you switch database types you might see it appear shortly during the animation.

### Versions
ownCloud 8.1 git master (e1483f65c3cd800f90e962764b06bf2379ca4432) and stable8 (cd311c1ac11cfcb71e220df788b28f2d25adba5d)

@jancborchardt didn't you fix something similar recently ?

**Comment by PVince81** [comment] 2015-05-28 12:56
Something must be wrong with the container. If I reduce the vertical size even further, it starts truncating the warning box too.

![ie9-setup](https://cloud.githubusercontent.com/assets/277525/7860471/a6942d08-0549-11e5-815f-78ed2b51ea91.png)

**Comment by MorrisJobke** [comment] 2015-05-28 17:55
Duplicate of https://github.com/owncloud/core/issues/15413#issuecomment-106306913

**Comment by MorrisJobke** [comment] 2015-05-28 17:56
I introduced this regression.

**Closed** 2015-05-28 17:55 UTC
Labels: browser:ie, design, duplicate, sev2-high
