### ISSUE TITLE
Etag isn't propagated to the root of the share owner if the file is uploaded to a group reshare

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#20714] opened 2015-11-24 16:20 UTC
### Steps to reproduce
1. User setup:

    * u1 without group
    * u2 and u3 inside group g1
    * u4 and u5 inside group g2
    * u6 and u7 inside group g3

2. u1 creates folder /test
3. u1 shares /test with groups g1 and g2
4. u2 (member of g1) reshares /test with g3
5. u6 (member of g3) uploads to /test/test_file.txt

### Expected behaviour
Etag is propagated to all of the users

### Actual behaviour
u1 doesn't change the etag of the root folder. The uploaded /test/test_file.txt can be seen as expected

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
Other than some locking errors that aren't affecting the outcome, nothing worthy
```

Related smashbox testing: https://github.com/owncloud/smashbox/pull/137

**Comment by rullzer** [comment] 2015-11-24 18:15
propegator fun! @icewind1991

**Comment by PVince81** [comment] 2015-11-25 10:54
proper gator :crocodile:

**Comment by icewind1991** [comment] 2015-11-25 14:46
Can't reproduce on master

Did you test this with https://github.com/owncloud/core/pull/20439 merged?

**Comment by PVince81** [comment] 2015-11-25 15:24
@icewind1991 seems it was observed on 8.2.1

**Comment by icewind1991** [comment] 2015-11-25 15:41
Do we want to look into a separate fix for 8.2.x (no idea how much work that will take pre-9.0 etag propagation is a complex beast) or rely on #20439 and only have it fixed for 9.0?

**Comment by PVince81** [comment] 2015-12-03 15:53
Yes, let's look into a 8.2 specific fix. Hopefully it won't be that complicated.

**Comment by icewind1991** [comment] 2015-12-09 12:39
Fix is here: https://github.com/owncloud/core/pull/21044

**Closed** 2015-12-10 11:11 UTC
Labels: feature:sharing, sev2-high
