### ISSUE TITLE
Deleting LDAP user is not possible

### ISSUE THREAD

**Issue by BiasF** [owncloud/core#27861] opened 2017-05-11 12:00 UTC
### Steps to reproduce
1. Delete user from LDAP
2. fire command sudo -u www-data php occ ldap:show-remnants
3. Fire Command sudo -u www-data php occ user:delete owncloud-user-id

### Expected behaviour
The user is deleted

### Actual behaviour
I get the followin error message:
 [OC\User\NoUserException]
  DB4178D7-B3D7-45AE-A774-5A1028EB998A is not a valid user anymore

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache 2

**Database:**
mySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.21 

**ownCloud version:** (see ownCloud admin page)
9.1.5

**Where did you install ownCloud from:**
Packages

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

**Comment by PVince81** [comment] 2017-05-12 14:54
@jvillafanez

**Comment by jvillafanez** [comment] 2017-05-15 08:05
@BiasF please, provide configuration and logs. If you're using memory cache (APCu, redis, memcache, etc) clear the caches and retry.

**Comment by BiasF** [comment] 2017-05-15 09:33
Hi,

clearing the APCu Cache doesn't solve the problem.

[config_report_20170515.txt](https://github.com/owncloud/core/files/1000651/config_report_20170515.txt)


The Log file doesn't show anything from today, the latest log entry is this, but I think, that is a other problem...

Exception: {"Message":"HTTP\/1.1 409 Parent node does not exist","Exception":"Sabre\\DAV\\Exception\\Conflict","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('temp\/Helgolands...', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1107,"User":"20855F2F-766C-43DD-A6E2-D8E5D2C43BEA"}

**Comment by jvillafanez** [comment] 2017-05-15 11:38
@BiasF could you check disabling the cache in order to discard problems with the cache? I guess commenting it should be enough.

**Comment by BiasF** [comment] 2017-05-15 12:05
Hi,

I removed the cache configuration from config file and tried again.
it doesn't fix the problem :/

**Comment by jvillafanez** [comment] 2017-05-15 13:23
I guess the last easy thing to do is to manually change the delete status for the user: go to the "preferences" table in the DB, look for the target user and user_ldap app, change the "isDeleted" value to "0"; then retry.

Are other users affected by this issue? Have you deleted other users under the same conditions sucessfully? I wonder if this is reproducible or just something that happened.
I did try LDAP user deletion without caching and I didn't bump into this issue... maybe it's reproducible by using the cache, but then it's not possible to fix it by disabling it. If you can remove another LDAP user (maybe one created just for testing this), try to remove it disabling the cache first. This could prove that by using the cache we reach an unrecoverable situation.

**Comment by BiasF** [comment] 2017-05-15 13:32
Hi,

I tried different users which are listet under show-remants, same issue.

I asked a colleague, he tells me that he deleted some users successfully a few days ago (before I installed the upgrade to Owncloud 9.1.5 )


I will try to set the value in my DB

**Comment by BiasF** [comment] 2017-05-15 14:04
Hi,

after setting the "isDeleted value" to 0, the user:delete command say this:

sudo -u www-data php ./occ user:delete "DB4178D7-B3D7-45AE-A774-5A1028EB998A"
User does not exist

Is it normal, that LDAP user aren't listed in oc_users?

**Comment by jvillafanez** [comment] 2017-05-16 08:46
> I asked a colleague, he tells me that he deleted some users successfully a few days ago (before I installed the upgrade to Owncloud 9.1.5 )

Which version did you upgrade from? It could help to limit the set of changes we should check.

> sudo -u www-data php ./occ user:delete "DB4178D7-B3D7-45AE-A774-5A1028EB998A"
User does not exist

This should be fine as long as the user really doesn't exists. His data should also have been deleted.

> Is it normal, that LDAP user aren't listed in oc_users?

Yes, this is normal. oc_users contains the users created directly in ownCloud. LDAP users (specifically the mappings to access to their information in the LDAP server) are stored in other place.

**Comment by terrytibbles** [comment] 2017-05-21 11:18
Hello,

I've also got this problem. The software versions are as follows:

Apache: 2.4.25
PHP: 7.0.18
MariaDB: 10.1.22
ownCloud: 9.1.5

I upgraded recently too, but haven't used this command for some time, so cannot verify the last time it worked.

**Comment by terrytibbles** [comment] 2017-05-21 11:25
It's nothing to do with this is it?

https://github.com/owncloud/core/pull/26848

**Comment by terrytibbles** [comment] 2017-05-25 02:11
This is important, because the files are disk on the disk once the user has been deleted, and if you are using a custom field for the internal LDAP username, if a new LDAP user gets created with the same username, then they immediately get access to the previous user's files and settings.

**Comment by jvillafanez** [comment] 2017-05-25 10:54
Reproduced using a default setup. Investigating...

**Comment by jvillafanez** [comment] 2017-05-25 12:30
Fix in https://github.com/owncloud/core/issues/28008 . This will probably be in 9.1.7 (too tight for 9.1.6 I think)

**Comment by terrytibbles** [comment] 2017-05-26 02:07
Thanks for the update.

**Comment by cdamken** [comment] 2017-07-06 15:55
@BiasF and @terrytibbles did you change any configuration in the expert tab from LDAP once the server was in production?

**Comment by terrytibbles** [comment] 2017-07-08 01:29
Not whilst the server was in production, but I am using uid for the Internal Username.

**Comment by terrytibbles** [comment] 2017-11-13 06:06
Any news on this? It doesn't seem to be in the list of changes [here](https://central.owncloud.org/t/owncloud-server-9-1-7-rc1/10343).

**Comment by jvillafanez** [comment] 2017-11-13 07:57
@terrytibbles the changes are in 9.1.7. You might want to test it with the RC1

I think the changelog for core is autogenerated so maybe only changes related to core are picked. This change is in the ldap app.

**Comment by PVince81** [comment] 2017-11-13 09:14
I see the change in the log but somehow `git log --merges v9.1.6..v9.1.7RC1` doesn't show it even though the entry is there. Maybe it's one of those rare PRs where we used the squash button which doesn't create a merge commit.

I'll add the entry in the changelog for final. Thanks for pointing out.

**Comment by PVince81** [comment] 2017-11-13 09:17
Changelog updated here https://central.owncloud.org/t/owncloud-server-9-1-7-rc1/10343

Closing. The fixing PR is https://github.com/owncloud/core/pull/28008

**Closed by PVince81** 2017-11-13 09:17 UTC
Labels: app:user_ldap, bug
