### ISSUE TITLE
[8.1 RC1] Non-migrated encryption confuses sync client

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#17035] opened 2015-06-18 21:00 UTC
See https://github.com/owncloud/client/issues/3360 which describe weird client behavior when the encryption migration has not been done.

After the upgrade to 8.1 I totally forgot that I needed to do the migration step.
@schiesbn I hope you still intend to find a way to show a message.

We need to:
- [ ] block the sync client in some way to prevent touching files
- [ ] block the sync client during key migration

**Comment by PVince81** [comment] 2015-06-18 21:02
Also to test:
- [ ] TEST: keep/force syncing before encryption migration was run
- [ ] TEST: keep/force syncing during enc migration
- [ ] TEST: keep/force syncing after enc migration was run, but before the default module is enabled

@jnfrmarks

**Comment by PVince81** [comment] 2015-06-18 21:03
@schiesbn if I remember well, you said the files would still work but be unencrypted ?
What I observed was that it was delivering the encrypted size instead of unencrypted size, which is what confused the client.

**Comment by PVince81** [comment] 2015-06-18 21:06
Ok, after I did the migration on my prod server, it re-uploaded the files again (the ones that were repeatedly uploaded) and told me to logout then relogin. I did that, and then sync worked properly again.

I think we still need to work on the UX here and double check whether moving the keys is atomic.

**Comment by PVince81** [comment] 2015-06-18 21:10
Note: the reupload case was observed with files I added to the local folder mid-upgrade, so maybe they got in a bad state somehow.

**Comment by PVince81** [comment] 2015-06-19 08:19
I'll see if I manage to reproduce this consistently. (the case above was on my productive server, not willing to roll it back)

**Comment by PVince81** [comment] 2015-06-19 08:49
Steps to reproduce.
1. Setup stable8
2. Enable encryption, log out then log in
3. Setup sync client, let it sync
4. Create two small non-empty text files locally "one.txt" and "two.txt"
5. Wait for sync
6. Upgrade to master / 8.1 (leave the client running)
7. Edit "one.txt" locally, wait for sync
8. Edit "two.txt" locally, wait for sync
9. With cadaver, do a propget on one.txt:
```
dav:/owncloud/remote.php/webdav/> propget one.txt
Fetching properties for `one.txt':
DAV: getlastmodified = Fri, 19 Jun 2015 08:42:48 GMT
DAV: getcontentlength = 8232
DAV: resourcetype = 
DAV: getetag = "24591547dd00e15443e6dacd4b09cce1"
DAV: getcontenttype = text/plain
```

The returned size is wrong.

```
+--------+---------+------------------------------------+----------------------------------+--------+---------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
| fileid | storage | path                               | path_hash                        | parent | name                | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions |
+--------+---------+------------------------------------+----------------------------------+--------+---------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
|     17 |       1 | files/one.txt                      | 23e38ba24285b3eddd9cdab4dde8ddd8 |      3 | one.txt             |        4 |        3 | 8232 | 1434703368 |    1434703368 |         1 |               12 | 24591547dd00e15443e6dacd4b09cce1 |          27 |
|     16 |       1 | files_encryption/keys/one.txt      | 22d66e7feac509343b0dc78b1ee26e60 |     12 | one.txt             |        2 |        1 |    0 | 1434703300 |    1434703300 |         0 |                0 | 5583d5c41549e                    |          31 |
|     25 |       1 | files_versions/one.txt.v1434703297 | 3377e9b9c3d649644a3c522b5a23eaed |     24 | one.txt.v1434703297 |        8 |        7 | 8232 | 1434703371 |    1434703371 |         0 |                0 | 0edaf60d98669a435ec1182d082aeb69 |          27 |
+--------+---------+------------------------------------+----------------------------------+--------+---------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+
```

Even though the newly uploaded file is not encrypted, the "encrypted" flag is still 1.

In general I think we should block uploads completely in this transitional situation.
But if we can't, then we should at least properly reset that flag.

It is probably best to tell admins to use "single user mode" when doing the 8.1 upgrade so they have enough time to go to the admin page to enable encryption, before the user's sync client start overwriting files.

**Comment by PVince81** [comment] 2015-06-19 09:03
Raised https://github.com/owncloud/documentation/issues/1231 to update the doc to tell admins to use single user mode to avoid bogus sync.

I still think we need to try and block file access during the transitional phase.
I don't think it's desirable to have files stored unencrypted in case of upload during the transitional phase.

@DeepDiver1975 @schiesbn @MTRichards

**Comment by DeepDiver1975** [comment] 2015-06-19 09:07
> I still think we need to try and block file access during the transitional phase.
> I don't think it's desirable to have files stored unencrypted in case of upload during the transitional phase.

yes - this is necessary.

@schiesbn how can we reliably identify that migration is not yet finished?

**Comment by schiesbn** [comment] 2015-06-19 09:42
The problem is that the old app is no longer there and the new one is not yet activated. We could try to hack this into the storage wrapper, because this one runs all the time. But this is really a hack because it is specifically for this one migration case and the next time someone replaces the "encryptionModule 2000" with the "encryptionModule3000" he has the same problem.

We could also add here some lines of code and enable automatically the new app is the old one gets disabled. https://github.com/owncloud/core/blob/master/lib/private/updater.php#L434 (again a ugly hack)

**Comment by PVince81** [comment] 2015-06-19 09:44
Is a migration from "module A" to "module B" even possible ? I thought that once a module is enabled it cannot be disabled any more.

Anyway, how about just blocking access to files that have "encryption === 1" in the DB as long as no encryption app is enabled ?

**Comment by PVince81** [comment] 2015-06-19 09:45
because accessing/overwriting an encrypted file when no encryption code is there to encrypt/decrypt doesn't make sense anyway. So throw 403 "No encryption module enabled" or something.

**Comment by DeepDiver1975** [comment] 2015-06-19 09:46
> So throw 403 "No encryption module enabled" or something.

should be a 50x error because the error is in the server  - not the client

**Comment by schiesbn** [comment] 2015-06-19 09:49
> Is a migration from "module A" to "module B" even possible ? I thought that once a module is enabled it cannot be disabled any more.

You can't disable the the encryption in core but the encryption modules are just apps you can enable/disable in the apps menu.

> Anyway, how about just blocking access to files that have "encryption === 1" in the DB as long as no encryption app is enabled ?

We already block it for read operations. Until now we allowed the write operation because this way you don't lose you data, we just replace the encrypted one with a unencrypted one if encryption was disabled. But now that we no longer allow to disable encryption maybe it makes sense to block write operations too. Hope I don't miss anything which breaks in this case... I will have a look.

**Comment by PVince81** [comment] 2015-06-19 09:51
Cool, thanks.

**Comment by PVince81** [comment] 2015-06-19 09:53
We might also need to make it return the correct size on PROPFIND. Else the sync client might try and reupload the same file over and over again, believing that it has changed because of the size mismatch.

So using a similar logic, if file has "encrypted" set to 1, but no encryption module is enabled, then return the unencrypted_size if not 0, else size.

**Comment by schiesbn** [comment] 2015-06-19 10:07
Hm, I just tried it on the web interface. Directly ofter the upgrade oC8->oC8.1 I can't download a encrypted file and I can't overwrite a existing encrypted file, both times I get a error message that the encryption module doesn't exists. Is this different with the sync client. The only thing which works is upload/create new files. They are simply not encrypted in this case, but I think this should be OK

**Comment by DeepDiver1975** [comment] 2015-06-19 10:09
> Is this different with the sync client.

I was explicitly testing these cases back in the days as we implemented this

**Comment by DeepDiver1975** [comment] 2015-06-19 10:09
we might need to debug into this - a missing execution path????

**Comment by schiesbn** [comment] 2015-06-23 12:30
fix merged

**Closed by schiesbn** 2015-06-23 12:30 UTC
Labels: app:encryption, bug, sev2-high
