### ISSUE TITLE
Cannot delete "Shared" folder on S3

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#11919] opened 2014-11-03 12:24 UTC
On our S3 server I cannot delete the "Shared" folder even when all files have been moved out. This is a different behaviour from what I can do on my own installation where I can delete the folder.

![2014-11-03_13-22-22](https://cloud.githubusercontent.com/assets/878997/4882301/4d1e6c4e-6354-11e4-871b-796eb5d110c6.png)

I suspect this is also the root cause of bugs such as https://github.com/owncloud/activity/issues/164

@schiesbn Any idea?

**Comment by butonic** [comment] 2015-01-23 12:11
@LukasReschke I rescanned your files. Should be fixed.

**Comment by butonic** [comment] 2015-01-23 12:31
The shared folder only had permissions 17. My gut feeling is that somewhere during sharing or the migration there is a case that allows permission updates to bubble up into the local storage. The only code I found to be related so far seems to be https://github.com/owncloud/core/blob/stable7/lib/private/files/view.php#L919 and https://github.com/owncloud/core/blob/stable7/lib/private/files/view.php#L989. Those lines update the permissions which might than bubble up throug the sharedstorage into the home/local storage. The whole thing might be a duplicate of https://github.com/owncloud/core/issues/10299 and as such be fixed with OC8. Might also only be a problem whon legacy local storages are still in play (yours was a home storage though). 

Yes that's a lot of might and could ... debugging remote systems is hard when you cannot reproduce the problem locally.

**Comment by DeepDiver1975** [comment] 2015-01-23 12:45
Is S3 configured to show all shares in the folder shared? In this case deleting that folder might not be allowed.

**Comment by LukasReschke** [comment] 2015-01-23 12:46
I'll test if this resolves https://github.com/owncloud/activity/issues/164 for me as well

**Comment by butonic** [comment] 2015-01-23 13:07
hm `'share_folder' => '/Shared'` is set.

**Comment by LukasReschke** [comment] 2015-01-23 13:09
I moved `/Shared/owncloud` to `/owncloud/` and still all new activities link to `/Shared/owncloud` instead of `/owncloud/`. This is really annoying and I don't know what else is broken due to that…

**Comment by PVince81** [comment] 2015-10-08 12:29
@nickvergessen wasn't this https://github.com/owncloud/core/issues/11919#issuecomment-71190833 fixed recently ?

**Comment by nickvergessen** [comment] 2015-10-08 12:54
Activities are fixed

**Closed** 2015-10-08 13:07 UTC
Labels: bug, sharing
