### ISSUE TITLE
Editing a file with quota almost depleted makes file unable to download.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16268] opened 2015-05-12 09:57 UTC
### Steps to reproduce

1. Enable encryption app.
2. Enable encryption module in admin page.
3. Relogin.
4. Create user1.
5. Assign him a quota of 2.1MB.
6. Login as user1. (Relogin if needed).
7. Upload 2 MB
8. Upload some small text files.
9. Edit it.
10. Go back, open the file.

### Expected behaviour
user1 can open file.

### Actual behaviour
user1 can't open the text file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
{"reqId":"hvfTi\/arBJwf7lCzGubX","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Encryption library: Decryption (symmetric) of content failed: error:0906D06C:PEM routines:PEM_read_bio:no start line\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(294): OCA\\\\Encryption\\\\Crypto\\\\Crypt->decrypt(false, false, 'vADBM5MOiE0eej+...', 'AES-256-CFB')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(275): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('tte+Fb1DsKqnjSo...', 'vADBM5MOiE0eej+...', 'AES-256-CFB')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(432): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('tte+Fb1DsKqnjSo...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(278): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(173): stream_get_contents(Resource id #44)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(230): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->file_get_contents('files\\\/owncloudp...')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(938): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_get_contents('files\\\/owncloudp...')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(471): OC\\\\Files\\\\View->basicOperation('file_get_conten...', '\\\/\\\/owncloudpropa...', Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(669): OC\\\\Files\\\\View->file_get_contents('\\\/\\\/owncloudpropa...')\\n#10 \\\/opt\\\/owncloud\\\/apps\\\/files_texteditor\\\/ajax\\\/loadfile.php(39): OC\\\\Files\\\\Filesystem::file_get_contents('\\\/\\\/owncloudpropa...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(153) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#12 [internal function]: __lambda_func(Array)\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func('?lambda_440', Array)\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tex...')\\n#15 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":351}","level":4,"time":"2015-05-12T09:49:44+00:00"}
```

### Client configuration

**browser**
Chrome 41

**Comment by SergioBertolinSG** [comment] 2015-05-12 10:53
This is no easily reproducible, I am closing it until i get proper steps. The file get corrupted somehow.

**Comment by SergioBertolinSG** [comment] 2015-05-12 13:08
OK, reproduced. user1 has to be 100% quota full. With user1 edit the file and there are no warnings. Later with user1 try to open the file and you can't.

**Comment by PVince81** [comment] 2015-05-15 14:48
Yes, this is because the quota stream wrapper is hard-limiting.
Duplicate of https://github.com/owncloud/core/issues/7626

**Closed by PVince81** 2015-05-15 14:48 UTC
Labels: app:files_encryption, app:files_versions, bug, sev2-high
