### ISSUE TITLE
OC 9.1 fresh install, connect to existing database

### ISSUE THREAD

**Issue by andrewjones216** [owncloud/core#27743] opened 2017-04-25 13:04 UTC
Link to forum discussion:
https://central.owncloud.org/t/install-oc-9-1-and-connect-to-an-existing-db/7121

### Steps to reproduce
1. Fresh server build, download owncloud from official source. Unzip and configure web server.
2. Go to OwnCloud installation wizard
3. Enter in existing db name, db admin and db admin password.

### Expected behaviour
The new installation connects to the existing database.

### Actual behaviour
Installation wizard fails, see logs below. 
For the purpose of this SELinux has been disabled but will be enabled for production.
OwnCloud attempts to create oc_root account and fails because it already exists, and it creates another account with oc_root1 oc_root2 etc. See screenshot below:
![9992f942e0287fa35a2c005d3b023bd8132a4cd9](https://cloud.githubusercontent.com/assets/12948449/25386287/c5c9d8da-29be-11e7-91c7-83a841e37943.jpg)

### Server configuration
Operating system: CentOS 7
Web server: Apache
Database: MySQL
PHP version: 5.4.16
ownCloud version (see ownCloud admin page): 9.1.4
Updated from an older ownCloud or fresh install: Fresh Install
Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):
External Storage, external authentication, reverse proxy and server-side encryption.

Installed from:
https://download.owncloud.org/community/owncloud-9.1.5.zip

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Instance not setup, no login. 

**The content of config/config.php:**

```
[root@xxx ~]# cat /var/www/owncloud/config/config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocjf9v8kliyd',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => '10.1.10.xxx',
  ),
  'datadirectory' => '/mnt/glusterfs',
  'overwrite.cli.url' => 'http://10.1.10.xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root3',
  'dbpassword' => 'xxx',
);

```

**Are you using external storage, if yes which one:** 
GlusterFS

**Are you using encryption:** 
Yes

**Are you using an external user-backend, if yes which one:**
OpenLDAP

### Client configuration
**Browser:**
Chrome 56

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WOTRGhPtOkSI7xOFEDnggQAAAAU","remoteAddr":"10.1.10.xxx","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `owncloud` . * TO 'oc_root'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'oc_root'@'%' to database 'owncloud'","level":3,"time":"2017-04-05T11:12:26+00:00","method":"POST","url":"\/index.php","user":"--"}
```

Have seen this post here but it references a Postgres DB [https://github.com/owncloud/core/issues/25665](url)

**Comment by PVince81** [comment] 2017-04-25 14:17
Yes, enhancement request: closing as duplicate of https://github.com/owncloud/core/issues/25665

**Closed by PVince81** 2017-04-25 14:17 UTC
