### ISSUE TITLE
OC_Image doesn't always set imageType correctly

### ISSUE THREAD

**Issue by gvde** [owncloud/core#18645] opened 2015-08-28 22:34 UTC
OC_Image has imageType = IMAGETYPE_PNG by default.

Several load functions like loadFromBase64, loadFromData, loadFromFileHandle, load don't (always) set imageType to the correct type of image loaded.

For example, if you load a JPEG with loadFromData() imageType remains on IMAGETYPE_PNG.

Due to this, some other image processing functions don't correctly work or cause errors.

For example you get error "OC_Image->fixOrientation() Image is not a JPEG" if you call fixOrientation() on a JPEG loaded with loadFromData even though it's in fact a JPEG.

imageType should always match the type of image. All functions seems to set mimeType correctly but lack to set imageType...

**Comment by karlitschek** [comment] 2015-08-29 12:04
Do you want to open a pull request?

**Comment by gvde** [comment] 2015-08-29 15:13
I don't fully understand how everything in OC_Image works together and there seem to be some more issues to get fixOrientation working. Commit 88db5a365b53e713fe31bcc032fc22e48a56accc sets the imagetype work loadFromData() and loadFromBase64(). It's still missing for load() if it gets passed a resource.
With this commit, fixOrientation fails with "OC_Image->fixOrientation() No readable file path set" if I upload a jpg into a contact. As it doesn't come from a file it looks like a more general issue here how to handle images loaded from other sources than files.
So I think someone who has a better understanding of that should have a look at this as further changes may have implications I don't see...

**Comment by PVince81** [comment] 2015-08-30 10:25
@georgehrke @oparoz

**Comment by oparoz** [comment] 2015-10-04 12:53
@gvde The first step would be to list all the methods in image which require a proper imagetype to be set and then the best thing to do is to provide a PR so that we can test various scenarios. The unit/integration tests of Preview should give us a first indication of if there are side-effects.

**Comment by oparoz** [comment] 2015-10-04 13:01
OK, quick assessment.

**Type is only set when an image is loaded from file**

Affected methods:
* `getOrientation()` Should break orientation support
* `preciseResize()` Should break transparency support
* `centerCrop()`Should break transparency support
* `crop()`Should break transparency support

So, it would be good to get a PR which also includes setting the imagetype for resources-

**Comment by PVince81** [comment] 2017-04-06 10:03
Please try again with 9.1.4 or 10.0 beta

**Comment by zero0cool0** [comment] 2018-08-22 18:07
Has this issue been fixed in 10.0.9.5? Reason for asking is that EXIF based image rotation is failing for all JPG images in my vanilla 10.0.9.5 installation.
Looking at the code, it seems that fixOrientation is failing because `loadFromFileHandle()` does not set the imageType but I'm not an expert.

Relevant log file lines...

`{"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"Generating preview for \"\/admin\/files\/IMG_1928.JPG\" with \"OC\\Preview\\JPEG\""}
{"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"OC_Image->fixOrientation() Image is not a JPEG."}
{"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"OC_Image->fixOrientation() Orientation: -1"}
`

**Comment by PVince81** [comment] 2018-08-23 11:33
do you have more details about setup and reproduction steps ? see https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by zero0cool0** [comment] 2018-08-23 12:18
### Steps to reproduce
1. Install owncloud 10.0.9.5 from scratch
2. Upload a JPG image which contains EXIF orientation information other than 0°, like the one attached. It doesn't matter if whether through a sync-client or through the web interface.

![img_1928](https://user-images.githubusercontent.com/8344334/44524093-8047b880-a6dc-11e8-8736-6218f7d557b4.JPG)

$ exiftool-5.26 IMG_1928.JPG
File Name                       : IMG_1928.JPG
File Type                       : JPEG
**Orientation                     : Rotate 180**
X Resolution                    : 72
Y Resolution                    : 72

### Expected behaviour
The thumbnail in the web interface as well as the preview produced by the gallery app should be rotated correctly. 

### Actual behaviour
JPG images are not rotated at all and appear upside down or rotated by 90° in either direction.

### Server configuration
**Operating system**:
Ubuntu 18.04.1

**Web server:**
Apache 2 bundled with Ubuntu

**Database:**
MariaDB

**PHP version:**
7.2.7

**ownCloud version:** (see ownCloud admin page)
10.0.9.5

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
`# cat /etc/apt/sources.list.d/owncloud.list
deb https://download.owncloud.org/download/repositories/stable/Ubuntu_18.04/ /`

**Signing status (ownCloud 9.0 and above):**

Technical information
==========
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
==========
- market
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [market] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97
                        )

                )

        )

)


**The content of config/config.php:**

{
    "system": {
        "loglevel": 0,
        "updatechecker": false,
        "instanceid": "ocdp4pbe74dr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/Data\/OwnCloud-Data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "version": "10.0.9.5",
        "logtimezone": "Europe\/Zurich",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "user_backends": [
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "localhost"
                ]
            }
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "log_rotate_size": "10485760"
    }
}


**List of activated apps:**

`
Enabled:
  - activity: 2.3.7
  - audioplayer: 2.3.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - duo: 2.5.1
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.4
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - external
`

**Are you using external storage, if yes which one:** local/smb/sftp/...
none

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Operating system:**
MAC OS 10.13.6

### Logs
`
{"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"Generating preview for \"\/admin\/files\/IMG_1928.JPG\" with \"OC\\Preview\\JPEG\""} {"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"OC_Image->fixOrientation() Image is not a JPEG."} {"reqId":"BYsRLO4mFkPyHhjYrTDl","level":0,"time":"2018-08-22T20:03:50+02:00","remoteAddr":"172.16.172.83","user":"admin","app":"core","method":"GET","url":"\/owncloud\/index.php\/apps\/gallery\/thumbnails?ids=16&scale=2&square=0&requesttoken=EgooBxMNRR5vUggLO0thImBAA18VGDNhYC0iUhMoeQY%3D%3AuPDdC8tSDkPZbyTRStInvRW43iFfPfOgBf967XtJVkM%3D","message":"OC_Image->fixOrientation() Orientation: -1"}
`

**Comment by PVince81** [comment] 2018-08-23 14:01
Confirmed.

As for gallery, it's strange because someone worked on rotation in recent versions https://github.com/owncloud/gallery/pull/764 and was reported working. I wonder what changed since.

**Comment by DeepDiver1975** [comment] 2018-08-23 14:14
> As for gallery, it's strange because someone worked on rotation in recent versions owncloud/gallery#764 and was reported working. I wonder what changed since.

this is a pure client side (in browser) feature - this has no influence on the thumbnail generation

**Comment by PVince81** [comment] 2018-10-16 07:54
seems `OC_Image::loadFromData` as called by `OC_Image::loadFromFileHandle` does not set `$this->imageType`, maybe it should do so based on mime type https://github.com/owncloud/core/blob/v10.0.10/lib/private/legacy/image.php#L598

side note: seems this stores the full picture in memory ??

**Comment by PVince81** [comment] 2018-10-16 08:02
I had a local try setting imageType, now it says `OC_Image->fixOrientation() No readable file path set.`. seems that method expects to have a writable file...

**Comment by gramels** [comment] 2018-12-05 09:32
any chance that this will be fixed soon?
The gallery in 10.0.10 is useless without the thumbnail rotation popper working.
Would be migrating to nextcloud a possible fix?

**Comment by PVince81** [comment] 2018-12-05 09:35
We're going to address various preview issues as part of this project https://github.com/owncloud/files_mediaviewer. Due to the current workload probably not until beginning next year or so (10.1.1)

**Comment by gramels** [comment] 2018-12-05 10:01
Sorry, but I dont get this.
This bug was introduced with 10.0.10 and it will take now several months to be fixed? Do you expect current users to downgrade again?
A picture gallery is a core feature und working image rotation is a basic.

**Comment by PVince81** [comment] 2018-12-05 10:46
@gramels we're a small team and we currently have other priorities so we cannot start working on this right away. Fixing this is definitely planned, together with other fixes to improve the preview system in general.

I agree that it is unfortunate that a regression is taking that long to fix. There were changes that needed to be made in the preview system (related to object store support with versioning) so fixing this will not be trivial and might require bigger changes in the preview system. I do hope that said changes will be for the best.

Also note that this is open-source so anyone else can also help fixing this.

**Comment by gramels** [comment] 2018-12-05 11:08
So is the message by the owncloud team to owncloud users not to use the gallery?

Did anybody experience the same issue with nextcloud?
This might be a trigger to migrate.

**Comment by gramels** [comment] 2018-12-05 13:55
migrated to nextcloud
seemed fixed in nc 12 & 13 & 14

**Comment by TDannhauer** [comment] 2019-01-19 21:58
I have the same issue. @ PVince: Any details when it will b e fixed?

**Comment by PVince81** [comment] 2019-01-30 10:48
@sharidas please also test with external storage and make sure the file is not downloaded to temp space when on local storage. With ext storage, `getLocalFile` should download the file from the ext storage to temp space.

**Comment by PVince81** [comment] 2019-01-30 10:49
@sharidas also verify version preview: open versions panel and see the thumbnail orientation

**Comment by sharidas** [comment] 2019-01-30 13:21
> @sharidas please also test with external storage and make sure the file is not downloaded to temp space when on local storage. With ext storage, `getLocalFile` should download the file from the ext storage to temp space.

While testing with external storage SFTP, I have noticed that `getLocalFile` method returns file of `/tmp/oc_tmp_*.jpg` ( obviously for a jpg file ). And when I try to check the file in my local machine:
```
✘ sujith@sujith-ownCloud  ~/test/owncloud2   stable10  ls /tmp/oc_tmp_y9p5iR-.jpg
ls: cannot access '/tmp/oc_tmp_y9p5iR-.jpg': No such file or directory
 ✘ sujith@sujith-ownCloud  ~/test/owncloud2   stable10 
```
So I believe it is not downloaded to the tmp location. Let me know if we agree with this observation.

**Comment by PVince81** [comment] 2019-01-30 13:59
@sharidas depending on your distro the tmp files might be in chroot somewhere in /tmp. try searching for the exact file name. you'll likely need to set a breakpoint to prevent the file getting deleted

**Closed** 2019-02-01 06:45 UTC
Labels: Effort: 1d, bug, feature:previews, p3-medium, regression

**Comment by PVince81** [comment] 2019-02-01 07:12
fix will be in 10.1.1 (10.1.0 already is in code freeze)

**Comment by depeje** [comment] 2019-04-09 19:34
The fix doesn't seem to be in 10.1.1: https://github.com/owncloud/core/blob/v10.1.1/lib/private/Preview/Image.php

**Comment by phil-davis** [comment] 2019-04-09 21:49
> fix will be in 10.1.1 (10.1.0 already is in code freeze)

Predicting the specific number of a future version is a risky undertaking ;)
There was a "hotfix patch" for a particular bug and that ended up being the version called `10.1.1`

The fix for the issue here was backported to `stable10` in PR #34356. That will be in the next "regular release". At the time of writing this post the release numbering "will be" `10.2` - but of course the next release could be `10.1.2` `10.2` or `11.0` - that just depends on the semver-related content of whatever is in the release.

**Comment by depeje** [comment] 2019-04-09 21:58
Thank you for the explanation :) , it's very helpful. I mainly wanted to save other readers here the hassle of having to find this out the hard way, and verify that this patch is indeed coming to a release.

**Comment by PVince81** [comment] 2019-04-16 09:52
you can already test with the RC1 is you like: https://central.owncloud.org/t/owncloud-server-10-2-0-rc1-released/19499
