### ISSUE TITLE
obscure hidden files from view

### ISSUE THREAD

**Issue by chrisjscott** [owncloud/core#15542] opened 2015-04-10 16:12 UTC
I know this has been submitted a few times, but it never seems to get resolved - rather, it always spirals in to a philosophical argument. I'd like to put this forward:

The developers of ownCloud, as well as many of those who use it, are technically-savvy. So, of course they'd prefer to be able to see hidden files. But given a professional environment where the users are not tech-savvy (translation: 98% of the rest of the world), hidden files cause an immense amount of confusion.

Case in point: I'm the IT manager for a 60+ ad agency. I would give my left finger to be able to implement ownCloud as a way for my users to be able to access our file server from outside the office. But I can't because ownCloud insists on showing the hidden files that live on our Samba server. My users, who are not idiots but are not nerds, would be completely befuddled by this.

It's for this reason ALONE that I can't implement ownCloud in my business environment.

Seriously: this shouldn't even be a debate - please implement the ability for me, as the admin, to decide whether or not users gain access to the hidden files (which are typically hidden for a reason). All of you nerds out there can have your hidden files but the rest of the world can start using this great tool, too!

**Comment by LukasReschke** [comment] 2015-04-10 16:15
Duplicate of https://github.com/owncloud/core/issues/2589 as far I can tell :-)

**Closed by LukasReschke** 2015-04-10 16:15 UTC
