### ISSUE TITLE
Internal error trying to download a file from webDAV while it's being encrypted

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14539] opened 2015-02-26 13:12 UTC
### Steps to reproduce
1. Enable the encryption app
2. Upload a file big enough so encryption takes some time (checked with 490MB text file)
3. Try to download the file from the webDAV interface while it's being encrypted. You can download with curl just after the progress bar in the web GUI reaches the end.

### Expected behaviour
Either the request waits until the file is completely encrypted or returns a meaningful error message

### Actual behaviour
Returns an internal server error

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** stable8

**Updated from an older ownCloud or fresh install:** fresh install

### Downloaded "file" from webDAV:
```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false" lang="en"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->

        <head data-requesttoken="">
                <title>
                ownCloud                </title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
                <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
                <meta name="apple-itunes-app" content="app-id=543672169">
                <link rel="shortcut icon" type="image/png" href="/core/img/favicon.png" />
                <link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png" />
                                        <link rel="stylesheet" href="/core/css/styles.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/header.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/mobile.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/icons.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/fonts.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/apps.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/fixes.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/multiselect.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/jquery-ui-fixes.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/jquery-tipsy.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/share.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/apps/files_versions/css/versions.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/styles.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                        <link rel="stylesheet" href="/core/css/header.css?v=707d7a9655967a7429e02a6f023d37b8" type="text/css" media="screen" />
                                                        <script type="text/javascript" src="/core/vendor/jquery/jquery.min.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/jquery/jquery-migrate.min.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/underscore/underscore.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/moment/min/moment-with-locales.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/handlebars/handlebars.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/placeholders.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/jquery-tipsy.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/compatibility.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/jquery.ocdialog.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/oc-dialogs.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/js.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/l10n.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/octemplate.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/eventsource.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/config.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/search/js/search.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/oc-requesttoken.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/apps.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/snapjs/dist/latest/snap.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/placeholder.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/vendor/blueimp-md5/js/md5.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/jquery.avatar.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/avatar.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/backgroundjobs.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/apps/files_encryption/js/encryption.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/apps/files_encryption/js/detect-migration.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/core/js/share.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/apps/files_sharing/js/share.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/apps/files_sharing/js/external.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        <script type="text/javascript" src="/apps/files_versions/js/versions.js?v=707d7a9655967a7429e02a6f023d37b8"></script>
                                        </head>
        <body id="body-login">
                <noscript><div id="nojavascript"><div>This application requires JavaScript for correct operation. Please <a href="http://enable-javascript.com/" target="_blank">enable JavaScript</a> and reload the page.</div></div></noscript>
                <div class="wrapper"><!-- for sticky footer -->
                        <div class="v-align"><!-- vertically centred box -->
                                                                        <header>
                                                <div id="header">
                                                        <div class="logo svg">
                                                                <h1 class="hidden-visually">
                                                                        ownCloud                                                                </h1>
                                                        </div>
                                                        <div id="logo-claim" style="display:none;"></div>
                                                </div>
                                        </header>
                                                                <span class="error error-wide">
        <h2><strong>Internal Server Error</strong></h2>
                <p>The server encountered an internal error and was unable to complete your request.</p>
                <p>Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.</p>
                <p>More details can be found in the server log.</p>
        <br />

        <h2><strong>Technical details</strong></h2>
        <ul>
                <li>Remote Address: 10.40.10.254</li>
                <li>Request ID: 517f963f88374976d634a93a75289151</li>
                        </ul>

        </span>
                                <div class="push"></div><!-- for sticky footer -->
                        </div>
                </div>

                <footer>
                        <p class="info">
                                <a href="https://owncloud.org" target="_blank">ownCloud</a> – web services under your control                   </p>
                </footer>
        </body>
</html>
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"517f963f88374976d634a93a75289151","remoteAddr":"10.40.10.254","app":"remote","message":"Encryption key not found for \"\/admin_oc8\/files\/qaz\/big-file-4.txt\" during attempted read via stream","level":4,"time":"2015-02-26T12:54:43+00:00"}
```

**Comment by karlitschek** [comment] 2015-02-26 19:43
@schiesbn Can you have a look?

**Comment by PVince81** [comment] 2015-02-27 09:51
Making it wait is currently no possible as we have no high level locking.

I'd rather expect the "WebDAV GET" to return 404 since the file isn't there yet.

While the file is being encrypted, it is usually written into a part file. And only once the encryption is finished it would rename the file to the target file.

@jvillafanez is it a brand new file or are you overwriting an existing file ?

In the case of overwrite I could imagine that maybe the new encryption keys overwrite the old ones too early.

**Comment by PVince81** [comment] 2015-02-27 10:39
I was able to reproduce this with a brand new file.

I made a loop:
`while true; do curl -D - -X GET 'http://root:admin@localhost/owncloud/remote.php/webdav/data1.dat' ; sleep 1; done`

And while running the loop, uploaded the file through the web UI. (brand new file, not overwrite)

**Comment by PVince81** [comment] 2015-02-27 10:46
Ah! Of course!

If you upload through the Web UI, no part file is used... the real file is overwritten.
This bug probably exists since the birth of OC...

There is currently no quickfix for this.
I suppose we could fix ajax/upload.php to write in a part file first and then rename it.
In the future we'd like to make the files app use WebDAV too, so the whole part file logic would still be there.

**Comment by DeepDiver1975** [comment] 2015-02-27 10:59
> If you upload through the Web UI, no part file is used... the real file is overwritten.
> This bug probably exists since the birth of OC...

8.1 then

**Comment by PVince81** [comment] 2015-02-27 11:05
@jvillafanez I expect the clients to be able to recover from that the next time they try to download, so shouldn't be a critical issue.

**Comment by karlitschek** [comment] 2015-05-04 18:32
So this should be fixed with the new high level file locking

**Comment by PVince81** [comment] 2015-05-11 14:31
Ref #11804

**Comment by schiesbn** [comment] 2015-05-26 12:43
I remove the encryption label. The same problem happens also without encryption. As explained by @PVince81 that's because we write files uploaded over the web interface directly to the final location. If you start to download the file before the upload finished you will always end up with a broken file. Most likely this bug exists since the first day of ownCloud

**Comment by PVince81** [comment] 2015-05-26 14:09
Tested with the PR https://github.com/owncloud/core/pull/16237#issuecomment-105536426 for files locking, and now when trying to download the file it returns a LockedException instead of a broken file.

Steps to reproduce without encryption:
1. Add "sleep(1);" in the stream copy loop here https://github.com/owncloud/core/blob/master/lib/private/helper.php#L623
2. Upload a file that has several 8k blocks (ex: a 1 MB picture)
3. During upload, try and download the file with curl
4. Same with the sync client

Without the PR: getting a partial file returned.
With the PR: getting 500 LockedException

**Comment by DeepDiver1975** [comment] 2015-06-02 11:51
As a result we need to have file locking enabled by default :speak_no_evil:

**Comment by DeepDiver1975** [comment] 2015-06-08 09:46
@PVince81 if you agree I'd like to move this to 8.2 - this is yet another webui-shall-use-webdav case for me - objections?

**Comment by PVince81** [comment] 2015-06-08 09:54
Yes, let's move it to 8.2.

Additionally @jnfrmarks found that it doesn't work as expected because the data doesn't hit the PHP code yet when uploading big files, so locking only kicks in late: https://github.com/owncloud/core/issues/16769

**Comment by DeepDiver1975** [comment] 2015-06-08 10:04
> Yes, let's move it to 8.2.

:tada: - and not really a sev1 - right?

**Comment by PVince81** [comment] 2015-06-08 10:09
Considering that the sync client would retry later and no data is lost, we can probably downgrade to high.

**Comment by DeepDiver1975** [comment] 2015-09-24 13:38
@jvillafanez @SergioBertolinSG can you rerun your tests on this with latest 8.2? Locking should solve this issue - THX

**Comment by jvillafanez** [comment] 2015-09-25 08:31
Checked with 8.2 beta1 (daily) Build:2015-09-25T03:08:40+00:00 e7bc2a10e3ffd16cda8d15ff06dcbc870e34a627  and transactional file locking enabled (with redis). It returns a locked exception. :+1:

**Comment by schiesbn** [comment] 2015-09-25 08:52
Great, so we can consider this issue as fixed -> close

**Closed by schiesbn** 2015-09-25 08:52 UTC
Labels: app:files, bug, sev2-high
