### ISSUE TITLE
Cannot sync with Jolla after update to 7.0.0 No basic authentication headers were found

### ISSUE THREAD

**Issue by No-1** [owncloud/core#9880] opened 2014-07-24 19:32 UTC
Hi,

I am running OC on my own server (ubuntu) and just updated from 6.0.1 to 7.0.0. First of all the update wiped my calendar and address book. Good that I had a second copy but I did not expect that to happen.
However, since the update I am not able to sync to my Jolla anymore. I the log file I see this:
webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found
Is it possible to solve that? Syncing with my computer works fine.

I am running Ubuntu 14.04 and do not use SSL currently.

Thanks

**Comment by blizzz** [comment] 2015-03-24 22:26
The problem is unlikely in ownCloud but in the (experimental!) Jolla CalDAV implementation.

The »No basic authentication headers were found« message is not a problem, as it is normal behaviour when an unauthenticated request is done. 401 is reported and the client will (is supposed to) send credentials the next time.

On together.jolla.com many people got it somewhat running, I'd suggest to look it up there.
See for instance [here](https://together.jolla.com/question/534/implemented-in-10716-support-for-caldav-based-calendars-eg-google-calendar-released/?sort=votes&answer=45133#post-id-45133) also [here](https://together.jolla.com/question/45179/caldav-owncloud/?answer=46576#post-id-46576) and [here](https://together.jolla.com/question/71947/caldav-sync-with-owncloud-still-buggy/), but there a far more threads and replies about it.

Opposed to @JanMalte's statement, the calendar works very well for me using Kontact 4.14.2 (except i saw it unmotivatedly delete entries few times -.-).

As the calendar works fine elsewhere it is a client problem, therefore I close it here. If you still experience issues, please browse https://together.jolla.com and engage there. Or, even better, fix SailfishOS's CalDAV implementation https://github.com/nemomobile/buteo-sync-plugin-caldav/ :)

**Closed by blizzz** 2015-03-24 22:26 UTC
Labels: bug
