### ISSUE TITLE
Could not obtain lock 1 warning message when LDAP user uploads files with encryption enabled.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17907] opened 2015-07-27 13:43 UTC
### Steps to reproduce

1. Enable LDAP backend
2. Enable encryption.
3. Login with an LDAP user.
4. Upload files on it.
5. Edit files.
6. Delete files.
7. Upload files again.

### Expected behaviour
Files are edited, deleted and uploaded again.

### Actual behaviour
Warning saying: Could not obtain lock-1

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.0","versionstring":"8.1.1 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - user_ldap: 0.6.1
 - windows_network_drive: 0.1.1
Disabled:
 - external
 - files_antivirus
 - files_drop
 - files_external
 - files_ldap_home
 - objectstore
 - sharepoint
 - user_external
 - user_shibboleth
 - user_webdavauth
```

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

### Client configuration

**browser**
Chrome 43

**Server Logs**
nothing relevant, it says nothing about the errors, which is weird.
files are uploaded, but corrupted.

**Comment by PVince81** [comment] 2015-07-27 14:22
Did you enable the new file locking or the old one ?
From the apps list I see the old one enabled: files_locking.
This looks like https://github.com/owncloud/core/issues/17898

@SergioBertolinSG please confirm if this is indeed a duplicate.

**Comment by PVince81** [comment] 2015-07-27 15:03
https://github.com/owncloud/core/issues/17903 should fix this

**Comment by PVince81** [comment] 2015-07-27 15:21
Confirmed duplicate of https://github.com/owncloud/core/issues/17898.

I verified that https://github.com/owncloud/core/pull/17903 fixed the issue.
Closing.

**Closed by PVince81** 2015-07-27 15:21 UTC
Labels: app:encryption, app:user_ldap, bug, feature:locking, sev1-critical

**Comment by SergioBertolinSG** [comment] 2015-07-28 08:55
Working fine in stable8.1.
