### ISSUE TITLE
Uploading files to an external storage encrypted by other server is not possible using 8.1.7rc1

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24330] opened 2016-04-28 12:44 UTC
### Steps to reproduce:

Having two servers, server9 and server8.1 both with encryption enabled do:
1. Mount an external storage on server9, upload some files.
2. Mount same external storage on server8.1.
3. Using a user of server8.1, upload a file in the external storage.
### Expected behaviour:

Files are uploaded.
### Actual behaviour

Files cannot be uploaded, there is an error.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.7.0","versionstring":"8.1.7 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, SFTP.

**Are you using encryption:** 
Yes.

**Logs**

```
(This log appears many times)
{"reqId":"MwniqpiIyS9hLnPAiIPH","remoteAddr":"HIDDEN_IP","app":"PHP","message":"Unsupported operand types at \/opt\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Net\/SFTP\/Stream.php#175","level":3,"time":"2016-04-28T12:34:00+00:00"}
```
### Client configuration

**browser**
Chrome

**Comment by nickvergessen** [comment] 2016-04-28 12:48
Same issue as https://github.com/owncloud/core/issues/24323 ?

**Comment by PVince81** [comment] 2016-04-28 12:49
Hmm, weird use case. So it means both would use the same remote external storage (a third server ?) and each would have their own folder with their own data, encrypted, and one cannot access the data of the other one. Not sure if that use case makes sense.

But I'd still expect OC 8.1.7 to be able to upload files even if there are other untouched encrypted files.

Can you try disabling the firewall just in case ?

**Comment by PVince81** [comment] 2016-04-28 12:52
Can we also see the log of the server that is hosting the external storage ?

**Comment by SergioBertolinSG** [comment] 2016-04-28 12:56
Disabling the firewall app doesn't help.

**Comment by SergioBertolinSG** [comment] 2016-04-28 12:57
> Can we also see the log of the server that is hosting the external storage ?

Do you mean the SFTP server?

**Comment by PVince81** [comment] 2016-04-28 13:00
Ah it's SFTP, missed that.
Ok, let me try this locally.

**Comment by PVince81** [comment] 2016-04-28 13:11
Works for me.

Steps:

1. Setup ownCloud v9.0.2RC1
1. Enable encryption + log out, log gin
1. Setup SFTP ext storage "/sftp"
1. Create folder "/sftp/enc"
1. Upload image to "/sftp/enc/oc9image.jpg"
1. Setup ownCloud v8.1.7RC1
1. Enable encryption + log out, log gin
1. Setup SFTP ext storage "/sftp"
1. Navigate into "/sftp/enc"
1. Upload another image

Works for me.

**Comment by SergioBertolinSG** [comment] 2016-04-28 13:34
Uploading from another 8.1.7rc1 server with encryption disabled works fine.

**Comment by PVince81** [comment] 2016-04-29 13:39
Not critical and not easily reproducible, moving to 8.1.8

CC @cmonteroluque

**Comment by PVince81** [comment] 2016-06-10 16:01
@SergioBertolinSG I need more detailed steps that look like https://github.com/owncloud/core/issues/24330#issuecomment-215418209
Also make sure to be clear which server is what, and what is mounted where (use real names for test folders in your steps)

**Comment by PVince81** [comment] 2016-09-20 09:43
I'm not sure this is really critical and possibly not a valid use case due to having two servers using different encryption keys but storing the files on the same storage. This cannot work.
Does it happen when connecting OC 8.2/9.0 versions ?

**Comment by PVince81** [comment] 2016-11-21 11:40
Closing due to lack of feedback.

**Closed by PVince81** 2016-11-21 11:40 UTC
Labels: app:encryption, app:files_external, bug, needs info, sev2-high
