### ISSUE TITLE
Breaking change: 10.2 changes  avatars location

### ISSUE THREAD

**Issue by j-snd** [owncloud/core#35311] opened 2019-05-23 08:09 UTC
Hi,
after upgrading with Debian package manager from 10.1 to 10.2 all avatars have gone. I have upgraded two different servers and avatars disappeared at both.

Operating system:
Debian Linux Stretch 9.9
Web server:
Apache Version 2.4.25
Database:
mysql 14.14 Distrib 5.6.30
PHP version:
PHP 7.0.33-0+deb9u3
ownCloud version: (see ownCloud admin page)
10.2.0 (stable)
Updated from an older ownCloud or fresh install:
10.1.1 (stable)
Where did you install ownCloud from:
deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /

Regards
Jochen

**Comment by davitol** [comment] 2019-05-24 08:16
@j-snd Thanks for reporting. Were the avatars hosted in an LDAP server or they were regular users

**Comment by j-snd** [comment] 2019-05-24 08:52
The avatars were from regular users. In the meantime I have upgraded another server by installing the tarball and all avatars are removed too. Did no one else had this problem? Is there a way to restore the avatars without going back to the previous version of owncloud?

**Comment by davitol** [comment] 2019-05-24 12:57
Just tested with a tarball too and I was able to reproduce it too. The info of the avatars persists in the backend but they are not shown in the webUI

**Comment by micbar** [comment] 2019-05-24 15:09
could be related to owncloud/enterprise#3332

**Comment by wassereimer86** [comment] 2019-05-25 10:20
I upgraded from 10.0.2 to 10.2.0 manually and have the same problem. The Data folder is not in the installation direrctory and the avatars are still there.

**Comment by VicDeo** [comment] 2019-05-29 12:51
most likely broken with https://github.com/owncloud/core/commit/18dc418c8a2bd3a92cae7f5c9d0448411fe6ac16

**Comment by VicDeo** [comment] 2019-05-29 13:20
yep, checkout to f5ae32e4ec11970bd16066c16732d182c21f66a0 changes the behavior.

**Comment by VicDeo** [comment] 2019-05-29 18:25
@micbar FYI: 10.2 pollute data folder on avatar upload.

**Comment by micbar** [comment] 2019-05-29 18:31
> @micbar FYI: 10.2 pollute data folder on avatar upload.

@cdamken @pako81 @voroyam 
Could be that you see avatars wrongly uploaded in customers `data/` folders instead of `data/avatars/`

**Comment by VicDeo** [comment] 2019-05-29 18:35
the fix for this issue is oneliner but we might need a repair step now to collect the garbage directories. :/

**Comment by VicDeo** [comment] 2019-05-29 18:36
@j-snd could you try the change from https://github.com/owncloud/core/pull/35363 ?

**Comment by j-snd** [comment] 2019-05-29 19:07
Hi VicDeo, I have changed Avatar.php and all missing avatars show up again. Was it this what I should try?

**Comment by micbar** [comment] 2019-05-31 15:05
@VicDeo Do you think the repair step is really necessary?

@pmaier1

**Comment by wassereimer86** [comment] 2019-05-31 15:09
If someone uploaded a new Avatar because the one befor was gone: Is it there after the update without a repair? Or does the User again have no Avatar? That´s the question which should answer the one above me.

**Comment by VicDeo** [comment] 2019-05-31 20:26
@micbar old location is a subdir of **data/avatars**.  md5 of uid with chars 1-2 and 3-4 treated as directory names
e.g if md5  is 16fdfa8f744211bb1f44be3042e5ebeb the avatar will be stored under
**data/avatars/16/fd/fa8f744211bb1f44be3042e5ebeb/**
for 10.2 it is just  **data/16/fd/fa8f744211bb1f44be3042e5ebeb/**

1. everybody started with 10.2 will have the same issue with 10.3 because the fix reverts new avatar location to the old one
2. data folder will have stray avatar directories like **16** in the example above as the new location is not unified

**Comment by pmaier1** [comment] 2019-06-03 12:10
> @VicDeo Do you think the repair step is really necessary?

Well, we should clean this up properly, yes.

**Comment by pmaier1** [comment] 2019-06-03 12:24
PR for release notes known issue https://github.com/owncloud/docs/pull/1294

**Closed** 2019-06-14 11:55 UTC
Labels: bug, p3-medium, regression
