### ISSUE TITLE
Federated shared subfolder not syncing.

### ISSUE THREAD

**Issue by ronbailer** [owncloud/core#20329] opened 2015-11-05 12:00 UTC
### Steps to reproduce
1. create user1 and user2 accounts.
2. user1 syncs root folder in desktop sync client (using default client settings).
3. user1 create a directory A and subdirectory B in A.
4. user1 share a subdirectory B whith user2 using federated cloud sharing (user2@myowncloudurl) whith edit permissons.
5. user2 access accross web interface and accept the new shared folder.
6. user2 upload f1 file into B folder.

### Expected behaviour
user1 sync client download f1 in B folder.

### Actual behaviour
The f1 file (uploaded by user2) is not synced in user1 computer.
But if user1 move B subdir to root folder everythings work properly.

### Server configuration
**Operating system:**
Debian 7
**Web server:**
Apache 2.2.22
**Database:**
Mysql 5.5
**PHP version:**
5.5.30 (Apache lib mod)
**ownCloud version:**
8.1.4
**Updated from an older ownCloud or fresh install:**
Upgraded across all versions since Owncloud 4.5

### Client configuration
**Operating system:**
Windows 10
**ownCloud client version:**
2.0.2

**Comment by karlitschek** [comment] 2015-11-05 15:03
@schiesbn any idea?

**Comment by PVince81** [comment] 2015-11-06 12:28
Pretty sure I've seen this before. If someone finds the duplicate, please link it. Thanks.

**Comment by ronbailer** [comment] 2015-11-17 12:02
I tested with owncloud 8.2 and so happen. Someone has been able to reproduce?

**Comment by ronbailer** [comment] 2015-12-14 11:45
Same issue happens in OC 8.2.1 :-(

Any news about this?

**Comment by PVince81** [comment] 2015-12-14 12:31
@schiesbn can you have a look ?

@icewind1991 is that the update detection issue ?

**Comment by Helios07** [comment] 2016-02-05 14:01
I just experienced a very similar problem that was reported by one of our users. Our scenario differs a little but I think it has the same origin as the one described here.
- User1 either shares via federated sharing or with a link with user2 (I tried both with the same results)
- User2 accepts the share respectively adds it to his ownCloud
- User2 creates another folder in his local file system in the shared folder and a file in this folder (but I think the latter is not necessary to trigger the error)
- The desktop client of user2 uploads the new folder (and the file within) and his other clients download those within 30 seconds
- Now you would expect user1's desktop client to do the same, but it doesn't. User1 has to restart his client in order to get the files downloaded to his desktop

The error also occurs if user1 and user2 are located on the same server.

**Comment by michaelstingl** [comment] 2016-02-05 14:19
@MorrisJobke Could you check the status?

00004741

**Comment by MorrisJobke** [comment] 2016-02-10 13:03
I just tested the steps of the initial post and this works in current master:

<img width="563" alt="bildschirmfoto 2016-02-10 um 14 02 12" src="https://cloud.githubusercontent.com/assets/245432/12947897/e92d00ce-cffe-11e5-85a8-1cf61cb07409.png">


Etags before the upload:

```
morrisjobke@gymir:~ » curl -i -X PROPFIND http://localhost/master/remote.php/webdav  -u abc:abc -s | egrep "href|etag"
  <d:href>/master/remote.php/webdav/</d:href>
    <d:getetag>&quot;56bb339670b25&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/A/</d:href>
    <d:getetag>&quot;56bb3396709e1&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/welcome.txt</d:href>
    <d:getetag>&quot;3387fbfb7175404a7ae56fa7a2096139&quot;</d:getetag>
morrisjobke@gymir:~ » curl -i -X PROPFIND http://localhost/master/remote.php/webdav/A  -u abc:abc -s | egrep "href|etag"
  <d:href>/master/remote.php/webdav/A/</d:href>
    <d:getetag>&quot;56bb3396709e1&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/A/B/</d:href>
    <d:getetag>&quot;56bb339670064&quot;</d:getetag>
```

etags after the upload:


```
morrisjobke@gymir:~ » curl -i -X PROPFIND http://localhost/master/remote.php/webdav  -u abc:abc -s | egrep "href|etag"
  <d:href>/master/remote.php/webdav/</d:href>
    <d:getetag>&quot;56bb343f00d4b&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/A/</d:href>
    <d:getetag>&quot;56bb343f00bb8&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/welcome.txt</d:href>
    <d:getetag>&quot;3387fbfb7175404a7ae56fa7a2096139&quot;</d:getetag>
morrisjobke@gymir:~ » curl -i -X PROPFIND http://localhost/master/remote.php/webdav/A  -u abc:abc -s | egrep "href|etag"
  <d:href>/master/remote.php/webdav/A/</d:href>
    <d:getetag>&quot;56bb343f00bb8&quot;</d:getetag>
  <d:href>/master/remote.php/webdav/A/B/</d:href>
    <d:getetag>&quot;56bb343f00a8f&quot;</d:getetag>
```

**Comment by MorrisJobke** [comment] 2016-02-10 13:14
I could reproduce this in stable8.2:

<img width="572" alt="bildschirmfoto 2016-02-10 um 14 09 41" src="https://cloud.githubusercontent.com/assets/245432/12948061/f65cd91c-cfff-11e5-90df-912b6987a653.png">


The etag of the folder B has changed, but for folder A this has not changed:

Before:
```
morrisjobke@gymir:~ » curl -X PROPFIND http://localhost/master/remote.php/webdav  -u abc:abc -s | xmllint --format "-"| egrep "href|etag"
    <d:href>/master/remote.php/webdav/</d:href>
        <d:getetag>"56bb355d0dea8"</d:getetag>
    <d:href>/master/remote.php/webdav/A/</d:href>
        <d:getetag>"56bb355d0e06d"</d:getetag>
    <d:href>/master/remote.php/webdav/welcome.txt</d:href>
        <d:getetag>"b6ac479a5830082e975888e5f9d9d3ad"</d:getetag>
morrisjobke@gymir:~ » curl -X PROPFIND http://localhost/master/remote.php/webdav/A  -u abc:abc -s | xmllint --format "-"| egrep "href|etag"
    <d:href>/master/remote.php/webdav/A/</d:href>
        <d:getetag>"56bb355d0e06d"</d:getetag>
    <d:href>/master/remote.php/webdav/A/B/</d:href>
        <d:getetag>"56bb355d0d53b"</d:getetag>
```

After the upload:
```
morrisjobke@gymir:~ » curl -X PROPFIND http://localhost/master/remote.php/webdav  -u abc:abc -s | xmllint --format "-"| egrep "href|etag"
    <d:href>/master/remote.php/webdav/</d:href>
        <d:getetag>"56bb355d0dea8"</d:getetag>
    <d:href>/master/remote.php/webdav/A/</d:href>
        <d:getetag>"56bb355d0e06d"</d:getetag>
    <d:href>/master/remote.php/webdav/welcome.txt</d:href>
        <d:getetag>"b6ac479a5830082e975888e5f9d9d3ad"</d:getetag>
morrisjobke@gymir:~ » curl -X PROPFIND http://localhost/master/remote.php/webdav/A  -u abc:abc -s | xmllint --format "-"| egrep "href|etag"
    <d:href>/master/remote.php/webdav/A/</d:href>
        <d:getetag>"56bb355d0e06d"</d:getetag>
    <d:href>/master/remote.php/webdav/A/B/</d:href>
        <d:getetag>"56bb36585781d"</d:getetag>
```

@icewind1991 I guess this is because of the recent changes to the etag propagation that now works on a per-storage level. Could you link to that issue/PR? I only found the latest cleanups: https://github.com/owncloud/core/pull/20875

**Comment by cmonteroluque** [comment] 2016-02-12 14:01
@schiesbn @icewind1991 ping

**Comment by PVince81** [comment] 2016-02-12 14:03
@MorrisJobke Per-storage level etag propagation is a 9.0 feature, not 8.2.2.

**Comment by MorrisJobke** [comment] 2016-02-12 16:16
> @MorrisJobke Per-storage level etag propagation is a 9.0 feature, not 8.2.2.

@Helios07 As said - sadly we can't backport this to stable8.2 because it involves too many changes.

**Comment by MorrisJobke** [comment] 2016-02-15 09:33
This is quite critical for @Helios07 - @PVince81 @icewind1991 is there any chance to implement a hot fix for the stable8.2 branch?

**Comment by cmonteroluque** [comment] 2016-02-17 21:38
@MorrisJobke will be looking into something quick

**Comment by cmonteroluque** [comment] 2016-02-24 19:12
@schiesbn any chance you can have an urgent look at this please?

**Comment by schiesbn** [comment] 2016-02-25 14:20
I can re-produce it. What I don't get at the moment... but I will try to find out:
We are talking about etag propagation at the owner side, not at the recipient side. So there are no different sorages, etc. Just a folder structure A/B. If I upload a file to B with webdav (cadaver) the etag gets propagated correctly. If I upload a file from a second ownCloud which mounted B as a federated share we only update the etag of B but not of A. Even if technically it is in both cases a webdav upload to A/B? What's the difference here?

**Comment by PVince81** [comment] 2016-02-25 14:32
Weird... There should be no difference if it's a webdav upload, it should always propagate the etag up to the root (well, up to "/files" at least)

**Comment by schiesbn** [comment] 2016-02-25 14:48
Yes, that's really wired. For some reasons when we propagate the changes from the federated share upload is `//filename` while on the webdav upload it is `/A/B/filename`. That explains while the propagation fails for a federated share upload. In this case it only propagates the changes up to '/' which seems to be 'B'. But I couldn't find out why the paths are different. It looks like we interpret the target folder ('B') as a storage, but why?

**Comment by schiesbn** [comment] 2016-02-25 14:55
@icewind1991 any idea where this strange behavior comes from?

**Comment by icewind1991** [comment] 2016-02-25 14:59
iirc the external share dav works on a View that's rooted at the share root (`/A/B`) and not the user's home folder and propagation (in 8.2) goes up to the view's root.

it's fixed in 9.0 because the view root no longer has any impact on propagation

**Comment by schiesbn** [comment] 2016-02-25 15:01
> iirc the external share dav works on a View that's rooted at the share root (`/A/B`)

What's the reasons for that? Why does the external share dav use a different root than a "normal" dav? Could this be a quick fix for 8.1/8.2 to change to root to the users home?

**Comment by icewind1991** [comment] 2016-02-25 15:03
atm the dav servers works on top of a view, changing the root of the view would change the root of the dav server

**Comment by icewind1991** [comment] 2016-02-25 15:03
A possible qf might be to change propagation to always run on the proper user view

**Comment by schiesbn** [comment] 2016-02-25 16:34
> A possible qf might be to change propagation to always run on the proper user view

I tried now several approaches but couldn't find a solution. At the moment I don't see how this could work without large changes. But you know the code much better than me. Do you want to give it a try and propose a PR? This would be really helpful! Thanks!

**Comment by icewind1991** [comment] 2016-02-26 11:33
Will have a go

**Comment by icewind1991** [comment] 2016-02-26 11:50
https://github.com/owncloud/core/pull/22676 should do it

**Comment by schiesbn** [comment] 2016-02-26 12:08
@icewind1991 great! Thanks a lot... I will try it.

**Comment by MorrisJobke** [comment] 2016-02-26 13:56
I tested it and it works :) Thanks @icewind1991

**Closed by MorrisJobke** 2016-02-26 13:56 UTC
Labels: blue-ticket, bug, feature:federated-cloud-sharing, sev1-critical
