### ISSUE TITLE
Saving issues for Office documents in WebDAV

### ISSUE THREAD

**Issue by HontoNoRoger** [owncloud/core#14157] opened 2015-02-12 14:29 UTC
Hello!

When opening Office documents via WebDAV network drive in Windows, Office won't let me save a changed file, because it sends UNLOCK requests for the file after opening them.
Without an active lock, the office products won't save a changed file and won't repeat the request to lock the file.

After some digging I found out that Windows has a problem with WebDAV network drives if the URL has a dot in it. This is the case for default OwnCloud installations (e.g. https://example.com/remote.php/webdav).
Mounting the WebDAV network drive with a dot in it, every WebDAV file command was issued by the native "Microsoft-WebDAV-MiniRedir" Client and not by the custom client used by Office software itself. 
To fix it, it was necessary to add custom rewrite rules, change the remote.php in OwnCloud and mount the network drive with the shortened URL. Office then uses it's own WebDAV clients to handle file manipulation on WebDAV drives.

Here's an example for the Apache VHost:

```apache
# Rewrite rules
RewriteEngine On
RewriteRule ^/remote/(.*)$ /remote.php/webdav/$1 [PT]
RewriteRule ^/remote$ /remote.php/webdav [PT]
```
The /remote without slash was necessary because Windows likes to remove the trailing slash when mounting and querying the server.

The following changes in OwnCloud's `remote.php` were necessary because it would give me errors concerining the base_url:

```php
<?php

try {
    require_once 'lib/base.php';

    // Fix for OwnCloud complaining about the base path when
    // using URL rewriting for integrated WebDAV:
    $_SERVER["REQUEST_URI"] = $_SERVER['PHP_SELF'];

…
```

If an Apache Proxy is being used, it's enough to add the rewrite rules to the proxy's VHost. No need to change the `remote.php` file then.

Tested with Office 2010 on Windows 7, OwnCloud Version 7 and 8.

Could you please deliver a fix / workaround for this issue or at least document it in the administrator's documentation in case anyone else is having trouble getting Office software to work properly with the integrated WebDAV server? Thanks!

**Comment by karlitschek** [comment] 2015-02-13 03:14
@DeepDiver1975 any idea?

**Comment by DeepDiver1975** [comment] 2015-02-13 07:51
@LukasReschke was already working an enhancement of our rewrite rule - see #14081 

Unfortunately we cannot deliver rewrite rules which work out of the box because the RewriteBase need individual setup.

But we can enhance the approach and add a rewrite rule for /r/ to /remote.php/

@LukasReschke if time permits please have a look - THX

**Comment by DeepDiver1975** [comment] 2015-02-13 15:00
@karlitschek @MTRichards if we really want to support this integration case we shall also fix related issues:

- [ ] support locking on shared files #13828 
- [ ] desktop client and mobile client shall no fall apart in case a file is locked
- [ ] display lock state in the browser :question: 
- [ ] propagate lock state to backends (if applies) - e.g. sharepoint / samba

**Comment by DeepDiver1975** [comment] 2015-02-13 15:01
the decision on the last two point has an impact on the implementation #13828

**Comment by DeepDiver1975** [comment] 2015-03-03 11:56
moving this to 8.2 - with 8.1 we will drop webdav locking because it's know to be broken

**Comment by cedriccarbone** [comment] 2015-12-21 10:38
> moving this to 8.2 - with 8.1 we will drop webdav locking because it's know to be broken

It seems this bug for MS Office files is still in Owncloud **8.2.1** (released on November 18 2015). Do you have any ETA to get a patch or a fix on a maintenance release? Thanks a lot!

**Comment by DeepDiver1975** [comment] 2015-12-21 10:39
> It seems this bug for MS Office files is still in Owncloud 8.2.1 (released on November 18 2015). Do you have any ETA to get a patch or a fix on a maintenance release? Thanks a lot!

There are currently no plans to fix this. Sorry

**Comment by cedriccarbone** [comment] 2015-12-21 10:40
thanks @DeepDiver1975 for your quick answer

**Comment by LukasReschke** [comment] 2016-03-01 21:49
Dupe of https://github.com/owncloud/core/issues/22596

**Closed by LukasReschke** 2016-03-01 21:49 UTC
Labels: bug
