### ISSUE TITLE
Bad Request AFTER any file finished uploading

### ISSUE THREAD

**Issue by refsoon** [owncloud/core#11778] opened 2014-10-26 20:08 UTC
Regardless what windows client (owncloud windows, cyberduck, webdrive, carotdav) i use any file uploads almost completely to my owncloud server then near the 100% upload mark, the the server does something and the transfer ends with a "Bad Request" error. Also a message that the expected file size was xxx bytes but the actual size is 0
Webdrive has a nice log, and I can see that the file was uploaded to the last byte, but somehow the file attributes do not get passed properly to the server

i can upload files through the browser interface, but none of the clients manage to communicate to the end with the server. It happens for both HTTP and HTTPS

i'm using https://myserver.com/cloud/remote.php/webdav to list the files properly, however the uploads work through the browser only

The only modification that I can make are in the php.ini, the htaccess and of course the files from the owncloud directory

Any ideas, what I can do?

thanks

**Comment by maces** [comment] 2015-04-19 14:49
any update on this?

I have tried setting the following from #9832 (also see https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/big_file_upload_configuration.html#apache):
```
        <Directory /path/to/owncloud/>
                ...
                LimitRequestBody 2147483647
                SSLRenegBufferSize 131072
        </Directory>
```
But this did not change anything.

**Comment by PVince81** [comment] 2015-10-08 12:23
Can you try again with 8.1.3 ? I believe that some issues regarding headers have been fixed, which might affect the errors you are seeing.

**Comment by PVince81** [comment] 2015-10-08 12:32
Duplicate of https://github.com/owncloud/core/issues/9832#issuecomment-90508358

**Closed by PVince81** 2015-10-08 12:32 UTC
Labels: bug

**Comment by maces** [comment] 2015-10-10 12:40
I have tried the configuration with 8.1.3 already and again today, but still no success.
