### ISSUE TITLE
Error	core	unable to rename, file is not writable : files_versions/MNA .v	2014-11-12T20:19:17+00:00

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#12148] opened 2014-11-12 20:25 UTC
Getting this error spamming my admin log pretty frequently on OC 7.0.3 on Linux
Error	core	unable to rename, file is not writable : files_versions/MNA .v	2014-11-12T20:19:17+00:00

**Comment by PVince81** [comment] 2015-08-18 14:22
Closing as duplicate of https://github.com/owncloud/core/issues/17962 which has more details

**Closed by PVince81** 2015-08-18 14:22 UTC
Labels: app:files_versions, bug
