### ISSUE TITLE
Group Sharing problems with OC8.1.4

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20645] opened 2015-11-20 14:43 UTC
### Steps to reproduce

1. In the web interface of account A create a folder and share it with account B.
2. Within that folder, create another new folder and share it with a group that account B is a member of.
3. Now make a text file in each folder named differently so you can clearly tell which folder is which.
4. Log out and back in as account B. You'll see a folder with the same name as the one created in step 1, shared from account A. Within that folder you'll see the the test file that is in the folder created in step 2. You won't see the folder from step 2 at all.

### Expected behavior
The expected behaviour is that sharing with the group in step 2 would have no impact on account B because they already have that same content shared with them from the parent folder in account B. The UI indicates that this is the case when adding the group to the folder in step 2. This was the behaviour in OC 7. 

### Actual behavior
It appears that if you share a folder with an individual and then share a sub folder with a group that person is a member of, ownCloud re-maps the existing share to target the folder shared with the group rather recognizing that the existing shared folder is a parent as it used to in OC 7.

### Server configuration
**Operating system**: RHEL 6

**Web server:** Apache

**Database:** Percona

**PHP version:** 5.5.30

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Updated

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** Active Directory

### Client configuration
Client OS: Mac

@MorrisJobke

**Comment by MorrisJobke** [comment] 2015-11-20 14:44
I will try to reproduce but this looks like a share propagation issue

**Comment by gig13** [comment] 2015-11-20 14:49
@MorrisJobke 
It is easy to reproduce.

**Comment by MorrisJobke** [comment] 2015-11-20 15:01
I can confirm this with v8.1.3:

owner:
![bildschirmfoto 2015-11-20 um 15 52 52](https://cloud.githubusercontent.com/assets/245432/11302628/d7abc8bc-8f9e-11e5-8ea0-03f28faf16a8.png)

What I received:
![bildschirmfoto 2015-11-20 um 15 52 40](https://cloud.githubusercontent.com/assets/245432/11302854/ef00617a-8f9f-11e5-9957-df4421fc589c.png)

**Comment by MorrisJobke** [comment] 2015-11-20 15:01
On master everything is working well. I will test on stable8.2 too.

**Comment by MorrisJobke** [comment] 2015-11-20 15:04
Also works on stable8.2. So a stable8.1 issue only

**Comment by MorrisJobke** [comment] 2015-11-20 15:09
Looks like wrong parent detection:

<img width="1124" alt="bildschirmfoto 2015-11-20 um 16 08 49" src="https://cloud.githubusercontent.com/assets/245432/11303039/0a9fa278-8fa1-11e5-90eb-a0e7789c2027.png">

cc @PVince81 @schiesbn @rullzer

**Comment by MorrisJobke** [comment] 2015-11-20 15:10
The entry with ID 4 looks really fishy .... it has a wrong parent and a wrong item_target and a wrong file_target

**Comment by PVince81** [comment] 2015-11-23 16:13
@MorrisJobke if you are able to reproduce it, it might be possible to reverse-bisect it (swap "good" and "bad") to find the PR that fixes it.

**Comment by MorrisJobke** [comment] 2015-11-24 08:29
```Gherkin
Scenario: Share of folder and sub-folder to same user - core#20645
  Given user "userA" exists
  And user "userB" exists
  And group "groupA" exists
  And user "userB" belongs to group "groupA"
  And user "userA" has following folder structure
    /parent
    /parent/child
  And user "userA" has following files
    /parent/parent.txt
    /parent/child/child.txt
  Then user "userA" shares "/parent" to user "userB"
  And user "userA" shares "/parent/child" to group "groupA"
  Then user "userB" should see following folders
    /parent
    /child
  And user "userB" should see following files
    /parent/parent.txt
    /child/child.txt
```

@DeepDiver1975 @SergioBertolinSG I tried to use as much as possible of the existing behat lines. Can the other lines be implemented? Then this would be super awesome to cover incoming tickets with tests. :rocket:

**Comment by SergioBertolinSG** [comment] 2015-11-24 08:35
Yes that could be added. I'll open an issue in QA repo to not forget this.

**Comment by MorrisJobke** [comment] 2015-11-24 08:41
> Yes that could be added. I'll open an issue in QA repo to not forget this.

You rock :)

**Comment by MorrisJobke** [comment] 2015-11-24 08:56
> @MorrisJobke if you are able to reproduce it, it might be possible to reverse-bisect it (swap "good" and "bad") to find the PR that fixes it.

Starting with 8de0773214e9217d30b480609187127358c61e5a the sharing works as expected.

**Comment by MorrisJobke** [comment] 2015-11-24 08:57
I will request a backport of https://github.com/owncloud/core/pull/19530

**Comment by MorrisJobke** [comment] 2015-11-24 09:02
Should be fixed by https://github.com/owncloud/core/pull/20698

**Comment by MorrisJobke** [comment] 2015-11-25 09:26
Fix is merged and will be released in 8.1.5

**Comment by gig13** [comment] 2015-11-25 14:22
Testing feedback and customer expectation:

I get both the parent and the child folders appearing in the account of the second user as independent shares. But the parent share now maps to the correct folder and shows the child folder as it's content rather than the content of the child folder.

The behaviour in 7 ircc was that the share of the child would effectively be ignored, recognizing that that content had already be shared with the user in question in the parent.

So what I'm expecting is:
```
User A
/parent shared with user b
/parent/child shared with group user b is a member of

User B
/parent shared from user a (including all child content)
```
What I'm seeing is:
```
User A
/parent shared with user b
/parent/child shared with group user b is a member of

User B
/parent shared from user a (including all child content)
/child shared from user a (including all the content of /parent/child)
```

**Comment by MorrisJobke** [comment] 2015-11-25 15:38
> The behaviour in 7 ircc was that the share of the child would effectively be ignored, recognizing that that content had already be shared with the user in question in the parent.

No. It now behaves as it was designed. If you want the behavior you are presenting you should open a new ticket that proposes this feature request. The bug in here is fixed.

**Closed by MorrisJobke** 2015-11-25 15:38 UTC
Labels: blue-ticket, bug, feature:sharing
