### ISSUE TITLE
owncloud.org force https but the SSL Certificate is not trusted 

### ISSUE THREAD

**Issue by husisusi** [owncloud/core#14217] opened 2015-02-13 17:10 UTC
The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate.

Regards
Huusi

**Comment by strugee** [comment] 2015-02-13 17:28
I cannot reproduce in Firefox Nightly built February 12, 2015. What browser are you using?

**Comment by strugee** [comment] 2015-02-13 17:34
Yep, you're right. Looks like the cert got revoked.

https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.org (note: not a permalink)

**Comment by RealRancor** [comment] 2015-02-13 18:31
This is known, dup of: https://github.com/owncloud/core/issues/14193, https://github.com/owncloud/owncloud.org/issues/433

**Comment by MorrisJobke** [comment] 2015-02-13 19:27
This is fixed now.

**Closed by MorrisJobke** 2015-02-13 19:27 UTC

**Comment by husisusi** [comment] 2015-02-14 12:57
No it's NOT!
It's annoying  to have issue like that! 
Is it so difficult to install an Intermediate/chain certificate to link it to a trusted root certificate?
You do not need a new certificate, Please just copy Intermediate/chain certificate in your Intermediate bundle path! 
https://support.godaddy.com/help/article/5238/installing-an-ssl-certificate-in-apache-centos?locale=de-DE&countrysite=en

**Comment by RealRancor** [comment] 2015-02-14 13:03
https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.org

There are no chaining issues reported there and ssllabs should be trustworthy.

**Comment by husisusi** [comment] 2015-02-14 13:05
What about this?:
https://www.sslshopper.com/ssl-checker.html#hostname=https://owncloud.org/

**Comment by RealRancor** [comment] 2015-02-14 13:08
https://www.sslshopper.com/ssl-checker.html#hostname=https://www.owncloud.org/

works as expected. Maybe the ssl-checker of sslshopper can't handle SNI?

**Comment by husisusi** [comment] 2015-02-14 13:13
OK I see! it works with www but without www (just owncloud.org) you have ssl issue.
Can you please permanent redirect owncloud.org to www.owncloud.org or fix this issue!

**Comment by RealRancor** [comment] 2015-02-14 13:16
Hi,

i can't do anything about this as  you might have noticed that i don't have either the "Contributor" nor the "Owner" badge on the right side of my username.

Such stuff is also best reported directly to the issue tracker of the homepage at https://github.com/owncloud/owncloud.org/issues

**Comment by husisusi** [comment] 2015-02-14 13:20
This is fixed now. !?! Thanks!
