### ISSUE TITLE
Online edit is not working after onlyoffice upgrade

### ISSUE THREAD

**Issue by kalpakgarud** [owncloud/core#35494] opened 2019-06-12 05:49 UTC
I have used owncloud 10.0.10 version, integrated with onlyoffice.
It was working smothly but after upgrade onlyoffice through Market Option, i got the below error and faced challenge with online edit. Page is not coming, it shows blank page.

{"reqId":"XQCQ7Zdby4ozYmhMhxsOQgAAAAs","level":3,"time":"2019-06-12T05:43:09+00:00","remoteAddr":"103.226.169.140","user":"kalpak","app":"index","method":"GET","url":"\/index.php\/apps\/onlyoffice\/ajax\/config\/21?filePath=%2Fallusers_gw_cb_accountstatus.xlsx","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OC\\\\Share20\\\\Share::getAttributes()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Onlyoffice\\\\Controller\\\\EditorController->config(21, '\\\/allusers_gw_cb...', NULL, false)\\n#1 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Onlyoffice\\\\Controller\\\\EditorController), 'config')\\n#2 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Onlyoffice\\\\Controller\\\\EditorController), 'config')\\n#3 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Onlyoffice\\\\\\\\...', 'config', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#4 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#5 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/onlyoffic...')\\n#6 \\\/var\\\/www\\\/html\\\/oc_groots_in\\\/index.php(54): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/oc_groots_in\\\/apps\\\/onlyoffice\\\/controller\\\/editorcontroller.php\",\"Line\":503}"}

**Comment by cortho** [comment] 2019-06-12 10:05
Looks like a duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/270

**Comment by VicDeo** [comment] 2020-04-02 13:55
Please reopen if update onlyoffice app to v2.3.1 or above didn't resolve it.

**Closed by VicDeo** 2020-04-02 13:55 UTC
