### ISSUE TITLE
LDAP password revealed in cleartext in logs

### ISSUE THREAD

**Issue by didierm** [owncloud/core#18547] opened 2015-08-25 12:32 UTC
Experiencing an issue with LDAP authentication, to my surprise the password is revealed in clear text in e.g. /var/log/messages :
```
Aug 25 11:22:00 *****1 ownCloud[17022]: {handleLogin} Exception: {"Message":"Lost connection to LDAP server.","Code":0,"Trace":"#0 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/ldap.php(256): OCA\\user_ldap\\lib\\LDAP->postFunctionCall()\n
#1 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/ldap.php(39): OCA\\user_ldap\\lib\\LDAP->invokeLDAPMethod('bind', Resource id #470, '', '')\n
#2 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/connection.php(594): OCA\\user_ldap\\lib\\LDAP->bind(Resource id #470, '', '')\n
#3 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/connection.php(526): OCA\\user_ldap\\lib\\Connection->bind()\n
#4 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/connection.php(150): OCA\\user_ldap\\lib\\Connection->establishConnection()\n
#5 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/connection.php(158): OCA\\user_ldap\\lib\\Connection->init()\n
#6 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/access.php(691): OCA\\user_ldap\\lib\\Connection->getConnectionResource()\n
#7 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/access.php(839): OCA\\user_ldap\\lib\\Access->executeSearch('(&(objectclass=...', Array, Array, NULL, NULL)\n
#8 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/access.php(638): OCA\\user_ldap\\lib\\Access->search('(&(objectclass=...', Array, Array, NULL, NULL)\n
#9 \/usr\/share\/owncloud\/apps\/user_ldap\/lib\/access.php(595): OCA\\user_ldap\\lib\\Access->searchUsers('(&(objectclass=...', Array, NULL, NULL)\n
#10 \/usr\/share\/owncloud\/apps\/user_ldap\/user_ldap.php(83): OCA\\user_ldap\\lib\\Access->fetchListOfUsers('(&(objectclass=...', Array)\n
#11 \/usr\/share\/owncloud\/lib\/private\/user\/manager.php(159): OCA\\user_ldap\\USER_LDAP->checkPassword('*****2', '*****3')\n
#12 \/usr\/share\/owncloud\/lib\/private\/user\/session.php(196): OC\\User\\Manager->checkPassword('*****2', '*****3')\n
#13 \/usr\/share\/owncloud\/lib\/private\/user.php(216): OC\\User\\Session->login('*****2', '*****3')\n
#14 \/usr\/share\/owncloud\/lib\/base.php(997): OC_User::login('*****2', '*****3')\n
#15 \/usr\/share\/owncloud\/lib\/base.php(893): OC::tryFormLogin()\n
#16 \/usr\/share\/owncloud\/lib\/base.php(855): OC::handleLogin()\n
#17 \/usr\/share\/owncloud\/index.php(36): OC::handleRequest()\n
#18 {main}","File":"\/usr\/share\/owncloud\/apps\/user_ldap\/lib\/ldap.php","Line":286}
```
```
*****1 : hostname
*****2 : username
*****3 : password (cleartext)
```

**Comment by LukasReschke** [comment] 2015-08-25 12:33
Duplicate of https://github.com/owncloud/core/issues/16318

**Closed by LukasReschke** 2015-08-25 12:33 UTC
