### ISSUE TITLE
Video Shared not seekable (HTML5) 

### ISSUE THREAD

**Issue by freechelmi** [owncloud/core#19129] opened 2015-09-17 13:27 UTC
### Steps to reproduce
1. Load a mp4 file from your android device on your owncloud 
2. Share the file and visit the URL ( like http://drive.ekimia.fr/index.php/s/LR4mNubFirBYbgx) 
3. Start the video and then try to navigate backwards
4. nothing happen.

### Expected behaviour
You should be able to seek the video 

### Actual behaviour
the video is not seekable

### Server configuration
**Operating system**:

Ubuntu 14.04 server

**Web server:**

Apache 2.4

**Database:**

Mysql 5

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

8.1

**Updated from an older ownCloud or fresh install:**

Fresh install 

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (

  'trusted_domains' => 
  array (
    0 => 'drive.ekimia.fr:8092',
    1 => 'drive.ekimia.fr:8091',
    2 => 'drive.ekimia.fr',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://drive.ekimia.fr:8091',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',

  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'drive',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'ekimia.fr',
  'loglevel' => 1,
  'appstore.experimental.enabled' => true,
  'ldapIgnoreNamingRules' => false,

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
**Browser:**
Chromium 47
**Operating system:**
GNU/Linux

We are using nginx as a reverse proxy

**Comment by oparoz** [comment] 2015-09-17 13:34
Probably a duplicate of https://github.com/owncloud/apps/issues/2064

**Comment by freechelmi** [comment] 2015-09-17 13:41
Yes sorry !  i did not find it when searching opened issue.

Good news, it's seekable on Firefox 40

**Closed** 2015-09-17 13:42 UTC
