### ISSUE TITLE
Can't setup dropbox external storage

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#13698] opened 2015-01-26 23:46 UTC
* enter credentials in the external storage settings
* click on the "grant access" button
* redirect to dropbox -> click the allow button
* redirect to owncloud

## expected

* dropbox mount point is mounted

## actual

* no mount point is in external storage settings list
* owncloud.log:
```
{
	"reqId":"c2bf8fd7f5fbfacd848d08b73993a6ef",
	"remoteAddr":"127.0.0.1",
	"app":"index",
	"message":"Exception: {
		"Message":"Creating \OC\Files\Storage\Dropbox storage failed","Code":0,"Trace":"#0 apps/files_external/lib/config.php(908): OC\Files\Storage\Dropbox->__construct(Array)
		#1 apps/files_external/lib/config.php(666): OC_Mount_Config::addStorageId(Array)
		#2 apps/files_external/lib/config.php(537): OC_Mount_Config::writeData('mjob', Array)
		#3 apps/files_external/ajax/addMountPoint.php(25): OC_Mount_Config::addMountPoint('Dropbox', '\OC\Files\Stora...', Array, 'user', 'mjob', true)
		#4 lib/private/route/route.php(135) : runtime-created function(1): require_once('/home/mjob/Proj...')
		#5 [internal function]: __lambda_func(Array)
		#6 lib/private/route/router.php(250): call_user_func('\x00lambda_1914', Array)
		#7 lib/base.php(763): OC\Route\Router->match('/apps/files_ext...')
		#8 index.php(28): OC::handleRequest()
		#9 {main}",
		"File":"apps/files_external/lib/dropbox.php",
		"Line":50
	}",
	"level":4,
	"time":"2015-01-26T23:38:37+00:00",
	"method":"POST",
	"url":"/index.php/apps/files_external/ajax/addMountPoint.php"
}
```

Current master bd88874

**Comment by MorrisJobke** [comment] 2015-01-26 23:47
cc @icewind1991

**Comment by DeepDiver1975** [comment] 2015-01-27 07:12
@MorrisJobke can you test stable7 please? THX

**Comment by MorrisJobke** [comment] 2015-01-27 09:29
Works with stable7.

**Comment by PVince81** [comment] 2015-01-27 10:43
From the exception, might be related to the recent addition of stabler storage ids ? @icewind1991

**Comment by PVince81** [comment] 2015-01-27 10:51
Confirmed on master.

**Comment by DeepDiver1975** [comment] 2015-01-27 10:53
8.0 :boom:

**Comment by PVince81** [comment] 2015-01-27 11:00
There's an issue with writing incomplete configs.
For GDrive and Dropbox we need to write the incomplete config, even though it is invalid at this point. The missing value will be added after access has been granted.

Currently the Storage class throws an exception due to incomplete config. Need to recover from that.
Happens here: https://github.com/owncloud/core/blob/master/apps/files_external/lib/config.php#L908

This is because of the newly introduced "storage id" which is read from the "oc_storages" entry and saved into the config. At this stage there is no "oc_storages" entry anyway, so we might want to still write a config entry without id... ugly, but would fix this issue.

**Comment by PVince81** [comment] 2015-01-27 12:36
Hmm looks like the unit test "mountconfig.php" was broken already by that change ("Invalid configuration"), but we don't run this any more on Jenkins.

I'll try and fix these as well.

**Comment by PVince81** [comment] 2015-01-27 12:46
Fix is here: https://github.com/owncloud/core/pull/13707

**Comment by PVince81** [comment] 2015-01-27 15:32
Fixed in https://github.com/owncloud/core/issues/13707

**Closed by PVince81** 2015-01-27 15:32 UTC
Labels: 5 - To review, app:files_external, bug, Regression, sev3-medium
