### ISSUE TITLE
Password tipsy

### ISSUE THREAD

**Issue by Julian1998** [owncloud/core#14543] opened 2015-02-26 14:30 UTC
The tipsy for password strength is not moved while scrolling

Steps to reproduce:
1. change your password into a random password
2. scroll down

![unbenannt](https://cloud.githubusercontent.com/assets/2546997/6393671/67c95cb6-bdcc-11e4-843b-3716cdb9e2f6.PNG)

**Comment by DeepDiver1975** [comment] 2015-02-26 15:23
@Julian1998 which version is this? git master branch? THX

**Comment by Julian1998** [comment] 2015-02-26 15:33
yeah I´m usig git master :)

**Comment by PVince81** [comment] 2015-02-26 17:09
That's likely to be an issue everywhere, the tipsy isn't appended into the scroll container but is absolute and floating.

One idea would be to kill all tipsies when a scroll event is detected.

**Comment by nickvergessen** [comment] 2015-02-26 17:27
Confirmed on the activity stream, the solution from @PVince81 sounds like a plan

**Comment by DeepDiver1975** [comment] 2015-03-02 10:37
PR welcome - any volunteer?

**Comment by DeepDiver1975** [comment] 2015-03-27 15:26
closing this as duplicate of https://github.com/owncloud/core/issues/14094

**Closed by DeepDiver1975** 2015-03-27 15:26 UTC
Labels: bug, Junior Job
