### ISSUE TITLE
File List cropped in IE

### ISSUE THREAD

**Issue by markymif** [owncloud/core#22289] opened 2016-02-10 15:18 UTC
To reproduce
1, Upload 16 folders with content using CHROME
2, upload 5 files using CHROME
3, View the same content in IE11

Expected behaviour
You should be able to see a scrolling list of 16 folders and 5 files

Actual behaviour
In CHROME, all views are as expected
in IE 11 only 13 folders are visible, no files
in IE8 only 9 folders are visible, no files.

Server configuration
Private Server
Centos 6.7
PHP 5.4.45
MySQL 5.1.73
Apache 2.2.15
OwnCloud 8.2.2
Updated from 8.2.1

apps enabled
Enabled:
  - activity: 2.1.3
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_locking: 
  - files_mv: 0.8.1a
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - gallery: 14.2.0
  - notifications: 0.1.0
  - sharelinks: 1.0.1
  - shorten: 0.0.14
  - storagecharts2: 2.6.1
  - templateeditor: 0.1

Config File
<?php
$CONFIG = array (
  'instanceid' => 'data line removed',
  'passwordsalt' => 'data line removed',
  'datadirectory' => '/data line removed/sitedata/sftpshared',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'data line removed',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'data line removed',
  'dbpassword' => 'data line removed',
  'installed' => true,
  'loglevel' => 0,
  'logtimezone' => 'Europe/London',
  'logfile' => '/data line removed/logs/sftp/sftplogin.log',
  'forcessl' => true,
  'theme' => 'data line removed',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'sftp.data line removed',
  ),
  'secret' => 'data line removed',
  'share_folder' => '/Shared',
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'sftp',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'data line removed',
  'trashbin_retention_obligation' => 'auto, auto',
  'has_internet_connection' => true,
);

No external storage
No Encryption
No external users

Client configuration
Chrome
IE11
IE8

Operating System
windows 7
Server 2003

Logs
No errors within the log
My IP Address - - [10/Feb/2016:15:14:32 +0000] "GET /core/img/loading.gif HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
My IP Address - - [10/Feb/2016:15:14:32 +0000] "GET /index.php/apps/gallery/config.public?extramediatypes=1&token=xlix4Cz9tc51H1a HTTP/1.1" 200 102 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
My IP Address - - [10/Feb/2016:15:14:32 +0000] "GET /index.php/apps/files_sharing/ajax/list.php?t=xlix4Cz9tc51H1a&dir=%2F&sort=name&sortdirection=asc HTTP/1.1" 200 5102 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

**Comment by RealRancor** [comment] 2016-02-10 15:19
Very likely a duplicate of https://github.com/owncloud/core/issues/21373 and https://github.com/owncloud/core/issues/21203 which gets fixed in oC 8.2.3 with https://github.com/owncloud/files_pdfviewer/pull/92

**Comment by markymif** [comment] 2016-02-10 15:30
I did try this with PDF Viewer disabled but the cropping was still there so left it enabled.

**Comment by RealRancor** [comment] 2016-02-10 15:32
Then its a duplicate of https://github.com/owncloud/core/issues/20044 :-)

**Closed** 2016-02-10 15:47 UTC
