### ISSUE TITLE
oc_filecache and oc_storages cleanup

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#15390] opened 2015-04-03 10:14 UTC
Ubuntu 14.04, nginx 1.7.11, MySQL
ownCloud 8.1 pre alpha (git), updated yesterday,  no encryption, additional enabled apps: files_external

Question:
I add a external mount, eg SMB, let eyerything scan so that the oc_filecache table gets filled up.
I can browse in owncloud, I see in the database in table oc_filecache and oc_storages the corresponding entries.
When I delete the external mount, it is not longer viewable and accessible, BUT in the database, all files imported in oc_filecache and the storage ID in oc_storages are still present.

I expected, that by deleting the external mount, the database gets cleaned up.
First, that in oc_filecache, all entries for a particular storage ID get deleted
Second, that in oc_storages, the particular storage ID gets removed.

**Comment by Xenopathic** [comment] 2015-04-03 22:20
Duplicate of #10820

**Closed by Xenopathic** 2015-04-03 22:20 UTC
