### ISSUE TITLE
SQL Error with upgrade from 7 to 8

### ISSUE THREAD

**Issue by rpelissi** [owncloud/core#14061] opened 2015-02-10 16:38 UTC
Hi,
I have tried the upgrade from the 7 version to the 8 and got this:

An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_ojvx4lky6ciba RENAME INDEX appconfig_config_key_index TO oc_loqrbaud4k715': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_loqrbaud4k715' at line 1

Any ideas on why it's not working?
Thanks

**Comment by LukasReschke** [comment] 2015-02-10 16:41
Duplicate of https://github.com/owncloud/core/issues/14003

**Closed by LukasReschke** 2015-02-10 16:41 UTC
