### ISSUE TITLE
Start page (files) is empty after upgrade to 8.1.3

### ISSUE THREAD

**Issue by wikon** [owncloud/core#19071] opened 2015-09-16 05:57 UTC
After upgrading to OC 8.1.3, no more files are displayed in the web interface.
![screenshot](https://cloud.githubusercontent.com/assets/9608795/9897433/97e5dbb6-5c48-11e5-9013-c65e92477898.png)

**Comment by RealRancor** [comment] 2015-09-16 06:04
Hi,

please disable the "Pictures" app. It could be also useful to fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating an issue).

**Comment by wikon** [comment] 2015-09-16 06:08
Hmm okay - this would also have been my first solution approach to disable the pictures app to make files working again ;-). But it works. Thanks.

**Comment by RealRancor** [comment] 2015-09-16 06:46
Hi,

feel free to close as this. The problem is caused if you have enabled the Pictures and Gallery+ apps together. A new release of the Gallery+ App should warn you if you have both enabled according to https://github.com/owncloud/apps/issues/2102#issuecomment-140049740

Nothing what can be fixed in core. :)

**Closed** 2015-09-16 06:52 UTC
