### ISSUE TITLE
Themes with Title "theme-" should be excluded from integritycheck

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#30290] opened 2018-01-26 18:26 UTC
Steps to Reproduce
1. copy theme-example in "theme-my-theme"
2. customize
3. go to web UI

what I expect - no integrity check errors

actual behaviour - integrity check errors

Why? Users, who are trying out to customize their ownCloud often get the integrity check errors, and are not sure what to do about it. They write in forum and we tell them to disable integrity check or exclude the custom theme folder from IC. Both are complicated solution.
A simple one would be - everything that is called "theme-*" is excluded from IC.

**Comment by PVince81** [comment] 2018-01-29 10:17
Duplicate of https://github.com/owncloud/core/issues/29094

**Closed by PVince81** 2018-01-29 10:17 UTC
Labels: bug, feature:theming
