### ISSUE TITLE
miss open bracket in html tag

### ISSUE THREAD

**Issue by MaximKulikov** [owncloud/core#38802] opened 2021-06-02 19:41 UTC
### Steps to reproduce
1. open /index.php/settings/admin?sectionid=general in russian locale with sqlite database
2. look red warning on top page
3. html tag printed as ussual text to user

### Expected behaviour
documentation link should be in correct <a> tag

### Actual behaviour
<a> tag not working, 

### Server configuration
**Operating system**:
docker container

**Web server:**

**Database:**
buildin sqlite

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.0.10.4

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
dockerhub

**Signing status (ownCloud 9.0 and above):**
no idea

There is useles boring form for such simple error
just replace current text block
"Для миграции на другую базу данных используйте команду: 'occ db:convert-type' или обратитесь к a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">документации ↗</a>."
to this one:
"Для миграции на другую базу данных используйте команду: 'occ db:convert-type' или обратитесь к <a target=\"_blank\" rel=\"noreferrer\" href=\"%s\">документации ↗</a>."
at core/settings/l10n/ru.json
line 285

![2021-06-02 223910](https://user-images.githubusercontent.com/2019153/120542131-6726d700-c3f3-11eb-8e5c-87fd3b060ff4.png)

**Comment by phil-davis** [comment] 2021-06-03 03:27
Note: the problem is where `a target=` starts. It should be `<a target=`

@MaximKulikov thanks for the report of the problem. This is also a problem in the current release in `ru.js` and `ru.json`. Those translation strings come from Transifex. Somebody who did the translation has accidentally deleted that opening `<`.

Please go to https://www.transifex.com/owncloud-org/owncloud/ and you (or anyone) can sign up and make the correction. Then it will automatically be transferred to the next ownCloud release.

**Comment by MaximKulikov** [comment] 2021-06-03 07:30
@phil-davis I seem to have fixed it in Transifex.
https://www.transifex.com/owncloud-org/owncloud/translate/#ru/settings-1/79989954

**Comment by phil-davis** [comment] 2021-06-03 07:48
Great. I don't have access to Russian translations. The change should come across in the nightly Transifex transfer commit.

**Closed** 2021-06-04 12:47 UTC
