### ISSUE TITLE
"Add trusted domains" button doesn't work

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14320] opened 2015-02-18 09:21 UTC
### Steps to reproduce

Having prepared an owncloud configuration:
1. Configure owncloud from localhost .
2. Try to access owncloud from another ip different to localhost.
### Expected behaviour

Owncloud shows a "add to trusted domains" suggestion with a button that adds that ip to trusted domains.
### Actual behaviour

Message and button are shown, but nothing happens after clicking the button.

![screen shot 2015-02-18 at 10 04 25](https://cloud.githubusercontent.com/assets/9048796/6244773/e9cd8abe-b757-11e4-8c33-4511db27db0d.png)
### Server configuration

**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
"version":"8.0.0.9,"versionstring":"8.0","edition":"Community"

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no
### Client configuration

Chrome, Firefox.

**Comment by karlitschek** [comment] 2015-02-18 09:26
@lukasreschke can you have a look?

**Comment by RealRancor** [comment] 2015-02-18 09:33
@SergioBertolinSG
Have a look at the JavaScript console of your browser and the data/owncloud.log when clicking on the button to see if you're getting any errors.

**Comment by SergioBertolinSG** [comment] 2015-02-18 09:39
There is an error while getting this file
GET http://10.40.40.130/owncloud_18-02-15/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)

**Comment by RealRancor** [comment] 2015-02-18 09:54
Hi,

this message itself is a duplicate of https://github.com/owncloud/core/issues/14057

Not quite sure if this is causing your problem.

**Comment by LukasReschke** [comment] 2015-02-18 10:21
Message is unrelated. That's just some browser debugging feature. Let me look at this.

**Comment by SergioBertolinSG** [comment] 2015-02-18 10:22
Ok, that javascript was unrelated. There weren't more javascript errors.

While clicking the button, an error message about web not available shows., showing this on networking.

 GET http://owncloud_18-02-15/index.php/settings/admin?trustDomain=10.40.40.130 net::ERR_NAME_NOT_RESOLVED
http://owncloud_18-02-15/index.php/settings/admin?trustDomain=10.40.40.130:1 GET http://owncloud_18-02-15/index.php/settings/admin?trustDomain=10.40.40.130 net::ERR_NAME_NOT_RESOLVED

**Comment by LukasReschke** [comment] 2015-02-18 10:23
Can you post your config?

**Comment by SergioBertolinSG** [comment] 2015-02-18 10:28
Well, it is a new installation, coming from #14321. But i saw this all the time before, this button has never worked. I always had to edit config.php to add the trusted domain manually.

**Comment by LukasReschke** [comment] 2015-02-18 10:32
It actually should work fine if the instance is configured properly and both addresses are accessible. 

The question here is more how we come into this incomsistent state:

1. How did you setup the ownCloud instance? Via Web or via CLI?
2. Was there any configured trusted domain in the config or was this an empty array or not existing key?

**Comment by SergioBertolinSG** [comment] 2015-02-18 11:22
I didn't setup owncloud yet this time.

Previous times I had a oc installed via web with only localhost in the array of trusted domains.

**Comment by LukasReschke** [comment] 2015-02-18 12:05
Got it… On it… Nice catch!!!

**Comment by LukasReschke** [comment] 2015-02-18 12:10
That was a nasty one caused by a security hardening for 8.1. - Patch is at https://github.com/owncloud/core/pull/14324

**Comment by SergioBertolinSG** [comment] 2015-02-18 13:39
Opened #14332. 
Clarified in #14324

**Comment by SamuAlfageme** [comment] 2018-02-01 09:23
Reopening as still relevant based in https://stackoverflow.com/questions/37974876 not sure, though, if it's a collateral of https://github.com/owncloud/core/issues/14332 (when the installation does not have access to said new trusted domain - like it happens when running ownCloud inside a container and trying to access via the host address)

**Comment by DeepDiver1975** [comment] 2018-02-01 10:16
that button was removed because of sec reasons some time back -> close and bye-bye

**Closed by DeepDiver1975** 2018-02-01 10:16 UTC
Labels: bug, junior job

**Comment by SamuAlfageme** [comment] 2018-02-01 10:21
@DeepDiver1975 you're right; didn't see https://github.com/owncloud/core/commit/a7b2d12d39876a56e7345f2905a781ca1f037685#diff-633cc665781c1b4e55d1a6d8679cc8a3 - 👌  then
