### ISSUE TITLE
OC 8.2 extremely slow

### ISSUE THREAD

**Issue by FrankMaute** [owncloud/core#20027] opened 2015-10-25 20:00 UTC
### Steps to reproduce
1. Updated from 8.1.3 to 8.2

### Expected behaviour
OC should be as fast as it was before

### Actual behaviour
Loading pages within OC is very slow, see screenshot

### Server configuration
**Operating system**: 
Debian 8

**Web server:** 
Apache/2.4.10 (Debian)

**Database:**

mysqlnd 5.0.11
**PHP version:**

5.6.13-0+deb8u1

**ownCloud version:** (see ownCloud admin page)

$OC_Version = array(8,2,0,12);
$OC_VersionString = '8.2.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,1);
$OC_Build = '2015-10-19T13:24:39+00:00 8ee2009de36e01a9866404f07722892f84c16e3e';

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - direct_menu: 0.4
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - imprint: 0.2.5
  - notifications: 0.1.0
  - ownnote: 0.0.8
  - tasks: 0.8
  - templateeditor: 0.1
  - updater: 0.6
  - user_external: 0.4
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

  1 <?php
  2 $CONFIG = array (
  3   'instanceid' => 'occ6s',
  4   'passwordsalt' => 'b,
  5   'secret' => '
  6   'trusted_domains' =>
  7   array (
  8     0 => '144.',
  9     1 => 'p',
 10   ),
 11   'datadirectory' => '/var/opt/ocdata/data',
 12   'overwrite.cli.url' => 'https://owncloud',
 13   'dbtype' => 'mysql',
 14   'version' => '8.2.0.12',
 15   'dbname' => 'owncloud',
 16   'dbhost' => 'localhost',
 17   'dbtableprefix' => 'oc_',
 18   'dbuser' => 'oc_',
 19   'dbpassword' => 'x',
 20   'installed' => true,
 21   'mail_smtpmode' => 'smtp',
 22   'mail_smtpsecure' => 'ssl',
 23   'mail_from_address' => 'owncloud',
 24   'mail_domain' => 'p',
 25   'mail_smtpauth' => 1,
 26   'mail_smtpauthtype' => 'PLAIN',
 27   'mail_smtphost' => 'mail.',
 28   'mail_smtpport' => '465',
 29   'mail_smtpname' => 'ownc',
 30   'mail_smtppassword' => '',
 31   'forcessl' => true,
 32   'app.mail.imaplog.enabled' => true,
 33   'theme' => '',
 34   'maintenance' => false,
 35   'loglevel' => 0,
 36   'log_rotate_size' => 104857600,
 37   'appstore.experimental.enabled' => true,
 38   'trashbin_retention_obligation' => 'auto',
 39 'memcache.local' => '\OC\Memcache\Redis',
 40 'redis' => array(
 41      'host' => 'localhost',
 42           'port' => 6379,
 43                'timeout' => 0.0,
 44                      ),
 45 );
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

Chrome

**Operating system:**

OSX 10.11

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
<img width="1434" alt="nettraceowncloud" src="https://cloud.githubusercontent.com/assets/8351663/10717522/3f7a5330-7b5b-11e5-99c7-57633f612e5a.png">

**Comment by LukasReschke** [comment] 2015-10-25 20:03
According to the screenshot this looks very likely like a duplicate of https://github.com/owncloud/core/issues/19888.

@FrankMaute You could help us to verify this by installing https://blackfire.io/ on the server, then copy one of those slow requests as cURL and measure them using `blackfire curl` and share the result with us.

**Comment by FrankMaute** [comment] 2015-10-25 20:34
@LukasReschke Well, I tried to make it work, but for some reason no results come up on blackfire. I guess I missed some configuration. Agents are installed and detected. Do I need to update code somewhere?

**Comment by LukasReschke** [comment] 2015-10-25 20:36
> @LukasReschke Well, I tried to make it work, but for some reason no results come up on blackfire. I guess I missed some configuration. Agents are installed and detected. Do I need to update code somewhere?

No code changes are required on your end. So what do you mean with "no results come up on blackfire"?

Btw. if you have IRC just ping me in Freenode on #owncloud-dev or query. Username is the same :smile:

**Comment by LukasReschke** [comment] 2015-10-25 21:44
Duplicate of https://github.com/owncloud/core/issues/19888. Referenced at https://github.com/owncloud/core/issues/19888#issuecomment-150977039.

If you want to increase performance right now without waiting for us to address this you might try to install Redis and configure it: https://github.com/owncloud/core/blob/172bcf2d51d9a10520129a7a794d397457d91d96/config/config.sample.php#L1139-L1145

**Closed by LukasReschke** 2015-10-25 21:44 UTC
Labels: needs info, performance

**Comment by dikodhiko** [comment] 2015-10-29 03:04
@FrankMaute 
helow, [OOT]

can u tell me what kind of application you use to speed test ur owncloud?
(apps on ur screenshot)

thanks.

**Comment by FrankMaute** [comment] 2015-10-29 05:54
@dikodhiko: Well, you meant were the screenshot came from? This is Developer tools in Firefox (CTRL-Shift-C) and the Network pane. 
Hope this helped. 
Frank.

**Comment by FrankMaute** [comment] 2015-10-29 05:56
@dikodhiko: Ah, I added a short how-to on my website to get 8.2 running nice and fast. At least it solved my issue: http://maute.eu/enhance-speed-of-owncloud-8-x/

**Comment by dikodhiko** [comment] 2015-10-29 08:15
@FrankMaute 

thanks for information.
thats so helpfully for me :)

cheers

**Comment by barrydegraaff** [comment] 2015-12-03 16:44
I have seen this issue also, when on CentOS7 and went from suse repo to owncloud 8.1.3 to 8.2

**Comment by barrydegraaff** [comment] 2015-12-03 17:15
I solved this issue by Adding:
 'memcache.locking' => '\\OC\\Memcache\\APCu',

Before I only had:
 'memcache.local' […]
