### ISSUE TITLE
[6.0.4] Debug message still appears but should be fixed in 6.0.3

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#9443] opened 2014-07-04 11:41 UTC
### Steps to reproduce
Mostly when you take pictures with the android app.

### Expected behaviour
No error, and should be fixed through discussion here #7541 and merged here: #8488

### Actual behaviour
```
Fatal webdav Sabre_DAV_Exception_NotFound: File with name InstantUpload/20140628_063548.jpg could not be located 2014-06-28T04:35:49+00:00 Shows up in log.
```

### Server configuration
Ubuntu Server 12.04

**Database:**
MySQL latest
**PHP version:**
PHP 5.3.10-1ubuntu3.12 with Suhosin-Patch (cli) (built: Jun 20 2014 00:38:55)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
**ownCloud version:** (see ownCloud admin page)
6.0.4
**Updated from an older ownCloud or fresh install:**
Updated from 6.0.3, 6.0.2 and 6.0.1
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc106ccbdf7c',
  'passwordsalt' => '2861cbdae28a053401111bca8dde0e',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.4.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost.localdomain',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_enoch',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'check_for_working_webdav' => false,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '3',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'enochowncloud.no-ip.org',
  ),
);

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Chrome Version 34.0.1847.131 m
**Operating system:**
Windows 7 Ultimate
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
Just a bunch of these:
{"app":"PHP","message":"Undefined index: all at \/var\/www\/owncloud\/apps\/files_versions\/lib\/versions.php#485","level":3,"time":"2014-07-03T14:55:48+00:00"}
Fatal webdav Sabre_DAV_Exception_NotFound: File with name InstantUpload/20140628_063548.jpg could not be located 2014-06-28T04:35:49+00:00
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by MorrisJobke** [comment] 2015-02-04 15:45
I still get this in stable6, stable7 and master. Just upload a picture via Android app into a subfolder:

stable6:
```
{"reqId":"54d23afd2fc72","app":"webdav","message":"Sabre_DAV_Exception_NotFound: File with name jsns\/IMG_20141024_204819.jpg could not be located","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #1 [internal function]: Sabre_DAV_Server->httpHead('jsns\/IMG_201410...')","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/Sabre\/DAV\/Server.php(473): call_user_func(Array, 'jsns\/IMG_201410...')","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/Sabre\/DAV\/Server.php(213): Sabre_DAV_Server->invokeMethod('HEAD', 'jsns\/IMG_201410...')","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #4 \/home\/mjob\/Projekte\/owncloud\/master\/apps\/files\/appinfo\/remote.php(57): Sabre_DAV_Server->exec()","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/master\/remote.php(43): require_once('\/home\/mjob\/Proj...')","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
{"reqId":"54d23afd2fc72","app":"webdav","message":"Exception: #6 {main}","level":4,"time":"2015-02-04T15:30:05+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/jsns\/IMG_20141024_204819.jpg"}
```

stable7:

```
{"reqId":"54d23c7580dfa","app":"webdav","message":"Sabre\\DAV\\Exception\\NotFound: File with name hd\/IMG_20141024_204828.jpg could not be located","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #1 [internal function]: Sabre\\DAV\\Server->httpHead('hd\/IMG_20141024...')","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #2 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'hd\/IMG_20141024...')","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #3 \/home\/mjob\/Projekte\/owncloud\/master\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('HEAD', 'hd\/IMG_20141024...')","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #4 \/home\/mjob\/Projekte\/owncloud\/master\/apps\/files\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #5 \/home\/mjob\/Projekte\/owncloud\/master\/remote.php(52): require_once('\/home\/mjob\/Proj...')","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
{"reqId":"54d23c7580dfa","app":"webdav","message":"Exception: #6 {main}","level":0,"time":"2015-02-04T15:36:21+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hd\/IMG_20141024_204828.jpg"}
```

master:
```
{"reqId":"74764de3d61d3230e20d18860281f7a9","remoteAddr":"192.168.0.11","app":"webdav","message":"Exception: {\"Message\":\"File with name hs\\\/IMG_20141024_204819.jpg could not be located\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(661): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('hs\\\/IMG_20141024...')\\n#1 [internal function]: Sabre\\\\DAV\\\\Server->httpHead('hs\\\/IMG_20141024...')\\n#2 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'hs\\\/IMG_20141024...')\\n#3 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('HEAD', 'hs\\\/IMG_20141024...')\\n#4 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/remote.php(54): require_once('\\\/home\\\/mjob\\\/Proj...')\\n#6 {main}\",\"File\":\"\\\/home\\\/mjob\\\/Projekte\\\/owncloud\\\/master\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":100}","level":0,"time":"2015-02-04T15:38:15+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/hs\/IMG_20141024_204819.jpg"}
```


It seems to be related to the HEAD request.

**Comment by cdamken** [comment] 2015-03-04 14:33
@MorrisJobke 

00002218

**Comment by MorrisJobke** [comment] 2015-03-04 19:36
@DeepDiver1975 @PVince81 Dav magic ;)

**Comment by PVince81** [comment] 2015-03-05 08:31
Yes, this is not an error. The mobile client does a PROPFIND on a non-existing file to check for existence, and expects a 404. That "error" was logged up to OC 6, then its log level was changed to DEBUG since OC 7.

**Comment by MorrisJobke** [comment] 2015-03-05 19:24
@PVince81 So we can close this?

**Comment by enoch85** [comment] 2015-03-05 19:35
@MorrisJobke @PVince81 I was the one that reported the original issue, and I opened this because it still appeared.

**Comment by MorrisJobke** [comment] 2015-03-06 09:42
@enoch85 you wrote:
> This is gone in 7.0 stable btw.

And @PVince81 said, that this is the intended behaviour for stable6.

**Comment by enoch85** [comment] 2015-03-06 13:28
@MorrisJobke Yes, I haven't seen it now for a while. Close then?

**Closed** 2015-03-06 13:38 UTC
Labels: blue-ticket, bug
