### ISSUE TITLE
REHL Repo issue

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#16343] opened 2015-05-13 19:10 UTC
[3119]

#### Summary of issue:
customer that use our repo via RHEL they are using the“collections” repo from Red Hat to address the need for PHP 5.4 however, when they go to do the upgrade/install it is not finding the needed PHP
(as when it is installed in collections it seems to to using some non-standard conventions to puts the code some place other than where our scripts are looking for it so the install fails for missing PHP).

#### Server configuration
Red Hat Enterprise Linux Server release 6.6 (Santiago)
httpd-2.2.15-39.el6.x86_64
php-common-5.3.3-40.el6_6.x86_64
owncloud-enterprise-7.0.5-3.1.noarch
storage is a cifs mount from a Windows 2012R2

#### Problem description:
owncloud-enterprise-6.0.7-2.1.noarch to 
owncloud-enterprise-7.0.5-3.1.noarch failed 
When I remove owncloud 6 and php 5.3 and install php54, installing 
owncloud from 
http://XXXXXs@download.ownCLOUD.com/download/repositories/7.0/RHEL_6_PHP54/
installs php 5.3 

You need to be aware that on Redhat enterprise 6 to enable systems to 
install different versions of software like php, they are using Software 
Collections. 
https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/1/html/Software_Collections_Guide/sect-What_Are_Software_Collections.html 

For me to install php5.4 I have to use these packages. 

The dependencies on your owncloud-enterprise-7.0.5-3.1.noarch.rpm 
rpm -qpR 
/var/cache/yum/x86_64/6Server/ee_7.0/packages/owncloud-enterprise-7.0.5-3.1.noarch.rpm 
config(owncloud-enterprise) = 7.0.5-3.1 
curl 
httpd 
mysql 
php >= 5.3.3 
php-ftp 
php-gd 
php-gmp 
php-json 
php-ldap 
php-mbstring 
php-pdo 
php-pecl(APC) 
php-process 
php-soap 
php-xml 
php-zip 
php5-libsmbclient >= 0.5.0 
rpmlib(CompressedFileNames) <= 3.0.4-1 
rpmlib(FileDigests) <= 4.6.0-1 
rpmlib(PayloadFilesHavePrefix) <= 4.0-1 
https://c.na15.content.force.com/servlet/servlet.FileDownload?file=00Pi000000MMDP9
rpmlib(VersionedDependencies) <= 3.0.3-1 
samba-client 
sqlite 
rpmlib(PayloadIsXz) <= 5.2-1 

The default php available to RHEL 6 is 5.3.3-40.el6_6 which satisfies 
the dependancy php >= 5.3.3 

To ensure that php 5.4 is being used, these dependencies need to be 
specified as php54-php, or php55-php for php 5.5 

If I try to upgrade using php53 and the 
http://oC
CRepo7:XXXXX@download.ownCLOUD.com/download/repositories/7.0/RHEL_6_PHP53 
repo I get the attached error. 
![image](https://cloud.githubusercontent.com/assets/10195796/7618665/a67c7268-f981-11e4-8fc1-48326625f595.png)

**Comment by LukasReschke** [comment] 2015-05-13 19:13
So how is this related to https://github.com/owncloud/core/issues/16204? – Is this about the SQL error in the update screen? 

For that you need to get in touch with some of our GCX folks as suggested by @DeepDiver1975 in https://github.com/owncloud/core/issues/16204#issuecomment-100363570

**Comment by iliyasbasir** [comment] 2015-05-14 12:48
@LukasReschke  https://github.com/owncloud/core/issues/16204? Juergen help me so he'll look this issue we already discusses.

**Comment by jnweiger** [comment] 2015-05-15 10:52
@iliyasbasir this report looks mostly identical to core#16204 -- we are mixing two issues:
* 1st issue: Seen in the screenshot. Database error during update. This should be handled in core#16204

* 2nd issue: How to make 7.0.5 run with php-5.4 - this we can discuss here.

I don't see an issue with using php-5.3.3 and 7.0.5 -- I believe that is a supported configuration. We require php-5.4 since 8.0.x, not before.

**Comment by jnweiger** [comment] 2015-05-15 10:57
For reference, here is a working Dockerfile that demonstrates how to install 7.0.5 with CentOS_6 and php-5.4
The same commands should work with RHEL_6

# autogenerated by:  /usr/bin/obs-docker-install ee:7.0 owncloud-enterprise CentOS_6_PHP54 -D
FROM centos:centos6
RUN wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN wget -nv http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
RUN rpm -ivh remi-release-6*.rpm epel-release-6*.rpm
RUN yum-config-manager --enable remi
RUN yum install -y --nogpgcheck php
RUN yum install -y wget samba-client
RUN rpm --import https://UUUUUUU:PPPPPPPPPPPP@download.owncloud.com/download/repositories/7.0//CentOS_6_PHP54/repodata/repomd.xml.key
RUN wget -nv --user 'UUUUUUUU' --password 'PPPPPPPPPPPP' https://download.owncloud.com/download/repositories/7.0/CentOS_6_PHP54/ee:7.0.repo -O /etc/yum.repos.d/ee:7.0.repo
RUN yum install -y owncloud-enterprise

Maybe these instructions are helpful?

**Comment by iliyasbasir** [comment] 2015-05-19 16:22
Here is note from customer 
````
But I would like you to submit a feature request that the rpms are updated to use RHEL provided packages when ever possible and baring that EPEL. Our best practices (and a lot of other enterprise customers) state that we will not use untrusted package providers. The Remi repository does not fit into that category. I understand RedHat is making things awkward with renaming the php 5.4 rpm, but, this should be a fairly easy request to fulfill. If you can't making the source rpm and/or spec file available will allow me to rewrite it to meet our requirements.
````

**Comment by DeepDiver1975** [comment] 2015-05-21 08:44
> But I would like you to submit a feature request

@MTRichards for roadmap planning - to be honest we decided to walk the remi path for a reason from my understanding. As long as this works I see no reason to AGAIN change the packages which are now finally working.

**Comment by MTRichards** [comment] 2015-05-21 09:38
@DeepDiver1975 
Sorry to disagree on the RHEL Remi conversation but here I go anyway.

RHEL remi is the _unsupported_ approach for users. If an enterprise customer wants to update and remain in compliance with their RHEL support contract, they must use the RHEL Collections repository. 
Sadly, this is not optional, as RHEL collections is the enterprise requirement. Remi is for anyone else.

I don't mind remi, but can't we add an "or" here and make it also support collections as an understood repository?

**Comment by jnweiger** [comment] 2015-05-22 16:11
We already support both. Users can choose Remi "or" SCL.

This is an example Dockerfile using Software Collections:
<pre>
# autogenerated by:  /usr/bin/obs-docker-install ee:7.0 owncloud-enterprise CentOS_6@SCL-PHP54 -D
FROM centos:centos6
RUN yum install -y --nogpgcheck php
RUN mv /etc/httpd/conf.d/php.conf /tmp/etc.httpd.conf.d.php-5.3.conf || true
RUN yum install -y --nogpgcheck centos-release-SCL
RUN yum install -y --nogpgcheck php54
RUN yum install -y --nogpgcheck php54-php

RUN yum install -y wget samba-client
RUN rpm --import https://UUUUUUUU:PPPPPPPP@download.owncloud.com/download/repositories/7.0//CentOS_6/repodata/repomd.xml.key
RUN wget -nv --user 'UUUUUUUU' --password 'PPPPPPPP' https://download.owncloud.com/download/repositories/7.0/CentOS_6/ee:7.0.repo -O /etc/yum.repos.d/ee:7.0.repo
RUN yum install -y owncloud-enterprise
</pre>

@iliyasbasir 
Full sources including spec files and all, for the next release are available at https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud 
The specfile there features an owncloud-server-scl-php54 packages, that is identical to the normal server, but requires php54 and friends instead of php.

Please note, that RPM does not allow the notation "Requires: php54 | php" -- compared to the DEB "Depends: php54 | php" which works fine to implement the "or" logig.
For RPM, we can only ressort to offering two different packages.

**Comment by sbelov1** [comment] 2015-05-28 15:15
Guys, this is an ongoing issue with multiple prospects we're working with. Whether RPM packages use different naming conventions or whatever the issue is, we're forced to load all the php modules manually - which defeats the whole purpose having rpms. I ran into those issues with RHEL and CentOS 7 so far. Can we please look into this issue?
@bboule @jnweiger

**Comment by jnweiger** [comment] 2015-05-29 08:37
@sbelov1 My second example script shows the procedure using redhat software collections. As you can see it involves no manual installation of all php modules. They are pulled in by rpm dependencies. 

I don't see why that should not work the same at a customers site.

**Comment by MorrisJobke** [comment] 2015-06-05 08:43
@carlaschroder Can you document these two ways of installing different versions of dependencies on Red Hat: https://github.com/owncloud/core/issues/16343#issuecomment-104700724

There is the Remi way and the Red Hat Collections way. Remi seems to work with the default packages and the Red Hat Collections need the steps in https://github.com/owncloud/core/issues/16343#issuecomment-104700724

**Comment by MorrisJobke** [comment] 2015-06-05 08:44
@carlaschroder Feel free to ask @jnweiger if there are still problems in understanding what is going on here ;)

**Comment by carlaschroder** [comment] 2015-06-05 15:07
I'm not a guy, but maybe I can help anyway.

**Comment by MorrisJobke** [comment] 2015-06-05 15:36
This is now tracked in the docu repo: close this one

**Closed by MorrisJobke** 2015-06-05 15:36 UTC
Labels: blue-ticket, documentation, packaging
