### ISSUE TITLE
suggestion for Changeable Iconthemes

### ISSUE THREAD

**Issue by blackcrack** [owncloud/core#21372] opened 2015-12-25 13:42 UTC
suggestion for Changeable Iconthemes

Postby Blackcrack » Fri Dec 25, 2015 2:30 pm
Hi peoples,

Why it is the iconstheme hard programmed in ?
Why can you not add an bit code for
check out an "$iconthemefolder = /owncloud/iconthemefolder
let check this out witch folder on it
and use the folders .. where can be the iconthemes on it..

and by this can you check out the KDE-Look kde4 and up iconthemes..
i use it as my own iconrepository for mimetypes and folders .

take a look and download an couple of themes and take a look how it is building up.
http://kde-look.org/index.php?xcontentmode=27

i have take my icontheme from my kde-theme for my own deco in PHP-FileMirror
there on my de domain http://blackysgate.de/files/ used.

well, so why make someone not possible for use easy kde-icon-themes with png or svg and svgz
pictures as owncloud-iconthemes , easy extracting in a subfolder like owncloud/iconthemes/default/
let check the folder of the icontheme and set this as icontheme .
therewith it is able for use easy kde-icon-themes for owncloud.

then maybe a icontheme.owncloud.org building up with verified kde-iconthemes for owncloud
for working well and upload there the icont hemes where works 100% in owncloud.

with it, can it be possible for have many different iconthemes for owncloud !

best regards
Blacky

there the originaltread ..

https://forum.owncloud.org/viewtopic.php?f=34&t=32231&p=104060#p104060

**Comment by MorrisJobke** [comment] 2015-12-29 15:56
Duplicate of https://github.com/owncloud/core/issues/6773

**Closed by MorrisJobke** 2015-12-29 15:56 UTC
