### ISSUE TITLE
Impossible to revert unsharing (opt-out of a shared folder) via GUI

### ISSUE THREAD

**Issue by brozkeff** [owncloud/core#29390] opened 2017-10-30 10:38 UTC
Owncloud 10/Ubuntu server, indifferent on desktop client version

At least for a year an issue exists with user unsharing a shared folder. User has no way reverting such action, even admin does not see list of unshared folders in GUI. Only database hack is available to list such unshared folders and optionally delete these database rows: `select * from oc_share where permissions=0 and share_type=2` (if you delete the undesired entry, the share will be visible again for the user from the „share_with“ column)

Detailed description with this workaround is on my blog https://www.brozkeff.net/2016/08/29/owncloud-database-hacking-how-to-revert-unsharing-of-folder-shared-to-a-group/

Please consider adding some GUI either to the user and/or to the admin or owner of the shared folder, to see these unshares with a possibility to delete it.

**Comment by PVince81** [comment] 2017-10-30 10:42
@brozkeff duplicate of https://github.com/owncloud/core/issues/13495.

**Closed by PVince81** 2017-10-30 10:42 UTC
