### ISSUE TITLE
Sharing a folder by link it is not said it is a folder anywhere in the screen shown by the URL

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16491] opened 2015-05-21 08:45 UTC
### Steps to reproduce
1. Enable option Allow users on this server to send shares to other servers
2. Share a folder by link (in this case it is empty)

### Expected behaviour
The screen shown by the URL should show the name of the folder and the files.

### Actual behaviour
The screen shown by the URL, does not say nothing about the folder, only shows the files if they would have existed,

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Mozilla Firefox 38

![captura de pantalla 2015-05-21 a las 10 36 36](https://cloud.githubusercontent.com/assets/10596560/7744774/533b3afa-ffa6-11e4-938a-f5ddd7faf8a5.png)

**Comment by PVince81** [comment] 2015-05-21 10:30
It actually shows the message "No files in here", which is expected.

The bug is that the container height is wrong, this was fixed yesterday.

Closing as duplicate of https://github.com/owncloud/core/issues/16335

**Closed by PVince81** 2015-05-21 10:30 UTC
Labels: enhancement, feature:federated-cloud-sharing, sev4-low
