### ISSUE TITLE
Users cannot delete folders or files they create 

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#12145] opened 2014-11-12 19:59 UTC
A org I'm associated with we have an OwnCloud instance currently running 7.0.3 on Linux and users have been reporting they cannot delete files or folders they create. The files and folders they are creating are under a shared folder that they are in a group that has access to edit and delete. How can I fix this? The admin logs are not providing any apparent cause.

**Comment by Artyum** [comment] 2015-01-26 22:06
I have similar problem. I cant delete files uploaded by users to shared folders with disabled "delete" permission:

Steps to reproduce
1. Create folder F by user A (Admin) through browser (Firefox 35). F is owned by A
2. Share F to user U with permissions: share no, create yes, update yes, delete no
3. on android login to U and upload a file to folder F
4. synchronize everytning on PC by A admin

Results:
A and U can see a file - OK
U can't delete file - OK
A can delete file on PC - ERROR no permission to delete, restoring

Nobody can't delete the file! After deleting file through ssh:
(translation from polish - original english version can be little different)
No permission to delete, restoring; Restoring failed: Error downloading https://domain/remote.php/webdav/Folder/F/DSC_0001.JPG - server replied: Not Found          

Operating system:
Ubuntu 14.04

Web server: Apache
Database: Mariadb
PHP version: 5.5.9
ownCloud version: 7.0.4 (stable)

**Comment by netopier** [comment] 2015-01-27 01:56
Hello.
I have same problem. But maybe this will help you locate the bug:
https://drive.google.com/folderview?id=0B_5EtPLrCtQiOFpJaTBmdEtETjg

RFP pub.. is folder shared by owner to group.
When I try delete some folders from this shared folder, I cant. Client just resync it with error "Not allowed to remove, restoring". But some others, I can delete with no problem.

Now when I log in to web gui, I see strange thing. When you mouseover trought folder "001 SCH...." you can see the trash icon on right (screen00). But when you go with mouse cursor on folder "Morav..." that delete icon is not there (screen 01). And when I use the check box on folder icon, now there appear banner with option to delete this folder (screen02).

And now, folders which are unable to delete from standard client, are exact same folders, which dont have  the "delete" icon when I use mouseover them in web gui.

I hope it will helps...

Owncloud server is 7.0.4 linux, client is last windows or MacOS.

Neto

**Comment by PVince81** [comment] 2015-01-27 09:05
Not sure if related, but there was a similar permissions issue with the share permission.
Could you guys try applying the following patch: https://github.com/owncloud/core/commit/d534f262aaa21773df5a55099e0d95d2d96434e2 (https://github.com/owncloud/core/commit/d534f262aaa21773df5a55099e0d95d2d96434e2.patch)

**Comment by Artyum** [comment] 2015-01-27 11:40
@PVince81
Your patch fixed my problem.
Now, the owner of shared folder can delete files uploaded by others users.

Thank you.

**Comment by PVince81** [comment] 2015-01-27 12:05
That's good news! That fix will be in 7.0.5.

@bkerensa and @netopier let us know if you have the possibility to test the patch too.

**Comment by hugoboss2014b** [comment] 2015-02-04 17:10
My last backup of my owncloud installation is a month old, and the backup lasted 4 days.
I tried to install the patch from my installation directory of owncloud, but it asked me where 2 of the files is that shall be patched. I installed and deinstalled the patch several times and overwrote "/apps/files_sharing/" with the original installation files at the end. All Owncloud Clients now download everything from the beginning from my owncloud server. But I could live with that, but: When everything is downloaded, it doesnt show that it is finished. I shows 100% and 0 seconds left. So on the one hand my data isnt lost, but on the other hand my owncloud installation is damaged and I don't know what to do. I can not install the patch.

**Comment by PVince81** [comment] 2015-02-04 17:14
@hugoboss2014b you could download the tarball your OC version (7.0.4?) and then copy the folder "file_sharing" back into your install.

How did you apply ? It should be `patch -p1 < patchfile.patch` inside the owncloud directory. If the patch doesn't apply it means you don't have the right OC version. That patch should apply on 7.0.4.

**Comment by PVince81** [comment] 2015-02-04 17:15
@bkerensa any news from you ? :smile:

**Comment by hugoboss2014b** [comment] 2015-02-04 18:08
I googled how to patch and did it this way:
patch < patchfile.patch

**Comment by hugoboss2014b** [comment] 2015-02-04 18:19
The Error is still the same: It want's to download everything again from the server, but not if it has done this already yesterday. And then in different folders it stay at the point 100% or short before 100% with different errors, that are acceptable for me, but not that it doesnt finish really. I could to the following: I could delete the .blabla hidden files from ownloud in the directory and reinstall every sync folder in the client. Would that help?

**Comment by PVince81** [comment] 2015-02-04 18:36
@hugoboss2014b the question was mostly whether the original issue "Users cannoot delete folders or files they create" was solved. If yes, then this ticket can be closed.

If you say that you are having additional issues or issues not related to the patch, then it would be better if you could raise a separate ticket and provide more information about your setup, so we can find out why this is happening.

Thanks.

**Comment by hugoboss2014b** [comment] 2015-02-04 19:28
Ahm well ok fine. I will need to create a new topic. But what I described happend together with the problem of this topic, or by trying to fix the problem of this topic.

**Comment by PVince81** [comment] 2015-02-04 19:30
So you mean that if you do not apply the patch, everything works fine ?

**Comment by PVince81** [comment] 2015-02-04 19:30
(apart from the original issue)

**Comment by hugoboss2014b** [comment] 2015-02-04 19:35
I guess that error occures, because I applied the patch wrong. I will create another topic if deleting these hidden files does not work.

**Comment by hugoboss2014b** [comment] 2015-02-05 15:57
I could create a new topic, because my problem is maybe only 90% the same problem of the creator of this topic.

**Comment by hugoboss2014b** [comment] 2015-02-06 00:17
I did what I describted. Didnt helped. But I found out, that the filesystem permissions were set to user and group root in the data directory. So now I change them to the user and group of nginx.

**Comment by hugoboss2014b** [comment] 2015-02-06 09:21
https://github.com/owncloud/core/issues/13176

This is my problem! So I don't need to create a new topic, because there is already another one.

**Comment by PVince81** [comment] 2015-02-06 10:06
@hugoboss2014b if the permissions were wrong on disk it's maybe because at some point you ran `./occ files:scan --all` as root. That command should always be run as the web server user, for example `sudo -uwww ./occ files:scan --all` (in OC 8 there will be a check to enforce this).

I'll close this ticket now. If any one is still having this issue "Users cannot delete folders or files they create" after running `sudo -uwww ./occ files:scan --all` and applying the patch https://github.com/owncloud/core/commit/d534f262aaa21773df5a55099e0d95d2d96434e2.patch (which will be in 7.0.5), feel free to reopen.

Thanks

**Closed by PVince81** 2015-02-06 10:06 UTC
Labels: bug, Sharing

**Comment by PVince81** [comment] 2015-02-06 10:59
For reference, this would be a duplicate of https://github.com/owncloud/core/issues/10299
