### ISSUE TITLE
Shared label in shared subfolder doesn't appear until opening sidebar.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25302] opened 2016-06-29 16:25 UTC
### Steps to reproduce:

Having three users, user1, user2 and user3 do:
1. As user1 create a folder called "test".
2. As user1 create a folder called "FOLDER" inside "test"
3. As user1 upload a file called "textfile.txt" to "/test/FOLDER"
4. As user1 share "/test/FOLDER" with user2.
5. As user2 share "/FOLDER/textfile.txt" with user3.
6. As user1, go to files view, enter "/test/FOLDER" open sidebar and go to sharing tab. 
### Expected behaviour:

Shared label appears on every file which has shares.
### Actual behaviour

Shared label appears only after opening sidebar and going to sharing tab.

<img width="136" alt="screen shot 2016-06-29 at 18 22 42" src="https://cloud.githubusercontent.com/assets/9048796/16460190/8ca24f9e-3e26-11e6-8694-c4259a0a4abd.png">
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master on serverA and serverB
{"installed":true,"maintenance":false,"version":"9.1.0.9","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

Addressbooks were exchanged correctly before the tests.
### Client configuration

Chrome, Firefox.

**Comment by SergioBertolinSG** [comment] 2016-06-29 16:35
cc @rullzer

**Comment by PVince81** [comment] 2016-06-30 09:23
Hmm, I see even another problem: at step 4 the share indicator also doesn't appear for user1 until I reload the page.

**Comment by PVince81** [comment] 2016-06-30 09:27
@SergioBertolinSG ok, I managed to reproduce your issue.

It looks like `<oc:share-types />` is empty, so it means the Share API call we're doing to compute it doesn't properly take flat reshares into account. Or the call needs to be adjusted/extended if it was by design.

**Comment by PVince81** [comment] 2016-06-30 09:28
Setting to medium. It's not too bad but still an annoyance.

**Comment by SergioBertolinSG** [comment] 2016-06-30 10:54
Please have in mind that mobile clients (perhaps desktop too) cannot detect that those files are shared also.

**Comment by PVince81** [comment] 2016-06-30 10:57
Yes, this is the same issue that the Webdav attribute doesn't have the correct value.
Unless the mobile client uses the OCS Share API instead of that, in which case something else might be wrong.

**Comment by SergioBertolinSG** [comment] 2016-06-30 10:59
Yes AFAIK they are using the share api. cc @nasli

**Comment by nasli** [comment] 2016-07-01 10:44
We use ocs/v1.php/apps/files_sharing/api/v1/shares

**Comment by SergioBertolinSG** [comment] 2016-08-17 11:16
I see this with current master (9.2.0.1) just sharing a folder. Shared label doesn't appear.

**Comment by PVince81** [comment] 2016-08-17 12:04
@SergioBertolinSG the issue you are seeing is https://github.com/owncloud/core/issues/25311

**Comment by SergioBertolinSG** [comment] 2016-08-17 12:11
Yes, it is that one.

**Comment by PVince81** [comment] 2016-08-17 12:20
That linked one is a Javascript issue, not related at all to the APIs

**Comment by PVince81** [comment] 2017-05-17 08:58
closing as duplicate, https://github.com/owncloud/core/issues/25311 is fixed in 10.0.0

**Closed by PVince81** 2017-05-17 08:58 UTC
Labels: bug, feature:sharing, sev3-medium
