### ISSUE TITLE
Filename is not updated in 'activities tab' when it is renamed

### ISSUE THREAD

**Issue by davitol** [owncloud/core#19222] opened 2015-09-21 11:25 UTC
### Steps to reproduce

1. Create a file, edit and save it
2. Close the file.
3. Rename the file
3. Go to the activities tab

### Expected behaviour
In the activities tab, the files hould be renamed, or it should be a line about renaming

### Actual behaviour
The activies show the old name

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-21T03:08:19+00:00 bbd1e996050fee80795d0e656da98b6451232c6c

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox

![renaming](https://cloud.githubusercontent.com/assets/10596560/9990772/2c311636-6064-11e5-8860-10919bd30924.png)

**Comment by davitol** [comment] 2015-09-21 12:28
Note: If the file is renamed, deleted, and restored from the trasjbin, the new activities appear new named

**Comment by karlitschek** [comment] 2015-09-21 12:32
@nickvergessen what is the intended behavior here?

**Comment by nickvergessen** [comment] 2015-09-21 13:23
Well activities always use the name they had when the activity was created. We need to add the rename activity though, then it would make a bit more sense: https://github.com/owncloud/activity/issues/375

But there is also the plan to remove file names from that panel completly as they are redundant there:
https://github.com/owncloud/activity/issues/395

So "will fix at some point" until then "intended behaviour"

**Comment by nickvergessen** [comment] 2015-09-22 10:14
Closing this in favor of the two activity issues.

**Closed by nickvergessen** 2015-09-22 10:15 UTC
Labels: bug, feature:sidebar, sev4-low
