### ISSUE TITLE
Syncing account files after app password is deleted from server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/core#40755] opened 2023-04-24 11:56 UTC
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Adding an account using the app-password. After deleting the app-password from the server, the client still syncs down the files from the server - how connection to server is being authorized even after the app-password has been deleted?

And after logout, when trying to login again with the deleted app-password, login fails (which is OK).

### Expected behavior

?

### Steps to reproduce the issue

1. Create and copy an app password from the oC10 server
2. Open desktop client
3. Add the account with username and app-password
4. Let the files sync
5. Delete the app-password from the server
6. Upload something in the server (client syncs down the uploaded files) :question: 
7. Logout and try to log in with deleted app-password (doesn't logs in :heavy_check_mark: )

### Logs
[ownCloud-client.log](https://github.com/owncloud/client/files/11310125/ownCloud.log)

### Client version number

ownCloud 4.0.0.10732-rc1 [93ec98](https://github.com/owncloud/client/commit/93ec98d7cb9e947d752ad8878e5bf823adb5956a)
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
ubuntu-5.19.0-40-generic

### Desktop environment (Linux only)

Ubuntu22.04

### Server information

ownCloud 10.12.1 (stable)

**Comment by iasdeoupxe** [comment] 2024-05-05 14:38
Duplicate of #30873?

**Comment by saw-jan** [comment] 2024-05-06 03:42
Probably yes!

**Closed** 2024-05-06 03:43 UTC
Labels: discussion
