### ISSUE TITLE
logtimezone setting does not work -> UTC only (owncloud 9.0)

### ISSUE THREAD

**Issue by masupilamie** [owncloud/core#23276] opened 2016-03-15 18:21 UTC
### Steps to reproduce
1. Install Ubuntu 14.04
2. Install owncloud 9.0 through repository (used stable repo)
3. Change 'logtimezone' => 'UTC' to 'logtimezone' => 'Europe/Amsterdam' in config.php

### Expected behaviour
Log file time should be in Europe/Amsterdam (one hour ahead of UTC)

### Actual behaviour
Log file time stays in UTC

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
SQLite (for testing)

**PHP version:**
php5.5.9+dfsg-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
No (used clean install on virtual machine to reproduce)

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/9.0/xUbuntu_14.04/

**Signing status (ownCloud 9.0 and above):**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ochb7iallurh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.10.111"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.10.111\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.0.19",
        "logtimezone": "Europe\/Amsterdam",
        "logfile": "\/var\/log\/owncloud.log",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 45.0

**Operating system:**
OS X 10.10.5

#### Web server error log
```
[Tue Mar 15 18:33:30.426126 2016] [mpm_event:notice] [pid 10826:tid 140360316999552] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Tue Mar 15 18:33:30.428059 2016] [core:notice] [pid 10826:tid 140360316999552] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:33:48.973100 2016] [mpm_event:notice] [pid 10826:tid 140360316999552] AH00491: caught SIGTERM, shutting down
[Tue Mar 15 18:33:50.272709 2016] [mpm_prefork:notice] [pid 12216] AH00163: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Tue Mar 15 18:33:50.273988 2016] [core:notice] [pid 12216] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:33:51.605206 2016] [mpm_prefork:notice] [pid 12216] AH00169: caught SIGTERM, shutting down
[Tue Mar 15 18:33:53.490215 2016] [mpm_prefork:notice] [pid 12300] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Tue Mar 15 18:33:53.491228 2016] [core:notice] [pid 12300] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:33:59.815458 2016] [mpm_prefork:notice] [pid 12300] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 15 18:34:00.731112 2016] [mpm_prefork:notice] [pid 12300] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Tue Mar 15 18:34:00.731377 2016] [core:notice] [pid 12300] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:34:07.760041 2016] [mpm_prefork:notice] [pid 12300] AH00169: caught SIGTERM, shutting down
[Tue Mar 15 18:34:09.080260 2016] [mpm_prefork:notice] [pid 12435] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Tue Mar 15 18:34:09.081765 2016] [core:notice] [pid 12435] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:34:15.956106 2016] [mpm_prefork:notice] [pid 12435] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Mar 15 18:34:17.112289 2016] [mpm_prefork:notice] [pid 12435] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 configured -- resuming normal operations
[Tue Mar 15 18:34:17.112372 2016] [core:notice] [pid 12435] AH00094: Command line: '/usr/sbin/apache2'
[Tue Mar 15 18:35:08.990935 2016] [:error] [pid 12539] [client 192.168.10.201:64908] creating sqlite db
[Tue Mar 15 18:39:12.071502 2016] [authz_core:error] [pid 12513] [client 192.168.10.201:65028] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Tue Mar 15 18:46:27.128342 2016] [authz_core:error] [pid 12540] [client 192.168.10.201:65269] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"3DH5xqLjel5Wvxp28hf0","remoteAddr":"192.168.10.201","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-15T17:35:10+00:00"}
{"reqId":"3DH5xqLjel5Wvxp28hf0","remoteAddr":"192.168.10.201","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-15T17:35:10+00:00"}
```

#### Browser log
```
Not necessary
```

**Comment by LukasReschke** [comment] 2016-03-15 18:22
Dupe of https://github.com/owncloud/core/issues/23134

**Closed by LukasReschke** 2016-03-15 18:22 UTC

**Comment by masupilamie** [comment] 2016-03-15 18:24
Sorry! (dit search for dupe, but not good enough it seems...)
