### ISSUE TITLE
Owncloud upgrade 7.0.3 -> 8.0.3 

### ISSUE THREAD

**Issue by Gasmann0815** [owncloud/core#16737] opened 2015-06-03 18:53 UTC
An exception occurred while executing 'CREATE TABLE oc_fscache (id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT, path VARCHAR(512) DEFAULT '' NOT NULL COLLATE BINARY, parent BIGINT DEFAULT 0 NOT NULL, name VARCHAR(300) DEFAULT '' '' NOT NULL COLLATE BINARY, user VARCHAR(64) DEFAULT '' '' NOT NULL COLLATE BINARY, size BIGINT DEFAULT 0 NOT NULL, ctime BIGINT DEFAULT 0 NOT NULL, mtime BIGINT DEFAULT 0 NOT NULL, mimetype VARCHAR(96) DEFAULT '' '' NOT NULL COLLATE BINARY, mimepart VARCHAR(32) DEFAULT '' '' NOT NULL COLLATE BINARY, encrypted SMALLINT DEFAULT 0 NOT NULL, versioned SMALLINT DEFAULT 0 NOT NULL, writable SMALLINT DEFAULT 0 NOT NULL, path_hash VARCHAR(32) DEFAULT '' NOT NULL COLLATE BINARY)': SQLSTATE[HY000]: General error: 1 near "''": syntax error

**Comment by MorrisJobke** [comment] 2015-06-04 07:21
> CREATE TABLE oc_fscache

This looks weird. This table was dropped in ownCloud 5? @icewind1991 Any idea how this could have slipped in?

@Gasmann0815 Can you provide more information? The best would be to fill out the issue template: https://github.com/owncloud/core/blob/master/issue_template.md

Is the instance now usable? Can you reproduce the issue? What steps did you run? What happened when?

**Comment by DeepDiver1975** [comment] 2015-06-04 07:25
Bloody xml Schema .....

**Comment by Gasmann0815** [comment] 2015-06-04 09:41
Steps to reproduce:
Upgrading from  7.0.4 -> 8.0.3

Tell us what happens instead
Server stop in maintenance mode

Server configuration
HP Proliant Mircoserver - AMD Turion(tm) II Neo N54L Dual-Core Processor
Freenas Jail
<https://forums.freenas.org/index.php?threads/drkks-definitive-guide-to-installing-owncloud-in-freenas-or-freebsd.19605/>

Operating system:
FreeNAS-9.3-STABLE-201505040117

Web server:
lighttpd-1.4.35_5

Database:
Sqlite3 3.8.7.4 2014-12-09 

PHP version:
PHP 5.4.36 (cli) (built: Dec 31 2014 22:18:37) 

ownCloud version: (see ownCloud admin page)

Updated from an older ownCloud or fresh install:
Updated from 7.0.4

List of activated apps:
Only Core Apps

The content of config/config.php:
$CONFIG = array (
  'datadirectory' => '/usr/local/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installedat' => '1323041396.4616',
  'lastupdatedat' => '1328963431.7317',
  'installed' => true,
  'loglevel' => '0',
  'instanceid' => '50004c0c36ffc',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '192.168.2.10',
  ),
  'secret' => 'xxx',
);

No external storage, no encyprytion
external user-bachend: webfrontend, android: caldav calendar-sync  carddav-sync

ownCloud log (data/owncloud.log)
{"reqId":"3539f73c25da5dc4392f7bad15678b7c","remoteAddr":"192.168.2.2","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('activity')\\n#1 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/base.php(781): OC_Util::setupFS()\\n#3 \\\/usr\\\/local\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-06-04T09:06:54+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=12d6a24de40838c2e9e62633ed77c237"}

**Comment by RealRancor** [comment] 2015-06-04 09:53
Looks similar to: https://github.com/owncloud/core/issues/16347 where this happened during the update from 8.0.2 -> 8.0.3

**Comment by MorrisJobke** [comment] 2015-06-04 11:00
Closing because of the duplicate.

Follow up in #16347

**Closed by MorrisJobke** 2015-06-04 11:00 UTC
Labels: bug, needs info, update
