### ISSUE TITLE
iPhone direct image uploads always named image.jpg

### ISSUE THREAD

**Issue by bence8810** [owncloud/core#18449] opened 2015-08-20 04:40 UTC
Hello,

I am not sure I am posting this to the right place - please feel free to move it if need be.

I wanted to create a folder where all my friends could upload their photos from our recent trip and as they don't have (or need) accounts to my owncloud, I created a share via link that can be edited.

They went and started uploading files but the iPhone which they all have names the photos image.jpg and this resulted in some of them overwriting eachothers' images.

First person uploads 10 files, it'll be image.jpg / image01.jpg / image02.jpg - image09.jpg
Next person comes, he'll be prompted that the file name already exist and if you choose to continue without paying attention, it'll overwrite the already existing files.

Is there a way to somehow allow the iPhone uploads to be automatically named like how it is done when one uses the Owncloud iOS app to synch files?

Thanks,
Ben

**Comment by MorrisJobke** [comment] 2015-08-20 07:18
Usually you will get a file conflict dialog where you can select both files and then the new one gets a new unused name.

![bildschirmfoto von 2015-08-20 09-16-51](https://cloud.githubusercontent.com/assets/245432/9377761/453f13f0-471c-11e5-9b32-e5167e1535af.png)


> Is there a way to somehow allow the iPhone uploads to be automatically named like how it is done when one uses the Owncloud iOS app to synch files?

I'm not sure, but I think it chooses the filename of the image. cc @rperezb

**Comment by bence8810** [comment] 2015-08-20 08:52
@MorrisJobke yes that is true - we all got that but on the iPhone 5 (ex. small screen) the whole window isn't shown and it's hard to click on Continue.

Also at the same time multiple people might be uploading which could also cause some trouble.
Best would be if it could date-name it or something like the Sync client. 
When you back an iPhone up or just download the files via iTunes, there are problem IMGxxxx.jpg names so I am not sure why it comes as image.jpg. 

Thanks,
Ben

**Comment by MorrisJobke** [comment] 2015-08-20 09:27
> When you back an iPhone up or just download the files via iTunes, there are problem IMGxxxx.jpg names so I am not sure why it comes as image.jpg.

I guess this is a sandboxing feature of iOS that can't be curricumvented :(

@jancborchardt We need to fix the conflict dialog for mobile UI.

**Comment by MorrisJobke** [comment] 2015-08-20 09:29
I would rate this as a duplicate of #15552

@bence8810 Please follow up there .

**Comment by MorrisJobke** [comment] 2015-08-20 09:29
And thanks for the report :)

**Closed by MorrisJobke** 2015-08-20 09:29 UTC
Labels: bug, design

**Comment by rperezb** [comment] 2015-08-20 12:54
@MorrisJobke, the thing is that this is a different use case, when the uploads are handled by the ownCloud iOS, no matter whether they are instant or not, we are renaming the images taken into account the date when they were taken. The idea was to avoid this error.
However, since in this case they are uploading the images directly to the web interface, the name is the one set by the system, IMG_xx.

So, no way of changing them, in advanced.
