### ISSUE TITLE
[question] create without without any file/folders

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#38628] opened 2021-04-09 07:03 UTC
### Description
new users created in OCIS are created without any files/folders but this is not the same with `owncloud/core`.
Even if skeleton dirs are turned off, the new users will get a file `welcome.txt`. 

can we create users without any files/folders like owncloud/core too??

**Comment by kiranparajuli589** [comment] 2021-04-09 07:05
Acceptance tests can be more optimized with this.

> https://github.com/owncloud/core/pull/38623#discussion_r609629086

**Comment by phil-davis** [comment] 2021-04-13 07:58
See issue #38607 
The problem is resolved by PR #38636 - we use `tinySkeleton` that was introduced in the testing app PR https://github.com/owncloud/testing/pull/171

In ownCloud 10 there is really no such thing as "without skeleton files" - there is always some "skeleton directory"

**Closed by phil-davis** 2021-04-13 07:58 UTC
