### ISSUE TITLE
Sharing to groups with many users becomes slower over time

### ISSUE THREAD

**Issue by butonic** [owncloud/core#13725] opened 2015-01-28 10:20 UTC
Sharing a file with a group not only creates one tupel in the oc_shares table for the group but also for every user in the group. That becomes a problem when sharing to large groups, as the number of rows in the table increases until we run into timeouts for huge groups.

IMO the correct solution is yet again an mq system that takes decouples db changes from the web request.

cc @schiesbn @DeepDiver1975

**Comment by PVince81** [comment] 2015-01-28 12:06
Note: we cannot do without having those extra entries because users might rename the target folder.

I agree with the background job approach, hopefully we can add this in the near future.

**Comment by butonic** [comment] 2015-01-28 12:36
when the user tries to rename his share we could add the user entry on the fly.

**Comment by butonic** [comment] 2015-02-03 14:17
@DeepDiver1975 any priorization on this?

**Comment by butonic** [comment] 2015-02-03 14:19
depends on https://github.com/owncloud/core/issues/13816 for a correct fix

**Comment by butonic** [comment] 2015-02-03 19:41
the cause is likely `apps/files_sharing/lib/updater.php Shared_Updater::postShareHook()`.

the code will update the parent etags of the folder that pops up in users homes. that is one file_exists and a stat call for each user. so sharing with a group of 10000 users will result in a stat call for at least the '/files' folder of every user in the group. which is 10000 stat call to the filesystem. Add another 10k stat calls if the `'share_folder'` is something different than '/'.

php caches stat calls, unfortunately in this case the filesystem has to stat 10000 different files.

@felixboehm try to comment https://github.com/owncloud/core/blob/stable7/apps/files_sharing/lib/helper.php#L19 to see if that removes some load. If it helps we could move this to a background job, so the share web request no longer times out.

**Comment by PVince81** [comment] 2015-02-04 08:58
@icewind1991 see previous comment

**Comment by PhilJung** [comment] 2015-02-04 12:08
When I observed this phenomenon (share taking more than 50 seconds), here is what is noticed:
- the time is not spent in the database. There are plenty of locks but most of them are immediate lock (no wait). There are plenty of SELECT but most of them get an immediate answer thanks to the query cache. There is no query taking more than 1 second (fro mysql_dump_slow) So maybe writing all users share in one transaction can be more efficient than one after the other but you won't gain a lot. Introducing a message in the queue is also writing in the database. May be in a smaller table but the "contention" will be transfered fro oc_share to oc_jobs
- the time is spent in the file system scanning (file_exists, mkdir, and so on, 35 to 40 seconds). One user performing ls is OK, but when 1000 people perform simultaneously file system io in a folder where there are 100.000 user data folders, especially when the filesystem is not local, this is the bottleneck I faced. 
In the case I faced, time was spent in 
apps/files_sharing/lib/share/file.php in generateTarget.

3/5 of the time in                  return \OCA\Files_Sharing\Helper::generateUniqueTarget($target, $excludeList, $view);
2/5 of the time in the first part of the code

**Comment by icewind1991** [comment] 2015-02-04 13:37
@PhilJung thanks for the info, would it be possible to get an xdebug or http://blackfire.io trace from a long share operation?

**Comment by PhilJung** [comment] 2015-02-04 15:06
I hope this is what you expect :-)
https://blackfire.io/profiles/0cba44b5-74be-460e-be57-88385cb5e9e9/graph

**Comment by icewind1991** [comment] 2015-02-04 15:28
@PhilJung thanks that's very helpfull

**Comment by icewind1991** [comment] 2015-02-04 17:09
With a combination of #13893, #13896, #13899 and #13829 I managed to shave almost 60% of the time required to share a file with a group of a thousand users on my local instance.

There is still plenty of room for improvement left but it would be easier to first have the above PR's merged

[comparison](https://blackfire.io/profiles/compare/c4a03dd3-1dcd-44d2-a18f-fc1392d78a86/graph)

**Comment by PVince81** [comment] 2015-02-04 17:12
Wow, you rock! Let's get this in 8.1

**Comment by schiesbn** [comment] 2015-02-04 18:32
> when the user tries to rename his share we could add the user entry on the fly.

That's how it is supposed to be. If it behaves differently then it is a bug. I will try to reproduce it tomorrow

**Comment by icewind1991** [comment] 2015-02-05 12:23
> That's how it is supposed to be. If it behaves differently then it is a bug. I will have a look at it tomorrow

Fix is here: https://github.com/owncloud/core/pull/13919

**Comment by PhilJung** [comment] 2015-02-05 12:25
Hi,
I had average times for some "standard' requests on the 7.0.4 versions. So I replayed the same tests on version 8.0.5 + the 4 PR mentionned above.
You will find average time for each user action. I have also detailled what is inside the user action.

You have just to take into account I have one additional non "PR" patch : the getHome for a user is not datadir/$uid but datadir/substr(md5($uid),2)/$uid.
With my glusterfs, having 100.000 user folders at one place is simply impossible. With my modification, I have 256 folders of +/- 400 users each and it works.

My feelings (and they may be wrong) :-)
- there are js file accessed though index.php 
- why not to call translations once for all
- Desktop client periodic check seems to be always too calls, why not to group them ? If I save 1 call every 30s for 100000 users that is 3000 requests per sec saved.

If you need more blackfire traces, just ask :-)

User action | V7.0.4 | V8 + patch | Detail
---------------------- | ---------------------- | ---------------------- | ----------------------
Authent (Web) | 14466 | 21386 | /, apps/files/, translations.php (x4) avatar (x2), mimes, scan, getstoragestats (x2), list, share
Create folder (DAV) | 8518 | 6403 | webdav (MKCOL, PROPFIND, MOVE, PROPPATCH, HEAD, PROPFIND)
Logout (Web) | 757 | 732 | Index, /
Push a file (DAV) | 5070 | 2150 | webdav (PUT) or webdav (PUT chunk1, PUT chunk 2)
Get server status (DAV) | 7868 | 10919 | /status.php and /remote.php/webdav
Open folder (Web) | 1100 | 801 | list, getstoragestats
Welcome (Web) | 966 | 1248 | /, oc.js, translations
Share a file to a group (Web) | 30444 | 7572 | share (getItem, getShareWith, getShareWith, getShareWith, share) 
Download a shared file (Web) | 2561 | 1702 | translations, shares, download
Delete file (DAV) | 3966 | 1690 | webdav (DELETE)
Delete folder (DAV) | 2949 | 1231 | webdav (DELETE)
Upload 100k file (web) | 8346 | 4204 | upload, mimeicon (x3), getstoragestats, preview, upload, getstoragestats, rename
Upload 20M file (web) | 38561 | 9320 | upload, mimeicon (x3), getstoragestats, preview, upload, getstoragestats, rename
Upload 500k file (web) | 8933 | 3518 | upload, mimeicon (x3), getstoragestats, preview, upload, getstoragestats, rename
Upload 5M file (web) | 16769 | 7419 | upload, mimeicon (x3), getstoragestats, preview, upload, getstoragestats, rename
Periodic check (DAV) | 19296 | 18591 | 10 webdav (getetag) + 10 webdav (quota-available-bytes/quota-used-bytes)

**Comment by MorrisJobke** [comment] 2015-02-05 13:19
> Desktop client periodic check seems to be always too calls, why not to group them ? If I save 1 call every 30s for 100000 users that is 3000 requests per sec saved.

cc @dragotin

**Comment by dragotin** [comment] 2015-02-05 14:07
The client does a quota request regularly which is account specific, not sync connection related. The second call that you see checks for the etag of each sync connection (!) which is not account, but folder specific. That is why its two or more.

**Comment by DeepDiver1975** [comment] 2015-02-24 11:27
> there are js file accessed though index.php

With OC8 there is only one javascript file left which is processed by php
(same applies to css files as well)

> why not to call translations once for all

with oc8 translations are loaded statically from the web server and can we cached in the browser now

@PhilJung what is the number in the two version columns? number of requests?

**Comment by PhilJung** [comment] 2015-02-24 11:52
@DeepDiver1975 Average time in milliseconds for the total "user" action. For example, when I log in, my injection test calls 
/
apps/files/
4 times translations.php
twice avatar (x2)
1 mimes, 
1 scan, 
2 getstoragestats (x2), 
1 list 
1 share

This is based on sniffing with JMeter recorder trafic between web browser and OC server.

The average total duration for all these actions were 14 seconds with v7 and is now 21 seconds with v8 + patch

**Comment by DeepDiver1975** [comment] 2015-02-24 12:07
Thanks a lot for the explanation @PhilJung

**Comment by DeepDiver1975** [comment] 2015-02-24 12:08
@jnfrmarks @PVince81 @icewind1991 we need some script based approach to measure time on operations - focus shall be webdav operations at first.

**Comment by craigpg** [comment] 2015-03-10 18:11
Removed green-ticket because there doesn't appear to be any additional trouble-shooting required to understand the requirement(s) / issue(s).

**Comment by PVince81** [comment] 2015-09-21 14:10
@schiesbn @icewind1991 are we still reading all users from the oc_share table as per the original post ? Or is this fixed and can be closed ?

**Comment by cmonteroluque** [comment] 2015-10-01 17:56
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by rullzer** [comment] 2015-10-02 13:45
As far as I can tell and can tests this is fixed. So closing time!

**Closed by rullzer** 2015-10-02 13:45 UTC
Labels: enhancement, performance, sharing
