### ISSUE TITLE
[enc2] Move file out of share as recipient breaks file

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15578] opened 2015-04-13 13:42 UTC
### Steps to reproduce
1. Enable encryption app + encryption module in admin page
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Create or upload a picture "test.jpg" into "test"
1. Share "test" with "user2"
1. Login as "user2"
1. Download and open pic: works
1. Move "test.jpg" into the root in the web UI (drag and drop)
1. Try downloading and opening "test.jpg" now

### Expected result
File can still be opened

### Actual result
Broken file is downloaded

### Versions
Observed on master (actually the enc2_migration branch https://github.com/owncloud/core/pull/15445)

@schiesbn @th3fallen 

@icewind1991 are we still doing a stream copy when moving between shared storage and regular storage ? I thought that would trigger re-encryption

**Comment by icewind1991** [comment] 2015-04-13 15:34
> @icewind1991 are we still doing a stream copy when moving between shared storage and regular storage ? I thought that would trigger re-encryption

atm we do, #13360 is looking to change that

**Comment by schiesbn** [comment] 2015-04-22 09:38
can't reproduce it any longer in master. Probably fixed by the #13360 or one of the other encryption fixes

**Closed by schiesbn** 2015-04-22 09:38 UTC
Labels: app:encryption, bug, sev2-high
