### ISSUE TITLE
Overwriting webroot does not work after upgrade from 8.1->8.2

### ISSUE THREAD

**Issue by milch** [owncloud/core#20080] opened 2015-10-27 10:57 UTC
### Steps to reproduce
1. Use a `Dockerfile` like this to install owncloud 8.1 with some php extensions:
```Dockerfile
FROM owncloud:8.1
MAINTAINER Manu Wallner <m.wallner@xforge.at>

RUN apt-get update -qq && apt-get install -y libldap2-dev libldb-dev libreoffice redis-server wget cron && apt-get clean && apt-get purge

# Install php ldap extension
RUN ln -fs /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/
RUN docker-php-ext-configure ldap && docker-php-ext-install ldap

# Install PHP redis extension
RUN cd /usr/src/php/ext && wget http://pecl.php.net/get/redis && tar xzf redis && rm redis && mv redis-* redis
RUN docker-php-ext-install redis

# Install cron owncloud script to run every 15 minutes
RUN echo "*/15  *  *  *  * /usr/local/bin/php -f /var/www/html/cron.php > /tmp/oc-cron.log 2>&1" | crontab -u www-data -

ADD ["var/www/html/config/config.php", "/var/www/html/config/config.php"]
``` 
2. Place the `config.php` file provided below in the subfolder `var/www/html/config/` relative to the `Dockerfile`.
3. Create a reverse proxy that points `https://example.org/owncloud/` to the ownCloud instance created above. Visit the address in your web browser and observe that the ownCloud instance is accessible. 
3. Upgrade to version 8.2 (i.e. by changing the line `FROM owncloud:8.1` to `FROM owncloud:latest` in the `Dockerfile`)

### Expected behaviour

Same as before the upgrade: The reverse proxy configuration should be picked up as normal and the ownCloud instance should be accessible.

### Actual behaviour

This is what the web page looks like after upgrading:

![screen shot 2015-10-27 at 11 22 27](https://cloud.githubusercontent.com/assets/279407/10755291/037b0fb2-7c9d-11e5-9f39-196f2c359a0c.png)

Login and sync is non-functional.

### Server configuration
**Operating system**:
Docker Host: Debian 8
**Web server:**
NGINX 1.9.5 reverse proxying to the Apache server from the ownCloud Docker image.
**Database:**
PostgreSQL 9.4.5
**PHP version:**
Same as ownCloud Docker image
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Updated from 8.1
**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - documents: 0.10.1
  - encryption: 1.1.0
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
  - user_ldap: 0.7.0
Disabled:
  - external
  - files_external
  - gallery
  - galleryplus
  - notifications
  - storagecharts2
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocbwrs69s1dm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.99.101",
            "owncloud",
            "example.org"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "https:\/\/example.org\/owncloud",
        "overwritehost": "example.org",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/owncloud",
        "dbtype": "pgsql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "db",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "example.org",
        "mail_smtpauth": 1,
        "mail_smtphost": "example.org",
        "mail_smtpport": "25",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local `/data/` folder

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:**
Safari 9.0.1 and Chrome 46.0.2490.80 (64-bit)
**Operating system:**
Mac OS X 10.11.1 (15B42)

#### Web server error log

```
$ tail /var/log/nginx.log
2015/10/27 10:29:57 [error] 6#6: *152 rewrite or internal redirection cycle while internally redirecting to "/index.php", client: **snip**, server: example.org, request: "GET /apps/firstrunwizard/js/jquery.colorbox.js?v=b5e96f820b65221c539d9f2494889fea HTTP/2.0", host: "example.org"
2015/10/27 10:29:57 [error] 6#6: *152 rewrite or internal redirection cycle while internally redirecting to "/index.php", client: **snip**, server: example.org, request: "GET /apps/firstrunwizard/js/firstrunwizard.js?v=b5e96f820b65221c539d9f2494889fea HTTP/2.0", host: "example.org"
# Many more of these
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"xRXdkRuZ2LgeCTcIVXnp","remoteAddr":"**snip**","app":"webdav","message":"Exception: {\"Message\":\"Requested uri (\\\/owncloud\\\/remote.php\\\/webdav\\\/) is out of base uri (\\\/remote.php\\\/webdav\\\/)\",\"Exception\":\"LogicException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1279): Sabre\\\\HTTP\\\\Request->getPath()\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/html\\\/remote.php(137): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Request.php\",\"Line\":210}","level":4,"time":"2015-10-27T10:35:57+00:00"}
```

#### Browser log
```
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (sharedialogshareelistview.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (visitortimezone.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (lostpassword.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (login.js, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (loading-dark.gif, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (user.svg, line 0)
[Error] Failed to load resource: the server responded with a status of 500 (HTTP/2.0 500) (password.svg, line 0)
```

![screen shot 2015-10-27 at 11 38 59](https://cloud.githubusercontent.com/assets/279407/10755858/9d4d2e4c-7ca0-11e5-94cc-293b7aefdaec.png)

(Note the missing /owncloud/ from the requested URLs)

**Comment by LukasReschke** [comment] 2015-10-27 10:59
Duplicate of https://github.com/owncloud/core/issues/19901

**Closed by LukasReschke** 2015-10-27 10:59 UTC
