### ISSUE TITLE
[Sharing] Web browser has to be refreshed to let a file be marked as shared, if we share a file from iOS OC app

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20711] opened 2015-11-24 15:14 UTC
### Steps to reproduce

1. Create folder using any browser
2. Using iOS mobile app, upload a file inside the browser
3. Share this file e.g. via link
4. Go to browser and browse to the root.
5. Browse inside the folder again

### Expected behaviour

The shared 'symbol' should be visible. The file should be marked as shared.

### Actual behaviour

The file does not appear as shared in the browser.
Note: The file appears as shared when refreshing the browser.
This behaviour does not happen renaming a file for example.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-19T04:29:14+00:00 da5285dc23dc88d8f570409a8d7ed1296b95f407

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-24 at 16 04 46](https://cloud.githubusercontent.com/assets/10596560/11370923/20c33772-92c6-11e5-8004-e4ba72cc9208.png)

![image1](https://cloud.githubusercontent.com/assets/10596560/11370926/280b816a-92c6-11e5-95c3-5900ebd1402a.PNG)

**Comment by rullzer** [comment] 2015-11-24 16:06
Yes this is known. It is ebcause there is no persistent connection to the server. Unfortunatly there is no clear solution to this.

Duplicate of https://github.com/owncloud/core/issues/6813 so closing.

**Closed by rullzer** 2015-11-24 16:06 UTC
Labels: bug, discussion, enhancement - proposed, feature:sharing
