### ISSUE TITLE
OC7: Problems converting from SQLite3 to PostgresQL

### ISSUE THREAD

**Issue by jmaerki** [owncloud/core#9891] opened 2014-07-25 08:01 UTC
(Move here from http://forum.owncloud.org/viewtopic.php?f=29&t=22446)

I've just upgraded to OwnCloud 7 and the upgrade went well. It's currently running on SQLite and I would like to migrate to PostgresQL since I've run into concurrency problems due to the usage of multiple devices.

### Steps to reproduce

So, after finding https://github.com/owncloud/core/issues/9526 I adjusted the call to the following:
`sudo php occ db:convert-type --password="wonttell" --all-apps pgsql owncloud localhost owncloud`

### Expected behaviour
Well, just a regular migration from SQLite to PostgresQL.

### Actual behaviour
The first issue was:

```
    oc_filecache
      8810/20428 [============>---------------]  43%

     [Doctrine\DBAL\DBALException]
      An exception occurred while executing 'INSERT INTO oc_filecache ("fileid", "storage", "parent", "name", "mimetype", "mimepart", "mtime", "encrypted", "path
      _hash", "etag", "storage_mtime", "path", "size", "unencrypted_size", "permissions") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["209
      08", "7", "20905", "\x31\x35 [..] \x6d\x70\x33", "11", "10", "1295508789", "0", "[..]", "[..]", "1295508789", "\x4d
      \x75\x73\x69\ [..] \xb4\x74 [..]", "3903543", "0", "0"]:

      SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xb4

      [PDOException]
      SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xb4
```

I've replaced some content with [..] above to obfuscate the actual data. Anyway, the Postgres database is set up as described in the manual. It says "UTF-8" as encoding, but I suspect this is coming from the reading side somehow.

I read somewhere that it is possible to reset the file cache, so I ran "sqlite3 owncloud.db" and "DELETE FROM oc_filecache;" and that actually brought me past this first issue.

But then I ran into the following:

```
    oc_contacts_cards_properties
      365/1516 [======>---------------------]  24%

      [Doctrine\DBAL\DBALException]
      An exception occurred while executing 'INSERT INTO oc_contacts_cards_properties ("id", "name", "value", "preferred", "userid", "contactid") VALUES (?, ?, ?, ?, ?, ?)' with params ["486", "PHOTO", "\/9j\/4AAQS [..] 8A\/9k=", "0", "[..]", "73"]:

      SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)

      [PDOException]
      SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)
```

"value" is quite big, surely more than 255 characters. Given that the parameter is called "PHOTO" I assume a base64-encoded JPEG image associated with a contact. But on the PostgresQL table created the column "value" is just "value character varying(255) DEFAULT NULL::character varying" which explains the problem. Should this maybe be a "text" or blob?

### Server configuration
**Operating system**: Linux 3.10.25+ armv6l (RaspberryPi)

**Web server:** Apache HTTPD 2.2.22

**Database:** SQLite3 3.7.13, PostgresQL 9.1.13

**PHP version:** 5.4.4-14+deb7u12

**ownCloud version:** 7.0.0

**Updated from an older ownCloud or fresh install:** Updated from latest OC 6.x

**List of activated apps:** Standard apps + Mozilla Sync

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '51bc88cb8abfa',
  'passwordsalt' => 'wonttell',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.0.8',
  'installed' => true,
  'loglevel' => '1',
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpdebug' => true,
  'mail_smtphost' => 'mail.wonttell',
  'mail_smtpauth' => true,
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'wonttell',
  'mail_smtppassword' => 'wonttell',
  'theme' => '',
  'maintenance' => false,
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'trusted_domains' =>
  array (
    0 => 'wonttell.domain',
  ),
);
```

**Are you using external storage, if yes which one:** local (external USB drive)

**Are you using encryption:** yes

### Client configuration
n/a here

#### Web server error log
n/a here
#### ownCloud log (data/owncloud.log)

I've got quite a few of these in the logs even before the upgrade to OC7 which could be relevant:

```
{"app":"core","message":null,"level":2,"time":"2014-07-24T08:29:30+00:00"}
{"app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at \/mnt\/usbdrive\/www\/owncloud\/lib\/private\/log\/owncloud.php#86","level":3,"time":"2014-07-24T08:29:30+00:00"}
```
Otherwise, I don't see anything in the logs that could be applicable to this problem.

#### Browser log
n/a here

**Comment by jmaerki** [comment] 2015-01-13 09:39
Thanks for all the feedback. That prompted me to try again and it actually helped me do the migration in the end even if there was quite a bit of manual editing of database.xml was required. Hopefully not with any downsides with future upgrades.
But....I want to make everyone aware that I had one major downside to it all and I don't know if it's a problem of the migration or the database design to begin with: After I migrated, the shares (by link) I had were suddenly pointing to random files that I've never shared with anyone. And that's really, really bad. It feels like the shares rely on an ID allocated by the database and when you migrate the IDs might be different but the link still uses the same number. I haven't checked the actual implementation and I realize that this is probably a separate issue from this ticket but it has clearly a connection to database migration.

**Comment by PVince81** [comment] 2015-01-13 10:55
The database does uses file ids for shares and in the future "favorites".

If the conversion code isn't able to keep file ids then this is a major bug!

@bantu can you comment on this ?

**Comment by DeepDiver1975** [comment] 2015-01-13 11:51
> If the conversion code isn't able to keep file ids then this is a major bug!

well - because we use autoincrement/sequences this will be really interesting to solve - we did not think about this .... tooo bad

**Comment by DeepDiver1975** [comment] 2015-01-13 11:52
@bantu please have a look at this as soon as time permits - THX

**Comment by DeepDiver1975** [comment] 2015-01-13 11:52
scheduling for 8.0 for at least analysis - let's see if we can come up with a solution .....

**Comment by bantu** [comment] 2015-01-13 12:16
> If the conversion code isn't able to keep file ids then this is a major bug!

> well - because we use autoincrement/sequences this will be really interesting to solve - we did not think about this .... tooo bad

From reading the code (https://github.com/owncloud/core/blob/master/core/command/db/converttype.php#L242), all data is copied including autoincrement/sequences. For PostgreSQL we additionally resynchronise sequences to their expected value (https://github.com/owncloud/core/blob/master/core/command/db/converttype.php#L271 https://github.com/owncloud/core/blob/master/lib/private/db/pgsqltools.php#L50)

**Comment by DeepDiver1975** [comment] 2015-01-22 11:48
moving to 8.1 - time is up for 8.0

**Comment by bantu** [comment] 2015-02-17 23:29
@DeepDiver1975 Not sure what to do with this further.

Based on https://github.com/owncloud/core/issues/9891#issuecomment-69736128 I don't think an accidental change of primary key columns as suggested by https://github.com/owncloud/core/issues/9891#issuecomment-69718387 is possible.

In my opinion, the root cause of most migration issues is insufficient validation of input data (in the first place). E.g., if you're writing into a varchar 100 column, validate that the data actually is 100 characters or less before attempting to write into the DB. (There has to be a proper error message saying that the data is too long anyway; instead of a SQL error or another generic message.)

The above combined with the fact that SQLite accepts arbitrary length data (as per https://github.com/owncloud/core/issues/9891#issuecomment-52438670) leads migrations to fail with "data too long" errors. Since the data is already in the database, users will have to cleanup their DBs before migration manually anyway.

**Comment by bantu** [comment] 2015-02-17 23:43
On second thought:

1. The "After I migrated, the shares (by link) I had were suddenly pointing to random files that I've never shared with anyone." behaviour described in https://github.com/owncloud/core/issues/9891#issuecomment-69718387 can be explain by the "DELETE FROM oc_filecache" query described in the ticket description in combination with SQLite's Truncate Optimization (https://www.sqlite.org/lang_delete.html): No WHERE clause --> DELETE actually is TRUNCATE --> Reset of auto increment counters -> reuse of ids -> shares pointing to different files.

2. The initial SQL error "SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xb4" remains to be investigated. So let's make this ticket about that.

**Comment by bantu** [comment] 2015-02-18 00:10
On the other hand, my sqlite does not seem to reproduce.
```
SQLite version 3.8.6 2014-08-15 11:46:33
Enter ".help" for usage hints.
sqlite> .tables
sqlite> create table tbl1(ID INTEGER PRIMARY KEY AUTOINCREMENT, col2 VARCHAR(255));
sqlite> insert into tbl1 (col2) VALUES ('foo');
sqlite> insert into tbl1 (col2) VALUES ('bar');
sqlite> select * from tbl1;
1|foo
2|bar
sqlite> delete from tbl1;
sqlite> insert into tbl1 (col2) VALUES ('barz');
sqlite> select * from tbl1;
3|barz
```

**Comment by DeepDiver1975** [comment] 2015-10-06 13:37
@karlitschek @cmonteroluque this is the famous 3byte vs 4byte mysql char set issue - not really a solution at hand - suggest to move this to the backlog

**Comment by karlitschek** [comment] 2015-10-06 13:48
Yes unfortunately. This needs a lot more thinking later.

**Comment by cmonteroluque** [comment] 2015-10-06 15:25
Nod.

**Comment by nickvergessen** [comment] 2016-02-16 12:14
The column in the new dav app is clob, so should be fine?
@DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment] 2016-02-24 12:51
> The column in the new dav app is clob, so should be fine?

yes - woth exception of the mysql utf8 issue - but this a total different topic.

For all the other issues I don't see much we can do -> closing

**Closed by DeepDiver1975** 2016-02-24 12:51 UTC
Labels: app:dav, bug, feature:update, sev2-high
