### ISSUE TITLE
Installation page has a confusing gif

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14526] opened 2015-02-26 09:53 UTC
### Steps to reproduce

1. Start a fresh installation, you don't need to fill any fields or do anything, just see the installation page.

### Expected behaviour
Installation page loads correctly and doesn't have confusing gifs of loading.

### Actual behaviour
There is a confusing gif at the bottom of the page.

![screen shot 2015-02-26 at 10 47 42](https://cloud.githubusercontent.com/assets/9048796/6389594/9974af8a-bda5-11e4-9de6-dfaa52d5292e.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.0

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
Browser, Chrome

**Comment by karlitschek** [comment] 2015-02-26 19:47
@jancborchardt What do you think?

**Comment by jancborchardt** [comment] 2015-02-26 19:57
@SergioBertolinSG does this also appear without any Enterprise theming? When testing I couldn’t reproduce.

@sebomoto you worked on introducing the loading spinner, any idea about what could be wrong here?
cc @owncloud/designers

**Comment by MorrisJobke** [comment] 2015-02-26 20:05
@jancborchardt This appears if you type something wrong in (i.e. DB password) then the page has this loading icon even if the side isn't loading anymore.

**Comment by SergioBertolinSG** [comment] 2015-02-27 08:34
@jancborchardt It happens also in the community theme.

![screen shot 2015-02-27 at 09 31 47](https://cloud.githubusercontent.com/assets/9048796/6409390/8990cdb0-be63-11e4-9473-1dd8cb2f6b1e.png)

**Comment by nickvergessen** [comment] 2015-03-02 15:43
@sebomoto this was broken by #12213 which is your PR.
can you try to help here?

**Comment by sebomoto** [comment] 2015-03-02 20:08
sure - i will look into this!

**Comment by sebomoto** [comment] 2015-03-02 20:43
i think it is because the loading-spinner is initiall hidden with javascript - i haven't thought about that because the other elements are hidden with .js as well.

**Comment by nickvergessen** [comment] 2015-03-03 08:45
Thanks

**Comment by nickvergessen** [comment] 2015-03-03 09:30
Reopening for stable8 fix

**Comment by jancborchardt** [comment] 2015-03-03 17:54
@sebomoto great, thanks for checking it out! :)

**Comment by jancborchardt** [comment] 2015-03-23 13:43
@nickvergessen is this fixed now?

**Closed** 2015-03-23 13:54 UTC
Labels: bug, Design, Junior Job, needs info, settings:installation
