### ISSUE TITLE
top bar on user page is not adaptive to browser screen window

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#17612] opened 2015-07-13 14:09 UTC
### Steps to reproduce
1.Setup owncloud 8.1
2. create a user 
3.resize your browser window and narrow it down

### Expected behaviour
Top Bar should collapse or be scrollable 

### Actual behaviour
Serach user Button overlays create user Button

### Server configuration
Centos6

**Web server:**
APache
**Database:**
Mysql
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.1 EE
**Updated from an older ownCloud or fresh install:**
Fresh install

### Client configuration
Chrome
**Operating system:**
Ubuntu14.04 LTS
![auswahl_003](https://cloud.githubusercontent.com/assets/12275313/8651505/87884ab2-2979-11e5-84f6-bf3c59d4c970.png)

@jancborchardt

**Comment by DeepDiver1975** [comment] 2015-07-13 14:17
@jancborchardt

**Comment by jancborchardt** [comment] 2015-07-14 14:25
Yeah – currently this is a compromise. The search bar shows on desktop and hides on mobile, and is shown as long as possible because search is pretty important for users.

We need to properly fix this by using the top search box for users as well, see https://github.com/owncloud/core/issues/14973 – something for 8.2

**Comment by jancborchardt** [comment] 2015-07-17 12:07
Closing as duplicate of #14973  then.

**Closed by jancborchardt** 2015-07-17 12:07 UTC
Labels: design
