### ISSUE TITLE
Owner cannot delete or rename files when others put files in  the owner's shared folder.

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#11341] opened 2014-09-28 07:12 UTC
### System Configuration
**OS:** Ubuntu 14.04.1 LTS with desktop environment
**Server:** Apache 2.4.7
**PHP version:** 5.5.9
**Database:** MySQL
**OwnCloud:** 7.0.2 update from 7.0.1

### Step to Reproduce
1. A share a folder "work" to B
2. B upload a file "meeting.docx" to "work" folder

### Actual Behavior
A isn't able to rename or delete by clicking the pencil / trash bin icon. (But A can delete the file by checking it and press delete instead of the trash bin icon.)

### Expect Behavior
A is able to click those icons.

**Comment by raiffeisennet** [comment] 2015-01-28 13:17
@PVince81 we have the same Problem in oc 7.04, please fix this Issue

**Comment by PVince81** [comment] 2015-01-28 13:25
@raiffeisennet in general fixing an issue is only possible when there is enough information to reproduce it and understand what is happening, which wasn't the case here. Next time please join the other reporters and provide info about your setup, the more information, the better.

But now we might be lucky because there was another fix related to a permission issue:
@raiffeisennet @KKyang @jacobsta811 please try applying this patch: https://github.com/owncloud/core/commit/d534f262aaa21773df5a55099e0d95d2d96434e2.patch which fixes a similar issue with permissions https://github.com/owncloud/core/issues/10299

Let me know if that fixes it for you or not. Thanks!

**Comment by raiffeisennet** [comment] 2015-01-28 15:00
@PVince81 Thank you! The Patch fixed our Issue

**Comment by KKyang** [comment] 2015-01-31 14:39
@PVince81 I'm using the installer from the OC website. How do I apply patches without git? Thanks!

**Comment by PVince81** [comment] 2015-01-31 21:58
Download the patch then run `patch -p1 < d534f262aaa21773df5a55099e0d95d2d96434e2.patch` on the command line inside the "owncloud" folder

**Comment by KKyang** [comment] 2015-02-04 03:29
Thanks. But after the patch it's still not working.

**Comment by KKyang** [comment] 2015-02-04 03:46
@PVince81 
Data permission with 31 is the one I can delete them. All 21s miss the trash bin icon.
![172](https://cloud.githubusercontent.com/assets/2676255/6034864/6570efa8-ac63-11e4-9309-ed95c4aa58d4.png)

**Comment by PVince81** [comment] 2015-02-04 09:07
Yes, the patch doesn't repair already broken entries but just makes sure that no such bogus entries are created in the first place.

You might be able to repair the permissions once by running `sudo -uwww ./occ files:scan --all` (replace "www" with your web server user)

**Comment by PVince81** [comment] 2015-02-06 10:59
So the patch fixed the issue, closing as duplicate of https://github.com/owncloud/core/issues/10299

**Closed by PVince81** 2015-02-06 10:59 UTC
Labels: bug
