### ISSUE TITLE
Make sharing permission defaults configurable

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#28384] opened 2017-07-12 13:04 UTC
We should switch to a more conservative policy in these regards.

This will prevent users from unintentionally giving more permissions on shares as needed. Users will have to consciously decide which additional permissions a recipient should have.
Will also tackle the issue that there always is a short time frame after sharing a file where all permissions are given https://github.com/owncloud/core/issues/11707.

I hope this is not a duplicate, could not find anything during a quick search.

@felixboehm @PVince81 Please find an assignment for this for 10.0.3.

Edit: 
Had another discussion and decided that changing defaults hardcoded is too big of a step. This means that we also need it configurable in the first step. 
For this a config switch with the following options would be minimum.
- all (default; -> as it is today)
- read-only

Depending on efforts setting granular defaults would be nice of course.

**Comment by PVince81** [comment] 2017-07-12 13:52
@pmaier1 duplicate of https://github.com/owncloud/core/issues/11707, I found easily because I knew it existed 😉 

As long as something is in backlog and not planned it doesn't make much sense to find an assignment.

**Comment by pmaier1** [comment] 2017-07-12 14:15
Yep, I thought to untangle the issue in smaller steps to make it easier to have a first step in 10.0.3 but it turned out that just changing defaults would not be a good idea which is why I edited with a minimum approach to make at least "extremes" configurable. I also read #11707 but I thought this ticket is a possible solution to it.

> As long as something is in backlog and not planned it doesn't make much sense to find an assignment.

If possible it would be good to plan the minimum approach for 10.0.3 which is why I asked to find an assignment.

**Comment by PVince81** [comment] 2017-07-12 14:20
assigning self

**Comment by pmaier1** [comment] 2017-07-24 09:49
- [ ] Add to admin docs
- [ ] Add a hint in the 'Hardening' guide

**Comment by PVince81** [comment] 2017-08-03 14:34
@felixboehm you moved this to development, do you still consider this to be a topic for 10.0.3 ?

same question for @pmaier1

**Comment by PVince81** [comment] 2017-08-07 14:53
Dev plan:

- [ ] add new checkbox in settings page under "Sharing" for the administrator: "[x] newly created local shares are read-write by default". The checkbox is ticked by default. If the admin unticks, then they will be read-only.
- [ ] adjust OCS API code to use that setting for its defaults
- [ ] (might not be required, need to test) pass the value to the JS side to properly set the default permissions

**Comment by PVince81** [comment] 2017-08-07 14:54
for the above plan, estimate is 0.25-0.5 md

**Comment by PVince81** [comment] 2017-08-08 11:10
WIP PR here: https://github.com/owncloud/core/pull/28619

**Comment by pmaier1** [comment] 2017-08-10 15:01
> you moved this to development, do you still consider this to be a topic for 10.0.3 ?

Actually yes, if possible.

**Comment by PVince81** [comment] 2017-08-31 09:41
at the bottom of my todo list currently, will move if I don't get to it before final.

**Comment by pmaier1** [comment] 2017-08-31 09:43
> at the bottom of my todo list currently, will move if I don't get to it before final.

10.0.4 is fine if you can't make it for 10.0.3 anymore.

**Comment by PVince81** [comment] 2017-09-01 11:01
PR ready for review: https://github.com/owncloud/core/pull/28619

**Closed** 2017-09-04 19:28 UTC
Labels: enhancement, feature:sharing, p2-high
