### ISSUE TITLE
Public Linc icon on folder not updated immeiately

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27655] opened 2017-04-18 12:13 UTC
### Steps to reproduce
1. share a folder vi public link

### Expected behaviour
The public link overlay in the filelist should be added immediately.

### Actual behaviour
A page refresh is needed to see the public link overlay.

### Server configuration
**Operating system**:
win 10

**Web server:**
apache 2.4

**Database:**
oracle

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
10.0 beta2

**Updated from an older ownCloud or fresh install:**
9.1.4

**Where did you install ownCloud from:**
release tar.bz2

**Signing status (ownCloud 9.0 and above):**
ok

**List of activated apps:**
default install

**Comment by butonic** [comment] 2017-04-18 12:13
cc @felixheidecke

**Comment by PVince81** [comment] 2017-04-20 14:53
Duplicate of https://github.com/owncloud/core/issues/25311

PR is available, please review... https://github.com/owncloud/core/pull/25838

**Closed by PVince81** 2017-04-20 14:53 UTC
Labels: bug, feature:sharing, regression
