### ISSUE TITLE
Cron job errors out and leaves tons of files in tmp directory

### ISSUE THREAD

**Issue by gig13** [owncloud/core#17748] opened 2015-07-20 12:48 UTC
### Steps to reproduce
1. Run the cron every 15 minutes

### Expected behaviour
The cron should run and complete successfully

### Actual behaviour
The cron fails after approximately 20 minutes and leaves a large number of files (125444) in /tmp/owncloud-oc9820a746f5, that start with the LDAP-user_ldap--*
The cron error is 
```
PHP Fatal error: Call to a member function file_exists() on a non-object in /var/www/html/owncloud-enterprise/lib/private/files/filesystem.php on line 610
Unexpected error!
```

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** Oracle 11.2

**PHP version:** 5.4.40

**ownCloud version:** 7.0.6.2

**Updated from an older ownCloud or fresh install:** Updated from OC6

**List of activated apps:** See Configuration Report

**The content of config/config.php:**

```
"config": {
        "instanceid": "12345",
        "passwordsalt": "xxxx Value is set but was removed by reporting app for security reasons xxxx",
        "trusted_domains": [
            "blah1",
            "blah2",
            "blah3"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud-enterprise\/data",
        "dbtype": "oci",
        "version": "7.0.6.2",
        "dbname": "owntest",
        "dbhost": "blah",
        "dbtableprefix": "oc_",
        "dbtablespace": "users",
        "loglevel": "2",
        "dbuser": "owncloud",
        "dbpassword": "xxxx Value is set but was removed by reporting app for security reasons xxxx",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "blah.blah",
        "mail_smtpport": 25,
        "session_lifetime": 5400,
        "trashbin_retention_obligation": 45,
        "singleuser": false,
        "appstoreenabled": false,
        "has_internet_connection": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci",
            "mssql"
        ],
        "secret": "blah",
        "share_folder": "\/Shared"
    },
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 

```
In config report
```

#### ownCloud log (data/owncloud.log)
```
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-07-17T19:55:23+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-07-17T19:55:23+00:00"}
{"app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-07-17T19:55:26+00:00"}
{"app":"PHP","message":"Undefined index: owner at \/var\/www\/html\/owncloud-enterprise\/lib\/private\/share\/hooks.php#64","level":3,"time":"2015-07-17T19:55:38+00:00"}
{"app":"PHP","message":"Call to a member function file_exists() on a non-object at \/var\/www\/html\/owncloud-enterprise\/lib\/private\/files\/filesystem.php#610","level":3,"time":"2015-07-17T19:55:38+00:00"}
```

@MorrisJobke

**Comment by karlitschek** [comment] 2015-07-20 14:56
@DeepDiver1975 @icewind1991 any idea?

**Comment by MorrisJobke** [comment] 2015-07-20 21:11
cc @schiesbn

**Comment by MorrisJobke** [comment] 2015-07-20 21:16
> {"app":"PHP","message":"Undefined index: owner at \/var\/www\/html\/owncloud-enterprise\/lib\/private\/share\/hooks.php#64","level":3,"time":"2015-07-17T19:55:38+00:00"}

This is a duplicate of #16740 which will be fixed in upcoming 7.0.8, 8.0.6, 8.1.1 and 8.2.0. Please retest with those versions. If the problem still exists, reopen this one.

**Comment by MorrisJobke** [comment] 2015-07-20 21:16
All other issues are most propably caused by this one.

**Comment by gig13** [comment] 2015-07-21 12:14
@MorrisJobke @cmonteroluque @bboule 
All other are "most probably" caused by this one? Has there been any testing or validation?

**Comment by gig13** [comment] 2015-09-15 17:46
@MorrisJobke 
I am re-opening this case. 

Sometimes the job completes, sometimes it fails with the error
```PHP Fatal error: Call to a member function file_exists() on a non-object in /var/www/html/owncloud-enterprise/lib/private/files/filesystem.php on line 610
Unexpected error!```

It also always leaves a /tmp/owncloud-oc9820a746f5, but if this
directory is removed the job always succeeds. 

This is with 7.0.8

**Comment by gig13** [comment] 2015-09-23 12:07
@MorrisJobke 
Any status on this? There is a significant amount of data being stored in owncloud cache folders,

**Comment by bboule** [comment] 2015-09-23 18:38
@MTRichards @cmonteroluque hey guys I think we need a little attention on this if possible?

**Comment by MTRichards** [comment] 2015-09-23 18:41
100% a bug.

**Comment by cmonteroluque** [comment] 2015-09-24 17:19
@bboule currently the focus is on finishing 8.2, we can revisit this in a few days

**Comment by gig13** [comment] 2015-09-25 16:19
@bboule 
Latest is this is working with 7.0.10 version with the cron running. All old tmp files have been cleaned up -- closing out.

**Comment by gig13** [comment] 2015-10-02 19:23
Re-opening due to cron showing files timestamped in the future.

```
lib/private/cache/file.php: $result = $storage->touch($key, time() + $ttl);
lib/private/cache/fileglobal.php: return touch($cache_dir.$key, time() 
+ $ttl);
```

As long as these future dated files don't fill up the filesystem, this can be ignored.

However, yesterday the system ran itself out of inodes again as a result of the other files left behind by the cronjob script.

Narrowed the ldap base user and base group trees in the advanced config and enabled apc caching on the command line to see if this helps with the problem.  Since the cronjob seems to randomly fail to cleanup  and fills up the filesystem,  I can't say its working until its been 
stable for longer than a week.

**Comment by gig13** [comment] 2015-10-02 19:23
@MorrisJobke

**Comment by MorrisJobke** [comment] 2015-10-05 09:31
@gig13 This looks like a complete different topic. Can we please open a new ticket?

**Comment by MorrisJobke** [comment] 2015-10-05 09:33
@gig13 Please follow up on #19578

**Closed by MorrisJobke** 2015-10-05 09:33 UTC
Labels: blue-ticket, bug, duplicate
