### ISSUE TITLE
Mobile: In tablet Acer A700 file/folder menu not visible before clicking in it

### ISSUE THREAD

**Issue by Bullnados** [owncloud/core#18259] opened 2015-08-13 09:16 UTC
In owncloud demo the download, share, garbage symbols in files app not visible, whether there would enough space(1920x1200).
You have to click the area to visible symbols and not to enter folder/file. The problem is when u click at (invisible) garbage symbol folder/file is deleted immediately. Same with share download symbols (here with popup)

**Comment by PVince81** [comment] 2015-08-13 09:17
@jancborchardt is there some kind of mobile detection ? I thought we were using media queries

**Comment by jancborchardt** [comment] 2015-08-13 09:19
Yeah, everything below 768px. Try in portrait mode.
Besides that, this is fixed in master with the new actions menu.

Or I’m not sure what you are talking about @Bullnados please be more clear and supply screenshots. :)

**Comment by Bullnados** [comment] 2015-08-13 21:22
Here is a screenshot, but not made by tablet, just minify browser.
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/9261799/ab4838ae-4210-11e5-90c5-4e1de776b735.PNG)
On tab u cant hover to see share, garbage, download symbol. When u click in red marked area the file/folder is deleted immediately. But perhaps you wont do(delete) anything. just make symbols visible. Hope it's clearer now.
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/9261858/10ddb95a-4211-11e5-9749-4316a380b707.PNG)
Yes you are If the new action menu symbol is visible all time, than it is solved.

**Comment by jancborchardt** [comment] 2015-08-13 21:43
Much like https://github.com/owncloud/core/issues/18256, this is fixed in latest master (and with 8.2) via https://github.com/owncloud/core/pull/17709

Also this is a duplicate of https://github.com/owncloud/core/issues/12081 – next time please search for existing issues to make our life easier. :)

**Closed by jancborchardt** 2015-08-13 21:43 UTC
Labels: bug, needs info

**Comment by Bullnados** [comment] 2015-08-13 21:57
OMG again -.-.Sorry for that. For me it is hard to find the correct search keys.

**Comment by jancborchardt** [comment] 2015-08-13 23:09
No worries – it takes some time to get used to the issue tracker. :)

**Comment by jancborchardt** [comment] 2015-08-13 23:10
Don’t let that demotivate you – if you notice something off in the design please always report it!

And join us on IRC in #owncloud-design (freenode IRC)

**Comment by LukasReschke** [comment] 2015-08-13 23:17
I tend to use Google with `site:github.com/owncloud/core/issues term` way better than the embedded GitHub search.
