### ISSUE TITLE
Enabled email field on user management page not present after browser refresh.

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13612] opened 2015-01-22 18:16 UTC
## Steps to reproduce

1. Install owncloud
2. Navigate to users page
3. Click on setting gear on lower left panel
4. enable user emails - email field is now present
5. refresh the browser
6. email field is gone

### Expected behaviour

Email field should remain

### Actual behaviour

Email field gone.

### Browser

Chrome
Firefox

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by LukasReschke** [comment] 2015-01-22 18:17
That's a dupe of about 5 other issues. Let me search them. On my way home atm.

**Closed by LukasReschke** 2015-01-22 18:17 UTC

**Comment by LukasReschke** [comment] 2015-01-22 18:18
https://github.com/owncloud/core/issues/12727

**Comment by jnfrmarks** [comment] 2015-01-22 18:19
@LukasReschke  I guess I should have looked first :)
