### ISSUE TITLE
Can't update Owncloud

### ISSUE THREAD

**Issue by andre-dierker** [owncloud/core#20965] opened 2015-12-05 09:37 UTC
Hi,

![selection_008](https://cloud.githubusercontent.com/assets/6938843/11607143/b4a07536-9b3b-11e5-9f1f-6274839a506a.png)

I can click on update but nothing happens. 

Expected behaviour
Actual version should be shown, an available new version too.

Actual behaviour

Server configuration

Operating system:

Debian Jessie Linux metapixl.com 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64 GNU/Linux

Web server:

nginx version: nginx/1.9.6

Database:

10.0.22-MariaDB-0+deb8u1 (Debian)

PHP version:

PHP 5.6.14-0+deb8u1 (cli) (built: Oct 4 2015 16:13:10) Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

ownCloud version: (see ownCloud admin page)

ownCloud 8.2.0 (stable)

Updated from an older ownCloud or fresh install:

fresh install with old data after broken update (not able to activate apps)

List of activated apps:

`Enabled:

activity: 2.1.3
calendar: 0.8.0
contacts: 0.5.0.0
encryption: 1.1.0
files: 1.2.0
files_external: 0.3.0
files_pdfviewer: 0.7
files_sharing: 0.7.0
files_texteditor: 2.0
files_trashbin: 0.7.0
files_versions: 1.1.0
files_videoviewer: 0.1.3
firstrunwizard: 1.1
gallery: 14.2.0
news: 6.0.6
tasks: 0.8
templateeditor: 0.1
updater: 0.6 Disabled:
documents
external
files_locking
notifications
provisioning_api
user_external
user_ldap`

"system": { "instanceid": "oc0dfc8eac9b", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "datadirectory": "\/home\/owncloud\/data", "overwrite.cli.url": "\/cloud", "dbtype": "mysql", "version": "8.2.0.12", "dbname": "oc6", "dbhost": "127.0.0.1", "dbtableprefix": "oc_", "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "memcache.local": "\\OC\\Memcache\\APCu", "asset-pipeline.enabled": true, "installed": true, "enable_previews": true, "theme": "", "maintenance": false, "forcessl": true, "trusted_domains": [ "6bq.de", "www.6bq.de" ], "mail_smtpmode": "smtp", "appcodechecker": false, "mail_from_address": "cloudmaster", "mail_domain": "6bq.de", "filesystem_check_changes": 1, "secret": "***REMOVED SENSITIVE VALUE***", "loglevel": 0, "app.mail.server-side-cache.enabled": true, "mail_smtpauthtype": "PLAIN", "mail_smtpauth": 1, "appstore.experimental.enabled": true, "mail_smtphost": "localhost", "mail_smtpname": "***REMOVED SENSITIVE VALUE***", "mail_smtppassword": "***REMOVED SENSITIVE VALUE***", "trashbin_retention_obligation": "auto" }

Are you using external storage, if yes which one: local/smb/sftp/...

no

Are you using encryption: yes/no

yes

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

no

LDAP configuration (delete this part if not used)

**Comment by RealRancor** [comment] 2015-12-05 10:19
@andre-dierker Duplicate of https://github.com/owncloud/updater/issues/184

Disable the asset-pipeline for now should fix this until the next oC version is released.

**Closed** 2015-12-05 10:26 UTC
