### ISSUE TITLE
Federated Share have the "share" permission by default

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/core#22122] opened 2016-02-04 11:18 UTC
On the mobiles we are developing the Federated Share UX.
I am using a server:
{"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

And sharing the file with a server:
{"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":""}

When I create the Federating share the permission that have by default it is "19". Also I can edit the permissions and grant all the permissions: "31".

Is it right? Can I change the permissions and put an higher one on a Federated Share?

Following the Doc as default a Federated Share should have the "Share" permission (16) (https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/federated_cloud_sharing_configuration.html) but If it have a 19 it is because it have that permission.

**Comment by rullzer** [comment] 2016-02-04 13:50
This is most likely beacuse you are sharing a file. Files can't have DELETE or CREATE permissions (as they mean nothing). So the default of 31 will be 19 for files.

Also granting full permissions *should* give an error. But there might be some code paths that pass it.

Anyway... it comes down to that for files DELETE and CREATE permissions are meaningless ;)

**Comment by javiergonzper** [comment] 2016-02-05 08:30
You are right, we are doing something wrong related with the permissions.
So @rullzer a Federated Share can have all the permission so... Is the documentation wrong?:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/federated_cloud_sharing_configuration.html

**Comment by nasli** [comment] 2016-02-05 09:09
In the web if you share with a remote server the permissions for a folder are only can edit as the documentation says, but the api allows more.
![fedcanedit](https://cloud.githubusercontent.com/assets/6570505/12841989/1aec80fc-cbf0-11e5-9b5e-7b8ddd21e9aa.png)
If now user4 share this folder can give full permissions

**Comment by rullzer** [comment] 2016-02-05 09:11
@javiergonzper well it is not a big deal since the permissions are meanlingless... but it is good to provide sane permissions ;)

**Comment by rullzer** [comment] 2016-02-05 09:12
O mmm I don't know about the resharing stuff... I think that is still on the todo of @schiesbn ?

**Comment by SergioBertolinSG** [comment] 2016-02-05 09:23
https://github.com/owncloud/documentation/issues/2137

**Comment by PVince81** [comment] 2016-02-05 13:09
I think the sharing permissions from fed shares cannot affect all servers.
A server A cannot technically forbid a server B to reshare. It could give a hint, yes, but cannot forbid.
So far, no such logic is implemented.

Also see https://github.com/owncloud/core/issues/16601 that describes the problems

**Comment by nasli** [comment] 2016-02-08 10:12
Have we reached any conclusions about resharing federated shares?

What it is wrong, the share api that allows all permissions, or the web and doc that said that only can share with can edit permissions?

As @carlaschroder  pointed out there are still a lot of open issues about federated sharing.

On the mobile clients we are currently implementing the federated sharing and need we reach an agreement about what permissions we should allow.

cc: @MTRichards

**Comment by rullzer** [comment] 2016-02-08 10:24
@schiesbn your input please :)

**Comment by MTRichards** [comment] 2016-02-08 12:30
@schiesbn @karlitschek what are the permissions allowed for federated sharing? Need it for mobile and desktop API calls.

**Comment by PVince81** [comment] 2016-02-08 12:52
For sharing, whenever a user initiates a brand new federated share, the user can only pick between "can edit" and "can not edit".

- user1@OCA shares read-only with user2@OCA: user2 can only reshare locally read-only
- user1@OCA shares read-only with user2@OCA: user2 can only reshare with fed sharing read-only
- user1@OCA shares read-write with user2@OCA: user2 can only reshare locally either read-only or read-write
- user1@OCA shares read-write with user2@OCA: user2 can only reshare with fed sharing either read-only or read-write

With federated shares you **cannot** disable resharing because you cannot prevent a remote server to reshare if they wanted to (through hacks)

These are the permissions as presented in the GUI.
Do not use any other permissions using the API. Maybe we need to lock down the API to prevent using other permissions and avoid potential mistakes or unpredictable behavior ? @rullzer

**Comment by rullzer** [comment] 2016-02-08 13:11
I can easily lock down the API... so no sharing permissions for federated shares for now?

**Comment by nasli** [comment] 2016-02-08 13:42
If federated shares always can be resharing, we could show the can share option always enabled in the GUI without being able to modify it to give the user this information

**Comment by schiesbn** [comment] 2016-02-08 13:42
I think the summary from @PVince81 is correct.

We can't control re-sharing on a different server. So it doesn't make sense to allow/forbid it. At the end a federated share is a webdav mount which can either read-only or read-write (while read-write also allows you to delete files if it was a shared folder). That's the only permission you can set in the web interface and the OCS API should probably also block all the other permissions... While thinking about it. This is probably something the federated share provider should check and throw an exception if the user tries to set a permission which isn't supported.

**Comment by nasli** [comment] 2016-02-10 08:06
@PVince81, @schiesbn  For federated sharing folders you can not edit sub options of can edit? As happens for normal shared files?

**Comment by PVince81** [comment] 2016-02-10 08:08
When creating federated shares in the share panel in the web UI, you only have a check box "can edit". Nothing else. So it's only "can edit" or "can not edit".

**Comment by PVince81** [comment] 2016-02-12 09:29
Do we want to block the other permissions in 9.0 or 9.1 ? If not, we might need to verify/test that weird permissions don't cause unpredictable behavior. @rullzer @schiesbn @cmonteroluque 

The clients should, for now, only set the allowed permissions.

**Comment by rullzer** [comment] 2016-02-12 09:34
I could prepare an almost trivial patch to the OCS Share API that disallows setting the share permissions on federated shares... but since we have no uniform share handling (incomming federated shares are just webdav mount etc) yet that won't change that much I think.

But up to you all if that is something we want...

**Comment by schiesbn** [comment] 2016-02-16 11:23
@rullzer maybe it makes sense to set the share permission, even if we don't use it. But it reflects the current state and  if we want to use it in the future it might be easier if the database already contain the correct permission to avoid large migration steps.

**Comment by rullzer** [comment] 2016-02-17 19:44
Ok I had a look into older owncloud versions. 8.2 and 8.1 both do not set reshare permissions in the webUI.

8.1: https://github.com/owncloud/core/blob/stable8.1/core/js/share.js#L498
8.2: https://github.com/owncloud/core/blob/stable8.2/core/js/shareitemmodel.js#L230
master: https://github.com/owncloud/core/blob/master/core/js/shareitemmodel.js#L158

So there is no behavior change actually.

The big change here is that now we have multiple clients (ios/andorid/desktop) using the OCS Share API. And in the API we don't block this. Because as explained above there is no real way to block this on other instances.

So for now I think it would be best if the clients acted the same as the webinterface. So by default share with READ | WRITE | UPDATE (7). And do not show the `can share` checkbox for federated shares. Just to have uniformity across the devices.

@MTRichards this was the issue you mentioned this afternoon right?

**Comment by MTRichards** [comment] 2016-02-17 21:17
@rullzer yep - this was the issue I mentioned. 

Agreed, uniformity is the goal in the short term. 
web = desktop = mobile

In the long term, we will need to implement some form of sharing permissions attribute among federated servers, because seamless is the goal - and if one kind of sharing is different than another, it will create problems as you get more and more federated shares.

For now though, the share API should return the correct sharing rights and the clients should just follow what the API says. This allows us the ultimate in flexibility for the future. This is a bug if this is not the case.

So, the question: What should the API return?
The API should return what the web ui allows or does not allow at this time. So, for example, it should not allow resharing for federated shares at this time.

**Comment by rullzer** [comment] 2016-02-18 09:20
I had a chat with @schiesbn about this.

Basically the webUI did not (and does not currently) allow setting of reshare permssions on federated shares. Is because we don't check them on the receiving instance. This is because it is actually a webdav mount on the receiving server and the initating server has no control weather that mount is shared with others again.

@MTRichards we fully agree that we want more seamless intergration of federated shares. But the fact of the matter is they are different shares. And your serverA has no control over what serverB choses to do with its incomming federated shares. Of course this does not mean we can't in the future tell serverB the initatior does not want you to reshare. And then if I share something with a friend I just have to trust that he is not running a rougue server.

@MTRichards the API you speak of. Basically it isn't there. We have no way to ask the server give me the max permissions I can share this file of this share type. The behaviour of the web is hard coded into the webUI at the moment. But such a function would be good to have for the v2 of the share API. https://github.com/owncloud/core/issues/21798#issuecomment-185619002

Anyway. Long story short. It does not matter. If you set the resharing permissions on a federated share or not. The receiving server can always reshare it. At least that is how it currently is. That is why it was chosen on the webUI to not show the resharing checkbox. To not give the impression that if this was removed the share could not be reshared.

**Comment by javiergonzper** [comment] 2016-02-18 09:24
@rullzer so on the mobile we have to do the same. Hardcoded the behaviour as the Web UI.

**Comment by PVince81** [comment] 2016-02-18 09:27
@rullzer did you check whether the "oc:permissions" Webdav property of the root of the fed share contains anything regarding reshare permissions ?

**Comment by rullzer** [comment] 2016-02-18 09:29
@javiergonzper: @schiesbn suggested an approach that actually makes more sense to me. We should show both. 'can edit' and 'can share'. But make the 'can share' always checked and not editable. Since that is the actual situation.

**Comment by rullzer** [comment] 2016-02-18 09:29
@PVince81 I did not (will do)... but that still does not give you any guarantee that your data won't be reshared

**Comment by PVince81** [comment] 2016-02-18 09:31
Yes, this is not a guarantee. It is just a "suggestion" for the target server to not show the sharing options in the various UIs

**Comment by PVince81** [comment] 2016-02-18 10:09
Had a chat with @rperezb @nasli @javiergonzper @schiesbn and @rullzer, here is the summary:

#### Permissions sent:
- share from OCA to OCB sends the permissions "1" for read-only and "7" for edit (there are no share permissions sent there). This is the case for 8.2.2 and 9.0 in the web GUI.
- all clients must send the same permissions regardless of OC versions for now (1 or 7)

#### Target server does not respect permissions:
- in OC <= 9.0: even though the permissions in the database do not allow resharing, the code still let people reshare. This was by design originally and we will reconsider in 9.1.
- in OC 9.0: the UI does NOT allow resharing any more, this is a regression and is inconsistent with the previous behavior.

#### Short-term solution
Since we don't have much time left, the solution is as follows:
- fix the OC 9.0 regression to behave like 8.2.2. Basically, always allow resharing of fed shares like it did before (separate ticket)
- all clients only send the edit permissions, either "1" (read-only) and "7" (read-write), but no sharing permission
- raise tickets for future work (see below)

#### Future
In the future, we look into this:
- in 9.1, work on making the target server properly respect the share permissions for fed shares, on ALL levels (API, GUI, etc), might need API additions to make clients aware of allowed reshare permissions (we'll need to continue the discussion from https://github.com/owncloud/core/issues/16601)
- in 9.1: introduce a new checkbox "can share" in fed share reshares
- also introduce this checkbox in all clients

CC @MTRichards @cmonteroluque

**Comment by PVince81** [comment] 2016-02-18 10:11
@rperezb can you post a reference to the client tickets ?

**Comment by PVince81** [comment] 2016-02-18 10:16
Raised https://github.com/owncloud/core/issues/22495 for 9.1 to consider preventing reshares if the source fed share said it wishes that.

**Comment by PVince81** [comment] 2016-02-18 10:24
@rullzer is investigating the regression

**Comment by rperezb** [comment] 2016-02-18 11:33
- [ ] Client: https://github.com/owncloud/client/issues/4481
- [ ] iOS: https://github.com/owncloud/ios/issues/543
- [ ] Android: https://github.com/owncloud/android/issues/1376

**Comment by MTRichards** [comment] 2016-02-18 12:57
Ok.

**Comment by rullzer** [comment] 2016-02-18 12:59
Regression fix is in #22503 so then resharing behaviour should be the same for as in 8.2 again.

**Comment by rullzer** [comment] 2016-02-22 11:33
I just noticed that we are actually inconsitent here.

We never set delete permissons for federated shares... it is either 7 (READ+CREATE+UPDATE) or 1 (READ) (for folders this is). However we do allow deleting files/folders inside our fedearated share.

What I propose. All the clients from now on start sending DELETE permissions as well (if can edit is selected). This does not affect the current server code but will prevent chaning the client code later.

And then in 9.1 we look into a migration path for existing shares.

@schiesbn @PVince81 agreed?

**Comment by PVince81** [comment] 2016-02-22 12:37
Sounds good.

**Comment by javiergonzper** [comment] 2016-02-22 13:05
We can do it. Is it definitive?
#define k_defaul_file_remote_share_permission 11
#define k_defaul_folder_remote_share_permission 15

Right?

**Comment by rullzer** [comment] 2016-02-22 13:48
>#define k_defaul_file_remote_share_permission 3
>#define k_defaul_folder_remote_share_permission 15

You can't share single files with delete permissions. So it only changes for the folders.

@javiergonzper Lets wait for @schiesbn to agree as well ;)

**Comment by javiergonzper** [comment] 2016-02-22 13:53
Ok, thank you @rullzer :wink:

**Comment by schiesbn** [comment] 2016-02-22 14:07
discussed it also with @rullzer and agree with this summary https://github.com/owncloud/core/issues/22122#issuecomment-187133309. This is a good way forward

**Comment by rullzer** [comment] 2016-02-22 14:09
@javiergonzper so yes please implement that...

**Comment by javiergonzper** [comment] 2016-02-22 14:10
:+1:

**Comment by rullzer** [comment] 2016-03-02 07:50
I'm not sure we can properly fix this for 9.0.1. I would propose to leave it as is for now since it works properly (as it did in 8.2.x etc). And to 'really' fix this for 9.1. Since fixing it would require chaning the permissions on the webdav endpoint we expose. And when we do that we might break a lot of stuff. 
@schiesbn what do you think?

@PVince81 @cmonteroluque fyi

**Comment by PVince81** [comment] 2016-03-02 09:16
Yeah, I think that's what we talk about already on IRC. Keep 9.0 compatible and make the bigger changes in 9.1.

**Comment by nasli** [comment] 2016-06-22 08:53
Permissions granted have changed? What it is the current status? 
For federate shares was:
default_file_remote_share_permission 3
default_folder_remote_share_permission 15
should we add share permission by default too? and in this case, should we allow the user to disable the share permission?

@rullzer, @PVince81

**Comment by PVince81** [comment] 2016-06-22 15:53
@nasli in the web UI of 9.1 the user can now choose to disable reshare permissions so it would make sense if the clients allowed that too.

Need to check how OC < 9.1 behaves if the user removes the default permission.
@rullzer did we enforce anything in previous versions ? I guess not.

@nasli also see https://github.com/owncloud/core/issues/24868#issuecomment-227776832
For the 9.1 entries the permissions reflect from what was chosen in the web UI.
The web UI of 9.1 now has these checkboxes for federated share:
   - can share
   - can edit

**Comment by PVince81** [comment] 2016-06-22 15:54
![fed-canshare](https://cloud.githubusercontent.com/assets/277525/16273560/63f08e64-38a2-11e6-98d0-bf59f14ec48d.png)

**Comment by PVince81** [comment] 2016-06-22 16:06
For federated shares nothing is enforced in OC < 9.1. So the client can send whichever permissions and they will be accepted and stored.

However for link shares, OC < 9.1 will either pick 1 or 7 instead of taking the permissions passed.

Since we're talking only about fed shares (not link shares), then the client should take the user's input and compute the correct permissions:
- fed share cannot edit, cannot share: 1
- fed share cannot edit, can share: 17
- fed share can edit, cannot share: 15
- fed share can edit, can share: 31

Please note that if the receiver of the fed share is OC < 9.1, it will ignore the "can share" permission.
Only OC 9.1 is a "good citizen" and respects this permission.

**Comment by PVince81** [comment] 2016-06-23 11:59
@nasli @ckamm let's check your defaults again:

- desktop: https://github.com/owncloud/client/issues/4996#issuecomment-227972081: 1 (readonly) or 3 (for files, read+update) or 15 (for folders, read+update+create+delete).
- mobile: https://github.com/owncloud/core/issues/22122#issuecomment-227682668: 3 (for files, read+update) or 15 (for folders, read+update+create+delete)

So let's do as follows in both clients, for consistency:
- when talking to OC < 9.1, keep everything as is, same permissions and no reshare as before
- when talking to OC >= 9.1, add an additional "can share" permission/checkbox in the UI and enable it by default (the web UI does that too)

This matches what @ckamm said here https://github.com/owncloud/client/issues/4996#issuecomment-227972081

**Comment by nasli** [comment] 2016-06-23 13:31
👍 Thanks for the resume @PVince81

**Comment by PVince81** [comment] 2016-06-24 15:38
Closing ticket since there is nothing to do on the server side

**Closed by PVince81** 2016-06-24 15:38 UTC
Labels: discussion, feature:federated-cloud-sharing, sev3-medium
