### ISSUE TITLE
Admin email not saving

### ISSUE THREAD

**Issue by bvkuik** [owncloud/core#15318] opened 2015-03-30 18:37 UTC
### Steps to reproduce
1. Install OwnCloud 8 via web installer
2. Go to admin page
3. Fill in email adress

### Expected behaviour
The "saving" label should change to "saved" after some time and the new email address should be saved in the database.

### Actual behaviour
The "saving" label did not change and the admin email address is not saved.
Moreover, the form of the admin email address has id 'lostpassword', which could be a part of the problem.

### Server configuration
**Operating system**: Not sure, hosted on external hosting party

**Web server:** Apache

**Database:** mySQL

**PHP version:** 5.4.34

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** Files, activity, images

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari, Chrome

**Operating system:** OSX

#### Browser log
Failed to load resource: index.php/settings/users/admin/mailAdress

**Comment by DeepDiver1975** [comment] 2015-03-30 19:28
@nickvergessen can you please have a look? master and stable8 please - thx

**Comment by nickvergessen** [comment] 2015-04-01 09:35
@bvkuik which admin page do you mean? the user list, or the admin "Email Server" settings page:
![email-settings](https://cloud.githubusercontent.com/assets/213943/6938343/06273c1a-d863-11e4-980d-98a98c49e93f.png)

**Comment by bvkuik** [comment] 2015-04-01 09:57
The admin page when clicking on the user at the top right, then choosing Administrator. Do you know what page I mean?

**Comment by nickvergessen** [comment] 2015-04-01 09:58
Can you post a screenshot of the section you are talking about?

**Comment by bvkuik** [comment] 2015-04-01 10:00
Unfortunately I do not have access at the moment, will post when I have!

**Comment by bvkuik** [comment] 2015-04-01 16:36
![email-field](https://cloud.githubusercontent.com/assets/9094723/6946022/c84ccbb8-d89d-11e4-9f33-7a78c4616ee8.png)
![code-email-field](https://cloud.githubusercontent.com/assets/9094723/6946021/c84bc22c-d89d-11e4-8337-8b81508979ea.png)

The first image shows the empty field after set up, when filling in my email the label 'Saving ...' appears but it never saves. Second image of DOM for this field.

**Comment by Xenopathic** [comment] 2015-04-01 18:01
Cannot reproduce on master or stable8

**Comment by nickvergessen** [comment] 2015-04-02 06:23
Me too.

**Comment by MorrisJobke** [comment] 2015-04-08 10:31
@bvkuik Is there still the same error message in your log?

> Failed to load resource: index.php/settings/users/admin/mailAdress

**Comment by PVince81** [comment] 2015-04-27 13:40
It should be "mailAddress" with two "d", not a single one.
@bvkuik can you confirm that the error you are seeing only has a single "d" ?

**Comment by bvkuik** [comment] 2015-04-27 13:44
@PVince81 It says mailAddress, with two "d". I must have typed that wrong, sorry for the confusion

**Comment by nickvergessen** [comment] 2015-04-27 14:00
@bvkuik can you answer the question of @MorrisJobke

**Comment by bvkuik** [comment] 2015-04-27 14:02
@nickvergessen @MorrisJobke Yes, the error still is there

**Comment by DeepDiver1975** [comment] 2015-05-04 09:48
@bvkuik which browser are you using? any errors in the browser error console?

**Comment by PVince81** [comment] 2015-08-03 15:44
Could it be a misunderstanding of the user interaction ? See https://github.com/owncloud/core/issues/17789

**Comment by nickvergessen** [comment] 2015-08-10 14:54
Required information missing, closing.
Feel free to reopen with the necessary answers.

**Closed by nickvergessen** 2015-08-10 14:54 UTC
Labels: bug, needs info

**Comment by agustaf9** [comment] 2015-08-23 00:30
It happened to me when I autofilled the form (using the chrome suggestion).

**Comment by koosmaat** [comment] 2015-11-29 18:50
Please help me too, i have also the problem that i can not save the email adress. also when i make a new user i can not save the email adress

**Comment by onewaypub** [comment] 2016-11-06 11:10
Same here cannot same the password anymore. I migrated from 9.0.4 to 9.1.1. Now all email adresse shown in the gui are "admin" and cannot changed anymore. Owncloud say "saving..." but go out of the page an step in again the value is "admin". Also press enter don't solve the problem

**Comment by RealRancor** [comment] 2016-11-06 14:18
@onewaypub Instead of pushing a nearly one year old and closed issue create a new issue if you're still seeing such problems. When doing so make sure that you're filling out the issue template shown when creating a new issue.
