### ISSUE TITLE
Content of skeleton file overwrites the content of shared file with same name 

### ISSUE THREAD

**Issue by bhawanaprasain** [owncloud/core#35787] opened 2019-07-09 09:40 UTC
### Steps to reproduce
1.Create two users ``user1`` and ``user2`` with skeleton file ``lorem.txt`` .
2.Login into the webUI as user ``user2`` and change the content of the  file ``lorem.txt`` to ``edited original content``.
3. Share the file ``lorem.txt`` with user ``user1``
4.Login into the webUI as user ``user1`` and view the content of file ``lorem.txt``

### Expected behaviour
File ``lorem.txt`` of user ``user1`` should have edited content .
### Actual behaviour
When file is viewed using the text editor in webUI user ``user1`` gets the original content of the skeleton file.
When file is viewed after downloading , ``lorem.txt`` has content from original skeleton file but the length of  the file is equal to the length of edited file .

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:**Apache

**Database:** MySql

**PHP version:**7.2

**ownCloud version:** ownCloud	11.0.0 prealpha (git)

**Updated from an older ownCloud or fresh install:**fresh install

**Where did you install ownCloud from:**git

### Client configuration
**Browser:**Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by kiranparajuli589** [comment] 2019-11-26 04:26
I'll close this as duplicate of #16450

**Closed by kiranparajuli589** 2019-11-26 04:26 UTC
Labels: bug
