### ISSUE TITLE
File Exists on Server But Not Displayed

### ISSUE THREAD

**Issue by TehTotalPwnage** [owncloud/core#16558] opened 2015-05-25 16:05 UTC
I had a bit of an issue while sorting out my music library. So every song in my music library exists in 4 folders that exist in one larger folder like so:

Main Music Folder
|-Sub Folder 1
|-Sub Folder 2
|-Sub Folder 3
|- Sub Folder 4

I tried renaming the main music folder, which resulted in sub folders 1 and 4 suddenly disappearing, taking away about half of my music library. However, if I use a file navigator as superuser on Ubuntu (Nautilus, Dolphin, etc.) and browse to the content directories inside ownCloud, I can still see Sub Folders 1 and 4 sitting there just fine. However, they do not appear on my client or the web interface. This is annoying as it means I have to manually move back my music folders and manually reedit the permissions.

As far as I know, this is an issue on the latest ownCloud (8.0.3).

**Comment by hoho508** [comment] 2015-05-26 07:13
#13948 should be able to improve your situation

**Comment by PVince81** [comment] 2015-05-26 08:39
Duplicate of #13391, but as you said https://github.com/owncloud/core/issues/13948 should improve the situation

**Closed by PVince81** 2015-05-26 08:39 UTC
