### ISSUE TITLE
Disable federated cloud sharing access for LDAP users

### ISSUE THREAD

**Issue by tmaex** [owncloud/core#21728] opened 2016-01-14 16:15 UTC
The bug works like this:

- user "data" shares "folder" with "ldap_group"
- user "ldap_user" is member of "ldap_group"
- user "ldap_user" shares "folder" with "federated@cloud.sh"
- user "ldap_user" is no more member of "ldap_group"
- user "federated" is **still** able to manipulate "folder"

Interessting addition:

- user "data" unshares "folder"
- user "federated" is no more able to manipulate "folder"

**Comment by karlitschek** [comment] 2016-01-14 21:20
@schiesbn What do you think?

**Comment by PVince81** [comment] 2016-01-15 10:45
CC @rullzer 

Maybe the original share wasn't deleted/invalidated properly.

**Comment by tmaex** [comment] 2016-01-15 11:44
Additional info:

stuff from "federated" changed after "ldap_user" is no more in "ldap_group" will be displayed as "from deleted user"

**Comment by PVince81** [comment] 2016-02-12 13:44
@rullzer @schiesbn please have a look. With a bit of luck this might be fixed in 9.0 already ?

**Comment by rullzer** [comment] 2016-02-12 19:37
I did not check it yet but the situation as describe is actually the behaviour we want in 9.0. with the new resharing behaviour.

I'll double check if this is happening as expected.

**Comment by rullzer** [comment] 2016-02-15 20:01
I think this is fixed now... but my ldap foo is very under devloped...

@MorrisJobke @blizzz could one of you verify my findings?

**Comment by MorrisJobke** [comment] 2016-02-15 21:46
> I did not check it yet but the situation as describe is actually the behaviour we want in 9.0. with the new resharing behaviour.

Correct. This is how it should work in 9.0 - do we want to fix this in 8.2 nevertheless?

**Comment by schiesbn** [comment] 2016-02-16 10:39
I just tried it with normal link shares and with local users/groups. If I remove a user from a group the link share gets deleted correctly in 8.2. So we could probably adjust the code to also remove federated shares... But I didn't found the code yet.

**Comment by rullzer** [comment] 2016-02-19 10:15
@cmonteroluque moved to 8.2.3 after talking to @PVince81 since the issue is fixed on 9.0

**Comment by cmonteroluque** [comment] 2016-02-19 20:45
@rullzer great, thanks

**Comment by rullzer** [comment] 2016-03-15 15:59
@blizzz how/when does the ldap_user app notify the server if group membership has changed? I don't see the {pre,post}_deleteUserFromGroup events geting called.

**Comment by blizzz** [comment] 2016-03-15 17:02
For the record:

```irc
<rullzer> Blizzz: how does the ldap server notify ownCloud that a user has been removed from a group?
<rullzer> do I need to do anything special for that?
<Blizzz> rullzer: it does not. when pull memberships regurlarly with a background and compare what we had before.
<rullzer> Blizzz: are all te proper hooks emitted then? like pre_deletefromgroup (and/or) post_deletefromgroup?
<Blizzz> rullzer: just post_*
<Blizzz> rullzer: do we need pre_?
<Blizzz> https://github.com/owncloud/core/blob/master/apps/user_ldap/lib/jobs.php#L95 and line 102
<rullzer> Blizzz: nah post is fine...
```

**Comment by rullzer** [comment] 2016-03-15 19:51
Mmmm I actually have no idea why this is not happening... 

https://github.com/owncloud/core/blob/stable8.2/lib/private/share/hooks.php#L167 *should* be called when a user is removed from a group. This select the group share and then deletes all the children that are shared by the user that is removed in https://github.com/owncloud/core/blob/stable8.2/lib/private/share/helper.php#L83 

So it should just delete the share from the oc_share table. And then the remote server should on next access notice this and delete the share as well..

**Comment by rullzer** [comment] 2016-03-15 19:52
@blizzz could you try to reproduce the steps here. Because my ldap fu is not good enough to properly trigger the post_removefromGroup hook.

**Comment by rullzer** [comment] 2016-03-18 11:14
Aaah ok so I finally managed to trigger this properly.
And this problem is the same without the federated share... (so just to a regular user)... which makes debugging a bit easier...

**Comment by rullzer** [comment] 2016-03-18 11:42
Nevermind a glitch...

**Comment by rullzer** [comment] 2016-03-18 11:43
Ok so from what I found this all works as expected.
It is important to note that you need to wait for the ldap cache to expire. Else you won't see the modifcations.

But the `post_removeFromGroup` hook is emitted succesfully. And the federated share is also cleanedup.

Now on the remote server the folder is still shows. But it is removed the moment you try to access it,

**Comment by rullzer** [comment] 2016-03-18 11:44
@tmaex can you please verify with the 8.2 branch?

**Comment by cmonteroluque** [comment] 2016-04-14 15:26
update?

**Comment by PVince81** [comment] 2016-06-01 15:21
@rullzer do you mean you tried it on stable8.2 and it worked fine ? Is there a released version that @tmaex could use for testing or is the fix only on stable8.2 ?

**Comment by tmaex** [comment] 2016-06-06 21:32
Updated to 9.0.2:
Now federated@cloud.sh shows up in data's share-menu, so the problem is solved.

**Comment by rullzer** [comment] 2016-06-08 06:39
@PVince81 yes I verified on stable8.2. Since @tmaex problem is fixed and I have no way to reproduce => close

**Closed by rullzer** 2016-06-08 06:39 UTC
Labels: bug, feature:federated-cloud-sharing, feature:sharing, sev2-high
