### ISSUE TITLE
Unable to login using LDAP Credentials

### ISSUE THREAD

**Issue by mzaian** [owncloud/core#25588] opened 2016-07-24 09:27 UTC
After upgrading from 9.0.3 to 9.0.4 my users are unable to login using their LDAP credentials.

The Apache server error log files shows the following repeatedly :-

PHP Fatal error:  Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::composeAndStoreDisplayName() in /var/www/owncloud/apps/user_ldap/user_ldap.php on line 386

Server configuration

Ubuntu 14.04.4 LTS

Web server:
Apache2
Database:
MYSQL
PHP version:
PHP 5.5.9-1ubuntu4.16
ownCloud version: (see ownCloud admin page)
9.0.4 Stable
Updated from an older ownCloud or fresh install:
Updated since version 5.*

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - announcementcenter
  - dashboard
  - documents
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - videos

Configuration:-

{
    "system": {
        "instanceid": "oc2a931c8470",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": "4",
        "log_rotate_size": 104857600,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "MY-DOMAIN-REMOVED"
        ],
        "share_folder": "\/Shared",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "owncloud-test",
        "mail_domain": "MY-DOMAIN-REMOVED",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "auto",
        "updatechecker": false,
        "appstore.experimental.enabled": false
    }
}

Are you using encryption: yes/no
No

**Comment by RealRancor** [comment] 2016-07-24 09:36
Looks to me like a duplicate of https://github.com/owncloud/core/issues/23248

**Comment by mzaian** [comment] 2016-07-24 09:42
Just to mention i think its totally different because i do not have owncloud news app enabled nor android users. Login is not working for LDAP users url or desktop client.

**Comment by DeepDiver1975** [comment] 2016-07-25 07:44
> Looks to me like a duplicate of #23248

yes

**Closed** 2016-07-25 07:44 UTC

**Comment by DeepDiver1975** [comment] 2016-07-25 07:53
Please help testing - https://github.com/owncloud/core/pull/25598

**Comment by philhenri34** [comment] 2016-09-16 15:35
owncloud 9.0.4 same issue after UG 8.2.7 To 9.0.4
**#sudo -u apache php ldap:search *cam**
is OK for the ldap user cam
but for the ldap user bor
**#sudo -u apache php ldap:search *bor**
it returns this issue : PHP Fatal error: Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() in /var/www/owncloud/apps/user_ldap/user_ldap.php on line 386
I guess it was a issue somewhere in the database mysql. The user bor said me, he used an old owwncloud client (1.7 ?) 
First, I delete the user 
#sudo -u apache php occ ldap:check-user d0b57bd4-...
#sudo -u apache php occ user:delete d0b57bd4-...
Nothing's changed
To debug,I log the query in mariadb (general_log=1)
And I delete entry related to the user in tables : 
DELETE * FROM `oc_ldap_user_mapping` WHERE ldap_dn like '%bor%'
DELETE * FROM `oc_preferences` WHERE userid = 'd0b57bd4-...'
DELETE * FROM `oc_ldap_group_mapping` WHERE ldap_dn like '%bor%'
DELET * FROM `oc_share` WHERE uid_owner = 'db53b542-...'  : this was the issue. This user db53b542-... was sharing a file with him, and after deleting ths share, the ldap::search return his displayName
