### ISSUE TITLE
Upgrade App does not check for versioning compatibility before altering system.

### ISSUE THREAD

**Issue by Spereicle** [owncloud/core#22302] opened 2016-02-10 23:45 UTC
When using the built in Upgrade App, the App may proceed with an upgrade - including making system and database changes - without confirming upgrade #versioning compatibility; the result of which can be catastrophic loss of data and inability to login.

For more information, see this thread: 
https://github.com/owncloud/core/issues/22300

A solution offering would be an ownCloud or github hosted lookup table which the app could access autonomously to determine appropriate upgrade path and versioning compatibility

**Comment by RealRancor** [comment] 2016-02-11 05:23
Duplicate of https://github.com/owncloud/appstore-issues/issues/4

**Closed** 2016-02-11 08:51 UTC
