### ISSUE TITLE
Start Update button does not work in Chrome running under Windows

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13702] opened 2015-01-27 08:46 UTC
### Steps to reproduce

1. Update Owncloud to 6 to 7 version
2. Update to 7.0.3 to 8.0.0 beta version in Windowsserver and with Chrome as browser
3. Click on Start Update button

### Expected behaviour
Update should start

### Actual behaviour

Start Update button does not work and there's also a small tiny text "owncloud" over the owncloud logo as it is shown in the screenshot attached.

### Server configuration
**Operating system**:
WindowsServer2008

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Updated from 7.0.3 to 8.0.0 beta

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome
![captura de pantalla 2015-01-27 a las 9 29 32](https://cloud.githubusercontent.com/assets/10596560/5915649/9b117288-a608-11e4-95a9-5e2ccf560da0.png)

**Comment by PVince81** [comment] 2015-01-27 10:44
Do you see anything in the Javascript console ? How about owncloud.log ?

**Comment by DeepDiver1975** [comment] 2015-01-27 10:54
OT: that font really looks ugly @jancborchardt

**Comment by nickvergessen** [comment] 2015-01-27 11:09
Just tested on my desktop.
The text does not appear above the logo and the update button works aswell.

**Comment by DeepDiver1975** [comment] 2015-01-27 11:14
@davitol javascript is enabled in your browser? What is the exact version of Chrome you are using? THX

**Comment by davitol** [comment] 2015-01-27 13:40
Yes, javascript is running and Chrome version is 39.0.2171.99 m

**Comment by nickvergessen** [comment] 2015-01-27 13:45
I have `40.0.2214.91 m`
Can you update Chrome and retry?

**Comment by DeepDiver1975** [comment] 2015-01-27 13:51
> Do you see anything in the Javascript console ? How about owncloud.log ?

@davitol can you please have a look at the logs? THX

**Comment by davitol** [comment] 2015-01-27 14:20
GET http://wincloud:8001/index.php/core/js/oc.js?v=28ce40ecb6f6fdbb58184d55debb2e84 503 (Service Unavailable)
js.js?v=28ce40ecb6f6fdbb58184d55debb2e84:1053 Uncaught TypeError: undefined is not a function
jquery.min.js?v=28ce40ecb6f6fdbb58184d55debb2e84:4 GET http://wincloud:8001/core/fonts/OpenSans-Regular.woff 
jquery.min.js?v=28ce40ecb6f6fdbb58184d55debb2e84:4 GET http://wincloud:8001/core/fonts/OpenSans-Bold.woff 
wincloud/:1 GET http://wincloud:8001/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)
firebug-lite.js:24306 'Attr.nodeValue' is deprecated. Please use 'value' instead.


Maybe this info can be useful for you.

**Comment by PVince81** [comment] 2015-01-27 14:28
Hmmm, looks like it's again that weird case where "oc.js" (the generated file) isn't available.
But the upgrade routine should be able to work even when that file isn't loaded.

I checked line "1053" and there is nothing. Maybe it's the line after that: https://github.com/owncloud/core/blob/v8.0.0beta1/core/js/js.js#L1056

@davitol in the Chrome JS console can you type the following:
`oc_config`
and
`typeof(oc_config.session_keepalive)`

I expect the first one to show "undefined" and the second one "false".

**Comment by jancborchardt** [comment] 2015-01-27 14:50
How does the typeface look so ugly? What operating system is this?

**Comment by MorrisJobke** [comment] 2015-01-28 00:09
@jancborchardt Seems like some files aren't loaded ;) So this is just the result of the actual problem.

**Comment by davitol** [comment] 2015-01-28 07:38
@jancborchardt WindowsServer2008
@PVince81 
oc_config
Object {}
typeof(oc_config.session_keepalive)
"undefined"

**Comment by DeepDiver1975** [comment] 2015-01-28 11:33
> How about owncloud.log ?

@davitol

**Comment by nickvergessen** [comment] 2015-01-29 14:38
@PVince81 
> Hmmm, looks like it's again that weird case where "oc.js" (the generated file) isn't available.

I remember that someone had a similar problem in the activity app. Nothing we can do about this?

**Comment by nickvergessen** [comment] 2015-01-29 21:48
Issue appeared in the activity app aswell:
https://github.com/owncloud/activity/issues/185

**Comment by MorrisJobke** [comment] 2015-01-30 00:32
was a blue ticket in activity

**Comment by SergioBertolinSG** [comment] 2015-01-30 09:05
Hi, experienced same screen after 6.0.6->7.0.4->8.0.0beta2, full owncloud.log here:

´´´
{"app":"core","message":"isWebDAVWorking: NO - Reason: HTTP error response. (errorcode 503) (Sabre_DAV_Exception)","level":2,"time":"2015-01-30T08:47:02+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: HTTP error response. (errorcode 503) (Sabre_DAV_Exception)","level":2,"time":"2015-01-30T08:47:11+00:00"}
{"app":"index","message":"OC\\NeedsUpdateException: ","level":4,"time":"2015-01-30T08:52:26+00:00"}
{"reqId":"49794e9af4abf8b31576d4dd42eb5efb","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:06+00:00"}
{"reqId":"49794e9af4abf8b31576d4dd42eb5efb","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:06+00:00"}
{"reqId":"73f3bfb98ff869a13b640ad1946fa774","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 C:\\\\owncloud\\\\lib\\\\private\\\\app.php(77): OC_App::loadApp('activity')\\n#1 C:\\\\owncloud\\\\lib\\\\private\\\\util.php(75): OC_App::loadApps(Array)\\n#2 C:\\\\owncloud\\\\lib\\\\base.php(762): OC_Util::setupFS()\\n#3 C:\\\\owncloud\\\\index.php(28): OC::handleRequest()\\n#4 {main}\",\"File\":\"C:\\\\owncloud\\\\lib\\\\private\\\\app.php\",\"Line\":96}","level":4,"time":"2015-01-30T09:01:10+00:00"}
{"reqId":"4808ee979335bcc1292c9c95ab5d96d7","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:11+00:00"}
{"reqId":"4808ee979335bcc1292c9c95ab5d96d7","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:11+00:00"}
{"reqId":"71cc0290b44c050a6e5c7582bb0a45bb","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:27+00:00"}
{"reqId":"71cc0290b44c050a6e5c7582bb0a45bb","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:27+00:00"}
{"reqId":"5e5de72b1da8fc7b07f7cdf7f5a45aad","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:28+00:00"}
{"reqId":"5e5de72b1da8fc7b07f7cdf7f5a45aad","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:28+00:00"}
{"reqId":"04e9a557e0751b3f98f7f124bd408bf1","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 C:\\\\owncloud\\\\lib\\\\private\\\\app.php(77): OC_App::loadApp('activity')\\n#1 C:\\\\owncloud\\\\lib\\\\private\\\\util.php(75): OC_App::loadApps(Array)\\n#2 C:\\\\owncloud\\\\lib\\\\base.php(762): OC_Util::setupFS()\\n#3 C:\\\\owncloud\\\\index.php(28): OC::handleRequest()\\n#4 {main}\",\"File\":\"C:\\\\owncloud\\\\lib\\\\private\\\\app.php\",\"Line\":96}","level":4,"time":"2015-01-30T09:01:29+00:00"}
{"reqId":"be7ac3a3dc1ee61906c57c07384c488f","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:31+00:00"}
{"reqId":"be7ac3a3dc1ee61906c57c07384c488f","remoteAddr":"fe80::e52b:2444:1a3:e7da%11","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:31+00:00"}
{"reqId":"f1203951011f197423ee8fa5013ec160","remoteAddr":"10.40.40.61","app":"PHP","message":"preg_split() expects parameter 2 to be string, array given at C:\\owncloud\\lib\\private\\app.php#1224","level":3,"time":"2015-01-30T09:01:54+00:00"}
{"reqId":"f1203951011f197423ee8fa5013ec160","remoteAddr":"10.40.40.61","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\owncloud\\lib\\private\\app.php#1227","level":3,"time":"2015-01-30T09:01:54+00:00"}
´´´

**Comment by nickvergessen** [comment] 2015-01-30 09:49
@davitol can you post the full page source of the page on the screenshot, e.g. on https://gist.github.com/
@cdamken @michaelstingl can you please request the full page source of the activity page that is being displayed on the screenshot in the activity issue?

**Comment by SergioBertolinSG** [comment] 2015-01-30 10:45
@nickvergessen (I am using same enviroment as @davitol)
https://gist.github.com/SergioBertolinSG/882169510fc96fe9b892#file-screenshot_source_code

**Comment by nickvergessen** [comment] 2015-01-30 14:51
@SergioBertolinSG @davitol can we get a full screenshot of chrome's development tool, displaying the networking while the page is loading?
Yes, it's going to be a long list, but we need to find out why the things that happen, do happen.

**Comment by SergioBertolinSG** [comment] 2015-02-02 07:38
Yes, two screenshots where there are errors:

![screen shot 2015-02-02 at 08 34 53](https://cloud.githubusercontent.com/assets/9048796/5997094/b148b0d6-aab6-11e4-9ff3-b8f718824b8f.png)
![screen shot 2015-02-02 at 08 35 34](https://cloud.githubusercontent.com/assets/9048796/5997097/b42d8bc8-aab6-11e4-9e71-c2403cb5b5cd.png)

**Comment by DeepDiver1975** [comment] 2015-02-02 07:43
The request for core/js/oc.js returns 503 - W(hy)TF?

**Comment by DeepDiver1975** [comment] 2015-02-02 08:28
setShowPassword is not longer present within OC8 - this shows that the javascript files are reused from the browser cache instead of refetched from the server.

Or the upgrade from 7 to 8 was not perform properly.

**Comment by PVince81** [comment] 2015-02-02 08:35
@DeepDiver1975 I think there might have been recent changes in base.php that somehow blocked oc.js in some situations. I didn't dare tweaking base.php that late when fixing #12204. Nevertheless, that file should be optional during upgrade. During my tests, oc.js also gave 503 and I could upgrade fine.

The real issue is likely to be the part related to `showPassword`. But why would that happen only on this specific environment ?

@SergioBertolinSG what are the enabled apps ?

**Comment by DeepDiver1975** [comment] 2015-02-02 08:37
> During my tests, oc.js also gave 503 and I could upgrade fine.

This is my current observation as well - oc.js not being available doesn't cause the problems in here (still a bug from my pov - but unrelated).

**Comment by DeepDiver1975** [comment] 2015-02-02 08:38
> But why would that happen only on this specific environment ?

is there an issue in generating the css/js version we append to force reload of these files on upgrade?

**Comment by PVince81** [comment] 2015-02-02 08:44
From the screenshot here https://github.com/owncloud/core/issues/13702#issuecomment-72183639 it looks like the version string is appended properly.

@SergioBertolinSG how did you upgrade ? Did you delete all files and keep only "config" and "data" or did you just extract the new tarball over the existing code ? (the latter could cause trouble and is not supported)

**Comment by SergioBertolinSG** [comment] 2015-02-02 08:58
I'm afraid this one was made just extracting the tarball, I am checking the upgrade following those steps, and if it doesn't happen we can close the issue.

**Comment by SergioBertolinSG** [comment] 2015-02-02 09:32
Upgrading keeping only config and data gave same screen.After that I've erased cache from chrome and it has worked.

**Comment by nickvergessen** [comment] 2015-02-02 09:45
well we could append an integer to the urls of js and css,
then everytime maintenance is set or triggered (update available) increase the value.
This would prevent caching to be an issue

**Comment by MorrisJobke** [comment] 2015-02-02 09:57
@nickvergessen This is actually what this hash does ;)

**Comment by DeepDiver1975** [comment] 2015-02-02 09:57
@SergioBertolinSG can you please compare the version number which is added to the js/css file before and after upgrade is triggered? THX

**Comment by nickvergessen** [comment] 2015-02-02 10:10
@MorrisJobke well the problem is, that we would need to update the value, before the versions are updated.

**Comment by PVince81** [comment] 2015-02-02 10:49
Maybe base the value on the version that is in versions.php, not the current version ?

**Comment by DeepDiver1975** [comment] 2015-02-02 11:42
> Maybe base the value on the version that is in versions.php, not the current version ?

the version tag does not change on update ... analyzing

**Comment by DeepDiver1975** [comment] 2015-02-02 11:44
> the version tag does not change on update ... analyzing

well - only the app versions are taken into account - no the core version - https://github.com/owncloud/core/blob/master/lib/private/templatelayout.php#L95

**Comment by MorrisJobke** [comment] 2015-02-02 11:49
@DeepDiver1975 Assign to youself, if you work on this ;)

**Comment by SergioBertolinSG** [comment] 2015-02-02 11:50
Hashes of js and css:
Before upgrade to 7:                                28ce40ecb6f6fdbb58184d55debb2e84 
after deleting cache and upgrading to 8: 84705acfbe1ee680e1821649aecbb569
But the problem happens before the upgrade, in the update screen. After copying files the first hash remains, not sure if that is fine.

**Comment by SergioBertolinSG** [comment] 2015-02-02 13:42
Tested using the branch ```include-core-version-in-js-version-tag``` for the upgrade from 7 to 8, working fine, chrome can upgrade.

**Comment by DeepDiver1975** [comment] 2015-02-02 13:55
> Tested using the branch include-core-version-in-js-version-tag for the upgrade from 7 to 8 without erasing the cache data, working fine, chrome can upgrade.

THX a lot

**Comment by DeepDiver1975** [comment] 2015-02-02 13:55
@SergioBertolinSG can I ask you to comment on https://github.com/owncloud/core/pull/13822 regarding the test status? THX

**Closed** 2015-02-02 14:02 UTC
Labels: 5 - To review, blue-ticket, bug
