### ISSUE TITLE
Switching from plain to encrypted setup makes group sharing virtually impossible.

### ISSUE THREAD

**Issue by tilllt** [owncloud/core#4986] opened 2013-09-25 09:57 UTC
### Expected behaviour
When switching an Owncloud installation from plain to encrypted, users should succesively be migrated to encrypted files. The encryption process seems to take place once a user logs in after the site setup to encryption has changed. It should be possible to share files with a group that consists of users that already have switched to encrypted files and users that haven't. Users logging in later should have the group shares on "hold" until their filebase is encrypted. once they made the transition, the files should be made available to them.

### Actual behaviour
After doing the switch from plain to encrypted, files can only be shared with groups of users that have all logged in and therefore got their files already encrypted. If you have Groups that consists of unencrypted and encrypted users and try to share a file with that group you will get an error message like this: "Following users are not set up for encryption: 6dd8a6b8-7b6c-1032-9f5b-97d153b89a3e, etc.pp."

### Steps to reproduce
1. Switch an existing Owncloud installation, that has several users and groups, from plain to encrypted.
2. Login some of the Groups users after the config change. 
3. Try to share a file with the group: you will get an error message.

### Server configuration
Operating system: Ubuntu Server 12.04 / Zentyal

Web server: nginx

Database: sqlite

PHP version: 5.3.10

ownCloud version: 5.0.11

### Client configuration
Browser: firefox 23.0.1

Operating system: osx 10.8.5

Nothing appears in the logs, just a message in the GUI.

**Comment by MorrisJobke** [comment] 2015-01-09 15:38
@schiesbn Is this a duplicate of #10010 . Please close then.

@MTRichards #10010 is the issue your refer, isn't it?

**Comment by MTRichards** [comment] 2015-01-09 15:46
Related but not the same.  Could be the same underlying issue though.

**Comment by PVince81** [comment] 2015-01-16 09:39
Similar issue happening when adding users to system-wide mounts that were assigned to groups: https://github.com/owncloud/core/issues/13376

**Comment by schiesbn** [comment] 2015-01-16 10:12
The point here is that switching from plain to encryption is basically migrating your ownCloud to a new configuration. This needs to be completed in order to work again in all circumstances.

There are two approaches to make it easier to switch between plain and encryption mode:

1. We thought about using and command line script for the migration which will create first a dummy key for all users and then migrate all files. Advantage: we can migrate all files and all shares. Disadvantage: every user will need update the private key password after first login so that it match again the login password. Issue where we discuss this idea: https://github.com/owncloud/core/issues/10956

2. If a new user gets added to a group we might be able to find a way to make it easier to encrypt the file for the user. It will probably never happen magically at the moment the user was added because then we would have only zero security if random people could get access to files that easily. Approach discussed here: https://github.com/owncloud/core/issues/10010#issuecomment-64797904

I think the issue here is a combination of the two issues I mentioned above. Let's continue to discuss the solutions there.

**Closed by schiesbn** 2015-01-16 10:12 UTC
Labels: bug, needs info
