### ISSUE TITLE
SQLite Schema issue with upgrading

### ISSUE THREAD

**Issue by jeroenh** [owncloud/core#14222] opened 2015-02-14 10:08 UTC
I tried updating through the website, but it failed quickly:

```
Updating ownCloud to version 8.0, this may take a while.

Turned on maintenance mode
Checked database schema update
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id
```

**Comment by RealRancor** [comment] 2015-02-14 11:08
Hi,

please use the issue template here:

https://raw.github.com/owncloud/core/master/issue_template.md

as requested in the "guidelines for contribute" (linked in the yellow box when creating a new issue) to provide more infos about your environment.

**Comment by jeroenh** [comment] 2015-02-14 11:56
### Steps to reproduce
1. Upgraded to OwnCloud 8.0.0
2. Open main web page
3. Press update

### Expected behaviour
Update should happen smoothly.

### Actual behaviour
```
Updating ownCloud to version 8.0, this may take a while.

Turned on maintenance mode
Checked database schema update
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id
```

### Server configuration
**Operating system**: FreeBSD 10.1

**Web server:** nginx 1.6.2

**Database:** SQLite3

**PHP version:** 5.4.37

**ownCloud version:** (see ownCloud admin page) 8.0.0

**Updated from an older ownCloud or fresh install:** Updated from 7.0.4.2

**List of activated apps:**
I'm using an outlook sync script (http://github.com/georgehrke/cl-calendarimport/issues)

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '511e32dfb4708',
  'datadirectory' => '/usr/local/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.4.2',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'mail_smtmode' => 'smtp',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '587',
  'forcessl' => true,
  'trusted_domains' =>
  array (
    0 => 'cloud.dckd.nl',
  ),
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'dckd.nl',
  'mail_smtpsecure' => 'tls',
  'preview_libreoffice_path' => '/usr/local/bin/libreoffice',
);
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes, serving as https through nginx.

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
nothing special in webserver logs.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"2bfbb713c91d3bc75fbfaa329e85eafc","remoteAddr":"2001:610:6a1:0:4460:4708:8d35:ac78","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('files_sharing')\\n#1 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/base.php(762): OC_Util::setupFS()\\n#3 \\\/usr\\\/local\\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-02-14T10:04:42+00:00"}
{"reqId":"ceca8ffddc7451300422ad8193c6d86b","remoteAddr":"2001:610:6a1:0:4460:4708:8d35:ac78","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'INSERT INTO oc_share_external (id, \"remote\", \"share_token\", \"password\", \"name\", \"owner\", \"user\", \"mountpoint\", \"mountpoint_hash\") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external':\n\nSQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_share_external.remote_id' in \/usr\/local\/www\/owncloud\/lib\/private\/db\/sqlitemigrator.php:39\nStack trace:\n#0 \/usr\/local\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\SQLiteMigrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#1 \/usr\/local\/www\/owncloud\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/usr\/local\/www\/...')\n#2 \/usr\/local\/www\/owncloud\/lib\/private\/updater.php(278): OC_DB::simulateUpdateDbFromStructure('\/usr\/local\/www\/...')\n#3 \/usr\/local\/www\/owncloud\/lib\/private\/updater.php(213): OC\\Updater->checkAppUpgrade('8.0.0.7')\n#4 \/usr\/local\/www\/owncloud\/lib\/private\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n#5 \/usr\/local\/www\/owncloud\/core\/ajax\/update.php(49): OC\\Updater->upgrade()\n#6 {main})","level":4,"time":"2015-02-14T10:04:53+00:00"}
{"reqId":"ecf000d1c95a5c3da81a9fbfb1700a5e","remoteAddr":"","app":"PHP","message":"Class 'OC_Calendar_Import' not found at \/usr\/local\/www\/owncloud\/outlooksync.php#40","level":3,"time":"2015-02-14T10:33:00+00:00"}
{"reqId":"1d61f7162fc198bcfa8d80289b0853ed","remoteAddr":"","app":"PHP","message":"Class 'OC_Calendar_Import' not found at \/usr\/local\/www\/owncloud\/outlooksync.php#40","level":3,"time":"2015-02-14T11:33:00+00:00"}
```

**Comment by LukasReschke** [comment] 2015-02-14 16:17
Thanks for the report!

This issue seems to be a duplicate of https://github.com/owncloud/core/issues/13970, in the comments you can also find a SQL command to resolve it.

**Closed by LukasReschke** 2015-02-14 16:17 UTC
