### ISSUE TITLE
Clicking on row doesn't bring out right side-bar in minimal mode

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19561] opened 2015-10-04 11:32 UTC
### Steps to reproduce

1. Resize the width until the left sidebar disappears
2. Click on a row

### Expected behaviour

Right side-bar comes out, as usual

### Actual result

Action is triggered

---
@PVince81 @rullzer @schiesbn @jancborchardt

**Comment by MorrisJobke** [comment] 2015-10-05 07:12
cc @blizzz

**Comment by PVince81** [comment] 2015-10-05 08:03
Likely to be a visual issue, not functional issue.
In minimal/mobile mode the CSS is different. From what I understand the right sidebar should be fullscreen.

**Comment by PVince81** [comment] 2015-10-05 08:14
Possibly related https://github.com/owncloud/core/issues/19554

**Comment by oparoz** [comment] 2015-10-05 12:19
I don't think it's related. If I click on menu->detailsView, I do get the sidebar, but clicking on the row launches an action.

**Comment by PVince81** [comment] 2015-10-05 12:22
Hmm, then maybe the file element is too large and covers the empty side that is supposed to show the sidebar. Or maybe it's intended. I don't remember. I could imagine that it's intentional that the sidebar can only open with the menu action on mobile. @jancborchardt

**Comment by oparoz** [comment] 2015-10-05 13:03
> I could imagine that it's intentional that the sidebar can only open with the menu action on mobile

Yes, I understand on mobile, but that happens when you resize the browser's window and is thus confusing.
If that's only for mobile, then maybe a "simple" check could be used to make sure the user is really on a mobile (`ontouchstart` perhaps)?

**Comment by PVince81** [comment] 2015-10-05 15:32
I think it's even worse. In my case I don't see a glitch, I can see the sidebar appearing fine when I click on "Details". But then there is no way to change the highlight.

The proper workflow is probably to never show the right sidebar on the right and have users manually pick "Details" from the menu every time, then show the right sidebar / details bar full screen.

**Comment by PVince81** [comment] 2015-10-05 15:33
Ah, it looks like the compact mode override isn't strong enough to override the sidebar styles.

**Comment by PVince81** [comment] 2015-10-05 15:35
Try this https://github.com/owncloud/core/pull/19590

**Comment by DeepDiver1975** [comment] 2015-10-05 20:03
Can we close this? #19590 has been merged - THX

**Comment by MorrisJobke** [comment] 2015-10-05 20:21
Not really. The action is still triggered instead of the sidebar.

**Comment by PVince81** [comment] 2015-10-05 20:26
@MorrisJobke I think this is by design. If you check mobile.css you can see that it is designed to have the name take up the whole row. If that's not acceptable, then we'll need to have @jancborchardt and others come up with a better design for mobile and there isn't any time left before RC.

For now, to open the sidebar in mobile mode you need to use "Details" in the menu.

I suggest moving this to 8.2.1 or 9.0

**Comment by MorrisJobke** [comment] 2015-10-05 20:29
> I suggest moving this to 8.2.1 or 9.0

Fine by me. We shouldn't mess up with UX that late in a release -> 9.0

**Comment by jancborchardt** [comment] 2015-11-04 12:04
This is intentional, yes. On mobile, the full row is reserved to launch the default action, which is opening.

**Closed by jancborchardt** 2015-11-04 12:04 UTC
Labels: app:files, bug, design, feature:sidebar, sev2-high
