### ISSUE TITLE
user app (internal user account management) hangs when opened as "...jquery-1.10.2.js was not found on this server

### ISSUE THREAD

**Issue by critzinger** [owncloud/core#24029] opened 2016-04-15 13:11 UTC
### Steps to reproduce
1. Login as admin
2. go to users
3. browser hanging (IE & Firefox)
4. after a few seconds failure appears „script hanging“ (see Screenshot)

### Expected behaviour
user listed in the browser window

### Actual behaviour
user listing stops with failure an browser hanging

### Server configuration
**Operating system**:		Debian Jessie 64bit
**Web server**:		Apache 2.4
**Database**:			MySQL 5.5.47
**PHP version**:		5.6.19

**ownCloud version**:  ownCloud 9.0.1 (stable) - 9.0.1.3

**Updated from 8.2.2 to 9.0.1.3**

**Where did you install ownCloud from:** i installed it over CLI

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

activity: 2.2.1
comments: 0.2
dav: 0.1.6
federatedfilesharing: 0.1.0
files: 1.4.4
files_sharing: 0.9.1
files_trashbin: 0.8.0
notifications: 0.2.3
provisioning_api: 0.4.1
systemtags: 0.2
templateeditor: 0.1
updatenotification: 0.1.0

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc3c32ffe38f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 365,
        "appcodechecker": true,
        "appstore.experimental.enabled": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "assetdirectory": "\/var\/www\/html\/owncloud",
        "asset-pipeline.enabled": false,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "filesystem_check_changes": 1,
        "forcessl": true,
        "loglevel": 2,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "cloud",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto, 30",
        "updatechecker": true,
        "versions_retention_obligation": "auto, 30"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/		no

**Are you using encryption**:		 no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/	  no

### Client configuration
**Browser**:  			IE11 & Firefox 45.0.2

**Operating system**:		Windows 10 64bit

#### Web server error log

No entries

#### ownCloud log (data/owncloud.log)

No entries

#### Browser log

In firefox debugging console we can see "The requested URL /owncloud/core/vendor/jquery/jquery-1.10.2.js was not found on this server".

we have uploaded the jquery-1.10.2.js manually, but the failure still exists.

After upload of jquery-1.10.2.js when i click debugging the script stops at line 874 

At

for ( ; i < length; i++ ) {
			fn( elems[i], key, raw ? value : value.call( elems[i], i, fn( elems[i], key ) ) );
		}
	}
}

We have currently over 800 Users an now we can´t manage the accounts because the browser hangs permanently

![script-hanging](https://cloud.githubusercontent.com/assets/16885644/14562159/67356796-031b-11e6-933a-05e4c7e49821.JPG)

**Comment by DeepDiver1975** [comment] 2016-04-15 13:16
Please try to find out which part of the webpage is requesting this file - the owncloud code base is not referencing this file anywhere.

**Comment by critzinger** [comment] 2016-04-15 13:24
this message only appears when i click on the left side onto users to manage users account

**Comment by DeepDiver1975** [comment] 2016-04-15 13:31
try to inspect the web page to see there the script is loaded - as long as we don't have more information we cannot find the cause

**Comment by nickvergessen** [comment] 2016-04-15 13:38
Duplicate of https://github.com/owncloud/core/issues/23834 ?

**Comment by DeepDiver1975** [comment] 2016-04-15 13:44
> Duplicate of #23834 ?

yes

**Closed by DeepDiver1975** 2016-04-15 13:44 UTC
Labels: settings:users

**Comment by florian0402** [comment] 2016-04-18 10:45
we only got that workaround to manage the users with occ on commandline/scripts

didn't get any info from here yet.

**Comment by samweisgamdschie** [comment] 2016-04-26 10:28
what exactly is the solution in this case? Because we have the same issue and no solution.

**Comment by florian0402** [comment] 2016-04-26 11:18
there is no soultion for the gui problem yet. We you the same build like you.

**Comment by florian0402** [comment] 2016-05-03 11:21
any news guys?

**Comment by samweisgamdschie** [comment] 2016-05-12 11:40
please reopen and resolve this issue, since a missing jquery linkage is not a duplicate of an enhancement of the user management!! We have the exact same error with 9.0.1 and it does not seem to be resolved in 9.0.2. and what the main problem is, we cannot manage our (about 450) users!!

**Comment by PVince81** [comment] 2016-05-12 14:51
The jquery error is misleading and is not related to this issue.
I grepped the 9.0.2 code and the only place that seems to refer to it is this file "core/vendor/jquery/jquery.min.map". This file is only used by debuggers to be able to un-minify files.

We should probably delete this file completely anyway.

The real issue with many groups is that the users page is loading all groups upfront and populates ALL dropdowns with ALL the groups, which makes page rendering very slow. This issue is tracked here https://github.com/owncloud/core/issues/23834

**Comment by PVince81** [comment] 2016-05-12 14:52
Sorry, pasted the wrong ticket.
