### ISSUE TITLE
[Experimental files locking] Uploading files to root folder is locked.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16970] opened 2015-06-16 15:05 UTC
Just to keep track of https://github.com/owncloud/core/pull/16729#issuecomment-108472058

### Steps to reproduce

Having a server with experimental files locking enabled do:

1. Using webdav upload files to the root.

### Expected behaviour
Files are uploaded.

### Actual behaviour
Files return 423 when uploading.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
Windows network drive.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**webdav**
Cadaver

**Comment by PVince81** [comment] 2015-06-16 15:39
Duplicate of https://github.com/owncloud/core/issues/16959

**Closed by PVince81** 2015-06-16 15:39 UTC
Labels: bug, feature:locking, sev1-critical
