### ISSUE TITLE
[6.0.6] unable to rename, file is not writable 

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#14728] opened 2015-03-06 11:46 UTC
In the last ten days owncloud.log growth with 21'675 of this error messages
```
{"app":"core","message":"unable to rename, file is not writable : files_versionsManuscript_Cut.docx.v1423491653","level":3,"time":"2015-02-11T07:46:26+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versionsManuscript_Cut.docx.v1420812698","level":3,"time":"2015-02-11T07:46:26+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versionsincident.txt.v1423640816","level":3,"time":"2015-02-11T07:48:09+00:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versionsincident.txt.v1423640916","level":3,"time":"2015-02-11T07:49:27+00:00"}
```

One of the two files is still on the file system:
```
./USER_NAME/files_trashbin/files/incident.txt.d1423632639
./USER_NAME/files_trashbin/files/incident.txt.d1423635281
./USER_NAME/files_trashbin/files/incident.txt.d1423637080
./USER_NAME/files_trashbin/files/incident.txt.d1423638141
./USER_NAME/files_trashbin/files/incident.txt.d1423639675
```

If I look at the permissions they are right:
```
-rw-r--r-- 1 apache apache 131218 Feb 12 23:52 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781562
-rw-r--r-- 1 apache apache 131771 Feb 12 23:53 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781587
-rw-r--r-- 1 apache apache 131309 Feb 12 23:54 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781631
-rw-r--r-- 1 apache apache 131241 Feb 12 23:54 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781687
-rw-r--r-- 1 apache apache 131235 Feb 12 23:55 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781759
-rw-r--r-- 1 apache apache 131236 Feb 12 23:57 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781832
-rw-r--r-- 1 apache apache 131431 Feb 12 23:58 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781882
-rw-r--r-- 1 apache apache 131454 Feb 12 23:58 /mnt/id_services_SERVER_NAME_data/data/USER_NAME/files_trashbin/files/incident.txt.d1423781931
```

Server Version: OwnCloud 6.0.6

@PVince81 You could reproduce it :+1: 

@MorrisJobke 

00002588

**Comment by PVince81** [comment] 2015-03-06 11:49
I don't have accurate reproduction steps yet.

Looking at the logs I deduced that the file "incident.txt" is created/overwritten every 30 seconds or so, so I made a script that uploads a new version of the file every 15 seconds.

Then sometimes while the script is running, I manually delete the file in the web UI.

And sometimes I get this:
```
{"reqId":"54f993643559c","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionsincident.txt.v1425642319 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:45:40+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

or from the web UI deletion or WebDAV delete:
```
{"reqId":"54f993643559c","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionsincident.txt.v1425642319 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:45:40+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

The suspicious part is that there is a missing slash between "files_versions" and the file name.

More soon.

**Comment by PVince81** [comment] 2015-03-06 11:54
Ok got the steps:

1. Create a file in the root, call it "test.txt"
2. Edit the file multiple times with the text editor to create versions
3. Open the versions dropdown and see that the versions exist
4. Delete the file "test.txt" (note: the trashbin app must be enabled)

```
{"reqId":"54f9953dc78ea","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionstest.txt.v1425642770 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:53:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9953dc78ea","app":"core","message":"unable to rename, file is not writable : files_versionstest.txt.v1425642770","level":3,"time":"2015-03-06T11:53:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9953dc78ea","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionstest.txt.v1425642768 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:53:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9953dc78ea","app":"core","message":"unable to rename, file is not writable : files_versionstest.txt.v1425642768","level":3,"time":"2015-03-06T11:53:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

Hmm, the same happens if the file is in a subdir "sub/testsub.txt":
```
{"reqId":"54f9956f88580","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionstestsub.txt.v1425642849 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:54:23+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9956f88580","app":"core","message":"unable to rename, file is not writable : files_versionstestsub.txt.v1425642849","level":3,"time":"2015-03-06T11:54:23+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9956f88580","app":"PHP","message":"filesize(): stat failed for \/srv\/www\/htdocs\/owncloud\/data\/testuser\/files_versionstestsub.txt.v1425642847 at \/srv\/www\/htdocs\/owncloud\/lib\/private\/files\/storage\/local.php#105","level":0,"time":"2015-03-06T11:54:23+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
{"reqId":"54f9956f88580","app":"core","message":"unable to rename, file is not writable : files_versionstestsub.txt.v1425642847","level":3,"time":"2015-03-06T11:54:23+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/delete.php"}
```

**Comment by PVince81** [comment] 2015-03-06 11:56
So basically if you delete any file that has versions attached, you will get the error.

This is on 6.0.6.
Will try OC 7 and 8.

**Comment by PVince81** [comment] 2015-03-06 12:11
Looks like stable7 (upcoming 7.0.5) is fine.

Let's compare the source.

**Comment by PVince81** [comment] 2015-03-06 12:14
Here's the stack trace that leads to the error by the way:
```
0  OC\Files\Storage\Local->rename() /srv/www/htdocs/owncloud/lib/private/files/storage/local.php:163
1  OC\Files\View->rename() /srv/www/htdocs/owncloud/lib/private/files/view.php:403
2  OCA\Files_Trashbin\Trashbin::retainVersions() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:220
3  OCA\Files_Trashbin\Trashbin::move2trash() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/trashbin.php:157
4  OCA\Files_Trashbin\Hooks::remove_hook() /srv/www/htdocs/owncloud/apps/files_trashbin/lib/hooks.php:42
5  call_user_func:{/srv/www/htdocs/owncloud/lib/private/hook.php:72}() /srv/www/htdocs/owncloud/lib/private/hook.php:72
6  OC_Hook::emit() /srv/www/htdocs/owncloud/lib/private/hook.php:72
7  OC\Files\View->runHooks() /srv/www/htdocs/owncloud/lib/private/files/view.php:754
8  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/files/view.php:693
9  OC\Files\View->unlink() /srv/www/htdocs/owncloud/lib/private/files/view.php:352
10 OC\Files\Filesystem::unlink() /srv/www/htdocs/owncloud/lib/private/files/filesystem.php:557
11 require_once()  /srv/www/htdocs/owncloud/apps/files/ajax/delete.php:22
12 OC::loadAppScriptFile() /srv/www/htdocs/owncloud/lib/base.php:807
13 call_user_func:{/srv/www/htdocs/owncloud/lib/private/router.php:127}() /srv/www/htdocs/owncloud/lib/private/router.php:127
14 OC_Router->match() /srv/www/htdocs/owncloud/lib/private/router.php:127
15 OC::handleRequest() /srv/www/htdocs/owncloud/lib/base.php:725
16 {main}          /srv/www/htdocs/owncloud/index.php:30
```

This also means that versions are lost on deletion.

**Comment by PVince81** [comment] 2015-03-06 12:32
Looks like this PR from @schiesbn fixed it for OC 7: https://github.com/owncloud/core/pull/10186

**Comment by PVince81** [comment] 2015-03-06 12:51
PR for stable6: https://github.com/owncloud/core/pull/14729

**Comment by cdamken** [comment] 2015-03-10 10:43
@PVince81 For my side is fixed.
#### Thank you.
You close the case when it's merged as we discussed in IRC

**Comment by MorrisJobke** [comment] 2015-04-08 11:03
WIll be in 6.0.8

**Comment by cdamken** [comment] 2015-07-29 14:47
@PVince81 @MorrisJobke The problem still happens in 7.0.6 :cry: 

```
{"app":"core","message":"unable to rename, file is not writable : files\/[Physio] Physiologie II Zsmf.docx.ocTransferId3764822684.part","level":3,"time":"2015-07-07T21:23:09+02:00"}
{"app":"core","message":"unable to rename, file is not writable : files_versions\/Masterarbeiten\/ERECS\/@Data Processing\/derived from V12.004\/Cleaned PWV data derived from Prism file analysis PWV_V2 (2015-06-17) incl covariates general data.v","level":3,"time":"2015-07-08T13:02:14+02:00"}
{"app":"core","message":"unable to rename, file is not writable : files\/Paper in prep\/Si Metasomatism Bracco\/Si Metasomatism Bracco_mv041.docx.ocTransferId3484751024.part","level":3,"time":"2015-07-08T13:08:47+02:00"}
```

Full log in S3-ownCloud\Shared\owncloud\support\github-issues\core\14728\owncloud.log

**Comment by PVince81** [comment] 2015-07-29 15:16
@cdamken it doesn't look like the same problem. The problem above was that "files_versions" was missing a trailing slash.

Mind raising a separate ticket ?

Or did you see new log entries with "files_versions" + file name without slash in between ?

**Comment by MorrisJobke** [comment] 2015-07-29 15:26
Looks like a different issue -> close

**Closed by MorrisJobke** 2015-07-29 15:26 UTC
Labels: 6.0.8, app:files_trashbin, app:files_versions, blue-ticket, bug

**Comment by cdamken** [comment] 2015-07-29 16:12
@PVince81 @MorrisJobke  Done, new case: https://github.com/owncloud/core/issues/17962. Thanks
