### ISSUE TITLE
No email notification with external storage

### ISSUE THREAD

**Issue by hhaeb** [owncloud/core#26809] opened 2016-12-11 18:18 UTC
### Steps to reproduce
1. Add an local folder as external storage
2. copy a file on the server to the local folder
3.

### Expected behaviour
1. File should be syncronised 
2. File should be in sync protokol
3. File should be in server activity protokol
4. email should be sent

### Actual behaviour
First 3 behaviour are O.K.
NO email were sent

### Server configuration
Ubuntu 14.04.4 LTS

**Web server:**
Apache/2.4.7

**Database:**
MySQL 5.5.49
**PHP version:**
PHP Version 5.5.9-1ubuntu4.16
**ownCloud version:** (see ownCloud admin page)
9.1.2
**Updated from an older ownCloud or fresh install:**
from 9.1.0
**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1


**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocnx26nrsp2m',
  'passwordsalt' => '##############################',
  'secret' => '#######################',
  'trusted_domains' => 
  array (
    0 => 'mycustomer.de',
  ),
  'datadirectory' => '/home/mycustomer2015/oc',
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'dbname' => 'owncloud_mycustomer',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_myname',
  'dbpassword' => '#####################',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => 'myname',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'mydomain',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mydomain.net',
  'mail_smtpport' => '587',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'myname@mydomain',
  'mail_smtppassword' => '##########',
  'updatechecker' => false,
  'overwrite.cli.url' => 'https://mycustomer.de/oc_mycustomer',
  'appstoreenabled' => false,
  'has_internet_connection' => true,
  'htaccess.RewriteBase' => '/oc_mycustomer',
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'loglevel' => 3,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment] 2016-12-12 09:38
Duplicate of https://github.com/owncloud/core/issues/26656

**Closed by PVince81** 2016-12-12 09:38 UTC
