### ISSUE TITLE
Encrypted external files (S3) open always as text files in owncloud web view

### ISSUE THREAD

**Issue by Sevyls** [owncloud/core#14238] opened 2015-02-15 22:26 UTC
![screenshot](https://cloud.githubusercontent.com/assets/547842/6205337/d7af4dd4-b56a-11e4-8235-a1bf3134505b.png)

### Steps to reproduce
1. Enable plugin files_encryption
2. Enable plugin files_external
3. Connect S3 bucket as an external storage
4. Upload test files (i.e. pdf, jpg, png files)
5. Open them in Web viewer

### Expected behaviour
Image fIles should open in the image viewer
Pdf files should open in the document viewer
etc

### Actual behaviour
All Images, Documents, etc. open in a Text editor and show the decrypted files contents.

### Server configuration
**Operating system**:
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-45-generic x86_64)

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
PostgreSQL 9.3

**PHP version:**
PHP 5.5.9-1ubuntu4.5 

**ownCloud version:**
ownCloud 8.0 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
Activity, Deleted files, External storage support, File locking, First run wizard, Mail Template Editor, PDF Viewer, Pictures, Provisioning API, Server-side Encryption, Share Files, Text Editor, Updater, Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocfd8sjvgcxo',
  'passwordsalt' => '***REMOVED***',
  'secret' => '***REMOVED***',
  'trusted_domains' =>
  array (
    0 => 'ec2-***REMOVED***.eu-central-1.compute.amazonaws.com',
    1 => '***REMOVED***',
  ),
  'datadirectory' => '/var/owncloud/data',
  'overwrite.cli.url' => 'https://ec2-***REMOVED***.eu-central-1.compute.amazonaws.com/owncloud',
  'dbtype' => 'pgsql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '***REMOVED***',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => '***REMOVED***',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '***REMOVED***',
  'mail_smtppassword' => '***REMOVED***',
  'mail_smtphost' => 'email-smtp.eu-west-1.amazonaws.com',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, aws s3

**Are you using encryption:** yes/no
yes

### Client configuration
**Browser:**
Chrome 40.0.2214.111 (64-bit)

**Operating system:**
Xubuntu 14.10

#### ownCloud log (data/owncloud.log)
```
find it at https://gist.github.com/Sevyls/f632899d35b2e427993d
```

**Comment by karlitschek** [comment] 2015-02-16 01:34
@butonic @schiesbn any idea?

**Comment by PVince81** [comment] 2015-02-17 10:08
Very likely to be a mimetype issue. @butonic I remember there was some custom code to retrieve mime types stored in S3 ?

@Sevyls please open the files app in the web UI, then use the browser inspector and inspect the "tr" element of a jpg file. What's the value in the "data-mime" field ?

It should normally be something like "image/jpeg" but I suspect it might be showing "text/plain" for some reason.

**Comment by Sevyls** [comment] 2015-02-17 10:32
@PVince81 there you go:

```
<tr data-id="130" data-type="file" data-size="119632" data-file="bla.jpg" 
data-mime="text/plain" data-mtime="1424037507000" data-etag="54e116c00ba53" 
data-permissions="27" data-mounttype="external" data-share-permissions="19">
...
</tr>
```

**Comment by PVince81** [comment] 2015-02-17 10:33
Ok thanks, this confirms it.
Were these files uploaded through ownCloud or uploaded outside of it ?

**Comment by Sevyls** [comment] 2015-02-17 10:35
These files were uploaded using the owncloud Desktop client on my Xubuntu 14.10 desktop machine.

**Comment by Sevyls** [comment] 2015-02-17 10:39
Note: the Android app opens the file in the image viewer, but it also says "Type: PLAIN" when you open the Details of this file.

**Comment by oparoz** [comment] 2015-02-23 12:03
(Subscribing)

**Comment by tudisco** [comment] 2015-03-10 07:19
I have a similar problem when uploading from my phone to an external foldered configured for s3. Plus encryption is also turned on.  All the photos show up in text editor.

**Comment by PVince81** [comment] 2015-10-12 14:39
You could try commenting out / removing the `getMimeTypes` method here: https://github.com/owncloud/core/blob/v8.1.3/apps/files_external/lib/amazons3.php#L421

This will make it fall back to the default mechanism that infers mime type based on the extension instead of asking S3 about it.

**Comment by schiesbn** [comment] 2015-10-13 10:04
Encrypted data is always represented as a string. That's probably the reason why S3 think that all encrypted files are text files. So disabling the mime type detection probably works.

I wonder why we use this in the first place? In all other places we detect the mimetype based on the extension. Why should it be different for s3?

**Comment by PVince81** [comment] 2015-10-13 10:06
It's probably very old code. I believe that before OC 6 or 7 we used the mime types delivered by the storage and later on changed to use extension-based detection.
But at that time I wasn't sure whether every external storage needed to be adjusted accordingly

**Comment by schiesbn** [comment] 2015-10-13 10:11
OK, so we just need to remove the getMimeType() implementation for fall back to the default one. Do you want to prepare a pull request?

**Comment by PVince81** [comment] 2015-10-14 08:23
PR here https://github.com/owncloud/core/pull/19758 (needs regression testing)

**Comment by PVince81** [comment] 2016-03-01 21:34
https://github.com/owncloud/core/pull/19758 was merged

**Closed by PVince81** 2016-03-01 21:34 UTC
Labels: app:files_encryption, app:files_external, bug
