### ISSUE TITLE
Ubuntu packages don't reflect the default location for apache2 webroots

### ISSUE THREAD

**Issue by krichter722** [owncloud/core#16787] opened 2015-06-07 15:28 UTC
On Ubuntu 15.04 the `owncloud` web root is placed in `/var/www/owncloud/` which doesn't reflect the default web root `/var/www/html/` of `apache2` in Ubuntu 14.04 (or 14.10) and later.

The already thin instructions at https://doc.owncloud.org/server/4.5/admin_manual/installation.html (which don't contain a link to further instructions) can't apply in any way without this reflection.

experienced with 8.0.4-0

**Comment by RealRancor** [comment] 2015-06-07 16:30
Hi,

> On Ubuntu 15.04 the owncloud web root is placed in /var/www/owncloud/ which doesn't reflect the default web root /var/www/html/ of apache2 in Ubuntu 14.04 (or 14.10) and later.

there are two existing reported issue about this: https://github.com/owncloud/core/issues/6388 and https://github.com/owncloud/core/issues/9840

> The already thin instructions at https://doc.owncloud.org/server/4.5/admin_manual/installation.html 

You're viewing an documentation here for ownCloud 4.5 which wasn't updated for a long time. Its really recommended to use the current documentation linked at https://doc.owncloud.org:

https://doc.owncloud.org/server/8.0/admin_manual/installation/index.html

**Comment by karlitschek** [comment] 2015-06-08 01:07
@jnweiger FYI

**Comment by DeepDiver1975** [comment] 2015-06-08 08:26
Moving the webroot has some implication on upgrade which requires careful testing.
Because of this we refrained in the past from moving the webroot.

**Comment by jnweiger** [comment] 2015-06-08 09:51
The filesystem layout is sub-optimal. I agree. As DeepDiver1975 mentioned, we did not make most of the recommended changes, to not break install or update scenarios.

The plan is to first have a solid (reproducable, efficient, comrehensive) ability to define most scenarios as test cases, and run them in an automated way. As soon as we can run such tests on our packages, I am willing to branch dedicated *:testing project in the build service and work on issues like this.

Resolved later...

**Comment by PVince81** [comment] 2015-06-08 10:17
Moving the webroot could also affect legacy storages that are hard-coded in the database, so need to be very careful.

**Comment by DeepDiver1975** [comment] 2015-06-08 10:23
> so need to be very careful.

as-in dont-touch ....

**Comment by Xenopathic** [comment] 2016-03-28 22:12
Duplicate of #10751 since both Debian and Ubuntu use the same filesystem structure

**Closed by Xenopathic** 2016-03-28 22:12 UTC
Labels: packaging
