### ISSUE TITLE
Stop overwriting .htaccess when upgrading via web updater

### ISSUE THREAD

**Issue by baldurmen** [owncloud/core#20662] opened 2015-11-21 16:36 UTC
### Steps to reproduce
1. Modify the .htaccess at the root of the installation
2. Update the instance via the web updater

### Expected behaviour
.htaccess should not be overwritten

### Actual behaviour
.htaccess is overwritten

### Comments
One of the many instance of Owncloud I manage is on a shared web server. I don't have access to command line and have to use a GUI to manage the different aspects of the hosting.

The only way I have to manage the PHP configuration on this instance is via php_value entries in .htaccess. I HAVE to modify some values, because the default one imposed by the hosting company leads to critical error on the instance.

Problem is, each and every time I upgrade the instance, I have to rewrite all the modifs I did to the .htaccess, because the upgrades overwrite it.

I understand that .htaccess has to be modified sometimes, but do the overwriting has to be systematic? It would be GREAT if this could be done only when necessary and be accompanied by a little notice on the upgrade page ("Beware, .htaccess has been updated to the last version. Your local modifications have been overwritten").

**Comment by RealRancor** [comment] 2015-11-21 16:48
Duplicate of https://github.com/owncloud/core/issues/2692

**Comment by PVince81** [comment] 2015-11-23 16:08
CC @VicDeo FYI

**Comment by ravloony** [comment] 2016-01-18 11:55
This is a issue for me because I have simp_le (Let's encrypt client) running via cron. I need to be sure that my domain verification will not fail when my cert is updated.

Standard way of solving this (à la Wordpress) would be to put Owncloud rules between two regexable headers in the htaccess file.

So content could be:

    ### Anything placed between the BEGIN and END mantras will be overwritten
    ### BEGIN Owncloud rules ###
    RewriteRule blah blah blah
    ### END Owncloud rules ###
    ... This bit is safe.

Is something like this possible?

**Comment by LukasReschke** [comment] 2016-03-01 22:11
Overwriting the .htaccess is expected behaviour

**Closed by LukasReschke** 2016-03-01 22:11 UTC
Labels: comp:core, feature:update
