### ISSUE TITLE
When moving files into folder via drag & drop with folder outside of visible screen, scrolling should happen automatically

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#18885] opened 2015-09-07 20:46 UTC
When moving files into folder via drag & drop with folder outside of visible screen, scrolling should happen automatically so that desired folder becomes reachable.

TO reproduce have a look at the screenshot below:

1. Lets assume I want to move the file "Demo PDF" into a folder which is far up outside of the screen, for example the "Music" folder.

2. I click & hold the file with the intention to bringing it up and dropping it into the folder.

3. When dragging it up towards the folder, the page does not scroll upwards.

4. I can never reach the folder via drag&drop that way, therefore I cannot move the file into the desired folder.

Solution: 
When dragging file to move to a folder outside of visivle page, page should scroll upwards automatically.
![file move](https://cloud.githubusercontent.com/assets/3358665/9722702/e759a57e-55a9-11e5-84c3-de3b8e5f4670.png)

**Comment by zanglerecke** [comment] 2015-09-15 06:01
a possible solution (help, not solve the Problem) is to select all files to move, and then minimize evrything with ctrl-Scroll, find the marked line, and drag it then... -> not very comfortable but it works,

**Comment by PVince81** [comment] 2015-09-16 15:57
Duplicate of https://github.com/owncloud/core/issues/12329

**Closed by PVince81** 2015-09-16 15:58 UTC
Labels: bug
