### ISSUE TITLE
Update to 8.0.3 failed

### ISSUE THREAD

**Issue by ip6li** [owncloud/core#16280] opened 2015-05-12 13:13 UTC
An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by RealRancor** [comment] 2015-05-12 13:23
Hi,

Duplicate of: https://github.com/owncloud/core/issues/16008 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097 , https://github.com/owncloud/core/issues/16157 , https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218

Documentation for this is also available here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

**Closed** 2015-05-12 14:50 UTC
