### ISSUE TITLE
User details not saved unless click Enter

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#17789] opened 2015-07-21 17:02 UTC
ownCloud 8.1

* Go to `index.php/settings/users`
* click to edit full name of user
* type new name, click outside of text field

Visually: name was changes
Really: refresh page, name was not changed

However, changes are saved when click enter to submit changes, not just click outside.

So, there is need to either reset user's name or actually save it.

Same for email (probably other fields, didn't check).

**Comment by RealRancor** [comment] 2015-07-21 17:07
Probably related / duplicate of https://github.com/owncloud/core/issues/15176

**Comment by michag86** [comment] 2015-12-03 16:21
The problem is, that the blur action updates the span from the input. 
Here

https://github.com/owncloud/core/blob/v8.2.1/settings/js/users/users.js#L750-L755

If I comment out this line:
https://github.com/owncloud/core/blob/v8.2.1/settings/js/users/users.js#L751
The value is reseted.

Now is the question, what is the right action for leaving the input or pressing "tab"?
Save or reset?

**Comment by MorrisJobke** [comment] 2015-12-07 07:31
https://github.com/owncloud/core/pull/15750 -> Let's answer your question with @jancborchardt's words: https://github.com/owncloud/core/pull/15750#issuecomment-156058331

**Closed** 2015-12-11 11:15 UTC
Labels: 3 - To Review, settings:users
