### ISSUE TITLE
Enabling activity app fails

### ISSUE THREAD

**Issue by jpschewe** [owncloud/core#14232] opened 2015-02-15 15:09 UTC
When I tried to enable the activity app with owncloud 8.0 on a postgresql database I get:

An exception occurred while executing 'CREATE TABLE "oc_activity" ("activity_id" SERIAL NOT NULL, "timestamp" INT DEFAULT 0 NOT NULL, "priority" INT DEFAULT 0 NOT NULL, "type" VARCHAR(255) NOT NULL, "user" VARCHAR(64) NOT NULL, "affecteduser" VARCHAR(64) NOT NULL, "app" VARCHAR(255) NOT NULL, "subject" VARCHAR(255) NOT NULL, "subjectparams" VARCHAR(255) NOT NULL, "message" VARCHAR(255) DEFAULT NULL, "messageparams" VARCHAR(255) DEFAULT NULL, "file" VARCHAR(255) DEFAULT NULL, "link" VARCHAR(255) DEFAULT NULL, PRIMARY KEY("activity_id"))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_activity" already exists

**Comment by RealRancor** [comment] 2015-02-15 17:35
Hi,

the issue tracker of the activity app is located here:

https://github.com/owncloud/activity/issues

Please re-open there using the issue template provided here:

https://raw.github.com/owncloud/core/master/issue_template.md

**Comment by karlitschek** [comment] 2015-02-15 18:29
@nickvergessen can you have a look please?

**Comment by nickvergessen** [comment] 2015-02-15 19:01
Not really sure, at least it's a core issue, since enabling an app that is already installed, is nothing the app can take care about.

**Comment by nickvergessen** [comment] 2015-02-16 11:53
@jpschewe can you help us out with more details as listed in the issue template?

**Comment by jkraemer** [comment] 2015-03-13 02:28
Same here.

Interesting fact, not sure if related: I am 100% sure I did the `occ upgrade` in the console and it completed successfully, I also logged in successfully as admin. After trying to enable some apps and logging out again OC still insisted on upgrading to 8.0.2, succeeding for the second time. Didn't ask again the next time I logged out though so I hope it was a one time hickup.

### Steps to reproduce

Log in as admin, go to Apps / Not enabled, try to enable the Activity app.

### Expected behaviour

Activity app should be enabled

### Actual behaviour

The following error is shown after clicking 'Enable':

```
An exception occurred while executing 'CREATE TABLE "oc_activity" ("activity_id" SERIAL NOT NULL, "timestamp" INT DEFAULT 0 NOT NULL, "priority" INT DEFAULT 0 NOT NULL, "type" VARCHAR(255) NOT NULL, "user" VARCHAR(64) NOT NULL, "affecteduser" VARCHAR(64) NOT NULL, "app" VARCHAR(255) NOT NULL, "subject" VARCHAR(255) NOT NULL, "subjectparams" VARCHAR(255) NOT NULL, "message" VARCHAR(255) DEFAULT NULL, "messageparams" VARCHAR(255) DEFAULT NULL, "file" VARCHAR(255) DEFAULT NULL, "link" VARCHAR(255) DEFAULT NULL, PRIMARY KEY("activity_id"))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_activity" already exists
```

### Server configuration
**Operating system**: Debian Jessie
**Web server:** nginx
**Database:** postgresql
**PHP version:**  5.6.6
**ownCloud version:** 8.0.2
**Updated from an older ownCloud or fresh install:** Update from 7.0.5
**List of activated apps:** None (disabled all for the upgrade), this was the first from the list of 'Not enabled' apps that I wanted to enable.

**The content of config/config.php:**

```
<?php 
$CONFIG = array ( 
  'instanceid' => 'someid', 
  'passwordsalt' => 'salt', 
  'datadirectory' => '/data/owncloud', 
  'dbtype' => 'pgsql', 
  'version' => '8.0.2.0', 
  'dbname' => 'owncloud', 
  'dbhost' => '10.10.1.1', 
  'dbtableprefix' => 'oc_', 
  'dbuser' => 'dbuser', 
  'dbpassword' => 'dbpass', 
  'installed' => true, 
  'loglevel' => '1', 
  'logfile' => '/var/log/oc/owncloud.log', 
  'theme' => '', 
  'maintenance' => false, 
  'trusted_domains' =>  
  array ( 
    0 => 'oc.jkraemer.net', 
  ), 
  'share_folder' => '/Shared', 
  'mail_smtpmode' => 'sendmail', 
  'mail_from_address' => 'oc', 
  'mail_domain' => 'jkraemer.net', 
  'secret' => 'redacted', 
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** data is on encfs, not using the builtin encryption

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
180.190.53.80 [13/Mar/2015:03:22:38 +0100] "GET /index.php/settings/apps/list?category=0 HTTP/1.1" 200 3801 "https://oc.jkraemer.net/index.php/settings/apps" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0" oc.jkraemer.net
 180.190.53.80 [13/Mar/2015:03:22:58 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 524 "-" "Mozilla/5.0 (Linux) mirall/1.7.1" oc.jkraemer.net  
 180.190.53.80 [13/Mar/2015:03:23:05 +0100] "GET /index.php/settings/apps/list?category=1 HTTP/1.1" 200 18582 "https://oc.jkraemer.net/index.php/settings/apps" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0" oc.jkraemer.net
 180.190.53.80 [13/Mar/2015:03:23:11 +0100] "POST /index.php/settings/ajax/enableapp.php HTTP/1.1" 200 712 "https://oc.jkraemer.net/index.php/settings/apps" "Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.4.0" oc.jkraemer.net
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"9bfb0c1ae00bd85a68885d5cda7f0406","remoteAddr":"180.190.53.80","app":"core","message":"Invalid OCS content returned for app activity","level":4,"time":"2015-03-13T02:23:11+00:00"}
{"reqId":"9bfb0c1ae00bd85a68885d5cda7f0406","remoteAddr":"180.190.53.80","app":"core","message":"An exception occurred while executing 'CREATE TABLE \"oc_activity\" (\"activity_id\" SERIAL NOT NULL, \"timestamp\" INT DEFAULT 0 NOT NULL, \"priority\" INT DEFAULT 0 NOT NULL, \"type\" VARCHAR(255) NOT NULL, \"user\" VARCHAR(64) NOT NULL, \"affecteduser\" VARCHAR(64) NOT NULL, \"app\" VARCHAR(255) NOT NULL, \"subject\" VARCHAR(255) NOT NULL, \"subjectparams\" VARCHAR(255) NOT NULL, \"message\" VARCHAR(255) DEFAULT NULL, \"messageparams\" VARCHAR(255) DEFAULT NULL, \"file\" VARCHAR(255) DEFAULT NULL, \"link\" VARCHAR(255) DEFAULT NULL, PRIMARY KEY(\"activity_id\"))':\n\nSQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"oc_activity\" already exists","level":3,"time":"2015-03-13T02:23:11+00:00"}
```

**Comment by jkraemer** [comment] 2015-03-13 02:34
Manually dropping the (empty) `oc_activity` and `oc_activity_mq` tables solved the problem, app could be enabled now.

**Comment by nickvergessen** [comment] 2015-03-24 10:35
Duplicate of #11047

**Closed by nickvergessen** 2015-03-24 10:35 UTC
Labels: needs info
