### ISSUE TITLE
Files a certain size are uploaded twice after confirmation of overwritting

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#15704] opened 2015-04-17 14:55 UTC
### Steps to reproduce
1. Upload a 6MB file. I don't know which size exactly triggers this behaviour
2. Upload the same file a second time.
3. When asked, tick the box which says you want to overwrite the file

### Expected behaviour
The just uploaded file should be available right away, replacing the old one

### Actual behaviour
The file is uploaded again

### Server configuration
Master, PHP 5.5
No encryption

### Client
Firefox

### Logs
I do see a JS error, but I don't think it's relevant.
`ReferenceError: checkbox is not defined`

**Comment by PVince81** [comment] 2015-04-20 16:49
I think this happens for every file, possibly duplicate of https://github.com/owncloud/core/issues/8664

**Comment by oparoz** [comment] 2015-04-20 16:53
Yep, #searchfail


   FROM: Vincent Petry
SENT: Monday, 20 April 2015 18:49
TO: core@noreply.github.com
REPLY TO: owncloud/core
CC: Olivier Paroz
SUBJECT: Re: [core] Files a certain size are uploaded twice after
confirmation of overwritting (#15704)

> I think this happens for every file, possibly duplicate of #8664[1]
>
> —
> Reply to this email directly or view it on GitHub[2].



Liens:
------
[1] https://github.com/owncloud/core/issues/8664
[2] https://github.com/owncloud/core/issues/15704#issuecomment-94505969

**Closed** 2015-04-20 21:22 UTC
Labels: app:files, bug, duplicate
