### ISSUE TITLE
[Clarification request, or suggestion] "Bulk changes" of e-mail notification settings for file events

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#9875] opened 2014-07-24 17:46 UTC
As an admin, I want to set the e-mail notification for all users to certain values, e.g. to enable notifications for all file events.

How can this be achieved?

**Comment by PVince81** [comment] 2017-12-14 15:44
closing as duplicate of https://github.com/owncloud/activity/issues/429

**Comment by Wikinaut** [comment] 2019-08-02 07:11
Still interested in such a feature.

**Comment by micbar** [comment] 2021-09-16 09:30
1) There is a system default
2) The user overrides it
3) Why should the admin change it and annoy the user with that action?

I don't get the use case.

**Closed by micbar** 2021-09-16 09:30 UTC
Labels: enhancement
