### ISSUE TITLE
Sharing files via link not working when sharing external storage files

### ISSUE THREAD

**Issue by affibox** [owncloud/core#16947] opened 2015-06-15 18:53 UTC
Greetings. 
I have s3 as my external storage. When we share a file using links we get an error.
Here is an example:
aws s3 storage: https://cumulus.intricloud.com/index.php/s/E3Wdqz50D9VE6Z6
local storage : https://cumulus.intricloud.com/index.php/s/36hywd7i2ktxmNR

Both links point to the same file which is a simple pdf. But when sharing files that are stored on s3 I get this error:
{
PDF.js v1.0.712 (build: 6969ed4)
Message: Missing PDF "https://cumulus.intricloud.com/index.php/s/E3Wdqz50D9VE6Z6/download".
}

Please help...!!!

**Comment by LukasReschke** [comment] 2015-06-15 20:13
Do we have some S3 testing credentials?

cc @DeepDiver1975

**Comment by PVince81** [comment] 2015-06-17 11:27
@affibox are you able to download the file by opening "https://cumulus.intricloud.com/index.php/s/E3Wdqz50D9VE6Z6/download"  directly in the browser ?

Can you post your owncloud.log from the time where you opened that link ?

**Comment by PVince81** [comment] 2015-06-17 11:28
Are you using a proxy or anything that might filter out this URL format ?

Please provide more info about your setup using the issue template https://raw.github.com/owncloud/core/master/issue_template.md
Thanks.

**Comment by PVince81** [comment] 2015-06-17 11:33
Works for me in 8.0.4.
Steps:
1. Mount a S3 bucket under "amazon-s3"
2. Upload a PDF file as "amazon-s3/test.pdf"
3. Share "amazon-s3/test.pdf" with link
4. Open the link
5. Download it

The PDF viewer appears with the file contents and I can also download it using the button on the top right (or append "/download") in the URL.

**Comment by affibox** [comment] 2015-06-17 13:02
Sorry for the late replay. I cut my self with an circular saw yesterday.

Let me get the log for you.

**Comment by affibox** [comment] 2015-06-17 13:07
Here is a link of a picture. https://cumulus.intricloud.com/index.php/s/3QeQyUnJ6Wf6Mem

**Comment by affibox** [comment] 2015-06-17 13:11
![error](https://cloud.githubusercontent.com/assets/8114543/8207631/c6a0d75e-14d0-11e5-909a-3ba8321af7c6.JPG)

**Comment by affibox** [comment] 2015-06-17 13:14
I keep getting this and I know curls is installed.
![error-curl](https://cloud.githubusercontent.com/assets/8114543/8207709/4c7997e4-14d1-11e5-9288-01f590d824b4.JPG)

**Comment by LukasReschke** [comment] 2015-06-17 13:15
This refers to the PHP cURL module which is then unlikely to be installed. On Debian systems: php5-curl

**Comment by LukasReschke** [comment] 2015-06-17 13:15
(8.2 will have a better check for this and enforces that cURL is available)

**Comment by affibox** [comment] 2015-06-17 13:21
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:09+00:00
Debug	lock	FREE: Released locks on /var/www/owncloud/data/files_encryption/pubShare_a544fc0c.privateKey	2015-06-17T13:08:47+00:00
Debug	lock	INFO: Released lock handle Resource id #255 on /var/www/owncloud/data/files_encryption/pubShare_a544fc0c.privateKey	2015-06-17T13:08:47+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.	2015-06-17T13:13:14+00:00
Debug	core	Adding default user backend WEBDAVAUTH.

**Comment by affibox** [comment] 2015-06-22 17:57
Any news regarding this problem?

**Comment by PVince81** [comment] 2015-07-16 15:23
Duplicate of https://github.com/owncloud/core/issues/17507
There's a bug with encryption.

**Closed by PVince81** 2015-07-16 15:23 UTC
Labels: app:files_external, bug, needs info
