### ISSUE TITLE
public link upload of large file happens 2x

### ISSUE THREAD

**Issue by CaptionF** [owncloud/core#17031] opened 2015-06-18 19:20 UTC
### Steps to reproduce
1. create via web interface folder in oC home as a oC user
2. create public link and allow upload of file
3. load large file (10 GB) through the public link upload functionality

### Expected behaviour
Tell us what should happen
the large file should be uploaded 1 time in the respective folder

### Actual behaviour
Tell us what happens instead
the file is uploaded 2x and at the end it is asked, which file the user wants to keep.

### Server configuration
**Operating system**:
SLES12
**Web server:**
Apache 2.4
**Database:**
Oracle RAC
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
8.0.3.4
**Updated from an older ownCloud or fresh install:**
previously 7.0.5
**List of activated apps:**
- no available
**The content of config/config.php:**

Due to enterprise prospect: logs are on #internal storage S3. ....

![doppleter upload](https://cloud.githubusercontent.com/assets/10551219/8239974/a7a73ec6-15ff-11e5-929f-135e74765507.PNG)

```

### Client configuration
**Browser:**
Firefox 38.0.5
**Operating system:**
Win7

**Comment by DeepDiver1975** [comment] 2015-06-19 06:31
Known issue. This is because of the conflict dialog AFAIK.  This will be fixed with 8.2

**Comment by PVince81** [comment] 2015-06-19 08:36
Duplicate of https://github.com/owncloud/core/issues/8664

@DeepDiver1975 how will it be fixed ? I'm not aware of any good solution yet.

**Comment by DeepDiver1975** [comment] 2015-06-19 08:46
> @DeepDiver1975 how will it be fixed ? I'm not aware of any good solution yet.

we will overhault that dialog handling as soon as we move to webdav. We basically can perform the conflict resolution on the client side by getting meta information about the existing file using PROPFIND

**Comment by bboule** [comment] 2015-06-19 11:24
I think we need to keep this open as a green ticket for tracking until we can set an expectation with the user @CaptionF how would you characterize the importance here?

**Comment by DeepDiver1975** [comment] 2015-06-19 11:32
@bboule we don't need two ticket foe one issue - I just added the green-ticket to #8664

**Closed by DeepDiver1975** 2015-06-19 11:32 UTC
Labels: bug, green-ticket, sharing

**Comment by bboule** [comment] 2015-06-19 12:42
Roger that  sorry for the confusion :)

**Comment by DeepDiver1975** [comment] 2015-06-19 13:43
> Roger that sorry for the confusion :)

no worries
