### ISSUE TITLE
Files In Folders Got Deleted After refresh .

### ISSUE THREAD

**Issue by hoho508** [owncloud/core#16389] opened 2015-05-18 07:08 UTC
Steps to reproduce
1. Rename a folders that has alot of small files 
2. While Cursor is spinning , Click on refresh 
3. 

### Expected behaviour
Folder got renamed 

### Actual behaviour
Folder got rename and it changes to 0bytes , all files got lost 

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
Fresh Install
**List of activated apps:**

Activity 1.2.0
Deleted files 0.6.2
File Locking
Mail Template Editor 0.1
Provisioning API 0.2
Share Files 0.6.1
Versions 1.0.5
 
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
No
```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome , IE , FireFox
**Operating system:**
Windows 7

**Comment by PVince81** [comment] 2015-05-18 08:02
Duplicate of #13391

**Closed by PVince81** 2015-05-18 08:02 UTC
