### ISSUE TITLE
Shared files as recipient can't be moved to external storage folders

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#14288] opened 2015-02-17 13:13 UTC
### Steps to reproduce

Having windows network drive or sharepoint enabled and one folder of them mounted:

1. User1 shares file1 with User2.
2. User2 tries to move file1 to a external storage folder.

### Expected behaviour
file1 is moved into a external storage folder.

### Actual behaviour
file1 can't be moved, and an alert is shown.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.8","versionstring":"8.0","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
Windows network drive or Sharepoint.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Logs
```
{"reqId":"L96WZ4vJbCRDKfGANGll","remoteAddr":"10.40.40.43","app":"admin_audit","message":"Rename \"\/ee13\/files\/Screen Shot 2015-02-04 at 09.38.33.png\" to \"\/ee13\/files\/WIN_FOLDER\/Screen Shot 2015-02-04 at 09.38.33.png\" by user ee13, owner: ser2","level":1,"time":"2015-02-17T13:12:27+00:00","method":"POST","url":"\/daily_13-02-15\/index.php\/apps\/files\/ajax\/move.php"}
{"reqId":"L96WZ4vJbCRDKfGANGll","remoteAddr":"10.40.40.43","app":"files","message":"It is not allowed to move one mount point into another one","level":0,"time":"2015-02-17T13:12:27+00:00","method":"POST","url":"\/daily_13-02-15\/index.php\/apps\/files\/ajax\/move.php"}

```

### Client configuration
Chrome.

**Comment by karlitschek** [comment] 2015-02-17 21:44
@icewind1991 @schiesbn any idea?

**Comment by PVince81** [comment] 2015-02-23 10:35
This is by design. You cannot move a shared folder on top of an external storage.
The log says "It is not allowed to move one mount point into another one".
Because: if we allow it, only the recipient would see that folder "floating" inside the external storage and the recipient will be confused why other people who have access to the ext storage don't see it.

The only bug here is that this message is supposed to appear in the web UI.

**Comment by rullzer** [comment] 2016-02-10 12:05
As said by @PVince81 this is by design. We basically do not allow nesting mount points since it can lead to all kinds of troubles 

I think we can close this..

**Comment by rullzer** [comment] 2016-02-19 09:27
Since this is by design => close.

**Closed by rullzer** 2016-02-19 09:27 UTC
Labels: app:files_external, bug, feature:sharing, sev4-low
