### ISSUE TITLE
s2s single file share + encryption, recipient cannot download

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13689] opened 2015-01-26 19:43 UTC
### Steps to reproduce
1. Enable encryption
2. Create two users "user1", "user2"
3. Login as "user1"
4. Create a text file "test.txt" with some contents
5. Share "test.txt" with "user2@localhost/owncloud" (change server/path accordingly, local works too)
6. Login as "user2" to accept the share (and refresh the page if necessary due to another bug)
7. Download "test.txt"

### Expected result
File can be downloaded.

### Actual result
File contains HTML page instead of real content. Excerpt:
```
<li class='error'>

                Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.              <br/>
                                <br/>
        </li>
```

### Versions
OC 8 git master (44d69d71780d94ab89f81e54ebf9ec23a5b04316)

@schiesbn @icewind1991 @DeepDiver1975 @karlitschek 

CC @jnfrmarks

**Comment by nickvergessen** [comment] 2015-01-27 10:45
Related #13700

**Comment by jnfrmarks** [comment] 2015-01-27 13:15
Duplicate of #13579

**Closed** 2015-01-27 13:29 UTC
Labels: app:files_encryption, bug, feature:server-to-server-sharing
