### ISSUE TITLE
Storage entry left behind when deleting a remote share

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#25130] opened 2016-06-16 07:28 UTC
1. Login with two users and check the `oc_storages` table
2. Create a remote share
3. As recipient accept the share
4. Check the `oc_storages` table
5. As recipient "unshare from self"
6. Check the `oc_storages` table
### Expected

The result of 6 and 4 are different, the `shared::` entry should be removed
### Actual

Stray entry is left behind

**Comment by PVince81** [comment] 2016-12-06 18:17
Closing as duplicate of https://github.com/owncloud/core/issues/15701

**Closed by PVince81** 2016-12-06 18:17 UTC
Labels: bug, feature:federated-cloud-sharing, sev3-medium
