### ISSUE TITLE
W: GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release: The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>

### ISSUE THREAD

**Issue by sjd4** [owncloud/core#37779] opened 2020-08-05 13:47 UTC
### Steps to reproduce
1. wget -nv https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Release.key -O Release.key
2. apt-key add - < Release.key
3. echo 'deb http://download.owncloud.org/download/repositories/production/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/owncloud.list
4. run apt-get update

### Expected behaviour
Tell us what should happen
Should complete

### Actual behaviour
Tell us what happens instead
Fails with error W: GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release: The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>

### Server configuration
**Operating system**:
Ubuntu 18.04

**Comment by sscotter** [comment] 2020-08-06 07:19
I'm also experiencing the same behavior on our Ubuntu 19.10 system this morning (may have been happening before then, I've not patched the system for about a month).

**Comment by nblomquist** [comment] 2020-08-06 13:20
I just saw this on my Ubuntu 18.04 server.

`The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>`

Same apt-key list as sscotter above.

**Comment by alexey601** [comment] 2020-08-06 13:47
I have the same problem. Removing and adding a key does nothing. Debian GNU/Linux 10

**Comment by gnuheidix** [comment] 2020-08-06 14:51
The issue is already being worked on. https://twitter.com/ownCloud/status/1291367851840937984

**Comment by flaviolenz** [comment] 2020-08-07 16:02
Any update?

**Comment by t0rzz** [comment] 2020-08-08 14:12
Confirmed as NOT working on Debian 10, official repo.

`W: Failed to fetch http://download.owncloud.org/download/repositories/production/Debian_10/Release.gpg  The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>`

**Comment by FabienLab** [comment] 2020-08-08 20:37
Same problem here on an odroid with ubuntu 18.04

**Comment by BlaiseThirard** [comment] 2020-08-09 13:06
Same problem on Debian 9.

```
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Hit:3 http://cdn-fastly.deb.debian.org/debian stretch Release
Hit:4 https://packages.sury.org/php stretch InRelease
Ign:2 https://attic.owncloud.org/download/repositories/production/Debian_9.0  InRelease
Get:6 https://download.owncloud.org/download/repositories/production/Debian_9.0  Release [977 B]
Get:7 https://download.owncloud.org/download/repositories/production/Debian_9.0  Release.gpg [481 B]
Ign:7 https://download.owncloud.org/download/repositories/production/Debian_9.0  Release.gpg
Get:8 https://download.owncloud.org/download/repositories/production/Debian_9.0  Packages [740 B]
Err:8 https://download.owncloud.org/download/repositories/production/Debian_9.0  Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:740 [weak]
   - SHA256:df738d714674184a7a669894d24470e3486fc8ffbb49a6f9280594ac3d42f54b
   - SHA1:ece10432d9c068bff915d3535230d197fb4ae142 [weak]
   - MD5Sum:29d83f6d4b9e353c881f19f606e01f18 [weak]
  Hashes of received file:
   - SHA256:229164d86faac30d657f4e5cdd6f81abde3bc3e03f077edfff1fd100881d19d8
   - SHA1:0eb2c4a75288879f02c7099a9194387eccfb904e [weak]
   - MD5Sum:cb5aa78e738975f1df6a3e93ba21119d [weak]
   - Filesize:740 [weak]
  Last modification reported: Fri, 24 Apr 2020 21:01:16 +0000
  Release file created at: Wed, 05 Aug 2020 03:29:47 +0000
Fetched 2198 B in 0s (3045 B/s)
Reading package lists... Done
W: GPG error: https://download.owncloud.org/download/repositories/production/Debian_9.0  Release: The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>
W: The repository 'http://download.owncloud.org/download/repositories/production/Debian_9.0  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://download.owncloud.org/download/repositories/production/Debian_9.0/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:740 [weak]
    - SHA256:df738d714674184a7a669894d24470e3486fc8ffbb49a6f9280594ac3d42f54b
    - SHA1:ece10432d9c068bff915d3535230d197fb4ae142 [weak]
    - MD5Sum:29d83f6d4b9e353c881f19f606e01f18 [weak]
   Hashes of received file:
    - SHA256:229164d86faac30d657f4e5cdd6f81abde3bc3e03f077edfff1fd100881d19d8
    - SHA1:0eb2c4a75288879f02c7099a9194387eccfb904e [weak]
    - MD5Sum:cb5aa78e738975f1df6a3e93ba21119d [weak]
    - Filesize:740 [weak]
   Last modification reported: Fri, 24 Apr 2020 21:01:16 +0000
   Release file created at: Wed, 05 Aug 2020 03:29:47 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ibcs01** [comment] 2020-08-11 15:12
Same problem here on Debian 10. 

```
root@server:~# aptitude update
Err https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg
  The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>
Get: 18 https://deb.liquidsoap.info/debian stable/main amd64 Packages [778 kB]
Fetched 1,482 kB in 3s (522 kB/s)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.owncloud.org/download/repositories/production/Debian_10  Release: The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>
W: Failed to fetch http://download.owncloud.org/download/repositories/production/Debian_10/Release.gpg: The following signatures were invalid: BADSIG 47AE7F72479BC94B ownCloud build service <obsrun@localhost>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by holgerfriedrich** [comment] 2020-08-11 22:54
With the latest update of the signature file, it seems to be resolved for Debian 10. Thanks a lot.

**Comment by t0rzz** [comment] 2020-08-12 00:44
> With the latest update of the signature file, it seems to be resolved for Debian 10. Thanks a lot.

What steps did you take to fix it?

**Comment by holgerfriedrich** [comment] 2020-08-12 05:27
> > With the latest update of the signature file, it seems to be resolved for Debian 10. Thanks a lot.
> 
> What steps did you take to fix it?

@t0rzz Sorry you got me wrong. Looking at the files in the repo, someone of the owncloud team seems to have updated the signature file. For me as a user, it now works fine to run `apt update`. Update to 10.5 worked as well.

**Comment by PitWenkin** [comment] 2020-08-12 05:48
Still not working on Ubuntu 18.4

> Get:8 https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release [980 B]
> Get:9 https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release.gpg [481 B]
> E: Repository 'https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release' changed its 'Origin' value from 'obs://s2.owncloud.com/ce:10.4/Ubuntu_18.04' to 'obs://s2.owncloud.com/ce:10.5/Ubuntu_18.04'
> E: Repository 'https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release' changed its 'Label' value from 'ce:10.4' to 'ce:10.5'
> N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
> Do you want to accept these changes and continue updating from this repository? [y/N] y
> Get:10 https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Packages [745 B]                                                                                                                                    
> Err:10 https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Packages                                                                                                                                            
>   File has unexpected size (741 != 745). Mirror sync in progress? [IP: 167.233.14.167 443]
>   Hashes of expected file:
>    - Filesize:745 [weak]
>    - SHA256:1ab6e5fbf236849993c9fa67bd3ecb36a637e2bd9f0c5205541f7d9c16dcd149
>    - SHA1:60c1b00f8e690d90f90bc897e464a673bc08360a [weak]
>    - MD5Sum:2873b5e9da8b4fd6c00b0cfa9123fbd2 [weak]
>   Release file created at: Wed, 05 Aug 2020 03:35:46 +0000
> Fetched 1,461 B in 17s (87 B/s)                                                                                                                                                                                                         
> Reading package lists... Done
> E: Failed to fetch https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Packages.gz  File has unexpected size (741 != 745). Mirror sync in progress? [IP: 167.233.14.167 443]
>    Hashes of expected file:
>     - Filesize:745 [weak]
>     - SHA256:1ab6e5fbf236849993c9fa67bd3ecb36a637e2bd9f0c5205541f7d9c16dcd149
>     - SHA1:60c1b00f8e690d90f90bc897e464a673bc08360a [weak]
>     - MD5Sum:2873b5e9da8b4fd6c00b0cfa9123fbd2 [weak]
>    Release file created at: Wed, 05 Aug 2020 03:35:46 +0000
> E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by t0rzz** [comment] 2020-08-12 05:49
> > > With the latest update of the signature file, it seems to be resolved for Debian 10. Thanks a lot.
> > 
> > What steps did you take to fix it?
> 
> @t0rzz Sorry you got me wrong. Looking at the files in the repo, someone of the owncloud team seems to have updated the signature file. For me as a user, it now works fine to run `apt update`. Update to 10.5 worked as well.

Nope, still not working. Signature key is still invalid.

**Comment by BlaiseThirard** [comment] 2020-08-12 06:36
I confirm that it works again on Debian 9. I just upgraded to Owncloud 10.5.

**Comment by gnuheidix** [comment] 2020-08-12 12:21
It looks like that at least one upstream server is serving the old signature file e.g. the [content](https://download.owncloud.org/download/repositories/production/Ubuntu_18.04/Release.gpg) of yoshi differs from luigi.

**Comment by sjd4** [comment] 2020-08-12 13:19
Seems to be working for me on Ubuntu 18.04 now.

**Comment by funlovin** [comment] 2020-08-12 14:04
same here

**Comment by alexey601** [comment] 2020-08-12 14:43
Debian 10 - Ok. Thanks!

**Comment by cbehren** [comment] 2020-09-14 08:04
This is an issue for me (Ubuntu 19.04)
> E: The repository 'http://download.owncloud.org/download/repositories/production/Ubuntu_19.04  Release' is not signed.
Is there a fix available?

**Comment by Kullid** [comment] 2020-10-13 21:49
Is there something I can do to get it working on Ubuntu 16.04?

**Comment by ho4ho** [comment] 2020-10-16 20:57
@cbehren @Kullid Found https://download.owncloud.org/download/repositories/production/owncloud/ by https://owncloud.com/download-server/ only lists 20.04, 19.10, 18.04. Not thinking fixing others by ownCloud.

**Comment by Phil-Rei** [comment] 2021-08-01 15:17
Also not working for me. Ubuntu 20.04 LTS with OwnCloud 10.5.0.10

Re-Adding Repo & Key doesn't work
https://download.owncloud.org/download/repositories/production/owncloud/

**Comment by CoolRunnerII** [comment] 2021-08-01 16:53
I also experience the same at the moment. Seems like the problem has returned after first being fixed

**Comment by ho4ho** [comment] 2021-08-01 18:46
https://central.owncloud.org/t/debian-10-badsig-apt-error/33286/2

**Comment by zerohack16** [comment] 2021-08-08 03:16
facing the same issue on ubuntu 20.04

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release: The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B

i have tried some others keys that people shared in this thread, but none is efective.

**Comment by t0rzz** [comment] 2021-08-08 22:02
Fix (remove previous repo first, it's in /etc/apt/sources.list.d/ in Debian):
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Debian_10/ /' | sudo tee /etc/apt/sources.list.d/isv:ownCloud:server:10.list
curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_10/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv_ownCloud_server_10.gpg > /dev/null
sudo apt update
sudo apt install owncloud-complete-files

**Comment by dliechty** [comment] 2021-08-09 00:07
I'm having the same problem as zerohack16. Also on Ubuntu 20.04. The only difference is that I am using the production/Ubuntu_20.04 repo URL, like so:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_20.04  Release: The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
W: Failed to fetch http://download.owncloud.org/download/repositories/production/Ubuntu_20.04/Release.gpg  The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by BWibo** [comment] 2021-08-10 07:49
Same here on Ubuntu 18.04:
I removed the repo and did a fresh setup from here: https://download.owncloud.org/download/repositories/production/owncloud/

But still this:

```
W: GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release: The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
E: The repository 'http://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release' is not signed.
```

**Comment by ho4ho** [comment] 2021-08-14 07:59
@BWibo @dliechty Looking to: https://github.com/owncloud/core/issues/37779#issuecomment-890568025

**Comment by BWibo** [comment] 2021-08-16 08:38
Thx, I can confirm this works for me.

**Comment by dliechty** [comment] 2021-08-16 15:01
Yes, me too, thanks. Upgrading from 10.5 posed a mild challenge as I had to clean up a bunch of 'extra files' that were causing an integrity check violation but other than that it was smooth sailing.

**Comment by JammingBen** [comment] 2021-09-21 12:29
Closing as the fix seems to work. You can re-open anytime if necessary.

**Closed by JammingBen** 2021-09-21 12:29 UTC
Labels: Type:Bug

**Comment by rnk-de** [comment] 2021-09-28 07:42
Seems to be still broken for Debian 10:

```
Err:11 https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg
  The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
```

**Comment by ho4ho** [comment] 2021-09-28 15:14
@rnk-de https://owncloud.com/news/owncloud-server-repositories-opensuse-obs/:

> As the ownCloud server packages now live at the public Open Build Service instance at opensuse.org, this means the old Linux server repositories (download.owncloud.org/download/repositories) **do not work anymore**.

**Comment by rnk-de** [comment] 2021-09-29 08:28
@ho4ho Thanks a lot for clarification - somehow I missed this official statement.
So I migrated to OBS repos an updated to 10.8 - worked like a charm. :)

**Comment by deftoner** [comment] 2021-11-27 17:49
Well, I'm using the directions from here: https://download.owncloud.org/download/repositories/production/owncloud/
And I still get
`Ign:9 https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release.gpg
Reading package lists... Done
W: GPG error: https://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release: The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
E: The repository 'http://download.owncloud.org/download/repositories/production/Ubuntu_18.04  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by ho4ho** [comment] 2021-11-27 18:49
@deftoner 

> Well, I'm using the directions from here: https://download.owncloud.org/download/repositories/production/owncloud/

From page:

> Attention: This repository is deprecated! Do not use!
> This Repository was last used with ownCloud server 10.7.0 -
> ownCloud server 10.8.0 and later are hosted at the public OBS of openSUSE.org
> 
> Please remove this repo from your system (see /etc/apt/sources.list.d/, /etc/yum.repos.d/ or /etc/zypp/repos.d/) and instead subscribe to
> https://software.opensuse.org//download.html?project=isv%3AownCloud%3Aserver%3A10&package=owncloud-complete-files
