### ISSUE TITLE
Unable to share any file when logged with a LDAP user

### ISSUE THREAD

**Issue by kettbi** [owncloud/core#23816] opened 2016-04-05 21:55 UTC
Hi,

I'm unable to share any file when logged with a LDAP user. 
No problem with users created with owncloud.

Sharing settings on admin page are correctly enabled

### Steps to reproduce
1. Configure owncloud with openLDAP
2. Log with a ldap user
3. try to share a file 

### Expected behaviour
Have the ability to create a shared link or share with another user

### Actual behaviour
sharing input is locked with the message "sharing is not allowed" 

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
fresh 

**Where did you install ownCloud from:**
Arhive File

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - files_w2g: 0.8.2.6
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.1
  - notifications: 0.2.3
  - ojsxc: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - user_external


```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occ7lpje9l2b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.fr"
        ],
        "datadirectory": "\/path\/to\/owncloud\/9rh3j8J3HG",
        "overwrite.cli.url": "http:\/\/my.domain.fr",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "loglevel": 1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "default_language": "fr",
        "defaultapp": "files"
    }
}

```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** openLDAP

#### LDAP configuration (delete this part if not used)

```
+-------------------------------+----------------------------------------------------------+
| Configuration                 |                                                          |
+-------------------------------+----------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                        |
| hasPagedResultSupport         |                                                          |
| homeFolderNamingRule          |                                                          |
| lastJpegPhotoLookup           | 0                                                        |
| ldapAgentName                 | cn=admin,dc=domain,dc=fr                               |
| ldapAgentPassword             | ***                                                      |
| ldapAttributesForGroupSearch  | ou                                                       |
| ldapAttributesForUserSearch   | uid                                                      |
| ldapBackupHost                |                                                          |
| ldapBackupPort                |                                                          |
| ldapBase                      | dc=domain,dc=fr                                        |
| ldapBaseGroups                | dc=domain,dc=fr                                        |
| ldapBaseUsers                 | ou=users-admin,dc=domain,dc=fr                         |
| ldapCacheTTL                  | 600                                                      |
| ldapConfigurationActive       | 1                                                        |
| ldapDynamicGroupMemberURL     |                                                          |
| ldapEmailAttribute            | mail                                                     |
| ldapExperiencedAdmin          | 0                                                        |
| ldapExpertUUIDGroupAttr       |                                                          |
| ldapExpertUUIDUserAttr        |                                                          |
| ldapExpertUsernameAttr        |                                                          |
| ldapGroupDisplayName          | ou                                                       |
| ldapGroupFilter               |                                                          |
| ldapGroupFilterGroups         |                                                          |
| ldapGroupFilterMode           | 0                                                        |
| ldapGroupFilterObjectclass    |                                                          |
| ldapGroupMemberAssocAttr      | memberUid                                                |
| ldapHost                      | localhost                                                |
| ldapIgnoreNamingRules         |                                                          |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(mail=%uid)(uid=%uid))) |
| ldapLoginFilterAttributes     | mail;uid                                                 |
| ldapLoginFilterEmail          | 0                                                        |
| ldapLoginFilterMode           | 0                                                        |
| ldapLoginFilterUsername       | 0                                                        |
| ldapNestedGroups              | 1                                                        |
| ldapOverrideMainServer        |                                                          |
| ldapPagingSize                | 500                                                      |
| ldapPort                      | 389                                                      |
| ldapQuotaAttribute            |                                                          |
| ldapQuotaDefault              |                                                          |
| ldapTLS                       | 0                                                        |
| ldapUserDisplayName           | displayname                                              |
| ldapUserDisplayName2          |                                                          |
| ldapUserFilter                | (|(objectclass=posixAccount))                            |
| ldapUserFilterGroups          |                                                          |
| ldapUserFilterMode            | 0                                                        |
| ldapUserFilterObjectclass     | posixAccount                                             |
| ldapUuidGroupAttribute        | auto                                                     |
| ldapUuidUserAttribute         | auto                                                     |
| turnOffCertCheck              | 0                                                        |
| useMemberOfToDetectMembership | 1                                                        |
+-------------------------------+----------------------------------------------------------+

```

### Client configuration
**Browser:** all (firefox / chrome / IE / Edge)

**Operating system:** windows 7 8 10

#### Web server error log
```
AH00687: Negotiation: discovered file(s) matching request: /path/to/owncloud/settings/admin (None could be negotiated).
AH01630: client denied by server configuration: /path/to/owncloud/9rh3j8J3HG/.ocdata
AH00687: Negotiation: discovered file(s) matching request: /path/to/owncloud/settings/admin (None could be negotiated).
```

#### ownCloud log (data/owncloud.log)
```
Error 	PHP 	OC\User\NoUserException: Backends provided no user object for myuser.name at /path/to/owncloud/lib/private/files/filesystem.php#387 	2016-04-05T21:42:28+00:00
Error 	files 	Backends provided no user object for myuser.name 	2016-04-05T21:42:28+00:00
Error 	PHP 	OC\User\NoUserException: Backends provided no user object for myuser.name at /path/to/owncloud/lib/private/files/filesystem.php#387 	2016-04-05T21:42:02+00:00
Error	PHP	OC\User\NoUserException: Backends provided no user object for myuser.name at /path/to/owncloud/lib/private/files/filesystem.php#387	2016-04-05T21:42:02+00:00
Error	files	Backends provided no user object for myuser.name	2016-04-05T21:42:02+00:00
Error	PHP	OC\User\NoUserException: Backends provided no user object for myuser.name at /path/to/owncloud/lib/private/files/filesystem.php#387	2016-04-05T21:42:02+00:00
Error	files	Backends provided no user object for myuser.name	2016-04-05T21:42:02+00:00
```

**Comment by ScottyTM** [comment] 2016-04-06 00:40
I know, stupid question, but did you allow sharing in the Admin interface?

**Comment by kettbi** [comment] 2016-04-06 07:04
Hi ScottyTM

> Sharing settings on admin page are correctly enabled

Yes it's done :)

**Comment by LukasReschke** [comment] 2016-04-06 08:27
cc @owncloud/ldap

**Comment by blizzz** [comment] 2016-04-06 10:29
Do you try to share from within an external storage?

**Comment by kettbi** [comment] 2016-04-06 12:00
No, I don't have external storage linked on my owncloud.

**Comment by scoopy2611** [comment] 2016-04-08 05:20
We have got the the same problem, after upgrading from 8.2.
OS: SLES 12
Php: 5.5.14
Mysql
Apache
no external storage
The link sharing from the desktop app is possible.

**Comment by kettbi** [comment] 2016-04-08 13:22
Ok so I will wait for the 9.0.1 available on the built-in updater.

**Comment by scoopy2611** [comment] 2016-04-12 12:37
the filesharing function in the webinterface stops working again. After the upgrade to 9.0.1 its works a few days until now :( we have made no further changes. The filesharing from the desktop app works.

**Comment by lucamemini** [comment] 2016-04-15 06:54
Same configuration, same problem... any update? 
thx! :-)

**Comment by lucamemini** [comment] 2016-04-15 08:13
uhuh... https://github.com/owncloud/mail/issues/1422

**Comment by kettbi** [comment] 2016-04-15 10:11
Thanks Lucamemini, when I disable the mail app, filesharing works for me ...

**Comment by olerichter** [comment] 2016-04-15 18:34
owncloud/mail#1422 -> disabling mail app and returning to roundcube also fixed it for me

**Comment by PVince81** [comment] 2016-04-19 13:20
@ChristophWurst are you able to reproduce this issue with mail app against v9.0.0 and v9.0.1 ?

**Comment by PVince81** [comment] 2016-04-19 13:20
Did you guys all update to v9.0.1 and is the problem still happening there, with or without mail app enabled ?

**Comment by lucamemini** [comment] 2016-04-19 13:40
hi,
with v9.0.1 the problem still exists... ONLY with LDAP users when app "mail" is enabled.

**Comment by PVince81** [comment] 2016-04-19 13:54
Tried with @ChristophWurst, could not reproduce.

Do you guys all have other third party apps enabled as well ? So far the mail app has no code that should be able to influence / disturb core, so this is still mysterious. Maybe there's yet another app causing side effects.

**Comment by PVince81** [comment] 2016-04-19 13:55
Which version of the mail app is it, just in case ?

**Comment by lucamemini** [comment] 2016-04-19 14:02
Enabled:
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.4.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - activity
  - encryption
  - external
  - files_external
  - files_videoplayer
  - rainloop
  - user_external

**Comment by lucamemini** [comment] 2016-04-19 14:11
Now i'm try to disable all apps (excpet: dav, vederatedfilesharing, files, file_sharing, mail and user_ldap), the problem persists.

**Comment by PVince81** [comment] 2016-04-19 14:17
@lucamemini so your problem is the same as OP and you see "Resharing not allowed" in the UI ?
Are you trying to reshare or is this not a reshare ? Trying to figure out the exact steps.

Do you also see `OC\User\NoUserException` in the logs, that could be a clue.

**Comment by lucamemini** [comment] 2016-04-19 14:27
Yep! the ui return "resharing not allowed" with ANY file on my home. I have this problem in both case (simple share to another user or reshare).

My log file:

```
{"reqId":"Rj2LM8rwQUE+jG1MTe5D","remoteAddr":"x.x.x.x","app":"files","message":" Backends provided no user object for lmemini","level":3,"time":"2016-04-19T14:17:47+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FPhotos&shared_with_me=true","user":"lmemini"}
{"reqId":"Rj2LM8rwQUE+jG1MTe5D","remoteAddr":"x.x.x.x","app":"PHP","message":"OC\\User\\NoUserException: Backends provided no user object for lmemini at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#387","level":3,"time":"2016-04-19T14:17:47+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json&path=%2FPhotos&shared_with_me=true","user":"lmemini"}
```

**Comment by lucamemini** [comment] 2016-04-19 14:33
when "click" share button my browser send 2 ajax request:

https://x.x.x.x/owncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FPhotos&shared_with_me=true
https://x.x.x.x/owncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FPhotos&reshares=true

for this request server return HTTP 200 OK but no data

**Comment by PVince81** [comment] 2016-04-19 14:35
@rullzer @blizzz any hints about the above error that could point at a way to reproduce this ?

**Comment by lucamemini** [comment] 2016-04-19 14:46
I think the problem is on this function (lib/private/user/manager.php)

```
        /**
         * get a user by user id
         *
         * @param string $uid
         * @return \OC\User\User|null Either the user or null if the specified user does not exist
         */
        public function get($uid) {
                if (isset($this->cachedUsers[$uid])) { //check the cache first to prevent having to loop over the backends
                        return $this->cachedUsers[$uid];
                }

                foreach ($this->backends as $backend) {
                        if ($backend->userExists($uid)) {
                                return $this->getUserObject($uid, $backend);
                        }
                }
                return null;
        }
```

**Comment by ChristophWurst** [comment] 2016-04-20 07:10
(copied from https://github.com/owncloud/mail/issues/1422#issuecomment-212289675):
> At least for me it only happens with ldap users, i will try to reproduce it from a plain installation this evening but i can't promise that have time to do it.
I am running on Debian, with apache 2.4.18 with php 7.0.5.

**Comment by lucamemini** [comment] 2016-04-21 07:23
Hi @ChristophWurst , 
My installation is on ubunutu 14.04.4, apache 2.4.7 & php 5.5.9

**Comment by olerichter** [comment] 2016-04-22 20:42
Sorry for the delay, I am sadly super busy and did not managed it earlier.
So I was able to reproduce the problem from a plain installation,
So thats what i did:
**Steps to reproduce:**

- Install a plain Debian stretch (testing).
- add the following to the apt sources: `deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/`
- Install packages: `apache2 php7.0 php7.0-ldap owncloud owncloud-deps-7.0 slapd`.
- run owncloud installation.
- create a user in ldap with the properties:
ObjectClasses: top, person, organizationalPerson, inetOrgPerson, shadowAccount
Attributs: cn, sn, uid, displayname, userPassword
- enable the owncloud apps: "LDAP user and group backend 0.8.0" and "Mail 0.4.2"
- enter the ldap config in owncloud:
localhost, cn=admin,dc=YOURHOSTNAME,dc=TLD, password you entered in the setup.

thats it,
log in as the ldapuser you created, and try to share => "resharing is not allowed"

disable mail app
=> sharing works fine

I also tested php5:
I disabled php7.0 and installed 'php5 php5-ldap owncloud-deps-5' 
wenn the mail app is enabeld => "resharing is not allowed"

hope it helps a little

**Comment by vadila2000** [comment] 2016-05-20 09:38
Hi, all. Sorry for English. Have the same problem after upgrade from 8.2.3 to 9.0.0 - 9.0.1 - 9.0.2
Enable Mail app -> Sharing not working
Disable Mail app -> Sharing works again.
I can provide virtual lab environment for testing purposes of any kind and catching the bug.
My server configs:
1. uname -a
3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
2. apachectl status
Server Version: Apache/2.4.7 (Ubuntu) mod_fastcgi/mod_fastcgi-SNAP-0910052141
mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.16 mod_python/3.3.1 Python/2.7.6 OpenSSL
3. mysqld --version
mysqld Ver 5.5.49-MariaDB-1ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))
4. php5 --version
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)
5. OwnCloud ver 9.0.2
6. sudo -u www-data bash -c "php occ app:list"
Enabled:

activity: 2.2.1
bookmarks: 0.7
calendar: 1.2.1
comments: 0.2
contacts: 1.2.0.0
dav: 0.1.6
direct_menu: 0.7.1
documents: 0.12.0
external: 1.2
federatedfilesharing: 0.1.0
federation: 0.0.4
files: 1.4.4
files_external: 0.5.2
files_mv: 0.8.2
files_pdfviewer: 0.8.1
files_sharing: 0.9.1
files_texteditor: 2.1
files_trashbin: 0.8.0
files_versions: 1.2.0
files_videoplayer: 0.9.8
firstrunwizard: 1.1
galleryplus: 15.0.0
music: 0.3.11
notifications: 0.2.3
ownnote: 1.08
provisioning_api: 0.4.1
systemtags: 0.2
templateeditor: 0.1
updatenotification: 0.1.0
user_external: 0.4
user_ldap: 0.8.0
Disabled:

encryption
gallery
news
{ "system": { "instanceid": "ocva2kfacx7s", "passwordsalt": "REMOVED SENSITIVE VALUE", "secret": "REMOVED SENSITIVE VALUE", "trusted_domains": [ "localhost", "REMOVED SENSITIVE VALUE" ], "datadirectory": "REMOVED SENSITIVE VALUE"", "overwrite.cli.url": "REMOVED SENSITIVE VALUE", "dbtype": "mysql", "version": "9.0.2.2", "dbname": ""REMOVED SENSITIVE VALUE"", "dbhost": "localhost", "dbtableprefix": "oc_", "dbuser": "REMOVED SENSITIVE VALUE", "dbpassword": "REMOVED SENSITIVE VALUE", "logtimezone": "UTC", "installed": true, "ldapIgnoreNamingRules": false, "mail_smtpmode": "smtp", "mail_smtpsecure": "tls", "mail_from_address": "REMOVED SENSITIVE VALUE"", "mail_domain": "skgpstroy.ru", "mail_smtpauthtype": "LOGIN", "mail_smtpauth": 1, "mail_smtphost": "mail.skgpstroy.ru", "mail_smtpport": "587", "mail_smtpname": "REMOVED SENSITIVE VALUE", "mail_smtppassword": "REMOVED SENSITIVE VALUE", "maintenance": false, "loglevel": 1 } }

**Comment by PVince81** [comment] 2016-07-18 14:17
Fixed by https://github.com/owncloud/core/pull/25126

Basically was an app loading order issue that was triggered by the mail app.

**Closed by PVince81** 2016-07-18 14:17 UTC
Labels: app:user_ldap, bug, feature:sharing, sev3-medium
