### ISSUE TITLE
Allow config.php contents to live outside of the OC installation directory

### ISSUE THREAD

**Issue by stevewi** [owncloud/core#8953] opened 2014-06-09 16:43 UTC
Pretty self-explanatory:  Mine looks like this:

config.php:

     require_once '/the/absolute/path/to/config.php';

You already do this for the database and this could be handled at installation.  config.php contains sensitive information that could allow a site to be compromised if a hacker got his hands on it.

**Comment by MorrisJobke** [comment] 2015-10-12 15:38
Duplicate of #11843

**Closed by MorrisJobke** 2015-10-12 15:38 UTC
Labels: enhancement
