### ISSUE TITLE
Deleting a file in a Google Drive Mount throws an error

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#40802] opened 2023-05-21 13:21 UTC
### Steps to reproduce
1. Delete a file from a Google Drive Mount (web or local with client)
2. The file gets deleted from GD
3. An error log entry appears

### Expected behaviour
No error log entry

### Actual behaviour
An error log entry gets created abou an `undefined variable: removedParent`:
```
Undefined variable: removedParent at \/var\/www\/owncloud\/apps\/files_external\/lib\/Lib\/Storage\/Google.php#507

\/remote.php\/dav\/files\/user_x\/ScanSnap@gd\/20230329_aPRES5%E1%BB%8B.pdf
```

### Server configuration
**Operating system**: U20.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.7

**ownCloud version:** 10.12.1

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):** no issues

**Are you using external storage, if yes which one:** smb/gd

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

@pako81 @jnweiger

**Comment by phil-davis** [comment] 2023-05-21 13:29
Issue #40777 was fixed by PR #40783 - but that looks like a different problem.

**Comment by mmattel** [comment] 2023-05-21 15:09
As you said, looks like related to the GD API update introduced with 10.12

**Comment by mmattel** [comment] 2023-05-22 11:31
Possibly true that you did not ran into the error, which does not mean that the cause does not exists as an owncloud error log entry is thrown. Looking into `Google.php` at about line 487 which is the only location where `removedParent` is defined:

```
if ($parentFolder2) {
    $removedParent = $parentFolder1->getId();
    $addedParent = $parentFolder2->getId();
} else {
```
and down at about line 507 where it is used:
```
$result = $this->service->files->update($file->getId(), $toUpdate, [
    'fields' => $this->getDefaultFieldsForFile(),
    'addParents' => $addedParent,
    'removeParents' => $removedParent
]);
```
This means, that if `parentFolder2` is empty, `removedParent` (and `addedParent`) will never be defined. If I am not wrong and to fix the problem, there should be on top at the function a variable definition so they are not undefined.

**Comment by pako81** [comment] 2023-05-22 12:16
sure, I rather meant we need consistent steps to reproduce so we can understand why/where it is failing and hopefully fix it. Wondering how the `rename` method kicks in here..we probably need the full stack trace.

**Closed** 2023-05-31 15:27 UTC
