### ISSUE TITLE
Make it possible to edit files in shared view

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#15491] opened 2015-04-08 21:27 UTC
### Steps to reproduce

1. Open the shared tab
2. Click on a file to edit

### Expected result
File should go to edit mode

### Actual behavior
File gets downloaded.

### Why?
This means that you have to go to the Files app instead, to edit documents such as .php, .txt files which I think is totally unnecessary.

Favorites solves it partially but it's not optimal. It could be enhanced.

CC @owncloud/designers

**Comment by MorrisJobke** [comment] 2015-04-08 21:59
Duplicate of https://github.com/owncloud/files_texteditor/issues/17

**Comment by MorrisJobke** [comment] 2015-04-08 21:59
ref #13273

**Closed by MorrisJobke** 2015-04-08 21:59 UTC
Labels: enhancement - proposed
