### ISSUE TITLE
Video thumbnails not generated since 7.0.3

### ISSUE THREAD

**Issue by fxshpac** [owncloud/core#14316] opened 2015-02-18 07:01 UTC
It was working in 7.0.2 but since 7.0.3 the mp4 files i uploaded only show default icons. The same is true for 7.0.4 and 8.0 as well.

All these versions were installed on Ubuntu Server 14.04.1 LTS. I also made sure libav-tools (ffmpeg equivalent in Ubuntu) is installed and avconv is working. Lastly I added line 'enable_previews' => true, to config.php and restarted apache2 afterwards.

It appears only video files are affected and image files are showing thumbnails correctly. In owncloud.log, I can see thumbnail related logs when a jpg file is being uploaded but nothing such is seen when a mp4 file is being uploaded.

I wonder if this is a known issue and if so it's on radar being addressed. Thx.

**Comment by RealRancor** [comment] 2015-02-18 07:51
Hi,

since some versions thumbnails/previews like the video needs to be explicitly enabled in your config.php:

http://doc.owncloud.org/server/7.0/admin_manual/configuration/config_sample_php_parameters.html#previews

**Comment by fxshpac** [comment] 2015-02-18 14:05
Thx @RealRancor for pointing me to the document. I updated my config.php to look like the one below and restarted apache2. Still I don't see no effect while uploading a MP4 video and owncloud.log show no sign of processing thumbnail for that either. Please let me know if you have further instructions.

<snip>
  'enable_previews' => true,
  'enabledPreviewProviders' => array(
          'OC\Preview\Image',
          'OC\Preview\MP3',
          'OC\Preview\TXT',
          'OC\Preview\MarkDown',
          'OC\Preview\Movies'
  ),
<snip>

**Comment by fxshpac** [comment] 2015-02-18 14:13
I make it working after checking the source code preview.php where instead of 'OC\Preview\Movies' it expects 'OC\Preview\Movie' with no letter s at the end of word 'Movie'. Guess the document needs to be update to reflect that if you will.

**Comment by RealRancor** [comment] 2015-02-18 15:02
Ah, you're right. Seems this is already fixed in master/stable8 but was not backported to OC7: https://github.com/owncloud/core/pull/12313

Maybe you could ask in the PR above for a backport to stable7.

**Comment by fxshpac** [comment] 2015-02-18 19:46
Checking the 7.0.4 version of Preview.php it is still using Movies instead of Movie. Therefore at least the 7.0 version document is in line with that.

Besides, while video thumbnails are now showing in web interface they are not in the Android app (1.6.2). Before I raise an issue with Android I just want to make sure the behavior is not core related.

**Comment by RealRancor** [comment] 2015-02-18 20:03
Hi,

the problem is the Class name is still "Movies" instead of "Movie" in stable7 (upcoming 7.0.5):

https://github.com/owncloud/core/blob/stable7/lib/private/preview/movies.php#L34

and also in 7.0.4:

https://github.com/owncloud/core/blob/v7.0.4/lib/private/preview/movies.php#L34

So the linked PR needs to be backported to get this fixed.

**Comment by MorrisJobke** [comment] 2015-03-18 16:13
Is fixed in 7.0.5 #14425

**Closed by MorrisJobke** 2015-03-18 16:13 UTC
Labels: Backport-Request, bug
