### ISSUE TITLE
How is working "create" right ?

### ISSUE THREAD

**Issue by christianlx** [owncloud/core#15000] opened 2015-03-18 14:08 UTC
Hi,

I'm testing share with special rights and I've a strange behaviour with the create option. I'de like to share a directory with another user. I'd like he can read and modify my files but not add or delete in this directory.

I share with "can modify" an "can update" and I've disabled delete and create.

The user can view my file, he can't delete or add something but he can't modify the existing files.

Is it a bug or something I misunderstand ?

I've already check some components related to webdav errors : 

- Synchronisation is working
- I have not 403 id errors
- I have not the message "server is not set properly"
- rewrite module is enabled
- no another webdav component activated
- litmus does not report any error
- SELinux is disabled

My problem is only with the create right with sharing a directory.

Here's the template : 

### Steps to reproduce
User A share a directory with user B. With the following rights : can edit, can modify. can create is disabled
A txt file is inside the directory

### Expected behaviour
User B should be able to modify the existing txt file created by A. He should not be able to synchronise a new file.

### Actual behaviour
With the Owncloud Client : B user cannot modifiy the file (could not write file content)
If the file is modified with Web interface, the file is duplicated with a "conflict" version in the B OC client 

### Server configuration
**Operating system**:
CentOS 6.6
**Web server:**
apache
**Database:**
MySQL
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
7.0.4. also tested on my test server with 7.0.5. I'm using repos
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Basics (File, Calendar, Contacts) and LDAP module
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc831c5ec663',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => 'gmhcloudtest',
    1 => 'gmhcloudtest.xxxxxx',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'https://gmhcloudtest/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.5.2',
  'dbname' => 'OWNCLOUD',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_adm-owncloud',
  'dbpassword' => 'xxxxxxx',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'mail_domain' => 'xxxxx.com',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'xxxx',
  'mail_smtpport' => 587,
  'mail_smtpauth" => true,
"mail_smtpname' => 'xxxx',
  'mail_smtppassword' => 'xxxx',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'theme' => '',
  'maintenance' => false,
);

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Users log with Active Directory Account
#### LDAP configuration (delete this part if not used)

```

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 7 to 8.1
### Logs
#### Web server error log
No error in the log
```

#### ownCloud log (data/owncloud.log)
the following when trying to synchronise the modified file

{"app":"webdav","message":"Sabre\\DAV\\Exception: Could not write file contents","level":4,"time":"2015-03-18T07:46:22+00:00"}

```
Regards, 

Christian

**Comment by DeepDiver1975** [comment] 2015-03-18 15:15
@dragotin something we should have a look at together

**Comment by PVince81** [comment] 2015-03-19 21:05
Okay, so you've shared the folder with only "can change" enabled.

Duplicate of https://github.com/owncloud/core/issues/13193

**Closed by PVince81** 2015-03-19 21:05 UTC
Labels: triage

**Comment by christianlx** [comment] 2015-03-20 09:59
I shared the folder with can change an can edit. Here's the print screen. Gui is in french but you should understand.
![occreate](https://cloud.githubusercontent.com/assets/10811230/6749397/17d9e6e6-cef0-11e4-9d78-3427beacbe86.jpg)

**Comment by PVince81** [comment] 2015-03-20 10:01
Yes. Actually the checkbox "can edit (édition autorisée)" is only there to automatically check or uncheck "create", "update" and "delete" at once. It's not a separate permission.

The real permission is the one on the last row, in your case "update (édition autorisée)" :smile:

**Comment by christianlx** [comment] 2015-03-20 10:13
OK, thanks for the explanation.

In my case, I just don’t understand the problem. Is it a bug or a feature not yet implemented ?

 

 

 

De : Vincent Petry [mailto:notifications@github.com] 
Envoyé : vendredi 20 mars 2015 11:02
À : owncloud/core
Cc : Christian Julia
Objet : Re: [core] How is working "create" right ? (#15000)

 

Yes. Actually the checkbox "can edit (édition autorisée)" is only there to automatically check or uncheck "create", "update" and "delete" at once. It's not a separate permission.

The real permission is the one on the last row, in your case "update (édition autorisée)"   <https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png>

**Comment by PVince81** [comment] 2015-03-20 10:27
It's a bug, see https://github.com/owncloud/core/issues/13193

A fix is in the works here https://github.com/owncloud/core/pull/13802
