### ISSUE TITLE
APC isn't properly cleanup after enabling / disabling apps from the command-line

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15359] opened 2015-04-01 13:19 UTC
### Steps to reproduce
1. Make sure you have installed APC in ownCloud (checked with APCu installed php5-apc package in ubuntu 14.04)
2. Go to the settings apps (enabled section) and then change to the disabled section
3. From the command-line enable a disabled app
4. Go to the settings apps - enabled section

### Expected behaviour
App should appear as enabled

### Actual behaviour
App still shows as disabled

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.4

**ownCloud version:** OC 8.0.3RC1

**Updated from an older ownCloud or fresh install:** fresh install

### APC configuration (from phpinfo page)
```
APC support 	Emulated

apcu
APCu Support	enabled
Version 	4.0.2
APCu Debugging 	Disabled
MMAP Support 	Enabled
MMAP File Mask 	no value
Serialization Support 	php, eval
Revision 	$Revision: 328290 $
Build Date 	Feb 19 2014 09:18:08

Directive	Local Value	Master Value
apc.coredump_unmap	Off	Off
apc.enable_cli	On	On
apc.enabled	On	On
apc.entries_hint	4096	4096
apc.gc_ttl	3600	3600
apc.mmap_file_mask	no value	no value
apc.preload_path	no value	no value
apc.rfc1867	Off	Off
apc.rfc1867_freq	0	0
apc.rfc1867_name	APC_UPLOAD_PROGRESS	APC_UPLOAD_PROGRESS
apc.rfc1867_prefix	upload_	upload_
apc.rfc1867_ttl	3600	3600
apc.serializer	php	php
apc.shm_segments	1	1
apc.shm_size	32M	32M
apc.slam_defense	On	On
apc.smart	0	0
apc.ttl	0	0
apc.use_request_time	On	On
apc.writable	/tmp	/tmp
```
You'll need to wait until the cache expires

**Comment by LukasReschke** [comment] 2015-04-01 13:21
Needs to call https://github.com/owncloud/core/blob/0af2dc7d3775f5d40cdfd3fe0cd4325abd6ce40d/settings/ajax/disableapp.php#L34-L36 then

**Comment by nickvergessen** [comment] 2015-04-01 13:27
Should do that in `OC_App::disable()` actually

**Comment by jvillafanez** [comment] 2015-05-06 09:26
It still happens in 8.1 alpha 3.

I think it might be because the cli uses another different php.ini file, or it doesn't access to the same memory segments

**Comment by Xenopathic** [comment] 2015-05-06 09:37
@jvillafanez Yes, very often the CLI has a different cache to the web server, but there's very little we can do about this. The best we could do is register a background job that gets run ASAP to clear the caches, but this only works if the system is using webcron and not system cron. Alternatively, we could try to send an HTTP request to the server (with some magical token) to clear the caches, but the complexity quickly becomes unmanageable.

**Comment by jvillafanez** [comment] 2015-05-06 09:55
Giving ideas, I'd probably use some kind of notification system. For example, a table in the DB which holds tickets that the apps should read at some point. In this scenario, the cli leaves behind a "ticket" saying "you need to clear the cache" to the apps page; the next time the page loads, it reads the ticket and clear the cache.

I think the system is easy, but I'm not sure if it will work with APC as the page is still cached automatically.

Anyway, I expect this problem is only related to APC and not other cache mechanism as redis or memcached (hopefully).

**Comment by Xenopathic** [comment] 2015-05-06 09:57
@jvillafanez That's effectively how the background job system works :smile: But again, the problem is whether background jobs are being triggered via webcron or system cron.

**Comment by nickvergessen** [comment] 2015-05-06 10:37
My suggestion is to just not cache that list on remote/distributed, so explicit use `createLocal()`.
That would solve the issue, right?

**Comment by LukasReschke** [comment] 2015-05-06 11:13
> My suggestion is to just not cache that list on remote/distributed, so explicit use createLocal().

APCu is local. I suspect `apc.enable_cli=1` is not set – worth a try.

**Comment by Xenopathic** [comment] 2015-05-06 12:31
@LukasReschke Even if APCu is enabled for the CLI, it will use a different cache than the web server or FPM - there is no way around this without telling the web server to execute the code itself.

**Comment by nickvergessen** [comment] 2015-05-06 12:36
@Xenopathic or use a different cache for this feature? But then again, we might run into the problem with other features aswell?

**Comment by Xenopathic** [comment] 2015-05-06 12:58
The cache backend is specified by the admin, and it would be ridiculous not to support APCu. This is just one of the things that happens with memcaches... it's probably not limited to the app disabling code either - anything that affects cached data will hit this bug at one point or another. The admin just needs to know to clear all caches when performing changes like this.

**Comment by jvillafanez** [comment] 2015-05-06 16:08
FYI, XCache present the same behaviour

**Comment by karlitschek** [comment] 2015-05-06 19:07
@nickvergessen How hard is it to add an expire cache call here?

**Comment by nickvergessen** [comment] 2015-05-07 06:48
@karlitschek we have one in place, but as stated above CLI an web UI use two different caches. So we can't expire one from the other

**Comment by jvillafanez** [comment] 2015-05-07 09:06
It's working with Memcached and probably with redis (I cannot test with redis right now). It's probably not recommended to use those caches for storing local data though, they are expected to perform a bit slower than APCu or XCache for these things.

**Comment by Xenopathic** [comment] 2015-05-07 12:17
We really have two options:

1. Explicitly tell the admin to clear caches from the web frontend to see their changes that were made on by the CLI; a 'Clear memcaches' button in the admin section would be quite nice for this, ref https://github.com/owncloud/core/issues/13658#issuecomment-71390263 (milestone 8.2)

2. Have an DB value that is checked on every web request and clears memcaches if set - the CLI simply sets this value when it wants caches cleared.

**Comment by nickvergessen** [comment] 2015-05-07 12:24
Or number three: https://github.com/owncloud/core/issues/16140#issuecomment-99788622

**Comment by LukasReschke** [comment] 2015-05-07 12:36
> Or number three: #16140 (comment)

Which would still mean that we have this problem as well in other cases, for example the LDAP users might get cached and we might have a command in the future to disallow users to login etc…

Option 1 from @Xenopathic and a hint in the CLI tool after the command finished seems like a sensible option to me.

**Comment by DeepDiver1975** [comment] 2015-06-02 12:18
What is the current cache timeout we use for the apps page?

@LukasReschke you know this by chance? THX

**Comment by LukasReschke** [comment] 2015-06-02 12:22
> What is the current cache timeout we use for the apps page?
> @LukasReschke you know this by chance? THX

300 seconds – https://github.com/owncloud/core/blob/ba52f6f8fc0d88000332e9e64c48a56c526823d9/settings/controller/appsettingscontroller.php#L242

**Comment by DeepDiver1975** [comment] 2015-06-22 14:11
From my understanding we need to properly document this behavior - not much we can do in the scope of 8.1

summoning @carlaschroder for docs - THX

**Comment by carlaschroder** [comment] 2015-06-22 15:05
I know exactly what to do. I'll make a cool graph full of nested if-elses!

**Comment by Xenopathic** [comment] 2015-06-25 20:45
@cmonteroluque Not fixed yet :/

Let's keep this issue open to track the implementation of a 'Clear memcaches' button.

**Comment by MorrisJobke** [comment] 2015-08-21 13:01
Fix is in #18475

**Comment by PVince81** [comment] 2015-09-18 11:10
PR's milestone was moved to 9.0 by @DeepDiver1975, moving the ticket's milestone accordingly.

**Comment by MorrisJobke** [comment] 2015-11-03 12:38
As a sum up to what was discussed in #18475:

* we don't want the clear cache button
* we want to set a value in config.php that indicates "clear cache" after app management stuff done in occ or web UI
* we will invalidate if the value in config.php is set on each app management request/occ call

**Comment by PVince81** [comment] 2016-06-01 14:20
Any update ? Is this still the approach we want or are there new ideas ?

**Comment by DeepDiver1975** [comment] 2016-08-29 17:24
this is still a work-as-designed case - see https://github.com/owncloud/core/issues/15359#issuecomment-114119173 -> close

**Closed by DeepDiver1975** 2016-08-29 17:24 UTC
Labels: 3 - To Review, bug, settings:apps, sev2-high
