### ISSUE TITLE
Broken webserver returning empty content length for non-empty file on resume

### ISSUE THREAD

**Issue by daniel569** [owncloud/core#27039] opened 2017-01-26 10:08 UTC
### Steps to reproduce
1. A lot of files on the cloud in synced folders. One day the client cant sync several files anymore, they produce the client-errormessage: Broken webserver returning empty content length for non-empty file on resume
2. The client stops syncing because of too many failures.
3. The file cant be downloaded in Firefox because of no filesize, Chrome saves the file and it can be opened without problems.
4. When uploaded again in the browser, the filesize is correct and the client can synchronize again, but with growing number of errors this cant be handled anymore.
5. Scanning the users files via occ does not solve the problem.
6. the problem seems not manually reproducible, it happens on different files, types and from time to time.

### Server configuration
**Operating system**: Debian 8.7

**Web server:** Apache 2.4.10

**Database:** MariaDB 10.0.29

**PHP version:** PHP 7.0.15-1

**ownCloud version:** v8.2.9

**Updated from an older ownCloud or fresh install:** Updated several times

**Where did you install ownCloud from:** owncloud.com download

**List of activated apps:**
Enabled:
  - activity: 2.1.4
  - encryption: 1.1.0
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - external
  - files_antivirus
  - files_external
  - notifications
  - provisioning_api
  - user_external
  - user_ldap

**The content of config/config.php:**
    "system": {
        "instanceid": "oc338s0d1i80",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "\/mnt\/***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.9.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "theme": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "activity_expire_days": 93,
        "log_rotate_size": "524288000",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** several: Firefox, Chrome

**Operating system:** several: Windows, Ubuntu

#### Web server error log
the webserver does not log any errors on this matter

#### ownCloud log (data/owncloud.log)
also owncloud does not log anything on this matter, loglevel  = 0

**Comment by PVince81** [comment] 2017-01-27 07:50
The first question is why the file has no filesize.

- Please check what the size is in oc_filecache: `select * from oc_filecache where path like '%thefilename%'`
- Does the file have the "encrypted" flag set ?
- Is this a shared file ?

Note that we have automated tests for range request downloads of encrypted files and they pass, so it could also be related to your environment that might not forward the range headers properly.

**Comment by daniel569** [comment] 2017-01-30 09:01
Hello PVince81 and thanks for your reply.

- The filesize in the oc_filecache is 47224, the webinterface shows 46kb and the effective size is 28.5kb.
- The 'encrypted' value in the oc_filecache is '0'.
- Its not a shared file.

It seems to me that  the files have the encrypted filesize in the oc_filecache instead of the unencrypted filesize.

**Comment by PVince81** [comment] 2017-01-30 09:15
Ok, then you have broken files likely from a restored backup.

Set the "encrypted" flag manually to 1 then redownload the file twice. That should repair it.

Duplicate of https://github.com/owncloud/core/issues/18225

**Closed by PVince81** 2017-01-30 09:15 UTC
Labels: needs info
