### ISSUE TITLE
Remote Sharing not working as expected

### ISSUE THREAD

**Issue by Tobus** [owncloud/core#21395] opened 2015-12-30 09:49 UTC
### Steps to reproduce
1. Go to OC1 and add user access to a folder via Federated-Cloud-ID of OC2
2. Open OC2 and accept the invitation
3. Open Files at OC2
### Expected behaviour

Remote folder of OC1 should be shown
### Actual behaviour

Nothing appears
### Server configuration

OC2:
Ubuntu 14.04.3 LTS

**Web server:**
Apache/2.4.7

**PHP version:**
PHP 5.5.9

**ownCloud version:**
OC 8.2.2 new installation

Enabled:
- activity: 2.1.3
- announcementcenter: 1.0.0
- calendar: 0.8.1
- contacts: 0.5.0.0
- documents: 0.11.0
- encryption: 1.1.0
- files: 1.2.0
- files_external: 0.3.0
- files_pdfviewer: 0.7
- files_sharing: 0.7.0
- files_texteditor: 2.0
- files_trashbin: 0.7.0
- files_versions: 1.1.0
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 14.2.0
- mail: 0.2.1
- music: 0.3.8
- notifications: 0.1.0
- provisioning_api: 0.3.0
- templateeditor: 0.1

Disabled:
- external
- news
- user_external
- user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '_',
  'passwordsalt' => '_',
  'secret' => '_',
  'trusted_domains' => 
  array (
    0 => '_',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '_',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '_',
  'dbpassword' => '_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '_',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '_',
  'mail_smtpport' => '_',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '_',
  'mail_smtppassword' => '_',
  'cache_path' => 'data/$user/cache',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

Chrome

**Operating system:**
Windows 10
#### ownCloud log (data/owncloud.log)

"reqId":"4d6ajFMVV1mpQxtgbh6V","remoteAddr":"","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-29T14:33:09+00:00"}
{"reqId":"X0LwYyFqWvpneNhK2ucK","remoteAddr":"ip","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-29T14:33:09+00:00"}
{"reqId":"njz+JtfuJ9ZUlrHmzupy","remoteAddr":"ip","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-29T14:43:19+00:00"}
{"reqId":"bHMCS9TxUGOjCU8wQ9L4","remoteAddr":"ip","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-29T14:45:17+00:00"}
{"reqId":"ip5OiekUIZQtFhO5Uofq","remoteAddr":"ip","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-29T15:40:11+00:00"}
{"reqId":"HVnp9LbYI2ZQR8KXwRMl","remoteAddr":"ip","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-29T16:03:12+00:00"}
{"reqId":"WcP5ufNaEfAB5j8AdRTu","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T08:43:48+00:00"}
{"reqId":"b\/hnARJ7u7cJ6uvbhvKb","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T08:44:39+00:00"}
{"reqId":"ObbLU3ioGVbP0aZwC0BT","remoteAddr":"ip2","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '\\/var\\/run\\/mysqld\\/mysqld.sock' (2)\",\"Exception\":\"Sabre\\DAV\\Exception\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \\/var\\/www\\/owncloud\\/remote.php(68): Sabre\\DAV\\Server->exec()\n#5 \\/var\\/www\\/owncloud\\/remote.php(140): handleException(Object(Doctrine\\DBAL\\DBALException))\n#6 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/remote.php\",\"Line\":66}","level":4,"time":"2015-12-30T08:52:29+00:00"}
{"reqId":"LJxlphsitZfHJqR45MtE","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:06:26+00:00"}
{"reqId":"cVVugod5SH4xDWXWswjG","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:06:39+00:00"}
{"reqId":"mR5dQmOKXYFMfqEaTIa8","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:14:21+00:00"}
{"reqId":"UJpidgoKXpM47SWzAnt9","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:14:30+00:00"}
{"reqId":"Vw\/05MSjfZrpg5STV3Ja","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:21:34+00:00"}
{"reqId":"GkexKd8MkSlmUHU9DuD9","remoteAddr":"ip2","app":"core","message":"Login failed: 'admin' (Remote IP: 'ip2')","level":2,"time":"2015-12-30T09:22:11+00:00"}
{"reqId":"3a2vYwb54\/xfkrbpVVb3","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:22:24+00:00"}
{"reqId":"QieV7nc2e3Mv8EdOFsHQ","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:30:00+00:00"}
{"reqId":"jGRMDpZQjpTudNs5Fn7c","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:31:00+00:00"}
{"reqId":"3TRA1D3H4ZD1TlXJjSoC","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:31:00+00:00"}
{"reqId":"3TRA1D3H4ZD1TlXJjSoC","remoteAddr":"ip2","app":"PHP","message":"OCP\Files\StorageNotAvailableException:  at \/var\/www\/owncloud\/apps\/files_sharing\/lib\/external\/storage.php#258","level":3,"time":"2015-12-30T09:31:00+00:00"}
{"reqId":"n4wwOX0LSIzYrddixcAo","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:31:02+00:00"}
{"reqId":"USWzC58+o1tZVcOPSWHN","remoteAddr":"ip2","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/owncloud\/lib\/private\/files\/filesystem.php#464","level":3,"time":"2015-12-30T09:31:03+00:00"}
{"reqId":"MgqeuK6e5hgespk+vN\/b","remoteAddr":"ip2","app":"core","message":"Exception while scanning storage \"shared::2099e8509322e12989ff938ca9338ac5\": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate","level":3,"time":"2015-12-30T09:31:05+00:00"}

**Comment by aspdye** [comment] 2015-12-30 09:53
Your config.php and also some Information of the Instance "oc1" :)

**Comment by Tobus** [comment] 2015-12-30 09:56
I will post the information about OC1 asap ....

**Comment by rullzer** [comment] 2015-12-30 12:18
The issue is the self signed certificates (as your logs tell you).
Basically OC1 and OC2 don't trust each others certificates.

**Comment by karlitschek** [comment] 2015-12-30 14:51
I think we should have better information in the UI if there is a problem with the certs.
What do you think @schiesbn @LukasReschke @jancborchardt

**Comment by jancborchardt** [comment] 2015-12-30 18:48
This is probably something we should show at the ownCloud instance which has the problematic cert. Then the admin there can fix it. Or should we have a way to accept shares when there is a cert problem as well?

**Comment by Tobus** [comment] 2015-12-30 19:12
May the better option is, to give the administrator the choice, if he wants to accept the certificate or not.

**Comment by Tobus** [comment] 2015-12-30 20:00
We adapted our certificates, now its working fine.

Thanks a lot for the support!

**Comment by aspdye** [comment] 2015-12-30 20:49
Maybe we could solve this via Frontend (TLS Root Certificate Import for Admins) as already done with External Storages :wink:

**Comment by Tobus** [comment] 2015-12-31 09:21
Sorry, i have to reopen the issue.
Now I can see the remote folder, but can not download the content.

Exception: {"Message":"Error creating resource: [message] fopen(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed\n[file] \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n[message] fopen(): Failed to enable crypto\n[file] \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n[message] fopen(https:\/\/www.fu-tech.net\/owncloud\/public.php\/webdav\/2015-11-21_porsche_museum\/DSC00949.JPG): failed to open stream: operation failed\n[file] \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 406\n[message] Undefined variable: http_response_header\n[file] \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Client\/StreamHandler.php\n[line] 407","Exception":"GuzzleHttp\\Exception\\RequestException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(104): GuzzleHttp\\Exception\\RequestException::wrapException(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Ring\\Exception\\RingException))\n#1 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#2 \/var\/www\/owncloud\/3rdparty\/react\/promise\/src\/FulfilledPromise.php(24): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n#3 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n#4 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n#5 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(135): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n#6 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(232): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#7 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(192): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\n#8 \/var\/www\/owncloud\/lib\/private\/http\/client\/client.php(123): GuzzleHttp\\Client->get('https:\/\/www.fu-...', Array)\n#9 \/var\/www\/owncloud\/lib\/private\/files\/storage\/dav.php(347): OC\\Http\\Client\\Client->get('https:\/\/www.fu-...', Array)\n#10 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(286): OC\\Files\\Storage\\DAV->fopen('2015-11-21_pors...', 'rb')\n#11 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/availability.php(302): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('2015-11-21_pors...', 'rb')\n#12 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(286): OC\\Files\\Storage\\Wrapper\\Availability->fopen('2015-11-21_pors...', 'rb')\n#13 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1021): OC\\Files\\Storage\\Wrapper\\Wrapper->fopen('2015-11-21_pors...', 'rb')\n#14 \/var\/www\/owncloud\/lib\/private\/files\/view.php(871): OC\\Files\\View->basicOperation('fopen', 'TF\/2015...', Array, 'rb')\n#15 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php(266): OC\\Files\\View->fopen('TF\/2015...', 'rb')\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(82): OC\\Connector\\Sabre\\File->get()\n#17 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#20 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#21 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#22 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#23 {main}","File":"\/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php","Line":51}

**Comment by Tobus** [comment] 2016-01-01 10:12
I think there is the problem described:

http://stackoverflow.com/questions/26148701/file-get-contents-ssl-operation-failed-with-code-1-and-more/28701786#28701786

**Comment by photoninger** [comment] 2016-01-19 13:55
I have the same problem. The other OC has even a Startcom certificate which is fine when I access via browser, but my OC won't sync the shared files.
I have php 5.5.31 with apache-2.4 on Linux.
Playing around with openssl s_client I found out the other OC does not include the intermediate CA cert of Startcom.
So I added all needed certs in my own cacert.pem file which works now with s_client, but when I modify  getDefaultCaBundle() in 3rdparty/guzzlehttp/ringphp/src/Client/ClientUtils.php getDefaultCaBundle() to return the path to my cacert.pem file, I get the following error:
Array to string conversion at htdocs/lib/private/template/functions.php#36
I will try to convince the admin of the other OC to include the intermediate CA cert and try again, if it works then.

**Comment by rullzer** [comment] 2016-01-19 14:06
CC @LukasReschke for the certificate stuff

**Comment by photoninger** [comment] 2016-01-25 18:50
I did some more testing. Meanwhile I upgraded my webservers to php-7.0.2, but I don't think it matters, because I found something strange with `resources/config/ca-bundle.crt`:
It has linebreaks after 76 characters. Looking at debian jessie's `/etc/ssl/certs/ca-certificates.crt` it has linebreaks after 64 characters, which is also the length of lines in pem files when you e.g. convert DER to PEM with openssl x509.
Now if I use debian's `ca-certificates.crt` for `resources/config/ca-bundle.crt` I am able to share between my OC-8.2 and another OC-8.1, but not with another OC-8.2. Both non-local OCs are using startcom certificates and both include the intermediate ca. When I try to add the OC-8.2 share link to my owncloud I get "Invalid or untrusted SSL certificate" in the web-ui. 
For my tests I used the following script:
```php
<?php

$contextOptions = array(
  'ssl' => array(
    'verify_peer'   => true,
// doesn't work:
    'cafile'        => '/SOME/PATH/TO/webserver/htdocs/resources/config/ca-bundle.crt',
// works:
//    'cafile' => '/SOME/PATH/TO/ca-certificates.crt',
// works:
//    'capath' => '/etc/ssl/certs',
    'verify_depth'  => 5
  ),
  'http' => array(
    timeout => 10.0
  )
);
$sslContext = stream_context_create($contextOptions);

$file = fopen("https://OTHER_OC_SITE/robots.txt", "r",NULL,$sslContext);
if (!$file) {
  echo "<p>error, could not open remote file</p>";
  exit;
}

while (!feof ($file)) {
  $line = fgets ($file, 1024);
  echo $line;
}

fclose($file);
?>
```
On Suse-Linux in `/etc/ssl/certs` we have a hashed directory with all trusted root CAs.
My test-script worked with both other OC sites while NOT using  `resources/config/ca-bundle.crt`.
When I replace `resources/config/ca-bundle.crt` with `ca-certificates.crt` the admin-page in my OC's web-ui tells me "This server has no working Internet connection. " under "Security & setup warnings", but then I can sync with the other OC-8.1.
As far as I know, the other OC-8.1 is running on openSuse and the OC-8.2 on Ubuntu server.
Very strange.

**Comment by LukasReschke** [comment] 2016-01-25 20:07
@photoninger Can you post your used domains? THX.

**Comment by LukasReschke** [comment] 2016-01-26 10:06
I received the domains from @photoninger via mail, and at least one of them has missing intermediate certificates.

**Comment by photoninger** [comment] 2016-01-26 14:49
I did some more research:
The non-local OC-8.2 has a weird apache-config, running `openssl s_client` against it without SNI it returns the intermediate certificates, with SNI it doesn't. I'm working with the admin to get this sorted out.
Reading related bug reports I enabled external_storage und uploaded the startcom_ca_chain to my users personal settings. After reloading the page a few times now sharing with the OC-8.2 works also, I'm still using the ca-certifcates.crt from debian. 
I suspect some caching effects are also interfering in my tests.
So my further plan is:
1. fix the ca_chain of the other OC-8.2
2. go back to the original ca-bundle.crt
3. clear all caches
4. test again.

**Comment by photoninger** [comment] 2016-01-27 14:10
Update:
The other OC-8.2 is now fixed. Still not working with original ca-bundle.crt.

Did some more tests:
Fresh install on SLES-11.4 with php5.6 from OBS: Same error with original ca-bundle.crt. Working with ca-certifcates.crt.
Fresh install on SLES-12.0 with php5.5 from SLES12: Works out of the box.

My conclusion: Old openssl 0.9.8j on SLES-11.4 vs. newer openssl 1.0.1i on SLES-12.0 is likely the root cause.

At this point I stop searching und try to get a newer openssl on my production OC installation.

@LukasReschke  Thanks for the help.

**Comment by bcutter** [comment] 2017-04-18 20:54
Any update on this? I see a "GuzzleHttp\Exception\ClientException" for every connected federated cloud share, in detail:

`GuzzleHttp\Exception\ClientException: Client error response [url] https://(own/next)cloud-address.com//ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 400 [reason phrase] Bad request`

Does this match this issue or do I need to post it in the federation app part of ownCloud?

**Comment by PVince81** [comment] 2017-12-18 13:17
closing in favor of https://github.com/owncloud/core/issues/23634#issuecomment-332496463.

@bcutter without further details we cannot say whether this matches. If you see a SSL error somewhere in the log then yes it matches.

**Closed by PVince81** 2017-12-18 13:17 UTC
Labels: enhancement, feature:federated-cloud-sharing

**Comment by bcutter** [comment] 2017-12-18 18:34
THX @PVince81. Didn’t see those errors for a long time, therefore no relevance any longer. They were replaced by many others ;-)
