### ISSUE TITLE
Syntax error in "sharedialogmailview.js"

### ISSUE THREAD

**Issue by Michael45678** [owncloud/core#31481] opened 2018-05-19 16:20 UTC
https://github.com/owncloud/core/blob/008c1ca4de20e5f84b236694788e2ee06d2d1c6c/core/js/sharedialogmailview.js#L197

this.$el.find('.emailPrivateLinkForm--emailField').select2({
-----------------------------------------------------------^

**Comment by patrickjahns** [comment] 2018-05-21 11:28
Duplicate of https://github.com/owncloud/core/issues/31338

**Closed by patrickjahns** 2018-05-21 11:28 UTC
Labels: needs info
