### ISSUE TITLE
Error PHP Call to undefined method OCA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() atapps/user_ldap/user_ldap.php#385

### ISSUE THREAD

**Issue by simpleuser99** [owncloud/core#26945] opened 2017-01-16 08:25 UTC
HI.
I update mu OC from 8.2.x to 8.2.9 and i have the next erorr

> Error PHP Call to undefined method CA\user_ldap\lib\user\OfflineUser::composeAndStoreDisplayName() at apps/user_ldap/user_ldap.php#385

My ldap users can't login to owncloud, they view 500 http code/

**Comment by kdslkdsaldsal** [comment] 2017-01-16 09:00
Duplicate of https://github.com/owncloud/core/issues/25588 which needs a new release 8.2.10 to have this fix included: https://github.com/owncloud/core/pull/26741

For now you can apply the patch from https://github.com/owncloud/core/pull/26741/files until 8.2.10 is released.

**Closed** 2017-01-16 18:05 UTC
