### ISSUE TITLE
User Charts for storage, activity and ...

### ISSUE THREAD

**Issue by juhulian** [owncloud/core#23647] opened 2016-03-30 09:09 UTC
Hello, it would be nice to have some charts in oc9+ like the plugin Storage Usage / Activity Charts for oc 7 and 8. 
https://apps.owncloud.com/content/show.php/Storage+Usage+%2B+Activity+Charts?content=166746

**Comment by RealRancor** [comment] 2016-03-30 09:55
Most likely a duplicate of https://github.com/owncloud/core/issues/1344

**Closed** 2016-03-30 10:56 UTC
Labels: enhancement
