### ISSUE TITLE
Files pdf make appear an error in the console due to the preview

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25144] opened 2016-06-16 11:19 UTC
### Steps to reproduce
1. In files view, upload a .pdf file
2. Refresh the screen
### Expected behaviour

The files should appear and no error should be shown
### Actual behaviour

An error appears in 'Firebug' error console:
"NetworkError: 404 Not Found"
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.0.2.2","versionstring":"9.0.2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

FIrefox

![screen shot 2016-06-16 at 13 07 24](https://cloud.githubusercontent.com/assets/10596560/16114963/71500c20-33c4-11e6-80ea-0715b8bebf78.png)

**Comment by davitol** [comment] 2016-06-16 11:22
Same behaviour with .rtf files

**Comment by nickvergessen** [comment] 2016-06-16 12:05
Well that happens with all files that have no content preview. They return a 404 and then we display the mimetype icon instead.

**Comment by PVince81** [comment] 2017-08-07 20:08
duplicate of https://github.com/owncloud/core/issues/24216

**Closed by PVince81** 2017-08-07 20:08 UTC
Labels: bug, sev4-low
