### ISSUE TITLE
There should be an unshare icon in the filelist instead of the standard rubbish bin

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#16481] opened 2015-05-20 17:24 UTC
### Steps to reproduce
1. Add a share to your oC
2. Roll over the row

### Expected result
There should be an unshare icon at the far right

### Actual result
There is a delete icon which is confusing

The tooltip actually says the button will unshare the share

**Comment by oparoz** [comment] 2015-05-20 17:30
@jancborchardt, is there such an icon in the library?

**Comment by jancborchardt** [comment] 2015-05-20 19:29
@oparoz good call. Will create icons for unsharing (a strikethrough version of the triangle-share icon) and for unsharing-link (breaking link version).

**Comment by PVince81** [comment] 2015-05-21 10:36
We call it the trash bin. But I like "rubbish bin" too :wink:

**Comment by jancborchardt** [comment] 2015-05-21 13:53
No, we call it »Deleted files« ;) – Trash is something which smells and you have to carry down.

**Comment by DeepDiver1975** [comment] 2015-06-16 12:14
not critical -> 8.2

**Comment by jancborchardt** [comment] 2015-11-10 10:25
Wasn’t this fixed with a recent PR @PVince81 @schiesbn?

**Comment by PVince81** [comment] 2015-11-10 10:42
Duplicate of https://github.com/owncloud/core/issues/20172

**Closed by PVince81** 2015-11-10 10:42 UTC
Labels: design, enhancement, junior job, sharing
