### ISSUE TITLE
Refresh current folder for new added files

### ISSUE THREAD

**Issue by stephane84** [owncloud/core#9474] opened 2014-07-06 06:57 UTC
When you're looking at a folder, and another user adds or modify one file in the same folder, you can't see it because it is not refreshed.

Most of the users will click on the name of the current folder (in the breadcrumbs) to refresh the content displayed, but this click triggers actually nothing.

Should it be possible to trigger a refresh of the current folder by clicking on the folder's name in the breadcrumb ?

Note 1 : when ordering the files by clicking on the columns names, this refresh IS already triggered and the nex files are displayed. The same behaviour should happen.

Note 2 : This happens often when you're at the phone and you say "ok, I've uploaded the file", "No, you don't, I don't see anything", "Yes, I did, please refresh the content of the folder", "Hmm, how ?" ;-)

**Comment by DeepDiver1975** [comment] 2015-01-09 14:33
@PVince81 8.0, 8.1 or backlog? THX

**Comment by PVince81** [comment] 2015-01-09 14:34
I'd say backlog for now. I don't see this as high priority.

**Comment by oparoz** [comment] 2015-05-21 10:19
Should be implemented via https://github.com/owncloud/core/issues/983

**Comment by MorrisJobke** [comment] 2015-05-27 06:09
Duplicate of #983

**Closed by MorrisJobke** 2015-05-27 06:09 UTC
Labels: 1 - To develop, app:files, enhancement
