### ISSUE TITLE
App update error is not displayed

### ISSUE THREAD

**Issue by sualko** [owncloud/core#10579] opened 2014-08-21 14:47 UTC
### Steps to reproduce
1. Try to update an app which includes an error (permission, not allowed call, ...) via webinterface.

### Expected behaviour
Successfully update this app.

### Actual behaviour
The update button changes his label to <code>Update...</code>, but nothing happens. If you open your console you see, that there was a call to <code>index.php/settings/ajax/updateapp.php</code> which results into a 500 server error. But the response is a complete html page which includes the error description.

### Server configuration
**ownCloud version:** 7.0.1

### Client configuration
**Browser:** Chrome 36

**Operating system:** Win 7

### Logs
Example logs, for an app with not allowed code.

#### ownCloud log (data/owncloud.log)
```
{"app":"core","message":"App \"ojsxc\" is using a not allowed call \"exec(\". Installation refused.","level":3,"time":"2014-08-21T13:56:27+00:00"}
{"app":"index","message":"Exception: Die Applikation kann auf Grund von unerlaubten Code nicht installiert werden","level":4,"time":"2014-08-21T13:56:27+00:00"}
```

#### Response
```
<!DOCTYPE html>
<!--[if lt IE 7]><html class="ng-csp ie ie6 lte9 lte8 lte7" data-placeholder-focus="false"><![endif]-->
<!--[if IE 7]><html class="ng-csp ie ie7 lte9 lte8 lte7" data-placeholder-focus="false"><![endif]-->
<!--[if IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false"><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false"><![endif]-->
<!--[if gt IE 9]><html class="ng-csp ie" data-placeholder-focus="false"><![endif]-->
<!--[if !IE]><!--><html class="ng-csp" data-placeholder-focus="false"><!--<![endif]-->

	<head data-requesttoken="....">
		<title>
		ownCloud		</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		
....
		
			</head>
		<body id="body-login">
		<div class="wrapper"><!-- for sticky footer -->
			<div class="v-align"><!-- vertically centred box -->
				<header><div id="header">
					<div class="logo svg"></div>
					<div id="logo-claim" style="display:none;"></div>
				</div></header>

				<ul class="error-wide">
			<li class='error'>
			Die Applikation kann auf Grund von unerlaubten Code nicht installiert werden<br/>
			<p class='hint'></p>
		</li>
	</ul>
			<div class="push"></div><!-- for sticky footer -->
			</div>
		</div>

		<footer>
			<p class="info">
				<a href="https://owncloud.org" target="_blank">ownCloud</a> – Web-Services unter Ihrer Kontrolle			</p>
		</footer>
	</body>
</html>
```

**Comment by MorrisJobke** [comment] 2015-10-29 12:41
Duplicate of #18721

**Closed by MorrisJobke** 2015-10-29 12:41 UTC
Labels: bug, settings:apps, sev3-medium, update
