### ISSUE TITLE
Sidebar feature: system-wide tagging for files & folders

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#16325] opened 2015-05-13 13:50 UTC
(borrowing from the conversation at https://github.com/owncloud/core/issues/3812)
As a user, I want to make my files and files I share with others easily accessible based on a concepts that are relevant to users of ownCloud so that I can quickly find what I am looking for.

Acceptance Criteria:
- All tags are system wide, so that if I create one it can be set / removed by anyone with whom the file/folder is shared, and tags can be edited by everyone
- The user can click on a file, and a tag option pops up to the right in the new sidebar panel there: https://github.com/owncloud/core/issues/16308
- The user is presented with a list where they can set tag(s) for the file or folder, and remove tags. 
- More than 1 tag can be selected per file or folder
- If a folder is tagged, a file or folder inside that folder is not automatically tagged the same
- The user can also create new tags, edit existing tags, and delete tags
- If a tag is renamed, the files and folders with this tag are renamed
- Initially the tags are empty (should they be, or should an admin set a couple of basic ones?)
- A possible example of tags is gmail, which is useful
![untitled](https://cloud.githubusercontent.com/assets/1818977/7611893/5b866d26-f955-11e4-90a6-9b53e6a92d52.png)

@jancborchardt your input greatly appreciated as the sidebar on the right is now possible.

**Comment by oparoz** [comment] 2015-05-13 18:24
> If a folder is tagged, a file or folder inside that folder is not automatically tagged the same

Can you give a use case?

**Comment by jancborchardt** [comment] 2015-05-18 13:15
First work-in-progress of a sidebar: https://github.com/owncloud/core/pull/16414

**Comment by blizzz** [comment] 2015-06-16 12:13
> All tags are system wide

I.e. there are no private tags?

> If a tag is renamed, the files and folders with this tag are renamed

I guess, not the files and folders themselves but the labels are renamed.

**Comment by MTRichards** [comment] 2015-06-16 12:26
We discussed yesterday, and agreed that private tags are the way to start. Public tags come later. That is a change.

And yes, the labels are remanded not the files or folders.

**Comment by PVince81** [comment] 2015-07-15 17:07
Please note that there are already APIs to read and write tags.
Tags are available on the FileInfo object (it's a simple array at the moment) under "data.tags".

A `TagsFileInfoView` class must be implemented that extends `DetailsFileInfoView` (which will be introduced by https://github.com/owncloud/core/pull/17656).
That class will provide the select2 control to display and apply tags.

To apply tags, see the existing tagsplugin class: https://github.com/owncloud/core/blob/v8.1.0/apps/files/js/tagsplugin.js#L165 method.

**Comment by PVince81** [comment] 2015-07-15 17:14
- [ ] ability to manage tags in a global manner (delete tags, not only unset from file; rename, etc)

**Comment by jancborchardt** [comment] 2015-09-08 15:02
Is this now 8.2 or 9.0 @karlitschek @MTRichards @PVince81?

**Comment by karlitschek** [comment] 2015-09-08 17:36
8.2 is unrealistic unfortunately. so 9.0 :-)

**Comment by MTRichards** [comment] 2015-09-18 08:50
We should also revisit the local vs. global tags here, because bother are useful but we need a way to create and edit, then set and distinguish global and local tags for a user.

**Comment by DeepDiver1975** [comment] 2015-10-22 12:37
To start off with the API design discussion:
How do we retrieve/manage tags for files?

Yes - there will be some table where the information is stored and it will hold a fileid referenceing the file .... but what about those installations where we are moving the whole sharing and the file cache out of the database (mainly because of scalability reasons).

To me this sounds like just another storage based interface we need similar to sharing and the metadata cache.

@karlitschek @cmonteroluque @icewind1991 @schiesbn @nickvergessen @PVince81

**Comment by schiesbn** [comment] 2015-10-22 13:07
> Yes - there will be some table where the information is stored and it will hold a fileid referenceing the file .... but what about those installations where we are moving the whole sharing and the file cache out of the database 

Still every file will have a ID. This is also needed for sharing if we want to reference a share in the OCS API. We don't care where the ID comes from and how it is generated/stored but every storage need to be able to generate such a ID for each file/folder.

**Comment by icewind1991** [comment] 2015-10-22 13:15
I agree that we should have a way for storage backends to overwrite the tagging implementation

**Comment by DeepDiver1975** [comment] 2015-10-22 14:15
> Still every file will have a ID. This is also needed for sharing if we want to reference a share in the OCS API. We don't care where the ID comes from and how it is generated/stored but every storage need to be able to generate such a ID for each file/folder.

the existance of the id is not of question - but the storage location of the data.

Just to clarify: as soon as an API is referencing a file by fileid - the requirement applies to allow a storage based implementation to be hooked in.

For the reasoning: some simply want to store the date in the same location by design or because of explicit scalability reasons. The later is the primary reason for us to have all these interfaces and allow hookup of alternative implementations.

**Comment by jancborchardt** [comment] 2015-11-02 10:35
Btw, mockup of this (also including the comment functionality) as posted in https://github.com/owncloud/core/issues/16328#issuecomment-103059715

Note the tags list below the file details. We can use a multiselect.js element here. (Or select2, not sure what’s our preference right now …)

Mockup of this (as posted in https://github.com/owncloud/core/issues/16308#issuecomment-113521360 ):
![](https://raw.githubusercontent.com/owncloud/design/master/Files/Sidebar-mockup.png)
([source in the design repo](https://github.com/owncloud/design/tree/master/Files))

**Comment by PVince81** [comment] 2015-11-02 10:38
@jancborchardt was thinking of select2, with this kind of view: https://select2.github.io/examples.html (scroll down to "Tagging support")

**Comment by PVince81** [comment] 2015-11-03 10:45
@MTRichards can you clarify that this requirement is about system-wide tags ? The issue title says "system-side tagging" but some of your comments above https://github.com/owncloud/core/issues/16325#issuecomment-112407401 say otherwise.

I seem to remember that we agreed that the first step is system-wide tags.

Then comes the question of system-wide tags management. As per the requirement as user is allowed to create new tags in the sidebar. But we'd say a user cannot manage system-wide tags, only an admin.

**Comment by PVince81** [comment] 2015-11-03 10:55
- [ ] system-wide files tagging backend: https://github.com/owncloud/core/issues/20258
- [ ] tagging GUI in right sidebar for system-wide tags (with select2 and allows creation of new tags)
- [ ] management GUI for admins for system-wide tags ? ( @MTRichards @jancborchardt)

**Comment by PVince81** [comment] 2015-11-03 13:03
If we decide to have the tag manager on storage level (storage specific) instead of global, then we also need to handle cross-storage move/copy to make sure the tags are read from tag manager TA from storage A and moved over to the tag manager TB from storage B.

- [ ] cross-storage move/copy, if applicable

**Comment by MTRichards** [comment] 2015-11-03 13:05
>I seem to remember that we agreed that the first step is system-wide tags.

Correct. System wide tags because we use this also for retention.

**Comment by MTRichards** [comment] 2015-11-03 13:09
>Then comes the question of system-wide tags management. As per the requirement as user is allowed to create new tags in the sidebar. But we'd say a user cannot manage system-wide tags, only an admin.

There are three types of tags, each needing its own namespace: 
- User viewable and editable tags
- User viewable tags
- Invisible tags

The user can see and edit only one of these types of tags (the first one) when they are set on a file or folder. These are, I think, the tags you are asking about. A user can remove or rename tags in this namespace at any time. And, a little x would allow the user to delete these tags as well - we are trying to not have another view, rather let these editable tags be managed in the sidebar.

Note, multiple of any tag type can be associated with a file or folder.

User viewable tags cannot be edited by the user. They can only be seen, and then edited by admins or system apps.

**Comment by PVince81** [comment] 2015-11-03 13:19
I rather see tag types like this: "default type" and "retention type". And then the visibility is mostly a matter of permission, could be either a "subtype" field or a "permissions" field.

But that's out of scope of this specific ticket here (it's documented already in a another ticket I believe)
We can still introduce the two fields "type" and "permissions" as part of this ticket, but leave them empty or set to default values.

**Comment by PVince81** [comment] 2015-11-03 13:21
>The user can see and edit only one of these types of tags (the first one) when they are set on a file or folder. These are, I think, the tags you are asking about. A user can remove or rename tags in this namespace at any time. And, a little x would allow the user to delete these tags as well - we are trying to not have another view, rather let these editable tags be managed in the sidebar.

@MTRichards we need to make sure we are clear about the difference between "deleting a tag" and "unassigning a tag". With "deleting" I mean "deleting completely from the system, from everyone". The same for renaming.
Are you saying a user should be able to rename (system-wide) and deleting (system-wide) tags from the sidebar ? Usually the "x" button is rather for unassigning a tag than deleting.

Just want to make sure we're clear :smile:

**Comment by PVince81** [comment] 2015-11-03 13:25
also "managing tag" vs "assigning tags" :smile:

**Comment by MTRichards** [comment] 2015-11-03 14:19
Great question - I like the conversation.

X would be to remove the tag from a file or folder, yes - we need one of those. 

In my head I also say an x on an unassigned tag for that file or folder, and that would remove the tag permanently from the system. So an assigned tag might be a solid color, an unassigned tag no color, and then the x on one means remove, the other delete. I will defer to @jancborchardt here...

@jancborchardt need some help input on tag sidebar design.

Also in my head, an assigned tag can be removed from the assigned file of course. And a tag is assigned to a file in a select2 sort of type ahead filter (but remember thousands of tags are possible, so speed is important).

**Comment by PVince81** [comment] 2015-11-03 15:11
@MTRichards understood after looking again at your original mock up :smile: 

select2 is able to support searching, so it won't need to load all the tags at once.
However I don't think it supports adding a "x" within the dropdown/results. But then I'm not sure whether it's a good UX to let people delete (system-wide delete) tags from within such selection list.

**Comment by MTRichards** [comment] 2015-11-03 15:14
Ok, so we have to figure something else out to be able to "manage" tags, which really means to delete tags.

**Comment by MTRichards** [comment] 2015-11-03 15:15
@jancborchardt Any idea on how to manage tags (delete, edit) easily without requiring a whole new view?

**Comment by karlitschek** [comment] 2015-11-03 15:20
I see different ways to do this. There should be an easy/simple way for tagging. So a user can just type in a tag into the tagging interface. If a tag is already used somewhere else then it is autocompleted. If the string is not used somewhere else then the user can just press enter an a new tag is set. This is useful so that every user can create and use any tag they want. For example for a new project. There is not system wide list of tags. What is used exists and what is not used doesn't exist.
This still works with the retention and security scenarios that we discussed. Some tag only have special meaning.

And then there is the more advanced and restricted way where and admin defined a list of tags that are allowed in the system. A user can only choose from this list. This is useful in a more restricted scenario. But makes it less useful for 'normal' users. You can't just tagsomething you first have to ask the admin to create a new 'project x' tag.

At the end of the day we probably need both.

comments?

**Comment by MTRichards** [comment] 2015-11-03 15:33
I agree on the need for the two approaches. There really is no choice. Sadly our idea to make this tag mgmt minimal, and reduce management of tags to a simple easy interface is not holding true.

**Comment by oparoz** [comment] 2015-11-03 17:19
> But then I'm not sure whether it's a good UX to let people delete (system-wide delete) tags from within such selection list.

I agree. If you really wanted to though, you could replace the x with a little bin once a tag is unassigned. Protected tags would get the bin crossed per example, indicating that it's not user-deletable. There are plenty of examples on the Internet of ways to represent user-denied actions.
I wouldn't play with colours (by removing them) as colours really help quickly identify if the right tag is showing up (like on here).

**Comment by jancborchardt** [comment] 2015-11-04 13:33
As @karlitschek said:

> What is used exists and what is not used doesn't exist.

This is also what I planned. No management-focused interface, just inherent tags. We should use the multiselect widget for that since it allows for the creation of inexistent elements – which is why we developed it back then. We could extend it to allow edit and deletion of existent elements.

**Comment by PVince81** [comment] 2015-11-04 14:58
So we all agree that the dropdown (whether multiselect or select2) should support system-renaming and system-deleting of tags within the dropdown while it's open ? My concern is mostly UX-wise as it doesn't feel user-friendly. But it can be a nice shortcut, yes.

**Comment by jancborchardt** [comment] 2015-11-04 15:03
I suggest you check out https://getpocket.com – their tags dropdown does basically exactly what I said above. And it’s a very widely used service.

**Comment by PVince81** [comment] 2015-11-13 14:55
Here is an update after the latest technical discussions:
- system-wide tag manager will be global, with a default implementation that can be overridden in config.php. "Global" means it will not be tied to any storages.
- db table
	- id (autoinc), tagName, visibility, changeability (unique key is (tagName, visibility, changeability)
	- backend-only for now: visibility: user-visible, not user visible
	- backend-only for now: changeability: user-changeable, not user changeable

So the tasks are as follows:
- [ ] 1. In core, implement SystemWideTagManager
    - decide endpoints (webdav or OCS)
    - decide PHP / OCP endpoints
- [ ] 2. Separate app for the tag UI
    - provides dropdown in sidebar
        - autocomplete / dropdown with tag list
        - used to assign/unassign tags to files/folders
	- user can create/edit system-wide tags within the dropdown
    - app can be disabled to disable tagging GUI
- [ ] extra: make webdav files endpoint return system-wide tags

**Comment by PVince81** [comment] 2015-11-16 15:14
> User viewable and editable tags

@MTRichards with "user editable tags" did you actually meant "user can assign/unassign tags from files", or "user can rename/delete these tags from the system" ? I could imagine a case where a user can see a tag (visible) but cannot unassign it from the file ?

**Comment by MTRichards** [comment] 2015-11-16 16:06
Yes, sorry - user can assign / unassign the tags on a file. There are really three options:
1) user can add/remove from file and see tags
2) user can see but not do anything
3) hidden from user

**Comment by PVince81** [comment] 2015-11-16 16:09
Cool thanks. Sounds like an integer value might cover this nicely.

**Comment by oparoz** [comment] 2015-11-16 16:24
> decide endpoints (webdav or OCS)

Why can't it be both? In case you want to avoid duplication, you can use a wrapper.
It's just that when writing app, if APIs are spread across various different endpoints it quickly becomes a pain to maintain.

**Comment by PVince81** [comment] 2015-11-16 16:37
Both also means more code paths with completely different formats, which also becomes a pain to maintain. Hmmm...
What you mean is likely not "spread across various different endpoints" but rather "different endpoint formats".

**Comment by PVince81** [comment] 2015-11-16 16:38
Ideal is if it's wrapped in a nice JS class that abstracts away the endpoint, whichever it is.

**Comment by icewind1991** [comment] 2015-11-16 16:40
dav seems to make the most sense since we already have the tagging for favorites there and imo we should try to have all file related api stuff in dav.

(maybe move sharing to dav one day... (cc @rullzer ))

**Comment by PVince81** [comment] 2015-11-16 16:47
The dav API could look like this:
- GET 'dav/tags'  to retrieve all tags (XML contains tagid and tag name)
- PUT 'dav/tags/tagid'  to create a new tag or rename it (by id)
- DELETE 'dav/tags/tagid' to delete a tag from the system
- PROPPATCH 'dav/files/path/to/file' with a body containing `<oc:systemtags><oc:tag>tag1</oc:tag><oc:tag>tag2</oc:tag>` (similar to how `oc:tags` work already now)
- PROPFIND 'dav/files/path/to/file' and pass `<oc:systemtags>` in the requested properties to also receive the system tags in the response (similar to how `oc:tags` works).

Note: we have to work with tag ids because a tag is "tag name + flags". So technically an invisible tag might exist as well as a visible one. (hmmm, what could possibly go wrong...)

**Comment by karlitschek** [comment] 2015-11-16 17:07
@PVince81 look good. I looked around if there is something that others do in this area or some kind of defacto standard. But I think there is none. So we could do it like that.

**Comment by DeepDiver1975** [comment] 2015-11-16 17:10
> GET 'dav/tags' to retrieve all tags (XML contains tagid and tag name)

Tags being a collections: its a PROPFIND - GET is not defined on collections

**Comment by PVince81** [comment] 2015-11-16 17:11
@DeepDiver1975 good point, edited.

**Comment by oparoz** [comment] 2015-11-16 18:32
> What you mean is likely not "spread across various different endpoints" but rather "different endpoint formats".

Actually, I meant both, simply based on my experience of building apps, but it's true that it usually has nothing to do with OCS, which is clearly defined. It has more to do with the fact that some endpoints are buried in apps.
Looking more closely at the specifications of WebDAV and OCS, it seems clear that tagging of documents should be made available through the WebDAV endpoint and tagging of people part of OCS. Now if you want to have a global manager then you need to make the same tags available through both APIs, avoiding duplication of data. Using solely WebDAV or OCS will results in requests having to be made to both APIs.

**Comment by PVince81** [comment] 2015-11-18 09:30
I wonder if we should call these "global tags" in the UI instead of "system-wide tags" ? "global" sounds less technical.

**Comment by PVince81** [comment] 2015-12-07 15:01
Related feature: filter by tags https://github.com/owncloud/core/issues/21001

**Comment by PVince81** [comment] 2016-01-13 10:23
I started implementing the GUI here: https://github.com/owncloud/core/pull/20847

But I realized that it doesn't match the GUI requirements.

From what I remember when discussing with @jancborchardt, it should look like this:
- tags input field looks like a regular non-editable field with a dropdown button, like https://github.com/owncloud/core/issues/16325#issuecomment-152983158 and also like in the user settings
- when clicking the dropdown button, the dropdown opens
- the dropdown shows the already assigned tags with a ticket checkbox (like group management)
- the dropdown also shows the non-assigned tags
- the dropdown contains a field to filter tags
- we could say it looks similar to the group management dropdown, but with an additional search field. Or even like the Github label selection dropdown
- the dropdown search field allows for creating new tags when none was found in the list
- every entry in the dropdown has a pencil icon on the right for global renaming
- every entry in the dropdown has a trash icon on the right for global deletion

@jancborchardt mind doing a quick mock up of the opened dropdown ?

**Comment by PVince81** [comment] 2016-01-13 10:49
So far it looks like select2 doesn't support this use case: https://github.com/select2/select2/issues/411 and requires additional hacking to make it work.

**Comment by PVince81** [comment] 2016-01-13 11:05
@jancborchardt also how to make it clear for the user that the tags are system-wide, especially when renaming/deleting ? (pencil/trash)

**Comment by Bugsbane** [comment] 2016-01-13 21:04
You could have a tooltip that displays "Edit how this appears to all users" when the cursor hovers over it, and combine it with a warning so that when a user clicks / taps delete or edits the tag and it's just about to be saved that they see:

"This will delete / edit how this tag appears to all other users. Continue?"
with Cancel, OK and a "Don't show this next time" checkbox (which would just apply to that user).

Alternatively, we could treat this similar to how we do with deleting files, that is, rather than asking users if they're sure, just do it, but warn them with a statusbar message (or whatever it's called) that has a one click undo button.

The second way breaks the user flow less, but it's also more likely to run into trouble from users not managing to read the statusbar warning and click before it disappears.

**Comment by PVince81** [comment] 2016-01-28 08:55
- [ ] TODO: background job to clean up orphaned system tag relationships: for example when a referenced file was deleted, the matching mappings must be cleant up

**Comment by PVince81** [comment] 2016-01-29 12:23
@karlitschek @MTRichards does it make sense to publish an activity when someone assigns/unassigns tags from files ? (only for visible tags)

**Comment by karlitschek** [comment] 2016-01-29 12:49
sure. this is intetedting. github dies this too.

**Comment by MTRichards** [comment] 2016-01-29 13:17
Yes, probably with an option in the notifications panel at some point - just like github. Also makes sense to write a log entry with who made the change, because of the retention use case for tags - need it auditable.

**Comment by PVince81** [comment] 2016-01-29 13:30
- [ ] publish activity when assigning/unassigning tags to files

**Comment by jancborchardt** [comment] 2016-01-29 14:15
Yep. But we need to make sure to group these activities as well. That is, when someone adds 4 tags, it should be displayed as 1 activity:

> Vincent added tags: Important, Biz, $$$, Confidential

Instead of having 4 separate activities.

**Comment by nickvergessen** [comment] 2016-02-01 09:13
Activities and admin-audit is moved to https://github.com/owncloud/core/issues/22041

**Comment by MorrisJobke** [comment] 2016-02-08 09:34
> ability to manage tags in a global manner (delete tags, not only unset from file; rename, etc)

@PVince81 This is the only open check box here - is this done?

**Comment by PVince81** [comment] 2016-02-08 09:41
The discussion was to not have a global tag manager. Also, the dropdown already makes it possible to rename or delete tags.

**Comment by MorrisJobke** [comment] 2016-02-08 09:49
> The discussion was to not have a global tag manager. Also, the dropdown already makes it possible to rename or delete tags.

This then means that this is fully covered and can be closed?! ;)

**Comment by PVince81** [comment] 2016-02-08 10:31
- QA: https://github.com/owncloud/QA/issues/111
- documentation: https://github.com/owncloud/documentation/issues/2141

**Closed by PVince81** 2016-02-08 10:31 UTC
Labels: design, enhancement - needs design, feature:tags, overview, p1-high
