### ISSUE TITLE
File icon isn't loaded in the versions dropdown

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#16678] opened 2015-06-02 08:46 UTC
### Steps to reproduce
1. Check that versions app is enabled
2. Upload a file (checked with a .pdf file, but any other file format which doesn't generate a preview should do)
3. Upload another version of the file
4. Click in the versions button of the file to show all available version.

### Expected behaviour
Preview of the file or the corresponding icon should be shown.

### Actual behaviour
If it's not possible to generate the preview, the file icon isn't loaded

![screenshot from 2015-06-02 10 32 29](https://cloud.githubusercontent.com/assets/1477829/7931771/a21673e4-0913-11e5-9663-40af81aea5c8.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 7.0.6RC2

**Updated from an older ownCloud or fresh install:** updated from 7.0.5

**Comment by MorrisJobke** [comment] 2015-06-02 09:04
Also reproducable on master.

**Comment by PVince81** [comment] 2015-06-02 13:05
Low ? This is a regression => high

**Comment by PVince81** [comment] 2015-06-02 13:06
Hmm... OC 7 ? From what I remember this used to work.

**Comment by PVince81** [comment] 2015-06-02 13:07
@oparoz @georgehrke @schiesbn

**Comment by georgehrke** [comment] 2015-06-02 13:16
@schiesbn Did anything change in the name schema for versioning? We only touched some hooks that affected previews of versioning, but nothing that should break the preview generation itself.

**Comment by MorrisJobke** [comment] 2015-06-02 13:33
> We only touched some hooks that affected previews of versioning, but nothing that should break the preview generation itself.

It's not the preview generation, but the fallback to the mimetype icons. If the file doesn't have a preview the mimetype icon should be shown. I think this never worked before.

**Comment by oparoz** [comment] 2015-06-02 13:38
Duplicate of https://github.com/owncloud/core/issues/14106

**Closed** 2015-06-02 13:41 UTC
Labels: app:files_versions, bug, duplicate, feature:previews, junior job, sev2-high
