### ISSUE TITLE
Owncloud doesn't falls back to replica LDAP server

### ISSUE THREAD

**Issue by patrick1990** [owncloud/core#19336] opened 2015-09-24 10:00 UTC
<h4>How to reproduce:</h4>
1) Set up a LDAP master server and a LDAP replica server.
2) Configure Owncloud-LDAP-Module so that everything works. Configure the replica server as backup in the Advanced section.
3) Check that everything works (normal operation and bypass master server by setting ldapOverrideMaster). Espacially try login with an LDAP user.
4) Uncheck ldapOverrideMaster and turn off the LDAP master.
5) Try to login to Owncloud.

<h4>Actual behaviour:</h4>
It seams that Owncloud can connect to both LDAP servers because everything works like expected in normal operation and when I set ldapOverrideMaster (so that Owncloud uses the backup server). But when the master server becomes unavailable and ldapOverrideMaster is unset, Owncloud is not able to connect to the LDAP server and I get the following Exception (I've formated it for better reading):
`Exception: {"Exception":`
`"OC\\ServerNotAvailableException",`
`  "Message":"Lost connection to LDAP server.",`
`  "Code":0,`
`  "Trace":`
`    "#0 /var/www/owncloud/apps/user_ldap/lib/ldap.php(259): OCA\\user_ldap\\lib\\LDAP->postFunctionCall()`
`	 #1 /var/www/owncloud/apps/user_ldap/lib/ldap.php(42): OCA\\user_ldap\\lib\\LDAP->invokeLDAPMethod('bind', Resource id #247, '', '')`
`	 #2 /var/www/owncloud/apps/user_ldap/lib/connection.php(609): OCA\\user_ldap\\lib\\LDAP->bind(Resource id #247, '', '')`
`	 #3 /var/www/owncloud/apps/user_ldap/lib/connection.php(541): OCA\\user_ldap\\lib\\Connection->bind()`
`	 #4 /var/www/owncloud/apps/user_ldap/lib/connection.php(160): OCA\\user_ldap\\lib\\Connection->establishConnection()`
`	 #5 /var/www/owncloud/apps/user_ldap/lib/connection.php(168): OCA\\user_ldap\\lib\\Connection->init()`
`	 #6 /var/www/owncloud/apps/user_ldap/lib/access.php(767): OCA\\user_ldap\\lib\\Connection->getConnectionResource()`
`...}`
The most interessting part for me is number 3, beause the called bind is the one for the master server. Is there an error handling missing after the function establishConnection was trying to connect to the master server?

<h4>Expected behaviour:</h4>
Owncloud should fall back to the backup/replica server and should not throw an exception.

<h4>Versions:</h4>
Owncloud: 8.1.1

**Comment by LukasReschke** [comment] 2015-09-24 12:20
@blizzz

**Comment by blizzz** [comment] 2015-09-24 18:19
Duplicate of https://github.com/owncloud/core/issues/18701

**Closed by blizzz** 2015-09-24 18:19 UTC
Labels: app:user_ldap, bug
