### ISSUE TITLE
receiving a local share is not possible when a federation share with same name was received before

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35154] opened 2019-05-06 07:46 UTC
### Steps to reproduce
1. install two servers with owncloud and configure federation sharing for me `http://localhost/owncloud-10.2.0/rc2_a` & `http://localhost/owncloud-10.2.0/rc2_b`
2. on server A create a user `user1_on_server_a`
3. on server B create two users `user1_on_server_b` `user2_on_server_b`
4. as `user1_on_server_a` create a folder called `to-share`
5. as `user1_on_server_a` share the folder `to-share` with `user1_on_server_b` via federation sharing
6. as `user1_on_server_b` accept the share
7. as `user2_on_server_b` create a folder called `to-share`
8. as `user2_on_server_b` share the folder `to-share` locally with `user1_on_server_b`

### Expected behaviour
as  `user1_on_server_b` there should be a received folder called `to-share` (fed sharing) and a folder called `to share (2)` local sharing

### Actual behaviour
as  `user1_on_server_b` there is only one received folder called `to-share` (fed sharing) and NO folder called `to share (2)` local sharing
in shared-with-you only one share is listed

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite / MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.2.0 RC2
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
community tarball

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occbl8s2az4f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-10.2.0\/rc2_b",
        "dbtype": "sqlite3",
        "version": "10.2.0.2",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/artur\/www\/owncloud-10.2.0\/rc2_b\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "sharing.federation.allowHttpFallback": true,
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/apps\/testing\/data\/webUISkeleton",
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.10.1
  - firstrunwizard: 1.2.0
  - market: 0.4.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Lf15XM4iMAsCf0u8CEo2","level":2,"time":"2019-05-06T07:39:56+00:00","remoteAddr":"127.0.0.1","user":"--","app":"notifications","method":"POST","url":"\/owncloud-10.2.0\/rc2_b\/index.php\/apps\/federatedfilesharing\/shares","message":"notification remote_share#2 can't be sent to user1_on_server_b via email: email for the user isn't set"}
```

**Comment by individual-it** [comment] 2019-05-06 08:21
also happens on 10.1.1 and 10.0.10

**Comment by PVince81** [comment] 2019-05-07 08:57
Let's defer this one. Likely an old overseen bug.

**Comment by VicDeo** [comment] 2019-05-23 10:28
Mount point names are unique per mount provider so federated and local shares could have collisions in mount point names.
The last mount provider wins in this case. And it's a federated mount provider.
lib/private/Files/Config/MountProviderCollection.php::getMountsForUser is the place of impact.

To change it we need to either 
1. pass already taken mount point names into `IMountProvider::getMountsForUser` 
or
2. iterate through all provider results in `MountProviderCollection.php::getMountsForUser` and update duplicates.

I like the former approach

**Comment by VicDeo** [comment] 2019-05-29 21:43
This was possibly introduced when federated shares were separated from internal shares.
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/SharedMount.php#L85-L104
and 
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/SharedMount.php#L122-L151

should be put into the core and operate on all available moveable mounts, not only on internal shares

**Comment by skshetry** [comment] 2019-06-13 09:12
I am not able to access the files as well. 

### Steps to reproduce:
1. Create two servers from owncloud 10.2.0 tarball.
2. Share `Photos` from one local to fed server.
3. Accept the share.
4. No `Photos (2)` folder exists. Same `Photos` gets shared. 

I can get the files listing on the webUI but, cannot access files (on both sides). I get the following error when trying to access a file:
```
Sabre\DAV\Exception\NotFound
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message/>
</d:error>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">...</d:error>
```

**Comment by micbar** [comment] 2019-06-21 09:17
@skshetry Is there anything to develop?

**Comment by skshetry** [comment] 2019-06-21 09:55
@micbar I think this regression is not covered. We could do on next sprint.

**Comment by paurakhsharma** [comment] 2019-06-25 10:33
Assigning myself for acceptance tests.

**Comment by micbar** [comment] 2019-07-26 14:05
@VicDeo Is this issue addressed in one of your PRs?

**Comment by micbar** [comment] 2019-08-02 11:25
@VicDeo @jvillafanez 
Assigning JP because of Victars vacation.

Seems to me that he didn't start fixing it.

**Comment by VicDeo** [comment] 2019-08-02 20:16
See https://github.com/owncloud/core/issues/35319, but it breaks a lot of existing tests

**Comment by jvillafanez** [comment] 2019-08-09 10:34
I've reached the same point as @VicDeo . I've checked the updated https://github.com/owncloud/core/pull/35319 PR, and also a similar patch that I created, but there are simply too many failing tests, most of them unrelated to the changes.

The main problem is that neither the failing tests are unit tests, nor they're isolated (this is just a quick scroll, there might be some more).
Some of the affected tests are:
* OCA\Files_Versions\Tests\VersioningTest
* OCA\Files_Trashbin\Tests\TrashbinTest
* OCA\Files_Sharing\Tests\SharedStorageTest
* OCA\Files_Sharing\Tests\EtagPropagationTest
* OCA\Files_Sharing\Tests\ApiTest

I've checked a bit the OCA\Files_Sharing\Tests\ApiTest and it also doesn't seem to cleanup after itself. I mean, the changes we're doing in the tests implies moving the mount point in order to avoid overlapping. Due to the tests not cleaning up the mountProviderCollection, next tests will fail because wrong assumptions. Note that I don't see any option to reset a service in the server in order to recreate it from scratch, but in any case this will likely break other tests because other service might not be wired properly.

@micbar we need to decide what to do here. Assuming that we can fix all the tests, my estimation doesn't go lower than 1 week dedicated, probably more. It's will be 1 week putting bandaids to make the tests pass. Worst case, we could spend 1 week and fail to fix some of the tests, throwing away all the work.
Rewritting the tests to make them unit tests (which is what we should do) will likely take more time, without any guarantee we can rewrite all the tests.

**Comment by micbar** [comment] 2019-08-09 12:02
@jvillafanez 
Please spend 2md next week on the test suite.
Victar will be back the week after.
Please coordinate with him and @patrickjahns and evaluate the success/failure on this fix in the context of the Release.

**Comment by jvillafanez** [comment] 2019-08-14 08:55
PR moved to https://github.com/owncloud/core/pull/36029
For now, the PR itself is untested, so not sure if it works properly. I assumed the original PR worked before, so I focused on fixing the tests.

There are A LOT of things wrong with the tests. Fixing things properly will take a lot of time taking into account there are changes in the code required, which are likely too late to be made.

**Comment by VicDeo** [comment] 2019-08-22 08:11
https://github.com/owncloud/core/pull/36029 has been merged

**Comment by PVince81** [comment] 2019-08-22 09:25
@jvillafanez can we close or is there more to it ?

**Comment by jvillafanez** [comment] 2019-08-22 12:54
I vote for close. We'd need to schedule time to fix the "unit" tests, which is out of the scope of this issue anyway.

**Closed** 2019-08-22 13:15 UTC
Labels: bug, p3-medium
