### ISSUE TITLE
Trash bin over quote.

### ISSUE THREAD

**Issue by borconi** [owncloud/core#16920] opened 2015-06-14 10:46 UTC
<b> Server </b>
Ubuntu 14.04
Lighttpd 1.4.33
PHP-FPM 5.9
OwnCloud 8.0.3

<b> Client </b>
Windows 7
Desktop SyncClient 1.8.1

<b> Scenario </b>

User X - shares a folder with the group. Folder size about 10 Gb, user X quota 15 GB.
Each user in the group, except X, have quote set to 2 GB.

One of the users - Lets call him Y - , on his local machine, MOVES the shared folder to a path OUTSIDE, the Client Sync watch folder, all data from server and from everybody else who synced it, get deleted (Fair enough till here). 
- Data does not go into User X trash bin since it's too big (expected behaviour nothing wrong).

After a few days I realized, user Y trash folder size is 264 GB on the server!!!!!!! when looking into it it contained several versions of the deleted shared folder, all from the same date when he moved the folder on his local computer.

Logging in to OC with user Y credential and checking his quote, showed X Mb used out of 2 Gb.

Problem:
I'm rsyncing all the data folder, to another storage (for backup purpose) with a 7 day incremental, and I almost run out of space, I spotted this by accident only, since this does not shows anywhere in OC log or any OC web interface. 

Any idea's?

**Comment by LukasReschke** [comment] 2015-06-14 10:56
Thanks for reporting issues back to us. You state that you use "OwnCloud 5.3" which however never was a valid release, do you refer to ownCloud 5.0.3?

In this case please be aware that ownCloud 5.x has reached EoL and you are strongly encouraged to update to ownCloud 8. (go 5->6->7->8), see https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule for a maintenance and release schedule.

**Comment by borconi** [comment] 2015-06-14 10:58
Sorry, BIG typo, just corrected it to the right version.

**Comment by LukasReschke** [comment] 2015-06-14 11:01
> After a few days I realized, user Y trash folder size is 264 GB on the server!!!!!!! when looking into it it contained several versions of the deleted shared folder, all from the same date when he moved the folder on his local computer.

@schiesbn FYI - trashbin related

**Comment by borconi** [comment] 2015-06-14 11:12
Here is a link with all the OC logs from the last 2 weeks:

https://cloudstorage.e-systems.co.uk/index.php/s/157NVORIn2f7fvx

**Comment by PVince81** [comment] 2015-08-18 09:23
@schiesbn @VicDeo any idea ?

**Comment by PVince81** [comment] 2015-10-09 11:19
Duplicate of https://github.com/owncloud/core/issues/15371

**Closed by PVince81** 2015-10-09 11:19 UTC
Labels: app:files_trashbin, bug
