### ISSUE TITLE
Strings in admin settings are not using translated strings.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27687] opened 2017-04-19 15:26 UTC
### Steps to reproduce

1. Change language to a different language to english.

### Expected behaviour
Strings in the left sidebar are translated.

### Actual behaviour
They are not translated, but I can find those strings in the localization json files.

For example 

lib/l10n/de.js:    "Help & Tips" : "Hilfe & Tipps"

But in the left sidebar in admin settings:

![screen shot 2017-04-19 at 17 24 12](https://cloud.githubusercontent.com/assets/9048796/25188088/2a058e6e-2525-11e7-9e92-987a690f5bf4.png)

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**Browser**
Chrome Edge IE11

**Logs**
```

```

**Comment by PVince81** [comment] 2017-04-19 15:32
Closing as duplicate of https://github.com/owncloud/core/issues/27327

**Closed by PVince81** 2017-04-19 15:32 UTC
Labels: bug, junior job, sev3-medium
