### ISSUE TITLE
Share a folder, non-resharably, with a group of which owner is a member, lose owner rights to contents

### ISSUE THREAD

**Issue by ajacobsmocana** [owncloud/core#14933] opened 2015-03-16 16:11 UTC
This is a new bug in version 8.  To reproduce:

(1) Create a folder.
(2) Share with a group of which owner is a member, with reshare rights disallowed.
(3) Create a new folder inside the first folder.
(4) Try to share the subfolder-- disallowed, even though I created the folder.

**Comment by karlitschek** [comment] 2015-03-16 16:24
@schiesbn is this a regression?

**Comment by PVince81** [comment] 2015-03-16 17:08
Confirmed on master.

1. Create a folder "folder" as admin
2. Share "folder" with the group "Admin", remove "can share" permission
3. Enter folder "folder"
4. Create a subfolder "folder/sub"
5. Share "sub": dropdown says "shared with you by XYZ, not allowed to share"

**Comment by PVince81** [comment] 2015-03-16 17:10
On stable7 the dropdown doesn't block you directly, but if you try to share with someone else it still says "No reshare permission".

On stable6 it works, I can share with someone else.

So this is a regression from stable6.

**Comment by PVince81** [comment] 2015-03-16 17:10
CC @jnfrmarks for the matching test case

**Comment by rullzer** [comment] 2015-03-17 11:36
It seems the dropdown fails because we send the reshare. However, in share.php also stuff breaks and an exception is thrown: https://github.com/owncloud/core/blob/master/lib/private/share/share.php#L1995

So the same error occurs when we try to do this from the OCS Api.

**Comment by PVince81** [comment] 2015-03-18 18:42
The dropdown code should check "uid_owner". If that matches the current user, then discard the "reshare" information and consider it a new share.

**Comment by magicvodi** [comment] 2015-03-26 15:12
I don't know, if its connected to this issue, but when I share a folder with a group (even if I'm not the member of this), I can't share a subfolder with a member of the group with extended rights.

folder       - shared with group user (read-only)
+--- subfolderA    -   when I share it with UserA (member of group user) I can't give edit rights 
+--- subfolderB    -

**Comment by rullzer** [comment] 2015-04-17 11:28
This should be taken care of together with #5873. Then the sharing dialog should use the same endpoint as all the other clients. So we do not have to duplicate code.

Moving to 8.2 as we won't get it into 8.1

**Comment by PVince81** [comment] 2015-04-22 07:57
Closing in favor of https://github.com/owncloud/core/issues/15771 which provides a fix

**Closed by PVince81** 2015-04-22 07:57 UTC
Labels: bug, regression, sharing
