### ISSUE TITLE
[User Management] Email address textbox is not visible after refreshing the screen.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#13550] opened 2015-01-21 13:42 UTC
### Steps to reproduce

1. Go to users
2. Activate send to email address to new users.
3. Refresh the browser.

### Expected behaviour
Email address textbox should be visible.

### Actual behaviour

Email address textbox disappears

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Firefox

**Comment by karlitschek** [comment] 2015-01-21 14:18
@LukasReschke

**Comment by LukasReschke** [comment] 2015-01-21 14:26
Dupe of https://github.com/owncloud/core/issues/12727 – I added that one to the 8.1 milestone.

**Closed by LukasReschke** 2015-01-21 14:26 UTC
Labels: bug
