### ISSUE TITLE
ownCloud Dekstop App for Windows does not synchronize files and folders with space at the end of the name

### ISSUE THREAD

**Issue by SDA-Admin** [owncloud/core#23956] opened 2016-04-12 21:40 UTC
### Steps to reproduce
1. Using a browser, create a folder or file with a space in the end (for example, "Test Folder " or "Test File ", but not "Test File .txt")
2. Using a browser, create a folder or file with NO space in the end, wait till it gets synchronized, then rename it by adding a space in the end (for example, create a folder "Test Folder", wait for synchronization, then rename it to "Test Folder ")

### Expected behaviour
Expected to have such files and folders synchronized by the desktop app.

### Actual behaviour
In step 1, a folder or a file with the space in the end will be successfully created using a browser, but they will not be synchronized by the desktop app. In step 2, after the folder is synchronized and then renamed to have a space in the end, it will be removed by desktop app with a pop-up balloon saying the folder has been removed.

### Server configuration

**ownCloud version:** (see ownCloud admin page)
 8.1.1

### Client configuration
**Browser:** IE 11 / Firefox 45.0.1

**Operating system:** Windows 7

**ownCloud Windows Desktop App version:** 2.1.1 (build 5837)

Notes: This is all the information I currently have. I can find out and provide other information if needed. I am also wondering if it could be just a Windows problem with not working correctly with folders or files with a space in the end because the android app does show such files.

**Comment by MorrisJobke** [comment] 2016-04-12 22:47
Duplicate of https://github.com/owncloud/client/issues/4263 and this is a technical limitation of windows.

**Closed by MorrisJobke** 2016-04-12 22:47 UTC

**Comment by SDA-Admin** [comment] 2016-04-12 23:21
I was afraid that that's the case. Thanks.
