### ISSUE TITLE
app:enable files_sharing  leads to internal server error

### ISSUE THREAD

**Issue by kku** [owncloud/core#35450] opened 2019-06-06 19:50 UTC
### Steps to reproduce
1.install oc 10.2.0 from tarball
2.before upgrade via web interface, oc complains about non-compliant apps that should be disabled, one of which is files_sharing
3.after upgrade, run occ app:enable files_sharing

### Expected behaviour
OC should start normally

### Actual behaviour
OC web interface shows 
'''
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 127.0.0.1
    Request ID: XPlrVeYoGgle3SkgZ4pADgAAAMU
'''

### Server configuration
**Operating system**:
Fedora 30
**Web server:**
apache2
**Database:**
mariadb
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.2
**Updated from an older ownCloud or fresh install:**
update from 10.0
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
"xx.xxx.113.12","user":"kku","app":"webdav","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"Exception: HTTP\/1.1 503 Error: Call to undefined method OC\\Share20\\Share::newAttributes(): {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"Error: Call to undefined method OC\\\\Share20\\\\Share::newAttributes()\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/owncloud\\\/remote.php(70): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/usr\\\/share\\\/owncloud\\\/remote.php(169): handleException(Object(Error))\\n#6 {main}\",\"File\":\"\\\/usr\\\/share\\\/owncloud\\\/remote.php\",\"Line\":68}"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment] 2019-06-21 14:59
@kku 
1. it's unclear from your steps what is the initial and the target version for your upgrade.
2. **files_sharing** is a shipped app and it should be replaced with **files_sharing** from a new release on upgrade.
and release always does contain a compatible **files_sharing** version.

so 
>before upgrade via web interface, oc complains about non-compliant apps that should be disabled, one of which is files_sharing

should never happen if files_sharing were replaced.

**Comment by VicDeo** [comment] 2019-12-05 12:47
I'm closing this issue due to lack of communication. Feel free to reopen it if it is still reproducible.

**Closed by VicDeo** 2019-12-05 12:47 UTC
