### ISSUE TITLE
External storage scanning don't work when using session credentials

### ISSUE THREAD

**Issue by QuentinC** [owncloud/core#25581] opened 2016-07-22 15:10 UTC
Following https://github.com/owncloud/core/issues/25511#issuecomment-234562369

### Steps to reproduce
1. Configure owncloud using LDAP auth and an external storage backend using session credentials (SMB in my case, but I strongly suspects that the behavior is the same with other backends). Use the system cron.
2. Open the web UI
3. The storage scanning don't occur, folder sizes stay to "waiting"

### Expected behaviour
Folder sizes should update with the scanning.

### Actual behaviour
No folder sizes update. Staying on "Waiting" ("En attente" in French)

### Server configuration
**Operating system**:
Debian Jessie x64

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16)

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 RC1 (beta)

**Updated from an older ownCloud or fresh install:**
Updated using ownCloud daily tgz

**Where did you install ownCloud from:**
Owncloud daily TGZ

**Signing status (ownCloud 9.0 and above):**
Integrity check is disabled. But I'm using the original sources, with this pull request applied: https://github.com/owncloud/core/pull/25531 

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0

Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external

**The content of config/config.php:**
{
    "system": {
        "instanceid": "*****",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*****"
        ],
        "datadirectory": "\/home\/cloud\/data",
        "skeletondirectory": "\/home\/cloud\/skeleton",
        "overwrite.cli.url": "*****",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "9.1.0.11",
        "dbname": "cloud",
        "dbhost": "*****",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_domain": "*****",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "loglevel": 0,
        "ldapIgnoreNamingRules": false
  }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes: SMB on a Windows server 2012 R2

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, a LDAP (on the Windows 2012 AD)

#### LDAP configuration (delete this part if not used)
Too big to fit the issue page. I can upload it if necessary.

### Client configuration
**Browser:** Chrome / IE / Firefox...

**Operating system:**
All

#### Web server error log
Nothing relevant

#### ownCloud log (data/owncloud.log)
{"reqId":"mUEO77IXcH\/oGIlGD4Qu","remoteAddr":"192.168.1.20","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'Thumbs.db' is not accessible or present !!!","level":0,"time":"2016-07-22T15:08:02+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Home","user":"quentin"}

#### Browser log
Nothing

**Comment by RealRancor** [comment] 2016-07-22 16:27
@QuentinC 

> The Log-in credentials, save in session mechanism uses the ownCloud login credentials of the user to connect to the storage. These are not stored anywhere on the server, but rather in the user session, giving increased security. The drawbacks are that sharing is disabled when this mechanism is in use, as ownCloud has no access to the storage credentials, and **background file scanning does not work**.

from https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/external_storage/auth_mechanisms.html#password-based-mechanisms

**Comment by QuentinC** [comment] 2016-07-22 16:35
This is what I thought, but isn't there a way to use session saved credentials in the cron script? 
Or scan using some Ajax requests? 

I'm not sure, but I think I remember that this was working before doesn't? 

If it's really not possible, you shouldn't disable the field saying "waiting" !

**Comment by DeepDiver1975** [comment] 2016-07-25 09:09
> This is what I thought, but isn't there a way to use session saved credentials in the cron script?

This is not possible - using the system cron you have no access to the session. 


> Or scan using some Ajax requests?

If you move back to ajax cron mode this might work out - as a work around for the time being.



> If it's really not possible, you shouldn't disable the field saying "waiting" !

If you navigate into the folders there will be some scanning triggered within your web request which will help to calculate the folder size.

I'm closing this because this works as designed

**Closed by DeepDiver1975** 2016-07-25 09:09 UTC

**Comment by QuentinC** [comment] 2016-07-25 09:19
Ok, thanks for your reply !

I can confirm that using Ajax cron works. As I only have SMB storage, I will keep using this !

Thanks !
