### ISSUE TITLE
After update from 9.0.4 to 9.1 occ files:scall --all does not work correctly.

### ISSUE THREAD

**Issue by mtdew365** [owncloud/core#25611] opened 2016-07-26 00:10 UTC
### Steps to reproduce
1.  Update to 9.1.0 from 9.0.4
2. Run sudo -u www-data /usr/share/nginx/html/owncloud/occ files:scan --all

### Expected behaviour
Update all the files.

### Actual behaviour
Scanning files for 3 users
Starting scan for user 1 out of 3 (jbergmann)
Home storage for user jbergmann not writable
Make sure you're running the scan command only as the user the web server runs as
Starting scan for user 2 out of 3 (ocadmin)
Starting scan for user 3 out of 3 (tbergmann)
Home storage for user tbergmann not writable
Make sure you're running the scan command only as the user the web server runs as

### Server configuration
**Operating system**:  
Ubuntu 16.04.2 LTS (armv7l)

**Web server:** 
nginx/1.10.0 (Ubuntu)

**Database:**
5.7.13-0ubuntu0.16.04.2 - (Ubuntu)

**PHP version:**
7.0.8-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
Upgrade from 9.0.4

**Where did you install ownCloud from:**
Install from tar.bz2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

Enabled:
  - activity: 2.3.2
  - calendar: 1.3.1
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notes: true
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
{
    "system": {
        "instanceid": "ocdwjmgr21tl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/nginx\/html\/owncloud\/apps-appstore",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "trusted_domains": [
            "192.168.1.8",
            "localhost",
            "cloudshell.bergmann.c"
        ],
        "datadirectory": "\/oc-data",
        "overwrite.cli.url": "https:\/\/192.168.1.8\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "myowncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Chicago",
        "log_rotate_size": 1048576000,
        "openssl": {
            "config": "\/usr\/lib\/ssl\/openssl.cnf"
        },
        "mount_file": "oc-data\/mount.json",
        "installed": true,
        "maintenance": false,
        "loglevel": 4,
        "htaccess.RewriteBase": "\/owncloud",
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome Version 52.0.2743.82 (64-bit)
**Operating system:**
Fedora 24 (64-bit)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by mtdew365** [comment] 2016-07-26 00:52
I regressed back to v9.0.4.  The problem did not follow.  9.0.4 works correctly without errors.

**Comment by jknockaert** [comment] 2016-07-27 11:58
Same behaviour observed here on a roughly similar setup.

**Comment by elvetemedve** [comment] 2016-08-03 19:35
I used to scan only sub-directories by running 
`/usr/share/webapps/owncloud/occ files:scan --path=/geza/files/downloads/`.
Now none of my files are going to be scanned. Even if I add the `-vvv` switch no more details displayed, only this:
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```

**Comment by kontaxis** [comment] 2016-08-06 18:58
@mtdew365 has any user shared files with jbergmann? I had the same error. Doing an strace revealed lstat system calls for files owned by a different user and shared with the user on which the scan failed. Of course at the OS level all files are owned by www-data. Try removing the shares (not the actual files) and repeat the scan. It should produce no errors.

**Comment by mtdew365** [comment] 2016-08-07 02:16
@kontaxis - Yes.  Users have files shared with jbergmann.  Do you mean remove ALL shares with another user to see if the issue goes away?  I just want to make sure I am doing the correct thing.

**Comment by kontaxis** [comment] 2016-08-07 02:35
@mtdew365 If I understand this bug correctly then everything shown in "Shared with you" for user jbergmann must go.

**Comment by mtdew365** [comment] 2016-08-07 02:46
@kontaxis Thanks.  I will remove all shares.  Upgrade to 9.1.0 and then create the shares again.  I will report back on my results.

**Comment by kontaxis** [comment] 2016-08-07 02:49
@mtdew365 Note that future scans will still fail after you recreate the shares. This is not a permanent fix. It only serves as proof that scans fail because of shared files.

**Comment by mtdew365** [comment] 2016-08-07 02:54
@kontaxis Ok thanks.  I need the shares in place.  I will stay on 9.0.4 until a permanent fix is in place.

**Comment by kontaxis** [comment] 2016-08-07 03:18
A few more context for people interested in the root cause.

apps/files/lib/Command/Scan.php calls function scan() in lib/private/Files/Utils/Scanner.php. Line 162 checks "if the home storage isn't writable then the scanner is run as the wrong user". It all comes down to is_dir() and file_exists() calls.

It seems that shares are considered mount points located directly under the user's home directory. (the one receiving the shares) However nothing is actually there as far as the OS is concerned. So is_dir() and file_exists() fail and a ForbiddenException is thrown.

**Comment by kontaxis** [comment] 2016-08-07 04:00
Looks like instanceOfStorage('\OC\Files\Storage\Home') is 1 for shared files in lib/private/Files/Utils/Scanner.php:162. I think this wasn't true in earlier versions. Subsequent checks fail and a ForbiddenException is thrown.

**Comment by PVince81** [comment] 2016-08-09 08:03
You might want to retry after applying the fix for https://github.com/owncloud/core/issues/25506

**Comment by PVince81** [comment] 2016-08-19 10:42
Closing as duplicate of https://github.com/owncloud/core/issues/25755 which contains the solution: upgrade to 9.1.1 RC1

**Closed by PVince81** 2016-08-19 10:42 UTC
Labels: bug, comp:filesystem, sev2-high

**Comment by koenlek** [comment] 2016-09-08 23:03
@PVince81 , where should I find documentation about how to upgrade to 9.1.1 RC1? I currently have 9.1.0 from debian repository (9.1.0-1.1 from  http://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/) 

Our users report several issues since updating from 9.0.3 to 9.1.0. For most or even all, the clients don't sync anymore. And some ran into some strange 'undeletable folders'. Folders visible in web interface, but non-existent in `/var/www/owncloud/data`. Also, I get a "CSync failed to access <file_url>" in the client on those folders.

I really hope 9.1.1 RC1 can help solve this. Am running a backup of all data now.

**Comment by PVince81** [comment] 2016-09-09 06:54
9.1.1 RC2 is out which solve even more issues related to sharing.
The scan bug should be fixed in 9.1.1 RC1.

The undeletable folders is often due to a PHP timeout which occurred and created a discrepancy between database and filesystem. This can be solved by running `occ files:scan --all`

**Comment by koenlek** [comment] 2016-09-09 11:18
Just upgraded to 9.1.1 RCS2. Upgrade ran properly, and so did `occ files:scan --all`. Files scan did not report any errors (not sure if it does report issues if it finds and/or fixes any?).  Afterwards same problem remain. I opened a new issue here: https://github.com/owncloud/core/issues/26080

**Comment by PVince81** [comment] 2016-09-12 07:22
@koenlek thanks, let's investigate there
