### ISSUE TITLE
Problems with multibyte unicode characters in filenames

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#4513] opened 2013-08-19 10:27 UTC
### Expected behaviour

ownCloud should handle multibyte unicode characters in filenames correctly.
### Actual behaviour

ownCloud drops every character after (multibyte) unicode character in a filename
### Steps to reproduce
1. Create a file like "%&:hankey:.pdf" on your computer
2. Upload it to ownCloud
3. After the upload, ownCloud displays the name correctly
4. reload the page
5. After reloading the page ownCloud shows only "%&"
### Server configuration

Operating system:
Debian 7

Web server: 
Apache

Database:
MySQL

PHP version:
PHP 5.4.x
The mbstring extension is enabled

ownCloud version:
latest master 
### Client configuration

Browser:
Chromium 30.0.1592.0

Operating system:
OS X

**Comment by MorrisJobke** [comment] 2015-07-30 13:50
See https://github.com/owncloud/core/pull/17978#issuecomment-126332406 for arguments for both ways.

**Comment by jaller94** [comment] 2016-09-26 11:19
This can still cause severe problems on ownCloud 9.0.5:
* All files with a 4 byte unicode character can't be edited, downloaded or deleted via ownCloud.
* "Share" a White Screen of Death
* Share your own root folder

### Steps to reproduce
## Preparation
1. Install ownCloud
2. Create user "Romeo" and "Juliet" (names don't matter)
3. Create a non-empty text file on your Desktop

## "Share" a White Screen of Death
4. Name that file "love letter🐦.txt" (4 byte unicode somewhere in the name)
5. Upload it to Romeo's root folder. (Don't reload the page as it might break your ability to share the file.)
6. Share it with Juliet.

**The result:** After reloading the page Romeo sees this file as "love letter". From now on http calls from Juliet won't have any content (resulting in a white page). The server replies with 200 and doesn't log anything (no info, no warning, no error). Romeo is not affected by this white screen.

**What happened?**: The actual file in the file system got created correctly. The entry in the database does not contain the file extension.

## Share your own root folder
4. Name that file "🐦love letter.txt" (4 byte unicode as the first character)
5. Upload it to Romeo's root folder. (Don't reload the page as it might break your ability to share the file.)
6. Share it with Juliet.

**The result:** After reloading the page Romeo sees this file as "files". Juliet sees a folder called "(2)". This folder contains all files from Romeo. Juliet also sees the file as "(2)" inside that folder "(2)".

**What happened?**: I think it stoped at the 4 byte character and shareed Romeo's /

### My System
## Server
**ownCloud:** New ownCloud 9.0.5 Community instance

**Operating System:** ubuntu-16.04.1-server-i386

**Database:** 10.0.27-MariaDB-0ubuntu0.16.04.1

**phpinfo:** https://gist.github.com/jaller94/92fe27758d2394ba6cf2442d6e9578c0

## Client
**Browser**: Firefox 45.2.0 and IE 11 on Windows 7

**Comment by jaller94** [comment] 2016-09-26 12:57
## Uploading "..🐦.txt"
Uploading a file "..🐦.txt" into my home directory (bug using: trying to get access to the parent dir):

**The result:** I can't access my home directory anymore. An error is shown: 
`This directory is unavailable, please check the logs or contact the administrator`.

**owncloud.log:**
```
Fatal 	webdav 	Exception: {"Message":"","Exception":"OCP\\Files\\InvalidPathException","Code":0,"Trace":"#0 \/var\/www\/html\/lib\/private\/files\/node\/node.php(179): OC\\Files\\Node\\Node->getFileInfo()\n#1 \/var\/www\/html\/apps\/dav\/lib\/connector\/sabre\/sharesplugin.php(162): OC\\Files\\Node\\Node->getId()\n#2 [internal function]: OCA\\DAV\\Connector\\Sabre\\SharesPlugin->handleGetProperties(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\Connector\\Sabre\\Directory))\n#3 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(999): Sabre\\Event\\EventEmitter->emit('propFind', Array)\n#5 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(919): Sabre\\DAV\\Server->getPropertiesByNode(Object(Sabre\\DAV\\PropFind), Object(OCA\\DAV\\Connector\\Sabre\\Directory))\n#6 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(334): Sabre\\DAV\\Server->getPropertiesForPath('', Array, 1)\n#7 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#10 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#12 \/var\/www\/html\/remote.php(138): require_once('\/var\/www\/html\/a...')\n#13 {main}","File":"\/var\/www\/html\/lib\/private\/files\/node\/node.php","Line":78,"User":"jaller94"} 	2016-09-26T12:45:56+00:00
```

## Sharing it with another user
Before my home directory became unavailable I shared it with my Test-Account "tester" (because it got /🐦test.txt as / :

**The result:** After the user "tester" logs into owncloud all http-requests get replied with 200 but don't contain any content. (white screen)

**owncloud.log:**
```
Error 	PHP 	TypeError: Argument 3 passed to OC\Files\Cache\Shared_Cache::__construct() must implement interface OCP\Files\Cache\ICacheEntry, boolean given, called in /var/www/html/apps/files_sharing/lib/sharedstorage.php on line 588 at /var/www/html/apps/files_sharing/lib/cache.php#63 	2016-09-26T12:50:19+00:00
```

**Comment by jaller94** [comment] 2016-09-26 14:25
I was able to reproduce both behaviours in the current ownCloud 9.1.1.3.
The server setup is the same as in both of my posts above.

But instead of a White Screen of death Juliet gets a message when a file `love letter🐦.txt` was shared with her:
![juliet_error](https://cloud.githubusercontent.com/assets/10872136/18837847/9b36095e-8405-11e6-9ff9-cdccf74fb9af.png)

**owncloud.log:**
```
Fatal 	cron 	Argument 3 passed to OCA\Files_Sharing\Cache::__construct() must be an instance of OCP\Files\Cache\ICacheEntry, boolean given, called in /var/www/html/apps/files_sharing/lib/sharedstorage.php on line 325 	2016-09-26T14:21:25+00:00
Error 	index 	Exception: {"Exception":"TypeError","Message":"Argument 3 passed to OCA\\Files_Sharing\\Cache::__construct() must implement interface OCP\\Files\\Cache\\ICacheEntry, boolean given, called in \/var\/www\/html\/apps\/files_sharing\/lib\/sharedstorage.php on line 325","Code":0,"Trace":"#0 \/var\/www\/html\/apps\/files_sharing\/lib\/sharedstorage.php(325): OCA\\Files_Sharing\\Cache->__construct(Object(OCA\\Files_Trashbin\\Storage), Object(OCA\\Files_Trashbin\\Storage), false)\n#1 \/var\/www\/html\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(387): OC\\Files\\Storage\\Shared->getCache('', Object(OCA\\Files_Trashbin\\Storage))\n#2 \/var\/www\/html\/lib\/private\/Files\/View.php(1362): OC\\Files\\Storage\\Wrapper\\Wrapper->getCache('')\n#3 \/var\/www\/html\/lib\/private\/Files\/Node\/Root.php(180): OC\\Files\\View->getFileInfo('\/Juliet')\n#4 \/var\/www\/html\/lib\/private\/Files\/Node\/Root.php(342): OC\\Files\\Node\\Root->get('\/Juliet')\n#5 \/var\/www\/html\/lib\/private\/Server.php(809): OC\\Files\\Node\\Root->getUserFolder('Juliet')\n#6 \/var\/www\/html\/lib\/private\/User\/Session.php(384): OC\\Server->getUserFolder('Juliet')\n#7 \/var\/www\/html\/lib\/private\/User\/Session.php(438): OC\\User\\Session->prepareUserLogin()\n#8 \/var\/www\/html\/lib\/private\/User\/Session.php(287): OC\\User\\Session->loginWithPassword(*** sensitive parameters replaced ***)\n#9 \/var\/www\/html\/core\/Controller\/LoginController.php(196): OC\\User\\Session->login(*** sensitive parameters replaced ***)\n#10 [internal function]: OC\\Core\\Controller\\LoginController->tryLogin(*** sensitive parameters replaced ***)\n#11 \/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#12 \/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#13 \/var\/www\/html\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#14 \/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('LoginController', 'tryLogin', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#15 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#16 \/var\/www\/html\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#17 \/var\/www\/html\/lib\/base.php(891): OC\\Route\\Router->match('\/login')\n#18 \/var\/www\/html\/index.php(39): OC::handleRequest()\n#19 {main}","File":"\/var\/www\/html\/apps\/files_sharing\/lib\/Cache.php","Line":64} 	2016-09-26T14:16:49+00:00 
```

**Comment by PVince81** [comment] 2016-10-17 06:10
see https://github.com/owncloud/core/issues/21899 for additional info

**Comment by PVince81** [comment] 2016-10-17 06:12
- [ ] requires: adding tests for 4 byte unicode characters: https://github.com/owncloud/core/pull/17978
- [ ] requires: doctrine migrations: #14851 

@DeepDiver1975 anything else ?

**Comment by butonic** [comment] 2016-11-28 13:46
has no corresponding SF case -> blue ticket

**Comment by PVince81** [comment] 2016-12-12 09:02
@DeepDiver1975 doctrine migrations merged. Can you move forward with the 4 byte unicode PR ?

**Comment by michaelstingl** [comment] 2016-12-20 14:32
for reference: 00006329

**Comment by cdamken** [comment] 2017-03-07 19:41
Hi Guys, could you please tell me some feedback from this issue?

**Comment by DeepDiver1975** [comment] 2017-03-08 06:57
Fixed with oc10

**Closed by DeepDiver1975** 2017-03-08 06:57 UTC
Labels: comp:core, enhancement, green-ticket

**Comment by PVince81** [comment] 2017-03-08 08:42
raise doc ticket for configuration hints: https://github.com/owncloud/documentation/issues/2924
