### ISSUE TITLE
OC 8.0: versions/restore issues

### ISSUE THREAD

**Issue by zebtom** [owncloud/core#14183] opened 2015-02-13 00:50 UTC
When restoring an older version of a file (click on 'Versions' and then 'Restore') the web UI is not refreshed in OC8. The file is actually restored, but the main window is not refreshed, which is a bit confusing. In OC 7.0.x, the web UI is refreshed after a file is restored.

Also, in OC8 file preview in the 'Versions' menu doesn't work (at least for .txt, .php, .c, ... files).

Both issues confirmed on demo.owncloud.org

**Comment by karlitschek** [comment] 2015-02-13 02:02
@schiesbn Can you have a look?

**Comment by PVince81** [comment] 2015-08-21 16:08
Duplicate of https://github.com/owncloud/core/issues/14559
Already resolved, works in 8.0.6 or 8.1.1.

**Closed by PVince81** 2015-08-21 16:08 UTC
Labels: bug
