### ISSUE TITLE
Wrong image rotation

### ISSUE THREAD

**Issue by massa007** [owncloud/core#21485] opened 2016-01-06 13:06 UTC
Hi all,

I want to refer to this issue: https://github.com/interfasys/galleryplus/issues/29
I have the same problem and it seems there is no open issue yet.

Pictures are wrong rotated in gallery, as well as thumbnails and file explorer in owncloud.
If I download the pictures it´s all fine and my windows app shows correctly.

![20151229_141403](https://cloud.githubusercontent.com/assets/16576171/12143152/8e2892d8-b47e-11e5-9e74-7bfc2b1c5053.jpg)

**Operating system**: Ubuntu Server 14.04

**Web server:** nginx current version

**Database:** MySQL

**PHP version:** Current version, exif enabled

**ownCloud version:** (see ownCloud admin page): 8.2.1

**Updated from an older ownCloud or fresh install:** fresh installation

**Comment by Xenopathic** [comment] 2016-01-06 13:26
When you rotated the image, it added metadata that tells viewers the image should be rotated: http://regex.info/exif.cgi?dummy=on&imgurl=https%3A%2F%2Fcloud.githubusercontent.com%2Fassets%2F16576171%2F12143152%2F8e2892d8-b47e-11e5-9e74-7bfc2b1c5053.jpg (see EXIF Metadata: Orientation: Rotate 90 CW)

We should detect such metadata in preview generation, but there's not much we can do about displaying it in the browser if the browser ignores the metadata...

**Comment by massa007** [comment] 2016-01-06 14:31
Just for your info, there is an owncloud clone used by some universities in germany. It is named sciebo. It´s nearly the same as original owncloud just with minor changes. So they used owncloud source for developing their own version.

The picture above was shared within sciebo by one of my friends and i synchronized it directly with my owncloud. In sciebo the rotation is correct but in my owncloud it is wrong.
So there must be something that the clone is doing better than my owncloud.

**Comment by MorrisJobke** [comment] 2016-01-06 19:46
> In sciebo the rotation is correct but in my owncloud it is wrong.
> So there must be something that the clone is doing better than my owncloud.

Weird - I don't think they change such internals, but I will ask them.

Back some time I fixed the rotation of the previews and it worked just fine with a lot of test images. See https://github.com/owncloud/core/pull/13448

Maybe also try the original gallery app - that's also what is very likely used at sciebo: https://github.com/owncloud/gallery

I can't reproduce the rotation issues on my local owncloud. Maybe you have an old version of the gd/imagick php module.

**Comment by ikeewee** [comment] 2016-01-08 05:50
Hi,

I'm not sure if this is relevant but I have uploaded an image created on an iPhone 5S to one ownCloud account and it displays correctly in the image gallery however if I share that image to a second account on the same ownCloud server the image displays with incorrect rotation

**Comment by oparoz** [comment] 2016-01-08 06:58
Thanks @ikeewee . 

Could one of you write down a 100% reproducible test case? Preferably one which doesn't involve Gallery, so no full screen preview before sharing per example.

Something like:

1. upload
2. thumbnail in Files is OK
3. share
4. open 2nd instance
5. thumbnail is wrong

but more detailed if it needs to be.

**Comment by ikeewee** [comment] 2016-01-08 10:27
These are the steps I can use to reproduce it here. This is on a recent fresh install of ownCloud 8.2.2 running on Linux Mint 17.2

1. Take photo on iPhone and select the ownCloud app from the iPhone's share menu. App opens, choose Photos folder as destination and wait for photo to sync to server.
2. Fire up Chrome and log in to ownCloud using first account. Select the Photos folder, thumbnail is correct. Click the grey share link next to the name of the file and share with second account. Log out
3. Log in to second account. The shared file is in the root folder and the thumbnail is rotated 90 degrees to the left

This also happens if I share the photo directly from within the iOS app

**Comment by massa007** [comment] 2016-01-08 12:35
In my case it is very simple:
1: Take a picture with iPhone 6s in upright mode (I hope "upright" is the correct word - home button is at the bottom)
2: Upload picture with any app (in my case Crypto Cloud)
3: Picture is wrong rotated in any view

**Comment by MorrisJobke** [comment] 2016-01-08 13:20
@massa007 Can I ask you to provide those images to us for debugging purposes? That would be helpful :)

**Comment by massa007** [comment] 2016-01-08 15:14
Of course :)
Thank you already for your help guys!

![2016-01-08 13-30-12 0183](https://cloud.githubusercontent.com/assets/16576171/12201122/cc6c71a4-b622-11e5-9e92-6720d7dc6ae4.jpg)
![2016-01-08 13-30-16 0184](https://cloud.githubusercontent.com/assets/16576171/12201123/cc6eeb96-b622-11e5-99af-bd66f8e3fbf6.jpg)

**Comment by MorrisJobke** [comment] 2016-01-08 15:19
I tested following:

* upload those files
* share the two files individually to another user -> :white_check_mark: everything works
* create a folder, put those two files in there and then share the folder to another user -> :x: the preview is not rotated

**Comment by massa007** [comment] 2016-01-08 16:08
I fear in my case it is always wrong ^^

**Comment by oparoz** [comment] 2016-01-08 17:07
I suspect that people affected by the general issue don't have the EXIF extension installed... but @MorrisJobke's 2nd use case is probably a different issue :cry:

**Comment by oparoz** [comment] 2016-01-08 17:48
@massa007 Check if the extension is really installed since it seems to fail from the start for you.
For the other reporters, the extension has to have been installed since it works the first time a preview is loaded

**Comment by massa007** [comment] 2016-01-08 19:40
I checked with the phpinfo site. Can you tell me how to really check it?

**Comment by oparoz** [comment] 2016-01-08 20:12
Hmmm... The only proper way would be through a test script. I'm sure someone has written one which list the metadata.

**Comment by oparoz** [comment] 2016-01-11 13:24
This is actually a duplicate of https://github.com/owncloud/core/issues/20484, so closing this.

**Comment by massa007** [comment] 2016-01-15 10:30
I Inserted the php code in the corresponding php file with no change..
Do I need to do anything more?

**Comment by Rayn0r** [comment] 2016-01-27 22:07
I don't think that this issue is a duplicate of #20484. 
Issue #20484 is about re-shared images. 

All portrait images I ever uploaded via owncloud app from my Android phone are displayed in landscape mode.
The problem first occurred after upgrading from 8.1.4.2 to 8.2.1.4. It seems like the exif information is not taken into account when displaying the image.

**Comment by Rayn0r** [comment] 2016-01-27 22:45
I have to correct myself. Not all photos are affected.
I just stumbled upon an image that (at least here) does display correctly: 
![img_20150518_091909](https://cloud.githubusercontent.com/assets/4147858/12630664/ca745ad0-c54d-11e5-87d1-2040de8cda98.jpg)
While this one does not: 
![img_20160126_085118](https://cloud.githubusercontent.com/assets/4147858/12630665/ca7b0f06-c54d-11e5-99e5-45a5d1fed6bb.jpg)

When opened from the HDD in XnView or Firefox both images are displayed correctly.

**Comment by oparoz** [comment] 2016-01-27 23:12
I've just tested both of these images on master and they both get the proper orientation.

Don't forget that you have to clear the cache in order to get the new thumbnails generated.

**Comment by Rayn0r** [comment] 2016-01-28 08:19
I deleted all thumbnails for the particular user. OC then re-created them. Here are the two newly created files from the thumbnail folder for the second image:
![2000-1500-with-aspect png](https://cloud.githubusercontent.com/assets/4147858/12638774/11d4090a-c5a0-11e5-92a9-bff4aa33a782.jpg)
![2048-1536-max png](https://cloud.githubusercontent.com/assets/4147858/12638775/11d68cf2-c5a0-11e5-98ce-2be929d00a97.jpg)

**Comment by Rayn0r** [comment] 2016-01-28 12:28
I turned on debug for my OC installation and then again deleted all thumbnails.
The log now shows the following when accessing an image in the gallerie.
I extracted only the "message" part from each log entry:

> ,"message":"fopen(\/usr\/share\/owncloud-data\/andrew\/thumbnails\/73401\/2000-1500-with-aspect.png): failed to open stream: No such file or directory at \/usr\/share\/owncloud\/lib\/private\/files\/storage\/local.php#247"
> "message":"Generating preview for \"Photos\/IMG_20160126_085118.jpg\" with \"OC\\Preview\\JPEG\""
> "message":"OC_Image->fixOrientation() No readable file path set."
> "message":"OC_Image->fixOrientation() Orientation: -1"

Because of the missing "file path" the orientation is set to -1.
So where should "file path" point to and where does its value come from?

**Comment by oparoz** [comment] 2016-01-28 12:34
Iirc, there is already an issue opened about that problem. Try to look for it and if you find a match, close this one :)

**Comment by Rayn0r** [comment] 2016-01-28 13:09
I was not able to find an issue that seemed related to this problem... So I did some more digging.

I changed line 364 of /usr/share/owncloud/lib/private/image.php to:
` $this->logger->debug('OC_Image->fixOrientation() No readable file path set. FilePath: '.$this->filePath, array('app' => 'core'));`
The log now states:
> "message":"OC_Image->fixOrientation() No readable file path set. FilePath: \/tmp\/oc_tmp_NZwlxY-.jpg"

Is there something missing. Should the file name end with a dash?

**Comment by Rayn0r** [comment] 2016-01-28 14:44
There is one more odd thing... 
After adding some more logging I figured out that the function "cleanFiles" in lib/private/tempmanager.php only cleans a file called /tmp\/oc_tmp_NZwlxY but not /tmp\/oc_tmp_NZwlxY-jpg.
I was not yet able to identify the function which cleans up the temp jpg file? Can anyone help me out here?

**Comment by oparoz** [comment] 2016-01-28 15:47
It seems to be specific to your installation. Maybe PHP runs out of memory?
I've just tested on 8.2.2, without encryption and get the proper orientation.

**Comment by Rayn0r** [comment] 2016-01-28 15:56
I'm sorry, but there is one thing I missed to mention. Encryption is enabled here...

How would PHP running out of memory delete a file under /tmp prior to being access by fixOrientation?
The temporary jpg is contained in the array $files that is passed to the function cleanFiles in lib/private/tempmanager.php. The jpg file does however not exist anymore.

**Comment by oparoz** [comment] 2016-01-28 16:16
>How would PHP running out of memory delete a file under /tmp prior to being access by fixOrientation?
I was thinking that maybe the cleaning operation is kept separate.

>I'm sorry, but there is one thing I missed to mention. Encryption is enabled here...
And that's the reason it doesn't work...

@icewind1991, can this be fixed like shared storage was fixed?

**Comment by massa007** [comment] 2016-01-29 07:42
Rayn0r I´m glad that you have the same issue but know much better about the system in general... I´m not able to dig deeper in this, but please, if you find any solution, write it here!
FYI: Encryption is enabled here as well

**Comment by Rayn0r** [comment] 2016-02-01 11:15
Over the past couple of days I tried to find the cause this issue, but I ran out of ideas where to look in the source and what exactly to search for.
I am still confused by the fact, that the temp image used by fixOrientation() does not seem to be deleted by the cleanFiles() function.
It would be really great if someone with deeper insight could take a look at this.

**Comment by versatileng** [comment] 2016-02-04 07:52
I'm facing the same problem:
All images uploaded *before* I enabled encryption are (still) rotated properly.
All images uploaded/added *after* I enabled encryption are not rotated at all - rotation is also not done in thumbnails - I disabled all gallery-apps for testing, no rotation, nowhere.
If I download a not properly rotated image, EXIF information is still here, image is rotated correclty by viewers and browsers.
Since I'm using OC for picture gallaries only I would really appreciative any hint or help!

**Comment by snoopyf** [comment] 2016-03-31 08:30
Hi everybody,
stumbled across this issue as I noticed some similar behaviour... as described here:
https://github.com/owncloud/gallery/issues/637

In my case image rotation is corrupted when images are stored in external storages (CIFS/SMB for example). When the same imaghes are uploaded to a "local" folder, everything seems to be fine (for more details have a look at the linked issue)

**Comment by josh4trunks** [comment] 2016-03-31 09:11
I believe this issue started happening in version 8.2.0 though I might have been somewhere else between 8.0-8.2. I've been updated my owncloud, with encryption enabled, since 7.0.0 and started noticing it at one point but never posted a bug report.

With encryption enabled I am seeing the ignoring of EXIF rotation of images previews in the files app and the slideshow from the gallery app when you click on a JPG.

**Comment by josh4trunks** [comment] 2016-03-31 09:58
I believe I was able to fix this issue in my testing. Both thumbnails and gallery previews are now respecting exif data for my encrypted files. =]

In https://github.com/owncloud/core/blob/master/lib/private/preview/image.php I moved `$image->fixOrientation();` directly below `$image->loadFromFile($fileName);`
Can someone test this doesn't brake anything and if feel like it write a PR?

Now that thumbnail generate properly is there a proper way to delete my old thumbnails so owncloud generate all new ones? Should I just be clearing the thumbnail folders for all users?
`rm -r DATADIR/*/thumbnails/*
Thanks

**Comment by josh4trunks** [comment] 2016-03-31 10:03
@oparoz @cmonteroluque if the fix mentioned here https://github.com/owncloud/core/issues/21485#issuecomment-203859192 works could we backport into 9.0.X? It's a minor bug fix so I don't see an issue?
Thanks

**Comment by Rayn0r** [comment] 2016-03-31 10:10
So you changed it like this?
```
--- image.php.org       2016-03-31 12:09:28.431677652 +0200
+++ image.php   2016-03-31 12:09:42.071685741 +0200
@@ -53,10 +53,10 @@
                        $fileName = $fileview->getLocalFile($path);
                }
                $image->loadFromFile($fileName);
+               $image->fixOrientation();
                if ($useTempFile) {
                        unlink($fileName);
                }
-               $image->fixOrientation();
                if ($image->valid()) {
                        $image->scaleDownToFit($maxX, $maxY);

```

**Comment by josh4trunks** [comment] 2016-03-31 10:12
@Rayn0r exactly
Though I believe we need to clear our old thumbnails to get those to regenerate.

**Comment by Rayn0r** [comment] 2016-03-31 10:19
It looks like the behaviour was introduced by this commit [a281737](https://github.com/owncloud/core/commit/a2817372ad89b11ef382845540068b016286d046).

**Comment by oparoz** [comment] 2016-03-31 10:42
Good job @josh4trunks :). That would explain why every backend except local storage can't rotate images. It's a bit surprising since we load the temp file into a PHP resource before deleting it, so it shouldn't have any impact.

`scaleDownToFit` should be tested, because it could very well be that it's affected by the same problem and that the real fix is to unlink the file at the very end.

**Comment by josh4trunks** [comment] 2016-03-31 10:44
Thanks
Probably best to the unlinking last just in case.

**Comment by oparoz** [comment] 2016-03-31 10:48
>Now that thumbnail generate properly is there a proper way to delete my old thumbnails so owncloud generate all new ones? Should I just be clearing the thumbnail folders for all users?

@josh4trunks - There is one project to do exactly that: https://github.com/owncloud/gallery/issues/22 , but it stalled due to the lack of funding, so yes, you can just delete that thumbnails folder and generate them again while browsing.

**Comment by josh4trunks** [comment] 2016-03-31 10:51
Sounds good. Personally I'll wait to delete my thumbnail folders once this gets merged.

**Comment by snoopyf** [comment] 2016-03-31 11:08
Thanks a lot to josh4trunks for this:

> So you changed it like this?
>
>```
>--- image.php.org       2016-03-31 12:09:28.431677652 +0200
>+++ image.php   2016-03-31 12:09:42.071685741 +0200
>@@ -53,10 +53,10 @@
>                       $fileName = $fileview->getLocalFile($path);
>              }
>                $image->loadFromFile($fileName);
>+               $image->fixOrientation();
>               if ($useTempFile) {
>                        unlink($fileName);
>                }
>-               $image->fixOrientation();
>                if ($image->valid()) {
>                        $image->scaleDownToFit($maxX, $maxY);
>
>
>```

After changing this and a quick test everything seems to work as expected for me now...

**Comment by josh4trunks** [comment] 2016-04-01 23:13
@oparoz
do you mind submitting a PR for this fix? I'd be great if we could get it in 9.0.1 but maybe it's too late?

**Comment by oparoz** [comment] 2016-04-02 11:44
@josh4trunks - Probably too late as people still have to test the solution, but just create the PR online, move the unlink to the end. Then ping all the people who have confirmed it fixes things for them.
It might be worth checking if other preview providers aren't affected as well.

**Comment by josh4trunks** [comment] 2016-04-02 15:16
I don't other providers would be affected because nothing else uses exif. k when I have a chance I'll write up a PR

**Comment by josh4trunks** [comment] 2016-04-02 15:51
@oparoz do you know what branch I should work off so this gets backported to 9.0.X?

**Comment by oparoz** [comment] 2016-04-02 15:52
@josh4trunks Always use master and ask for the backport in the PR.

**Comment by josh4trunks** [comment] 2016-04-02 15:53
@oparoz Great, thanks!

**Comment by cmonteroluque** [comment] 2016-04-05 09:55
Coyping @karlitschek for backport

**Comment by karlitschek** [comment] 2016-04-05 12:22
nice fix. please backport :+1:

**Closed** 2016-04-11 12:04 UTC
Labels: bug, feature:previews, in progress, regression, sev4-low
