### ISSUE TITLE
[6.0.3] Folders not shown after rename

### ISSUE THREAD

**Issue by psde** [owncloud/core#9141] opened 2014-06-22 11:26 UTC
After renaming a folder with about 3000 files inside, the mirall client reported a few folders/files as deleted. I opened a bug report (https://github.com/owncloud/mirall/issues/1883) but it seems the fault is in the core server after all.

Here is what I did:
I moved the folder `.pidgin` into the folder `Stuff` with mirall:
```
18:32:20|0|Stuff/.pidgin/status.xml|INST_RENAME|Up|1343482866|539dc616acbe0|0|00062207oc5fc53bdb1d|4||0|219|1343482866|||INST_NONE|
18:32:19|0|Stuff/.pidgin/smileys|INST_RENAME|Up|1402848786|539dc61259761|0|00062204oc5fc53bdb1d|4||0|0|1343482862|||INST_NONE|
18:32:19|0|Stuff/.pidgin/prefs.xml|INST_RENAME|Up|1343482882|539dc615459d7|0|00062205oc5fc53bdb1d|4||0|17822|1343482882|||INST_NONE|
18:32:18|0|Stuff/.pidgin/certificates/x509/tls_peers|INST_RENAME|Up|1402848785|539dc61162d82|0|00062203oc5fc53bdb1d|4||0|0|1343482860|||INST_NONE|
18:32:18|0|Stuff/.pidgin/certificates/x509|INST_RENAME|Up|1402848785|539dc611c0c56|0|00062202oc5fc53bdb1d|4||0|0|1402842658|||INST_NONE|
```
After the move was completed, a few files and folders were deleted. Also, a new mirall logfile was created:
```
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started 2014-06-17T22:00:22 until 2014-06-17T22:01:26 (63326 msec)
|0|Stuff/.pidgin/certificates/x509|INST_REMOVE|Down|1402842658|539dc611c0c56|0||0||0|0|0|||INST_NONE|
|0|Stuff/.pidgin/certificates|INST_REMOVE|Down|1402842658|539dc611ccccf|0||4||0|0|0|||INST_NONE|
|0|Stuff/.pidgin/certificates/x509/tls_peers|INST_REMOVE|Down|1343482860|539dc61162d82|0||0||0|0|0|||INST_NONE|
|0|Stuff/.pidgin/smileys|INST_REMOVE|Down|1343482862|539dc61259761|0||4||0|0|0|||INST_NONE|
```

The `dir` column saying `Down` indicates this is deleted from the server, but there are no logs on the server indicating what could be wrong. Also, these files do not show up under the "Deleted Files" section.

The Apache2 access log does only show some of the files:
```
[17/Jun/2014:18:32:43 +0000] "PROPPATCH /remote.php/webdav/Stuff/.pidgin/prefs.xml HTTP/1.0" 207 1378 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"
[17/Jun/2014:18:32:44 +0000] "HEAD /remote.php/webdav/Stuff/.pidgin/prefs.xml HTTP/1.0" 200 142 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"
[17/Jun/2014:18:32:45 +0000] "PROPPATCH /remote.php/webdav/Stuff/.pidgin/status.xml HTTP/1.0" 207 1379 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"
[17/Jun/2014:18:32:46 +0000] "HEAD /remote.php/webdav/Stuff/.pidgin/status.xml HTTP/1.0" 200 142 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"
```

But here is an `ls` in the directory, showing the folders:
```
/owncloud/data/psde/files/Stuff/.pidgin # ls -lha
total 40K
drwxr-xr-x  4 http http 4.0K 15. Jun 18:13 .
drwxr-xr-x 11 http http 4.0K 16. Jun 01:47 ..
drwxr-xr-x  3 http http 4.0K 15. Jun 18:13 certificates
-rw-r--r--  1 http http  18K 28. Jul 2012  prefs.xml
drwxr-xr-x  2 http http 4.0K 15. Jun 18:13 smileys
-rw-r--r--  1 http http  219 28. Jul 2012  status.xml
```
These folders are not shown in the OwnCloud web interface. It seems like the folders got moved, but indirectly, as I can't find them in the Apache2 log.

The server is running OwnCloud 6.0.3 (stable) on Ubuntu 14.04 LTS.
I am using Mirall 1.6.0 on Windows 7 x64 with an Administrator account.

**Comment by PVince81** [comment] 2015-03-06 18:31
Very likely to be a duplicate of https://github.com/owncloud/core/issues/13391

**Closed by PVince81** 2015-03-06 18:31 UTC
Labels: bug
