### ISSUE TITLE
SMB access is broken with Samba 3.6.25

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24314] opened 2016-04-27 16:52 UTC
### Steps to reproduce
1. Running ownCloud 9.0.2 RC1 (daily)
2. Having SMB mounts sucessfully mounted and in use
3. Update via webupdater (daily)

### Expected behaviour
SMB mounts are present and accessible (as before)

### Actual behaviour
SMB mounts are after the update present but no longer accessible nor creatable

Note I: the owncloud error as shown below is always thrown when I either try to change eg the pwd on the smb mount point or create a new smb mount point.

Note II: the file logged in the owncloud log (always a different one) resides on a federated share

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
nginx

**Database:**
mysql

**PHP version:** 
5.5.9

**ownCloud version:** (see ownCloud admin page)
9.0.2 RC1 (daily)

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
no file found
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oci1ewzyz3i0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 0,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Opera

**Operating system:**
W7x64

#### Web server error log
```
no corresponding error log entries
```

#### ownCloud log (data/owncloud.log)
```
Error while running background job (class: OC\Command\CommandJob, arguments: O:33:"OCA\Files_Versions\Command\Expire":2:{s:43:"OCA\Files_Versions\Command\ExpirefileName";s:70:"/yyyyyyy";s:39:"OCA\Files_Versions\Command\Expireuser";s:8:"xxxx";}): {"Exception":"OC\\User\\NoUserException","Message":"Attempted to initialize mount points for null user and no user in session","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(102): OC\\Files\\Filesystem::initMountPoints(false)\
n#1 \/var\/www\/owncloud\/apps\/files_versions\/lib\/storage.php(682): OCA\\Files_Versions\\Storage::getUidAndFilename('\/Innovation Eng...')\
n#2 \/var\/www\/owncloud\/apps\/files_versions\/command\/expire.php(61): OCA\\Files_Versions\\Storage::expire('\/Innovation Eng...')\
n#3 \/var\/www\/owncloud\/lib\/private\/command\/commandjob.php(34): OCA\\Files_Versions\\Command\\Expire->handle()\
n#4 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OC\\Command\\CommandJob->run('O:33:\"OCA\\Files...')\
n#5 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/queuedjob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
n#6 \/var\/www\/owncloud\/cron.php(171): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
n#7 {main}","File":"\/var\/www\/owncloud\/lib\/private\/files\/filesystem.php","Line":376}
```

**Comment by LukasReschke** [comment] 2016-04-27 19:04
@Xenopathic @icewind1991

**Comment by PVince81** [comment] 2016-04-28 08:31
That message is caused by https://github.com/owncloud/core/pull/24186 but should not in any way affect SMB, this is cron. So unrelated.

Let's try SMB locally

**Comment by mmattel** [comment] 2016-04-28 09:19
> That message is caused by #24186 

OK, but interresting that it is always triggered when changing smb settings or creating smb mounts
>Let's try SMB locally

What exactly do you mean? My existing smb mounts are down (inaccessible), and new one can not be created. They are signalling no access (red square in admin, pink bar in file app)... And beside the cron message, no other messages are logged?

**Comment by PVince81** [comment] 2016-04-28 09:24
I just meant that I intended to do a test on my local system with SMB to confirm the regression.

**Comment by davitol** [comment] 2016-04-28 11:15
I've just tested twice and everything went fine. Cannot reproduce this isssue 😢

**Comment by mmattel** [comment] 2016-04-28 11:42
bad, I have system with a broken smb access which worked before the upgrade... :cry:

**Comment by icewind1991** [comment] 2016-04-28 11:43
@mmattel if you know how, you can try doing a git bisect to find the commit that introduced the regression

**Comment by mmattel** [comment] 2016-04-28 11:46
This system was setup via tar and then updated via the web updater (daily).
Last update about a week ago.

**Comment by PVince81** [comment] 2016-04-28 12:03
@mmattel can you maybe give more detail about that specific SMB mount or is it all mounts ?

**Comment by PVince81** [comment] 2016-04-28 12:04
also can you clarify "no longer accessible nor creatable" ?

Are you able to navigate and see their contents in the web UI ? How about Webdav ?

**Comment by PVince81** [comment] 2016-04-28 12:04
as long as we can't reproduce this it will be close to impossible to help

**Comment by mmattel** [comment] 2016-04-28 12:11
No longer accessible means, that the SMB mount was present before the update and accessible (including all contents), both via the web and webdav. After the update the mount is present, you can see it in the files app and in the admin page, but both report an error (inaccessible). Webdav reports "The remote server returned an error: (503) Server Unavailable." While local folders are accessible.

**Comment by PVince81** [comment] 2016-04-28 12:16
Okay, interesting.

Can you check the `oc_storages` table and do `update oc_storages set available=1, last_checked=NULL;`

Then try and access them again and see what exception they produce in the log.

There is a system in place that whenever certain errors occur, it will mark the storage as unavailable for 10 minutes or so and will just return 503 without retrying, which might hide the real reason/exception. The SQL query above will reset the flag and make it retry directly.

**Comment by mmattel** [comment] 2016-04-28 12:56
Did that, tried to access with the files app.
````
Externer Einhängefehler

There was an error with message: Leere Antwort vom Server erhalten. Do you want to review mount point config in admin settings page?
````
The database shows on the SMB share now a non NULL value for ``last_checked``
BTW the German translation "Einhängefehler" has room for improvement...

owncloud.log:
````
Debug	OC\Files\Cache\Scanner	!!! Path '' is not accessible or present !!!	
````

**Comment by mmattel** [comment] 2016-04-28 18:48
You will not believe what I found. But the good news first.

The issue is solved, it has nothing to do with the code.
I have a another VM, same OS but which I did not updated recently...
I checked on this machine if the issue is the same but it worked.

My finding was the following, there was an update of the samba client package which caused the problem. Because I am running a non Windows fileserver (NetApp running a Ontap 7.x release) I was affected by this upgrade. (The hint was here: http://community.netapp.com/t5/Network-Storage-Protocols-Discussions/samba-3-6-23-30-on-CentOS-gt-error-in-smbclient/td-p/118268 and here: **smbclient to non-windows server broken since BADLOCK fixes** https://bugzilla.redhat.com/show_bug.cgi?id=1327216)

I had to revert the smbclient to the former working release. By doing so, it worked again :smile:

Here are in a nutshell the tasks I did.

````
dpkg -s smbclient
Version: 2:4.3.8+dfsg-0ubuntu0.14.04.2

sudo apt-cache showpkg smbclient
2:4.3.8+dfsg-0ubuntu0.14.04.2 - samba-client
2:4.1.6+dfsg-1ubuntu2.14.04.13 - samba-client

sudo apt-get remove samba-common
sudo apt-get remove samba-libs
sudo apt-get remove smbclient
sudo apt-get autoremove

sudo apt-get install samba-common=2:4.1.6+dfsg-1ubuntu2
sudo apt-get install samba-libs=2:4.1.6+dfsg-1ubuntu2
sudo apt-get install libldb1=1:1.1.16-1
sudo apt-get install smbclient=2:4.1.6+dfsg-1ubuntu2
sudo apt-get install libsmbclient=2:4.1.6+dfsg-1ubuntu2

sudo apt-mark hold samba-common
sudo apt-mark hold samba-libs
sudo apt-mark hold smbclient
sudo apt-mark hold libsmbclient
````

**Comment by mmattel** [comment] 2016-04-28 18:56
Maybe to mention: https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1572122

Seems that there are more things affected by this samba upgrade which possibly could cause LDAP problems.

Therefore adding @blizzz FYI

**Comment by PVince81** [comment] 2016-04-29 14:33
Closing since this is a SMB bug.

I added the version in the ticket title to be able to find it again.

**Closed by PVince81** 2016-04-29 14:33 UTC
Labels: app:files_external, bug, needs info

**Comment by mmattel** [comment] 2016-05-11 11:26
**UPDATE:**
According to: https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1572122
a fix has been released and is available via standard update.

The packages mentioned above beeing marked hold can now be unhold and updated.

I have tested this and access to smb shares is now possible again.
