### ISSUE TITLE
Critical: Server crash and database gets corrupt on windows after recreating a directory with other case spelling

### ISSUE THREAD

**Issue by BastiCambeo** [owncloud/core#12861] opened 2014-12-15 16:31 UTC
System: Apache 2.5.10, ownCloud Server 7.0.4, MySQL 5.7, Windows 8.1 (Both Server and Client)

In my current database state apache immediately gets into an endless loop of creating ghost folders... 
Even after restarting apache and clearing all apparent occurences of the ghost folder database entries in the behaviour persists at restart...

Steps to reproduce:
- Use fresh owncloud environment with only admin account and no files synced yet
- Delete an existing folder (e.g. "documents") and sync
- Recreate a folder with same name but other case spelling (e.g. "Documents")
- Start syncing a local folder (e.g. C:\users\\...\Documents) with the owncloud folder via the client
- Receive a corrupt database with apache endless looping at every start...Even without client interaction. Even if all apparent database ghost entries have been deleted manually... (there must be some hidden logic that I don't find)

![neue bitmap](https://cloud.githubusercontent.com/assets/2535762/5439295/f9adef02-847e-11e4-9b7d-d4a15657dada.jpg)

**Comment by nickvergessen** [comment] 2015-02-19 17:20
Duplicate of #6553

**Closed by nickvergessen** 2015-02-19 17:20 UTC
Labels: bug, windows server
