### ISSUE TITLE
Upgrade to v8.0.0 failed

### ISSUE THREAD

**Issue by Hajo1961** [owncloud/core#14303] opened 2015-02-17 16:37 UTC
Could not automatically fix legacy storage "local::/var/www/owncloud/data/xxxx/" => "home::xxxx" because they both have data.

These User is an ad user and was deleted! There are no data, only the cache directory are present. I delete the complete directory of this user, but the upgrade fail again.

**Comment by LukasReschke** [comment] 2015-02-17 16:40
@PVince81

**Comment by PVince81** [comment] 2015-02-17 16:42
@Hajo1961 if that's an old user, you said you deleted the directory on disk. Can you also remove the matching entries in the `oc_storages` table and try again ?

Closing as duplicate of https://github.com/owncloud/core/issues/13980

**Closed by PVince81** 2015-02-17 16:42 UTC
