### ISSUE TITLE
Issue with mappedlocal.php version 8.0.0 running on Windows 2012 with IIS

### ISSUE THREAD

**Issue by jay905** [owncloud/core#14237] opened 2015-02-15 19:57 UTC
Hi, let me first preface my issue post with a comment that i'm not a developer so my knowledge of code is very limited.  Also forgive me if I don't post my issue in the correct format, I was encouraged to post my finding/suggested fix from the ownCloud forum.

I installed a fresh copy of ownCloud 8.0.0 running on a Windows 2012 R2 server running IIS, with PHP 5.6, pretty much following the install guide.  I configured it, and proceeded to upload some files using the desktop sync program but ran into some issues.  Upon looking at all the logs, seeing the errors and researching Google I found a few others with the same problem.  One person suggested copying mappedlocal.php from 7.0.4 into the 8.0.0 code which worked, but I wanted to dig into this further and try and figure out which pieces of code were causing the problem.  

So, first here's the issue.  When adding files to the server I always had errors like this below:

{"reqId":"f92131f5a5cc2b4291204c008068d76f","remoteAddr":"70.31.x.x","app":"PHP","message":"unlink(E:\\inetpub\\wwwroot\\owncloud\\data\/jason\/files\/documents\/daycare\/2008-daycare.xlsx): Permission denied at E:\\inetpub\\wwwroot\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-14T03:05:39+00:00"}
{"reqId":"f92131f5a5cc2b4291204c008068d76f","remoteAddr":"70.31.x.x","app":"PHP","message":"scandir(E:\\inetpub\\wwwroot\\owncloud\\data\/jason\/files\/documents\/daycare\/2008-daycare.xlsx,E:\\inetpub\\wwwroot\\owncloud\\data\/jason\/files\/documents\/daycare\/2008-daycare.xlsx): The directory name is invalid. (code: 267) at E:\\inetpub\\wwwroot\\owncloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-14T03:05:39+00:00"}

What looked odd was all the slashes in both directions.  I've seen double "\\" before with certain code in a Windows environment.

After looking at the difference between the 7.0.4 code and the 8.0.0 code, and doing some experimentation I found that modifying the following code fixed this issue.

First replace the following lines of code:
-----------------------------------------------------------------------------
protected function getSourcePath($path) {
$path = $this->stripLeading($path);
$fullPath = $this->datadir . $path;
return $this->mapper->logicToPhysical($fullPath, true);
}

/**
* {@inheritdoc}
*/
public function isLocal() {
return true;
}

/**
* @param string $path
* @return string
*/
private function dirName($path) {
$path = dirname($path);
if ($path === '.') {
return '';
} else {
return $path;
}
}
-----------------------------------------------------------------------------

WITH THIS BELOW:
-----------------------------------------------------------------------------
private function getSourcePath($path, $create = true) {
$path = $this->stripLeading($path);
$fullPath = $this->datadir . $path;
return $this->mapper->logicToPhysical($fullPath, $create);
}
-----------------------------------------------------------------------------

and, replace this:
-----------------------------------------------------------------------------
public function rename($path1, $path2) {
$srcParent = $this->dirname($path1);
$dstParent = $this->dirname($path2);

if (!$this->isUpdatable($srcParent)) {
\OC_Log::write('core', 'unable to rename, source directory is not writable : ' . $srcParent, \OC_Log::ERROR);
return false;
}

if (!$this->isUpdatable($dstParent)) {
\OC_Log::write('core', 'unable to rename, destination directory is not writable : ' . $dstParent, \OC_Log::ERROR);
return false;
}
-----------------------------------------------------------------------------

WITH THIS BELOW:
-----------------------------------------------------------------------------
public function rename($path1, $path2) {
if (!$this->isUpdatable($path1)) {
\OC_Log::write('core', 'unable to rename, file is not writable : ' . $path1, \OC_Log::ERROR);
return false;
}
-----------------------------------------------------------------------------

I hope someone can look into why the code in 8.0.0 broke under Windows Server and can add some fixes to the next release for others.

Thanks,
Jason

**Comment by BrentNewland** [comment] 2015-02-16 20:41
I've got the same problem. Windows Server 2008 R2. Owncloud 7 to Owncloud 8 upgrade. Get the following errors in my logs:

{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): failed to open dir: No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 2): No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"rename(C:\\cloud\\data\/BrentNewland\/files\/beta\/readme.md,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): The process cannot access the file because it is being used by another process. (code: 32) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#218","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"Undefined index: \/C:\/cloud\/data\/BrentNewland\/files\/beta\/readme.md at C:\\Server\\www\\cloud\\apps\\files_locking\\lib\\lockingwrapper.php#140","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): failed to open dir: Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 13): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/readme.md.d1424115388): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"d5cb29ef7b6ab278d2f6c621eec9ed08","remoteAddr":"192.168.10.1","app":"webdav","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Tree.php(102): OC_Connector_Sabre_File->delete()\\n#1 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(691): Sabre\\\\DAV\\\\Tree->delete('beta\\\/README.md')\\n#2 [internal function]: Sabre\\\\DAV\\\\Server->httpDelete('beta\\\/README.md')\\n#3 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(474): call_user_func(Array, 'beta\\\/README.md')\\n#4 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('DELETE', 'beta\\\/README.md')\\n#5 C:\\\\Server\\\\www\\\\cloud\\\\apps\\\\files\\\\appinfo\\\\remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#6 C:\\\\Server\\\\www\\\\cloud\\\\remote.php(54): require_once('C:\\\\\\\\Server\\\\\\\\www\\\\\\\\c...')\\n#7 {main}\",\"File\":\"C:\\\\Server\\\\www\\\\cloud\\\\lib\\\\private\\\\connector\\\\sabre\\\\file.php\",\"Line\":202}","level":4,"time":"2015-02-16T19:36:28+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): failed to open dir: No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 2): No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"rename(C:\\cloud\\data\/BrentNewland\/files\/beta\/changelog.md,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): The process cannot access the file because it is being used by another process. (code: 32) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#218","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"Undefined index: \/C:\/cloud\/data\/BrentNewland\/files\/beta\/changelog.md at C:\\Server\\www\\cloud\\apps\\files_locking\\lib\\lockingwrapper.php#140","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): failed to open dir: Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 13): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/changelog.md.d1424115389): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"3ec247a04a5e2db783da37be75da91f0","remoteAddr":"192.168.10.1","app":"webdav","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Tree.php(102): OC_Connector_Sabre_File->delete()\\n#1 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(691): Sabre\\\\DAV\\\\Tree->delete('beta\\\/changelog....')\\n#2 [internal function]: Sabre\\\\DAV\\\\Server->httpDelete('beta\\\/changelog....')\\n#3 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(474): call_user_func(Array, 'beta\\\/changelog....')\\n#4 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('DELETE', 'beta\\\/changelog....')\\n#5 C:\\\\Server\\\\www\\\\cloud\\\\apps\\\\files\\\\appinfo\\\\remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#6 C:\\\\Server\\\\www\\\\cloud\\\\remote.php(54): require_once('C:\\\\\\\\Server\\\\\\\\www\\\\\\\\c...')\\n#7 {main}\",\"File\":\"C:\\\\Server\\\\www\\\\cloud\\\\lib\\\\private\\\\connector\\\\sabre\\\\file.php\",\"Line\":202}","level":4,"time":"2015-02-16T19:36:29+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): failed to open dir: No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 2): No such file or directory at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"rename(C:\\cloud\\data\/BrentNewland\/files\/beta\/serve,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): The process cannot access the file because it is being used by another process. (code: 32) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#218","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"Undefined index: \/C:\/cloud\/data\/BrentNewland\/files\/beta\/serve at C:\\Server\\www\\cloud\\apps\\files_locking\\lib\\lockingwrapper.php#140","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"unlink(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#270","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390,C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): The directory name is invalid. (code: 267) at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): failed to open dir: Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"scandir(): (errno 13): Permission denied at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"Invalid argument supplied for foreach() at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#275","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"PHP","message":"rmdir(C:\\cloud\\data\/BrentNewland\/files-trashbin\/files\/serve.d1424115390): Invalid argument at C:\\Server\\www\\cloud\\lib\\private\\files\\storage\\mappedlocal.php#289","level":3,"time":"2015-02-16T19:36:30+00:00"}
{"reqId":"4bed27d0b17f0692eec2c1ba77575fba","remoteAddr":"192.168.10.1","app":"webdav","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Tree.php(102): OC_Connector_Sabre_File->delete()\\n#1 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(691): Sabre\\\\DAV\\\\Tree->delete('beta\\\/serve')\\n#2 [internal function]: Sabre\\\\DAV\\\\Server->httpDelete('beta\\\/serve')\\n#3 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(474): call_user_func(Array, 'beta\\\/serve')\\n#4 C:\\\\Server\\\\www\\\\cloud\\\\3rdparty\\\\sabre\\\\dav\\\\lib\\\\Sabre\\\\DAV\\\\Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('DELETE', 'beta\\\/serve')\\n#5 C:\\\\Server\\\\www\\\\cloud\\\\apps\\\\files\\\\appinfo\\\\remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#6 C:\\\\Server\\\\www\\\\cloud\\\\remote.php(54): require_once('C:\\\\\\\\Server\\\\\\\\www\\\\\\\\c...')\\n#7 {main}\",\"File\":\"C:\\\\Server\\\\www\\\\cloud\\\\lib\\\\private\\\\connector\\\\sabre\\\\file.php\",\"Line\":202}","level":4,"time":"2015-02-16T19:36:30+00:00"}



Owncloud has been basically unusable until replacing the mappedlocal.php. Had to run the following command after:

c:\server\php\php.exe -c c:\server\php\php-cloud.ini c:\server\www\cloud\occ files:scan --all

And I was still left with a ton of *_conflict_date_* files that I have to sort through manually. This is a critical bug, and has ruined a ton of stuff I had Owncloud connected to.

**Comment by BrentNewland** [comment] 2015-02-16 20:42
Forgot to mention I also had to delete every .csync_journal.db because it was giving me 403 forbidden messages (item not synced because of previous errors) which were not valid.

**Comment by PVince81** [comment] 2015-02-17 10:09
@nickvergessen

**Comment by carvan** [comment] 2015-03-09 17:22
By replacing that file with the previous version it worked like a charm! I was struggling and messing up with folder permissions for a week and then I fixed it in 10 seconds thanks to your suggestion!!! So was it marked as a bug?

**Comment by nickvergessen** [comment] 2015-03-09 17:55
Duplicate of #14513

See https://forum.owncloud.org/viewtopic.php?f=31&t=26421&p=80666#p80666 or https://github.com/owncloud/core/issues/14513#issuecomment-76173623
Disable the files locking app to solve the issue

**Closed by nickvergessen** 2015-03-09 17:55 UTC
Labels: bug, windows server

**Comment by BrentNewland** [comment] 2015-03-09 22:59
I fail to see how issue 14237 is a duplicate of 14513 - numbers tell me that 14513 came after this one. So 14513 would be the duplicate.

Perhaps next time you should say something like "We're keeping work on this issue on #14513".

**Comment by nickvergessen** [comment] 2015-03-10 07:42
The issue I linked to is already spread in the forum and via twitter, so it makes sense to keep that one up to date. Sorry that we didn't identify your problem being the same one in first place. Also note, the "duplicate" sentence is no offense and just provides context for the ticket id afterwards.
