### ISSUE TITLE
Group calendars can't be edited by group members

### ISSUE THREAD

**Issue by schmees** [owncloud/core#23011] opened 2016-03-09 11:05 UTC
A calendar that is shared with a group (group is allowed to edit) cannot be edited by the group members. They can only see the already entered dates. To make a calendar editable by group members, it has to be shared with each one of them individually.

 
### Steps to reproduce
1. Create a group with some users.
2. Create a calendar.
3. Share this calendar with the group and make it group editable.

### Expected behaviour
The group members should see the shared calendar and be able to insert new dates or change already entered ones.

### Actual behaviour
The calendar is shared, but read-only.

### Server configuration
**Operating system**: Debian 3.16.0-4-amd64

**Web server:** Apache 2.4.10

**Database:** MySQL 5.5.47

**PHP version:** 5.6.27

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** update from 8.2

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0

Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by LukasReschke** [comment] 2016-03-09 11:06
cc @DeepDiver1975

**Comment by RealRancor** [comment] 2016-03-09 11:24
Probably a dup of https://github.com/owncloud/core/issues/22932

**Comment by aspdye** [comment] 2016-03-09 11:26
No. I don't think so. #22932 is about migration of shares from versions before 9.0 and this issue is with new created calendars in ownCloud :wink:

**Comment by schmees** [comment] 2016-03-09 11:27
It is true that the group shares (as mentioned in #22932) weren't migrated correctly. But I did adapt them and afterwards the problem still existed.

**Comment by RealRancor** [comment] 2016-03-09 11:27
@aspdye Its the same issue if you have a look at https://github.com/owncloud/core/issues/22932#issuecomment-193702793

**Comment by DeepDiver1975** [comment] 2016-03-09 12:20
I'll have a look at this - THX for reporting

**Comment by DeepDiver1975** [comment] 2016-03-10 11:58
@schmees any chance to test this patch? THX 

https://github.com/owncloud/core/pull/22949

**Comment by schmees** [comment] 2016-03-14 07:23
@DeepDiver1975 As far as I can see, your patch influences the migration process. But if you install a fresh instance of ownCloud (without any previous migration) and proceed as described, the problem still exists. I don't have a test system running where I could apply your patch to, there is just our main instance running that is currently used by a lot of people. However, the workaround by sharing the important calendar with each group member individually works, but should be only a temporary solution.

**Comment by DeepDiver1975** [comment] 2016-03-14 10:50
@schmees I honestly cannot reproduce this.

I just shared a calendar with edit rights to a group. After logging in with one of the group members the shared calendar pops up in the calendar app and events can be added and edited.

Let me try this with plain oc9 ....

**Comment by DeepDiver1975** [comment] 2016-03-14 11:01
Okay ... this is reproducible in plain 9.0.0

**Comment by DeepDiver1975** [comment] 2016-03-14 11:19
Restarting ....

**Comment by DeepDiver1975** [comment] 2016-03-14 11:29
The write acl is properly setup - the group has write permissions. I suspect the calendar app has issues in processing the acl

@georgehrke can you please double check? THX

**Comment by DeepDiver1975** [comment] 2016-03-14 11:30
@schmees are you experiencing these issues with anyother caldav client as well or only with our web app?

**Comment by georgehrke** [comment] 2016-03-14 12:10
Most certainly related to this line: https://github.com/owncloud/calendar/blob/de9ff0f36b36e606beef3e40e6220e9cc6eaee4c/js/app/service/calendarservice.js#L399

Is there something like a group-principal we could query?

**Comment by DeepDiver1975** [comment] 2016-03-22 11:04
there is no group concept in caldav/carddav - we need to explicitly add the current principal to the acl

**Comment by DeepDiver1975** [comment] 2016-03-23 10:39
fix is in #23318

**Comment by MorrisJobke** [comment] 2016-03-31 09:16
This is fixed via https://github.com/owncloud/core/pull/23342

**Closed by MorrisJobke** 2016-03-31 09:16 UTC
Labels: 3 - To Review, 9.0.1-current, app:dav, bug, in progress, sev2-high
