### ISSUE TITLE
Can't create or upload a new file or folder when parent directory contains chinese characters

### ISSUE THREAD

**Issue by DruidCode** [owncloud/core#3499] opened 2013-05-26 09:40 UTC
### Actual behaviour
just can't create a new file or folder when parent directory contains chinese characters

### Steps to reproduce
1. create a new folder contains chinese characters.example: 中文 . At the moment there is a new folder names 51a1ce6e6293f
2. but when you try to create or upload anything in the second-level directory, it is failed
3. In the table oc_file_map, the physic_path is 'G:\soft\data/admin/files/51a1d4997291f/51a1d49972933'
4. but the true path should be 'G:\soft\data/admin/files/51a1ce6e6293f'...
4. it seems the path is wrong.  

### Server configuration
Operating system:  windows server 2003 service pack 1

Web server:  apache 2.2.22  mod_fcgid 2.3.6

Database: mysql 5.1.57

PHP version: php 5.3.5

ownCloud version: 5.0.6

### Client configuration
Browser: Firefox

Operating system: windows 7

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"filemtime(): stat failed for G:\\soft\\data\/admin\/files\/51a1d4997291f\/51a1d49972933 at G:\\soft\\www\\owncloud\\lib\\files\\storage\\mappedlocal.php#113","level":2,"time":1369560290}
{"app":"hook","message":"error while running hook (\\OC\\Files\\Cache\\Updater::writeHook): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'mtime' at row 1","level":3,"time":1369560290}

#### Browser log
{"data":{"message":"Error when creating the folder"},"status":"error"}

**Comment by nickvergessen** [comment] 2015-02-19 15:08
Fixed in oC 8.0 with #10619
Issue is duplicate of #6722

**Closed by nickvergessen** 2015-02-19 15:08 UTC
Labels: bug, windows server

**Comment by woeoio** [comment] 2017-02-16 02:41
你好，请问你的中文问题解决了吗

**Comment by woeoio** [comment] 2017-02-16 03:39
@ @ @ @DruidCode 请问问题解决了吗

**Comment by DruidCode** [comment] 2017-02-17 02:21
@woeoio  3年前的了。。。忘记了。
