### ISSUE TITLE
xml file is converted do txt downloading in chrome

### ISSUE THREAD

**Issue by mafigo** [owncloud/core#23176] opened 2016-03-12 11:40 UTC
### Steps to reproduce
1. upload xml file to owncloud
2. download file with chrome (works fine in firefox, ie and edge), choose download from the pop-up menu, it works ok if the download link from selected file check box is used. 
3. 

### Expected behaviour
the file extension of the downloaded file should be xml

### Actual behaviour
the file is converted to txt

### Server configuration
centos 7
**Web server:**
nginx
**Database:**
mariadb 10.1
**PHP version:**
5.6.18
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated from 8.2.2
**Where did you install ownCloud from:**
tar
**Signing status (ownCloud 9.0 and above):**

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome
**Operating system:**
windows 10

**Comment by LukasReschke** [comment] 2016-03-12 21:20
We should probably add the filename to the Content-Disposition header.
 
![2016-03-12_22-19-40](https://cloud.githubusercontent.com/assets/878997/13725395/872f0740-e8a0-11e5-84fb-d5b5348954fb.png)

**Comment by PVince81** [comment] 2016-03-14 11:33
Strange, but the extension is in the file name already.

**Comment by PVince81** [comment] 2016-03-14 11:34
Okay, it looks like the "downloadSecret" part is disturbing chrome.

This is likely a regression from when moving to Webdav for downloads, Webdav has its own "Content-Disposition" logic.

**Comment by PVince81** [comment] 2016-06-09 09:34
PR here https://github.com/owncloud/core/pull/25043

**Closed** 2016-06-10 07:56 UTC
Labels: app:dav, bug, regression, sev2-high
