### ISSUE TITLE
Deadlock found when trying to get lock

### ISSUE THREAD

**Issue by xrm** [owncloud/core#17060] opened 2015-06-21 11:17 UTC
### Steps to reproduce
Not sure. Just tried to browse my external smb storage (which was first very slow and then didn't respond at all).

### Expected behaviour
Being able to browse my smb storage without errors

### Actual behaviour
Errors as stated below and either slow or no response from the smb storage (just stayed at the top level folder)

### Server configuration
**Operating system**:
Debian 8.1

**Web server:**
Apache
2.4.10

**Database:**
MySQL 5.5.43

**PHP version:**
5.6.9

**ownCloud version:** (see ownCloud admin page)
8.0.4.2

**Updated from an older ownCloud or fresh install:**
Updated from 8.0.2 (not too sure on the .2, though)

**List of activated apps:**
Activity
Deleted Files
External storage support
External user support
File Locking
First Run Wizard
LDAP user and group backend
Share Files
Text Editor

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '__',
  'passwordsalt' => '__',
  'secret' => '__',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '__',
    2 => 'owncloud',
    3 => 'oc.__',
    4 => 'owncloud.__',
    5 => 'owncloud.__',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost:889/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'cloud',
  'dbhost' => '127.0.0.1',
  'dbuser' => '__',
  'dbpassword' => '__',
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 0,
  'theme' => '',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

```
mysql> select * from oc_appconfig where appid='user_ldap';
+-----------+-----------------------------------+---------------------------------------------+
| appid     | configkey                         | configvalue                                 |
+-----------+-----------------------------------+---------------------------------------------+
| user_ldap | cleanUpJobOffset                  | 500                                         |
| user_ldap | enabled                           | yes                                         |
| user_ldap | has_memberof_filter_support       | 0                                           |
| user_ldap | home_folder_naming_rule           |                                             |
| user_ldap | installed_version                 | 0.5.0                                       |
| user_ldap | last_jpegPhoto_lookup             | 0                                           |
| user_ldap | ldap_agent_password               | __                                          |
| user_ldap | ldap_attributes_for_group_search  |                                             |
| user_ldap | ldap_attributes_for_user_search   |                                             |
| user_ldap | ldap_backup_host                  |                                             |
| user_ldap | ldap_backup_port                  |                                             |
| user_ldap | ldap_base                         | dc=__                                       |
| user_ldap | ldap_base_groups                  | dc=__                                       |
| user_ldap | ldap_base_users                   | dc=_-                                       |
| user_ldap | ldap_cache_ttl                    | 600                                         |
| user_ldap | ldap_configuration_active         | 1                                           |
| user_ldap | ldap_display_name                 | displayname                                 |
| user_ldap | ldap_dn                           | cn=ldap-admin,__                            |
| user_ldap | ldap_email_attr                   | mail                                        |
| user_ldap | ldap_experienced_admin            | 1                                           |
| user_ldap | ldap_expert_username_attr         |                                             |
| user_ldap | ldap_expert_uuid_group_attr       |                                             |
| user_ldap | ldap_expert_uuid_user_attr        |                                             |
| user_ldap | ldap_group_display_name           | cn                                          |
| user_ldap | ldap_group_filter                 | (&(|(objectclass=posixGroup)))              |
| user_ldap | ldap_group_filter_mode            | 1                                           |
| user_ldap | ldap_group_member_assoc_attribute | memberUid                                   |
| user_ldap | ldap_groupfilter_groups           |                                             |
| user_ldap | ldap_groupfilter_objectclass      | posixGroup                                  |
| user_ldap | ldap_host                         | ldap://__                                   |
| user_ldap | ldap_login_filter                 | (&(|(objectclass=ldUserAccount))(uid=%uid)) |
| user_ldap | ldap_login_filter_mode            | 1                                           |
| user_ldap | ldap_loginfilter_attributes       |                                             |
| user_ldap | ldap_loginfilter_email            | 0                                           |
| user_ldap | ldap_loginfilter_username         | 1                                           |
| user_ldap | ldap_nested_groups                | 0                                           |
| user_ldap | ldap_nocase                       | 0                                           |
| user_ldap | ldap_override_main_server         | 0                                           |
| user_ldap | ldap_paging_size                  | 500                                         |
| user_ldap | ldap_port                         | 389                                         |
| user_ldap | ldap_quota_attr                   |                                             |
| user_ldap | ldap_quota_def                    | 0                                           |
| user_ldap | ldap_tls                          | 1                                           |
| user_ldap | ldap_turn_off_cert_check          | 1                                           |
| user_ldap | ldap_user_filter_mode             | 1                                           |
| user_ldap | ldap_userfilter_groups            |                                             |
| user_ldap | ldap_userfilter_objectclass       | ldUserAccount                               |
| user_ldap | ldap_userlist_filter              | (|(objectclass=ldUserAccount))              |
| user_ldap | ocsid                             | 166061                                      |
| user_ldap | types                             | authentication                              |
+-----------+-----------------------------------+---------------------------------------------+

```

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win 8.1

#### Web server error log
Empty.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"d5e480ac5ba62ac95e9b943baf0939f9","remoteAddr":"10.16.1.1","app":"core","message":"Exception while scanning file \"Klassen\/10f\/zzzz\/Europas Expansion in \u00dcbersee  Errichtung der Kolonialherrschaft   wissen.de.htm    1_files\/fp.js\": An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"3\", \"48\", \"1430905779\", \"4514\", \"5585f86ee998c\", \"1430905779\", \"11\", \"77291\", \"af52622fa97c4adc6538971c15827edc\", \"Klassen\\\/10f\\\/zzzz\\\/Europas Expansion in \\u00dcbersee  Errichtung der Kolonialherrschaft   wissen.de.htm    1_files\\\/fp.js\", \"fp.js\", \"12\", \"12\", \"af52622fa97c4adc6538971c15827edc\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","level":0,"time":"2015-06-20T23:34:07+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/scan.php?force=false&dir=&requesttoken=qeCAXFw1.6t5gn7h294fDiZD\/TYGVe"}
```

**Comment by PVince81** [comment] 2015-06-22 08:39
@icewind1991 possibly concurrent scanners trying to scan the same folders at the same time.

Have you been able to access the SMB folder after retrying ?

**Comment by xrm** [comment] 2015-06-23 07:53
Yes and no. I have two smb-mounts and one keeps failing while the other works just fine (they're both mounts from the same server) and in both shares are files that caused deadlock-warnings.
When I access the functional mount now, I don't get any further deadlock-warnings, though.

**Comment by PVince81** [comment] 2015-06-23 09:18
Hmm are both SMB mounts pointing to the same physical storage ?
Can you check the "oc_storages" table ? There should be one "smb::" entry for each storage.

**Comment by xrm** [comment] 2015-06-23 09:26
Among a few other entries:
````
mysql> SELECT * FROM oc_storages;
+--------------------------------------------+------------+
| id                                         | numeric_id |
+--------------------------------------------+------------+
...
| home::ses                                  |          5 |
| local::/var/www/owncloud/data/             |          2 |
| smb::ses@10.16.1.1//ses//                  |         11 |
| smb::ses@10.16.1.1//tausch//               |         12 |
| smb::ses@172.16.18.1//home//               |          3 |
| smb::ses@172.16.18.1//ses//                |          4 |
| smb::ses@172.16.18.1//tausch//             |          6 |
+--------------------------------------------+------------+
````

Not sure why there are two different IPs; the 10.16-address is the internal one, the 172.16 is the external one (the smb-includes refer to the internal address).

**Comment by PVince81** [comment] 2015-06-23 09:29
Hmmmm... did you at some point move the ownCloud instance ?

Maybe check if the matching oc_filecache entries are the new ones or outdated. `select * from oc_filecache where storage=11 order by path` (replace the storage id accordingly).

If your setup somehow causes it to alternate between the one or the other, you're going to have a bad time :frowning:

**Comment by PVince81** [comment] 2015-06-23 09:31
Did you configure the SMB mount points by IP or by host name ? Does the admin page show an IP or a host name ?

**Comment by xrm** [comment] 2015-06-23 09:38
By IP. I think I moved it once in the very beginning, yes.

oc_filecache lists entries for all of the entries except for #3. 4 and 6 do not contain the content of subfolders, though.

About the times ... probably not so cool:
````
mysql> select fileid,storage,path,path_hash,mtime,storage_mtime from oc_filecache where (storage=4 or storage=11) and path = 'backup'  order by path;
+--------+---------+--------+----------------------------------+------------+---------------+
| fileid | storage | path   | path_hash                        | mtime      | storage_mtime |
+--------+---------+--------+----------------------------------+------------+---------------+
|     45 |       4 | backup | 402051f4be0cc3aad33bcf3ac3d6532b | 1284983623 |    1284983623 |
|    172 |      11 | backup | 402051f4be0cc3aad33bcf3ac3d6532b | 1284983623 |    1284983623 |
+--------+---------+--------+----------------------------------+------------+---------------+
2 rows in set (0.01 sec)
````

**Comment by xrm** [comment] 2015-06-26 08:08
So ... Shall I just delete the wrong entries and the issue will be solved? :-)

**Comment by PVince81** [comment] 2015-06-26 08:13
You can try. With a bit of luck it will be solved, but I doubt it.

**Comment by nickvergessen** [comment] 2015-11-17 10:37
Duplicate of #20555 ?

**Comment by PVince81** [comment] 2016-02-17 17:48
Please try again with 8.2.2 which provides another level of locking to prevent concurrent scanners to scan the same thing, and also to prevent having two processes update the same database entry at the same time (file locking)

If you're still seeing this issue in 8.2.2, please reopen.

**Closed by PVince81** 2016-02-17 17:48 UTC
Labels: app:files_external, bug
