### ISSUE TITLE
An exception occurred while executing 'UPDATE oc_filecache', General Error

### ISSUE THREAD

**Issue by frankuit** [owncloud/core#12591] opened 2014-12-04 08:56 UTC
Hi Guys,

Since i upgraded to 7.03 last month, the load on my Mysql server seems to be increasing to a point of error.

First, i noticed the load on my mysql server increasing, and a couple of queries taking longer then they should.

in phpmyadmin i see: 

```
stop proces 	7547 	owncloud 	<removed ip>,55557 	owncloud 	Query 	20 	Updating 	UPDATE oc_filecache SET mimepart = '3', mimetype = '12', mtime = '1415098260', size = '699
```

it runs for very long, about 50 seconds, and after that, it bails out giving the error below.

```
{core} Exception while scanning file "files_trashbin/files/result_d20081217t092358_Gm025s04.dat.d1415105363": An exception occurred while executing 'UPDATE `oc_filecache` SET `mimepart` = ?, `mimetype` = ?, `mtime` = ?, `size` = ?, `etag` = ?, `storage_mtime` = ?, `permissions` = ?, `parent`=? WHERE `fileid` = ?':#012#012SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
```

I've tried increasing the general timeout value in mysql:
```
SET GLOBAL innodb_lock_wait_timeout = 400;
```

but then the processes stack up until there are (almost) no recources available.
i've tracked the files down in this message, and it belongs to a user who has about 6500 files in his trashbin. 
Retention was at 30 days, I've lowered it to 7, to see if that helps, but it deletes only 1 file every 10 seconds or so, so that will take weeks...
I had to restart the mysql server twice now to prevent bigger problems.

Any hints please ? 

### Server configuration
**Operating system**:
Debian wheezy 64 bit
**Web server:**
Apache2 (latest version of Debian)
**Database:**
Server version: 5.5.40-0+wheezy1-log (Debian)
**PHP version:**
5.4.35-0+deb7u2
**ownCloud version:** (see ownCloud admin page)
owncloud                              7.0.3-1 

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'owncloud.somesite.com',
  ),
  'datadirectory' => '/zfs/owncloud/owncloud',
  'dbtype' => 'mysql',
  'version' => '7.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'somehost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'bla',
  'dbpassword' => 'blabla',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'trashbin_retention_obligation' => 7,
  'trashbin_auto_expire' => true,
  'log_authfailip' => true,
  'loglevel' => '0',
  'log_type' => 'syslog',
  'logfile' => '',
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mailserver.somehost.com',
  'mail_smtpport' => '25',
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'somedomain.com',
);
```
**Updated from an older ownCloud or fresh install:**
Updated using dpkg as always.

**Comment by frankuit** [comment] 2015-01-09 08:58
Today, this problem is occuring again. and it's really wreaking havoc on my mysql server. 
Is there anyone who has any idea what can be done about this ? or, can we add a function for admins to clear a trashbin for a specific user as a temp workaround ?

Thanks,
Frank

**Comment by karlitschek** [comment] 2015-05-04 17:23
@frankuit Which apps do you have enabled?

**Comment by karlitschek** [comment] 2015-05-04 17:23
@schiesbn Can you have a look? Maybe related to files_trash

**Comment by frankuit** [comment] 2015-05-06 22:49
@karlitschek Sorry for the late reply, was on vacation, i have:

Deleted files 0.6.2
External storage support 0.2.3
External user support 0.4
First Run Wizard 1.1
LDAP user and group backend 0.5.0
Pictures 0.6.0
Picture gallery for ownCloud.
Share Files 0.6.1
Versions 1.0.5

**Comment by PVince81** [comment] 2015-05-11 11:07
Starting with OC 8.1, the trashbin expiration logic will be run in a background job. So it should hopefully not spam the database / logs that often.

**Comment by PVince81** [comment] 2015-05-28 12:41
Possibly related to concurrent scanner processes: https://github.com/owncloud/core/issues/16584
If I remember well, there is a code path that rescans the trashbin folder. If that would happen twice in a row for the same user, both scanners would try and update the same folder at the same time (in two separate folder-based transactions).

I'm closing this as duplicate of https://github.com/owncloud/core/issues/16584. Hopefully locking can be implemented to prevent two scanners to scan the same folder at the same time.

Also, as stated above, in 8.1 the trashbin expiration will happen in a background job, which should hopefully (in the short term) reduce the number of occurrences.

**Closed by PVince81** 2015-05-28 12:41 UTC
Labels: bug, db:mysql, sev2-high

**Comment by PVince81** [comment] 2015-05-28 12:45
I'd also recommend you to upgrade to 8.0.3.
From what I see in the code, the scan command in the trashbin is actually used to find versions, see https://github.com/owncloud/core/blob/v8.0.3/apps/files_trashbin/lib/trashbin.php#L838 vs the old version https://github.com/owncloud/core/blob/v8.0.2/apps/files_trashbin/lib/trashbin.php#L830
In 8.0.2 and before it was scanning too much and too often.
