### ISSUE TITLE
ownCloud 9: Undefined index: newVersionString

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#22999] opened 2016-03-09 09:40 UTC
### Steps to reproduce
1. Upgrade from ownCloud 8.2.2 to 9.0
2. Open the admin panel
3. Take a look at the logfiles

### Expected behaviour
No errors in the logiles

### Actual behaviour
the following error is logged multiple times:<code>Undefined index: newVersionString at /share/MD0_DATA/htdocs/owncloud/apps/updatenotification/templates/admin.php#8/<code>

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** "No errors have been found."

**List of activated apps:**
Calendar 1.0
Contacts 1.0

**Comment by LukasReschke** [comment] 2016-03-09 09:47
Dupe of https://github.com/owncloud/core/issues/22917

**Closed by LukasReschke** 2016-03-09 09:47 UTC
