### ISSUE TITLE
Quota mismatch between Personal and sync client

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#18852] opened 2015-09-05 20:03 UTC
Personal page of the Web UI and the sync client report different used and available storage space.
~~In fact, none of them report actual used space as reported by 'du' in Linux.~~
It's the case on both stable8.1 and master.

**Comment by DeepDiver1975** [comment] 2015-09-06 07:04
Please add more explicit data. Screenshots might help .. As well as using the issue template.

**Comment by fossxplorer** [comment] 2015-09-07 12:25
### Steps to reproduce
Install oC8.1 or master
Create user and add some amount of data
Install the sync client and after connecting, check the reported used and free space
Compare with reported info from Web UI Personal page
Run a 'du -sh data/<user>/files

### Expected behaviour
Sync client and Web UI Personal page should report same and correct quota info


### Actual behaviour
Web UI Personal page, Sync client and actual filesystem du report different amount.

### Server configuration
**Operating system**:
CentOS 6.7

**Web server:**
Apache 2.2

**Database:**
MariaDB 10

**PHP version:**
5.4.41

**ownCloud version:** (see ownCloud admin page)
Master and 8.1

**Updated from an older ownCloud or fresh install:**
Upgrade from 7->8.1 and then to master

**List of activated apps:**
Enabled:
  - activity: 2.1.2
  - calendar: 0.7.3
  - contacts: 0.4.0.0
  - documents: 0.10.1
  - files: 1.1.11
  - files_external: 0.2.3
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.3
  - files_texteditor: 0.4
  - files_versions: 1.0.6
  - firstrunwizard: 1.1
  - notes: 1.1.0


```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google Drive
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox, Chrome

**Operating system:**
CentOS 6.7

**Comment by DeepDiver1975** [comment] 2015-09-07 13:18
Which value is there in the desktop client?

**Comment by fossxplorer** [comment] 2015-09-07 13:37
![oc8_quota_01](https://cloud.githubusercontent.com/assets/3185080/9717846/514c9de4-5576-11e5-8eda-7a4c5485d0bc.png)

**Comment by DeepDiver1975** [comment] 2015-09-07 20:18
@dagotin is the desktop client on si units?

**Comment by LukasReschke** [comment] 2015-09-08 09:43
I think this is a duplicate of https://github.com/owncloud/enterprise/issues/798

cc @dragotin

**Comment by MorrisJobke** [comment] 2015-09-08 13:01
> 16470596 bytes are actually 15.7GiB so the Personal page seems to be correct.

That is the big problem - it's GiB and not GB. Also Windows mix up the units. We need a decision here which unit we want to have and then we can move all of our code to the very same unit/factor.

**Comment by karlitschek** [comment] 2015-09-08 13:25
Seems that this is getting more complex. we have to take the clients and also Windows/Mac into account.

@MTRichards What do you think?

**Comment by MTRichards** [comment] 2015-09-08 13:48
I would like to revert it to where we were before the update to SI units because users in deployments had this problem solved with, for example, LDAP entries specifying quota. Then we made a change on the server calculation and all of those quotas lost something like 7%, or whatever the difference is, simply because we changed a quota calculation. = Bad.

So, 1) revert to where we were before SI units. Then 2), label it correctly and change the clients to match what the server does because it is the server setup that is the master here, others need to map to that. If we have to, in clients, we can display both so users can see the state and have it make sense in their environment.

**Comment by LukasReschke** [comment] 2015-09-08 21:40
> Then we made a change on the server calculation and all of those quotas lost something like 7%, or whatever the difference is, simply because we changed a quota calculation. = Bad.

Is this really the case? As far I can tell we did no changes to the server so this simply is just a cosmetic issue and the same amount of data can be stored as before.

**Comment by MTRichards** [comment] 2015-09-08 23:31
Ok, so if that is the case....what happened here?
>We use AD to store quota information in an attribute. It’s just a text value, eg “10 GB”. So this means that when this change takes place on the server, a user with 10 GB of storage will have more than a 7% reduction in their actual storage space because ownCloud is interpreting the string differently than it used to. This is a significant percentage and will put some users suddenly over quota. We have some accounts for departments with 1 TB quotas. They now see a reduction.

**Comment by LukasReschke** [comment] 2015-09-09 10:06
> what happened here?

My guess: Multiple people assuming stuff without checking the source code.

So what we have in the LDAP app is `updateQuota` which is unmodified since April 2014 as can be seen at https://github.com/owncloud/core/blame/c4c9c5ffad9a67c6f0b19a567ac99aa6e97840de/apps/user_ldap/lib/user/user.php#L281-L302, the final calculation happens at https://github.com/owncloud/core/blame/c4c9c5ffad9a67c6f0b19a567ac99aa6e97840de/lib/private/helper.php#L283-L314 which since a long time uses non SI units.

So before we proceed let's please somebody actually perform some testing. I strongly believe this affects only the display and before the huge discussion at https://github.com/owncloud/enterprise/issues/798 should have even started somebody should have verified whether this is the case.

**Comment by LukasReschke** [comment] 2015-09-09 10:07
What we have is https://github.com/owncloud/client/pull/3558, in the client the **displayed size** changed but the server is as far I can tell still doing the same things we did for ages.

**Comment by LukasReschke** [comment] 2015-09-09 10:11
Also in https://github.com/owncloud/enterprise/issues/798 there is the following statement:

> We have a customer that is very upset about the change to SI units. Reference owncloud/core#13386

When you check owncloud/core#13386 you will see that there is no change in the server code referenced.

**Comment by MTRichards** [comment] 2015-09-09 12:27
Cool, thank you @LukasReschke 
> So before we proceed let's please somebody actually perform some testing. I strongly believe this affects only the display and before the huge discussion at owncloud/enterprise#798 should have even started somebody should have verified whether this is the case.

@bboule @cmonteroluque @MorrisJobke Not sure the process for getting attention on this particular issue, but would be good to confirm what is actually happening - ideally it is just the display Units that are a problem.

**Comment by dragotin** [comment] 2015-09-10 10:15
Back to "How it was before" in the client with 995b42d0fc31bee5882b2f6a704400f4f221c192

Just for the record: The displayed number is now wrong for the displayed unit, but consistent with the server and most of the rest of the world.

**Closed by dragotin** 2015-09-10 10:15 UTC
Labels: blue-ticket, triage

**Comment by fossxplorer** [comment] 2015-09-10 11:36
@danimo, shouldn't oC have a consistent way of reporting quota status to users?

**Comment by danimo** [comment] 2015-09-10 11:42
@fossxplorer After @dragotin's patch, we do again have a consistent way.

**Comment by fossxplorer** [comment] 2015-09-10 11:48
@danimo Great thanks! Misunderstood your previous comment .

**Comment by tflidd** [comment] 2015-09-10 12:02
With Microsoft-units, full Windows support is only a matter of time ... :smile:

**Comment by MTRichards** [comment] 2015-09-10 12:06
Thank you @danimo @dragotin
