### ISSUE TITLE
Personal page a little bit mixed up

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21089] opened 2015-12-09 19:09 UTC
![2015-12-09_20-09-08](https://cloud.githubusercontent.com/assets/878997/11695681/c5bd418c-9eb0-11e5-9074-42bc2d6c45a9.png)

**Comment by LukasReschke** [comment] 2015-12-09 19:12
Oh. That's in every browser… Ok :speak_no_evil: 

@jancborchardt

**Comment by MorrisJobke** [comment] 2015-12-09 19:17
Fixes are in https://github.com/owncloud/core/pull/20994

**Comment by jancborchardt** [comment] 2015-12-09 21:56
Also, this is a duplicate of https://github.com/owncloud/core/issues/20610 ;)

**Closed by jancborchardt** 2015-12-09 21:56 UTC
Labels: bug, design
