### ISSUE TITLE
Upgrade failed 8.2.0.12 -> 8.2.1.4 : "Unable to move ..." and "Directory not empty"

### ISSUE THREAD

**Issue by mistersixt** [owncloud/core#20627] opened 2015-11-20 06:32 UTC
Hi all,

I just tried to upgrade from 8.2.0.12 (which I manually updated from 8.1.X some few weeks ago) to 8.2.1.4 by hitting the update button within the administration panel, and it fails on step 3 with:

Error 	updater 	Unable to move /var/www/owncloud/_oc-upgrade/8.2.1.4/core/resources to /var/www/owncloud/resources
Error 	updater 	Something went wrong for core. Rolling back. 
Error 	PHP 	rename(/var/www/owncloud/_oc-upgrade/8.2.1.4/core/resources,/var/www/owncloud/resources): Directory not empty at /var/www/owncloud/apps/updater/lib/helper.php#52

All files and folders belong to user "www-data", so it cannot be a permissioning issue I think, enough space is available, too, so I am lost here already.

Any help is welcome,

kind regards, Joerg.

**Comment by schricka** [comment] 2015-11-20 07:10
some to me

**Comment by RealRancor** [comment] 2015-11-20 08:26
Might be a duplicate of https://github.com/owncloud/updater/issues/189

**Comment by PVince81** [comment] 2015-11-20 09:05
Closing as duplicate.

**Closed by PVince81** 2015-11-20 09:05 UTC
