### ISSUE TITLE
Odt files doesn't download with a click after upgrading from 7.0.4 encripted to 8.0.0 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13773] opened 2015-01-29 17:21 UTC
### Steps to reproduce

1. Having a oc 7.0.4 server with an account with odt files.
2. Upgrade to oc 8.0.0 .
3. Click on the name of the file.   (Not in the download button).

### Expected behaviour
File is downloaded correctly.

### Actual behaviour
An error message appears.

![screen shot 2015-01-29 at 18 04 13](https://cloud.githubusercontent.com/assets/9048796/5962356/a0990176-a7e3-11e4-99f5-f5b6eca65205.png)

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Encryption, Documents

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes

### Client configuration

**browser*
Chrome

**Comment by RealRancor** [comment] 2015-01-29 18:09
Hi,

as this seems to be related to the documents app its probably better to report this in the issue tracker of this app:

https://github.com/owncloud/documents/issues

I also don't see an error message in the screenshot as you have described. Could be useful to have a look at the javascript console of your browser and the /data/owncloud.log to see if you got any errors there.

**Comment by PVince81** [comment] 2015-01-30 11:31
Are both ODF viewer / documents app enabled at the same time ?
Anything in the logs?

**Comment by SergioBertolinSG** [comment] 2015-01-30 12:01
Nothing in logs (browser&owncloud.log).
It is activated Documents app.

**Comment by PVince81** [comment] 2015-01-30 12:51
How did you upgrade ? Did you replace the code into your owncloud code ? Or did you delete everything and only kept "config" and "data" ?
Or did you install the documents app from the app store ? Because ownCloud 8 doesn't bundle the documents app any more so I suspect that you might still be using the documents app from OC 7 (which was still in the "apps" folder if you didn't upgrade by deleting everything but "config" and "data")

I tried copying the old OC 7 documents app to reproduce this case and I see the same symptoms.
Maybe we should modify the old OC 7 documents app to have "requiremin = 8" ?

@karlitschek @VicDeo

**Comment by PVince81** [comment] 2015-01-30 12:51
I meant "requiremax=7"

**Comment by SergioBertolinSG** [comment] 2015-01-30 13:22
Yes, that app was there before copying everything from 8.0.0 tarball into owncloud folder.

**Comment by RealRancor** [comment] 2015-01-30 13:29
@SergioBertolinSG 

You shouldn't do that. Please see the upgrading guide at the documentation how to do a proper upgrade:

http://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html

**Comment by VicDeo** [comment] 2015-01-30 18:56
@PVince81 Submitted as https://github.com/owncloud/documents/pull/446

**Comment by VicDeo** [comment] 2015-02-11 20:43
BTW 
1. I disagree. Expected behavior is to view document, not download it
2. This is not an error message. This message is used by our upstream instead of progressbar while viewer is opening.

**Comment by PVince81** [comment] 2015-08-03 13:03
Linked ticket was closed, closing.

@SergioBertolinSG you might want to verify this in 8.0.5 and 8.1.

**Closed by PVince81** 2015-08-03 13:03 UTC
Labels: bug
