### ISSUE TITLE
owncloud update to  8.1.4 was unsuccessful

### ISSUE THREAD

**Issue by frandomr** [owncloud/core#20934] opened 2015-12-03 19:08 UTC
After updating the packages to via apt-get, my owcloud installation went into maintenance-mode (as I was informed by the webserver info page) but did not went to normal operation even after spending an hour like this. 
Manual editing of config.php enabled me to "start update" via the web interface. Finally the update failed with the following message:
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "contacts_index" as such route does not exist. 
![oc_update_failure](https://cloud.githubusercontent.com/assets/16140253/11570796/7118ca4a-99f9-11e5-94c6-eba0fd010062.png)
Thanks for any help!

**Comment by LukasReschke** [comment] 2015-12-03 19:11
Dupe of https://github.com/owncloud/core/issues/19145, just disable the maintenance mode in the config file manually for now

**Closed by LukasReschke** 2015-12-03 19:11 UTC
