### ISSUE TITLE
Stable repo for Xenial contains upgrade to 10.0.0

### ISSUE THREAD

**Issue by yoniy0** [owncloud/core#27775] opened 2017-04-29 17:37 UTC
### Steps to reproduce
1. On Xenial machine, with a working OC server, version 9.1.4, add the stable repository at `deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.10/ /` to sources.
2. Run `apt update`
3. Run `apt list --upgradable`

### Expected behaviour
The next stable version after 9.1.4 is 9.1.5, and it should be offered for upgrade; or else, all packages (relative to OC) should appear as current.

### Actual behaviour
One receives the following upgrade suggestions:
```
owncloud/unknown 10.0.0-1.1 all [upgradable from: 9.1.4-2.1]
owncloud-deps-php7.0/unknown 10.0.0-1.1 all [upgradable from: 9.1.4-2.1]
owncloud-files/unknown 10.0.0-1.1 all [upgradable from: 9.1.4-1.1]
```

Note that 10.0.0 is still in RC, and shouldn't be considered "stable".

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** PHP 7.0.15-0ubuntu0.16.04.4

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** Updated from 9.1.3 (or 2)

**Where did you install ownCloud from:** Stable repository

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**Comment by yoniy0** [comment] 2017-04-29 17:39
Sorry, I tried to do this from a mobile device, and can't figure out how to complete the necessary data. I'll fill in details in a few hours.

**Comment by yoniy0** [comment] 2017-04-29 21:36
Updated with relevant information.

**Comment by spelga** [comment] 2017-04-30 10:50
Issue also applies to 9.1.5 otherwise same setup.

**Comment by individual-it** [comment] 2017-05-01 10:27
I think in oC term it is "stable" but not "production"
https://owncloud.org/release-channels/

**Comment by yoniy0** [comment] 2017-05-01 11:13
@individual-it this is madness. An end-user adding a PPA dubbed "stable" doesn't expect software that isn't production-ready to hit his instance.

Not to mention, I don't recall any such explanation of terminology being available when I included this PPA in my sources list.

If this is the direction OC wants to go, then there should be a (very) visible explanation on the "Packages" tab under "Download". Moreover, under "Repos: Stable or Major Release?" in [the documentation](https://doc.owncloud.org/server/9.1/admin_manual/installation/linux_installation.html) there should really be a clarification that "stable" isn't "production-ready", instead of 

> When you use the Stable repo, you never have to change it as it always tracks the current stable ownCloud version through all major releases: 8.2, 9.0, and so on. (Major releases are indicated by the second number, so 8.0, 8.1, 8.2, and 9.0 were all major releases.)
> 
> If you wish to track a specific major release, such as 9.0 or 9.1, then use that repo. That way you won’t accidentally find yourself looking at an upgrade to the next major release before you’re ready.

**Comment by kdslkdsaldsal** [comment] 2017-05-01 17:37
@yoniy0 I think you should keep this open for now until one of the repo maintainer is having a look at this. If you e.g. browse on:

https://download.owncloud.org/download/repositories/stable/Ubuntu_16.10/

you see that there is 9.1.5 available and not 10.0.0. Not quite sure if the repo index needs to be refreshed or similar

**Comment by t0rzz** [comment] 2017-05-02 13:23
FYI, this is happening with the Debian repository too.

**Comment by yoniy0** [comment] 2017-05-02 13:30
@kdslkdsaldsal this bug isn't about the 404 error when upgrading using the "stable" repo; my understanding of how GitHub works is lacking, so I'll appreciate comments on how to proceed.

**Comment by kdslkdsaldsal** [comment] 2017-05-02 13:31
@yoniy0 Just keep this open and some one with the knowledge about the repositories might have a look at it

**Comment by t0rzz** [comment] 2017-05-02 14:55
Just leave the issue open until a repo maintainer fix the issue.

ToR

**Comment by kdslkdsaldsal** [comment] 2017-05-02 15:09
cc @jnweiger @crrodriguez

**Comment by Saphieron** [comment] 2017-05-04 11:04
Is there any ETA, when this can be fixed?

**Comment by kdslkdsaldsal** [comment] 2017-05-05 08:57
Side-note: If your system is not a testing system wait for 10.0.1 or 10.0.2 before upgrading. Until then the repositories are probably fixed as well.

**Comment by PVince81** [comment] 2017-05-12 14:45
@crrodriguez

**Comment by crrodriguez** [comment] 2017-05-12 14:49
Stable contains 9.1.x series until issues on 10.0 are sorted.. I cannot reproduce the problem you are seeing.

**Comment by yoniy0** [comment] 2017-05-12 14:58
@crrodriguez I can confirm that it does now, so I guess this issue is solved.

However, it used to suggest the upgrade to 10.0 for `owncloud 10.0.0-1.1 owncloud-files 10.0.0-1.1 owncloud-deps-php7.0 10.0.0-1.1`, then fail with a 404; this was definitely an issue for multiple people (see https://central.owncloud.org/t/ubuntu-16-04-lts-upgrade-failing/7325).

**Comment by crrodriguez** [comment] 2017-05-12 14:59
@yoniy0 yes, this issue has also been fixed. wont happen again when 10.0 shows up properly in upcoming releases.
closing.

**Closed by crrodriguez** 2017-05-12 14:59 UTC

**Comment by genna87** [comment] 2017-05-12 15:16
I'm still having the same problem
`sudo apt-get dist-upgrade -V`

gives this 

> Lettura elenco dei pacchetti... Fatto
> Generazione albero delle dipendenze
> Lettura informazioni sullo stato... Fatto
> Calcolo dell'aggiornamento... Fatto
> I seguenti pacchetti saranno aggiornati:
>    owncloud (9.1.4-2.1 => 10.0.0-1.1)
>    owncloud-deps-php7.0 (9.1.4-2.1 => 10.0.0-1.1)
>    owncloud-files (9.1.4-1.1 => 10.0.0-1.1)
> 3 aggiornati, 0 installati, 0 da rimuovere e 0 non aggiornati.
> È necessario scaricare 27,8 MB di archivi.
> Dopo quest'operazione, verranno occupati 38,1 MB di spazio su disco.
> Continuare? [S/n]
> Err:1 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud 10.0.0-1.1
>   404  Not Found [IP: 85.10.210.219 80]
> Err:2 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-files 10.0.0-1.1
>   404  Not Found [IP: 85.10.210.219 80]
> Err:3 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-deps-php7.0 10.0.0-1.1
>   404  Not Found [IP: 85.10.210.219 80]
> E: Impossibile recuperare http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud_10.0.0-1.1_all.deb  404  Not Found [IP: 85.10.210.219 80]
> 
> E: Impossibile recuperare http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-files_10.0.0-1.1_all.deb  404  Not Found [IP: 85.10.210.219 80]
> 
> E: Impossibile recuperare http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-deps-php7.0_10.0.0-1.1_all.deb  404  Not Found [IP: 85.10.210.219 80]
> 
> E: Impossibile scaricare alcuni pacchetti. Potrebbe essere utile eseguire "apt-get update" o provare l'opzione "--fix-missing".

**Comment by Saphieron** [comment] 2017-05-12 15:24
Same issue here:

"sudo apt-get update" and "sudo apt-get upgrade" gives me:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  owncloud owncloud-deps-php7.0 owncloud-files
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.8 MB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:130:934f::3 80]
Err:2 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-files 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:130:934f::3 80]
Err:3 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-deps-php7.0 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:130:934f::3 80]
E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud_10.0.0-1.1_all.deb  404  Not Found [IP: 2a01:4f8:130:934f::3 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-files_10.0.0-1.1_all.deb  404  Not Found [IP: 2a01:4f8:130:934f::3 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-deps-php7.0_10.0.0-1.1_all.deb  404  Not Found [IP: 2a01:4f8:130:934f::3 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by crrodriguez** [comment] 2017-05-12 15:29
did you clean the apt cache first ? stable does not have 10.0.0 packages at all.

**Comment by genna87** [comment] 2017-05-12 15:32
Using `sudo apt-get clean && sudo apt-get update > /dev/null && sudo apt-get dist-upgrade -V` gives the very same output

**Comment by t0rzz** [comment] 2017-05-12 16:19
I've been having, as already stated, the exact same problem for a month so far. Cleaning the partial apt directory won't fix it (nor won't fix it the clean apt command).

Francesco Menghetti

**Comment by t0rzz** [comment] 2017-05-12 16:21
I forgot to say that this very same issue happens on Debian stable. Since other users are reporting it on Ubuntu too (same repo?) I believe it is a repository issue.

**Comment by bachp** [comment] 2017-05-12 17:19
I'm also still hitting this on both Ubuntu 14.04 and 16.04. `sudo apt-get clean` doesn't help.

**Comment by KoffeinKaio** [comment] 2017-05-12 23:29
Same here - still having this even after apt clean

```

Fehl http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:190:21ad::3 80]
Fehl http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud-files 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:190:21ad::3 80]
Holen: 2 http://security.debian.org/ jessie/updates/main libpq5 amd64 9.4.12-0+deb8u1 [126 kB]
Fehl http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud-deps-php5 10.0.0-1.1
  404  Not Found [IP: 2a01:4f8:190:21ad::3 80]


root@Koro:~# cat /etc/debian_version
8.8
root@Koro:~# cat /etc/apt/sources.list.d/owncloud.list
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

```

**Comment by JonnewDev** [comment] 2017-05-13 09:47
It still get a problem for Ubuntu 14.04,

Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud-files 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud-deps-php5 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud_10.0.0-1.1_all.deb  404  Not Found [IP: 144.76.105.220 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud-files_10.0.0-1.1_all.deb  404  Not Found [IP: 144.76.105.220 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud-deps-php5_10.0.0-1.1_all.deb  404  Not Found [IP: 144.76.105.220 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

sudo apt list --installed owncloud  gives
owncloud/now 9.1.5-1.1 all [installed,upgradable to: 10.0.0-1.1]

**Comment by spelga** [comment] 2017-05-13 10:29
Same problem for me too. I've tried apt-get clean & apt-get autoclean and their apt versions. None seems to clear things out so it pull down v9 latest. This is on Ubuntu Server 16.04

**Comment by yoniy0** [comment] 2017-05-13 10:38
I haven't the foggiest why I see 9.1.5 in "stable" where many other people still see 10.0. The only thing I might've done differently is that I changed my sources list to use the 9.1 PPA, so for this test I had to change it back to "stable", then run `apt update && apt list --upgradable`.

Perhaps some of you could try to change and restore the repo, and see if that makes a difference. Also, could someone post the output of `apt policy owncloud`?

**Comment by spelga** [comment] 2017-05-13 11:29
Here's the apt policy without taking any of the other steps ie switching to
9.1 PPA.

owncloud:
  Installed: 9.1.5-1.1
  Candidate: 10.0.0-1.1
  Version table:
     10.0.0-1.1 500
        500
http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04
 Packages
 *** 9.1.5-1.1 100
        100 /var/lib/dpkg/status

**Comment by fkraiem** [comment] 2017-05-13 13:29
My understanding is that 10.0 packages were (mistakenly?) uploaded to the repositories, and then removed. If you refreshed the package list through `apt update` while the 10.0 packages were there, they are now in your Apt index, and Apt will try to install them (which will fail, since they have been removed). In principle, running `apt update` now should remove them from the package list; on my system I have

```
% apt-cache policy owncloud                     
owncloud:
  Installed: (none)
  Candidate: 9.1.5-1.1
  Version table:
     9.1.5-1.1 500
        500 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Packages
```

If that doesn't work for some weird reason, you can force Apt to ignore this version by putting this in `/etc/apt/preferences`:

```
Package: owncloud*
Pin: version 10.0*
Pin-Priority: 0
```

(And some terminology nitpicking: please don't use the term "PPA" to refer to the Owncloud repositories; it should be reserved for those hosted on `ppa.launchpad.net`.)

**Comment by JonnewDev** [comment] 2017-05-13 13:36
Did this,

/etc/apt/sources.list/owncloud.list
renamed to owncloud.list.old

ran apt-get update

got warning
N: Ignoring file 'owncloud.list.old' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

ran apt-get upgrade

got warning

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
N: Ignoring file 'owncloud.list.old' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
N: Ignoring file 'owncloud.list.old' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension

renamed owncloud.list.old to owncloud.list

ran apt-get update
ran apt-get upgrade

Now sudo apt list --installed owncloud says
owncloud/unknown,now 9.1.5-1.1 all [installed]

instead of previously when it said,
owncloud/now 9.1.5-1.1 all [installed,upgradable to: 10.0.0-1.1]

So I suppose it fixed my problem.
I’m not very good with apt but I would guess there is a better way to “refresh” the source.

**Comment by Saphieron** [comment] 2017-05-13 15:18
@JonnewDev 's workaround worked like a charm. Everything was updated on my machine.

**Comment by t0rzz** [comment] 2017-05-13 17:23
This fixed the problem on my end too.

Thank you!

Il 13 Mag 2017 17:18, "Saphieron" <notifications@github.com> ha scritto:

**Comment by spelga** [comment] 2017-05-14 00:22
Seemed to work for me as I get no message now when I upgrade. Renaming has to use mv rather than cp which is probably technically correct but just in case anyone else has problems renaming you must mv as cp doesn't work.

**Comment by janhenke** [comment] 2017-05-14 08:42
That is not a fix, please fix your repository properly. If you provide a repository for your software, it should not be broken so severely.

**Comment by bachp** [comment] 2017-05-14 09:02
@janhenke I don't think the repository is broken anymore. It's just the data on you local machine that is not correct anymore.

**Comment by janhenke** [comment] 2017-05-14 09:21
@bachp Well, no. Since the repository was broken by Owncloud, they should fix it properly. Requiring the user to apply local steps is not a proper fix. Even more, it should not have happened in the first place. Do you operate public repositories if you are not knowing what you are doing. This should have never happened in the first place.

By the way, a proper fix would have been to upload a new package to the repository, which has a higher version number (like 10.0.0-1~really9.1.5-2), which then would be picked up. Never just drop packages, once they have been published! This issues sheds quite a bad light on the quality in this project.

**Comment by kdslkdsaldsal** [comment] 2017-05-14 17:59
quality in this project != quality of the repository 😄 

Two different things and IMHO the OBS repositories should be dropped completely as a software project like ownCloud never should be responsible and provide linux repositories for such a large amount of different linux distros.

**Comment by janhenke** [comment] 2017-05-14 18:02
@kdslkdsaldsal As long as the repositories are provided officially by the project, the quality of these repositories is one part of the overall project quality. See my point from above, if you provide such a thing, make sure you know what you are doing, if not, do not setup a repository in the first place.

**Comment by kdslkdsaldsal** [comment] 2017-05-14 18:19
It might be a part, but a minor part and everyone is free to choose other installation methods better fitting / providing to their use case.

> if you provide such a thing, make sure you know what you are doing, if not, do not setup a repository in the first place.

And how should people get familiar / into that into the first place? If everyone would think like this and would never start then there would be progress in IT at all... 😉

**Comment by janhenke** [comment] 2017-05-14 18:33
@kdslkdsaldsal It is all about how you appear to the outside world, minor or not, but it shows the project in bad light. It is not the first time this project has packaging problems like this.

> And how should people get familiar / into that in the first place? If everyone would think like this and would never start then there would be no progress in IT at all... 😉

Are you serious? There are plenty ways to gain experience, just do not try to learn the basics in the **public**, **official** repository of a major open source project.
You can start with your own private project, if you break it, only you are affected. But your attitude shows a deep lack of understanding of software engineering principles and basic common sense. I teach myself plenty of things via private projects, but once you work on something meant for production use, make damn sure you know what you are doing.

The last remark shows again a worrying lack of professional attitude.

**Comment by kdslkdsaldsal** [comment] 2017-05-14 19:03
Again:

> IMHO the OBS repositories should be dropped completely as a software project like ownCloud never should be responsible and provide linux repositories for such a large amount of different linux distros.

This would avoid that we need to discuss this here.

Another way:

Instead of complaining / flaming here about the repositories have you consider to just contribute and take over the maintenance? This is still Open Source and people are free to contribute if they think the repository maintainer don't understand the basics...

**Comment by genna87** [comment] 2017-05-15 13:10
The workaround @JonnewDev used worked like a charm for me.

Just a question, for the sake of knowledge:
It's technically possible to resolve the issue via repository uploading a temporary package?

**Comment by janhenke** [comment] 2017-05-15 18:34
@genna87 Yes, it is possible, as I described above. That would have been the correct solution instead of deleting an already published package.

**Comment by crrodriguez** [comment] 2017-05-15 19:12
Folks,  first of all.. 10.0 packages are still there, but not in the stable repository, this is because they were reverted, they won't be released to stable until next patch update.
We cannot fix the fallout problems in your installation (or better said the weird apt behaviour ) magically from remote. We will try not to have to revert released packages again. Sorry for the inconvenience.

**Comment by rowland39** [comment] 2017-05-18 05:45
Hi, I ran into this problem. I'm not an expert on APT beyond simply using it, but after looking at the apt-cache manual page, this worked for me:

```
sudo mv /var/lib/apt/lists/download.owncloud.org_download_repositories_stable_Ubuntu%5f16.04_* .
sudo apt-get update
```

I was able to update fine after that. I moved those list files instead of deleting them just in case (and . was my home directory at the time), but it turns out I could have simply deleted them. That's specific to my Ubuntu release, so it would need to be adjusted for others.

**Comment by sibidharan** [comment] 2017-05-21 10:13
@rowland39 Worked. Thanks.

**Comment by deftoner** [comment] 2017-05-23 20:55
@rowland39 That worked for me too! THANKS.

**Comment by jochenwezel** [comment] 2017-05-29 14:07
Many thanks @rowland39 for his shell commands. For me with my Ubuntu 16.04 LTS, I had to drop a few more files and use
```bash
rm /var/lib/apt/lists/download.owncloud.org_download_repositories_*
apt-get update
apt-get upgrade
```
After that, apt-get was able to upgrade from 9.1.4 to 9.1.5. (I assume 10.0.1 or 10.0.2 will follow automatically as soon as they're considered stable enough)
