### ISSUE TITLE
possible not found exception when refreshing session

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#20527] opened 2015-11-16 12:52 UTC
Today, when i wanted to access my 8.2 dev instance, I was faces with a OCP\Files\NotFoundException. At this point of time, I was logged in as an local admin user. I disabled LDAP, just in case. Meanwhile, I am not able to reproduce it anymore.

What happend is that I got a NotFoundException exception when I attempted to access ownCloud as local admin user. At that point I was logged in from a previous session. The backtrace is:

```
#0 /home/blizzz/owncloud/dev/stable8.2/apps/files/index.php(92):  OC_Helper::getStorageInfo('/', false)
#1 /home/blizzz/owncloud/dev/stable8.2/lib/private/route/route.php(154) : runtime-created function(1): require_once('/home/blizzz/ow...')
#2 [internal function]: __lambda_func(Array)
#3 /home/blizzz/owncloud/dev/stable8.2/lib/private/route/router.php(282): call_user_func('\\x00lambda_106', Array)
#4 /home/blizzz/owncloud/dev/stable8.2/lib/base.php(851): OC\\Route\\Router->match('/apps/files/')
#5 /home/blizzz/owncloud/dev/stable8.2/index.php(39): OC::handleRequest()
#6 {main}","File":"/home/blizzz/owncloud/dev/stable8.2/lib/private/helper.php","Line":841
```

In the data directory there were no folders, but that's ok. It was a fairly new install, and all my LDAP users i usually test with have their directories somewhere else. The  exception only went away after I created the users folder in the data directory, plus the files subfolder.

However, when I tried to replicate this it always worked (as in: not uncaught exception thrown):
- create a new local user (= has no data dir yet), login → works
- delete the admin users folder again. logout and login as admin → works
- while being logged in, delete the admin folder, refresh → works
- share a file in both directions with another user, delete admin home folder, refresh → works 
- delete the other user from DB (so that no hooks are fired and cleanup is done), delete admin home folder, refresh → works

So, I do not really know what caused this edge case. Maybe someone with more insights to files? Maybe just a side effect from just running from git? @icewind1991 @PVince81 

cc @cmonteroluque

**Comment by PVince81** [comment] 2015-11-16 12:59
Can you clarify with what you mean with "delete the admin users folder again" ? Is it a web UI action or deleted on the "data" folder directly ? Same question for all other filesystem actions.

**Comment by blizzz** [comment] 2015-11-16 13:03
> Can you clarify with what you mean with "delete the admin users folder again" ? Is it a web UI action or deleted on the "data" folder directly ? Same question for all other filesystem actions.

Deleted the users folder from the data directory by command line, since that's the only way to get rid of it, except deleting the whole user.

**Comment by PVince81** [comment] 2015-11-16 13:06
>Today, when i wanted to access my 8.2 dev instance, I was faces with a OCP\Files\NotFoundException. At this point of time, I was logged in as an local admin user. I disabled LDAP, just in case. Meanwhile, I am not able to reproduce it anymore.

Assuming you accessed it from the browser. Was it from a browser tab that was already open ? (hearbeat) Or was it simply an existing session cookie that "revived" your session when you opened a new tab on your OC instance ?

**Comment by PVince81** [comment] 2015-11-16 13:16
Hmm, are you saying that all folders disappeared from the "data" directory ?
Else how could your admin user still be logged in if there was no home ? Or was it a session from a previous "instance reset" ?

**Comment by blizzz** [comment] 2015-11-16 13:31
> Assuming you accessed it from the browser. Was it from a browser tab that was already open ? (hearbeat) 

A new browser tab

> Or was it simply an existing session cookie that "revived" your session when you opened a new tab on your OC instance ?

Good point, i forgot to mention this: While i was faced with the Exception, I also deleted the session cookies. After refresh, the Exception was shown again. That surprised me.

**Comment by blizzz** [comment] 2015-11-16 13:35
> Hmm, are you saying that all folders disappeared from the "data" directory ?

No. I am not entirely sure there were folders at all, but actually I expected the local admins folder to be there. ~~My LDAP users have their directories somewhere else.~~ LDAP users should have  their folders there as well. This makes it strange, now I don't want to exclude that these directories disappeared.

> Else how could your admin user still be logged in if there was no home ? Or was it a session from a previous "instance reset" ?

No, there were no instance resets.

**Comment by PVince81** [comment] 2015-11-16 14:05
I tried the following:

1. Setup OC with "root" as the admin user
1. Setup LDAP with zombies
1. Login as "zombie1"
1. Create a folder "test" with some contents
1. Share "test" with "root"
1. Login as "root" in the web UI
1. Disable the LDAP server
1. Refresh the web UI

I get the expected `OC\ServerNotAvailableException` with "Lost connection to LDAP server".

Nothing about file not found.

**Comment by PVince81** [comment] 2015-11-16 14:07
The code path from the original stack traces goes to the files app's "apps/files/index.php".

In my test case it doesn't even reach that file and throws an exception earlier.

**Comment by blizzz** [comment] 2015-11-16 14:10
I don't believe LDAP contributes hereto. I operated with local users only, and I always got NotFoundException. Also, disabled the LDAP config, so ServerNotAvailableException could not have happened.

**Comment by PVince81** [comment] 2015-11-16 14:13
Hmm ok... strange.

I just did some "race condition" tests and put a breakpoint just before the failing line, then stopped LDAP at this point. I still did not get the error as above. Same result when the breakpoint is at the end of setupFS().

Moving to 8.2.2 for now, this is not a regression.

**Comment by PVince81** [comment] 2015-11-16 14:14
@icewind1991 could this be caused by memcached stuff ?

**Comment by PVince81** [comment] 2015-11-25 15:35
Not sure how to debug/reproduce this possible race condition without more data.

**Comment by PVince81** [comment] 2015-11-25 16:09
Let's close it for now as it is not reproducible.

**Closed by PVince81** 2015-11-25 16:09 UTC
Labels: blue-ticket, bug, comp:filesystem, discussion, sev2-high

**Comment by blizzz** [comment] 2015-11-27 11:27
This was caused by running single unit tests (any). Probably due to the cleanup methods from our TestCase class.
