### ISSUE TITLE
LDAP users belonging to group sometimes not showing OC 8.2.2

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#22175] opened 2016-02-05 21:23 UTC
Dear all,

I setup LDAP to sync users and also groups, and this works mostly fine, eg people in group A in LDAP are put in the ownCloud group A.

However, when in the admin view, either as admin or as user with group admin rights, when I click on a group on the left menu, the list appears empty. In "Everyone", however, I can see all the users correctly.

Furthermore, in Chrome, when clicking on Everyone, the list is empty, but upon "Refreshing" the page, the list of users appear.

Could you please help me figure what's wrong here or if there's a bug somewhere?

For reference, this is the line I see in owncloud.log when clicking on "Everyone" or "mygroup" when the page shows up white

```bash
{"reqId":"VrUTE4sP7F@RWz5hIqKJNgAAAAM","remoteAddr":"10.244.9.18","app":"PHP","message":"array_slice() expects parameter 1 to be array, object given at \/var\/www\/html\/owncloud\/apps\/user_ldap\/group_ldap.php#530","level":0,"time":"2016-02-05T21:24:35+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=30&gid=_everyone&pattern="}
```

Thank you,

```bash
[root@lcsb-oc1-server owncloud]# sudo -u apache php occ ldap:show-config ''
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                   |
| hasPagedResultSupport         |                                                                                                     |
| homeFolderNamingRule          |                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                   |
| ldapAgentName                 | uid=ldapconnector,cn=users,cn=accounts,dc=uni,dc=lu                                                 |
| ldapAgentPassword             | ***                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                     |
| ldapBackupHost                |                                                                                          |
| ldapBackupPort                |                                                                                                  |
| ldapBase                      | dc=uni,dc=lu                                                                                        |
| ldapBaseGroups                | cn=groups,cn=accounts,dc=uni,dc=lu                                                                  |
| ldapBaseUsers                 | cn=users,cn=accounts,dc=uni,dc=lu                                                                   |
| ldapCacheTTL                  | 600                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                     |
| ldapExpertUsernameAttr        |                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                  |
| ldapGroupFilter               | (&(objectclass=groupofnames)(memberOf=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))              |
| ldapGroupFilterGroups         |                                                                                                     |
| ldapGroupFilterMode           | 1                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                              |
| ldapHost                      | myldaphpst.uni.lu                                                                              |
| ldapIgnoreNamingRules         |                                                                                                     |
| ldapLoginFilter               | (&(&(objectClass=posixaccount)(memberof=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                   |
| ldapNestedGroups              | 0                                                                                                   |
| ldapOverrideMainServer        |                                                                                                     |
| ldapPagingSize                | 500                                                                                                 |
| ldapPort                      | 389                                                                                                 |
| ldapQuotaAttribute            |                                                                                                     |
| ldapQuotaDefault              | 200000000000                                                                                        |
| ldapTLS                       | 0                                                                                                   |
| ldapUserDisplayName           | displayname                                                                                         |
| ldapUserFilter                | (&(objectClass=posixaccount)(memberof=cn=owncloud,cn=groups,cn=accounts,dc=uni,dc=lu))              |
| ldapUserFilterGroups          |                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                   |
| ldapUserFilterObjectclass     | person                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                |
| turnOffCertCheck              | 0                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
```

ownCloud: `LCSB Cloud version 8.2.2`
LDAP App version: `LDAP user and group backend  0.7.1`

--
Trefex

**Comment by Xenopathic** [comment] 2016-02-07 09:56
@owncloud/ldap

**Comment by blizzz** [comment] 2016-02-08 11:18
Possibly duplicate of https://github.com/owncloud/core/issues/21896 fixed with https://github.com/owncloud/core/pull/21999. Can you confirm, @Trefex?

**Comment by PVince81** [comment] 2016-02-23 10:11
@Trefex any update ? Do you still see the issue with 9.0beta2 which contains the fix ?

**Comment by Trefex** [comment] 2016-02-23 13:33
@PVince81 for that I would have to setup a test environment and test it. 

But it seems related yes.

**Comment by blizzz** [comment] 2016-02-23 13:39
@Trefex I'll close it then as fixed. If you still see the issue once 8.2.3 is out, please reopen this report.

**Closed by blizzz** 2016-02-23 13:39 UTC
Labels: app:user_ldap, bug, needs info, sev2-high
