### ISSUE TITLE
New users has to relogin to generate keys when encryption was already enabled.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16128] opened 2015-05-06 16:42 UTC
### Steps to reproduce

1. Enable encryption app.
2. Enable default encryption module (admin page).
3. Log out and log in again.
4. Create a new user "user1".
5. Log out.
6. Login with user1.

### Expected behaviour
Keys are generated at first login.

### Actual behaviour
user1 has to relogin to generate keys. A warning message appears suggesting the user1 to relogin. 

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in community edition. + Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes one sftp enabled.

**Are you using encryption:** 
yes

### Client configuration

**browser**
Chrome 41

**Operating system**
Mac OS X

**Comment by schiesbn** [comment] 2015-05-06 16:52
duplicate of https://github.com/owncloud/core/issues/15981
fix waits for review: https://github.com/owncloud/core/pull/16075

**Closed by schiesbn** 2015-05-06 16:52 UTC
Labels: app:encryption, bug
