### ISSUE TITLE
File created manualy on file system not discovered by owncloud

### ISSUE THREAD

**Issue by vpo92** [owncloud/core#21351] opened 2015-12-23 10:51 UTC
Hi.
Since last update (8.2.1), when I create a file on the file system, this file is not automaticaly discovered by owncloud. I have to run an occ:files scan to see it.

My cron job is working well and host owncloud on debian.

Any idea ?

Thanks !

**Comment by rullzer** [comment] 2015-12-23 11:04
This is expected behaviour. Besides scanning there is no way for ownCloud to find out there are new files it did not create.

You could setup a cronjob to scan on regular intervals (but that does not really scale if you have a large amount of files and/or users).

Closing as this is not a bug but expected.

**Closed by rullzer** 2015-12-23 11:04 UTC

**Comment by vpo92** [comment] 2015-12-23 11:39
Okay, but I think it was working before ?
I will add the cron job !

Thanks !

**Comment by RealRancor** [comment] 2015-12-23 12:47
@vpo92 Also see this shiny new FAQ at the forums: https://forum.owncloud.org/viewtopic.php?f=17&t=32183
