### ISSUE TITLE
The update was unsuccessful.  (8.2.2 to 9.0.0)

### ISSUE THREAD

**Issue by argv1** [owncloud/core#23175] opened 2016-03-12 11:10 UTC
### Steps to reproduce
1. Uploaded the files in a new folder
2. Rename the old and new installtion
3. Run the update page

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

Got this error message:
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `ocw_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'ocw_notifications' already exists

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
8.2.2 to 9.0.0
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-03-12 11:36
Probably related or even a duplicate of: https://github.com/owncloud/core/issues/22993 (Even if its another table).

**Closed** 2016-03-12 22:21 UTC
