### ISSUE TITLE
Update from Owncloud 7 to 8: The update was unsuccessful.

### ISSUE THREAD

**Issue by honkyponk** [owncloud/core#14302] opened 2015-02-17 16:30 UTC
An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external': SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL

**Comment by LukasReschke** [comment] 2015-02-17 16:32
Duplicate of https://github.com/owncloud/core/issues/13970 -  an interim solution can be found there as well. Thanks for reporting issues back to us!

**Closed** 2015-02-17 16:32 UTC
