### ISSUE TITLE
[Sharing][8.2.6] "Shared by link" icon are not updated properly

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/core#25463] opened 2016-07-13 07:26 UTC
### Expected behaviour
If a file/folder is shared by link a "shared by link" icon should appear associated to it otherwise it should disappear.

### Actual behaviour

![sharedfile](https://cloud.githubusercontent.com/assets/18436398/16794989/2e241f0a-48db-11e6-87c6-575a1767aeff.gif)
![sharedfolder](https://cloud.githubusercontent.com/assets/18436398/16794990/2e25a19a-48db-11e6-96a1-a959b5be31d1.gif)

### Server configuration
**Operating system**: Ubuntu 14.04 LTE

**Web server:** Apache2

**PHP version:** PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46

**ownCloud version:** ownCloud Enterprise Edition 8.2.6 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by PVince81** [comment] 2016-07-13 07:34
Duplicate of https://github.com/owncloud/core/issues/25311

**Closed by PVince81** 2016-07-13 07:34 UTC
Labels: 8.2.6, bug, sev3-medium
