### ISSUE TITLE
File locking enabled, folder rename still successful during upload

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#21480] opened 2016-01-06 10:09 UTC
Hello,

I have verified that my ownCloud 8.2.1 installation is actually successfully using transactional file locking. However, when I try to rename a folder during file upload (in another browser window), it still is successful. When the upload is finished it shows an internal server error as it doesn't find the folder. This doesn't sound normal as according to the documentation it "Locks parent directories so they cannot be renamed during any activity on files inside the directories".

Renaming a folder during download is prevented correctly though and a message is shown saying the folder is locked.

Thanks.

**Comment by karlitschek** [comment] 2016-01-06 13:24
@icewind1991 What is you opinion?

**Comment by PVince81** [comment] 2016-01-07 16:46
The thing here is that when you upload with the web UI, it uses HTTP POST. PHP first uploads the file into a temporary file before giving it to ownCloud. So at this stage, ownCloud doesn't know that an upload is happening and cannot lock the file. It's only when the file reaches ownCloud that locking kicks in, at which time you already renamed the folder.

For a more accurate test, try uploading the file using Webdav instead.

Note that in 9.0 the web UI will also use Webdav for uploads which should make this misunderstanding disappear: https://github.com/owncloud/core/issues/4380

Now the part that isn't nice is that you're getting a 500 instead of a 404 when the upload code finds out that the folder disappeared.

**Comment by PVince81** [comment] 2016-03-02 15:04
Closing as duplicate of webdav upload https://github.com/owncloud/core/issues/4380

**Closed by PVince81** 2016-03-02 15:04 UTC
Labels: bug, feature:locking, triage
