### ISSUE TITLE
Can't sync changes to existing shares after an upgrade to 8.1.3

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20068] opened 2015-10-26 17:04 UTC
### Steps to reproduce
1. Upgrade from OC7.0.10 to OC8.0.8 to OC8.1.3
2. Check the shares sync as expected
3. Check that the share pop-up shows the "delete" check box

### Expected behaviour
Shares should function as expected after an upgrade and users should be able to sync existing shares

### Actual behaviour
After upgrading the environment to 8.1.3 I'm seeing a number of users complaining that they can't sync changes to existing shares. In my own account, when I click on an existing share and look at the cruds permissions a user has I don't see the delete box at all. It's missing entirely. This is for a folder I own so I absolutely have delete access.

If I go into that folder and make a change to it in someway, suddenly the delete checkbox is back and has the value it should have (on or off). The issue isn't present on new shares, just ones that existed before the upgrade. I've done a files:scan on my account and that didn't make any difference. I'm guessing this is related to something in the share table not the filecache.

I'm still troubleshooting the extent of the problem but something is clearly not quite right. It looks like ownCloud doesn't detect that a recipient of a share that does have delete privileges has that ability until something in the share is changed by the owner there by forcing the permissions to be re-evaluated.

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** Percona

**PHP version:** 5.5

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:** Updated from OC7 to OC8.0 to OC8.1

**List of activated apps:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### ownCloud log 

@MorrisJobke @tariqsiddiqui

**Comment by MorrisJobke** [comment] 2015-10-27 08:07
@schiesbn @icewind1991 @PVince81 Where there any cleanup/repair scripts that maybe changed permissions of shares/folders?

**Comment by nickvergessen** [comment] 2015-10-27 09:31
There is only one for reseting the expire date: https://github.com/owncloud/core/blob/master/lib/repair/repairinvalidshares.php

**Comment by PVince81** [comment] 2015-10-27 09:54
That one will be in 8.1.4 / 8.2, not 8.1.3

**Comment by gig13** [comment] 2015-10-27 13:15
This appears to be related to the different filter views.

The delete checkbox appears as normal and selected as it should be when using the normal section of the files list. When you go to "shared with others", that's where the delete check box is always missing. There's something in the js that determines the permissions for shares for that filtered view that's different to the regular view.

**Comment by PVince81** [comment] 2015-10-27 13:21
Yes, it is by design that you cannot delete from there. Some people thought this was the "unshare" button and mistakenly deleted their files, see https://github.com/owncloud/core/issues/11599 and https://github.com/owncloud/core/issues/11599#issuecomment-62744953

**Comment by PVince81** [comment] 2015-10-27 13:21
@jancborchardt I wonder if we should bring back the delete permission now in 8.2/9.0, because the action is in the menu and has the text "Delete". So the user error from https://github.com/owncloud/core/issues/11599 is more unlikely.

**Comment by scolebrook** [comment] 2015-10-27 14:54
It's the delete crud checkbox that's missing and it appears to be related to https://github.com/owncloud/core/pull/12305

That pr make oc believe that the owner doesn't have delete permissions on an item so it doesn't draw the delete button. Or the delete checkbox in the sharing dialog. This would seem like an unintended consequence of the way the delete button was removed.

**Comment by PVince81** [comment] 2015-10-27 14:55
This method was a quickfix, not the cleanest way...

**Comment by MorrisJobke** [comment] 2015-10-27 15:10
> This appears to be related to the different filter views.

Ah...now I understand this issue.

**Comment by MorrisJobke** [comment] 2015-10-27 15:10
> I wonder if we should bring back the delete permission now in 8.2/9.0, because the action is in the menu and has the text "Delete". So the user error from #11599 is more unlikely.

cc @owncloud/designers

**Comment by jancborchardt** [comment] 2015-10-27 21:27
@Pvince81 yeah, I would say we can bring delete back here. Unsharing and delete don't clash anymore.

**Comment by PVince81** [comment] 2015-10-28 09:05
Anyway, I don't see what this has to do with the original issue about not being able to sync changes.
I'll make a separate ticket for the delete action: https://github.com/owncloud/core/issues/20105

**Comment by PVince81** [comment] 2015-12-03 16:41
Maybe try upgrading to 8.1.4 and have the repair step run ?

**Comment by gig13** [comment] 2015-12-03 17:13
@scolebrook 
Is this still an issue -- are you using 8.1.3?

**Comment by scolebrook** [comment] 2015-12-04 03:48
@gig13 @PVince81 The delete checkbox is a separate issue. The syncing shares thing seems to have turned into a couple of more distinct issues as we've received more feedback from users. They seem happy to put up with "broken" rather than report a problem. I don't think they believe that I'm here to make their life better :smile:.

One issue was fixed in 8.1.4. The other has only been reported by a small handful. I'm still trying to gather data and find users who may be affected. If it turns out to be a real issue is should probably be in it's own thread. So I don't see a reason to not close this if everyone else agrees.

**Comment by MorrisJobke** [comment] 2015-12-04 08:42
> One issue was fixed in 8.1.4. The other has only been reported by a small handful. I'm still trying to gather data and find users who may be affected. If it turns out to be a real issue is should probably be in it's own thread. So I don't see a reason to not close this if everyone else agrees.

Okay. Let's close this here and raise new ones once they occur. Thanks for the feedback @scolebrook

**Closed by MorrisJobke** 2015-12-04 08:42 UTC
Labels: blue-ticket, bug, design, feature:sharing, needs info
