### ISSUE TITLE
Trusted domains are not recognized

### ISSUE THREAD

**Issue by cornelius** [owncloud/core#23202] opened 2016-03-13 20:27 UTC
### Steps to reproduce

1. Run ownCloud 9.0.0 in SUSE Studio Test Drive (e.g. from https://susestudio.com/a/TadMax/owncloud-in-a-box-v9-0-0-unstable).
2. Set it up by choosing an admin login and proceeding

In Test Drive the server runs in a virtual machine behind a port forwarding configuration. While the server listens on port 80, HTTP traffic is forwarded from another port from the outside.

### Expected behaviour

Expected is a working instance of ownCloud, which can be accessed without further configuration.

### Actual behaviour

The UI of ownCloud is not accessible. An error message about untrusted domains is shown. It includes a button with a text of something like "Add "node78.susestudio.com:16080" as trusted domain", although this entry already is in the config.php. Clicking the button has no effect.

### Server configuration
**Operating system**:

openSUSE 13.2

**Web server:**

Apache

**Database:**

SQLite

**PHP version:**

5.6.1

**ownCloud version:** (see ownCloud admin page)

9.0.0

**Updated from an older ownCloud or fresh install:**

Fresh install

**Where did you install ownCloud from:**

Tarball from web site built in SUSE Studio

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

Chromium

**Operating system:**

openSUSE Leap 42.1

**Comment by LukasReschke** [comment] 2016-03-13 20:32
Dupe of https://github.com/owncloud/core/pull/23125

**Comment by LukasReschke** [comment] 2016-03-13 20:33
(aka will be fixed in 9.0.1)

**Closed by LukasReschke** 2016-03-13 20:32 UTC
