### ISSUE TITLE
Problems with public shares

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#31454] opened 2018-05-16 07:29 UTC
### Steps to reproduce
1. Click on share button
2. public share
3. incomplete dialog opens and gives this JS error: TypeError: this.$el.find(...).select2 is not a function

### Expected behaviour
Show modal with all options for the public share

### Actual behaviour
Incomplete modal dialog

![grafik](https://user-images.githubusercontent.com/9192953/40102706-81474cbc-58eb-11e8-8bce-387cf552642f.png)

### Server configuration
**Operating system**: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-119-generic x86_64)

**Web server:** Apache Apache/2.4.18

**Database:** Mysql  5.5.59

**PHP version:** 7.0.30

**ownCloud version:** 10.0.8.5

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** via updater app

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'ocxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxx.xxxxxxxxx.xxx',
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
  ),
  'overwritehost' => 'xxxxx.xxxxxxxxx.xxx',
  'overwritewebroot' => '',
  'overwriteprotocol' => 'https',
  'proxy' => 'x.x.x.x:3128',
  'forcessl' => true,
  'check_for_working_webdav' => true,
  'enable_avatars' => true,
  'updatechecker' => true,
  'mail_domain' => 'xxxxxxxxx',
  'mail_from_address' => 'xxxxxx',
  'mail_smtphost' => 'x.x.x.x',
  'datadirectory' => '/data',
  'overwrite.cli.url' => 'https://xxxxx.xxxxxxxxx.xxx',
  'dbtype' => 'mysql',
  'version' => '10.0.8.5',
  'dbname' => 'owncloud',
  'dbhost' => 'x.x.x.x',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxxxx',
  'installed' => true,
  'distinguishedName' => 'OU=Users,OU=xxxxx,DC=xxxxx,DC=xxxxx,DC=de',
  'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ',
  'maintenance' => false,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    7 => 'OC\\Preview\\PDF',
    11 => 'OC\\Preview\\SVG',
    12 => 'OC\\Preview\\TIFF',
  ),
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'smtp',
  'log_type' => 'owncloud',
  'loglevel' => 3,
  'knowledgebaseenabled' => false,
  'log_rotate_size' => 104857600,
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/',
  'activity_expire_days' => 60,
  'updater.secret' => 'xxxxxxxxxxx',
);
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - audioplayer: 2.3.0
  - bookmarks: 0.10.2
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - customgroups: 0.3.6
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.12.0
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 16.0.2
  - impersonate: 0.2.0
  - market: 0.2.4
  - notifications: 0.3.3
  - provisioning_api: 0.5.0
  - qownnotesapi: 17.7.0
  - security: 0.0.2
  - tasks: 0.9.6
  - user_external: 0.4
  - user_ldap: 0.11.0
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 59.0.3 (64-Bit)

**Operating system:** Windows 10 Ultimate 64Bit

#### Web server error log
```
None
```

#### ownCloud log (data/owncloud.log)
```
None
```

#### Browser log
```
TypeError: this.$el.find(...).select2 is not a function
TypeError: this.$dialog is undefined
TypeError: this.$field is undefined

```

**Comment by phil-davis** [comment] 2018-05-16 07:45
It works OK for me on ownCloud 10.0.8 and Firefox.
Did you hard-refresh the browser (ctrl-F5) to make sure all the JavaScript... is the current 10.0.8 code?

**Comment by pierrejochem** [comment] 2018-05-16 07:56
Yes and I have also tried it with Chrome 66.0.3359.181. Same result. Problems with the upgrade so not all is upgraded properly maybe?

**Comment by pierrejochem** [comment] 2018-05-16 08:25
Depends on which button I click, I get also these errors:

TypeError: this.$el.find(...).select2 is not a function => While opening the share dialog
TypeError: this.$dialog is undefined => Cancel Button
TypeError: this.$field is undefined => Share Button

**Comment by phil-davis** [comment] 2018-05-16 08:54
Anyone else got any idea of what might have gone wrong?
Feel free to comment :)

**Comment by gardouille** [comment] 2018-05-17 05:42
Hi,

I just complete an upgrade on our server and got the same issue…

If anything can help, here is it some informations :

### Server configuration

**Operating system:** Linux 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

**Web server:** Apache 2.4.10-10+deb8u12

**Database:** Mysql 5.5.60-0+deb8u1

**PHP version:** 5.6.33+dfsg-0+deb8u1

**ownCloud version:** 10.0.8-1+1.1

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** http://download.owncloud.org/download/repositories/10.0/Debian_8.0/

**Signing status (ownCloud 9.0 and above):**
```
No errors have been found.
```

**The content of config/config.php:**
``` php
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'version' => '10.0.8.5',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.org',
  ),
  'datadirectory' => '/mnt/data',
  'overwrite.cli.url' => 'https://cloud.domain.org',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'logtimezone' => 'Europe/Paris',
  'theme' => '',
  'loglevel' => 4,
  'log_type' => 'syslog',
  'logdateformat' => 'Ymd H:i:s',
  'log_query' => false,
  'log_authfailip' => true,
  'trashbin_retention_obligation' => 'auto',
  'ldapIgnoreNamingRules' => false,
  'ldapUserCleanupInterval' => 1,
  'activity_expire_days' => 14,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'cloud.domain.org',
  'mail_smtphost' => 'smtpint.domain.org',
  'mail_smtpport' => '25',
  'customclient_android' => 'http://f-droid.org/app/com.owncloud.android',
  'maintenance' => false,
  'updatechecker' => false,
  'singleuser' => false,
  'skeletondirectory' => '',
);
```

**List of activated apps:**
```
Enabled:
  - activity: 2.3.6
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - gallery: 16.0.2
  - market: 0.2.4
  - notifications: 0.3.3
  - provisioning_api: 0.5.0
  - templateeditor: 0.3
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0
Disabled:
  - encryption
  - files_videoplayer
  - firstrunwizard
  - systemtags
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration

**Browser:** Firefox 60.0-1

**Operating system:** Debian Sid up-to-date

**Comment by patrickjahns** [comment] 2018-05-17 07:15
@gardouille 

Can you try to enable `systemtags` application - refresh/reload the browser and try again.

**Comment by pierrejochem** [comment] 2018-05-17 07:33
@patrickjahns In my case it is not installed :-|

**Comment by pierrejochem** [comment] 2018-05-17 07:44
I added my config.php content now

**Comment by gardouille** [comment] 2018-05-17 07:48
@patrickjahns Oh perfect, thank you. Quiet strange ?

Just enable it won't work cause it was broken.
I had to remove it, add it, run an occ upgrade then everything seems good.

Thank you for the help ! And sorry for the noise.

**Comment by PVince81** [comment] 2018-05-17 08:29
The bug is that the public link dialog now requires select2. It was already provided by the systemtags app so when that app is disabled that plugin is missing. The proper fix is to have select2 be included by core, not system tags.

Closing as duplicate of https://github.com/owncloud/core/issues/31338

**Closed by PVince81** 2018-05-17 08:29 UTC

**Comment by pierrejochem** [comment] 2018-05-17 08:42
@PVince81 After adding the systemtags app manually, it works! Thank you very much

**Comment by MadriSX** [comment] 2018-05-29 14:49
Is it a bug or it isn´t?

**Comment by PVince81** [comment] 2018-05-29 15:01
it's a bug, fix will be in the next OC version

**Comment by MadriSX** [comment] 2018-05-30 11:04
Ok, thanks for the fix!
