### ISSUE TITLE
Server-to-server: Browser crashes when shared file is deleted

### ISSUE THREAD

**Issue by Tegomena** [owncloud/core#13620] opened 2015-01-23 08:31 UTC
On server1, I'm sharing a file to server2. The file appears in the web interface of server2. When deleting the file on server1, the file still appears on server2. When clicking of the shared file, the browser (tab) crashes (tested on Firefox and IE).

**Comment by MorrisJobke** [comment] 2015-01-23 10:03
@Tegomena It would be nice if you could provide additional information https://github.com/owncloud/core/blob/master/issue_template.md That helps us to find the cause of this problem.

@PVince81 Is this maybe something that will be fixed with your latest PRs in the s2s sharing code?

**Comment by rzg-kaiser** [comment] 2015-01-29 10:45
We (Tegomena is a collegue of mine) had a bit closer look at the problem.

It appears to be a bug in files_texteditor (the file in question was a text file).
I submitted a bug report with a possible fix there:

https://github.com/owncloud/files_texteditor/issues/58

**Comment by MorrisJobke** [comment] 2015-01-29 11:13
@rzg-kaiser Thanks. Then this can be closed.

**Closed by MorrisJobke** 2015-01-29 11:13 UTC
Labels: bug, feature:federated-cloud-sharing, needs info
