### ISSUE TITLE
Private key file name format changed from 7.x to 8.0alpha2

### ISSUE THREAD

**Issue by mwehr** [owncloud/core#13450] opened 2015-01-19 07:51 UTC
Hi,

After upgrading our 7.0.4 instance to the 8.0 alpha2 we got: "Public key exists but private key is missing" for all our users.
It turns out that the private key format changed from 7 -> 8.
In 7.0 the format was {UserId}.private.key
Now in 8.0alpha2 the format changed to  {UserId}.privateKey
I don't know if there is a migration process for renaming, In my case the keys remained in the 7.0 format.
This causes the "Public key exists but private key is missing". After manually renaming the private keys everything went fine :-)

regards

Mario

**Comment by MorrisJobke** [comment] 2015-01-19 08:18
CC @SCHIE

**Comment by MorrisJobke** [comment] 2015-01-19 08:18
cc @schiesbn

**Comment by MorrisJobke** [comment] 2015-01-19 08:24
https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/migration.php#L42 is called on upgrade and it seems to call also the public key rename https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/migration.php#L50

**Comment by PVince81** [comment] 2015-01-19 10:32
Possibly a bug in the migration then. @schiesbn can you have a look ?

@mwehr where was the private key stored before and after ? Did you upgrade from earlier OC 4, OC 5 ? (just in case, maybe the key was named differently)

**Comment by mwehr** [comment] 2015-01-19 12:05
I've updated from 7.0.4 to 8.0.0alpha2
7.0.4 was my initial version.

The upgrade process from 7 -> 8 showed no errors.

The private keys are stored before/after under /data/{UserId}/files_encryption/
Access rights are correct, owner www-data.
I'm using the latest stable wheezy with PHP 5.5.20 from dotdeb.org
I've a migration folder "encryption_migration_backup_2015-01-16_12-39-21" with keys in the 7.x filename format.

Maybe the presence of this folder is a hint for a not clean run of the key migration process?

**Comment by schiesbn** [comment] 2015-01-20 13:41
@mwehr does it happen for all users or just for some users? What user back-end do you use. The native ownCloud user management, LDAP or something different?

**Comment by mwehr** [comment] 2015-01-20 17:34
It happens for all users. None of the private key files were changed.
I'm using LDAP for user management.

**Comment by DeepDiver1975** [comment] 2015-01-21 10:07
hmmm - @blizzz can you test this encryption key migration with LDAP? THX

**Comment by blizzz** [comment] 2015-01-21 10:51
@mwehr could you also please post your LDAP configuration? You can get it easy from command line running ```./occ ldap:show-config```

**Comment by blizzz** [comment] 2015-01-21 12:13
@schiesbn at this point of time https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/migration.php#L64 external user backends are not loaded. Returned users are always and only local.

Also in the later steps i wonder whether everything will work as expected. My feeling is that setupFS($user) will not to be done so that the paths to the user folders are correct.

**Comment by blizzz** [comment] 2015-01-21 12:17
(That said i could reproduce it. I can follow up there after lunch.)

**Comment by mwehr** [comment] 2015-01-22 08:27
@blizz are you interested on some specific ldap config properties?

**Comment by blizzz** [comment] 2015-01-22 09:48
@mwehr especially username and home folder settings. But i am working on a fix anyway and try to cover all setups in this regard.

**Comment by blizzz** [comment] 2015-01-22 10:22
@schiesbn is it necessary to have the migration done for every single user at once on upgrade?

**Comment by DeepDiver1975** [comment] 2015-01-22 11:01
maybe we move this to a repair step? 
Are auth apps already loaded when running repair steps?

Maybe a generally approach to handle migrations as they cane be executed again?

summoning repair step master @PVince81

**Comment by DeepDiver1975** [comment] 2015-01-22 11:03
> @schiesbn is it necessary to have the migration done for every single user at once on upgrade?

thinking about very big installations this might take a while - furthermore we can run into scenarios where only a partial user set is available? Hence the idea of the repair step ...

**Comment by blizzz** [comment] 2015-01-22 12:48
Also in maintenance mode, as when apps are upgraded, we don't allow apps to be loaded. We would need to circumvent it for auth apps… per se not a big issue, alas i am not sure whether this would bring back other faulty behaviour?

**Comment by DeepDiver1975** [comment] 2015-01-22 13:17
did you follow the path discussed yesterday? 
1.) upgrade auth apps
2.) load auth apps
3.) upgrade all other apps

Did additional issue arise?
Which?

THX

**Comment by blizzz** [comment] 2015-01-22 13:21
@DeepDiver1975 

yes. as said, first that apps do not load in maintenance mode. Second, if I get around this, LDAP  does not return all users, but only up to the server limit. Feels like a regression, I test this. Furthermore i think the file system will be needed to setup for each user, only i did not confirm it yet.

**Comment by DeepDiver1975** [comment] 2015-01-22 13:27
@schiesbn I'd vote for moving this key migration into an lazy mode - e.g. login hook of the user and in addition we add a repair step which can be executed with the console.

The current approach will fail with hugh amounts of users and in cases where we require external user sources

**Comment by DeepDiver1975** [comment] 2015-01-22 13:28
I will come up with a POC-PR ...

**Comment by PVince81** [comment] 2015-01-22 13:56
Could the app itself call the repair step from it's "appinfo/update.php" code ?
Because after the core server has finished its upgrade, it will update the apps.

**Comment by DeepDiver1975** [comment] 2015-01-29 09:32
@mwehr so we have a console command to be used for migrating the keys for ldap users - feel free to use this command to fix your installation. Thanks a lot!

```sh
$ ./occ encryption:migrate-keys

**Closed by DeepDiver1975** 2015-01-29 09:32 UTC
Labels: app:files_encryption, bug, ownCloud 8.0 Showstoppers

**Comment by mwehr** [comment] 2015-01-29 10:21
Perfect thx!
