### ISSUE TITLE
Sharing settings need to be revisited

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22674] opened 2016-02-26 11:42 UTC
We have a bunch of settings around sharing on the admin page atm.

And the most important question is, whether `Allow apps to use the Share API` is really what we want to have :question: 

Should that option prevent sharing a calendar, addressbook, etc? Or should this setting state that it's only about the file-sharing API?

@DeepDiver1975 @schiesbn @rullzer @karlitschek

**Comment by karlitschek** [comment] 2016-02-26 17:39
agreed. maybe it is time to remove this setting completely. If you don't want sharing then just disable the sharing app. What do you think @MTRichards

**Comment by MTRichards** [comment] 2016-02-26 18:11
I have often thought about that feature. I know when I disable it, sharing doesn't work. But if that is all it does, then disabling the app is fine for me.

The one thing I wonder is if that option was supposed to disable the sharing API, for things like Mobile and Desktop, which would make sense to me.

**Comment by nickvergessen** [comment] 2016-02-29 08:18
> The one thing I wonder is if that option was supposed to disable the sharing API, for things like Mobile and Desktop, which would make sense to me.

Well they can't do ownCloud sharing when the app is not there either. And when you mean sharing via whatsapp or whatever, no, that does not check this setting.

**Comment by PVince81** [comment] 2016-10-10 14:57
Closing as duplicate of https://github.com/owncloud/core/issues/17863

**Closed by PVince81** 2016-10-10 14:57 UTC
Labels: discussion, feature:sharing, technical debt
