### ISSUE TITLE
Cannot re-share: "unable to get mount for shared storage"

### ISSUE THREAD

**Issue by milgner** [owncloud/core#12857] opened 2014-12-15 15:07 UTC
### Expected behaviour:

If user A re-shares a folder X for user B, folder X should be accessible for that second user.

### Observed behaviour:

The folder does not become visible. Trying to open it in the browser navigates back to their home folder.

### Server configuration:

**Operating system**: Debian Wheezy

**Web server:** Apache 2.2.22 

**Database:** PostgreSQL 9.3

**PHP version:** PHP 5.4.4 with XCache v2.0.0

**OwnCloud version:** 7.0.4, updated from previous versions, no additional apps.

Config file:

```php
$CONFIG = array (
  'instanceid' => 'ocd6900105c4',
  'passwordsalt' => '************',
  'trusted_domains' => 
  array (
    0 => 'mydomain.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '************',
  'dbpassword' => '************',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'secret' => '************',
);
```

### Logs

*No error in Apache logs*

#### OwnCloud log:

    {"app":"files_sharing","message":"Unable to get mount for shared storage '1' user 'user_A'","level":3,"time":"2014-12-15T14:54:25+00:00"}

### Possibly related

Issue #12801
[Forum Post](http://forum.owncloud.org/viewtopic.php?t=23117&p=70848)

**Comment by milgner** [comment] 2015-01-05 15:57
After further investigation I can confirm that this is specific to re-sharing. Sharing the folder from the original user does work as expected.

**Comment by PVince81** [comment] 2015-01-20 12:31
@milgner does "user1" receive the share over a group share ?

Possibly a duplicate of https://github.com/owncloud/core/issues/13361
You could try applying the patch from https://github.com/owncloud/core/pull/13423

**Comment by milgner** [comment] 2015-01-20 12:39
Yes, it's indeed a group share. I'll try applying the patch, thanks for the feedback!

**Comment by PVince81** [comment] 2015-07-31 15:59
Please try again with 7.0.7 or 8.0.5 which should have the patch.
Feel free to reopen if the problem persists on these versions.
Thanks.

**Closed by PVince81** 2015-07-31 15:59 UTC
Labels: bug
