### ISSUE TITLE
admin page (internal server error) -> owncloud.log 

### ISSUE THREAD

**Issue by abrumloop** [owncloud/core#13978] opened 2015-02-09 11:54 UTC
Hi,

i did a fresh install (owncloud 8, php 5.5 and mysql-backend). Everything works well, execpt that it is not possible to access the admin page. Everything else works fine (including adding and removing new users).

Anyone else with this problem? With Owncloud 7 everything works great.

Unfortunately i have no access to apache´s logfiles. 

Thanks alot

EDIT: Problem is owncloud.log. The file increases up to 64MB(!), still no solution.
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"<IP-ADRESS>","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:08:50+00:00"}

**Comment by karlitschek** [comment] 2015-02-09 13:50
Can you post a full bug report using the issue template please?
https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by abrumloop** [comment] 2015-02-09 14:19
Sure, sorry about that. this is my first bugreport. I hope i dont miss anything.

### Steps to reproduce
1. do a fresh Owncloud 8 install, admin page is accessable
2. do something
3. after some time, admin page is not available 
4. rename data/owncloud.log to something else (or delete), everthing works fine
5. do something
6. admin page is not available (internal server error)

### Expected behaviour
admin page should be available

### Actual behaviour
internal server error while loading admin page. Everything else works fine. I think its caused through data/owncloud.log. The file increases rapidly up to 64MB(!). if i rename owncloud.log, everything works like it should (but owncloud.log still increases rapidly)

### Server configuration
**Operating system**:

**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.5 
**ownCloud version:** (see ownCloud admin page)
8.0

**Updated from an older ownCloud or fresh install:**
fresh install 

**List of activated apps:**
contacts, kalender, share

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oczxzjxdmzrh',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'coffeinflash.de',
  ),
  'datadirectory' => '/mnt/webr/c3/66/54458666/htdocs/owncloud/data',
  'overwrite.cli.url' => 'https://<url>/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'DB2016509',
  'dbhost' => 'rdbms.strato.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'U2016509',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => 1,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'oc',
  'mail_smtpmode' => 'php',
  'mail_domain' => '',
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
./.
**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
firefox/ chrome

**Operating system:**
fedora 21

### Logs
#### Web server error log

Insert your webserver log here
not available, i dont have access to the server log sorry

#### ownCloud log (data/owncloud.log)
Insert your ownCloud log here
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}
{"reqId":"15f07f28ededa93b31810c14e80eb0d2","remoteAddr":"178.202.129.107","app":"PHP","message":"readdir() expects parameter 1 to be resource, boolean given at \/mnt\/webr\/c3\/66\/54458666\/htdocs\/owncloud\/lib\/private\/tempmanager.php#135","level":3,"time":"2015-02-09T12:07:20+00:00"}

**Comment by RealRancor** [comment] 2015-02-09 17:12
Hi,

duplicate of: https://github.com/owncloud/core/issues/13953

**Comment by abrumloop** [comment] 2015-02-09 17:42
confirmed, edititing tempmanger works. Thank you.

**Comment by RealRancor** [comment] 2015-02-09 18:32
@abrumloop 
Feel free to close the issue then. I don't have the permissions to do this.

**Closed** 2015-02-09 18:40 UTC
Labels: bug
