### ISSUE TITLE
Log spammed with "open_basedir restriction in effect"

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#25353] opened 2016-07-04 20:57 UTC
### Steps to reproduce
1. upgrade from oc 8 to oc 9
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
my log file is spammed every few seconds with

```
{"reqId":"ihNHXXUTTq3lyJ42GH7a","remoteAddr":"xx.xx.xx.xx","app":"PHP","message":"is_readable(): open_basedir restriction in effect. File(\/dev\/urandom) is not within the allowed path(s): (\/var\/www\/xxx\/htdocs:\/var\/www\/xxx\/apps:\/var\/www\/xxx\/priv:\/var\/www\/xxx\/tmp:\/usr\/share\/pear:\/usr\/share\/php:\/tmp) at \/var\/www\/xxx\/htdocs\/xxx\/owncloud\/3rdparty\/paragonie\/random_compat\/lib\/random.php#66","level":3,"time":"2016-07-04T20:34:14+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xxx"}
```

### Server configuration
**Operating system**: debian

**Web server:** apache

**Database:** mysql 5.5

**PHP version:** 5.6

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** from 8

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
News, Mail, Calendar, Contacts, Files, Activity
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

**Comment by RealRancor** [comment] 2016-07-05 04:01
Duplicate of https://github.com/owncloud/core/issues/24905

**Closed** 2016-07-05 08:27 UTC
