### ISSUE TITLE
IE Language Pack Support

### ISSUE THREAD

**Issue by PluueeR** [owncloud/core#23842] opened 2016-04-07 13:36 UTC
I'm experiencing the exact same as #1410 with ownCloud 9 . We use Windows 2008 R2 with the Dutch Language Pack installed:

Mozilla Firefox 45 (Dutch): Works fine. Language detection as well as setting default_language in config.php.
Internet Explorer 11: Language detection works partitally (see screenshot). Same goes fot setting default_language in config.php.

I also Internet Explorer 11 (English) on Windows 8 (English). Setting default_language in config.php works fine. Language is detected as English.

PS: I also commented this in #1410.

![knipsel](https://cloud.githubusercontent.com/assets/16321232/14352748/58846ce2-fcd6-11e5-8a73-462bba5e51fd.PNG)
h. Which seems to be fine.

**Comment by LukasReschke** [comment] 2016-04-07 16:22
Please fill out the issue template. THX.

Also add stuff like the the request headers: http://requestb.in/

**Comment by PluueeR** [comment] 2016-04-08 08:47
1. Start Internet Explorer.
2. Login to ownCloud.

### Expected behaviour
Language should be detected as Dutch and all should be translated.

### Actual behaviour
ownCloud is partially translated. Half english/half dutch. See screenshot.

### Server configuration
Debian Linux unstable.

Apache 2.4.18

MySQL 5.6.21

PHP 5.6.19

ownCloud 9.0.0

Upgrade from 8.2.3

Installed from tarball (manual update).

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**
Enabled:
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - activity
  - encryption
  - external
  - files_external
  - user_external

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc3d9d13d911",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/cloudtest.alkmaar.intern\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "installed": true,
        "dbname": "owncloudtest",
        "dbhost": "alkmys01",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "30, auto",
        "share_folder": "\/Shared",
        "loglevel": "0",
        "trusted_domains": [
            "cloudtest.alkmaar.intern",
            "cloudtest"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, ActiveDirectory.

#### LDAP configuration (delete this part if not used)
+-------------------------------+------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                |
| hasPagedResultSupport         |                                                                                                |
| homeFolderNamingRule          |                                                                                                |
| lastJpegPhotoLookup           | 0                                                                                              |
| ldapAgentName                 | cn=***,ou=***,ou=***,dc=***,dc=***                                                             |
| ldapAgentPassword             | ***                                                                                            |
| ldapAttributesForGroupSearch  |                                                                                                |
| ldapAttributesForUserSearch   |                                                                                                |
| ldapBackupHost                |                                                                                                |
| ldapBackupPort                |                                                                                                |
| ldapBase                      | dc=***,dc=***                                                                                  |
| ldapBaseGroups                | dc=***,dc=***;;                                                                                | 
| ldapBaseUsers                 | ou=***,dc=***,dc=***;;                                                                         |
| ldapCacheTTL                  | 600                                                                                            |
| ldapConfigurationActive       | 1                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                |
| ldapEmailAttribute            |                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                              |
| ldapExpertUUIDGroupAttr       |                                                                                                |
| ldapExpertUUIDUserAttr        |                                                                                                |
| ldapExpertUsernameAttr        |                                                                                                |
| ldapGroupDisplayName          | cn                                                                                             |
| ldapGroupFilter               |                                                                                                |
| ldapGroupFilterGroups         |                                                                                                |
| ldapGroupFilterMode           | 0                                                                                              |
| ldapGroupFilterObjectclass    |                                                                                                |
| ldapGroupMemberAssocAttr      | member                                                                                         |
| ldapHost                      | ldaps://***.***.***                                                                            |
| ldapIgnoreNamingRules         |                                                                                                |
| ldapLoginFilter               | (&(memberOf:1.2.840.113556.1.4.1941:=CN=***,OU=***,OU=***,DC=***,DC=***)(sAMAccountName=%uid)) |
| ldapLoginFilterAttributes     | sAMAccountName                                                                                 |
| ldapLoginFilterEmail          | 0                                                                                              |
| ldapLoginFilterMode           | 1                                                                                              |
| ldapLoginFilterUsername       | 0                                                                                              |
| ldapNestedGroups              | 0                                                                                              |
| ldapOverrideMainServer        | 0                                                                                              |
| ldapPagingSize                | 500                                                                                            |
| ldapPort                      | 636                                                                                            |
| ldapQuotaAttribute            |                                                                                                |
| ldapQuotaDefault              |                                                                                                |
| ldapTLS                       | 0                                                                                              |
| ldapUserDisplayName           | displayname                                                                                    |
| ldapUserDisplayName2          |                                                                                                |
| ldapUserFilter                | (|(objectclass=user))                                                                          |
| ldapUserFilterGroups          |                                                                                                |
| ldapUserFilterMode            | 0                                                                                              |
| ldapUserFilterObjectclass     | user                                                                                           |
| ldapUuidGroupAttribute        | auto                                                                                           |
| ldapUuidUserAttribute         | auto                                                                                           |
| turnOffCertCheck              | 0                                                                                              |
| useMemberOfToDetectMembership | 1                                                                                              |
+-------------------------------+------------------------------------------------------------------------------------------------+

### Client configuration
Microsoft Internet Explorer 11

Microsoft Windows Server 2008 R2 with Dutch Language Pack

### Logs
#### Web server error log
[Fri Apr 08 06:25:02.814903 2016] [mpm_prefork:notice] [pid 2649] AH00163: Apache/2.4.18 (Debian) OpenSSL/1.0.2g configured -- resuming normal operations
[Fri Apr 08 06:25:02.814926 2016] [core:notice] [pid 2649] AH00094: Command line: '/usr/sbin/apache2'

#### ownCloud log (data/owncloud.log)
When switching loglevel 1, nothing is being added to owncloud.log while logging in to ownCloud.

#### Browser log
```
Insert your browser log here, this could for example include:

[Netwerkgegevens.txt](https://github.com/owncloud/core/files/209869/Netwerkgegevens.txt)

http://requestb.in/udunjbud?inspect

**Comment by nickvergessen** [comment] 2016-04-11 13:17
Well if the translators didn't translate the string yet, it falls back to english
Dutch is currently at 98% with ~70 strings missing, so that might be the issue.
Jump onto transifex if you want to help out: https://www.transifex.com/owncloud-org/owncloud/language/nl/

**Comment by PluueeR** [comment] 2016-04-11 13:39
Huuh, this shouldn't be closed!

As I described in the opening post, it works fine in Mozilla Firefox. all strings are translated. But not in IE with Dutch Language Pack.

**Comment by nickvergessen** [comment] 2016-04-11 14:27
Right, sorry I misread

**Comment by nickvergessen** [comment] 2016-04-21 10:46
Can you try 9.0.1 with https://github.com/owncloud/core/pull/23541

**Comment by PluueeR** [comment] 2016-04-21 11:05
I will try on our testing environment. Keep you posted.

**Comment by PluueeR** [comment] 2016-04-21 13:23
Problem seems to be solved. Nice!

**Comment by PluueeR** [comment] 2016-05-03 09:11
Sorry, but this problem still exists. I also installed ownCloud 8.2.3 to do some side by side comparision. Seems ownCloud 8.2.3 is doing everything as expected:

```
ownCloud 8.2.3
								

Windows 2008 R2 Dutch Language pack - Firefox 45 Dutch

                                      | Login screen | Interface
--------------------------------------+--------------+----------
Default                               | Dutch        | Dutch
Personal -> Language -> French        | Dutch        | French
config.php 'default language' => 'de' | German       | German


Windows 2008 R2 Dutch Language pack - Internet Explorer 11

                                      | Login screen | Interface
--------------------------------------+--------------+----------
Default                               | Dutch        | Dutch
Personal -> Language -> French        | Dutch        | French
config.php 'default language' => 'de' | German       | German


Windows 10 Professional English - Edge 25

                                      | Login screen | Interface
--------------------------------------+--------------+----------
Default                               | Dutch        | Dutch
Personal -> Language -> French        | Dutch        | French
config.php 'default language' => 'de' | German       | German



ownCloud 9.0.1


Windows 2008 R2 Dutch Language pack - Firefox 45 Dutch

                                      | Login screen | Interface
--------------------------------------+--------------+----------
Default                               | Dutch        | Dutch
Personal -> Language -> French        | Dutch        | French/parts in Dutch*
config.php 'default language' => 'de' | German       | German


Windows 2008 R2 Dutch Language pack - Internet Explorer 11

                                      | Login screen | Interface
--------------------------------------+--------------+----------
Default                               | English      | English/parts in Dutch*
Personal -> Language -> French        | English      | French/parts in Dutch*
config.php 'default language' => 'de' | English      | English/parts in German*


Windows 10 Professional English - Edge 25

                                      | Login screen | Interface
--------------------------------------+--------------+-------------------------
Default                               | English      | English/parts in Dutch*
Personal -> Language -> French        | English      | French/parts in Dutch*
config.php 'default language' => 'de' | English      | English/parts in German*



* Shared with you, Shared with others, Shared by link, Deleted files

```

Has language handling changed since ownCloud 9? I can't seem to find `$_SERVER['HTTP_ACCEPT_LANGUAGE']` in any of the files.

**Comment by nickvergessen** [comment] 2016-05-03 09:14
Duplicate of https://github.com/owncloud/core/issues/24270

**Closed by nickvergessen** 2016-05-03 09:14 UTC
Labels: feature:l10n
