### ISSUE TITLE
Users cannot set email address on personal settings

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27667] opened 2017-04-18 16:54 UTC
### Steps to reproduce

1. Create a user "user1".
2. As "user1" go to settings personal/general.
3. Set email address.
4. Refresh page.

### Expected behaviour
"user1" sets an email address correctly.

### Actual behaviour
"user1" email address is ignored.

![error_email_personal_settings](https://cloud.githubusercontent.com/assets/9048796/25142761/62dc3f70-2468-11e7-9e7a-579218ffb4bf.gif)

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```
```

**Comment by PVince81** [comment] 2017-04-18 19:25
It's only saved once you confirm your email...

This also bothers me a bit.

@imujjwal96 another case for later

moving this to 10.0.1

**Comment by c-holtermann** [comment] 2017-11-07 15:23
At the moment I can't change an email at all because even if I go to the link of the validation email which gets sent correctly then email address doesn't get changed.

**Comment by jdopson** [comment] 2017-11-17 16:27
I'm also having this issue with 10.0.3 and 10.0.4.  It affects both internal and external users.  The admin user is able to change their password but no one else.

**Comment by dekompeti** [comment] 2017-12-25 19:58
I have the same problem with Owncloud 10.0.3.
Owncloud will fix this problem with an 10.0.5 upgrade?

Regards,

**Comment by vborges87** [comment] 2017-12-28 18:59
I have the same problem... Owncloud 10.0.3.

**Comment by PVince81** [comment] 2018-01-08 11:40
@jdopson @vborges87 can you clarify "same problem" ? Do you mean the one from https://github.com/owncloud/core/issues/27667#issuecomment-342516272 about the validation email not saving the confirmed email address ?

It would be good if you guys provide more details about your setup and the logs. This feature works correctly here after the confirmation email. I wonder if there are special characters in your email address that might make the process fail ? The logs might show more information.

**Comment by Taz0** [comment] 2018-01-14 20:06
I have the same problem too. Only the admin user is working properly. The rest of the users are receiving the email, and after clicking the link, the success message is shown (email changed successfully or something like that) but the email field is still blank (in the web interface and NULL in the database).

We have OC 10.0.4, MySQL 5.7.20, Nginx (with SSL) and Redis 4.0.6 on Docker.

Can't find anything at the logs.

Best,

**Comment by PVince81** [comment] 2018-01-15 11:28
Are the users with problems local DB users or are they LDAP users or users from another backend ? Not sure if it's possible to set email to such users that way.

**Comment by Taz0** [comment] 2018-01-15 11:47
They are regular local DB users. In fact, if we manually change the email from the 'account' table on the database it works perfectly.

**Comment by koenlek** [comment] 2018-01-22 07:25
We are experiencing the exact same issue on two ownCloud 10.0.4 installations (I manage it for two different projects). The instances run with docker-compose based on `owncloud/server:10.0.4`, `webhippie/mariadb:latest`, and `webhippie/redis:latest` . Previously, they were manual installations that I migrated a couple of months ago into docker.

`docker-compose logs --tail 100 -f owncloud_main` doesn't show any kind of error. It shows these lines when someone clicked the confirmation e-mail:

```
owncloud_main_1   | 172.19.0.2 - - [22/Jan/2018:07:14:41 +0000] "GET /settings/mailaddress/change/<some_hash>/<username> HTTP/1.1" 303 792 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
owncloud_main_1   | 172.19.0.2 - - [22/Jan/2018:07:14:41 +0000] "GET /settings/personal?changestatus=success HTTP/1.1" 200 7235 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
```

**Comment by PVince81** [comment] 2018-01-26 09:06
Confirmed broken on 10.0.0

**Comment by PVince81** [comment] 2018-01-26 09:23
Found the breaking commit b73b488cc91803d2236a9f1ff7ac7d78b6b1b1fa from https://github.com/owncloud/core/pull/28351.

@sharidas can you have a look ?

**Comment by sharidas** [comment] 2018-02-22 12:36
Close the ticket as the changes are merged to master and stable10 branches respectively.

**Closed by sharidas** 2018-02-22 12:36 UTC
Labels: bug, regression, sev2-high
