### ISSUE TITLE
Switching between file list and gallery view not working in 9.0.0

### ISSUE THREAD

**Issue by thejabok** [owncloud/core#23178] opened 2016-03-12 12:52 UTC
### Steps to reproduce
1. In Files app, navigate to folder containing images in Web GUI
2. After file list has loaded, click on "gallery" icon on top right

### Expected behaviour
GUI should switch to gallery view and display images in folder as thumbnails.

### Actual behaviour
When a certain number of images in the folder is exceeded (in my case ~10), the file app reloads the page and shows file list view again.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6.14-0+deb8u1

**ownCloud version:** 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Where did you install ownCloud from:** Manually as described in admin manual

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- lib/private/setup.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => b00eac79b2db577d523f56b683399505294611d99fbc9d23c2776ad8254213cddf4ee50a1314a944f07e9aed6b69aeeb02f390b1a8daacbddccef4f996f21316
                        )

                    [lib/private/setup.php] => Array
                        (
                            [expected] => 32930461d746dad2513a53a4962b25cc53c2575b0df7ebb8f59e4c7f2297301db1cf031969708c3605ee2b8515d65521e3a2d3b31facc12158bbc0c8dbc60cff
                            [current] => f6b73a92c6edb1ba28c3d7014ba6f14e9512e7a0fb92a1e29836d1c4d0880c3166994daa4588d070d974838a1860f86fa8d2fcdcfe7835c4a09f9d295a18d71c
                        )

                )

        )

)

```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - systemtags: 0.2
Disabled:
  - encryption
  - external
  - files_external
  - mail
  - notifications
  - provisioning_api
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc8aakgw49m2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/oc-data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": 30,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "asset-pipeline.enabled": false,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "ldapIgnoreNamingRules": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45.0

**Operating system:** Windows 7

#### Web server error log
```
N/A
```

#### ownCloud log (data/owncloud.log)
```
N/A
```

**Comment by RealRancor** [comment] 2016-03-12 13:10
AFAIK this "Gallery" icon is provided by the Gallery app so its probably better to close here and re-open in: https://github.com/owncloud/gallery/issues

**Comment by thejabok** [comment] 2016-03-12 13:15
Thanks, @RealRancor, will do!

**Comment by RealRancor** [comment] 2016-03-12 15:56
Ref: https://github.com/owncloud/gallery/issues/591

**Comment by thejabok** [comment] 2016-03-14 14:29
@RealRancor, @oparoz, reopening this issue here because it seems to be a bug in core. The described problem occurs not only when trying to switch between file list view and gallery view, but also sporadically when trying to switch between admin page and apps page before Security & Setup Warnings have finished loading. Instead of apps administration page opening, admin page just reloads. Happy to provide any information necessary, but the issue is difficult to reproduce.

**Comment by oparoz** [comment] 2016-03-14 14:41
We've tried to pinpoint what exactly the problem is, but have been unsuccessful so far.

Some pre-conditions:

* Low powered hardware (Pi 2) or some high latency network perhaps?
* Switching away from the app while some AJAX requests are still being processed. I've noticed that if a notification shows up after I've tried to move away from Gallery, then my request gets cancelled. @thejabok has noticed that if tried top switch to the Gallery "view" from a folder after having uploaded some images, but before getting all the previews back then that request would get cancelled

@PVince81 @MorrisJobke - This makes me think about some recent work done to redirect requests which were failing (or something like that). Or it call be that the callbacks prevent the original call to switch to a different app.

**Comment by PVince81** [comment] 2016-03-21 13:26
Might need to add code to auto-cancel ajax calls. Strange thing that we even need to do that.

**Comment by oparoz** [comment] 2016-03-21 18:24
I've just tried on slow hardware, but haven't been able to experience your issue. I'm able to switch after uploading files.
It must be something specific like the cron or storagestats.

**Comment by thejabok** [comment] 2016-03-22 13:07
@oparoz Try navigating to a folder that already exists and that has a lot of images in it with no rendered thumbnails. That's when I experience the error. After upload, it works alright.

**Comment by oparoz** [comment] 2016-03-22 13:28
@thejabok - That's what I did. My top folder has a few sub-folders one of them is full of JPGs which can't get rendered.
I opened that folder, saw a few requests to generate previews and pressed the button to switch.
It must be a timing issue. A new request is made which requires the URL to belong to Files

**Comment by oparoz** [comment] 2016-03-22 15:12
@thejabok - Take a look at https://github.com/owncloud/core/issues/23482#issuecomment-199858330

**Comment by PVince81** [comment] 2016-03-22 16:04
Closing in favor of https://github.com/owncloud/core/issues/23482

**Closed by PVince81** 2016-03-22 16:04 UTC
Labels: bug, sev3-medium

**Comment by thejabok** [comment] 2016-03-22 17:17
@oparoz @PVince81 Thanks, I'll try that when I get home!
