### ISSUE TITLE
Call to a member function getValue() on a non-object

### ISSUE THREAD

**Issue by babelouest** [owncloud/core#12300] opened 2014-11-19 14:02 UTC
I have 2 owncloud instances, one for the calendar/contacts and one to access network files.
When I updated from 7.0.2 to 7.0.3, it went ok on the first instance, but not on the second one. The main difference is that the broken owncloud instance is hosted on a nfs drive.

I had similar issues with the master branch a few weeks ago, I fixed it by moving the owncloud folder from the nfs drive to a local drive.

So now, when I try to access the owncloud instance that is hosted on the nfs drive, I have a blank page after a few minutes of loading, then I see the following error on the apache error logs:
`Call to a member function getValue() on a non-object in /[nfs-drive]/owncloud/lib/private/legacy/config.php on line 52`
I run both owncloud instances on a debian stable, with apache and php5, and a mysql database.

I had similar problems lately on another project, due to the presence of a sqlite3 database file on a network drive, sqlite3 library doesn't like it at all. I don't know if that's the problem.

**Comment by nickvergessen** [comment] 2015-03-24 12:26
@MorrisJobke legacy/config

**Comment by MorrisJobke** [comment] 2015-03-24 12:45
@LukasReschke @babelouest So the actual problem here is not really the config, but the file locking.

**Comment by babelouest** [comment] 2015-03-25 00:50
@MorrisJobke , that's correct, The problem in my case is the file locking problem due to owncloud files located in an NFS drive.

**Comment by dvwallin** [comment] 2015-05-19 16:51
Any progress on this? Im having the same issues.

**Comment by babelouest** [comment] 2015-05-20 11:18
@dvwallin , not on my side, I moved owncloud core files to /usr/local to prevent the problem

**Comment by RandolfCarter** [comment] 2015-05-20 21:06
Just got basically the same error when trying to upgrade from 8.0.3 to 8.1.0beta2 (PHP Fatal error:  Call to a member function getValue() on a non-object in /home/bfroehler/htdocs/owncloud/lib/private/legacy/config.php on line 60) - for me it was caused by a wrong ownership of the config.php file.

**Comment by PVince81** [comment] 2015-11-06 12:29
Is this still an issue with 8.1.4 or 8.2.0 ?

**Comment by babelouest** [comment] 2015-11-06 16:22
AFAIK, it's no longer an issue, this was fixed on contacts app.

**Comment by PVince81** [comment] 2015-11-06 16:27
I'll close this then. If anyone still gets this issue on recent OC versions feel free to reopen :smile:

**Closed by PVince81** 2015-11-06 16:27 UTC
Labels: bug

**Comment by babelouest** [comment] 2015-11-06 21:00
:+1:
