### ISSUE TITLE
MySQL/MariaDB syntax error after 8.0 update

### ISSUE THREAD

**Issue by deg0nz** [owncloud/core#14355] opened 2015-02-19 00:03 UTC
I updated my OwnCloud installation on my ubuntu server.
After the update from ubuntu 14.04 to 14.10 I entered the new repository entry to /etc/apt/sources.list.d/owncloud.list and updated the owncloud package via apt. (maybe that was wrong?!)

When I start the update-process via the webinterface, I get the following error:

An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_60ugir47tgmz6 RENAME INDEX appconfig_config_key_index TO oc_5gh51xk4XXXX': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_5gh51xk4XXXX' at line 1

MariaDB and apache are the newest available versions.

note: the XXXXes are for anonymization, if you need them, please tell me. (but I dont think so)

**Comment by LukasReschke** [comment] 2015-02-19 00:10
Duplicate of https://github.com/owncloud/core/issues/14003 - thanks for reporting issues back!

The linked issue contains a hotfix as well.

**Closed by LukasReschke** 2015-02-19 00:10 UTC
