### ISSUE TITLE
"App does not provide an info.xml file" After fresh installation of OC 8.0.2

### ISSUE THREAD

**Issue by nsediq** [owncloud/core#14963] opened 2015-03-17 15:28 UTC
i install a fresh OC 8.0.2, and when decide to enable Calender or any application in recommended list the "App does not provide an info.xml file" error ocurrend.

i ask my server administrator and he said curl, zip and xml packages are installed.

**Comment by RealRancor** [comment] 2015-03-17 15:39
Hi,

did you had a look at the search engine in this repos? Currently don't have time to search for issues but there are at least two issues available for this.

**Comment by nsediq** [comment] 2015-03-17 16:20
after some search and speak with server admin, they said its will be ok if in line 73 "lib/private/httphelper.php" add
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
and SSL be inactive.

**Comment by RealRancor** [comment] 2015-03-17 16:23
Hi,

they/you should better import the owncloud.com cert or even upgrade to a recent distro shipping the correct certs.

**Comment by nsediq** [comment] 2015-03-17 16:49
Hello
in this issue said that the problem maybe is for curl version.
https://github.com/owncloud/core/issues/14840#issuecomment-81858769

**Comment by karlitschek** [comment] 2015-03-17 17:58
@LukasReschke Do you have any creative idea how to improve the user experience here? Can we detect this somehow and add a better error message? I´m not sure but we get a ton of error messages with the current behavior.

**Comment by LukasReschke** [comment] 2015-03-17 17:59
> @LukasReschke Do you have any creative idea how to improve the user experience here? Can we detect this somehow and add a better error message? I´m not sure but we get a ton of error messages with the current behavior.

ownCloud Proxy and SSL support is completely broken. Nothing we can really do more except a complete rewrite. Sorry. – It's not only broken in regard to the AppStore but in A LOT of other places as well.

Luckily I spent yesterday and today to rewrite that whole HTTP client handling: https://github.com/owncloud/core/pull/14913

That should help… – But then again only 8.1 ;-)

**Comment by LukasReschke** [comment] 2015-03-17 18:00
For ownCloud 8 I can add a somewhat "easier to understand" warning, but that would be only a hack and not really fix the underlying problem… Will think how to do this though.

**Comment by karlitschek** [comment] 2015-03-17 18:01
@LukasReschke Hmm. This sucks. Maybe we should then switch back to http or disable cert checks for 8.0.x Because the current behavior really sucks for a lot of users.

**Comment by karlitschek** [comment] 2015-03-17 18:01
what do you think?

**Comment by LukasReschke** [comment] 2015-03-17 18:03
If it is only the appstore problem I can add yet another gigantic hack under the premise that we fix it properly anyways for 8.1… It's broken in a lot of other places again as I stated :see_no_evil:

**Comment by LukasReschke** [comment] 2015-03-17 18:04
That said this will only address the "SSL certificate cannot get verified warning"… Not the fact that some cURL versions and the remove server sometimes do nasty stuff that leads to unexpected results :see_no_evil:

**Comment by karlitschek** [comment] 2015-03-17 18:21
@LukasReschke I understand. Let´s do whatever you suggest.

**Comment by RealRancor** [comment] 2015-03-17 21:24
If this is fixed consider going through the issue tracker and search for all "App does not provide an info.xml file" issues. From what i see there are at least 4-5 issues reported here but i don't know if all of them are related.

**Comment by nsediq** [comment] 2015-03-17 21:41
Hi 
@RealRancor i see before the oldest issues. but all of them was for update from a old version of OC into 8.0.2. my issue that distinct from others, is that the fresh installation of OC 8.0.2 generated this error.

**Comment by wildhare3d** [comment] 2015-03-19 15:07
I don't know if these are issues are related. But I have the issues above - "App does not provide an info.xml file"

and I also cannot set up external storage when I try to setup FTP storage i get this mesage int he log:

Error	PHP	file_exists(): connect() failed: Permission denied at /var/www/html/owncloud/apps/files_external/lib/streamwrapper.php#51

**Comment by wildhare3d** [comment] 2015-03-20 16:07
disabling selinux fixed the External storage issue.

**Comment by RealRancor** [comment] 2015-03-20 16:35
@wildhare3d 
Yes, SELinux is causing such issues with FTP. Had documented this a few hours ago: https://github.com/owncloud/documentation/pull/969

**Comment by flotho** [comment] 2015-03-23 23:27
Hy,

I'm running on CentOS7 with latest OSB/rpm release
I also have the same message but SELINUX is disabled.
Additionnaly I have this issue :
```
"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/var\/www\/html\/owncloud\/lib\/private\/archive\/zip.php#135","level":0,"time":"2015-03-23T23:22:35+00:00","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/enableapp.php"}
```
I'll dig to #14840

**Comment by VicDeo** [comment] 2015-03-24 18:51
Closing as a duplicate of https://github.com/owncloud/core/issues/14840 which is older and has an isuue template inside.

**Closed by VicDeo** 2015-03-24 18:51 UTC
Labels: bug
