### ISSUE TITLE
when uploading large (>2GB) files to FTP storage, OC shows incorrect file size in UI

### ISSUE THREAD

**Issue by MarvinFS** [owncloud/core#14100] opened 2015-02-11 12:16 UTC
Using latest daily master trying to upload files to FTP external storage
(https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2)
new DB new everything, clean server

### Steps to reproduce
1. upload large (>2GB) file to FTP external storage

### Expected behaviour
1. files are uploaded 
2. files size shows correct values in OC UI
3. successful download uploaded file

### Actual behaviour
1. uploaded 4.5GB file - working just fine - speed is also great about 11 MB\sec through public internet
2. after upload is finished, OC UI incorrectly shows the uploaded file size: only 359MB (see the attached screenshot
![2015-02-11 10-50-19 1 - - owncloud - mozilla firefox](https://cloud.githubusercontent.com/assets/7998636/6146746/b0c00daa-b211-11e4-8c30-9d72615da6b8.png)
)
3. when you try to download that file, the same 359MB are downloaded
4. the actual uploaded file on target FTP server is full size 4.5GB and has the correct MD5
5. OC server restart or updating the page doesn't help - still shows incorrect file size

### Server configuration
Ubuntu 14LTS

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
PHP Version 5.5.21-1+deb.sury.org~trusty+2

**ownCloud version:** (see ownCloud admin page)
January 10, 2015 daily master

**Updated from an older ownCloud or fresh install:**
the very fresh

**List of activated apps:**
only defaults and external storages app

**The content of config/config.php:**
```
$CONFIG = array (
  'instanceid' => 'ocn6xdc7fntm',
  'trusted_domains' =>
  array (
    0 => '******',
    1 => '10.1.9.23',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://10.1.9.23/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'ocloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '9',
  'logtimezone' => 'Asia/Yekaterinburg',
  'log_authfailip' => true,
  'log_rotate_size' => 10485760,
  'debug' => true,
  'xframe_restriction' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'ocloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'hermes',
  'mail_smtpport' => '25',
);


```

**Are you using external storage, if yes which one:** 
ftp

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
firefox, ie11, chrome
**Operating system:**
windows 7, 8.1

#### ownCloud log (data/owncloud.log)
```
nothing in logs related to FTP transfer

```
php options in .htaccess

```
php_value upload_max_filesize 16G
php_value post_max_size 16G
php_value memory_limit 1024M
php_value output_buffering 16384
php_value mbstring.func_overload 0
php_value max_input_time 36484
php_value max_execution_time 36484

```
![Uploading 2015-02-11 10-50-19 1 - Файлы - ownCloud - Mozilla Firefox.png . . .]()

**Comment by PVince81** [comment] 2015-02-11 14:36
There are multiple possible issues:
1) Either the FTP server reports the wrong size
or
2) The PHP FTP protocol wrapper reports the wrong size
or
3) Something is wrong with numbers > 32-bits.

Are these all running n 64 bit systems ?

CC @bantu

**Comment by MarvinFS** [comment] 2015-02-11 15:02
1. it's not, because from the screen shot you can see the actual ftp directory listing and it has correct size.
2. no idea
3. all systems involved are 64bits, the FTP server is 32bit though (serv-u ftp server on windows 7on ntfs), but it handles any file sizes just great! i transfer 20+ gigs mkvs through it like several times per week...

**Comment by RealRancor** [comment] 2015-02-20 22:07
Not quite sure if this related but:

> php_value output_buffering 16384

should be set to:

> php_value output_buffering 0

according to: http://doc.owncloud.org/server/8.0/admin_manual/configuration/big_file_upload_configuration.html#configuring-php

**Comment by PVince81** [comment] 2015-08-03 14:17
Possibly related https://github.com/owncloud/core/issues/9144

**Comment by PVince81** [comment] 2016-03-01 19:37
Closing as duplicate of https://github.com/owncloud/core/issues/9144

**Closed by PVince81** 2016-03-01 19:37 UTC
Labels: bug
