### ISSUE TITLE
OwnCloud asked me to report this Problem here

### ISSUE THREAD

**Issue by DutchForce** [owncloud/core#28274] opened 2017-06-30 17:46 UTC
### Steps to reproduce
1.  Copying the new files to my webspace
2.  overwriting the config.php with he old one I saved before
3. opening my "cloud2 from Firefox by typing the adres

### Expected behaviour
Updateprogramm should start

### Actual behaviour
Tell us what happens instead:
Following errormessage appears:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
can´t login anymore

**Updated from an older ownCloud or fresh install:**
Overwriting older installation

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment] 2017-06-30 18:07
@DutchForce This is a duplicate of quite a lot other issues already reported here: https://github.com/owncloud/core/issues/28147, https://github.com/owncloud/core/issues/28036, https://github.com/owncloud/core/issues/28015, https://github.com/owncloud/core/issues/28007

Please close here and watch/subscribe to https://github.com/owncloud/core/issues/28007 for further updates to this issue.

**Comment by DutchForce** [comment] 2017-06-30 19:31
Thanks for your comment, I will watch/subscribe to #28007

**Closed** 2017-06-30 19:30 UTC

**Comment by kdslkdsaldsal** [comment] 2017-07-02 18:39
@DutchForce Thanks.

If you need support on how to get your instance running again (as https://github.com/owncloud/core/issues/28007 is not fixed yet) you can jump over to https://central.owncloud.org/ (you can login with your github handle there).
