### ISSUE TITLE
[6.0.6] Database and Data folders not consistent after upgrade.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#12035] opened 2014-11-07 16:48 UTC
### Expected behavior
Database and Data folder have the same structure

### Actual behavior
Database and Data folder have different structure

Now I have 3 different structures:
Wrong1: 
```
| cn=cdamken,ou=users,ou=nethz,ou=id,ou=auth,o=domain,c=com| 738b0228-c84e-1033-80ad-1b497b871bc2 | 738b0228-c84e-1033-80ad-1b497b871bc2 |
Folder in Data: 738b0228-c84e-1033-80ad-1b497b871bc2
```
Wrong2: 
```
| cn=cdamken,ou=users,ou=nethz,ou=id,ou=auth,o=domain,c=com| 738b0228-c84e-1033-80ad-1b497b871bc2 | 738b0228-c84e-1033-80ad-1b497b871bc2 |
Folder in Data: cdamken
```
Right: 
```
| cn=cdamken,ou=users,ou=nethz,ou=id,ou=auth,o=domain,c=com| cdamken| 738b0228-c84e-1033-80ad-1b497b871bc2 | 
Folder in Data: cdamken
```

### Architecture
RHEL 6
oC 6.0.6
PHP 5.3.3
MySQL 5.1.73
Open LDAP

@craigpg @blizzz @PVince81 @icewind1991 

00002045

**Comment by cdamken** [comment] 2015-01-05 11:17
@PVince81 https://github.com/owncloud/core/issues/12035#issuecomment-64895631 who else can do this if @felixboehm is busy?

**Comment by cdamken** [comment] 2015-01-09 20:15
@MorrisJobke  I have the dump from the database, we can recreate the environment if its possible.

**Comment by cdamken** [comment] 2015-01-16 18:24
@craigpg @markviens I need some help here, I can not upgrade until the database is fixed.

**Comment by MorrisJobke** [comment] 2015-01-28 21:06
I can try to write that one-shot script, but I need the help from @blizzz and @PVince81 if this is possible. What is to do to get this working?

* for the users of wrong1 - update the username in the database & move their user folder (this includes the rename of the storage)
* for the users of wrong2 - update the username in the database & adjust the storage (or is this already correct? I think a rename of the storage ID is enough here

@PVince81 Can you explain me the storage ID stuff in detail so that I fully understand the issues that could be caused by this. That would be nice.

@blizzz @PVince81 Is this what needs to be done? Then I will have a look at the DB dump tomorrow and list all tables that need to be touched and ask furhter questions.

@craigpg Is this fine for you too?

**Comment by PVince81** [comment] 2015-01-29 09:04
The storage id logic works as follows:
Whenever a user "userx" has their filesystem setup:
1. Look at `oc_storages` whether there is an entry with id "local::$datadir/userx/". If yes, use it. (replace $datadir with the data dir location, yes... hard-coded in the DB)
2. Else: look at `oc_storages` for an entry with id "home::userx". If yes use it.
3. Else: no entry found, auto-create one with id "home::userx".

The entry format from point 1. is the one from OC <= 5.0.12. As long as the admin didn't move the datadir to another location, everything should be fine. If the admin moved the data dir, then according to the logic above, step 1 would NOT find the old entry and would create a new one, causing duplicate ids. The shares that pointed to "oc_filecache" for 1. are still pointing there, so they become unusable.

Now for LDAP such thing might happen too: if the user id format changes, then it would also create a new "home::newidforuser" instead of using the old "home::oldidforuser". Because step 2 wouldn't find the entry when looking for "home::newidforuser".

I hope this helps understand it.

**Comment by PVince81** [comment] 2015-01-29 09:10
In the case of LDAP user change it would likely also create a new entry on the filesystem under "data/newuserid" instead of reusing the files from "data/olduserid". But I guess this was already known.

I'm not so familiar with the user id format for LDAP and have no idea would they would even change in the first place, especially when upgrading from 6.0.6 to OC 7 ?!

**Comment by MorrisJobke** [comment] 2015-01-29 09:11
@PVince81 So case 3 can be ignored because this also happens on initial login or am I wrong?

**Comment by PVince81** [comment] 2015-01-29 09:15
There are not cases, just the sequence for the logic.
It only explains why OC might have decided to create a new home instead of reusing the old one (either when data dir changed or the user id changed)

**Comment by PVince81** [comment] 2015-01-29 09:16
Do we have an explanation yet for the sudden change of user id without admin interaction ? Was there any recent change in OC 7.0.4 that might cause it ?

**Comment by MorrisJobke** [comment] 2015-01-29 09:18
@blizzz Was there a default value change somewhere in the LDAP settings?

**Comment by butonic** [comment] 2015-01-29 09:28
looking at update.php we are updating the `ldap_expert_uuid_user_attr` to `''` if it was not set before:
https://github.com/owncloud/core/blob/stable7/apps/user_ldap/appinfo/update.php#L19 will return 'not existing'
https://github.com/owncloud/core/blob/stable7/apps/user_ldap/appinfo/update.php#L22 sets value to `''`
https://github.com/owncloud/core/blob/stable7/apps/user_ldap/appinfo/update.php#L24 sets  `ldap_expert_uuid_user_attr` to `''`

That in turn causes Access::detectUuidAttribute to return true because `'' !== 'auto'` https://github.com/owncloud/core/blob/stable7/apps/user_ldap/lib/access.php#L1247

The check in https://github.com/owncloud/core/blob/stable7/apps/user_ldap/lib/access.php#L1251 is never reached.

IMHO the default value set in the update php should be `'auto'` not `''`.

@blizzz @PVince81 @MorrisJobke This is just from reading code. can you confirm?

**Comment by MorrisJobke** [comment] 2015-01-29 09:53
@butonic This was change in 7.0.3 https://github.com/owncloud/core/commit/ada93bab0cd0cdb14a66b2ebdecba68c26a1107e

@blizzz Could that be the problem?

**Comment by butonic** [comment] 2015-01-29 09:53
Then again I might be wrong because it was explicitly changed from `'auto'` to `''` for 7.0.3 in https://github.com/owncloud/core/commit/ada93bab0cd0cdb14a66b2ebdecba68c26a1107e#diff-2af2ba33b6e46e7c274bfe956b1cda78R22

@blizz can you elaborate on 'must be empty not auto'

**Comment by blizzz** [comment] 2015-01-29 11:42
@butonic @MorrisJobke  yes, that's it. ldap_uuid_*_attribute must be auto and the other pair ''. The commit @butonic pointed to was supposed to only fix one default value (of the expert settings). No idea what came over me :rage:

**Comment by MorrisJobke** [comment] 2015-01-29 17:41
@cdamken Does these wrong1 or wrong2 users already exists in the stable6 instance? If now the patch in #13759 will hopefully fix the migration. Otherwise we need a handcrafted script to fix this anyway. Maybe something we can adapt for @jcfischer too.

**Comment by MorrisJobke** [comment] 2015-01-31 09:29
This is something to be fixed in stable7 and not in 8.0 -> move to the maintenance milestone

**Comment by cdamken** [comment] 2015-02-10 15:05
@MorrisJobke 
>Does these wrong1 or wrong2 users already exists in the stable6 instance?

The system is a 6.0.6. and we can't know when it the problem started. We can't upgrade until we see that the database has the same information for all the users.

**Comment by MorrisJobke** [comment] 2015-02-10 15:46
@cdamken So the problem doesn't exists yet, but appear once the upgrade happened?

**Comment by cdamken** [comment] 2015-02-12 09:52
@MorrisJobke The problem exist!, since https://github.com/owncloud/core/issues/10954 

I closed that issue because was only about the scan, but there is where we saw that the problem exist since a long time, the server seems to be started with 5.0.9 EE

The upgrade information that we have until now:
11.06.2014: 5.0.13 -> 6.0.3
08.07.2014: 6.0.3 -> 6.0.4
18.09.2014: 6.0.4 -> 6.0.5
05.12.2014: 6.0.5 -> 6.0.6

We want to upgrade but we need that the database is fixed to avoid problems during the upgrade.

**Comment by MorrisJobke** [comment] 2015-02-12 09:55
@butonic @blizzz Okay. Then this isn't caused by the wrong setting in the LDAP upgrade (`'auto'` vs `''`)

**Comment by DeepDiver1975** [comment] 2015-02-17 13:11
@MorrisJobke @butonic @PVince81 anything we can do for 7.0.5? Moving to 7.0.6???

**Comment by MorrisJobke** [comment] 2015-02-17 17:46
@DeepDiver1975 I'm workind on this, but this isn't bound to 7.0.5

**Comment by craigpg** [comment] 2015-04-27 21:15
@cdamken, can you (re)confirm the status of this case?

**Comment by MorrisJobke** [comment] 2015-04-27 21:22
@craigpg We are currently working with ETH to get the first iteration of the cleanup done. The tests succeeded today and we plan another test together with them. E-mail to them is out - just minutes ago ;)

https://github.com/owncloud/consulting/tree/eth

**Comment by cdamken** [comment] 2015-04-28 10:43
@craigpg yes, @MorrisJobke @felixboehm and @butonic are trying to fix it.

**Comment by bboule** [comment] 2015-05-01 17:57
Guys it does not look like anyone has commented on this in two months... @cdamken what is the status of the case with the customer?  trying to sort out what this needs to move forward or close??

**Comment by MorrisJobke** [comment] 2015-05-03 11:19
> Guys it does not look like anyone has commented on this in two months... @cdamken what is the status of the case with the customer? trying to sort out what this needs to move forward or close??

This needs manual fixes inside the database. We are working on this.

**Comment by craigpg** [comment] 2015-05-04 21:09
Thx @MorrisJobke.  I see now that there's another issue we're using to track the work on this: owncloud/enterprise#525.

**Comment by DeepDiver1975** [comment] 2015-06-17 13:53
please continue discussion in owncloud/enterprise#525.

**Closed** 2015-06-17 13:52 UTC
Labels: 3 - To Review, blue-ticket
