### ISSUE TITLE
MYSQL Error 2006 during upgrade from 7.0.3 to 7.0.4

### ISSUE THREAD

**Issue by JonTheNiceGuy** [owncloud/core#13910] opened 2015-02-04 22:21 UTC
When running occ upgrade, I'm getting a 2006 mysql error message which seems to be either a timeout error or a Max connection size is exceeded error.

During the execution of the request, I see the following in my logs: http://pastie.org/9887108

It would appear that a reconnection request is required, but I can't see where to add it, although I suspect it should probably be in /lib/private/db.php or in /lib/private/db/migrator.php

Are there any thoughts? I've tried the various suggestions at http://stackoverflow.com/q/10474922/5738 with no luck. This was previously working under 7.0.3, so I doubt it's in the config somewhere!

**Comment by PVince81** [comment] 2015-08-03 13:41
Did you still see this happening in 7.0.7 or 8.0.5 ?

**Comment by JonTheNiceGuy** [comment] 2015-08-04 16:45
Sorry, I didn't try, I've stopped using OwnCloud at 7.0.4 until I have time to sort it out.

**Comment by PVince81** [comment] 2015-10-09 09:16
duplicate of https://github.com/owncloud/core/issues/15407

**Closed by PVince81** 2015-10-09 09:16 UTC
Labels: bug, triage
