### ISSUE TITLE
Calendars infinitely loading in owncloud 9.1.5 and calendar 1.5.4

### ISSUE THREAD

**Issue by gagbo** [owncloud/core#29663] opened 2017-11-23 12:22 UTC
### Steps to reproduce
1. Upgrade from owncloud-9.1.5-1.fc26 to owncloud-9.1.5-2.fc27
2. Go on the calendar page on the owncloud web page
3.

### Expected behaviour
All calendars should be loaded and displayed in the app ; DAVDroid shares should continue working

### Actual behaviour
The calendars in the calendar page are not displaying (there is just a loading icon).
The DAVDroid shares do not work anymore [here is the log](https://gist.github.com/gagbo/fa006d55c5ef436d81ad70cc95fb0031)

### Server configuration
**Operating system:** Fedora 27

**Web server:** Apache 2.4.29 ( 2.4.29-1.fc27 )

**Database:** mysql - mariaDB 10.2.9 ( 3:10.2.9-3.fc27 ) 

**PHP version:** 7.1.11-1.fc27

**ownCloud version:** (see ownCloud admin page) 9.1.5

**Updated from an older ownCloud or fresh install:** 9.1.3 -> 9.1.4 -> 9.1.5 -> 9.1.5 (from F25 to F27)

**Where did you install ownCloud from:** packages

**Signing status (ownCloud 9.0 and above):**
As seen below, the integrity checker is not enabled apparently. I don't know how to activate, but the
occ integrity:check-core and check-app calendar commands did not produce any output on the server

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:** [Gist](https://gist.github.com/gagbo/c06b42597ad0b977640ae737ccf30f22)

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
Disabled:
  - bookmarks
  - contacts
  - encryption
  - external
  - files_antivirus
  - files_external
  - news
  - ownnote
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 57, Firefox 56, Edge, DAVdroid...

**Operating system:** Linux, Windows, Android

#### Web server error log
Here are the current last few lines, tell me if there's something specific I should look for :
```
X.X.X.X - - [23/Nov/2017:12:52:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:52:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:52:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:53:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:53:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:53:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:53:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:54:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:54:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:54:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:54:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:55:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:55:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:55:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:55:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:56:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:56:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:56:13 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:56:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:56:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:56:58 +0100] "GET /index.php/apps/calendar/ HTTP/1.1" 200 56338 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
X.X.X.X - - [23/Nov/2017:12:56:59 +0100] "GET /index.php/core/js/oc.js?v=156e43eaba67f738da1fc7478cda2558 HTTP/1.1" 200 2567 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57
.0"
X.X.X.X - - [23/Nov/2017:12:57:00 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:57:00 +0100] "PROPFIND /remote.php/dav HTTP/1.1" 207 507 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
X.X.X.X - - [23/Nov/2017:12:57:00 +0100] "POST /index.php/apps/calendar/v1/config HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
X.X.X.X - - [23/Nov/2017:12:57:01 +0100] "PROPFIND /remote.php/dav/principals/users/gerry/ HTTP/1.1" 207 452 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
X.X.X.X - - [23/Nov/2017:12:57:02 +0100] "GET /apps/calendar/js/public/app.min.js.map HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0"
X.X.X.X - - [23/Nov/2017:12:57:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:57:30 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:57:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:58:00 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:58:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:58:30 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
X.X.X.X - - [23/Nov/2017:12:58:41 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 341 "-" "Mozilla/5.0 (Linux) mirall/2.3.3"
X.X.X.X - - [23/Nov/2017:12:59:00 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/
57.0"
```

#### ownCloud log (data/owncloud.log)
There was no relevant info there I think (only warnings about autosize.js as per owncloud/calendar#821 )
But I have a lot of errors in my mariadb log
```
2017-11-22 18:13:04 139689059948288 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:14:16 139689059948288 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:17 139689059948288 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:32 139688915158784 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:32 139688915158784 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:32 139688915158784 [ERROR] InnoDB: Fetch of persistent statistics requested for table `owncloud`.`oc_oc_appconfig_zqwa1vpefdckd` but the required system tables mysql.innodb_table_stats and mysql.innodb_index_stats are not present or have unexpected structure. Using transient stats instead.
2017-11-22 18:15:32 139688915158784 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:32 139688915158784 [ERROR] InnoDB: Fetch of persistent statistics requested for table `owncloud`.`oc_addressbookchanges` but the required system tables mysql.innodb_table_stats and mysql.innodb_index_stats are not present or have unexpected structure. Using transient stats instead.
2017-11-22 18:15:33 139688915158784 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:33 139688915158784 [ERROR] InnoDB: Fetch of persistent statistics requested for table `owncloud`.`oc_bookmarks` but the required system tables mysql.innodb_table_stats and mysql.innodb_index_stats are not present or have unexpected structure. Using transient stats instead.
2017-11-22 18:15:33 139688915158784 [ERROR] InnoDB: Column last_update in table `mysql`.`innodb_table_stats` is INT UNSIGNED NOT NULL but should be BINARY(4) NOT NULL (type mismatch).
2017-11-22 18:15:33 139688915158784 [ERROR] InnoDB: Fetch of persistent statistics requested for table `owncloud`.`oc_bookmarks_tags` but the required system tables mysql.innodb_table_stats and mysql.innodb_index_stats are not present or have unexpected structure. Using transient stats instead.
```
And then another bunch of innodb_table_stats errors like the first

#### Browser log
See the DAVdroid log for Android, Browser log on Calendar page is (sorry for the tad of french)
```
JQMIGRATE: Migrate is installed, version 1.4.0
jquery-migrate.min.js:2:542
Logging system initialised at Thu Nov 23 2017 13:08:10 GMT+0100 (CET)
common.js:195:17
TypeError: e[(("{" + r.NS_IETF) + "}calendar-home-set")][0] is undefined
[En savoir plus]
app.js:4846:4
Erreur dans les liens source : TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : moz-extension://be66aada-7766-49ac-8f12-0ad10bae3377/common/common.js
URL du lien source : common.js.map
```

### Misc
Also, I don't know if it's relevant or not, but I still find my calendars in the db I just don't know what else to check there: 
```
MariaDB [owncloud]> select * from oc_calendars;
+----+--------------------------+-------------------+-------------------+-----------+---------------+---------------+---------------+----------+--------------+-------------+                                     
| id | principaluri             | displayname       | uri               | synctoken | description   | calendarorder | calendarcolor | timezone | components   | transparent |                                     
+----+--------------------------+-------------------+-------------------+-----------+---------------+---------------+---------------+----------+--------------+-------------+                                     
|  1 | principals/users/gerry   | Personnel         | personnel         |        85 | Personnel     |             0 | #E5FFCC       | NULL     | VEVENT,VTODO |           0 |                                     
|  2 | principals/users/gerry   | These             | thèse             |        73 | These         |             0 | #0080FF       | NULL     | VEVENT,VTODO |           0 |                                     
|  3 | principals/users/gerry   | My                | my                |         8 | My            |             0 | #FFB266       | NULL     | VEVENT,VTODO |           0 |                                     
|  4 | principals/users/gerry   | Plans sorties     | planssorties      |        19 | Plans sorties |             0 | #B266FF       | NULL     | VEVENT,VTODO |           0 |                                     
|  5 | principals/users/myriam  | Personal          | personal          |         1 | Personal      |             0 | NULL          | NULL     | VEVENT,VTODO |           0 |                                     
|  6 | principals/users/gerry   | Contact birthdays | contact_birthdays |         1 | NULL          |             0 | #FFFFCA       | NULL     | VEVENT       |           0 |                                     
|  7 | principals/users/myriam  | Contact birthdays | contact_birthdays |         1 | NULL          |             0 | #FFFFCA       | NULL     | VEVENT       |           0 |                                     
|  8 | principals/system/system | Contact birthdays | contact_birthdays |         1 | NULL          |             0 | #FFFFCA       | NULL     | VEVENT       |           0 |                                     
+----+--------------------------+-------------------+-------------------+-----------+---------------+---------------+---------------+----------+--------------+-------------+                                     
8 rows in set (0.00 sec)
```

**Comment by DeepDiver1975** [comment] 2017-11-23 12:35
@Julian1998 please have a look - thx

**Comment by gagbo** [comment] 2017-11-27 12:20
I may have found a culprit.

I just noticed I can't share my files with any user because the 'completion' popup never fills to propose users when I write.

Looking at the log, I had these error, which look more relevant to the issues I have (`176.159.76.84` is my current IP) : 
```
{"reqId":"Whv5UoKGQyUDa9-qBE-tqwAAAIg","remoteAddr":"176.159.76.84","app":"PHP","message":"RuntimeException: Starting sabre\/vobject 4.0 the children property is now protected. You should use the children() method instead at \/usr\/share\/php\/Sabre\/VObject4\/Component.php#466","level":3,"time":"2017-11-27T11:38:59+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=Myri&perPage=200&itemType=folder","user":"gerry"}
```

**Comment by kku** [comment] 2017-11-27 15:27
The sharing failure has most probably nothing to do with this. See: https://github.com/owncloud/core/issues/27474

**Comment by gagbo** [comment] 2017-11-27 18:52
Indeed this is unrelated and the bug is still here. I'm still trying to search a little bit everywhere to find a reasonable explanation. There are a few [distribution related bugs](https://bugzilla.redhat.com/show_bug.cgi?id=1460603) about owncloud and [dav shares](https://bugzilla.redhat.com/show_bug.cgi?id=1514823) but that's pretty much everything I found about this.

**Comment by kku** [comment] 2017-11-27 19:17
I found something here: https://help.nextcloud.com/t/calendar-is-not-showing-anymore/5780
Line 4846 in calendar/js/public : var properties = ['{' + DavClient.NS_IETF + '}calendar-home-set'];
Above reference holds that the problem should be fixed with OC 10.x - which does not help for poor Fedora 27 users who are tied to what their distribution gives them. I feel tempted to meddle with the code directly...

**Comment by kku** [comment] 2017-11-27 19:36
I found something here: https://help.nextcloud.com/t/calendar-is-not-showing-anymore/5780
Line 4846 in calendar/js/public : `var properties = ['{' + DavClient.NS_IETF + '}calendar-home-set'];`
Above reference holds that the problem should be fixed with OC 10.x - which does not help for poor Fedora 27 users who are tied to what their distribution gives them. I feel tempted to meddle with the code directly...

**Comment by kdslkdsaldsal** [comment] 2017-11-27 20:13
Concerning https://github.com/owncloud/core/issues/27474:

If some one of you has an account on the fedora / redhat bugtracker its still highly recommended that the issue with the vobject is reported there. This might have additional unknown side effects if the components they are using doesn't match whats required by ownCloud.

**Comment by gagbo** [comment] 2017-11-27 20:22
The [second bug](https://bugzilla.redhat.com/show_bug.cgi?id=1514823) I linked talks about Sabre/ownCloud compatibility, though I'm not sure they have the same version of the package as I.

**Comment by kdslkdsaldsal** [comment] 2017-11-27 20:39
That bug is referencing to sabre/dav, however the message is caused by a too new sabre/vobject as pointed out in https://github.com/owncloud/core/issues/27474#issuecomment-288818413

If they are also using some other libraries from their own repositories instead of the ones needed / shipped by https://github.com/owncloud/3rdparty/tree/stable9.1 additional issues like e.g. something you're currently seeing could be seen.

**Comment by gagbo** [comment] 2017-11-27 21:17
I'm currently running a repoquery to list the dependencies pulled by the package manager, does the list of dependencies in  https://github.com/owncloud/3rdparty/tree/stable9.1 has a "simpler to read" list form so I can compare version numbers quickly ?

**Comment by kku** [comment] 2017-11-28 14:29
Would there be a possibility to split up this issue in its *unrelated* parts? I am really (and at the moment: only) keen to see the loading issue resolved. No calendar functionality anywhere. This is most aggravating.

**Comment by kdslkdsaldsal** [comment] 2017-11-28 15:39
@kku The question remains if any of the used dependency on fedora is just causing this issue:

Because @gagbo updated from owncloud-9.1.5-1.fc26 to owncloud-9.1.5-2.fc27 (there is no change in the ownCloud version, just an OS upgrade) so this whole issue could be also completely related to the upgrade from Fedora 26 to 27.

**Closed** 2017-11-28 15:42 UTC
Labels: bug

**Comment by gagbo** [comment] 2018-02-06 03:52
For the record, the workaround given in that other issue (owncloud/calendar#867) works for me too, and is detailed in this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1525208), which is the place to watch for a permanent solution.
