### ISSUE TITLE
Checksum is only set every 2nd WebDAV upload when uploading the same file

### ISSUE THREAD

**Issue by Papts** [owncloud/core#37124] opened 2020-03-13 16:25 UTC
If I upload the same unchanged file via WebDav several times to the same URI, the checksum field in the MariaDB is only set every **2nd** upload. If I include the http "OC-Checksum:" header for the upload, the behaviour remains the same.
After I refresh my localhost-browser-view, the db checksum is set. If I upload a different file to the same URI, the db checksum is also set.
Use-case is probably negligible because why would you re-upload an unchanged file? But maybe it's a bug, one which also affects other cases.

### Steps to reproduce
<br>
1. Upload a file via WebDav/cURL

```
curl -u admin:admin "http://localhost:8080/remote.php/dav/files/admin/test.txt" -T "test.txt"
```

<br>

2. Check the MariaDB entry

```
+--------+----------------+------+------------+-----------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
| fileid | path           | size | mtime      | encrypted | etag                             | permissions | checksum                                                                                            |
+--------+----------------+------+------------+-----------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
|   4221 | files/test.txt |  295 | 1583843028 |         0 | bf64c4de8aab4837e728fa34de9431e4 |          27 | SHA1:edde2f3e9e741a77c04ad6681832333f20896ce0 MD5:e5e4d3b6b43b19ca028fbaaf144ae9b6 ADLER32:ad705297 |
+--------+----------------+------+------------+-----------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
```
<details>
<summary>MySQL commands</summary>

Login
```
mysql -u owncloud -p  owncloud
```

Select owncloud database
```
use owncloud;
```

Show checksum entry of "files/test.txt" from filecache table.
```
SELECT path, checksum FROM oc_filecache WHERE path="files/test.txt";
```
</details>
<details>
<summary>Or WebDav PROPFIND</summary>

Request:
```
curl -u admin:admin "http://localhost:8080/remote.php/dav/files/admin/test.txt" -X PROPFIND --data-binary @"find.txt"
```

with find.txt:
```
<?xml version="1.0" encoding="utf-8" ?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
    <a:prop>
        <oc:checksums/>
    </a:prop>
</a:propfind>
```

Response:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
   <d:response>
      <d:href>/remote.php/dav/files/admin/test.txt</d:href>
      <d:propstat>
         <d:prop>
            <oc:checksums>
               <oc:checksum>SHA1:edde2f3e9e741a77c04ad6681832333f20896ce0 MD5:e5e4d3b6b43b19ca028fbaaf144ae9b6 ADLER32:ad705297</oc:checksum>
            </oc:checksums>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>
```

</details>

<br>
<br>

3. Repeat the upload
```
curl -u admin:admin "http://localhost:8080/remote.php/dav/files/admin/test.txt" -T "test.txt"
```

<br>

4. Check the MariaDB entry again
``` +--------+----------------+------+------------+-----------+----------------------------------+-------------+----------+
| fileid | path           | size | mtime      | encrypted | etag                             | permissions | checksum |
+--------+----------------+------+------------+-----------+----------------------------------+-------------+----------+
|   4221 | files/test.txt |  295 | 1583843507 |         0 | ff1fb0f0602bf29040a9d76159d17b99 |          27 |          |
+--------+----------------+------+------------+-----------+----------------------------------+-------------+----------+
```

<details>
<summary>WebDav PROPFIND response</summary>

```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
   <d:response>
      <d:href>/remote.php/dav/files/admin/test.txt</d:href>
      <d:propstat>
         <d:prop>
            <oc:checksums/>
         </d:prop>
         <d:status>HTTP/1.1 404 Not Found</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>
```

</details>

<br>

### Expected behaviour
The checksum field should be set.

### Actual behaviour
The checksum field is not set.

### Server configuration
**Operating system**: Linux Docker (on Windows 10 Pro 64bit)

**Web server:** Docker Image

**Database:** MariaDB

**ownCloud version:** Tested on 10.3.2 (stable) and 10.4.0 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** Docker Image

**Signing status (ownCloud 9.0 and above):**
```
No errors have been found.
```

**The content of config/config.php:**
```
https://pastebin.com/bZTkHh5b
```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

**Comment by IljaN** [comment] 2020-09-15 14:42
Thank you for this report! This might explain some checksum bugs we are hunting for ages.

**Comment by cdamken** [comment] 2020-09-15 15:37
Hi @Papts 

I tested with 10.5, php 7.4 and I sadly can't reproduce the error:

```
root@snoopy4:~# vi checksumtest.txt
root@snoopy4:~# curl -u carlos "https://cloud.damken.com:/remote.php/dav/files/carlos/checksumtest.txt" -T "checksumtest.txt"
Enter host password for user 'carlos':
root@snoopy4:~# occ_db "select * from oc_filecache where path like '%checksumtest%'"
+----------+---------+------------------------+----------------------------------+---------+------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
| fileid   | storage | path                   | path_hash                        | parent  | name             | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions | checksum                                                                                            |
+----------+---------+------------------------+----------------------------------+---------+------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
| 16453357 |       1 | files/checksumtest.txt | dea1b6076871cacff889cd7a8fb141a2 | 3842431 | checksumtest.txt |       13 |       12 |    7 | 1600182224 |    1600182224 |         0 |                0 | f0699c46aa6f482d050b7de154f564ca |          27 | SHA1:86a2fa7bbc75b6f56fbf2ca8f09bde1bb3e9f2db MD5:fea16baf9a91fbcb5a656503af6388f4 ADLER32:0b29028f |
+----------+---------+------------------------+----------------------------------+---------+------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
root@snoopy4:~# vi checksumtest.txt
root@snoopy4:~# curl -u carlos "https://cloud.damken.com:/remote.php/dav/files/carlos/checksumtest.txt" -T "checksumtest.txt"
Enter host password for user 'carlos':
root@snoopy4:~# occ_db "select * from oc_filecache where path like '%checksumtest%'"
+----------+---------+---------------------------------------------+----------------------------------+----------+------------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
| fileid   | storage | path                                        | path_hash                        | parent   | name                         | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions | checksum                                                                                            |
+----------+---------+---------------------------------------------+----------------------------------+----------+------------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
| 16453357 |       1 | files/checksumtest.txt                      | dea1b6076871cacff889cd7a8fb141a2 |  3842431 | checksumtest.txt             |       13 |       12 |   14 | 1600182359 |    1600182359 |         0 |                0 | 158a1e5b378b8f0283b6e31923516373 |          27 | SHA1:0589435b581417828bdd0cdbea1797c551b554ff MD5:2d600a370e233bc98c98284357d25458 ADLER32:28a6051f |
| 16453358 |       1 | files_versions/checksumtest.txt.v1600182224 | 8a5ec71dec8e2714139653e6c1e031c5 | 16047742 | checksumtest.txt.v1600182224 |       10 |        5 |    7 | 1600182359 |    1600182359 |         0 |                0 | b3d6bf65d41d1a93aeba0d4517519e79 |          27 |                                                                                                     |
+----------+---------+---------------------------------------------+----------------------------------+----------+------------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+-----------------------------------------------------------------------------------------------------+
```

can you give me some hints?

I will create an issue why is the checksum removed from the version file, if its already calculated why it disappears.

**Comment by Papts** [comment] 2020-09-16 07:48
Interesting @cdamken. I retried it on a fresh 10.5.0.10 install (php 7.4.3) and the issue remained. I am using a (HTTP) localhost  server via Docker on my Windows machine for testing.

Config Report:
https://pastebin.com/0R9ayGTh

**Comment by Papts** [comment] 2020-09-16 10:14
@cdamken I noticed that your uploaded files differ in file size and hash value. The issue only appears if you upload the exact same file twice.

**Comment by NannaBarz** [comment] 2020-09-16 11:12
I tested it with a 10.4.1 on my Ubuntu 20.04 with docker and can reproduce it:
```
MariaDB [owncloud]> SELECT path, checksum FROM oc_filecache WHERE path="files/test.txt";
+----------------+-----------------------------------------------------------------------------------------------------+
| path           | checksum                                                                                            |
+----------------+-----------------------------------------------------------------------------------------------------+
| files/test.txt | SHA1:0f0b17c683fa6880d5f1772b8a32f5bf1c6c0185 MD5:fd8f593c61e05cd53c06cc65f3433b49 ADLER32:2abd0613 |
+----------------+-----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MariaDB [owncloud]> SELECT path, checksum FROM oc_filecache WHERE path="files/test.txt";
+----------------+----------+
| path           | checksum |
+----------------+----------+
| files/test.txt |          |
+----------------+----------+
1 row in set (0.00 sec)
```
I tried it with the same file

**Comment by cdamken** [comment] 2020-09-16 14:48
thanks @NannaBarz from the reproduction. we will fix this too

**Comment by IljaN** [comment] 2021-01-14 12:35
Fixed via https://github.com/owncloud/core/pull/37934

**Closed by IljaN** 2021-01-14 12:35 UTC
