### ISSUE TITLE
Update Fails 7.0.4.2 --> 8.0.0-5

### ISSUE THREAD

**Issue by merylen** [owncloud/core#14032] opened 2015-02-10 09:26 UTC
Hi,
i´ve a problem Upgrading to 8.0.0-5 using opensuse packages.

DB-Backend: MariaDB

su www-data -c "/usr/bin/php occ upgrade" -s /bin/bash
Turned on maintenance mode
An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_vbesord6y0x7p RENAME INDEX appconfig_config_key_index TO oc_jr9se4eqhnqx4':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_jr9se4eqhnqx4' at line 1
Turned off maintenance mode
Update failed

**Comment by LukasReschke** [comment] 2015-02-10 09:34
Duplicate of https://github.com/owncloud/core/issues/14003

**Closed by LukasReschke** 2015-02-10 09:34 UTC
