### ISSUE TITLE
Configure the default "landing" folder for new folders shared with you per user

### ISSUE THREAD

**Issue by mihaig11** [owncloud/core#12298] opened 2014-11-19 11:32 UTC
Hello,
For the moment the default "landing" folder for new folders shared with you" can be configured via the "share_folder" option in config.php per server (meaning the same for all users). 

 More interesting would be per user, for example I have 3 users (user1, user2 and user3) that share files with each other:
 user1 has two folders "user2 files" and "user3 files" in which he sees files shared with him by user2 and user3 respectively. The problem is, when user2 (for example) shares a new file/folder with user1, this one appears in the root of user1's home directory, and needs to be manually moved to "user2 files" folder, for example.
 Also had a problem that files already shared by user2 and manually moved into "user2 files" folder moved back by themselves (into the root of his home dir)...I moved them again into "user2 files" and for the moment they stay there, but if someone knows why this could happen, I sure like to avoid the problem in the future.
 Thanks

**Comment by MorrisJobke** [comment] 2016-01-19 00:38
Duplicate of https://github.com/owncloud/core/issues/14049

**Closed by MorrisJobke** 2016-01-19 00:38 UTC
Labels: enhancement
