### ISSUE TITLE
Master unit tests are broken

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#15326] opened 2015-03-31 08:23 UTC
```
There was 1 error:

1) OCA\Files_Encryption\Tests\Share::testRemoteShareFile
Exception: Sharing 377 failed, could not find user1@server1, maybe the server is currently unreachable.

/home/lreschke/core/lib/private/share/share.php:759
/home/lreschke/core/lib/public/share.php:245
/home/lreschke/core/apps/files_encryption/tests/share.php:648

--

There were 2 failures:

1) Test\Files\View::testRenameFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/lreschke/core/tests/lib/files/view.php:915
/home/lreschke/core/tests/lib/files/view.php:877

2) Test\Files\View::testCopyFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/lreschke/core/tests/lib/files/view.php:915
/home/lreschke/core/tests/lib/files/view.php:881
```

**Comment by LukasReschke** [comment] 2015-03-31 08:23
@DeepDiver1975 @karlitschek FYI

**Comment by LukasReschke** [comment] 2015-03-31 08:23
This is on PHP 5.4 with SQLite on a Debian machine

**Comment by LukasReschke** [comment] 2015-03-31 08:27
stable8 has the same issues: https://github.com/owncloud/core/issues/15327

**Comment by LukasReschke** [comment] 2015-03-31 08:30
The two failing tests have been introduced with https://github.com/owncloud/core/commit/232de3bdc093e839048d5b00d7f08ecc87ba7908

I'm still bisecting the encryption sharing fail…

**Comment by LukasReschke** [comment] 2015-03-31 08:30
@PVince81 FYI

**Comment by LukasReschke** [comment] 2015-03-31 08:36
@schiesbn @th3fallen For the failing encryption test

**Comment by MorrisJobke** [comment] 2015-03-31 08:41
I have the same failures with PHP 5.6.6 on ArchLinux

**Comment by LukasReschke** [comment] 2015-03-31 08:46
That magic sharing encryption test looks broken for me since ever… So what…

**Comment by DeepDiver1975** [comment] 2015-03-31 08:47
> That magic sharing encryption test looks broken for me since ever… So what…

which is not true - jenkins is passing

**Comment by LukasReschke** [comment] 2015-03-31 08:47
> which is not true - jenkins is passing

Well – on our Jenkins also the other tests are passing but I guess tests that are only passing on Jenkins are not really reliable…

**Comment by DeepDiver1975** [comment] 2015-03-31 08:50
> Well – on our Jenkins also the other tests are passing but I guess tests that are only passing on Jenkins are not really reliable…

Seriously? This statement is bullshit - sorry

**Comment by nickvergessen** [comment] 2015-03-31 08:53
Maybe it's a problem of the run order again. In most cases we have passing locally and failing on master. This time it is the otherway around.

**Comment by Xenopathic** [comment] 2015-03-31 11:51
BTW: I've had a consistent unit test failure since forever: 

    Test_Files_Sharing_Mount::testShareMountLoseParentFolder
    Failed asserting that 8 is identical to 1.

No-one else seems to get the problem, nor does Jenkins, so I can only assume it's my environment. I don't get any other failures though (unless I've broken something!)

**Comment by nickvergessen** [comment] 2015-03-31 14:09
Can't reproduce here.

@LukasReschke @MorrisJobke Since tests of apps are run aswell and might interfer, can you please post lists of the apps you have in your folders and maybe remove them and then try again?

If that does not help, please run tests with `--debug --verbose` so we get the test order and can compare that.

**Comment by LukasReschke** [comment] 2015-03-31 14:13
> @LukasReschke @MorrisJobke Since tests of apps are run aswell and might interfer, can you please post lists of the apps you have in your folders and maybe remove them and then try again?

It's only core.

> If that does not help, please run tests with --debug --verbose so we get the test order and can compare that.

That I can do.

**Comment by rullzer** [comment] 2015-03-31 20:00
So it is actually a know issue #14953

**Comment by PVince81** [comment] 2015-04-07 10:06
Oh, does it mean that Jenkins is finally having the same failing test as I had locally ?
Not sure whether I should feel sad or happy.

**Comment by PVince81** [comment] 2015-04-07 14:38
Green again it seems: https://ci.owncloud.org/job/server-master-linux/

**Comment by MorrisJobke** [comment] 2015-04-07 15:17
Okay...new broken stuff due to enc 2.0

**Comment by nickvergessen** [comment] 2015-04-08 08:16
https://ci.owncloud.org/job/server-master-linux/ is still all green here?

**Comment by MorrisJobke** [comment] 2015-04-08 08:37
I get something like http://ix.io/hn2

**Comment by nickvergessen** [comment] 2015-04-08 08:44
Everything "OK" here
```
OK, but incomplete, skipped, or risky tests!
Tests: 3526, Assertions: 10400, Skipped: 127.

**Comment by Xenopathic** [comment] 2015-04-08 09:07
@MorrisJobke That's due to a bug fixed in a69b752ed05dbe86814bde3f9284b0fa3dd34a07, in PR #13641

**Comment by MorrisJobke** [comment] 2015-04-08 09:57
@Xenopathic I fixed it by increasing the max_nesting_level of xdebug to 1000 :(

**Comment by LukasReschke** [comment] 2015-04-08 09:58
> @Xenopathic I fixed it by increasing the max_nesting_level of xdebug to 1000 :(

I think that's also what we do on Jenkins… :see_no_evil:

**Comment by MorrisJobke** [comment] 2015-04-08 10:00
Nevertheless - I still get following:

```
There were 2 failures:

1) Test\Files\View::testRenameFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:915
/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:877

2) Test\Files\View::testCopyFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:915
/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:881
```

**Comment by PVince81** [comment] 2015-04-08 10:06
I'm working on a fix.
The big nesting is due to $originalStorage being remounted on the root. $originalStorage is already wrapped by storage wrappers, so mounting it again would rewrap it over and over again over time.
See https://github.com/owncloud/core/blob/master/tests/lib/files/filesystem.php#L56

I'm now trying to replace all occurences of `$originalStorage` with a proper FS teardown.

**Comment by PVince81** [comment] 2015-04-08 10:52
Fix is here: https://github.com/owncloud/core/pull/15464

**Comment by PVince81** [comment] 2015-04-08 12:25
@MorrisJobke can you rerun the tests on master locally and see if you still get the failures you mentionned here https://github.com/owncloud/core/issues/15326#issuecomment-90867894 ?

**Comment by MorrisJobke** [comment] 2015-04-08 12:54
@PVince81 The max nesting level thing is gone, but the other failure still exists:

```
There were 2 failures:

1) Test\Files\View::testRenameFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:911
/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:873

2) Test\Files\View::testCopyFailDeleteTargetKeepSource
Failed asserting that true is false.

/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:911
/home/mjob/Projekte/owncloud/master/tests/lib/files/view.php:877
```

**Comment by PVince81** [comment] 2015-04-08 13:12
@MorrisJobke I guess it's your turn now to do some debugging. Tests run fine on my env.

**Comment by rullzer** [comment] 2015-04-08 15:26
I have the same errors locally as @MorrisJobke. I did not do a full debugging session yet. But something is wrong.

Diff with my (hacky) debug code so far: https://github.com/rullzer/core/commit/fa65672d67c7acc362a41cec548a2b129d9659f2

This shows me that
$storage1->filesize('dirtomove/indir1.txt') = 7
$storage1->filesize('dirtomove/indir2.txt') = 18

It also shows me that on strorage 2 I have a quota of 9 and 5 free space (which makes sense).

Now the copy succeeds. And indir1.txt is copied and of the same size.
However indir2.txt does not exists when I get the filesize.


So it is very weird the copy does not return false.


However more spooky stuff is going on. If I get the free space after the copy it is 2. Before it was 5 and now it is 2. While indir1.txt is already 7.


When I'm home again I'll rewrite this a bit more structured and run some more tests. But maybe somebody understands and knows what the problem is ;)

**Comment by butonic** [comment] 2015-04-09 13:39
I also got these two failing tests. I really wonder how Jenkins can not have them. Debugging this led to https://github.com/owncloud/core/pull/15517, which fixes the test according to what it expects. Namely that copying / moving a folder will leave copied files at the target location, even when some files fail. This does change the semantics of the move / copy operation so I am wondering how we can get different results here ...

**Closed** 2015-04-09 16:41 UTC
Labels: bug, showstopper

**Comment by butonic** [comment] 2015-04-10 11:41
@karlitschek backport?

**Comment by karlitschek** [comment] 2015-04-10 13:53
backport is fine. Thanks :+1:

**Comment by MorrisJobke** [comment] 2015-04-10 13:55
Backport: #15539
