### ISSUE TITLE
Cannot redeclare normalizer_normalize()

### ISSUE THREAD

**Issue by asifrasheed6** [owncloud/core#38248] opened 2020-12-24 12:21 UTC
I tried to install own cloud on my raspberry pi, however the webpage never loads. Looking at the Apache2 log I found this:
```
[Thu Dec 24 16:05:12.557991 2020] [mpm_prefork:notice] [pid 17187] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Thu Dec 24 16:05:12.558207 2020] [core:notice] [pid 17187] AH00094: Command line: '/usr/sbin/apache2'
[Thu Dec 24 16:05:20.346612 2020] [php7:error] [pid 17188] [client 176.205.133.161:54454] PHP Fatal error:  Cannot redeclare normalizer_normalize() (previously declared in /var/www/cloud.althafar.me/public_html/lib/composer/symfony/polyfill-intl-normalizer/bootstrap.php:18) in /var/www/cloud.althafar.me/public_html/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 21, referer: http://cloud.althafar.me/
[Thu Dec 24 16:11:52.088252 2020] [php7:error] [pid 17476] [client 176.205.133.161:54462] PHP Fatal error:  Cannot redeclare normalizer_normalize() (previously declared in /var/www/cloud.althafar.me/public_html/lib/composer/symfony/polyfill-intl-normalizer/bootstrap.php:18) in /var/www/cloud.althafar.me/public_html/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 21, referer: http://cloud.althafar.me/
[Thu Dec 24 16:14:21.768790 2020] [php7:error] [pid 17492] [client 176.205.133.161:54468] PHP Fatal error:  Cannot redeclare normalizer_normalize() (previously declared in /var/www/cloud.althafar.me/public_html/lib/composer/symfony/polyfill-intl-normalizer/bootstrap.php:18) in /var/www/cloud.althafar.me/public_html/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 21, referer: http://cloud.althafar.me/
```

### Expected behaviour
OwnCloud setup should show on the browser.

### Actual behaviour
HTTP Error 500

### Server configuration
**Operating system**: Raspberry Pi OS

**Web server:** Apache 2.4.38

**Database:** MySQL 15.1

**PHP version:** 7.3.19

**ownCloud version:** 10.6

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** From the owncloud website

**Comment by asifrasheed6** [comment] 2020-12-25 13:00
So the issue isn't part of older version of own cloud.

**Comment by markusbaker** [comment] 2020-12-26 03:56
Same issue for me today on fresh Ubuntu 20.04 install:

Expected behaviour
OwnCloud setup should show on the browser.

Actual behaviour
HTTP Error 500

Server configuration
Operating system: Ubuntu 20.04

Web server: Apache 2.4.46

Database: MarkiaDB 10.3.25

PHP version: 7.4.13

ownCloud version: 10.6

Updated from an older ownCloud or fresh install: Fresh install with php 8, then downgraded to php 7.4

Where did you install ownCloud from: Manual install on fresh Ubuntu 20.04 installation

**Comment by JammingBen** [comment] 2020-12-30 14:04
Do you have the php-intl extension installed properly? Usually this error happens if that is not the case.

**Comment by asifrasheed6** [comment] 2020-12-30 14:08
Yes I have installed the php-intl extension properly and as I mentioned in a comment earlier, older versions of owncloud doesn't have this issue.

**Comment by ypnos** [comment] 2020-12-30 14:15
I tried to update 10.2 to 10.6 and got the same problem.

Turns out, while php-intl was installed for previous versions of PHP, it was missing on the system for the current version (7.4).

It would be great if the extension could be checked before running into this rather cryptic error. Or having a Troubleshooting page containing this information.

**Comment by JanAckermann** [comment] 2021-01-12 09:51
> It would be great if the extension could be checked before running into this rather cryptic error. Or having a Troubleshooting page containing this information.

Agree, there should be a previous call to check if all extensions are installed.
Installing a fresh owncloud displays these kinds of errors in a proper way while opening the UI

**Comment by JanAckermann** [comment] 2021-01-21 07:20
Should be resolved with:
https://github.com/owncloud/core/pull/38286
https://github.com/owncloud/core/pull/38315

**Closed by JanAckermann** 2021-01-21 07:20 UTC
Labels: bug
