### ISSUE TITLE
Restoring an encrypted file as a share recipient breaks its versions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39664] opened 2022-01-08 03:23 UTC
Seen with 10.9.1RC1 with encryption 1.5.1 (initially disabled)

* admin creates a file shared.txt in his Documents folder
* admin shares the folder with user Alice
* both edit the file several times
* Alice deletes the file. It appears in the trashcan of both users, with all versions info each.

enable masterkey encryption. logout/login all users.

* Alice restores the file from the trashcan.
* Alice inspects the versions: The topmost listed version has a broken thumbnail and cannot be downloaded.
* Alice restores this version. The file is now permanently lost. no other versions can now be restored.

![image](https://user-images.githubusercontent.com/1108546/148629871-87dcb7d5-efc9-4710-90c3-a01eee6f678c.png)

The share owner admin also sees this error, when he tries to edit the file.
Removing the share and re-sharing does not help.

**Comment by JanAckermann** [comment] 2022-01-10 10:52
Reproduced - error is existing

**But this is also existing on 10.8 and 10.9, not a regression**

**Comment by JammingBen** [comment] 2022-01-12 12:45
Note that this error is not occurring due to enabling encryption in between the steps. The issue is also happening when enabling encryption at the beginning.

**Comment by jvillafanez** [comment] 2022-01-27 12:12
It seems the file itself is fine and "could" be downloaded. The problem is the signature verification fails somehow. Bypassing the signature verification (not recommended) works. Running the `occ encryption:fix-encrypted-version` fixes the issue.

I'll try to figure out why the signature verification fails.

**Comment by jvillafanez** [comment] 2022-01-28 12:17
Unless someone has a better idea, I think we should create some tooling to check the encrypted files:
* Comparing decrypted content of any file in ownCloud, including trashbin, versions, external storages, etc.
* Comparing filekeys of any file
* Signature verification (without modification)

Right now, it seems that something goes wrong when we try to restore the file from the trashbin, but we can't ensure that the signature broke when they landed in the trashbin, so the problem could happen before restoring.

**Comment by mrow4a** [comment] 2022-02-07 18:16
maybe stupid but maybe when restoring a file code from `occ encryption:fix-encrypted-version` should be executed?

**Comment by jvillafanez** [comment] 2022-02-08 08:02
For me it isn't clear that the signature gets broken when the file is restored. It might happen when the file is deleted and moved to the trashbin, so then you restore the file "correctly" with the broken signature. The problem is that I'm not sure how we can verify when the signature get broken.

> maybe stupid, but maybe when restoring a file, code from occ encryption:fix-encrypted-version should be executed ?

That's a fix for something that shouldn't happen in the first place. In addition, I'm not sure if it fixes just the file but not the versions.

**Comment by jvillafanez** [comment] 2022-02-24 10:48
https://github.com/owncloud/core/pull/39822 should fix this ticket.

Note that the cause for https://github.com/owncloud/encryption/issues/321 is different. A different PR will fix it.

**Comment by mrow4a** [comment] 2022-02-24 21:17
Ahh true.. nice catch!

**Comment by jvillafanez** [comment] 2022-02-28 12:28
https://github.com/owncloud/core/pull/39822 merged. Closing

**Closed by jvillafanez** 2022-02-28 12:28 UTC
Labels: Type:Bug

**Comment by jnweiger** [comment] 2022-05-12 20:18
Confirmed fixed in 10.10.0 RC2
