### ISSUE TITLE
ownCloud 9: Share filters in Files App are empty

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#23000] opened 2016-03-09 09:45 UTC
### Steps to reproduce
1. Upgrade from ownCloud 8.2.2 to 9.0
2. Share a file by link or with another user
3. Open the view "shared by link" or "shared by me"

### Expected behaviour
All shared files and folders are listed.

### Actual behaviour
All views (shared with me, shared by me, shared by link) are always empty.

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** "No errors have been found."

**List of activated apps:**
Calendar 1.0
Contacts 1.0

**Comment by LukasReschke** [comment] 2016-03-09 09:47
cc @owncloud/sharing

**Comment by rullzer** [comment] 2016-03-09 09:53
Does your log tell you anything?

**Comment by BenS89** [comment] 2016-03-09 10:01
yes, maybe [#22997](https://github.com/owncloud/core/issues/22997) could be the cause?

**Comment by PVince81** [comment] 2016-03-09 14:31
Closing as duplicate of https://github.com/owncloud/core/issues/22997

**Comment by PVince81** [comment] 2016-03-09 14:31
Note that these filter views are using the OCS Share API, so they are empty because of the server error.

**Closed by PVince81** 2016-03-09 14:31 UTC
Labels: bug, feature:sharing
