### ISSUE TITLE
'Shared' text overlaps long filenames.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21802] opened 2016-01-20 12:49 UTC
### Steps to reproduce

1. Upload a file with a long name.
2. Having a wide screen (left sidebar appears) click on the file, right sidebar will open.
3. Share the file with another user.

### Expected behaviour

'Shared' caption doesn't overlap file name. Instead it has a white background.

### Actual behaviour

'Shared' text overlaps the filenames making it blurry.

![screen shot 2016-01-20 at 13 11 26](https://cloud.githubusercontent.com/assets/9048796/12449285/74953c0a-bf7c-11e5-9247-aa132d4f8ccb.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":"Enterprise"}
(current master)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by MorrisJobke** [comment] 2016-01-20 12:55
cc @owncloud/designers

**Comment by jancborchardt** [comment] 2016-01-20 13:45
Duplicate of https://github.com/owncloud/core/issues/19790, closing. @SergioBertolinSG please review the PR at https://github.com/owncloud/core/pull/19873

**Closed by jancborchardt** 2016-01-20 13:45 UTC
Labels: bug, design, regression, sev4-low
