### ISSUE TITLE
[7.0.4.2 -> 8.0.0] db update fails

### ISSUE THREAD

**Issue by jeekajoo** [owncloud/core#14006] opened 2015-02-09 20:32 UTC
Hi,
I'm having trouble while updating to last version from 7.0.4.2 (opensuse packages https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud)

backend: mysql
dbtableprefix: mysecuredprefix
error:
```javascript
su www-data -c "/usr/bin/php occ upgrade" -s /bin/bash
Turned on maintenance mode
An exception occurred while executing 'CREATE TABLE oc_mysecuredprefix_appconfig_1wx1t82s2y5jg (`appid` VARCHAR(32) DEFAULT '' NOT NULL, `configkey` VARCHAR(64) DEFAULT '' NOT NULL, `configvalue` LONGTEXT DEFAULT NULL, INDEX oc_of9a7tlefxwb5 (`configkey`), INDEX oc_j8jrmaayrrcmf (`appid`), PRIMARY KEY(`appid`, `configkey`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_mysecuredprefix_appconfig_1wx1t82s2y5jg' already exists
Turned off maintenance mode
Update failed
```
I disabled ALL 3rd party apps before proceeding.
Thanks

**Comment by DeepDiver1975** [comment] 2015-02-09 21:52
@icewind1991 can you please have a look? THX

@jeekajoo this issue is related to our migration tests - feel free to skip these test by using the option --skip-migration-test

A database backup is mandatory for this step - THX

**Comment by jeekajoo** [comment] 2015-02-09 21:59
used --skip-migration-test and got this:
```
Turned on maintenance mode
Updated database
PHP Fatal error:  Class 'OCA\Files\App' not found in /var/www/owncloud/apps/files_sharing/appinfo/app.php on line 37
```

**Comment by DeepDiver1975** [comment] 2015-02-09 22:13
@jeekajoo looks like the files app was missing in the packages - seems to be fixed

````
owncloud (8.0.0-2) stable; urgency=low

  * subpackage owncloud-app-files was missing for debian/ubuntu
    fixed https://github.com/owncloud/core/issues/13991

 -- Jürgen Weigert <juewei@linux-z0ae.fritz.box>  Mon, 09 Feb 2015 17:35:36 +0100

**Comment by PVince81** [comment] 2015-02-09 22:13
Did you upgrade by deleting everything but "data" and "config" ? Extracting the tarball over existing code can cause such strange issues and is not supported.

**Comment by PVince81** [comment] 2015-02-09 22:14
Ah, packages. Never mind then.

**Comment by jeekajoo** [comment] 2015-02-09 22:22
upgraded to 8.0.0-3
```
Turned on maintenance mode
Updated database
Turned off maintenance mode
Update successful
```

@DeepDiver1975 thanks !

**Comment by DeepDiver1975** [comment] 2015-02-09 22:24
@jeekajoo I'm glad to hear this is working out for you now - let me reopen this to give @icewind1991 a chance to have a look a the migration issue

**Comment by oparoz** [comment] 2015-03-15 21:56
On 8.0.2
Updated an app version
oC redirects me to the update page
I click on update
Same exception message as the OP, same engine, same charset.
Database: MariaDB 10

**Comment by DeepDiver1975** [comment] 2015-03-30 09:39
> When using --skip-migration-test, the process ends with zend_mm_heap corrupted

@oparoz seems to be a different issue - please open a new issue if you are still running into this issue

**Comment by DeepDiver1975** [comment] 2015-03-30 09:39
Root cause for that db issue still unknown -> 8.0.4

**Comment by oparoz** [comment] 2015-03-30 13:43
@DeepDiver1975 - The issue has already been reported, but the backport is missing: https://github.com/owncloud/core/issues/9885

**Comment by DeepDiver1975** [comment] 2015-06-17 13:34
@VicDeo didn't you have a look at a similar issue recently? please have a look - thx

**Comment by VicDeo** [comment] 2015-06-17 14:10
@DeepDiver1975 
yes, `Base table or view already exists` for custom prefixes is already known
I was a slowpoke in this case and just tested an existing solution. 

Fixed for master and stable8:
master https://github.com/owncloud/core/pull/14660
stable8 https://github.com/owncloud/core/pull/16421
Closing as a duplicate

**Closed** 2015-06-17 21:20 UTC
Labels: bug, update
