### ISSUE TITLE
Updating to 10.0.3 - Syntax error or access violation: 1118 Row size too large

### ISSUE THREAD

**Issue by InDaCloudz** [owncloud/core#29472] opened 2017-11-06 16:34 UTC
Update to 10.0.3
Server configuration

Ubuntu 16.04
PHP 7.0.15-0ubuntu0.16.04.4
Apache/2.4.18
MySQL Ver 14.14 Distrib 5.7.17

Are you using encryption: yes
Are you using an external user-backend, if yes which one: No

It's a fresh install updated directly from 9 to 10, so impossible to access the admin page.

ownCloud will be updated to version 10.0.3
These apps will be updated:

Activity (activity)
WebDAV (dav)

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_activity CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

Preparing update
Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_activity CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by kdslkdsaldsal** [comment] 2017-11-06 17:00
Closing as a duplicate of https://github.com/owncloud/core/issues/27755

**Closed by kdslkdsaldsal** 2017-11-06 17:00 UTC
