### ISSUE TITLE
PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/lib/private/user.php on line 241

### ISSUE THREAD

**Issue by Biopticon** [owncloud/core#13040] opened 2014-12-27 22:19 UTC
After I set up encryption in Apps, when I tried to logon Owncloud I started getting "Initial encryption is running... Please try again later" message, and then the browser would show a white blank screen. This has been going on more than a day. I thought, since I have many files already synched, it would take a long time to encrypt all of them. But after I restared the owncloud server, although the browser login keeps reporting the message, the owncloud client running on windows, cannot connect due to a server internal error. I can turn the encryption off if I can login to owncloud. In this thread, there are discussions on this problem, but I did not understand if there was a solution. 

Owncloud version 7.0.4-3
Apache 2.2-22
Php5 5.4.35
MySql
I am using external storage for the owncloud data folder.

I can provide more diagnostic information if you guide me.

Ownlcoud client running on Win 7:
Error downloading https://xxx/owncloud/remote.php/webdav/ -server replied:Internal Server Error 

owncloud.log:
{"reqId":"549edd3c35f24","app":"PHP","message":"Call to a member function getUID() on a non-object at \/var\/www\/owncloud\/lib\/private\/user.php#241","level":3,"time":"2014-12-27T16:24:28+00:00","method":"PROPFIND",$

apache2 log;
[Sat Dec 27 11:55:56 2014] [error] [client 192.168.1.1] PHP Fatal error:  Call to a member function getUID() on a non-object in /var/www/owncloud/lib/private/user.php on line 241

And php-errors.log is empty.

Thank you for any help.

**Comment by PVince81** [comment] 2015-01-09 10:14
How many files did you have ? If you have lots of files it can take a while.
To see whether it's still running, check the network console of the browser and see if there is a long-running pending call when you decrypt files (the call is to `decryptall.php`).
If that call is still pending, it means that it's probably still decrypting your files.
If however it is not pending, then check its response and see if there is an error message.

After this, are you still getting the getUID() error ?
Did you have the external storage app enabled ?

**Comment by Biopticon** [comment] 2015-01-11 19:02
Hello Vincent,
There must be many files. The Owncloud Client wrongly reports used space in the storage as 78GB, but phpmyadmin  and command "df -h" both report 84GB. I had stopped encrypting files a while ago in order to be able to login to the owncloud server. But I had run decrypting many days before this. I started again today. But since there is no progress indicator for this process I am not sure what's going on. I tried running decryptall.php   (https://www.myserver.com/owncloud/decryptall.php), but I am getting 404 error. How shall I run this, where is the network on the console? Yes, I had set external storage app enabled.

**Comment by PVince81** [comment] 2015-01-12 10:01
Do not run "decryptall.php" manually.
Try decrypting the files from the "Personal" settings page.
Before you click "Decrypt", open the Chrome Network console.
Then click "Decrypt"
Observe the console and see the line with "decryptall.php".
Is that line stuck on "Pending" ? Or does it finish fast and/or becomes red with an error ?

**Comment by Biopticon** [comment] 2015-01-12 15:27
Hello Vincent,

Wow. I did not know that you could do all that! I started network console, then decrypting. See teh screen shot.

![capture](https://cloud.githubusercontent.com/assets/6756426/5705154/06cd2d7a-9a45-11e4-84f2-135d54655570.JPG)

But I cannot see any entry in the page to do with decrypting? I saved the har file. How can I attach it here if you need to have a look?

**Comment by PVince81** [comment] 2015-01-12 15:35
Did you start the network console before clicking "Decrypt all Files" ?
The best way is to clear the network console before clicking "Decrypt all Files", then click the button.
Something should appear.

**Comment by Biopticon** [comment] 2015-01-12 19:05
Hello Vincent,
This afternoon around noon the decrypting of files stopped. there is no more orange warning message on the owncloud (OC) console. It hopefully means that all the encrypted files were now decrypted. This is great. Thank you. I just needed patience.  But I could not test what you suggested with the Networking console. And I am afraid to start encryption again with the fear that I cannot log in back to OC until the problem is resolved. But I have to use encryption as soon as we have a new version.of OC.

When I tried to log in to my OC server through Chrome, I got "Privacy error, "NET::ERR_CERT_AUTHORITY_INVALID" message. I was able to log in by going through the advanced setup. After logged in successfully, on the address window of Chrome, the https: was crossed by a red line. This means that the link I had was not secure, I think. This does not happen if I use FireFox to log in to OC. So I am puzzled by this. Do I have to do something different to log in to the OC server when I use Chrome instead?  

Thank you again for your help.

**Comment by PVince81** [comment] 2015-01-13 10:38
@Biopticon the certificate issue you're having is probably something else, not related to ownCloud. Please check your web server config.

**Comment by PVince81** [comment] 2015-01-13 14:20
@Biopticon maybe you're right: the decryption process took too long every time and PHP timed out. So running it several times probably helped to complete the process.
So this is more about finding a way to decrypt files without running into a PHP timeout.

I guess you're not getting "Call to a member function getUID()" any more now ?

**Comment by PVince81** [comment] 2015-01-13 14:21
PHP timeout for decryption has been reported here already: https://github.com/owncloud/core/issues/12495

**Comment by Biopticon** [comment] 2015-01-13 14:29
Hello Vincent,

It seems that all is working, I am not getting any errors anymore. Thank you.  After many tries I believe all my files were decrypted. But I have to encrypt them after the problem is resolved. Thank you for your help.

**Comment by Biopticon** [comment] 2015-01-13 14:37
Vincent,
It would be very helpful if there is a progress indicator in the decryption/encryption section of the OC dashboard. Since OC seems already know the encrypted files, it might be possible to report encryption/decryption process so that we can avoid unnecessary worries!

**Comment by PVince81** [comment] 2015-01-13 14:39
Also found this https://github.com/owncloud/core/issues/6949

**Comment by PVince81** [comment] 2015-01-13 15:25
Closing as duplicate of https://github.com/owncloud/core/issues/12412

The error you had initially with "getUID()" appears when the encryption migration was somehow stuck.

**Closed by PVince81** 2015-01-13 15:25 UTC
Labels: bug
