### ISSUE TITLE
Code Integrity Check shows problems after web updater has run

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#23857] opened 2016-04-08 10:25 UTC
### Steps to reproduce
1. prepare the instance for web updating (permissions)
2. run th updater via the web (success)

### Expected behaviour
No message about problems with code integrity check

### Actual behaviour
Tell us what happens instead
![image](https://cloud.githubusercontent.com/assets/3321281/14381022/6f4e7fd2-fd83-11e5-9b43-9df2e60fa21e.png)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.2

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
9.0.1.3 (daily)

**Updated from an older ownCloud or fresh install:**
daily update

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

````
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/sabre/dav/lib/DAV/Version.php
		- 3rdparty/sabre/dav/lib/DAV/CorePlugin.php
		- 3rdparty/sabre/dav/lib/CardDAV/Backend/PDO.php
		- 3rdparty/sabre/dav/CHANGELOG.md
		- 3rdparty/composer/installed.json
		- 3rdparty/composer/autoload_classmap.php
		- 3rdparty/composer.lock
		- 3rdparty/composer.json
		- updater/src/Command/DetectCommand.php
		- updater/src/Controller/DownloadController.php
	- EXTRA_FILE
		- updater/update.log
		- _oc_upgrade/100.0.0.0/owncloud/config/.htaccess
		- _oc_upgrade/100.0.0.0/owncloud/themes/README
		- _oc_upgrade/100.0.0.0/owncloud/themes/example/core/css/styles.css
		- _oc_upgrade/100.0.0.0/owncloud/themes/example/core/img/logo.png
...
````

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
{
    "system": {
        "instanceid": "oci1ewzyz3i0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 0,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

### Logs
No correspondend log entries

**Comment by ronnicek** [comment] 2016-04-08 21:22
I had also similar problem, so I delete everything except config and data folder and unzip everything again. Rescan and everything looks ok now.

**Comment by nickvergessen** [comment] 2016-04-11 13:23
@mmattel can you retry if this is re-producable?

**Comment by mmattel** [comment] 2016-04-11 14:54
Before I start, shall I delete the contents of the updater/ folder ?

**Comment by koehn** [comment] 2016-04-11 18:27
I've bee having the same issue on Ubuntu 14.04 with the OC packages. I had no integrity problems prior to the upgrade from 9.0 to 9.0.1. 

```
Results
=======
- core
	- EXTRA_FILE
		- 3rdparty/mcnetic/phpzipstreamer/ZipStreamer.php
		- test.php
		- core/doc/admin/_sources/configuration_server/performance_tuning.txt
		- core/doc/admin/configuration_server/performance_tuning.html
		- core/doc/admin/_images/video_firstminute.png
		- core/doc/admin/_images/sharing-user.png
		- core/doc/admin/_images/sharing-user-local.png
		- core/doc/admin/_images/sharing-admin.png
		- core/doc/admin/_images/remote_shares.png
		- core/doc/admin/_images/install-wizard-advanced.png
		- core/doc/admin/_images/smb-create-share.png
		- core/doc/admin/_images/smb-files-view.png
		- core/doc/admin/_images/smb-user-share.png
		- core/skeleton/ownCloudUserManual.pdf
- files_sharing
	- EXTRA_FILE
		- lib/exceptions.php
```

**Comment by teslasmoustache** [comment] 2016-04-11 20:46
similar error with these files:

`Results
=======
- core
	- EXTRA_FILE
		- .rnd

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
`

**Comment by nickvergessen** [comment] 2016-04-12 06:45
> sorry about the crap formatting.

Fixed formatting with triple `


Try deleting the files:
 * 3rdparty/mcnetic/phpzipstreamer/ZipStreamer.php
 * core/doc/
 * apps/files_sharing/lib/exceptions.php

**Comment by Salzi** [comment] 2016-04-13 07:54
I just upgraded from owncloud 9 to owncloud 9.0.1 with the webinterface. Now I have the same error as @mmattel in the first post.

**Comment by mmattel** [comment] 2016-04-13 08:24
@nickvergessen 
> Before I start, shall I delete the contents of the updater/ folder ?

Delete or not to delete before I run the update again, or is this already obsolete by your PR?

**Comment by nickvergessen** [comment] 2016-04-13 08:35
* If a file is INVALID_HASH make sure to upload it again to the server
* If a file is FILE_MISSING make sure to upload it to the server
* If a file is EXTRA_FILE make sure to delete it from the server

**Comment by Salzi** [comment] 2016-04-13 08:38
I replaced the listed files by the original from a new downloaded archive. Now its working but to me it still looks like bug in the updater.

**Comment by LukasReschke** [comment] 2016-04-13 08:53
This is a bug in the updater…

**Comment by LukasReschke** [comment] 2016-04-13 08:53
cc @jospoortvliet @karlitschek The bug from the mail…

**Comment by LukasReschke** [comment] 2016-04-13 08:58
cc @VicDeo

**Comment by mmattel** [comment] 2016-04-13 09:29
@nickvergessen 
hmmmm....
I never touched the updater folder. This folder is managed by the updater process and not manually by the admin (me). Therefore your suggestion is complicated to handle as I do not know which files do have which state, or are valid or should be deleted afterwards but have not ect. I just see the complaint from ownCloud based on an ownCloud process...

**Comment by nickvergessen** [comment] 2016-04-13 09:30
@mmattel just wait for a patch from lukas then, as he seems to be digging into this now

**Comment by PVince81** [comment] 2016-04-21 16:20
@LukasReschke is https://github.com/owncloud/core/issues/24134 the mighty awaited patch ?

If yes, it was merged already and should run in the next git update on stable9 or daily.

**Comment by LukasReschke** [comment] 2016-04-21 16:22
It is. – But git update won't do as they are not signed :)

**Comment by PVince81** [comment] 2016-04-25 15:49
Waiting for @owncloud/qa to verify with the dailies

**Comment by PVince81** [comment] 2016-04-29 13:55
@jvillafanez have you seen this in your latest tests ?

Else let's close it as solved.

**Comment by PVince81** [comment] 2016-05-02 12:07
I tested updating from 9.0.1 tarball to 9.0.2RC2 tarball (had to hack updater URL), and it worked fine. No more integrity check warnings.

Same when updating from 9.0.1 tarball to stable9 daily. No more warnings.

Closing as solved.

**Closed by PVince81** 2016-05-02 12:07 UTC
Labels: bug, feature:code-signing-integrity, feature:update, sev1-critical

**Comment by davitol** [comment] 2016-05-03 06:58
> Same when updating from 9.0.1 tarball to stable9 daily. No more warnings.

:+1:

**Comment by bcutter** [comment] 2016-05-05 14:32
I´ve been directed here when asking for the reason the updater app still doesn´t offer an upgrade from 8.2.3 to v9.0.1 or v9.0.2. I read the thread, but couldn´t find an appropriate answer. Will the updater app ever work and provide the update to the v9 release? I´m waiting for weeks now...

**Comment by jospoortvliet** [comment] 2016-05-28 09:33
There are still issues with 9.0.2 at the moment. There might be a 'silent' update to 9.0.2 that fixes it, if so we'll enable the updater soon. If we don't do that, it will be 9.0.3 that should allow the updater to be turned on.

**Comment by dg1sek** [comment] 2019-02-12 15:34
Similar issue when upgrading dockerized nextcloud from 15.0.2 to 15.0.4.

Root cause seems to be that the /var/www/html/... is in a docker mounted volume that is not upgraded when I update to a more recent nextcloud with docker-compose pull.

Only fix I can find is to open a shell into the container and then manually download the files with the wrong checksum. But this seems not a good way of proceeding. Would be preferable to have the application detect that the docker volume needs updating.
