### ISSUE TITLE
upload of files named .htaccess not possible

### ISSUE THREAD

**Issue by tapete** [owncloud/core#25586] opened 2016-07-23 10:51 UTC
### Steps to reproduce
1. Upload file named .htaccess using the webinterface
2. File can not be uploaded, error occurs: "Fehler beim Hochladen der Datei ".htaccess": Hochladen fehlgeschlagen. Die hochgeladene Datei konnte nicht gefunden werden."
3. 

### Expected behaviour
File uploaded successfully

### Actual behaviour
Error occurs

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
apache newest version

**Database:**
Mysql

**PHP version:**
7

**ownCloud version:** (see ownCloud admin page)
9.1 (issue is relevant for each 9.x version)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
zip

**Signing status (ownCloud 9.0 and above):**
OK

**List of activated apps:**
standard
```

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
### Client configuration
**Browser:**
each

**Operating system:**
each

#### Web server error log
```

Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
{"reqId":"E3uSHGlrEtbWRlkWYZH8","remoteAddr":"192.168.2.101","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/test\\\/ocl91\\\/own...', Resource id #131, Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), false)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1034): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('test\\\/ocl91\\\/ownc...', Resource id #131, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":108,\"User\":\"admin\"}","level":4,"time":"2016-07-23T10:40:24+00:00","method":"PUT","url":"\/remote.php\/webdav\/test\/ocl91\/owncloud\/.htaccess","user":"admin"}

**Comment by RealRancor** [comment] 2016-07-23 11:30
@tapete Duplicate of https://github.com/owncloud/core/issues/6188 where you can find all necessary infos about the security implications when allowing users to upload .htaccess files and how to allow it anyway on your own risk.

**Closed** 2016-07-25 07:53 UTC
