### ISSUE TITLE
[IE9] [Sharing by link] Cannot modify the password once it is set

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16506] opened 2015-05-21 14:50 UTC
### Steps to reproduce
1. Send a file to a user by link with password protection
2. Browse away and try to modify the password.

### Expected behaviour
THe user should be able to delete the password *

### Actual behaviour
The cursor always moves to the beginning and it is not possible to modify the password. The only option is unmark and mark the checkbox.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9
![captura de pantalla 2015-05-21 a las 16 44 48](https://cloud.githubusercontent.com/assets/10596560/7751190/fc1684a4-ffd8-11e4-82fa-c7608dd9d351.png)

**Comment by rullzer** [comment] 2015-05-22 06:57
I can't reproduce this on master. Probably an IE bug..

**Comment by davitol** [comment] 2015-05-22 07:06
reproduce in IE and Firefox for Mac

**Comment by rullzer** [comment] 2015-05-22 07:10
What I did

1. Create link share
2. create password
3. navigate to other folder
4. navigate back
5. try to edit password.

I assume those are all the steps?

**Comment by rullzer** [comment] 2015-05-22 07:10
@LukasReschke could you verify on your mac?

**Comment by davitol** [comment] 2015-05-22 07:46
![deletepwd2](https://cloud.githubusercontent.com/assets/10596560/7766228/5cc5b930-0067-11e5-80b5-b37d63aac8a2.gif)

**Comment by rullzer** [comment] 2015-05-22 11:23
Thanks that makes it more clear. Although I still can't reproduce it.
Could you check if it is only a visual issue? So if you try to enter text and hit enter.. does the password get updated?

**Comment by davitol** [comment] 2015-05-25 07:12
@rullzer It is only a visual issue. You can change the pwd if you write it down from the beginning.

![modpwd2](https://cloud.githubusercontent.com/assets/10596560/7793355/2cf5f630-02be-11e5-9c0f-d03de3da8f1d.gif)

**Comment by PVince81** [comment] 2015-09-22 08:10
I see it's IE9, possible related to all the other password field placeholder shim issues that exist for IE9.

**Comment by PVince81** [comment] 2015-10-16 09:59
I tried upgrading the placeholders library locally but it doesn't fix this issue.

I think it's not worth spending the time trying to work this around for this minor IE9 issue.
Please note that if we wanted we could remove the placeholder completely, but then the field would always be blank and the visual affect would be even worse.

=> closing as won't fix

**Closed by PVince81** 2015-10-16 09:59 UTC
Labels: browser:ie, bug, feature:federated-cloud-sharing, sev4-low
