### ISSUE TITLE
files:scan for a user with only external storage scans ALL files

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#17943] opened 2015-07-29 07:48 UTC
Hi,

I have a medium-size OC 8.1.0 with several users. One, "Backups", is only there to group 2 items of local external storage so that I can have a nightly cron job do a "files:scan" only on these two items (which also get updated nightly before the files:scan).

This is because - in earlier versions at least - OC did not notice the new file modification times on the local external storage and the GUI was telling me wrong info - it appeared that my backup jobs had not run when in fact they had. The files:scan cured that problem. Q: Is that still neccessary or have improvements made it unneccessary?

Apart from that there is now a bug: **Instead of just the two items of local external storage which are accessible to the "Backups" user, now ALL the files stored in OC are rescanned!**

Is this problem solved with [fix 17077](https://github.com/owncloud/core/pull/17077) or is it a different issue that still needs addressing?

Cheers and Thanks,
Tim

PS In my own files I noticed there are many many files under "gallery" subdir, but I disabled the pictures app a year ago! How can I safely delete all those superfluous gallery files?

**Comment by PVince81** [comment] 2015-07-29 08:41
@timreeves the problem you have is a duplicate of https://github.com/owncloud/core/issues/17414 and will be fixed in 8.1.1 with https://github.com/owncloud/core/pull/17659

If you disabled the pictures app you can just manually delete the "gallery" folders with a "find" command.

**Closed by PVince81** 2015-07-29 08:41 UTC
