### ISSUE TITLE
Version dropdown not removed after restoring a file

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#14559] opened 2015-02-26 21:18 UTC
### Steps to reproduce

1. Install owncloud 
2. upload or create a text file
3. edit the file a couple of time so that there are a few versions
4. click on the version link for the file
5. select one of the version and click the restore link

### Expected behaviour

The file is restored and the version dropdown goes away

### Actual behaviour

The file is restored but the version dropdown remains.  This makes it seem that the restore didn't happen so I end up clicking it multiple times getting an error message that the file can't be restored because I'm trying to restore a file that has already been restored.

This is a regression from 7.

![p295](https://cloud.githubusercontent.com/assets/8480343/6402096/02fcdb62-bdd3-11e4-9647-3ae0099762b9.PNG)

### Server Host info:

CentOS release 6.6 (Final)
PHP 5.4.36

### Server configuration

ownCloud Enterprise Edition 8.0 (daily) Build:2015-02-26T05:30:39+00:00 bc1418156339d4e61fe81bd1474f91555432ca00

**Comment by LukasReschke** [comment] 2015-02-26 21:26
Completely broken on stable8 and master – awesome :angry: 

> An exception occurred while executing &#039;UPDATE &quot;oc_filecache&quot; SET &quot;path&quot; = ?, &quot;path_hash&quot; = ?, &quot;name&quot; = ?, &quot;parent&quot; =? WHERE &quot;fileid&quot; = ?&#039; with params [&quot;files\/welcome.txt&quot;, &quot;c49a144e772727f51b75705170e88a43&quot;, &quot;welcome.txt&quot;, &quot;3&quot;, 15]:
> SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.storage, oc_filecache.path_hash

**Comment by LukasReschke** [comment] 2015-02-26 21:31
@DeepDiver1975 @icewind1991 Big fun! – Let me bisect…

**Comment by LukasReschke** [comment] 2015-02-26 21:33
V8.0.0 broken as well…

> Exception: {"Message":"An exception occurred while executing 'UPDATE \"oc_filecache\" SET \"path\" = ?, \"path_hash\" = ?, \"name\" = ?, \"parent\" =? WHERE \"fileid\" = ?' with params [\"files\\\/welcome.txt\", \"c49a144e772727f51b75705170e88a43\", \"welcome.txt\", \"3\", 23]:\n\nSQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.storage, oc_filecache.path_hash","Code":0,"Trace":"#0 \/Users\/lreschke\/Programming\/owncloud\/stable8\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/Users\/lreschke\/Programming\/owncloud\/stable8\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE \"oc_file...', Array)\n#2 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/db\/statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/db.php(141): OC_DB_StatementWrapper->execute(Array)\n#4 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/files\/cache\/cache.php(424): OC_DB::executeAudited('UPDATE `*PREFIX...', Array)\n#5 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/files\/cache\/updater.php(107): OC\\Files\\Cache\\Cache->move('files_versions\/...', 'files\/welcome.t...')\n#6 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/files\/view.php(546): OC\\Files\\Cache\\Updater->rename('\/files_versions...', '\/files\/welcome....')\n#7 \/Users\/lreschke\/Programming\/owncloud\/stable8\/apps\/files_versions\/lib\/storage.php(273): OC\\Files\\View->rename('files_versions\/...', 'files\/welcome.t...')\n#8 \/Users\/lreschke\/Programming\/owncloud\/stable8\/apps\/files_versions\/ajax\/rollbackVersion.php(10): OCA\\Files_Versions\\Storage::rollback('\/welcome.txt', 1424986077)\n#9 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/route\/route.php(135) : runtime-created function(1): require_once('\/Users\/lreschke...')\n#10 [internal function]: __lambda_func(Array)\n#11 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/private\/route\/router.php(250): call_user_func('\\x00lambda_1758', Array)\n#12 \/Users\/lreschke\/Programming\/owncloud\/stable8\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/files_ver...')\n#13 \/Users\/lreschke\/Programming\/owncloud\/stable8\/index.php(36): OC::handleRequest()\n#14 {main}","File":"\/Users\/lreschke\/Programming\/owncloud\/stable8\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractSQLiteDriver.php","Line":47}

**Comment by LukasReschke** [comment] 2015-02-26 22:35
Okay, I debugged this and it is caused by a change of behaviour in  `\OC\Files\View::rename`, the following code will throw an exception in master but not in stable7:

```php
$view = new \OC\Files\View('/admin/');
$view->touch('files_versions/oldVersion.txt');
$view->touch('files/original.txt');
$view->rename('files_versions/oldVersion.txt', 'files/original.txt');
```

@DeepDiver1975 @icewind1991 That looks REALLY bad to me. I mean I am not the storage expert here but having breaking behaviour that breaks potentially a lot of other stuff? – I am not qualified to fix this on my own and any assistance would be utmost welcome.

What we need to clear:

1. Is the old behaviour (working) the expected one?
2. Can we fix this error for stable8 and master and when was this introduced?
3. What could be other problems caused by this behaviour?

**Comment by LukasReschke** [comment] 2015-02-26 22:53
Regression has been introduced with https://github.com/owncloud/core/commit/ce0aa02aacee6b4e2641bdb1666f5650507ed28a

**Comment by LukasReschke** [comment] 2015-02-26 23:04
Nope, was https://github.com/owncloud/core/pull/13667

**Comment by LukasReschke** [comment] 2015-02-26 23:22
@icewind1991 Please take a look at above test script and the pointed out PR. Thanks.

**Comment by LukasReschke** [comment] 2015-02-26 23:25
Was atually also mentioned at https://github.com/owncloud/core/pull/13667#issuecomment-71634431 :see_no_evil:

**Comment by icewind1991** [comment] 2015-02-27 13:28
This wasn't actually caused by #13667, but that PR did trigger an older bug.

Fix here: #14575

**Comment by MorrisJobke** [comment] 2015-02-27 16:12
#14575 needs to be backported to stable8

**Comment by karlitschek** [comment] 2015-02-27 16:17
please backport :+1:

**Comment by MorrisJobke** [comment] 2015-02-27 16:46
Backport is in #14584

**Comment by PVince81** [comment] 2015-02-27 18:00
Backport was merged, closing

**Closed by PVince81** 2015-02-27 18:00 UTC
Labels: 5 - To review, bug, Regression, sev2-high, showstopper

**Comment by maxmitch** [comment] 2015-09-18 19:13
This is the most annoying feature!
