### ISSUE TITLE
When downloading from web interface eats up the memory (8.0.2)

### ISSUE THREAD

**Issue by Babzsak** [owncloud/core#15018] opened 2015-03-18 22:30 UTC
### Steps to reproduce
1. Log in to owncloud web interface
2. select a folder with e.g. 1gb data in it and download it (click on the download icon - so a .zip archive of the folder will be downloaded)
3. watch what happens with the memory usage

### Expected behaviour
Normally - I would expect 10 - 30 % increase in memory usage at such case, and after the download normally the memory drops down to normal stage

### Actual behaviour
The folder I've tested this bug was about 1.9GB and the memory usage increased from 1.2 GB to about 3.7 and after the download has finished the usage only increased 
**************** UPDATE ******************
After I have done some investigation in the topic, I've found out that probably during the sreaming process the cached chunks stay there in the cache - so the problem is with the stream caching /emptying in my opinion

### Server configuration
**Operating system**: ubuntu 14.04 server

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** Mysql (MongoDB)

**PHP version:** PHP 5.5.9-1ubuntu4.7 (cli) (built: Mar 16 2015 20:47:39)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

**ownCloud version:** 8.0.2

**Updated from an older ownCloud or fresh install:** 8.0.1

**List of activated apps:** - 

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxxxxxxxxx',
    1 => 'xxxxxxxxxx',
    2 => 'xxxxxxxxxxx',
    3 => 'xxxxxxxxxxxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'xxxxxxxxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'logtimezone' => 'Europe/Berlin',
  'logfile' => '/var/log/owncloud.log',
  'loglevel' => '2',
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'forceSSLforSubdomains' => false,
);
config.php (END)

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla 36.01

**Operating system:** Windows 7 64bit

#### Web server error log

xxx.xxx.xxx.xxx - - [18/Mar/2015:23:17:32 +0100] "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=xxxxxxxxx HTTP/1.1" 200 27750192 "https://xxx.xxxxxx.xxx/owncloud/index.php/apps/files?dir=%2F" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0"

#### ownCloud log (data/owncloud.log)
.......
{"reqId":"54e878b516701","app":"core","message":"Adding default user backend wordpress.","level":0,"time":"2015-02-21T12:23:17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54e878b516701","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/user_wordpress\/lib\/wordpress.class.php#104","level":3,"time":"2015-02-21T12:23:
17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54e878b516701","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/user_wordpress\/lib\/wordpress.class.php#104","level":3,"time":"2015-02-21T12:23:
17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54e878b516701","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/user_wordpress\/lib\/wordpress.class.php#104","level":3,"time":"2015-02-21T12:23:
17+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"54e878b516701","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/owncloud\/apps\/user_wordpress\/lib\/wordpress.class.php#104","level":3,"time":"2015-02-21T12:23:
......
(but I suppose the error in the owncloud.log has not much to do with this issue)

output of free -h 

before:

             total       used       free     shared    buffers     cached
             3,9G       1,1G       2,7G       117M        39M       437M

after:

             total       used       free     shared    buffers     cached
			 3,9G		 3,7G		117M       125M       4,6M       2,9G

**Comment by RealRancor** [comment] 2015-03-18 23:21
Consider using something like: 

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html

when handling such large files. The error messages itself should be reported to the issue tracker of the 3rdparty user_wordpress app.

**Comment by Babzsak** [comment] 2015-03-19 06:23
The manual says: "Controlled file serving does not work for generated zip files. This is due to zip files being generated and streamed back directly to the client." This happened while downloading a whole folder - which is originally not a zipped folder - so the server zipped it and served it to the client. Does it still have a sense to set the downloads only for static file serving?

**Comment by PVince81** [comment] 2015-03-19 21:01
I think @RealRancor misunderstood the use case.
Static file serving will not help with the ZIP stuff.

Since OC 7, the zip file is built and streamed to the client on the fly, so I don't see why this would suddenly eat that much memory. Something to investigate.

CC @McNetic

**Comment by sulaweyo** [comment] 2015-05-09 06:24
I have the same issue on my installation OC8.0.3 (ArchLinux, lighttpd), basically it just happens to be a problem later. I can download 10GB zips with no real problem but if a user gets to the point of actually selecting 40GB+ things get messy. It does not actually look like a memleak as the memory is freed again but if almost the whole system is moved to swap things start to get slow.

Imho there should be a configurable limit for the max total size before the files are handed over to ZipStreamer. If the total of the files is over that limit it should pop up an error message.

**Comment by McNetic** [comment] 2015-05-10 22:26
As more users seem to be having this problem, I'll try to investigate to cause of it.
I tested Zipstreamer with big files many times (of course), and have never observed any such problem, not in command line tests nor in owncloud. I just tested with big streamed zip files again in my 7.0.5 production box and my git test environment (a few weeks old, pre 8.1). Both don't increase memory usage when streaming big zip files.
Technically, Zipstreamer reads the input files in chunks of about 1 MB, and writes them to output immediately (or should I say it should work like this)? At the moment, I can only imagine that a different caching mechanism caches the results before sending them to the client; as I don't know very much about owncloud (aside from zipstreamer) and/or possible php caching mechanisms, I have no idea where to look for the issue.
However, @sulaweyo, you suggest you could reproduce the issue on command line with sample code. Could you provide the exact code you were able to achieve this with? That would be very appreciated.

**Comment by sulaweyo** [comment] 2015-05-11 04:14
Basically what i did was that:
´´´
<?php
require("ZipStreamer.php");
$zip = new ZipStreamer\ZipStreamer();
$stream = fopen('someHugeFile','r');
$zip->addFileFromStream($stream, 'test1.txt', 1);
fclose($stream);
$zip->addEmptyDir("testdirectory", 1);
$zip->finalize();
?>
´´´
At start it does not really increase memory consumption a lot but the longer the download takes the more memory is consumed. I tested it with the zipstreamer version in the owncloud repo and with the current git version.

**Comment by McNetic** [comment] 2015-05-11 08:32
I just tested your code with a 15GB file on my Debian 7 box with apache 2 and hat absolutely no issues. Memory usage of my apache instances stays at 0.3 % (4 GB RAM in the machine) for the whole download time.

I think the problem could be either a configuration issue with the web server (althought the problem was also reported on apache), or it could be a bug in Zipstreamer that only appears with special php versions and/or configuration.

To take the web server out of the equatation, could you call your php script from command line and see if it consumes memory, also? (like this "php script.php > /dev/null")

**Comment by sulaweyo** [comment] 2015-05-11 08:56
I'll try that as soon as i get home and i'll try it with apache as well just to verify if it's lighttpd or something in my php settings.

**Comment by sulaweyo** [comment] 2015-05-11 14:57
Ok i just tested it out...
command line -> OK
apache -> OK
---> seems to be some lighttpd issue or maybe php-fpm related which i did not use in apache test

**Comment by McNetic** [comment] 2015-05-11 21:27
Ok, I'm happy that your problem is solved that way (and also that it does not appear to be a generic problem with Zipstreamer). Maybe it's really a problem with lighthttpd. I don't know much about it; but quick search brought up e.g. http://redmine.lighttpd.net/issues/2586, which could be a related issue.

However, there still might be room for improvement in Zipstreamer, especially as there also was a report from an apach user. @Babzsak, could you possibly try the simple example by sulaweyo, and, if the issue persists, also do the command line test?

**Comment by Babzsak** [comment] 2015-05-14 07:30
@McNetic thanks for the tips, I think I will have some time on the weekend, so will play try these out. Will keep you updated.

**Comment by nickvergessen** [comment] 2015-05-20 14:11
@Babzsak did you have any chance to test this?

**Comment by DeepDiver1975** [comment] 2015-06-02 12:23
I guess this issue might be better suited to be handled in the zipstreamer repo. closing this therefore. THX

**Closed by DeepDiver1975** 2015-06-02 12:23 UTC
Labels: bug, sev2-high

**Comment by McNetic** [comment] 2015-06-03 13:48
To the reporters: If you notice the problem again, or can give more input on the issue, please don't hesitate to open an issue over at https://github.com/McNetic/PHPZipStreamer/issues.

**Comment by jdascenzio** [comment] 2015-11-03 11:56
I have the same issue on a debian 8 (jessie) with lighttpd and owncloud v8.1.3.
When the download is too slow, my memory grow unitl the oom-killer is called...

**Comment by RealRancor** [comment] 2015-11-03 12:06
@jdascenzio See the comment one above yours.
