### ISSUE TITLE
Error Updating to 10.0.2

### ISSUE THREAD

**Issue by bonedrums** [owncloud/core#28383] opened 2017-07-12 12:44 UTC
Updating to 10.0.2

files_external: An exception occurred while executing 'CREATE TABLE "oc_external_mounts" ("mount_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "mount_point" VARCHAR(128) NOT NULL, "storage_backend" VARCHAR(64) NOT NULL, "auth_backend" VARCHAR(64) NOT NULL, "priority" INTEGER DEFAULT 100 NOT NULL, "type" INTEGER NOT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_external_mounts" already exists
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
files_external: An exception occurred while executing 'CREATE TABLE "oc_external_mounts" ("mount_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "mount_point" VARCHAR(128) NOT NULL, "storage_backend" VARCHAR(64) NOT NULL, "auth_backend" VARCHAR(64) NOT NULL, "priority" INTEGER DEFAULT 100 NOT NULL, "type" INTEGER NOT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_external_mounts" already exists
The update was unsuccessful. Please report this issue to the ownCloud community.

Any suggestions folks?

**Comment by kdslkdsaldsal** [comment] 2017-07-12 13:44
Closing as a duplicate of https://github.com/owncloud/core/issues/28205 and various others for now. Please make sure to follow the instructions in https://github.com/owncloud/core/issues/28205#issuecomment-310829910

If you have done a correct upgrade please create a new issue and make sure that you're using/filling out the issue template shown when creating a new issue.

Thanks

**Closed by kdslkdsaldsal** 2017-07-12 13:44 UTC
