### ISSUE TITLE
LDAP configuration was only using the backup server, not the primary

### ISSUE THREAD

**Issue by gig13** [owncloud/core#24164] opened 2016-04-21 15:10 UTC
### Steps to reproduce
1. Setup a primary AD and a backup AD with the backup receiving updates once daily
2. Create a new group in the primary AD associated with existing users that have ownCloud access
3. Login to the Users page and check for the group in the group listing and under the users that are associated with the group
### Expected behaviour

When a new group is added to the primary AD, it should show up in ownCloud in a few minutes. 
### Actual behaviour

We observed that while checking he Users page, it was slow for displaying the Users and very "jumpy". The group did not show up in the Users page even after 20 hours. When we removed the configuration for the backup LDAP, the group showed up on the next refresh of the Users page. The Users page was also more responsive.
We conducted a few more tests with the backup AD configured and adding a new group or user, and we noticed that the ownCloud seemed to always be routing to the backup and not the primary AD.

One other oddity, was when we unchecked the "active server" checkbox under the backup LDAP server section, we could not login using LDAP at all and had to login as the local admin user.
### Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.4.16

**ownCloud version:** 8.1.5.2

**Updated from an older ownCloud or fresh install:** Upgrade

**List of activated apps:**
report configuration on s3

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory
#### LDAP configuration

On s3

@blizzz @MorrisJobke

**Comment by gig13** [comment] 2016-04-21 15:13
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F24164

**Comment by PVince81** [comment] 2016-04-21 16:13
@blizzz I see there was a fix from you related to backup server that made it into 8.1.5 which is https://github.com/owncloud/core/pull/20362, not sure if related in any way.

@blizzz do you think this https://github.com/owncloud/core/pull/23403 could help ? That fix seems to be for when using memcache and the config shows that they have:
```
"memcache.local": "\\OC\\Memcache\\APC",
```

**Comment by blizzz** [comment] 2016-04-21 23:34
Was their main LDAP server down at some point (or maybe just not accessible form the ownCloud server)?

Is the main one a real LDAP server or a loadbalancer or something like this? 

When we removed the configuration for the backup LDAP, the group showed up on the next refresh of the Users page. 

@PVince81 first one is in that way related, that using backup server works again. Second one would not help - it fixes a bug where the main server would always be attempted.

> When we removed the configuration for the backup LDAP, the group showed up on the next refresh of the Users page. 

Until that I would have thought that the main one is just not reachable…

> One other oddity, was when we unchecked the "active server" checkbox under the backup LDAP server section, we could not login using LDAP at all and had to login as the local admin user.

There is none. Possibly they refer to "Configuraiton Active" which is above this, and is does what it is supposed to: https://doc.owncloud.org/server/8.1/admin_manual/configuration_user/user_auth_ldap.html#connection-settings

**Comment by PVince81** [comment] 2016-04-25 09:46
> Was their main LDAP server down at some point (or maybe just not accessible form the ownCloud server)?

> Is the main one a real LDAP server or a loadbalancer or something like this? 

@gig13 can you provide this information ?

**Comment by gig13** [comment] 2016-04-25 11:37
@PVince81 
The main LDAP was always online and there was no loadbalancer in use.

**Comment by gig13** [comment] 2016-04-28 14:07
@PVince81 @blizzz Do you need any other information? The main LDAP was online and so was the backup, no network bumps occurred when we stumbled on this issue.

**Comment by gig13** [comment] 2016-05-16 19:34
@PVince81 any update?

**Comment by PVince81** [comment] 2016-06-10 15:57
Not sure what to do here @felixboehm.
I don't have enough understanding of LDAP and don't know anything about AD to be able to help.

Maybe @owncloud/ldap have an idea ?

**Comment by jvillafanez** [comment] 2016-07-06 15:28
Could you check the latest version (I guess 8.1.9)? The fix might be there.

I've checked the changes made between 8.1.5 and 8.1.9 and I found an interesting one:
```
@@ -574,7 +564,7 @@ class Connection extends LDAPUtility {
                                $this->doConnect($this->configuration->ldapBackupHost,
                                                                 $this->configuration->ldapBackupPort);
                                $bindStatus = $this->bind();
-                               if($bindStatus && $error === -1 && !$this->getFromCache('overrideMainServer')) {
+                               if($bindStatus && $error === -1) {
                                        //when bind to backup server succeeded and failed to main server,
                                        //skip contacting him until next cache refresh
                                        $this->writeToCache('overrideMainServer', true);
```
I did the diff the reversed way, so the "-" line is from stable8.1 and the "+" for 8.1.5

So basically, for 8.1.5 you're refreshing the "overrideMainServer" flag on every access to the LDAP. The latest code for stable8.1 should check if the flag is in the cache before writing it, so once the LDAP ttl expires it should be able to access to the main server again (if the "overrideMainServer" configuration is unchecked.

**Comment by jvillafanez** [comment] 2016-07-06 15:31
One minor correction: 8.1.8 doesn't contain that fix, but latest code for stable8.1 (future 8.1.9) does.

**Comment by PVince81** [comment] 2016-09-21 07:49
8.1.10 was released. Is there anything else to be done here ?

**Comment by jvillafanez** [comment] 2016-09-21 11:59
I guess we should check if this is reproducible in 8.1.10

**Comment by PVince81** [comment] 2016-10-20 08:38
@jvillafanez are you able to check this ?

**Comment by jvillafanez** [comment] 2016-11-25 12:12
Checked with latest stable8.1 (8.1.11 (daily) Build:2016-11-25T04:15:12+00:00 e77290d6365e4f360c7d9a60e3c9688ceaafdbd4) looks good.

I haven't checked with stable9.1 nor stable9 but that piece of code is also there, so it should work.

**Comment by PVince81** [comment] 2017-01-30 14:37
Can you check or instruct @davitol how to check it ? Ideally we should also have automated tests for this.

**Comment by PVince81** [comment] 2017-02-03 18:22
Moving to 8.2.11 since 8.1.12 is the last of the 8.1 series (EOL)

**Comment by jvillafanez** [comment] 2017-02-22 17:48
1. Setup 2 LDAP servers with the same contents, one of them as backup in the ownCloud configuration
2. Verify the users are loaded fine
3. Turn off the main LDAP server
4. Verify the users keep loading fine.

That should be enough to check the backup server is working fine. We could also check that if the main server is turned on, the requests are sent to the main server or are sent to the backup server until we reach the ttl.

**Comment by PVince81** [comment] 2017-04-13 14:19
8.2 is EOL end of May, moving to 9.0.10. Needs to be verified there

**Comment by PVince81** [comment] 2017-06-29 14:55
closing as not reproducible. If the issue pops up again for someone we'll see it.

**Closed by PVince81** 2017-06-29 14:55 UTC
Labels: app:user_ldap, blue-ticket, bug, sev2-high
