### ISSUE TITLE
accessing public link previews when `'enable_previews' => false` returns Error 500

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#38436] opened 2021-02-23 08:03 UTC
### Steps to reproduce
1. set `'enable_previews' => false`  in config.php
2. run `tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature:43` acceptance test

This need more info and investigations, I don't have time for that now, but want to open this issues so that I will not forget it

### Expected behaviour
Tell us what should happen

### Actual behaviour
error 500

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"JvsUfdmcbV1rvLa5E7YH","level":3,"time":"2021-02-23T07:57:17+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/owncloud-core\/index.php\/apps\/files_sharing\/ajax\/publicpreview.php?file=testavatar.jpg&t=FmBfcuZgEvJUSHl","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function file_get_contents() on null\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/legacy\\\/image.php(573): OC\\\\Files\\\\Filesystem::file_get_contents()\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Preview.php(1170): OC_Image->loadFromFile()\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Preview.php(799): OC\\\\Preview->getMimeIcon()\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/files_sharing\\\/ajax\\\/publicpreview.php(120): OC\\\\Preview->showPreview()\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/home\\\/artur\\\/www...')\\n#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Route\\\/Router.php(341): OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(*** sensitive parameters replaced ***)\\n#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(915): OC\\\\Route\\\\Router->match()\\n#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Files\\\/Filesystem.php\",\"Line\":864}"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by dpakach** [comment] 2021-05-14 07:49
@individual-it I could-not reproduce this issue. The preview URL always gives 200 for me if the file exists, even if `enable_previews` is set to `false`.
it gives 500 if the file is not there(which is a different issue) 

seems like setting `enable_previews` to false will only make it not show preview for the image in the webUI filelist but the API always works.

**Comment by dpakach** [comment] 2021-05-14 10:54
@individual-it should we close this? I could not reproduce

**Closed** 2021-05-14 11:18 UTC
Labels: QA:team
