### ISSUE TITLE
Public share is not working since update

### ISSUE THREAD

**Issue by einmalacht** [owncloud/core#31921] opened 2018-06-27 07:59 UTC
### Expected behaviour
I cant share public files since i updated from 10.0.7 to 10.0.8 
The Sharing Page iss blank see picture
![unbenannt](https://user-images.githubusercontent.com/10926339/41960690-b6a4f65e-79f0-11e8-8721-0b164df981e4.JPG)

### Server configuration
**Operating system**:
Linux Ubuntu 4.4.0-128-generic
**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-04-18T14:53:04
**Database:**
mysql
**PHP version:**
PHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1

**Comment by ownclouders** [comment] 2018-06-27 08:20
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8559 (public links no longer work after restore of shared folder), https://github.com/owncloud/core/issues/21395 (Remote Sharing not working as expected), https://github.com/owncloud/core/issues/17952 (Sharing doesn't work), https://github.com/owncloud/core/issues/21598 (Public share fails when master key is enabled), and https://github.com/owncloud/core/issues/1197 (Calendar sharing not working properly).

**Comment by PVince81** [comment] 2018-06-28 13:20
likely duplicate of https://github.com/owncloud/core/issues/31454
workaround is disabling the "collaborative tags" app

or upgrade to 10.0.9 RC2

**Closed by PVince81** 2018-06-28 13:20 UTC
