### ISSUE TITLE
Password Reset not working_OC v8.1.3

### ISSUE THREAD

**Issue by tx7** [owncloud/core#19754] opened 2015-10-13 23:52 UTC
Hi all,

I'm tried to do a password reset for the user, but it not working in the Admin console.
It retain the old password.
I'm running on Nginx.

### Steps to reproduce
1. Log in OC admin console.
2. Select a user.
3. Change the user password.

### Expected behaviour
New password should be changed.

### Actual behaviour
New password didn't changed.
User continue to use old password.

### Server configuration
**Operating system**:
Linux  SMP Debian 3.16.7-ckt11-1+deb8u4~bpo70+1 (2015-09-22) x86_64 GNU/Linux

**Web server:**
Nginx  1.2.1-2.2+wh 
**Database:**
MySQL
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.1.3
**Updated from an older ownCloud or fresh install:**
Updated from an older ownCloud.
**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - agreedisclaimer: 1.0.4
 - audios: 1.2.5
 - delete_confirmation: 1.0.1
 - direct_menu: 0.4
 - external: 1.2
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_external: 0.2.3
 - files_locking:
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - firstrunwizard: 1.1
 - galleryplus: 14.1.0
 - html5_videoplayer: 1.0
 - ownnote: 1.05
 - passwordpolicy: 1.1
 - provisioning_api: 0.2
 - templateeditor: 0.1

**Comment by LukasReschke** [comment] 2015-10-14 00:04
Please fill out the issue template - thanks: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version

**Comment by PVince81** [comment] 2015-10-14 07:49
Did you hit enter or clicked outside after changing the password ?

**Comment by tx7** [comment] 2015-10-14 11:41
I hit Enter.

**Comment by DeepDiver1975** [comment] 2015-10-14 12:09
anything in the log files?

**Comment by tx7** [comment] 2015-10-14 12:28
There is no error in the log file or message at all.
I've tried password reset about 7 times already.

**Comment by rmcaninch** [comment] 2015-10-27 22:58
I have the same problem using the web interface. I was able to use the command line occ utility to change the password successfully. Did not see anything in the owncloud.log

**Comment by DeepDiver1975** [comment] 2015-10-28 06:45
@rperezb for the qa plan

**Comment by DeepDiver1975** [comment] 2015-10-28 06:46
@pvince81 is this reproducable?

**Comment by PVince81** [comment] 2015-10-28 13:11
Works for me.

@tx7 you might want to try disabling some of the third party apps you installed, like for example "password_policy", in case these interfere with the password form in the settings dialog.

**Comment by PVince81** [comment] 2015-10-28 13:12
Also, you need to hit "enter" after entering the password in the users page.

**Comment by PVince81** [comment] 2015-10-28 13:13
@rmcaninch resetting the password with `occ` also works for me on 8.1.3. Are you using any third party apps like @tx7 ?

**Comment by tx7** [comment] 2015-10-28 13:35
I'll disable 'password policy', and try again.
I don't wan to reset the user password via web gui, not occ command.

**Comment by rmcaninch** [comment] 2015-10-28 13:47
No third party plugins. I guess I missed hitting enter after typing the password. Think I'd rather have a change button that is obvious :)

**Comment by PVince81** [comment] 2015-10-28 14:16
@rmcaninch there's already another ticket for the "enter" part, somehow I can't find it any more.

**Comment by PVince81** [comment] 2015-10-28 14:16
ah here it is https://github.com/owncloud/core/issues/16360

**Comment by muesliq** [comment] 2015-11-09 07:35
I have the same problem. ownCloud 8.1.3, no apps.

**Comment by LukasReschke** [comment] 2015-11-09 09:35
So I assume we can close this?

**Closed by LukasReschke** 2015-11-09 09:35 UTC
Labels: bug, needs info, settings:users
