### ISSUE TITLE
Can't use HTTPS: "URL /index.php/apps/files/ not found"

### ISSUE THREAD

**Issue by andrey-utkin** [owncloud/core#20414] opened 2015-11-09 22:26 UTC
Ubuntu 14.04.3. Owncloud advertised repositories.
Have tried this with fresh installs of owncloud 8.1 (stable), testing (8.2...-RC...), nightly (8.1-20151108). HTTP works, HTTPS doesn't, giving this after login page:
```
Not Found

The requested URL /index.php/apps/files/ was not found on this server.
```

/etc/apache2/sites-enabled/oc.example.org-le-ssl.conf:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName oc.example.org
        ServerAlias oc.example.org
        DocumentRoot "/var/www/owncloud"
        <Directory   "/var/www/owncloud">
        AllowOverride All
        order allow,deny
        Allow from all
        </Directory>

SSLCertificateFile /etc/letsencrypt/live/oc.example.org/cert.pem
SSLCertificateKeyFile /etc/letsencrypt/live/oc.example.org/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateChainFile /etc/letsencrypt/live/oc.example.org/chain.pem
</VirtualHost>

</IfModule>
```

**Comment by Xenopathic** [comment] 2015-11-09 23:10
Duplicate of #20202

**Closed by Xenopathic** 2015-11-09 23:10 UTC

**Comment by RealRancor** [comment] 2015-11-10 08:08
Fixed now in Let's Encrypt with https://github.com/letsencrypt/letsencrypt/pull/1390
