### ISSUE TITLE
"Login failed" in log due to Android App

### ISSUE THREAD

**Issue by fnerdwq** [owncloud/core#12269] opened 2014-11-18 21:07 UTC
With Owncloud 7.0.3 I find "Login failed" messages in the ownlcoud log when using the Android Owncloud Client 1.6.1 - correct credentials are entred, the acces otherwise works.

Each time I change directory in the app I finde _two_ lines in the log like this (same reqId):

{"reqId":"5465cd1f44108","app":"core","message":"Login failed:
'user@email.de' (Remote IP: 'XXX.XXX.XXX.XXX', X-Forwarded-For:
'')","level":2,"time":"2014-11-14T09:36:31+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=%2F&reshares=false&subfiles=true"}

For the rest the App works as expected, only that that the 'update account' (or similar; "Konto updaten" in german) doesn't seem to finish (keeps circling).

This bug is quite 'annoying' since my fail2ban will kick me out....

**Comment by DeepDiver1975** [comment] 2015-01-22 11:47
needs analysis -> 8.1

**Comment by karlitschek** [comment] 2015-05-04 17:20
@DeepDiver1975 Do you had time for the analysis?

**Comment by swas** [comment] 2015-10-06 00:42
I have the same issue, but three repetitions of the login error line instead two.

I appreciated this error since the first version of owncloud 7


My current test:

**Operating system**: Debian 7
**ownCloud version**: 7.0.7.2
**Web server**: nginx 1.6.2
**PHP version**: 5.6.12
**Database**:  MySQL 5.5.44

**Android client version**: 1.8.0

**Comment by cmonteroluque** [comment] 2015-10-25 17:45
@LukasReschke do you have any thoughts on this one?

**Comment by LukasReschke** [comment] 2015-10-25 17:47
Thoughts yes. Can I prove or test them without Android device? No.

**Comment by cmonteroluque** [comment] 2015-11-03 16:09
@rperezb @davivel @masensio Could you help debug this?

**Comment by davivel** [comment] 2015-11-03 16:45
Is the sharing API enabled in the server? The requests generating the "Login failed" messages are those trying to get the shares in the current folder.

**Comment by PVince81** [comment] 2015-11-04 16:07
Is this reproducible ? Does it happen after performing specific steps ?

If not, then maybe the session has timed out and the client doesn't know it, and it just tries to call OCS endpoints (not webdav) without credentials, which might cause these errors ?

**Comment by davivel** [comment] 2015-11-04 16:17
The Android app doesn't use session. Every request is authenticated with the credentials.

**Comment by cmonteroluque** [comment] 2015-11-09 09:19
@swas can you update to 8.1 or 8.2 and let us know

**Comment by swas** [comment] 2015-11-10 23:58
The upgrade is not yet planned, but when I do it, I will perform the test.

**Comment by PVince81** [comment] 2016-06-17 14:37
Closing as old. Please try againwith 8.2.6 or 9.0.2. If the problem still exists there, please reopen.

**Closed by PVince81** 2016-06-17 14:37 UTC
Labels: bug, sev3-medium
