### ISSUE TITLE
Too many users in ldap are not shown in users page.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19240] opened 2015-09-22 08:35 UTC
### Steps to reproduce

Having a LDAP server with 1 million users do:

1. Enable ldap app.
2. Set it up.
3. Go to the user management page. 

### Expected behaviour
LDAP Users appears. 

### Actual behaviour
There is an spinner, waiting and later only not-LDAP users appear.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
master 
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
LDAP.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:46+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:46+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:46+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:46+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:47:48+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:47:49+00:00"}
{"reqId":"go4QThB0wDBAC9IEw6JG","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:47:51+00:00"}
{"reqId":"U8kM0D5ogKZVDoIzKdJJ","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:51+00:00"}
{"reqId":"U8kM0D5ogKZVDoIzKdJJ","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:51+00:00"}
{"reqId":"U8kM0D5ogKZVDoIzKdJJ","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:51+00:00"}
{"reqId":"U8kM0D5ogKZVDoIzKdJJ","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:51+00:00"}
{"reqId":"lZ0xXfrEeEtFmwoN4XqD","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:53+00:00"}
{"reqId":"lZ0xXfrEeEtFmwoN4XqD","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:53+00:00"}
{"reqId":"lZ0xXfrEeEtFmwoN4XqD","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:53+00:00"}
{"reqId":"lZ0xXfrEeEtFmwoN4XqD","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:53+00:00"}
{"reqId":"jx6rgJcZujgkbl\/Ay2KU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"jx6rgJcZujgkbl\/Ay2KU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"jx6rgJcZujgkbl\/Ay2KU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"jx6rgJcZujgkbl\/Ay2KU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"jx6rgJcZujgkbl\/Ay2KU","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"zp7+zz8HvNWEqL0VqSWU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"zp7+zz8HvNWEqL0VqSWU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"zp7+zz8HvNWEqL0VqSWU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"zp7+zz8HvNWEqL0VqSWU","remoteAddr":"HIDED_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"zp7+zz8HvNWEqL0VqSWU","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:47:59+00:00"}
{"reqId":"FAUQelKJ+md3R433YtVn","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:48:00+00:00"}
{"reqId":"+1BLQ8Oglw8j+S8Ccxmc","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:50:25+00:00"}
{"reqId":"e\/ccKFRwz795wsWYyAIQ","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:50:36+00:00"}
{"reqId":"e\/ccKFRwz795wsWYyAIQ","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-09-22T07:50:39+00:00"}
{"reqId":"e\/ccKFRw
```
### Client configuration

**browser**
Chrome.

**Comment by SergioBertolinSG** [comment] 2015-09-22 09:49
After setting the configuration is is working.
Please, reopen if reproducible again.

**Comment by davitol** [comment] 2015-10-06 10:44
I have reproduce it again :crying_cat_face: , but I don't know why it happens, due to it is an erratic behaviour, and it not happens always.

**Comment by SergioBertolinSG** [comment] 2015-10-06 10:53
@blizzz 👋

**Comment by blizzz** [comment] 2015-10-09 13:29
Well, if it's reproducible only on new moon days while the tide is high it get's tricky. Can you see a difference for instance with caching turned off and on? Also providing the configuration might help.

**Comment by MorrisJobke** [comment] 2016-02-14 19:16
We can't do much, if it is not reproducible. Please grab @blizzz once this happens again and gain him access to the instance to be able to debug it. Beside that I will close this ticket here, because it doesn't help us.

**Comment by SergioBertolinSG** [comment] 2016-02-17 08:11
Still happening, will talk with @blizzz to triage it.
```
{"reqId":"51J9NJAigNAKGyMoqey2","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#264","level":3,"time":"2016-02-17T07:58:34+00:00"}
{"reqId":"6BtKzj49\/wzddJxnU1wc","remoteAddr":"HIDED_IP","app":"PHP","message":"usort(): Array was modified by the user comparison function at \/opt\/owncloud\/lib\/private\/user\/manager.php#246","level":3,"time":"2016-02-17T08:02:18+00:00"}
{"reqId":"fHw708iRzQcvz2JzLZYw","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#264","level":3,"time":"2016-02-17T08:04:54+00:00"}
{"reqId":"fHw708iRzQcvz2JzLZYw","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#264","level":3,"time":"2016-02-17T08:04:55+00:00"}
{"reqId":"fHw708iRzQcvz2JzLZYw","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#264","level":3,"time":"2016-02-17T08:04:57+00:00"}
{"reqId":"gf9yb+y63mZ898QFADu5","remoteAddr":"HIDED_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#264","level":3,"time":"2016-02-17T08:05:02+00:00"}
```

**Comment by blizzz** [comment] 2016-02-22 20:48
@SergioBertolinSG with current master?

**Comment by blizzz** [comment] 2016-02-29 11:01
Talked with @SergioBertolinSG and got access to an instance. It was a configuration issue, because a wrong (the default) user display name attribute was set. Apparently, "Count users" was not clicked on the user tab, which triggeres an automatic discovery of this attribute. Otherwise you can do it manually in the advanced tab. Having this correct, it works as intended → closing.

**Closed by blizzz** 2016-02-29 11:01 UTC
Labels: app:user_ldap, bug, needs info, settings:users, sev2-high

**Comment by SergioBertolinSG** [comment] 2016-02-29 11:30
To make this work, "User display name field" in advanced tab was changed to "cn".
