### ISSUE TITLE
'Activate' button avaialbe for already installed apps

### ISSUE THREAD

**Issue by dragetd** [owncloud/core#14059] opened 2015-02-10 15:49 UTC
This is a followup on  #14033

Due to the SSL issue with the app server, a workaround was suggested to manually install the applications. (Contacts/Calendar)

Even with the app already installed, the 'Activate' button is still available on the apps page. When trying to install it, OC reports an error of 'application directory already existing'. This does not affect the functionality in any way, but makes it impossible to deactive it via the webinterface.

**Comment by MorrisJobke** [comment] 2015-02-10 16:11
Are there any log entries in the owncloud.log in your data folder?

**Comment by MorrisJobke** [comment] 2015-02-10 16:13
oh ... duplicate of #14054

**Closed by MorrisJobke** 2015-02-10 16:13 UTC
Labels: bug, settings:apps

**Comment by MorrisJobke** [comment] 2015-02-10 16:14
and duplicate of #14004
