### ISSUE TITLE
[6.0.3] Files uploaded directly to SWIFT storage don't show up in oC

### ISSUE THREAD

**Issue by ser72** [owncloud/core#8633] opened 2014-05-19 12:41 UTC
**Steps**
1) configure External Storage as SWIFT
2) Upload a file directly to the SWIFT storage -- not through oC
3) View SWIFT directory in oC and the file from Step 2 isn't there:

**IMAGES**
Swift storage -- the last file is uploaded directly to SWIFT.  The other 2 were uploaded via oC.

![bouquet_contents_missing_file](https://cloud.githubusercontent.com/assets/5174383/3014057/e3302794-df52-11e3-9b65-8248b047e64e.jpg)

oC.  Notice the missing file
![capture](https://cloud.githubusercontent.com/assets/5174383/3014049/b96a9f2a-df52-11e3-8227-154714253a39.PNG)

**Comment by carlaschroder** [comment] 2015-01-29 18:10
added to release notes

**Comment by Xenopathic** [comment] 2015-03-20 11:22
Given that release notes have been updated, I'm marking this as a duplicate of #11797

**Closed by Xenopathic** 2015-03-20 11:22 UTC
Labels: app:files_external, blue-ticket, bug, sev3-medium
