### ISSUE TITLE
Upload/new button appears several times after switching sections

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#19020] opened 2015-09-14 14:19 UTC
### Steps

1. Open the files app
1. Switch to "Favorites" or any other section in the left sidebar
1. Switch back to "All files"

### Expected
Only one "+" button

### Actual
Several "+" buttons

### Versions
ownCloud 8.2 pre-alpha git master 211a2437840ec6897e377a5025f85aec27618263

**Comment by LukasReschke** [comment] 2015-09-14 15:39
Dupe of https://github.com/owncloud/core/issues/18894, let's close the older one as you assigned yourself here :smile:

**Comment by PVince81** [comment] 2015-09-14 16:43
I still haven't read all my 888+ github emails, so it's likely that I'll bump against dupes :smile:

**Comment by PVince81** [comment] 2015-09-22 14:49
Fix is here https://github.com/owncloud/core/pull/19277

**Closed** 2015-09-23 09:31 UTC
Labels: bug, regression, sev2-high
