### ISSUE TITLE
Public link share always copies first link to clipboard

### ISSUE THREAD

**Issue by fmkaiser** [owncloud/core#27887] opened 2017-05-15 13:13 UTC
### Steps to reproduce
1. Create two public link shares
2. Click "copy to clipboard" button on 2nd share

### Expected behaviour
Link for 2nd share is copied to clipboard

### Actual behaviour
Link for 1st share is copied to clipboard

### Server configuration
**Operating system**:
CentOS 7

**Web server:**
Apache 2.4

**PHP version:**
7.1

**ownCloud version:** (see ownCloud admin page)
10.0

**Browser**
Firefox 52 and Chrome 58

### Analysis
core/js/sharedialoglinklistview.js:24: (...) data-clipboard-target="#linkText-{{cid}}">
-> cid seems to be empty when the template is rendered 

![owncloud_linkshare_cid_bug](https://cloud.githubusercontent.com/assets/2922101/26058980/627e910e-3980-11e7-813b-08d31496276d.png)

**Comment by kdslkdsaldsal** [comment] 2017-05-15 15:04
@fmkaiser This looks to me like a duplicate of https://github.com/owncloud/core/issues/27851 which got fixed recently by https://github.com/owncloud/core/pull/27863

**Comment by PVince81** [comment] 2017-05-15 15:34
yes, duplicate. Thanks for reporting, fix will be in 10.0.1

**Closed by PVince81** 2017-05-15 15:34 UTC
