### ISSUE TITLE
Wrong File opens / thumbnail not updated

### ISSUE THREAD

**Issue by archfoe** [owncloud/core#23193] opened 2016-03-13 00:59 UTC
### Steps to reproduce
1. I have to give you my username and password
2. my original file in images display a different thumbnail, after clicking on it displays different image 
3.

### Expected behaviour
Tell us what should happen
It should open the original file name, not some other image file
### Actual behaviour
Tell us what happens instead
it shows completely different images from the filename
### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache 2.4
**Database:**
mariadb 10
**PHP version:**
php 7
**ownCloud version:** (see ownCloud admin page)
owncloud 9
**Updated from an older ownCloud or fresh install:**
upgraded from 8
**Where did you install ownCloud from:**
from main source
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``No errors have been found.`

**List of activated apps:**
nothing additional added
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - external
  - files_external
  - user_ldap

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
all browsers
**Operating system:**
linux
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by smirkybg** [comment] 2016-03-13 07:33
I confirm this since upgrading to OC 8.2 to 9.0. I get different thumbnails and image previews, but the name of the image file is the correct one. If you download it with the download button, it's the original one too.

**Comment by PVince81** [comment] 2016-03-14 12:55
@oparoz @georgehrke

**Comment by oparoz** [comment] 2016-03-14 14:19
I don't understand the "steps to reproduce".

Users are on Files and press on an image to launch the slideshow?

@smirkybg - Are you also on PHP 7?

**Comment by smirkybg** [comment] 2016-03-22 06:19
@oparoz Yes, I'm using PHP7.

 0 « smirky » ~ » pacman -Q | grep php
```
php 7.0.4-2
php-apache 7.0.4-2
php-apcu 5.1.3-1
php-fpm 7.0.4-2
php-gd 7.0.4-2
php-imap 7.0.4-2
php-intl 7.0.4-2
php-mcrypt 7.0.4-2
```

**Comment by oparoz** [comment] 2016-03-22 10:45
Thanks @smirkybg. I've just tested on PHP7 and get the proper image, so that's not the problem.

The best thing to do wold be to press F12, go to the network tab and click on an image in the filelist to see what's happening. Maybe that image is skipped because it can't be displayed.

**Comment by archfoe** [comment] 2016-03-28 22:41
Here is the problem. The thumbnail and the displayed image are showing the wrong file.


![2016-03-28-173518_1349x612_scrot](https://cloud.githubusercontent.com/assets/2957393/14092390/1b8ca380-f50c-11e5-876f-49d10fe7731f.png)

**Comment by oparoz** [comment] 2016-03-28 22:49
Since I doubt 2 images in the filesystem have that same name, I'll exclude the missing hook issues which should have triggered a thumbnail update.
This problem could very well be related to the new caching in 9.0. @PVince81 @rullzer 

@archfoe -  Have you tried to rescan all your files?

**Comment by archfoe** [comment] 2016-03-28 22:51
I tried:
sudo -u www-data php console.php  files:scan --all
but it didn't help.

**Comment by oparoz** [comment] 2016-03-28 22:52
@archfoe - Thanks

**Comment by archfoe** [comment] 2016-03-28 23:04
What is the way to clear the owncloud 9 cache?

**Comment by smirkybg** [comment] 2016-03-29 04:45
Previously I used:

```
 0 « smirky » ~/stuff/scripts » cat oc_purge_cache.sh 
#!/bin/bash
mysql -u cloud -p --database "cloud" --execute "TRUNCATE TABLE oc_filecache"
```

I don't know if this is a good idea though :) I used it when I manually move files into the storage and need to get them visible into OC since it doesn't have such a detection at the moment.

**Comment by DeepDiver1975** [comment] 2016-03-29 04:47
NO! Dont mess with the database! :angry:

**Comment by smirkybg** [comment] 2016-03-30 09:08
So what's the current status here? Do we need more information on this?
I will be happy to provide whatever's necessary, but it's not that obvious to me what would be needed.
I can reproduce it perfectly however.

**Comment by oparoz** [comment] 2016-03-30 09:12
@smirkybg -  I can probably tell you how to get the proper thumbnails, but it won't help preventing it from happening again...

**Comment by archfoe** [comment] 2016-04-06 19:01
I got the latest version but the problem is still there
ownCloud <https://owncloud.org> 9.0.1 RC2 (daily)
Build:2016-04-06T03:48:40+00:00 277c9f4a03be77c03a7b051cf92bfc0e14c3e398

Where is the thumnail info stored and the path to the original files?

**Comment by PVince81** [comment] 2016-06-02 17:26
Maybe a time difference issue preventing the thumbnail to expire ?

**Comment by oparoz** [comment] 2016-06-02 20:46
@archfoe - You can delete `data/<username>/thumbnails`, but that would only solve the problem for you.

There should be something telling the server that a new version of the file has been pushed, but it's not happening.

**Comment by archfoe** [comment] 2016-06-02 21:08
Duh!
Removing thumbnails folder fixed my issue:)
I should've guessed it but I was dropping the database cache instead.

Thanks Olivier!

**Comment by oparoz** [comment] 2016-06-02 21:11
You're welcome :).

Since you're on 9.1 RC2, you could try to upload a picture with the same name to see if the problem still exists. The thumbnail should automatically be updated.

**Comment by PVince81** [comment] 2016-07-18 14:59
Closing. If the problem persists in 9.0.3 or 9.1.0 RC2, please reopen

**Closed by PVince81** 2016-07-18 14:59 UTC
Labels: bug, feature:previews, sev3-medium
