### ISSUE TITLE
[IE9] Password is lost from the textbox when clicking in the textbox of shared link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16511] opened 2015-05-21 16:38 UTC
### Steps to reproduce
1. Try a file to a user of another server by link.
2. Write down a password
3. Click again in the textbox of the link

### Expected behaviour

Password should be kept

### Actual behaviour
Password disappears. (gif below with the behaviour)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Internet Explorer 9 & Firefox

![pwdlost](https://cloud.githubusercontent.com/assets/10596560/7753839/49af5dee-ffe8-11e4-9460-317d987a87ea.gif)

**Comment by rullzer** [comment] 2015-05-21 19:31
I can't reproduce this on master.
Could you verify if it is only the text not showing or that no actual request is fired?

**Comment by davitol** [comment] 2015-05-22 07:23
Just reproduce on Master. The paswword disappears from the textbox, but it is required when sharing the link.

**Comment by rullzer** [comment] 2015-05-22 11:37
Could you verify if it is just visual? Or that the password update really isn't happening?

**Comment by rullzer** [comment] 2015-05-22 13:11
@PVince81 do you have any idea what might be going on here?

**Comment by rullzer** [comment] 2015-05-22 13:12
I started working on unit tests in https://github.com/rullzer/core/commit/914c74ea9b21c26da3e033591eec855d0e4d5857 which also shows correct behaviour...

**Comment by PVince81** [comment] 2015-05-22 13:25
In IE9 the placeholder code could be messing up, but I can't explain why it would happen on Firefox too.

**Comment by PVince81** [comment] 2015-05-22 13:27
@davitol did you use any of the "enforce" options in the admin page ? (like enforce password). From the screenshot probably not.

**Comment by PVince81** [comment] 2015-05-22 13:28
From what I see when testing locally is that the password is replaced by the placeholder text "Password protected" (grey). In IE9 the placeholder might be broken / does not appear.

@davitol can you make a gif of the behavior in Firefox too ?

**Comment by PVince81** [comment] 2015-05-22 13:28
@rullzer please submit your nice tests as a PR, more tests never hurt :wink:

**Comment by rullzer** [comment] 2015-05-22 13:50
@PVince81 yeah that was still on the todo... but done :)

**Comment by davitol** [comment] 2015-05-25 06:57
![captura de pantalla 2015-05-25 a las 8 39 49](https://cloud.githubusercontent.com/assets/10596560/7793144/f56b0ef6-02ba-11e5-96c1-9981f3717a12.png)
Those are the options marked

**Comment by davitol** [comment] 2015-05-25 06:57
![pwdlostag](https://cloud.githubusercontent.com/assets/10596560/7793211/1666e76e-02bc-11e5-8908-db45de1f5a45.gif)
Same behaviour with firefox

**Comment by PVince81** [comment] 2015-05-26 08:11
@davitol the GIF for Firefox is the expected behavior. The password will be replaced by the placeholder "Password protected". If you want to change it, you need to click and retype it.

The only problem I see is that in IE9 it doesn't show the placeholder due to a general issue with field placeholders, but this might be "by design" too. Does this ring any bells @MorrisJobke ?

**Comment by MorrisJobke** [comment] 2015-05-27 05:18
> Does this ring any bells @MorrisJobke ?

Only the annoying bells :(

The placeholder hack we have present for IE8 and 9 aren't working for password fields. @jancborchardt Worth to fix? Because this would require a lot of JS to mimic that behaviour - and has a huge potential to break the behaviour in IE8 and 9 even more. :(

**Comment by jancborchardt** [comment] 2015-05-27 12:00
Good question if we want to introduce a bunch of JS just to fix that. Feels like we don't want to do that.

@DeepDiver1975 your call.

**Comment by PVince81** [comment] 2015-09-22 08:11
IE9 placeholder bug

**Comment by PVince81** [comment] 2015-10-16 09:42
I was about to say that it's not worth fixing it if it's only a visual issue.

However I found that if I click inside the password field in IE9 (the one with the hidden placeholder) and then I exit the field again, it will try and **save** the placeholder as the password... so the password is not the originally entered one. This is bad.

**Comment by PVince81** [comment] 2015-10-16 09:57
Fix for the "mistakenly changed the password" issue here: https://github.com/owncloud/core/pull/19824

**Comment by cmonteroluque** [comment] 2015-10-25 18:45
@PVince81 this PR is marked for 9.0, is that right or should we move it to 8.2.1?

**Comment by MorrisJobke** [comment] 2015-10-26 07:47
> @PVince81 this PR is marked for 9.0, is that right or should we move it to 8.2.1?

It is right, because the PR is against master (which is 9.0). Once it is merged it can be back ported to stable8.2 which would then result in a PR with the milestone 8.2.1 ;)

**Closed** 2015-10-27 08:57 UTC
Labels: browser:ie, bug, feature:federated-cloud-sharing, sev3-medium

**Comment by MorrisJobke** [comment] 2015-10-27 08:59
I requested a backport of #19824 to stable8.2
