### ISSUE TITLE
Multiple conflicts with emojis

### ISSUE THREAD

**Issue by CriticalNoob** [owncloud/core#21397] opened 2015-12-30 11:10 UTC
### Issue

I identified several problems that can come with the use of emoji.
I suspect it come from the encoding of the database in utf8_bin whereas a four byte UTF-8 encoding is needed to store emoji.

#### First case :
As documented here (read the end) https://github.com/owncloud/contacts/issues/1117 there is a problem with the import or sync of contacts whose name contains an emoji.

#### Second case
Adding an event which name contains an emoji in the calendar cause errors in the log and is not stored. 
```
{"reqId":"Ox5FoxcsRAuoQ0yqi5g1","remoteAddr":"88.168.110.81","app":"calendar","message":"Event (owncloud-a6d4fe06761a89d00c0eaa155b5cfc56.ics) contains invalid data: End of document reached prematurely","level":2,"time":"2015-12-30T11:02:35+00:00"}
```

#### Third case
Deleting a file which which name contains an emoji from the web interface works, but then trying to restore it is impossible :

```
{"reqId":"9jpqUKiYBedobgQ128H5","remoteAddr":"88.168.x.x","app":"PHP","message":"Undefined index: permissions at \/var\/www\/owncloud\/lib\/private\/files\/fileinfo.php#177","level":3,"time":"2015-12-30T11:04:14+00:00"}
{"reqId":"aV4KGjSn81LecDZ\/X40+","remoteAddr":"88.168.x.x","app":"files_trashbin","message":"trash bin database inconsistent!","level":3,"time":"2015-12-30T11:04:17+00:00"}
{"reqId":"aV4KGjSn81LecDZ\/X40+","remoteAddr":"88.168.x.x","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\InvalidPathException\",\"Message\":\"Les caract\\u00e8res sur 4 octets ne sont pas pris en charge dans les noms de fichiers\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(663): OC\\\\Files\\\\View->verifyPath('\\\/files', 'Nicolas  ???? -...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/trashbin.php(377): OC\\\\Files\\\\View->rename('\\\/files_trashbin...', '\\\/files\\\/Nicolas ...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/ajax\\\/undelete.php(72): OCA\\\\Files_Trashbin\\\\Trashbin::restore('\\\/\\\/Nicolas  ????...', 'Nicolas  ???? -...', '1451471994')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 [internal function]: __lambda_func(Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('?lambda_3173', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(851): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tra...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1709}","level":3,"time":"2015-12-30T11:04:17+00:00"}
```

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Fresh install
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocjjeva77i4v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "www.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/example.com",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0
    }
}

**Comment by RealRancor** [comment] 2015-12-30 11:26
Looks like a duplicate of https://github.com/owncloud/core/issues/4513

**Comment by CriticalNoob** [comment] 2015-12-30 11:28
May be related but emoji are displayed in owncloud for me and the other problems are not referenced.

**Comment by CriticalNoob** [comment] 2015-12-30 11:55
I must add that the contact and calendar issues are only reproductibles with mysql, only restoring file doesn't work with sqlite.

**Comment by RealRancor** [comment] 2015-12-30 12:31
@CriticalNoob As you already have found the current state at https://github.com/owncloud/core/pull/17978#issuecomment-126332406 you probably can close here.

**Closed** 2016-01-02 21:23 UTC
