### ISSUE TITLE
There is currently no way to query the quota for a user via the provisioning api

### ISSUE THREAD

**Issue by butonic** [owncloud/core#20643] opened 2015-11-20 14:34 UTC
As an admin you cannot get the quota of a user, because users can only see their own quota.

**Comment by PVince81** [comment] 2015-11-20 17:41
Are you talking about quota usage or assigned quota ?

If assigned quota, GOTO https://github.com/owncloud/core/issues/19810

**Comment by PVince81** [comment] 2017-01-27 16:07
Closing as duplicate of https://github.com/owncloud/core/issues/19810

**Closed by PVince81** 2017-01-27 16:07 UTC
Labels: app:provisioning_api, enhancement
