### ISSUE TITLE
Updating to 10.0.2 - The update was unsuccessful.

### ISSUE THREAD

**Issue by OwncloudUser01** [owncloud/core#28147] opened 2017-06-17 10:55 UTC
I update OwnCloud from 9.1.4 to 10.0.2  with Softaculous  an I have these issue:
(I use PHP version: 5.6.30)

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment] 2017-06-17 17:06
@OwncloudUser01 This is known and a duplicate of https://github.com/owncloud/core/issues/28007. For now you can close here and watch that issue for more info.

**Comment by PVince81** [comment] 2017-06-20 14:58
@kdslkdsaldsal feel free to close duplicates yourself

**Closed** 2017-06-20 14:57 UTC

**Comment by kdslkdsaldsal** [comment] 2017-06-20 15:29
@PVince81 No Collaborator/Owner, no issue closing :-)

**Comment by PVince81** [comment] 2017-07-04 08:29
@kdslkdsaldsal you can now :-D

**Comment by iget-master** [comment] 2018-04-12 17:28
Hi there, I have a problem that might me related with this.

I have a owncloud (using docker) setup, actually on v10.0.2.1. I'm stuck on this version. Everytime I try to upgrade it to any version I get:

```
2017-11-07T03:16:03+00:00 Updating database schema
2017-11-07T03:16:03+00:00 Doctrine\DBAL\Schema\SchemaException: There is no table with name 'owncloud.oc_account_terms' in the schema.
2017-11-07T03:16:03+00:00 Update failed
```

And my logs shows:

> {"reqId":"W8UT4oYfWCUGzXFBqVJU","level":3,"time":"2018-04-12T17:18:53+00:00","remoteAddr":"172.18.0.1","user":"--","app":"core","method":"GET","url":"/core/ajax/update.php?requesttoken=LTg7K31XchV0C3l%2Fc1QKdkgKPlMVGRsKYDUXBjM%2BBVw%3D%3ATbqFKfBm5O8%2F1alOqRr2BiiC0Ms3AK01b8ce1iyfnLo%3D","message":"Exception: {"Exception":"Doctrine\\DBAL\\Schema\\SchemaException","Message":"There is no table with name 'owncloud.oc_account_terms' in the schema.","Code":10,"Trace":"#0 \/var\/www\/owncloud\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Schema\/Schema.php(197): Doctrine\\DBAL\\Schema\\SchemaException::tableDoesNotExist('owncloud.oc_acc...')\n#1 \/var\/www\/owncloud\/core\/Migrations\/Version20170526104128.php(17): Doctrine\\DBAL\\Schema\\Schema->getTable('owncloud.oc_acc...')\n#2 \/var\/www\/owncloud\/lib\/private\/DB\/MigrationService.php(401): OC\\Migrations\\Version20170526104128->changeSchema(Object(Doctrine\\DBAL\\Schema\\Schema), Array)\n#3 \/var\/www\/owncloud\/lib\/private\/DB\/MigrationService.php(358): OC\\DB\\MigrationService->executeStep(20170526104128)\n#4 \/var\/www\/owncloud\/lib\/private\/Updater.php(269): OC\\DB\\MigrationService->migrate()\n#5 \/var\/www\/owncloud\/lib\/private\/Updater.php(223): OC\\Updater->doCoreUpgrade()\n#6 \/var\/www\/owncloud\/lib\/private\/Updater.php(108): OC\\Updater->doUpgrade('10.0.7.2', '10.0.2.1')\n#7 \/var\/www\/owncloud\/core\/ajax\/update.php(190): OC\\Updater->upgrade()\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Schema\/SchemaException.php","Line":43}"}

This problem is affecting me since Nov-2017, I'm stuck on this version. The table doesn't exists, my database looks broken!

**Comment by PVince81** [comment] 2018-04-13 08:04
@iget-master what process are you using for upgrading ? the upgrade is supposed to create said table

**Comment by iget-master** [comment] 2018-04-13 14:51
@PVince81 just replaced the docker image version.

There's a fixed issue related on owncloud/core about this table, where for some reason it was not being created on v10.0.1 (or .0.2, don't remember). Probably I've migrated with this bug, the table wasn't created then this issue happened. That's my opinion.
