### ISSUE TITLE
Problems syncing graphical files

### ISSUE THREAD

**Issue by ovidiub13** [owncloud/core#7104] opened 2014-02-05 23:51 UTC
While syncing project files from GIMP or Krita, at random times the sync stops providing me with this error: "The item is not synced because of previous errors: The server did not provide an Etag."

After that the syncing stops. The server kind of crashes. I cannot connect to it via the web interface or the client.

### Expected behaviour
Sync to work normally, just sync the file(s) to the server.

### Actual behaviour
Sync stops with: "The item is not synced because of previous errors: The server did not provide an Etag.".

### Steps to reproduce
1. Create and edit GIMP or Krita projects.
2. Save changes to those files in a OwnCloud synced directory.
3. Repeat until error is received.

### Server configuration
Operating system: Debian 7
128MB RAM

1 OwnCloud user.

Web server: apache2

Database: mysql  Ver 14.14 Distrib 5.5.35, for debian-linux-gnu (i686) using readline 6.2

PHP version: PHP 5.4.4-14+deb7u7 (cli) (built: Dec 12 2013 10:55:22) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2012 Zend Technologies

ownCloud version: (see ownCloud admin page)

Updated from an older ownCloud or fresh install: fresh install.

List of activated app: Files. Because of this error and from what I've read in the apache error log I've disabled all other apps.

The content of config/config.php: (Without the database password and passwordsalt)
<?php                                                                                                                                
$CONFIG = array (                                                                                                                    
  'instanceid' => 'oc17705b99a2',                                                                                                    
  'passwordsalt' => '',                                                                                
  'datadirectory' => '/media/sf_ownCloud',                                                                                           
  'dbtype' => 'mysql',                                                                                                               
  'version' => '6.0.0.16', 
  'installed' => true,
  'loglevel' => '0',
  'enable_previews' => false,
);

Are you using external storage, if yes which one:
The server runs in a Virtual Machine. The data directory is in a shared directory that lies on an external USB 2TB HDD. There were no power outages or other electricity problems. I'm using the same HDD for other services as well, and I haven't had any problems with them.

### Client configuration
Browser: Chromium.

Operating system: Arch Linux

#### Web server error log
```
[Thu Feb 06 00:56:08 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 7243396\\n    [mtime] => 1391618389\\n    [storage_mtime] => 1391618389\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f26cddd67a1\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391640963\\n    [size] => -1\\n    [etag] => 52f2c1878f24c\\n    [storage_mtime] => 1391640963\\n)\\n","level":0,"time":"2014-02-05T22:56:07+00:00"}
[Thu Feb 06 01:09:30 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 7723055\\n    [mtime] => 1391640963\\n    [storage_mtime] => 1391640963\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c1878f24c\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391640974\\n    [size] => -1\\n    [etag] => 52f2c4aa03019\\n    [storage_mtime] => 1391640974\\n)\\n","level":0,"time":"2014-02-05T23:09:30+00:00"}
[Thu Feb 06 01:12:23 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 8291041\\n    [mtime] => 1391640974\\n    [storage_mtime] => 1391640974\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c4aa03019\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391641778\\n    [size] => -1\\n    [etag] => 52f2c556d6e93\\n    [storage_mtime] => 1391641778\\n)\\n","level":0,"time":"2014-02-05T23:12:22+00:00"}
[Thu Feb 06 01:13:10 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 9117041\\n    [mtime] => 1391641778\\n    [storage_mtime] => 1391641778\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c556d6e93\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391641945\\n    [size] => -1\\n    [etag] => 52f2c5863c530\\n    [storage_mtime] => 1391641945\\n)\\n","level":0,"time":"2014-02-05T23:13:10+00:00"}
[Thu Feb 06 01:13:13 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10533\\n    [storage] => home::ovidiub13\\n    [path] => files\\/Nunta\\n    [parent] => 2\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 19848319\\n    [mtime] => 1391641946\\n    [storage_mtime] => 1391641946\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c55b74a1f\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391641989\\n    [size] => -1\\n    [etag] => 52f2c588cb484\\n    [storage_mtime] => 1391641989\\n)\\n","level":0,"time":"2014-02-05T23:13:13+00:00"}
[Thu Feb 06 01:13:59 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 9942980\\n    [mtime] => 1391641945\\n    [storage_mtime] => 1391641945\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c5863c530\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391641994\\n    [size] => -1\\n    [etag] => 52f2c5b7d0ee8\\n    [storage_mtime] => 1391641994\\n)\\n","level":0,"time":"2014-02-05T23:13:59+00:00"}
[Thu Feb 06 01:14:13 2014] [error] [client 192.168.2.65] {"app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-02-05T23:14:13+00:00"}
[Thu Feb 06 01:23:47 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_versions\\/Nunta' !!! \\ncache: Array\\n(\\n    [fileid] => 10179\\n    [storage] => home::ovidiub13\\n    [path] => files_versions\\/Nunta\\n    [parent] => 10178\\n    [name] => Nunta\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 10464856\\n    [mtime] => 1391641994\\n    [storage_mtime] => 1391641994\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f2c5b7d0ee8\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391642382\\n    [size] => -1\\n    [etag] => 52f2c80313ebe\\n    [storage_mtime] => 1391642382\\n)\\n","level":0,"time":"2014-02-05T23:23:47+00:00"}
[Thu Feb 06 01:26:51 2014] [error] [client 192.168.2.65] {"app":"core","message":"redirectToDefaultPage: http:\\/\\/owncloud.geekaliens.com\\/index.php\\/apps\\/files","level":0,"time":"2014-02-05T23:26:51+00:00"}
[Thu Feb 06 01:27:35 2014] [error] [client 192.168.2.65] {"app":"OC\\\\Files\\\\Cache\\\\Scanner","message":"!!! No reuse of etag for 'files_trashbin\\/files' !!! \\ncache: Array\\n(\\n    [fileid] => 10170\\n    [storage] => home::ovidiub13\\n    [path] => files_trashbin\\/files\\n    [parent] => 10169\\n    [name] => files\\n    [mimetype] => httpd\\/unix-directory\\n    [mimepart] => httpd\\n    [size] => 32217127\\n    [mtime] => 1391623109\\n    [storage_mtime] => 1391623109\\n    [encrypted] => \\n    [unencrypted_size] => 0\\n    [etag] => 52f27bd3db833\\n)\\n \\ndata: Array\\n(\\n    [mimetype] => httpd\\/unix-directory\\n    [mtime] => 1391642036\\n    [size] => -1\\n    [etag] => 52f2c8e6a6218\\n    [storage_mtime] => 1391642036\\n)\\n","level":0,"time":"2014-02-05T23:27:35+00:00"}
[Thu Feb 06 01:36:18 2014] [error] [client 192.168.2.65] {"app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2014-02-05T23:36:17+00:00"}
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"file_put_contents(\/media\/sf_ownCloud\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#184","level":2,"time":"2014-01-31T04:14:40+00:00"}
{"app":"PHP","message":"file_put_contents(\/media\/sf_ownCloud\/index.html): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/setup.php#185","level":2,"time":"2014-01-31T04:14:40+00:00"}

```

I will provide any other necessary information to fix this.

**Comment by PVince81** [comment] 2015-03-23 17:00
Are you guys still getting these issues with 7.0.5 or 8.0.2 ?

**Comment by werwer18** [comment] 2015-07-05 05:32
I can confirm, that this issue happens on Owncloud 8.03 and 8.04, for me up to now only with .jpg file extension: missing ETAG.
If I rename the same files, p.ex. into .jpg1 extension they are synced properly. Even the renaming back into .jpg is synced accordingly and the result is a properly synced file on both sides.

While this can be a method of syncing properly, it is of course way to cumbersome.

It also shows the method of resolution for OC developers: just provide the same way of syncing for .jpg
(and maybe also other types of extensions) like for unknown extensions such as .jpg1

I have not the slightest idea, why it should be worthwhile to observe the extension for syncing, but
hey that is what happens right now. If this is the fault of OC or Apache or whatever. It is clear that OC should work in all thinkable configs so the actions for devs are clear by now.

Hope this will make it into 8.1, otherwise it would be a shame, such a flaw in a nearly perfect base system (lets not talk about extensions here).

**Comment by PVince81** [comment] 2015-07-06 08:27
@werwer18 there is no special handling for file extensions in ownCloud.
Maybe your web server (Apache?) has some modules that do something special when uploading/downloading images and interfering with ownCloud's sync system ?

Mind posting your setup using the issue template ? https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Comment by werwer18** [comment] 2015-07-09 06:15
I am running php 5.6 using graphicsmagick. Can you send a list of php modules required to run oc without flaws. In 5.6 you have to specify each and every module seperately otherwise it is missing in the php functionality. 

Yes it is Apache, any precautions for that?

I assume in this case you can NOT verify this behavior? So this runs ok at your side? No ETAG issue?

**Comment by werwer18** [comment] 2015-07-09 08:31
Just upgraded to OC 8.1 and the problem is gone, so definitely connected to Owncloud.

Now calendar ad contacts not working anymore, very cumbersome.

**Comment by PVince81** [comment] 2015-07-09 08:34
I never had any issues with graphical files. You might need ImageMagick, not sure what GraphicsMagick is.

**Comment by PVince81** [comment] 2015-07-09 08:35
but also ImageMagick is only to be able to display previews in the web UI. If you don't have it it should not show previews.

**Comment by PVince81** [comment] 2015-07-09 08:36
@werwer18 calendar and contacts should work. These apps might need upgrading, please check in the apps page.

**Comment by PVince81** [comment] 2015-07-09 08:37
(well they work on my server, I use them for syncing)
Calendar should be version 0.7.0 and contacts 0.3.1.0

**Comment by werwer18** [comment] 2015-07-11 21:48
You are right they just needed upgrading. Now I have the cron job problem back: cron job is not working at all. 

Error 	PHP 	Array to string conversion at ........../lib/private/template/functions.php#36 	
Error 	PHP 	Undefined index: SCRIPT_FILENAME at ............/lib/base.php#144 

No resolution available from other posts.

**Comment by PVince81** [comment] 2015-07-13 06:39
@werwer18 See https://github.com/owncloud/core/issues/7715

You might need to run cron with "php-cli cron.php" instead of "php cron.php" depending on what distribution you are using.

**Comment by werwer18** [comment] 2015-07-16 18:02
Sure I tried this as well, looks like php is using cli anyway. Basically gave up on this, using AJAX, which is a shame.

Is cron needed for syncing calendar and adressbook, or files upload? What is done every 15 mins (as recommended)?
Some have it runnning every minute, what makes more sense?

Well mine crashes, so giving no errors on the command line, if I run it directly, but in the error log.

Can it be that these errors come not from cron? But the oc system says cron is not run. But I can run it from the command line without errors. Very strange.

**Comment by PVince81** [comment] 2015-07-17 08:16
Cron is not needed for syncing. It's for operations like sending emails for activities, updating news feeds if you have the news app, etc.
However starting with 8.1 cron is needed to auto-expire versions and trashbin files.

**Comment by werwer18** [comment] 2015-07-23 07:29
The jpg syncing problem still persists in Owncloud 8.1. It is the well known missing ETAG thing and is connected solely to the filetype .jpg. Renamed files with p.ex. renamed to jpg1 can be synced properly. 

So OC must evaluate in a way the file extension and do some extra magic with .jpg which apparently fails. Apache 2.4 handles .jpg correctly and I have no othe problems with .jpg in many other installations I host.

One more issue I came across:
files_encryption app is deprecated in OC8.1 but still delivered. On a clean install, when users activate by mistake the delivered files_encryption (replaced by encryption in 8.1) this messes up the whole system database and OC asks you to upgrade the encryption keys (from what? new already).

You should remove deprecated libs on a clean install, to avoid confusion. If it is needed for upgrade, it should be deleted by the installer if a clean install is detected. I think a lot of the problems users encounter in this forum can be reduced to this problem. It gave me nights of error search before I just deleted this app and it was fine then.

**Comment by PVince81** [comment] 2015-07-27 12:54
@werwer18 can you try maybe disabling previews ? See https://github.com/owncloud/core/blob/master/config/config.sample.php#L646. But as far as I know the previews are only generated when viewing the file list in the web UI. Uploading a ".jpg" shouldn't make a difference.

Do you have any third party apps enabled that might do something with uploaded jpg files ? You could try disabling them temporarily one by one until jpg upload works again.

**Comment by werwer18** [comment] 2015-07-27 18:19
Found it. It was a leech protection on the server which was overlaying the htacess file. Selective for images. Apparently htacess files can be cascading, new to me. Was thinking the lowest in hierachy prevails. But apparently all properties from the higher one which are not explicitely overwritten by the local one are still there.

**Comment by Kawohl** [comment] 2015-10-08 08:53
Closing since not related to owncloud.

**Closed** 2015-10-08 08:55 UTC
Labels: bug
