### ISSUE TITLE
Email templates are chosen based on sender language not recipient

### ISSUE THREAD

**Issue by srggavrilov** [owncloud/core#16797] opened 2015-06-08 12:42 UTC
### Steps to reproduce
1. Choose lang1 language for user1 and lang2 for user2 at their profiles
2. Share file from user1 for user2, check "notify by email"

### Expected behaviour
User2 gets notification email in lang2 language

### Actual behaviour
User2 gets notification email in lang1 language

### Server configuration
**Operating system**: 3.16.0-30-generic x86_64 GNU/Linux
**Web server:** Apache/2.4.7

**Database:** mysql  Ver 14.14 Distrib 5.5.43

**PHP version:** PHP 5.5.9-1ubuntu4.9

**ownCloud version:** ownCloud 8.0.3 (stable) 

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by MorrisJobke** [comment] 2015-06-08 20:38
Duplicate of #7417

**Closed by MorrisJobke** 2015-06-08 20:38 UTC
Labels: enhancement
