### ISSUE TITLE
[8.2.2] Unused old external storages still in DB

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#22431] opened 2016-02-16 14:12 UTC
I saw that some old testing storages are kept in the database and are not configured with anything or never worked:

for example:
in oc_storage I have
smb::foo@10.1.10.103//carlos//
smb::carlos@10.1.10.13//carlos//

There are in oc_filecache too.

Is there any way to purge all old and unused storage and file information that is not anymore needed?

@MorrisJobke

**Comment by MorrisJobke** [comment] 2016-02-16 14:22
cc @Xenopathic @icewind1991 @PVince81

**Comment by cdamken** [comment] 2016-02-24 13:14
Do you need more info?

**Comment by cdamken** [comment] 2016-03-01 10:01
@MorrisJobke Ping?

**Comment by PVince81** [comment] 2016-03-03 12:43
How old ?

In 8.2.2 if you delete over the web UI it will automatically delete the selected entries (unless it uses the $user variable). I suspect these are older than 8.2 where OC wasn't deleting them.

Can you confirm ?

We cannot safely automatically delete those afterwards due to data structure limitations. If they are sure it's not used they can delete them manually.

**Comment by cdamken** [comment] 2016-03-03 13:59
> How old ?

Updated from an older ownCloud or fresh install:
8.1.0.8 -> 8.1.3.0 -> 8.1.4 -> 8.2.2

> In 8.2.2 if you delete over the web UI it will automatically delete the selected entries (unless it uses the $user variable). I suspect these are older than 8.2 where OC wasn't deleting them.

> Can you confirm ?

Created and deleted over the WebUI, but they where not with $user variable. all with username and password. to tell the truth I don't remember when I created them for the first time.

I tested now and in 8.2.2 are erased, but the old are still there. I will erase them manually.

But, I notices that the shared (from the issue: https://github.com/owncloud/core/issues/22759) are still in the oc_storage:
```
| shared::/Blah Blah                                              |        161 |         1 |         NULL |
```

The non existing shares have still a record in the database.

**Comment by PVince81** [comment] 2016-03-03 14:07
Can you check what files are in oc_filecache where storage=161 ?

**Comment by cdamken** [comment] 2016-03-03 14:11
```
MariaDB [ocdamken]> select * from oc_filecache where storage=161;
Empty set (0.00 sec)
```

**Comment by PVince81** [comment] 2016-03-03 14:14
Those entries are usually remote shares mounted locally.

**Comment by cdamken** [comment] 2016-03-03 14:26
In this case where not mounted locally, only shared by link and shared to user where the folder was deleted without removing the share

**Comment by PVince81** [comment] 2016-03-07 11:19
The stray external share is a duplicate of https://github.com/owncloud/core/issues/15701

**Closed by PVince81** 2016-03-07 11:19 UTC
