### ISSUE TITLE
[Sharing] Changing the password of a shared folder link in server A causes a bad UX accessing to it from server B

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#14577] opened 2015-02-27 13:48 UTC
### Steps to reproduce
1. Create a folder and upload some files in server A
2. Share the folder as shared link, and make it password protected
3. Open the shared link in another browser and add the link to your ownCloud - server B (follow the normal process, putting the correct passwords)
4. You should be able to get the shared folder in your server B and access normally to it.
5. Go to the server A and change the password to the link shared with server B
6. Try to access to the shared folder from server B (tested after loging out and loging in to clear session info just in case, but probably it's not needed)

### Expected behaviour
An error is shown to the users, ideally notifying that the password changed and allowing the user to input the new password

### Actual behaviour
The folder appears normally. After trying to enter to it a "service unavailable" notification is shown and the folder disappears.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** both servers stable8

**Updated from an older ownCloud or fresh install:** both servers fresh install

### Notes
I found the UX harsh in this case because there is no warning that the shared folder is "disconnected". The folder is deleted after that, so it's likely that the user doesn't know what server the folder comes from, and he won't be able to get access to the file again

**Comment by jvillafanez** [comment] 2015-03-02 09:53
Something similar happens when the shared link expires: checked with a file instead of a folder, the file shows after the link is expired in server B; accessing the file causes a "file not found" error showing in the template, and later the file is deleted in server B

**Comment by PVince81** [comment] 2015-10-27 14:29
Closing as duplicate of https://github.com/owncloud/core/issues/13564, at some point a password dialog should be added

**Closed by PVince81** 2015-10-27 14:29 UTC
Labels: enhancement, feature:federated-cloud-sharing
