### ISSUE TITLE
External Storage SMB/CIFS File Datetime not refreshed in owncloud

### ISSUE THREAD

**Issue by anduz** [owncloud/core#15925] opened 2015-04-29 09:17 UTC
Hello,

I've found an issue replacing some files in a sub-folder of a SMB/CIFS external storage.
After replacing the files, the "Modified" date didn't change.
Then I deleted the files and copied them again into the folder and now it's fine.

Best regards
Anduz

**Comment by Xenopathic** [comment] 2015-04-29 10:03
Duplicate of #11797

@anduz Unfortunately this is a known issue that we've been struggling with for a long time. In oC 8.1 you can mitigate the issue somewhat by setting `filesystem_check_changes` to `1` in the relevant `mount.json` entry (documentation forthcoming).

**Closed by Xenopathic** 2015-04-29 10:03 UTC
