### ISSUE TITLE
owncloud upgrade from 7.0.1 to 7.0.2 fails on a PostgreSQL DB that has other schemas

### ISSUE THREAD

**Issue by rocklob** [owncloud/core#11601] opened 2014-10-15 20:18 UTC
### Steps to reproduce
1. Take an existing PostgreSQL DB that already has non-owncloud schemas in it.  (In my case, there is a gitlab schema, among others.)
2. Create an owncloud user
   	  `createuser -P owncloud`
3. Create an owncloud schema:
   	  `create schema owncloud authorization owncloud;`
4. Install owncloud 7.0.1 (in my case, I'm running it in a docker container from https://registry.hub.docker.com/u/jchaney/owncloud/, but I don't think that this has any bearing on the problem.)
5. Configure owncloud to use the PostgreSQL database/user referenced above.
6. Confirm that owncloud created its tables in the owncloud schema:
     	  `\dt owncloud.*`
7. Initiate the owncloud upgrade process to 7.0.2 in the admin UI or on the command-line with `occ upgrade`.

### Expected behaviour
The upgrade should work.

### Actual behaviour
Even though `occ upgrade` says the update was successful, it was not.  The problem appears to be that owncloud is trying to access tables in other schemas.  Here is the output from `occ upgrade`:
```
Turned on maintenance mode
An exception occurred while executing 'SELECT min_value, increment_by FROM gitlab.broadcast_messages_id_seq':

SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema gitlab
LINE 1: SELECT min_value, increment_by FROM gitlab.broadcast_message...
                                            ^
Turned off maintenance mode
Update successful
```
### Server configuration
**Operating system**:
Docker host is running Arch Linux
Docker container where owncloud lives is running Ubuntu 14.04

**Web server:**
nginx/1.4.6

**Database:**
PostgreSQL 9.3.5

**PHP version:**
PHP 5.5.9-1ubuntu4.3

**ownCloud version:** (see ownCloud admin page)
7.0.1

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
(none)

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc30a95612c2',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'owncloud.int:8443',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'main',
  'dbhost' => '172.17.42.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### Web server error log
```
N/A
```

#### ownCloud log (data/owncloud.log)
```
{"app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'SELECT min_value, increment_by FROM gitlab.broadcast_messages_id_seq':\n\nSQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema gitlab\nLINE 1: SELECT min_value, increment_by FROM gitlab.broadcast_message...\n                                            ^' in \/var\/www\/owncloud\/lib\/private\/db\/migrator.php:117\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(75): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(111): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/owncloud\/lib\/private\/db.php(337): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(225): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(187): OC\\Updater->checkCoreUpgrade()\n#5 \/var\/www\/owncloud\/lib\/private\/updater.php(139): OC\\Updater->doUpgrade('7.0.2.1', '7.0.1.1')\n#6 \/var\/www\/owncloud\/core\/command\/upgrade.php(110): OC\\Updater->upgrade()\n#7 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(244): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(897): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(191): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(121): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/owncloud\/console.php(43): Symfony\\Component\\Console\\Application->run()\n#12 \/var\/www\/owncloud\/occ(11): require_once('\/var\/www\/ownclo...')\n#13 {main})","level":4,"time":"2014-10-15T20:03:12+00:00"}
```

#### Browser log
```
N/A
```

**Comment by PVince81** [comment] 2015-03-28 12:30
@rocklob are you still seeing this with 7.0.5 or 8.0.2 ?

I believe that code has been added to make sure only the relevant tables are migrated.

**Comment by patcable** [comment] 2015-06-24 22:06
I'm seeing this when migrating to 6.0 to 7.0.6. Did you eventually figure something out, @rocklob?

**Comment by rocklob** [comment] 2015-06-30 18:41
Unfortunately, I never did figure out a clean solution.  I didn't really pursue it and am not actively using owncloud anymore.

**Comment by remixtj** [comment] 2015-07-15 07:52
I can confirm also upgrading from 7.03 to 7.0.7. Now i'll debug a bit

**Comment by remixtj** [comment] 2015-07-15 13:15
The bug is in DBAL Library. The function listSequences called by createSchema in AbstractSchemaManager wants to read all sequences of the db due to a query that doesn't check if the currently connected user has access to that schema.

```
--- owncloud.old/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php	2015-07-03 12:36:42.000000000 +0200
+++ owncloud.new/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php	2015-07-15 14:44:18.015268996 +0200
@@ -167,7 +167,7 @@
                 FROM
                    pg_class c, pg_namespace n
                 WHERE relkind = 'S' AND n.oid = c.relnamespace AND
-                    (n.nspname NOT LIKE 'pg_%' AND n.nspname != 'information_schema')";
+                    (n.nspname NOT LIKE 'pg_%' AND n.nspname != 'information_schema') AND has_schema_privilege(n.nspname,'usage');";
     }
```

This is the patch i wrote.

**Comment by remixtj** [comment] 2015-07-15 13:59
Seems that from dbal 2.5 the query has changed, and now returns correct data. The issue is so limited to owncloud prior to 8, because is using an older version.

**Comment by PVince81** [comment] 2015-10-08 12:19
So if I understand well this works properly on OC 8.0 ?
I don't think we can easily upgrade the DBAL version on older ownCloud as there is a big risk of breakage. (CC @DeepDiver1975)

Closing hence.

**Closed by PVince81** 2015-10-08 12:19 UTC
Labels: bug, db:postgresql, update
