### ISSUE TITLE
Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/core#25869] opened 2016-08-19 09:20 UTC
I dont know exactly where to post, so i will leave here.
Could this key be 'fixed' to avoid this warning ?

 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg: Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)

**Comment by DeepDiver1975** [comment] 2016-08-19 09:58
@jnweiger @crrodriguez is there anything we can/should do? THX

**Comment by jnweiger** [comment] 2016-08-19 14:01
We probably should generate a new key and take the complains for invalidating the old key. We don't seem to have an option to edit or update the existing key :-(

duplicate of https://github.com/owncloud/client/issues/505

**Closed by jnweiger** 2016-08-19 14:01 UTC
Labels: packaging

**Comment by crrodriguez** [comment] 2016-08-19 17:27
@jnweiger edit or update the current key..would violate the security model afaik..

**Comment by dominix** [comment] 2016-08-19 20:56
I guess you have to change the security model if it is based  on a weak key ...
anyway it's an issue. people can not use your'e repository, so you can not just "close" the issue, at least let it open  for the people to know that.

**Comment by crrodriguez** [comment] 2016-08-19 21:00
@dominix You got it the wrong way.. the build system only alllows to extend the expiration date of a key or create a new pair. .. you cannot "edit" or "update" the key in the traditional sense..if the key is weak.. we can only issue a new one.

**Comment by RealRancor** [comment] 2016-08-21 12:04
@dominix 
> so you can not just "close" the issue, at least let it open for people to know that

Wrong repo -> closed

And an open issue is btw still available at the correct client issue tracker (https://github.com/owncloud/client/issues/5055) so they will find it if they are looking at the correct repository

**Comment by jsalatiel** [comment] 2016-08-21 13:01
what you mean by wrong repo ? What would be the correct one ?

**Comment by RealRancor** [comment] 2016-08-21 13:04
@jsalatiel https://github.com/owncloud/client/issues/5055 as already pointed out twice

**Comment by jsalatiel** [comment] 2016-08-21 13:27
@RealRancor i think i am really dumb now since i do not see the correctly repo on the link you pointed.

The repo i use is : http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key

There are two repos in that issue you pointed:
The one i use http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04 and /Release.key and  http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/Release for ubuntu 14.04 variants.

I have no expired keys:

# sudo apt-key list | grep expired
no results

Tried to reget the keys using:
sudo apt-key adv --recv-keys --keyserver keys.gnupg.net BA684223
Executing: /tmp/tmp.9krXUgujcV/gpg.1.sh --recv-keysv --keyserver keys.gnupg.net BA684223
gpg: requesting key BA684223 from hkp server keys.gnupg.net
gpg: key BA684223: "isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>" 5 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 5

But it still shows the error 
# sudo sudo apt-get update
W: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg: Signature by key F9EA4996747310AE79474F44977C43A8BA684223 uses weak digest algorithm (SHA1)

**Comment by RealRancor** [comment] 2016-08-21 13:34
@jsalatiel Just in simple words:

https://github.com/owncloud/core/issues -> ownCloud **SERVER** where **you have** reported this issue here

https://github.com/owncloud/client/issues -> ownCloud **CLIENT** where **you should have** reported this issue

And in the second repository you will find the (already pointed out and still open) issue https://github.com/owncloud/client/issues/5055 . As this issue is not solved yet it should be obvious that you're still getting this error.

**Comment by jsalatiel** [comment] 2016-08-21 13:41
Thanks !
