### ISSUE TITLE
error in updating

### ISSUE THREAD

**Issue by baseKo** [owncloud/core#16285] opened 2015-05-12 15:17 UTC
I got the following message while updating ownCloud to version 8.1 beta 1 (from 6 or 7.0? I'm not sure.)
-----
An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
The update was unsuccessful. Please report this issue to the ownCloud community.
-----
What can I do?

**Comment by RealRancor** [comment] 2015-05-12 15:34
Hi,

Duplicate of: https://github.com/owncloud/core/issues/16008 , https://github.com/owncloud/core/issues/16063, https://github.com/owncloud/core/issues/16066 , https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/16097 , https://github.com/owncloud/core/issues/16157 , https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218 , https://github.com/owncloud/core/issues/16280

Documentation for this is also available here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting

**Closed** 2015-05-12 17:24 UTC
