### ISSUE TITLE
very high disk load with webdav

### ISSUE THREAD

**Issue by h-2** [owncloud/core#13786] opened 2015-01-29 23:27 UTC
### Steps to reproduce
1. start kodi on my android device
2. add owncloud share as webdavs
3. scan library
4. click on a movie

### Expected behaviour
 the movie should play and everyone should be happy; the server might spend som cycles on php and some on io, but not more than 10% cpu load.

### Actual behaviour
owncloud spawn some php-cgi scripts that go rampage with disk-io, causing the disk encryption subsystem of the kernel to use up all the cpu on all the cores; resulting in poor response time; the server is unable to serve the file to the android client.
This could of course be the client-app causing problems BUT even if I kill the client app (kodi) the process don't die on the server until 5minutes later...

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE

**Web server:** lighttpd-1.4.35_5

**Database:** postgresql94-server-9.4.0

**PHP version:** php5-5.4.36 

**ownCloud version:** owncloud-7.0.4

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** activity, bookmarks, calendar, contacts, documents, external storage support, first run wizard, mail template editor, pdf viewer, share files, text editor, updater, video viewer

**The content of config/config.php:**
```
post_max_size = 2000M
upload_max_filesize = 1999M
upload_tmp_dir = /tmp
cgi.fix_pathinfo = 1
memory_limit = 32M

error_reporting = E_ALL & ~E_NOTICE
display_errors = 0
log_errors = 1
html_errors = 0
fastcgi.logging = 1


[PostgresSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no (at least not in owncloud)

#### Web server error log
Nothing is logged to the server during the error...

#### ownCloud log (data/owncloud.log)

Nothing is logged to the owncloud log during the issue. I do however have some other (unrelated?) entries there:
```
{"reqId":"54cabe623cdd5","app":"core","message":"Unable to parse OCS content for app 166052","level":4,"time":"2015-01-29T23:12:36+00:00","method":"GET","url":"\/index.php\/settings\/js\/apps-custom.js?appid="}

...
{"reqId":"54cabfb62ef5c","app":"carddav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-29T23:18:14+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/hannes\/"}
{"reqId":"54cabfb76341c","app":"carddav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-29T23:18:15+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/hannes\/kontakte\/"}

```

### Other comments

Note that FreeBSD uses ZFS which is a copy-on-write filesystem, so maybe something causes owncloud to repeatedly dump the database to disk (or something else?) which causes this. Otherwise I am kind of at a loss with ideas.. I mean, why should anything at all be written to the server's disk, when it is supposed to stream a file to the outside?

**Comment by schiesbn** [comment] 2015-01-30 09:39
If I remember correctly the webdav implementation from ownCloud doesn't support streaming from a webdav resource but creates a local copy to read the file. This should explain why your disk encryption subsystem gets busy  cc @PVince81 is this correct?

**Comment by PVince81** [comment] 2015-01-30 10:14
@schiesbn no, WebDAV will simply do a fopen() on the file. If the file is directly on disk, it will stream it.
If it's on external storage, the ext storage will make a copy.
In the case of encryption, the fopen proxies would take care of reading directly from disk and decrypting on the fly.

**Comment by PVince81** [comment] 2015-01-30 10:18
Also @h-2 mentionned disk encryption, not ownCloud encryption, so probably not related.

I wonder if Kodi is simply streaming the file from disk or doing multiple RANGE requests ?

From what I remember SabreDAV should be able to do fopen() + fseek() to read the proper pieces of the file.

@h-2 are you able to find out details about what files are accessed repeatedly ? Can you check the access log and see how many requests Kodi is making for a single file ? (to rule out the RANGE case)

**Comment by h-2** [comment] 2015-01-30 11:23
Thanks for your quick replies and hi to Björn from a fellow fellow ;)

@PVince81 you mentioned:
> If it's on external storage, the ext storage will make a copy.

A copy from where to where? From the ext storage to local storage of the owncloud? Or from ext storage to the client?
If it's from ext storage to local, does this also happen if the external storage is actually just a local dir? Because if there is an overhead involved there, I can change it to where the directory is directly mounted into the tree of my user and then shared from there (instead of external storage being made available to the group).

I am quite sure that it is not copying to the client, because I do see the first frames of the movie (albeit it very slowly) on the android device.

> @h-2 are you able to find out details about what files are accessed repeatedly ? Can you check the access log and see how many requests Kodi is making for a single file ? (to rule out the RANGE case)

I will check when I am back home. Which log file is that exactly?

**Comment by PVince81** [comment] 2015-01-30 11:25
If the external storage is of type "Local" it should access the files directly, not do a copy.
But for others like SMB or Dropbox a fopen() would first download the file to a temp dir.
The exception is SFTP which supports direct streaming.

**Comment by h-2** [comment] 2015-01-31 18:28
Ok, when I try to rescan the library it it says "preparing" in Kodi, then it is quickly done. Immediately cpu load goes up and stays up for quite some time.

top -PSa says:
```
  PID USERNAME    THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
  741 root          1  45    -     0K    16K geli:w  1 554:25  34.86% [g_eli[1] gpt/zdata_]
  732 root          1  52    -     0K    16K CPU0    0 565:38  26.66% [g_eli[0] gpt/zdata_]
  736 root          1  52    -     0K    16K RUN     0 557:07  26.56% [g_eli[0] gpt/zdata_]
  737 root          1  52    -     0K    16K RUN     1 563:56  25.88% [g_eli[1] gpt/zdata_]
  740 root          1  42    -     0K    16K geli:w  0 569:50  25.00% [g_eli[0] gpt/zdata_]
  733 root          1  52    -     0K    16K RUN     1 549:39  25.00% [g_eli[1] gpt/zdata_]
39284 www           1  26    0   193M 22912K RUN     1   2:13  11.47% /usr/local/bin/php-cgi
    0 root        317  -8    0     0K  5072K -       0 520:19   8.35% [kernel]
    3 root         12  -8    -     0K   224K zvol:i  1  27.1H   2.49% [zfskern]
```
I think the `geli:w` hints that it is indeed a write-process that is causing the load, but I am not 100% sure. lighttpd's acces.log says this when the update is triggered:
```
 **IP** *HOSTNAME* - [31/Jan/2015:17:55:51 +0000] "PROPFIND /remote.php/webdav/hannes_pub/video/ HTTP/1.1" 401 304 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:52 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 200 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:52 +0000] "HEAD /remote.php/webdav/.nomedia HTTP/1.1" 404 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:52 +0000] "HEAD /remote.php/webdav/ HTTP/1.1" 200 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:53 +0000] "GET /remote.php/webdav/ HTTP/1.1" 200 1978 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:53 +0000] "HEAD /remote.php/webdav/http://sabre.io/.nomedia HTTP/1.1" 404 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:53 +0000] "HEAD /remote.php/webdav/http://sabre.io/ HTTP/1.1" 404 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:54 +0000] "GET /remote.php/webdav/http://sabre.io/ HTTP/1.1" 404 304 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:54 +0000] "GET /remote.php/webdav/http://sabre.io/ HTTP/1.1" 404 304 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:54 +0000] "HEAD /remote.php/webdav/hannes_pub/video/ HTTP/1.1" 200 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:17:55:55 +0000] "HEAD /remote.php/webdav/hannes_pub/video/.nomedia HTTP/1.1" 404 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
```
About five minutes later it starts accessing files:
```
**IP** *HOSTNAME* - [31/Jan/2015:17:59:08 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE1.mkv HTTP/1.1" 206 32036 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:18:00:00 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE1.mkv HTTP/1.1" 206 32036 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:18:00:34 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE2.mkv HTTP/1.1" 206 32036 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:18:01:07 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE3.mkv HTTP/1.1" 206 32036 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:18:02:10 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE4.mkv HTTP/1.1" 206 32036 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
**IP** *HOSTNAME* - [31/Jan/2015:18:03:05 +0000] "GET /remote.php/webdav/hannes_pub/video/FILE5.mp4 HTTP/1.1" 206 32043 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
```

When clicking on a movie the log says:
```
**IP** *HOSTNAME* - [31/Jan/2015:18:17:28 +0000] "HEAD /remote.php/webdav/hannes_pub/video/FILE99.mkv HTTP/1.1" 200 0 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
```
Kodi then says that it couldn't playback the file and that I should check the logs...

**Comment by PVince81** [comment] 2015-02-02 08:40
Hmm strange. AFAIK heavy write operations should only happen on uploading, not on PROPFIND or HEAD.
So it looks like Kodi is using "HEAD", maybe something to have a look at.
I suppose it might do this to first get the size of the file and/or check whether it exists.

Also this is really strange:
```
**IP** *HOSTNAME* - [31/Jan/2015:17:55:54 +0000] "GET /remote.php/webdav/http://sabre.io/ HTTP/1.1" 404 304 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
```

It's as if something was redirecting Kodi to a bogus URL. Or do you have such a file/folder in your ownCloud ?

**Comment by h-2** [comment] 2015-02-02 11:23
> Hmm strange. AFAIK heavy write operations should only happen on uploading, not on PROPFIND or HEAD.
> So it looks like Kodi is using "HEAD", maybe something to have a look at.
> I suppose it might do this to first get the size of the file and/or check whether it exists.

I am not too sure anymore is actually writes and not reads... does the GET imply fetching the entire file? That would explain major slowdowns and load.. (fetching multpiple multi-GB files a second...).

>Also this is really strange:

```
**IP** *HOSTNAME* - [31/Jan/2015:17:55:54 +0000] "GET /remote.php/webdav/http://sabre.io/ HTTP/1.1" 404 304 "-" "Kodi/14.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) Android/5.0.2 Sys_CPU/armv7l App_Bitness/32 Version/14.0-Git:2014-12-23-ad747d9-dirty"
```

> It's as if something was redirecting Kodi to a bogus URL. Or do you have such a file/folder in your ownCloud ?

Well, maybe some weird protocol mangling takes place. If you access owncloud's webdav-url (e.g. demo.owncloud.org/remote.php/webdav ) through http or https you get an html document that includes the aforementionend link... but this is wild speculation here.

**Comment by PVince81** [comment] 2015-02-02 15:23
Yes, a GET operation is for downloading the whole file, unless range headers are passed which would ask ownCloud to only deliver a specific piece of file (which I'd expect to happen when seeking).

Does the Kodi client stream the files or does it first downloads them then cache them locally ?

**Comment by h-2** [comment] 2015-02-02 22:07
> Yes, a GET operation is for downloading the whole file, unless range headers are passed which would ask ownCloud to only deliver a specific piece of file (which I'd expect to happen when seeking).

Can you see this based on the info above, or is there some way I can find out whether or not this is the case? Also not that the larger block in my previous psot was from scanning the database, it definitely shouldn't fetch entire files for that.

> Does the Kodi client stream the files or does it first downloads them then cache them locally ?

I sincerely hope it streams them, otherwise the feature would be rather pointless...

**Comment by PVince81** [comment] 2015-02-02 22:34
Have you tried with desktop Kodi ?

@jknockaert provided a PR to make range requests work with encryption, so he tested with desktop XBMC, which means that at least that version should stream instead of a full download.

Not sure about the Android Kodi you're using right now. You could compare performance ?

I don't have time right now but later I'll try and debug the HEAD calls and see what ownCloud does to make sure it isn't doing too much useless stuff.

**Comment by h-2** [comment] 2015-02-02 23:46
> Have you tried with desktop Kodi ?

I haven't yet, but I hope I get time to do so in the next days.

> @jknockaert provided a PR to make range requests work with encryption, so he tested with desktop XBMC, which means that at least that version should stream instead of a full download.

Hm, ok. There is also an extra owncloud plugin for kodi/xbmc, but that isn't working for other reasons. Maybe that will be fixed soon, though, as well.

**Comment by h-2** [comment] 2015-02-04 14:38
> Have you tried with desktop Kodi ?

I have tried with desktop xbmc-13 and the behaviour is the same. I initially add a directory, the scan completes, i.e. I get the list of videos. Load during the initial scan is only caused by php-cgi and no crazy IO. Then after two minutes I want to browse the files again (not even starting a movie), disk-io spikes on the server, xbmc hangs briefly then says that it cannot connect to the server.
I quit xbmc and a two minutes later the IO stops again on the server.

**Comment by jknockaert** [comment] 2015-02-09 16:44
@h-2 I will update #12909 and test it with Kodi on Android. It definitely works fine with raspbmc (very responsive), but I didn't monitor resource. I have been testing the owncloud plugin in the past and I remember it had a number of issues (after which I decided to refactor the owncloud encrypted stream implementation).

**Comment by h-2** [comment] 2015-02-16 00:26
thanks @jknockaert  please bare in mind though that I am **not using encryption** by owncloud, I didn't completely understand whether #12909 was specific for that or general for range requests...

**Comment by jknockaert** [comment] 2015-02-16 07:12
@h-2 OK, my mistake. #12909 is specific to encrypted files.

**Comment by jknockaert** [comment] 2015-02-19 11:07
While testing the code for #12909 I observed that there's definitely something specific to the webdav client in Kodi for Android.

**Comment by PVince81** [comment] 2015-08-03 14:10
Did the seekable encryption wrapper help improve performance in 8.1 ?

**Comment by jknockaert** [comment] 2015-08-03 14:17
I did some testing with Kodi, and skipping forward/backward to any point in a 2GB film happens almost instantly. So yes in that case it improves performance dramatically.

**Comment by PVince81** [comment] 2015-08-03 14:20
@h-2 are you still seeing issues with 8.0.5 or 8.1 ?

**Comment by danielreuther** [comment] 2015-09-15 00:08
Haven't done much debugging yet but it definitely feels like I'm suffering of the same issue on 8.1. After adding a WebDAV location to Kodi, I'm seeing very high load caused by kernel threads (I suppose because of LUKS?).

@h-2 Have you gotten further in analyzing this issue? I should definitely be able to collect more details about the requests Kodi makes to the server—if that would be of help.

**Comment by PVince81** [comment] 2015-09-21 14:17
@h-2 @danielreuther did you find any more insights regarding the performance issue ? Does it still happen with 8.1.3 ?

**Comment by h-2** [comment] 2015-09-21 18:08
I am still running 8.0.X but will get back to you once I have upgraded....

**Comment by cmonteroluque** [comment] 2015-10-01 17:56
This bug will fall off 8.2 if not resolved by 6 Oct

**Comment by danielreuther** [comment] 2016-02-29 00:56
Just did another quick test on 8.2.2. The following seems to be a somewhat typical sequence of requests from Kodi:
```
"HEAD /owncloud/remote.php/webdav/Media/Movie/.nomedia HTTP/1.1" 404 629 "-" "Kodi/16.0 (Windows NT 6.1; WOW64) App_Bitness/32 Version/16.0-Git:20160220-a5f3a99"
"HEAD /owncloud/remote.php/webdav/Media/Movie/ HTTP/1.1" 200 142 "-" "Kodi/16.0 (Windows NT 6.1; WOW64) App_Bitness/32 Version/16.0-Git:20160220-a5f3a99"a5f3a99"
"PROPFIND /owncloud/remote.php/webdav/Media/Movie/ HTTP/1.1" 207 1842 "-" "Kodi/16.0 (Windows NT 6.1; WOW64) App_Bitness/32 Version/16.0-Git:20160220-a5f3a99"
"HEAD /owncloud/remote.php/webdav/Media/Movie/Movie.avi HTTP/1.1" 200 629 "-" "Kodi/16.0 (Windows NT 6.1; WOW64)
```
And indeed, when manually doing a HEAD request on a large file, my kworker threads are spiking and it takes several seconds for the server to send a response. And to make things worse, Kodi seems to create quite a number of parallel threads, all doing HEAD requests.

My hunch right now would be that this is related to how Sabre implements HEAD requests (it's doing a full GET first but returns an empty body after that).

Anyone able to confirm unusually long response times for HEAD requests on large files? @h-2?

**Comment by danielreuther** [comment] 2016-02-29 01:57
Okay, sorry -- it's been too long ago that I read this thread. Looks like you guys were discussing HEAD requests before.

But thinking about it again, it feels like an inherently bad idea to read (and temporarily write?) whole files **without added network latency**. You could essentially saturate all available server processes for a long time, just by queuing up some HEAD requests to big files. And if you add OS-level encryption and RAID calcs to the mix, it becomes even worse.

**Comment by PVince81** [comment] 2016-02-29 09:22
@danielreuther this will need some debugging. I'd expect a HEAD request to only access the file cache's "size" field and not download any files.

**Comment by danielreuther** [comment] 2016-02-29 11:46
@PVince81 Sorry for not being too clear on this one -- the HEAD request will of course not send the file over the wire (that's why it's a HEAD request) but from a very brief look at Sabre (yesterday late night), I started to assume that **something** might cause Sabre to read the file in its entirety. I jumped to this conclusion because Sabre is internally calling httpGet and just sets the response body to an empty string afterwards (see here: https://github.com/fruux/sabre-dav/blob/master/lib/DAV/CorePlugin.php#L245).

Though, now that I looked at the code again, it's definitely not that obvious, since it does check if the response body should be sent before actually doing a stream_copy_to_stream.

**Comment by danielreuther** [comment] 2016-02-29 13:56
Alright, I guess this could be a "simple" matter of updating Sabre to a later version.
After merging [this](https://github.com/fruux/sabre-dav/commit/4e16fa25b55e12f79c911a2b444e6b951aaeb7e3), the problem disappears :)

Would it be possible to get this into a next OC release?

**Comment by PVince81** [comment] 2016-02-29 14:00
9.0 is using Sabre 3.0.7, not sure if the fix is in.

I raised https://github.com/owncloud/core/issues/22724 for 9.1 to update to Sabre 3.1

**Comment by danielreuther** [comment] 2016-02-29 14:08
3.0.7 seems to have the fix -- great!

Any chance that the 4 lines from https://github.com/fruux/sabre-dav/commit/4e16fa25b55e12f79c911a2b444e6b951aaeb7e3 could make their way into a 8.2 maintenance release? It's a pretty bad bug after all; possibly with effects on system stability.

**Comment by h-2** [comment] 2016-02-29 21:28
> Any chance that the 4 lines from fruux/sabre-dav@4e16fa2 could make their way into a 8.2 maintenance release?

:+1:

**Comment by PVince81** [comment] 2016-03-01 08:54
No, we don't backport library fixes to older versions. The only way I see for this to work is to have Sabre backport their fix to 2.1 and then we could consider upgrading the Sabre version of 8.2.2, but also need to be careful that it doesn't break other things (regressions and all)

**Comment by RealRancor** [comment] 2016-03-06 21:00
Did a short  research for https://github.com/owncloud/android/issues/1074 and just found out that the fix hasn't made it into 2.1 however the changelog of 2.1.x is stating that https://github.com/fruux/sabre-dav/blob/3.1.1/CHANGELOG.md#212-2014-12-10

So its probably just a matter of pinging upstream for a backport?

**Comment by h-2** [comment] 2016-03-09 21:20
Hm, so is this fixed in owncloud 9 or any other version of owncloud? Or only upstream in sabredav?

**Comment by danielreuther** [comment] 2016-03-09 21:25
Should be fixed in 9 -- up until now I only tested merging the fix into 8.2, though. Will re-test as soon as I had a chance to upgrade.

Although, while it seems to fix the extremely high I/O for HEAD requests (i.e. when Kodi is indexing media), I still have some (load-related?) problems playing files. Will look into this, too.

**Comment by h-2** [comment] 2016-03-09 21:28
@danielreuther thanks a lot! +1

**Comment by PVince81** [comment] 2016-05-18 13:03
Any update ? Has it gotten better with 9.0.2 ?

**Comment by h-2** [comment] 2016-05-22 12:24
I have tried with a recent kodi from FreeBSD over the LAN and it seems to work very well with cpu load on the server high during initial scan, but low during watching (1-3%). Both server and client are responsive.
I will try with an android client from outside ASAP, but I am hopeful!

Thanks for looking into this.

**Comment by PVince81** [comment] 2016-06-17 15:02
I'm closing this now. If there are further issues with recent ownCloud versions, please reopen.

**Closed by PVince81** 2016-06-17 15:02 UTC
Labels: bug, performance
