### ISSUE TITLE
9.0.2 update from files_versions to 1.2.0

### ISSUE THREAD

**Issue by reportguy** [owncloud/core#25427] opened 2016-07-10 01:49 UTC
### Steps to reproduce
1. this came from FreeBSD ports
2. Updating from webui to 9.0.2
3. Status hang up "Updated "files_versions" to 1.2.0"

### Expected behaviour
Success message or redirect to homepage

### Actual behaviour
notifications: An exception occurred while executing 'CREATE TABLE `oc_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_notifications' already exists

### Server configuration
**Operating system**: FreeBSD

**Web server:** lighttpd-1.4.39_1

**Database:** mysql (mysql56-client-5.6.30

**PHP version:** php56-5.6-22

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:** Update, don't remember what build

**Where did you install ownCloud from:** pkg

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``` "No errors have been found."

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => 
  'trusted_domains' =>
  array (
    0 => '1.2.3.4',
    1 => 'domain.com',
  ),
  'datadirectory' => '/usr/local/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'dbname' => 'secret',
  'dbhost' => '1.2.3.9',
  'dbuser' => 'dbuser',
  'dbpassword' => '',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by RealRancor** [comment] 2016-07-10 07:52
> Well even with that error after re-running at the terminal it was successful. I did try it 3 times on web and 2 via command line.

from https://github.com/owncloud/core/issues/25421#issuecomment-231374351

**Comment by PVince81** [comment] 2016-10-06 07:28
duplicate of https://github.com/owncloud/core/issues/23867

**Closed by PVince81** 2016-10-06 07:28 UTC
