### ISSUE TITLE
Invitee to calendar event sees event in Contact Birthdays calendar!

### ISSUE THREAD

**Issue by Pazu** [owncloud/core#26746] opened 2016-11-30 10:31 UTC
### Steps to reproduce
1. Create users A and B
2. User A creates event in default Personal calendar and invites user B

### Expected behaviour
User B should see event in their own default Personal calendar

### Actual behaviour
User B sees event in their Contact Birthdays calendar

### Server configuration
**Operating system**: linux

**Web server:** Apache Version 	2.4.23

**Database:** MySQL Version 	10.1.19-MariaDB

**PHP version:** 5.6.24

**ownCloud version:** (see ownCloud admin page) 9.1.2

**Updated from an older ownCloud or fresh install:** Fresh install over old version

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Activity 2.3.2
Collaborative tags 0.3.0
Comments 0.3.0
Default encryption module 1.3.0
Federation 0.1.0
First run wizard 1.1
Gallery 15.0.0
Mail Template Editor 0.1
Notifications 0.3.0
Provisioning API 0.5.0
Share Files 0.10.0
Update notification 0.2.1
Video player 0.9.8
Calendar 1.4.1
Contacts 1.4.0.0
Documents 0.13.1
Tasks 0.9.3
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => [removed],
  'datadirectory' => [removed],
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'dbname' => [removed],
  'dbhost' => [removed],
  'dbtableprefix' => 'oc_',
  'dbuser' => [removed],
  'dbpassword' => [removed],
  'installed' => true,
  'instanceid' => [removed],
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'maintenance' => false,
  'singleuser' => false,
  'theme' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.owncloud.com/server/',
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'check_for_working_wellknown_setup' => true,
  'loglevel' => 3,
  'trusted_domains' => 
  array (
    0 => [removed],
  ),
  'cron_log' => true,
  'secret' => [removed],
  'mail_from_address' => [removed],
  'mail_smtpmode' => 'php',
  'mail_domain' => [removed],
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/',
  'tempdirectory' => [removed],
  'asset-pipeline.enabled' => true,
  'session_keepalive' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** yes/no Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Firefox 50.0.1

**Operating system:** Mac OS X 10.12.1 and Windows 7

#### Web server error log
```
Nothing obviously relevant in here, please request as necessary.
```

#### ownCloud log (data/owncloud.log)
```
Nothing obviously relevant in here, please request as necessary.
```

#### Browser log
```
Nothing obviously relevant in here, please request as necessary.
```

**Comment by Flachzange** [comment] 2016-12-18 19:28
I can confirm the bug. We can observe the same behaviour with 9.1.2 using Google Calendar App on Android to create the events and invitations.

I had to delete the new events of the birthday directly in the database due to its write protection.

**Comment by PVince81** [comment] 2016-12-22 12:15
@DeepDiver1975

**Comment by Flachzange** [comment] 2017-02-03 15:04
Any update on this issue? Is there something I could provide to help investigating? Issue still exists with 9.1.4.

**Comment by DeepDiver1975** [comment] 2017-05-17 12:55
Okay - I guess I finally was capable to reproduce this ....

**Comment by DeepDiver1975** [comment] 2017-05-17 13:10
... okay - it just takes the first calendar which is available .....

**Comment by DeepDiver1975** [comment] 2017-05-17 13:24
we need to adopt the sabre dav libary here .....

**Comment by felixboehm** [comment] 2017-10-04 16:52
Is this solved in 10.0.3 ?

**Comment by DeepDiver1975** [comment] 2017-10-04 18:21
> Is this solved in 10.0.3 ?

no

**Comment by Mito73** [comment] 2017-10-05 11:38
Well, this ist frustrating: I assumed that this issue would be fixed in 10.0.3 since it is referenced to [#28011](https://github.com/owncloud/core/pull/28011) which shows as milestone the 10.0.3 version.
This bug was my main reason for updating as it renders the calendar unusable for us since we also use the contacts application.

Is there any workaround, maybe by changing calendar numbers in the database? Or does anyone now when this really is fixed?

**Comment by DeepDiver1975** [comment] 2017-11-23 10:50
@Julian1998 please try to reproduce this and get back to me if you have questions.
I'm assigning you to this issue for now - THX

**Comment by ownclouders** [comment] 2018-01-01 01:10
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).

**Comment by felixboehm** [comment] 2018-01-02 10:26
@Julian1998 reopened

**Comment by ownclouders** [comment] 2018-02-20 01:10
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Closed** 2018-06-25 11:59 UTC
Labels: bug, comp:caldav, p3-medium
