### ISSUE TITLE
Ctrl-Enter to submit comment

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#24638] opened 2016-05-14 14:23 UTC
In the comment tab of the sidebar, commenting is only possible by clicking the button. Ctrl-Enter as a common shortcut should also work.

In the future we might even want to think about using enter to submit, and Ctrl-Enter for inserting line breaks to make it even easier to comment. Comments are meant to be pretty short and not long texts.

cc @owncloud/javascript @schiesbn

**Comment by MorrisJobke** [comment] 2016-05-15 06:13
Duplicate of https://github.com/owncloud/core/issues/24302 and fixed by https://github.com/owncloud/core/issues/24396

**Comment by MorrisJobke** [comment] 2016-05-15 06:13
Even works with Cmd + Enter on OS X ;)

**Closed by MorrisJobke** 2016-05-15 06:13 UTC
Labels: 1 - To develop, design, enhancement, feature:comments, junior job
