### ISSUE TITLE
Maintenance Mode after Upgrading to 9.1.4

### ISSUE THREAD

**Issue by admincrps** [owncloud/core#27256] opened 2017-02-26 11:57 UTC
yesterday we have done the upgrade to 9.1.4 and the upgrade was done without errors.
But when we want to access OCC via Web, the directories will be shown, but when opening a file there is always a 503 error.
When opening a file via IOS client, system tells "no server access due to maintenance".

No inconsistancy or other erros.
Maintenance mode in config is already set to "false".
 
### Steps to reproduce
1. opening a file via webclient (503)
2. opening a file via IOS app (maintenance mode)
3.

### Expected behaviour
Opening the files

### Actual behaviour
error messages (see above)

### Server configuration
Ubuntu 14.04.4 LTS‬ 

**Web server:**
Apache 2

**Database:**
5.5.53-0ubuntu0.14.04.1

**PHP version:**
5.5.9+dfsg-1ubuntu4.17

**ownCloud version:** (see ownCloud admin page)
9.1.4

**Updated from an older ownCloud or fresh install:**
running owncloud 9.0

**Where did you install ownCloud from:**
owncloud.org/install/

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocbregaqrdop',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => '...g',
  ),
  'datadirectory' => '/var/www/vhosts/.../data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => '...',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '..',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '...',
  'integrity.check.disabled' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '...',
  'mail_smtpname' => '...',
  'mail_smtppassword' => '...',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'memcache.local' => '\OC\Memcache\APCu',
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment] 2017-02-27 11:17
Did you try `occ maintenance:mode --off` ?

**Comment by admincrps** [comment] 2017-02-27 14:35
Yes we also have tried this.


CRPS NRW Köln e.V
CRPS Netzwerk - Gemeinsam stark.
Morbus Sudeck Selbsthilfegruppe 
Landesgruppe Nordrhein-Westfalen | Ortsgruppe Köln
‪Neusser Straße 112a, 50670 Köln‬
Telefon: ‪+49 (0)221 355 33‬ 83-972, Fax: ‪+49 (0)221-355 33‬ 83-979, Email: dirk-stefan.droste@crps-netzwerk.org
www.crps-nrw.de - www.crps-koeln.de - www.crps-netzwerk.de

++++Unser Newsletter auf NEWSLETTER.crps-nrw.de++++Unsere Gruppentreffen auf TERMINE.crps-nrw.de++++Unser Flyer auf FLYER.crps-nrw.de+++

Rechtlicher Hinweis:
Diese E-Mail ist ausschließlich für den/die o.g. Empfaenger/in bestimmt und kann vertrauliche Informationen enthalten. Sollten Sie diese Nachricht irrtuemlich erhalten haben bitten wir darum, den Absender umgehend zu informieren und die E-Mail von Ihrem System zu loeschen. Personen oder Organisationen, fuer die diese Information nicht bestimmt ist, ist es nicht gestattet, diese erneut zu uebertragen, zu verbreiten oder diese anderweitig zu verwenden.

Legal notice:
This E-Mail is intended for the above mentioned recipient only and may contain privileged or confidential information. If you received this E-Mail in error, please contact the sender and delete this E-Mail from your system. Any review, retransmission, dissemination or other use is prohibited.

**Comment by PVince81** [comment] 2017-02-27 14:45
And what happens when you do ? Does it stay in maintenance mode ?
Any log entries ? (web server log, owncloud.log)

**Comment by admincrps** [comment] 2017-02-27 15:12
Yes it has no result, via web we get 503 errors and iOS apps day "maintenance mode".

We cannot reproduce the logs because we have restored our backup yesterday to 9.0 because we cannot miss the cloud.

CRPS NRW Köln e.V
CRPS Netzwerk - Gemeinsam stark.
Morbus Sudeck Selbsthilfegruppe 
Landesgruppe Nordrhein-Westfalen | Ortsgruppe Köln
‪Neusser Straße 112a, 50670 Köln‬
Telefon: ‪+49 (0)221 355 33‬ 83-972, Fax: ‪+49 (0)221-355 33‬ 83-979, Email: dirk-stefan.droste@crps-netzwerk.org
www.crps-nrw.de - www.crps-koeln.de - www.crps-netzwerk.de

++++Unser Newsletter auf NEWSLETTER.crps-nrw.de++++Unsere Gruppentreffen auf TERMINE.crps-nrw.de++++Unser Flyer auf FLYER.crps-nrw.de+++

Rechtlicher Hinweis:
Diese E-Mail ist ausschließlich für den/die o.g. Empfaenger/in bestimmt und kann vertrauliche Informationen enthalten. Sollten Sie diese Nachricht irrtuemlich erhalten haben bitten wir darum, den Absender umgehend zu informieren und die E-Mail von Ihrem System zu loeschen. Personen oder Organisationen, fuer die diese Information nicht bestimmt ist, ist es nicht gestattet, diese erneut zu uebertragen, zu verbreiten oder diese anderweitig zu verwenden.

Legal notice:
This E-Mail is intended for the above mentioned recipient only and may contain privileged or confidential information. If you received this E-Mail in error, please contact the sender and delete this E-Mail from your system. Any review, retransmission, dissemination or other use is prohibited.

**Comment by PVince81** [comment] 2017-02-27 15:14
Without log entries it will be impossible to debug / reproduce / fix since we cannot know the reason why maintenance mode was stuck.

**Comment by admincrps** [comment] 2017-02-27 15:31
We will install a new version on another subdomain to try the new version.
But we just have seen that the website just shows the enterprise version. Can it be that we have upgraded our community version with the enterprise version and thats the problem?
Where can we download the latest  community version?

**Comment by admincrps** [comment] 2017-02-27 15:34
have found it on own cloud.org


CRPS NRW Köln e.V.
CRPS Netzwerk - Gemeinsam stark.
Morbus Sudeck Selbsthilfegruppe 
Landesgruppe Nordrhein-Westfalen | Ortsgruppe Köln
Neusser Strasse 112a, 50670 Köln 
Telefon: +49 (0)221 355 33 83 - 970, Sammelruf: +49 (0)221 355 83 - 972, Fax: +49 (0)221-355 33 83 - 979, Email: dirk-stefan.droste@crps-netzwerk.org
www.crps-koeln.de - www.crps-nrw.de - www.crps-netzwerk.org

++++Unser Newsletter auf NEWSLETTER.crps-nrw.de++++Unsere Gruppentreffen auf TERMINE.crps-nrw.de++++Unser Flyer auf FLYER.crps-nrw.de+++

Rechtlicher Hinweis:
Diese E-Mail ist ausschließlich für den/die o.g. Empfaenger/in bestimmt und kann vertrauliche Informationen enthalten. Sollten Sie diese Nachricht irrtuemlich erhalten haben bitten wir darum, den Absender umgehend zu informieren und die E-Mail von Ihrem System zu loeschen. Personen oder Organisationen, fuer die diese Information nicht bestimmt ist, ist es nicht gestattet, diese erneut zu uebertragen, zu verbreiten oder diese anderweitig zu verwenden.

Legal notice:
This E-Mail is intended for the above mentioned recipient only and may contain privileged or confidential information. If you received this E-Mail in error, please contact the sender and delete this E-Mail from your system. Any review, retransmission, dissemination or other use is prohibited.

**Comment by PVince81** [comment] 2017-08-07 20:41
closing due to lack of further feedback

**Closed by PVince81** 2017-08-07 20:41 UTC
