### ISSUE TITLE
Update from 8.1beta to 8.1rc1 streaming of files failed

### ISSUE THREAD

**Issue by libasys** [owncloud/core#17242] opened 2015-06-29 15:43 UTC
Testenviroment:
Apache/2.2.29 (Unix) + mysql5.6 server + php5.4.4

I have written a little streaming class for an mp3 app, with the beta version of OC8.1 all was well,
with latest update to 8.1rc1, the streaming never works! On Firefox it plays the song for round about 10 seconds, than abort. With Safari it plays the song but you see no  time of the song!

On the admin page no error!
On the apache log no error!

Link to the streaming class: https://github.com/libasys/ownCloud-8.1-MP3Player-App/blob/master/audios/lib/audiostream.php

thanks in advance!

**Comment by PVince81** [comment] 2015-06-29 16:09
@libasys have you been able to bisect and find the exact commit after which it stopped working ?
This would be very helpful.
Thanks.

**Comment by libasys** [comment] 2015-06-29 16:41
https://github.com/libasys/ownCloud-8.1-MP3Player-App Here is the updated mp3 app, some small fixes needed, to get the scanner working with 8.1rc1! install is normal upload the "audios" folder to your app dir and activate it on the apps+!

**Comment by DeepDiver1975** [comment] 2015-06-30 08:38
@libasys is there a unit test available for this audio stream? Testing/bisect/analysis would be much easier. Can you add such a unit test? THX a lot!

**Comment by DeepDiver1975** [comment] 2015-06-30 08:39
While having a look at the code I realized that this basically adds http range requests. Sabredav already supports range requests - as a result streaming should work out of the box when you connect the mp3 player via webdav.

**Comment by nickvergessen** [comment] 2015-06-30 08:49
IIRC you said it worked with 8.1.0beta1 yesterday? For me it doesn't work there either. it always stops between 10 and 20 seconds, depending on the file.

**Comment by PVince81** [comment] 2015-06-30 08:51
Could it be the Firefox version ? (Firefox update vs ownCloud update)

**Comment by libasys** [comment] 2015-06-30 09:09
@PVince81 no that is not a problem of firefox version!
https://ssl.webpack.de/demo81.libasyscloud.de <-- OC8.1beta1 and here the mp3 player works like expected! @DeepDiver1975 webdav how can i connect the mp3 with webdav?

**Comment by PVince81** [comment] 2015-06-30 09:10
@libasys for webdav, just open the file from http://example.com/owncloud/remote.php/webdav/path/to/file.mp3 instead of your php file.

Maybe on that server the environment/config is different ? Is there a timeout for the connection ?

**Comment by libasys** [comment] 2015-06-30 09:14
@PVince81 local installed and on webserver at libasyscloud.de i haven't problems with the mp3 player app with the beta of oc8.1! timeout for scripting or other connection abort?

**Comment by PVince81** [comment] 2015-06-30 09:17
Also it is very likely to be due to your environment difference. You said there was no error message, so it's likely that Apache directly killed the PHP process after a timeout.

I don't see any reason why it would break in the middle of a stream. If there was an exception, then that exception should appear in the log (assuming you also set loglevel to 0 in config.php).

So you are saying in your exact same local environment (same web server) OC 8.1 RC1 has connection aborts ?

@nickvergessen said he sees the 10-20 second abort on beta1 locally.

Can you both post your timeout values of Apache ?

**Comment by PVince81** [comment] 2015-06-30 09:19
> timeout for scripting or other connection abort

timeout for scripting

**Comment by libasys** [comment] 2015-06-30 09:25
Local, i have a test installation with OC8.1beta1 and OC8.1rc1 on the same webserver! beta mp3 player works, rc1 song abort after 10 - 20 seconds!
```
Max Requests Per Child: 10000 - Keep Alive: on - Max Per Connection: 100
Timeouts 	Connection: 300 - Keep-Alive: 5 
max_execution_time: 30
```

**Comment by PVince81** [comment] 2015-06-30 09:28
Hmm, but it still doesn't explain why @nickvergessen has it aborting after 10 seconds on beta1.

When it works, how long can the mp3 play ? Does it work for a 4-5 minutes track ?
Just want to make sure the delay isn't happening later.

**Comment by PVince81** [comment] 2015-06-30 09:30
and you are testing in both with the exact same song ?
Is encryption enabled or disabled ?

**Comment by libasys** [comment] 2015-06-30 09:31
PVince81, you know i am always look for a error on my side, but this stream abort comes from the core!
encryption disabled! and a working demo is online on demo81 with beta!

**Comment by libasys** [comment] 2015-06-30 09:33
yes tested with same songs

**Comment by PVince81** [comment] 2015-06-30 09:37
Having trouble with your app. There is no upload button in the app.
I uploaded a mp3 in the files app but it doesn't appear in app.
UX problem or bug ?

Please provide the exact steps to reproduce (where to click, etc)
Thanks.

**Comment by PVince81** [comment] 2015-06-30 09:38
Ok got it. Seems I needed to click on the arrows button.

**Comment by libasys** [comment] 2015-06-30 09:40
accesslog on streaming a file: 
```
127.0.0.1 - - [30/Jun/2015:11:39:06 +0200] "GET /81rc11/index.php/apps/audios/getaudiostream/music/02%20-%20Boogie%20Belgique%20-%20Hello%20Sinner.mp3 HTTP/1.1" 206 473088
```

**Comment by PVince81** [comment] 2015-06-30 09:40
Hmm and now I click play and nothing happens, no error!
Both in Firefox 38.0.6 and Chromium 43.0

**Comment by PVince81** [comment] 2015-06-30 09:41
server is 8.1.0beta1

**Comment by libasys** [comment] 2015-06-30 09:43
Version
ownCloud 8.1 beta 1 (testing)

Entwickelt von der ownCloud-Community, der Quellcode ist unter den Bedingungen der AGPL lizenziert.

**Comment by PVince81** [comment] 2015-06-30 09:48
and now getting this:
```
{"reqId":"RP8cKIXpe3cYqXMfHoIH","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_audios_albums` (`user_id`,`name`,`year`,`genre_id`) VALUES(?,?,?,?)' with params [\\\"root\\\", \\\"Various\\\", \\\"\\\", 0]:\\n\\nSQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'year' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(172): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps3\\\/audios\\\/controller\\\/scannercontroller.php(328): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps3\\\/audios\\\/controller\\\/scannercontroller.php(219): OCA\\\\Audios\\\\Controller\\\\ScannerController->writeAlbumToDB('Various', '', 0)\\n#5 [internal function]: OCA\\\\Audios\\\\Controller\\\\ScannerController->scanForAudios()\\n#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Audios\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(107): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Audios\\\\Controller\\\\ScannerController), 'scanForAudios')\\n#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ScannerControll...', 'scanForAudios', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/audios\\\/sc...')\\n#13 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":4,"time":"2015-06-30T09:47:24+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/audios\/scanforaudiofiles"}
```

scanning aborts.

Will retry from scratch with different audio files.

**Comment by PVince81** [comment] 2015-06-30 10:16
So, finally have something playing. It seems the "play" button in the top bar is broken.
One needs to click on a track directly to get another "play" button.

Tested 1 minute runs for as 3 minute song:
- beta1: no abort
- rc1: abort after around 10-20 seconds

Also I discovered that this app isn't about streaming, but reading chunks. So it first reads the first chunk, plays it, and later loads the next chunk, etc. The abort seems to be whenever it tries to load the next chunk.

So it's not about a connection abort but maybe range request.
(just speculating)

I'll bisect this now.

**Comment by libasys** [comment] 2015-06-30 10:17
thanks for your help

**Comment by PVince81** [comment] 2015-06-30 10:31
Bisect fail. When I reached RC1 the player still worked properly.
When bisecting, I did not re-setup OC from scratch between steps.

So far I had the feeling the bug can only be triggered after resetting OC from scratch and playing a track directly after scanning.

Could be some kind of race condition...

I'll redo the bisect but this time I will re-set OC from scratch between steps and also clear the browser cache.

**Comment by PVince81** [comment] 2015-06-30 11:13
Nice...
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
35c377f7a9a0413bea5fa6768467c6e5f7c2d83e
1270c6800dd439e411278764e3a2ddb2f68040ac
8d53dc803f978f0b2e5db1c3503dc5fb0d55b0c5
0775e9c1ca95a3f93b1069610fd89a0801f9f897
2d63fd77de1cbfdb0a3474cadf99f1dcf4962d5f
5edf294ce597c59c204c37e9fb753807ab40082f
e08423f95631a1b06f2de0216c5765552092075c
b98dd3ceb84f1372415fd69bc7992d0bba954f3f
d519aba878cca25acbe0aecc39efa9cb76bda4bb
a1a25a9b5bddab05b6e8250557e8b7b6e17da1ff
f0b86727299728bb7243e99584a21038c54123cd
006eaa84aa25b6301fc75cdf2fbf2594e21b4271
7e418c7d699718b6d934de6184f6c96fdf9437d6
6df502a5aa29b137d17bb7c17cb2552719386203
We cannot bisect more!
```

plenty to look at.

In some of the commits I couldn't upload, so could not test.
I'll try again with having the music file always present in data to avoid the upload bugs.

**Comment by PVince81** [comment] 2015-06-30 11:17
@libasys has confirmed that the problem also exists on master

**Comment by libasys** [comment] 2015-06-30 11:20
Version: ownCloud 8.1 RC1 (git)

**Comment by PVince81** [comment] 2015-06-30 11:21
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
a1a25a9b5bddab05b6e8250557e8b7b6e17da1ff
7e418c7d699718b6d934de6184f6c96fdf9437d6
d519aba878cca25acbe0aecc39efa9cb76bda4bb
5edf294ce597c59c204c37e9fb753807ab40082f
We cannot bisect more!
```

Trying to get closer...

**Comment by PVince81** [comment] 2015-06-30 11:22
Probably one of 7e418c7d699718b6d934de6184f6c96fdf9437d6 or a1a25a9b5bddab05b6e8250557e8b7b6e17da1ff

The others seem unrelated.

**Comment by PVince81** [comment] 2015-06-30 11:33
It still worked at e64360e72db8514b305c628a38cd30809fb2913d.

So now to find out what exactly in https://github.com/owncloud/core/commit/7e418c7d699718b6d934de6184f6c96fdf9437d6 would break

**Comment by libasys** [comment] 2015-06-30 11:34
perhaps
```
use Icewind\Streams\CallbackWrapper;
```

**Comment by PVince81** [comment] 2015-06-30 11:34
CC @icewind1991 for clues

**Comment by PVince81** [comment] 2015-06-30 11:35
another possibility is now to revert each hunk of that commit on master until it works again. (I'll try that later)

**Comment by PVince81** [comment] 2015-06-30 11:36
Ah, yes, could be this: https://github.com/owncloud/core/commit/7e418c7d699718b6d934de6184f6c96fdf9437d6#diff-d9747e68e80ce288dcea911cb8607546R987

The callback wrapper would automatically fclose() the file at the end of the PHP process.

But in case of streaming (if that's streaming) it might never close it ?

**Comment by PVince81** [comment] 2015-06-30 11:36
@icewind1991 I'd suggest to skip the callbackwrapper logic when locking is not enabled, at least to prevent regressions on master. (but needs to be fixed later when locking is enabled)

**Comment by PVince81** [comment] 2015-06-30 11:38
Yep. Comment out the block https://github.com/owncloud/core/commit/7e418c7d699718b6d934de6184f6c96fdf9437d6#diff-d9747e68e80ce288dcea911cb8607546R987 and the issue is fixed.

Could it be a buffering issue ? Maybe PHP doesn't flush the data when that callback is pending or something ? (just wild guessing)

**Comment by PVince81** [comment] 2015-06-30 11:39
I'll prepare a short-term fix to skip this block when locking is disabled.

**Comment by libasys** [comment] 2015-06-30 11:39
sounds good

**Comment by PVince81** [comment] 2015-06-30 11:47
short term fix here https://github.com/owncloud/core/pull/17256

**Comment by libasys** [comment] 2015-06-30 11:54
ok with this fix now it works in all tested browser (FF,Safari,Chrome)

**Comment by icewind1991** [comment] 2015-06-30 12:53
I cant reproduce the issue with latest master.

Playback works fine with both ff and chrome

**Comment by PVince81** [comment] 2015-06-30 12:55
I wonder if it's related somehow to the PHP config, buffer sizes or whatever.

I still think we should apply the short-term fix https://github.com/owncloud/core/pull/17256 until we have enough time to investigate the details of it.

**Comment by libasys** [comment] 2015-06-30 13:44
@icewind1991  perhaps you have to watch the operation fseek, also!

**Comment by libasys** [comment] 2015-06-30 14:16
ok my workaround for this, is not to work with view->fopen
(example)
```
$this->userView->fopen($this -> path, 'rb')
```
i now work with view->getLocalFile() and use function fopen  so i am not running in this issue that the file get closed!

**Comment by icewind1991** [comment] 2015-06-30 14:22
> i now work with view->getLocalFile() and use function fopen so i am not running in this issue that the file get closed!

And you're defeating the purpose of streaming files when using remote storages or encryption

I managed to reproduce the issue, will look into a permanent sollution

**Comment by PVince81** [comment] 2015-06-30 16:30
https://github.com/owncloud/core/pull/17256 was merged.

Raised https://github.com/owncloud/core/issues/17262 to look into a better solution that is compatible with locking.

**Closed by PVince81** 2015-06-30 16:30 UTC
Labels: bug, regression, sev2-high
