### ISSUE TITLE
Sabre 	Array to string conversion 

### ISSUE THREAD

**Issue by JaBecker** [owncloud/core#21460] opened 2016-01-05 11:02 UTC
Hello,

I have a lot of these messages in my owncloud log file:

	Array to string conversion at /usr/share/webapps/owncloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php#62

Also, neither Calendar or Tasks sync work via CalDAV.

Im on ownCloud 8.2.2 (stable) with php7. Maybe its an issue between SabreDAV and PHP7?

**Comment by JaBecker** [comment] 2016-01-05 11:09
Bug seems similar to https://github.com/owncloud/calendar/issues/1002.

**Comment by RealRancor** [comment] 2016-01-05 11:13
@JaBecker Yes, its a duplicate of https://github.com/owncloud/calendar/issues/1002 where you can see that this seems to be caused by a component of SabreDAV not compatible with PHP7.

**Closed** 2016-01-05 22:09 UTC
