### ISSUE TITLE
Update to OC 8 in web interface failed on Debian 7

### ISSUE THREAD

**Issue by fachexot** [owncloud/core#14234] opened 2015-02-15 15:22 UTC
Updated Owncloud on Debian with apt repository.
Content of /etc/apt/sources.list.d/owncloud.list: `deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /`

When I now go to my owncloud web interface and press "Start Update" the following error occurs:
```
Updating ownCloud to version 8.0, this may take a while.

Turned on maintenance mode
Checked database schema update

An exception occurred while executing 'INSERT INTO oc_share_external (id, "remote", "share_token", "password", "name", "owner", "user", "mountpoint", "mountpoint_hash") SELECT id, remote, share_token, password, name, owner, user, mountpoint, mountpoint_hash FROM __temp__oc_share_external': SQLSTATE[23000]: Integrity constraint violation: 19 oc_share_external.remote_id may not be NULL
```

**Comment by RealRancor** [comment] 2015-02-15 17:34
Probably related / duplicate of https://github.com/owncloud/core/issues/14222, https://github.com/owncloud/core/issues/13970

**Comment by karlitschek** [comment] 2015-02-15 18:32
@schiesbn any idea?

**Comment by schiesbn** [comment] 2015-02-16 12:18
Do you have anything else in your apache or owncloud log?

I don't know any upgrade script which should perform a instert operation on the oc_share_external table. The only update script we have updates existing entries and set "accepted" to 1, see https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/migration.php#L35

**Comment by fachexot** [comment] 2015-02-16 12:29
I worked around the error by following the comment in [#13970](https://github.com/owncloud/core/issues/13970). It could delete the row and the update worked fine. But I was not able to reinsert the row because the `select` did not match the table scheme (9 instead of 11 columns) and I did not find out how they were mapped.

I am going to look over my apache/OC logs this evening.

**Comment by berni123** [comment] 2015-02-19 11:49
@fachexot In my workaroud I just discarded the data and did not restore it via an insert statement - if you need the external link probably you will have to do it via the gui

**Comment by VicDeo** [comment] 2015-02-19 16:11
it's all the same #12751,  #13970, #14222

**Comment by PVince81** [comment] 2015-08-03 13:05
There were fixed here https://github.com/owncloud/core/issues/13970#issuecomment-76161095
Please try again with 8.0.5 or newer.

**Closed by PVince81** 2015-08-03 13:05 UTC
Labels: bug, update
