### ISSUE TITLE
Update 6.0.2 to 6.0.3 deletes hidden files and doesn't back it up

### ISSUE THREAD

**Issue by AlexanderWatzinger** [owncloud/core#8402] opened 2014-04-29 13:36 UTC
An update from 6.0.2 to 6.0.3 removed a hidden directory (.git) in the root and it wasn't in the backup either.

I'm working and testing on a local machine (Mac 10.8.5) before putting owncloud on a production server and so lost my versioning (.git) directory at the last update.

It's wasn't much of a problem (using a web repository from where I could fetch it again) but it was kind of unexpected and maybe raises more critical issues for other users.

**Comment by PVince81** [comment] 2015-03-23 18:55
@VicDeo can you confirm ?

**Comment by VicDeo** [comment] 2015-03-23 20:24
Duplicate of https://github.com/owncloud/updater/issues/48
Fixed since OC 7.0.5

**Comment by PVince81** [comment] 2015-03-23 20:24
Thanks, closing then.

**Closed by PVince81** 2015-03-23 20:24 UTC
Labels: bug, update
