### ISSUE TITLE
Cron Error When Using System Cron and PHP CLI

### ISSUE THREAD

**Issue by mintonline** [owncloud/core#17257] opened 2015-06-30 13:07 UTC
### Server configuration
**Operating system**: Red Hat
**Web server:** Apache 2
**Database:** MySQL
**PHP version:** 5.4
**ownCloud version:** (see ownCloud admin page) 8.0.4
**Updated from an older ownCloud or fresh install:** Fresh install
**List of activated apps:** Activity, Deleted Files, File Locking, Firs Run Wizard, Mail Template Editor, PDF Viewer, Pictures, Provisioning API, Server-side Encryption, Share Files, Text Editor, Updater & Video Viewer

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => '********',
  'passwordsalt' => '********',
  'secret' => '********',
  'trusted_domains' => 
  array (
    0 => 'www.********',
  ),
  'datadirectory' => '/home/sites/********/owncloud-data',
  'overwrite.cli.url' => 'https://www.********/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => '********',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '********',
  'dbpassword' => '********',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => '********',
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** PHP CLI

**Operating system:** Red Hat

#### Web server error log
******** [Tue Jun 30 12:58:58 2015] [error] [client 79.170.44.5:48601] AH01215: PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /home/sites/********/public_html/owncloud/cron.php on line 51
******** [Tue Jun 30 12:58:58 2015] [error] [client 79.170.44.5:48601] AH01215: PHP Warning:  Unexpected character in input:  '\\' (ASCII=92) state=1 in /home/sites/********/public_html/owncloud/cron.php on line 51
******** [Tue Jun 30 12:58:58 2015] [error] [client 79.170.44.5:48601] AH01215: PHP Parse error:  syntax error, unexpected T_STRING in /home/sites/********/public_html/owncloud/cron.php on line 51

**Comment by LukasReschke** [comment] 2015-06-30 13:08
Please post your `/home/sites/********/public_html/owncloud/cron.php`.

**Comment by RealRancor** [comment] 2015-06-30 13:23
Very likely the cron is executed with PHP 5.2:

https://github.com/owncloud/core/issues/5198

**Comment by nickvergessen** [comment] 2015-06-30 13:51
Please run `php --version` from your console

**Comment by mintonline** [comment] 2015-06-30 14:55
Thanks all I thought I'd checked teh 5.2 issue, but clearly not, it was using PHP5.2, I've switched to PHP5.4 and now I get a 302 Temporarily Moved status instead. Nothing in the server error log or the OwnCloud log though, any advice?

**Comment by RealRancor** [comment] 2015-06-30 18:03
Very likely related to or even a duplicate of: https://github.com/owncloud/core/issues/7715

**Closed** 2015-07-01 06:04 UTC
Labels: needs info
