### ISSUE TITLE
ownCloud 8.2.2 sync with ownCloud Client 2.1.0 for Windows causes sometimes an Integrity constraint violation exception

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#21725] opened 2016-01-14 15:20 UTC
When changed files were uploaded with the ownCloud sync client 2.1.0 for windows to an ownCloud server 8.2.2, sometimes the following exception occurs:

```
Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/87a7430264a1a25082762e2813ec896c\", 1, 1452780555, \"files\\\/87a7430264a1a25082762e2813ec896c\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/87a7430264a1a25082762e2813ec896c' for key 'lock_key_index'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/db\/connection.php(242): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/lock\/dblockingprovider.php(111): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/lock\/dblockingprovider.php(156): OC\\Lock\\DBLockingProvider->initLockField('files\/87a743026...', 1)\n#7 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/files\/storage\/common.php(635): OC\\Lock\\DBLockingProvider->acquireLock('files\/87a743026...', 1)\n#8 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Common->acquireLock('files\/Hochschul...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(572): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Hochschul...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/files\/view.php(1803): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Hochschul...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/files\/view.php(1902): OC\\Files\\View->lockPath('\/Hochschule', 1)\n#12 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/node.php(260): OC\\Files\\View->lockFile('\/Hochschule\/Mas...', 1)\n#13 \/share\/MD0_DATA\/htdocs\/owncloud\/lib\/private\/connector\/sabre\/lockplugin.php(77): OC\\Connector\\Sabre\\Node->acquireLock(1)\n#14 [internal function]: OC\\Connector\\Sabre\\LockPlugin->getLock(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#16 \/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#17 \/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \/share\/MD0_DATA\/htdocs\/owncloud\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#19 \/share\/MD0_DATA\/htdocs\/owncloud\/remote.php(137): require_once('\/share\/MD0_DATA...')\n#20 {main}","File":"\/share\/MD0_DATA\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66}
```

This problem did not occur with earlier ownCloud server versions with client 2.1.0. Therefore, it could be a server issue.  

Steps to reproduce:
1. Change text-files in your ownCloud directory
2. Wait for the ownCloud windows client to upload the changed files

Expected behaviour:
No errors

Actual behaviour:
Sometimes, the mentioned error occurs. I do not know exactly which situation causes this error. If I retry the sync, everything works fine. 

Enabled apps:
Calendar 0.8.1
Contacts 0.5.0.0

Used database:
MariaDB 5.5.44

PHP-Version: 5.6.10
OS: Embedded QNAP-Linux

**Comment by nickvergessen** [comment] 2016-01-14 15:37
Another MariaDB with insertIfNotExists issue :(

Duplicate of #20555

See https://github.com/owncloud/core/issues/20555#issuecomment-157331571

**Closed by nickvergessen** 2016-01-14 15:37 UTC
