### ISSUE TITLE
A log appears in owncloud.log file sharing a folder via link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25455] opened 2016-07-12 08:20 UTC
### Steps to reproduce
1. Create a folder
2. Share it via link
3. Make it editable
4. Access the link

### Expected behaviour

No logs should be written in owncloud.log file
### Actual behaviour

A log appears in owncloud.log file
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
{"9.1.0.11","versionstring":"9.1.0 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"VlK0aQ9d3+O0F\/0xspAY","remoteAddr":"82.159.139.58","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-07-12T08:04:15+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
```
### Client configuration

**browser**

Firefox

**Comment by enoch85** [comment] 2016-07-25 12:27
I can confirm this on 9.1 stable using Ubuntu 16.04 and PHP 7 + MySQL 5.7.

**Comment by MaxuNs** [comment] 2016-08-25 09:29
I have the same problem on OC 9.1.0 (stable) + Ubuntu 14.04.1 + PHP 5 + MySQL 5.5.50 on Federated two Servers:

Warning	filesystem	Storage wrapper 'readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

Warning	filesystem	Storage wrapper 'readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

Warning	filesystem	Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.

**Comment by MaxuNs** [comment] 2016-08-25 09:44
On Remote Server (on Federated) appears:

Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 Storage not available","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(903): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('Folder_Shared')\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(334): Sabre\\DAV\\Server->getPropertiesForPath('Folder_Shared', Array, 1)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":159,"User":"--"}

**Comment by mj-mel** [comment] 2016-08-25 14:37
I too am experiencing this problem using the same versions as reported originally in the call. Any progress?
Thanks

**Comment by tflidd** [comment] 2016-08-29 10:39
9.1.1RC1 has this issue as well (not sure when it appeared for the first time).

**Comment by kurdt94** [comment] 2016-09-06 11:03
Experience the same error in log @ fresh 9.1.0 (stable) install.

**Comment by enoch85** [comment] 2016-09-27 11:22
9.1.1 as well

```
Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
```

**Comment by stanelie** [comment] 2016-10-04 18:58
Having this issue on 9.1.0.16

**Comment by Jenlues** [comment] 2016-10-24 14:39
9.1.1 (stable) on Debian as well

**Comment by enoch85** [comment] 2016-10-24 14:49
@PVince81 Why backlog?

**Comment by PVince81** [comment] 2016-10-24 14:52
Because low severity and also: there are lots of tickets with high severity that needs attention.

But as it goes for any other tickets, anyone is free to take on this task any time.

**Comment by enoch85** [comment] 2016-10-24 14:54
Makes sense.

**Comment by astranges** [comment] 2016-10-27 07:48
same with centos 7.2 - php 7 - maraidb 10.1 - owncloud 9.1.1(stable)

**Comment by enoch85** [comment] 2016-10-29 16:29
It's fixed in Nextcloud.... https://github.com/nextcloud/server/pull/1722

**Comment by PVince81** [comment] 2016-11-02 09:13
Well... that's the kind of hack I thought we should rather avoid but fix the core problem instead.

**Comment by PVince81** [comment] 2016-11-02 09:27
Alternative PR that groups the hacks in one place, since it seems we can't avoid hacks at this point: https://github.com/owncloud/core/pull/26520

**Closed** 2016-11-07 10:13 UTC
Labels: comp:filesystem, feature:sharing, sev4-low
