### ISSUE TITLE
Favorite page is very slow loading

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14859] opened 2015-03-13 09:41 UTC
On one of my production ownCloud instances the favorite page is very slow loading and requires nearly ten seconds. Though the user has not a single favorite.

This is 8.0.2 updated from 7.0.4 on a Debian 7 with PHP 5.4 and MySQL.

BlackFire Trace: https://blackfire.io/profiles/eb73d901-1946-4e71-9523-7f35d025fdd5/graph

The user itself does not have a single file except two shared folders shared with a group that he is member of, the data is also not that massive as it are only 16'513 entries in the filecache and the overall filesize is 10GB.

@PVince81 Let me know if you need more informations.

**Comment by LukasReschke** [comment] 2015-03-13 09:42
Pretty sure it is related to the 20415 (!) SQL queries that Blackfire shows :see_no_evil:

**Comment by PVince81** [comment] 2015-03-13 09:44
How many subdirs ? The problem is that to show the favorites it needs to run a search on all storages.
While the search on the Local storage should be fast (direct SQL query), the search on a shared storage currently needs to iterate/recurse in all subfolders to search for favorite/tagged files...

I haven't looked at the report yet, I hope we can still optimize it a bit.

**Comment by LukasReschke** [comment] 2015-03-13 09:50
```
mysql> select count(*) from oc_filecache where path LIKE "files/Verein%" AND mimetype=2;
+----------+
| count(*) |
+----------+
|      673 |
+----------+
1 row in set (0.01 sec)
```

```
mysql> select count(*) from oc_filecache where path LIKE "files/Projekte%" AND mimetype=2;
+----------+
| count(*) |
+----------+
|      369 |
+----------+
1 row in set (0.01 sec)
```

**Comment by PVince81** [comment] 2015-03-13 09:58
One thing we cannot get away at the moment is iterating over all folders to find the favorites, not until @icewind1991's shared storage refactor is done.
See https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/cache.php#L381

What we could try and optimize is avoiding to re-resolve the source cache for every entry in the loop, either by moving the logic from getSourceCache() https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/cache.php#L51 outside the loop or by storing its result in an attribute.

I suppose this logic here https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/cache.php#L154 could also be simplified, avoiding the re-resolve stuff several times.

**Comment by PVince81** [comment] 2015-03-13 10:01
unless https://github.com/owncloud/core/pull/12086 can be merged soon, but I doubt it. And I'm not sure how many changes would be needed here to make it work (considering that it will take time to make the changes, test, etc)

**Closed** 2015-03-24 12:27 UTC
Labels: 5 - To review, 8.1 Bugfixing Shortlist, app:files, bug, feature:tags, performance
