### ISSUE TITLE
Users can't delete on publicly shared link

### ISSUE THREAD

**Issue by YogaKick** [owncloud/core#20646] opened 2015-11-20 15:03 UTC
Hi,

I share a folder for a couple of customers. When i need config files or backups they upload those files to my Owncloud server using a publicly shared link.

Users can upload files and modify them, but deleting files using the trashbin icon doesn't do anything. They can see the icon though. This means that if the customer uploads a file he didn't meant to be uploaded, i manually need to log in and remove it.

Is this usual behavior from Owncloud? Users who have a link to my publicly shared folder, that can't delete files inside that folder?

Many thanks!

**Comment by MorrisJobke** [comment] 2015-11-20 15:13
Duplicate of https://github.com/owncloud/core/issues/6635

**Closed by MorrisJobke** 2015-11-20 15:13 UTC
