### ISSUE TITLE
"Not enough storage available" / Upload limit of 0 byte on Strato

### ISSUE THREAD

**Issue by ghost** [owncloud/core#18886] opened 2015-09-08 06:53 UTC
Don't use the issue template as i don't have this issue myself but want to note this anyway.

There are some reports of Strato Users at the forums that they are getting an "Not enough storage available" / Upload limit of 0 byte on their Strato webhosting:

https://forum.owncloud.org/viewtopic.php?f=32&t=28057
https://forum.owncloud.org/viewtopic.php?f=31&t=30246

A common fix for this is to replace:

```
$space = @disk_free_space($this->getSourcePath($path));
```

from https://github.com/owncloud/core/blob/v8.1.1/lib/private/files/storage/local.php#L265 with:

```
$space = @disk_free_space('/');
```

Maybe some one with a better knowledge of the oC internals could have a look at this to see why this happens and if its possible to fix this in oC.

**Comment by PVince81** [comment] 2015-09-16 16:03
Maybe disk_free_space fails / if forbidden on the specific folder it's called on for this specific hoster.
Or the partition in which the data folder is in is not the same as "/".

The storage wrappers should make it possible for third parties to write apps that override the "disk_free_space" behavior for specific hosters. This could be an idea, so those users could be told to install the "strato" specific disk free fix app. (just an idea)

@icewind1991

**Comment by icewind1991** [comment] 2015-09-17 12:38
We might want to count a free_space of 0 to mean unkown, since the chance of the filesystem actually having exactly 0 byte free is pretty much non existant

**Comment by DeepDiver1975** [comment] 2015-09-17 12:43
Hosting companies have all strange methods to get the free disk usage (e.g. querying a webserver).

We cannot implement fallbacks for all of them.

Maybe a simple switch in the config could be used to basically tell the code base: hey - no idea how much free disk space you have.

Anyway ... backlog for me ... anybody from the community is welcome to submit a fix at any time.

**Comment by cdamken** [comment] 2015-09-24 20:25
Solution :
https://forum.owncloud.org/viewtopic.php?f=32&t=28057#p86764

I replaced /lib/private/files/storage/local.php
```
Code: Select all
    public function free_space($path) {
             $space = @disk_free_space($this->getSourcePath($path));
             if ($space === false || is_null($space)) {
                return \OCP\Files\FileInfo::SPACE_UNKNOWN;
             }
             return $space;
    }
```

with

```
    public function free_space($path) {
             $space = @disk_free_space('/');
             if ($space === false || is_null($space)) {
                return \OCP\Files\FileInfo::SPACE_UNKNOWN;
             }
             return $space;
    }
```

and now it works :)

**Comment by RealRancor** [comment] 2015-09-24 21:48
@cdamken Please re-open until a proper solution is found where people don't need to modify the oC source code.

**Comment by icewind1991** [comment] 2015-09-25 11:17
From what I can tell the issue is not the result from free_space (which we recognize as unknown) but how some hosters handle `INF` (see #15030)

Can someone with this issue try the possible fix mentioned in #15030 instead of changing the `disk_free_space` call

**Comment by RealRancor** [comment] 2015-10-11 09:23
@icewind1991 We had a user reporting that this was fixed for him with 8.1.3:

https://forum.owncloud.org/viewtopic.php?f=21&t=30411#p98520

But from what i can see https://github.com/owncloud/core/pull/19533 wasn't backported to stable8.1

**Comment by PVince81** [comment] 2016-04-29 14:44
@RealRancor has there been any more reports of this or has the problem fixed itself with recent versions ?

**Comment by RealRancor** [comment] 2016-04-30 00:33
Nope, no new reports so closing this for now.

**Comment by ntnn** [comment] 2016-05-22 13:33
Actually, I've been running into this problem. Uploading via webdav works fine, uploading via webinterface throws the error - however nothing shows up in the logs.

**Comment by RealRancor** [comment] 2016-05-28 11:44
Another user reported something similar after upgrading from 8.1.3 to 8.2.5:

https://forum.owncloud.org/viewtopic.php?f=21&t=37010

so re-opening again.

**Comment by mikebabb** [comment] 2016-06-01 11:55
I'm also affected by this problem, and none of the workarounds posted so far appear to be working for ownCloud 9.0.2. I'm getting the message "Your storage is full, files can not be updated" on a VPS at 50% capacity, personal allowance is set to "unlimited". VPS capacity recently increased from 30GB to 60GB, but ownCloud is behaving as if it hasn't been.

On attempting to upload any more files to my ownCloud, I get log entries like:

> Exception: {"Message":"HTTP\/1.1 507 Insufficient Storage","Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Code":0,"Trace":"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota

**Comment by borconi** [comment] 2016-06-08 10:18
I'm Facing the same issue as @ntnn 

Version: 9.0.2
Server: Ubuntu 14.04
Web Server: Lighttpd 1.4.33
Storage (local only): 1.4Tb free
PHP 7.0.3

`Nothing in the error log, but I keep getting: Error uploading file "xxx": Not enough free space, you are uploading 63 KB but only 0 B is left`

I had a look in the mentioned files and it's all there, I figured out that the error is caused by file-upload.js which tries to read the $("#free_space").val() to ensure that there is enough space before even starting the upload. Manually checking the $("#free_space").val() it returns an empty string (which explains the error). I have tried to manually change the:

  `freeSpace = $('#free_space').val();`
to
  `freeSpace = 9999999999999;`

Just to see if it works, but then I got the following error in the console:

` Uncaught SyntaxError: Unexpected token < in JSON at position 0 VM3858:1 `

which wasn't to helpful. 

Still no error in the log file, and the file wasn't uploaded.

**Comment by PVince81** [comment] 2017-04-06 10:07
Can the `disk_free_space` error be caught ? If yes, then detect it and make it switch to the other behavior.

Can someone test this ?

**Comment by Atari-Frosch** [comment] 2017-11-14 16:01
I'm afraid I have to add one. Not Strato, but a dedicated server running on Debian Jessie, with oc10.0.2. Same problem, it seems. Directly after installation everything worked fine, using only the web UI. Shortly afterwards uploads via web UI were no more possible, it says „Not enough free space, you are uploading 267 KB but only 0 b is left.“ Available physical disk space is around 2 TB. Inodes are at 1 % (xfs). File permissions seem to be correct. Log file gives no warning or error. I changed the standard quota to 10 GB, no change. All I found were the same question for older versions (from 5 to 9), and most of them concern webspace users; and none of these questions seem to have gotten proper / working answers.

If I'm at the wrong place here, please give me a hint.

**Comment by PVince81** [comment] 2017-11-14 16:07
Please try running this PHP code:

```php
<?php
$space = @disk_free_space('/');
```

then replace the path with the path of the data folder of ownCloud.

I suspect that PHP is thinking that there are zero bytes available there.

**Comment by Atari-Frosch** [comment] 2017-11-14 16:28
I'm not used to PHP; I'm a Python beginner ;-) I tried these two:
# php5 -r "print @disk_free_space('/');" – and got: 3027101286
# php5 -r "print @disk_free_space('/srv/owncloud/');" – and got: 2562070908928
No zero.

**Comment by PVince81** [comment] 2017-11-14 16:30
how about "/srv/owncloud/data" or whatever path the data is stored in?
and "/srv/owncloud/data/user1/files", replace "user1" with the user id in question.

**Comment by Atari-Frosch** [comment] 2017-11-14 16:35
Same: 
php5 -r "print @disk_free_space('/srv/owncloud/$myuser/files');" – 2562069602304

**Comment by PVince81** [comment] 2017-11-14 16:36
hmmm... I don't understand why this doesn't work then...

you could try this workaround: https://github.com/owncloud/core/issues/18886#issuecomment-143041564

**Comment by Atari-Frosch** [comment] 2017-11-14 16:45
Just got a hint from somewhere else to take a look into the error_log of the webserver (nginx), and there it says: 2017/11/14 17:21:50 [error] 19589#0: *1361 access forbidden by rule, client: 37.201.xxx.xxx, server: wolke.atari-frosch.de, request: "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1", host: "wolke.atari-frosch.de" 

So it seems the script getstoragestats.php is trying to get its data from /, and of course it must not use this. How can I tell it to use the correct path? (And besides: Why did it work at first?)

**Comment by PVince81** [comment] 2017-11-14 16:50
Hmm, when getstoragestats uses "/" it's supposed to be the path inside the "data" folder, not the real root.

I checked with a debugger and it will call getFileInfo on the path "/admin/files" for me (inside the data folder)

Then `getSourcePath` leads it to `/srv/www/htdocs/owncloud/data/admin/' and it queries `disk_free_space` on this one folder.

If you want to check you could add this line (assuming you have 10.0.3):
```
		\OCP\Util::writeLog('DEBUG', 'disk free space: $sourcePath="' . $sourcePath . '" is ' . $space, \OCP\Util::DEBUG);
```

after this line: https://github.com/owncloud/core/blob/master/lib/private/Files/Storage/Local.php#L297

For me locally it outputs this:
```
{"reqId":"XVCDgXh0nN9FdTaARfpC","level":0,"time":"2017-11-14T16:49:38+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"DEBUG","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"disk free space: $sourcePath=\"\/srv\/www\/htdocs\/owncloud\/data\/admin\/\" is 1072934912"}
```

**Comment by PVince81** [comment] 2017-11-14 16:51
(needs loglevel=>0 in config.php)

**Comment by Atari-Frosch** [comment] 2017-11-14 17:19
As I have 10.0.2 the file did not exist. I tried upgrading to 10.0.3 and ran into new problems. I'll report back later …

**Comment by PVince81** [comment] 2017-11-15 16:52
The file does exist in 10.0.2, see https://github.com/owncloud/core/blob/v10.0.2/lib/private/Files/Storage/Local.php#L292.

Please double check. If the file is missing then maybe something is wrong in your source code deployment.

**Comment by Atari-Frosch** [comment] 2017-11-16 15:37
OK, found it. But not in the same path; it actually sits in $owncloud/lib/private/Files/Storage, not somewhere in $owncloud/core/blob – the directory blob/ even does not exist in core/. I downloaded the .zip file from owncloud.org.

I'm now on 10.0.3.3 (new installation) and … well, get the same error message.

I pasted your line after line 297 as you told me to do; it does nothing, it seems. No output in the logfile (yes, loglevel is 0), no change in behaviour, no new error message. *sigh*

**Comment by Atari-Frosch** [comment] 2017-11-16 16:00
Gotcha. I had included global/restrictions.conf in nginx. This includes a statement to disallow execution of .php files in an upload directory … now it works like a charm.

Thank you for your patience with a beginner! I hope I didn't steal too much of your time.

**Comment by PVince81** [comment] 2017-11-16 20:18
@Atari-Frosch can you clarify what works now ? Does the free space reporting of PHP to ownCloud works correctly now ?

**Comment by Atari-Frosch** [comment] 2017-11-16 21:52
Free space reporting seems to work, at least there is no notice about a lack of space, but it does not tell me how much is free. I can upload via web UI, no error messages.

**Comment by PVince81** [comment] 2017-11-17 08:28
@Atari-Frosch so you didn't change any ownCloud code and it works now ?

If it doesn't report any space, maybe PHP is reporting INF (infinite) to ownCloud, so ownCloud just ignores the value and lets you upload.

**Comment by ownclouders** [comment] 2018-01-13 01:10
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ntnn** [comment] 2018-01-15 20:37
This is still an issue. Please reopne.

**Comment by ownclouders** [comment] 2018-02-24 01:11
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment] 2018-02-26 09:17
@ntnn can you describe your environment / scenario and check with the patch from https://github.com/owncloud/core/issues/18886#issuecomment-344322364 ?

**Comment by ntnn** [comment] 2018-02-26 15:43
Thanks for getting back to the issue, I've described the environment in https://github.com/owncloud/core/issues/18886#issuecomment-220832676.

The fixes in this thread, including the one you linked, haven't fixed the issue.

But I'm sorry to say that I won't be able to help you any further, I've switched to nextcloud at the end of january.

**Comment by vadq91** [comment] 2018-03-13 15:25
@PVince81 Hi, I have this issue:
![owncloud_issue](https://user-images.githubusercontent.com/6743170/37351167-758dc8da-26a8-11e8-9292-0a789c8ebd81.png)

`{"reqId":"Wqfqq8c4oXLcOfDF27KVkgAAAAQ","remoteAddr":"XX.XX.XX.XX","app":"DEBUG","message":"disk free space: $sourcePath=\"\/data\/victor.david\/\" is 323320635392","level":0,"time":"2018-03-13T15:13:48+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"victor.david"}`

Version: 9.0.2
Server: Centos 7
Web Server: Apache/2.4.6 
Storage (local only): 302G free
PHP 5.4.16

**Comment by PVince81** [comment] 2018-10-15 14:01
is this still happening with 10.0.10 ?

**Closed** 2021-09-21 09:30 UTC
Labels: Type:Bug
