### ISSUE TITLE
[Feature Request] Give the possibility to change the default check for "Can share" 

### ISSUE THREAD

**Issue by cristiy2007** [owncloud/core#32082] opened 2018-07-18 13:27 UTC
Hello,

As an administrator there should be an option to define the default options that are enabled or disabled when a user creates a new share.
Also a user that has shared information with someone should be able to audit the access to any file/folder shared by him and see exactly who has access.

### Steps to reproduce
1. Share a folder with someone
2. By default "Can share" is enabled and alot of users miss that
3. User who first shared the file/folder can no longer control who has access to the shared file/folder and cannot see who has access to it

### Expected behaviour
1. In the Admin interface there should be an option to change the default options when creating a share
2. The user should be able to audit who has gained access to the files/folders he has shared

### Server configuration
**ownCloud version:** 9.1.7

**Comment by ownclouders** [comment] 2018-07-18 13:52
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/14348 ([feature request] Improved sharing capabilities), https://github.com/owncloud/core/issues/2869 (Feature Request: approve shared files), and https://github.com/owncloud/core/issues/21376 (Feature Request: Sharing full folder path).

**Comment by PVince81** [comment] 2018-07-18 15:13
duplicate of https://github.com/owncloud/core/issues/28384, please upgrade to 10.0.9

**Closed by PVince81** 2018-07-18 15:13 UTC
