### ISSUE TITLE
Checkboxes missing in LDAP wizard

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#19238] opened 2015-09-22 08:03 UTC
### Steps to reproduce
1. Enable LDAP user backend
2. Setup a valid configuration

### Expected behaviour
The "login attributes" tab shows a clear way to enable / disable login with the LDAP username or email.

### Actual behaviour
There is no checkbox to show if those attributes are enabled or not, and the only way to modify it is by clicking in the text. I find it very confusing because clicking in the text isn't common, and also we cannot know the state

### Server configuration
**Operating system**: centos 6.6

**Web server:** httpd

**Database:** mysql

**PHP version:** 5.4

**ownCloud version:** 8.2 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

![screenshot from 2015-09-22 09 59 50](https://cloud.githubusercontent.com/assets/1477829/10013307/b5e70e38-6110-11e5-8a7a-a4e269bf1717.png)

**Comment by jvillafanez** [comment] 2015-09-22 09:01
Looks like it's more a design issue since external storages are also affected. The option to enable previews in the external storage isn't clear to know if it's enabled or not, and probably the same with the encryption option in the external storage.

![screenshot from 2015-09-22 11 01 18](https://cloud.githubusercontent.com/assets/1477829/10014415/4d735c72-6119-11e5-9da8-32169047cdc8.png)

**Comment by PVince81** [comment] 2015-09-22 09:54
@owncloud/designers @jancborchardt @Henni looks like there are more missing checkboxes.

Can you please add a fallback ? This is important to make sure that older apps' checkboxes still appear.

**Comment by Henni** [comment] 2015-09-22 20:55
"enable previews" should work on current master.
See #19284 for the LDAP user backend fix.

**Comment by blizzz** [comment] 2015-09-23 09:54
Caused by https://github.com/owncloud/core/pull/18735/files#diff-463c027b5536faafc395f8fd4d09792bR166

**Comment by MorrisJobke** [comment] 2015-09-28 09:44
This was resolved by reverting the breaking PR. It is now a backwards compatible way of switching to the new design -> I will close this, because it looks like before now.

**Closed by MorrisJobke** 2015-09-28 09:44 UTC
Labels: 3 - To Review, design, regression, sev2-high
