### ISSUE TITLE
[Experimental files locking] Moving a folder doesn't forbid you to download files from moved folder or destination folder.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16859] opened 2015-06-10 11:05 UTC
### Steps to reproduce

**EDIT: Only happens in web ui.**

1. Enable redis as cache system.
2. Enable experimental files locking.
3. Enable external storage app.
4. Mount a SFTP folder.
5. Create a folder 'folder'.
6. Upload files on it.
7. Move 'folder' to SFTP mount folder.
8. Try to download files from 'folder' or from 'SFTP/folder'

### Expected behaviour
You get an error about locked folder.

### Actual behaviour
You can download files (corrupted since they are moving).

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Chrome 41, Firefox

**Comment by PVince81** [comment] 2015-06-10 11:17
Something to discuss @icewind1991 @DeepDiver1975

There are pro and cons for locking the whole dir during transfer.

Pro: prevent sync client to download an unfinished folder
Con: already moved content is locked longer

**Comment by DeepDiver1975** [comment] 2015-06-10 12:15
@icewind1991 your pov - THX

**Comment by icewind1991** [comment] 2015-06-10 12:27
Imo the move operation of a folder should be "atomic", allowing other request to work on the in-between state would only lead to unexpected results

**Comment by DeepDiver1975** [comment] 2015-06-10 14:12
> Imo the move operation of a folder should be "atomic", allowing other request to work on the in-between state would only lead to unexpected results

as in we shall lock the involved folders - can we expect a pr on this? THX

**Comment by icewind1991** [comment] 2015-06-10 14:42
I cant reproduce the issue, I added a `sleep` in the rename code, triggered a rename from the webui and tried to download a file from the source folder over webdav and got a locked error as expected

**Comment by icewind1991** [comment] 2015-06-10 14:43
When acquiring a lock in the view it also acquires a read lock on all parent folders, this disallows getting any lock on files in a folder that has a write lock on it

**Comment by DeepDiver1975** [comment] 2015-06-10 14:47
Anything specific to this because a move to an external fs is involved? @icewind1991

**Comment by icewind1991** [comment] 2015-06-10 14:50
Should be the same, locking is unrelated from the storage used

**Comment by DeepDiver1975** [comment] 2015-06-10 14:53
> Should be the same, locking is unrelated from the storage used

yes - should - but you never know ... :wink:

**Comment by cmonteroluque** [comment] 2015-06-11 14:59
blocking test development

**Comment by PVince81** [comment] 2015-06-11 15:07
In what way does this block test development ?

@SergioBertolinSG did you do the uploading with WebDAV ? (remember that web UI upload does not behave the same)

**Comment by SergioBertolinSG** [comment] 2015-06-12 08:03
@PVince81 This bug was just about web ui.
Same steps using webdav works fine.

**Comment by icewind1991** [comment] 2015-06-16 14:53
Ok, I've done some more testing and found that the file is properly locked during the rename, but when moving a folder to an external storage there is some delay before the rename is started (things like checking if the target exists probably)

When adding a `sleep` to the rename operation, doing a move to an external storage and trying to download the file a few times over webdav:

- The first try (<1 sec after starting the rename) the download succeeds
- A few seconds later the download fails with a locked exception as expected

I would say that this issue is a false positive since no data corruption can happen if a file is downloaded before the actual rename has started.

**Comment by PVince81** [comment] 2015-06-18 08:22
Agreed, closing

**Closed by PVince81** 2015-06-18 08:22 UTC
Labels: bug, feature:locking, sev1-critical
