### ISSUE TITLE
CentOS 7 + Apache + LDAP + WebDAV trouble

### ISSUE THREAD

**Issue by wpoely86** [owncloud/core#11779] opened 2014-10-26 20:43 UTC
### Steps to reproduce
1. Configure Owncloud to auth with LDAP
2. Try to use the webdav interface (with desktop client or any webdav client)
3. Authentication failures (password is correct)

### Expected behaviour
After giving the correct username & password, I should be able to login through the webdav interface. 

Using the same username & password, I can log in to the web interface. If I go to the webdav interface in the same browser (using the cookies from the web interface), I can use the webdav interface. However, after logging out, It ask for username & password and refuses to accept the correct password. 

I've watched the network traffic: When logging in with the webinterface, I see a bind for that user to the LDAP tree. However, when I try the webdav interface, there are no queries to the LDAP tree. 

I've put the loglevel to zero but nothing appears in the logs (that is relevant to this).

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6 18.el7.centos (using php-fpm and fcgi proxy)

**Database:** mariadb 5.5.37 1.el7_0

**PHP version:** php 5.4.16 23.el7_0.1

**ownCloud version:** 7.0.2

**Updated from an older ownCloud or fresh install:** from a 6.x install

**List of activated apps:**

**The content of config/config.php:**
```

  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXXXXXX',
  'dbpassword' => 'XXXXXXXXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => false,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_domain' => 'XXXXXXXXXX',
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'log_type' => 'syslog',
  'logfile' => '',
  'loglevel' => '0',
  'log_query' => true,
  'logtimezone' => 'XXXXXXXXXX',
  'log_authfailip' => true,
  'xframe_restriction' => true,
  'enable_avatars' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'XXXXX',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'session_keepalive' => true,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'overwritewebroot' => '/owncloud',
  'preview_max_scale_factor' => 10,
  'preview_office_cl_parameters' => '',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),


```

**Are you using encryption:** no

### Client configuration
**Browser:** firefox 33

**Operating system:** Fedora 20

**Comment by danmac-uk** [comment] 2015-02-11 11:26
Confirmed WebDAV now working on my ownCloud 8. Ubuntu 14.04 with Apache & php5-fpm, using the patched request.php and that config line. Many thanks :)

**Comment by DeepDiver1975** [comment] 2015-03-21 21:21
> Confirmed WebDAV now working on my ownCloud 8. Ubuntu 14.04 with Apache & php5-fpm, using the patched request.php and that config line. Many thanks :)

sounds like case closed

**Comment by danmac-uk** [comment] 2015-03-21 21:59
I'm just a random user, but I would be inclined to disagree, given the nature of the solution and other issues raised? Although https://github.com/owncloud/core/issues/7719 is probably a duplicate of this anyway. I'm waiting for this to get fixed before I continue applying updates to my install.

**Comment by wpoely86** [comment] 2015-03-22 12:30
@DeepDiver1975 if you consider manually patching owncloud after every update a 'proper' solution, than yes, it this case closed. However, I do not. As long as the patch in #7719 is not merged in master, this is not properly fixed.

**Comment by DeepDiver1975** [comment] 2015-03-22 12:43
Looks like I missed the part that a patch is still pending.  Please submit patches as pull requests and we happily accept them.

**Comment by RealRancor** [comment] 2015-08-13 12:08
Could anyone test https://github.com/owncloud/core/pull/18194 ?

**Closed** 2016-03-01 21:34 UTC
Labels: bug
