### ISSUE TITLE
Share button gets blocked browsing away using Safari as browser 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#17125] opened 2015-06-24 07:33 UTC
### Steps to reproduce
1. Using Safari as browser click on the share button.
2. Browse away in the screen

### Expected behaviour
The share "menu" should dissapear

### Actual behaviour
The share menu is visible and share buttons are blocked

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:**"version":"8.1.0.7","versionstring":"8.1 RC1","edition":"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.0
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_shibboleth: 1.0.1.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Comment by PVince81** [comment] 2015-06-24 08:07
With "browse away" do you mean leaving the page or just clicking anywhere outside the dropdown ?

Anything in the JS console ?

**Comment by PVince81** [comment] 2015-06-24 08:18
@georgehrke @LukasReschke (people with Macs :wink:)

**Comment by georgehrke** [comment] 2015-06-24 08:26
Are you referring to scrolling when you say "browse away"?

**Comment by davitol** [comment] 2015-06-24 08:43
@PVince81 @georgehrke 
No, just to click in any part of the screen.
Console:
[Warning] Unexpected CSS token: : (styles.css, line 36)
[Warning] Unexpected CSS token: : (fixes.css, line 85)
[Warning] Unexpected CSS token: : (mediaelementplayer.css, line 620)
[Warning] Unexpected CSS token: : (mediaelementplayer.css, line 648)
[Warning] Unexpected CSS token: : (styles.css, line 45)

If you want a gif of the way I reproduce just ping

**Comment by davitol** [comment] 2015-06-24 08:47
Safari 8.0.5

**Comment by DeepDiver1975** [comment] 2015-06-25 12:11
> If you want a gif of the way I reproduce just ping

ping

**Comment by georgehrke** [comment] 2015-06-25 13:29
> No, just to click in any part of the screen.

Can't reproduce that with Safari 8.0.6. please try 8.0.6 as well

**Comment by davitol** [comment] 2015-06-25 14:16
Updated to Safari 8.0.6 and the same behaviour occurs.
OC "version":"8.1.0.7","versionstring":"8.1 RC1"
![sharefail](https://cloud.githubusercontent.com/assets/10596560/8356433/8b71457a-1b55-11e5-891f-838fc8d96d29.gif)

**Comment by PVince81** [comment] 2015-06-25 14:27
Can you try clicking in the toolbar or dark blue header instead ?
The place you are currently clicking becomes blue, it is very strange.

**Comment by davitol** [comment] 2015-06-25 14:32
@PVince81 same behaviour anywhere I click

**Comment by PVince81** [comment] 2015-06-25 14:35
Ok thanks. I thought that maybe that specific zone had a bogus click event handler.

Still no idea why it doesn't work for you.

**Comment by davitol** [comment] 2015-06-25 14:37
:sob: Thanks anyway for trying to get the reason

**Comment by georgehrke** [comment] 2015-06-29 11:24
I have absolutely no idea what changed in my environment since I checked 4 days ago, but I can reproduce it and it gives me a js error:
`TypeError: undefined is not a function (evaluating 'event.target.closest('[data-apps-slide-toggle]')')` in `apps.js:61`
will look into it.

**Comment by DeepDiver1975** [comment] 2015-06-29 11:28
@georgehrke thanks a lot for working on this!

**Comment by PVince81** [comment] 2015-07-14 09:51
Same issue appears on IE9.

The console also says that `closest` is not supported for event.target, the line that https://github.com/owncloud/core/issues/17359 tries to fix.

**Comment by davitol** [comment] 2015-07-16 16:25
Should we close this issue due to the reasons written in :
https://github.com/owncloud/core/pull/17359#issuecomment-121190475
?

**Comment by georgehrke** [comment] 2015-07-16 16:34
No, this is still a bug in a supported version.

Please excuse my brevity and typos.

**Comment by MorrisJobke** [comment] 2015-07-17 11:59
@PVince81 @georgehrke Please have a look at #17490

**Comment by MorrisJobke** [comment] 2015-07-17 13:14
Fixed in #17490

**Comment by MorrisJobke** [comment] 2015-07-17 13:14
Backport to stable8.1: #17707

**Closed by MorrisJobke** 2015-07-17 13:14 UTC
Labels: browser:ie, browser:safari, sev2-high, sharing

**Comment by davitol** [comment] 2015-07-22 11:55
:+1: Works for me too in Safari and IE11
OC server: owncloud-daily-master.tar.bz2 (22 jul) version":"8.2.0.2","versionstring":"8.2 pre alpha"
OC server: owncloud-daily-stable8.1.tar.bz2 (22-jul) version":"8.1.0.8","versionstring":"8.1.0
