### ISSUE TITLE
SMTP Email Problem since Ubuntu 16.04 and PHP7

### ISSUE THREAD

**Issue by einmalacht** [owncloud/core#25175] opened 2016-06-17 21:43 UTC
Hello together,

on my Ubuntu 14.04 installation i can sent SMTP Emails via owncloud very well over TLS.

But on 16.04 php7 i cant sent with the same Email config.
Here is the Error log:

A problem occurred while sending the email. Please revise your settings. (Error: Unable to connect with TLS encryption)

stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed at /var/www/owncloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php#95

I connect to my Exchange server over port 587 TLS
In Ubuntu 14.04 i dont have problems to sent over TLS

ownCloud 9.0.2 (stable)

**Comment by RealRancor** [comment] 2016-06-17 23:40
Probably caused by a stricter SSL verification in newer PHP versions together with an insufficient SSL configuration of the SMTP server.

**Comment by einmalacht** [comment] 2016-06-18 07:37
Okay thanks for your reply.
I use sellf signed Certificate on SMTP side .. is it possible to skip this check?

**Comment by DeepDiver1975** [comment] 2016-07-01 13:26
@einmalacht you might want to have a look at the swift mailer api/docs if there is way to influence this.
Closing for now - not really an issue with owncloud itself

**Closed by DeepDiver1975** 2016-07-01 13:26 UTC
