### ISSUE TITLE
Share API: Two subsequent calls to update a share wipes expire date

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#16735] opened 2015-06-03 15:26 UTC
By testing this issue:
https://github.com/owncloud/client/issues/3265
I found that the OCS share API (on stable8 on commit d1f99f10036dd859a5fa36cddeb4663665a17c58) wipes the expire date. Here is what happens:

To update an existing share, the client sends two PUT requests to the share: The first sets the (proper) expire date, and the second sets an empty password. Remember that we need to do two PUTs because the API only accepts one change item per request.

After the second PUT, the client fetches the share again using GET, and the result is that the expire date of the share is null instead of the value sent in the first PUT.

**Comment by LukasReschke** [comment] 2015-06-03 15:27
@rullzer Interested? ;-)

**Comment by rullzer** [comment] 2015-06-03 15:46
I'll have a look.
@dragotin did you test this on master as well?

**Comment by dragotin** [comment] 2015-06-03 15:51
@rullzer no, not yet, sorry

**Comment by rullzer** [comment] 2015-06-03 18:51
I can't reproduce this on master... using curl that is. Lets see what 8.0 does different

**Comment by rullzer** [comment] 2015-06-03 18:57
Aaaah got it.
Master works because there I fixed the password bug. On 8.0 the when a password is set a whole new share is created. And apparently this does not take the expire date into account.

I'll see if this can be fixed easily. If I remember correctly the fix on master is not easily backportable. But I'll look into it.

**Comment by rullzer** [comment] 2015-06-03 19:57
PR with the backports in https://github.com/owncloud/core/pull/16738

**Comment by MorrisJobke** [comment] 2015-06-09 15:10
Merged

**Closed by MorrisJobke** 2015-06-09 15:10 UTC
Labels: 3 - To Review, bug, sharing
