### ISSUE TITLE
User input for login isn't case sensitive, but user input to reset password is case sensitive

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#24896] opened 2016-05-30 12:34 UTC
### Steps to reproduce
1. Add user "User" (upper case "U")
2. Login as "user" with wrong password (lower case "u")
3. Klick "Reset it?" link

### Expected behaviour
User input for login should behave same as user input to reset password.

### Actual behaviour
User input for login isn't case sensitive, but user input to reset password is case sensitive

<img width="558" alt="napkin 30-05-16 2 14 48 pm" src="https://cloud.githubusercontent.com/assets/214010/15649412/a10b3328-2671-11e6-835c-8177ac59cc24.png">

### Server configuration
**Operating system**:
Debian GNU/Linux 8

**Web server:**
Server version: Apache/2.4.10 (Debian)

**Database:**
SQLite

**PHP version:**
PHP 5.6.21

**ownCloud version:** (see ownCloud admin page)
9.0.2

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://hub.docker.com/_/owncloud/

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9t9os06qxo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:9080"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "http:\/\/localhost:9080",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "ocadmin",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 50

**Operating system:**
Mac OSx 1.11.5

@nickvergessen Can case sensitivity for login and password reset be aligned? /cc @cmonteroluque 

00005558

**Comment by PVince81** [comment] 2016-05-30 14:14
I think there was another such report before but can't seem to find it.

**Comment by nickvergessen** [comment] 2016-05-30 14:18
Relates to https://github.com/owncloud/core/issues/23873
I can have a look again later

**Comment by nickvergessen** [comment] 2016-05-30 16:28
After some looking it is not that easy. The problem is that the user object gets initiated with the wrong uid, so when we look for the config values (e.g. email address) we can't find them, because `test` doesn't have an entry, only `Test` has. However that is just on case which we could solve one way or the other. The real problem ist, that the preferences are case sensitive while our user backend is not.

My suggestion would be to create a method in the user backends that returns the uid to use. So even case insensitive backends can use case sensitive functionality (like preferences) no matter which casing they where started with. However adding methods to user backends is always bad, so not sure if that is the best solution.

cc @DeepDiver1975

**Comment by PVince81** [comment] 2016-06-27 10:09
Closing in favor of https://github.com/owncloud/core/issues/10102

Most other similar tickets got closed as duplicate of this one as well.

**Closed by PVince81** 2016-06-27 10:09 UTC
Labels: blue-ticket, sev2-high
