### ISSUE TITLE
Update does not work

### ISSUE THREAD

**Issue by Kornexl** [owncloud/core#16400] opened 2015-05-18 10:08 UTC
An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_41tf0rvm1921a` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by LukasReschke** [comment] 2015-05-18 10:08
Duplicate of https://github.com/owncloud/core/issues/16008, https://github.com/owncloud/core/issues/16214, https://github.com/owncloud/core/issues/16218, https://github.com/owncloud/core/issues/16285, https://github.com/owncloud/core/issues/16185, https://github.com/owncloud/core/issues/16157, https://github.com/owncloud/core/issues/16097, https://github.com/owncloud/core/issues/16089, https://github.com/owncloud/core/issues/7769, https://github.com/owncloud/core/issues/16066, https://github.com/owncloud/core/issues/16063 and https://github.com/owncloud/core/issues/16352

Final tracking of this issue is at https://github.com/owncloud/core/issues/16008 and targeted for 8.0.4 - documentation and work-around are available at this issue as well.

**Closed by LukasReschke** 2015-05-18 10:08 UTC
