### ISSUE TITLE
Files app disabled / config defaults issue ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#13840] opened 2015-02-02 21:18 UTC
I upgraded my openSUSE 13.1 package of owncloud-7.0.4-17 to owncloud-8.0.0~beta2.
Then I ran `sudo -uwww ./occ upgrade`, all went fine.

Now WebDAV doesn't work and the log says:
```
{"reqId":"187e1bbd19a92b4d7a45775be28ab0eb","remoteAddr":"85.180.4.155","app":"remote","message":"App not installed: files","level":4,"time":"2015-02-02T21:13:54+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"4f1045ced87c86d8bf1388425fa1bd1d","remoteAddr":"85.180.4.155","app":"remote","message":"App not installed: files","level":4,"time":"2015-02-02T21:14:26+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"c056c3692650b029d06b1217fb98f8ff","remoteAddr":"85.180.4.155","app":"remote","message":"App not installed: files","level":4,"time":"2015-02-02T21:14:58+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"80e7624c491895e35032a46d468f4f4b","remoteAddr":"85.180.4.155","app":"remote","message":"App not installed: files","level":4,"time":"2015-02-02T21:15:30+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
```

Checking the DB:
```
MariaDB [owncloud]> select * from oc_appconfig where appid='files';
+-------+-----------------------------------+-------------+
| appid | configkey                         | configvalue |
+-------+-----------------------------------+-------------+
| files | backgroundwatcher_previous_file   | 16874       |
| files | backgroundwatcher_previous_folder | 13963       |
| files | default_quota                     | 1 GB        |
| files | installed_version                 | 1.1.9       |
| files | types                             | filesystem  |
+-------+-----------------------------------+-------------+
```

There is no "enabled" key at all ?!

I checked my backup from 7.0.4 and the key was *also* missing.

So I guess that in 7.0.4 the default value for "enabled" was "yes" and now in 8.0.0 we changed it to "no" ? Was this on purpose ? Or is it a side-effect of the recent refactorings of the app config stuff ?

Note: this is different than https://github.com/owncloud/core/issues/13523 where the disabling was done on purpose, and also has the "enabled" key present.

I believe this is a different issue here, related to default config values handling.

Note that I upgraded since OC 4 so maybe that key never existed, so maybe people with similar setups will experience it as well.

@MorrisJobke @LukasReschke

**Comment by PVince81** [comment] 2015-02-02 21:20
If we decided to have "enabled" default to no, we need to provide a repair step that will insert the entry for the "files" app in case it's missing.

@DeepDiver1975 @karlitschek showstopper ?

**Comment by karlitschek** [comment] 2015-02-02 21:27
showstopper

**Comment by PVince81** [comment] 2015-02-02 21:34
You can partially reproduce the symptoms by deleting the "enable" key that might be on new installs.

I remember there was some code where `if ($appid=='files' )` or such and maybe it was removed in OC 8 ? If it's just that we can either add it back or go the repair step way.

**Comment by PVince81** [comment] 2015-02-02 22:31
@MorrisJobke can you have a look as you're familiar with the changes ?
If too busy let me know and I'll take over.

**Comment by MorrisJobke** [comment] 2015-02-02 22:42
On my production instance with 7.0.4 (updated from 6.0.0) I have the key. and in my fresh installed master I also have this key. Let me check the code.

**Comment by MorrisJobke** [comment] 2015-02-02 22:50
Weird:

I upgraded from stable6 to 7.0.4 to master. Before doing the upgrade to master (so on 7.0.4) I deleted the files app enabled entry in the database. Then I upgraded via command line.

on master:

```
$ ./occ app:list
Enabled:
 - files
 - files_sharing
 - files_trashbin
 - files_versions
Disabled:
 - files_encryption
 - files_external
 - provisioning_api
 - user_ldap
 - user_webdavauth
```

I can access the web UI, but the webdav isn't working. I will try to debug.

**Comment by MorrisJobke** [comment] 2015-02-02 22:50
But the main question is: Why did the enabled state got dropped?!?

**Comment by MorrisJobke** [comment] 2015-02-02 22:53
On 7.0.4 everything (also WebDAV) still works if I disable the files app. ("files" "enabled" -> "no" in database)

**Comment by MorrisJobke** [comment] 2015-02-02 23:00
Bisecting from 7.0.4 to master says: 4c13918bd8b12ac4bd341c846a50accc1bf9704d

**Comment by MorrisJobke** [comment] 2015-02-02 23:01
Seems that I did something wrong while bisecting.

**Comment by MorrisJobke** [comment] 2015-02-02 23:11
Ah ... looks a lot better: 7cb12d4bff80e91cb844b9ed0021c290455279ee

Add sabredav plugin to check if a user has access to an app

**Comment by MorrisJobke** [comment] 2015-02-02 23:15
So. This is just a proper implementation of our previous fails. So I would go for an approach to just repair such installations: If the files app isn't enabled: enable it. Or are there any other suggestions? I have no real idea, why your installation has a broken file app. Will look into that later, but first of all I will provide a fix for this problem.

**Comment by MorrisJobke** [comment] 2015-02-02 23:16
> I believe this is a different issue here, related to default config values handling.

It was not to changed default, but to actual implementing it in the correct way. (and not that weird hacky "files app is always enabled" way)

**Comment by MorrisJobke** [comment] 2015-02-02 23:21
Old path: https://github.com/owncloud/core/blob/master/lib/private/app.php#L262-L263 (wrong hacky way)
New path: https://github.com/owncloud/core/blob/master/lib/private/app/appmanager.php#L71-L93 (correct implemented)

**Comment by MorrisJobke** [comment] 2015-02-02 23:53
Fix is #13843

**Comment by MorrisJobke** [comment] 2015-02-02 23:55
@PVince81 This dosn't fix the cause of your missing DB entry.

**Comment by MorrisJobke** [comment] 2015-02-03 00:05
Duplicate of #13523 -> @danimo also didn't dropped the key over there -> I close this one and let's move the discussion over there.

**Comment by MorrisJobke** [comment] 2015-02-03 00:05
BTW: I also migrated the labels.

**Closed by MorrisJobke** 2015-02-03 00:05 UTC
Labels: 5 - To review, bug, ownCloud 8.0 Showstoppers, Regression

**Comment by PVince81** [comment] 2015-02-03 09:40
@MorrisJobke I think the cause doesn't matter, could have been from some very old version.
