### ISSUE TITLE
Creating tag putting an emoji makes dropdown unable to find tags.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22093] opened 2016-02-03 09:08 UTC
### Steps to reproduce

Having no tags in the server do:
1. Assign some tags to a file/folder.
2. Assign an emoji tag, press enter.
3. Refresh the page, open the tags dropdown.
### Expected behaviour

If emoji tags are allowed, then I'd expect the tags.
If not, they should be rejected as non valid tags.
### Actual behaviour

Dropdown is broken.

Step 2:
![screen shot 2016-02-03 at 10 03 28](https://cloud.githubusercontent.com/assets/9048796/12777525/e5f7338a-ca5d-11e5-801b-fdf5fd1c66b3.png)

Step 3:
![screen shot 2016-02-03 at 10 03 55](https://cloud.githubusercontent.com/assets/9048796/12777551/f8bb5208-ca5d-11e5-8572-e718b07ea72b.png)
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.8","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment] 2016-02-03 09:33
If you use MySQL, emojis are very likely to break it. MySQL by default doesn't support 4-byte UTF-8 characters. So if you put emojis in file names or anywhere in ownCloud, it won't work.

You might want to confirm this on your setup.

**Comment by SergioBertolinSG** [comment] 2016-02-03 09:56
In user creation there is an error when creating user.

Does other databases support it? 

I guess the better solution is to avoid emojis on tags returning an error as well.

**Comment by PVince81** [comment] 2016-02-03 10:06
Other databases support emojis, only MySQL doesn't.

@MorrisJobke might know a bit more about this.

**Comment by RealRancor** [comment] 2016-02-03 11:54
Ref: https://github.com/owncloud/core/pull/17978

**Comment by PVince81** [comment] 2016-10-20 16:09
Do emoji tags work correctly with SQLite or PostgreSQL ? (non-mysql)
If yes, then this is a duplicate of https://github.com/owncloud/core/issues/4513

**Comment by PVince81** [comment] 2017-04-06 17:22
Please try again with 10.0 with the 4 byte mode enabled

**Closed by PVince81** 2017-04-06 17:22 UTC
Labels: bug, feature:tags, sev3-medium
