### ISSUE TITLE
Update from 8.1.2 to 8.2.1 failed - owncloud does not work anymore

### ISSUE THREAD

**Issue by ekant1** [owncloud/core#21496] opened 2016-01-07 08:57 UTC
I used the update option in the settings area, it got struck during the installation.
Trying again, it states "Aktualisierung wird gestartet", but immediately, I get the error message

Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by MorrisJobke** [comment] 2016-01-07 09:34
> Exception: Updates between multiple major versions and downgrades are unsupported.
> The update was unsuccessful. Please report this issue to the ownCloud community.

Duplicate of #21367

It seems that you skipped an version. Check the current installed version in config/config.php and the version of the new owncloud in /version.php 

This is the allowed update path:

7.0.x -> 8.0.x -> 8.1.x -> 8.2.x -> 9.0.x

So the first two version numbers matter.

**Closed by MorrisJobke** 2016-01-07 09:34 UTC

**Comment by ekant1** [comment] 2016-01-07 09:38
I just clicked the "update" button in the admin settings area of the wen client to perform an automatic update.
Why should this allow me (as the user) to skip versions which causes crashing my installation?
And how can I repair my installation now?

**Comment by MorrisJobke** [comment] 2016-01-07 09:44
> Why should this allow me (as the user) to skip versions which causes crashing my installation?
> And how can I repair my installation now?

What version are you on? (check the content of your config/config.php file)

**Comment by ekant1** [comment] 2016-01-07 09:46
(See above.) I'm quite sure that in the web application, the banner at the top said something like
"Upgrade to version 8.2.1" and then I just followed the update advice in the settings area.

**Comment by MorrisJobke** [comment] 2016-01-07 10:02
Ah. I now see it:

> My config.php:
> 'version' => '8.0.2.0'

You first need to upgrade to a version in the 8.1.x release - 8.1.5 for example

**Comment by ekant1** [comment] 2016-01-07 10:09
Sure, thanks. But how should I?
Again, I clicked: "Update" in the admin area - nothing else. It did not ask me for a specific version.
I expect that this would just work, without crashing the system.

Can I do something to recover the installation or to initiate the *right* update process?
And how can I avoid those issues in teh future?

I see it clearly as a bug if the software is not able to update itself (especially if it provides an option for it).

Can it be that I interrupted the update process (e.g., by reloading the page) and that this left the system in that buggy (and unsuable) state? Maybe, this would be a kind of robustness worth to be achieved?

**Comment by MorrisJobke** [comment] 2016-01-07 10:11
> Can I do something to recover the installation or to initiate the right update process?
> And how can I avoid those issues in teh future?

This is then something for the updater app (that provides the button). Please open this issue in the updater issue tracker and mention @VicDeo : https://github.com/owncloud/updater/issues

**Comment by RealRancor** [comment] 2016-01-07 10:15
@MorrisJobke Nothing for the updater, only the update URL needs to be fixed to provide the correct version to the updater: https://github.com/owncloud/appstore-issues/issues/4
