### ISSUE TITLE
External Storage as Root Directory Help

### ISSUE THREAD

**Issue by mikshepard** [owncloud/core#24175] opened 2016-04-21 18:06 UTC
Our organization has been running Owncloud since version 7, and we use it as an overlay to our network file storage.  Meaning when inside the building, users can view their "H:\" (a samba user home share) to see their data, but when outside the building, they log into Owncloud and see the contents of their "H:\" as the Owncloud root.   Basically, it functions to give web access to their drive shares when outside the local network.  This has always been accomplished by editing the mount.json file and changing the first share to something like the following:

  

>  "user": {
>         "all": {
>             "\/$user\/files\/": {
>                 "id": 15,
>                 "backend": "local",
>                 "authMechanism": "null::null",
>                 "options": {
>                     "datadir": "\/media\/smb\/Home\/$user"
>                 },
>                 "priority": 150,
>                 "mountOptions": {
>                     "encrypt": true,
>                     "previews": true,
>                     "filesystem_check_changes": 1
>                 }

This allows an external local share to function seamlessly as the Owncloud user root, thereby eliminating the need for a sync client (saving bandwidth and duplications of files), since the users are viewing their actual "Home" drive network share.  Other department network drives shares are mounted as normal external smb shares inside Owncloud and appear inside their root, along all the files of their "H:\" home.  This way when a file is put on their "H:\", it immediately is available on the cloud (no uploading, or database file re-scanning).  The same goes for department shares.

 This has worked perfectly through version 8, however version 9 now seems to have moved to storing the external share info in the database, instead of the json file.  When I go to the admin page, the "/" mount point is changed to "Local" immediately instead.  Editing the database seems to allow me to change it back to "/", however the next time the admin page is visited, this is changed back to "Local" automatically.  

I was able to bypass this, by editing the "_apps/files_external/js/settings.js_" and commenting out lines #960 and #919 -- "_storageParams.mountPoint = storageParams.mountPoint.substr(1); // trim leading slash_".  While this solves the problem of not being able to have "/" assigned to an external mount point, the "Home" icon in the navigation bar now doesn't work, when moving through directories.  Meaning, when inside a subdirectory of a root folder, clicking the "Home" icon does nothing to bring you back, you instead need to use the "All files" option in the Left side-bar.

How can I fix this "Home" button to return to the same functionality as the previous versions?  While I do understand that running Owncloud in this manner may not be officially supported, I do think you can see the benefit our organization achieves by do so.

Any thoughts or help would be greatly appreciated,
Thanks,
-Mike

**Comment by RealRancor** [comment] 2016-04-21 19:29
Hi,

i think you should ask such questions at either the mailinglists or the forums like described here:

https://owncloud.org/support/

A bugtracker is most likely the wrong place for setup / configuration questions.

**Comment by mikshepard** [comment] 2016-04-21 20:33
Thank you for the reply, I have since posted in the forum as per your advice.  My reason for posting here was that beyond getting help for this problem, that it would serve as a feature request.  Since in previous versions, running Owncloud in this manner was fully functional, and extremely beneficial, I was hoping that this could become an option in the files_external app, to allow an external share to have a mountpoint of root.

**Comment by Xenopathic** [comment] 2016-04-21 21:03
Marking as duplicate of #23246, see #23260 for a potential fix

**Closed by Xenopathic** 2016-04-21 21:03 UTC

**Comment by mikshepard** [comment] 2016-04-21 21:56
Great, thanks!
