### ISSUE TITLE
Listing of apps takes too much time.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15851] opened 2015-04-24 08:57 UTC
### Steps to reproduce

1. Install OC 8.1alpha2.
2. List apps enabled or disabled.

### Expected behaviour
Apps are listed quickly.

### Actual behaviour
Apps takes a lot of time to be listed. ~1 minute.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.3","versionstring":"8.1 alpha 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise version.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Logs**
It is plenty of lots of the same message: 
```
{"reqId":"lPE6aoSNmwG1J1hl1Vvn","remoteAddr":"10.40.40.46","app":"core","message":"Could not get application: cURL error 28: Resolving timed out after 5524 milliseconds","level":3,"time":"2015-04-24T08:51:26+00:00"}
```
### Client configuration

**browser**
Chrome 41

**Comment by LukasReschke** [comment] 2015-04-24 12:03
Probably dupe of https://github.com/owncloud/enterprise/issues/578

**Comment by nickvergessen** [comment] 2015-04-24 13:45
Well it's basically quite easy:
https://github.com/owncloud/core/blob/ba52f6f8fc0d88000332e9e64c48a56c526823d9/lib/private/app.php#L838

For each app you have we send a request to the app store to check for an update. In the other ticket @LukasReschke mentions some caching stuff, which helps for subsequent requests.
However, the question is, if we can create an endpoint on the app store which we pass a list of ocsid, so we can do 1request to get all update infos instead of 1 request per app

**Comment by jancborchardt** [comment] 2015-05-01 18:02
Yeah, this should go much faster. A start would be that the appstore just has the titles, authors and the id’s of the app in a list which can be fetched by one request. Any app description or whatever can be loaded later.

**Comment by nickvergessen** [comment] 2015-05-04 08:19
Another thing would be to load the page with the details we have and fetch the update information asyncronous with a second request.

**Comment by jnfrmarks** [comment] 2015-06-04 19:43
I'd like to see us resolve this in 8.1.  The performance when loading the apps page is slower than in 8.0.3

**Comment by SergioBertolinSG** [comment] 2015-06-10 08:06
I have tried this with redis enabled as cache and it still needs a lot of time to load.

**Comment by nickvergessen** [comment] 2015-06-10 08:48
Well as said, the first page view is slow as it requests the app server for each app.
Let me try if I can come up with a quick way to load the update info after the initial page is displayed.

**Closed** 2015-06-16 09:41 UTC
Labels: performance, settings:apps, sev2-high
