### ISSUE TITLE
Reshare not allowed in subdirs

### ISSUE THREAD

**Issue by canepan** [owncloud/core#13518] opened 2015-01-20 16:02 UTC
Hello.
I have an OC 7.0.4 under Apache 2.2 with PHP 5.3
If an user shares a folder, with share permission flag enabled (reshare allowed globally, but it was not allowed when the folder was first shared).
I can reshare the main folder, but not sub-folders or files within the folder

**Comment by karlitschek** [comment] 2015-01-20 16:04
@schiesbn What do you think?

**Comment by kiswap** [comment] 2015-01-21 08:42
maybe related: if a directory (dir1) is shared with a user (user1), but resharing is not allowed (ie permission 15), then nobody who sees that folder (and have share and other permissions, ie 31) can share the contents that the user1 upload into that folder (dir1), even admin cannot share!
This is because the new contents (file1) in that folder (dir1) is inserted into oc_filecache db table with permissions that user1 has on dir1 (ie permission:15) 
If I change the database record for the content (file1) in dir1 and update permissions to 31 (all), then admin and others with reshare permissions can share content (i'm not sure, if user1 can also share. i gues yes).

on client side apps/files_sharing/js/share.js: 143
the validation is: if ((permissions & OC.PERMISSION_SHARE) === 0) {
which disable resharing the content for users those have reshare permission on the parent folder anyway, because permission is connected to file/dir and not the user.

permissions should not have assigned to filecache globally but to "user-share-file" relations, so the system should determine if a content is reshareable by a user according to the permissions set to user on then content which can be different for every user.

**Comment by PVince81** [comment] 2015-01-22 09:23
Duplicate of https://github.com/owncloud/core/issues/10299

**Comment by canepan** [comment] 2015-01-23 17:26
I'm not sre it's the same issue since:
- share button does not disappear
- only (and predictably) happens on subfolders of a shared folder

Environment:
- Apache 2.2
- PHP 5.3
- sqlite DB
- CentOS 6 x86_64
- OwnCloud 7.0.4 fresh install

Even tried
 `occ files:scan --all`
after applying d534f26

**Comment by PVince81** [comment] 2015-01-23 17:47
If files:scan --all didn't fix it then it's a different issue.
Reopening.

**Comment by ravermeister** [comment] 2015-01-26 18:49
I've exactly the same problem, If I try to reshare a File in a Subfolder of a shared Folder, 
I get the error Message that resharing is not allowed.

I did an 
> php consolo.php files:scan --all too
and checked the filerights, they look ok to me (the webserver and php user have read write execute)
but that did not solve the problem. 

I'm using latest Owncloud 7 (7.0.4)

**Comment by ravermeister** [comment] 2015-01-26 19:00
canepan commented 3 days ago:

> I'm not sre it's the same issue since:
> share button does not disappear
> only (and predictably) happens on subfolders of a shared folder

I've exactly the same problem, If I try to reshare a File in a Subfolder of a shared Folder,
I get the error Message that resharing is not allowed.

I did an

    php consolo.php files:scan --all 
too
and checked the filerights, they look ok to me (the webserver and php user have read write execute) but that did not solve the problem.

I'm using latest Owncloud 7 (7.0.4)

Okay, for me I could solve it by removing and readding the group from the share (which should be allowed to reshare)

hope that helps,

**Comment by PVince81** [comment] 2015-02-06 10:55
@canepan just to confirm, did you run `files:scan --all` as the web server user ?
`sudo -uwww ./occ files:scan --all`. This is crucial. If you ran as root it might set file permissions to root which is wrong. (a safety check for this has been added in the upcoming OC 8)

**Comment by canepan** [comment] 2015-02-09 08:33
I executed it as root, but permissions were OK (owner: web server user, permissions rw only by owner), else the files/directory would not be accessible at all (but I double-checked it)

**Comment by PVince81** [comment] 2015-04-22 07:56
Please try again with 7.0.5, there was a fix related to reshares: https://github.com/owncloud/core/issues/10299

**Comment by canepan** [comment] 2015-04-22 13:35
Thnank you.
I'm checking it.
The upgrade procedure has a glitch: {version} appears instead of the
correct version (see screenshot).

Nicola

2015-04-22 9:56 GMT+02:00 Vincent Petry <notifications@github.com>:

> Please try again with 7.0.5, there was a fix related to reshares: #10299
> <https://github.com/owncloud/core/issues/10299>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/13518#issuecomment-95067146>.
>



-- 
http://canne.homeunix.net

**Comment by PVince81** [comment] 2015-04-22 13:37
The glitch was fixed in OC 8

**Comment by canepan** [comment] 2015-04-22 13:43
Sorry: it only happens with OC 7.0.2: upgrading from 7.0.4 displays
correctly

Nicola

2015-04-22 15:37 GMT+02:00 Vincent Petry <notifications@github.com>:

> The glitch was fixed in OC 8
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/13518#issuecomment-95179601>.
>



-- 
http://canne.homeunix.net

**Comment by PVince81** [comment] 2015-05-15 13:15
Ok cool, thanks for the feedback.
Closing.

**Closed by PVince81** 2015-05-15 13:15 UTC
Labels: bug
