### ISSUE TITLE
WebDAV external storage only works partly

### ISSUE THREAD

**Issue by angelus1969** [owncloud/core#23419] opened 2016-03-21 07:39 UTC
### Steps to reproduce
1. add external storage, WebDAV in this case
2. data gets synced
3. add file to external storage in ownCloud; data gets synced to WebDAV server
4. add/remove file on WebDAV server; everything stops, no more sync in either direction.

### Expected behaviour
Data should get synced or else this external storage makes no sense

### Actual behaviour
nothing, that's the problem

### Server configuration
**Operating system**: Debian 8

**ownCloud version:** (see ownCloud admin page)
8.x and also on 9.x
**Updated from an older ownCloud or fresh install:**
both
**Where did you install ownCloud from:**
repository
**Signing status (ownCloud 9.0 and above):**

This problem has existed for a LONG time now, and is not limited to WebDAV is my experience. The whole external storage does NOT work as expected. Perhaps spend a little less time on new versions with very questionable practices like the 'signing' in version 9 and make sure that existing features actually WORK!

**Comment by MorrisJobke** [comment] 2016-03-21 08:50
cc @Xenopathic @icewind1991

**Comment by PVince81** [comment] 2016-03-21 15:20
My steps on v9.0.0:

1. `docker run -d -e USERNAME=test -e PASSWORD=test -p 8888:80 morrisjobke/webdav`
1. Setup "Webdav" external storage as mount point "/dav", "localhost:8888" with "/webdav" as root
1. Setup desktop sync client
1. Wait for sync
1. Using "cadaver", connect directly to http://localhost:8888/webdav
1. Put a file "test.txt"
1. Wait for sync

This works for me.

It's only when you make changes in deeper folders that ownCloud cannot properly detect changes.
This is because the Webdav server doesn't propagate mtimes or etags further than the first parent.
One would need a full rescan to detect changes. The workaround is running "occ files:scan --all" in a cronjob.

Closing as duplicate of https://github.com/owncloud/core/issues/11797

**Closed by PVince81** 2016-03-21 15:20 UTC
Labels: app:files_external, bug
