### ISSUE TITLE
Internal Server Error, depending on directory name

### ISSUE THREAD

**Issue by volkerwysk** [owncloud/core#25813] opened 2016-08-16 12:37 UTC
### Steps to reproduce
I assume that ~/ownCloud is synchronized. 
Do "mkdir ~/ownCloud/'blah :123'"

When I remove the ":" character, it works fine.

### Expected behaviour
The created directory ~/ownCloud/"blah :123" is synchronized.

### Actual behaviour
An "Internal Server Error", is reported in the desktop client: 16.08.16 14:08:15, blah :123, ownCloud,Error downloading https://localhost/owncloud/remote.php/webdav/blah :123 - server replied: Internal Server Error 

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache 2.4.18

**Database:**
SQLite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/ /

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - calendar: 1.3.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocaq6khjlv21",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "vwysk.now-ip.net"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/localhost\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.1.0.15",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/owncloud"
    },
    "apps": {
        "activity": {
            "installed_version": "2.3.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "64"
        },
        "calendar": {
            "installed_version": "1.3.2",
            "enabled": "yes",
            "types": "",
            "ocsid": "168707",
            "signed": "true"
        },
        "comments": {
            "installed_version": "0.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "1.3.1.0",
            "enabled": "yes",
            "types": "",
            "ocsid": "168708"
        },
        "core": {
            "installedat": "1462107115.1298",
            "lastupdatedat": "0",
            "public_files": "files_sharing\/public.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "lastcron": "1471082129",
            "repairlegacystoragesdone": "yes",
            "oc.integritycheck.checker": "[]"
        },
        "dav": {
            "installed_version": "0.2.5",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "0.3.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "0.1.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.5.1",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "0.10.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "0.9.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "0.9.8",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": "",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "15.0.0",
            "types": "",
            "enabled": "yes"
        },
        "notifications": {
            "installed_version": "0.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "0.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "templateeditor": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "0.2.1",
            "types": "",
            "enabled": "yes"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
~ % apt-show-versions firefox
firefox:amd64/xenial-security 48.0+build2-0ubuntu0.16.04.1 uptodate

**Operating system:**
~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
This is 1.7 Megabytes big!

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2016-08-16 13:34
> ownCloud version: (see ownCloud admin page) 9.0.1

Please always use a recent oC version (currently 9.0.4 for the 9.0.x branch) before reporting any issues with such outdated versions like 9.0.1

It might be also useful to know which version of the sync-client you're running.

**Comment by volkerwysk** [comment] 2016-08-16 15:42
Am Dienstag, 16. August 2016, 06:35:09 CEST schrieb RealRancor:
> > ownCloud version: (see ownCloud admin page) 9.0.1
> 
> Please always use a recent oC version (currently 9.0.4 for the 9.0.x branch)
> before reporting any issues with such outdated versions like 9.0.1

Sorry, that's a typo. The version is 9.1.0.

> It might be also useful to know which version of the sync-client you're
> running.

The client version is 2.2.3.

Greetings,
V.W.

**Comment by PVince81** [comment] 2016-08-17 09:12
Duplicate of https://github.com/owncloud/core/issues/25479

Basically a PHP bug

**Closed by PVince81** 2016-08-17 09:12 UTC
