### ISSUE TITLE
Tooltips do not disappear sometimes using Safari 8.0.5 browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#15984] opened 2015-04-30 16:20 UTC
### Steps to reproduce
1. Go to LDAP wizard configuration using Safari 8.0.5 
2. Move the cursor over the different textboxes

### Expected behaviour

Only one tooltip should be shown.

### Actual behaviour
Several tooltips are shown when we move the cursor over the textboxes as it is shown in the image

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

![captura de pantalla 2015-04-30 a las 18 13 03](https://cloud.githubusercontent.com/assets/10596560/7417271/464a9102-ef65-11e4-82e1-1e5af8ffed0e.png)

**Comment by davitol** [comment] 2015-04-30 16:20
@jancborchardt

**Comment by jancborchardt** [comment] 2015-04-30 16:27
This will be solved by moving from tipsy to the Bootstrap tooltip library: https://github.com/owncloud/core/issues/13646

**Comment by davitol** [comment] 2015-05-12 09:10
Just fyi checked this with IE9 and it works as expected

**Comment by blizzz** [comment] 2015-08-07 08:30
@davitol with https://github.com/owncloud/core/pull/17075 being merged, does it work with current master (upcoming 8.2)?

**Comment by davitol** [comment] 2015-08-07 08:56
It works perfect for me now :+1: +1
:version":"8.2.0.3","versionstring":"8.2 pre alpha" (master

**Comment by jancborchardt** [comment] 2015-08-07 14:35
We can thank @Henni for that! He replaced the old tooltip library with a better one. :)

**Comment by davitol** [comment] 2015-11-05 16:29
Same issue in Safari 8.0.8 and LDAP wizard

**Comment by Henni** [comment] 2015-11-05 17:05
This was probably caused by #19940

**Comment by PVince81** [comment] 2016-02-08 20:27
@davitol is this still an issue on 9.0 ?

**Comment by davitol** [comment] 2016-02-09 07:28
@PVince81 . Yes, i've just reproduce it in ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-02-09T04:14:39+00:00 850ac0cf84f2492b16204b811f58a0dc7dc43b6e

**Comment by davicente** [comment] 2016-05-05 11:25
I've been playing a little bit with this issue, and I discovered with @davitol that it works properly in 8.2.0 version, it used a different tooltip.
This is how it looks like in this version
![8_2_0](https://cloud.githubusercontent.com/assets/752240/15040415/e91ba29a-12b4-11e6-8418-73f711977910.png)

And this is what sometimes happens in the rest of versions on Safari

![8_1_7](https://cloud.githubusercontent.com/assets/752240/15040452/329e36c6-12b5-11e6-80d9-091c665a8189.png)

It's easy to go back to the simpler tooltip.
@blizzz @jancborchardt , what do you think?

**Comment by jancborchardt** [comment] 2016-05-05 11:52
I would say that nice looking tooltips take precedence over them sometimes not disappearing in some specific part of the app using a niche browser.

**Closed** 2016-05-05 11:55 UTC
Labels: browser:safari, bug, comp:core-js, design, sev4-low, won' t fix
