### ISSUE TITLE
Thumbnail generation seems to fail in some cases

### ISSUE THREAD

**Issue by AndyScherzinger** [owncloud/core#20762] opened 2015-11-26 15:35 UTC
### Steps to reproduce
1. upload a photo made with the cellphone

### Expected behaviour
Image should get uploaded and thumbnail should be shown in the file list and also in the gallery view

### Actual behaviour
Image gets uploaded but thumbnail isn't shown (just the mimetype image icon) in the file list and the gallery view simply states error creating preview, removing it from preview. This hapens for images taken by a Nexus5 and a Nexus5X but all of the above works for pictures that have been taken with a Galaxy Nexus device (lower resolution)

### Server configuration
**Operating system**:
unknown - hosting at 1&1
**Web server:**
unknown - hosting at 1&1
**Database:**
mySQL
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**

unknown - hosting at 1&1

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocjz6cj0y3vd',
  'trusted_domains' => 
  array (
    0 => 'yyy.yyy.net',
  ),
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\Movie',
  ),
  'datadirectory' => '/homepages/13/yyyyyyy/htdocs/yyyyyyy/yyyyyyy/data',
  'overwrite.cli.url' => 'http://yyy.yyy.net',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'yyy',
  'dbhost' => 'yyy.1and1.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'yyy',
  'dbpassword' => 'yyy',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 42.0
**Operating system:**
Windows 7
#### Web server error log
unknown - hosting at 1&1

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VlckVQouGx0AAAhysgAAAABt","remoteAddr":"193.24.32.43","app":"core","message":"Generating preview for \"\/IMG_20150605_145434.jpg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2015-11-26T15:25:10+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FIMG_20150605_145434.jpg&c=2a5ff0279912d1285b0da55189440f19&x=40&y=40&forceIcon=0"} {"reqId":"VlckVQouGx0AAAhysgAAAABt","remoteAddr":"193.24.32.43","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2015-11-26T15:25:10+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FIMG_20150605_145434.jpg&c=2a5ff0279912d1285b0da55189440f19&x=40&y=40&forceIcon=0"} {"reqId":"VlckWAouGx0AAAhVrXIAAABQ","remoteAddr":"193.24.32.43","app":"core","message":"Generating preview for \"\/Photos\/IMG_20151126_150517.jpg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2015-11-26T15:25:13+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPhotos%2FIMG_20151126_150517.jpg&c=12ab7a67dcaf74141b186243a58f4a83&x=40&y=40&forceIcon=0"} {"reqId":"VlckWAouGx0AAHnTg50AAAAR","remoteAddr":"193.24.32.43","app":"core","message":"Generating preview for \"\/Photos\/2015-07-14 22.06.05.jpg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2015-11-26T15:25:14+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPhotos%2F2015-07-14+22.06.05.jpg&c=5ae4fd48e5d166a5b69b52b8c582ca82&x=40&y=40&forceIcon=0"} {"reqId":"VlckWAouGx0AAAhkr9MAAABf","remoteAddr":"193.24.32.43","app":"core","message":"Generating preview for \"\/Photos\/2015-11-10 22.15.41.jpg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2015-11-26T15:25:14+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPhotos%2F2015-11-10+22.15.41.jpg&c=196b2a1703cadf83890d3f41f287838f&x=40&y=40&forceIcon=0"} {"reqId":"VlckWAouGx0AAHnTg50AAAAR","remoteAddr":"193.24.32.43","app":"core","message":"OC_Image->fixOrientation() Orientation: 1","level":0,"time":"2015-11-26T15:25:14+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPhotos%2F2015-07-14+22.06.05.jpg&c=5ae4fd48e5d166a5b69b52b8c582ca82&x=40&y=40&forceIcon=0"} {"reqId":"VlckWAouGx0AAAhkr9MAAABf","remoteAddr":"193.24.32.43","app":"core","message":"OC_Image->fixOrientation() Orientation: 1","level":0,"time":"2015-11-26T15:25:14+00:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FPhotos%2F2015-11-10+22.15.41.jpg&c=196b2a1703cadf83890d3f41f287838f&x=40&y=40&forceIcon=0"} {"reqId":"VlclNAouGx0AABo6edsAAAAG","remoteAddr":"193.24.32.43","app":"PHP","message":"Array to string conversion at \/homepages\/13\/yyy\/htdocs\/yyy\/ownCloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-11-26T15:28:52+00:00","method":"GET","url":"\/index.php\/settings\/admin"} 
```

pictures used for testing.
2012-03-25 19.59.06.jpg (works)
![2012-03-25 19 59 06](https://cloud.githubusercontent.com/assets/1315170/11426294/4f98b978-945b-11e5-9f43-c152c5bda6d7.jpg)

2015-07-14 22.06.05.jpg (doesn't work)
![2015-07-14 22 06 05](https://cloud.githubusercontent.com/assets/1315170/11426322/746384a4-945b-11e5-8b60-04c740c84533.jpg)

IMG_20151126_150517.jpg (doesn't work)
![img_20151126_150517](https://cloud.githubusercontent.com/assets/1315170/11426345/a3fbf318-945b-11e5-9432-c3734d793fe3.jpg)

If there is anything else that might help please let me know. As far as remember this worked fine for the first two images on oC 8.1.x but I can't tell if 1&1 did any changes.

**Comment by PVince81** [comment] 2016-03-04 18:00
@oparoz @georgehrke

**Comment by oparoz** [comment] 2016-03-04 18:12
Likely a duplicate of #17713, #18417 and #21173. Apparently a problem since 8.1.
The main difference here seems to be that there is no orientation error.

The Android app must be using a path which doesn't create the max preview for some reason.

**Comment by AndyScherzinger** [comment] 2016-03-04 21:39
This one is different since the server seems to be the problem, due to the fact, that the web interface fails to show the pictures too. And even if I copy the files from my phone and upload them via drag and drop on my laptop via the web interface, the server isn't able to generate preview images.

**Comment by oparoz** [comment] 2016-03-04 21:50
You're right and the fact that it doesn't work in the GUI reminds me of a recent report from someone on 1&1. The problem was that PHP did not have enough memory to process the images. Maybe you're having the same problem and need to upgrade to a more powerful plan?
The theory would check out if pictures 2 and 3 were larger than picture 1.

**Comment by AndyScherzinger** [comment] 2016-03-04 23:10
Picture size isn't the issue since some larger ones work and some smaller ones don't which isn't an indication since like you said it might be a memory/ressource problem so it always depends on the memory available. :disappointed:

**Comment by oparoz** [comment] 2016-03-04 23:20
But you do mention in the OP that all your lowres pictures had no issues and that you only had problems with the larger ones.
What happens if you upload the same lowres pictures from a Nexus 5X? Does it also fail?

**Comment by AndyScherzinger** [comment] 2016-03-04 23:41
Haven't given that one a try but can give it a try but like I said this also happens if I upload them via the web interface. So it does not depend on the phone uploading the images. Since some Nexus5 pictures get previews but most don't I would also go for memory problem.

**Comment by PVince81** [comment] 2016-07-06 10:13
@georgehrke

**Comment by PVince81** [comment] 2016-10-20 16:22
Is this still happening with 9.1.1 ? There were some path fixes for previews recently.

**Comment by AndyScherzinger** [comment] 2016-10-20 20:57
It's not happening for me anymore but I did upgrade my hosting plan, so I now have way more memory which leads to likely solved the issue in my case.

**Comment by PVince81** [comment] 2016-10-21 08:21
mmmhhh that first pic looks delicious...

uhhh...

Okay but I didn't see any memory error in your log. So it's probably rather the path construction code that was fixed recently.

**Closed by PVince81** 2016-10-21 08:21 UTC
Labels: bug, feature:previews
