### ISSUE TITLE
Cannot modify header information - headers already sent (heartbeat)

### ISSUE THREAD

**Issue by benkinooby** [owncloud/core#24462] opened 2016-05-06 07:12 UTC
### Steps to reproduce
don't know but I guess "heartbeat" is responsible

### Expected behaviour
not sure

### Actual behaviour
not sure

### Nota Bene
Please note that the owncloud logs are nearly ident to issue 24461
https://github.com/owncloud/core/issues/24461

### Server configuration
**Operating system**:
gentoo (ARM)

**Web server:**
nginx

**Database:**
mysql 5.6.28

**PHP version:**
5.6.20

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
updated from 8.2.3
I recall seeing similar messages in 8.2.2 and 8.2.3

**Where did you install ownCloud from:**
gentoo's package manager "portage"

**Signing status (ownCloud 9.0 and above):**
webapp is a gentoo tool for managing virtual hosts.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .webapp

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp] => Array
                        (
                            [expected] => 
                            [current] => 
                        )
                )
        )
)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_pdfviewer
  - files_texteditor
  - files_videoplayer
  - firstrunwizard
  - gallery
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oce8d15oay3j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX.XXX.com"
        ],
        "datadirectory": "\/var\/www\/XXX.XXX.com\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/XXX.XXX.com",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud02",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "YYY.YYY",
        "mail_domain": "gmx.at",
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpport": "587",
        "loglevel": 0,
        "mail_smtpauthtype": "LOGIN",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Mozilla Firefox

#### ownCloud log (data/owncloud.log)
```
{"reqId":"1T3Y1uJJUnBrPyQR4QEY","remoteAddr":"XXX.XXX.XXX.XXX","app":"base","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/XXX...', 47, Array)\\n#1 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(47): setcookie('oce8d15oay3j', '', -1, '\\\/')\\n#2 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(425): OC\\\\Session\\\\Internal->__construct('oce8d15oay3j')\\n#3 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(579): OC::initSession()\\n#4 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#5 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/XXX...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":127}","level":3,"time":"2016-05-05T22:55:13+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"1T3Y1uJJUnBrPyQR4QEY","remoteAddr":"XXX.XXX.XXX.XXX","app":"index","message":"Exception: {\"Exception\":\"ErrorException\",\"Message\":\"Cannot modify header information - headers already sent\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Session\\\\Internal->trapError(2, 'Cannot modify h...', '\\\/var\\\/www\\\/XXX...', 103, Array)\\n#1 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/response.php(103): header('HTTP\\\/1.1 500 In...')\\n#2 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(436): OC_Response::setStatus(500)\\n#3 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(579): OC::initSession()\\n#4 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#5 \\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/XXX...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/XXX.XXX.com\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php\",\"Line\":127}","level":3,"time":"2016-05-05T22:55:13+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"1T3Y1uJJUnBrPyQR4QEY","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"ErrorException: Cannot modify header information - headers already sent at \/var\/www\/XXX.XXX.com\/htdocs\/owncloud\/lib\/private\/session\/internal.php#127","level":3,"time":"2016-05-05T22:55:13+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
{"reqId":"1T3Y1uJJUnBrPyQR4QEY","remoteAddr":"XXX.XXX.XXX.XXX","app":"PHP","message":"Cannot modify header information - headers already sent at Unknown#0","level":3,"time":"2016-05-05T22:55:13+00:00","method":"POST","url":"\/index.php\/heartbeat","user":"--"}
```

**Comment by benkinooby** [comment] 2016-05-06 07:19
FWIW:
The admin page also mentions: "No memory cache has been configured. To enhance your performance please configure a memcache if available."

**Comment by PVince81** [comment] 2016-05-06 08:22
Closing as duplicate of https://github.com/owncloud/core/issues/24461

They both seem to follow the `setcookie` path

**Closed by PVince81** 2016-05-06 08:22 UTC
