### ISSUE TITLE
Improve handling of unavailable external storages

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#22833] opened 2016-03-03 19:10 UTC
particularly in a way the mount providers such as files_external don't need to handle it.

A non available storage should still show up in webdav/webui, give a proper exception when somebody tries to access it and show with a red background in the webui

see https://github.com/owncloud/core/pull/22816

**Comment by PVince81** [comment] 2016-03-04 10:32
>  non available storage should still show up in webdav/webui

Agreed. That was not the case in the past so it's understandable that the code might need bigger changes to accomodate for that.

@Xenopathic

**Comment by PVince81** [comment] 2016-06-24 12:29
I saw this working with a misconfigured SMB, the storage did appear in the GUI, so it's probably solved.
@icewind1991 can you confirm ?

**Comment by PVince81** [comment] 2016-06-24 12:30
on master / 9.1.0

**Comment by PVince81** [comment] 2016-12-08 09:58
Closing as dupe of https://github.com/owncloud/core/issues/11792

**Closed by PVince81** 2016-12-08 09:58 UTC
Labels: app:files_external, enhancement
