### ISSUE TITLE
WebDAV quota value returned in exponential format

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#16240] opened 2015-05-11 13:27 UTC
See https://github.com/owncloud/android/issues/940

**Comment by PVince81** [comment] 2015-10-09 10:09
### Steps

1. Setup OC
1. `update oc_filecache set size=123123123123123 where storage=1 and path = 'files'` (sets 123 TB used size)
1. `curl -X PROPFIND http://root:admin@localhost/owncloud/remote.php/webdav/ | xmllint --format -`

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/owncloud/remote.php/webdav/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Fri, 09 Oct 2015 09:57:10 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>123123123123123</d:quota-used-bytes>
        <d:quota-available-bytes>25262518272</d:quota-available-bytes>
        <d:getetag>"56178f76a2db8"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/owncloud/remote.php/webdav/welcome.txt</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Fri, 09 Oct 2015 09:57:10 GMT</d:getlastmodified>
        <d:getcontentlength>123123123123123</d:getcontentlength>
        <d:resourcetype/>
        <d:getetag>"3a9cd1a46f7a2492ab65030dd205db89"</d:getetag>
        <d:getcontenttype>text/plain</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

I couldn't reproduce this neither in stable8, stable8.1 or 8.2 RC1.

**Comment by PVince81** [comment] 2015-10-09 10:10
@EtienneBruines are you still seeing this issue with recent OC versions ?

**Comment by PVince81** [comment] 2015-10-13 09:05
Reopening due to wrong PR linking.

**Comment by MorrisJobke** [comment] 2015-11-25 13:03
I will close this issue, because we can't reproduce this anymore and have no additional debug information.

**Closed by MorrisJobke** 2015-11-25 13:03 UTC
Labels: bug, feature:quota
