### ISSUE TITLE
If a user belongs to a group that has not been set in the excluded groups from sharing, he can share files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20473] opened 2015-11-12 10:07 UTC
### Steps to reproduce

1. Create a user that belongs to two groups
2. Go to admin page
3. Set one of the previous groups to be excluded from sharing
4. Login with the  user created and try to share a file

### Expected behaviour

Proposal:
If a user belongs to a group that has been set in the excluded groups from sharing, he should not be able to share files (most restrictive condition)

### Actual behaviour

If a user belongs to a group that has not been set in the excluded groups, he can share files

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 8.2.1. (RC2)

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-12 at 11 02 14](https://cloud.githubusercontent.com/assets/10596560/11115592/df6019b4-892c-11e5-9b94-3a4b79aa905e.png)

**Comment by davitol** [comment] 2015-11-12 10:16
@blizzz 

Another situation: 
Using an Active Directory with nested groups allowed. User belongs to group1 and this group is included in group2. If group2 is added to 'Exclude groups from sharing', the user should not be able to share files, even if group1 is not included in the forbidden groups specifically

**Comment by rullzer** [comment] 2015-11-14 12:26
Well that would be changeing behaviour and have unexpected result for people that rely on the current behaviour. 

Anyway, this is a duplicate of https://github.com/owncloud/core/issues/16346. So lets discuss there.

**Closed by rullzer** 2015-11-14 12:26 UTC
Labels: discussion, needs info
