### ISSUE TITLE
Shared video not playable in Firefox, Safari, Safari(iOS) but works in Google Chrome.

### ISSUE THREAD

**Issue by dabvid** [owncloud/core#12835] opened 2014-12-14 10:34 UTC
I have tried to play and download two different videos from a public share url. One .mov and one .mp4.

Safari iOS 8.1.2
Can play video: No
Can download video: No

Safari 8.0.2 OSX Yosemite 10.10.1
Can play video: No
Can download video: Yes
 
Firefox 34.0.5 OSX Yosemite 10.10.1
Can play video: No
Can download video: Yes

Google Chrome OSX Yosemite 10.10.1
Can play video: Yes
Can download video: Yes

**Comment by autrui** [comment] 2015-03-01 15:50
I can't recall that playing iPhone videos shared by public link (password protected or not) has ever worked at all. See [#10749](https://github.com/owncloud/core/issues/10749).
@karlitschek filed it under enhancement requests. To me it seems like a bug (why would you have all the built-in video support + a dedicated iOS app and then not have it work with publicly shared links?).

**Comment by bs** [comment] 2015-03-18 06:03
Seems like a bug to me. It looks like it should play (displays a play button) but then doesn't.

**Comment by autrui** [comment] 2015-08-16 16:24
Public sharing of videos (by link) still not working. Ex.: Safari shows video viewer window with play button but nothing ever plays.
That's definitely not a mere enhancement as suggested by the label assigned.

I get that support for public multimedia shares is maybe not a priority.
But I'd really like to use OC to share photos and videos with people when I'm travelling. So far it only works for photos. I've never been able to get (iPhone) videos to work with OC.

**Comment by dbubs** [comment] 2016-06-01 13:04
The **ENTIRE** purpose of owncloud is to share content! Currently this issue renders sharing video with mobile users useless. This happens regardless of how the video was uploaded, ie desktop browser or mobile app. 

I uploaded a video to OC from a desktop browser last night and created a public link. I was able to visit the public link via Chrome on my Mac and the video played fine and I was able to download it (it did not, however, play in Safari on the Mac - it just showed a play button that didn't do anything when clicked). I sent the link to a bunch of people and they are all complaining to me that it doesn't work on mobile devices. I just tried from my iPhone (Safari and Chrome) and confirmed that I can't play OR download the video. 

Expected behavior: Videos from public link should play in a mobile browser AND clicking the download link in a mobile browser should download the video to the devices photo album or camera roll.

Actual behavior: Videos from public link cannot be played or downloaded to devices photo albums.

OwnCloud Version tested on: 9.0.2

**Comment by RealRancor** [comment] 2016-06-01 13:14
@dbubs See https://github.com/owncloud/files_videoplayer/issues/45 which gets fixed by https://github.com/owncloud/core/pull/24750 in the upcoming 9.0.3 and 9.1.0

If that doesn't fix your issue its the lack of video support in your browser

**Comment by dbubs** [comment] 2016-06-01 16:42
@RealRancor sounds good! I'll check it out as soon as it's released. Thanks!

**Comment by PVince81** [comment] 2016-06-14 11:47
@dbubs you could try it out with a test 9.1.0beta2 instance and upload your files there.
I'm closing this now. If the problem still exists in this version, please reopen.

**Closed by PVince81** 2016-06-14 11:47 UTC
Labels: enhancement

**Comment by cerberustecnologia** [comment] 2019-02-11 15:20
Por que funciona el chrome y no en mozilla?
Why does chrome work and not in mozilla?

**Comment by PVince81** [comment] 2019-02-11 15:36
likely html5 codec issue ?
