### ISSUE TITLE
After deleting a LDAP user, it is no longer possible to take over his files

### ISSUE THREAD

**Issue by patrakov** [owncloud/core#23757] opened 2016-04-03 11:58 UTC
### Steps to reproduce
1. Create three users in LDAP (baduser, gooduser, thirdparty).
2. Have them put files into ownCloud, and share some files.
3. Delete baduser from LDAP (without thinking that he has shared stuff in owncloud).
4. Attempt to take over the deleted user's files:

 sudo -u www-data php occ files:transfer-ownership -vv baduser gooduser

### Expected behaviour

gooduser becomes the owner of the files that perviously belonged to baduser

### Actual behaviour

```                                       
  [OC\User\NoUserException]            
  baduser is not a valid user anymore  
                                       

Exception trace:
 () at /var/www/owncloud/apps/user_ldap/user_ldap.php:329
 OCA\user_ldap\USER_LDAP->getHome() at /var/www/owncloud/lib/private/user/user.php:251
 OC\User\User->getHome() at /var/www/owncloud/lib/private/user.php:497
 OC_User::getHome() at /var/www/owncloud/lib/private/files/filesystem.php:380
 OC\Files\Filesystem::initMountPoints() at /var/www/owncloud/apps/files/command/transferownership.php:101
 OCA\Files\Command\TransferOwnership->execute() at /var/www/owncloud/3rdparty/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/owncloud/3rdparty/symfony/console/Application.php:840
 Symfony\Component\Console\Application->doRunCommand() at /var/www/owncloud/3rdparty/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/www/owncloud/3rdparty/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/www/owncloud/lib/private/console/application.php:145
 OC\Console\Application->run() at /var/www/owncloud/console.php:88
 require_once() at /var/www/owncloud/occ:11

files:transfer-ownership <source-user> <destination-user>
```

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache (from ppa:ondrej/apache2)

**Database:** MySQL

**PHP version:** 7.0.4 (from ppa:ondrej/php)

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** tarballs

**Signing status (ownCloud 9.0 and above):** what's this?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

    No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_external

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

{
    "system": {
        "instanceid": "oce0e2e83ff5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "loglevel": 1,
        "session_lifetime": 86400,
        "remember_login_cookie_lifetime": 86400,
        "updatechecker": false,
        "knowledgebaseenabled": false,
        "enable_avatars": false,
        "allow_user_to_change_display_name": false,
        "appstoreenabled": false,
        "skeletondirectory": "",
        "forcessl": true,
        "mail_smtpmode": "php",
        "trashbin_retention_obligation": "30, auto",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "theme": "cloud",
        "appstore.experimental.enabled": false
    }
}

**Are you using external storage, if yes which one:** just local files

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (OpenLDAP)

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
```
+-------------------------------+---------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                             |
+-------------------------------+---------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                           |
| hasPagedResultSupport         |                                                                                             |
| homeFolderNamingRule          |                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                           |
| ldapAgentName                 | uid=*****,ou=services,ou=users,dc=*********                                                 |
| ldapAgentPassword             | ***                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                             |
| ldapAttributesForUserSearch   |                                                                                             |
| ldapBackupHost                |                                                                                             |
| ldapBackupPort                |                                                                                             |
| ldapBase                      | dc=*********                                                                                |
| ldapBaseGroups                | dc=*********                                                                                |
| ldapBaseUsers                 | dc=*********                                                                                |
| ldapCacheTTL                  | 600                                                                                         |
| ldapConfigurationActive       | 1                                                                                           |
| ldapDynamicGroupMemberURL     |                                                                                             |
| ldapEmailAttribute            | mail                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                             |
| ldapExpertUsernameAttr        | uid                                                                                         |
| ldapGroupDisplayName          | cn                                                                                          |
| ldapGroupFilter               | (|(cn=all)(cn=coordinators))                                                                |
| ldapGroupFilterGroups         | all;coordinators                                                                            |
| ldapGroupFilterMode           | 1                                                                                           |
| ldapGroupFilterObjectclass    |                                                                                             |
| ldapGroupMemberAssocAttr      | member                                                                                      |
| ldapHost                      | ldap.*********.com                                                                          |
| ldapIgnoreNamingRules         |                                                                                             |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=cloud,ou=groups,dc=*********)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                             |
| ldapLoginFilterEmail          | 0                                                                                           |
| ldapLoginFilterMode           | 1                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                           |
| ldapNestedGroups              | 0                                                                                           |
| ldapOverrideMainServer        | 0                                                                                           |
| ldapPagingSize                | 500                                                                                         |
| ldapPort                      | 389                                                                                         |
| ldapQuotaAttribute            |                                                                                             |
| ldapQuotaDefault              |                                                                                             |
| ldapTLS                       | 0                                                                                           |
| ldapUserDisplayName           | uid                                                                                         |
| ldapUserDisplayName2          |                                                                                             |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=cloud,ou=groups,dc=*********)))              |
| ldapUserFilterGroups          | cloud                                                                                       |
| ldapUserFilterMode            | 0                                                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                        |
| turnOffCertCheck              | 0                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                           |
+-------------------------------+---------------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:** N/A

**Operating system:** N/A

#### Web server error log
```
Insert your webserver log here
```

Too sensitive to show

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

A lot of possibly-related stuff like:

"reqId":"gJ6JboN9s9iuh5Cb6YL1","remoteAddr":"*.*.*.*","app":"webdav","message":"Exception: {\"Message\":\"baduser is not a valid user anymore\",\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/user.php(251): OCA\\\\user_ldap\\\\USER_LDAP->getHome('baduser')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(497): OC\\\\User\\\\User->getHome()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(380): OC_User::getHome('baduser')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(81): OC\\\\Files\\\\Filesystem::initMountPoints('baduser')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(570): OC\\\\Files\\\\Storage\\\\Shared->init()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(381): OC\\\\Files\\\\Storage\\\\Shared->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(124): OC\\\\Files\\\\View->getFileInfo('\\\/gooduser\\\/file...')\\n#8 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":329,\"User\":\"gooduser\"}","level":4,"time":"2016-04-03T11:53:04+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

N/A

**Comment by patrakov** [comment] 2016-04-03 12:15
Reverting the bottom part of https://github.com/owncloud/core/commit/8c7930015644fdd3121dd8399c975b7d15bf40a7 works around the issue

**Comment by nickvergessen** [comment] 2016-04-04 14:19
Duplicate of https://github.com/owncloud/core/issues/23671 and possibly invalid

**Closed by nickvergessen** 2016-04-04 14:19 UTC
