### ISSUE TITLE
Update script did not auto-update 8.1.1 apps when updating from 8.1.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#18043] opened 2015-08-04 05:17 UTC
I had 8.1.0 on openSUSE 13.2 installed from RPMs then upgraded to 8.1.1 from the testing repo.

The upgrade ran on the CLI:
```
(  1/282) Installing: owncloud-server-8.1.1~RC1-13.1 .......................................................................................[done]
Additional rpm output:
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Update successful
Turned off maintenance mode
Maintenance mode disabled


(  2/282) Installing: owncloud-app-activity-8.1.1~RC1-13.1 .................................................................................[done]
(  3/282) Installing: owncloud-app-files_trashbin-8.1.1~RC1-13.1 ...........................................................................[done]
(  4/282) Installing: owncloud-app-files-8.1.1~RC1-13.1 ....................................................................................[done]
(  5/282) Installing: owncloud-app-files_pdfviewer-8.1.1~RC1-13.1 ..........................................................................[done]
(  6/282) Installing: owncloud-app-external-8.1.1~RC1-13.1 .................................................................................[done]
(  7/282) Installing: owncloud-app-user_external-8.1.1~RC1-13.1 ............................................................................[done]
(  8/282) Installing: owncloud-app-gallery-8.1.1~RC1-13.1 ..................................................................................[done]
(  9/282) Installing: owncloud-app-files_sharing-8.1.1~RC1-13.1 ............................................................................[done]
( 10/282) Installing: owncloud-app-firstrunwizard-8.1.1~RC1-13.1 ...........................................................................[done]
( 11/282) Installing: owncloud-app-files_locking-8.1.1~RC1-13.1 ............................................................................[done]
( 12/282) Installing: owncloud-app-encryption-8.1.1~RC1-13.1 ...............................................................................[done]
( 13/282) Installing: owncloud-app-files_texteditor-8.1.1~RC1-13.1 .........................................................................[done]
( 14/282) Installing: owncloud-app-provisioning_api-8.1.1~RC1-13.1 .........................................................................[done]
( 15/282) Installing: owncloud-app-files_videoviewer-8.1.1~RC1-13.1 ........................................................................[done]
( 16/282) Installing: owncloud-3rdparty-8.1.1~RC1-13.1 .....................................................................................[done]
( 17/282) Installing: owncloud-app-user_webdavauth-8.1.1~RC1-13.1 ..........................................................................[done]
( 18/282) Installing: owncloud-app-files_versions-8.1.1~RC1-13.1 ...........................................................................[done]
( 19/282) Installing: owncloud-app-templateeditor-8.1.1~RC1-13.1 ...........................................................................[done]
( 20/282) Installing: owncloud-app-user_ldap-8.1.1~RC1-13.1 ................................................................................[done]
( 21/282) Installing: owncloud-app-files_external-8.1.1~RC1-13.1 ...........................................................................[done]
( 22/282) Installing: owncloud-config-apache-8.1.1~RC1-13.1 ................................................................................[done]
Additional rpm output:
owncloud update: Checking for running Apache
owncloud-config-apache: Upgrade complete
owncloud-config-apache: Reloading
redirecting to systemctl reload apache2.service


( 23/282) Installing: owncloud-8.1.1~RC1-13.1 ..............................................................................................[done]

```

But after accessing the web UI I noticed that an upgrade was still due.
Both version.php and config.php had the same version so I ran the upgrade again manually on the CLI:
```
vincent-server:/srv/www/htdocs/owncloud # sudo -uwwwrun ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating <files> ...
Updated <files> to 1.1.10
Update successful
Turned off maintenance mode
```

So here it seems that the reason for the pending update was due to the files app.

Why didn't this happen together with the first call ?

Not directly a packaging issue but possible an issue with the upgrade process.
Setting to sev3-medium as there is an easy workaround.

@DeepDiver1975 @MorrisJobke @schiesbn @nickvergessen

**Comment by MorrisJobke** [comment] 2015-08-04 09:26
> Not directly a packaging issue but possible an issue with the upgrade process.
> Setting to sev3-medium as there is an easy workaround.

Because the occ upgrade runs in step 1 and the new code of the files app was added in step `4/282`

I still don't like that the packages call the `occ upgrade` command ... it's not designed to be an unattended upgrade command.

**Comment by DeepDiver1975** [comment] 2015-08-04 09:28
This is an issue with the packages @jnweiger

**Comment by DeepDiver1975** [comment] 2015-08-04 09:29
> Because the occ upgrade runs in step 1 and the new code of the files app was added in step 4/282

Absolutely the right analysis - best would be to execute occ upgradde after all packages have been updated - kind of tricky .... @jnweiger

**Comment by jnweiger** [comment] 2015-08-04 16:30
Submitted a possible fix for RPM: Confirmed with SUSE, that PreReq is the correct way to assert that all dependencies are in, *before* the %post is run.
https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.1:testing/owncloud?linkrev=base&rev=6
Todo: needs testing after the packages built.
Todo: review DEB if this has the same issue. Rumor has it, that DEB runs all their postinstall scripts at the very end. (But I've also seen that claim for RPM.)

**Comment by jnweiger** [comment] 2015-08-05 17:45
The fix is not possible. In OBS, PreReq is always interpreted as a build time dependency. This behaviour disagrees with the documented behaviour "Like Requires, but asserts that the dependency is installed before running pre or post scriptlets".

Interpreted as build time dependencies, they are unresolvable circular dependencies,  as they all come from the same specfile.
There are several other forms Requires(pre,preun), Requires(post), they all have the same issue.

Ideas welcome, how to run a scriptlet after installing 'a package and its dependencies'.

**Comment by jnweiger** [comment] 2015-08-06 12:41
As discussed with SUSE, there is no proper solution for this in the Build Service. PreReq cannot be used. %posttrans was mentioned, but not suggested due to other isuses.

I am working on merging all community apps into the owncloud-server package. The split is no longer necessary since calender and contacts are gone, and all other community app are also supported as enterprise apps. This solves the issue of dependencies being installed too late, by no longer having dependecies.

**Comment by jnweiger** [comment] 2015-08-07 15:58
Merging app-packages back into the owncloud-server package was smooth. 
The code is ready for testing in https://build.opensuse.org/package/show/isv:ownCloud:community:8.1:testing:merged/owncloud 
It survives basic install tests. Not to be used for 8.1.1 -- as the changes are intrusive, and we have no time for testing.

For now, we special case the files-app with an additional call to occ upgrade. 
This is the suggested candidate for 8.1.1:
https://build.opensuse.org/package/rdiff/isv:ownCloud:community:8.1:testing/owncloud?linkrev=base&rev=29

**Comment by jnweiger** [comment] 2015-08-07 20:28
openSUSE-13.2 having 8.1.0 installed:

<pre>
zypper --gpg-auto-import-keys addrepo http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1:/testing/openSUSE_13.2/isv:ownCloud:community:8.1:testing.repo
zypper install owncloud
</pre>

<pre>
...
Checking for file conflicts: .............................................................................................................................[done]
( 1/23) Installing: owncloud-server-8.1.1~RC1-38.1 .......................................................................................................[done]
Additional rpm output:
owncloud-server: Upgrade starting
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
owncloud-server Upgrade complete
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Update successful
Turned off maintenance mode
&lt;warning>The setting "trusted_domains" could not be set automatically by the upgrade script, please set it manually&lt;/warning>Maintenance mode disabled


( 2/23) Installing: owncloud-app-activity-8.1.1~RC1-38.1 .....................
( 3/23) Installing: owncloud-app-files_trashbin-8.1.1~RC1-38.1 ...........................................................................................[done]
( 4/23) Installing: owncloud-app-files-8.1.1~RC1-38.1 ....................................................................................................[done]
Additional rpm output:
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Maintenance mode disabled
owncloud-server: occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updating &lt;files> ...
Updated &lt;files> to 1.1.10
Update successful
Turned off maintenance mode
&lt;warning>The setting "trusted_domains" could not be set automatically by the upgrade script, please set it manually&lt;/warning>Maintenance mode disabled

( 5/23) Installing: owncloud-app-files_pdfviewer-8.1.1~RC1-38.1 ...
...
</pre>

We now run occ upgrade twice. 
This is safe, but not a good solution, as users may be surprised by the unexpected delay. It takes ca 15 seconds on an almost empty owncloud each time occ upgrade is run, with no visible progress.

**Comment by MorrisJobke** [comment] 2015-08-07 21:34
> It takes ca 15 seconds on an almost empty owncloud each time occ upgrade is run, with no visible progress.

There is something fishy then. On my PC an empty upgrade takes only 1-2 seconds.

**Comment by MorrisJobke** [comment] 2015-08-07 21:35
> empty upgrade

Only version number increase of an app.

**Comment by jnweiger** [comment] 2015-08-10 15:28
For 8.1.1 the solution is to run occ upgrade twice. For 8.1.x later, this should become a non-issue, using a merged owncloud-server package with apps included.

considered fixed.

**Closed by jnweiger** 2015-08-10 15:28 UTC
Labels: bug, packaging, sev3-medium

**Comment by wolfgangkarall** [comment] 2015-09-16 04:19
Now the fix "Merged all *-apps-* packages into owncloud-server" has hit Ubuntu, this will probably scare users:

```
The following packages will be REMOVED:
  libav-tools* owncloud-3rdparty* owncloud-app-activity*
  owncloud-app-encryption* owncloud-app-external* owncloud-app-files*
  owncloud-app-files-external* owncloud-app-files-locking*
  owncloud-app-files-pdfviewer* owncloud-app-files-sharing*
  owncloud-app-files-texteditor* owncloud-app-files-trashbin*
  owncloud-app-files-versions* owncloud-app-files-videoviewer*
  owncloud-app-firstrunwizard* owncloud-app-gallery*
  owncloud-app-provisioning-api* owncloud-app-templateeditor*
  owncloud-app-user-external* owncloud-app-user-ldap*
  owncloud-app-user-webdavauth* php5-imagick*
The following NEW packages will be installed:
  php5-ldap
The following packages will be upgraded:
  owncloud owncloud-config-apache owncloud-server
3 upgraded, 1 newly installed, 22 to remove and 0 not upgraded.
Need to get 0 B/23.7 MB of archives.
After this operation, 456 kB disk space will be freed.
```

Empty transitional packages for the *-apps-* packages would've been great, but I guess it's now too late.
