### ISSUE TITLE
Shared files with users existing before encryption cannot be decrypted by sharee

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16264] opened 2015-05-12 08:11 UTC
### Steps to reproduce

1. Create user1
2. Enable encryption app.
3. Enable encryption module in admin page.
4. Relogin.
5. Upload a file as admin.
6. Share it with user1.
7. Login with user1 (Relogin it a warning message request it).
8. Open with user1 the file shared by admin.

### Expected behaviour
user1 can open file.

### Actual behaviour
user1 can't decrypt file.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
Encryption.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes

**Logs**
```
```
### Client configuration

**browser**
Chrome 41

**Comment by schiesbn** [comment] 2015-05-12 11:13
Will be fixed with a error message here: https://github.com/owncloud/core/pull/16243

**Comment by PVince81** [comment] 2015-05-18 09:44
Actually this ticket is a duplicate of https://github.com/owncloud/core/issues/15981

**Comment by SergioBertolinSG** [comment] 2015-05-20 11:28
Tested in 8.1.0.6, the error message is not enough clarifying. 
This error message is not well shown in chrome. In firefox it's just too simple.

Chrome message:
![screen shot 2015-05-20 at 13 20 26](https://cloud.githubusercontent.com/assets/9048796/7724626/6eb6e260-fef3-11e4-8ab2-db7d81398504.png)

Firefox message:
![screen shot 2015-05-20 at 13 25 34](https://cloud.githubusercontent.com/assets/9048796/7724656/b88af336-fef3-11e4-9d0c-6aeb328cb13c.png)


I don't think this is a dup of #15981. It is related, but this is a specific situation which has to be correctly handled.

**Comment by schiesbn** [comment] 2015-05-21 12:51
I don't know how you generated the screenshots. The error message should look like this:

![1](https://cloud.githubusercontent.com/assets/1589737/7748875/dfbf4ec2-ffc8-11e4-8372-91caf11c31a6.png)

**Comment by schiesbn** [comment] 2015-05-21 12:52
@SergioBertolinSG can you please try again with current master? Thanks!

**Comment by SergioBertolinSG** [comment] 2015-05-21 14:16
Maybe it is a problem with the enterprise theme.

**Comment by SergioBertolinSG** [comment] 2015-05-25 10:58
Tested with last master branch (2015-05-25). Same behaviour.

![screen shot 2015-05-25 at 12 57 21](https://cloud.githubusercontent.com/assets/9048796/7796256/b3b7c7e2-02dd-11e5-9646-91135562aca8.png)

**Comment by schiesbn** [comment] 2015-05-26 08:15
Tried it again with the enterprise theme and this state of owncloud: 6198fb20cb20af2c9192a470f6cb2be4c43721ad

This is the error message I get:

![1](https://cloud.githubusercontent.com/assets/1589737/7807960/c160936c-038f-11e5-85b6-6606a3f782d6.png)

I followed exactly your steps. Maybe you can add more details to your last step:

> Open the shared file by admin.

First I assume that you meant "user1" and not admin, right. The admin is the owner and you shared the file with user1 and logged-in as user1 in step 7. In step I clicked on the "download" link. Did you do the same? Or did you clicked directly on the file name and tried to open it with a internal viewer (image viewer, text teditor,...) ?

**Comment by SergioBertolinSG** [comment] 2015-05-26 09:37
Yes I meant 'Open with user1 the file shared by admin' sorry for confusion.

I tried to open the file with text editor.

**Comment by schiesbn** [comment] 2015-05-26 11:35
ok, this might explain it. Try to click on the download link instead, this should lead to the error page I showed above.

For the text editor you need this PR to be able to display errors correctly: https://github.com/owncloud/files_texteditor/pull/72

**Comment by DeepDiver1975** [comment] 2015-06-02 11:56
@SergioBertolinSG can you please test owncloud/files_texteditor#72 - THX

**Comment by DeepDiver1975** [comment] 2015-06-05 10:04
@SergioBertolinSG @jnfrmarks owncloud/files_texteditor#72 is merged now - please retest - THX

**Comment by SergioBertolinSG** [comment] 2015-06-08 11:55
Tested in master
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}
Not working. user1 opens the file shared by admin and it is empty. There is no error, just the file shared, and when opening it is empty.

**Comment by DeepDiver1975** [comment] 2015-06-08 11:58
@SergioBertolinSG is owncloud/files_testedito#72 in beta2 - if not it is pointless to test beta2

**Comment by schiesbn** [comment] 2015-06-08 12:32
Just tested it @SergioBertolinSG is right, it was broken here: https://github.com/owncloud/files_texteditor/pull/77/files We now always follow the success path... I will look into it.

**Comment by SergioBertolinSG** [comment] 2015-06-08 12:53
@DeepDiver1975 I tested on daily master, not the beta2 tarball. It has "8.1 beta 2" name as well.

**Comment by schiesbn** [comment] 2015-06-08 18:13
Should work now with the latest master and https://github.com/owncloud/files_texteditor/pull/79

**Comment by davitol** [comment] 2015-06-10 08:30
:+1: fixed with https://github.com/owncloud/files_texteditor/pull/79

**Closed** 2015-06-10 08:42 UTC
Labels: 3 - To Review, app:encryption, approved by qa, bug, sev2-high, sharing
