### ISSUE TITLE
Files list on iOS 8 devices jiggles or hangs unscollable while scrolling up/down

### ISSUE THREAD

**Issue by finius** [owncloud/core#15556] opened 2015-04-12 15:41 UTC
since oc8 the problem is that the main file/folder list is now nearly unscrollable on iOS 8 devices like iPhone 6 and iPad Air. Issue hasn't existed in oc7. When trying to scroll down the menu on the left slides out and the files list either moves jerky or seems to hang motionless.
It's no Safari issue because in Chrome it doesn't work either. It maybe is in relation to the issue https://github.com/owncloud/core/issues/14639 concerning the unfunctional menue bar on iOS devices in oc7 which had been fixed in oc8. see:

**Comment by karlitschek** [comment] 2015-04-12 20:21
@jancborchardt What do you think?

**Comment by jancborchardt** [comment] 2015-04-13 08:38
(I rather think this is related to https://github.com/owncloud/core/issues/11193)

**Comment by jancborchardt** [comment] 2015-05-01 22:43
@finius can you track down the commit with which this started to happen? That would be massively helpful! :)

**Comment by finius** [comment] 2015-05-02 09:08
@jancborchardt sorry? if the question is since when the file/folder list started to be unscollable on iOs devices, the answer is "since the upgrade to ownCloud 8"

**Comment by jancborchardt** [comment] 2015-07-20 20:47
Closing as duplicate of https://github.com/owncloud/core/issues/11193 – let’s continue there.

**Closed by jancborchardt** 2015-07-20 20:47 UTC
Labels: bug, design, needs info, regression
