### ISSUE TITLE
Can't change user's timezone. It's always set to 'Europe/Helsinki'

### ISSUE THREAD

**Issue by mtzanidakis** [owncloud/core#22523] opened 2016-02-19 13:01 UTC
Hi there,
I've noticed a weird thing on a fresh 8.2.2 installation. All users have the timezone set to 'Europe/Helsinki' in the database, on all apps.

I've tried to manually change the timezone in the 'core' appid in the 'oc_preferences' table, but after logging in as that user, the timezone is changed back to 'Europe/Helsinki', automatically. Is there a way to change the user's timezone from the web interface?

My php.ini was already set to 'date.timezone = Europe/Athens', prior to the installation of ownCloud, but it has no effect on that, whatsoever.

A small note about my setup, although I'm not sure it's relevant to my problem. Nginx & PHP run in a chroot in /var/www (the default setup in OpenBSD). The correct localtime file for my timezone is created in /var/www/etc/localtime and is accessible inside the chroot; at least other applications I run on the same server work without problems.

### Steps to reproduce
1. Change user timezone in oc_preferences table.
2. Log in as that user.
3. timezone is set back to 'Europe/Helsinki' in the db.

### Server configuration
Operating system: OpenBSD 5.9 (-current snapshot)

Web server: nginx 1.9.10

Database: MariaDB 10.0.23

PHP version: 5.6.18

ownCloud version: 8.2.2

Updated from an older ownCloud or fresh install: fresh

**Comment by LukasReschke** [comment] 2016-02-19 19:23
If you go to the login screen, open the developer console and execute:

```
jstz.determine().name()
```

What is the output? - I assume `Europe/Helsinki`? [This script does no geolocation and only finds the correct timezone](http://pellepim.bitbucket.org/jstz/). Since Helsinki and in Athens is both in the same timezone this is reported. Closing as potential expected behaviour. There is no way for an user to change the timezone manually at the moment. (but it's also not displayed to users in core somwhere from what I can tell)

<hr/>
![2016-02-19_20-19-11](https://cloud.githubusercontent.com/assets/878997/13186354/2d1c95da-d746-11e5-97e4-4d475cab0b79.png)

**Closed by LukasReschke** 2016-02-19 19:23 UTC

**Comment by mtzanidakis** [comment] 2016-02-21 22:11
Thanks for clearing this up, Lukas.
