### ISSUE TITLE
Deadlock detected by pdo and cron fails with uncaught exception

### ISSUE THREAD

**Issue by gig13** [owncloud/core#20226] opened 2015-11-02 14:24 UTC
### Steps to reproduce
1. Trying to reproduce

### Expected behaviour
There should not be any deadlock detected by pdo. The cron should also not fail due to an uncaught exception (caused by this deadlock in this case)

### Actual behaviour
We had the cron job report this today. It seems that there is a deadlock reported by pdo when trying to perform a query. We have a galera cluster behind an haproxy load balancer. So queries go to all three nodes. It appears that a query on one node had a lock when the cron job wanted it.

### Server configuration
**Operating system**: RHEL

**Web server:** Apache

**Database:** Galera cluster

**Load Balancer:** HAProxy - queries go through all nodes

**PHP version:** 5.5.29

**ownCloud version:** 8.1.3

**Updated from an older ownCloud or fresh install:**  Updated

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### ownCloud log (data/owncloud.log)
```
PHP Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction' in /var/www/html/owncloud-enterprise/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/html/owncloud-enterprise/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
#1 /var/www/html/owncloud-enterprise/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(165): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
#2 /var/www/html/owncloud-enterprise/lib/private/db/statementwrapper.php(73): Doctrine\DBAL\Statement->execute(Array)
#3 /var/www/html/owncloud-enterprise/lib/private/db.php(147): OC_DB_StatementWrapper->execute(Array)
#4 /var/www/html/owncloud-enterprise/lib/private/files/cache/cache.php(364): OC_DB::executeAudited('UPDATE `*PREFIX...', Array)
#5 /var/www/html/owncloud-enterprise/lib/private/files/cache/changepropagator.php(79): OC\Files\Cache\Cache->updat in /var/www/html/owncloud-enterprise/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

**Comment by gig13** [comment] 2015-11-02 14:39
@MorrisJobke

**Comment by gig13** [comment] 2015-11-02 14:45
I've read that this can happen when the same columns are referred to in different orders between two queries. Eg, referring to col1 and col2 in that order in one UPDATE query and col2 and col1 in another. The first query will get a lock on col1 at the same time the second query gets a lock on col2. Then each query blocks the other from getting a lock on the remaining column, hence the deadlock. If they both request the same column at the same time (ie they are listed in the same order), the first one gets the lock and the second one waits until the first query releases the lock rather than obtain a lock on the next column.

**Comment by MorrisJobke** [comment] 2015-11-02 14:47
@icewind1991 Change propagator.

**Comment by gig13** [comment] 2015-11-12 13:59
@MorrisJobke @icewind1991 @bboule 
Is this targeted for any release? Do you need additional information?

The cron is run on each web server. One server is scheduled for 00 and 30 minutes past the hour and the other is 15 and 45. We've specified in config.php for the path for the cron lock file to be in our data directory. That's shared between both servers by smb so one can see if the other has a cron job still running (eg long running activity clean up or something). Our smb share does support locking and I've tested to confirm that cron will only run one at at time. So it's not a case of two cron jobs causing the deadlock.

**Comment by icewind1991** [comment] 2015-11-12 14:03
This might be fixed with 8.2 with locking

**Comment by gig13** [comment] 2015-11-12 14:08
@icewind1991 
Might be? Do we have anything more definitive? Do you have any insight as to why this is happening and are there any workarounds for existing users?

Just to confirm you mean using Redis and https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html

**Comment by icewind1991** [comment] 2015-11-12 14:14
I can't say anything more decisive without having more information about how to reproduce the issue.
This sounds like simular issues that were fixed by locking but atm there is to little info to really know.

> Just to confirm you mean using Redis and https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/files_locking_transactional.html

transactional locking yes, it's enabled by default for 8.2 and while redis is not required it's recommended

**Comment by gig13** [comment] 2015-11-12 14:32
@icewind1991 
Understood, the issue does not have concrete reproduction steps. Is there any other information that you need for debugging further?

report config file is at https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F20226

**Comment by icewind1991** [comment] 2015-11-12 14:56
As far as I can tell this is a concurency issues which would be solved by locking

Unless we there are proper reproduction steps we can't go any further as "propably solved by locking"

**Comment by nickvergessen** [comment] 2015-11-17 10:36
Duplicate of #20555 ?

**Comment by MorrisJobke** [comment] 2015-11-17 14:01
> Duplicate of #20555 ?

cc @LukasReschke

**Comment by LukasReschke** [comment] 2015-11-17 14:03
> #4 /var/www/html/owncloud-enterprise/lib/private/files/cache/cache.php(364): OC_DB::executeAudited('UPDATE `*PREFIX...', Array)

Seems like an update statement? #20555 is more about INSERT IF NOT EXISTS.

cc @icewind1991

**Comment by bboule** [comment] 2016-01-06 17:06
@felixboehm could I ask you to care for this from gcx?

**Comment by MorrisJobke** [comment] 2016-01-06 19:30
The planned way of fixing this is by using the transactional file locking in 8.2+ (together with redis). The upgrade was planned for Dec/early January. So this can be closed from a GCX point of view.

**Closed by MorrisJobke** 2016-01-06 19:30 UTC
Labels: blue-ticket, bug, in progress, needs info
