### ISSUE TITLE
Problem with upgrade to 8.0.4

### ISSUE THREAD

**Issue by baladino** [owncloud/core#18026] opened 2015-08-03 07:23 UTC
Hello, 

I tried to upgrade to 8.0.4 and I encountered one problem:
"An exception occurred while executing 'CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash)': SQLSTATE[23000]: Integrity constraint violation: 19 indexed columns are not unique"
Now, when i try to log in, I always find the upgrade window.

Can anyone help me to resolve this problem.

Thanks in advance,

Tom from Paris but in Africa for a while ;-)

**Comment by Kawohl** [comment] 2015-08-03 08:15
Hey Tom, 

could you please use the issue template. This helps us to reproduce this issue and to find out what is actually wrong. You find the issue template here. Just copy and paste. ;-)

**Comment by baladino** [comment] 2015-08-03 08:20
Hello Kawohl,
The link ti issue template is broken ;-)

Thanks for your so quick answer.

Regards,
tom

**Comment by Kawohl** [comment] 2015-08-03 08:29
https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Sorry my mistake.

**Comment by MorrisJobke** [comment] 2015-08-03 08:47
Weird. This index wasn't added in 8.0.4 but exists sine ownCloud 5.0.0: https://github.com/owncloud/core/blob/v5.0.0/db_structure.xml#L296-L307

@DeepDiver1975 Yet another hard to debug issue, because the migration schema diff is created on demand.

**Comment by MorrisJobke** [comment] 2015-08-03 08:53
Maybe following: #2566 (https://github.com/owncloud/core/issues/2566#issuecomment-64780077 for even more related tickets)

Maybe this occurs on index generation because the duplicate entries are already present before the index.

On the other side: the fix for this was added to 8.0.3 #14665

Maybe @PVince81 knows anything related to this :)

**Comment by PVince81** [comment] 2015-08-21 11:20
Hmm not sure. It is likely that the table already contained duplicate entries before the index was created.

What I find strange is that this index seems to exist already since OC 5.

@baladino please use the issue template and make sure to not skip versions when updating.

**Comment by Kawohl** [comment] 2015-10-08 10:36
I'll close since no reaction since two months.

**Closed by Kawohl** 2015-10-08 10:36 UTC
Labels: needs info, update
