### ISSUE TITLE
Extremely slow browser response with the LDAP app inside a VPN

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#15930] opened 2015-04-29 11:55 UTC
### Steps to reproduce
1. Setup two different LDAP configurations, (checked with a LDAP server inside a LAN and another one inside an external VPN)
2. Check that both of them are accessible inside the VPN
3. Exit from the VPN. You should still be able to connect to the LDAP server in the LAN.
4. From the LDAP wizard, deactivate the configuration for the LDAP server in the VPN, so only the one inside the LAN is active.
5. Switch to the user page

### Expected behaviour
The use page is loaded in an acceptable amount of time (less than 10 seconds?)

### Actual behaviour
The user page take too much time to load (more than 1 minute 40 seconds)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 alpha 2

**Updated from an older ownCloud or fresh install:** fresh install

### Notes
I have a hunch that the PHP session could be opened while the connection to the LDAP inside the VPN is being tested. This might be blocking the page load of the user page (en probably others) until the connection test times out

**Comment by jvillafanez** [comment] 2015-04-29 11:56
@blizzz

**Comment by jvillafanez** [comment] 2015-04-30 11:23
Something similar happens switching to other configuration, same symptoms :

1. Having two configurations, one of them taking some time to respond, perform some operation over the LDAP (such as count the number of users or groups)
2. Before the operation finish, go to the server tab and switch the server configuration to another one

The previous server configuration stays for a while (until the previous operation finish) before switching to the selected one

**Comment by blizzz** [comment] 2015-05-05 14:24
Do you see it only with 8.1 or also earlier releases?

**Comment by jnfrmarks** [comment] 2015-05-05 15:05
@jvillafanez

**Comment by jvillafanez** [comment] 2015-05-06 12:45
I've checked also with 8.0.3 with the same behaviour

**Comment by Yamakasi** [comment] 2015-05-06 15:14
Same here on 8.0.3.

Can we apply some fix or rollback to an earlier version ?

**Comment by DeepDiver1975** [comment] 2015-10-06 08:17
@karlitschek @cmonteroluque 

I guess this requires in depth analysis on the explicit setup - @blizzz has hard time to reproduce this.

In addition this might require more of an admin task to find the bottleneck - maybe @danimo can help out. No idea to be honest.

**Comment by cmonteroluque** [comment] 2015-10-06 12:31
@jvillafanez can you help @blizzz with the setup?

**Comment by blizzz** [comment] 2015-10-06 16:08
Okay, after recapitulating: a configuration is being disabled while an LDAP operation is in progress. 

The reality is: the operation needs to be finished by PHP. There is no way we can safely cancel a running PHP  process from another one. So this will be going on until our PHP script (and the LDAP server) are doing what was requested. These are all synchronous calls. The only way to restart this is restarting the web server (and possibly the LDAP server).

**Comment by MorrisJobke** [comment] 2015-10-12 14:08
What to do here? It's not really in our hand to fix this properly, or am I wrong?

**Comment by cmonteroluque** [comment] 2015-10-13 11:14
We'd need to rethink this in terms of asynchronous calls. Not happening for 8.2, moving to 9.0 for some re-thinking

**Comment by blizzz** [comment] 2016-02-24 15:34
Still don't really know how to fix this, if at all possible. LDAP requests cannot be done asynchronously. Spawning other PHP processes? Won't help much – why need to have the channel back to the user. Next to management overhead.

Setting the LDAP_OPT_TIMELIMIT option to a low value does not help in normal operation, rather the opposite, because we try to fulfill requests (limit), and do not return back fewer values if there are more available. Thus, effects are not that big in the wizard, but either it is already optimized and operation do not take long, or the same applies as above (e.g. reading groups basically).

That said, the only way is to try to be a economic as possible with LDAP requests, as a general matter.

**Comment by cmonteroluque** [comment] 2016-02-24 16:15
moving it to 9.1

**Comment by danimo** [comment] 2016-02-24 16:46
Since I keep getting pinged on this:

Do I understand correctly that the title is a misnomer, unrelated to VPN, and should actually be "ownCloud unresponsive if an LDAP server disappears while a query is running directed towards it"?

**Comment by blizzz** [comment] 2016-02-24 23:02
@danimo yes and no, see https://github.com/owncloud/core/issues/15930#issuecomment-145913317

**Comment by jvillafanez** [comment] 2016-03-02 13:55
To give an example:

Let's say we have two files, slow_write.php and slow_read.php

slow_write:
```
<?php
session_start();
$_SESSION['FOO'] = date('c');
# session_write_close();
sleep(20);
```

slow_read:
```
<?php
session_start();
print_r($_SESSION['FOO']);
```

First you load the slow_write.php page, and after 20 seconds load the slow_read.php. The load time of the slow_read is immediate under normal circumstances.

However, if you load first the slow_write.php you won't be able to load the slow_read.php page until the first page finish (20 seconds).

If you uncomment the "session_write_close" call in the slow_write.php you can load the slow_read.php immediately without waiting the 20 seconds for the slow_write.php page to finish.

I'm not sure if this can be done within ownCloud. It's possible to close the session but you won't be able to write in it, so closing the session in the middle of a request could be dangerous if the code to be run isn't yours (the code could need to read or write in the session). It should be fine for testing connectivity to the LDAP server though because the code should be isolated.

To be a bit more clear, in any case the sleep (or the long synchronous process) won't be stopped, but it won't block the next requests.

**Comment by PVince81** [comment] 2016-06-15 11:26
@butonic do you have an idea ?

**Closed** 2016-07-26 13:56 UTC
Labels: app:user_ldap, bug, sev2-high
