### ISSUE TITLE
Deprecate usage of OC::CLASSPATH - we should use proper naming to enable autoloader

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#11003] opened 2014-09-11 06:06 UTC

**Comment by PVince81** [comment] 2015-01-14 16:51
Seems to be the only two apps still using it in core:
- [ ] files_external
- [ ] files_sharing

**Comment by MorrisJobke** [comment] 2016-01-19 00:36
Duplicate of https://github.com/owncloud/core/issues/12573

**Closed by MorrisJobke** 2016-01-19 00:36 UTC
Labels: app:files_external, enhancement, feature:sharing, technical debt
