### ISSUE TITLE
Admins can't edit mails of users if `allow_user_to_change_display_name` is set to false

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#14127] opened 2015-02-11 22:49 UTC
Had a little chat with @enoch85 and he couldn't change the mail of users even as admin. Turned out that he had `allow_user_to_change_display_name` set to false and from the code logic admins can't change the users email then.

We either need to allow it for admins or hide those settings in the UI.

**Comment by LukasReschke** [comment] 2015-02-11 22:49
@MorrisJobke FYI

**Comment by LukasReschke** [comment] 2015-02-11 22:52
Or the error should make the reason more clear

**Comment by enoch85** [comment] 2015-02-11 22:56
No error in owncloud.log either. Not even in debug mode.

**Comment by enoch85** [comment] 2015-02-11 23:08
The logged in users can't change their email either, they are prompted with the same error "can't change email".

**Comment by snake2903** [comment] 2015-02-12 06:08
I also have allow_user_to_change_display_name set to false and can't change e-mail address as admin. After seting to true, i can change email address as admin.

**Comment by MorrisJobke** [comment] 2015-02-12 08:21
-.- This is because usually the "can change" permission is fetched from the backend (because there are read-only backends out there). It seems that this setting overwrites this functionality.

**Comment by DeepDiver1975** [comment] 2015-02-16 15:39
not really critical -> 8.1

**Comment by karlitschek** [comment] 2015-05-04 18:21
@georgehrke In the mood for a nice junior job? :-)

**Comment by PVince81** [comment] 2015-09-21 14:30
fix is here https://github.com/owncloud/core/issues/19053

**Comment by MorrisJobke** [comment] 2015-09-23 13:53
@DeepDiver1975 requested to postpone this to 9.0 https://github.com/owncloud/core/pull/19053#discussion_r40074520

**Comment by cmonteroluque** [comment] 2015-10-01 17:57
ok

**Comment by colomailbe** [comment] 2016-02-03 10:11
'allow_user_to_change_display_name' => true,
Still block user and admin to change email (and is therefore useless).

This setting is essential and was postponed since a very long time, was hoping some changes with new milestone, but no chance. Is there still any plan to fix it? Any timeline? Thanks!

**Comment by PVince81** [comment] 2016-02-25 16:39
We now have two conflicting PRs:
- from @georgehrke https://github.com/owncloud/core/pull/19053
- from @nickvergessen https://github.com/owncloud/core/pull/22610

Both require API changes which is bad after feature freeze...

**Comment by cmonteroluque** [comment] 2016-02-26 20:37
https://github.com/owncloud/core/pull/22669 minimal fix merged. Moving rest to 9.1

**Comment by PVince81** [comment] 2016-06-07 15:38
Okay, so the two PRs got closed.

What approach should we use for this then ? Does the minimal fix cover enough of the requirements ?
What's the next step for the rest ?

**Comment by DeepDiver1975** [comment] 2016-08-29 17:25
the current behavior works as designed -> 9.2 will bring the user account table and any property can the be changed -> close

**Closed by DeepDiver1975** 2016-08-29 17:25 UTC
Labels: bug, in progress, settings:users, sev2-high
