### ISSUE TITLE
Meta data missing the username when querying for an ldap user via the provisioning api

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#15084] opened 2015-03-20 17:50 UTC
### Steps to reproduce

1. Install owncloud
2. configure ldap 
3. query for an ldap user using the provisioning api

### Expected behaviour

Expect all data to be returned

### Actual behaviour

The "Users" field is missing the username

```
jennifer@ubuntu-14-client:~/smash-box/lib/oc-tests$ curl http://<user>:<pw>@x.x.x.x/owncloud/ocs/v1.php/cloud/users
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <users>
   <element>aaliyah_oconnell_II</element>
   <element>abagail_kuhic</element>
   <element>abagail_kuhlman_III</element>
   <element>abagail_runolfsdottir</element>
   <element>at_admin</element>
   <element>user1</element>
   <element>user2</element>
   <element>user3</element>
  </users>
 </data>
</ocs>
jennifer@ubuntu-14-client:~/smash-box/lib/oc-tests$ curl http://<user>:<pw>@x.x.x.x/owncloud/ocs/v1.php/cloud/users?search=user1
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <users>
   <element>user1</element>
  </users>
 </data>
</ocs>
jennifer@ubuntu-14-client:~/smash-box/lib/oc-tests$ curl http://<user>:<pw>@x.x.x.x/owncloud/ocs/v1.php/cloud/users?search=abagail_kuhic
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <users/>               
 </data>
</ocs>
jennifer@ubuntu-14-client:~/smas-hbox/lib/oc-tests$


```

### Server configuration

Ubuntu 14.04
PHP 5.5.9
MySQL DB

ownCloud Enterprise Edition 8.1 pre alpha (daily) Build:2015-03-19T03:27:00+00:00 fe8002a7db0ccfec3a96def4f889c265b52ace53

**Comment by jnfrmarks** [comment] 2015-03-26 10:54
LDAP users can have a space in their names; ownCloud does not support spaces in usernames so the space gets converted to an underscore. When we search for the ldap user with a space in the name, we need to remove the underscore to find the user.  

I have validated that this works now as expected; closing this as not an issue

**Comment by jnfrmarks** [comment] 2015-03-26 12:54
@PVince81 

In discussing my solution with Vincent, he had some feedback/questions on the solution so I am reopening this.

**Comment by PVince81** [comment] 2015-03-26 12:56
From what I understood the problem is about user names that have spaces in them.

As an API consumer, I should be able to pass a user name with space to the "search" argument and get the correct results. So we need to put a fix/workaround either in the provisioning API, or fix the LDAP search code properly retrieve such users (or do the "iterate over the list" workaround there).

**Comment by PVince81** [comment] 2015-03-26 12:56
@blizzz what do you think ?

**Comment by PVince81** [comment] 2015-03-26 12:57
Here was the workaround proposed by @jnfrmarks in pyocclient https://github.com/owncloud/pyocclient/pull/85 but I think it's not the right place to do it. (but that code illustrates a possible workaround that we could put in the server code)

**Comment by PVince81** [comment] 2015-03-27 14:07
@tomneedham

**Comment by blizzz** [comment] 2015-03-30 11:15
Spaces in user names (and other characters) are not allowed. 

The issue here is that the configured LDAP attribute, that user names are derived from, contains those. However, you cannot rely that the attribute value will be exactly the user name. Forbidden characters are one thing, name collisions the other (a string will be added).  You should not do any assumptions upon the username.

I would rather say that you replace the underscores  before doing the search, or to look for the exact attribute value. The downside there is that if many search terms are provided (seperated by underscores) this is split up and compared individually against the search attributes. The purpose was to allow a flexible search against first and last names without knowledge about  the internal structure of LDAP attribute values. This may very well turn out in many results in this case.

Frankly speaking, using the display name is a bad way to use as internal username attribute,  because it often is user changeable and thus not necessarily unique. I understand the general purpose here is having a test setup, but it is probably better to revise the setup  and use uid/samaccountname for the internal username. Theoretically, white spaces are allowed there as well, but they should be avoided. As this is what you usually login against, whitespaces and special characters are practically not used.

**Comment by PVince81** [comment] 2015-09-21 14:59
@blizzz how to move forward ?

**Comment by blizzz** [comment] 2015-09-22 10:52
Actually it's about the usage. You need to know the username if you want to modify one. First step should be to determine it by using users/getusers call and providing a search term. LDAP user search attributes should be configured to include an identifying attribute (uid/samaccountname) which you would pass as search term. There's a hidden trap, when possible values may show up in other attributes that are included in the user search attributes, so admin needs to be a bit careful about it.  But then, you'll know the username and can operate normally.  I don't see anything to fix here. An addition however could be to add an LDAP specific call for the provisioning API to return an ownCloud username for a provided login name to make it more specific and ensure not to fall into the beforementioned trap.

**Comment by cmonteroluque** [comment] 2015-09-25 21:27
@blizzz adding the LDAP call seems right

**Comment by PVince81** [comment] 2015-09-29 08:53
Please evaluate severity

**Comment by blizzz** [comment] 2015-10-02 21:12
@cmonteroluque please leave a comment when changing severity towards high (or critical) so close to the deadline in order to have us notified and able to plan accordingly…

**Comment by cmonteroluque** [comment] 2015-10-05 20:02
@blizzz sure thing. I think this issue should be fixed. Your proposal from 13 days ago makes sense and it should happen within the focus on the provisioning API. Fair comment, I will do that going forward

**Comment by blizzz** [comment] 2015-10-06 11:43
Fix is here: https://github.com/owncloud/core/pull/19600

**Comment by MorrisJobke** [comment] 2015-10-13 08:57
The fixing PR was moved to 9.0 https://github.com/owncloud/core/pull/19600#issuecomment-147396716

Moving this too

**Closed** 2016-03-31 18:15 UTC
Labels: 3 - To Review, app:user_ldap, bug, sev2-high, won' t fix
