### ISSUE TITLE
Files deleted via Windows File Explorer not being moved to ownCloud Trash

### ISSUE THREAD

**Issue by aleishman01** [owncloud/core#15476] opened 2015-04-08 13:57 UTC
When a user with the ownCloud Desktop Client deletes files from the ownCloud directory via the command line or any File Explorer (e.g. Windows Explorer, Linux Thunar...), those files do not appear in the ownCloud trash bin and can not be recovered via the ownCloud web interface.

This is a very serious issue for my company as we have 23 remote (all over the United States) ownCloud users syncing thousands of images each every week.  We can not micro-manage them.

Our ownCloud server is running on Debian 8 and is kept current via apt-get.  Our clients are running desktop version ownCloud-1.8.0.4893 and using Windows XP, 7 and 8.1.

Edit:  our storage space is 2.5 terabytes and only 8% full.

More information:  When they delete folders, they usually contain well over 100 image files.

**Comment by karlitschek** [comment] 2015-04-08 14:24
Not sure I understand correctly. Can you please post a full bug report using the issue tracker template? https://github.com/owncloud/core/blob/master/CONTRIBUTING.md 
So you sync folders from the server to the desktop with the owncloud syncing client. Then you delete a folder locally on the desktop. then the desktop sync client also deletes it on the server. then you can´t restore this folder in the ownCloud webinterface?

**Comment by aleishman01** [comment] 2015-04-08 14:31
You understanding is correct. But, here is our order of operations:

1) Client copies folders of files (images) into their local ownCloud folder.
2) The folder(s) are synced with the server (server A).
3) A different server (server B) has an ownCloud client installed and gets the files (synced).
4) (Server B) processes the images and then deletes the folders from its ownCloud folder.
5) (Server A) and the client (from step 1) have their folders deleted by the ownClud synchronization.

Occasionally, files need to be retrieved. Those folders are not in the trash on the ownCloud server and cannot be seen via the web interface.

I will fill out a bug report.

**Comment by karlitschek** [comment] 2015-04-08 15:04
Not sure I understand. How can you have two owncloud servers?

**Comment by aleishman01** [comment] 2015-04-08 15:06
We have one ownCloud server (Server A) and the other server (Server B) is a "client".

**Comment by DeepDiver1975** [comment] 2015-04-13 09:57
duplicate of https://github.com/owncloud/core/issues/15009

**Closed by DeepDiver1975** 2015-04-13 09:57 UTC
