### ISSUE TITLE
Failing login with LDAP users.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24743] opened 2016-05-20 08:17 UTC
### Steps to reproduce:

1. Enable ldap app, set up ldap server correctly.
2. Login with one of the ldap users.

### Expected behaviour:
LDAP user can log in.

### Actual behaviour
LDAP user cannot log in.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.2","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"NzzX99tRo2qEp669Q8NL","remoteAddr":"HIDDEN_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2016-05-20T07:57:39+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"03Y6g7mOg8+zmq65LK+u","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2016-05-20T07:57:40+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"03Y6g7mOg8+zmq65LK+u","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2016-05-20T07:57:40+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"03Y6g7mOg8+zmq65LK+u","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Configuration Error (prefix ): No LDAP Login Filter given!","level":2,"time":"2016-05-20T07:57:40+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"03Y6g7mOg8+zmq65LK+u","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2016-05-20T07:57:40+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"03Y6g7mOg8+zmq65LK+u","remoteAddr":"HIDDEN_IP","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/opt\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2016-05-20T07:57:40+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"D8fQnWKdfl9llr+N3YxQ","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldap:\\\/\\\/docker.oc.solidgear.es:389\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(121): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('b9088772-8742-1...')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(190): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(291): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(390): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#4 \\\/opt\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(187): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'b9088772-8742-1...', 'secret')\\n#5 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin('aaliyah_mcclure', 'secret', NULL)\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(45): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/login')\\n#13 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":105}","level":3,"time":"2016-05-20T08:00:17+00:00","method":"POST","url":"\/index.php\/login","user":"--"}
{"reqId":"D8fQnWKdfl9llr+N3YxQ","remoteAddr":"HIDDEN_IP","app":"core","message":"Login failed: 'b9088772-8742-1034-8d75-39af73a96b9a' (Remote IP: 'HIDDEN_IP')","level":2,"time":"2016-05-20T08:00:17+00:00","method":"POST","url":"\/index.php\/login","user":"--"}
{"reqId":"HvPWr0phaTijM+DL4K84","remoteAddr":"HIDDEN_IP","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name on ldap:\\\/\\\/docker.oc.solidgear.es:389\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(121): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('b8df1298-8742-1...')\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Manager.php(190): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(291): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(390): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#4 \\\/opt\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(187): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'b8df1298-8742-1...', 'secret')\\n#5 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin('aaliyah_adams', 'secret', '%2Findex.php%2F...')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(45): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/opt\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/login')\\n#13 \\\/opt\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":105}","level":3,"time":"2016-05-20T08:00:34+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F","user":"--"}
{"reqId":"HvPWr0phaTijM+DL4K84","remoteAddr":"HIDDEN_IP","app":"core","message":"Login failed: 'b8df1298-8742-1034-8cb4-39af73a96b9a' (Remote IP: 'HIDDEN_IP)","level":2,"time":"2016-05-20T08:00:34+00:00","method":"POST","url":"\/index.php\/login?redirect_url=%252Findex.php%252Fapps%252Ffiles%252F","user":"--"}

```

### Client configuration

**browser**
Chrome

cc @owncloud/ldap

**Comment by SergioBertolinSG** [comment] 2016-05-20 08:40
Stable9 doesn't have this problem.

**Comment by PVince81** [comment] 2016-05-20 09:48
Confirmed broken on master

**Comment by blizzz** [comment] 2016-05-20 10:14
Report is missing crucial info (LDAP config? What do you see after the login failed?) . Does the lookup work on "Test Loginname" in the LDAP Wizard? With a very brief test with a master-based branch (as of yesterday evening) it works for me.

**Comment by PVince81** [comment] 2016-05-20 10:17
In my case it was just the plain docker https://github.com/owncloud/administration/tree/master/ldap-testing with zombie users.

If you say it worked yesterday, then it is likely related to auth PRs. We merged a bunch of them since.
Also the PSR-4 ones, but that's less likely.

**Comment by SergioBertolinSG** [comment] 2016-05-20 10:32
> Report is missing crucial info (LDAP config?

Using our ldap server in docker container (port 389 one)

> What do you see after the login failed?)

The login page appears again.

> Does the lookup work on "Test Loginname" in the LDAP Wizard?

This works fine: User found and settings verified

**Comment by SergioBertolinSG** [comment] 2016-05-20 13:03
Editing this attribute in the expert view
Internal Username Attribute: uid
And clearing the mappings (click on both buttons), has worked as a workaround.

**Comment by SergioBertolinSG** [comment] 2016-05-20 13:26
@davicente bisected this to find this commit as the start of this failure: https://github.com/owncloud/core/commit/331e4efacb226f95551962f3a53030feced0b190

**Closed** 2016-05-24 15:51 UTC
Labels: app:user_ldap, bug, regression, sev2-high
