### ISSUE TITLE
Sharing Broken / folder disappear after sharing sub-folders in oc 8.1.3 with encryption module enabled

### ISSUE THREAD

**Issue by Kruseltier** [owncloud/core#19415] opened 2015-09-28 14:53 UTC
### Steps to reproduce

Do all following steps with the admin-user:
1. Create 3 different Groups (testgroup1, testgroup2, testgroup3)  and 2 Users (testuser1, testuser2)
2. add testuser1 and testuser2 to the testgroups1, testgroup2 and testgroup3
3. Create the following Folder structures with the following shares (
4. testfolder 
   - subTestFolder1
     - testfile
   - subTestFolder2
     - testfile
   - subTestFolder3 
     - testfile
5. Now share the testfolder with testuser1 and testuser2 (everything seems to be fine until now, check it with login as testuser1 and testuser2
6. Now share also subTestFolder1, subTestFolder2 and subTestFolder3 with testgroup1, testgroup2 and testgroup3
7. Now the folder-Structure under the testfolder is disappearing, but one testfile is shown directly in testfolder
8. Now remove testuser1 from testgroup1 (and the folders are appearging again)
9. after removing testuser1 from all groups and readding to testgroup1,testgroup2 and testgroup3 ererything seems to work

So i think there is some big problem with sharing, it seems to complete broken
### Expected behaviour

Every shared folder (group or user-share) has to be visible to the user
### Actual behaviour

Folders are disapearing while there are still rights and shares for the user
### Server configuration

**Operating system**:
Clean and Fresh installed Debian 8, Installed from SUSE-Build-Service Debian repository as recommended

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Aug 28 2015 16:28:08

**Database:**
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.6.13-0+deb8u1 (cli) (built: Sep  7 2015 13:38:37)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.3

**Updated from an older ownCloud or fresh install:**
Clean/Fresh install 

**List of activated apps:**
Enabled:
- activity: 2.0.2
- encryption: 1.0.0
- files: 1.1.10
- files_locking:
- files_pdfviewer: 0.7
- files_sharing: 0.6.2
- files_texteditor: 0.4
- files_trashbin: 0.6.3
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 0.6.0
- provisioning_api: 0.2
- templateeditor: 0.1
- updater: 0.6
  Disabled:
- external
- files_external
- user_external
- user_ldap
- user_webdavauth

`
**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocscuyxul6wh',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no


### Client configuration
**Browser:**
Chrome Version 45.0.2454.101
Firefox 40.0.3

**Operating system:**
Windows 10 Professional 64Bit

### Logs
#### Web server error log
```

[Mon Sep 28 16:24:37.433557 2015] [mpm_prefork:notice] [pid 7827] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using xxx. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 28 16:24:37.628095 2015] [mpm_prefork:notice] [pid 7827] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Mon Sep 28 16:24:37.628138 2015] [core:notice] [pid 7827] AH00094: Command line: '/usr/sbin/apache2'
#### ownCloud log (data/owncloud.log)

```
{"reqId":"Rwi2Rp9YjaaEuVrJRsA8","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-09-28T14:25:25+00:00"}
{"reqId":"Rwi2Rp9YjaaEuVrJRsA8","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fopen(\/var\/www\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-09-28T14:25:25+00:00"}
{"reqId":"eG04bVvTDj5kV9jOTe2f","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-09-28T14:25:37+00:00"}
{"reqId":"ESqexK0U6ko1PyCbvMdc","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/appframework\/http\/request.php#685","level":3,"time":"2015-09-28T14:26:43+00:00"}
{"reqId":"RM\/y0rABCejSHXAddyLd","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#311","level":3,"time":"2015-09-28T14:37:33+00:00"}
{"reqId":"RM\/y0rABCejSHXAddyLd","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#311","level":3,"time":"2015-09-28T14:37:33+00:00"}
{"reqId":"fBXhZna92NuurQAzUItx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#311","level":3,"time":"2015-09-28T14:37:40+00:00"}
{"reqId":"fBXhZna92NuurQAzUItx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#311","level":3,"time":"2015-09-28T14:37:40+00:00"}

I created a testing-machine and reproduced this issues directly so this is the whole log, cause nothing else is made with this test-account. Apache error-Log shows also nothing unusual.




```

**Comment by karlitschek** [comment] 2015-09-28 15:10
@schiesbn

**Comment by Kruseltier** [comment] 2015-09-28 17:32
I reviewed this Bug on a second / not clean Accout and there everything is working a as espected, so i cannot reproduce the bug hiere:

OC Version 8.1.1, Centos 6, Apache 2.4, PHP 5.6 (with lsapi), former upgraded from 7.x, encryption enabled,

**Comment by PVince81** [comment] 2015-09-29 08:13
Strange thing.
That Array to String conversion error points to: https://github.com/owncloud/core/blob/v8.1.3/core/ajax/share.php#L311
Hopefully a useful clue.

**Comment by Kruseltier** [comment] 2015-09-29 08:22
Maybe that this is just a Error in the visability, caused by getting the shares via java-script/ajax in this line of code ? (I think this line reads the user-shares ?)

**Comment by PVince81** [comment] 2015-09-29 08:26
@Kruseltier yes it does. I guess it happens when you open the share dropdown, whenever it tries to load whoever the current file is shared with ?

You could try the following: open the DOM inspector in the browser, then evaluate the "tr" of the file row, search for the "data-id" attribute. Its value is the file id.
Then go to your database and do a `select * from oc_share where item_source=$FILEID`, replace $FILEID with the fileid you got. Then post the anonymized result here.

Another thing to try: use the network console to find out the "ajax/share.php" request after opening the share dropdown. That one is probably red since it failed. Then copy the request parameters and paste them here.

**Comment by Kruseltier** [comment] 2015-09-29 09:18
@PVince81  it´s pretty Hard to reproduce the errors in /core/ajax/share.php#L311 (i think maybe they occur only on the first time i share it ?) I will clean everything and try to get a console-log after it.

>You could try the following: open the DOM inspector in the browser, then evaluate the "tr" of the file >row, search for the "data-id" attribute. Its value is the file id.

This is not possible cause there is no file in this particular folder, there will be only showed the file or folders in the next subdir. See Screenshot as testuser2 and corrosponding sql screen. (I think there is something failing with the sharing)

Is there a possibility to give you direct access to my testsystem? (there is nothing productional and everything can be removed etc. it is running in an vm who can be resettet at any time,  but i cannot finde a personal messaging system on github, maybe send you access via mail ?)

Actual Folder-Structure:

* Root1 (shared with testuser1, testuser2)
  * grp1 (shared with testgroup1, testgroup2)
     *  test.txt
   * grp2 (shared with testgroup1, testgroup2)

for testing i created a few minutes ago a paralell folder structure:
* Root2 (shared with testuser1, testuser2)
  * grp1 (shared with testgroup1, testgroup2)
     *  test.txt
   * grp2 (shared with testgroup1, testgroup2)

(i removed this second folder structrue completely but they still are in the oc_share table, see screenshot)

The oc_share_table seems to be corrupt also, the ID 18,19 are in my opinion questionable. 
Wy to share the file_target /root again with parentID 17, to same share_user as in ID 15/17 ?

![2015-09-29 11_11_49-193 200 160 244 _ localhost _ owncloud _ oc_share _ phpmyadmin 4 2 12deb2](https://cloud.githubusercontent.com/assets/12657922/10159820/fa573af4-669a-11e5-90c0-58051655590d.png)

Folder root as admin:
![2015-09-29 11_12_56-](https://cloud.githubusercontent.com/assets/12657922/10159849/224dec1a-669b-11e5-9002-64991696be2b.png)

Folder root as testuser it seems that the test2.txt is the file in the folder root->grp2: 
![root-testuser](https://cloud.githubusercontent.com/assets/12657922/10160035/92bc8498-669b-11e5-8706-1f8120c25c79.png)

**Comment by PVince81** [comment] 2015-09-29 09:21
>the ID 18,19 are in my opinion questionable.

This is normal. For group shares, additional entries are added to track local changes like if the recipients moved/renamed the target folder (file_target). You can see that the "parent" field points to the parent share 17.

**Comment by PVince81** [comment] 2015-09-29 09:23
>This is not possible cause there is no file in this particular folder, there will be only showed the file or folders in the next subdir. See Screenshot as testuser2 and corrosponding sql screen. (I think there is something failing with the sharing)

Okay, so this means the ajax/share.php call is not the one from when opening the share dropdown, but is the one happening the file list app when retrieving all known shares.

**Comment by PVince81** [comment] 2015-09-29 09:25
>(i removed this second folder structrue completely but they still are in the oc_share table, see screenshot)

You might need to empty the trashbin and wait for a cron run. There's a background OC cron job that cleans up orphaned shares.

Regarding ajax/share.php, I think it happens when you open the file list at first. You could try opening the network console while in the file list, then refresh the page. Then find the "ajax/share.php" call there, I expect it to be red.

**Comment by Kruseltier** [comment] 2015-09-29 10:08
>the ID 18,19 are in my opinion questionable.
>>This is normal. For group shares, additional entries are added to track local changes like if the 
recipients moved/renamed the target folder (file_target). You can see that the "parent" field points to >the parent share 17.

But 17 is not the parent share, 17 is the child of file_target /root and "testgruppe1"  has no access to the file_target /root ?

>This is not possible cause there is no file in this particular folder, there will be only showed the file or folders in the next subdir. See Screenshot as testuser2 and corrosponding sql screen. (I think there is something failing with the sharing)
>>Okay, so this means the ajax/share.php call is not the one from when opening the share dropdown, but is the one happening the file list app when retrieving all known shares.

yes i think this is correct.

>(i removed this second folder structrue completely but they still are in the oc_share table, see screenshot)
>>You might need to empty the trashbin and wait for a cron run. There's a background OC cron job that cleans up orphaned shares.

I also cleaned the trash bin completly and thought the cron-jobs would be runned every time with ajax. 

>Regarding ajax/share.php, I think it happens when you open the file list at first. You could try opening the network console while in the file list, then refresh the page. Then find the "ajax/share.php" call there, I expect it to be red.

No, when i load the folder, even with STRG+F5 (to prevent caching) thereis no error with ajax/share.php in the owncloud.log and even the request in the browser is working but failing. 
(see sreenshots, i will again clear everything, every user, folder etc, and try to get this error again)

![network-share](https://cloud.githubusercontent.com/assets/12657922/10161213/b6271860-66a2-11e5-8ae2-c69eac8ed367.png)
![console](https://cloud.githubusercontent.com/assets/12657922/10161212/b62460a2-66a2-11e5-8994-4c3a88240d7b.png)

**Comment by Kruseltier** [comment] 2015-09-29 10:39
cause the test2.txt has not to be directly in the root directory, but in the subfolder root/grp2/text2.txt i added also every ajax request called in the folder /root ( as shown in above screenshot)

/index.php/apps/files/ajax/list.php?dir=%2Froot&sort=name&sortdirection=asc
``` 
{"data":{"directory":"\/root","files":[{"id":"155","parentId":"153","date":"29. September 2015 um 10:35:25 MESZ","mtime":1443515725000,"icon":"\/core\/img\/filetypes\/text.svg","name":"test2.txt","permissions":27,"mimetype":"text\/plain","size":0,"type":"file","etag":"4ddcbc888d9ed531337e7c6f41ecd2b9","shareOwner":"owncloud","mountType":"shared"}],"permissions":31},"status":"success"}
```

This file has not to be there.

/index.php/core/ajax/share.php?fetch=getItemsSharedStatuses&itemType=file

```
{"data":[],"status":"success"}
```

**Comment by Kruseltier** [comment] 2015-09-30 08:49
I cleaned my whole instance, (deleted user and folders) and tried to escalate the "Array to string conversion" error in share.php again with console etc. 

The error occours when i open the sharing window and typing something in the "user/group-search field" to share this folder: (see screen below)

![image](https://cloud.githubusercontent.com/assets/12657922/10188517/382de286-6760-11e5-914b-dc742c7475f0.png)

This throws the given Error in share.php#311 but the response on console in the browser is still correct there is no error:

```
request:

http://xxx.xxx.xxx.xxx/index.php/core/ajax/share.php?fetch=getShareWith&search=tes&limit=200&itemShares%5B0%5D%5B%5D=testuser1&itemType=folder

response:

{"data":[{"label":"testgruppe1","value":{"shareType":1,"shareWith":"testgruppe1"}},{"label":"testgruppe2","value":{"shareType":1,"shareWith":"testgruppe2"}},{"label":"testuser2","value":{"shareType":0,"shareWith":"testuser2"}}],"status":"success"}
```

So the problem with the sharings (also i get no error on console while open the share) may be a problem direct when sharing the directory ?

**Comment by Kruseltier** [comment] 2015-10-12 12:29
Hi, again an update from me! 

This is a very serious problem and i reproduced it on 8.1.1 as well as on the actual stable 7.xx Version. It seems that this easy szenario (sharing a folder in a shared folder) isn´t working since ages. 

* the database entries differes everytime, depending on the sequence i share the files
* even if the folders do not dissaperaing (just possible with the right sharing sequence), the rights are not correct inherited (so if i remove write right from upper folder but i sould have still write right on lower folder, but don´t have)
* sometimes it helps to remove and re add a user to a group or first set rights and than add him. (also depending on the sharing order and so on, the displaying of the folders is different)
 * sometimes the lower shares (in this example subTestFolder1) apperas in the root folder (on ulinking them and using them inside the testfolder the rights are not corret inherited)
 * sometimes there is a seperate testfolder, named testfolder2 but sometimes one of the testfolders is empty

I looked in the code and checkt the database entries on every action i take, and it is pretty unexpected for me that the database entries are very diffenent and not consistent in dependence of all upper called szenarios. In my opinion there cannot be a correct behavior of the sharing in this case!

I will also help you to debug this and can also participate in developing but a little help from you, how we can together improve this would be very nice!

Thanks

**Comment by PVince81** [comment] 2015-10-12 12:34
@rullzer can you reproduce this ?

**Comment by rullzer** [comment] 2015-10-13 09:03
I just checked master and it all seems to work here... @Kruseltier could you check if that works for you as well?

**Comment by PVince81** [comment] 2015-10-13 09:04
master or 8.2RC1

**Comment by rullzer** [comment] 2015-10-13 09:05
I tested master... but let me check RC1 as well

**Comment by rullzer** [comment] 2015-10-13 09:11
8.2RC1 also seems to work here.

**Comment by rullzer** [comment] 2015-10-13 09:11
Note that I tested without encryption as @Kruseltier said that was most likely unrelated.

**Comment by Kruseltier** [comment] 2015-10-13 13:33
@rullzer  did you reproduce the error before with the older stable versions ? 
I will try it with 8.2RC1 and give Feedback again!

**Comment by Kruseltier** [comment] 2015-10-13 13:57
Sry for this noob question, .. i has to get the actual master build with ocdev ?!
How can i checkout tags here ? I can only choose branches ?

**Comment by PVince81** [comment] 2015-10-13 13:58
There is a release tarball for 8.2RC1, let me find it

**Comment by rullzer** [comment] 2015-10-13 13:59
http://download.owncloud.org/community/testing/owncloud-8.2RC1.zip

**Comment by Kruseltier** [comment] 2015-10-13 13:59
Thank you, stand by, i will try it ;)

**Comment by Kruseltier** [comment] 2015-10-13 14:25
Ok, i have a Feedback for you without encryption:
* sharing works
* the shares are visible 
 * in the structure (testfolder -> subTestFolder -> testfile)
 * and also in the root directory  (see screenshot below)
![root-structure](https://cloud.githubusercontent.com/assets/12657922/10457407/7d6b1560-71c6-11e5-9cc3-53ce37b71ac9.png)

I think this seems to be correct. The only thing that persists is, that if i remove the write right from the root folder ("testfolder") but still have the write-right in the subfolders with the groups the rights from the root folder will get inherited and overwrites the subfolder rights (as shown below)
![image](https://cloud.githubusercontent.com/assets/12657922/10457492/e81fcd88-71c6-11e5-8194-88a89c611fe9.png)

Is this a bug or a feature ?

I will test it again with encryption!

**Comment by rullzer** [comment] 2015-10-13 14:28
> Is this a bug or a feature ?

That is a bug. Basically what we do is for subshares to follow the permissions of the parent. So if userA shares folderA with userB. And userB shares a subfolder of that with userC then if userA revokes write permissions to userB they should also be revoked to userC.

But it seems we do this to agressively. Let me think about how to solve that in a somewhat graceful way.

**Comment by Kruseltier** [comment] 2015-10-13 14:35
> But it seems we do this to agressively. Let me think about how to solve that in a somewhat graceful way.

Let me know if i can help you here in any way. I have also PHP developer here who can participate if that helps here.

Feedback with encryption:
* it works in the same way as without encryption, so this is correct encryption has noting to do with this issue

**Comment by bjr53** [comment] 2015-10-27 05:24
Hi there,

I believe I have stumbled upon the same issue. I'm using AD (Zentyal AD) LDAP  for user group memberships but suspect the LDAP component is unrelated.

I'm running ownCloud 8.1.3 on ubuntu 14.04. 

The problem:
When a parent folder has been shared with a group, and multiple immediate sub folders are shared with a different group of which the user is also a member, then sub folders do not display for that user in the Web interface. What seems to happen is that when the user clicks on the parent folder they are taken directly 'into' one of the sub folders (which is arbitrarily chosen - possibly the first one to be shared) instead of getting a 'list' of the sub folders.

Directory Layout:
Parent
      |--sub1
            |-- new file.txt
      |--sub2
            |-- new file.txt
      |--sub3
            |-- new file.txt
      |--etc...

The Parent Dir has been shared with parent_group. User A is member of parent_group.
The sub1 dir has been shared with sub1_group. User A is also a member of sub1_group.
The sub2 dir has been shared with sub2_group. User A is also a member of sub2_group... and so on.

Expected Behaviour:
When User A clicks on Parent they are presented with a list of sub dirs.

Actual Behaviour:
When User A clicks on Parent they are presented with new file.txt i.e. the contents of one of the sub dirs. Which sub dirs contents depends on the particular mapped sub dir that has been picked by OC. Presumably it is based on the first sub dir shared because on my real world server this appeared to be the case e.g. it did not appear to be an alphanumerically based decision.

When clicking on the 'Shared with you' left menu shortcut User A is presented with the Parent dir listed multiple times. Once for each sub folder. However clicking on any of the presented shares still takes you directly to the same arbitrarily mapped sub dir.

Soft of Fix: 
Once User A is removed from all groups assigned to all sub dirs, and remains in the parent_group, then expected functionality is restored.

Obviously this 'fix' is a work-around since User A's permissions from the Parent dir cascade to the sub dirs anyway: Thus things work. But having to keep track of whether a user is a member of another group with directory permissions further up the directory chain is a bit of a nightmare. The consequences of getting this wrong leads to directories linking to erroneous sub dirs and files will be deemed 'missing' by users or will be misplaced at best. The scenario is setting the scene for people to fail.


Anyway that is my two cents. Perhaps it is helpful. Perhaps not.

Thanks to those all involved in this great product! :)

**Comment by PVince81** [comment] 2016-03-03 14:52
@rullzer any update ?

**Comment by rullzer** [comment] 2016-03-03 15:09
Ok so in 9.0 we don't have this behaviour anymore. Since we have the new resharing stuff.

**Comment by PVince81** [comment] 2016-10-20 08:52
Is this still happening with 8.2.8 ?

**Closed** 2017-01-27 17:35 UTC
Labels: app:encryption, bug, feature:sharing
