### ISSUE TITLE
ownCloud 8.2.2 (stable) - Drop down menu add group will not be shown on scrolling

### ISSUE THREAD

**Issue by JB1985** [owncloud/core#21609] opened 2016-01-11 11:31 UTC
Hi, 

i am using OC8.2.2 stable with Debian7.

apache2                            2.2.22-13+deb7u6
php5                                  5.4.45-0+deb7u2
mysql-server-core-5.5       5.5.46-0+deb7u1

I  have the problem, if I have more than 50 users (can be on 10 or 20 users, i dont know) and i scroll down and want to add a user in a group, the drop down menu will not be shown.

It is always at the top of the page and not just on the field.

![bildschirmfoto vom 2016-01-11 12-14-04](https://cloud.githubusercontent.com/assets/9932751/12232462/15aaaaa0-b85f-11e5-82b7-03d2bd196408.png)

**Comment by PVince81** [comment] 2016-01-11 11:33
Duplicate of https://github.com/owncloud/core/issues/20503

**Closed by PVince81** 2016-01-11 11:33 UTC
