### ISSUE TITLE
Delete button for groups of files/folders is not present in external storage folders.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18004] opened 2015-07-31 06:59 UTC
### Steps to reproduce

1. Mount an external storage folder.
2. Select a group of files/folders inside the external storage folder.
3. Try to delete all of them with one click.

### Expected behaviour
There is a button for doing this.

Regular folder:

![screen shot 2015-07-30 at 13 28 33](https://cloud.githubusercontent.com/assets/9048796/8982177/f4566b7c-36be-11e5-8d4f-db8ceb086ead.png)

### Actual behaviour
There is no delete button inside external storage folder.

Enterprise version:
![screen shot 2015-07-30 at 13 26 33](https://cloud.githubusercontent.com/assets/9048796/8982189/145f42ea-36bf-11e5-9c36-3f44f7de81cd.png)

### Server configuration

Operating system:
Cent OS 6.6

Web server:
Apache

Database:
MySQL

PHP version:
5.4

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.1","versionstring":"8.1.1 beta1","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
External storage

Are you using external storage, if yes which one: local/smb/sftp/...
Yes SMB, Local

Are you using encryption: 
no

### Client configuration
Chrome

**Comment by DeepDiver1975** [comment] 2015-07-31 08:49
@SergioBertolinSG milestone assignments are to be done my @cmonteroluque @karlitschek or mysqlf - THX

**Comment by SergioBertolinSG** [comment] 2015-07-31 09:18
@DeepDiver1975 OK, I wasn't sure of this. In previous versions we were encouraged to assign a milestone with the severity of the issues.

**Comment by PVince81** [comment] 2015-07-31 13:48
Duplicate of https://github.com/owncloud/core/issues/16533

**Closed by PVince81** 2015-07-31 13:48 UTC
Labels: app:files_external, bug, sev3-medium
