### ISSUE TITLE
Fatal webdav oc 8.1.4

### ISSUE THREAD

**Issue by gthery** [owncloud/core#20520] opened 2015-11-16 09:49 UTC
Hi,
I have a problem with webdav, My installation is:

Debian 7

Apache:
<pre><code>
apache2 -v
Server version: Apache/2.2.22 (Debian)
Server built:   Aug 18 2015 09:50:52
</code></pre>

mysql:
<pre><code>
5.5.46-0+deb7u1
</code></pre>

php:
<pre><code>
php -v
PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
with XCache v2.0.0, Copyright (c) 2005-2012, by mOo
</code></pre>

owncloud 8.1.4
The error message is:
<pre><code>
Exception: {"Message":"HTTP\/1.1 400 expected filesize 1573944 got 1474560","Code":0,"Trace":"#0 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #208)\n#1 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Nestier\/DOSSIER...', Resource id #208, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#7 \/mnt\/web\/www\/bm-tech.fr\/owncloud\/remote.php(132): require_once('\/mnt\/web\/www\/bm...')\n#8 {main}","File":"\/mnt\/web\/www\/bm-tech.fr\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":144}
</code></pre>
The apache Vhost:
<pre><code>
<VirtualHost 192.168.0.11:443>
        ServerAdmin admin@bmtech.fr
        ServerName cloud.bmtech.fr
        ServerAlias www.cloud.bmtech.fr
        ServerAlias cloud.bm-tech.fr
        ServerAlias www.cloud.bm-tech.fr
        ServerAlias cloud.groupe-secre.eu
        ServerAlias www.cloud.groupe-secre.eu
        ServerAlias nestier.bmtech.fr
        ServerAlias www.nestier.bmtech.fr
        ServerAlias cloud.jsdadzif.fr
        ServerAlias www.cloud.jsdadzif.fr

        DocumentRoot /mnt/web/www/bm-tech.fr/owncloud
        <Directory />
                LimitRequestBody 0
                Options FollowSymLinks
                AllowOverride All
                SSLRenegBufferSize 10486000
        </Directory>
        <Directory /mnt/web/www/bm-tech.fr/owncloud>
                LimitRequestBody 0
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
                SSLRenegBufferSize 10486000
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride All
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog /var/log/apache2/error_owncloud.bm-tech.fr.log
# Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog /var/log/apache2/access_owncloud.bm-tech.fr.log combined

    Alias /doc/ "/usr/share/doc/"
    <Directory "/usr/share/doc/">
        Options Indexes MultiViews FollowSymLinks
        AllowOverride None
        Order deny,allow
        Deny from all
        Allow from 127.0.0.0/255.0.0.0 ::1/128
    </Directory>

  <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
    </IfModule>

SSLEngine On
SSLOptions +FakeBasicAuth +ExportCertData +StrictRequire
SSLCertificateFile /etc/ssl/owncloud.crt
SSLCertificateKeyFile /etc/ssl/owncloud.key
</VirtualHost>
</code></pre>

can you help me?

I'm sorry for my English, i'm French.

Thank you in advance.

**Comment by RealRancor** [comment] 2015-11-16 10:42
@gthery Duplicate of https://github.com/owncloud/core/issues/9832, a write-up for all known workarounds is available here:

https://github.com/owncloud/core/issues/9832#issuecomment-156222485

**Closed** 2015-11-16 10:48 UTC

**Comment by gthery** [comment] 2015-11-20 12:03
thanks is work :)
