### ISSUE TITLE
Way to recover sharing

### ISSUE THREAD

**Issue by dubsflyt** [owncloud/core#14884] opened 2015-03-13 16:50 UTC
Recently we had an issue when a user accidentally deleted a folder which had a number of subfolders, of course we had backups of these so could restore them, but a number of these subfolders had sharing rules applied. After restore these files obviously had different etags so no longer showed as shared, while not a massive deal with just a couple of subfolders, if this was a larger amount it could take hours or days to restore all of the sharing links. 

There really needs to be a way for sharing to be recoverable OR for the deleted items system to restore folder structure when it restores a file, as at the moment if the folder doesnt exist that the file came from it appears to just go to the top level.

**Comment by PVince81** [comment] 2015-03-16 09:41
Duplicate of https://github.com/owncloud/core/issues/10158

**Closed by PVince81** 2015-03-16 09:41 UTC
Labels: Enhancement
