### ISSUE TITLE
Newly created users are missing .../files_trashbin/files in 8.2

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#20127] opened 2015-10-29 00:53 UTC
### Steps to reproduce
1. Create a new user
2. Wait for an error message to pop up in owncloud.log
### Expected behavior

No error output, or that the dirs are created
### Actual behavior

No dirs in the new user folder and this:

```
opendir(/var/www/owncloud/data/olsson/files_trashbin/files): failed to open dir: No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#96
```

**Server**
8.2
Ubuntu 14.04

**MySQL**
5.5.46-0ubuntu0.14.04.2 (Ubuntu)
**PHP**
PHP 5.6.14-1+deb.sury.org~trusty+1 (cli)
### How to make the error message disappear

Manually creating that dir/path.

**Comment by karlitschek** [comment] 2015-10-29 01:04
@schiesbn

**Comment by PVince81** [comment] 2015-10-29 08:53
Not really an issue. That folder  is created on demand.
So this is just about removing the warning.

**Comment by PVince81** [comment] 2015-10-29 14:04
@enoch85 don't add tickets to releases unless you are going to work on them yourself and have an idea about the solution

**Comment by schiesbn** [comment] 2015-10-29 14:15
as said by @PVince81 this shouldn't be a problem. Still of course it would be nice if we could suppress this error message. But therefor it woud be good to have some explicite steps how to trigger it, "Wait for an error message to pop up in owncloud.log" is to general in this case.

**Comment by enoch85** [comment] 2015-10-29 21:18
@Pvince81, sorry just my way of pushing things. Won't happen again. 

Regarding removing if from loglevel 2, yes please.

**Comment by eidota** [comment] 2015-11-11 09:20
Sry for joining in, but i have the same issue. Its really filling up our logfile and makes it hard to spot the important messages. If its inappropriate to post here i will create a new issue.

### Steps to reproduce
1. Set up ownCloud 8.2
2. Configure LDAP
3. In LDAP: Grant User ABC the permission to login to oC but dont log in
4. Wait for next cronjob or trigger it

### Expected behaviour
No errors. There should be no checks on non existant folders.

### Actual behaviour
ownCloud tries to check the trashbin folder which of course doesnt exist yet. This happens for all users that are known through LDAP but havent logged in yet (so user folder doesnt exist).
`{"reqId":"...","remoteAddr":"","app":"PHP","message":"opendir(\/nfs\/owncloud\/data\ABC\/files_trashbin\/files): failed to open dir: No such file or directory at \/disk1\/webserver\/owncloud\/lib\/private\/files\/storage\/local.php#96","level":3,"time":"..."}`

### Server configuration
**Operating system**: Redhat 7
**Web server:** Apache/2.4.6
**Database:** MariaDB
**PHP version:** 5.4.16
**ownCloud version:** 8.2
**Updated from an older ownCloud or fresh install:** Fresh Install

**Comment by PVince81** [comment] 2015-11-11 16:57
Okay, thanks for the details. So now we know it might happen due to cron jobs.

Has any of these users ever logged in ? I think as soon as they log in they should get a trashbin folder and the warning will disappear.

**Comment by enoch85** [comment] 2015-11-11 19:21
In my cases they have logged in, issue still appears.

**Comment by eidota** [comment] 2015-11-12 07:53
1. It happens even though they have not logged in yet. I assume the cronjob shouldnt check data folders of users who never logged in.
2. Even after they logged in, the trashbin_files(/files) folder isnt created so the message stays until they delete something and the folder is created. Couldnt the trashbin folder be created along with the standard "files" folder?

**Comment by PVince81** [comment] 2015-11-13 08:51
Okay, then maybe it was the case in older OC versions and isn't in newer ones.

Ideally the code that tries to access that folder should simply ignore the folder if it doesn't exist, or auto-create it.

**Comment by enoch85** [comment] 2015-11-13 12:31
@PVince81 This is on 8.2.

**Comment by PVince81** [comment] 2017-09-11 15:50
closing as duplicate of https://github.com/owncloud/core/issues/16365

**Closed by PVince81** 2017-09-11 15:50 UTC
Labels: app:files_trashbin, bug, sev4-low
