### ISSUE TITLE
memcache key issue in OC9

### ISSUE THREAD

**Issue by Loki3000** [owncloud/core#23187] opened 2016-03-12 20:48 UTC
### Steps to reproduce
1. go to https://domain.site.net/index.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0 (it's request from activity app)

### Expected behaviour
JSON with a result

### Actual behaviour
Server error

In server error log "Error 33 interacting with memcached : A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE"
The reason is in key generation in
lib/private/route/cachingrouter.php
```php
$key = $this->context->getHost() . '#' . $this->context->getBaseUrl() . $name . json_encode($parameters) . intval($absolute);
```
allows prohibited symbols.
The solution is to limit numbers of used symbols. For example:
```php
$key = $this->context->getHost() . '#' . $this->context->getBaseUrl() . $name . json_encode($parameters) . intval($absolute);
$key=md5($key);
```
after that all warks right.

### Server configuration
**Operating system**: Ubuntu 14.04
**Web server:** Apache/2.4.18
**Database:** mysql  5.5.47
**PHP version:** PHP 5.5.9
**ownCloud version:** ownCloud 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:** updated from 8.2
**Where did you install ownCloud from:** repository

```
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - direct_menu: 0.7.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 7.1.2
  - notes: 2.0.0
  - notifications: 0.2.3
  - ocdownloader: 1.5
  - provisioning_api: 0.4.1
  - rainloop: 4.12
  - search_lucene: 0.7.0
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - updater: 0.6
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.site.net"
        ],
        "datadirectory": "\/home\/cloud",
        "overwrite.cli.url": "https:\/\/domain.site.net",
        "logfile": "\/var\/log\/owncloud.log",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "root",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forcessl": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "defaultapp": "rainloop",
        "filesystem_check_changes": 1,
        "asset-pipeline.enabled": false,
        "updatechecker": false,
        "logtimezone": "UTC",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "x.x.x.x",
                11211
            ]
        ]
    }
}

```

**Comment by LukasReschke** [comment] 2016-03-12 20:55
Dupe of https://github.com/owncloud/core/issues/23076. Potential workaround is also there at https://github.com/owncloud/core/issues/23076#issuecomment-194799114

**Closed by LukasReschke** 2016-03-12 20:55 UTC
