### ISSUE TITLE
Exclude subfolder from sharing

### ISSUE THREAD

**Issue by SirSolero** [owncloud/core#7272] opened 2014-02-19 07:37 UTC
If ownCloud is used in companys etc with many sharings and similare architecture for all users it would be usefull to be able to mark files/folders within a shared folder not to be shared.

**Comment by hubearth** [comment] 2017-01-18 02:15
+1. I know there are work around, but the beauty of Owncloud is its simplicity. Adding a feature to unshare a subfolder would help to keep a good structure while restricting specific parts to some users only.

**Comment by webmarka** [comment] 2017-02-23 22:32
What about it as of now? Is this feature planned? I think it's a crucial point for being free to share as we want to... there is also things we don't want to share with every one! 

As a group admin / user now with OC I have to figure a complex folders naming hierarchy and taxonomy to be able to fulfil my needs in regards of group and users access...

**Comment by hodyroff** [comment] 2017-04-22 10:41
Right now we have full inheritance of rights downstream. Thinking about fully flexible folders but those would be a different category and likely have multiple owners as well.

**Comment by hodyroff** [comment] 2017-04-22 10:42
Duplicate of https://github.com/owncloud/core/issues/4579

**Closed by hodyroff** 2017-04-22 10:42 UTC
Labels: enhancement
