### ISSUE TITLE
Not all subfolders are shown of a shared folder

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/core#21675] opened 2016-01-13 08:01 UTC
Hello,

we are using very successfully owncloud in our intranet.

Now I did share a folder with 34 subfolders via public link only for the download of some installation files. owncloud only displays maximum 19 of the 34 subfolders depending of the fonts size. I took a look into the html source and in that table with the id "filestable" there are lines only for the first 19 subfolders.

Currently as a workaround I can switch the sorting of the subfolders from ascending to descending. But what, if the count of subfolders increases?

Is there a limitation of the count of subfolders I have to take care about? Or is that a bug?

Greetings Ingo

**Comment by RealRancor** [comment] 2016-01-13 08:07
Could be a duplicate of https://github.com/owncloud/core/issues/21373 or https://github.com/owncloud/core/issues/21203

**Comment by PVince81** [comment] 2016-01-13 08:49
Closing as duplicate.

If you think it's a different issue, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

**Closed by PVince81** 2016-01-13 08:49 UTC
