### ISSUE TITLE
After upgrading from 8.0.0-19.1 to 8.0.0-20.1 owncloud does not leave maintenance screen

### ISSUE THREAD

**Issue by tps800** [owncloud/core#14184] opened 2015-02-13 07:52 UTC
After upgrading from 8.0.0-19.1 to 8.0.0-20.1 OwnCloud does not leave maintenance screen. Within the installed docs: /usr/share/doc/owncloud/README and /usr/share/doc/owncloud/README.SELinux are no hints what to do next after the packages are installed. You are lost.

**Comment by tps800** [comment] 2015-02-13 08:03
Looks like the automatic upgrade procedure does not remove "'maintenance' => true" from config/config.php after successfully upgrading owncloud.

**Comment by tps800** [comment] 2015-02-13 08:07
Workaround: change "'maintenance' => true" to "'maintenance' => false", rerun "sudo -u apache php occ upgrade" (should indicate Owncloud being already the latest version), then restart your http-server: service httpd restart (fedora, centos, oraclelinux).
Afterwards everything should be fine again.

**Comment by pelicanmedia** [comment] 2015-02-13 18:13
@tps800 You should apply for a position at ownCloud! As they don't seem to have a clue!
Thank you for your answer, been on this all day !!

**Comment by tps800** [comment] 2015-02-19 09:27
Same upgrading from 8.0.0-20.1 to 8.0.0-22.1. This time I had the chance to find out why "'maintenance' => true" is not replaced: just because the web-server could not be restarted!
You should not assume "service httpd restart" working in any case, because it might be the server is restarted with its own script, because there are more than only one instance of httpd, lighttpd, nginx, roxen, ... running, started by there own scripts.

**Comment by pelicanmedia** [comment] 2015-02-19 09:31
I was just looking up this post to fix my OC, again ! As I have just had the same issue.
Why all of a sudden is it doing this though ? Had no issues (like this) in v7 ?!

**Comment by jancborchardt** [comment] 2015-02-19 12:37
@pelicanmedia how about being less sarcastic towards people who develop open source software you can freely use? Thanks.

**Comment by pelicanmedia** [comment] 2015-02-19 12:47
@jancborchardt Then they should test the software thoroughly before releasing it. I use OC in a commercial environment, as do many other people.
Also they should listen to the community when they report an issue, to address it. Not release another update that causes they same problem.
I fully understand the idea behind open source and the non cost to everyone. But as said above, it should be tested before released. Thanks.

**Comment by jancborchardt** [comment] 2015-02-19 16:46
@pelicanmedia we’re doing our best to test it. You can do your part by testing release candidates – please sign up to the [testpilots mailing list](https://mailman.owncloud.org/mailman/listinfo/testpilots) so you get notified when there’s something to test. ([More information on the testpilots program here.](http://doc.owncloud.org/server/8.0/developer_manual/testing/index.html))
Thanks for being a positive part of the community!

**Comment by tps800** [comment] 2015-02-20 10:35
@jancborchardt, @pelicanmedia: pelicanmedia you are right. 8.0.0-22.1 is not a released version, it is a release candidate. It is fine to use these, but do not await all errors found and removed within such software. But normally you'll do not find serious errors within release candidates.
This bug isn't serious, but annoying. But it is quite simple to know about it and fix it by hand. The final release (8.0.1) thou shouldn't have this bug any more!

**Comment by tps800** [comment] 2015-02-23 13:09
Same with 8.0.0-22.1 to 8.0.0-23.1 does stop httpd but does not start it again.
Doesn't clear maintenance mode.

**Comment by tps800** [comment] 2015-03-01 21:49
Going from 8.0.0-2.1 to 8.0.0-24.1 now clears maintenance mode, but does not restart httpd again after applying updates.

**Comment by DeepDiver1975** [comment] 2015-03-02 08:26
@jnfrmarks packaging related - please have a look - THX

**Comment by jnfrmarks** [comment] 2015-03-02 12:30
Should Juergen look at this if it's packaging related?

**Comment by DeepDiver1975** [comment] 2015-03-02 12:35
> Should Juergen look at this if it's packaging related?

yes @jnweiger - THX

**Comment by jvillafanez** [comment] 2015-03-02 14:01
I've checked with an upgrade from 8.0.0 to 8.0.1 and it worked fine. It was a very basic installation so the upgrade was fast.

For big installations, it's recommended to upgrade through command line with the `occ upgrade` command which is less likely to hit a timeout. This could be the cause of the issue.

**Comment by MorrisJobke** [comment] 2015-03-18 16:20
@DeepDiver1975 @jnfrmarks @jvillafanez What is the state of this? I guess it can be closed.

**Comment by jnfrmarks** [comment] 2015-03-18 17:15
@MorrisJobke 

Is there a change that needs to be validated?  It looks like @jvillafanez tested and did not see any issues.  I'm not sure if @jnweiger found any issues when he did his analysis.  We did not see this in our final package testing.

**Comment by jnweiger** [comment] 2015-03-18 17:25
Did someone explicitly test the update from 8.0.0 to 8.0.2 -- maybe there is something special here.

**Comment by MorrisJobke** [comment] 2015-03-23 13:40
cc @jnfrmarks

**Comment by enoch85** [comment] 2015-03-28 12:48
ping @jnfrmarks

**Comment by jnfrmarks** [comment] 2015-03-30 13:13
What is needed from me?

**Comment by MorrisJobke** [comment] 2015-03-30 14:37
@jnfrmarks Ah okay ... then we can close this. You already verified, that this doesn't occur anymore.

**Closed by MorrisJobke** 2015-03-30 14:37 UTC
Labels: bug, packaging, update
