### ISSUE TITLE
Don't show incompatible app updates

### ISSUE THREAD

**Issue by ghost** [owncloud/core#25782] opened 2016-08-12 08:33 UTC
### Steps to reproduce
1. Have ownCloud 9.0.4 installed
2. Have News App 8.8.0 installed
3. Get incompatible News App 9.0.0 offered
### Expected behaviour

Incompatible News App 9.0.0 shouldn't be offered
### Actual behaviour

Incompatible News App 9.0.0 is offered
### Server configuration

**ownCloud version:** (see ownCloud admin page) 9.0.4

When having a look at the appstore URL the news app is not offered for 9.0.x:

https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=920&approved=all

and only for 9.1.x:

https://api.owncloud.com/v1/content/data?version=9x1x0x0&categories=920&approved=all

Still ownCloud thinks that the News App 9.0.0 is compatible as seen on the following screenshot:

![screenshot - 12 08 2016 - 10 29 33](https://cloud.githubusercontent.com/assets/2248459/17617012/da0a49c6-6077-11e6-9f7f-5d4fe43fa797.png)

When hitting the "Update to 9.0.0" button the following text is shown:

> App can't be installed because it is not compatible with this version of ownCloud

**Comment by DeepDiver1975** [comment] 2016-08-12 08:39
bloody appstore ......

**Comment by RealRancor** [comment] 2016-08-12 09:10
It looks to me more like an issue in ownCloud itself rather then in the appstore or am i wrong?

I don't now the URL oC itself is requesting to check for the app updates but the appstore itself is not reporting the News App 9.0.0 for ownCloud 9.0.4

**Comment by PVince81** [comment] 2016-08-12 11:33
Hmm, without looking at the code I guess that the reason you see the "News" app in the list is because it's already installed, not because the app store offers it. So the logic needs to be adjusted that if there is an incompatible update, don't show it.

**Comment by PVince81** [comment] 2016-10-20 09:03
@PhilippSchaffrath wanna have a try fixing this ?

**Comment by PhilippSchaffrath** [comment] 2016-10-20 10:49
@PVince81 sure, i'll give it a try!

**Comment by RealRancor** [comment] 2016-10-25 10:17
@PhilippSchaffrath Unfortunately the news app is not available at https://apps.owncloud.com anymore as it was removed from there. So no, i can't reproduce this anymore as the prerequisite is missing.

However this doesn't mean that the bug itself is gone :-)

**Comment by PhilippSchaffrath** [comment] 2016-10-25 11:11
In `9.0.4` the AppList only checks if there is a later version of the app in general.
https://github.com/owncloud/core/blob/v9.0.4/lib/private/ocsclient.php#L172

It's getting this information from Links like this: https://api.owncloud.com/v1/content/data/168040
Those currently all fail.

Going to take a look at master next.

**Comment by PVince81** [comment] 2016-11-30 08:59
@DeepDiver1975 will this code be reused for the market ? If not then might not be worth spending time to fix it but need to make sure the approach here is used for the market too ?

**Comment by PhilippSchaffrath** [comment] 2016-11-30 14:48
I stopped looking into this issue because it's currently not reproducible. This will probably all be new in the new market.

**Comment by PVince81** [comment] 2017-02-06 10:12
Closing this then

**Closed by PVince81** 2017-02-06 10:12 UTC
Labels: bug, junior job, settings:apps, sev3-medium
