### ISSUE TITLE
Operation canceled: connection closed

### ISSUE THREAD

**Issue by LaurentLM2I** [owncloud/core#22957] opened 2016-03-08 16:31 UTC
**Client:** Version 2.1.1 (build 5837) sur machine Windows 10 
**OR**
**Client:** Version 2.1.0 (build 5683) sur machine Windows 10
**Server:** 8.2.2 (stable)
**Machine server:** Debian Linux 8.3
**Apache2** Version 2.4.10
**PHP** Version 5.6.17-0+deb8u1
**MySQL** Version 5.5.47 

**Error message when the client sync:**
```
26/02/2016 15:28:25, Création/Blois_MySQL.xlsx, ownCloud,Operation canceled
26/02/2016 15:28:25, Création/Blois BSM 1.xlsx, ownCloud,Connexion fermée
26/02/2016 15:28:23, Création/Maintenance 2016.pdf, ownCloud,Conserver sur liste noire : Error downloading https://SERVEUR/owncloud/remote.php/web ... aintenance 2016.pdf - server replied: Bad Request (expected filesize 29954 got 8192)

```

**Server logs:**
```
{"reqId":"qpoxfH+DfcfkfuImTQCk","remoteAddr":"IP","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 400 expected filesize 5242880 got 8192","Exception":"Sabre\DAV\Exception\BadRequest","Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/connector/sabre/file.php(101): OC\Connector\Sabre\File->createFileChunked(Resource id #30)
#1 /var/www/owncloud/lib/private/connector/sabre/directory.php(115): OC\Connector\Sabre\File->put(Resource id #30)
#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1053): OC\Connector\Sabre\Directory->createFile('Blois_MySQL.xls...', Resource id #30)
#3 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('Création/...', Resource id #30, NULL)
#4 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#5 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#6 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#7 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#8 /var/www/owncloud/apps/files/appinfo/remote.php(56): Sabre\DAV\Server->exec()
#9 /var/www/owncloud/remote.php(137): require_once('/var/www/ownclo...')
#10 {main}","File":"/var/www/owncloud/lib/private/connector/sabre/file.php","Line":361}","level":4,"time":"2016-02-26T13:47:55+00:00"}
{"reqId":"MsZWEoFnwpcxhYugBGXU","remoteAddr":"IP","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 400 expected filesize 5242880 got 8192","Exception":"Sabre\DAV\Exception\BadRequest","Code":0,"Trace":"
#0 /var/www/owncloud/lib/private/connector/sabre/file.php(101): OC\Connector\Sabre\File->createFileChunked(Resource id #30)
#1 /var/www/owncloud/lib/private/connector/sabre/directory.php(115): OC\Connector\Sabre\File->put(Resource id #30)
#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1053): OC\Connector\Sabre\Directory->createFile('Blois BSM 1.xls...', Resource id #30)
#3 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('Création/...', Resource id #30, NULL)
#4 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#5 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#6 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#7 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#8 /var/www/owncloud/apps/files/appinfo/remote.php(56): Sabre\DAV\Server->exec()
#9 /var/www/owncloud/remote.php(137): require_once('/var/www/ownclo...')
#10 {main}","File":"/var/www/owncloud/lib/private/connector/sabre/file.php","Line":361}","level":4,"time":"2016-02-26T13:47:56+00:00"}
{"reqId":"XcYRnW0qBv3Lj6OUEf4g","remoteAddr":"IP","app":"webdav","message":"Exception: {"Message":"HTTP/1.1 400 expected filesize 29954 got 8192","Exception":"Sabre\DAV\Exception\BadRequest","Code":0,"Trace":"
#0/var/www/owncloud/lib/private/connector/sabre/directory.php(115): OC\Connector\Sabre\File->put(Resource id #30)
#1 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1053): OC\Connector\Sabre\Directory->createFile('Maintenance...', Resource id #30)
#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(513): Sabre\DAV\Server->createFile('Création/...', Resource id #30, NULL)
#3 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#4 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#5 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#6 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#7 /var/www/owncloud/apps/files/appinfo/remote.php(56): Sabre\DAV\Server->exec()
#8 /var/www/owncloud/remote.php(137): require_once('/var/www/ownclo...')
#9 {main}","File":"/var/www/owncloud/lib/private/connector/sabre/file.php","Line":139}","level":4,"time":"2016-02-26T14:28:57+00:00"}

```

**I had to look this post:** https://forum.owncloud.org/viewtopic.php?f=17&t=32517

**I just read it in detail and tested the following changes (without success):**
1. A bug in Apache https://github.com/owncloud/core/issues ... -148380791
2. A too small "SSLRenegBufferSize" Apache setting https://github.com/owncloud/core/issues ... t-90508358
3. A too small "LimitRequestBody" Apache setting https://github.com/owncloud/core/issues ... t-68443113
4. Timeouts on server side https://github.com/owncloud/core/issues ... t-85709557
5. Just a temporary network issue https://github.com/owncloud/core/issues ... t-86418646

**and:**
1) owncloud server> as administrator> I have set all of the users to quota = UNLIMITED
2) The Following option added to my apache config: 10486000 SSLRenegBufferSize
the apache config Was Located in /etc/apache2/conf.d/owncloud.conf, and is shown below:

```
---------------------------------- ------------- Conf.d ----------------------
Alias ​​/ owncloud "/var/www/owncloud/"

SSLRenegBufferSize 10486000
Options + FollowSymLinks
AllowOverride All

<IfModule mod_dav.c>
  Dav off
</ IfModule>

SetEnv HOME /var/www/owncloud
SetEnv HTTP_HOME /var/www/owncloud

# Just in case if .htaccess gets disabled
Require all denied
----------------------------- ----------------- End conf.d -----------------
```

3) etc / php5 / apache2 / php.ini has-been changed from 2M to 16G: upload_max_filesize = 16G

4) /etc/apache2/httpd.conf point to server-tuning.conf Where I ensured
KeepAlive On
MaxKeepAliveRequests 500
KeepAliveTimeout 500

Restarted server: apache2 restart systemctl

**/etc/apache2/conf-available/owncloud.conf:**
```
Alias /owncloud "/var/www/owncloud/"
<Directory /var/www/owncloud/>
SSLRenegBufferSize 10486000
Options +FollowSymLinks
AllowOverride All
SetEnv MOD_X_SENDFILE_ENABLED 1
XSendFile On
XSendFilePath /tmp/
</Directory>

```

**/etc/apache2/sites-available/SERVEUR.conf:**
```
<VirtualHost *:443>
DocumentRoot /var/www/owncloud
ServerName SERVEUR
<IfModule mod_headers.c>
Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>


SSLEngine on
SSLOptions +StdEnvVars
SSLStrictSNIVHostCheck off

SSLCertificateFile /etc/apache2/ssl/SERVEUR.crt
SSLCertificateKeyFile /etc/apache2/ssl/SERVEUR.key

</VirtualHost>

```

**/var/www/owncloud/config/config.php:**
```
<?php
$CONFIG = array (
'instanceid' => 'xxxxxxxxxxxxxxx',
'passwordsalt' => 'xxxxxxxxxxxxxxx',
'secret' => 'xxxxxxxxxxxxxxx',
'trusted_domains' => 
array (
0 => 'SERVEUR',
1 => 'IP',
),
'datadirectory' => '/var/www/owncloud/data',
'overwrite.cli.url' => 'https://SERVEUR/owncloud',
'dbtype' => 'mysql',
'version' => '8.2.2.2',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => '',
'dbuser' => 'cloudAdmin',
'dbpassword' => 'xxxxxxxxxxxxxxx',
'logtimezone' => 'UTC',
'installed' => true,
'filelocking.enabled' => 'true',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'redis' => 
array (
'host' => 'localhost',
'port' => 6379,
'timeout' => 500,
'password' => '',
'dbindex' => 0,
),
'memcache.local' => '\\OC\\Memcache\\APCu',
'theme' => '',
'log_type' => 'owncloud',
'logfile' => '/var/www/owncloud/data/owncloud.log',

'loglevel' => 0,
'log_rotate_size' => 10485760,

'maintenance' => false,
);
```

**## impossible to synchronize new files. but if there are no new files, it works correctly ...**

**Comment by RealRancor** [comment] 2016-03-08 16:38
Very likely a duplicate of the still open issue here: https://github.com/owncloud/core/issues/9832

**Comment by LaurentLM2I** [comment] 2016-03-08 16:44
Sorry, I copy my post on the right subject and I close this one.

**Closed** 2016-03-08 17:28 UTC
