### ISSUE TITLE
Ubuntu package using apache2 is installed in an old path

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13900] opened 2015-02-04 17:10 UTC
### Steps to reproduce
Install owncloud package in Ubuntu >14.XX:

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0/xUbuntu_14.10/ /' >> /etc/apt/sources.list.d/owncloud.list"
sudo apt-get update
sudo apt-get install owncloud

### Expected behaviour
apache2 in this ubuntu version uses /var/www/html 
Owncloud is located in /var/www/html/owncloud

### Actual behaviour
Owncloud is located in /var/www

**Comment by karlitschek** [comment] 2015-02-04 17:20
@jnweiger Please have a look. Marking this as a showstopper

**Comment by DeepDiver1975** [comment] 2015-02-04 20:06
> Owncloud is located in /var/www

as long as the apache config is properly setup and  owncloud is served I see no big issue with this.
Finally it's a bit tricky to do this right across all version if Debian and Ubuntu because the layout of /var/www was changed some point in the past.

**Comment by DeepDiver1975** [comment] 2015-02-04 20:39
but this is critical:

````
Setting up libhtml-template-perl (2.95-1) ...
Setting up owncloud-server (8.0.0~RC1-3) ...
Setting up owncloud-config-apache (8.0.0~RC1-3) ...
ERROR: /etc/apache2/conf-enabled/owncloud.conf is a dangling symlink!
ERROR: Conf owncloud does not exist!
 * Reloading web server apache2                                                                                                                                                                                     * 
 * The apache2 configtest failed. Not doing anything.
Output of config test was:
apache2: Syntax error on line 216 of /etc/apache2/apache2.conf: Could not open configuration file /etc/apache2/conf-enabled/owncloud.conf: No such file or directory
Action 'configtest' failed.
The Apache error log may have more information.

**Comment by DeepDiver1975** [comment] 2015-02-04 20:50
Issue seems to be in here

https://build.opensuse.org/package/view_file/isv:ownCloud:community:8.0/owncloud/debian.owncloud-config-apache.install?expand=1

````
etc/apache2/conf*/owncloud.conf
.htaccess /var/www/owncloud/.htaccess

**Comment by SergioBertolinSG** [comment] 2015-02-05 07:54
@DeepDiver1975 I agree this is just a detail which can be avoided with apache setup. But I am thinking about people just trying owncloud for the first time in the one of the most popular linux distributions. If they install it and it requires more setup, maybe they will dislike it.

**Comment by SergioBertolinSG** [comment] 2015-02-05 08:54
@DeepDiver1975 about the config problem, after testing in Debian I've opened #13914

**Comment by DeepDiver1975** [comment] 2015-02-05 16:11
this is not really a showstopper - the old packages got installed in var/www as well. no regression - nothing

**Comment by karlitschek** [comment] 2015-02-06 00:51
agreed. still a broken package.

**Comment by jnweiger** [comment] 2015-02-10 14:44
the old location is as designed. The update issue is handled at https://github.com/owncloud/core/issues/13992 the package is no longer broken.

**Closed by jnweiger** 2015-02-10 14:44 UTC
Labels: packaging
