### ISSUE TITLE
A new version is available: {{newVersion}}

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#20720] opened 2015-11-25 03:06 UTC
My beta version OC 8.2.1 shows this in the Admin page:
```
A new version is available: {{newVersion}}
```
![screen shot 2015-11-25 at 11 04 15](https://cloud.githubusercontent.com/assets/2703373/11387353/91db897a-9364-11e5-8bfd-2df4aa6157a9.png)

**Comment by RealRancor** [comment] 2015-11-25 05:22
Duplicate of https://github.com/owncloud/updater/issues/184

**Closed** 2015-11-25 07:20 UTC
