### ISSUE TITLE
External storages not listed when going back from other part of the menu

### ISSUE THREAD

**Issue by davicente** [owncloud/core#27665] opened 2017-04-18 16:16 UTC
### Steps to reproduce
1. Go to External storage 
2. Go to another part of the menu (e.g.: All files)
3. Go back to External storage

### Expected behaviour
List the external storages

### Actual behaviour
Noone of the external storages are shown, only the number of them

### Server configuration
Operating system:
Ubuntu 14.04

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version:
""9.1.0.5","versionstring":"9.1.0 beta 1","edition":""}

Updated from an older ownCloud or fresh install:
Fresh

Are you using external storage, if yes which one: local/smb/sftp/...
Yes: Local, Dropbox

Are you using encryption:
No

![localmounts](https://cloud.githubusercontent.com/assets/752240/25141175/03e335be-2463-11e7-9bef-d913ebc4d585.gif)

**Comment by hodyroff** [comment] 2017-04-18 17:51
Do I see it right that they are shown, it just takes a little bit of time?

**Comment by davicente** [comment] 2017-04-19 06:19
It's not a question of time, it needs to be reordered clicking in some of the selectors above to appear again.

**Comment by PVince81** [comment] 2017-04-20 14:49
Duplicate of https://github.com/owncloud/core/issues/27697

**Closed by PVince81** 2017-04-20 14:49 UTC
Labels: bug
