### ISSUE TITLE
Download of a folder does not work: zipfile claims to be last disk of a multi-part archive

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#13595] opened 2015-01-22 13:39 UTC
Clicking on the "Download" link on a folder in the owncloud web interface downloads a unusable ZIP file as you can see below:

$ unzip -t Backups.zip
Archive:  Backups.zip
warning [Backups.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
error [Backups.zip]:  missing 8588437314 bytes in zipfile
  (attempting to process anyway)
error [Backups.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

This happens with any folders of any sizes. I am using owncloud 7.0.4 with PostgreSQL 9.1.4, nginx 1.6.2 and PHP 5.5.20.

Any ideas? or is this a bug?

**Comment by hostingnuggets** [comment] 2015-01-22 14:02
I presume this is exactly the same problem as reported in #10001

I should have mentioned before that my unzip attempt is on Mac OS X.

**Comment by LukasReschke** [comment] 2015-01-22 14:02
Closing as duplicate of said issue.

**Closed by LukasReschke** 2015-01-22 14:02 UTC
