### ISSUE TITLE
Difficult to read sync error message written to server log file

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13133] opened 2015-01-06 16:31 UTC
I'm running owncloudcmd to sync a file.  There's an error in the sync resulting in this very difficult to read message being written to the server log. There are way too many "\" to understand what the message is.

``` json
{"reqId":"7083eda4aac1fb047d720641ae0b2ee0",
"remoteAddr":"172.18.5.120",
"app":"webdav",
"message":"Exception: {\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(888): OC_Connector_Sabre_File->put(Resource id #129)\\n#1 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('TEST_FILE_MODIF...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'TEST_FILE_MODIF...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'TEST_FILE_MODIF...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":133}",
"level":4,
"time":"2015-01-06T16:26:15+00:00",
"method":"PUT",
"url":"\/owncloud\/remote.php\/webdav\/TEST_FILE_MODIFIED_USER_SHARE.txt"}
```
### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.0 alpha 1 (daily) Build:2015-01-05T04:12:18+00:00

**Comment by karlitschek** [comment] 2015-01-06 17:00
@icewind1991

**Comment by DeepDiver1975** [comment] 2015-01-06 17:06
@jnfrmarks are there any further error messages available? THX

**Comment by jnfrmarks** [comment] 2015-01-06 17:35
@DeepDiver1975 

I have the server log file if you want me to send it to you.  

This was caused from setting a file share to read only, having the user modify the file locally, and then try to sync via owncloudcmd.  

I'm assuming that the error is itself is valid and that the format of the error stinks.

**Comment by DeepDiver1975** [comment] 2015-01-06 18:46
> This was caused from setting a file share to read only, having the user modify the file locally, and then try to sync via owncloudcmd.

So TEST_FILE_MODIFIED_USER_SHARE.txt is a file shared by another user read only?

Hmm - the error message should really be different.

Do you have reproduction steps for me? THX

**Comment by nickvergessen** [comment] 2015-01-07 10:28
Cleaned error:
```json
Exception:
{
	"Message":"Could not rename part file to final file",
	"Code":0,
	"Trace":"#0 /var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(888): OC_Connector_Sabre_File->put(Resource id #129
		#1 [internal function]: Sabre\\DAV\\Server->httpPut('TEST_FILE_MODIF...'
		#2 /var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'TEST_FILE_MODIF...'
		#3 /var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PUT', 'TEST_FILE_MODIF...'
		#4 /var/www/html/owncloud/apps/files/appinfo/remote.php(61): Sabre\\DAV\\Server->exec(
		#5 /var/www/html/owncloud/remote.php(54): require_once('/var/www/html/o...'
		#6 {main}",
	"File":"/var/www/html/owncloud/lib/private/connector/sabre/file.php",
	"Line":133
}

**Comment by PVince81** [comment] 2015-01-09 10:50
The reason why error messages are hard to read in the log is because the log is in JSON format, so many characters need to be escaped.

**Comment by PVince81** [comment] 2015-08-03 10:06
Changing to enhancement => improve readability / provide alternative log format that is better readable.

**Comment by hodyroff** [comment] 2017-12-11 11:29
JSON is fine for now. Closing.

**Closed by hodyroff** 2017-12-11 11:29 UTC
Labels: comp:core, enhancement
