### ISSUE TITLE
occ files:scan's memory consumption grows with amount of files scanned

### ISSUE THREAD

**Issue by danimo** [owncloud/core#19115] opened 2015-09-17 07:39 UTC
## Expected behavior

The memory consumption of the scanner is constant.

## Actual behavior

The memory consumption of the scanner grows with the amount of files, requiring to increase the memory limit again and again for users with a large amount of data.

## Details

ownCloud: 8.1.3
Total amount of file in user's share: 45308
Memory required: > 256 MB, < 512 MB

**Comment by karlitschek** [comment] 2015-09-17 09:30
@icewind1991

**Comment by oparoz** [comment] 2015-10-03 17:31
It's by design https://github.com/owncloud/core/pull/10922.
All the information is collected first, before being sent to the database, in order to speed up the process.
So the solution seems to be to give large amounts of memory (in the GB range) to the cli.

**Comment by oparoz** [comment] 2015-10-03 17:35
I see one possible enhancement: Collect structure data first and launch non-recursive scans from the bottom of the tree. Each folder update will be committed separately.

**Comment by PVince81** [comment] 2016-03-03 14:49
This could be due to stat caches.

When scanning a local storage, PHP will store stuff in its stat cache. Not sure if that one is capped.

Regarding SMB, we added a cap to the stat cache recently: https://github.com/owncloud/core/pull/21648

If this is still happening in 8.2.2 or 9.0 RC1, please reopen.

**Closed by PVince81** 2016-03-03 14:49 UTC
Labels: bug
