### ISSUE TITLE
Problem with override

### ISSUE THREAD

**Issue by elfeffe** [owncloud/core#18243] opened 2015-08-12 17:32 UTC
I'm trying to override
/settings/templates/users/part.userlist.php

With
/themes/MyTheme/core/settings/templates/users/part.userlist.php
Css is overriding, but I can't override php

The same with

/settings/js/users/users.js
and
/themes/MyTheme/core/settings/js/users/users.js

Is this a bug? Or I'm doing something wrong?

**Comment by karlitschek** [comment] 2015-08-12 17:37
@jancborchardt can you check please?

**Comment by jancborchardt** [comment] 2015-08-12 17:44
@schiesbn might be a better person of contact for this. :)

@elfeffe note that we generally recommend against overriding PHP templates or JS files, as they will likely change with upgrades and necessitate a change in your theme then.

Also, can you provide any logs or more info. Would be good if you can fill out the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md).

**Comment by elfeffe** [comment] 2015-08-12 17:53
I need to override because delete users is too easy, and then lose files is too easy too.
There must be an option of keep the files, or at least to disable user deletion (let only disable users ad Jira does).
I know I will have to update php and js most of the times I upgrade, but it's better than touch core files.

About the template:
Log is pretty big, what I have to look for? Because it's full of other information too.
I'm using the .deb version in Ubuntu 14.04
Mysql
Redis

I have some errors in firebug
```
4
Content Security Policy: Las opciones para esta página han bloqueado la carga de un recurso en self (script-src http://cloud.web.com 'unsafe-eval').
	
onsubmit attribute on DIV element
```
The translation is like "The options on this page had blocked the load of a resourse in self"

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.web.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.web.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'mail_smtpmode' => 'php',
  'loglevel' => 0,
'theme' => 'MyTheme',
);

**Comment by elfeffe** [comment] 2015-08-12 17:58
Custom CSS and Favicon loads from the theme, but I can't override.

**Comment by elfeffe** [comment] 2015-08-12 18:01
It works, correct folder structure is
 /themes/MyTheme/settings/templates/users/part.userlist.php

not 
 /themes/MyTheme/core/settings/templates/users/part.userlist.php

sorry

**Comment by PVince81** [comment] 2016-03-02 09:40
@LukasReschke @icewind1991 any idea why PHP overriding of templates wouldn't work ?

**Comment by PVince81** [comment] 2016-11-30 11:01
@PhilippSchaffrath any idea ?

**Comment by PhilippSchaffrath** [comment] 2016-11-30 14:39
Will test this, but might be already fixed with the new theming through apps approach. (because of the directory naming inconsistency that we fixed there)

**Comment by PhilippSchaffrath** [comment] 2016-12-01 07:23
Loading templates uses `OC_Templates:inc` which ultimately ignores themes. Seems like someone started implementing theme-support there, but never finished it. I will fix this.

**Comment by PhilippSchaffrath** [comment] 2016-12-02 11:36
Fixed in #26757 and now works as expected.

**Comment by DeepDiver1975** [comment] 2016-12-02 11:37
@PhilippSchaffrath issues are to be closed as soon as the pr is merged. THX

**Comment by PhilippSchaffrath** [comment] 2016-12-02 11:38
@DeepDiver1975 ups sry, thought a reference would be enough. My fault.

**Comment by DeepDiver1975** [comment] 2016-12-02 11:39
> @DeepDiver1975 ups sry, thought a reference would be enough. My fault.

no prob at all - thx

**Comment by PVince81** [comment] 2016-12-03 14:42
From looking at the PR and the code it looks like this was never supported before.
But the question is whether it was by design or not... Anyway, starting with 9.2 overriding templates will be supported.

**Closed** 2016-12-03 14:41 UTC
Labels: bug, feature:theming, sev3-medium
