### ISSUE TITLE
Exclude additional files from integrity check

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#27102] opened 2017-02-07 15:53 UTC
![bildschirmfoto von 2017-02-07 16-50-51](https://cloud.githubusercontent.com/assets/1005065/22698716/a15bc706-ed55-11e6-9c03-22834cba51e9.png)

**Comment by dalenoe** [comment] 2017-02-07 17:16
Is there a way to make the integrity check exclude files (that I specify), or how would I go about getting the file I created signed.

**Comment by kdslkdsaldsal** [comment] 2017-02-07 17:33
@dalenoe There are two possibilities:

1. The file needs to be added to the following array in the next official release: https://github.com/owncloud/core/blob/v9.1.4/lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php#L38

2. https://github.com/owncloud/core/issues/23186 needs to be implemented

**Comment by dalenoe** [comment] 2017-02-07 17:49
Thanks @kdslkdsaldsal for the update. Looks like I play the waiting game.. :(

**Comment by dalenoe** [comment] 2017-02-07 17:51
@kdslkdsaldsal If I manually added the file to that ExcludeFileByNameFilterIterator.php, will that accomplish what I'm looking for? I'm not expecting owncloud to add my custom script to the excludes..

**Comment by kdslkdsaldsal** [comment] 2017-02-07 18:04
This would trigger the integrity check of ownCloud itself as you're modifying an ownCloud internal file.

**Comment by PVince81** [comment] 2017-02-07 18:29
Closing as duplicate of https://github.com/owncloud/core/issues/23186.

This should be implemented as part of https://github.com/owncloud/core/issues/23186 to make this configurable.

**Closed by PVince81** 2017-02-07 18:29 UTC
