### ISSUE TITLE
Tipsy does not close on shared folder

### ISSUE THREAD

**Issue by baboupc** [owncloud/core#14094] opened 2015-02-11 09:51 UTC
Hello,

Tipsy tooltip stays forever on screen. (see attached capture)
![capture d ecran 2015-02-11 a 10 48 28](https://cloud.githubusercontent.com/assets/8754369/6144841/d6605c76-b1db-11e4-9729-c7b33305741e.png)

Tested with Owncloud 8 and Safari/Firefox

**Comment by karlitschek** [comment] 2015-02-11 15:13
@jancborchardt any idea?

**Comment by jancborchardt** [comment] 2015-02-12 16:13
Have to call in @MorrisJobke or @PVince81 for JS wizardry.

**Comment by MorrisJobke** [comment] 2015-02-17 14:39
I didn't had a look yet.

**Comment by jancborchardt** [comment] 2015-02-17 14:55
Maybe these glitches would also be fixed by moving to the Bootstrap tooltip library? https://github.com/owncloud/core/issues/13646 cc @Raydiation

**Comment by PVince81** [comment] 2015-02-17 15:04
@baboupc please use the issue template and state your ownCloud version: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Also, how to reproduce the issue ? Do you simply hover on the file to make the tipsy appear then go away ? Or are you clicking something while the tooltip is there ?

**Comment by Raydiation** [comment] 2015-02-17 16:03
@jancborchardt yep, classic tipsy problem which I ran into when trying to use it in the News app. Was fixed with twitter bootstrap

**Comment by jancborchardt** [comment] 2015-03-27 15:23
@Raydiation are you interested in replacing Tipsy in core with the Bootstrap tooltip library as well? That would be quite cool. :)

**Comment by Raydiation** [comment] 2015-03-27 15:24
@jancborchardt no time ;D thesis due in 3 weeks

**Comment by Henni** [comment] 2015-06-22 14:48
I'm not able to reproduce this. When should the tipsy show up?

**Comment by jancborchardt** [comment] 2015-06-23 08:34
@Henni this seems to be in the »Shared with others« section in Files.

**Comment by Henni** [comment] 2015-06-23 12:42
@jancborchardt I don't see a tipsy by hovering over the entries in the "shared with others" section.
I tried this on the current master and on 8.0.4
Has it been removed our am I doing something wrong?

**Comment by jancborchardt** [comment] 2015-06-23 13:38
It was probably fixed meanwhile. I can’t remember if I could reproduce back then. So I’ll close this. @baboupc if this happens again please let us know! :)

**Closed by jancborchardt** 2015-06-23 13:38 UTC
Labels: app:files, bug, design, junior job, sharing
