### ISSUE TITLE
Renaming Folder delete contents

### ISSUE THREAD

**Issue by chmol** [owncloud/core#12210] opened 2014-11-16 13:21 UTC
### Steps to reproduce
Couldn't reproduce it again
1. rename folder on client file manager (thunar) from "abc 1" to "abc1"

### Expected behaviour
the new folder name is synced with OC
### Actual behaviour
Only 2 sub directory and 3 files  out of 60 are left on the client ( files that cannot be synced: invalid character).  The wastebasket is empty. No way to recover the files there

The directory is empty on the webpage. if renamed as before the file are seen but corrupted. When I attempt to download it : 
```File not found
Firefox can't find the file at https://myip/path/to/file```

The files are present on the server.

### Server configuration
**Operating system**: ubuntu 12.01

**Web server:*apache

**Database: don't know was a classic install

**PHP version:*5.3.10-1ubuntu3.6*

**ownCloud version:** 7.0.3

**Updated from an older ownCloud or fresh install:*installed last year updated since*

**List of activated apps:*activity, calendar contact, deleted files , document,encryption, 1st run, pdf, share , text, version, app framework, shorty*

**The content of config/config.php:**

```
Insert your config.php content here
?php
define('DEBUG',true);
$CONFIG = array (
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.0.3.4',
  'installed' => true,
  'loglevel' => '0',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 =>myip0',
  ),
  'appcodechecker' => false,
);

```


**Are you using encryption:** yes

### Client configuration
**Browser:*firefox*

**Operating system:*manjaro '(archlinux) -  OC client 1.7.0*

#### ownCloud log (data/owncloud.log)
```
i would gladly add it if i knew what is needed, the file is huge even for a day 
```

### Extra
Any hint on how recover the files would be welcomed too, I already asked here: http://forum.owncloud.org/viewtopic.php?f=29&t=24800 
and here how to un-encrypt http://forum.owncloud.org/viewtopic.php?f=23&t=14110

**Comment by PVince81** [comment] 2015-04-13 09:15
Likely to be a duplicate of https://github.com/owncloud/core/issues/13391

**Comment by PVince81** [comment] 2015-04-13 09:16
@chmol did you find whether the files still existed on disk ? You could try running `./occ files:scan --all` as the web server user to reindex them properly.

**Closed by PVince81** 2015-04-13 09:15 UTC
Labels: bug

**Comment by chmol** [comment] 2015-04-20 08:51
they are still present. 
running ./occ files:scan --all output after the scann : 
```
[Doctrine\DBAL\DBALException]                                                           
An exception occurred while executing 'DELETE FROM "oc_filecache" WHERE "fileid" = ?':  
                                                                                          
SQLSTATE[HY000]: General error: 5 database is locked  
```
```
File not found
Firefox can't find the file at https://myip/path/to/file```
```

probably non-relevant but I also get a lot of sync error with the client : 
``` 
The item is not synced because of previous errors: The server did not acknowledge the last chunk. (No e-tag were present)  
```
```
Error downloading https://myip/owncloud/remote.php/webdav/share-owncloud/ replied: Internal Server Error4 KiB   
```

I think I'll just reinstall the whole thing ...

**Comment by PVince81** [comment] 2015-04-20 09:46
If you do reinstall, I'd recommend using MySQL or PostgreSQL to avoid the locking issues.

This looks indeed like the problem in https://github.com/owncloud/core/issues/13391.
The database index was not updated fully/properly after moving the files, so there's a mismatch.
