### ISSUE TITLE
Can not share file via link from a shared folder / Error: "Default encryption module" is not able to read

### ISSUE THREAD

**Issue by js94x** [owncloud/core#23296] opened 2016-03-16 09:53 UTC
### Steps to reproduce
1. Encryption enabled
2. LDAP enabled (Active Directory)
3. Create folder with local admin account 
4. Share folder e.g. "CustomerX" with group "GroupX" in LDAP
5. Log in with an AD user that is member of group "GroupX"
6. Upload file in shared folder
7. Share this file via link
### Expected behaviour

Link opens and the file is available for download
### Actual behaviour

Link opens and an error message appears:
Encryption module "Default encryption module" is not able to read /admin/files/CustomerX/Hydragenas.jpg. Can not read this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
### Server configuration

**Operating system**: 
Ubuntu 14.04 LTS
**Web server:**
2.4.7-1ubuntu4.9
**Database:**
5.5.47-0ubuntu0.14.04.1
**PHP version:**
 5.5.9+dfsg-1ubuntu4.14

**ownCloud version:**
8.2.3

**Updated from an older ownCloud or fresh install:**
Updated from 8.1.6

**List of activated apps:**
Enabled:
- activity: 2.0.2
- encryption: 1.0.0
- files: 1.1.10
- files_pdfviewer: 0.7
- files_sharing: 0.6.3
- files_texteditor: 2.0
- files_versions: 1.0.6
- files_videoviewer: 0.1.3
- firstrunwizard: 1.1
- gallery: 0.6.0
- provisioning_api: 0.2
- templateeditor: 0.1
- updater: 0.6
- user_ldap: 0.6.1.1

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc1hvsjuh43r",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "xxx",
        "overwrite.cli.url": "xxx",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "xxx",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "theme": "xxx",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "info",
        "mail_smtpmode": "php",
        "mail_domain": "xxx",
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "log_type": "syslog",
        "log_authfailip": true,
        "syslog_tag": "ownCloud_xxx",
        "maintenance": false,
        "loglevel": 0
    }
}
#### Web server error log

Nothing
#### ownCloud log (data/owncloud.log)

`{"reqId":"JiViV7sLFHF88kHQNq08","remoteAddr":"xxx.xxx.xxx.xxx","app":"no app in context","message":"Encryption module \"Default encryption module\" is not able to read \/admin\/files\/CustomerX\/Hydragenas.jpg","level":2,"time":"2016-03-16T08:43:51+00:00"}`

**Comment by PVince81** [comment] 2016-03-21 13:24
@js94x can this user download the file correctly (the one you're trying to share with link) ?
Did that user logged in before you created the first share to the group ?

**Comment by js94x** [comment] 2016-03-29 09:09
@PVince81 

> can this user download the file correctly (the one you're trying to share with link) ?

The user who wants to share the file via link can download the file. 

> Did that user logged in before you created the first share to the group ?

Some group members have never logged in but the relevant user was already logged in.

admin: share folder x with group -> group members have access to folder x
group member: upload file in shared folder x -> share uploaded file via link -> error

During the troubleshooting I noticed that a share via link usually creates a file with the extension .sharekey in file-system. But unfortunately not in the case above.

**Comment by PVince81** [comment] 2016-03-30 09:49
@schiesbn trouble with link share and encryption

**Comment by PVince81** [comment] 2016-10-10 15:28
Is this still happening with 9.0.5 or 9.1.1 ?

**Comment by PVince81** [comment] 2017-01-13 16:54
Did the user wait for the upload to end before sharing the folder ? If yes, then this is a duplicate of https://github.com/owncloud/core/issues/26942

I suggest to create the link share before doing the upload just to be sure.

**Closed by PVince81** 2017-01-13 16:54 UTC
Labels: app:encryption, bug
