### ISSUE TITLE
"Error while sharing - error" when trying to share a file or directory on owncloud 7.0.4

### ISSUE THREAD

**Issue by tarator** [owncloud/core#13908] opened 2015-02-04 20:52 UTC
# Steps to reproduce
1. Login webinterface
2. Choose file, click on share
3. Select checkbox "Share link"

* Error appears on every file/directory and with every user.
* Previously shared links are still working.

# Expected behaviour
Menu for shared link should appear.

# Actual behaviour
Error pops up "Error while sharing"! 

This feature worked fine before (previous version!?)

![Screenshot of error message](https://cloud.githubusercontent.com/assets/8111200/5096577/a1897e24-6f73-11e4-8d10-f5d605a56610.jpg)

# Server configuration
* Operating system: openSUSE 13.2
* Web server: Apache
* Database: MySQL
* PHP version: 5.6.1
* ownCloud version: 7.0.4
* Updated from an older ownCloud or fresh install: Updated

### config.php
````php
<?php
$CONFIG = array (
  'datadirectory' => '/some/dir/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'installedat' => '1331491351.1509',
  'lastupdatedat' => '1331492839.8863',
  'dbname' => 'xxx',
  'dbhost' => 'xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => '3',
  'instanceid' => 'xxx',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'mydomain.com',
  ),
  'mail_from_address' => 'bla',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'foo.com',
  'secret' => 'xxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.example.com',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
);

````

* Are you using external storage, if yes which one: had some enabled, but disabled them for testing this bug
* Are you using encryption: no

# Client configuration
* Browser: Firefox 
* Operating system: Kubuntu 14.10

# Logs

### Web Server Logs:
nothing special

### owncloud.log
nothing, when I press the "Share link" checkbox.

But sometimes this appears:

````
{"app":"PHP","message":"Invalid argument supplied for foreach() at \/some\/path\/onserver\/public_html\/owncloud\/lib\/private\/files\/cache\/scanner.php#216","level":3,"time":"2015-02-04T20:56:26+00:00"}
````

````
{"app":"PHP","message":"PHP Startup: apc: Unable to initialize module\nModule compiled with module API=20100525\nPHP    compiled with module API=20131226\nThese options need to match\n at Unknown#0","level":3,"time":"2015-02-04T20:57:35+00:00"}
````

````
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"} 
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"} 
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}  
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}  
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}  
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}
````

**Comment by DeepDiver1975** [comment] 2015-02-04 21:08
> {"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"}

hmmm - doesn't look that good - @PVince81 @icewind1991 can I ask you to have a look? THX

**Comment by DeepDiver1975** [comment] 2015-02-04 21:08
scheduling for 8.1 for analysis

**Comment by PVince81** [comment] 2015-02-05 09:03
Do you use LDAP ?
Did you move the "data" directory recently ?

If not, please try the following queries:
1) Orphaned shares: `select * from oc_share where item_source not in (select fileid from oc_filecache)`
2) Check `select * from oc_storages` whether there are entries like "local::$datadir/$user" and where $datadir is the path to your data dir (or a wrong path).
3) Also check the storage 8: `select * from oc_storages where numeric_id=8` and its contents `select * from oc_filecache where storage=8`.

**Comment by tarator** [comment] 2015-02-05 12:27
@PVince81 :

* No, I don't use LDAP 
* I didn't move the data directory recently, I did before, but that's more than one year ago.
* The query `select * from oc_share where item_source not in (select fileid from oc_filecache)` returns an empty result.
* I have __eaxactly one__ result for the query `select * from oc_storages` which starts with `local::/some/dir/owncloud/data/some_username/` and the directory looks like the directory structure from my old server (which is not valid anymore). But I don't think this causes the problem, since I have the problem with very user.
* The value of the column `id` for `numeric_id=8` looks something like this: `351234563d4678abc12345a0fd123456` 
* There are some other lines in the table.
    * Some look like this: `351234563d4678abc12345a0fd123456`
    * Some like this: `dropbox::afj498vnq43huvj3haevhu/`
    * And for each user: `home::some_username`

Can I safely change the path to the correct one for the wrong `local::` entry?

**Comment by tarator** [comment] 2015-02-05 12:37
@PVince81 : I solved the problem with the missing share __8__
Now, the following error message is not appering anymore.
````
{"app":"files_sharing","message":"Unable to get mount for shared storage '8' user 'some_username'","level":3,"time":"2015-02-04T20:58:30+00:00"} 
````

The problem was, that the webserver-user had no writing permissions to the folder: `/some/dir/owncloud/data/some_username/lucene_index`

However, the Sharing problem is still __NOT__ fixed.

**Comment by PVince81** [comment] 2015-02-05 14:25
Ok, that sharing error might be something else.
Please try setting "loglevel" to 0 (debug) and try sharing again.
I hope something will pop up in the owncloud.log with more infos.

You could also check the web browser's network console and see what response is coming back from the ajax call to "share.php".

**Comment by tarator** [comment] 2015-02-05 16:30
## Request when clicking on the share checkbox:
* Request URI: https://myowncloud-domain.com/index.php/core/ajax/share.php
* Request-Method: POST
* Status-Code: 200 OK

### Request Header:
````
Host: myowncloud-domain.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: */*
Accept-Language: de-at,de-de;q=0.8,de;q=0.7,en-gb;q=0.5,en-us;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
requesttoken: 3fhwnwghpow98ph47gv
X-Requested-With: XMLHttpRequest
Referer: https://myowncloud-domain.com/index.php/apps/files/?dir=%2FBilder%2F12_04_05_Some_Filename
Content-Length: 136
Cookie: 508j3f48ßzmg9n8uu93hpri8bekpu1g0; oc_username=some_username; oc_token=d680uti6fglgzuftzidx65787t9redcfjg444; oc_remember_login=1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
````

### Request-Body
````
action=share&itemType=file&itemSource=100721&shareType=3&shareWith=&permissions=1&itemSourceName=2012-04-05+15.01.10.jpg&expirationDate=
````

### Answer:
one empty line, no data or error-message


And I think I found the Problem:
in the file `core/ajax/share.php` on line 30 the following condition makes the problem:
````
if (isset($_POST['shareType']) && isset($_POST['shareWith']) && isset($_POST['permissions'])) {
 ....
}
````
when I remove the second condition (`isset($_POST['shareWith'])`), the request works well.
As you can see above the parameter `shareWith=` is empty in my request. Maybe my PHP version handles `isset` differently?

**Comment by PVince81** [comment] 2015-02-05 16:34
Hmm... ownCloud should work fine with PHP 5.6 (sharing does work on my dev env on PHP 5.6.4).

I believe that `shareWith` is empty because you are creating a link share, is that correct ?

@schiesbn any idea why shareWith is empty and whether it is correct ?

**Comment by tarator** [comment] 2015-02-05 16:49
@PVince81 yes, I'm creating a link share. Maybe this feature has only be tested, when the file/folder has already be shared with another user?

I'm not a PHP programmer, but I think this might be a flaw in the `share.php` code, since `isset(...)` is `NULL` in my case.

http://php.net/manual/de/function.isset.php

**Comment by tarator** [comment] 2015-02-05 16:57
As I can see, the code from `share.php ` is not new! And I'm sure, the feature worked for me before! I can't tell you, if there has been an PHP update on my server lately, but maybe this is an PHP flaw? Maybe empty params from the request are not set in the _POST variable?

**Comment by transistor91** [comment] 2015-02-06 12:31
I had a similiar problem described in this issue: github.com/owncloud/core/issues/13720. Perhaps you can check your /var/log/message if you have suhosin errors?

**Comment by tarator** [comment] 2015-02-06 14:12
@transistor91 This is possible, since I activated suhosin on my server shortly. I checked already the log files, but didn't find anything. I will check again.

**Comment by fbassas** [comment] 2015-02-09 10:57
HI, I have had a similar problem this weekend.
We have owncloud 7.0.4 in a ubuntu 14.04 server. One of my users send o big copy of files from a local server to owncoud. I taked so long and at midnight our mysql and ldap stopped for backup. After that, in log file appeared:

{"app":"files_sharing","message":"Unable to get mount for shared storage '81' user '6332d98a-7f3e-102a-8c7d-fdcd95ab32a5'","level":3,"time":"2015-02-07T01:28:25+00:00"}

And the share info was lost.
I have made the queries PVince81 suggested, and I have seen two "local::$datadir/$user" records, one with obsolete info about an old server with different datadir. I've remove it and it the log now I get:

{"app":"webdav","message":"Sabre\\DAV\\Exception\\Conflict: Parent node does not exist","level":4,"time":"2015-02-09T10:27:06+00:00"}

Should I create it again?

I've done a "occ files:scan" over user datadir and it seems share info has recovered. Does it have any sense?

But "Unable to get mount..." message still remains. What can I do?

Thanks in advance.

Frank

**Comment by fbassas** [comment] 2015-02-11 11:26
Hi again,
iI've got this on the log file:

{"app":"hook","message":"error while running hook (OCA\\Files_Versions\\Hooks::write_hook): An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)':\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '89-f5131d6bbd6ed754ccf5712adc1c384d' for key 'fs_storage_path_hash'","level":3,"time":"2015-02-11T10:18:34+00:00"}

What's the problem? Can it be related to "Unable to get mount" message?

Thnaks,

Frank

**Comment by shoelzle** [comment] 2015-05-02 11:10
Hello,

Same issue here: Sharing via links is not working for any files or folders.
Nothing suspicious in the logs, not even with loglevel set to 0 (debug).

Owncloud: 8.0.2
PHP: 5.6.1
Webserver: Apache
Operating System: openSUSE 13.2
Database: MySQL

I can provide more information if necessary. Any help is appreciated.

**Comment by tarator** [comment] 2015-05-03 15:02
@shoelzle Do you have suhosin enabled? In my case the problem was, that suhosin (with pretty much default settings) filters requestparams which don't have a value. In PHP then the check with `issset(param_name)` returns `false` when suhosin is enabled. If you disable suhosin the same PHP-Directive returns `true` since the param is simply `null` but not filtered-out.

@Developers: What do you think about that issue? I think this affects more code-parts in the application. Maybe you should make a guideline on how parameters are checked...

**Comment by shoelzle** [comment] 2015-05-13 20:01
@tarator suhosin is enabled. I tried disabling suhosin for testing, however I did not succeed.
I tried two ways:
* setting "php_flag suhosin.simulation On" in .htaccess in owncloud folder
* setting "suhosin.simulation = On" in /etc/php5/conf.d/suhosin.ini

After restarting apache2 suhosin was still enabled. How did you disable it ?

**Comment by shoelzle** [comment] 2015-05-28 10:12
I managed to disable suhosin by setting "php_flag suhosin.simulation On" in the vhost.conf  for the owncloud.
I can confirm that sharing by link works with suhosin disabled.

**Comment by rbahassine** [comment] 2015-06-05 10:14
Hi All,

I have same issue here. Owncloud 7.0.4 on "PHP 5.3.10-1ubuntu3.10 with Suhosin-Patch (cli) (built: Feb 28 2014 23:14:25)"

"Unable to get mount for shared storage '7' user 'some_username'

I have USER1 that's shares a folder FOLDER1 with 30 others users, and since yesterday all share lost (but files still on the server)
NOT USING SHARING BY LINK (so not related with SUHOSIN)

@PVince81 :

I tried all your SELECT and I got this results :

1) Orphaned shares: 
```SQL
select * from oc_share where item_source not in (select fileid from oc_filecache)
```
I got 9 orphans.

2) Check 
```SQL
 select * from oc_storages
```
 whether there are entries like "local::$datadir/$user" and where $datadir is the path to your data dir (or a wrong path)

I have one local::$datadir/$user but the path is right and $user is the username who shares the "unmounted shared storage N°7"

3) Also check the storage 7 : 
```SQL
select * from oc_storages where numeric_id=7 
```
returns one row : home::USERNAME

and its contents 
```SQL
select * from oc_filecache where storage=7.
```
got 8000 lines...

@tarator : checked the permissions of the lucene_folder all is ok.

Seems to be a little different of all what I read on github...

**Comment by PVince81** [comment] 2015-06-05 12:14
Can you confirm that you do not have any entry "home::$user" that would be the same user as "local::$datadir/$user" ?

**Comment by rbahassine** [comment] 2015-06-05 12:41
I confirm.
I made a mistake on my previous post, the entry which begins with "local::" does not contains any user id, its patterns looks like "local::$datadir". >> there is no $user inside the value.
```
local::/files/owncloud/data/
```
And all other entries looks like home::$user and there is no double entries.

May I add the related $user at the end of string local::/files/owncloud/data/ ?

**Comment by PVince81** [comment] 2015-06-05 13:39
No, do not modify that entry, it is not related. Just ignore it.
It seems your storage entries are fine.

You could try deleting the orphaned shares, it might make the issue disappear because then it will not try to resolve them any more. Or you could try upgrading to 7.0.5 which might contain a fix for this, not sure. I just remember that OC 8.0.x should properly ignore orphaned shares.

**Comment by rbahassine** [comment] 2015-06-05 14:02
Thank you PVince.
I deleted orphans but the folder still not appears.
I will try to upgrade to 7.0.5 or 8.0.x

**Comment by PVince81** [comment] 2015-08-21 09:08
@rbahassine did you have any more luck with 7.0.6, 8.0.6 or 8.1.1 ?

**Comment by PVince81** [comment] 2015-08-21 09:08
Please reopen if the issue persists in these versions.
Thanks.

**Closed by PVince81** 2015-08-21 09:08 UTC
Labels: bug, triage
