### ISSUE TITLE
Feature Request: ability to prevent sharing based on mount type

### ISSUE THREAD

**Issue by mdieterich** [owncloud/core#10572] opened 2014-08-21 11:22 UTC
We have a use case where it would be really handy to enable CIFS mounts.  However, there are directories users could mount via CIFS that we do not want to allow our users to share via ownCloud and have thus not enabled this ability for users.  It would be great if there were a way for an admin to specify that sharing was not permitted for certain types of backends, i.e. CIFS, S3, ...

Thanks!

Mark

**Comment by PVince81** [comment] 2015-10-27 12:54
Duplicate of https://github.com/owncloud/core/issues/19157

**Closed by PVince81** 2015-10-27 12:54 UTC
Labels: app:files_external, enhancement, enhancement - proposed, sharing
