### ISSUE TITLE
Sharing API and ldap accounts

### ISSUE THREAD

**Issue by gig13** [owncloud/core#15115] opened 2015-03-23 13:44 UTC
**Expected behavior**
Share a folder using the Sharing API with an LDAP user that has not logged in yet. Expect the share to be created without issue.

**Actual behavior**
When sharing to an LDAP user that has not logged in yet -- receive an error message from the API.

**Steps to reproduce**
Use OC7.0.5 and share a folder with an LDAP user that has not logged in yet.

**Server Configuration**
OC7
Red Hat 7
MySql

**Log - error message**
sharing API reports back the following error:
```
<?xml version="1.0"?><ocs> <meta> <status>failure</status> <statuscode>403</statuscode> <message>sharing 9583 failed, because the user abc123456@gmail.com does not exist</message> </meta> <data/></ocs>
```

**Comment by gig13** [comment] 2015-03-24 12:37
@karlitschek 
What is the criteria for identifying a user exists?

**Comment by gig13** [comment] 2015-03-24 12:42
It was working fine in OC5. What are the differences there? Can we have the same behavior?

**Comment by PVince81** [comment] 2015-03-24 12:47
@blizzz

**Comment by DeepDiver1975** [comment] 2015-03-24 12:53
sounds like duplicate of https://github.com/owncloud/core/issues/15086

**Comment by blizzz** [comment] 2015-03-24 13:25
I also think it's a dup. Please follow up at #15086

**Closed by blizzz** 2015-03-24 13:25 UTC
Labels: blue-ticket, bug
