### ISSUE TITLE
Info icon no correctly visible in sharing sidebar

### ISSUE THREAD

**Issue by hasso** [owncloud/core#20402] opened 2015-11-09 14:06 UTC
Info icon is not correctly visible in sharing sidebar. On narrow screens it may not be visible at all, on wider screens it's often half-visible. In webkit browsers (Chrome 46 and Safari 9 on MacOSX Yosemite) it jumps to the better place if you hover over it with mouse, but in case of narrow screens not enough. In Firefox (42.0 on MacOSX Yosemite) it doesn't jump and remains hidden.
![info-icon-problem](https://cloud.githubusercontent.com/assets/1933532/11035544/cf1f816c-86fb-11e5-9612-0002acc5944f.png)

**Comment by MorrisJobke** [comment] 2015-11-09 14:36
Duplicate of https://github.com/owncloud/core/issues/20061

**Closed by MorrisJobke** 2015-11-09 14:36 UTC
Labels: bug
