### ISSUE TITLE
Add dialog to enter credentials for files_externals mount points

### ISSUE THREAD

**Issue by jmaciasportela** [owncloud/core#20888] opened 2015-12-02 09:44 UTC
Related to https://github.com/owncloud/core/issues/16302

Add a custom dialog to enter credentials when a mountpoint has status unauthorized or incomplete configuration. Migrate from WND.

**Comment by jmaciasportela** [comment] 2015-12-03 09:12
@icewind1991 I need to now the endpoint to send credentials entered on the dialog and other info that you need to store it in db (mountpointId for example)

**Comment by jmaciasportela** [comment] 2015-12-03 11:34
![credentials](https://cloud.githubusercontent.com/assets/1454351/11559536/1713f77a-99ba-11e5-94b1-a54c1c9bea75.jpg)

I need to know the ajax call to store credentials to relaunch availability check

https://github.com/owncloud/core/pull/20920

**Comment by Xenopathic** [comment] 2015-12-03 12:27
I still think it will be better to simply take the user to the external storage configuration section in the settings, rather than having a modal dialog (and all the extra code paths that revolve around that). We effectively have to support each authentication method twice this way, once in the configuration GUI itself, and then again in the modal dialog. Not to mention if the problem isn't with credentials, but rather a hostname change/port change/subdirectory change etc. Keeping all the configuration logic in one place makes things more consistent too.

**Comment by PVince81** [comment] 2016-01-26 11:34
@Xenopathic while I agree for code simplicity, from the UX point of view being able to fill in the credentials in the popup will not disrupt the UX. Maybe the user wanted to enter that folder but jumping to the personal page moves the user away from that.

**Comment by PVince81** [comment] 2016-01-26 11:35
@icewind1991 what's the URL to the new endpoint you added in https://github.com/owncloud/core/pull/21790 ?

**Comment by PVince81** [comment] 2016-01-26 11:47
Ah, there is already a PR https://github.com/owncloud/core/pull/20920

**Comment by PVince81** [comment] 2016-02-11 15:58
Already done, closing.

**Closed by PVince81** 2016-02-11 15:58 UTC
Labels: app:files_external, enhancement
