### ISSUE TITLE
Failed Code Integrity Check after clean install

### ISSUE THREAD

**Issue by miyuchina** [owncloud/core#24367] opened 2016-05-01 09:53 UTC
### Steps to reproduce
System: Ubuntu 16.04 LTS
ownCloud version: 9.0.1 (not Enterprise Edition)
```
$ sudo apt-get purge owncloud
$ sudo apt-get install owncloud
```
I set /data location to /var/storage, and used SQLite, if it can be of any help.

EDIT: According to suggestion by RealRancor, I also purged owncloud-files and owncloud-deps-php* packages, to no avail.

### Expected behaviour
Code Integrity Check should succeed, since I don't remember change any files associated with ownCloud itself. Nor would it make sense for me to modify the listed files. See Actual Behaviour.

### Actual behaviour
The popup "There were problems with the code integrity check" is on the admin screen. Under "List of invalid files" I see a lot of .png files (see below).

### Server configuration
**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache 2.4.18

**Database:** SQLite

**PHP version:** 7.0.4

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/

**Signing status (ownCloud 9.0 and above):**

Under "List of invalid files":

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_images/admin_filehandling-1.png
		- core/doc/admin/_images/admin_filehandling-2.png
		- core/doc/admin/_images/antivirus-config.png
		- core/doc/admin/_images/antivirus-executable.png
		- core/doc/admin/_images/code-integrity-admin.png
		- core/doc/admin/_images/code-integrity-notification.png
		- core/doc/admin/_images/community-vm-console.png
		- core/doc/admin/_images/community-vm-splash.png
		- core/doc/admin/_images/documents_apply_test.png
		- core/doc/admin/_images/dropbox-allowshare.png
		- core/doc/admin/_images/dropbox-configapp.png
		- core/doc/admin/_images/dropbox-oc.png
		- core/doc/admin/_images/external-sites-1.png
		- core/doc/admin/_images/federation-1.png
		- core/doc/admin/_images/federation-2.png
		- core/doc/admin/_images/federation-3.png
		- core/doc/admin/_images/ftp.png
		- core/doc/admin/_images/google-drive10.png
		- core/doc/admin/_images/google-drive11.png
		- core/doc/admin/_images/google-drive13.png
		- core/doc/admin/_images/google-drive8.png
		- core/doc/admin/_images/install-wizard-a1.png
		- core/doc/admin/_images/install-wizard-a4.png
		- core/doc/admin/_images/ldap-advanced-2-directory.png
		- core/doc/admin/_images/ldap-advanced-3-attributes.png
		- core/doc/admin/_images/ldap-expert.png
		- core/doc/admin/_images/ldap-home-connector-2.png
		- core/doc/admin/_images/ldap-home-connector-3.png
		- core/doc/admin/_images/ldap-wizard-1-server.png
		- core/doc/admin/_images/ldap-wizard-2-user.png
		- core/doc/admin/_images/ldap-wizard-3-login.png
		- core/doc/admin/_images/ldap-wizard-4-group.png
		- core/doc/admin/_images/oc_admin_app_page.png
		- core/doc/admin/_images/oracle-1.png
		- core/doc/admin/_images/scaling-1.png
		- core/doc/admin/_images/scaling-2.png
		- core/doc/admin/_images/scaling-3.png
		- core/doc/admin/_images/scaling-4.png
		- core/doc/admin/_images/scaling-5.png
		- core/doc/admin/_images/sharepoint-1.png
		- core/doc/admin/_images/sharepoint-2.png
		- core/doc/admin/_images/shib-gui1.png
		- core/doc/admin/_images/shib-gui4.png
		- core/doc/admin/_images/skeleton-files.png
		- core/doc/admin/_images/skeleton-files1.png
		- core/doc/admin/_images/smb.png
		- core/doc/admin/_images/upgrade-2.png
		- core/doc/admin/_images/webbrander-1.png
		- core/doc/admin/_images/webdav.png
		- core/doc/admin/_static/comment-bright.png
		- core/doc/admin/_static/comment-close.png
		- core/doc/admin/_static/comment.png
		- core/doc/admin/_static/down-pressed.png
		- core/doc/admin/_static/down.png
		- core/doc/admin/_static/file.png
		- core/doc/admin/_static/img/social/diaspora.png
		- core/doc/admin/_static/img/social/diasporaround.png
		- core/doc/admin/_static/minus.png
		- core/doc/admin/_static/plus.png
		- core/doc/admin/_static/up-pressed.png
		- core/doc/admin/_static/up.png
		- core/doc/user/_images/calendar_caldav_icon.png
		- core/doc/user/_images/calendar_caldav_ios.png
		- core/doc/user/_images/calendar_default.png
		- core/doc/user/_images/contact_new.png
		- core/doc/user/_images/contact_picture.png
		- core/doc/user/_images/contact_picture_default.png
		- core/doc/user/_images/contact_uploadbutton.png
		- core/doc/user/_images/contacts_empty.png
		- core/doc/user/_images/contacts_settings.png
		- core/doc/user/_images/encryption2.png
		- core/doc/user/_images/file_menu_comments_2.png
		- core/doc/user/_images/files_page.png
		- core/doc/user/_images/oc_documents_edit.png
		- core/doc/user/_images/webdav_gnome3_nautilus.png
		- settings/img/trans.png
- files_pdfviewer
	- INVALID_HASH
		- vendor/pdfjs/web/images/treeitem-collapsed-rtl.png
		- vendor/pdfjs/web/images/treeitem-collapsed-rtl@2x.png

```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocl0gwr6bhd4',
  'passwordsalt' => '########',
  'secret' => '########',
  'trusted_domains' => 
  array (
    0 => 'xx.xx.xx.xx',
  ),
  'datadirectory' => '/var/storage',
  'overwrite.cli.url' => 'http://xx.xx.xx.xx/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

### Client configuration
**Browser:** Chrome

**Operating system:** OS X El Capitan 10.11.4

**Comment by RealRancor** [comment] 2016-05-01 10:27
@miyuchina 
> sudo apt-get purge owncloud

This will only remove the metapackage. If you want to do a clean setup you also need to purge the owncloud-files and owncloud-deps-php* packages

**Comment by RealRancor** [comment] 2016-05-01 10:29
Already tested?

**Comment by miyuchina** [comment] 2016-05-01 10:43
Sorry for the confusion. I realized I need to purge other packages after I opened the issue. I closed the issue while testing, because you suggested the same thing.

However, the Code Integrity Check still fails, with the identical "List of invalid files" as above.

Thanks.

**Comment by RealRancor** [comment] 2016-05-01 11:01
Have you rescanned the integrity afterwards (in your admin backend)

**Comment by jcullen86** [comment] 2016-05-01 11:18
Same issue here, same files, latest ubuntu 16.04 with the latest owncloud 9.0.1

**Comment by miyuchina** [comment] 2016-05-01 11:25
Yes, I have rescanned the integrity after installation.

I'm guessing the problem is with the HASH values in signature.json, rather than all the files themselves?

**Comment by RealRancor** [comment] 2016-05-01 12:11
cc @jnweiger

**Comment by volkerwysk** [comment] 2016-05-01 12:58
I have exactly the same problem. Purging owncloud owncloud-files owncloud-deps-php5 owncloud-deps-php7.0 doesn't help.

**Comment by jesusrop** [comment] 2016-05-01 17:50
I'm having the same issue here. Clean install on ubuntu server 16.04 gives integrity check errors. A bunch of png files only as reported.

**Comment by RealRancor** [comment] 2016-05-01 17:53
Instead of saying "i have the same problem" you just can "vote" at the first issue. This avoids having comments in here without additional info

**Comment by volkerwysk** [comment] 2016-05-01 18:02
I can't find a possibility to "vote" in the issue's page.

**Comment by miyuchina** [comment] 2016-05-01 23:03
If someone has the exact same issue please click the emoji 👍 right under the first issue on the bottom left corner.

More info concerning this issue is much appreciated in the comments 😃

**Comment by f-s** [comment] 2016-05-02 07:04
Same repos and os, same issue!

**Comment by LukasReschke** [comment] 2016-05-02 07:58
cc @jnweiger

**Comment by jnweiger** [comment] 2016-05-02 15:09
Is this all *.png files, or only some of them? 
Maybe php7 cannot validate binary data?

**Comment by jesusrop** [comment] 2016-05-02 15:24
The list posted by miyuchina looks the same as mine. Where can I find more png files?

**Comment by PVince81** [comment] 2016-05-02 17:44
Are you guys all running PHP 7 ?

**Comment by jnweiger** [comment] 2016-05-02 20:29
First example:
<pre>
                   [core/doc/admin/_images/admin_filehandling-2.png] => Array
                        (
                            [expected] => b3a80fe53681f2c006fb7268f0e72ce2fa4a5f101d1df885f5a5cdc486400183245894f4188c9b23bfb336217ccde2ee66629716d968364b09bda8342386195a
                            [current] => d292e4fa66f33c770cad48982551b48d76756bbfce206a9dceea8c06ea68c9227e3c0e9372021c4e742cbcee251ae798950dd8974bf112b96d9838ef363162b7
                        )
</pre>

Comparing Ubuntu_16.04 with an openSUSE_13.2 build we see the difference in the files.
(So php7 is not guilty)

<pre>
sha512sum /shared/14.04-admin_filehandling-1.png core/doc/admin/_images/admin_filehandling-1.png
4cb6cc5aa813f2770d416997620d51d5535ebd933680e079875f34ceef89b494f621df7f17930b51b81b78b24738c1f12a681538f123d167e33fc36e1f7dde41  /shared/14.04-admin_filehandling-1.png
d75b9fc4ddedcfdcc8655827f005ab1ed5ea02ea5d1062c752afc59a334aaaea23752daba7f34150f8c5495e8dc928bd63bebb464bb0f73387f629a47ff6945d  core/doc/admin/_images/admin_filehandling-1.png
</pre>

The diff between the two files is in the png header

<pre>
--- /shared/902-admin_filehandling-1.png.xxd    2016-05-02 20:42:15.847758367 +0000
+++ /shared/14.04-admin_filehandling-1.png.xxd  2016-05-02 21:21:20.959802393 +0000
@@ -1,106 +1,106 @@
 00000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR
 00000010: 0000 01cc 0000 0080 0806 0000 0086 3659  ..............6Y
 00000020: 2500 0000 0662 4b47 4400 ff00 ff00 ffa0  %....bKGD.......
 00000030: bda7 9300 0000 0970 4859 7300 000b 1300  .......pHYs.....
 00000040: 000b 1301 009a 9c18 0000 0007 7449 4d45  ............tIME
-00000050: 07e0 041b 0c1d 2d1b a10e 7100 0020 0049  ......-...q.. .I
+00000050: 07e0 011a 060e 3463 ee8a e000 0020 0049  ......4c..... .I
 00000060: 4441 5478 daed dd67 7894 c5da c0f1 ffb3  DATx...gx.......
 00000070: 35d9 7492 104a 0201 42a8 1e9a f42e 08a2  5.t..J..B.......
 00000080: 1eac a014 1501 0115 4191 ae07 1439 8088  ........A....9..
 00000090: c2d1 8088 a288 5204 5494 5729 d234 8082  ......R.T.W).4..
 000000a0: 28e5 d00c 2d94 2440 0aa4 ec66 932d f37e  (...-.$@...f.-.~
 000000b0: 4894 1052 4968 c7fb 775d 7c08 bb3b 3b73  H..RIh..w]|..;;s
</pre>

Thank you Ubuntu_16.04 for messing with my timestamps!
</pre>

**Comment by miyuchina** [comment] 2016-05-02 22:27
I have the same expected and obtained hash as posted by jesusrop. Looks like we found the problem!

**Comment by jnweiger** [comment] 2016-05-02 22:32
Will need to bisect the ubuntu package build process tomorrow, unless someone comes up with a hint.

**Comment by rsmith4321** [comment] 2016-05-03 04:35
I did a completely fresh install on Ubuntu 16.04 using the recommended install method from the owncloud packages.  Everything is a default install and all the core files fail integrity checking.

**Comment by jnweiger** [comment] 2016-05-03 16:53
I've disabled 9.0.2 packages on Ubuntu_16.04 for now. The only hint I received so far was about Ubuntu's "reproducible build" feature.

https://wiki.debian.org/ReproducibleBuilds/TimestampsInPNG

**Comment by jnweiger** [comment] 2016-05-03 22:28
9.0.2 for Ubuntu_16.04 is still in testing
http://download.owncloud.org/download/repositories/9.0:/testing/owncloud/index.html

**Comment by enoch85** [comment] 2016-05-03 22:52
@all I just installed ownCloud 9.0.2 on Ubuntu 16.04. I see no issues as all. Everything works as expected. 

I used this script: https://raw.githubusercontent.com/enoch85/ownCloud-VM/master/production/owncloud_install_production.sh and the testing repos: http://download.owncloud.org/download/repositories/9.0:/testing/owncloud/index.html

**Comment by miyuchina** [comment] 2016-05-04 01:56
9.0.2 works for me. No issues so far. Thanks @enoch85

**Comment by Simsey** [comment] 2016-05-04 11:44
Did a fresh installation yesterday (Ubuntu 16.04; php7+mysql) + stable repo and go the same intogrity errors. 

Today, I added the test repo and upgraded to ownCloud 9.0.2 (stable). For me the error is still the same, even after "apt-get purge owncloud owncloud-files owncloud-deps-php*" and reinstalling owncloud

Example:
`[core/doc/admin/_images/admin_filehandling-1.png] => Array
                        (
                            [expected] => 4cb6cc5aa813f2770d416997620d51d5535ebd933680e079875f34ceef89b494f621df7f17930b51b81b78b24738c1f12a681538f123d167e33fc36e1f7dde41
                            [current] => 9b5e8e7f70e1549ddcbefff9441c13c7c3881001b73fb7654ffb2b411a42c359f6a6a6196502457aef6a2a7c67f80314e41db41243b5a9aeacc11c0d8ee5c87e
                        )`

Thanks for your great support

**Comment by jnweiger** [comment] 2016-05-04 12:02
Fix added to the templates:

https://github.com/owncloud/administration/commit/82cc30d76c69f8466a517afe34f8b2a9c3979070

**Comment by jnweiger** [comment] 2016-05-04 15:59
Pushed the fix to http://download.owncloud.org/download/repositories/9.0:/testing/owncloud

Will add Ubuntu_16.04 with the fix to http://download.owncloud.org/download/repositories/stable/owncloud
if the fix can be confirmed by more people.

**Comment by Simsey** [comment] 2016-05-04 16:12
Thanks, worked for me

**Comment by enoch85** [comment] 2016-05-04 17:25
@jnweiger works here as well.

**Comment by enoch85** [comment] 2016-05-04 21:07
@jnweiger Please release this to stable OBS this weekend if possible.

@all Can more people please confirm that the testing packages are working?

>Will add Ubuntu_16.04 with the fix to http://download.owncloud.org/download/repositories/stable/owncloud
if the fix can be confirmed by more people.

**Comment by miyuchina** [comment] 2016-05-05 07:59
I can confirm it is working. Thank you.

**Comment by meic** [comment] 2016-05-06 08:51
This resolved the issue for me. And everything seems to be working on http://download.owncloud.org/download/repositories/9.0:/testing/owncloud for me.

Thanks!

**Comment by comexos** [comment] 2016-05-06 09:06
@jnweiger thanks, the testing packages are working for me as well

**Comment by jnweiger** [comment] 2016-05-06 11:07
Great. Thanks for confirming the fix, @Simsey, @enoch85 
Pushed to stable. Closed fixed.
@SergioBertolinSG @jospoortvliet Ubuntu_16.04 finally made it to http://download.owncloud.org/download/repositories/stable/owncloud

**Closed by jnweiger** 2016-05-06 11:07 UTC
Labels: packaging
