### ISSUE TITLE
Inconsistent minimum search character requirements

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#12431] opened 2014-11-25 20:34 UTC
### Steps to reproduce

1.  Add a bunch of users to ownCloud, local and/or via ldap
2.  Go to the users page and do a search
3.  Data is returned after entering one character
4.  This is inconsistent with the new two character autocomplete support added for sharing (see #11644)

### Expected behaviour

The user search would require a minimum of two characters

### Actual behaviour

The user search would requires one character

### Server configuration

ownCloud Enterprise Edition 7.0.3 (daily) Build:2014-11-25T04:07:01+00:00

**Comment by Xenopathic** [comment] 2015-03-11 22:43
The difference here is that when sharing, there is no list shown without something written in the field, so having a minimum of 2 characters to trigger autocomplete makes sense. In the user list, without a search parameter the full list is shown, and it wouldn't make very much sense to continue showing all users if a single character is written.

A possible workaround to this is to grey out the search field if there is no search term or if it is too short (aka 1 char), and return it to the standard white when enough text is written to search with. cc @jancborchardt

**Comment by jancborchardt** [comment] 2015-03-18 11:52
As @Xenopathic explained, the cases are different.

I would prefer for the autosuggestions in the share dialog to work earlier already – that is after the first character is put in. But I guess that’s too much of a performance hit?

**Comment by Xenopathic** [comment] 2015-03-18 13:50
@jancborchardt I think the problem with the share dialog is that with only a single character you are probably matching ~80% of the users in your oC - hardly useful as a filtering mechanism. If this inconsistency is considered an issue, my vote goes to greying out the user list filter until there are enough characters, then it turns white and the filtering takes place. That gives suitable user feedback IMHO.

**Comment by jancborchardt** [comment] 2015-03-18 14:47
@Xenopathic we’re only looking for the beginning though (of username or display name), right? So probably only 1/26th of users would be matched?

**Comment by Xenopathic** [comment] 2015-03-18 15:50
@jancborchardt I'm not sure how the filtering works - I always thought it did something like `.*foobar.*`

**Comment by jancborchardt** [comment] 2015-03-18 21:21
I’m pretty sure it only looks for the beginnings. If it doesn’t – it should. (Although for display name it should also look after every space if possible, for last names and such.)

**Comment by blizzz** [comment] 2015-03-19 13:51
> 

@Xenopathic we’re only looking for the beginning though (of username or display name), right? So probably only 1/26th of users would be matched?

That depends on the user backend. This is what happens for local users.

LDAP for instance may look into more fields, and there might be far more users (6 digit number). While were also looking from the start, it still delivers too many results.

**Comment by Xenopathic** [comment] 2015-03-19 14:47
Just looked into the database backend: It does the equivalent of `.*foobar.*`.

**Comment by jancborchardt** [comment] 2015-03-23 17:57
Generally, we should require as few characters as possible. Consistency is not the question here.

> with a single character filter the user will get no meaningful results (given that the search list is limited to 15 users max)

The more important point here rather than getting meaningful results is getting immediate feedback. If you have to type 2 characters before seeing any feedback (in the form of the name suggestions), it can be confusing as to what you have to do. Typing one letter into the box is easy though and will immediately show how it works.

**Comment by PVince81** [comment] 2015-10-08 12:49
Related: https://github.com/owncloud/core/issues/14095

**Comment by PVince81** [comment] 2016-02-15 10:12
Closing as duplicate of https://github.com/owncloud/core/issues/14095

**Closed by PVince81** 2016-02-15 10:12 UTC
Labels: bug, feature:sharing, settings:users
