### ISSUE TITLE
Mail address saved in admin settings only after pressing enter

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#17094] opened 2015-06-23 09:26 UTC
Confused the hell out of my users as everything was gone when he refreshed. Will prepare a fix.

**Comment by LukasReschke** [comment] 2015-06-23 09:28
Mhm. This applies to all input fields in the admin settings. When clicking in a white area the input field is closed but the data not saved, though shown to the user.

@jancborchardt I guess we should adjust this everywhere?

**Comment by jancborchardt** [comment] 2015-06-23 11:47
Duplicate of https://github.com/owncloud/core/issues/15176 (Confirm function for text fields) :)

**Closed by jancborchardt** 2015-06-23 11:48 UTC
Labels: design, settings:users
