### ISSUE TITLE
file is locked

### ISSUE THREAD

**Issue by Erwan75** [owncloud/core#28991] opened 2017-09-13 08:28 UTC
Hello,

When I upload a file more than 100GB, I have a message "file locked" at the end of upload and my file doesn't appeared. I have no problem with a 7,8GB file.
My configuration is:

<?php
$CONFIG = array (
  'instanceid' => '****************',
  'passwordsalt' => '*************',
  'secret' => '**************',
  'trusted_domains' =>
  array (
    0 => 'data.domain.com',
  ),
  'datadirectory' => '/var/www/vhosts/data.domain.com/httpdocs/data',
  'overwrite.cli.url' => 'http://data.domain.com',
  'dbtype' => 'mysql',
  'version' => '10.0.2.1',
  'dbname' => '******',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '**********',
  'dbpassword' => '***********',
  'logtimezone' => 'Europe/Paris',
  'installed' => true,
  'integrity.check.disabled' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => [
             'host' => 'localhost',
             'port' => 6379,
             'timeout' => 0.0,
             'password' => '', // Optional, if not defined no password will be used.
             ],
);

I try my upload after I have this option:
'filelocking.enabled' => false,
And it's ok now.

I think, it's not good to disable that, no ?

What can I do ?

Thanks

**Comment by kdslkdsaldsal** [comment] 2017-09-13 08:50
@Erwan75 As you have missed to fill out the shown issue template asking you various information about your issue i'm closing this as a possible duplicate of https://github.com/owncloud/core/issues/27574

How to unlock a file and additional info can be found here: https://central.owncloud.org/t/file-is-locked-how-to-unlock/985

**Closed by kdslkdsaldsal** 2017-09-13 08:50 UTC

**Comment by Erwan75** [comment] 2017-09-14 18:46
Hello @kdslkdsaldsal I have tried with  9.1.6, I don't have the problem.
The only solution to not lock file on 10.0.2.1 is to disable locking ...
Thanks for your help
