### ISSUE TITLE
Bug on user quota settings !?

### ISSUE THREAD

**Issue by simogeo** [owncloud/core#20109] opened 2015-10-28 10:24 UTC
Hi, 

When setting quota to users, I don't get expecting resulting.

For example, I just added unlimited quota to all my users but it seems the application does not take it into account.

And this is what I get from my client :+1: 

![bug-quota](https://cloud.githubusercontent.com/assets/154323/10785723/33b78a56-7d66-11e5-80fa-2a8906492e75.png)

I get a similar message when logged-in into the web UI

I use ownlcoud v8.02 and client v2
Thanks for help

**Comment by nickvergessen** [comment] 2015-10-28 10:27
Maybe the client caches that information for some hours.

**Comment by simogeo** [comment] 2015-10-28 10:29
thanks for quick reply. I did it some days back already

**Comment by tflidd** [comment] 2015-10-28 10:44
You are sure you have enough space on your disk (`df -h`)?

**Comment by simogeo** [comment] 2015-10-28 10:56
well spotted ! it seems to be the problem. 
I have a deeper look and close the issue as soon as possible.

Thanks for helping!

**Comment by DeepDiver1975** [comment] 2015-10-28 11:04
> well spotted ! it seems to be the problem.

please let us know in case the problem is not solved - closing for now - THX

**Closed** 2015-10-28 11:03 UTC
