### ISSUE TITLE
Defer app update

### ISSUE THREAD

**Issue by liamdennehy** [owncloud/core#27781] opened 2017-05-01 14:46 UTC
OwnCloud 9.1.5 on Linux
### Steps to reproduce
1. Open any function (files, Owncloud in a browser
2. Get presented with the upgrade screen because a single app can be updated, effectively disabling OwnCloud
3. Proceed no further because upgrading the app is not an option (admin page is not available either - it redirects to the upgrade screen). OwnCloud is effectively offline.

### Expected behaviour
 - Do nothing differently if a non-admin user is on the site (mandatory?)
 - Allow an app upgrade to be deferred (preferred), or
 - Allow access to the app administration page/present a single link to disable the app (not ideal, but still of value).

### Actual behaviour
OwnCloud web interface is totally useless until an upgrade can be performed of an optional component.

### Rationale
Not every app upgrade should be considered mandatory. There may be a bug that the latest release introduces or (as in issue #27741) the upgrade is impossible. I am able to upgrade the entire instance at my own convenience, but app upgrades are mandatory for some reason, and without commandline (occ) access there is no way to return the site to function.

**Comment by kdslkdsaldsal** [comment] 2017-05-01 15:32
@liamdennehy This is most likely a duplicate of https://github.com/owncloud/core/issues/27747

**Comment by liamdennehy** [comment] 2017-05-01 15:50
Apologies, I didn't include the version in the original report. This issue affects 9.1.5, not 10+ mentioned in #27747.

**Comment by kdslkdsaldsal** [comment] 2017-05-01 15:58
Then i think you should close this here because:

> Not every app upgrade should be considered mandatory. 

If you upgrade an app code then the upgrade of the database for this app is indeed mandatory (you can't also update from 9.1.4 to e.g. 9.1.5 and just "defer" the update of the oC database.

Instead just delete the app folder from /var/www/owncloud/apps and you get a working installation back (without the need to use occ).

**Comment by liamdennehy** [comment] 2017-05-01 16:07
If the new version is only logic/presentation/security, and requires no db update, surely I should decide?
![under your control](https://cloud.githubusercontent.com/assets/4996358/25585059/0fd534ae-2e99-11e7-818d-aefa0326b87d.PNG)

**Closed** 2017-05-01 16:09 UTC

**Comment by kdslkdsaldsal** [comment] 2017-05-01 16:10
@liamdennehy I'm not quite sure, maybe this is just an issue in the app then? If the "logic/presentation/security" is true then you shouldn't get an update screen at all.
