### ISSUE TITLE
server to server shares not showing up on "shared with you" page

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13684] opened 2015-01-26 18:27 UTC
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, share a file with a user on system two
3. on system two, log in as the user with the share
4. accept the share
5. Click on "Shared with you"

### Expected behaviour

The share should be visible

### Actual behaviour

The share is not visible.  In the attached files, files share by user2 are local; the others are remote.

![p265](https://cloud.githubusercontent.com/assets/8480343/5905560/edac2dee-a55e-11e4-93e4-be0e32f698c3.PNG)

![p266](https://cloud.githubusercontent.com/assets/8480343/5905566/f240d274-a55e-11e4-83dc-413ad01ea006.PNG)

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (testing)

**Comment by PVince81** [comment] 2015-01-26 19:22
Duplicate of https://github.com/owncloud/core/issues/9098

**Closed by PVince81** 2015-01-26 19:22 UTC
