### ISSUE TITLE
LDAP groups using memberOfGroup

### ISSUE THREAD

**Issue by alex42ka** [owncloud/core#19840] opened 2015-10-16 15:00 UTC
Owncloud-version: 8.1.3 stable
Webserver: Apache

I'm running an owncloud instance on a root server. I've configured OC to use my LDAP-server (set up with Iredmail) which works good (users are discoverd and shown, they can login, groups are discovered and shown).

I'm using mailLists as groups. Having a look in the user entry (using phpldapadmin) I can see that the users are members of several groups (memberOfGroup). But Owncloud doesn't recognize the membership of the users in the groups. So the groups are empty. What can I do? Can I provide more data to solve the issue?

**Comment by RealRancor** [comment] 2015-10-16 15:12
> Can I provide more data to solve the issue?

I think it could be useful if you fill out the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

which is also asking for your ldap config of oC and how to get them.

**Comment by alex42ka** [comment] 2015-10-16 17:36
### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache

**Database:** Mysql

**PHP version:** PHP 5.5.9-1ubuntu4.13 (cli)

**ownCloud version:** 8.1.3 (stable)

**Updated from an older ownCloud or fresh install:** (updated from 8.1.2)

**List of activated apps:**
Enabled:
 - activity: 2.0.2
 - calendar: 0.7.3
 - contacts: 0.4.0.1
 - direct_menu: 0.4
 - documents: 0.10.2
 - external: 1.2
 - files: 1.1.10
 - files_antivirus: 0.7.0.1
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 14.1.0
 - mail: 0.2.0
 - ownnote: 1.05
 - provisioning_api: 0.2
 - tasks: 0.8
 - templateeditor: 0.1
 - user_ldap: 0.6.1
Disabled:
 - encryption
 - files_external
 - gallery
 - news
 - roundcube
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:**
[InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.



**Are you using external storage, if yes which one:**  No
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** LDAP
#### LDAP configuration (delete this part if not used)
+-------------------------------+--------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                  |
+-------------------------------+--------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                    |
| hasPagedResultSupport         |                                                                                      |
| homeFolderNamingRule          |                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                    |
| ldapAgentName                 | cn=Manager,dc=example,dc=com                                                  |
| ldapAgentPassword             | ***                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                      |
| ldapAttributesForUserSearch   |                                                                                      |
| ldapBackupHost                |                                                                                      |
| ldapBackupPort                |                                                                                      |
| ldapBase                      | o=domains,dc=example,dc=com                                                   |
| ldapBaseGroups                | ou=Groups,domainName=example.com,o=domains,dc=example,dc=com           |
| ldapBaseUsers                 | o=domains,dc=example,dc=com                                                   |
| ldapCacheTTL                  | 600                                                                                  |
| ldapConfigurationActive       | 1                                                                                    |
| ldapEmailAttribute            | mail                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                    |
| ldapExpertUUIDGroupAttr       |                                                                                      |
| ldapExpertUUIDUserAttr        | mail                                                                                 |
| ldapExpertUsernameAttr        |                                                                                      |
| ldapGroupDisplayName          | cn                                                                                   |
| ldapGroupFilter               | (&(|(objectclass=mailList)))                                                         |
| ldapGroupFilterGroups         |                                                                                      |
| ldapGroupFilterMode           | 1                                                                                    |
| ldapGroupFilterObjectclass    | mailDomain                                                                           |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                         |
| ldapHost                      | localhost                                                                            |
| ldapIgnoreNamingRules         |                                                                                      |
| ldapLoginFilter               | (&(|(objectclass=mailUser))(|(|(mailPrimaryAddress=%uid)(mail=%uid))(|(mail=%uid)))) |
| ldapLoginFilterAttributes     | mail                                                                                 |
| ldapLoginFilterEmail          | 1                                                                                    |
| ldapLoginFilterMode           | 0                                                                                    |
| ldapLoginFilterUsername       | 0                                                                                    |
| ldapNestedGroups              | 0                                                                                    |
| ldapNoCase                    | 0                                                                                    |
| ldapOverrideMainServer        |                                                                                      |
| ldapPagingSize                | 500                                                                                  |
| ldapPort                      | 389                                                                                  |
| ldapQuotaAttribute            |                                                                                      |
| ldapQuotaDefault              |                                                                                      |
| ldapTLS                       | 1                                                                                    |
| ldapUserDisplayName           | cn                                                                                   |
| ldapUserFilter                | (|(objectclass=mailUser))                                                            |
| ldapUserFilterGroups          |                                                                                      |
| ldapUserFilterMode            | 1                                                                                    |
| ldapUserFilterObjectclass     | mailUser                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                 |
| turnOffCertCheck              | 0                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------+

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"VnSY0E2\/4xksvbUfuE0H","remoteAddr":"109.90.232.89","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-15T11:56:25+00:00"}
{"reqId":"\/mmaTjpWQDgR0nG\/ZnN7","remoteAddr":"109.90.232.89","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-15T17:15:47+00:00"}
{"reqId":"OFX+zhVgllSS50n4Nbuw","remoteAddr":"178.200.132.195","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-16T10:30:09+00:00"}
{"reqId":"owS7g2kF9YtaQ6bQNjk2","remoteAddr":"178.200.132.195","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-16T11:31:43+00:00"}
{"reqId":"Tcst\/Cj7qRQlej\/\/wNjM","remoteAddr":"109.90.232.89","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-16T11:48:07+00:00"}
{"reqId":"4a7FDwVLjZ8Z3pqM7xWI","remoteAddr":"109.90.232.89","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-16T14:38:05+00:00"}

**Comment by RealRancor** [comment] 2015-10-16 17:40
Might be related or a duplicate of https://github.com/owncloud/core/issues/18340 and https://github.com/owncloud/core/issues/17570

**Comment by alex42ka** [comment] 2015-10-16 18:09
Tried the mentioned:

[code]sudo -u www-data php occ ldap:set-config "s01" useMemberOfToDetectMembership 0[/code]

But with no effect. Any idea how I can solve the issue?

**Comment by RealRancor** [comment] 2015-10-18 07:45
Then you might want to close here and follow https://github.com/owncloud/core/issues/18340 which looks to me like the same issue.

**Comment by alex42ka** [comment] 2015-10-18 07:53
I don't think that it is the same issue. My users do appear. But the groups, which appear as well, are not filled with users.

**Comment by RealRancor** [comment] 2015-10-18 08:18
Ah, yes. Seems you're right

**Comment by alex42ka** [comment] 2015-10-18 10:39
To clarify my LDAP installation:

* Let's say we have mailing list account 'group@xx.com', and it has 2 members: user1@xx.com, user2@xx.com.
* The mailing list account is stored under 'ou=Groups,domainName=[domain],o=domains,dc=xx,dc=xx'.
* Mail users are stored under 'ou=Users,domainName=[domain],o=domains,dc=xx,dc=xx'.
* Membership is stored in user object with attribute/value pair: memberOfGroup=group@xx.com
* Mailing list object is used to store additional info like mailing list access policy, moderators, etc.

**Comment by Xenopathic** [comment] 2015-10-18 11:18
Currently, user_ldap advertises support for only a handful of group member attributes, `member (AD)`, `uniqueMember`, and `memberUid`. `memberOfGroup` hasn't been specifically implemented, and unfortunately due to the attribute's structure cannot work with ownCloud at this time, since the attribute is on the user object and not on the group object.

You might be able to hack it though: replace all `memberOf` in with `memberOfGroup` on this line: https://github.com/owncloud/core/blob/master/apps/user_ldap/group_ldap.php#L200, and make sure you re-enable memberOf support if you've disabled it (`sudo -u www-data php occ ldap:set-config "s01" useMemberOfToDetectMembership 1`). Hopefully, your groups will appear. If so, we might want to consider making the `memberOf` attribute configurable @blizzz

**Comment by alex42ka** [comment] 2015-10-18 11:55
My groups appear already.

I've tried to change the group_ldap.php of my existing installation (8.1.3 from OpenSuse-sources) like mentioned by @Xenopathic  and re-enabled memberOf support. 
But sadly with no effect. Groups still appear but are not filled with users.

**Comment by Xenopathic** [comment] 2015-10-18 19:16
@alex42ka In 8.1.3, I take it you edited https://github.com/owncloud/core/blob/015323c1cb239ab242ff43183fd2edb8e3103025/apps/user_ldap/group_ldap.php#L380 ? That's the only line you would need to change, but you probably need to clear the LDAP cache for the changes to take effect (clear your memcache).

Also, could you perhaps post a sample `memberOfGroup` entry? I don't know what it should look like

**Comment by alex42ka** [comment] 2015-10-19 11:03
Yes, thats the line I've edited. I've rebooted (server and desktop) - so my cache should be cleared. But still the groups are empty.

An example of a memberOfGroup entry would be: 

memberOfGroup

group1@example.com
group3@example.com

**Comment by Xenopathic** [comment] 2015-10-19 14:27
Ah, that explains it. ownCloud expects a DN and not an email address...

It seems to me that `memberOfGroup` really isn't designed for POSIX groups. Do any other authentication providers, e.g. SSSD, nslcd, Apache LDAP etc. support this scheme?

**Comment by alex42ka** [comment] 2015-10-19 14:40
In fact I've got  no idea if other authentication provider support this scheme. But I would say that Iredmail is widespread.

Can I change the settings so that OC can cope with the email address?

**Comment by alex42ka** [comment] 2015-10-22 16:20
@Xenopathic do you maybe can give me a hint what we would have to change in the group_ldap.php to make it possible that OC can cope with the iRedMail-LDAP? We want to use OC in our school and we do have lots of users and lots of groups ;-)

**Comment by alex42ka** [comment] 2015-10-22 17:29
Maybe it is to some part a caching problem? I've realized that changes in the cn of my groups for example  do have no effect to the shown cn in ownCloud! How can I delete the cache? (Even reboots didn't help)

**Comment by Xenopathic** [comment] 2015-10-22 20:45
@alex42ka You would need to lookup users based on their email address, while at the moment users are looked up with a full DN. Then you need to read that user object in, and parse out the data. All in all, you are looking at a partial rewrite of the LDAP logic, certainly not an easy job... Again, I just refer to how it seems that no other LDAP authenticators support this mechanism, since it's not designed for group membership but seemingly rather for mailing list membership.

As for the 'caching', that'd be the mapping tables stored in the database. You can clear them in the Expert tab of the LDAP configuration wizard.

**Comment by alex42ka** [comment] 2015-10-23 14:31
@Xenopathic The lookup of the users, using their email-address is well supported by ownCloud. I'm using it for my private cloud and the school cloud as well. You just have to set the right Login attributes.
```
(|(mailPrimaryAddress=%uid)(mail=%uid))
```

The lookup of the group seems to work as well (groups are shown under groups and I can choose which attribute should be shown as group name. Just the association of both, user and group, doesn't work.

In fact I could try to populate the group with users setting the user-mail as ```hasmember```. Would this be a working solution? Or is there another attribute I could set in LDAP?

**Comment by Xenopathic** [comment] 2015-10-23 15:46
What I meant by lookup was how group membership information is linked to users, and at the moment with `member` only full DNs and UIDs are supported, not email addresses.

You really should be using a standard POSIX group membership attribute such as `member`, `memberOf`, `uniqueMember` or `memberUid` though...

**Comment by alex42ka** [comment] 2015-10-24 13:39
Could you maybe provide an example LDIF for an user and a group?

**Comment by alex42ka** [comment] 2015-10-25 19:43
I've created a new group and populated it with users. But still they are empty in ownCloud. Here comes the group ldif:
```
# LDIF Export for cn=Test2,ou=Groups,domainName=example.com,o=domains,dc=example,dc=com
# Server: My LDAP Server (localhost)
# Suchbereich: base
# Suchfilter: (objectClass=*)
# Anzahl der Eintraege: 1
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on October 25, 2015 7:12 pm
# Version: 1.2.2

version: 1

# Eintrag 1: cn=Test2,ou=Groups,domainName=example.com,o=domains,d...
dn: cn=Test2,ou=Groups,domainName=example.com,o=domains,dc=example,dc=com
cn: Test2
member: mail=user1@example.com,ou=Users,domainName=example.com,o=domains,dc=example,dc=com
objectclass: groupOfNames
objectclass: top
```
and here an users ldif:
```
# LDIF Export for mail=user1@example.com,ou=Users,domainName=example.com,o=domains,dc=example,dc=com
# Server: My LDAP Server (localhost)
# Suchbereich: base
# Suchfilter: (objectClass=*)
# Anzahl der Eintraege: 1
#
# Generated by phpLDAPadmin (http://phpldapadmin.sourceforge.net) on October 25, 2015 7:34 pm
# Version: 1.2.2

version: 1

# Eintrag 1: mail=user1@example.com,ou=Users,domainName=example...
dn: mail=user1@example.com,ou=Users,domainName=example.com,o=domains,dc=example,dc=com
accountstatus: active
amavislocal: TRUE
cn: Example User
enabledservice: internal
enabledservice: doveadm
enabledservice: lib-storage
enabledservice: indexer-worker
enabledservice: dsync
enabledservice: mail
enabledservice: smtp
enabledservice: smtpsecured
enabledservice: pop3
enabledservice: pop3secured
enabledservice: imap
enabledservice: imapsecured
enabledservice: deliver
enabledservice: lda
enabledservice: forward
enabledservice: senderbcc
enabledservice: recipientbcc
enabledservice: managesieve
enabledservice: managesievesecured
enabledservice: sieve
enabledservice: sievesecured
enabledservice: lmtp
enabledservice: shadowaddress
enabledservice: displayedInGlobalAddressBook
givenname: user1
homedirectory: /var/vmail/vmail1/example.com/u/s/e/user1-2015.10
 .19.14.50.02/
mail: user1@example.com
mailmessagestore: vmail1/example.com/u/s/e/user1-2015.10.19.14.5
 0.02/
mailquota: 2147483648
memberofgroup: examplegroup@example.com
mtatransport: dovecot
objectclass: inetOrgPerson
objectclass: mailUser
objectclass: shadowAccount
objectclass: amavisAccount
shadowlastchange: 0
sn: user1
storagebasedirectory: /var/vmail
uid: user1
userpassword: ***secret***

```

Am I doing something wrong?

**Comment by blizzz** [comment] 2015-10-27 11:40
Did you switch ldapGroupMemberAssocAttr to member (Advanced settings)?

**Comment by alex42ka** [comment] 2015-10-31 19:16
Now I've created POSIX-groups in which I've added the users. These POSIX-groups are show in owncloud and they are filled with users. So with this LDAP-design everything is working fine.

**Comment by blizzz** [comment] 2015-11-02 09:26
Glad you got it working.

**Closed by blizzz** 2015-11-02 09:26 UTC
Labels: app:user_ldap
