### ISSUE TITLE
Internal Error 500

### ISSUE THREAD

**Issue by bkerensa** [owncloud/core#21869] opened 2016-01-24 06:48 UTC
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu Server

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 
8.2.2

**Updated from an older ownCloud or fresh install:**
Updated from 8.1.5

**Signing status (ownCloud 9.0 and above):**

```
Cannot access
```

**List of activated apps:**

```json
{
    "system": {
        "instanceid": "oc7cae5d6098",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/home\/sensitiveuser\/owncloud.somedomain.com\/data",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": "0",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "no-reply",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Chrome

**Operating system:** OSX

#### Web server error log
```
[Sat Jan 23 22:36:46 2016] [error] [client IP] Premature end of script headers: cron.php
[Sat Jan 23 22:36:46 2016] [error] [client IP] File does not exist: /home/user/owncloud.somedomain.com/internal_error.html
```

#### ownCloud log (data/owncloud.log)

This is most recent so there is nothing helpful as to why this error is happening
```json
{"reqId":"VpcVyK3snV4AAEP3UrIAAAAD","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T03:28:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"VpcYl63snV4AAGRWZRAAAAAO","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T03:40:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"VpcbZ63snV4AAHuPHikAAAAB","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T03:52:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"VpceN63snV4AAAazeeUAAAAI","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T04:04:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"VpchB63snV4AAAfpGOUAAAAD","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T04:16:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"Vpcj163snV4AAAnZiXYAAAAC","remoteAddr":"dong","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-01-14T04:28:08+00:00","method":"POST","url":"\/index.php\/heartbeat"}
```

#### Browser log
```
I'm unsure how this would be useful in the case of a 500 error
```

**Comment by bkerensa** [comment] 2016-01-24 06:52
Mind you nothing has been changed and my owncloud install has been up solid for over a year now but all of a sudden this week I got to access it and I get this 500 error and I notice another user has the same issue as me:
https://forum.owncloud.org/viewtopic.php?f=36&t=32660

My only guess is cron or something that usually runs broke something in the install but the lack of useable logs is not helping me find out what

**Comment by DeepDiver1975** [comment] 2016-01-24 09:10
> Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream

please fix this - THX

**Comment by bkerensa** [comment] 2016-01-24 10:05
That shouldn't be causing a 500 error in a build that still supports it and that said for most folks on a shared platform always_populate_raw_post_data is going to be on.

**Comment by RealRancor** [comment] 2016-01-24 12:19
Hi,

a first starting point would be to research what was changed within your environment to get to this state (ownCloud itself won't magically damage itself).

As the cron.php is mentioned you should check your cron settings and php-cli environment which is executing that file.

The always_populate_raw_post_data should be also fixed on your side as already suggested. I think the message is not there just for fun.

**Comment by RealRancor** [comment] 2016-01-24 12:25
Ah, as both of you have the "File does not exist: /home/xxx/owncloud.unleashedfinancial.com/ownCloud/internal_error.html" message in your logfile you'r probably both are on the same shared hoster?

If yes then it should be obvious that your hoster probably changed something in their environment which is causing those issues.

Have you considered contacting the support of your hoster about that issue?

**Comment by bkerensa** [comment] 2016-01-24 12:52
No we're not on the same hosted and others have had this too look on forums. Nothing has changed my provider tailed their logs and it's OC install that's busted.

**Comment by RealRancor** [comment] 2016-01-24 13:09
So you're saying you both are not on the same hoster but have the same uncommon 'internal_error.html' in your logfiles? Or do you just have copied over the logfiles of the other user in here?

**Comment by bkerensa** [comment] 2016-01-24 13:12
I just said in the comment above that my host investigated. We have other OC installs on the same server that are low major version and still chugging along fine.

**Comment by RealRancor** [comment] 2016-01-24 13:13
Please answer the questions above

**Comment by bkerensa** [comment] 2016-01-24 13:20
Im not in any position to explain someone else's setup. That said I've supplied the necessary info for the template of an actual OC dev wants more info I'll provide it.

**Comment by RealRancor** [comment] 2016-01-24 13:23
I'm just asking you to answer this:

> So you're saying you both are not on the same hoster but have the same uncommon 'internal_error.html' in your logfiles? Or do you just have copied over the logfiles of the other user in here?

**Comment by bkerensa** [comment] 2016-01-24 13:28
I don't know what part of I can't tell you what kind of environment another user that I do not know is on.

Maybe ask him? He isn't on my host that's all I know and I know because I trace routed his hostname.

**Comment by RealRancor** [comment] 2016-01-24 13:36
This is not about the environment of the other user. I'm just asking you if that are the logfiles of your server you have posted here.

**Comment by bkerensa** [comment] 2016-01-24 19:16
Why would I post someone else's log files ? Yes they are mine

**Comment by RealRancor** [comment] 2016-01-24 20:36
Just to be sure. I have seen a lot of things in the last 2 years since i'm giving support at the forums.

Just have asked the other user at the forums to contact his hoster. Maybe they can provide more info/insights.

**Comment by RealRancor** [comment] 2016-01-24 21:32
Cross-Posting from the linked forums post:

> I just found out what changed. DreamHost added zend_extension=opcache.so to my phprc file. I removed that line and the site works fine.
>
> Woo Hoo. unintended consequences of a dreamhost modification

**Comment by bkerensa** [comment] 2016-01-24 21:38
So first off I do have one instal as I mentioned above that works fine on dreamhost and I just checked and yep opcode is there.

That said according to OwnCloud doc opcode should be supported so someone might want to file a bug about that.

On the OwnCloud instance that's 500 erroring is on a different provider Arivxe and opcode is not set in phprc.

**Comment by MorrisJobke** [comment] 2016-01-25 13:03
This is clearly nothing the bug tracker is for. This seems to be a setup issue. Please try to figure out what the cause of this is.

Once you know which setting/feature/setup is not compatible with owncloud you can report a bug here, but this just seems to be a setup issue and we as owncloud developers can't do much here.

I will close this because it lacks the essential information of how to reproduce the issue.

**Closed by MorrisJobke** 2016-01-25 13:03 UTC
Labels: needs info

**Comment by bkerensa** [comment] 2016-01-25 21:35
@MorrisJobke Actually the information is there and basically if a server has Zend opcache enabled it then OC breaks. According to doc this form of caching is supported so this is a bug.

I checked my phprc on a different host and the same issue caused it and so I would encourage reopening this and editing the title and queuing it to be worked on.

**Comment by Xenopathic** [comment] 2016-01-25 21:42
@bkerensa Zend Opcache works fine for most people, myself included. Given that we have seen 2 instances of a broken ownCloud due to this issue, out of likely many hundreds of thousands of installations, I'd say it's a specific environment issue, and you're better off getting help from the forums or other support channels.

**Comment by bkerensa** [comment] 2016-01-25 21:47
Looking at logs the breakage happened on first cron run after I upgraded to 8.2.2 so perhaps a regression? I mean its your project if it were mine and I do run open source projects myself I would definitely investigate it more versus write it off to forums or a environment issue.

If you think its environment then ask for more info to rule that out.... But again its your call and if it is a regression I guess you will see more of these reports come up.

**Comment by MorrisJobke** [comment] 2016-01-25 21:54
> @MorrisJobke Actually the information is there and basically if a server has Zend opcache enabled it then OC breaks. According to doc this form of caching is supported so this is a bug.

Nearly all instances I'm aware of use Zend opcache and all work fine :( Sadly it seems to be really hard to reproduce.

We are also not aware of any issues on Ubuntu (especially the LTS versions). The packages there just work. Maybe you have some other hints what is different on those systems. If this is not possible, we can't do much. We always try to investigate, but if this doesn't show any hints what it could be there is not much we can do.

@bkerensa Where is this "internal_error.html" coming from?

**Comment by RealRancor** [comment] 2016-01-26 04:28
There is a third instance showing issues with opcache but with a different error (400): https://github.com/owncloud/core/issues/21876

**Comment by bkerensa** [comment] 2016-01-26 06:39
@karlitschek le ping

**Comment by RealRancor** [comment] 2016-01-30 21:15
Getting more reports about that:

https://github.com/owncloud/core/issues/21876
https://forum.owncloud.org/viewtopic.php?p=106269
https://forum.owncloud.org/viewtopic.php?p=106269#p106269
https://forum.owncloud.org/viewtopic.php?f=31&t=32772

**Comment by RealRancor** [comment] 2016-02-04 06:42
@bkerensa Have raised https://github.com/owncloud/core/issues/22117
