### ISSUE TITLE
PROPFIND of a root folder with a S3 external storage folder mounted is very slow

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#15967] opened 2015-04-30 11:21 UTC
### Steps to reproduce

1. Mount an amazon S3 folder and be sure encryption is enabled on it (gear on the right).
2. Upload some files to it.
3. Do:
```
curl -X PROPFIND -H "Content-Type: text/xml" http://USER:PASSWORD@HOST/remote.php/webdav/ | xmllint --format -
```

### Expected behaviour
Have a quick response.

### Actual behaviour
It is quite slow.
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3101  100  3101    0     0     79      0  0:00:39  0:00:39 --:--:--   828
```

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
8.1 alpha2

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes S3.

**Are you using encryption:** 
Yes.

I was testing propfind requests with encryption, but after disabling S3 mounted folder, the request went like a charm, so encryption doesn't slows it down.

**Logs**
```

```

**Comment by karlitschek** [comment] 2015-05-06 19:55
@butonic What is your opinion?

**Comment by PVince81** [comment] 2015-05-26 11:09
Duplicate of https://github.com/owncloud/core/issues/13147
We need a stat cache for every external storage.

**Closed by PVince81** 2015-05-26 11:09 UTC
Labels: bug, performance, sev3-medium

**Comment by PVince81** [comment] 2015-05-26 11:11
@jnfrmarks I see you set the milestone. Please reevaluate whether we want 8.1 or 8.2 on https://github.com/owncloud/core/issues/13147.

Note that implementing a stat cache will affect all file operations and would need full regression testing of S3. A stat cache was implemented for SWIFT a while ago but got deferred again to 8.2: https://github.com/owncloud/core/pull/7897

General info about stat caches for external storage: https://github.com/owncloud/core/issues/7910
