### ISSUE TITLE
Language codes in chooser, and sorted before proper languages

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18622] opened 2015-08-28 10:19 UTC
![language chooser](https://cloud.githubusercontent.com/assets/925062/9544189/cf7a44a0-4d7e-11e5-8328-0b6e0953ff0d.png)

These valid languages should be sorted before the ones with the weird language codes. Also, we should fix the language codes being shown only before the release.

@MorrisJobke @DeepDiver1975 @owncloud/designers

**Comment by nickvergessen** [comment] 2015-08-28 13:49
@jancborchardt you mean languages without `_` before those with?

**Comment by jancborchardt** [comment] 2015-08-28 15:15
@nickvergessen yep – but there’s also language codes without underscores as you see from the screenshot.

**Comment by nickvergessen** [comment] 2015-08-28 15:35
The screenshot displayes the language name, language code is different: code=de_DE is name="Deutsch (Sie)"

**Comment by MorrisJobke** [comment] 2015-08-28 15:43
Kind of duplicate of #18141

**Closed** 2015-08-28 16:39 UTC
Labels: 1 - To develop, bug, settings:personal
