### ISSUE TITLE
Remember choosen order mode for folder

### ISSUE THREAD

**Issue by blaskovic** [owncloud/core#11699] opened 2014-10-22 10:26 UTC
Would it be possible to remember last used order method for separated folders?

For example InstantUpload folder - I am using it always with ordering by date descending to see the newest photos from my smartphone at the top. It's irritating to order it every time when I switch to this folder.

**Comment by jancborchardt** [comment] 2015-01-28 11:35
Closing as duplicate of https://github.com/owncloud/core/issues/10788 since it’s both about remembering the sort order.

**Closed by jancborchardt** 2015-01-28 11:35 UTC
Labels: enhancement - proposed, triage
