### ISSUE TITLE
File list seems incomplete (invisible below the 'page fold') but files are there and can be clicked / depends on screen height!

### ISSUE THREAD

**Issue by flipsa** [owncloud/core#15482] opened 2015-04-08 14:47 UTC
I see the very same problem described by somebody else on the OC forums: https://forum.owncloud.org/viewtopic.php?f=31&t=27348

Steps to reproduce:
- open file browser in OC and navigate to a folder with more items than your screen can show without scrolling
- scroll down / past the files shown initally
- no further files are shown below the ones listed before scrolling
- BUT, all files are there and can be clicked (followed / opened), as can be seen in the browser status bar when hovering

Expected:
- When scrolling a long file list, all files should be visible

Actual:
- As stated above: only the initial set of files before scrolling down are visible

Software versions:
OC: 8.0.2
php: 5.5.9
MySQL 14.14 Distrib 5.5.41
Hardware: arm7 SoC device

More info:
- Behaviour happens on Firefox and Chrome (on Gentoo & Ubuntu on Linux; Windows7)
- Android app does NOT show this problem!
- The "table-header" (above the file list; where you can select all files or change the sort order) is missing as well, but a window resize brings it back. When changing the sort order, files that were not visible before now show up, but other files which don't fit on the screen disappear / are not visible when scrolling down
- i think(!) this problem did not exist a few days ago. I did not update OC during that time, but I did upgrade various Apache2 and php5 packages (via apt-get). Have not tried downgrading yet, but could do so (in a few days as I am super busy with work till Friday) if OC devs can't reproduce this bug otherwise.

Let me know if you need more info!

**Comment by DeepDiver1975** [comment] 2015-04-08 14:56
@jancborchardt afaik this issue will be fixed with 8.1 - maybe even 8.0.3 ???

**Comment by jancborchardt** [comment] 2015-04-08 15:48
Most probably, this sounds like it had to do with the threshold of when lazy loading is triggered. @PVince81 do you remember when you adjusted that?

**Comment by PVince81** [comment] 2015-04-08 15:54
The page scroll was fixed a long time ago and should work in OC 8 already.
Maybe this is a different issue.

**Comment by flipsa** [comment] 2015-04-08 16:50
I think I just found the problem:

Short explanation: 
- In the list of enabled apps, I had enabled the app "Share Files" (v0.6.1) but _recently_ disabled sharing from the admin backend
- Re-enabling sharing from the admin backend solves the problem
- Disabling the app solves the problem, too (irrespective of the admin backend settings)

Long explanation:
I recently deactivated sharing functionality completely (in the administration backend -> untick "Allow apps to use the share API"), but it was enabled before. Also, maybe of interest, this is an old OC installation, i think i first installed OC5 and kept upgrading. 

Now, after deactivating sharing a few days ago, when listing files, i get this javascript error in Chrome's developer console (sorry, I overlooked that before):

    Uncaught TypeError: Cannot read property 'loadIcons' of undefined

It refers to owncloud/apps/files_sharing/js/share.js on line 75:

    74 if (!OCA.Sharing.sharesLoaded){
    75 OC.Share.loadIcons('file', fileList, function() {
    76 // since we don't know which files are affected, just refresh them all
    77 updateIcons();
    78 });
    79   ....
    
   

After re-enabling sharing functionality, the javascript error is gone, and I can see all files. Not sure if that is something that would have also happened if I did a fresh install of OC8, or if it is not properly checked if sharing was disabled when listing files.

**Comment by PVince81** [comment] 2015-04-08 16:52
Ah yes, this is a know issue.
Something breaks the JS code loading, so basically breaks a lot of JS stuff including the scrolling...

Closing as duplicate of https://github.com/owncloud/core/issues/15186

**Closed by PVince81** 2015-04-08 16:52 UTC
Labels: bug

**Comment by flipsa** [comment] 2015-04-08 17:01
Ah, makes sense...

Btw, i completely agree with your last comment in #15186. For a moment, I wasn't sure if the sharing app was maybe obsolote / part of the core app now or not. Having part of the options in the admin backend but the rest of it as part of a - recommend, but alas... - external app does not make all that much sense ;)
