### ISSUE TITLE
[Sharing] No dropdown is displayed when the pattern does not match with any username

### ISSUE THREAD

**Issue by davitol** [owncloud/core#22319] opened 2016-02-11 12:51 UTC
### Steps to reproduce

1. In share dialog, write down a username pattern that doesn't fit with any user

### Expected behaviour

The dropdown should show a message related to 'no users where found'

### Actual behaviour

No dropdown is shown.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2016-02-10T04:14:42+00:00 53d57bffed38d5f0723df26f011b1876be9360f7

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no.
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox for Mac OSX

![screen shot 2016-02-11 at 13 34 46](https://cloud.githubusercontent.com/assets/10596560/12976578/79086802-d0c5-11e5-8f85-2cdf29b907c8.png)

![screen shot 2016-02-11 at 13 34 56](https://cloud.githubusercontent.com/assets/10596560/12976583/7fae5ad6-d0c5-11e5-80ae-fd4c1f7670fb.png)

@rullzer

**Comment by MorrisJobke** [comment] 2016-02-12 08:13
Duplicate of https://github.com/owncloud/core/issues/17408

**Closed by MorrisJobke** 2016-02-12 08:13 UTC
Labels: bug, feature:sharing, sev4-low
