### ISSUE TITLE
LDAP multiple base dns not working

### ISSUE THREAD

**Issue by joba12** [owncloud/core#23138] opened 2016-03-11 09:28 UTC
### Steps to reproduce
1. Login to owncloud
2. goto administration -> ldap
3. fill in the first base dn and all other fields, save and validate that users out of this base dn are able to login
4. goto administration -> ldap
5. enter a new line and fill in the second base dn
6. save
7. test if users out of the second base dn are able to loing

### Expected behaviour
users out of both base dns are able to login to the owncloud

### Actual behaviour
it says the configuration is complete, but only users out the first base dn are able to login
"sudo -u apache php occ ldap:show-config" shows that only the ldapBase has been updated to contain two base dns, seperated by a semicolon. ldapBaseGroups and ldapBaseUsers only contains one base dn

i tried to change the ldapBaseGroups and ldapBaseUsers via the occ command to contain two base dns as ldapBase does, it worked perfectly. now users out of both base dns are able to login. i think, this should be done automatically when adding a second base dn via the webinterface.

### Server configuration
**Operating system**:
Fedora 23 Server

**Web server:** 
apache

**Database:** 
mariadb

**PHP version:** 
5.6.18
 
**ownCloud version:** (see ownCloud admin page) 
8.2.2

**Updated from an older ownCloud or fresh install:** 
fresh install

**Where did you install ownCloud from:** 
fedora 23 owncloud repos

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - user_ldap: 0.7.1
Disabled:
  - encryption
  - external
  - files_external
  - user_external

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc277po467ex",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.24.10.23",
            "example.example.com"
        ],
        "datadirectory": "\/srv\/data",
        "overwrite.cli.url": "http:\/\/172.24.10.23",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_from_address": "example",
        "mail_smtpmode": "smtp",
        "mail_domain": "example.com",
        "mail_smtphost": "172.24.20.20",
        "mail_smtpport": "25"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Active Directory

#### LDAP configuration (delete this part if not used)
before my changes, just after adding the second base dn via the webinterface:
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                   |
| hasPagedResultSupport         |                                                                                                                                     |
| homeFolderNamingRule          |                                                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                                                   |
| ldapAgentName                 | CN=Owncloud,OU=hidden,OU=Netzlink,DC=hidden,DC=hidden                                                                        |
| ldapAgentPassword             | ***                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                                                     |
| ldapBackupHost                |                                                                                                                                     |
| ldapBackupPort                |                                                                                                                                     |
| ldapBase                      | OU=hidden,OU=hidden,DC=hidden,DC=hidden;OU=hidden,OU=hidden,DC=hidden,DC=hidden                              |
| ldapBaseGroups                | OU=hidden,OU=hidden,DC=hidden,DC=hidden                                                                                           |
| ldapBaseUsers                 | OU=hidden,OU=hidden,DC=hidden,DC=hidden                                                                                           |
| ldapCacheTTL                  | 600                                                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                                                     |
| ldapExpertUsernameAttr        |                                                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=organizationalUnit)))                                                                                              |
| ldapGroupFilterGroups         |                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                   |
| ldapGroupFilterObjectclass    | organizationalUnit                                                                                                                  |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                        |
| ldapHost                      | hidden                                                                                                                        |
| ldapIgnoreNamingRules         |                                                                                                                                     |
| ldapLoginFilter               | (&(|(objectclass=person)(objectclass=user))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(sAMAccountType=%uid)))) |
| ldapLoginFilterAttributes     | sAMAccountType                                                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                   |
| ldapNestedGroups              | 0                                                                                                                                   |
| ldapOverrideMainServer        |                                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                                 |
| ldapPort                      | 389                                                                                                                                 |
| ldapQuotaAttribute            |                                                                                                                                     |
| ldapQuotaDefault              |                                                                                                                                     |
| ldapTLS                       | 0                                                                                                                                   |
| ldapUserDisplayName           | displayName                                                                                                                         |
| ldapUserFilter                | (|(objectclass=person)(objectclass=user))                                                                                           |
| ldapUserFilterGroups          |                                                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                                                   |
| ldapUserFilterObjectclass     | person;user                                                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+

after my changes via the occ command:
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                   |
| hasPagedResultSupport         |                                                                                                                                     |
| homeFolderNamingRule          |                                                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                                                   |
| ldapAgentName                 | CN=hidden,OU=hidden,OU=hidden,DC=hidden,DC=hidden                                                                        |
| ldapAgentPassword             | ***                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                                                     |
| ldapBackupHost                |                                                                                                                                     |
| ldapBackupPort                |                                                                                                                                     |
| ldapBase                      | OU=hidden,OU=hidden,DC=hidden,DC=hidden;OU=hidden,OU=hidden,DC=hidden,DC=hidden                              |
| ldapBaseGroups                | OU=hidden,OU=hidden,DC=hidden,DC=hidden;OU=hidden,OU=hidden,DC=hidden,DC=hidden                              |
| ldapBaseUsers                 | OU=hidden,OU=hidden,DC=hidden,DC=hidden;OU=hidden,OU=hidden,DC=hidden,DC=hidden                              |
| ldapCacheTTL                  | 600                                                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                                                |
| ldapExperiencedAdmin          | 0                                                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                                                     |
| ldapExpertUsernameAttr        |                                                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=organizationalUnit)))                                                                                              |
| ldapGroupFilterGroups         |                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                   |
| ldapGroupFilterObjectclass    | organizationalUnit                                                                                                                  |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                        |
| ldapHost                      | hidden                                                                                                                        |
| ldapIgnoreNamingRules         |                                                                                                                                     |
| ldapLoginFilter               | (&(|(objectclass=person)(objectclass=user))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(sAMAccountType=%uid)))) |
| ldapLoginFilterAttributes     | sAMAccountType                                                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                   |
| ldapNestedGroups              | 0                                                                                                                                   |
| ldapOverrideMainServer        |                                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                                 |
| ldapPort                      | 389                                                                                                                                 |
| ldapQuotaAttribute            |                                                                                                                                     |
| ldapQuotaDefault              |                                                                                                                                     |
| ldapTLS                       | 0                                                                                                                                   |
| ldapUserDisplayName           | displayName                                                                                                                         |
| ldapUserFilter                | (|(objectclass=person)(objectclass=user))                                                                                           |
| ldapUserFilterGroups          |                                                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                                                   |
| ldapUserFilterObjectclass     | person;user                                                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+

### Client configuration
**Browser:** Firefox

**Operating system:**
Windows 10

**Comment by PVince81** [comment] 2016-03-14 11:01
@blizzz please help

**Comment by blizzz** [comment] 2016-03-14 14:53
The base setting on the first tab (Server) is the general Base DN. From this, specific bases for both Users and Groups are derived. Subsequently you can change those only on the "Advanced Tab", "Director Settings" section https://doc.owncloud.org/server/9.0/admin_manual/configuration_user/user_auth_ldap.html#directory-settings

Or via command line, which you did.

Might be confusing at first glance, but works as intended. Thus closing (not stating that there is no room for improvement).

**Closed by blizzz** 2016-03-14 14:53 UTC
Labels: app:user_ldap, bug
