### ISSUE TITLE
Shared folder doesn't display all files (endless scrolling seems to be broken for not logged in users)

### ISSUE THREAD

**Issue by mediumbuddha** [owncloud/core#20372] opened 2015-11-06 14:51 UTC
### Steps to reproduce
1. Share a folder with "many" files (in my case > 60 pdf files)
2. Just share, no special additions (no password, no time limit)
3. Open the shared link with the web browser (without being logged in / best to test, share with someone who has no account)

### Expected behaviour
I would expect to see all shared files - all files not visible due to monitor size limitation would be visible by scrolling down.

### Actual behaviour
I just see the amount of files in the viewable area and then the total amount of files. In my case, about 20 files are displayed - that's it. If unzooming the browser to 50% and reload the share link, I can see twice as much files..

### Server configuration
**Operating system**: Linux Ubuntu 12.04

**Web server:** Nginx 1.9.6

**Database:** MySQL 

**PHP version:** PHP 5.6

**ownCloud version:** (see ownCloud admin page) 8.2.0

**Updated from an older ownCloud or fresh install:** Updated from latest version

**List of activated apps:** 
Official: Activity, Deleted Files, External storage support, File locking, First run wizard, Mail Template editor, Pdf viewer, Share files, Text editor, Versions, Video viewer
Tested: Calendar, Contacts, Gallery+

**The content of config/config.php:**

{
    "system": {
        "forcessl": true,
        "installed": 1,
        "has_internet_connection": true,
        "datadirectory": "\/var\/data\/owncloud",
        "dbtype": "mysql",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "theme": "own-theme",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "allowZipDownload": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "version": "8.2.0.12",
        "maintenance": false,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "apps_paths": [
            {
                "url": "\/apps",
                "path": "\/var\/www\/owncloud\/apps",
                "writable": false
            },
            {
                "url": "\/user-apps",
                "path": "\/var\/www\/owncloud-apps\/user-apps",
                "writable": true
            }
        ],
        "dbname": "ownclouddb",
        "instanceid": "*****************",
        "dbhost": "localhost",
        "trusted_domains": [
            "owncloud.domain"
        ],
        "maxZipInputSize": 838860800,
        "mail_smtpmode": "php",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by d--j** [comment] 2015-11-06 15:23
This commit fixes it 480a005b47d5b61bba08e0f6b29b22e5ac919ed0 – does not look like it is part of a release yet.

**Comment by d--j** [comment] 2015-11-06 15:55
duplicate of #19886

**Comment by MorrisJobke** [comment] 2015-11-09 09:56
Tees. Duplicate and will be fixed in 8.2.1

**Closed by MorrisJobke** 2015-11-09 09:56 UTC
Labels: bug

**Comment by yannick67** [comment] 2015-12-14 21:22
i make the update 8.2.1, but this problem persist with ie 11.

**Comment by chrissi5120** [comment] 2016-01-01 18:41
8.2.2 here, 

Problem still exists

my public.js already looks like this:
scrollContainer: $('#content-wrapper'),

Tested with Firefox,Chromium,Chrome

**Comment by MorrisJobke** [comment] 2016-01-02 21:13
@chrissi5120 Can you please open a separate issue for this.

**Comment by saschaludwig** [comment] 2016-01-22 00:33
Problem still exists in 8.2.2 please fix this.

**Comment by cschachinger** [comment] 2016-01-22 20:01
I can confirm the issue also happens to me with 8.2.2

**Comment by matthias-g** [comment] 2016-01-23 18:58
@chrissi5120  @cschachinger @saschaludwig Please check if owncloud/files_pdfviewer@7d56944 fixes this issue for you.

**Comment by picpic122** [comment] 2016-01-24 13:08
@chrissi5120 @cschachinger @saschaludwig
I have just applied these Changes in my owncloud installation 8.2.2 as recommended by @matthias-g 
https://github.com/owncloud/files_pdfviewer/commit/7d56944
Now scrolling in a shared link works in Chrome and Firefox

**Comment by ovidiub13** [comment] 2016-01-30 10:12
This issue also affects the gallery. If I share a folder of pictures, I can see only the ones that fit in the current height. Scrolling does nothing. I've tried to look in the css and js for things like in owncloud/files_pdfviewer@7d56944 but with no success.

Should I report a new bug for this?

**Comment by matthias-g** [comment] 2016-01-30 10:28
@ovidiub13 Have you already applied the changes of owncloud/files_pdfviewer@7d56944 to your files in apps/files_pdfviewer?

**Comment by ovidiub13** [comment] 2016-01-30 12:01
@matthias-g I can't. That's for the pdfviewer. The problem i'm having is with the gallery.

**Comment by matthias-g** [comment] 2016-01-30 12:17
@ovidiub13 Have you checked that the folder apps/files_pdfviewer doesn't exist in your installation? Or have you disabled the pdf viewer app?
If you've installed from https://owncloud.org/download the pdf viewer is included and enabled by default.

**Comment by ovidiub13** [comment] 2016-01-30 14:42
@matthias-g I have the pdfviewer app installed. I haven't tried if I'm experiencing this problem with that app. I'm experiencing it with the Gallery app. it has it's own CSS and JS files.
I don't see the point of tampering with the pdfviewer app code since it's not the one giving me problems right now.

**Comment by matthias-g** [comment] 2016-01-30 15:56
@ovidiub13 The pdf viewer stylesheets are being loaded when you view a gallery, too. That's why they can break the gallery even they are not part of the gallery app.

**Comment by ovidiub13** [comment] 2016-01-30 18:43
@matthias-g  I've applied  owncloud/files_pdfviewer@7d56944 and it's fixed. Will this interfere with the future updates?

**Comment by matthias-g** [comment] 2016-01-30 18:58
@ovidiub13 No, I don't think it will.

**Comment by cyril23** [comment] 2016-04-09 15:19
Please commit a official bugfix.

For me the workaround with deactivating the PDF viewer app worked though.
