### ISSUE TITLE
Can not sync edited remote share file

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#16471] opened 2015-05-20 13:46 UTC
### Sync client problem

1. Create two user
2. As user1 create file `test.txt`
3. As user1 share file `test.txt` with `user2@localhost`
4. As user2 accept the share
5. Start a sync client for user2
6. Sync files for user2 with the client
7. As user2 edit the file
8. Sync files for user2 with the client

### Expected
The file is updated

### Actual
The file is kept as before and a conflict file is generated.

Client log:
```
#=#=#=# Syncrun started 2015-05-20T15:44:13 until 2015-05-20T15:44:13 (381 msec)
|0|test.txt|INST_SYNC|Up|1432129451|555c8f9e6ec0d|31||3|Error downloading http://localhost/ownCloud/master/core/remote.php/webdav/test.txt - server replied: Precondition failed (An If-Match header was specified, but none of the specified the ETags matched.)|0|23|1432129183|555c8f9e6ec0d|00000041oc6erbfm5lll|INST_NONE|
```

What's also interesting is that on each sync-poll the client reports that "`test.txt` has been downloaded"
```
#=#=#=# Syncrun started 2015-05-20T15:42:58 until 2015-05-20T15:42:58 (372 msec)
13:42:58|209|test.txt|INST_SYNC|Down|1432129183|555c8f602a31e|23|00000041oc6erbfm5lll|4||0|23|1432129183|555c8f08798b9||INST_NONE|
#=#=#=# Syncrun started 2015-05-20T15:43:58 until 2015-05-20T15:43:58 (395 msec)
13:43:58|222|test.txt|INST_SYNC|Down|1432129183|555c8f9c20b7a|23|00000041oc6erbfm5lll|4||0|23|1432129183|555c8f627877d||INST_NONE|
```

PS: just tested and this also happens on stable8 :frowning:

**Comment by nickvergessen** [comment] 2015-05-20 14:12
Well I guess it's a duplicate of https://github.com/owncloud/core/issues/14726

**Comment by PVince81** [comment] 2015-06-02 11:51
Actually a duplicate of https://github.com/owncloud/core/issues/15125 where I managed to reproduce (and fix) this issue

**Closed by PVince81** 2015-06-02 11:51 UTC
Labels: bug, feature:federated-cloud-sharing
