### ISSUE TITLE
Sharing. It is not allowed to share a file with a user named with only one character

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16903] opened 2015-06-12 11:47 UTC
### Steps to reproduce
1. Create a user named with only one character. e.g. A
2. Try to share a file with the user just created.

### Expected behaviour
The file is shared with the user.

### Actual behaviour
It is not allowed to share a file with a user named with only one character.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** "version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 1.2.3
 - admin_audit: 0.6
 - encryption: 1.0.0
 - enterprise_key: 0.1.0
 - files: 1.1.9
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.1
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.2
 - files_versions: 1.0.5
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.4
 - user_ldap: 0.6.0
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![captura de pantalla 2015-06-12 a las 13 40 42](https://cloud.githubusercontent.com/assets/10596560/8129407/38ba944a-1109-11e5-84f9-afa062d5c0a2.png)

**Comment by PVince81** [comment] 2015-06-15 12:53
This is not a problem of being allowed.

The problem is that autocomplete only works with minimum 2 characters to avoid having too many results.

Duplicate of https://github.com/owncloud/core/issues/14095

**Closed by PVince81** 2015-06-15 12:53 UTC
Labels: bug, sev3-medium, sharing
