### ISSUE TITLE
path already shared with this user

### ISSUE THREAD

**Issue by kevinkk525** [owncloud/core#25151] opened 2016-06-16 17:38 UTC
Many users are in one group. I share a folder with that group for read-only. Now I want to add a specific user to that share who should be able to write to that folder. Adding a user to that share is not possible as the following error is reported: "path already shared with this user"

If I have a new folder and share it first with that user and after that with the whole group, then it works perfectly.

### Steps to reproduce
1. Create folder
2. Share folder with group
3. Share folder with one member of the group (to allow him write-access)

### Expected behaviour
User should be added to the share with the correct privileges

### Actual behaviour
Error: "path already shared with this user"

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:**apache

**Database:** mysql

**PHP version:** 7

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** 8.1.4

**Are you using encryption:** no

**Comment by PVince81** [comment] 2016-06-17 07:30
@owncloud/sharing

**Comment by TDannhauer** [comment] 2016-07-08 12:20
I have the same issue. sharing as describt bei the Threadstarter should be possible to allow fine grained permission setup

**Comment by PVince81** [comment] 2016-07-08 12:24
Ah yes, this is a regression. Duplicate of https://github.com/owncloud/core/issues/25359

Fix will be in 9.0.4.

**Closed by PVince81** 2016-07-08 12:24 UTC
Labels: bug, feature:sharing
