### ISSUE TITLE
 Cannot set e-mail address - \Swift_Validate::email($email) returns nothing

### ISSUE THREAD

**Issue by ChrisCheney** [owncloud/core#32754] opened 2018-09-19 01:52 UTC
### Steps to reproduce
1. Install ownCloud 10.0.10 on entware
2. Go to Settings via web ui and try to add an email address
3. Error 'invalid email address'

It also happens when you try to add a new user.

### Expected behaviour

It should work.

### Actual behaviour

It shows 'invalid email address'

### Server configuration
**Operating system**:

entware

**Web server:**

lighttpd 1.4.49

**Database:**

sqlite 3230100-1

**PHP version:**

php7 7.2.9-1

**ownCloud version:** (see ownCloud admin page)

10.0.10.4

**Updated from an older ownCloud or fresh install:**

fresh install

**Where did you install ownCloud from:**

owncloud website

**Signing status (ownCloud 9.0 and above):**

It says:

"No errors have been found."

**The content of config/config.php:**
    "config": {
        "instanceid": "oc0oamh915kk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/tmp\/mnt\/router\/entware\/share\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "10.0.10.4",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": "0"
    },

**List of activated apps:**
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

firefox 62.0

**Operating system:**

Linux Mint 19

#### ownCloud log (data/owncloud.log)

This is what was logged based on the changes noted in: https://github.com/owncloud/core/issues/27546#issuecomment-352038364

This is likely a different issue than that one though.

Notice there is no return value for "validate result".

```
{"reqId":"fPAoQOduDHhQRyRBqmgX","level":0,"time":"2018-09-18T23:39:01+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"***REMOVED SENSITIVE VALUE***","app":"DEBUG","method":"PUT","url":"\/owncloud\/index.php\/settings\/users\/***REMOVED SENSITIVE VALUE***\/mailAddress","message":"validate result: "}
```

**Comment by ownclouders** [comment] 2018-09-19 02:16
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/27546 (Cannot set e-mail address), https://github.com/owncloud/core/pull/29909 (Validate email address in mail settings), https://github.com/owncloud/core/issues/30915 (cannot set own full name or email address), https://github.com/owncloud/core/issues/27667 (Users cannot set email address on personal settings), and https://github.com/owncloud/core/issues/27916 (Can't test Email server settings, but can't set personal email address either).

**Comment by PVince81** [comment] 2018-10-16 20:55
does the email address contain special characters ? could be duplicate of https://github.com/owncloud/core/issues/13586 which required an upgrade of the bundled swiftmail library

**Comment by PVince81** [comment] 2019-03-13 15:15
closing due to lack of feedback. we'll update swiftmailer in 10.2 so you can try again with that version once it's out in a few weeks

**Closed** 2019-03-13 15:14 UTC
Labels: needs info
