### ISSUE TITLE
Let anonymous users create folder in a public shared folder 

### ISSUE THREAD

**Issue by redhell** [owncloud/core#17803] opened 2015-07-22 10:26 UTC
Hi,
i had the case that multiple users, who don't have owncloud, wanted to upload their files in a folder which was shared by myself.

The scenario:
I share folder x with rigths to public upload
User 1 wants to share files and creates a folder "Files user1"
User 2  wants to share files and creates a folder "Files user2"
and so on.
At this point user n is not able to create a folder and he uploads his files to the document root of the shared folder.
As you can see a mess of files will be created with no chance to assign them later.
I have to create the folders by hand in forseight who will upload their files. But it is hard because of a group of 30 people i don't know who of them will upload their files.
It would be much easier if the user create a folder by himself and it would be an great enhancement to owncloud.

**Comment by RealRancor** [comment] 2015-07-22 10:38
Looks to me like a duplicate of https://github.com/owncloud/core/issues/6635

**Comment by LukasReschke** [comment] 2015-07-22 10:41
Agreed. Thanks @RealRancor.

@RealRancor We can also grant you contributor permissions on this repository which would allow you to tag, edit and close issues. – If you're interested you just need to sign https://owncloud.org/contribute/agreement/ (since technically you can then also push to the code base) and after this we can grant you these permissions quite quickly :smile:

**Closed by LukasReschke** 2015-07-22 10:41 UTC

**Comment by redhell** [comment] 2015-07-22 11:00
Oh didn't see it when i searched for it.
