### ISSUE TITLE
group menu binds to last user row for any user after first page (from lazy load)

### ISSUE THREAD

**Issue by wrought** [owncloud/core#21492] opened 2016-01-06 23:17 UTC
on `/index.php/settings/users`

I'm having an issue with the user management interface. I want to change the membership status for various groups of an individual user account. However, when I select the group membership drop-down menu for a user in any row after the first page (loaded after I scroll down the page), instead of binding properly to the appropriate drop-down button I just clicked, the group menu binds to the last row of the first page of users (before the rows added via ajax). 

This appears like there is no group menu for my desired user, but if I scroll up, I can still select check-box items and so forth. However, this instead appears like I'm changing the group membership settings of a different user (namely the user of the last row of the first page before loading the rest).

Wondering if ya'll have test data and any test cases that include more than 1 page of users.

**Comment by MorrisJobke** [comment] 2016-01-07 09:35
cc @blizzz

**Comment by MorrisJobke** [comment] 2016-01-07 09:36
Duplicate of https://github.com/owncloud/core/issues/20503

**Closed by MorrisJobke** 2016-01-07 09:36 UTC
Labels: bug, settings:users, sev3-medium
