### ISSUE TITLE
ownCloud Web UI fails for LDAP users after login, when…

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#24467] opened 2016-05-06 11:26 UTC
### Steps to reproduce
1. Have LDAP configured, but without cache
2. Have Log level set to 0
3. Login with LDAP user

### Expected behaviour

Succeeds and redirect to files app

### Actual behaviour

Succeed, but ``The connection was reset``. Infinite loop!

The reason is: while doing a userExists operation against LDAP, a log line is attempted to be written. Since https://github.com/owncloud/core/commit/7adae4476f2a4488a00ce822cd2edc726b475c0e we log more information, including the logged in user. I.e. the user logged in user is retrieved, which means a userExists check is driven, so we end up in a cyclic dependency aka infinite loop.

### Server configuration
**Operating system**: Antergos

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 5.6

**ownCloud version:** git master

**The content of config/config.php:**

```
{
    "system": {
        "debug": true,
        "appstore.experimental.enabled": true,
        "apps_paths": [
            {
                "path": "\/srv\/http\/dev\/master\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/srv\/http\/dev\/master\/apps2",
                "url": "\/apps2",
                "writable": false
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/http\/dev\/master\/data",
        "dbtype": "mysql",
        "version": "9.1.0.0",
        "theme": "",
        "dbname": "oc_master",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": true,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocb9a5589224",
        "trusted_domains": [
            "zara.owncloud.bzoc",
            "192.168.2.14",
            "192.168.178.26"
        ],
        "maintenance": false,
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": "1",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "cachedirectory": "\/srv\/http\/dev\/master\/data\/cache",
        "overwrite.cli.url": "master",
        "trashbin_retention_obligation": "auto",
        "enforce_home_folder_naming_rule": false,
        "ldapProviderFactory": "\\OCA\\user_ldap\\lib\\LDAPProviderFactory"
    }
}

```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (AD)

**Comment by blizzz** [comment] 2016-05-06 11:26
@LukasReschke

**Comment by PVince81** [comment] 2016-05-24 12:21
Raising to critical, because it will make debug log impossible when wanting to ask info from systems that run LDAP.

Any idea how to fix this ? I suppose it was introduced recently when adding the user id in log statements ?

CC @ChristophWurst @SergioBertolinSG

**Comment by PVince81** [comment] 2016-05-24 12:21
@davicente

**Comment by PVince81** [comment] 2016-05-24 12:22
Is there a way to use the user's UID directly instead of having to get the user object and check for existence ?

**Comment by davicente** [comment] 2016-05-24 12:24
checking

**Comment by PVince81** [comment] 2016-05-24 12:25
Seems like we had a workaround in this duplicate ticket: https://github.com/owncloud/core/issues/24409
So since we don't have a clean solution short term I suggest we just apply that...

**Comment by davicente** [comment] 2016-05-25 08:05
I have applied that workaround (https://github.com/owncloud/core/pull/23799/commits/a50619200c6a08929dbe802118a6afadb376b866) and it's not working to me, it's not autenticating. And still an endless loop appears (but not always)

`{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b94a63ae-8742-1034-8e9e-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_kassulke_iii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_kassulke_iii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b94a8e10-8742-1034-8e9f-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_kassulke_iv,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_kassulke_iv,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b94ab994-8742-1034-8ea0-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_keebler,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:29+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaron_keebler,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T07:15:30+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T07:15:30+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"GoLs4ceQyLRQ2wd94RIV","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b94b0e62-8742-1034-8ea1-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T07:15:30+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}`


The authentication issue is solved in master thanks to this PR (https://github.com/owncloud/core/pull/24748). So I think this workaround will not offer any advantage right now. But master is breaking with LDAP authentication when log level is set tu mininum.

I suggest to close this issue and open another one for this bug.

**Comment by PVince81** [comment] 2016-05-25 08:31
@davicente if the preconditions / steps to reproduce this bug are the same as before, let's keep this ticket.

If the old workaround doesn't work then we need to find a new solution or workaround for it.

**Comment by PVince81** [comment] 2016-05-25 15:35
@davicente not sure how you tested, but that patch works for me: https://github.com/owncloud/core/pull/23799

I'll make a PR

**Comment by PVince81** [comment] 2016-05-25 15:41
PR here for master/9.1: https://github.com/owncloud/core/pull/24851

**Comment by davicente** [comment] 2016-05-25 16:20
I'm not sure if I'm doing something wrong, but when I log out with the LDAP user. I obtain the infinite loop again. 

Any case, loging in is working :)


`{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8ea61b6-8742-1034-8cef-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_dach,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_dach,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8ea9d16-8742-1034-8cf0-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_dach_ii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_dach_ii,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"No DN found for b8eaba6c-8742-1034-8cf1-39af73a96b9a on ldap:\/\/docker.oc.solidgear.es","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_daniel,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_daniel,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"7o6c6Tr31sl\/TjlrsTk\/","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-25T15:57:55+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}`

**Closed** 2016-06-01 12:56 UTC
Labels: bug, comp:core, regression, sev1-critical
