### ISSUE TITLE
Error output when passing --data-dir during command line installation

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#23637] opened 2016-03-30 00:56 UTC
### Steps to reproduce
*Basically, install ownCloud via CLI.*
1. Use [this](https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud_install.sh#L158-L187) script
2. Install ownCloud with --^ script

(Change `--data-dir` to something else other than `/var/www/owncloud/data`)

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#command-line-installation

### Expected behaviour
No error output

### Actual behaviour

OwnCloud installs fine, but I get this error output during install:

```
ownCloud is not installed - only a limited number of commands are available
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-30T00:48:11+00:00","method":"--","url":"--","user":"--"}
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"--"}
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"--"}
ownCloud was successfully installed
{"reqId":"mWcNULK3K9oZiXs7OLp1","remoteAddr":"","app":"PHP","message":"chmod(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#112","level":3,"time":"2016-03-30T00:48:13+00:00","method":"--","url":"--","user":"ocadmin"}

ownCloud version:
  - installed: true
  - version: 9.0.1.1
  - versionstring: 9.0.1 RC1
  - edition: 

```

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.6
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
9.0.1-RC1
**Updated from an older ownCloud or fresh install:**
New
**Where did you install ownCloud from:**
ZIP package from ownCloud

### Logs
 
No logs

**Comment by enoch85** [comment] 2016-03-30 17:47
@DeepDiver1975 Any thoughts?

**Comment by Xenopathic** [comment] 2016-03-30 18:51
Could you try replacing this line (https://github.com/owncloud/core/blob/master/lib/private/setup/mysql.php#L46) with the following:

   if (!$row or $row[0] == 0) {

i.e. s/result/row/ on that line

**Comment by enoch85** [comment] 2016-03-30 21:51
@Xenopathic Thanks, will try. Want to debug this with me tonite? Will be trying for one more hour. I'm enoch85 @ IRC.

**Comment by enoch85** [comment] 2016-03-30 22:13
@Xenopathic That gives me the same output, I think:

``` 
ownCloud is not installed - only a limited number of commands are available
{"reqId":"VPaNQo6uOLbk4fakRtTi","remoteAddr":"","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-30T22:11:56+00:00","method":"--","url":"--","user":"--"}
{"reqId":"VPaNQo6uOLbk4fakRtTi","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-30T22:11:57+00:00","method":"--","url":"--","user":"--"}
{"reqId":"VPaNQo6uOLbk4fakRtTi","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(636): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(587): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(558): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/maintenance\\\/install.php(84): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Maintenance\\\\Install->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Maintenance\\\\Install), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#14 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-30T22:11:57+00:00","method":"--","url":"--","user":"--"}
ownCloud was successfully installed
{"reqId":"VPaNQo6uOLbk4fakRtTi","remoteAddr":"","app":"PHP","message":"chmod(): No such file or directory at \/var\/www\/owncloud\/lib\/private\/log\/owncloud.php#112","level":3,"time":"2016-03-30T22:11:57+00:00","method":"--","url":"--","user":"ocadmin"}
```

**Comment by enoch85** [comment] 2016-03-30 22:23
Also, when I set `--data-dir` ownCloud expects `occ` to be in `$OCDATA/occ`.

[Changing pass](https://github.com/enoch85/ownCloud-VM/blob/master/beta/owncloud-startup-script.sh#L275-L278) gives me this: 

```
Could not open input file: /var/data/occ
Could not open input file: /var/data/occ
```

**Comment by Xenopathic** [comment] 2016-03-30 22:44
It's that "Undefined offset" error that I was trying to fix - as far as I can tell that line is supposed to check if the ownCloud tables have been installed, and if they haven't, install them. Since the DB isn't being properly populated, you then get the cascade of errors with missing tables.

If you can, put some `var_dump()` statements to see the actual value of `$row` at that point in the script.

**Comment by enoch85** [comment] 2016-03-30 22:50
@Xenopathic PHP? Not my area of expertise. Please join me on IRC, easier to chat there. :)

**Comment by Xenopathic** [comment] 2016-03-30 23:00
@enoch85 Sorry, I've got a long trip ahead of me tomorrow morning so can't stay up late tonight.

**Comment by enoch85** [comment] 2016-03-30 23:02
@Xenopathic It's ok. I'm going offline now anyway. We could pick this up later, any help is appreciated.

**Comment by enoch85** [comment] 2016-04-04 11:00
@PVince81 Are you the occ command master? :) I know 9.0.1 is due tomorrow, would be great if a fix for this could go in.

**Comment by enoch85** [comment] 2016-04-04 11:37
cc @DeepDiver1975 as well, as the issues seems related to DAV, Contacts and Calenadar. Maybe @georgehrke because of the Calendar?

**Comment by enoch85** [comment] 2016-04-04 19:58
@Xenopathic Ping on IRC. :)

**Comment by enoch85** [comment] 2016-04-04 22:20
Ok so @Xenopathic fixes work. Any chance we could get this in 9.0.1? Please. :)

**Comment by PVince81** [comment] 2016-04-18 09:50
@Xenopathic can you submit a PR with the suggested change ? Thanks

**Comment by Xenopathic** [comment] 2016-04-18 10:15
@PVince81 I did (#23790) but @DeepDiver1975 wanted to make a better version... still waiting on that

**Comment by enoch85** [comment] 2016-05-18 16:57
Any update here @DeepDiver1975?

**Comment by PVince81** [comment] 2016-05-19 08:03
@DeepDiver1975 can we use the current version instead of waiting for the "better version" ? :smile:

**Comment by PVince81** [comment] 2016-06-27 13:28
From what I see the PRs were merged and @DeepDiver1975 hasn't delivered a "better version".

If the problem is fixed I'm closing this now. Please reopen if you think otherwise.

**Closed by PVince81** 2016-06-27 13:28 UTC
Labels: 3 - To Review, bug, comp:console-occ

**Comment by enoch85** [comment] 2016-06-27 17:43
The PR fixing this issue is not merged, just partially. Right @Xenopathic?

**Comment by enoch85** [comment] 2016-06-27 17:46
@PVince81 Please refer to the merged PR.

**Comment by PVince81** [comment] 2016-06-28 07:52
I thought this https://github.com/owncloud/core/pull/23760 would fix it, it was also backported by you: https://github.com/owncloud/core/issues/23805 and https://github.com/owncloud/core/issues/23807, both merged.

Is the issue still happening ?

**Comment by enoch85** [comment] 2016-06-28 07:56
#23760 was only the MySQL part, but not the whole fix. 

Anyway, it's fixed now and there is a PR that will backport the fix as well. Look here https://github.com/owncloud/core/pull/23790 for details.

**Comment by DeepDiver1975** [comment] 2016-06-28 08:12
> Look here #23790 for details.

the backport is here #25279
