### ISSUE TITLE
Users view doesn't load

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13710] opened 2015-01-27 14:23 UTC
### Steps to reproduce

Using an administrator account: 

1. Go to the users view.
2. Wait

### Expected behaviour
Users are loaded.

### Actual behaviour
Page keeps loading users with no luck.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
```
{"installed":true,"maintenance":false,"version":"8.0.0.4","versionstring":"8.0 beta 2","edition":""}
```
**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'instanceid' => 'ocy3qofa1jym',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '10.40.40.143',
  ),
  'datadirectory' => '/var/www/html/owncloud_27-01-15/data',
  'overwrite.cli.url' => 'http://10.40.40.143/owncloud_27-01-15',
  'dbtype' => 'mysql',
  'version' => '8.0.0.4',
  'dbname' => 'owncloud_27-01-15',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin7',
  'dbpassword' => '',
  'installed' => true,
);
```

**Logs**
```json
{"reqId":"39c71e48fce7bbeb352179aba95820f0","remoteAddr":"10.40.40.56","app":"index","message":"Exception: {\"Message\":\"Could not resolve OCA\\\\Settings\\\\Controller\\\\UsersController! Class OCA\\\\Settings\\\\Controller\\\\UsersController does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(93): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\Settings\\\\Co...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/private\\\/appframework\\\/app.php(90): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\Settings\\\\Co...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('UsersController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#3 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/settings\\\/users...')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/index.php(28): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud_27-01-15\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php\",\"Line\":79}","level":4,"time":"2015-01-27T14:10:26+00:00"
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

cc @LukasReschke 
cc @jnfrmarks

**Comment by LukasReschke** [comment] 2015-01-27 14:24
How exactly did you setup your ownCloud instance? – What were the involved steps?

**Comment by SergioBertolinSG** [comment] 2015-01-27 14:26
I just cloned current core repository (27-01-2015 15:25) with all submodules recursively.

**Comment by LukasReschke** [comment] 2015-01-27 14:27
@MorrisJobke Ever experienced something like that?

It seems to try to load the Controller from the OCA namespace and not the OC one.

**Comment by MorrisJobke** [comment] 2015-01-27 15:36
Pretty message:

```
{
	"reqId":
	"39c71e48fce7bbeb352179aba95820f0",
	"remoteAddr":"10.40.40.56",
	"app":"index",
	"message":"Exception: {
		"Message":"
			Could not resolve OCA\Settings\Controller\UsersController! Class OCA\Settings\Controller\UsersController does not exist","Code":0,"Trace":"#0 lib/private/appframework/utility/simplecontainer.php(93): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\Settings\Co...')
			#1 lib/private/appframework/app.php(90): OC\AppFramework\Utility\SimpleContainer->query('OCA\Settings\Co...')\
			#2 lib/private/appframework/routing/routeactionhandler.php(44): OC\AppFramework\App::main('UsersController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\
			#3 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\
			#4 lib/private/route/router.php(250): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\
			#5 lib/base.php(763): OC\Route\Router->match('/settings/users...')\
			#6 index.php(28): OC::handleRequest()\
			#7 {main}",
		"File":"lib/private/appframework/utility/simplecontainer.php",
		"Line":79
	}",
	"level":4,
	"time":"2015-01-27T14:10:26+00:00"
}
```

**Comment by MorrisJobke** [comment] 2015-01-27 15:40
This route is defined here https://github.com/owncloud/core/blob/3478634df1ce2b7717bfe211425f59c4107688f8/settings/routes.php#L15

Maybe @Raydiation knows why this breaks? But why is it working in our environments?!?

**Comment by LukasReschke** [comment] 2015-01-27 15:54
Could _somehow_ reproduce this locally (it just happened) – I'll take a look. Showstopper.

@DeepDiver1975 FYI

**Comment by Raydiation** [comment] 2015-01-27 16:23
Breaks for me too. You'll encounter this issue because the controller is most likely not defined in the container, so it is being looked up in the OCA namespace. Other than that: settings has an app structure it behaves like an app and should be an app :)

**Comment by LukasReschke** [comment] 2015-01-27 16:25
Regression caused by https://github.com/owncloud/core/commit/9fbeaf0fd9f3ba4cd01aa566553cb2373dde8cb2 seems not to like `$c->query('OCP\\App\\IAppManager')` as far I can see

**Comment by LukasReschke** [comment] 2015-01-27 16:25
> Other than that: settings has an app structure it behaves like an app and should be an app :)

Sure – but nothing we can change a few days before the release :-)

**Comment by LukasReschke** [comment] 2015-01-27 16:28
WTF. It works when doing `$c->query('OCP\\IAppManager')` … mhm…

**Comment by LukasReschke** [comment] 2015-01-27 16:30
Got it – https://github.com/owncloud/core/blob/master/lib/private/appframework/dependencyinjection/dicontainer.php#L68-70 is to blame

**Comment by Raydiation** [comment] 2015-01-27 16:30
@LukasReschke I've added the wrong namespace in here https://github.com/owncloud/core/blob/master/lib/private/appframework/dependencyinjection/dicontainer.php#L68

**Comment by LukasReschke** [comment] 2015-01-27 16:30
I'll prepare a PR :)

**Comment by MorrisJobke** [comment] 2015-01-27 16:31
@Raydiation YOu added the wrong namespace: https://github.com/owncloud/core/pull/12830/files#diff-94695368380289cb5ce414833e2a7947R67

**Comment by MorrisJobke** [comment] 2015-01-27 16:31
:stuck_out_tongue_closed_eyes:

**Comment by LukasReschke** [comment] 2015-01-27 16:36
Patch is at https://github.com/owncloud/core/pull/13718 - @SergioBertolinSG would be great if you could test this tomorrow again. (though I think we already have that patch merged then ;))

**Comment by Raydiation** [comment] 2015-01-27 16:38
As for the error message: https://github.com/owncloud/core/blob/master/lib/private/appframework/app.php#L85

It checks to see if a controller exists in the container under that name and catches a query exception which because of the recursive resolve method was thrown when resolving the app manager. So it tries to look up the controller in the OCA namespace which ofc fails.

Quite hard to fix this kind of error behavior

**Comment by Raydiation** [comment] 2015-01-27 16:38
Basically caused by backwards compability fixes

**Closed** 2015-01-27 16:39 UTC
Labels: bug, ownCloud 8.0 Showstoppers, Regression, settings:users

**Comment by Raydiation** [comment] 2015-01-27 16:41
Confirmed working

**Comment by LukasReschke** [comment] 2015-01-27 16:42
Thanks @Raydiation :-)

**Comment by SergioBertolinSG** [comment] 2015-01-28 07:45
Working fine now for me too.
