### ISSUE TITLE
Federated cloud sharing: New share doesn't show up in "all files"

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#19606] opened 2015-10-06 12:22 UTC
### Steps to reproduce
1.Have two instances of owncloud running
2.Share from from server1 vie federated share to server2 
3.As user on server2 share the federated share from server one with a group on server2.

### Expected behaviour
Users within the group should see the shared file in the "all files section"

![bildschirmfoto 2015-10-06 um 13 53 22](https://cloud.githubusercontent.com/assets/12275313/10307828/147356d8-6c32-11e5-9118-a388346d3aa5.png)

### Actual behaviour

![bildschirmfoto 2015-10-06 um 13 53 22](https://cloud.githubusercontent.com/assets/12275313/10307784/aedd6d4a-6c31-11e5-9dc6-e4fa3c85cb0f.png)
File doesn't show in the all Files section, you can find it in "shared with you" though.

### Server configuration for both servers, 
**Operating system**:
Ubuntu 14.04
**Web server:**
APAche
**Database:**
Mysql
**PHP version:**
55
**ownCloud version:** (see ownCloud admin page)
8.1.3 stable
**Updated from an older ownCloud or fresh install:**
fresh 
**List of activated apps:**
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - logreader: 1.0.1
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth

Log Server 1 (file origin)
```Error	core	Exception while scanning storage "shared::2de7c4af480b77c801517dab539dbad4": Sabre\HTTP\ClientException: SSL certificate problem: self signed certificate```

Log Server 2 (file destination) 

```Error	files_sharing	Unable to get mount for shared storage '3' user 'admin'```

cc @hodyroff

**Comment by schiesbn** [comment] 2015-10-06 12:49
@Kawohl that goes back to https://github.com/owncloud/core/issues/19599 which describes how we can improve the situation, right?

For now, this is the solution: https://github.com/owncloud/core/issues/19370#issuecomment-145818551
And this the work around: https://github.com/owncloud/core/issues/19370#issuecomment-145818272

**Comment by Kawohl** [comment] 2015-10-06 12:53
There is something wrong because both servers don´t have any certs. and https is not enforced on neither one of them.

**Comment by schiesbn** [comment] 2015-10-06 12:55
ok, let's see if I can reproduce it

**Comment by Kawohl** [comment] 2015-10-06 12:56
I used two machines on Digitalocean. And can give you Access

**Comment by PVince81** [comment] 2015-10-06 12:57
Duplicate of https://github.com/owncloud/core/issues/15116.

Also you have a weird screenshot, it seems that both "All files" and "Favorites" are selected at the same time ?!

**Comment by schiesbn** [comment] 2015-10-06 12:58
@PVince81 I was just about to write the same

**Closed by PVince81** 2015-10-06 12:57 UTC

**Comment by Kawohl** [comment] 2015-10-06 13:04
![bildschirmfoto 2015-10-06 um 15 03 52](https://cloud.githubusercontent.com/assets/12275313/10309204/8726e5ce-6c3b-11e5-92f9-032721b77046.png)
Here ya go.

**Comment by PVince81** [comment] 2015-10-06 13:05
@Kawohl hopefully it was not a bug then :smile:
