### ISSUE TITLE
Upgrade app in the admin panel allows skipping major versions even though it's not supported.

### ISSUE THREAD

**Issue by sirhans** [owncloud/core#24140] opened 2016-04-21 04:28 UTC
A quick suggestion:

I just used the upgrade tool in the admin panel to go from 8.0.0 to 8.2.1.  Of course, it failed and left my owncloud installation broken.  I should have read the documentation that said skipping major versions is not supported.  But, could you add a check to the upgrade tool that prevents version-skipping updates, or at least shows a warning?

thanks.

**Comment by RealRancor** [comment] 2016-04-21 04:43
Duplicate of https://github.com/owncloud/appstore-issues/issues/4

**Comment by MorrisJobke** [comment] 2016-04-21 07:05
@LukasReschke is working on this.

Closing as duplicate.

**Closed by MorrisJobke** 2016-04-21 07:05 UTC
