### ISSUE TITLE
fetchRow method removed after upgrade to DBAL 2.5.x

### ISSUE THREAD

**Issue by LEDfan** [owncloud/core#14985] opened 2015-03-18 06:51 UTC
Hi

When trying to run the Chat app with ownCloud master I'm getting this error:
````
( ! ) Fatal error: Call to undefined method Doctrine\DBAL\Statement::fetchRow() in /var/www/owncloud/apps/chat/lib/och/db/conversationmapper.php on line 110
````

The documentation says this
````
 public function authorNameCount($name) {
        $sql = 'SELECT COUNT(*) AS `count` FROM `*PREFIX*myapp_authors` ' .
            'WHERE `name` = ?';
        $query = $this->db->prepareQuery($sql);
        $query->bindParam(1, $name, \PDO::PARAM_STR);
        $result = $query->execute();

        while($row = $result->fetchRow()) {
            $result->closeCursor();
            return $row['count'];
        }
    }
````
Which is almost the same code as I'm using. I think this method is removed after upgrading to DBAL 2.5.x?

Why is this method removed?

**Comment by DeepDiver1975** [comment] 2015-03-18 07:14
@Raydiation did we mess up the methods somehow? Can you please have a look? THX

**Comment by DeepDiver1975** [comment] 2015-03-18 07:15
@LEDfan which core version are you running? master? THX

**Comment by LEDfan** [comment] 2015-03-18 07:22
@DeepDiver1975 I'm running master indeed.
I updated the error I get.

**Comment by Raydiation** [comment] 2015-03-18 08:02
https://github.com/owncloud/core/blob/master/lib/private/db/statementwrapper.php

This is some none standard kung fun that we've added on the statement wrapper. Since master skips this now and uses the connection directly, this won't work anymore ofc. If this is still in the docs, we need to fix it. The correct method is fetch instead of fetchRow. This also works on lower versions so I'd simply close this issue (also keeping in mind that the statement wrapper is in the private namespace)

**Comment by Raydiation** [comment] 2015-03-18 08:07
This should however still work fine if you are using IDb instead of IDbConnection like in the change since that class still wraps the thing in the statement wrapper https://github.com/owncloud/core/blob/master/lib/private/appframework/db/db.php#L58

**Comment by LEDfan** [comment] 2015-03-18 08:11
@Raydiation the Mapper class use the IDBConnection: https://github.com/owncloud/core/blob/master/lib/public/appframework/db/mapper.php#L48 .

IMO this is a change to our public API (i.e. the mapper) and this will break some apps.

**Comment by Raydiation** [comment] 2015-03-18 08:14
Ok, I see where the issue lies now, this breaking change was actually not expected :P. The plan is to remove fetchRow but with a migration period of 2 years but still keep the old stuff working until then. The issue is here: https://github.com/owncloud/core/blob/master/lib/public/appframework/db/mapper.php#L195

The statement for doctrine is not returned from the execute method, IDb and our statement wrapper should do that https://github.com/owncloud/core/blob/master/lib/public/appframework/db/mapper.php#L220

I will add a simple instanceof check to check if this thing returns a statement wrapper and return the execute result directly.

**Comment by Raydiation** [comment] 2015-03-18 08:28
I didnt test the PR, can you check if it works?

**Comment by Raydiation** [comment] 2015-03-18 08:48
Or tell me how to test it for the chat app ;)

**Closed** 2015-03-19 16:04 UTC
Labels: 5 - To review, bug
