### ISSUE TITLE
Weird behavior if user is in 2 or more groups with one shared folder

### ISSUE THREAD

**Issue by JonesfromHan** [owncloud/core#22455] opened 2016-02-16 20:05 UTC
This is a possible duplicate, but I have seen no issue with the exact behavior.

### Steps to reproduce
1. Add two Users, User A and User B
2. Add two Groups, Group 1 and Group 2
3. User B has not logged in yet on the server
4. User B is assigned to both Groups
5. User A makes a new folder "WTF" and shares it with both Groups
6. User B logges in for the first time
7. -> Point A
8. User B leaves one Group and then enters again (by himself or admin)
9. -> Point B
10. User A removes the share with and both groups, and then shares again
11. -> Point C

### Expected behaviour
The User B should only see the folder one time

### Actual behaviour
Point A: He does see only one copy of the folder, even if he is in both groups
Point B: He has now 2 copies of the folder, one time with a (2) behind it. If he marks the secons one (the little hook), it is set on the first copy of the folder
Point C. He sees only one folder

### Server configuration
**Operating system**:
Ubuntu 14.04.3 LTS
**Web server:**
Apache 2.4.7
**Database:**
MySQL 5.5.47
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0 beta 1 (daily) Build:2016-02-16T04:41:41+00:00 907430a80812bbf5378a4c5d10de6ab7ddf6f8e4
**Updated from an older ownCloud or fresh install:**
fresh
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Activity
Comments
Deleted files
First Run Wizard
Gallery
Mail Template Editor
Notifications
PDF Viewer
Provisioning API
Share files
System tags
Text Editor
Update Notification
Versions
Video player

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc2tuvuc72zw',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'oc9.domain.tld',
  ),
  'datadirectory' => '/path/web/data',
  'overwrite.cli.url' => 'http://oc9.domain.tld',
  'dbtype' => 'sqlite3',
  'version' => '9.0.0.11',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:**
no
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Firefox 44.0.2
**Operating system:**
Windows 8.1
#### Web server error log
no error log

#### ownCloud log (data/owncloud.log)
{"reqId":"YMLj9PF4WqO0SKmsC95z","remoteAddr":"95.90.207.169","app":"PHP","message":"is_readable(): open_basedir restriction in effect. File(\/dev\/urandom) is not within the allowed path(s): (\/var\/www\/clients\/client2\/web19\/web:\/var\/www\/clients\/client2\/web19\/private:\/var\/www\/clients\/client2\/web19\/tmp:\/var\/www\/oc9.boeck.mn\/web:\/srv\/www\/oc9.boeck.mn\/web:\/usr\/share\/php5:\/usr\/share\/php:\/tmp:\/usr\/share\/phpmyadmin:\/etc\/phpmyadmin:\/var\/lib\/phpmyadmin) at \/var\/www\/clients\/client2\/web19\/web\/3rdparty\/paragonie\/random_compat\/lib\/random.php#66","level":3,"time":"2016-02-16T19:29:28+00:00"}
Multiple times

**Comment by ItsReallyMeDE** [comment] 2016-02-16 20:40
Use case description to understand the impact of this issue:
Assume owncloud use for a set of working groups (WG). A WG corresponds to an owncloud "group".
- Users may obviously be part of multiple WGs
- Assets (Folders, calenders) can be shared with one or several WGs
--> Assigning users to multiple WGs leads to duplicated shared calendars or shared folders as reported above, IFF these assets are shared with multiple WGs.

Very undesirable behavior.

**Comment by PVince81** [comment] 2016-02-17 09:29
@rullzer please evaluate severity and whether this is a regression

**Comment by ItsReallyMeDE** [comment] 2016-02-17 11:00
@PVince81 we observed the "feature" in 8.2.2 and retested on the latest 9

**Comment by rullzer** [comment] 2016-02-18 15:13
Indeed also happens on 8.2.

This basically happens because we check for collison. But if the user never logged in yet there never is collision.

The feature is a bit broken anyway. since if the folder was first shared with `group1` and then a recipient moves it to `foo` and then it is shared with `group2` they would still see different shares.

@PVince81 I propose to tackle this properly when we move the internals over to sharing 2.0. So 9.1.
Any fix I can come up with now will be incomplete with the potential to break stuff.

**Comment by PVince81** [comment] 2016-09-22 10:21
Cannot reproduce on 9.0.5 and 9.1.1, likely fixed through https://github.com/owncloud/core/pull/25543

**Closed by PVince81** 2016-09-22 10:21 UTC
Labels: bug, feature:sharing, sev3-medium
