### ISSUE TITLE
Redis Server Went Away

### ISSUE THREAD

**Issue by guyintruck** [owncloud/core#16216] opened 2015-05-09 16:17 UTC
On 8.0.2 this error keeps popping up, this apparently is being fixed in 8.1, however what can the 8.0.2 users do?  Can this be fixed?  Is there something I can change in my settings/php?

**Comment by RealRancor** [comment] 2015-05-09 16:49
Just as a reference. The main problem here seems to be that the redis server itself is broken/wrong configured but OC is always choosing to use redis if no other caches are enabled: https://github.com/owncloud/core/issues/14742

**Comment by PVince81** [comment] 2015-10-27 16:25
Duplicate of https://github.com/owncloud/core/issues/14742

@guyintruck you might be able to tweak config.php to prevent it using redis: https://github.com/owncloud/core/issues/14742#issuecomment-113035872

**Closed by PVince81** 2015-10-27 16:25 UTC
Labels: bug

**Comment by HLFH** [comment] 2015-10-27 20:48
Redis Server Went Away issue solved https://github.com/owncloud/contacts/issues/1082#issuecomment-151638547

**Comment by Ardakilic** [comment] 2016-03-27 21:01
@HLFH the link you've provided is unreachable, did you (and anyone reading here) by any chance have a copy saved somewhere ?

**Comment by RealRancor** [comment] 2016-03-27 21:05
@Ardakilic The old contacts app was moved to the "owncloudarchive" organization so the issue is now available here: https://github.com/owncloudarchive/contacts/issues/1082#issuecomment-151638547

**Comment by Ardakilic** [comment] 2016-03-27 21:08
@RealRancor 

![](http://i.imgur.com/n71EEKF.jpg)

**Comment by HLFH** [comment] 2016-03-27 23:49
@Ardakilic I got the same issue before yesterday when I installed once again ownCloud with Redis. So, I also remembered this issue on `owncloudarchive/contacts` and it now works perfectly. If you need help in some way, don't hesitate to ask.

**Comment by Ardakilic** [comment] 2016-03-27 23:56
Thank you @HLFH  , @RealRancor , I sorted it out, but with another way, I don't know if these are related though.

I don't know which did it, but here goes:

I firstly checked group and user owners of my redis sock file, which were both `redis`.

So, I added my nginx user `www-data` to `redis` group, so it can reach the redis sock:

```shell
usermod -a -G redis www-data
```

Then I've commented out `unixsocketperm` parameter from `/etc/redis/redis.conf`, which was uncommented with 755 as value. Now, only unixsocker parameter is enabled.

After this, I could run owncloud with redis as socket just fine.

**Comment by HLFH** [comment] 2016-03-28 00:56
@Ardakilic Cool, congratulations you did fine! Same as you but with Arch Linux, Nginx, Redis, MariaDB, and PHP7. Have a great day.

**Comment by Ardakilic** [comment] 2016-07-29 14:44
Just a side note: I have clean installed a Debian 8, and I have installed PHP7 and Redis from dotdeb.org's repositories, and I've stumbled upon to the same issue, and the fix provided above also fixed it on Debian.

**Comment by RealRancor** [comment] 2016-07-29 15:10
@Ardakilic Time to make a FAQ out of his at https://central.owncloud.org/c/faq :smile:
