### ISSUE TITLE
External shares can been seen in a folder.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#27535] opened 2017-03-29 16:33 UTC
### Steps to reproduce
1. Create an external storage share  (e.g. Google-drive)
2. Change the mount point from the external share to a folder (e.g. /ext-shares/Google-drive)
3. Share the folder with another user (e.g. Charlie shares ext-shares with Snoopy)

### Expected behavior
Snoopy see the external share folder in the share folder

### Actual behavior
Snoopy see an empty share folder

### Server configuration
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7

**ownCloud version:** (see ownCloud admin page)
9.1.4

**Updated from an older ownCloud or fresh install:**
Upgraded 

**Where did you install ownCloud from:**
Tar

**Comment by cdamken** [comment] 2017-03-29 16:57
![shares1](https://cloud.githubusercontent.com/assets/7264495/24466527/786766ce-14b1-11e7-8759-ed6071742554.png)

The shares are created by the user

**Comment by cdamken** [comment] 2017-03-29 16:57
FYI @hodyroff @michaelstingl

**Comment by davitol** [comment] 2017-03-29 19:14
@cdamken Cannot reproduce this issue in oC 9.1.4. and in oC 10 beta

** Steps followed**

1 - Configure a Google Drive mount (global mount)
2 - In Files view, create a folder called Folder
3 - In Admin menu / External Storage Set Folder/GoogleDrive as Folder name for the mount
4 - Share folder 'Folder' with userB
5 - Log in with userB
6 - Browse into Folder shared

**Result**

The mount is visible and available.

Did I missunderstood any step?

**Comment by PVince81** [comment] 2017-03-30 09:54
Duplicate of https://github.com/owncloud/core/issues/20990.

But I'm surprised if @davitol says it works for him.

**Comment by PVince81** [comment] 2017-03-30 09:59
@davitol I can reproduce the issue on 9.1.4 and master, see my steps in https://github.com/owncloud/core/issues/20990 for more details. One part is about making sure the mount point is only visible for the sharer, so if it's system-wide, adjust its scope to be only for the first user.


Closing as duplicate of https://github.com/owncloud/core/issues/20990

**Closed by PVince81** 2017-03-30 09:59 UTC
Labels: bug

**Comment by PVince81** [comment] 2017-03-30 10:09
Note that adding support for this could potentially also add support for "a share in a share" but would likely create potential recursions.

**Comment by davitol** [comment] 2017-03-30 10:16
BTW @Vincent @cdamken, using Personal mounts, the share is not done, so there's not only an issue related to 'available for'

**Comment by michaelstingl** [comment] 2017-03-30 11:40
> Note that adding support for this could potentially also add support for "a share in a share" but would likely create potential recursions.

We need to decide if we want to support it or not. @hodyroff @pmaier1 Where can I find this information?
