### ISSUE TITLE
[10.0.8.5] Sharing-Dialog: select2 is not a function

### ISSUE THREAD

**Issue by Commifreak** [owncloud/core#31532] opened 2018-05-25 09:57 UTC
### Steps to reproduce
1. Open the share dialog for a text file as example
2. Dialog is empty

### Expected behaviour
Normal dialog should appear

### Actual behaviour
Javascript error occurs

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** MySQL 5.5

**PHP version:** 5.6

**ownCloud version:** 10.0.8

**Updated from an older ownCloud or fresh install:** updated (10.0.7)

**Where did you install ownCloud from:** updater

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here:

No errors have been found.
```

**List of activated apps:**

```
Text-Editor
```

### Client configuration
**Browser:** FF 60

**Operating system:** Windows 10

## The problem

When I open a share-dialog, it stays empty. I've recorded it for you:

![20180525_114325](https://user-images.githubusercontent.com/87267/40538655-9182b28c-6012-11e8-8fcd-77cc8e105393.gif)

This is the developer console output (second 17):

![20180525_114643](https://user-images.githubusercontent.com/87267/40538676-9e29e7a8-6012-11e8-9ad9-8797974b4ac5.gif)

Something wrong with select2? Something missing?

Thanks in advance!

**Comment by Commifreak** [comment] 2018-05-25 10:03
Related to #31481  #31338 and #31454

**Comment by patrickjahns** [comment] 2018-05-25 10:09
Duplicate of #31338 - fixed by https://github.com/owncloud/core/pull/31498 (master) - backport for next release outstanding

**Closed by patrickjahns** 2018-05-25 10:09 UTC

**Comment by ownclouders** [comment] 2018-05-25 10:20
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixheidecke.

Possibly related issues are https://github.com/owncloud/core/issues/5155 (Sharing dialog doesn't search for users), https://github.com/owncloud/core/issues/6327 (File Share dialog doesn't appear), https://github.com/owncloud/core/issues/10331 (Selecting "No people found" in share with dialog gives error), https://github.com/owncloud/core/issues/15812 (Share dialog password field hidden when enabled), and https://github.com/owncloud/core/issues/18910 (Share Dialog Problems repeating user list).
