### ISSUE TITLE
The federated sharing with SHIBB and Redirected server is not working, you can't share

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/core#21252] opened 2015-12-17 09:53 UTC
### Steps to reproduce
You new two differents server (one with SHIB (with HTTPS) (e.g user Myself), other normal sever (with HTTP) (e.g user Admin)
1. Go to the Desktop Client with SHIB
2. Create a new folder (e.g. aaa)
3. Click on Share with oC
4. On "Share with users or groups" enter a user on normal server (e.g. admin@xxxxxxxx)
5. Click Enter
6. Go to the Server web with the user Admin
7. Accept the screen "Add Remote Share"
![screen shot 2015-12-15 at 10 54 38](https://cloud.githubusercontent.com/assets/12032058/11807942/8cb8458c-a31d-11e5-9692-e9412e90c4ec.png)

### Expected behaviour
You should see the shared folder

### Actual behaviour
When you accept the screen and go to the Desktop Client with the user Admin,  you can't see the folder aaa to share

### Server configuration
Desktop client v ownCloud-2.1.0.2967-nightly20151215.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by Dianafg76** [comment] 2015-12-17 09:54
related #4287, and #4234

**Comment by rullzer** [comment] 2015-12-17 10:08
@schiesbn

**Comment by DeepDiver1975** [comment] 2015-12-17 10:15
refs https://github.com/owncloud/core/issues/21227#issuecomment-165101455

As stated above - federation and shibboleth needs QA

**Comment by PVince81** [comment] 2015-12-21 10:02
@Dianafg76 any server logs ?

@davitol already posted some here https://github.com/owncloud/core/issues/21227#issuecomment-165101455

**Comment by Dianafg76** [comment] 2015-12-23 09:53
@rullzer @PVince81 I tested this issue:
1.- Desktop client v2.1.0, Server web v 8.2.2
2.- On the Desktop client I don't have Logs
3.- This is the Server Logs:
   a.- Server A (with SHIB (LDAP, SSO):
```
{"reqId":"ScDHTgfGDeE3iyrLIEtq","remoteAddr":"82.159.139.58","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-23T09:41:18+00:00","method":"PROPFIND","url":"\/oc-shib\/remote.php\/webdav\/"}
{"reqId":"ScDHTgfGDeE3iyrLIEtq","remoteAddr":"82.159.139.58","app":"user_ldap","message":"readAttribute: uid=aaliyah_anderson,ou=people,dc=owncloudqa,dc=com found","level":0,"time":"2015-12-23T09:41:18+00:00","method":"PROPFIND","url":"\/oc-shib\/remote.php\/webdav\/"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"readAttribute: uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com found","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"readAttribute: uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com found","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => uid=aaliyah_adams,ou=people,dc=owncloudqa,dc=com\n)\n attr Array\n(\n    [0] => displayName\n)\n limit 500 offset 0","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"bBDsjGX\/H2psuvZau1nY","remoteAddr":"82.159.139.58","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2015-12-23T09:42:54+00:00","method":"POST","url":"\/index.php\/heartbeat"}
root@279f896ccbca:/opt/owncloud/data# 
```
   b.- Server B:
```
{"reqId":"eDN1f2GHnv5UNLEioEWt","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::ce05d209a036677fe978edc864388511\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:39:13+00:00"}
{"reqId":"JjpUWpbZ+N1JrgEJVv3W","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::e2f60b9be16ba78cc132c10d311ae1c1\": Sabre\\HTTP\\ClientException: Failed to connect to docker.oc.solidgear.es port 54246: Connection refused","level":3,"time":"2015-12-23T09:39:37+00:00"}
{"reqId":"JjpUWpbZ+N1JrgEJVv3W","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::63687a3c14350d4bd4ab7fabc06d630d\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:39:37+00:00"}
{"reqId":"JjpUWpbZ+N1JrgEJVv3W","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::9ac54f7f68069a5ee95443f44157bd0c\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:39:37+00:00"}
{"reqId":"JjpUWpbZ+N1JrgEJVv3W","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::ce05d209a036677fe978edc864388511\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:39:37+00:00"}
{"reqId":"EOltX\/gNxvdWtzzVr0P\/","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::e2f60b9be16ba78cc132c10d311ae1c1\": Sabre\\HTTP\\ClientException: Failed to connect to docker.oc.solidgear.es port 54246: Connection refused","level":3,"time":"2015-12-23T09:40:05+00:00"}
{"reqId":"EOltX\/gNxvdWtzzVr0P\/","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::63687a3c14350d4bd4ab7fabc06d630d\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:40:05+00:00"}
{"reqId":"EOltX\/gNxvdWtzzVr0P\/","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::9ac54f7f68069a5ee95443f44157bd0c\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:40:05+00:00"}
{"reqId":"EOltX\/gNxvdWtzzVr0P\/","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::ce05d209a036677fe978edc864388511\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:40:05+00:00"}
{"reqId":"EOltX\/gNxvdWtzzVr0P\/","remoteAddr":"82.159.139.58","app":"core","message":"Exception while scanning storage \"shared::b4ae56c1630ea2b5d7d0e77e2ac21b53\": Sabre\\HTTP\\ClientException: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2015-12-23T09:40:05+00:00"}
```

**Comment by PVince81** [comment] 2015-12-23 11:12
@Dianafg76 in your case it seems to be a certificate issue.

In @davitol's test case there is a bogus redirect to the IDP when trying to connect to "public.php/webdav".

**Comment by Dianafg76** [comment] 2015-12-23 11:15
@PVince81 The second server is certificated

**Comment by rullzer** [comment] 2015-12-23 14:34
@Dianafg76 the first one also? Because both ways are rquired.

**Comment by PVince81** [comment] 2015-12-24 10:48
I thought that maybe the SSL issue is not when connecting against the remote OC instance. In the other ticket we saw that it gets redirected to the IDP. So maybe the SSL error is due to the IDP's certificate ?

**Comment by PVince81** [comment] 2016-02-12 13:50
Closing as duplicate of https://github.com/owncloud/core/issues/21227

**Closed by PVince81** 2016-02-12 13:50 UTC
Labels: bug, feature:federated-cloud-sharing
