### ISSUE TITLE
Search box in user management only appears when making the font bigger or smaller.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#17945] opened 2015-07-29 08:41 UTC
### Steps to reproduce

1. As admin, go to user management.
2. Create some users.
3. Look for the search box, to search users.
4. Hit ctrl+'+'

### Expected behaviour
We can see the search box all the time.

### Actual behaviour

![screen shot 2015-07-29 at 10 34 14](https://cloud.githubusercontent.com/assets/9048796/8953380/478e21ae-35de-11e5-88e0-b18a1a619842.png)

Search box only appears after step 4.

This happens using both themes enterprise and community.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.1.0","versionstring":"8.1.1 beta1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default ones.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

### Client configuration

**browser**
Chrome 43

**Comment by PVince81** [comment] 2015-07-29 08:57
Confirmed on stable8.1 with Chrome 43 and Firefox 39.

The search box is missing initially and a resize/zoom action is needed.
I suspect that something is listening to resize events to calculate the search box' position, but that event handler isn't called initially.

**Comment by PVince81** [comment] 2015-07-29 09:00
Looks like `adjustControlsWidth` in core is supposed to be triggered not only on resize, but also when the event "apprendered" is triggered. I suspect that the users page doesn't fire that event.

Investigating...

**Comment by PVince81** [comment] 2015-07-29 09:03
@SergioBertolinSG severity is medium, so not sure about having this scheduled for 8.1.1.
CC @cmonteroluque @DeepDiver1975 

Fix is here: https://github.com/owncloud/core/pull/17946

**Comment by cmonteroluque** [comment] 2015-07-29 12:11
@PVince81 this seems like a small change, since we have 5 other issues pending, can't this be fixed in the meantime?

**Closed** 2015-07-29 12:38 UTC
Labels: bug, settings:users, sev3-medium

**Comment by PVince81** [comment] 2015-07-29 12:50
@cmonteroluque yes, the fix was trivial. It was more a matter of principle of whether we want non-critical tickets to be put into 8.1.1. But as we're before RC1 it should be fine.
