### ISSUE TITLE
Can't add a shared link to the cloud the link was shared from

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/core#13850] opened 2015-02-03 10:51 UTC
The ownCloud Android app only lets you share a file through a link. Naturally, you would assume that to share a file with somebody else on your cloud, you send them the link. They can use the 'add this file to your owncloud' button to, well, add it to their cloud. Unfortunately, this gives an error as ownCloud does not detect you are already both on the same installation.

Of course, the Android (and probably iOS) client can be fixed in this regard but it seems something that should work.

### Steps to reproduce
1. Share a link to a user on the same cloud as you
2. User opens link and adds it to the ownCloud instance you both use
3. ownCloud gives an error: can't add shared link

### Expected behaviour
ownCloud detects you're on the same server and just adds the file as if it was shared by user name.

### Actual behaviour
ownCloud gives an error.

### Server configuration
ownCloud 7 EE on S3 ;-)

@schiesbn with oC8 this might be relatively easy to do - Junior Job maybe?

**Comment by MorrisJobke** [comment] 2015-02-03 10:53
@schiesbn Wasn't there an issue about that already?

**Comment by DeepDiver1975** [comment] 2015-02-03 10:55
afaik fixed with #13837 - @LukasReschke please confirm

**Comment by LukasReschke** [comment] 2015-02-03 10:57
#13837 is unrelated to this specific bug.

**Comment by LukasReschke** [comment] 2015-02-03 10:57
(But I also remember seeing an ticket about this somewhere here on GH)

**Comment by PVince81** [comment] 2015-02-03 11:00
Last time I tried this 1-2 weeks ago it worked. It would mount the share as if it was remote.
It caused useless network round trips but at least works (I joked about calling it a "symbolic link" if you share it with yourself)

**Comment by PVince81** [comment] 2015-02-03 11:05
The expected behavior is a duplicate of https://github.com/owncloud/core/issues/9090

In the short term we should make sure that the folder is still mounted properly, even if it's considered as a remote connection to the same server.

**Comment by schiesbn** [comment] 2015-02-03 11:30
> In the short term we should make sure that the folder is still mounted properly, even if it's considered as a remote connection to the same server.

Just tried it, this still works on master

**Comment by DeepDiver1975** [comment] 2015-02-03 12:04
> ownCloud 7 EE on S3 ;-)

it indeed works on master - have to double check stable7 - removing from milestone 8

**Comment by PVince81** [comment] 2015-02-03 12:04
Also works for me on master (f4d20dc1f30d4ab4748166956fcacdaeb0773e75)

**Comment by DeepDiver1975** [comment] 2015-02-03 12:20
even working on stable7 8305ae6b091a63f0818b263fea2fa398311f7897

**Comment by DeepDiver1975** [comment] 2015-02-03 12:24
working on tag v7.0.4 - 77bcc5b2f3713f18a5183ae69bd5c21d0591e901

**Comment by DeepDiver1975** [comment] 2015-02-03 12:38
Aha - as soon as I'm trying to add the public link as generated with s3 to my local test instance I'm getting a more detailed error message.

The remote share doesn't work because the ssl cert validation fails.

**Comment by DeepDiver1975** [comment] 2015-02-03 12:41
We could think about backporting this commit to stable7 in order to enhance the UX: https://github.com/owncloud/core/commit/9509bc403a4f05c96b88e1218e6c7a78f9dd6c20

**Comment by karlitschek** [comment] 2015-02-03 13:11
@schiesbn do you agree with a backport?

**Comment by MorrisJobke** [comment] 2015-02-03 13:33
Whitespace cleaned version: https://github.com/owncloud/core/commit/9509bc403a4f05c96b88e1218e6c7a78f9dd6c20?w=1

**Comment by MorrisJobke** [comment] 2015-02-04 13:09
fix is in #13880

**Closed** 2015-02-04 13:09 UTC
Labels: feature:federated-cloud-sharing, Regression
