### ISSUE TITLE
[master] Encryption wrapper makes all storages it wraps non-local

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#15848] opened 2015-04-23 22:14 UTC
and as soon as it wraps user home by default we end up with non-local storages only, that is definitely makes no sense (and brokes all actions that should be applied to local files only by using `Storage::isLocal` call )

https://github.com/owncloud/core/blob/master/lib/private/files/storage/wrapper/encryption.php#L345 : 

```
	/**
	 * Returns the wrapped storage's value for isLocal()
	 *
	 * @return bool wrapped storage's isLocal() value
	 */
	public function isLocal() {
		return false;
	}
```

**Comment by VicDeo** [comment] 2015-04-23 22:14
@icewind1991 @PVince81 @schiesbn

**Comment by DeepDiver1975** [comment] 2015-04-24 07:30
Looks like we need to perform this check path based. @icewind1991 objections?  Ideas? Thanks

**Comment by dirkahrnke** [comment] 2015-04-24 07:42
sorry, I was distracted somehow. hope its reverted to the intended state

**Comment by icewind1991** [comment] 2015-04-24 12:33
Marking them as non local seems like the right approach for me since you can no longer access the files without going trough oc's filesystem

**Comment by VicDeo** [comment] 2015-04-24 15:44
@icewind1991 ok, I assume that we should index all files for full-text search. Who cares about storage speed. :snail:

**Comment by oparoz** [comment] 2015-04-25 21:32
Duplicate of https://github.com/owncloud/core/issues/15548

And there is also [this issue](https://github.com/owncloud/core/issues/15703), discussing what's wrong with isLocal() and isMounted()

**Comment by VicDeo** [comment] 2015-04-26 19:49
@oparoz not exact. It's about storage, not folder.

I just see no reason to have a method that is only capable to return false.

**Comment by oparoz** [comment] 2015-04-26 22:01
@VicDeo - It's exactly the same thing. A folder is "located" on a specific storage.
The command I'm refering to in the issue I mentioned is:
`$folder->getStorage()->isLocal()`

The log shows that it's wrapped in the encryption wrapper which corrupts isLocal().

I understand that it's not longer "local", but I think the new direction is wrong because it's misleading, thus my other open issue about the subject.

**Comment by DeepDiver1975** [comment] 2015-04-27 07:17
> Marking them as non local seems like the right approach for me since you can no longer access the files without going trough oc's filesystem

@icewind1991 which is true for encrypted files - but what about not encrypted? We have to properly reflect this.

@PVince81 maybe you have some ideas on this - THX

**Comment by PVince81** [comment] 2015-04-27 08:28
The original purpose of `isLocal()` was to tell whether the file can be accessed directly without going through any layers (basically a direct fopen() would work). Such information is needed for example for X-Sendfile which needs access to such local file.

Now with encryption I'd say the file cannot be opened directly so "isLocal()" should return false.
I agree that the name is misleading/confusing.

Not sure why that would corrupt anything ?

**Comment by PVince81** [comment] 2015-04-27 09:08
Ok one thing I just remembered: the encryption wrapper is always there even when encryption isn't enabled. This means that `isLocal()` needs to check whether the encryption module is enabled for the underlying storage. If it's not, then call `return $this->storage->isLocal()`. If encryption is enabled, then `return false'.

**Comment by oparoz** [comment] 2015-04-27 11:42
@PVince81 - I meant corrupt the meaning of isLocal(), since as you've pointed out, it shouldn't be false if encryption is disabled.
And I would still love some method telling devs whether files are local to this oC instance or not, as it makes a huge difference in access time.

**Closed** 2015-04-27 13:06 UTC
Labels: bug
