### ISSUE TITLE
External Storage FTP indexing

### ISSUE THREAD

**Issue by htwsaaraub** [owncloud/core#20092] opened 2015-10-27 16:06 UTC
Hi,

I'm using owncloud 8.2 with Debian 8.
APC Version	4.0.7
PHP Version	5.6.13-0+deb8u1
Server Software	Apache/2.4.10 (Debian)

I mount an external storage FTP Folder in my personal page settings.
I can access the mounted ftp storage. 
I can create a new folder which show up on the Directory on the FTP Server.

If the folder is deleted not in owncloud,  in Filezilla, this folder is still shown in owncloud. 
I can access the deleted folder. Owncloud shows me a emtpy folder, no error message. 
If I want to download or rename the folder owncloud shows a error message, folder not found, which is correct.
If I remove the folder with the delete command in owncloud it disappears. But if I leave the folder and access it again, the deleted Folder appears again. 
The same Issue for Files in Folders on a external mount ftp storage, not only for folders.

Even if I set the mount to always check when accessing the Filesytem the behaviour is the same.
A new Loggout/Login and a apache restart (to clear apc cache) gives no improvement.

Mounting the same directory with SMB the File/Folder appears or disappears correct, even when it was deleted outside owncloud.

**Comment by PVince81** [comment] 2015-10-28 12:08
External storage update detection.

Related: https://github.com/owncloud/core/issues/11797

**Comment by PVince81** [comment] 2015-10-29 09:05
Closing as duplicate of https://github.com/owncloud/core/issues/16407

**Closed by PVince81** 2015-10-29 09:05 UTC
Labels: app:files_external, bug
