### ISSUE TITLE
Download text is "flippering" when hovering around on Share button 

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#18912] opened 2015-09-08 18:04 UTC
`Download` is missing when you hover around this area back and forth: 
![image](https://cloud.githubusercontent.com/assets/4511254/9742968/fdd968b0-5663-11e5-916c-627b9392f57d.png)
Move up / down with the mouse and this happens:
![image](https://cloud.githubusercontent.com/assets/4511254/9742986/21c060c6-5664-11e5-8238-a17e3e701544.png)

Is this intended?

cc @jancborchardt @MorrisJobke 

### Server configuration

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version:** (see ownCloud admin page)
8.1.1
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Chrome 
**Operating system:**
Windows 10
**Sync Client**
2.0.1 stable
**Mobile app*
Android 1.7.2

**Comment by jancborchardt** [comment] 2015-09-08 19:16
Can’t reproduce with stable8.1. Also this will go away anyway with the move to the action menu with 8.2.

**Comment by jancborchardt** [comment] 2015-09-08 19:16
Can anyone of you reproduce @owncloud/designers?

**Comment by MorrisJobke** [comment] 2015-09-09 08:18
I also can't reproduce this in Firefox and Chromium here. And as @jancborchardt said, this will be obsolete with the move to the dropdown in 8.2

@enoch85 I hope it's okay to close this minor glitch - we have a lot of other stuff that is actually more critical and this one will disappear with 8.2 anyway. Thanks for the report anyway :)

**Closed by MorrisJobke** 2015-09-09 08:18 UTC
Labels: bug, design

**Comment by enoch85** [comment] 2015-09-09 10:04
@MorrisJobke Totally fine with me. I also thought this would be fixed in 8.2 but I was not sure.
