### ISSUE TITLE
Public upload "keep file version popup" not resized to screen resolution (answering is not possible)

### ISSUE THREAD

**Issue by dteccode** [owncloud/core#16848] opened 2015-06-09 18:02 UTC
### Steps to reproduce
1. Generate a shared folder (with link, allow public upload)
2. Upload an single image from the iPhone / Android browser
3. Upload another single image (on iPhone every time image.jpeg)
4. Now you can't answer the question which version should be saved, because the popup is not resized to the screen resolution or scrollable

![screenshot_2015-06-09-19-52-59](https://cloud.githubusercontent.com/assets/12817931/8065534/5670a6b0-0ee2-11e5-9be4-3a9cbb98ccc2.png)

![screenshot_2015-06-09-19-53-07](https://cloud.githubusercontent.com/assets/12817931/8065540/610c02fe-0ee2-11e5-9a41-65c7c7dc4988.png)

### Expected behaviour
Popup should be readable at all resolutions and devices

### Actual behaviour
Not possible to answer the question

### Server configuration
**Operating system**:
Debian
**Web server:**
Nginx
**Database:**
MySql
**PHP version:**
5.5.7
**ownCloud version:** (see ownCloud admin page)
8.0.2
**Updated from an older ownCloud or fresh install:**
update
**List of activated apps:**
Galery, Calendar, Contacts
**The content of config/config.php:**
Not representative
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Standard or Chrome
**Operating system:**
IOS 7, Android 4.4.2
#### Web server error log
Not representative
#### ownCloud log (data/owncloud.log)
Not representative

**Comment by oparoz** [comment] 2015-06-09 19:23
Duplicate of https://github.com/owncloud/core/issues/15552

**Closed by oparoz** 2015-06-09 19:23 UTC
