### ISSUE TITLE
Undefined variable on view.php line 1051

### ISSUE THREAD

**Issue by ElGimpoGrande** [owncloud/core#22068] opened 2016-02-02 11:28 UTC
### Steps to reproduce
Share a folder to a User, who doesn't have share permissions, then sync with desktop client

### Expected behaviour
No errors in the log

### Actual behaviour
Everything seems to work fine, but there are a ton of errors logged ( up to 1 / 30sec)

### Server configuration
**Operating system**: Ubuntu Server 12.04.5 LTS

**Web server**: Apache 2.4.16

**Database**: MySQL 5.5.47-0ubuntu0.12.04.1

**PHP version**:  5.5.31

**ownCloud version**: 7.0.12

**Updated from an older ownCloud or fresh install**: Updated from 6

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

throws me back to /apps/files
```

**List of activated apps**:

 - activity
 - files
 - files_sharing
 - search_lucene
 - templateeditor

```

**The content of config/config.php**:

<?php
$CONFIG = array (
  'instanceid' => 'oc2c07f158e1',
  'passwordsalt' => '',
  'datadirectory' => '/owncloud-data',
  'dbtype' => 'mysql',
  'version' => '7.0.12.2',
  'dbname' => 'transfer',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_kw_transferad',
  'dbpassword' => '',
  'installed' => true,
  'default_language' => 'en',
  'forcessl' => true,
  'theme' => 'pxc',
  'maintenance' => false,
  'logtimezone' => 'Europe/Berlin',
  'trusted_domains' => 
  array (
    0 => 'thisdomain.de',
  ),
  'secret' => '',
  'proxy' => '1.2.3.4:8080',
  'loglevel' => 2,
);

```

**Are you using external storage, if yes which one**: No

**Are you using encryption**: no

**Are you using an external user-backend, if yes which one**: no

### Client configuration
**Browser**: OwnCloud Desktop Client Windows 2.1.0

**Operating system**: Windows 7 / 8.1 / 10

**### Logs**

**#### ownCloud log (data/owncloud.log)**
```
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-02T01:26:42+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-02T01:24:19+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-02T01:23:21+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-01T20:19:19+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-01T14:18:53+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-01T14:18:23+01:00
Error	PHP	Undefined variable: content at /var/www/lib/private/files/view.php#1051	2016-02-01T14:17:53+01:00
```

**Comment by RealRancor** [comment] 2016-02-02 12:06
Looks like similar/duplicate of https://github.com/owncloud/core/issues/13306 and https://github.com/owncloud/core/issues/18119 which got only fixed in 8.1+ according to https://github.com/owncloud/core/pull/18124

**Comment by MorrisJobke** [comment] 2016-02-02 17:50
@DeepDiver1975 Why the milestone?

**Comment by aspdye** [comment] 2016-02-03 15:17
Still releasing updates for ownCloud 7 :scream: :smiley:

**Comment by MorrisJobke** [comment] 2016-02-04 11:05
> Still releasing updates for ownCloud 7?

But only security ones ;)

**Comment by DeepDiver1975** [comment] 2016-02-04 11:06
won't fix

**Closed by DeepDiver1975** 2016-02-04 11:06 UTC

**Comment by MorrisJobke** [comment] 2016-02-04 11:16
> won't fix

To be more concrete: Could you try to upgrade to a more recent version and try if the error is gone?

**Comment by aspdye** [comment] 2016-02-04 14:34
For better understanding @MorrisJobke, how long will ownCloud 7 get security patches? 
The error should be gone in more recent versions according to what @RealRancor has said above.

**Comment by RealRancor** [comment] 2016-02-04 14:37
@aspdye See https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by aspdye** [comment] 2016-02-04 14:45
@RealRancor Thats clear :wink: As I see @MTRichards has moved the EoL for ownCloud 7 a bit :smile: 
Is there any official reference - why? I thought ownCloud 7 will be dropped with the new Year 2016.

**Comment by MorrisJobke** [comment] 2016-02-04 15:26
> Is there any official reference - why? I thought ownCloud 7 will be dropped with the new Year 2016.

Yes. There was some internal misunderstanding so we choose to not bring anybody bad news so we took the later date ;)

**Comment by ElGimpoGrande** [comment] 2016-02-12 12:17
Just for the record:

I upgraded to OwnCloud 8.2.2 and the issue went away.
I now have 2 new issues,both of them I can live with for the moment.

cURL is using an outdated OpenSSL Version
Looks like I have to Upgrade the Ubuntu Version for this, but we dont use Federated Cloud Sharing Feature so for now I am going to ignore this.

https://github.com/owncloud/core/issues/17468 
Disabled Updater App (Hasn't worked for me anyways)
