### ISSUE TITLE
Feature request: Add personal text on sharing emails

### ISSUE THREAD

**Issue by novij** [owncloud/core#13549] opened 2015-01-21 13:37 UTC
Is it possible to add a text box on link sharing for a personal comment which is added in the mail to the recipient?

**Comment by DeepDiver1975** [comment] 2015-01-21 13:41
we had this request already in the past - @jancborchardt what was our approach here? THX

**Comment by DeepDiver1975** [comment] 2015-01-21 13:41
most probably duplicate ....

**Comment by jancborchardt** [comment] 2015-02-04 15:56
Duplicate of https://github.com/owncloud/core/issues/9940, let’s continue there.

**Closed by jancborchardt** 2015-02-04 15:56 UTC
