### ISSUE TITLE
after update from 8.0.2 to 8.0.3 An exception occurred while executing

### ISSUE THREAD

**Issue by HaraldKoeln** [owncloud/core#16819] opened 2015-06-09 07:31 UTC
I install the owncloud-8.0.3.tar.bz2 then i got the Error:
An exception occurred while executing 'ALTER TABLE oc_clndr_share_event ENGINE=InnoDB;': SQLSTATE[HY000]: General error: 1598 Binary logging not possible. Message: Transaction level 'READ-COMMITTED' in InnoDB is not safe for binlog mode 'STATEMENT' 

I can´t login anymore.

I use an QNAP Server with Firmware 4.1.3, PHP 5.5.22, MySQL 5.1.36

**Comment by LukasReschke** [comment] 2015-06-09 08:20
Duplicate of https://github.com/owncloud/core/issues/16008 which also contains work-arounds

**Closed by LukasReschke** 2015-06-09 08:20 UTC
