### ISSUE TITLE
[Share] It´s not possible to distinguish with whom you have shared something

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#20291] opened 2015-11-04 10:26 UTC
STEPS:
1.- Create 2 users, user1 and user2
2.- login as user1 and change its full name to user
3.- login as user2 and change its full name to user
4.- login as admin and select to share a file with user

CURRENT BEHAVIOR:
You don't know with whom user you are sharing something

![screen shot 2015-11-04 at 11 23 01](https://cloud.githubusercontent.com/assets/1846927/10935515/eb528dd4-82e6-11e5-9e55-c28ff628be7d.png)

EXPECTED BEHAVIOR:
Be able to distinguish the user with whom you have share.... ui input needed!

**Comment by rperezb** [comment] 2015-11-04 10:27
@jancborchardt @owncloud/designers

**Comment by rperezb** [comment] 2015-11-04 10:30
@MTRichards this is important for clients development.

We plan to show on the mobile apps and client the same user id as the one on the webinterface

fyi @rullzer @davivel @masensio @ggdiez @javiergonzper @nasli

**Comment by jancborchardt** [comment] 2015-11-04 13:11
The username shows on hover. In addition, to clear up this edge-case, we could show the username of people where the display name is duplicate in parentheses after the display name like so:
* **user** (user1)
* **user** (user2)

But _only_ when there is a case of duplicate display names as this should be very rare.
However maybe it would be more intelligent to enforce unique display names and put out a warning if there are dupicates? cc @DeepDiver1975?

**Comment by MTRichards** [comment] 2015-11-04 14:09
Concur with Jan's answer if we can.

**Comment by MTRichards** [comment] 2015-11-04 14:10
Does the API also need to respond with both the username and display name so mobile and desktop can take advantage of it?

**Comment by rullzer** [comment] 2015-11-04 14:55
> Does the API also need to respond with both the username and display name so mobile and desktop can take advantage of it?

Already does :wink:

**Comment by MTRichards** [comment] 2015-11-04 15:00
Excellent, so this becomes a mobile and desktop item.
@dragotin @rperezb 
So that we can handle internal sharing with users that have the same display name.

**Comment by rperezb** [comment] 2015-11-04 16:04
got it! thanks

**Comment by MorrisJobke** [comment] 2015-11-09 14:44
cc @michaelstingl 

00004123

**Comment by MorrisJobke** [comment] 2015-11-09 14:49
API: https://github.com/owncloud/core/pull/18234
API doc: https://github.com/owncloud/documentation/issues/1626

**Comment by MorrisJobke** [comment] 2015-11-09 15:00
> well then we need to think about something generic. Since we can't assume the e-mail is set.

Correct. Therefore I would like to add either the full user object (and the handle this in the frontend) or and alternative more verbose label for the case there are multiple same labels.

**Comment by jancborchardt** [comment] 2015-11-11 16:55
Btw, this is actually a duplicate of https://github.com/owncloud/core/issues/8194 from last year where I suggested exactly the same thing. ;)

**Comment by rullzer** [comment] 2015-11-11 17:03
@jancborchardt so just to be perfectly clear.

Assume we have 3 users:
* id: user1, email: user1@foo.com, displayName: Bar
* id: user2, email: user2@foo.com, displayName: Bar
* id: user3, email: , displayName: Bar

And I share with all those users it whould show up as

* Bar (user1@foo.com)
* Bar (user2@foo.com)
* Bar (user3)

**Comment by jancborchardt** [comment] 2015-11-11 17:12
Yep. Then of course we should also eventually have some system for mail address verification and ensuring it’s unique – see https://github.com/owncloud/core/issues/7326

**Comment by jancborchardt** [comment] 2015-11-11 17:14
@rullzer wait – actually I think it should always be the user id, not the email address. As that can be confused with the remote sharing ID.

**Comment by rullzer** [comment] 2015-11-11 17:18
> Yep. Then of course we should also eventually have some system for mail address verification and ensuring it’s unique – see #7326

Sure, but that is a separate issue

> @rullzer wait – actually I think it should always be the user id, not the email address. As that can be confused with the remote sharing ID.

This will break in case of LDAP since that is an internal ID. That can be pretty random.

**Comment by MTRichards** [comment] 2015-11-11 18:22
@rullzer I like the solution. Good results guys.

**Comment by MTRichards** [comment] 2015-11-11 18:30
>This will break in case of LDAP since that is an internal ID. That can be pretty random.

there is definitely an internal unique user ID, but the username and display ID are usually not so crazy...if I recall.

@blizzz

**Comment by bboule** [comment] 2016-01-07 16:35
Guys this seems like a feature request a, I wrong?

**Comment by MorrisJobke** [comment] 2016-01-07 16:44
> Guys this seems like a feature request a, I wrong?

Correct (see the enhancement label in the sidebar ;))

**Comment by MTRichards** [comment] 2016-01-07 20:33
If I sum this up, the same displayname shows up as the same person, and you can't tell them apart.

Therefore, we do as @rullzer suggested with displayname, email if available, username in that order. If the UID is the username, that sucks but what else can we use?

For federated sharing, can we used the name of the remote server before username?

**Comment by nickvergessen** [comment] 2016-02-02 09:35
> If the UID is the username, that sucks but what else can we use?

Well we at least know, that it is the same user. and then there should be only one user with this UID === username combination

**Comment by cdamken** [comment] 2016-02-23 10:37
I just took over the case 00004123 in SFDC, and its referred to this issue.

> Guys this seems like a feature request a, I wrong?

I'm reading the customers request and he asked it since oC6,  

Other customers have a similar solution with second display name like: https://github.com/owncloud/enterprise/issues/690 and https://github.com/owncloud/enterprise/issues/1088

In this case is Shibboleth an additional factor, I'm not sure if that is a difference

**Closed** 2016-02-25 15:55 UTC
Labels: blue-ticket, enhancement, enhancement - approved, feature:sharing, in progress, sev2-high

**Comment by MorrisJobke** [comment] 2016-02-25 16:15
Okay. 9.0 will contain a workaround. I think we nevertheless should handle this properly in the client side. I will open a ticket on this.

**Comment by MorrisJobke** [comment] 2016-02-25 16:19
https://github.com/owncloud/core/issues/22652
