### ISSUE TITLE
Make the address bar dissappear on Google Chrome Android to save space on the screen

### ISSUE THREAD

**Issue by elpraga** [owncloud/core#21179] opened 2015-12-14 07:59 UTC
Some of the owncloud apps are very usable even on mobile phones in the web interface of ownCloud (like Tasks), but the address bar of Google Chrome never disappears (opposed to dissappearing on other pages when scrolling down).

On mobile phones it does make a big difference as it takes up much valuable space on the screen. 

Is there a way to make it hide?

**Comment by elpraga** [comment] 2015-12-14 08:18
I found someone trying to address an oposite issue, but it might help. Please note, I cannot write code, so unfortunatelly, I cannot provide a solution..

http://stackoverflow.com/questions/25298443/force-address-bar-to-show-in-mobile-chrome-app
```
Edit v2: One method that could potentially work is to use the 'Fullscreen API' and detect every time the user scrolls (using a jQuery method) - then tell the browser to exit fullscreen mode each time to keep the address bar. Bear in mind this is untested so tell me whether you have any luck with this method...

$(window).scroll(function(){
    document.webkitExitFullscreen();
    document.exitFullscreen();
});
```

**Comment by PVince81** [comment] 2015-12-14 10:51
@owncloud/designers

**Comment by jancborchardt** [comment] 2015-12-14 16:44
@elpraga since you have a code sample ready, maybe directly prepare a pull request? :)

Also relevant for this is hiding the header automatically on scrolling down, and showing it again on scrolling up: https://github.com/owncloud/core/issues/7826

**Comment by elpraga** [comment] 2015-12-29 08:53
I am sorry to reply so late, @jancborchardt  I would love to be able to prepare a pull request, but I cannot code :( The found that code when I was searching the internet about the issue, and I pasted it just in case it could give some hint, it actually does the oposite then what we would need. 

I tried to find if someone was trying to solve the same issue for other webpage, but I did not find anything, unfortunatelly, my skills are not high enough to be able to prepare the fix myself. :cry: I apologize..

**Comment by jancborchardt** [comment] 2015-12-29 09:26
Yeah, no worries. :) Thinking about it too, ivoking fullscreen every time is quite invasive. I would close this as duplicate of #7826

**Closed by jancborchardt** 2015-12-29 09:26 UTC
Labels: design, enhancement, enhancement - proposed

**Comment by elpraga** [comment] 2015-12-29 09:27
Well, well, well... I gave it another though and some more searching... and I found out that there is an option.. by adding 
```
<meta name="mobile-web-app-capable" content="yes">
```
user can use the menu item in google chrome for Android to add a shortcut to the home screen and the app then appears without the address bar. Then I checked the code of OC and to my surprise it is already there, and it works as expected.

I was about the close the issue, but I just realized that You did it..

**Comment by jancborchardt** [comment] 2015-12-29 17:38
;) yep, that capability has been added a long time ago. No worries.
