### ISSUE TITLE
updating problem to 8.0.2 

### ISSUE THREAD

**Issue by Gabriel2000** [owncloud/core#15416] opened 2015-04-06 10:13 UTC
When I update to 8.0.2 I get the following error:

An exception occurred while executing 'CREATE TABLE `oc_share_external` (`id` INT AUTO_INCREMENT NOT NULL, `remote` VARCHAR(512) NOT NULL COMMENT 'Url of the remove owncloud instance', `remote_id` INT DEFAULT -1 NOT NULL, `share_token` VARCHAR(64) NOT NULL COMMENT 'Public share token', `password` VARCHAR(64) DEFAULT NULL COMMENT 'Optional password for the public share', `name` VARCHAR(64) NOT NULL COMMENT 'Original name on the remote server', `owner` VARCHAR(64) NOT NULL COMMENT 'User that owns the public share on the remote server', `user` VARCHAR(64) NOT NULL COMMENT 'Local user which added the external share', `mountpoint` VARCHAR(4000) NOT NULL COMMENT 'Full path where the share is mounted', `mountpoint_hash` VARCHAR(32) NOT NULL COMMENT 'md5 hash of the mountpoint', `accepted` INT DEFAULT 0 NOT NULL, INDEX sh_external_user (`user`), UNIQUE INDEX sh_external_mp (`user`, `mountpoint_hash`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`owncloud`.`oc_share_external`' already exists

**Comment by DeepDiver1975** [comment] 2015-04-06 10:16
Db? Version?

**Comment by RealRancor** [comment] 2015-04-06 10:29
Also please use the issue template provided here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

This includes mandatory questions about your environment like also asked above.

**Comment by Gabriel2000** [comment] 2015-04-06 12:23
Sorry,

Operating system: Windows 2008R2
Web server: IIS
Database: MySQL 5.5.21
PHP version: 5.4

ownCloud version: 7.0.2
And I tried to update to 8.0.2

**Comment by RealRancor** [comment] 2015-04-06 12:41
Hi,

try first to upgrade to OC 7.0.5 (latest point release) like described here:

https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#upgrading-your-owncloud-server

**Comment by Gabriel2000** [comment] 2015-04-06 13:06
With the update to 7.0.5 I have no problems. But then from 7.0.5 to 8.0.2 I get the following error messages

An exception occurred while executing 'CREATE TABLE `oc_share_external` (`id` INT AUTO_INCREMENT NOT NULL, `remote` VARCHAR(512) NOT NULL COMMENT 'Url of the remove owncloud instance', `remote_id` INT DEFAULT -1 NOT NULL, `share_token` VARCHAR(64) NOT NULL COMMENT 'Public share token', `password` VARCHAR(64) DEFAULT NULL COMMENT 'Optional password for the public share', `name` VARCHAR(64) NOT NULL COMMENT 'Original name on the remote server', `owner` VARCHAR(64) NOT NULL COMMENT 'User that owns the public share on the remote server', `user` VARCHAR(64) NOT NULL COMMENT 'Local user which added the external share', `mountpoint` VARCHAR(4000) NOT NULL COMMENT 'Full path where the share is mounted', `mountpoint_hash` VARCHAR(32) NOT NULL COMMENT 'md5 hash of the mountpoint', `accepted` INT DEFAULT 0 NOT NULL, INDEX sh_external_user (`user`), UNIQUE INDEX sh_external_mp (`user`, `mountpoint_hash`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table '`owncloud`.`oc_share_external`' already exists

**Comment by Gabriel2000** [comment] 2015-04-06 13:32
And updating from 7.0.5 to 8.0.0 give the same error.

**Comment by nickvergessen** [comment] 2015-04-07 09:51
Duplicate of #14916

**Closed by nickvergessen** 2015-04-07 09:51 UTC
Labels: needs info
