### ISSUE TITLE
ALTER TABLE oc_appconfig error on update to 8.0

### ISSUE THREAD

**Issue by hebbet** [owncloud/core#14089] opened 2015-02-11 07:58 UTC
### Steps to reproduce
1. Extract tar.gz
2. open owncloud in browser
3. hit "update button"

### Expected behaviour
Tell us what should happen

Update should be successful

### Actual behaviour
Tell us what happens instead
Update not successful
### Server configuration
**Operating system**: Ubuntu 14.04.1 LTS

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** 5.5.21-1+deb.sury.org~trusty+2

**ownCloud version:** (see ownCloud admin page) 7.0.4

**Updated from an older ownCloud or fresh install:** older install

**List of activated apps:** Documents, Encryption, Gallery i think

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oca773127154',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/DOMAIN/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'loglevel' => '4',
  'trusted_domains' =>
  array (
    0 => 'owncloud.DOMAIN.tdl',
  ),
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'mail',
  'mail_domain' => 'DOMAIN.tdl',
  'secret' => '',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no yes

### Client configuration
**Browser:** Chrome 40

**Operating system:** Windows 7

#### Web server error log
```
nothing logged by that issue
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"07a233e7fe31c883319c0f2a6c36fb60","remoteAddr":"141.24.47.200","app":"core","message":"Simulated database structure update failed (exception 'OC\\DB\\MigrationException' with message 'An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_yokptl2qzkeys RENAME INDEX appconfig_config_key_index TO oc_rg2bffp6f3ypi':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX appconfig_config_key_index TO oc_rg2bffp6f3ypi' at line 1' in \/var\/www\/DOMAIN\/owncloud\/lib\/private\/db\/migrator.php:133\nStack trace:\n#0 \/var\/www\/DOMAIN\/owncloud\/lib\/private\/db\/migrator.php(91): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/DOMAIN\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(113): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/DOMAIN\/owncloud\/lib\/private\/db.php(252): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/DOMAIN...')\n#3 \/var\/www\/hDOMAIN\/owncloud\/lib\/private\/updater.php(241): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/DOMAIN...')\n#4 \/var\/www\/DOMAIN\/owncloud\/lib\/private\/updater.php(210): OC\\Updater->checkCoreUpgrade()\n#5 \/var\/www\/DOMAIN\/owncloud\/lib\/private\/updater.php(149): OC\\Updater->doUpgrade('8.0.0.7', '7.0.4.2')\n#6 \/var\/www\/DOMAIN\/owncloud\/core\/ajax\/update.php(49): OC\\Updater->upgrade()\n#7 {main})","level":4,"time":"2015-02-11T07:56:35+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment] 2015-02-11 08:44
Hi,

this is a duplicate of https://github.com/owncloud/core/issues/14003 and some more.

**Closed** 2015-02-11 08:48 UTC
