### ISSUE TITLE
error Update ownCloud to version 8.2.1

### ISSUE THREAD

**Issue by DanielAlexandre** [owncloud/core#25630] opened 2016-07-27 11:51 UTC
Try make update owncloud 6.5 to 8.2.1 for webpage but fail. someone have the same problem?

thanks

Set log level to debug - current level: "Info"
Ativado o modo de manutenção
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful

**Comment by RealRancor** [comment] 2016-07-27 12:20
@DanielAlexandre You can close this issue instantly as this is not a bug in ownCloud. Please do a correct upgrade by reading the following upgrade instructions:

https://doc.owncloud.org/server/9.1/admin_manual/maintenance/manual_upgrade.html

Further infos are also available here: https://central.owncloud.org/t/updates-between-multiple-major-versions-are-unsupported/815

**Closed** 2016-07-27 13:55 UTC

**Comment by RealRancor** [comment] 2016-07-27 14:21
@DanielAlexandre Sorry, forgot to mention: If you need further help with the upgrading of your instance feel free to ask for more info at https://central.owncloud.org/ (you can even login with your github account there).
