### ISSUE TITLE
Failing test on PGSQL

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#21057] opened 2015-12-09 06:35 UTC
Introduced with #21030

```
Test\DB\QueryBuilder\QueryBuilderTest::testGetLastInsertId
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT lastval()':

SQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session

/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:91
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:116
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:836
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/connection.php:182
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:541
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/adapterpgsql.php:28
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/connection.php:221
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/lib/private/db/querybuilder/querybuilder.php:1057
/ssd/jenkins/workspace/core-ci-linux/database/pgsql/label/SLAVE/tests/lib/db/querybuilder/querybuildertest.php:1135
```

**Comment by nickvergessen** [comment] 2015-12-09 08:49
Closing as duplicate of #21052 because it's the same issue

**Closed** 2015-12-09 08:49 UTC
Labels: bug, db:postgresql, regression, sev1-critical
