### ISSUE TITLE
User management settings are not saved

### ISSUE THREAD

**Issue by floeschie** [owncloud/core#16448] opened 2015-05-19 13:48 UTC
If I change the settings in the user management area, they are gone again after leaving the page. Only default user quota value is saved.

# Steps to reproduce
1. Go to user management (https://your.owncloud.site/index.php/settings/users)
1. Click the settings icon (gear) on the bottom left
1. Change the quota from unlimited to 5 GB
1. Check all checkboxes
1. Logout and login again
1. Go back to user management again
1. Click on settings icon (gear) again

# What I expected
- Checkboxes are still checked
- All settings have been saved, so that I don't have to re-check them again

# What happens instead
- Checkboxes are not checked anymore
- Only default quota has been saved
- Google Chrome JavaScript Console output: GET https://your.owncloud.site/core/vendor/jquery/dist/jquery-migrate.min.map 404 (Not Found)

# Additional Info
- Client: Google Chrome Version 42.0.2311.152 (64-bit) on Kubuntu 14.04
- Server:
  - ownCloud 8.0.3 (stable) installed via http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.04/
  - Ubuntu 14.04.2 LTS
  - Apache 2.4.7-1ubuntu4.4
  - PHP 5.5.9-1ubuntu4.9

**Comment by DeepDiver1975** [comment] 2015-05-19 13:50
afaik a duplicate - we are aware of this - @MorrisJobke do you remember the issue? THX

**Comment by oparoz** [comment] 2015-05-19 16:04
Hmmm... Shouldn't this be a showstopper? Users not being able to save their settings sound like a pretty big deal to me.

**Comment by PVince81** [comment] 2015-05-19 16:37
Works for me on master. Let me try 8.0.3.

**Comment by PVince81** [comment] 2015-05-19 16:40
Okay, small nuance:

On 8.0.3:
- saving the default quota works (there is a "setquota.php" ajax call directly after changing)
- saving the checkboxes state doesn't trigger any ajax call

So basically this is about the checkboxes, not the default quota.

**Comment by PVince81** [comment] 2015-05-19 16:43
I checked the user management page enhancement summary  and didn't see such item: https://github.com/owncloud/core/issues/12998

So either saving checkboxes stopped working for some reason and it's a bug, or saving them was never implemented in the first place ?

@MorrisJobke @LukasReschke

**Comment by LukasReschke** [comment] 2015-05-19 16:55
Saving them was never implemented. Duplicate of https://github.com/owncloud/core/issues/12727.

**Closed by LukasReschke** 2015-05-19 16:55 UTC
Labels: bug
