### ISSUE TITLE
After clicking new + text file, the text editor should open

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19230] opened 2015-09-21 15:49 UTC
### Description

As a user, I click on the "+" button to create a file I will use immediately.
Opening the text editor right after I've created a text file would save me one click and impress my friends about the usability of ownCloud.

### Acceptance criteria

* User clicks +, file is created, files is opened in text editor (if installed)
* The editor should only automatically open for media types supported by the text editor

@jancborchardt

**Comment by jancborchardt** [comment] 2015-09-22 08:08
Technically a duplicate of https://github.com/owncloud/core/issues/7031, but this is more specific so let’s continue here instead. :) I totally agree @oparoz!

And for folders:
> For »New folder«, insert the folder directly in the file list and have it in rename mode.

**Comment by jancborchardt** [comment] 2015-09-22 08:09
Also cc @tomneedham for the text editor.

**Comment by oparoz** [comment] 2015-09-22 12:06
> For »New folder«, insert the folder directly in the file list and have it in rename mode.

Defo!

**Comment by PVince81** [comment] 2016-01-22 08:38
This is done in 9.0, closing

**Closed by PVince81** 2016-01-22 08:38 UTC
Labels: 1 - To develop, app:files, design, enhancement, junior job, sev3-medium

**Comment by jancborchardt** [comment] 2016-01-22 10:53
Opened https://github.com/owncloud/core/issues/21848 for the »New folder« part.

**Comment by oparoz** [comment] 2016-01-22 11:32
:+1:
