### ISSUE TITLE
Introduce new X-OC-ETag header to fix some sync issues.

### ISSUE THREAD

**Issue by guruz** [owncloud/core#9005] opened 2014-06-12 10:57 UTC
The syncing client uses the ETag header for its syncing algorithm.

There is however a difference in semantics of what the sync client needs and what the HTTP RFC (and servers) implement.

The syncing client uses the ETag to uniquely identify (changed) file contents.
The HTTP servers do the same, however compressing responses (```Content-Encoding```) also changes or removes the ETag.
(The sync client doesn't want that!)

This can be seen for example here:
https://httpd.apache.org/docs/trunk/mod/mod_deflate.html#deflatealteretag
http://lxr.nginx.org/source/src/http/modules/ngx_http_gzip_filter_module.c#0309
pagespeed modules (lost the link)

So a plain webserver works fine with the sync client, but as soon as users configure gzip on their servers, it might break.

A solution would be for the server to additionally(!) send a ```X-OC-ETag``` header with the "real" oC file ETag.

I will try to do a pull request. Probably code change in ```lib/private/connector/sabre/file.php``` in ```get()``` if no one has a better idea

(This should be done for oC6 and oC7)

CC @ogoffart @PVince81 @dragotin 

Source issues:
https://github.com/owncloud/mirall/issues/1291
https://github.com/owncloud/documentation/issues/344
https://github.com/owncloud/mirall/issues/1097
https://github.com/owncloud/mirall/issues/1306

**Comment by PVince81** [comment] 2015-02-06 11:08
Reopening this, setting to 8.0.1

**Comment by PVince81** [comment] 2015-02-06 11:08
(the original fix was reverted here: #13932)

**Comment by nsymms** [comment] 2015-03-21 15:35
The ETag issue has been opened / closed / fixed / reverted so many times I've lost track.

I'm still having the same problem with server v8.0.2 using nginx. The v1.7.1 windows client continues to receive a tiny text file over and over again because "No E-Tag received from server."

What's going to happen with this? Since this particular issue (9005) is still open, is the issue still active? Or did someone just forget to close this issue?

I can post logs and other info if needed.

**Comment by RealRancor** [comment] 2015-03-21 15:40
@nsymms 
Try to disable gzip in your NginX config: https://github.com/owncloud/documentation/pull/922

AFAIK this "X-OC-ETag" will be added in OC 8.1 so thats probably the reason why this issue here is still open.

**Comment by nsymms** [comment] 2015-03-21 15:56
Thanks. gzip disabled, error disappeared. I was concerned because I saw PVince set it to target 8.0.1. Now I see that it is an 8.1 fix.

On a side note, I am using OC inside a docker container, so I had to disable gzip on both the container's nginx and the outside nginx proxy (just for the OC server).

**Comment by RealRancor** [comment] 2015-03-22 11:33
@nsymms 
Great, thanks for the feedback. Hope my documentation change linked above will be merged soon.

Really wonder why no one had found the initial problem which i had already reported nearly a year ago in https://github.com/owncloud/documentation/issues/344

**Comment by PVince81** [comment] 2015-03-26 14:08
I merged it too quickly... sorry. Revert PR here https://github.com/owncloud/core/pull/15218

The problem is described here: https://github.com/owncloud/core/pull/15168#issuecomment-86509482

**Comment by PVince81** [comment] 2015-03-26 15:08
Fix here: https://github.com/owncloud/core/pull/15227
This one is much simpler and copies the Etag header in Sabre's "afterMethod"

**Comment by PVince81** [comment] 2015-03-27 12:11
Fixed through https://github.com/owncloud/core/issues/15227

**Closed by PVince81** 2015-03-27 12:11 UTC
Labels: bug, sev2-high
