### ISSUE TITLE
OC8.0 Picture-App: Overview doesn't work. 

### ISSUE THREAD

**Issue by Huster-at-github** [owncloud/core#14630] opened 2015-03-02 08:05 UTC
Ubuntu 14.04
Apache 2.4
MySQL
PHP 5.5.9-1ubuntu4

Picture-App doesnt display the overview.
Viewing pictures from Files-App works.

I get in a interval of a few seconds up to some minutes errors like this:

```
{
    "reqId": "3dcd768a715bc70e661aa7ba9d79dd56",
    "remoteAddr": "81.232.214.130",
    "app": "webdav",
    "message": {
        "Exception": {
            "Message": "No basic authentication headers were found",
            "Code": 0,
            "Trace": {
                "#0": [
                    "/var/www/owncloud/lib/private/connector/sabre/auth.php(123):",
                    "Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')"
                ],
                "#1": [
                    "/var/www/owncloud/lib/private/connector/sabre/auth.php(103):",
                    "OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')"
                ],
                "#2": [
                    "/var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Auth/Plugin.php(108):",
                    "OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')"
                ],
                "#3": [
                    "[internal",
                    "function]: Sabre\DAV\Auth\Plugin->beforeMethod('PROPFIND', 'clientsync')"
                ],
                "#4": [
                    "/var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(433):",
                    "call_user_func_array(Array, Array)"
                ],
                "#5": [
                    "/var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(455):",
                    "Sabre\DAV\Server->broadcastEvent('beforeMethod', Array)"
                ],
                "#6": [
                    "/var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214):",
                    "Sabre\DAV\Server->invokeMethod('PROPFIND', 'clientsync')"
                ],
                "#7": [
                    "/var/www/owncloud/apps/files/appinfo/remote.php(61):",
                    "Sabre\DAV\Server->exec()"
                ],
                "#8": [
                    "/var/www/owncloud/remote.php(54):",
                    "require_once('/var/www/ownclo...')"
                ],
                "#9": [
                    "{main}",
                    null
                ]
            },
            "File": "/var/www/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Auth/Backend/AbstractBasic.php",
            "Line": 73
        }
    },
    "level": 0,
    "time": "2015-03-02T07:56:42+00:00",
    "method": "PROPFIND",
    "url": "/owncloud/remote.php/webdav/clientsync"
}
```

**Comment by DeepDiver1975** [comment] 2015-03-02 08:31
the error log messages seem unrelated to the issue with the gallery

**Comment by DeepDiver1975** [comment] 2015-03-02 08:31
@Huster-at-github Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by Huster-at-github** [comment] 2015-03-02 09:05
Before this issue, Gallery stopped displaying folders at a number of 393:
https://forum.owncloud.org/viewtopic.php?f=31&t=26774&start=10

### Steps to reproduce
1. Start "Pictures" in the web interface


### Expected behaviour
All folders with pictures in it should be shown.

### Actual behaviour
"Waiting" sign

### Server configuration
Ubuntu 14.04
Apache 2.4
mySQL
PHP 5.5.9-1ubuntu4
ownCloud 8.0
Updated from 7.0.4

**List of activated apps:**
All recommended

**The content of config/config.php:**
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => 'oc45a7343c0a',
  'passwordsalt' => '5f85025b8a21004985319886c4d26d',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'domain1',
    2 => 'domain2',
    3 => 'domain3',
    4 => 'domain4',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Admin',
  'dbpassword' => '47f299786jrd6d29c44a68fd3fcd14',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.gmx.net',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpname' => 'oc_sender@gmx.de',
  'mail_smtppassword' => 'pokiiujhhzzt',
  'mail_smtpport' => '587',
  'mail_domain' => 'gmx.de',
  'mail_from' => 'oc_sender@gmx.de',
  'mail_fromname' => 'oc_sender@gmx.de',
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'oc_sender',
  'secret' => '6a7977223514a3dbc23dcddb49a4562e1d815a0bf8cf3748e460d3327f90090565ee3d68d5c08171a85fde8e62b18b92',
);


**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Firefox 35.0
Ubuntu 14.04

### Logs
#### Web server error log
No errors when pressing Pictures

#### ownCloud log (data/owncloud.log)
See above

#### Browser log

**Comment by LukasReschke** [comment] 2015-03-02 09:42
@Huster-at-github You did post clear-text passwords in your above configuration. I removed all sensitive entries. Please change your passwords.

**Comment by Huster-at-github** [comment] 2015-03-02 10:17
@LukasReschke Thanks, but I changed all senitive data in my posting.  :-)

**Comment by Huster-at-github** [comment] 2015-03-02 17:47
@DeepDiver1975 Think, you're right: This bug seems not be related to the error log "No basic authentication headers were found"

Seems, it comes from CarDAV, CalDAV or WebDAV clients.

Also reported here: https://github.com/owncloud/core/issues/14510

**Comment by oparoz** [comment] 2015-03-04 15:20
Without a proper error log, it's difficult to tell what's happening, but I'd call this a duplicate of https://github.com/owncloud/gallery/issues/158 and https://github.com/interfasys/galleryplus/issues/17

**Comment by DeepDiver1975** [comment] 2015-03-06 09:42
closing because being a duplicate - THX

**Closed by DeepDiver1975** 2015-03-06 09:42 UTC
