### ISSUE TITLE
[8.2] Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes()

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/core#20090] opened 2015-10-27 15:19 UTC
Is this a known issue?

**Comment by Xenopathic** [comment] 2015-10-27 15:26
Line number? Error logs? Upgrade/fresh install? We really need some more information that that...

**Comment by pierrejochem** [comment] 2015-10-27 15:29
Upgrade from Version 8.1.3 to 8.2 (New Ubuntu Repo for Version 8.2)



```
{"reqId":"8PhGcCFACsHHrJ3ACV7a","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:18:02+00:00"}
{"reqId":"6pDs3wd9bH9gG7gT\/IDj","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:18:34+00:00"}
{"reqId":"flMvFoIyEz1TkoCZB5lj","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:19:06+00:00"}
{"reqId":"qgkzW3ms8zDtEWAqJnq3","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:19:38+00:00"}
{"reqId":"lCDTh+36sQdvUnIeuLRO","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:20:10+00:00"}
{"reqId":"CbX3KMMEI60wK+HQbuv3","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:20:42+00:00"}
{"reqId":"e8w1LS1HkLEIDfCm3pQK","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:21:14+00:00"}
{"reqId":"AHmncwrIcyVgDtR+I9Z0","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:21:46+00:00"}
{"reqId":"4gqRVG1ijJMgwe8PuvyG","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:22:18+00:00"}
{"reqId":"8sNsYNTyLbxbpFRbtecC","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:22:50+00:00"}
{"reqId":"DWMwEwo8bsFU+JcWCbZ2","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:23:09+00:00"}
{"reqId":"mP3Aib+M5qBMIsokpevy","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:23:15+00:00"}
{"reqId":"1\/gS66+0D\/9Fvo06SGPw","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:23:22+00:00"}
{"reqId":"B7YAhG63LO0VRW3jOZk9","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:37+00:00"}
{"reqId":"XWD+WAqQIBca42fBtCrO","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:46+00:00"}
{"reqId":"g64SZoGTmbmLXNDIb7S0","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:50+00:00"}
{"reqId":"cY5u7QO4lSbnj+sZeATF","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:53+00:00"}
{"reqId":"cY5u7QO4lSbnj+sZeATF","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:53+00:00"}
{"reqId":"lpiGgivln5ws++PSP08x","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:23:54+00:00"}
{"reqId":"LH1AKgeeOLd1Fv4pKTiI","remoteAddr":"X.X.X.X","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-10-27T15:23:59+00:00"}
{"reqId":"gUZ8MaeH4gq\/p7wFCZWK","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:24:26+00:00"}
{"reqId":"Gbat6w8\/jEjALgl2cXxi","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:24:58+00:00"}
{"reqId":"s8DeC7kNLXQ6a7kdKsja","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:25:30+00:00"}
{"reqId":"QmosqTIp2BSrAqNaHnH4","remoteAddr":"","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:25:35+00:00"}
{"reqId":"je+rzPgtxut73eW9dYVm","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:26:02+00:00"}
{"reqId":"LLHynWO3Xg+KyIGbONdN","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:26:34+00:00"}
{"reqId":"SUGNA\/foQuD57Dj7WzF\/","remoteAddr":"X.X.X.X","app":"PHP","message":"Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() at \/var\/www\/owncloud\/apps\/user_ldap\/lib\/access.php#698","level":3,"time":"2015-10-27T15:27:06+00:00"}
```

**Comment by Xenopathic** [comment] 2015-10-27 16:43
@blizzz

**Comment by Venice-89** [comment] 2015-10-29 14:06
Hi,

I have the same Error after Upgrading my Owncloud to 8.2 from the new Ubuntu Repository. 

[Thu Oct 29 15:00:18.952980 2015] [:error] [pid 22814] [client xxxxxx:54601] PHP Fatal error:  Call to undefined method OCA\\user_ldap\\lib\\user\\OfflineUser::processAttributes() in /var/www/owncloud/apps/user_ldap/lib/access.php on line 698

**Comment by blizzz** [comment] 2015-10-29 19:56
Any reproduction steps? Please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md), thx!

**Comment by blizzz** [comment] 2015-10-29 20:08
Never mind, at least I saw the cause of it. An OfflineUser instance is returned instead which should happen only for users marked as deleted. So the user for whom the error appeared (not the logged in one but the one processed in the function) was once found as not existing on LDAP and marked as deleted. Now the user reappeared somehow. I guess that's time for unflagging them… Need to think of a proper fix.

As a temporary workaround those affected can add a dummy function to the OfflineUser class that does nothing, to get ownCloud working again:

```diff
diff --git a/apps/user_ldap/lib/user/offlineuser.php b/apps/user_ldap/lib/user/offlineuser.php
index 72c0242..4ff32d9 100644
--- a/apps/user_ldap/lib/user/offlineuser.php
+++ b/apps/user_ldap/lib/user/offlineuser.php
@@ -220,4 +220,6 @@ class OfflineUser {
 
        $this->hasActiveShares = false;
    }
+
+   public function processAttributes($ldapEntry) { }
 }
```

**Comment by Venice-89** [comment] 2015-10-29 20:35
thx, that's working for me !

**Comment by pierrejochem** [comment] 2015-10-30 07:38
I have done a downgrade in the meantime. Some users could not login after the upgrade and that is bad for over 2000...

@blizzz Thanks for the workaround. Will do another upgrade on another server before I do it again at the production system.

**Comment by blizzz** [comment] 2015-10-30 15:30
@Venice-89 @pierrejochem do either of you have a clue why such users were marked as deleted on LDAP? For instance, were they (temporarily?) really removed from LDAP? Or were you experimenting with the occ ldap:check-user command?

**Comment by Venice-89** [comment] 2015-10-30 16:15
@blizzz hmmm, no I don't know, may be because of my user was moved to an other OU (in that OU OwnCloud can't look, because is above the base DN which is configured in OC)  but after that, I moved my account back and I was able to use the owncloud since many weeks. 

Does Owncloud remove the "deleted" flag after a successfull LDAP auth? Because before I made the Upgrade to 8.2, I was logged in.  

Sunday or Monday I can look at my database backup If my user really was marked as deleted.

**Comment by blizzz** [comment] 2015-10-30 17:37
> Does Owncloud remove the "deleted" flag after a successfull LDAP auth? 

Nope. But this opens an opportunity to act upon it.

**Closed** 2015-11-02 10:28 UTC
Labels: app:user_ldap, bug, sev2-high

**Comment by tps800** [comment] 2015-11-09 08:32
Did this fix make it into the stable release? There is no newer than 8.1.4 available -- and this bug kills user administration because if ldap enabled the user list will never finish building ...!

**Comment by blizzz** [comment] 2015-11-09 08:36
@tps800 the fix was merged into 8.1 series just four days ago, i.e. will be included in 8.1.5: https://github.com/owncloud/core/pull/20246

**Comment by wcbzero** [comment] 2015-11-12 05:00
I had the same issue after upgrading to 8.2.0, the workaround suggested by @blizzz seems to be working for now.

**Comment by blizzz** [comment] 2015-11-12 08:39
@wcbzero will also be fixed in 8.2.1.

**Comment by simsasaile** [comment] 2015-11-12 10:32
Log in for LDAP-Users was also not working here after upgrading to V8.2. Thanks for the workaround (https://github.com/owncloud/core/issues/20090#issuecomment-152303971)!

**Comment by shtrom** [comment] 2015-11-14 07:18
@blizzz's quick fix works. Thanks.
