### ISSUE TITLE
@PublicPage routes no longer work in latest master (1d932e4)

### ISSUE THREAD

**Issue by Commenter123** [owncloud/core#21226] opened 2015-12-16 11:31 UTC
routes.php:
```php
return [
	'routes' => [
		['name' => 'site#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'site#test', 'url' => '/test', 'verb' => 'GET'],
	],
];
```

Methods in sitecontroller.php:
```php
/**
 * @NoAdminRequired
 * @NoCSRFRequired
 * @PublicPage
 */
public function index() {
	return new TemplateResponse('myapp', 'index', array());
}

/**
 * @NoAdminRequired
 * @NoCSRFRequired
 * @PublicPage
 */
public function test() {
	return new TemplateResponse('myapp', 'test', array());
}
```

When opening `/index.php/apps/myapp/` in browser, I get `Internal Server Error 500`.

Browser devconsole:
```text
Uncaught ReferenceError: oc_appconfig is not defined - shareconfigmodel.js:22
```

data/owncloud.log:
```text
{"reqId":"M3ZwmWQHU97piZmGEIAh","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"user does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/helper.php(202): OC\\\\AvatarManager->getAvatar(false)\\n#1 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/templatelayout.php(139): OC_Helper::userAvatarSet(false)\\n#2 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/template.php(224): OC_TemplateLayout->__construct('user', 'myapp')\\n#3 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/public\\\/appframework\\\/http\\\/templateresponse.php(156): OC_Template->fetchPage()\\n#4 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#5 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\MyApp\\\\Controller\\\\SiteController), 'index')\\n#6 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('SiteController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/route\\\/router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/base.php(866): OC\\\\Route\\\\Router->match('\\\/apps\\\/myapp\\\/')\\n#10 \\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/storage\\\/users\\\/myusername\\\/Documents\\\/git\\\/owncloud\\\/latest\\\/lib\\\/private\\\/avatarmanager.php\",\"Line\":66}","level":3,"time":"2015-12-16T11:26:45+00:00"}
```

Problem is that OC tries to fetch an avatar of user false, which does not exist.

**Comment by Commenter123** [comment] 2015-12-16 11:37
BTW: Everything works fine with `'empty'` as last argument to `new TemplateResponse`: `return new TemplateResponse('myapp', 'index', array(), 'empty');`

**Comment by DeepDiver1975** [comment] 2015-12-16 13:20
@Commenter123 which owncloud version are you using?

**Comment by Commenter123** [comment] 2015-12-16 13:54
As already said: Latest master, revision 1d932e4.

**Comment by DeepDiver1975** [comment] 2015-12-16 13:57
> As already said: Latest master, revision 1d932e4.

THX - didn't recognize that ...

**Comment by DeepDiver1975** [comment] 2015-12-16 13:58
@rullzer for avatars
@PVince81 @blizzz for sharemodel.js

THX

**Comment by blizzz** [comment] 2015-12-16 16:46
shareconfigmodel.js is just using oc_appconfig which is populated by core/js/config.php. If anything, than this is perhaps not loaded for some reason in this particular use case.  @LukasReschke do you know anything? some hardening possibly? :)

**Comment by blizzz** [comment] 2015-12-16 16:52
@Commenter123 do you happen to know the last revision it worked with?  (git bisect can assist in finding it out)

**Comment by LukasReschke** [comment] 2015-12-16 19:51
Mhm. Works for me locally here.

@Commenter123 Can you add your whole app code so that I could reproduce? If I could git checkout that would be awesome :smile:

**Comment by LukasReschke** [comment] 2015-12-16 19:59
Or test https://github.com/owncloud/core/pull/21241 :wink:

**Comment by Commenter123** [comment] 2015-12-17 11:05
#21241 fixes the issue :)

**Comment by blizzz** [comment] 2015-12-17 11:18
And it's merged.

**Closed by blizzz** 2015-12-17 11:18 UTC
Labels: bug, needs info, regression
