### ISSUE TITLE
Files disappear after renaming folder that is shared to multiple users

### ISSUE THREAD

**Issue by apodosenin** [owncloud/core#26644] opened 2016-11-16 16:16 UTC
### Steps to reproduce
1.Create folder that a number of subfolders and files and is shared between multiple users with sync agent enabled
2.Take one of the users offline
3.Rename folder via Agent with other user
4.Bring user in step 2 back online and start sync

### Expected behaviour
All users should have the same renamed folder on their computer

### Actual behaviour
Some files that were not synced are deleted.

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Apache/2.4.6 (CentOS)
**Database:**
mysql 5.5.38
**PHP version:**
5.5.38
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.2 (stable)
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment] 2016-11-30 13:36
@SergioBertolinSG please check

**Comment by PVince81** [comment] 2016-12-22 12:24
If that folder was really huge it is likely that the sync client issued a single MOVE for the folder, but PHP ran into a timeout and left the database in a corrupted state as explained in https://github.com/owncloud/core/issues/25569 and was also observed in https://github.com/owncloud/core/issues/25814.

You should be able to make these files reappear by running `occ files:scan --all`.

Best would be to increase the PHP timeout value for now.
I'm closing this as duplicate of the two mentionned tickets.

**Closed by PVince81** 2016-12-22 12:24 UTC
Labels: feature:sharing
