### ISSUE TITLE
core/preview.png?file=*.zip 404 Not Found error

### ISSUE THREAD

**Issue by milancoin-project** [owncloud/core#26453] opened 2016-10-24 08:00 UTC
when view the url https://localhost/index.php/apps/files/
get lots of 404 (Not Found) error ,looks like 
https://localhost/index.php/core/preview.png?file=abc.zip
https://localhost/index.php/core/preview.png?file=abc.docx
https://localhost/index.php/core/preview.png?file=abc.pdf
if files mime is text or image,,no problem.

php7.0  apache2.4  ubuntu 16.04  owncloud git

**Comment by RealRancor** [comment] 2016-10-24 08:08
@milancoin-project This is a duplicate of https://github.com/owncloud/core/issues/24216

The 404s are just thrown if its not possible to generate previews or if the preview generation is not configured for supported filetypes.

**Comment by milancoin-project** [comment] 2016-10-24 08:15
when i change the apps/files/js/filelist.js  file  like this,,looks very well,,but the unit test error

diff -ru ./apps/files/js/filelist.js /var/www/core/build/dist/owncloud/apps/files/js/filelist.js
--- ./apps/files/js/filelist.js 2016-10-24 13:10:51.105115696 +0500
+++ /var/www/core/build/dist/owncloud/apps/files/js/filelist.js 2016-10-24 11:48:29.792586166 +0500
@@ -1695,19 +1695,17 @@
                 * @param etag file etag (for caching)
                 */
                lazyLoadPreview : function(options) {
-                        var mime = options.mime;
-                        var ready = options.callback;
-                        // get mime icon url
-                        var iconURL = OC.MimeType.getIconUrl(mime);
-                        ready(iconURL); // set mimeicon URL
-
-                        if (mime.indexOf("text") == 0 || mime.indexOf("image") == 0){
                        var self = this;
                        var path = options.path;
+                       var mime = options.mime;
+                       var ready = options.callback;
                        var etag = options.etag;

+                       // get mime icon url
+                       var iconURL = OC.MimeType.getIconUrl(mime);
                        var previewURL,
                                urlSpec = {};
+                       ready(iconURL); // set mimeicon URL

                        urlSpec.file = OCA.Files.Files.fixPath(path);
                        if (options.x) {
@@ -1747,7 +1745,6 @@
                                img.onerror = options.error;
                        }
                        img.src = previewURL;
-                       }
                },

                /**

**Closed** 2016-10-24 08:42 UTC
