### ISSUE TITLE
Drag and Drop from sharing to private destroys files when quota exceeded (web frontpage)

### ISSUE THREAD

**Issue by TheFudge** [owncloud/core#7993] opened 2014-04-01 15:59 UTC
When a user moves a shared file to his own directory and has his quota exceeded, the file is moved from the shared folder.
But because the user has no storage left the filename appears in his home directory but has no file size.
(a test.txt file was completely empty.)

**Comment by PVince81** [comment] 2015-03-09 12:04
Duplicate of https://github.com/owncloud/core/issues/14284 which was fixed

**Closed by PVince81** 2015-03-09 12:04 UTC
Labels: bug, needs info, Quota, Sharing
