### ISSUE TITLE
One of the two files with same name but different path disappears when details dialog of other is opened

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33011] opened 2018-10-04 06:57 UTC
### Steps to reproduce
1.  Share a file  'lorem.txt' to other internal user
2.  Create another file 'lorem.txt' in another folder and then share it as done previously.
3. Go to the `Shared with others` page.
4. Open details dialog of one of the two files. 

### Expected behaviour
Both the files are shown in the file list while the detail of one of the file is shown.

### Actual behaviour
The other file disappears from the file list.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
Apache

**Database:**
mariadb

**PHP version:**
7.2.10

**ownCloud version:** (see ownCloud admin page)
10.1.0 prealpha (git)

**Updated from an older ownCloud or fresh install:**
No

**Where did you install ownCloud from:**
github

**Signing status (ownCloud 9.0 and above):**

**The content of config/config.php:**

**List of activated apps:**

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

### Client configuration
**Browser:**
Chrome, Firefox

**Operating system:**
Ubuntu 18.04

**Comment by phil-davis** [comment] 2018-10-04 07:12
The problem is also in the favorites page and the tags page and probably every other page where the file list can have duplicate file names that come from different folders.

**Comment by JammingBen** [comment] 2021-09-21 09:27
Fixed via https://github.com/owncloud/core/pull/38415

**Closed by JammingBen** 2021-09-21 09:27 UTC
Labels: Type:Bug, QA
