### ISSUE TITLE
Rename collision message in favorites names wrong folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39552] opened 2021-12-03 21:03 UTC
Seen in 10.9.0 beta1

* Create files a.txt and b.txt in folder Photos. 
* Mark b.txt as favorite, (but not a.txt)
* Visit Favorites page, and try rename b.txt to a.txt, as expected an error message is shown.
* The error message has the wrong folder:
![image](https://user-images.githubusercontent.com/1108546/144672364-e1c625d5-8899-45d3-88e9-6326eb2e54b5.png)

no file a.txt exists in /, and if so, that would not be the cause of the collision.

Expected behaviour: The name "a.txt" is already used in the folder "Photos". Please choose a different name.

**Comment by JammingBen** [comment] 2021-12-07 12:49
Not a regression IMO, but fix will be included in 10.9 since it's super small: https://github.com/owncloud/core/pull/39569

**Closed** 2021-12-07 15:25 UTC
Labels: Type:Bug

**Comment by jnweiger** [comment] 2021-12-10 11:00
Confirmed fixed in RC1. Thanks.
