### ISSUE TITLE
folder & filetype icons hardcoded? 

### ISSUE THREAD

**Issue by vgiannoul** [owncloud/core#16547] opened 2015-05-23 22:17 UTC
I'm trying to figure out how could possibly change folder icon without luck. 
I've changed icons and placed them inside my theme folder ([themename]/core/img/filetype/folder.svg) and nothing changed. 
As far as I can understand the filelist.js (files app) generates inline links for the icons. 
What would be the proper way to alter these icons?
Thanks in advance and hope there is some solution.

**Comment by RealRancor** [comment] 2015-05-24 08:44
Hi,

i'm not sure but for the logos you need to also modify the header.css: https://github.com/owncloud/documentation/issues/1092

**Comment by vgiannoul** [comment] 2015-05-27 14:39
Hello again, 
I modified the relevant css file (icons.css) but still no luck.

**Comment by DeepDiver1975** [comment] 2015-05-27 14:44
@jancborchardt any idea on how to get this done? THX

**Comment by jancborchardt** [comment] 2015-05-28 22:01
Duplicate of https://github.com/owncloud/core/issues/15320, and fix at https://github.com/owncloud/core/pull/15586 - please review that! :)

**Closed by jancborchardt** 2015-05-28 22:01 UTC
Labels: enhancement

**Comment by vgiannoul** [comment] 2015-05-29 08:53
Thanks a lot for the response @jancborchardt

**Comment by jancborchardt** [comment] 2015-05-29 15:28
@vgiannoul well, please test https://github.com/owncloud/core/pull/15586 and leave your review there. :)
