### ISSUE TITLE
enable password recovery by default?

### ISSUE THREAD

**Issue by xoroz** [owncloud/core#28495] opened 2017-07-26 13:53 UTC
Is there a way to enable password recovery by default? 
If not, is there a occ command to change this value for several users?

I am afraid that users LDAP password gets changed and data remains encrpyted with old password....

I noticied that some systems dont have enable password recovery configured! 

please help

**Comment by PVince81** [comment] 2017-07-26 15:48
Are you talking about the recovery key for encryption ? If yes, duplicate of https://github.com/owncloud/core/issues/11948

**Closed** 2017-09-07 15:23 UTC
