### ISSUE TITLE
Admin user interface does not save email adresses

### ISSUE THREAD

**Issue by poVoq** [owncloud/core#18825] opened 2015-09-04 07:31 UTC
Version: 8.1.1. (using latest Firefox)

What was done: Adding new email addresses to user accounts without email addresses set through the admin user interface

Expected behavior: Settings to show email addresses and email addresses added should be saved

Actual behavior: when I exit the user edit screen and re-enter it all visibility setting are reset and all email addresses added through the admin interface are forgotten.

Partially work-around: write email address and then press enter key. If one just clicks elsewhere it looks like it is saved (see above) but this is not actually the case. Visibility of email settings are still lost however.

**Comment by PVince81** [comment] 2015-09-16 15:25
Duplicate of https://github.com/owncloud/core/issues/16360

**Closed by PVince81** 2015-09-16 15:25 UTC
Labels: bug, settings:users
