### ISSUE TITLE
Can not remote share a file/folder with a quote in the name

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#22247] opened 2016-02-09 15:05 UTC
I assume URL encoding breaks something somewhere.
The share can not be created (at least via the sidebar)

@rullzer @schiesbn

**Comment by rullzer** [comment] 2016-02-10 13:02
I'll look into this...

**Comment by rullzer** [comment] 2016-02-10 14:05
Ok found the root of all evil:

https://github.com/owncloud/core/blob/master/apps/files_sharing/ajax/external.php#L48
https://github.com/owncloud/core/blob/master/lib/public/util.php#L639
https://github.com/owncloud/core/blob/master/lib/private/util.php#L1418
https://github.com/owncloud/core/blob/master/lib/public/constants.php#L73

Now the comments say to use \OC\Files\View::verifyPath but I do not want to setup the entire view.

@icewind1991 am I correct in assuming that we can change https://github.com/owncloud/core/blob/master/lib/public/constants.php#L73 to `\\/' since that is what you seem to use in the verifyPath code as well?

**Comment by icewind1991** [comment] 2016-02-11 12:22
> am I correct in assuming that we can change https://github.com/owncloud/core/blob/master/lib/public/constants.php#L73 to `\/' since that is what you seem to use in the verifyPath code as well?

Seems so

**Comment by rullzer** [comment] 2016-02-12 07:44
Actually this is not a regression since it was not possible before ;)
But PR in #22338

**Comment by rullzer** [comment] 2016-02-16 13:25
#22338 merged...

**Closed by rullzer** 2016-02-16 13:25 UTC
Labels: bug, feature:federated-cloud-sharing, sev2-high
