### ISSUE TITLE
Owncloud 8.1. fails to save view of User settings in admin page

### ISSUE THREAD

**Issue by farson2003** [owncloud/core#17215] opened 2015-06-27 21:53 UTC
Under the user section the admin has a few checkboxes to 
-Show storage location
-Show email address 
and so on.

Once a checkbox is checked, everytime the admin reloads that page the boxes become unchecked again.

For better usability they should remain checked, so the admin gets the standard view he likes.

Please consider.

**Comment by LukasReschke** [comment] 2015-06-27 21:58
Dupe of a ton of other issues, https://github.com/owncloud/core/issues/12727

**Closed by LukasReschke** 2015-06-27 21:58 UTC
