### ISSUE TITLE
[8.2.0] New Login Screen missing Login Button

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#19975] opened 2015-10-22 12:21 UTC
With ownCloud 8.2.0 we have a new login screen, on the right on the image:
![logins](https://cloud.githubusercontent.com/assets/1070214/10664916/8f00e054-78c7-11e5-97e3-74de5b6862f5.png)

Even though I understand that it looks stylish, I wonder if the lack of a login button helps "normal" users. Everybody I saw/talked about was confused and did not recognise the greyed out arrow as an control element. Maybe this should be reconsidered for the Enterprise edition.

Not having the word *ownCloud* any more is a matter of taste...

**Comment by oparoz** [comment] 2015-10-22 19:04
Agreed, there is already a discussion about this here: https://github.com/owncloud/core/issues/18940
My first impression this Summer was that master was broken, not that there was a new way to login.

**Comment by jancborchardt** [comment] 2015-10-22 21:03
Duplicate of https://github.com/owncloud/core/issues/18940

So far I haven’t seen a report by someone who is _not_ an ownCloud developer. Will try to do some more usability testing.

Also @dragotin realizing stuff like this is exactly what the beta phases are for. ;)

**Closed by jancborchardt** 2015-10-22 21:03 UTC
Labels: design

**Comment by danger89** [comment] 2016-05-03 18:48
For me it was also kinda confusing, but apparently this is a 'feature'.
