### ISSUE TITLE
Fresh Install v9 - Caldav Broke

### ISSUE THREAD

**Issue by Keelan** [owncloud/core#24169] opened 2016-04-21 16:55 UTC
### Steps to reproduce
1. Fresh install
2. new user
3. add item to calendar
4. sync calendar via caldav

### Expected behaviour
Pull in calendar items

### Actual behaviour
12:50:31 PM Work [CalDAV / CardDAV]  MailExceptions.OperationException: Sync of Work/ failed due to the following error: Work (Service Unavailable)
12:50:31 PM <?xml version="1.0" encoding="utf-8"?>
12:50:31 PM <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
12:50:31 PM   <s:sabredav-version>3.0.8</s:sabredav-version>
12:50:31 PM   <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
12:50:31 PM   <s:message>RemoteException: App not installed: </s:message>
12:50:31 PM </d:error>

### Server configuration
**Operating system**:
centos 6

**Web server:**
apache 2.4

**Database:**
mysql

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
9.0.1.3

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
manual download link tar 

**Signing status (ownCloud 9.0 and above):**

```
no issues
```

**List of activated apps:**

```
only built in ones (fresh install) plus calendars and contacts
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc88bti22mo7',
  'passwordsalt' => '',
  'secret' => '251PGkWHBCo1B4xImjBtyD2wc8QmxYt4PWrpUd9BsWdAwA+i',
  'trusted_domains' => 
  array (
    0 => 'relcontrols.ca',
  ),
  'datadirectory' => '/home/relcontr/public_html/files/data',
  'overwrite.cli.url' => 'http://relcontrols.ca/files',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'relcontr_fil',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'relcontr_fil',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome

**Operating system:**
windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_Keelan\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'relcontr_fil'@'localhost' for table 'user'","level":3,"time":"2016-04-21T16:37:44+00:00","method":"POST","url":"\/files\/index.php","user":"--"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `relcontr_fil` . * TO 'relcontr_fil'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'relcontr_fil'@'localhost' to database 'relcontr_fil'","level":3,"time":"2016-04-21T16:37:44+00:00","method":"POST","url":"\/files\/index.php","user":"--"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(639): include('\\\/home\\\/relcontr\\\/...')\\n#4 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/home\\\/relcontr\\\/...')\\n#5 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-21T16:37:52+00:00","method":"POST","url":"\/files\/index.php","user":"--"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(639): include('\\\/home\\\/relcontr\\\/...')\\n#4 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(590): OC_Installer::includeAppScript('\\\/home\\\/relcontr\\\/...')\\n#5 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/installer.php(561): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/lib\\\/base.php(832): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/relcontr\\\/public_html\\\/files\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/relcontr\\\/public_html\\\/files\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-21T16:37:52+00:00","method":"POST","url":"\/files\/index.php","user":"--"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"PHP","message":"file_get_contents(\/home\/relcontr\/public_html\/files\/.htaccess): failed to open stream: No such file or directory at \/home\/relcontr\/public_html\/files\/lib\/private\/setup.php#412","level":3,"time":"2016-04-21T16:37:53+00:00","method":"POST","url":"\/files\/index.php","user":"--"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"PHP","message":"copy(\/home\/relcontr\/public_html\/files\/.user.ini): failed to open stream: No such file or directory at \/home\/relcontr\/public_html\/files\/lib\/private\/integritycheck\/checker.php#189","level":3,"time":"2016-04-21T16:37:53+00:00","method":"POST","url":"\/files\/index.php","user":"Keelan"}
{"reqId":"VxkB2MBjAFgAAEOyNFgAAAAI","remoteAddr":"76.70.14.62","app":"files","message":"Can't write upload limit to \/tmp\/oc_tmp_4KlXSZ-folder\/.user.ini. Please check the file permissions","level":2,"time":"2016-04-21T16:37:53+00:00","method":"POST","url":"\/files\/index.php","user":"Keelan"}
{"reqId":"VxkDM8BjAFgAAC0VFsIAAAAG","remoteAddr":"76.70.14.62","app":"core","message":"App directory already exists","level":3,"time":"2016-04-21T16:43:33+00:00","method":"POST","url":"\/files\/index.php\/settings\/ajax\/enableapp.php","user":"Keelan"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Keelan** [comment] 2016-04-21 16:57
Contacts work fine but calendars do not

http://relcontrols.ca/files/remote.php/davhp/dav/calendars/Keelan2/default/

results in app not installed.

**Comment by RealRancor** [comment] 2016-04-21 17:24
Duplicate of https://github.com/owncloud/core/issues/23964 (just a slight difference between davphp and dave.php)

**Closed** 2016-04-22 05:24 UTC
