### ISSUE TITLE
Upgrade not possible - encryption related ???

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#17915] opened 2015-07-27 19:34 UTC
as per https://github.com/owncloud/core/pull/17911#issuecomment-125319559

2 of 3 8.1 instances could not be migrated - both blocked instances share the fact that encryption is enabled.

from the log:

````

{
"reqId":"No8qjIlPGyrrIuoE7Qc8",
"remoteAddr":"178.25.225.40",
"app":"index",
"message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/owncloud8.1\\\/lib\\\/private\\\/app.php(99): OC_App::loadApp('files')\\n#1 \\\/srv\\\/www\\\/owncloud8.1\\\/lib\\\/private\\\/util.php(127): OC_App::loadApps(Array)\\n#2 \\\/srv\\\/www\\\/owncloud8.1\\\/lib\\\/base.php(872): OC_Util::setupFS()\\n#3 \\\/srv\\\/www\\\/owncloud8.1\\\/index.php(40): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/srv\\\/www\\\/owncloud8.1\\\/lib\\\/private\\\/app.php\",\"Line\":118}"
,"level":4,
"time":"2015-07-27T19:28:02+00:00"
}

**Comment by DeepDiver1975** [comment] 2015-07-28 09:00
hmmm ... was successful on the 3rd retry ..... we still need to test the upgrade scenario.

**Comment by schiesbn** [comment] 2015-07-28 09:02
Just a few seconds ago I also upgrade from 8.1.0 to stable8.1 with encryption enabled successfully.

**Comment by DeepDiver1975** [comment] 2015-07-28 09:04
@rperezb can you please asap start with upgrade testing using the daily tar ball for 8.1.1 ?

Setups to be tested:

encryption | locking
--------------|----------
 no | no
 yes | no
 yes | yes
 no | yes

**Comment by rperezb** [comment] 2015-07-28 10:59
@DeepDiver1975, yes, @jvillafanez will take care of this. 
The first iteration it will be from 8.0 to 8.1.1
Then, 8.0.5 to 8.1.1

**Comment by schiesbn** [comment] 2015-07-28 11:09
maybe that's the steps we need to reproduce it: https://github.com/owncloud/core/issues/17925 I will look into it later

**Comment by PVince81** [comment] 2015-07-29 08:35
@DeepDiver1975 are you guys still seeing this on stable8.1 ? The PR was merged.

**Comment by jvillafanez** [comment] 2015-07-29 10:32
Tested upgrades 8.0.0 to stable8.1 and 8.0.5 to stable8.1, both passing fine.

The test includes
1. enable files_encryption
2. run smashbox test (basicSync)
3. upload an extra file
4. upgrade to stable8.1
5. enable encryption
6. migrate keys
7. download the file in step 3 and check is the same as the one uploaded
8. run again the same smashbox test (basicSync)

No sharing involved for now

**Comment by DeepDiver1975** [comment] 2015-07-29 11:24
we need to test 8.1.0 to 8.1.1 - just in case this was not clear of I did miss anything

**Comment by jvillafanez** [comment] 2015-07-30 08:38
Today's tests with today's packages: upgrades 8.0.0 -> stable8.1 ; 8.0.5 -> stable8.1 ; 8.1.0 -> stable8.1

Test includes:
1. enable files_encryption (*)
2. create a new user
3. run smashbox test (basicSync)
4. create a new folder with a file inside
5. share the file with the new user
6. upgrade to stable8.1
7. enable encryption
8. migrate keys
9. download upload file in step 4 from both accounts
10. run again smashbox test

The script doesn't crash, but I've notice a couple of things:
* 8.0.0 and 8.0.5 have files_encryption enabled, after upgrade to stable8.1, I do `occ app:enable encryption` and `occ encryption:enable` and the response is that no encryption module is loaded, so it's not clear the encryption status.

Relevant trace from the script:
```
INFO:servers:run_remote_occ -> ['app:enable', 'encryption']
INFO:servers:encryption enabled

INFO:servers:run_remote_occ -> ['encryption:enable']
INFO:servers:Encryption enabled

No encryption module is loaded

INFO:servers:run_remote_occ -> ['encryption:migrate']
INFO:servers:Reorganize system folder structure
Migrating keys for users on backend Database
   admin
   foo_user
   user
```

* 8.1.0 doesn't have files_encryption so the test isn't the same as for 8.0.0 and 8.0.5 (that part of the test isn't done with encryption then). Anyway, in this case, after doing the same steps as I did before, the encryption module is set as the OC_DEFAULT_MODULE.

```
INFO:servers:run_remote_occ -> ['app:enable', 'encryption']
INFO:servers:encryption enabled

INFO:servers:run_remote_occ -> ['encryption:enable']
INFO:servers:Encryption enabled

Default module: OC_DEFAULT_MODULE

INFO:servers:run_remote_occ -> ['encryption:migrate']
INFO:servers:Reorganize system folder structure
Migrating keys for users on backend Database
   admin
   foo_user
   user
```
@schiesbn could you explain the behaviour and the encryption status in those cases?

**Comment by jvillafanez** [comment] 2015-07-30 08:42
In addition, for the 8.1.0 to stable8.1, the `occ encryption:migrate`.... I think it should fail or at least the message should be different because there shouldn't be any key to migrate since the files_encryption wasn't enabled, doesn't it?

**Comment by jvillafanez** [comment] 2015-07-30 11:46
Adjusted the script for 8.1.0 to stable8.1 to enable encryption instead of files_encryption and don't migrate the encryption keys: it seems to be fine

Although notice that keys shouldn't be migrated in this case: ref https://github.com/owncloud/core/issues/17983

**Comment by schiesbn** [comment] 2015-08-03 10:04
I still can't reproduce it. @jvillafanez if you understand you correctly, now with #17983 resolved it also works for you in all circumstances. @DeepDiver1975 you also can't reproduce it anymore, right? So I'm not sure what to do with it if none of us three can re-produce it.

**Comment by schiesbn** [comment] 2015-08-03 10:09
@jvillafanez maybe we cann add some extra output at the end like:

````
X Users migrated
Database Migrated (or Database already up-to-date
````

But this could be confusing too.

What would a admin think if he sees "312 users migrated" but he knows that he has 364 users? Is it a bug that not all users are migrated? Are the other users already migrated? Maybe some of them doesn't had any keys/files?

Maybe it is more confusing than it adds clarity. Probably we should just stick to "executed successful"  or an useful error message if something went wrong.

**Comment by jvillafanez** [comment] 2015-08-03 10:52
I'll prepare a script to verify #17983 against stable8.1 for tomorrow's build (the current script applies the corresponding patch, so it will probably fail tomorrow because the patch is already applied). Other than that, the encryption + upgrade scenario is tested, as well as the basic upgrade.

The scenario with locking isn't tested yet, neither setups with external storages.

**Comment by DeepDiver1975** [comment] 2015-08-03 10:56
Let's keep this open for now.

@rperezb we need full upgrade testing of 8.1.1 once bundled - THX

**Comment by cmonteroluque** [comment] 2015-08-03 11:06
@jvillafanez following up previous comment from @DeepDiver1975 for testing.

**Comment by jvillafanez** [comment] 2015-08-05 15:40
Tested both with and without encryption:
- 8.1.0 -> 8.1.1
- 8.0.5 -> 8.1.1
- 8.0.0 -> 8.1.1
- 8.0.5 -> 8.0.6
- 8.0.0 -> 8.0.6
- 7.0.7 -> 8.0.6
- 7.0.7 -> 7.0.8
- 7.0.0 -> 7.0.8
- 6.0.9 -> 7.0.8

The only bit missing is 6.0.9 to 7.0.8 with encryption, due to https://github.com/owncloud/pyocclient/issues/106 , but I don't expect any issue.

Locking is still outside of the tests.

**Comment by jvillafanez** [comment] 2015-08-06 12:37
Added locking to the upgrade 8.1.0 -> 8.1.1, both with and without encryption.

Smashbox's locking test seemed too unreliable (with and external server they pass fine, but not in this environment) so I've stuck to basic_sync tests.

**Comment by PVince81** [comment] 2015-08-12 08:42
Moving to 8.1.2.

Is this still an issue ?

**Comment by rperezb** [comment] 2015-08-12 12:16
@PVince81 the tests suggested by @DeepDiver1975  https://github.com/owncloud/core/issues/17915#issuecomment-125511259 were checked by @jvillafanez  and everything went fine.
From our POV this may be closed

**Comment by PVince81** [comment] 2015-08-13 09:12
Thanks, closing then.

**Closed by PVince81** 2015-08-13 09:12 UTC
Labels: app:encryption, regression, showstopper, update
