### ISSUE TITLE
While uploading to Dropbox I get strange errors

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#11655] opened 2014-10-19 01:09 UTC
I know there have been some issues since before with the External Storage, and that @PVince81 is working on a fix here #6069. But I don´t know how work is going over there?

Anyway, here is another isuse with failuers when mounting Dropbox though  external storage.

### Steps to reproduce
1. Sync your ownCloud with your Dropbox
2. Upload files through Dropbox.com
3. After many sloow uploads with the sync-client...
4. ...these errors appears.

### Expected behaviour
No errors

### Actual behaviour
I get this in owncloud.log:
```

Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:53+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:52+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:51+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:50+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:50+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:49+00:00
Error	PHP	file_get_contents(http:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
Error	PHP	file_get_contents(https:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
```

### Server configuration
Ubuntu Server 12.04

**Database:**
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
**PHP version:**
PHP 5.3.10-1ubuntu3.14 with Suhosin-Patch (cli) (built: Sep  4 2014 07:08:49)
**ownCloud version:** (see ownCloud admin page)
7.0.2
**Updated from an older ownCloud or fresh install:**
Updated from stable 5 and then later stable 6
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost.localdomain',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'check_for_working_webdav' => false,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => '',
    1 => '192.168.1.111',
  ),
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'appstoreenabled' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Version 37.0.2062.120 m
**Operating system:**
Windows 8.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-19T11:33:15+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-19T11:33:14+00:00
Error	files_external	Error: (503) Failed to grab locks for 10637368, please re-issue request.	2014-10-19T11:33:13+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-19T10:16:07+00:00
Error	files_external	Resource at uri: https://api.dropbox.com/1/fileops/delete could not be found. Path '/its-13 (delad)/owncloudstresstest/owncloudtest/78/14.txt.octransferid2074397084.part' not found	2014-10-19T10:16:07+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-19T10:16:06+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 3 got 0	2014-10-19T10:15:18+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-19T10:15:18+00:00
Error	files_external	Error: (503) Service Unavailable	2014-10-19T10:15:14+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 3 got 0	2014-10-19T09:39:37+00:00
Error	files_external	Resource at uri: https://api.dropbox.com/1/fileops/delete could not be found. Path '/ITS-13 (delad)/owncloudstresstest/owncloudtest/75/0.txt.octransferid1760320718.part' not found	2014-10-19T09:39:37+00:00
Error	files_external	Error: (503) Service Unavailable	2014-10-19T09:39:34+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 3 got 0	2014-10-19T09:27:54+00:00
Error	files_external	Resource at uri: https://api.dropbox.com/1/fileops/delete could not be found. Path '/ITS-13 (delad)/owncloudstresstest/owncloudtest/74/1.txt.octransferid1785710701.part' not found	2014-10-19T09:27:54+00:00
Error	files_external	Error: (503) Service Unavailable	2014-10-19T09:27:51+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 3 got 0	2014-10-19T03:54:16+00:00
Error	files_external	Resource at uri: https://api.dropbox.com/1/fileops/delete could not be found. Path '/ITS-13 (delad)/owncloudstresstest/owncloudtest/48/65.txt.octransferid1152331292.part' not found	2014-10-19T03:54:16+00:00
Error	files_external	Curl error: (52) Empty reply from server	2014-10-19T03:54:13+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-19T02:12:14+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-19T02:12:13+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-19T02:12:12+00:00
Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:53+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:52+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:51+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:50+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:50+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:49+00:00
Error	PHP	file_get_contents(http:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
Error	PHP	file_get_contents(https:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Error	PHP	Division by zero at /var/www/owncloud/lib/private/preview.php#426	2014-10-19T00:57:51+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:53+00:00
Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file	2014-10-18T22:31:52+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:51+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:50+00:00
Error	webdav	\OC\Files\Filesystem::rename() failed	2014-10-18T22:31:50+00:00
Error	files_external	Error: (503) Failed to grab locks for 356313242, please re-issue request.	2014-10-18T22:31:49+00:00
Error	PHP	file_get_contents(http:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
Error	PHP	file_get_contents(https:///status.php): failed to open stream: operation failed at /var/www/owncloud/apps/files_sharing/ajax/testremote.php#15	2014-10-18T22:09:21+00:00
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by enoch85** [comment] 2015-03-23 19:55
@PVince81 I don't use Dropbox anymore so I can't help you debug this. Keep it open anyway?

**Comment by PVince81** [comment] 2016-04-29 14:38
Closing as obsolete if there is no way to reproduce.

Also in v9.0.1 there were improvements in upload/download code for Dropbox, maybe that could help as well in case it was due to timeouts.

**Closed by PVince81** 2016-04-29 14:38 UTC
Labels: app:files_external, bug
