### ISSUE TITLE
9.0 oC broken after updating with the updater app (daily)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#23469] opened 2016-03-22 10:06 UTC
Note: I put this here because of: missing OCA\Files_Sharing\API\Server2Server message

### Steps to reproduce
1. Having 9.0 installed via tar
2. Setting proper pre- update permissions
3. Updating via the updater app from the admin screen, setting to daily.

### Expected behaviour
Update should pass, and after resetting to strong permissions, the instance should work fine.

### Actual behaviour
Instance is dead and inaccessible

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) was 9.0.0.19

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
Enabled:
Disabled:
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oci1ewzyz3i0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 0,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### Web server error log
```
2016/03/22 10:35:55 [error] 38627#38627: *31 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OCA\Files_Sharing\API\Server2Server' not found in /var/www/owncloud/ocs/routes.php on line 102
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/index.php:0
PHP message: PHP   2. OC::handleRequest() /var/www/owncloud/index.php:39
PHP message: PHP   3. OC\Route\Router->match() /var/www/owncloud/lib/base.php:878
PHP message: PHP   4. OC\Route\Router->loadRoutes() /var/www/owncloud/lib/private/route/router.php:244
PHP message: PHP   5. require_once() /var/www/owncloud/lib/private/route/router.php:156" while reading response header from upstream, client: 80.110.35.173, server: xxx, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"

2016/03/22 10:39:53 [error] 38627#38627: *127 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 138
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/remote.php:0" while reading response header from upstream, client: 80.110.35.173, server: xxx, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VbCktlJfOl2Sq1C8p\/MU","remoteAddr":"80.110.35.173","app":"PHP","message":"Class 'OCA\\Files_Sharing\\API\\Server2Server' not found at var\/www\/owncloud\/ocs\/routes.php#102","level":3,"time":"2016-03-22T11:00:39+01:00","method":"GET","url":"\/"}
{"reqId":"xHz0VdJZFzztrndlQ3Fu","remoteAddr":"80.110.35.173","app":"PHP","message":"require_once(\/appinfo\/v1\/webdav.php): failed to open stream: No such file or directory at var\/www\/owncloud\/remote.php#138","level":3,"time":"2016-03-22T11:00:42+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
{"reqId":"xHz0VdJZFzztrndlQ3Fu","remoteAddr":"80.110.35.173","app":"PHP","message":"require_once(): Failed opening required '\/appinfo\/v1\/webdav.php' (include_path='var\/www\/owncloud\/3rdparty\/pear\/console_getopt:var\/www\/owncloud\/3rdparty\/pear\/pear_exception:var\/www\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:var\/www\/owncloud\/3rdparty\/pear\/archive_tar:var\/www\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:var\/www\/owncloud\/lib\/private:var\/www\/owncloud\/config:var\/www\/owncloud\/3rdparty:var\/www\/owncloud\/apps:.:\/usr\/share\/php:\/usr\/share\/pear:var\/www\/owncloud') at var\/www\/owncloud\/remote.php#138","level":3,"time":"2016-03-22T11:00:42+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
```

**Comment by mmattel** [comment] 2016-03-22 10:38
I think I found the problem:

It seems that it is a updater app problem. There was a renaming/moving of the directory apps/ to __apps/ but not back. Because the apps/ directory was empty, the instance reported the error.
````
:/var/www/owncloud/$ ll apps
total 8
drwxr-x---  2 www-data www-data 4096 Mar 22 10:29 ./
drwxr-x--- 17 root     www-data 4096 Mar 22 11:18 ../

:/var/www/owncloud/$ ll __apps/
total 108
drwxr-x--- 27 root www-data 4096 Mar 14 12:12 ./
drwxr-x--- 17 root www-data 4096 Mar 22 11:18 ../
drwxr-x--- 12 root www-data 4096 Mar  8 14:57 activity/
drwxr-x--- 10 root www-data 4096 Mar 14 12:12 calendar/
drwxr-x---  7 root www-data 4096 Mar  8 14:57 comments/
drwxr-x---  5 root www-data 4096 Mar  8 14:57 dav/
drwxr-x--- 13 root www-data 4096 Mar  8 14:57 encryption/
drwxr-x--- 10 root www-data 4096 Mar  8 14:54 external/
drwxr-x---  5 root www-data 4096 Mar  8 14:57 federatedfilesharing/
drwxr-x--- 16 root www-data 4096 Mar  8 14:57 federation/
drwxr-x--- 13 root www-data 4096 Mar  8 14:57 files/
drwxr-x--- 15 root www-data 4096 Mar  8 14:57 files_external/
drwxr-x---  9 root www-data 4096 Mar  8 14:57 files_pdfviewer/
drwxr-x--- 11 root www-data 4096 Mar  8 14:57 files_sharing/
drwxr-x---  8 root www-data 4096 Mar  8 14:57 files_texteditor/
drwxr-x--- 11 root www-data 4096 Mar  8 14:57 files_trashbin/
drwxr-x--- 10 root www-data 4096 Mar  8 14:57 files_versions/
drwxr-x---  7 root www-data 4096 Mar  8 14:57 files_videoplayer/
drwxr-x--- 10 root www-data 4096 Mar  8 14:57 firstrunwizard/
drwxr-x--- 20 root www-data 4096 Mar  8 14:57 gallery/
drwxr-x---  9 root www-data 4096 Mar  8 14:57 notifications/
drwxr-x---  5 root www-data 4096 Mar  8 14:57 provisioning_api/
drwxr-x---  9 root www-data 4096 Mar  8 14:57 systemtags/
drwxr-x--- 12 root www-data 4096 Mar  8 14:57 templateeditor/
drwxr-x---  8 root www-data 4096 Mar  8 14:57 updatenotification/
drwxr-x---  5 root www-data 4096 Mar  8 14:57 user_external/
drwxr-x--- 12 root www-data 4096 Mar  8 14:57 user_ldap/
````
After manually renaming __apps/ to apps/ things worked fine again.

IMHO, there should be a check if mandatory apps are present or not and report an log entry in case.

**Comment by PVince81** [comment] 2016-03-22 10:38
@mmattel thanks for testing!

@VicDeo can you have a look ?

**Comment by mmattel** [comment] 2016-03-22 10:42
I was in panic for some moments, because this was my productive instance...
Damn, my heart is still beating :smile:

**Comment by PVince81** [comment] 2016-03-22 10:44
I'd also panic if I didn't have backups before upgrading :wink:

**Comment by VicDeo** [comment] 2016-03-22 11:19
duplicate of #280

Fixed with
#281
#282

@mmattel 
application.php upgrade:checkpoint --list
application.php upgrade:checkpoint --restore [checkpointid] 
are your friends

**Closed by VicDeo** 2016-03-22 11:19 UTC
Labels: bug, feature:update, sev2-high

**Comment by mmattel** [comment] 2016-03-22 11:48
@PVince81 @VicDeo 

Maybe a good point to highlight a documentation update need on https://github.com/owncloud/documentation/blob/master/admin_manual/maintenance/manual_upgrade.rst
describing the manual ``update`` command (a bit confusing as there is already an ``upgrade`` command) ``sudo -uwww-data php updater/application.php`` with its parameters...
As @VicDeo mentioned in a differet thread, the use of the latter gives the ability to run pre and post scipts like setting proper permissions...

As an additional idea, I vote for a occ ``update`` command wrapping ``updater/application.php`` and add this to the already existing documents.

**Comment by mmattel** [comment] 2016-03-22 13:37
Created a feature request: https://github.com/owncloud/updater/issues/293
