### ISSUE TITLE
Web GUI share link unhandled condition

### ISSUE THREAD

**Issue by vpecinka** [owncloud/core#24257] opened 2016-04-25 15:30 UTC
### Steps to reproduce
1. Set up to require password for public links (admin console)
2. Select any file or folder you want to share via public link (open sharing tab)
3. Click on checkbox to share link, the input for password should appear
4. Unselect the checkbox without entering the password
5. You can see waiting icon and no chexkbox is visible until you reload the page/tab
### Expected behaviour

The checkbox should appear again
### Actual behaviour

The page show waiting icon pretending it is doing something :)
### Server configuration

**Operating system**: Linux Debian
**ownCloud version:**  8.2.3
### Client configuration

**Browser:**  Tried with Safari  9.1 and Firefox 45.0.2
**Operating system:** OS X
#### Browser log

The javascript console is empty, does not report any error when I select/unselect the checkbox

**Comment by PVince81** [comment] 2016-04-26 08:22
@rullzer

**Comment by souravbadami** [comment] 2016-12-20 22:05
I'm unable to reproduce it on the latest master. I think, it got fixed ?

**Comment by davitol** [comment] 2017-02-27 08:00
This issue is fixed and it is no longer reproducible in master so let's close it @PVince81

**Closed by davitol** 2017-02-27 08:00 UTC
Labels: bug, feature:sharing, junior job, sev3-medium
