### ISSUE TITLE
Internal server error disabling the activity app

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#17364] opened 2015-07-03 07:29 UTC
### Steps to reproduce
1. Install ownCloud 8.1.0
2. Disable the activity app or the pictures app

### Expected behaviour
The app is disabled without any error

### Actual behaviour
Internal error appears in the logs. The app is disabled anyway

![screenshot from 2015-07-03 09 24 00](https://cloud.githubusercontent.com/assets/1477829/8494435/462b5670-2165-11e5-9f14-22e0a1f530c4.png)

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** Postgresql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1.0

**Updated from an older ownCloud or fresh install:** fresh install

#### ownCloud log (data/owncloud.log)
```
{"reqId":"K2FXOHeUVlYPPfyFpnPt","remoteAddr":"82.159.139.58","app":"index","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"activity.Activities.showList\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(306): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('activity.Activi...', Array, false)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/urlgenerator.php(65): OC\\\\Route\\\\Router->generate('activity.Activi...', Array)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/activity\\\/appinfo\\\/app.php(35): OC\\\\URLGenerator->linkToRoute('activity.Activi...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/navigationmanager.php(63): OC_App::OCA\\\\Activity\\\\AppInfo\\\\{closure}()\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/app.php(395): OC\\\\NavigationManager->getAll()\\n#5 \\\/opt\\\/owncloud\\\/settings\\\/ajax\\\/navigationdetect.php(29): OC_App::getAppNavigationEntries('activity')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/opt\\\/owncloud\\\/s...')\\n#7 [internal function]: __lambda_func(Array)\\n#8 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('?lambda_358', Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/base.php(867): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#10 \\\/opt\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/3rdparty\\\/symfony\\\/routing\\\/Symfony\\\/Component\\\/Routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":134}","level":4,"time":"2015-07-03T07:16:01+00:00"}
```

### Notes
This happens with the activity and pictures app. It probably can be extended to any app that appears in the navigation manager.

As said before, the app is disabled and removed from the navigator after reloading the page.

**Comment by LukasReschke** [comment] 2015-07-03 07:31
Duplicate of https://github.com/owncloud/core/issues/8361

**Comment by LukasReschke** [comment] 2015-07-03 07:31
(Feel free to assign severity etc. tags to this issue)

**Closed by LukasReschke** 2015-07-03 07:31 UTC
Labels: bug, settings:apps, sev2-high
