### ISSUE TITLE
Activity, favorites menu shows the name of other activities instead of 'favorited'

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26440] opened 2016-10-21 11:24 UTC
### Steps to reproduce

1. Favorite a file
2. Go to Activity page
3. Browse to the favorites menu

### Expected behaviour
File X was favorited message should be shown

### Actual behaviour

Other activities are listed instead of favorited

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** 
"version":"9.1.2.3","versionstring":"9.1.2 RC1"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox.

![screen shot 2016-10-21 at 13 22 07](https://cloud.githubusercontent.com/assets/10596560/19596947/a7a90cbe-9791-11e6-8c61-c9d002979b36.png)

**Comment by PVince81** [comment] 2016-10-24 14:05
Yes, this only shows the activities related to the files you marked as favorite.
Works as intended.

**Closed by PVince81** 2016-10-24 14:05 UTC
Labels: bug, feature:activity, sev4-low
