### ISSUE TITLE
owncloud not refreshing dropbox when new folders etc. added

### ISSUE THREAD

**Issue by nekromoff** [owncloud/core#15060] opened 2015-03-20 11:14 UTC
exactly what happens in issue #377 that has been closed, but it's still an existing bug.
https://github.com/owncloud/core/issues/377

after using console.php full rescan it

**Comment by Xenopathic** [comment] 2015-03-20 11:19
Duplicate of #11797

**Closed by Xenopathic** 2015-03-20 11:19 UTC
