### ISSUE TITLE
In IE11 after owncloud fresh install - list of Files or list of Users are not shown

### ISSUE THREAD

**Issue by romanrajniak** [owncloud/core#25688] opened 2016-08-02 16:47 UTC
### Steps to reproduce
1. Local VM - install and configure Owncloud 9.1.0 using OVA appliance 
2. Connect/login from browser Internet Explorer 11 as default user admin
3. Configure windows client for user admin to new local folder with default files

### Expected behaviour
If first run is in IE 11  _Warn before this temporary issue._

### Actual behaviour
4. Default files shown in local windows folder
5. Default files not shown on web page  Files  .../owncloud/index.php/apps/files   in IE 11
6. Default files shown on web page  Files  .../owncloud/index.php/apps/files   in Firefox
7. Taking long time to test "why" (with login/logout, restarts of VM, adding new file to local folder, searching for hints in help, restarts of IE ) problem was self fixed and also page with Users works/shows all.

### Server configuration
**Operating system**:
Ubuntu 14 - using downloaded appliance  Ubuntu_14.04-owncloud-9.1.0-1.1-201607211103.ova.zip
**Web server:**
(default from appliance)
**Database:**
(default from appliance)
**PHP version:**
(default from appliance)
**ownCloud version:** (see ownCloud admin page)
9.1.0 - (default from appliance)
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**

**The content of config/config.php:**
(default from appliance) - manualy added only ip address for trusted_domains array 
<<--Button to Add this IP in IE 11 does not work - (?new issue?).

**Comment by PVince81** [comment] 2016-10-25 10:47
> Button to Add this IP in IE 11 does not work - (?new issue?).

Since you are using the appliance, it is unlikely that you can reach it through "localhost" and the only way to add trusted domains in the web UI is using "localhost" or do it manually like you did. Not a bug.

**Comment by PVince81** [comment] 2016-10-25 10:50
I can confirm that with IE11 the file list doesn't appear with v9.1.0, the following JS error appears in the console:
```
Unexpected call to method or property access
jquery.min.js, Line: 3, Column: 5682
```

**Comment by PVince81** [comment] 2016-10-25 11:00
v9.1.1 is affected as well but v9.1.2RC1 works properly, file list always appears.

Closing.

**Closed by PVince81** 2016-10-25 11:00 UTC
Labels: browser:ie, bug
