### ISSUE TITLE
LDAP wizard configuration:  Comboboxes info slides over the screen

### ISSUE THREAD

**Issue by davitol** [owncloud/core#16194] opened 2015-05-08 09:21 UTC
### Steps to reproduce

1. Go to LDAP wizard configuration.
2. Spread one combox info. e.g. object classes
3. Scroll down

### Expected behaviour

Info shown should stay together the head of the combobox

### Actual behaviour
The info floats over the screen as it is shown in the image attached

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 1

**Updated from an older ownCloud or fresh install:** fresh install

![flyingcombox](https://cloud.githubusercontent.com/assets/10596560/7533726/434e82d2-f574-11e4-9878-32bcedf60d21.png)

**Comment by davitol** [comment] 2015-05-08 09:21
@jancborchardt

**Comment by jancborchardt** [comment] 2015-05-08 09:36
@blizzz a bug with the dropdown?

**Comment by blizzz** [comment] 2015-05-08 11:36
Yes. Duplicate of https://github.com/owncloud/core/issues/11444

**Closed by blizzz** 2015-05-08 11:36 UTC
Labels: app:user_ldap, bug
