### ISSUE TITLE
Wrong icon for folders in the trashbin menu

### ISSUE THREAD

**Issue by davitol** [owncloud/core#18055] opened 2015-08-04 14:38 UTC
### Steps to reproduce
1. Create a folder
2. Delete the folder
3. Go to deleted files menu

### Expected behaviour
The  icon folder appears  in the trashbin view when a folder has been deleted.

### Actual behaviour
The folder icon is not shown in the trashbin view, instead of it, it appears a rectangle.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:"8.2.0.3","versionstring":"8.2 pre alpha","edition"

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Enabled:
 - activity: 2.0.1
 - admin_audit: 0.6
 - enterprise_key: 0.1.0
 - files: 1.1.10
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_sharing_log: 0.5
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firewall: 0.91.2
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
 - windows_network_drive: 0.1.1

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![trashbin](https://cloud.githubusercontent.com/assets/10596560/9063343/2c6fd78a-3ac7-11e5-8634-76b0d8d1a769.png)

**Comment by PVince81** [comment] 2015-08-04 16:14
Ouch. Are you able to navigate into the folder at least ? If not then it's a more severe issue.

**Comment by davitol** [comment] 2015-08-04 16:32
I can navigate into the folder, it is only an icon problem. I wrote in the description **ownCloud version:"8.2.0.3","versionstring":"8.2 pre alpha","edition" (RC1) but of course it isn't RC1, but master. I will edit it

**Comment by PVince81** [comment] 2015-08-05 08:11
Confirmed. I'll bisect this.

**Comment by PVince81** [comment] 2015-08-05 08:14
Regression introduced through: https://github.com/owncloud/core/pull/17483

@rullzer can you have a look ? Needs some adaptation for the trashbin app.
Thanks!

**Comment by PVince81** [comment] 2015-08-05 08:14
Moved severity to high because it looks bad and might confuse users.

**Comment by rullzer** [comment] 2015-08-05 08:16
I'll have a look tomorrow.

**Comment by rullzer** [comment] 2015-08-05 12:05
PR in #18077

**Comment by rullzer** [comment] 2015-08-06 05:48
PR merged. Should be fixed in master.

**Closed by rullzer** 2015-08-06 05:48 UTC
Labels: app:files_trashbin, bug, regression, sev2-high
