### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

### ISSUE THREAD

**Issue by ecxod** [owncloud/core#18329] opened 2015-08-16 08:24 UTC
I was asked by the upgrading software to tell you this : 

Aktualisiere ownCloud auf Version 8.1.1. Dies könnte eine Weile dauern.
Wartungsmodus eingeschaltet
Datenbankschema-Aktualisierung überprüft
Datenbankschema-Aktualisierung für Apps überprüft
Datenbank aktualisiert
„files“ zu 1.1.10 aktualisiert
„activity“ zu 2.0.1 aktualisiert
„files_sharing“ zu 0.6.2 aktualisiert
„files_trashbin“ zu 0.6.3 aktualisiert
„files_versions“ zu 1.0.6 aktualisiert
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by HotShadow** [comment] 2015-08-16 10:46
Hi there

Same here:

La mise à jour de ownCloud vers la version 8.1.1 est en cours. Cela peut prendre un certain temps.

Mode de maintenance activé
Mise à jour du schéma de la base de données vérifiée
Mise à jour du schéma de la base de données pour les applications vérifiée
Base de données mise à jour
Mise à jour de « files » vers 1.1.10
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
The update was unsuccessful. Please report this issue to the ownCloud community.

ownCloud – services web sous votre contrôle

**Comment by stevleibelt** [comment] 2015-08-16 11:24
Same for me. Updating from version `8.1.0.8`.

```
Updating ownCloud to version 8.1.1, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.
```

**Comment by stevleibelt** [comment] 2015-08-16 11:34
I did a rollback, updated the calendar application/module/component first and gave the update a second try.
Second time, everything was running fine.

**Comment by oparoz** [comment] 2015-08-16 11:44
Can you use ownCloud after you clear your browser's cache?

**Comment by HotShadow** [comment] 2015-08-16 11:54
I relaunched the installation a second time and then it completed successfully. However, the applications I had activated were deactivated (calendar, contacts, gallery/pictures), thank you.

I can connect now and I reactivated the applications.

Now I'm tracking a data corruption error (photos corruption) in the contacts on another thread https://github.com/owncloud/contacts/issues/994.

Greetz

**Comment by stevleibelt** [comment] 2015-08-16 12:08
I've also tried a second round for the update. This time, I updated the calendar application/module/component before.
Everything was running fine so far.

**Comment by MorrisJobke** [comment] 2015-08-16 12:33
Duplicate of #18224

**Closed by MorrisJobke** 2015-08-16 12:33 UTC
Labels: bug
