### ISSUE TITLE
Documentation latest file not found [developer manual]

### ISSUE THREAD

**Issue by thoresuenert** [owncloud/core#28240] opened 2017-06-27 20:43 UTC
Hi,
the documentation link for developer is not working:
[https://doc.owncloud.org/server/latest/developer_manual/](https://doc.owncloud.org/server/latest/developer_manual/) 
[https://doc.owncloud.org/server/latest/ownCloudDeveloperManual.pdf](https://doc.owncloud.org/server/latest/ownCloudDeveloperManual.pdf)
both give 404

**Comment by PVince81** [comment] 2017-06-29 10:06
@settermjd likely duplicate of known infrastructure issue ?

**Comment by cortho** [comment] 2017-06-30 08:36
This has been fixed with https://github.com/owncloud/documentation/issues/3185

**Comment by kdslkdsaldsal** [comment] 2017-07-09 11:18
So closing as this is solved.

**Closed by kdslkdsaldsal** 2017-07-09 11:18 UTC
