### ISSUE TITLE
[Re-Open] Toogle show/hidden system files, temporary, .DS_Store,.... in the web client.

### ISSUE THREAD

**Issue by aqxavier** [owncloud/core#14694] opened 2015-03-04 19:30 UTC
I'm reopening the discussion, because I think it was unclear in which client I am referring to filter hidden files ..

The content filtering on clients (PC / Mac / iOS / Android) I understood, but the web interface (web client) this feature does not exist.

So if I do an SMB directory and this directory there are hidden files like .DS_Store, temporary files of Microsoft Office and even Thumbs if tornão visible in the file list to the Web via the User access (https)

**Comment by jancborchardt** [comment] 2015-03-17 17:02
This is a duplicate of https://github.com/owncloud/core/issues/2589

**Closed by jancborchardt** 2015-03-17 17:02 UTC
Labels: Enhancement
