### ISSUE TITLE
How to change fonts on the main page to be bolder?

### ISSUE THREAD

**Issue by gig13** [owncloud/core#21810] opened 2016-01-20 13:47 UTC
The main page of the ownCloud interface for ownCloud 8.2 is difficult to read and when theming where can I change the fonts to be bolder and easier to read? Something similar to older OC would be better (OC 7 for example).

The Favorites, Shared with you, etc is barely readable. Even the All Files is very thin, maybe a different font altogether?

![fonts](https://cloud.githubusercontent.com/assets/4803385/12450503/2f27c0c2-bf52-11e5-961e-bb535b42ec4e.PNG)

@MorrisJobke @jancborchardt 

The changes from https://github.com/owncloud/core/pull/20176/files don't look to make a significant improvement.

**Comment by jancborchardt** [comment] 2016-01-20 13:56
@gig13 what is the browser and operating system? And are there external monitors being used?

Worst case: We can just supply a short CSS snippet which will change the body font to the Regular style. But maybe we can adjust the core to adapt more to different systems.

**Comment by gig13** [comment] 2016-01-20 14:03
Windows OS mostly --  IE, Chrome, Firefox
some Mac -- Chrome, Safari, Firefox

**Comment by MorrisJobke** [comment] 2016-01-20 15:01
> Windows OS mostly -- IE, Chrome, Firefox
> some Mac -- Chrome, Safari, Firefox

For me the old font size is used on all non-retina screens. Can you provide the screen size and resolution of the display? Maybe we have forgotten something.

**Comment by nickvergessen** [comment] 2016-01-21 10:37
btw which 8.2 version? IIRC we changed the font weight for 8.2.1 or 8.2.2

**Comment by MorrisJobke** [comment] 2016-01-21 13:07
> The changes from https://github.com/owncloud/core/pull/20176/files don't look to make a significant improvement.

They were introduced in 8.2.1 - so this is a 8.2.1 instance that contains the fixes @nickvergessen mentioned?

**Comment by gig13** [comment] 2016-01-21 13:53
8.2.1 server

**Comment by gig13** [comment] 2016-01-22 14:07
@jancborchardt @MorrisJobke 
Any temp css or set of changes to make the change? What files should we review and add to the theme?

**Comment by jsimplicio** [comment] 2016-02-01 17:33
I never recommend using thin weight in small sizes because of how some operating systems/browser render them. When you use regular weight at a sizes like that in the example, it often looks thin enough for most fonts so it should look good. Unless you really absolutely want the thin weight for a good reason, it's not really a safe choice when it comes to readability in all use cases

**Comment by jancborchardt** [comment] 2016-02-08 14:24
@jsimplicio we do have a fallback for certain resolutions which serves the normal font-weight: https://github.com/owncloud/core/blob/master/core/css/fonts.css#L1-L9 and usually this works.

@gig13 the fix for the issue is to basically remove the block mentioning »Open Sans Light« from the fonts.css file: https://github.com/owncloud/core/blob/master/core/css/fonts.css#L11-L16 and then removing the media query around the »Open Sans Regular« block above: https://github.com/owncloud/core/blob/master/core/css/fonts.css#L2
Let me know if there’s further help needed.

**Comment by PVince81** [comment] 2016-03-04 17:43
Is this a bug or a request for help ?

**Comment by gig13** [comment] 2016-03-04 17:51
@PVince81 Several customers have complained about the main page as being to light, not enough contrast and difficult to view. I will label it a bug.

**Comment by PVince81** [comment] 2016-03-04 17:53
@gig13 thanks

**Comment by MorrisJobke** [comment] 2016-04-14 11:42
> @PVince81 Several customers have complained about the main page as being to light, not enough contrast and difficult to view. I will label it a bug.

@owncloud/designers Could we review the design then again please? We have complains, so we should have a look at the overall feedback and maybe change to a slightly thicker font.

**Comment by MorrisJobke** [comment] 2016-04-14 11:42
> @owncloud/designers Could we review the design then again please? We have complains, so we should have a look at the overall feedback and maybe change to a slightly thicker font.

especially @jancborchardt

**Comment by jancborchardt** [comment] 2016-04-15 14:09
@gig13 as always, it would be good to know their configurations. Like screen resolution, operating system, browser. To know if our fallback just fails or if it’s really just bad.

cc @karlitschek

**Comment by PVince81** [comment] 2017-01-13 15:05
@felixheidecke something to consider for the next version's design ?

**Comment by felixheidecke** [comment] 2017-02-01 09:03
Changing the font-weight from "normal" to "bold" drastically changes the over all appearance. Increasing the font size however does not, but boosts readability. I'll provide an adequate design solution.

**Comment by felixheidecke** [comment] 2017-02-03 10:06
Sure, this should be tackled in a overall styleguide wich is still far away. Is there still a need to increase readability as of now? I couldn't really make that out :neutral_face:

**Comment by PVince81** [comment] 2017-02-03 10:09
@cdamken can you check if the need is still there ?

I'm fine closing this for now until we have the style guide.

**Comment by cdamken** [comment] 2017-02-13 12:09
Yes, we can close it.

**Closed by cdamken** 2017-02-13 12:09 UTC
Labels: blue-ticket, bug, design
