### ISSUE TITLE
»a few seconds ago« should be simplified to »seconds ago«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#18627] opened 2015-08-28 14:19 UTC
This is also how it used to be. »seconds ago« is much more concise and doesn’t cause as much overflow, especially with translations. cc @MorrisJobke @owncloud/designers

**Comment by PVince81** [comment] 2015-08-28 14:38
Ah yes, we might need to change/redefine the matching string from the momentjs library.

**Comment by MorrisJobke** [comment] 2015-08-29 11:13
See https://github.com/owncloud/core/pull/18639#issuecomment-135972484

**Comment by jancborchardt** [comment] 2015-09-16 12:04
@MorrisJobke @raghunayyar so, is this fixed in the core method? It will result in pretty long text for the date field, possibly overflow, if it’s not fixed.

**Comment by raghunayyar** [comment] 2015-09-16 15:27
@jancborchardt the issue is open because, the fix I suggested is not the best way to do it. See the discussion on my PR #18639

**Comment by jancborchardt** [comment] 2015-09-16 15:46
I know, I read that. How do we proceed then? This should be fixed for 8.2

**Comment by raghunayyar** [comment] 2015-09-16 15:46
cc @MorrisJobke & @PVince81 , do you want to move with the solution I suggested till then?

**Comment by PVince81** [comment] 2015-09-16 15:48
If this is only for english, a hack could be provided to automatically replace the string...

**Comment by jancborchardt** [comment] 2015-09-16 16:06
That would definitely be an improvement. But the translations should also follow suit. Compare:
* a few seconds ago: German »vor einigen Sekunden«
* seconds ago: German »vor Sekunden«

**Comment by PVince81** [comment] 2015-09-16 16:08
Okay I see, so it looks like we'll need to find a way to provide own translations / override the default translations (which could be taken from the usual transifex)

**Comment by MorrisJobke** [comment] 2015-09-23 09:18
> Okay I see, so it looks like we'll need to find a way to provide own translations / override the default translations (which could be taken from the usual transifex)

Or try to move this upstream.

**Comment by jancborchardt** [comment] 2015-09-23 09:49
@MorrisJobke @PVince81 whichever way you do it, would be really cool if the fix can make it for 8.2 – so be pragmatic please.

**Comment by cmonteroluque** [comment] 2015-10-01 19:58
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by MorrisJobke** [comment] 2015-10-02 08:19
Fix is here #19523

**Closed** 2015-10-02 12:11 UTC
Labels: 3 - To Review, bug, design, junior job, regression
