### ISSUE TITLE
Plz remove "pull right to open menu" function from mobile template

### ISSUE THREAD

**Issue by SunboX** [owncloud/core#17503] opened 2015-07-08 17:15 UTC
On mobiles devices it's very frustrating to scroll (for example) a list of files, because you will constantly open the menu.
Please open the menu only on click on the "hamburger" menu button and remove the "pull right to open" function. That's unnecessary and doesn't help at all.

**Comment by DeepDiver1975** [comment] 2015-07-08 19:33
@jancborchardt

**Comment by jancborchardt** [comment] 2015-07-08 19:59
Duplicate of https://github.com/owncloud/core/issues/11193 – let’s continue there. @zerosine suggested a fix there and someone needs to issue a pull request implementing that.

**Closed by jancborchardt** 2015-07-08 19:59 UTC
