### ISSUE TITLE
Amazon S3 not updating

### ISSUE THREAD

**Issue by dev4press** [owncloud/core#11652] opened 2014-10-18 16:01 UTC
When I added S3 bucket, it was attached and files where added. I removed some files using ownCloud, but S3 was not deleting files. I removed files manually, and I had to delete S3 access keys from ownCloud and add them again, and only than changes were visible.

But now, I have many new files added into bucket, but ownCloud shows only state of bucket from 20 days ago, and it is not seeing any new file in bucket. Removing and adding access keys have no effect.

Only error in the log is this:
```
Fatal | remote | An exception occurred while executing 'SELECT `size` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
```

Regards,
Milan

**Comment by PVince81** [comment] 2015-08-03 13:11
Closing as duplicate of https://github.com/owncloud/core/issues/13507

**Closed by PVince81** 2015-08-03 13:11 UTC
Labels: app:files_external, bug, db:mysql, triage
