### ISSUE TITLE
Sharing with many content -> scrolling broken

### ISSUE THREAD

**Issue by Dennis1993** [owncloud/core#22697] opened 2016-02-28 12:28 UTC
### Steps to reproduce
1. Upload more than 50 Pictures (or other files) into a Folder (e.g. "pics")
2. share the complete Folder by link without Password or so
3. open the share-link an view the files. Now you can't scroll down to see all files

### Expected behaviour
I don't know

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6

**PHP version:**
PHP 7.0.2

**ownCloud version:** (see ownCloud admin page)
8.2.2

**Updated from an older ownCloud or fresh install:**
fresh install

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Page can't be open, Redirect to index.php/apps/files

**List of activated apps:**
No, fresh Installation without apps

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
I don't have access

**Are you using external storage, if yes which one:** local/smb/sftp/...
I don't now, I use a webhoster like strato

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Tested with Firefox (44.0.2)
Tested with IE 11
Tested with Microsoft Edge

**Operating system:**
Windows 10 x64 Pro

#### Web server error log
Where can I find that?

Insert your webserver log here
no access

#### ownCloud log (data/owncloud.log)

1.{"reqId":"VtLhAFUNiQcAAEkeNYMAAADD","remoteAddr":"38.201.225.144","app":"PHP","message":"Undefined index: permissions at \/www\/htdocs\/cust9948\/owncloud\/lib\/private\/files\/fileinfo.php#177","level":3,"time":"2016-02-28T12:58:56+01:00"}

2.{"reqId":"VtLhAFUNiQcAAEkeNYMAAADD","remoteAddr":"38.201.225.144","app":"PHP","message":"Undefined index: permissions at \/www\/htdocs\/cust9948\/owncloud\/lib\/private\/files\/fileinfo.php#177","level":3,"time":"2016-02-28T12:58:56+01:00"}

3.{"reqId":"VtLhAFUNiQcAAEkeNYMAAADD","remoteAddr":"38.201.225.144","app":"PHP","message":"Undefined index: permissions at \/www\/htdocs\/cust9948\/owncloud\/lib\/private\/files\/fileinfo.php#177","level":3,"time":"2016-02-28T12:58:56+01:00"}

**Comment by RealRancor** [comment] 2016-02-28 16:03
Very likely a duplicate of #21373 and #21203 which gets fixed in oC 8.2.3 with owncloud/files_pdfviewer#92

If disabling the files_pdfviewer is not solving this then its a duplicate of https://github.com/owncloud/core/issues/22289, https://github.com/owncloud/core/issues/20044 and https://github.com/owncloud/core/issues/22303 where https://github.com/owncloud/core/issues/20044 is still open.

**Closed** 2016-02-29 08:21 UTC
