### ISSUE TITLE
Sharee API perPage parameter is returning double users as expected when having a LDAP backend setup.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21667] opened 2016-01-12 17:30 UTC
### Steps to reproduce

1. Have many regular users in an owncloud server or create them.
2. Enable LDAP backend with several users.
3. Make a request to the sharee API to get a list of users for sharing using pagination (page 2 is used in the example)

```
curl -X GET "http://ADMINUSER:PASSWORD@HOST/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=search&shareType=0&perPage=3&page=2"

```

### Expected behaviour
3 users are returned.

### Actual behaviour
6 users are returned.

3 regular users and 3 from LDAP.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":"Enterprise"}
(current maste, but seen in 8.2 as well)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
+
LDAP backend.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Comment by SergioBertolinSG** [comment] 2016-01-12 17:30
cc @rullzer

**Comment by rullzer** [comment] 2016-01-12 19:55
@SergioBertolinSG well it is expected that you get both. Since we query both backend.

**Comment by SergioBertolinSG** [comment] 2016-01-13 07:38
I think it should return just 3 users and not differentiate between LDAP and regular users. 

@davivel Is having trouble with this in the android app.

**Comment by rullzer** [comment] 2016-01-13 07:46
Well there is no way to do this properly. We can't filter out all the users that are in LDAP and in the local db. If a user wants to switch to LDAP they should empty their local user db...

I don't see a different (scaleable) solution... @nickvergessen

**Comment by nickvergessen** [comment] 2016-01-13 08:00
This is expected behaviour and can't be changed, since we can't know which set of user's we'd need from which backend.
Mixed backend usage is also only a fantasy use-case, as rullzer already said, local users should be migrated away, the only user that should remain in the user backend is the admin user from installation, to be sure to still have access when the ldap backend breaks.

So closing, because behaviour is expected.

**Closed by nickvergessen** 2016-01-13 08:00 UTC
Labels: bug, sev3-medium

**Comment by davivel** [comment] 2016-01-14 09:40
OK, thanks everybody. Not a deal-breaker for me, just will take it into account for my tests.
