### ISSUE TITLE
SMB_OC not passing domain through to samba share auth

### ISSUE THREAD

**Issue by sammcj** [owncloud/core#13407] opened 2015-01-15 22:12 UTC
smb_oc is passing through the username, but not the domain for the smb shares.
See: https://github.com/owncloud/core/blob/89db2a027701503ea758380b20b10ca7f5a244d9/apps/files_external/lib/smb_oc.php#L40

This causes mapping of external samba shares using domain authentication to fail.

Example of failed login:

```
session setup failed: NT_STATUS_LOGON_FAILURE params(-d 0 '//files.yourdomain.com/shared' -c 'ls') at /var/www/owncloud/apps/files_external/3rdparty/smb4php/smb.php#201
```

This is caused by trying to map the share named 'shared' with username rather than domain\username

hacking smb_oc.php to hard code the domain infront of the username fixes the issue, but obviously this needs to be added into the code properly.

```
        "user" => "mydomain\\$user",
```

My suggestion is to add the option to allow users to specify the domain they wish to prepend to smb users.

I am happy to provide testing if some code is provided?

cc/ @Xenopathic @PVince81

**Comment by Sugaroverdose** [comment] 2015-01-15 22:49
FIY: you can pass domain to smb server using username@domain.name

**Comment by sammcj** [comment] 2015-01-15 22:51
But how do you do that automatically for all users?
Can you just use 'username' and it uses the logged in users username?

-- 
Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod]

**Comment by Sugaroverdose** [comment] 2015-01-15 23:03
Sorry i misunderstood your point, are users mapped using ldap backend?

**Comment by sammcj** [comment] 2015-01-15 23:04
Yes that's correct. It doesn't seem to prepend the (right?) domain for samba mappings.

**Comment by Sugaroverdose** [comment] 2015-01-15 23:35
i just imagined that it would be cool to add checkbox 'use user ldap domain'.
i've configured on my OC8 to use ldap and smb, will try to make pr, at least with domain field

**Comment by Xenopathic** [comment] 2015-01-16 08:51
Odd, I've never needed a domain component to mount SMB shares, I've always done it with the raw username. Still, it's well documented that usernames *can* have that format. I don't think LDAP is the way to go about it (it doesn't have a 'NetBIOS domain' property AFAIK @blizz), but a simple new field in the configuration would do the trick.

**Comment by sammcj** [comment] 2015-01-16 08:54
When you have SAMBA4 and its setup as a fledged AD replacement domain
file server you need the client to pass the domain with the username.

-- 
Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod]

**Comment by Xenopathic** [comment] 2015-01-16 08:56
@sammcj Not for all setups then, I use Samba 4 and don't need the domain component :see_no_evil:

**Comment by sammcj** [comment] 2015-01-16 08:57
Are your users part of a domain, or just locally authenticated?

-- 
Sam McLeod
@s_mcleod[https://twitter.com/s_mcleod]

**Comment by blizz** [comment] 2015-01-17 14:29
Please do not include me in these threads.


Sent from my Verizon Wireless 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Robin McCorkell <notifications@github.com> </div><div>Date:01/16/2015  1:51 AM  (GMT-07:00) </div><div>To: owncloud/core <core@noreply.github.com> </div><div>Cc: blizz <blizzardville@yahoo.com> </div><div>Subject: Re: [core] SMB_OC not passing domain through to samba share auth
  (#13407) </div><div>
</div>Odd, I've never needed a domain component to mount SMB shares, I've always done it with the raw username. Still, it's well documented that usernames can have that format. I don't think LDAP is the way to go about it (it doesn't have a 'NetBIOS domain' property AFAIK @blizz), but a simple new field in the configuration would do the trick.

**Comment by LukasReschke** [comment] 2015-01-17 14:41
@blizzz

**Comment by Sugaroverdose** [comment] 2015-01-18 18:38
@sammcj could you try changes from this https://github.com/Sugaroverdose/core/commit/27ced440435c45f5324295d61fb93d09c704884b commit?

**Comment by abelgomez** [comment] 2015-02-05 17:58
@Xenopathic, @Sugaroverdose is the Sugaroverdose@c438caa patch going to be merged into master? I already needed that feature to connect from a Linux server to a Windows file server. In my case I implemented the feature by myself... but if the work is already done in master would be better :)

Additionally, what's the point of the "Use username as share" option if, if I'm not wrong, using "/$user" as share would do the trick?

**Comment by Sugaroverdose** [comment] 2015-02-05 18:13
i didn't create pr for https://github.com/Sugaroverdose/core/commit/c438caa83fa07ff0ba4229b0f5f651c3c74f3c2c, as i said - i can't test it, if you have same issue and commit solves it - i'll make pr.

**Comment by abelgomez** [comment] 2015-02-05 18:25
I have tested the Sugaroverdose@c438caa commit on a unmodified OC 7.0.4 installation.

I confirm that it works and it also solves my problem.

It would be great if you make PR to integrate it. Thanks!

**Comment by Xenopathic** [comment] 2015-02-05 19:37
@abelgomez Your point about "Use username as share" is a good one - there is little point for it. However, there is currently no intuitive feedback about the placeholders available for the fields.

**Comment by Sugaroverdose** [comment] 2015-02-05 20:26
@Xenopathic smb4php(current backend) parses url by itself, after that, it generates command for smbclient and it does support ';' so my changes shouldn't brake anything :)

**Comment by abelgomez** [comment] 2015-02-05 20:32
Given that the discussion has emerged, please let me give you my opinion:

It's true that there's no intuitive feedback about the placeholders, and they are not even mentioned in the [GUI documentation](http://doc.owncloud.org/server/7.0/admin_manual/configuration/custom_mount_config_gui.html). But, although the doc for the [external storage using a config file](http://doc.owncloud.org/server/7.0/admin_manual/configuration/external_storage_configuration.html) gives some hints, adding the "Username as share" option led me to think that there was no support for placeholders. I even ended up doing my own implementation for placeholders.

Maybe I'm just dumb, but maybe it would be better just to improve the documentation or add some kind of hint in the configuration form.

**Comment by Xenopathic** [comment] 2015-02-05 20:49
@abelgomez That's precisely what I was thinking :smile: I thought about adding a Tipsy (or when the migration happens, a Bootstrap tooltip) to the currently focussed field showing the placeholders it supports.

**Comment by DeepDiver1975** [comment] 2015-08-21 09:13
@icewind1991 I guess this was fixed with the latest update to your smb lib 1.0.4 - right?

**Comment by icewind1991** [comment] 2015-08-23 17:19
probably...

I'm still waiting for someone who has the issue to confirm the fix

**Comment by Xenopathic** [comment] 2015-08-23 22:05
The update of the SMB library won't have affected this, as the problem is getting the domain into the user string in the first place, not actually using it to connect. With SMB_OC, the user string was forced to be the oC username (without any domain), but #18473 allows a user to explicitly set the domain to be used.

**Closed** 2015-09-16 16:17 UTC
Labels: app:files_external, bug, sev2-high, triage
