### ISSUE TITLE
Archive checksum files are in wrong format

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#19516] opened 2015-10-01 17:13 UTC
Our archive checksum files are not in the correct format. For example, the contents of owncloud-8.1.3.tar.bz2.md5:

    6ec33493b7901a56c04af4759d4bedde - 

So when you run the automatic comparison (md5sum -c owncloud-8.1.3.tar.bz2.md5) it fails by hanging until you kill it. A properly-formatted file names the archive:

    6ec33493b7901a56c04af4759d4bedde owncloud-8.1.3.tar.bz2

Then you get a correct result:

    md5sum -c owncloud-8.1.3.tar.bz2.md5
    owncloud-8.1.3.tar.bz2: OK 

Users can make a manual comparison to the hash in the file with md5sum owncloud-8.1.3.tar.bz2. Or pass in the archive filename:

    md5sum -c owncloud-8.1.3.tar.bz2.md5 < owncloud-8.1.3.tar.bz2
    -: OK

Which I am adding to the docs. But as a splendid cutting-edge software, it would be nice to do this the right way :)

**Comment by PVince81** [comment] 2015-10-02 06:16
@karlitschek @jnweiger

**Comment by MorrisJobke** [comment] 2015-10-02 08:48
@cmonteroluque

**Comment by karlitschek** [comment] 2015-10-02 14:58
we had this in the past but removed the filename because of a reason I can't recall at the moment. Something to investigate

**Comment by karlitschek** [comment] 2015-10-02 14:59
not critical imho

**Comment by cmonteroluque** [comment] 2015-10-02 15:02
I agree. Nice to have a workaround but also that it should be fixed... We need to triage 8.1.4 in full after next Tuesday so we'll see if this stays put

**Comment by jnweiger** [comment] 2015-10-02 15:03
I assume that the release process involves some manual renaming of the ZIP and TAR archives after the checksums are generated. This (should not be done, but) would breaks checksum files with filenames in them.

**Comment by karlitschek** [comment] 2015-10-02 15:05
@jnweiger no manual renaming happens

**Comment by karlitschek** [comment] 2015-10-02 15:06
@cmonteroluque Sure. Not sure it is very high on the list of critical topics compared with other issues on github. Minor convenience max imho.

**Comment by carlaschroder** [comment] 2015-10-02 16:57
True, this is far from a showstopper. But someday it really should be fixed :)

**Comment by cmonteroluque** [comment] 2015-12-14 20:40
ok, this should be resolved. Hoping to see the result with the daily builds and the RC1 @carlaschroder @karlitschek

**Comment by karlitschek** [comment] 2015-12-14 20:44
nice :-)

**Comment by carlaschroder** [comment] 2015-12-14 21:15
Yay!

**Comment by cmonteroluque** [comment] 2015-12-16 00:44
confirmed with RC1 packages. Closing...

**Closed by cmonteroluque** 2015-12-16 00:44 UTC
Labels: bug
