### ISSUE TITLE
Upload on shared URL gives js error

### ISSUE THREAD

**Issue by dico** [owncloud/core#20552] opened 2015-11-17 08:39 UTC
When trying to upload file in a shared URL, the developer console shows this error: "Uncaught TypeError: Cannot read property 'fileList' of undefined   file-upload.js?v=576817bd6c97f641d91ed884825e7e92:185 Uncaught TypeError: Cannot read property 'fileList' of undefined".

The error refers to line 185 in file-upload.js, "var fileList = OCA.Files.App.fileList;".

The GUI does not show any feedback at all.

Version: ownCloud 8.2.0 (stable)

**Comment by RealRancor** [comment] 2015-11-17 09:43
Hi,

probably a duplicate of https://github.com/owncloud/core/issues/19922 which gets fixed with the upcoming 8.2.1

**Closed** 2015-11-17 09:52 UTC
