### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry for key 'lock_key_index'

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/core#23073] opened 2016-03-10 09:24 UTC
### Steps to reproduce
1. Add a large file on a desktop client (all desktop clients seem to trigger this), chunking may be key
2. OC starts syncing but fails seemingly by random about once for every 4 files of 100MB each, clients report error failed to sync and the file turns up in "Not Synced"
3. OC starts syncing again, this time usually succeeding and file disappears from "Not Synced"

### Expected behaviour
File is synced on first try.

### Actual behaviour
File sync upload sometimes randomly fails on first try.

### Server configuration
**Operating system:** Ubuntu 14.04 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** Mysql 5.5 on separate host

**PHP version:** PHP 5.5.9-1ubuntu4.14

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** Updated from since 6

**Where did you install ownCloud from:** deb repo

**The content of config/config.php:**
```json
{
    "system": {
        "datadirectory": "\/srv\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "192.168.0.110",
        "dbtableprefix": "oc_",
        "installed": true,
        "instanceid": "oc761iupfq18",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** locally mounted fs on ceph rbd

**Are you using encryption:** not in OC

**Are you using an external user-backend, if yes which one:* no

#### Web server error log
no errors

#### ownCloud log (data/owncloud.log)
```json
{"reqId":"+XdCno45+pUnAyrUzPB6","remoteAddr":"333.333.333.333","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/2c7aa6896caeba794caef99081de1b42\\\", 1, 1457602279, \\\"files\\\\\\\/2c7aa6896caeba794caef99081de1b42\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/2c7aa6896caeba794caef99081de1b42' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(242): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(111): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(156): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/2c7aa6896...', 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(635): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/2c7aa6896...', 1)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(572): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/Books\\\/aud...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(572): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Books\\\/aud...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1803): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Books\\\/aud...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1898): OC\\\\Files\\\\View->lockPath('Books\\\/audio\\\/The...', 1, false)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1196): OC\\\\Files\\\\View->lockFile('Books\\\/audio\\\/The...', 1)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/objecttree.php(148): OC\\\\Files\\\\View->getFileInfo('Books\\\/audio\\\/The...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/lockplugin.php(71): OC\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Books\\\/audio\\\/The...')\\n#15 [internal function]: OC\\\\Connector\\\\Sabre\\\\LockPlugin->getLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#21 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":4,"time":"2016-03-10T08:31:19+00:00"}

{"reqId":"uk39dM4snXrZhgXcP1kC","remoteAddr":"333.333.333.333","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 5210112\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #32)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #32)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('02 The Hobbit 0...', Resource id #32)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Books\\\/audio\\\/The...', Resource id #32, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":361}","level":4,"time":"2016-03-10T08:31:30+00:00"}
```

**Comment by LukasReschke** [comment] 2016-03-10 10:24
Duplicate of https://github.com/owncloud/core/issues/20555

**Closed by LukasReschke** 2016-03-10 10:24 UTC

**Comment by PVince81** [comment] 2016-07-18 10:56
not directly related, but the "duplicate entry" part still likely to happen, potential fix here: https://github.com/owncloud/core/pull/25512
