### ISSUE TITLE
Can we filter activities send to oC active user only from LDAP group.

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/core#15865] opened 2015-04-24 12:57 UTC
#### Expected behavior

LDAP group have some oC active user when they perform activity notification send to all  LDAP group user not only oC active users. 
### Actual behavior

Email notification should sent to  oC user ONLY.
### Steps to reproduce

1)  Create LDAP group called “employee”.
2)  Add the four user on “employee” group.
3)   Our of 4 –LDAP user make 2- active user in oC
4)  Now do some activity between 2-oC user
5)  You will see e-mail notification send all 4 user of “employee” group.

This company not allow to create separate group beside “employee” in LDAP
### Suggestion

It would be possible script at https://github.com/owncloud/core/blob/v7.0.5/apps/user_ldap/group_ldap.php#L441  modification at line # 441
### Server configuration

Operating system: centos 6.6
Web server: Apache 2.2.15
Database:
PHP version: 5.5.20
ownCloud version:7.0.4

**Comment by nickvergessen** [comment] 2015-04-24 13:10
@blizzz

**Comment by blizzz** [comment] 2015-04-24 16:05
@iliyasbasir can provide step by step description on how to reproduce this, please?

**Comment by iliyasbasir** [comment] 2015-04-27 18:02
@blizzz : Re-produced step listed.

**Comment by craigpg** [comment] 2015-04-27 21:07
This is not a top-10 issue so I'm clearing the milestone assignment.

**Comment by nickvergessen** [comment] 2015-04-27 21:23
@craigpg atm we use milestones to track in which oC version something should be fixed ideally. Not whether it's a top 10 issue (what every list on) or not

**Comment by bboule** [comment] 2015-04-28 15:13
Hey Guys... what is the status here?  is this still in line for 7.0.6 if so we can close the case on the front end.

**Comment by iliyasbasir** [comment] 2015-04-29 18:30
@blizzz @nickvergessen @PVince81: Do you have fix for this issue , if not when I can expect this fix will be releasing

**Comment by DeepDiver1975** [comment] 2015-04-29 20:19
> Do you have fix for this issue , if not when I can expect this fix will be releasing

based on the comment history in here there is nothing in the pipe. Details have to be added my @blizzz once he is back.

**Comment by iliyasbasir** [comment] 2015-04-30 15:36
@blizzz  Can you update me on this when you have moment plz

**Comment by DeepDiver1975** [comment] 2015-04-30 16:05
> added by @blizzz once he is back.

@iliyasbasir @blizzz is on a sick leave at the moment - hopefully he will be back next week.

**Comment by blizzz** [comment] 2015-05-05 15:03
>  Now do some activity between 2-oC user

not that precise. I will try, but please be more specific.

Also, what are the sharing and notification settings?

**Comment by iliyasbasir** [comment] 2015-05-06 13:15
@blizzz : can you please tell me where you need me to specify...if you like to have chat we can have Skype call

**Comment by nickvergessen** [comment] 2015-05-06 13:17
@blizzz the settings shouldn't matter too much, just enable all email settings and then share a folder with the user whose emails you want to test. Then upload and delete files in the shared folder.

**Comment by iliyasbasir** [comment] 2015-05-06 14:45
@blizzz : we tested this we noticed that all  activity e-mail send  LDAP group not only oC user; 
we looking for email need to sent oC gorup only inside that LDAP group [LDAP> oC ]

Do you have some time we can set-up skype call b.c look like it's keep rounding and rounding

Thank you

**Comment by blizzz** [comment] 2015-05-06 15:13
@nickvergessen well, that's what i did. Cannot reproduce it for local users (tested just plain file creation and sharing), for LDAP users in the LDAP group no mail is sent. I call cron manually, and when i check $affectedUsers in runStep after this was fetched, it is always empty. Need to investigate further.

**Comment by blizzz** [comment] 2015-05-07 11:22
@nickvergessen it looks like mails are only fired, if a local user is involved. at least i tried with another one, and suddenly everybody who i expected got an email.

@iliyasbasir since everybody who I expected got an email, first I cannot reproduce your issue, and second i would doubt it would have to do with LDAP at all. 

Currently I believe you work with a folder that is shared with a group, in that case of course all members are notified.

**Comment by iliyasbasir** [comment] 2015-05-08 13:30
@blizzz : it is with LDAP , oC user is part of their LDAP group...all oC user carryover  from LDAP no single user created locally.

**Comment by iliyasbasir** [comment] 2015-05-08 13:37
@nickvergessen : we simply looking some feature/code to distinct oC active user inside LDAP group so we can send e-mail notification to only active oC user not all LDAP user in similar group.

**Comment by blizzz** [comment] 2015-05-08 13:43
@iliyasbasir I still have no idea what you are doing. Anyway, please speak to @MTRichards about features.

**Comment by iliyasbasir** [comment] 2015-05-08 19:32
@nickvergessen : can we have phone chat next week i was very clear on my request what customer issue , i'm not clear what part you did not get it in my request,

**Comment by DeepDiver1975** [comment] 2015-05-08 21:07
@iliyasbasir as already explained by @blizzz - you are looking for a new feature (aka something we cannot do as of today).

New features have to be carried to product management. There is no need in talking to the devs - THX

**Comment by nickvergessen** [comment] 2015-05-11 09:11
Other then that, the result has to be fixed on LDAP side, not activity app.

**Comment by bboule** [comment] 2015-05-11 16:13
Sounds like a work around for this would be to NOT pull email address from AD and have the users populate email information in the personal page (the non-active users would never do this) the other option to avoid this is to simply create an AD security group this way you would not need to alter the existing groups, but simply add a security group and make the active OC users a member of that... this would keep the non active users out of the line of fire... seems like two reasonable solutions.

**Comment by iliyasbasir** [comment] 2015-05-11 16:27
1) all user is associated with AD no single user created locally(oC). 2) Company not allow create second group due to their HR system tie  with this group.

**Comment by bboule** [comment] 2015-05-11 20:33
Nothing to do with local users... simply not pulling email from AD so they can do this without issue... Viable work around while we enter a feature request

**Comment by felixboehm** [comment] 2015-11-11 13:19
@bboule please update status, can we remove blue?

**Comment by nickvergessen** [comment] 2015-11-23 13:42
Changed title to "activities" to avoid confusion, because notifications is a different system now.

**Comment by PVince81** [comment] 2017-12-12 13:46
Closing this old issue. To be reopened in user_ldap repo if there is a clear requirement to have activity email splitting.

cc @pmaier1

**Closed by PVince81** 2017-12-12 13:46 UTC
Labels: app:user_ldap, enhancement, feature:activity
