### ISSUE TITLE
OC7 LDAP groups issue

### ISSUE THREAD

**Issue by gig13** [owncloud/core#13180] opened 2015-01-08 18:10 UTC
Referencing history https://github.com/owncloud/core/issues/12532

We have a group used in the login filter to define access and all users are members. It is not in the group filter. We have nested groups turned on and we restrict sharing by group.

User EURO 1, EURO 2 and EURO Leader are all members of group AG100. AG100 is a member of the group EURO. EURO Leader is also a member of the group OwnCloudUnrestrictedGAL (there are a bunch of other members of this group). In the users list EURO Leader's groups list only has that group checked. EURO and AG100 are unchecked. Users EURO 1 and EURO 2 have both AG100 and EURO checked.

In the left column, AG100 shows 3 users, EURO shows 4. Clicking on them shows the same three users (EURO 1, EURO 2 and EURO Leader) so I assume the extra one in the count for EURO is caused by it counting AG100 when it probably shouldn't (counting all members without detecting if those members are users or other object types). It's odd that ownCloud recognizes EURO Leader as being a member of these two groups in the left column but doesn't check the box for those two groups when looking at its groups list.

That's all admin stuff and doesn't really matter, but may help troubleshoot the real issue which is what shows up via auto complete when sharing a file. EURO 1 sees EURO (the group) EURO 2, EURO Leader and AG100. Exactly as expected. Same for EURO 2. EURO Leader can only see the ownCloudUnrestrictedGAL group and the other members of that group. So it seems that the list of checked boxes defines who you can share with.

Adding ownCloudDevRVAUsers (the login filter group) to the group filter changes things significantly. All users correctly show as being members of that group and can therefore share with each other. But they do not have the boxes checked for their other group members. The groups in the left column do show them though when clicked.

So the issue is why is this list not reflecting correctly for all users?

The two groups that trigger this have long names and do not have any child groups. They are also in a different OU. That is the only way in which they are different from the other groups. Even moving them to the same OU and changing the filters accordingly doesn't have anything to do with it. I've created a new group called ocungal to match the ownCloudUnrestrictedGAL group and then removed all users from it. I've removed all the ldap proxy files in /var/tmp restarte apache and memcached and the problem is the same, just with a different group name. So it's just co-incidence that the two groups with problems are the two with long names. If I remove EURO, it doesn't change the check boxes for ocungal. If I remove AG100 then EURO 1 and EURO 2 appear to not be members of any group.

EURO/AG100 are one pair of 9 and the behavior is consistent across all of them.

Environment
RHEL 6
MySQL Percona
Apache

@MorrisJobke

**Comment by gig13** [comment] 2015-01-08 18:11
The owncloud.log is set to log everything and is not showing anything more than the filters that are displayed in the web interface.

**Comment by MorrisJobke** [comment] 2015-01-08 18:15
@blizzz Is this the same problem as the "LDAP user is just in one group in the group dropdown, but counted correctly in all in the group count"?

**Comment by blizzz** [comment] 2015-01-13 12:39
I think it is a duplicate of https://github.com/owncloud/core/issues/12306, which we fixd just recently.

@gig13 can you confirm https://github.com/owncloud/core/pull/13280 solves the issue?

**Comment by scolebrook** [comment] 2015-01-14 19:32
@blizzz @gig13 Thank you so much. Yes, it resolves the issue. The checkboxes are checked as they should be. Now I just need to clean up all these test users and groups after troubleshooting :smile: .

**Comment by blizzz** [comment] 2015-01-15 11:35
@scolebrook thank you for the confirmation!

**Closed by blizzz** 2015-01-15 11:35 UTC
Labels: app:user_ldap, blue-ticket, bug
