### ISSUE TITLE
Client not syncing all directories

### ISSUE THREAD

**Issue by tps800** [owncloud/core#14528] opened 2015-02-26 10:28 UTC
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Install OwnCloud Clients
3. Upload various Directories via OwnCloud Client from Ubuntu to Server
4. Download uploaded Directories via OwnCloud Client from Windows from Server
   most Directories will sync, but some will never show up on Windows
   without any error message or log entry

The directory including pictures is there:
![nc158v3_116_02 - files - owncloud - chromium](https://cloud.githubusercontent.com/assets/702156/6390091/b2cca68c-bda9-11e4-923f-92786b59d9c9.jpg)

But not synced by windows OwnCloud client:
![nc158v3_115_o__lasair_bilder_2015_02](https://cloud.githubusercontent.com/assets/702156/6390086/a4cdb80a-bda9-11e4-9362-b72c4da03f77.jpg)

There is no message/error message within the client log:
```
# grep -i 'Galaball' owncloud.log
#
```

The client was started with
```
"C:\Program Files (x86)\ownCloud\owncloud.exe" --logfile "%USERPROFILE%\Desktop\owncloud.log"
```

The Linux client (Ubuntu 14.04.2 LTS, Client version 1.7.1 installed from repository) syncs to Ubuntu.

### Expected behaviour
All directories on server synced to Windows client if necessary allow
filename translation to match allowed charset for filenames. At least
inform the user about file/directory names not alowed on this operating
system.

### Actual behaviour
Some directories on server not synced to Windows Client

### Client configuration
**Operating system:** Ubuntu 14.04.2 LTS

**OwnCloud Client:** 1.7.1 (build 4382)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 1.7.1 (build 4382)

### Server configuration
**Operating system:** Oracle Linux 6.6

**Web server:** Apache 2.2.15-39.0.1

**Database:** PostgreSQL 9.3.6

**PHP version:** PHP 5.5.21

**ownCloud version:** 8.0.0-23.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_texteditor
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server>.<local>.<domain>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
No entry found regarding "Galaball LuST e.V."
```

#### ownCloud log (data/owncloud.log)
```
No entry found regarding "Galaball LuST e.V."
```

#### Browser log
```
Browser shows directory "Galaball LuST e.V."
```

**Comment by karlitschek** [comment] 2015-02-26 19:51
Can this be a client issue? @dragotin

**Comment by DeepDiver1975** [comment] 2015-02-26 19:58
> Can this be a client issue? @dragotin

No - it's most probably a server issue with shared folders and missing etag propagation.
We have a similar case documented already.

scheduled for 8.1

**Comment by nickvergessen** [comment] 2015-03-02 15:33
If we have a similar case already, we can close this one as duplicate?

**Comment by DeepDiver1975** [comment] 2015-03-16 15:41
@tps800 these folders which are not synced are folders which are shared with the user in question? In this case this would be a duplicate of https://github.com/owncloud/core/issues/14726

**Comment by tps800** [comment] 2015-03-30 15:06
No, these folders are not shared with other users (not all, one is).

**Comment by tps800** [comment] 2015-03-30 15:07
But switching to ownCloud 8.2 seemed to solve the problem.

**Comment by karlitschek** [comment] 2015-05-04 18:31
@tps800 I guess you mean 8.1 or 8.0.2 right?
Closing for now

**Closed by karlitschek** 2015-05-04 18:31 UTC
Labels: bug
