### ISSUE TITLE
fresh installation with strange errors in logfile

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#15992] opened 2015-04-30 20:34 UTC
After a fresh setup of ownCloud I see this messages in the logfile. This shouldn´t happen and gives a bad impression about our code.

--------------------------
Error	PHP	Undefined offset: 0 at /var/www/owncloud/core/lib/private/appframework/http/request.php#683	2015-04-30T20:26:57+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/core/lib/private/appframework/http/request.php#683	2015-04-30T20:26:40+00:00
Error	PHP	touch(): Unable to create file /var/www/owncloud/core/data/owncloud.log because No such file or directory at /var/www/owncloud/core/lib/private/log/owncloud.php#60	2015-04-30T20:25:57+00:00

### Steps to reproduce
Fresh install of master on a fresh ubuntu default box.

### Expected behaviour
nothing in the error log

### Actual behaviour
errors. See above.

### Server configuration
ubuntu 15.04

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
5.6.4

**ownCloud version:** (see ownCloud admin page)
master (April 30th)

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
non. only core.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'occtcs2penar',
  'passwordsalt' => 'CCbZSvrIN2iBNn6ijFLOTKKMObnTG3',
  'secret' => 'sFtOyYdVNIXSimwwXcleItyfI7DW92i7E9D0OfGVXivRL3+O',
  'trusted_domains' =>
  array (
    0 => 'dev',
  ),
  'datadirectory' => '/var/www/owncloud/core/data',
  'overwrite.cli.url' => 'http://dev/owncloud/core',
  'dbtype' => 'sqlite3',
  'version' => '8.1.0.3',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
no

```
run: sqlite3 data/owncloud.db
then execute:  select * from oc_appconfig where appid='user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Chrome

**Operating system:**
OS X, Ubuntu

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
{"reqId":"r74qMdsVF+ZnpTRpvO2s","remoteAddr":"192.168.58.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/core\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-04-30T20:25:57+00:00"}
{"reqId":"r74qMdsVF+ZnpTRpvO2s","remoteAddr":"192.168.58.1","app":"PHP","message":"touch(): Unable to create file \/var\/www\/owncloud\/core\/data\/owncloud.log because No such file or directory at \/var\/www\/owncloud\/core\/lib\/private\/log\/owncloud.php#60","level":3,"time":"2015-04-30T20:25:57+00:00"}
{"reqId":"TJqRYUBCUroaj1o6GgGF","remoteAddr":"192.168.58.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/core\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-04-30T20:26:40+00:00"}
{"reqId":"4S9G4Zz+tvOrd16sIZni","remoteAddr":"192.168.58.1","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/owncloud\/core\/lib\/private\/appframework\/http\/request.php#683","level":3,"time":"2015-04-30T20:26:57+00:00"}
#### Browser log
none

**Comment by karlitschek** [comment] 2015-04-30 20:35
@Raydiation @PVince81  what do you think?

**Comment by Raydiation** [comment] 2015-04-30 21:05
Error happens here https://github.com/owncloud/core/blob/master/lib/private/appframework/http/request.php#L683

Apparently is caused by having no trusted_domains setting in config/config.php which could be because initially there are no trusted domains

@LukasReschke ideas?

**Comment by Raydiation** [comment] 2015-04-30 21:06
@karlitschek is the setting present?

**Comment by karlitschek** [comment] 2015-04-30 21:42
Well the setting is the default that was automatically detected during setup.
'trusted_domains' =>
array (
0 => 'dev',
),

Independently how this is configured, we should never spam the logfile

**Comment by Raydiation** [comment] 2015-05-01 08:51
Tested on PHP 5.6.4, I can only reproduce {"reqId":"onsHOAQTJRTs2YBDf1YB","remoteAddr":"::1","app":"PHP","message":"fopen(\/srv\/http\/owncloud\/config\/config.php): failed to open stream: No such file or directory at \/srv\/http\/owncloud\/lib\/private\/config.php#191","level":3,"time":"2015-05-01T08:49:16+00:00"}

on apache.

**Comment by Raydiation** [comment] 2015-05-01 08:52
Error PHP touch(): Unable to create file /var/www/owncloud/core/data/owncloud.log because No such file or directory at /var/www/owncloud/core/lib/private/log/owncloud.php#60 2015-04-30T20:25:57+00:00

went away when I created a data directory beforehand btw.

**Comment by Raydiation** [comment] 2015-05-01 08:54
Steps I've used:

http is the webserver user and /srv/http the apache directory

    cd /srv/http
    ocdev setup core --dir owncloud
    cd owncloud
    mkdir data
    sudo chown -R http:http data
    sudo chown -R http:http apps
    sudo chown -R http:http config

**Comment by DeepDiver1975** [comment] 2015-05-01 09:36
> Error happens here https://github.com/owncloud/core/blob/master/lib/private/appframework/http/request.php#L683
> 
> Apparently is caused by having no trusted_domains setting in config/config.php which could be because initially there are no trusted domains
> 
> @LukasReschke ideas?

well - at any point in time non-sense could be read from the config file.
Array access always has to be validated in order to prevent such errors.

**Comment by DeepDiver1975** [comment] 2015-05-01 09:42
> Error PHP touch(): Unable to create file /var/www/owncloud/core/data/owncloud.log because No such file or directory at /var/www/owncloud/core/lib/private/log/owncloud.php#60 2015-04-30T20:25:57+00:00

strange - this should not create any error because of @ - https://github.com/owncloud/core/blob/master/lib/private/log/owncloud.php#L60

**Comment by Raydiation** [comment] 2015-05-01 09:53
@DeepDiver1975 indeed, the question is though why this is there in the first place and what implications on security it could have if we swallow it. Depending on the reason it may be better to throw an exception.

**Comment by RealRancor** [comment] 2015-05-01 10:24
Hi,

the touch() error was already reported some time ago at: https://github.com/owncloud/core/issues/12893

**Comment by LukasReschke** [comment] 2015-05-02 19:29
> Array access always has to be validated in order to prevent such errors.

Let me think about the consequences of returning an empty string on `getServerHost` in case of an error. I think it should be safe. Something for next week.

**Comment by karlitschek** [comment] 2015-05-06 20:10
@LukasReschke So what do you think?

**Comment by PVince81** [comment] 2015-06-02 13:13
The "touch()" was raised here https://github.com/owncloud/core/issues/12893
And the 0 one here https://github.com/owncloud/core/issues/16685 (which is different).

Closing this so that each issue can be adressed separately (especially that they have different causes/env/reproduction envs)

**Closed by PVince81** 2015-06-02 13:13 UTC
Labels: bug, sev3-medium
