### ISSUE TITLE
Locally failing unit test related to encryption + s2s

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#14953] opened 2015-03-17 11:22 UTC
It's been weeks that I've been seeing this local unit test fail on master with SQLite:
```
1) OCA\Files_Encryption\Tests\Share::testRemoteShareFile
Exception: Sharing 49 failed, could not find user1@server1, maybe the server is currently unreachable.

/srv/www/htdocs/owncloud/lib/private/share/share.php:739
/srv/www/htdocs/owncloud/lib/public/share.php:236
/srv/www/htdocs/owncloud/apps/files_encryption/tests/share.php:643
```

Is anyone else seeing it too ? @schiesbn ?

**Comment by DeepDiver1975** [comment] 2015-03-17 12:41
no - work here

**Comment by PVince81** [comment] 2015-03-17 13:16
I actually have two computers where it happens, both have a version of PHP 5.6.

This one here (laptop) has openSUSE Factory and php5-5.6.6-1.1.x86_64.

At some point I'll try and debug this then.

**Comment by nickvergessen** [comment] 2015-04-01 08:40
Closing as duplicate of #15326

**Closed by nickvergessen** 2015-04-01 08:40 UTC
Labels: bug
