### ISSUE TITLE
Better file management functionality built-in (web gui)

### ISSUE THREAD

**Issue by BloodyIron** [owncloud/core#25413] opened 2016-07-07 17:23 UTC
I'm on 9.0.3 and a bunch of versions ago one of the apps that I use heavily started breaking things. Another app stopped working too. These apps help me with managing lots of files across folders, but in ways that almost any OS out there already does.

I'm talking about clipboards and moving of files.

The two apps that I was using before, but cannot any more, are:

1. Files Clipboard : https://apps.owncloud.com/content/show.php/files_clipboard?content=167818
2. Files Move : https://apps.owncloud.com/content/show.php/Files+move?content=150271

Files Clipboard doesn't work past 8.2, and has been abandoned, I think.

Files Move breaks Gallery+, and cannot be enabled at this time.

I really would like to see this functionality baked into OC natively, and maybe even make it a lot better than they already are. When I'm dealing with lots of files, these apps have helped me a lot since I have a lot of folders to keep myself organised. I think bringing these in-house will not only increase the quality of these functions, but also increase the general usability of OC to everyone.

**Comment by PVince81** [comment] 2016-07-11 09:03
Related:
- drag move onto breadcrumb: https://github.com/owncloud/core/issues/8570
- https://github.com/owncloud/core/issues/19569

**Comment by PVince81** [comment] 2016-07-11 09:04
okay, closing all as duplicate of https://github.com/owncloud/core/issues/10656

**Closed by PVince81** 2016-07-11 09:04 UTC
Labels: app:files, enhancement

**Comment by BloodyIron** [comment] 2016-07-11 16:25
This may work in some scenarios, but in a lot of scenarios where I have complex folder structures, this doesn't work. PLEASE RE-OPEN.

Consider the following:

I have a folder Photos > Cats > Sphynx. I want to move to folder Photos > Dogs > Charlie

I cannot drag and drop to that folder as the Charlie folder is not visible in the breadcrumb.

I have far more complex folder structures than this example, this just easily demonstrates it.

Please don't just blindly close this ticket without fully understanding how this is distinct from existing functionality.

**Comment by BloodyIron** [comment] 2016-07-11 16:30
Oops, didn't find that ticket when I first looked. I added my thoughts to that one.
