### ISSUE TITLE
Image files uploaded has no preview in root folder. (no problems in sub folders)

### ISSUE THREAD

**Issue by athulrajdr** [owncloud/core#13300] opened 2015-01-13 08:55 UTC
The images in root folder has no preview.
koala.jpg is in root folder.
![1](https://cloud.githubusercontent.com/assets/7678226/5717981/8b6fbffe-9b2e-11e4-8e22-4b04b895a5fb.png)
when it open. there are no preview.
![no prview](https://cloud.githubusercontent.com/assets/7678226/5718002/ad951c82-9b2e-11e4-8001-0d43f58cd6c2.png)
The file is moved to a sub folder "my pics".

![3 preview](https://cloud.githubusercontent.com/assets/7678226/5718123/30233bc4-9b30-11e4-88a0-1b65e77aa4e4.png)
and it hasn't any problem.

"squirrel.jpg" from the folder "photos" (default file) is moved to the root folder, and it hasn't any problem while the preview. while the koala.jpg has also no preview after moving from the "my pics" folder to the root.

**Comment by DeepDiver1975** [comment] 2015-01-13 09:29
@athulrajdr Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by nickvergessen** [comment] 2015-01-13 11:16
Duplicate of #9998 ?

**Comment by athulrajdr** [comment] 2015-01-13 11:25
@nickvergessen i didn't find any issue while the search on the topic.. thanks a lot for your info to get me to the solution.

**Closed** 2015-01-13 11:28 UTC
