### ISSUE TITLE
Permalink to files in subfolders doesn't point to the file.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28106] opened 2017-06-08 12:57 UTC
### Steps to reproduce

1. Create a folder 'FOLDER'. 
2. Upload a file 'file.txt' to 'FOLDER'.
3. Copy permalink of the file (chain icon in the sidebar).
4. Open the copied link in a new window/tab.

### Expected behaviour
It should open 'file.txt' folder, showing it selected. (maybe with the sidebar open? cc @pmaier1 )

### Actual behaviour
It opens the folder 'FOLDER'. The permalink points to that folder. File 'file.txt' is not selected.

This affects mobile development (cc @nasli).

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Firefox

**Logs**
```
```

**Comment by pmaier1** [comment] 2017-06-09 10:54
So the highlighting for private links apparently does not work. This is really bad as it's actually the most important part of the feature.

@felixheidecke please take a look and get this fixed!

**Comment by felixheidecke** [comment] 2017-06-16 09:50
How did this work in the past? Highlighting the file is a nice idea, and of course it will open the folder :-)

**Comment by felixheidecke** [comment] 2017-06-16 09:50
This is **not** a bug!

**Comment by pmaier1** [comment] 2017-06-16 12:27
> How did this work in the past?

The folder opened in the browser and respective file/folder was highlighted. You can try with oC < 10, e.g. our internal instance.

**Comment by felixheidecke** [comment] 2017-06-19 07:47
I see this still works in some cases. Don't know why yet.

**Comment by PVince81** [comment] 2017-06-20 14:09
in this case it's a bug/regression, not enhancement.

**Comment by PVince81** [comment] 2017-08-03 09:51
@felixheidecke any update ? maybe bisecting could help once consistent reproduction was achieved ?

**Comment by PVince81** [comment] 2017-08-07 14:43
moving to "planned" for the next release...

**Comment by PVince81** [comment] 2017-08-10 18:56
moving back... @felixheidecke

**Comment by felixheidecke** [comment] 2017-08-14 10:40
The problem here is the following: The function to scroll to and highlight the file `scrollTo()` and `highlightFiles()` runs before the contents of the subfolder are displayed `getFolderContents()`.

highlighting should be the very last function to run to ensure the file is present within the view. I'm currently looking for a nice way to do that. Lots of code to dig thru tho. :sweat_smile:

**Comment by PVince81** [comment] 2017-08-14 10:47
I wonder if this problem is due to https://github.com/owncloud/core/issues/27890.

A quick hack would be to call `_.defer` for the scroll to happen later...

**Comment by SamuAlfageme** [comment] 2017-09-15 10:29
I'm not seeing this one fixed in 10.0.3 stable w/ firefox/safari

**Comment by PVince81** [comment] 2017-09-15 11:25
there is no 10.0.3 stable, do you mean 10.0.3RC1?

**Comment by PVince81** [comment] 2017-09-15 11:27
Confirmed happening on 10.0.3RC1... maybe some other changes affected this

**Comment by PVince81** [comment] 2017-09-15 11:29
@pmaier1 another known issue

**Comment by PVince81** [comment] 2017-09-15 11:29
I believe it existed in 10.0.2 already, so might not be worth mentioning again in the release notes ?

**Comment by PVince81** [comment] 2017-09-15 11:34
Ok I see... actually @felixheidecke's fix was valid back then because of another bug. Now that said bug is fixed, his fix doesn't work any more. Said bug is https://github.com/owncloud/core/pull/28843.

Fix incoming...

**Comment by PVince81** [comment] 2017-09-15 11:38
Fix is here, I reverted @felixheidecke's workaround and now it works again: https://github.com/owncloud/core/pull/29019

The original issue was that the file list double-loaded, so while the first load would have scrolled, the second load cancelled it, so @felixheidecke catered for that. Now the double load is gone, so the event doesn't fire that late any more.

**Comment by PVince81** [comment] 2017-09-15 11:42
master PR https://github.com/owncloud/core/pull/29020
stable10 https://github.com/owncloud/core/pull/29019

**Closed** 2017-09-18 13:21 UTC
Labels: bug, p2-high, regression, sev3-medium
