### ISSUE TITLE
[7.0.5] Re-sharing of server-server shared files/folders

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#16241] opened 2015-05-11 13:48 UTC
We have one user A that has received files/folders from other ownCloud servers and added them as “server to server” shared files. This works nicely for user A.

user A shares these files & folders with user B in the same organization. User B sees them in the “shared with you” tab, but not in the “all files” tab.

If he tries to open such a folder, the Web UI stays on the spinner for a long time, no files are shown.

Is this the expected behavior or is there something wrong? 

@MorrisJobke 

00003129

**Comment by MorrisJobke** [comment] 2015-05-12 15:02
Definetely a bug.

Error log:

```
{"reqId":"0esVrtVlL6J\/dHPHrCGu","remoteAddr":"127.0.0.1","app":"files_sharing","message":"Unable to get mount for shared storage '3' user 'mjob'","level":3,"time":"2015-05-12T15:00:49+00:00","method":"GET","url":"\/master\/index.php\/apps\/files\/ajax\/list.php?dir=%2FTest&sort=name&sortdirection=asc"}
```

Reproducable on master (both instances). Resharing a received remote share doesn't show up at the reecipient (only in the "Shared with you") but clicking on that entry causes the above error message.

cc @schiesbn @PVince81

**Comment by PVince81** [comment] 2015-05-12 15:12
I thought it would be a duplicate of https://github.com/owncloud/core/issues/15758 which should be fixed on master too.

**Comment by MorrisJobke** [comment] 2015-05-12 16:13
> I thought it would be a duplicate of #15758 which should be fixed on master too.

I tested with master (from one hour ago) and it doesn't work. BTW: it's a re-share of a remote share (as recipient of the remote share)

**Comment by PVince81** [comment] 2015-05-12 16:16
Either it broke again due to other changes or it's another case, settting to 8.1 to investigate.

**Comment by cdamken** [comment] 2015-05-15 11:47
@PVince81 Should this solution solve this situation too?

Same behavior happens with:

1.- Share a file over server to server sharing.
2.- Open the file with the text editor in the second server
3.- Erase/unshare the file from the first server, or broken connection.
4.- Web interface will be freezes.

**Comment by PVince81** [comment] 2015-05-15 11:49
@cdamken this is likely to be a different issue. Is the text editor still open after erasing/unsharing in the original server ? The text editor might not have error detection for such cases.

**Comment by cdamken** [comment] 2015-05-15 11:52
@PVince81  What we are worried about is that similar bugs might be hiding in other viewer apps (pictures, pdf, documents etc.) since apparently the error handling is up to the app in this case and doesn't happen in ownCloud core.

**Comment by PVince81** [comment] 2015-05-15 11:56
Yes, unfortunately it is up to apps to catch such errors, because apps use their own mechanism to read files from the server. Some might still show exceptions though.
I saw that the text editor has a PR to properly display errors: https://github.com/owncloud/files_texteditor/pull/72

**Comment by cdamken** [comment] 2015-05-15 12:51
@PVince81 Thanks! :+1:

**Comment by PVince81** [comment] 2015-05-15 13:10
Confirmed happening on master (e1923bac07305fadb136f80ca098cd9f7e454f22) for both instances.

**Comment by PVince81** [comment] 2015-05-15 13:17
Duplicate of https://github.com/owncloud/core/issues/15116

**Closed by PVince81** 2015-05-15 13:17 UTC
Labels: bug, feature:federated-cloud-sharing, resolves-blue-ticket, sev3-medium, sharing

**Comment by PVince81** [comment] 2015-05-15 13:18
I'll move over the tags
