### ISSUE TITLE
4 byte unicode in comments 

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#24009] opened 2016-04-14 19:01 UTC
We should make sure that we support 3 byte unicode also in comments with databases that only support 3byte like mysql.
For example by an additional manual php encoding step of the affected characters without encoding the complete string. 

@blizzz @PVince81 @cmonteroluque

**Comment by DeepDiver1975** [comment] 2016-04-14 21:11
@dragotin already reported this

**Comment by SergioBertolinSG** [comment] 2016-04-15 07:10
Related: https://github.com/owncloud/core/pull/17978

**Comment by DeepDiver1975** [comment] 2016-04-15 08:03
> we support 3 byte unicode

@karlitschek 4 byte I assume?

**Comment by cmonteroluque** [comment] 2016-04-18 19:20
I presume this is for old versions of MySQL before utf8mb4?

**Comment by DeepDiver1975** [comment] 2016-04-18 19:37
> utf8mb4 support?

we do not support utf8mb4 yet - there are many issues related - see https://github.com/owncloud/core/pull/17978

**Comment by cmonteroluque** [comment] 2016-04-19 11:03
right, I thought the idea was to resolve that for MySQL 5.5 and above, or did I get the point of this issue wrong?

**Comment by DeepDiver1975** [comment] 2016-04-19 11:33
We are facing many issues with mysql regarding 4 bytes ....
- index length are different which has to be addressed by special mysql config options
- some tables are exceeding the max size - we know at least of the activities table

**Comment by nickvergessen** [comment] 2016-04-19 11:47
I tested the following apps, only activity needed a fix for now:
```
  - activity: 2.3.2
  - admin_audit: true
  - announcementcenter: 1.2.0
  - calendar: 1.1
  - comments: 0.3.0
  - dav: 0.2.3
  - encryption: 1.3.0
  - enterprise_key: true
  - federatedfilesharing: 0.2.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: true
  - files_drop: 0.5.0
  - files_external: 0.6.0
  - files_ldap_home: true
  - files_pdfviewer: 0.8
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - mail: 0.4.2
  - notifications: 0.3.0
  - password_policy: true
  - provisioning_api: 0.5.0
  - search_lucene: true
  - sharepoint: true
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - testing: 0.1.0
  - updatenotification: 0.2.0
  - user_ldap: 0.9.0
  - windows_network_drive: 0.2.33
  - workflow: 0.2.2
```

**Comment by DeepDiver1975** [comment] 2016-04-19 11:49
> I tested the following apps, only activity needed a fix for now:

@nickvergessen thanks a lot!

**Comment by PVince81** [comment] 2016-11-03 08:32
Closing as duplicate of https://github.com/owncloud/core/issues/4513

**Closed by PVince81** 2016-11-03 08:32 UTC
Labels: bug, feature:comments
