### ISSUE TITLE
Users Page hanging

### ISSUE THREAD

**Issue by florian0402** [owncloud/core#23834] opened 2016-04-07 10:28 UTC
### Steps to reproduce
1. login as admin
2. go to users page
3. wait for it.

### Expected behaviour
users and gruops should be showed correctly

### Actual behaviour
Chrome, IE, Opera are hanging. Firefox tells me, that there is a not responding script.

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 5.5.x

**ownCloud version:** 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**  it comes up in both cases. With an updated version or a fresh install

**Where did you install ownCloud from:**
manually with tar from website.

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**
```
Enabled:
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- files: 1.4.4
- files_sharing: 0.9.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- templateeditor: 0.1
Disabled:
- activity
- comments
- encryption
- external
- federation
- files_external
- files_pdfviewer
- files_texteditor
- files_videoplayer
- firstrunwizard
- gallery
- notifications
- provisioning_api
- systemtags
- updatenotification
- user_external
- user_ldap
```

**The content of config/config.php:**
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocqgx09lj97t',
  'passwordsalt' => "***REMOVED SENSITIVE VALUE***",
  'secret' => "***REMOVED SENSITIVE VALUE***",
  'trusted_domains' => 
  array (
    0 => 'x.x.x.x',
  ),
  'datadirectory' => '/var/www/data',
  'overwrite.cli.url' => 'http://x.x.x.x',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'something',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

```json
{
    "system": {
        "instanceid": "ocqgx09lj97t",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.x.x.x"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "http:\/\/x.x.x.x",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** 

With access to your command line run e.g.:

### Client configuration
**Browser:** Firefox 45, Chrome 49, and every other

**Operating system:** Windows 7, 8.1 and 10

#### ownCloud log (data/owncloud.log)
empty

#### Browser log
```xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /core/vendor/jquery/jquery-1.10.2.js was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at x.x.x.x Port 80</address>
</body></html>
```

**Comment by nickvergessen** [comment] 2016-04-07 10:33
`core/vendor/jquery/jquery-1.10.2.js was not found on this server` This says enough, right?
Please make sure to upload that file

**Comment by florian0402** [comment] 2016-04-07 11:19
hey Nick. i would, but there is no jquery-1.10.2.js in that folder. i uploaded a screenshot of the jquery folder.

![oc](https://cloud.githubusercontent.com/assets/18326805/14349425/4741d810-fcc3-11e5-9600-f9fbf5111d4e.PNG)

**Comment by critzinger** [comment] 2016-04-15 06:32
i have the same problem.
i have uploaded jquery-1.10.2.js, but the problem was the same.

we have currently over 800 non ldap users. the users are managed internal with owncloud

**Comment by florian0402** [comment] 2016-05-04 13:57
any news? still no comment from the devs :(

**Comment by nickvergessen** [comment] 2016-05-09 06:56
maybe @PVince81

**Comment by PVince81** [comment] 2016-05-09 08:26
@critzinger do you also have a lot of groups ?

Seems this is a duplicate of https://github.com/owncloud/core/issues/9201

**Comment by critzinger** [comment] 2016-05-10 04:37
Yes we also have a lot of groups.
we have about 30 pieces

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Montag, 9. Mai 2016 10:27
An: owncloud/core
Cc: Ritzinger Christian; Mention
Betreff: Re: [owncloud/core] Users Page hanging (#23834)[Avira checked]


@critzinger<https://github.com/critzinger> do you also have a lot of groups ?

Seems this is a duplicate of #9201<https://github.com/owncloud/core/issues/9201>

**Comment by PVince81** [comment] 2016-05-10 06:23
Ok, thanks for the info. Closing as duplicate of https://github.com/owncloud/core/issues/9201

**Closed by PVince81** 2016-05-10 06:23 UTC
Labels: app:user_ldap, comp:core-js, needs info, settings:users
