### ISSUE TITLE
Broken / ugly layout off login page

### ISSUE THREAD

**Issue by arkascha** [owncloud/core#16060] opened 2015-05-05 07:34 UTC
Saw this from 8.0 onwards, still not fixed in 8.0.3: 

the layout (styling) of the login page is broken or at least ugly. Things do not line up horizontally, the login button sticks out at the right side. Looks like the containing fieldset is to wide. Using standard theme / templates. 

I attach a screenshot taken on a chromium browser.

**Comment by arkascha** [comment] 2015-05-05 07:35
![owncloud-login](https://cloud.githubusercontent.com/assets/2156237/7468528/040f7b88-f30a-11e4-9d1a-a42f410ce3e9.png)

**Comment by nickvergessen** [comment] 2015-05-05 07:38
@jancborchardt

**Comment by jancborchardt** [comment] 2015-05-05 09:47
@arkascha Can’t reproduce. I’m gonna need some more info than that. ;)

* Which browser version?
* Does it happen in other browsers too?
* Does it happen only on desktop or on mobile (below 768px width) too?
* Disable all apps. Does it still happen?
* Any JS errors in the console?

cc @owncloud/designers

**Comment by arkascha** [comment] 2015-05-11 11:24
Sorry, took me a while to check, a bit under pressure before my holiday...

 * this does not seem to be app dependent. 
 * this does not appear to be language dependent

It does only appear as shown on three systems of mine, all with this browser: 
chromium 41.0.2272.76 Ubuntu 14.04 (64-bit)
That is the current version offered in the standard repos.

**Comment by jancborchardt** [comment] 2015-05-11 11:44
@arkascha ok – does it also happen with Chrome then? And 2 remaining important questions:
> * Does it happen only on desktop or on mobile (below 768px width) too?
> * Any JS errors in the console?

Thanks!

**Comment by jancborchardt** [comment] 2015-06-11 10:50
Can anyone of you reproduce this @owncloud/designers @aidanamavi @colmoneill? I can not.

**Comment by arkascha** [comment] 2015-06-11 11:41
@jancborchardt  Sorry, didn't see your last comment on May 11 and only came back from holidays abroad...

 * no error in js console, looks more like a static styling issue to be, but I did not really investigate closer
 * can't test chrome, since I have no system running that, only chromium. But there should be enough chrome users to check that...
 * looks fine on mobile (but chrome@android, not chromium)

**Comment by jancborchardt** [comment] 2015-06-11 12:32
@arkascha I don’t want to ignore it – I just can not reproduce it and hence not debug it. ;) If you want to play around a bit with the CSS and can find a way to fix it that would be cool.

**Comment by MorrisJobke** [comment] 2015-06-11 12:34
@arkascha Which version of chromium do you use on what OS?

**Comment by arkascha** [comment] 2015-06-11 12:44
@MorrisJobke As written above on May11: chromium 41.0.2272.76 Ubuntu 14.04 (64-bit)

@jancborchardt You mean you also cannot reproduce it using chromium on a ubuntu X86_64? Hm...

And sorry, don't expect a fix or hint from my side, I simply do not want to promise something where it is unlikely that I will find time to really take a look at, since I am not really using owncloud any more... (this is meant as a transparency statement)

**Comment by MorrisJobke** [comment] 2015-06-11 13:02
> @MorrisJobke As written above on May11: chromium 41.0.2272.76 Ubuntu 14.04 (64-bit)

:see_no_evil: Sorry ... I didn't read this :(

**Comment by colmoneill** [comment] 2015-06-11 14:41
Can't reproduce this either, but I'm noticing that the 'remember' checkbox is missing from this screenshot, could that have anything to do with it?

**Comment by jancborchardt** [comment] 2015-06-11 15:24
@colmoneill the »remember me« checkbox is missing when an app such as external storage is activated. I think for security reasons or whatnot we can’t remember the session.

If no one can reproduce this, I will close this issue. We need more info to fix it.

**Closed by jancborchardt** 2015-06-11 15:24 UTC
Labels: browser:chrome, bug, design, needs info
