### ISSUE TITLE
Text preview (icon and sidebar picture) doesn't change when a file is modified by sharee.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#19531] opened 2015-10-02 11:19 UTC
### Steps to reproduce
1. Create a text file as 'admin'.
2. Share it with 'user2' with edit privileges.
3. Using 'user2' edit the file and change all the content (first lines specially).
4. Login with 'admin' and see the preview.
### Expected behaviour

Preview changes, since text of the file is different.
### Actual behaviour

Preview doesn't change. But the file is modified, which is confusing.
### Server configuration

**Operating system**:
Cent OS 6.6

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
Using enterprise theme.
{"installed":true,"maintenance":false,"version":"8.2.0.6","versionstring":"8.2 beta1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Default in enterprise edition.
+
External storage

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, S3, SMB and Dropbox, but not related with test.

**Are you using encryption:** 
No

**Comment by PVince81** [comment] 2015-10-05 08:40
I'm pretty sure I saw a duplicate of this a while ago but somehow cannot find it any more.

@georgehrke

**Comment by PVince81** [comment] 2016-06-14 11:34
Still happening on 9.1.0beta2. Admin still sees the old preview.

**Comment by PVince81** [comment] 2017-12-12 13:11
Please reopen if issue persists with 10.0.4

**Closed by PVince81** 2017-12-12 13:11 UTC
Labels: bug, feature:sharing, sev4-low
