### ISSUE TITLE
Copying files between external folders located in same place deletes them.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#21968] opened 2016-01-28 09:18 UTC
### Steps to reproduce

As admin user:
1. Enable external storage.
2. Mount a system wide SFTP folder called SFTPsystem. Allow users to mount personal points.
3. Mount a personal wide SFTP folder called SFTPpersonal connecting to the same folder as SFTPsystem .
4. Using cadaver(webdav client) copy a file from  SFTPsystem to SFTPpersonal.
    `
    cp SFTPsystem/file.txt SFTPpersonal
`
### Expected behaviour

Nothing happens as both folders are in the same place.
### Actual behaviour

file.txt is removed.
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.0.0.6","versionstring":"9.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes SFTP.

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**
Chrome

**webdav client**
Cadaver

**Comment by PVince81** [comment] 2016-01-28 17:10
Ouch... That's probably because the code that does the copy first deletes the target before doing the copy.

@SergioBertolinSG does it happen for any storages ? I think that logic is in the Webdav code. We might need to add a check whether the COPY or MOVE is being done on exactly the same file...

**Comment by SergioBertolinSG** [comment] 2016-01-29 08:52
Yes, it is general. sev1 because of data loss? or this is a corner case?

**Comment by PVince81** [comment] 2016-01-29 10:34
Not sure. This shouldn't happen in a regular situation.

How do other Webdav clients behave when copying a file onto itself ?
I'll at least raise to high

**Comment by SergioBertolinSG** [comment] 2016-01-29 11:10
OS X's Finder tries to copy, fails gets confused, you need to stop it and the file is removed finally.

**Comment by PVince81** [comment] 2016-02-11 14:33
Hmmm, wait. I thought you were copying into the same storage.

But actually you are copying from storage A to storage B, but both happen to be pointing at the same remote storage. This is very tricky, because ownCloud cannot easily tell that these are the same storage.

The only thing we could try to do is use part files when copying files. So instead of first deleting the target, copy the file to the target storage as part file and then rename it to the final file.

@icewind1991 what do you think ? Similar idea like https://github.com/owncloud/core/issues/13379

**Comment by icewind1991** [comment] 2016-02-12 13:30
part files for cross-storage copy/move seems the only way to handle this correctly

do we want that for 9.0?

**Comment by PVince81** [comment] 2016-02-12 13:31
Considering that the described env/situation is rather a corner case, and the changes are slightly risky, I'd rather say 9.1.

@cmonteroluque

**Comment by cmonteroluque** [comment] 2016-02-16 15:31
woud 9.0.1 make sense instead? @PVince81 @icewind1991

**Comment by PVince81** [comment] 2016-02-23 10:09
This would be a bigger change of behavior because we never used part files for move/copy operations, so it needs to be thought through properly to avoid potential regressions.

I can set it to 9.0.1 to evaluate the risk.

**Comment by PVince81** [comment] 2016-03-09 18:06
Let's see if there is a quickfix for 9.0.1. I don't want to risk changing the move/copy code logic for such a small corner case.

**Comment by PVince81** [comment] 2016-11-30 10:40
I remember looking into this and not seeing a possible quickfix.

Also, I think configuring two ext storages pointing to the exact same remote storage with same credentials isn't really a use case as the receiving user would have the same storage twice.

Downgrading to medium

**Comment by PVince81** [comment] 2017-04-06 16:18
backlog for now, very uncommon "use case"

**Comment by SergioBertolinSG** [comment] 2017-04-07 07:19
Well I don't think this is a use case at all, it is more an accidental situation that would lead to deletions. Someone could make that configuration mistake.

**Comment by PVince81** [comment] 2017-12-12 15:32
Corner case, and also only possible with special client. Won't fix.

**Closed by PVince81** 2017-12-12 15:32 UTC
Labels: app:files_external, bug, sev3-medium
