### ISSUE TITLE
Update kills the instance

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24871] opened 2016-05-27 11:32 UTC
### Steps to reproduce
1. Prepare the instance
2. Update with daily channel
3. Wait to suceed

### Expected behaviour
Update should pass

### Actual behaviour
Update makes the instance unusable. Tried to manually upgrade with the upgrade command respectively with the browser without any success. I needed to revert to a backuped instance folder.
When the updater screen showed the error message (see below), I looked to the owncloud root directory and saw, that the occ command file was not set to executable. I highly believe, that this could be one of the root causes.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.14

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

**Updated from an older ownCloud or fresh install:**
This was a fresh setup from tar and updated once, daily channel

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.
Sie können zur Rückkehr zu ownCloud hier klicken.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### owncloud.log
This was the output when I tried to update via the browser again not from the updater app, but I was (re)directed to the main screen (like login)
```
{"reqId":"mKxkr7WmzXkqUDdGDAey","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"files can't be disabled.\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(407): OC\\\\App\\\\AppManager->disableApp('files')\\
n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(405): OC_App::disable('files')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(250): OC\\\\Updater->checkAppsRequirements()\\
n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.1.0.5', '9.1.0.5')\\
n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/Upgrade.php(290): OC\\\\Updater->upgrade()\\
n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\
n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\
n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\
n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\
n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(145):Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\
n#10 \\\/var\\\/www\\\/owncloud\\\/console.php(94): OC\\\\Console\\\\Application->run()\\
n#11 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/w...')\\
n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":256}","level":3,"time":"2016-05-27T12:01:44+02:00","method":"--","url":"--","user":"--"}
```
#### Updater Screen
```
Updating apps
Upgrading the application activity


   
  [Symfony\Component\Process\Exception\ProcessFailedException]  
  The command "php /mnt/mm-eddie/www/owncloud/occ --no-warnings upgrade" failed.  
  Exit Code: 5(Unknown error)  
  Output:  
  ================  
  Set log level to debug  
  Turned on maintenance mode  
  Checking whether the database schema can be updated (this can take a long time depending on the database size)  
  Checked database schema update  
  Checking updates of apps  
  Checking whether the database schema for   <activity>   can be updated (this can take a long time depending on the database size)  
  Checked database schema update for apps  
  Updating database schema  
  Updated database  
  Exception: files can't be disabled.  
  Update failed  
  Maintenance mode is kept active  
  Reset log level  
  Error Output:  
  ================  
   [1A oc_appconfig  
  0/24 [>---------------------------] 0%  
   [1A oc_appconfig  
  1/24 [=>--------------------------] 4%  
   [1A oc_storages  
  2/24 [==>-------------------------] 8%  
   [1A oc_mounts  
  3/24 [===>------------------------] 12%  
   [1A oc_mimetypes  
  4/24 [====>-----------------------] 16%  
   [1A oc_filecache  
  5/24 [=====>----------------------] 20%  
   [1A oc_group_user  
  6/24 [=======>--------------------] 25%  
   [1A oc_group_admin  
  7/24 [========>-------------------] 29%  
   [1A oc_groups  
  8/24 [=========>------------------] 33%  
   [1A oc_preferences  
  9/24 [==========>-----------------] 37%  
   [1A oc_properties  
  10/24 [===========>----------------] 41%  
   [1A oc_share  
  11/24 [============>---------------] 45%  
   [1A oc_jobs  
  12/24 [==============>-------------] 50%  
   [1A oc_users  
  13/24 [===============>------------] 54%  
   [1A oc_authtoken  
  14/24 [================>-----------] 58%  
   [1A oc_vcategory  
  15/24 [=================>----------] 62%  
   [1A oc_vcategory_to_object  
  16/24 [==================>---------] 66%  
   [1A oc_systemtag  
  17/24 [===================>--------] 70%  
   [1A oc_systemtag_object_mapping  
  18/24 [=====================>------] 75%  
   [1A oc_systemtag_group  
  19/24 [======================>-----] 79%  
   [1A oc_privatedata  
  20/24 [=======================>----] 83%  
   [1A oc_file_locks  
  21/24 [========================>---] 87%  
   [1A oc_comments  
  22/24 [=========================>--] 91%  
   [1A oc_comments_read_markers  
  23/24 [==========================>-] 95%  
   [1A oc_credentials  
  24/24 [============================] 100% [1A oc_activity  
  0/2 [>---------------------------] 0%  
   [1A oc_activity  
  1/2 [==============>-------------] 50%  
   [1A oc_activity_mq  
  2/2 [============================] 100%  
```
#### Update via Browser
```
Aktualisierung auf 9.1.0 beta 1

Exception: files can't be disabled.
Detaillierte Fehlermeldungen 
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die ownCloud Community.
```

**Comment by mmattel** [comment] 2016-05-27 16:26
Because I kept the copy of the dead instance and was able to dive into deeper, here are more details:

**From the owncloud.log**
```
{"reqId":"zHrraNfkft66ZFf8D+Gh","remoteAddr":" xx.xx.xx.xx ","app":"core","message":"starting upgrade from 9.0.2.0 to 9.1.0.5","level":0,"time":"2016-05-27T11:50:27+02:00","method":"--","url":"--","user":"--"}

{"reqId":"pDCh2IBhyOUTmDC40XjM","remoteAddr":" xx.xx.xx.xx ","app":"PHP","message":"Argument 1 passed to OC\\Updater::__construct() must implement interface OCP\\IConfig, instance of OC\\HTTPHelper given, called in \/var\/www\/owncloud\/apps\/updatenotification\/appinfo\/app.php on line 27 and defined at \/var\/www\/owncloud\/lib\/private\/Updater.php#83","level":3,"time":"2016-05-27T11:50:52+02:00","method":"--","url":"--","user":"--"}

{"reqId":"pDCh2IBhyOUTmDC40XjM","remoteAddr":" xx.xx.xx.xx ","app":"PHP","message":"Argument 2 passed to OC\\Updater::__construct() must be an instance of OC\\IntegrityCheck\\Checker, instance of OC\\AllConfig given, called in \/var\/www\/owncloud\/apps\/updatenotification\/appinfo\/app.php on line 27 and defined at \/var\/www\/owncloud\/lib\/private\/Updater.php#84","level":3,"time":"2016-05-27T11:50:52+02:00","method":"--","url":"--","user":"--"}

{"reqId":"pDCh2IBhyOUTmDC40XjM","remoteAddr":" xx.xx.xx.xx ","app":"PHP","message":"Argument 3 passed to OC\\Updater::__construct() must implement interface OCP\\ILogger, instance of OC\\IntegrityCheck\\Checker given, called in \/var\/www\/owncloud\/apps\/updatenotification\/appinfo\/app.php on line 27 and defined at \/var\/www\/owncloud\/lib\/private\/Updater.php#85","level":3,"time":"2016-05-27T11:50:52+02:00","method":"--","url":"--","user":"--"}
```

**Comment by saphirblanc** [comment] 2016-05-28 15:17
Exactly the same issue from my side when I try to update to 9.1.0 beta 1 (switched to daily channel and tried to update from Stable 9). Tried with the command line and via WebGUI.
```
sudo -u www-data ./occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                     
 24/24 [============================] 100%
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
 Done                                     
 2/2 [============================] 100%  
Checked database schema update for apps
Updating database schema
Updated database
Exception: files can't be disabled.
Update failed
Maintenance mode is kept active
Reset log level
```

**Comment by PVince81** [comment] 2016-05-30 09:47
@VicDeo please have a look

**Comment by VicDeo** [comment] 2016-05-30 09:52
Duplicate of https://github.com/owncloud/updater/issues/336
Fixed in master/stable9

**Comment by mmattel** [comment] 2016-05-30 10:37
@VicDeo sorry if this sounds stupid, but my current instance is running in production and I have to take care of it... What steps exactly should I do? Do you mean I should do a git clone of eg apps ? What to do with the git related files when cloning (if)?

**Comment by mmattel** [comment] 2016-05-30 13:11
All: the procedure described by @VicDeo  leads to errors.
What I did:
- Moving folders Updater/ and apps/ to a location outside owncloud
- Inside owncloud ``sudo git clone https://github.com/owncloud/updater.git`` same with apps.git
- Setting the correct permissions to update
- Try to enter the webpage of the instance

The page stays blank, no update possible.

**Here are the webserver (nginx) site error logs:**
```
2016/05/30 14:40:20 [error] 15237#15237: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/
phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 138
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/remote.php:0" while reading response header from upstream, client: yy.yy.yy.yy, server: xxx, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"

2016/05/30 14:40:39 [error] 15237#15237: *15 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OCA\Files_Sharing\API\Server2Server' not found in var/www/owncloud/ocs/routes.php on line 102
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/index.php:0
PHP message: PHP   2. OC::handleRequest() /var/www/owncloud/index.php:39
PHP message: PHP   3. OC::checkMaintenanceMode() /var/www/owncloud/lib/base.php:839
PHP message: PHP   4. OC\Template\Base->printPage() /var/www/owncloud/lib/base.php:310
PHP message: PHP   5. OC_Template->fetchPage() /var/www/owncloud/lib/private/template/base.php:122
PHP message: PHP   6. OC\TemplateLayout->__construct() /var/www/owncloud/lib/private/template.php:225
PHP message: PHP   7. OC\URLGenerator->linkToRoute() /var/www/owncloud/lib/private/templatelayout.php:141
PHP message: PHP   8. OC\Route\CachingRouter->generate() /var/www/owncloud/lib/private/urlgenerator.php:66
PHP message: PHP   9. OC\Route\Router->generate() /var/www/owncloud/lib/private/route/cachingrouter.php:56
PHP message: PHP  10. OC\Route\Router->loadRoutes() /var/www/owncloud/lib/private/route/router.php:310
PHP message: PHP  11. require_once() /var/www/owncloud/lib/private/route/router.php:159" while reading response header from upstream, client: yy.yy.yy.yy, server: xxx, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"

2016/05/30 14:40:52 [error] 15237#15237: *18 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/
phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 138
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/remote.php:0" while reading response header from upstream, client: yy.yy.yy.yy, server: xxx, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"

2016/05/30 14:41:24 [error] 15237#15237: *22 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require_once(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/
phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') in /var/www/owncloud/remote.php on line 138
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /var/www/owncloud/remote.php:0" while reading response header from upstream, client: yy.yy.yy.yy, server: xxx, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxx"
```

**Here is the owncloud.log:**
```
Error	PHP	require_once(/appinfo/v1/webdav.php): failed to open stream: No such file or directory at /var/www/owncloud/remote.php#138	2016-05-30T14:40:52+02:00
Error	PHP	Class 'OCA\Files_Sharing\API\Server2Server' not found at /var/www/owncloud/ocs/routes.php#102	2016-05-30T14:40:39+02:00
Error	PHP	require_once(): Failed opening required '/appinfo/v1/webdav.php' (include_path='/var/www/owncloud/3rdparty/pear/console_getopt:/var/www/owncloud/3rdparty/pear/pear_exception:/var/www/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/owncloud/3rdparty/pear/archive_tar:/var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/owncloud/lib/private:/var/www/owncloud/config:/var/www/owncloud/3rdparty:/var/www/owncloud/apps:.:/usr/share/php:/usr/share/pear:/var/www/owncloud') at /var/www/owncloud/remote.php#138	2016-05-30T14:40:20+02:00
Error	PHP	require_once(/appinfo/v1/webdav.php): failed to open stream: No such file or directory at /var/www/owncloud/remote.php#138	2016-05-30T14:40:20+02:00

```

I would really appreciate a fix / procedure for this mess.

BTW: restoring apps/ and updater/ from the saved location made the instance working again :disappointed_relieved:

**Comment by VicDeo** [comment] 2016-05-30 13:13
@mmattel daily channel (and even beta) is not suitable for production

**Comment by mmattel** [comment] 2016-05-30 13:16
This is principly correct, but it highlights a serious issue which has to be resolved.

**Comment by VicDeo** [comment] 2016-05-30 13:20
@mmattel 
(the instructions below are valid for `daily` channel only, for other channels `100.0.0.0` will be different )
update is stalled in the state when there is a downloaded package `100.0.0.0.zip` under `data/updater-data/download/`
it is extracted into `data/updater-data/download/100.0.0.0/owncloud` 

what you need to do is to either extract `100.0.0.0.zip` anywhere and place `apps` from it instead of your owncloud `apps` dir 
or use already extracted `data/updater-data/download/100.0.0.0/owncloud/apps`

**Comment by mmattel** [comment] 2016-05-30 13:37
- When I restored the instance some days ago after the failing update, all downloaded zips have been reset also. There is no actual zip file, only the last old one which succeeded.
- Where to download the actual zip file?
- You also mentioned the updater/ folder, but not in your description directly above...

**Comment by VicDeo** [comment] 2016-05-30 13:48
@mmattel as soon as your initial updater is dated 2016-04-28 it should download packages for update into 
`/path_to_owncloud_datadir/updater-data/download/`
and extract them into
`/path_to_owncloud_datadir/updater-data/download/_oc_upgrade/100.0.0.0/owncloud`

**Comment by VicDeo** [comment] 2016-05-30 15:46
Correct sequence right after the failure:
1. look into `/Path_to_owncloud_datadir/updater-data/download/_oc_upgrade/Version_you_are_trying_to_update_to/owncloud/`
2. Find some directories here that were not moved properly (`apps` and `updater` in your case)
3. Move directories that called in the same way out of your OC instance
4. Put directories from step 2 into your OC instance
5. Open your OC webroot or execute `php occ upgrade` from shell

**Comment by mmattel** [comment] 2016-05-30 15:48
OK, here is the procedure I did and was successful with (one thing is missing, but later)

- Download with ``sudo wget https://download.owncloud.org/community/owncloud-daily-master.zip`` the latest daily build
- Rename the current instance folder to owncloud.x
- Extract the daily build to the webservers root for owncloud, because this contains all files and folders necessary in the latest daily build state
- Copy from owncloud.x the config, .user.ini and the data directory
- Run the shell script to first initialize rights and ownership
- Run the pre shell script to prepare the upgrade
- Run ``sudo -uwww-data ./occ upgrade``
- Run the post shell script to finalize the upgrade

Logon via the browser works and the version shown is now ownCloud 9.1.0 beta 1 (daily) Build:2016-05-30T03:09:20+00:00 c870e7754696d179a9ba8f84a1c1379e5ad1a274

The error I get logged is:
```
Error	files_external	Could not load storage: "Unable to get backend for smb"	2016-05-30T17:44:43+02:00
```

Will dive deeper into what the root cause could be

**Comment by PVince81** [comment] 2016-06-14 07:48
@mmattel so is this still an issue ? (the update part)

**Comment by PVince81** [comment] 2016-06-23 12:44
Please reopen if you still have issues with update with the latest dailies

**Closed by PVince81** 2016-06-23 12:44 UTC
Labels: bug, feature:update, sev2-high
