### ISSUE TITLE
Owncloud stable upgrade error (8.1.3-13.1) over (8.1.1-1)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19102] opened 2015-09-16 18:18 UTC
### Steps to reproduce
1. Installed Owncloud version 8.1.1-1 stable
2. sudo apt-get update // upgrade

### Expected behaviour
Finishing upgrade without problems

### Actual behaviour
Upgrade error at the console

### Server configuration
**Operating system**: Ubuntu 14.04
**Web server:** nginx 1.9.4
**Database:** mysql 5.5.44
**PHP version:** 5.5.9

**ownCloud version:** base version: 8.1.1-1 stable
**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** 
pls see comment at the end

**The content of config/config.php:**

```
  'logtimezone' => 'Europe/Vienna',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'assetdirectory' => '/xxx',
  'asset-pipeline.enabled' => true,
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF',
    15 => 'OC\\Preview\\Raw',
  ),
  'theme' => '',
  'maintenance' => false,
```

**Are you using external storage, if yes which one:** local/smb/
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

#### console message
```
Preparing to unpack .../owncloud-server_8.1.3-13.1_all.deb ...
owncloud-server: occ maintenance:mode --on
PHP Notice:  Undefined index: SERVER_PROTOCOL in /xxx/lib/private/response.php on line 77
PHP Stack trace:
PHP   1. {main}() /xxx/occ:0
PHP   2. require_once() /xxx/occ:11
PHP   3. require_once() /xxx/console.php:41
PHP   4. OC::init() /xxx/lib/base.php:1121
PHP   5. OC_Response::setStatus() /xxx/lib/base.php:533
3rdparty directory not found! Please put the ownCloud 3rdparty folder in the ownCloud folder or the folder above. You can also configure the location in the config.php file.Unpacking owncloud-server (8.1.3-13.1) over (8.1.1-1) ...
Setting up owncloud-server (8.1.3-13.1) ...
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)
owncloud-server: occ upgrade
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)
Setting up owncloud-config-apache (8.1.3-13.1) ...
Setting up owncloud (8.1.3-13.1) ...
```
#### ownCloud log (data/owncloud.log)
```
Error		core	Could not get application: cURL error 28: Resolving timed out after 5517 milliseconds	2015-09-16T19:44:15+02:00
Fatal	index	Exception: "Exception":"OC\\NeedsUpdateException","Message":"","Code":0,"Trace":"
#0 \/xxx\/lib\/private\/app.php(98): OC_App::loadApp('activity')\
n#1 \/xxx\/lib\/private\/util.php(127): OC_App::loadApps(Array)\
n#2 \/xxx\/lib\/base.php(873): OC_Util::setupFS()\
n#3 \/xxx\/index.php(40): OC::handleRequest()\
n#4 {main}","File":"\/xxx\/lib\/private\/app.php","Line":118}
```

### Additional Info
The upgrade worked, when I accessed the the instance with the browser, maintanance mode was shown and sucessully finished. I had to manually reenable galleryplus (but gapperyplus does not show any pictures at all, even present...)

When I tried to run a occ command, I get the following
```
sudo -u www-data php occ config:list system
An unhandled exception has been thrown:
OC\HintException: [0]: Missing memcache class \OC\Memcache\APCu for local cache (Is the matching PHP module installed and enabled ?)
```
To be noted, I have on the same server a test instance which is a clone from git with the same config  and here the occ command works = not a problem of the server...

**Comment by karlitschek** [comment] 2015-09-16 18:24
@jnweiger

**Comment by janhenke** [comment] 2015-09-16 18:24
This is most likely caused by a partial update pushed to the mirrors. Only ```owncloud```, ```owncloud-server``` and ```owncloud-config-apache``` have been published in version 8.1.3-13.1, while the rest of the packages is still only on 8.1.1-1. Due to the versioned dependencies, this prevents apt from installing all required packages.

This really is a bug in the release process. You must never publish a partial update like this on the mirrors. If not all packages are build, you must hold back the rest until everything is available at the same time. Please fix this. @davitol

**Comment by mmattel** [comment] 2015-09-16 18:49
Because this is the stable release, the impact is critical.
occ does not work anymore after the upgrade which is imho a no-go for production evironments...

**Comment by RealRancor** [comment] 2015-09-16 20:58
There are no packages missing here. Those where just merged together according to @jnweiger. That is also described here: http://owncloud.10557.n7.nabble.com/Upgrading-from-8-1-1-to-8-1-3-on-Debian-Jessie-x86-64-tp15802p15804

**Comment by janhenke** [comment] 2015-09-17 07:34
@RealRancor the link you provided leads to a 404.

The fact this issue exists is a clear sign the change in packaging was not communicated enough. A minor version update that removes a number of existing packages is always suspicious in breaking existing installations. It would have been much better to keep the additional packages (with no content) and remove the only on the next major version bump (where such a large change can be expected).

**Comment by RealRancor** [comment] 2015-09-17 07:42
@janhenke See: http://owncloud.10557.n7.nabble.com/Upgrading-from-8-1-1-to-8-1-3-on-Debian-Jessie-x86-64-tp15802p15804.html

The message itself posted by @mmattel are not related to this packaging problem itself. From my PoV just create a new issue to discuss this with the packager.

**Comment by jnweiger** [comment] 2015-09-17 09:04
@mmattel Can you log in to that system? If possible please show us the output of
ls -la /xxx/
ls -la /xxx/core/
ls -la /xxx/lib/
ls -la /var/www
ls -la /var/www/owncloud
dpkg -l | grep owncloud

Your files apparently are installed in a non-standard location /xxx/. This should not be possible using our deb packages. 

The error message includes '3rdparty directory not found!' -- can you confirm if /var/www/owncloud/3rdparty exists?

**Comment by mmattel** [comment] 2015-09-17 16:48
xxx ... /var/www/owncloud   (/var/www/ is symlinked to another disk, I just replaced the full link path by xxx, sorry for the confusion)

ls -la /xxx/
````
drwxr-xr-x 13 root     root      8192 Sep 16 19:32 .
drwxr-xr-x  8 root     root      4096 Aug 31 17:33 ..
drwxr-xr-x 26 root     root      4096 Sep 16 19:31 3rdparty
drwxr-xr-x 23 www-data www-data  4096 Sep 16 19:31 apps
drwxrwx---  2 www-data www-data  4096 Sep 16 21:52 assets
-rw-r--r--  1 root     root       477 Sep 10 17:34 AUTHORS
drwxrwxr-x  2 www-data www-data  4096 Sep 16 19:32 config
-rw-r--r--  1 root     root      2492 Sep 10 17:34 console.php
-rw-r--r--  1 root     root     34520 Sep 10 17:34 COPYING-AGPL
drwxr-xr-x 19 root     root      4096 Sep 16 19:32 core
-rw-r--r--  1 root     root      5179 Sep 10 17:34 cron.php
drwxrwx---  4 www-data www-data  4096 Sep 16 21:36 data
-rw-r--r--  1 root     root     22276 Sep 10 17:34 db_structure.xml
-rw-r--r--  1 root     root      2029 Sep 10 17:34 .htaccess
-rw-r--r--  1 root     root       179 Sep 10 17:34 index.html
-rw-r--r--  1 root     root      2076 Sep 10 17:34 index.php
-rw-r--r--  1 root     root      2595 Sep 10 17:34 indie.json
drwxr-xr-x  2 root     root      4096 Sep 16 19:32 l10n
drwxr-xr-x  6 root     root      4096 Sep 16 19:32 lib
-rwxr-xr-x  1 root     root       283 Sep 10 17:34 occ
drwxr-xr-x  2 root     root      4096 Sep 16 19:32 ocs
-rw-r--r--  1 root     root      3058 Sep 10 17:34 public.php
-rw-r--r--  1 root     root      4337 Sep 10 17:34 remote.php
-rw-r--r--  1 root     root        26 Sep 10 17:34 robots.txt
drwxr-xr-x 13 root     root      4096 Sep 16 19:32 settings
-rw-r--r--  1 root     root      1771 Sep 10 17:34 status.php
drwxr-xr-x  3 www-data www-data  4096 Sep 16 19:32 themes
-rw-r--r--  1 root     root       141 Jul 20 13:58 .user.ini
-rw-r--r--  1 root     root       190 Sep 10 17:38 version.php
````

ls -la /xxx/core/
````
drwxr-xr-x  2 root root  4096 Sep 16 19:32 ajax
-rw-r--r--  1 root root  4176 Sep 10 17:34 application.php
drwxr-xr-x  2 root root  4096 Sep 16 19:32 avatar
drwxr-xr-x  9 root root  4096 Sep 16 19:32 command
drwxr-xr-x  3 root root  4096 Sep 16 19:32 css
drwxr-xr-x  4 root root  4096 Jul 20 10:05 doc
drwxr-xr-x  2 root root  4096 Sep 16 19:32 fonts
drwxr-xr-x  6 root root  8192 Sep 16 19:32 img
drwxr-xr-x  3 root root  8192 Sep 16 19:32 js
drwxr-xr-x  2 root root 61440 Sep 16 19:32 l10n
drwxr-xr-x  5 root root  4096 Jul 20 10:05 lostpassword
-rw-r--r--  1 root root  3483 Sep 10 17:34 register_command.php
-rw-r--r--  1 root root  5382 Sep 10 17:34 routes.php
drwxr-xr-x  6 root root  4096 Jul 20 10:05 search
drwxr-xr-x  2 root root  4096 Sep 16 19:32 setup
-rw-r--r--  1 root root   674 Sep 10 17:34 shipped.json
drwxr-xr-x  4 root root  4096 Sep 16 19:32 skeleton
-rw-r--r--  1 root root  1020 Sep 10 17:34 strings.php
drwxr-xr-x  2 root root  4096 Sep 16 19:32 tags
drwxr-xr-x  3 root root  8192 Sep 16 19:32 templates
drwxr-xr-x  2 root root  4096 Sep 16 19:32 user
drwxr-xr-x 15 root root  4096 Jul 20 10:05 vendor
````

ls -la /xxx/lib/
````
-rw-r--r--  1 root root  4870 Sep 10 17:34 autoloader.php
-rw-r--r--  1 root root 38655 Sep 10 17:34 base.php
drwxr-xr-x  2 root root 61440 Sep 16 19:32 l10n
drwxr-xr-x 36 root root 20480 Sep 16 19:32 private
drwxr-xr-x 19 root root 16384 Sep 16 19:32 public
drwxr-xr-x  2 root root  4096 Sep 16 19:32 repair
````

ls -la /xxx/3rdparty
````
-rw-r--r--  1 root root   183 Sep 10 17:34 autoload.php
drwxr-xr-x  3 root root  4096 Sep 16 19:31 bantu
drwxr-xr-x  2 root root  4096 Sep 16 19:31 composer
-rw-r--r--  1 root root  1287 Sep 10 17:34 composer.json
-rw-r--r--  1 root root 82720 Sep 10 17:34 composer.lock
drwxr-xr-x  9 root root  4096 Sep 16 19:31 doctrine
drwxr-xr-x  6 root root  4096 Sep 16 19:31 guzzle
drwxr-xr-x  5 root root  4096 Sep 16 19:31 guzzlehttp
drwxr-xr-x  3 root root  4096 Sep 16 19:31 icewind
drwxr-xr-x  5 root root  4096 Sep 16 19:31 ircmaxell
drwxr-xr-x  3 root root  4096 Sep 16 19:31 james-heinrich
drwxr-xr-x  3 root root  4096 Sep 16 19:31 jeremeamia
drwxr-xr-x  3 root root  4096 Sep 16 19:31 kriswallsmith
-rw-r--r--  1 root root   543 Sep 10 17:34 LICENSE INFO
drwxr-xr-x  3 root root  4096 Sep 16 19:31 mcnetic
drwxr-xr-x  3 root root  4096 Sep 16 19:31 mrclay
drwxr-xr-x  3 root root  4096 Sep 16 19:31 natxet
drwxr-xr-x  3 root root  4096 Sep 16 19:31 nikic
-rw-r--r--  1 root root   386 Sep 10 17:34 patches.txt
drwxr-xr-x  3 root root  4096 Sep 16 19:31 patchwork
drwxr-xr-x  4 root root  4096 Sep 16 19:31 pear
-rw-r--r--  1 root root  1087 Sep 10 17:34 PEAR5.php
-rw-r--r--  1 root root 33916 Sep 10 17:34 PEAR.php
drwxr-xr-x  3 root root  4096 Sep 16 19:31 phpseclib
drwxr-xr-x  3 root root  4096 Sep 16 19:31 pimple
drwxr-xr-x  3 root root  4096 Sep 16 19:31 punic
drwxr-xr-x  3 root root  4096 Sep 16 19:31 rackspace
drwxr-xr-x  3 root root  4096 Sep 16 19:31 react
drwxr-xr-x  6 root root  4096 Sep 16 19:31 sabre
drwxr-xr-x  3 root root  4096 Sep 16 19:31 swiftmailer
drwxr-xr-x  6 root root  4096 Sep 16 19:31 symfony
````

ls -la /var/www
````
(only showing owncloud)
drwxr-xr-x 13 root root     8192 Sep 16 19:32 owncloud
````

dpkg -l | grep owncloud
````
ii  owncloud                              8.1.3-13.1                           all          The ownCloud Server - Private file sync and share server
ii  owncloud-config-apache                8.1.3-13.1                           all          The ownCloud configuration for the apache web server
ii  owncloud-doc                          0~20140120-1                         all          documentation for ownCloud
ii  owncloud-server                       8.1.3-13.1                           all          The owncloud-server package
````

**Comment by RealRancor** [comment] 2015-09-17 16:54
@jnweiger 
I don't think this is an issue with the 3rdparty folder here. The message of the missing 3rdparty folder was probably just caused because the owncloud-3rdparty package was removed, then the ./occ was called before:

> Preparing to unpack .../owncloud-server_8.1.3-13.1_all.deb ...
> owncloud-server: occ maintenance:mode --on

the actual "new" 3rdparty folder was extracted from the:

> Unpacking owncloud-server (8.1.3-13.1) over (8.1.1-1) ...

@mmattel Do you have actual any issues with that installation?

**Comment by mmattel** [comment] 2015-09-17 17:12
No issues identified from that what I have tested

**Comment by PVince81** [comment] 2015-10-21 12:52
@mmattel is this still an issue ?

**Comment by mmattel** [comment] 2015-10-21 13:11
I would need to install 8.1.1-1 stable and test it, but I am currently running out of time...

**Comment by PVince81** [comment] 2015-12-03 17:02
Any more luck with 8.1.4 ?

**Comment by PVince81** [comment] 2016-02-11 11:21
Please reopen if you're still seeing this issue with 8.1.5 or 8.2.2

**Closed by PVince81** 2016-02-11 11:21 UTC
Labels: bug, packaging, sev1-critical
