### ISSUE TITLE
Array to string conversion at /var/www/owncloud/core/ajax/share.php#363

### ISSUE THREAD

**Issue by TheKaban** [owncloud/core#22193] opened 2016-02-08 10:11 UTC
Hello!
I jumped out the error:
**Array to string conversion at /var/www/owncloud/core/ajax/share.php#363**
Please tell me that this error represents and how to fight it?
OwnCloud Version 8.2.2
Thank you

**Comment by LukasReschke** [comment] 2016-02-08 10:23
Can you tell us what you did to get that error message?

**Comment by TheKaban** [comment] 2016-02-08 10:38
This is after I share my user folder.
Thank you!

**Comment by LukasReschke** [comment] 2016-02-08 10:40
> This is after I share my user folder.

To another user/group/public link?

**Comment by TheKaban** [comment] 2016-02-08 10:48
Sharing the folder is not on the links, the user is with me in the same group.

If I share at a time with just one person, then all is well.
If I just share with two or more users, this error appears in the log.
Thank you!

**Comment by RealRancor** [comment] 2016-02-08 13:40
Looks like a duplicate of https://github.com/owncloud/core/issues/20095

**Comment by TheKaban** [comment] 2016-02-08 14:10
If I do like [this:](https: //github.com/owncloud/core/commit/41689cff55f4db51b1b67d913b448ffc7c65a42b)

So I have 2 errors appear:

in_array() expects parameter 2 to be array, string given at /var/www/owncloud/core/ajax/share.php#365
Array to string conversion at /var/www/owncloud/core/ajax/share.php#365

Can I do something wrong?
Thank you!

**Comment by TheKaban** [comment] 2016-02-08 14:28
The problem seems solved this [way](https://github.com/owncloud/core/commit/a6f180f24e850dff7c0f5541c814b63d5007df40)
Many thanks to the community!

**Comment by RealRancor** [comment] 2016-02-08 14:33
@LukasReschke Backport? :-)

**Comment by MorrisJobke** [comment] 2016-02-15 21:28
Will be fixed in 8.1.6, 8.2.3 and 9.0.0

**Comment by MorrisJobke** [comment] 2016-02-15 21:29
ref #22364 #22363

**Closed** 2016-02-15 21:28 UTC
Labels: 8.1.6-current, 8.2.3-current, bug, feature:sharing
