### ISSUE TITLE
Existing files in google drive with special characters cannot be downloaded when mounted as external storage.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23692] opened 2016-03-31 10:20 UTC
### Steps to reproduce:

1. Upload files to google drive which has special characters and spaces in the name.
2. Mount google drive (authorizing it and so on).
3. Try to download one of the files with special characters.

### Expected behaviour:
Files can be downloaded.

### Actual behaviour
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
<s:message>Could not open file</s:message>
</d:error>
```

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.1.1","versionstring":"9.0.1 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**

```
{"reqId":"CoEQR4l6Da1dja5v7lPK","remoteAddr":"hidden_ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/remote.php(138): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":306,\"User\":\"admin\"}","level":4,"time":"2016-03-31T07:55:56+00:00","method":"GET","url":"\/remote.php\/webdav\/GoogleDrive\/Guia%20Viva%20Espa%C3%B1a%20en%20moto%20(2).pdf","user":"admin"}
```

### Client configuration

**browser**
Chrome

**Comment by PVince81** [comment] 2016-03-31 10:28
@atroxix looks strangely like what we discussed in https://github.com/owncloud/client/issues/4573

**Comment by PVince81** [comment] 2016-03-31 10:28
Ah no, wrong. The linked ticket is about something else.

**Comment by PVince81** [comment] 2016-03-31 10:29
@SergioBertolinSG mind posting the file name you used ? Because we have unit tests (that needs to be run locally with own account) that already confirm that special chars work.

**Comment by PVince81** [comment] 2016-03-31 10:29
@SergioBertolinSG also, was it uploaded with a Mac (NFD encoding) ?

**Comment by SergioBertolinSG** [comment] 2016-03-31 10:31
@PVince81 all files with special characters fail. For example "Primeros pasos con Dropbox español.pdf"

**Comment by SergioBertolinSG** [comment] 2016-03-31 10:32
Files were uploaded to google drive using their web ui.

**Comment by PVince81** [comment] 2016-03-31 10:41
From a Mac ? :wink:
Were the files created/named on Mac ?

**Comment by SergioBertolinSG** [comment] 2016-03-31 10:45
Yes.

**Comment by PVince81** [comment] 2016-03-31 10:47
I copy-pasted the file name to my console and it shows weirdly. `convmv` tells me that it's a NFD-encoded file name:
```
% cp Primeros\ pasos\ con\ Dropbox\ espan<0303>ol.pdf enctest 

% convmv -r -f utf8 -t utf8 --nfc -r enctest

Starting a dry run without changes...
mv "enctest/Primeros pasos con Dropbox español.pdf"     "enctest/Primeros pasos con Dropbox español.pdf"
No changes to your files done. Would have converted 1 files in 0 seconds.
Use --notest to finally rename the files.
```

So this is a duplicate of #21365 

@SergioBertolinSG can you try creating a new file locally on Linux/Windows and manually type in the "n" + accent character ? Upload that directly to GDrive, then test again.
This would guarantee that it uses the NFC UTF-8 encoding instead of Mac's fancy exotic NFD one.

**Comment by SergioBertolinSG** [comment] 2016-03-31 11:08
@PVince81 Yes, uploading from windows works fine.

BTW, the upload detection problem was also related with this kind of files.

**Comment by PVince81** [comment] 2016-03-31 12:05
Thanks, closing as duplicate of #21365

**Closed by PVince81** 2016-03-31 12:05 UTC
Labels: app:files_external, bug, sev2-high
