### ISSUE TITLE
PHP Fatal error - External Storage Support Plug-in

### ISSUE THREAD

**Issue by marioskourtesis** [owncloud/core#23215] opened 2016-03-14 10:30 UTC
### Steps to reproduce
1. login to owncloud 9
2. Navigate to https://owncloud.../index.php/settings/admin

The page returns an error. Checking the error logs I found the following error
PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268

After disabling the "External storage support  0.5.2" plug in the problem is solved.

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
PHP 5.4.16
Zend Engine v2.4.0

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:**
Updated from owncloud 8 to 9
**Where did you install ownCloud from:**
From owncloud repositories
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - bookmarks
  - documents
  - encryption
  - external
  - files_external
  - search_lucene
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no

**Comment by LukasReschke** [comment] 2016-03-14 10:32
Dupe of https://github.com/owncloud/core/issues/22960

**Closed by LukasReschke** 2016-03-14 10:32 UTC
