### ISSUE TITLE
Duplicate sessions even with device specific passwords

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25049] opened 2016-06-09 17:27 UTC
Maybe I misunderstood the feature but I was expecting that if I give a device specific password to a device, it would be able to only use a single session.

I've generated three passwords:
- Android's CalDAV sync
- Android official mobile client for ownCloud 2.0.1
- Laptop's desktop client 2.2.1

This is the result:
![duplicatesessions](https://cloud.githubusercontent.com/assets/277525/15939415/e2241b50-2e77-11e6-82a1-e3546da150c2.png)

![duplicatesessions2](https://cloud.githubusercontent.com/assets/277525/15939452/04564bd0-2e78-11e6-9de9-a7804d1fdfc6.png)

@ChristophWurst is this normal behavior ?

CC @nickvergessen who observed something similar lately

**Comment by ChristophWurst** [comment] 2016-06-09 18:11
I can take another look at this. Apparently clients do not always re-use their sessions, not sure if this is fixable easily.

**Comment by ChristophWurst** [comment] 2016-06-10 06:42
(As discussed somewhere else) we shouldn't need session tokens for clients using a device-specific password. The only real reason why we create them at the moment is to reduce the number of user backend queries (password is not checked on *every* request, only only once per five minutes).

Hence what we can do instead of having a session for those clients, is store the timestamp of the last password check in the database entry of the token instead of the PHP session. That way clients are completely session-less in terms of authentication.

The other thing I'm worried about are legacy clients using a password for authentication, that do not support cookies/sessions. Should we create session tokens for those? If yes, that will probably spam the list of connected browsers. If no, someone can connect to your ownCloud account and there is no way to disconnect that connection. The latter would only make sense if we log those clients out right after the request. On the other hand, users will not see a connected client of that kind and would assume nobody connected to their account. Hence, this can be a new security threat IMHO.

One solution I thought of is not using any kind of PHP session for clients. While that works well for clients using a token (we only have to query the DB on those requests, user back-end once per 5 minutes), it will create a bottle-neck for password-authenticated clients as we will have to query the user back-end on every single request. Hence this is *not* a valid approach for now.

**Comment by DeepDiver1975** [comment] 2016-06-10 07:00
For the time being we need to support sessions because e.g. the shibboleth integration of our clients requires the use of sessions.

**Comment by rullzer** [comment] 2016-06-10 07:03
I think we can only 'properly' solve this is we take over the entire session management ourselfs. But that is not in the near future.

And as @DeepDiver1975 mentions in certain setups we still require those sessions.

**Comment by ChristophWurst** [comment] 2016-06-10 07:09
Right, we need to keep sessions for now (as I also wrote above), but the situation right now is not ideal if it spams the browser session list with certain devices/configurations.

However, the problem is not a new one. It existed before, but was not visible to users as we didn't have that personal settings page.

**Comment by ChristophWurst** [comment] 2016-06-10 07:15
Another (probably not acceptable) approach is to have a new token type for client-session-tokens, which are then *not* listed on the personal settings page. As the personal settings page would lie with 'these are the browsers connected to your device' then, this is not acceptable IMHO. This could be used to connect to an ownCloud account without the notice of the users…

**Comment by rullzer** [comment] 2016-06-10 07:29
@ChristophWurst I agree either we show it all or nothing. Maybe we could add a litte star or so to the client sessions that we can then explain below.

**Comment by DeepDiver1975** [comment] 2016-06-10 07:30
Mark them as kind of legacy connection or something

**Comment by ChristophWurst** [comment] 2016-06-10 07:33
Yup, good idea @rullzer.

But what about clients that do not support cookies? They would still flood the list. Should I revive https://github.com/owncloud/core/pull/24742 for that? Can someone check if the approach I tried could work?

**Comment by ChristophWurst** [comment] 2016-06-10 07:33
> Mark them as kind of legacy connection or something

But still show them in the list, right?

**Comment by ChristophWurst** [comment] 2016-06-10 07:35
Another thought: currently session tokens are created in the Sabre auth plugin. Should we move that to the ``UserSession::logClientIn`` method to have it for all APIs? DAV is not the only API clients use.

**Comment by PVince81** [comment] 2016-06-10 07:50
From what I remember both desktop and mobile clients are supposed to reuse the session cookie. Because in the past there were issues about older sessions being reused where the encryption keys didn't match.

Maybe some debugging will show whether it's really a session/cookie problem ?

@guruz @davivel can you confirm that the clients are using cookies and reuse the session ?
Or does every sync cycle create a new session ?

**Comment by dragotin** [comment] 2016-06-10 07:52
@PVince81 no, we maintain the session cookie. Remember we had the problems where lots of sessions were created in the past? Also, I thought that sending the cookie minimizes the efforts for credential validation (LDAP...). 
Actually the client returns all cookies IIRC.

**Comment by guruz** [comment] 2016-06-10 07:56
IMHO there must be a bug somewhere in the server?

> Apparently clients do not always re-use their sessions, not sure if this is fixable easily.

We use a "cookie jar" to keep the PHP session cookies (and others), so in theory it should re-use a session

HOWEVER if the server creates a new session for some reason it might use that one? Can this be related to the client blindly sending an ```Authorization``` header? And the server not taking into account that the session is already authenticated? Although I remember @rullzer had fixed this..

> That way clients are completely session-less in terms of authentication.

I'm not sure I understand that. Using the PHP session is a good thing!

>  Should we create session tokens for those? If yes, that will probably spam the list of connected browsers.

No, because this should be based on the PHP session. And neither browsers nor sync clients should have any interest in re-creating the PHP session :)

**Comment by guruz** [comment] 2016-06-10 07:59
@dragotin The mirall in the screenshot above is every 5 minutes. Interesting.. I'd have expected it to be every 30 seconds or so?

The CalDAV in the screenshot does not support sessions/cookies then because it comes in a row?

**Comment by guruz** [comment] 2016-06-10 08:01
@ChristophWurst Could our token stuff somehow remember to which PHP session it belongs and then give CalDAV always the same PHP session? Hm.
Might be a security fishyness though.

**Comment by PVince81** [comment] 2016-06-10 08:02
I guess the CalDAV sync Android app probably doesn't support sessions.
But for now I'd say let's focus on finding out why the sessions aren't kept for desktop/mobile clients. I also suspect a server bug.

**Comment by guruz** [comment] 2016-06-10 08:10
The session cookie can apparantly be set by calling https://secure.php.net/manual/en/function.session-name.php before session_start(). Maybe we could say that for tokes, we'd always want it to re-use the same session & session name?

**Comment by ChristophWurst** [comment] 2016-06-10 08:12
For clients that do not support session we should revive/finish PR https://github.com/owncloud/core/pull/24742

**Comment by karlitschek** [comment] 2016-06-10 08:12
@LukasReschke maybe you can help here? Would be great!

**Comment by ChristophWurst** [comment] 2016-06-10 08:13
I will try to debug this once again, maybe there is indeed a bug in the server code.

**Comment by ChristophWurst** [comment] 2016-06-10 09:26
Tested with desktop client and password login. Session seems to be reused while syncing. It's lost though if I exit the client and start it again.
@PVince81 did you restart your client while testing?

**Comment by PVince81** [comment] 2016-06-10 09:28
I didn't for the 3 first sync runs. You can see I had the rc1 and then when I upgraded to final I restarted it.

Will redo a local test against master.

**Comment by PVince81** [comment] 2016-06-10 09:30
Quick report from my personal server, the same as in the original report.
This morning I got duplicate sessions for the same continuously running desktop client:
![duplicatesessions3](https://cloud.githubusercontent.com/assets/277525/15960123/b004a7ca-2efe-11e6-8cec-b8cd6c2fc8a9.png)

**Comment by PVince81** [comment] 2016-06-10 09:30
Now it could also be the OCS call to the activity API that is somehow triggering a different session ?

**Comment by ChristophWurst** [comment] 2016-06-10 09:38
well, we create the session token for clients [here](https://github.com/owncloud/core/blob/68c3b23e0421a59d5423357e516ab7f4df9fcfbc/apps/dav/lib/Connector/Sabre/Auth.php#L119), which means if the client connects to OCS first it will not get a new session token. That is bad for performance (the next request is logged out before the login), but that should not cause those duplicate tokens…

**Comment by PVince81** [comment] 2016-06-10 09:49
I checked the access log of my server, you can find it here: https://owncloud.vincentpetry.net/index.php/s/hzohw6KnzAQbyr9

When checking the session list from the screenshot above, I found that at exactly the same time there's a log entry connecting to the notifications API. Snippet:
```
85.180.4.122 - vincent [10/Jun/2016:10:55:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:56:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:56:13 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:56:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:57:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:57:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:58:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:58:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:59:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:10:59:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:11:00:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:11:00:43 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:11:01:13 +0200] "PROPFIND /remote.php/webdav/clientsync HTTP/1.1" 207 365 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
85.180.4.122 - vincent [10/Jun/2016:11:01:13 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
```

These match with session entries from the following times today: 10:56, 11:01

**Comment by PVince81** [comment] 2016-06-10 10:04
Hmmm, strange thing. I can't reproduce it locally: have a desktop client running against master and I can see calls to the notifications API, but it doesn't result in more entries.

Next up: try with v9.1.0beta2 which is what I have on my server.

**Comment by PVince81** [comment] 2016-06-10 10:25
Not directly related to the duplicate sessions, but I observed this on v9.1.0beta2: whenever the desktop client makes a request, it looks like the last token gets revoked and replaced by a new one.
You can see one of the entries change and its password + id field change:
```
MariaDB [owncloud]> select * from oc_authtoken where name like '%mirall%';
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| id | uid   | login_name | password                                                                                                                                                                                                           | name                             | token                                                                                                                            | type | last_activity |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| 15 | admin | admin      | 0a770f72c1ed778a823f273c8dca3e5b3c0ee2a01ff3b2726e5e0d5c7167adcb|JXXXqAXlHu619wp6|f04581e8f75e2af396021193a4f2cce6c3d97621e25424802a59b817c5159710e722220db0e3dc176d08ff6eac3c0b12f3a6c09141cff987bbb5c30cec878ae3 | Mozilla/5.0 (Linux) mirall/2.2.1 | 078ab2ca5ec20d20f47a548e3a2eb6338b43b9cb108c02efbb4eb893e9c6ba94b94ddfd318919f1ef4e8ed7a6b983314e29c78b2970093ceeeb250b0f0b608c4 |    0 |    1465553223 |
| 16 | admin | admin      | 095dca8c8dd833a142a42548daa3851303e05527a407c226a40408b0c54aacf1|2xIhaQNjSA3EK0Gs|5552a1bd750b99f2372ef2a85214e86258e622e7478cc984ff0be05687a6adf68e6d79196656da9de86b8d13205ccc1b2a532bdf24f4ddefa3f758bd21182b63 | Mozilla/5.0 (Linux) mirall/2.2.1 | 73f2afe29d66eb410745c6fc0efda8c8aa64997aa1c8ef7e96022782d1c74b3402e6d6f16b7227e016a48bccb71215e667ab469fb2a64cc0996217ebb40c67d6 |    0 |    1465553223 |
| 33 | admin | admin      | f24052bc268f63d6cdc905f5870ec95cf657f04eb4768b81f24dd86e0bc2df9a|SjvL8Md3A8q3oGnr|782e8d22de14a84f6c1b8d762ad5ff015cda6e5dfae4045c8845de859aa2a1d2a0a1f9876597c9b37a47f59153d0d46a88d7ce4bde48af5e86d69f0a5beb05b1 | Mozilla/5.0 (Linux) mirall/2.2.1 | 428620c6e4ec960162d21eabf7d43a8efa1949061be2d9ce10599d2a15373a189f3500f7cec4087cb76983cb41eee005f5e3b7ff382dc8e0690be0d4d952e839 |    0 |    1465553703 |
| 44 | admin | admin      | 1bed00de9fb066ea12cae73ae70c2468e1295810310a73db37309275bef000c4|or+3iBejbQsoM0Px|b04089779ce92e9d4b00cbcc196dc3fea4cea0f27b841d3ed81aed3d21c304fae8634c67f9f0ba03ee34679f247aa4c482a74203d97e617649f38912228ee615 | Mozilla/5.0 (Linux) mirall/2.2.1 | ff3ef1fa650f6acaf5d1119b2c95a64d1b2bbcbbd35ff65a8a984110872735d475dd8b958199767eaab49b44f0ee7a166370d2058cfc5236b37fc89858274b93 |    0 |    1465554033 |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
4 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_authtoken where name like '%mirall%';
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| id | uid   | login_name | password                                                                                                                                                                                                           | name                             | token                                                                                                                            | type | last_activity |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| 15 | admin | admin      | 0a770f72c1ed778a823f273c8dca3e5b3c0ee2a01ff3b2726e5e0d5c7167adcb|JXXXqAXlHu619wp6|f04581e8f75e2af396021193a4f2cce6c3d97621e25424802a59b817c5159710e722220db0e3dc176d08ff6eac3c0b12f3a6c09141cff987bbb5c30cec878ae3 | Mozilla/5.0 (Linux) mirall/2.2.1 | 078ab2ca5ec20d20f47a548e3a2eb6338b43b9cb108c02efbb4eb893e9c6ba94b94ddfd318919f1ef4e8ed7a6b983314e29c78b2970093ceeeb250b0f0b608c4 |    0 |    1465553223 |
| 16 | admin | admin      | 095dca8c8dd833a142a42548daa3851303e05527a407c226a40408b0c54aacf1|2xIhaQNjSA3EK0Gs|5552a1bd750b99f2372ef2a85214e86258e622e7478cc984ff0be05687a6adf68e6d79196656da9de86b8d13205ccc1b2a532bdf24f4ddefa3f758bd21182b63 | Mozilla/5.0 (Linux) mirall/2.2.1 | 73f2afe29d66eb410745c6fc0efda8c8aa64997aa1c8ef7e96022782d1c74b3402e6d6f16b7227e016a48bccb71215e667ab469fb2a64cc0996217ebb40c67d6 |    0 |    1465553223 |
| 33 | admin | admin      | f24052bc268f63d6cdc905f5870ec95cf657f04eb4768b81f24dd86e0bc2df9a|SjvL8Md3A8q3oGnr|782e8d22de14a84f6c1b8d762ad5ff015cda6e5dfae4045c8845de859aa2a1d2a0a1f9876597c9b37a47f59153d0d46a88d7ce4bde48af5e86d69f0a5beb05b1 | Mozilla/5.0 (Linux) mirall/2.2.1 | 428620c6e4ec960162d21eabf7d43a8efa1949061be2d9ce10599d2a15373a189f3500f7cec4087cb76983cb41eee005f5e3b7ff382dc8e0690be0d4d952e839 |    0 |    1465553703 |
| 48 | admin | admin      | 56bbdcf49b272207a0e4f32cbd574f5f9d272843ffd52b47c34cac62fb760a17|Jb/IVJQsO5KERq1N|51d0b33713df9a42c31ce9ef06938693be67045f3c322e2199e4ff58350fd9fb6d88eb92246054d244f9aaf6d43a4e79063d04b7d083318abf7fbd4780163948 | Mozilla/5.0 (Linux) mirall/2.2.1 | 0ce0f35300f023aa9d25a5520ef2a1ae0eca89adaced294d615e5a70f3e0f3388a47d51d8eadd6f99f2684b35da0bbfbd8bc17d27058a3943064fb0d52324e2c |    0 |    1465554153 |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
4 rows in set (0.00 sec)

MariaDB [owncloud]> select * from oc_authtoken where name like '%mirall%';
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| id | uid   | login_name | password                                                                                                                                                                                                           | name                             | token                                                                                                                            | type | last_activity |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| 15 | admin | admin      | 0a770f72c1ed778a823f273c8dca3e5b3c0ee2a01ff3b2726e5e0d5c7167adcb|JXXXqAXlHu619wp6|f04581e8f75e2af396021193a4f2cce6c3d97621e25424802a59b817c5159710e722220db0e3dc176d08ff6eac3c0b12f3a6c09141cff987bbb5c30cec878ae3 | Mozilla/5.0 (Linux) mirall/2.2.1 | 078ab2ca5ec20d20f47a548e3a2eb6338b43b9cb108c02efbb4eb893e9c6ba94b94ddfd318919f1ef4e8ed7a6b983314e29c78b2970093ceeeb250b0f0b608c4 |    0 |    1465553223 |
| 16 | admin | admin      | 095dca8c8dd833a142a42548daa3851303e05527a407c226a40408b0c54aacf1|2xIhaQNjSA3EK0Gs|5552a1bd750b99f2372ef2a85214e86258e622e7478cc984ff0be05687a6adf68e6d79196656da9de86b8d13205ccc1b2a532bdf24f4ddefa3f758bd21182b63 | Mozilla/5.0 (Linux) mirall/2.2.1 | 73f2afe29d66eb410745c6fc0efda8c8aa64997aa1c8ef7e96022782d1c74b3402e6d6f16b7227e016a48bccb71215e667ab469fb2a64cc0996217ebb40c67d6 |    0 |    1465553223 |
| 33 | admin | admin      | f24052bc268f63d6cdc905f5870ec95cf657f04eb4768b81f24dd86e0bc2df9a|SjvL8Md3A8q3oGnr|782e8d22de14a84f6c1b8d762ad5ff015cda6e5dfae4045c8845de859aa2a1d2a0a1f9876597c9b37a47f59153d0d46a88d7ce4bde48af5e86d69f0a5beb05b1 | Mozilla/5.0 (Linux) mirall/2.2.1 | 428620c6e4ec960162d21eabf7d43a8efa1949061be2d9ce10599d2a15373a189f3500f7cec4087cb76983cb41eee005f5e3b7ff382dc8e0690be0d4d952e839 |    0 |    1465553703 |
| 50 | admin | admin      | c8977f6594acaeca2ae43ea7287569d2d5f1bc44d6085a15f5685dd09c58267a|iTOtVzkY1gDpSwYd|34fbd87d66e79b38e1de8ed8e6ee6abdebafd75aa6cb486db2f8fb74a4f27af2726670f68837fb504db3c125c4a44e530edf07574c95b0214d6ff462b8c2a6dc | Mozilla/5.0 (Linux) mirall/2.2.1 | cef889eeaea9a1ed108829dcc1cae93792e783cb604468a9e7f40b61ed7a116b1c3a39c5ac9f5b7fa84942dee098fac44aabe8e23b0f0ffd66e0d468acf1b9df |    0 |    1465554213 |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
```

**Comment by PVince81** [comment] 2016-06-10 10:26
I don't think the client really logs out as I don't see any call to the logout route. Maybe it's a clue that something weird is happening with the sessions ? Maybe the client is sending the Authorization headers correctly and the server uses that with higher priority than the session cookie ?

**Comment by PVince81** [comment] 2016-06-10 10:28
Okay, at exactly 12:25 there's a new notification call:
```
127.0.0.1 - admin [10/Jun/2016:12:25:03 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 363 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
127.0.0.1 - admin [10/Jun/2016:12:25:03 +0200] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
127.0.0.1 - admin [10/Jun/2016:12:25:33 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 363 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
127.0.0.1 - admin [10/Jun/2016:12:26:03 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 363 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
127.0.0.1 - admin [10/Jun/2016:12:26:33 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 363 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
127.0.0.1 - admin [10/Jun/2016:12:27:03 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 363 "-" "Mozilla/5.0 (Linux) mirall/2.2.1"
```

and now an additional token has appeared in the table:
```
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| id | uid   | login_name | password                                                                                                                                                                                                           | name                             | token                                                                                                                            | type | last_activity |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
| 15 | admin | admin      | 0a770f72c1ed778a823f273c8dca3e5b3c0ee2a01ff3b2726e5e0d5c7167adcb|JXXXqAXlHu619wp6|f04581e8f75e2af396021193a4f2cce6c3d97621e25424802a59b817c5159710e722220db0e3dc176d08ff6eac3c0b12f3a6c09141cff987bbb5c30cec878ae3 | Mozilla/5.0 (Linux) mirall/2.2.1 | 078ab2ca5ec20d20f47a548e3a2eb6338b43b9cb108c02efbb4eb893e9c6ba94b94ddfd318919f1ef4e8ed7a6b983314e29c78b2970093ceeeb250b0f0b608c4 |    0 |    1465553223 |
| 16 | admin | admin      | 095dca8c8dd833a142a42548daa3851303e05527a407c226a40408b0c54aacf1|2xIhaQNjSA3EK0Gs|5552a1bd750b99f2372ef2a85214e86258e622e7478cc984ff0be05687a6adf68e6d79196656da9de86b8d13205ccc1b2a532bdf24f4ddefa3f758bd21182b63 | Mozilla/5.0 (Linux) mirall/2.2.1 | 73f2afe29d66eb410745c6fc0efda8c8aa64997aa1c8ef7e96022782d1c74b3402e6d6f16b7227e016a48bccb71215e667ab469fb2a64cc0996217ebb40c67d6 |    0 |    1465553223 |
| 33 | admin | admin      | f24052bc268f63d6cdc905f5870ec95cf657f04eb4768b81f24dd86e0bc2df9a|SjvL8Md3A8q3oGnr|782e8d22de14a84f6c1b8d762ad5ff015cda6e5dfae4045c8845de859aa2a1d2a0a1f9876597c9b37a47f59153d0d46a88d7ce4bde48af5e86d69f0a5beb05b1 | Mozilla/5.0 (Linux) mirall/2.2.1 | 428620c6e4ec960162d21eabf7d43a8efa1949061be2d9ce10599d2a15373a189f3500f7cec4087cb76983cb41eee005f5e3b7ff382dc8e0690be0d4d952e839 |    0 |    1465553703 |
| 53 | admin | admin      | f3ab5b3b958266c3d8a5032faf89c53d27bd1b9f784edfd73e69bcb2b8455821|EDLE+Jmbon0xeI1d|8f753024ebaeca7bc58953e5c5b12130be558d966a6a8365139ae108c0e8790237e64338e7053947047c7e2a64ccbf775541ad93d865e14b4af3a64bd79dd5e0 | Mozilla/5.0 (Linux) mirall/2.2.1 | 3311e60eeda1d01c6a3f5417d33a8bc4ed914edb27265a7664179e6df66eb07e10bb485f4d9962136381475feeca6e10c16f9bdb7378ff3b807d7e2e22db7ec9 |    0 |    1465554303 |
| 57 | admin | admin      | 52a628f6b1dfd52a3a83c4efa85b9012cc6e632e6f24de7398ae53659c1061bb|zeydOnF8VrnXaVDQ|ea26ba8e656c0f610c926145f68da92b529694a2defd7f16cd0e8ad110da2744e116cd1de5004829da209eefce0ab49acd0c5eda90c917c7aa01a6f8ff67ed87 | Mozilla/5.0 (Linux) mirall/2.2.1 | b66ba5271bea602b96dd02e3b651633f0f1a69031e330afedb58acde343a10dba44d3a1d99eaa82690347ba44c183855caf266499f5007657382836fabd77145 |    0 |    1465554423 |
+----+-------+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------+------+---------------+
```

This is all still on v9.1.0beta2.

**Comment by PVince81** [comment] 2016-06-10 10:46
@ChristophWurst I haven't managed to reproduce it **at all** on master, only on v9.1.0beta2 with the same setup. I suspect that maybe you fixed it on master indirectly with one of your PRs ?

```
commit 9997c431c312042f313792fd3ba511ec703595e9
Author: Christoph Wurst <christoph@owncloud.com>
Date:   Wed May 25 09:58:01 2016 +0200

    use client login method on CORS routes

commit 46e26f6b4939759c6037fe848c5f56854a70ca3b
Author: Christoph Wurst <christoph@owncloud.com>
Date:   Wed Jun 8 15:03:15 2016 +0200

    catch sessionnotavailable exception if memory session is used

commit ec929f07f21341ed0e679ca27dc7e3cacd8b1b2d
Author: Christoph Wurst <christoph@owncloud.com>
Date:   Fri Jun 3 08:55:00 2016 +0200

    When creating a session token, make sure it's the login password and not a device token
```

**Comment by PVince81** [comment] 2016-06-10 10:50
@ChristophWurst it also looks like the id revokation from https://github.com/owncloud/core/issues/25049#issuecomment-225147980 does **not** happen on master, only on v9.1.0beta2.

Can you have a try on v9.1.0beta2 on your setup and then compare with master ? If you are able to reproduce only on v9.1.0beta2 then it will be a second confirmation that the problem went away.

**Comment by ChristophWurst** [comment] 2016-06-10 11:08
Oh, if commit ec929f07f21341ed0e679ca27dc7e3cacd8b1b2d is not part of v9.1.0beta2 that will probably be the reason why sessions are ended prematurely. Let me test again with v9.1.0beta2

**Comment by ChristophWurst** [comment] 2016-06-10 11:29
confirmed, was caused by tokens that have a 'password' that is actually the token :see_no_evil: 

fixed on master, closing this now

**Closed by ChristophWurst** 2016-06-10 11:29 UTC
Labels: bug, sev2-high

**Comment by guruz** [comment] 2016-06-10 11:57
@PVince81 so even for the CalDAV stuff (that might not support cookies?) it works? No filled up list?

**Comment by PVince81** [comment] 2016-06-10 12:20
@guruz I didn't try CalDAV sync on my test server.
I tried with cadaver on master and a device token and it does create a separate entry for every operation.

That's the part for maybe consolidating the sessions with the token would be helpful. I raised it here to discuss: https://github.com/owncloud/core/issues/25059

**Comment by davivel** [comment] 2016-06-10 17:44
> @davivel can you confirm that the clients are using cookies and reuse the session ?

Sorry, I just saw this call :$

The Android client does NOT reuse session cookies, unless Shibboleth is the auth method.

We have code in place to use session for any auth method, but never got to enable it because were worried about active sessions not being shut down when the password was changed.
