### ISSUE TITLE
Strange behaviour when sharing

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#20384] opened 2015-11-08 12:07 UTC
### What I did before it got strange

1. Created a user called test
2. Added test to a group and med test admin for that group
3. Deleted the user test from the user gui (now I suddenly saw things shared with me that I didn't see before)
4. I deleted the files that was shared with me from the user (in the backend)
5. I did a files:scan with occ (now the files where gone, as expected
6. I created a new folder, and shared that folder with another user
7. Here I noticed the strange behavior
8. **I checked the data folder that contained folders with strange names, I deleted them, and also deleted the strange shared entries in the database** That also occured in a previous version on another server: https://github.com/owncloud/core/issues/12645#issuecomment-66364381 @LukasReschke 
9. I ran files:scan, and also the repair step in occ

### Expected behavior
No strange share names

### Actual result

Activites:
![image](https://cloud.githubusercontent.com/assets/4511254/11020120/50d14728-8615-11e5-876c-ec591c41a66c.png)

Database (oc_storages)
![image](https://cloud.githubusercontent.com/assets/4511254/11020125/75edf5c4-8615-11e5-9e2b-24b37d7de805.png)

Even if I delete the strange entries they come back. I checked all the other database tables, and they look ok. 

**Update, I deleted them several times and now they are gone from the database (replaced by normal names, but the share name is still strange, also - all the other shares are still normal and existing.**

### Logs
**owncloud.log**
```
{"reqId":"ZMq9OJe6nlFEsa3qmfg8","remoteAddr":"IP-ADRESS","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#343","level":3,"time":"2015-11-08T12:32:01+01:00"}
{"reqId":"ZMq9OJe6nlFEsa3qmfg8","remoteAddr":"IP-ADRESS","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#343","level":3,"time":"2015-11-08T12:32:01+01:00"}
{"reqId":"ZMq9OJe6nlFEsa3qmfg8","remoteAddr":"IP-ADRESS","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#343","level":3,"time":"2015-11-08T12:32:01+01:00"}
{"reqId":"H5XAVizqrfrCHxty+onw","remoteAddr":"IP-ADRESS","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#343","level":3,"time":"2015-11-08T12:32:04+01:00"}
{"reqId":"H5XAVizqrfrCHxty+onw","remoteAddr":"IP-ADRESS","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/core\/ajax\/share.php#343","level":3,"time":"2015-11-08T12:32:04+01:00"}
```

### occ files:scan on the user where I deleted the files from
![image](https://cloud.githubusercontent.com/assets/4511254/11020190/f956242a-8617-11e5-925c-43ad4a3dbf7a.png)

### Server configuration
Ubuntu Server 14.04

**Database:**
Server version: 5.5.46
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
8.2
**Updated from an older ownCloud or fresh install:**
Updated since 6.0 
**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - files: 1.2.0
  - files_locking: 
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mail: 0.2.1
  - notifications: 0.1.0

Disabled:
  - encryption
  - external
  - files_external
  - provisioning_api
  - templateeditor
  - updater
  - user_external
  - user_ldap

**Comment by enoch85** [comment] 2015-11-08 12:13
I noticed that this only affects that specific folder inside that specific subdir. If I delete the folder and make new one in root, and then share that folder with the same user, the error is gone.

**Comment by enoch85** [comment] 2015-11-08 12:26
If I stop sharing the subdir that the shared folder is in, the shared folder acts as normal. But, If I share the subdir again, the shared folder inside that subdir gets a strange name.

**Comment by PVince81** [comment] 2015-11-09 12:35
> now I suddenly saw things shared with me that I didn't see before

Are these local shares ? Can you describe what user what sharing what with you and why you could not see them ?

For the error messages and the "shared::xxxx" entries, they look like federated shares.

Not sure about the weird share names in your screenshot, it looks like link shares got transformed into regular shares ? Did you fiddle with the share_type field lately ?

**Comment by rullzer** [comment] 2015-11-09 15:22
Those weird entries look like our hash output... so something weird is happening indeed.

**Comment by enoch85** [comment] 2015-11-09 23:16
@PVince81 
>Are these local shares ? 

No, federated cloud shares. I dont know why I couldn't see them before, but they just showed up after those steps. The shares was shared with me like one month ago, I don't remember if I removed them or not.

>Did you fiddle with the share_type field lately ?

No

@rullzer Thanks for confirmation on the weirdness! :)

**Comment by PVince81** [comment] 2015-11-10 07:43
Yeah, these entries look like public link shares that got somehow converted to local shares, spooky!

**Comment by MorrisJobke** [comment] 2015-11-10 08:22
> Yeah, these entries look like public link shares that got somehow converted to local shares, spooky!

o.O I thought this isn't implemented yet :confused:

**Comment by PVince81** [comment] 2015-11-16 11:26
It isn't. I was just suspecting that some bug simply changed the "share_type" from 3 to 0 for some reason.

**Comment by PVince81** [comment] 2016-03-03 15:10
Not sure if we'll ever manage to reproduce this weird issue, also the sharing code has changed a lot in 9.0 RC1. I'm closing this now.

If there are any detailed steps to reproduce this consistently on 8.2.2 or 9.0 RC1, feel free to reopen.

**Closed by PVince81** 2016-03-03 15:10 UTC
Labels: bug, feature:sharing
