### ISSUE TITLE
[settings:personal] Remove image button appears when changing the fullname 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#20601] opened 2015-11-19 08:11 UTC
### Steps to reproduce

1. Go to personal settings
2. Modify the full name

### Expected behaviour

Changing the full name should not show the remove image button.

### Actual behaviour

The Remove Image button appears even when there is no avatar image set.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: ownCloud Enterprise Edition 9.0 pre alpha (daily) Build:2015-11-19T04:29:14+00:00 da5285dc23dc88d8f570409a8d7ed1296b95f407

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no;
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

![screen shot 2015-11-19 at 09 03 09](https://cloud.githubusercontent.com/assets/10596560/11265492/e96ccbb2-8e9c-11e5-9e3d-180b051fb310.png)

**Comment by rullzer** [comment] 2016-02-10 12:02
Duplicate of https://github.com/owncloud/core/issues/20601

**Closed by rullzer** 2016-02-10 12:02 UTC
Labels: bug, settings:personal, sev4-low

**Comment by davitol** [comment] 2016-02-10 12:07
@rullzer https://github.com/owncloud/core/issues/20601#issuecomment-182336093 :eyes: 

Dupe of itself?

**Comment by rullzer** [comment] 2016-02-10 12:38
@davitol hehe wrong issue...
I mean https://github.com/owncloud/core/issues/17320

**Comment by davitol** [comment] 2016-02-10 12:47
@rullzer thank you for the info :wink:
