### ISSUE TITLE
External mounts are not longer visible (tested with SMB)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#19150] opened 2015-09-18 07:48 UTC
Ubuntu 14.04, nginx, mysql

Setting up a new testing instance with ``sudo ocdev setup base --dir=xxx``
Finalizing installation, enabling external storage support

Adding a SMB share sucessully
Problem: the mount is not shown in the Files-App!

No error messages logged

**Comment by karlitschek** [comment] 2015-09-18 08:01
can you post a full bug report using the issue template please?

**Comment by PVince81** [comment] 2015-09-18 09:11
@mmattel if you are using master, please pull. Possibly duplicate of https://github.com/owncloud/core/issues/19084

**Closed by PVince81** 2015-09-18 09:11 UTC
Labels: bug

**Comment by mmattel** [comment] 2015-09-18 12:55
@PVince81 
pull/rebase solved <this> problem. I can see the mount now in Files.
But now I get as long I am logged in the instance every second a error message (logoff stops it, login starts it):

owncloud.log
{"reqId":"mQEStr+sD\/s55QTLTSAV","remoteAddr":"y.y.y.y","app":"no app in context","message":"Trying to acquire a lock for 'files\/d6b4674e7c75ef0b6eb6f6e476a6d3e4' while inside a transition", "level":2,"time":"2015-09-18T14:47:00+02:00"}

Where the key after files\/ is every time different.

Shall I open an new issue?

**Comment by PVince81** [comment] 2015-09-18 12:58
Argh. This PR might fix it https://github.com/owncloud/core/pull/19098 but is still WIP.

If you need a working system you can quickly disable locking by setting "filelocking.enabled" to false in config.php. Don't forget to reenable it later.

**Comment by mmattel** [comment] 2015-09-18 13:12
It is only for tests and to check the current state and how changes / improvements are doing. test and prod is running on the same physical system, so I can clearly see what is the different behaviour.
``'filelocking.enabled' => false,`` worked as workaround.
As this is not going into production, and I regulary clone master by ``ocdev setup base`` there is no worry for me. Sometimes I do a rebase too - of course...

**Comment by Xenopathic** [comment] 2015-09-18 14:24
Or, alternatively, set a memcache as the file locking backend.
