### ISSUE TITLE
OC 10.0.4 & Postgresql 10

### ISSUE THREAD

**Issue by maximd1** [owncloud/core#29787] opened 2017-12-07 13:29 UTC
Hello,

I am facing issue with upgrade of Owncloud to 10.0.4. The issue is that 10.0.4 does not support Postgresql 10.1, error is: 

> 2017-12-07T13:18:30+00:00 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"':
> 
> SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
> LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq...
>                ^
> 2017-12-07T13:18:30+00:00 Update failed

The same is on the admin page:

> Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq... ^

### Steps to reproduce
1. cd /var/www/owncloud
2. sudo -u nobody ./occ upgrade

### Expected behaviour
OC should be successfully upgraded to 10.0.4.

### Actual behaviour
Error during the database update:

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq... ^

### Server configuration
CentOS Linux release 7.4.1708 (Core) x64

**Web server:**
Apache 2.4.6

**Database:**
PostgreSQL 10.1

**PHP version:**
php56w-5.6.32-1.w7.x86_64

**ownCloud version:** (see ownCloud admin page)
10.0.3.3

**Updated from an older ownCloud or fresh install:**
from an older ownCloud

**Where did you install ownCloud from:**
rpm

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
can't retreive, oc locked in the maintenance mode

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'debug' => false,
  'instanceid' => 'id',
  'passwordsalt' => '**************',
  'secret' => '*************',
  'trusted_domains' =>.
  array (
    0 => 'homecloud',
    1 => 'example.com',
  ),
  'datadirectory' => '/mnt/NAS/HomeCloud',
  'overwrite.cli.url' => 'http://example.com',
  'dbtype' => 'pgsql',
  'version' => '10.0.3.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:5432',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '*************',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'from',
  'mail_domain' => 'example.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '587',
  'theme' => '',
  'maintenance' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpauth' => 1,
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '*****',
  'mail_smtpsecure' => 'ssl',
  'loglevel' => 3,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'asset-pipeline.enabled' => true,
  'htaccess.RewriteBase' => '/',
  'updatechecker' => false,
  'versions_retention_obligation' => 'disabled',
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>.
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '',
  ),
);

**Comment by kdslkdsaldsal** [comment] 2017-12-07 14:04
Closing as a duplicate of https://github.com/owncloud/core/issues/29342 which is about missing PostgreSQL 10 support and currently discusses various points about PostgreSQL 10 support.

**Closed by kdslkdsaldsal** 2017-12-07 14:04 UTC
Labels: bug
