### ISSUE TITLE
Failed to download thumbnails with spaces in dirnames

### ISSUE THREAD

**Issue by mvysny** [owncloud/core#17855] opened 2015-07-24 17:31 UTC
When I try to download a thumbnail of a file in, say, tmp/foo/bar.jpg, the thumbnail is produced immediately. However, if I try e.g. https://*****/owncloud/index.php/apps/files/api/v1/thumbnail/300/300/fotky/2013-01-31%20konecne%20doma/IMG_20130131_154117.jpg
The GET fails with 404 not found. Perhaps I am encoding the URL incorrectly?

**Comment by mvysny** [comment] 2015-07-24 17:33
I'm using OwnCloud 8.2 from OwnCloud official repositories, on Ubuntu 14.04 x86.

**Comment by mvysny** [comment] 2015-07-24 17:38
Hmm, even links like https://******/owncloud/index.php/apps/files/api/v1/thumbnail/300/300/fotky/2013-01-25/IMG_20130125_155516.jpg do not work and fail with 404. Perhaps the "-" character is at fault here? I have not altered the default config regarding the thumbnail setting, so 300x300 thumbnails should have been provided correctly.

**Comment by mvysny** [comment] 2015-07-24 17:40
Nope, "-" is not it: https://******/owncloud/index.php/apps/files/api/v1/thumbnail/300/300/huhu-foo/bar.jpg works correctly.

**Comment by mvysny** [comment] 2015-07-24 17:42
I have checked the Settings/Admin/Logs, but there are no logs from this day.

**Comment by rullzer** [comment] 2015-07-25 17:06
Could you fill in the issue template at https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

Since all I can tell you now is that previews seem to be working here.

**Comment by mvysny** [comment] 2015-07-27 19:59
Thank you very much for your response. While filling in the form, I have encountered this particular line in the owncloud log file:
{"reqId":"8CyO9N4uqy0mBKoXrisK","remoteAddr":"******","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2015-07-27T19:49:48+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/files\/api\/v1\/thumbnail\/100\/100\/fotky\/2013-01-26\/IMG_20130126_144553.jpg"}

This may be the cause of the issue. The full filled-in report is present here: https://gist.github.com/mvysny/51d30e28509460f1b18f
Please let me know if there is anything I can help.

**Comment by PVince81** [comment] 2015-07-28 10:07
@oparoz @georgehrke

**Comment by mvysny** [comment] 2015-07-28 10:49
I just double-checked and the jpg in question indeed is a valid JPG file:

$ file IMG_20130126_144553.jpg
IMG_20130126_144553.jpg: JPEG image data, EXIF standard 2.2, baseline, precision 8, 2592x1944, frames 3

**Comment by oparoz** [comment] 2015-07-28 14:09
"IMG_20130126_144553.jpg: JPEG image data, EXIF standard 2.2, baseline, precision 8, 2592x1944, **frames 3**"

This looks suspicious. Maybe a panoramic picture?

**Comment by oparoz** [comment] 2015-07-28 14:12
But more importantly, do you have previews in Files and Gallery?
If not, and it only affects these specific pictures, then it's a problem with their format.

**Comment by mvysny** [comment] 2015-07-28 14:17
It is a standard picture, taken with the Galaxy Nexus phone. I have retrieved the EXIF data: https://gist.github.com/mvysny/ef8fac83b061be2536eb

The image is a standard 4:3 5-megapixel image, not a panorama. The "Files" browser *do* show preview for this (and all other) image.

**Comment by oparoz** [comment] 2015-07-28 14:23
Thanks :)

If you get previews in Files, then it's specific to the thumbnails API, which needs lots of love...

**Comment by mvysny** [comment] 2015-07-28 14:25
No problem :) Thank you for looking on this. Yes, the thumbnails API docu is quite hard to find ;) Please, if you need more debug info, just let me know. If the thumbnails PHP impl uses some linux binary, just let me know and I can run the binary myself and post the result.

**Comment by mvysny** [comment] 2015-07-28 14:29
Perhaps the Orientation value of 0 is the root of the problem? Perhaps the OC_Image->fixOrientation() function hates the 0 (undefined) orientation value.

**Comment by oparoz** [comment] 2015-07-28 14:29
The code responsible for the thumbnails is here:
https://github.com/owncloud/core/blob/master/apps/files/controller/apicontroller.php#L81-L86

First thing I notice is that it uses `urldecode`. In Gallery, I use `rawurldecode` (https://github.com/owncloud/gallery/blob/master/controller/filescontroller.php#L106) 

So, maybe try that?

**Comment by oparoz** [comment] 2015-07-28 14:31
> Perhaps the OC_Image->fixOrientation() function hates the 0 (undefined) orientation value.
No, it just thinks the file is not a JPEG, which may be a red herring if the problem is that the file can't be found.

**Comment by mvysny** [comment] 2015-07-29 14:27
I have found the file in /var/www/owncloud/apps/files/controller/apicontroller.php, however I am not sure on how should I change the line (I am no PHP programmer). Should it read

$preview = $this->previewManager->createPreview('files/' + rawurldecode($file), $x, $y, true);

?

**Comment by oparoz** [comment] 2015-07-29 14:37
Ah, sorry, I thought you were :D 

You forgot the dot, but otherwise that's what I meant, yes.

**Comment by oparoz** [comment] 2015-07-29 14:38
Ah, sorry, I thought you were :D 

You need to replace the `+` with a `.` , but otherwise that's what I meant, yes.

**Comment by mvysny** [comment] 2015-07-29 14:55
What do you know, it worked :-D Now I get thumbnails instead of that pesky 404 - thanks! I have changed the line as you suggested, to

$preview = $this->previewManager->createPreview('files/'.rawurldecode($file), $x, $y, true);

**Comment by oparoz** [comment] 2015-07-29 15:16
Cool! ;)

I'll prepare a PR so that other people can test and voice their opinion. Thanks for testing :)

**Comment by DeepDiver1975** [comment] 2015-08-19 07:59
fixed with #18076

**Closed** 2015-09-15 14:23 UTC
Labels: app:files, bug
