### ISSUE TITLE
Log errors after upgradde 7.0.4 -> 8.0.4

### ISSUE THREAD

**Issue by srissel** [owncloud/core#17028] opened 2015-06-18 16:09 UTC
Hello,

I just upgraded from ownCloud 7.0.4 to 8.0.4, using the build in update center.
As described in several blog posts I found, I deactivated the old Calendar and Contacts app, before the actual upgrade.

The upgrade process itself went through without errors.
One thing bothers me after the upgrade:
Each time I open the App manager (.../index.php/settings/apps), two errors are reported into the log (see below).

Do you have any help on this?
Can you tell something about the errors' impact on owncloud's functionality?

### Steps to reproduce
* have a running ownCloud 7.0.4 server installation
* disable Calendar app and Contacts app
* upgrade from ownCloud 7.0.4 to 8.0.4 using integrated Update Center

### Expected behaviour
No log erros after upgrade procedure

### Actual behaviour
2 log errors each time when opening App manager

### Logs
```
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "Invalid argument supplied for foreach() at ...\/lib\/private\/app.php#1233",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
},
{
	"reqId": "0f354fc916e8571fd11afda56f649625",
	"remoteAddr": "...",
	"app": "PHP",
	"message": "preg_split() expects parameter 2 to be string, array given at ...\/lib\/private\/app.php#1230",
	"level": 3,
	"time": "2015-06-17T20:42:18+00:00"
}
```

Kind regards,
Sascha.

**Comment by RealRancor** [comment] 2015-06-18 16:31
Hi,

looks like a duplicate of https://github.com/owncloud/core/issues/16251

**Comment by srissel** [comment] 2015-06-18 19:03
@RealRancor 
Might be the case, at least it seems related.
But indeed I have successfully enabled 8 apps. So far I did not ran into the behaviour of #16251 ....

At the moment, it's just the two log message, I experience when opening App manager. At least it *seems* to work as expected.

**Comment by DeepDiver1975** [comment] 2015-06-30 10:11
looks like one of the apps has a description which is not a string but an array - strange.

**Closed** 2015-07-01 13:44 UTC
Labels: 3 - To Review, bug, sev3-medium
