### ISSUE TITLE
occ files:scan does not invalidate checksums if file changed on disk.

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#23783] opened 2016-04-04 15:56 UTC
### Steps to reproduce
1. Create a file on client
2. Wait until it is synced.
3. Check that it has a checksum in the database, which was sent from the client.
4. Edit the file on the server file system, which is not supported and forbidden as you should know.
5. Feel bad about yourself and think `occ files:scan --all` will fix it.
6. Start `occ files:scan --all` as you are an experienced admin for ownCloud
7. See that the checksum of the file has not changed and was not invalidated :-1: 

### Expected behaviour
When a files mtime on disk is changed, the checksum on the server needs to be recalculated. If that can not be done, it needs at least to be invalidated. The occ file scan must compare the mtime of the file and the one stored in the db and wipe the checksum if they do not match. In addition there should be a switch to wipe *all* checksums, if they can not be recalculated.

Having a wrong checksum for a file is a **critical** problem as the client will complain about a corrupted file on download .

### Server configuration
**Operating system**:
Linux 
**Web server:**
apache 
**Database:**
mysql 
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
9.0.x, master branch, 15833d9843c3ff7c0cb51b95f8610bddb044472d
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
git
**Are you using external storage, if yes which one:** local/smb/sftp/...
no external storage
**Are you using encryption:** yes/no
no encryption
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no user-backend.

**Comment by rullzer** [comment] 2016-04-04 17:56
Yes agreed this must be handled properly.
I think the safest thing would even be to just invalidate all checksums on file scan. As we have (without recalculating) no guarantees the data is unchanged...

**Comment by danimo** [comment] 2016-04-04 18:00
<sysadmin_hat>Safe? Yes. Expected: no. Scanning has become _the_ default solution when something is wrong. Invalidating checksums by default makes this impossible, as it means resynch with all clients. Not something you want with a considerable amount of users and devices.</sysadmin_hat>

**Comment by rullzer** [comment] 2016-04-04 18:06
@danimo well if we don't want to calculate checksums on the server this is kind of playing with fire... 

I guess the 'second' safest thing to do it compare mtime + size...

**Comment by rullzer** [comment] 2016-04-04 18:06
Raised to sev2 as this has to be fixed for 9.0.2 from my POV. @cmonteroluque

**Comment by dragotin** [comment] 2016-04-04 18:47
@danimo  no, invalidating the checksums would not mean to resync to all clients, as we use the ETags to decide upon syncing as you remember. 

I think that there is no alternative to invalidating all checksums on rescan as, with this bug, we can not trust any checksum that is stored in the server db, as long as it is not validated.

**Comment by danimo** [comment] 2016-04-04 18:57
@dragotin you are right, of course.

**Comment by cmonteroluque** [comment] 2016-04-07 20:22
@rullzer agreed

**Comment by moscicki** [comment] 2016-04-14 07:49
You should NOT to send any checksums in the reply headers (GET) if you are unable to guarantee that these checksums are correct. So only send checksums if you are sure they are correct by design.  So I think you should disable sending any checksums until you fix this issue in the server.

**Comment by PVince81** [comment] 2016-04-18 12:56
CC @icewind1991 since it's related to scanning.

**Comment by rullzer** [comment] 2016-04-19 18:42
PR that fixes this in https://github.com/owncloud/core/pull/24098

**Comment by rullzer** [comment] 2016-04-20 18:55
Stable 9 backport in https://github.com/owncloud/core/pull/24129

**Comment by rullzer** [comment] 2016-04-21 10:57
Merged. Closing.

**Closed by rullzer** 2016-04-21 10:57 UTC
Labels: app:files, bug, comp:filesystem, sev1-critical
