### ISSUE TITLE
UPGRADE ISSUE

### ISSUE THREAD

**Issue by Dunmarie** [owncloud/core#15267] opened 2015-03-27 11:38 UTC
I have upgrade OwnCloud from version 7.0.4 to 8.0.2 using the YUM repositories on CentOS 6.5.
Getting the following error when login to website and click on "Start Upgrade":
Could not automatically fix legacy storage "local::/data/www/html/owncloud/data/007EF7C6-7A9C-4FC6-93DE-D258B0F2EFB3/" => "home::007EF7C6-7A9C-4FC6-93DE-D258B0F2EFB3" because they both have data.
Please advise.
Thanks.

**Comment by RealRancor** [comment] 2015-03-27 12:04
Hi,

this is a duplicate of https://github.com/owncloud/core/issues/13980 where you can find some workarounds and further infos that this should be fixed in OC 8.0.3.

**Closed** 2015-03-27 12:15 UTC
Labels: duplicate
