### ISSUE TITLE
DB-Failure while upgrading

### ISSUE THREAD

**Issue by peterporta** [owncloud/core#25691] opened 2016-08-02 21:51 UTC
Upgrading owncloud from 8.2.7 to 9.0.1 or 9.0.4 I get the following message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by RealRancor** [comment] 2016-08-03 05:01
@peterporta Duplicate of https://github.com/owncloud/core/issues/23988

Please close here and follow the issue there.

**Closed** 2016-08-03 06:01 UTC
