### ISSUE TITLE
[User management] save settings like "Show last log in"

### ISSUE THREAD

**Issue by michag86** [owncloud/core#13859] opened 2015-02-03 15:45 UTC
In the user management are settings for:
 - Show storage location
 - Show last log in
 - Show user backend
 - Send email to new user
 - Show email address 

When I enable some of this settings, switch to "Personal" and switch back, all settings are unchecked.

Tested with current daily from 2015-02-03.

**Comment by MorrisJobke** [comment] 2015-02-03 15:58
I added it to the list in #12998

**Comment by LukasReschke** [comment] 2015-02-03 22:12
Dupe of https://github.com/owncloud/core/issues/12727

**Comment by LukasReschke** [comment] 2015-02-03 22:12
(adjusted the reference in the meta issue)

**Closed by LukasReschke** 2015-02-03 22:12 UTC
Labels: Enhancement, settings:users
