### ISSUE TITLE
Sharing with other users through Safari, stored passwords blocks UI

### ISSUE THREAD

**Issue by DIYglenn** [owncloud/core#19082] opened 2015-09-16 09:31 UTC
Hi!
I'm using Safari on Yosemite, and Owncloud 8.1. We're only Mac users here, and we're seeing a problem with the "Share" portion of OwnCloud. The problem is that stored password in Safari pops up when you want to write, blocking the "Share Link" button and also the suggested users to share with.

I guess this is a problem related to how Safari handles those text boxes, but maybe there is a way to stop this from happening? Not allowing stored data in those boxes?

(Sorry for the Norwegian text, but I guess you know which share-button I'm talking about)

![password bug](https://cloud.githubusercontent.com/assets/10504432/9901207/56353e1e-5c66-11e5-9a94-6cb7f5c702fb.png)
![password bug 2](https://cloud.githubusercontent.com/assets/10504432/9901209/59df12a6-5c66-11e5-852e-35efce6ae923.png)

**Comment by MorrisJobke** [comment] 2016-01-20 12:34
I just checked with owncloud 8.2.2 and Safari 9.0.2 and the issue isn't reproducible anymore. I will close this then.

**Closed by MorrisJobke** 2016-01-20 12:34 UTC
Labels: bug
