### ISSUE TITLE
imagepng() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by philfry** [owncloud/core#14036] opened 2015-02-10 10:26 UTC
Hi,

pictures are showing up fine when using "files", but when trying to browse them using the gallery ("pictures") I only get the spinning circle.

The logs show:
```
"app":"PHP","message":"imagepng() expects parameter 1 to be resource, boolean given  at \/var\/www\/html\/owncloud\/lib\/private\/image.php#292","level":3,"time":"2015-02-10T10:22:51+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=...
"app":"core","message":"OC_Image->data. Error getting image data.","level":3,"time":"2015-02-10T10:22:51+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=...
```

Regards,

Phil

**Comment by PVince81** [comment] 2015-02-10 10:40
@icewind1991 @oparoz

**Comment by oparoz** [comment] 2015-02-10 10:52
I think it's an issue with the Image class not properly checking the response it gets from the preview provider. I encountered the problem when working on the Preview class.
@georgehrke

**Comment by RealRancor** [comment] 2015-02-10 11:17
Probably a duplicate of: https://github.com/owncloud/gallery/issues/158

**Comment by MorrisJobke** [comment] 2015-02-27 14:58
Gallery issue -> something for the gallery bug tracker -> close

**Comment by oparoz** [comment] 2015-02-27 15:30
The error is non-blocking, but there is still a `core` issue.

```
imagepng() expects parameter 1 to be resource, boolean given
```
The method data() is using `$this->resource`, without even checking that it has one.
The default value for resource is false.

I think @georgehrke should still take a look and make that function more robust.

**Comment by oparoz** [comment] 2015-02-27 16:24
Thanks!

**Comment by itheiss** [comment] 2015-03-13 14:08
I am facing this bug since ownCloud v8.0 and it´s really really frustrating to have a broken gallery with only a spinning circle. In my humble opinion this isn't a low priority bug. We are talking about a core functionality that is completly broken for every person affected!

Any news or quick fixes to apply myself are relly appreciated.

Regards,

Ingo

**Comment by MorrisJobke** [comment] 2015-03-13 14:10
cc @nickvergessen because you also dig into this maybe

**Comment by oparoz** [comment] 2015-03-13 14:21
@itheiss - Which browser?

**Comment by georgehrke** [comment] 2015-03-13 14:24
I can take a look this evening, should be fairly easy to fix.

Please excuse my brevity and typos.

**Comment by itheiss** [comment] 2015-03-13 14:29
@oparoz  I am using Chrome v 40.0.2214.111 m on Windows 7

**Comment by oparoz** [comment] 2015-03-13 14:31
@itheiss - Thanks I just wanted to make sure you were not on Internet Explorer :)

**Comment by georgehrke** [comment] 2015-03-13 16:26
@itheiss can you validate that https://github.com/owncloud/core/pull/14883 fixes the issue?

**Comment by itheiss** [comment] 2015-03-13 16:45
@georgehrke  The error 'imagepng() expects parameter 1 to be resource, boolean given' is gone but the spinning circle remains. It seems to me the thumbnail generation stops at a specific image. Is the a way to enable traceing to see which images are processed? Maybe we can get a clou which image is causing the problem?

**Comment by oparoz** [comment] 2015-03-13 16:48
@itheiss - You're affected by https://github.com/owncloud/gallery/issues/158 and https://github.com/owncloud/gallery/issues/159

You'll have better luck switching to Gallery+: https://apps.owncloud.com/content/show.php/Gallery%2B?content=169116

**Comment by itheiss** [comment] 2015-03-13 17:42
@oparoz Thanks for pointing me to Gallery+. Works like a charm!

**Closed** 2015-03-16 11:22 UTC
Labels: bug, sev4-low

**Comment by MorrisJobke** [comment] 2015-03-16 12:16
stable8 #14917

**Comment by Trefex** [comment] 2015-03-30 16:20
:+1: affects me
