### ISSUE TITLE
Error running files:scan --all --repair

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29806] opened 2017-12-10 18:29 UTC
### Steps to reproduce
1. Upgrading from 10.0.3 to 10.0.4
2. Single user mode
3. run ./occ command

### Expected behaviour
Pass error free

### Actual behaviour
Error output in command line

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7

**ownCloud version:** (see ownCloud admin page) 10.0.4

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xyz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xyz",
        "dbtype": "mysql",
        "version": "10.0.4.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "xyzzy",
        "mail_smtpsecure": "tls",
        "mail_domain": "xyzzy",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "xyzzy",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": true
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.6",
            "signed": "true",
            "types": "filesystem"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "2.1.0",
            "signed": "true",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "274"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "core": {
            "OC_Channel": "production",
            "backgroundjobs_mode": "cron",
            "enable_external_storage": "yes",
            "installedat": "1472717543.0954",
            "lastcron": "1512927012",
            "lastupdateResult": "[]",
            "lastupdatedat": "1512928212",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "repairlegacystoragesdone": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "vendor": "owncloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.3.2",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.1",
            "types": "filesystem"
        },
        "federation": {
            "autoAddServers": "1",
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "10 MB",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_clipboard": {
            "enabled": "yes",
            "installed_version": "0.6.2",
            "signed": "true",
            "types": ""
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "0.7.1",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "dav,owncloud,smb,files_external_dropbox,ftp,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_external_dropbox": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "signed": "true",
            "types": "filesystem"
        },
        "files_external_ftp": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "signed": "true",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.2",
            "ocsid": "166049",
            "signed": "true",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "ocsid": "166051",
            "signed": "true",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.2",
            "signed": "true",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.1.1",
            "ocsid": "169116",
            "types": ""
        },
        "logreader": {
            "enabled": "no",
            "installed_version": "1.1.5",
            "levels": "00111",
            "ocsid": "170871",
            "types": ""
        },
        "market": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "market": "0.2.3",
            "music": "0.5.4",
            "signed": "true",
            "types": ""
        },
        "music": {
            "enabled": "yes",
            "installed_version": "0.5.4",
            "ocsid": "164319",
            "signed": "true",
            "types": "filesystem"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.2",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "rainloop": {
            "enabled": "no",
            "installed_version": "5.0.0",
            "ocsid": "165254",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "core": "9.1.6",
            "enabled": "yes",
            "installed_version": "0.2.1",
            "rainloop": "5.0.0",
            "types": ""
        }
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.6.2
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.0
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - music: 0.5.4
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** local, smb, ftp, dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** MacOS

#### ownCloud log (command shell output)
```
Exception during scan: ErrorException: Undefined index: size
#0 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(421): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/var/w...', 421, Array)
#1 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(382): OC\Files\Cache\Scanner->handleChildren('SYNC/abcd/...', true, 3, '95899', true, 3136838)
#2 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('SYNC/abcd/...', true, 3, '95899', true)
#3 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('SYNC/abcd/...', true, 3, '95795', true)
#4 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('SYNC/abcd', true, 3, '94409', true)
#5 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren(‚SYNC/abc', true, 3, '94367', true)
#6 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(385): OC\Files\Cache\Scanner->scanChildren('SYNC', true, 3, '94025', true)
#7 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(316): OC\Files\Cache\Scanner->scanChildren('', true, 3, '93998', true)
#8 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(238): OC\Files\Cache\Scanner->scan('', true, 3)
#9 /var/www/owncloud/apps/files/lib/Command/Scan.php(224): OC\Files\Utils\Scanner->scan('/user_1', false)
#10 /var/www/owncloud/apps/files/lib/Command/Scan.php(310): OCA\Files\Command\Scan->scanFiles('user_1', '/user_1', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, false)
#11 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(262): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/owncloud/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/owncloud/lib/composer/symfony/console/Application.php(826): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/owncloud/lib/composer/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/owncloud/lib/composer/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/owncloud/lib/private/Console/Application.php(162): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/owncloud/console.php(106): OC\Console\Application->run()
#18 /var/www/owncloud/occ(11): require_once('/var/w...')
#19 {main}
```

**Comment by ownclouders** [comment] 2017-12-10 18:38
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment] 2017-12-11 08:06
This seems to be the regular scan that happens after repairing, so it is likely that it's not related to the repair.

Any special chars involved in the scanned folder ? UTF-8 NFD characters ? (files created on Mac)

**Comment by mmattel** [comment] 2017-12-11 08:13
No.
I just used a terminal app (Terminus) in MacOS to access the Ubuntu server.
The user where it stumbled (mine) has a federated share, a dropbox mount and some smb mounts.
The mounts are all running fine.

**Comment by PVince81** [comment] 2017-12-11 08:59
@mmattel does the error also happen if you don't specify `--repair` ?

I suspect maybe a federated share. Sadly it seems the log output is not showing the whole path.

**Comment by mmattel** [comment] 2017-12-11 09:53
Just running a ``sudo -uwww-data ./occ files:scan --repair user_1`` will let you know the result when done

**Comment by mmattel** [comment] 2017-12-11 10:38
Bad, same error at the same folder:
```
Starting scan (and repair) for user 1 out of 1 (user_1)
    0 [>---------------------------]
    0 [>---------------------------]
    0 [>---------------------------]
    0 [>---------------------------]
Exception during scan: ErrorException: Undefined index: size
#0 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(421): OCA\Files
\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/var/w...', 421, Array)
...
```

**Comment by mmattel** [comment] 2017-12-11 19:47
The fileid in question = 95899 in oc_filecache has following data
![image](https://user-images.githubusercontent.com/3321281/33848127-1c4783b2-dead-11e7-8172-d5564ac74ce8.png)
The content looks fine to me.

Looking into the code and because of the error reported: ``Undefined index: size`` in L421

Function L371 calls via L380 function L397 and errors at L421
**If you look into the code lines between L371 and L380 ``$size`` gets nowhere set !**

https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Scanner.php#L371
```
protected function scanChildren($path, $recursive = self::SCAN_RECURSIVE, $reuse = -1, $folderId = null, $lock = true) {
```
https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Scanner.php#L380
```
$childQueue = $this->handleChildren($path, $recursive, $reuse, $folderId, $lock, $size);
```

https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Scanner.php#L397
```
private function handleChildren($path, $recursive, $reuse, $folderId, $lock, &$size) {
```
https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Scanner.php#L421
```
} else if ($size !== -1) {
```

**Not questioning why L421 is needed, but quering something that is not set must fail...**

**Comment by PVince81** [comment] 2017-12-12 08:57
@mmattel beware, L421 on v10.0.4 is a bit shifted compared to master, it's the one with the array, see https://github.com/owncloud/core/blob/v10.0.4/lib/private/Files/Cache/Scanner.php#L421

**Comment by PVince81** [comment] 2017-12-12 08:59
I wonder if this is related: https://github.com/owncloud/core/pull/29739
Can you try applying it ?

Basically maybe the file does not exist or is not accessible for some reason, and instead of returning a null array form `getMetadata()` that tells "the file is not there" it returns a partial array. A partial array would be missing the size attribute.

**Comment by mmattel** [comment] 2017-12-12 10:40
You are right L421 in 10.0.4 points to ``} else if ($data['size'] === -1) {`` which is in master 2 lines above at L419...

I tested #29739 and HURRA it works now.
```
sudo -uwww-data ./occ files:scan user_1
Starting scan for user 1 out of 1 (user_1)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 13652   | 91024 | 00:08:32     |
+---------+-------+--------------+
```

**Comment by PVince81** [comment] 2017-12-12 10:43
@mmattel great to hear.

Can you check the actual file/folder on disk and see what its permissions are ? I wonder why the scanner would have trouble with it.

**Comment by mmattel** [comment] 2017-12-12 10:45
will respond later, just on the way to London...

**Comment by PVince81** [comment] 2017-12-14 09:10
@mmattel you likely had a file with NFD encoding... see https://github.com/owncloud/core/issues/28181#issuecomment-351645276

**Comment by PVince81** [comment] 2017-12-14 09:10
Closing as duplicate of https://github.com/owncloud/core/issues/28181

**Closed by PVince81** 2017-12-14 09:10 UTC
Labels: bug-analysis
