### ISSUE TITLE
[Share api] Error message is shown when setting a password

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#18713] opened 2015-08-31 15:01 UTC
### Steps to reproduce
1. in the web, select to share a file
2. Using poster or curl, obtain the share id
3.Using curl, set a password
curl -X PUT -u admin server/ocs/v1.php/apps/files_sharing/api/v1/shares/2 -d password=aaaa

### Expected behaviour
Password is set

### Actual behaviour
Error is shown 
``` <?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>400</statuscode>
  <message>Wrong or no update parameter given</message>
 </meta>
 <data/>
</ocs>```

### Server configuration
Operating system: Ubuntu 14.0.4
Database: MySQL
ownCloud version: {"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

**Comment by karlitschek** [comment] 2015-08-31 15:32
@schiesbn can you have a look?

**Comment by purigarcia** [comment] 2015-08-31 16:10
it does not happen in {"installed":true,"maintenance":false,"version":"8.1.2.0","versionstring":"8.1.2RC1","edition":"Enterprise"}

**Comment by SergioBertolinSG** [comment] 2015-09-01 08:47
I've tried this with master version 8.2 alpha (2015-09-01), it returned 100, no problems with the petition.

But, there is a problem with the public share, when you open it you have to be logged in to see it, and you shouldn't need to be.

**Comment by rullzer** [comment] 2015-11-15 19:49
I can't reproduce this, not on master and not on 8.2.0

@purigarcia I assume you shared by link?

**Comment by rullzer** [comment] 2016-02-02 09:11
Still can't reproduce this. And we have intergration test to cover this. And it all works. So closing this.

@purigarcia please reopen if this still happens.

**Closed by rullzer** 2016-02-02 09:11 UTC
Labels: bug, feature:sharing
