### ISSUE TITLE
Exlude Sharing not working when not all groups are listed

### ISSUE THREAD

**Issue by SerialG** [owncloud/core#15837] opened 2015-04-23 14:43 UTC
Hi, 
I experience the following issue with sharing exclusions on owncloud 8.0.2 (CentOS):
GroupA is listed in Option "Exclude Groups from Sharing".
An LDAP User (Active Directory) User1, which only belong to GroupA won't have the Sharing Options.
An LDAP User User2, which belongs to GroupA and GroupB will have the Sharing Options. 

(Groups also belong to LDAP Active Directory)

This make mostly impossible to use this function in a company, where LDAP Users will always belongs many groups and not only the one excluded for sharing.

Does someone has expierenced this? Is there a workaround or bugfix already available?

Many thanks anyway for your wonderful job!

**Comment by karlitschek** [comment] 2015-04-23 16:36
@blizzz @schiesbn what do you think?

**Comment by blizzz** [comment] 2015-04-23 20:15
Same behaviour for local groups.

**Comment by blizzz** [comment] 2015-04-23 20:50
Code-wise (including comments) it is intended behaviour, see: https://github.com/owncloud/core/blob/stable8/lib/private/util.php#L161

Not sure why it was done like this. @schiesbn ?

**Comment by nickvergessen** [comment] 2015-04-24 09:11
Well, it's the question whether we want Yes to overwrite No, or the other way around.

**Comment by blizzz** [comment] 2015-04-24 09:30
Exactly. I assume we have a reasoning somewhere.

**Comment by SerialG** [comment] 2015-04-24 12:22
Thank you for pointing me the code.

Why not let choose the admin with a checkbox? 
- Member of ALL groups
- Member of AT LEAST one group

**Comment by blizzz** [comment] 2015-08-07 08:16
@schiesbn if you could enlighten us… ? :smile_cat:

**Comment by schiesbn** [comment] 2015-08-07 10:51
This was the intended behavior we agreed back then. Every group which is not selected is allowed to share, so as long as a user is in a group which is allowed to share he will be able to do it.

We could add a option similar to what was suggested by @SerialG. But in general the share settings are already quite complex, so I would like to add it only if it is a use-case many people are looking for.

cc @MTRichards because afaik we discussed the behavior in the past and agree on the way it works now.

**Comment by MTRichards** [comment] 2015-08-07 11:45
Yes, this works as designed. When originally requested, the ask was for an "exclude groups from sharing" option. And, at the time, the request was that yes overwrites a no. Since then we have not had additional input. Let's gather some before making additional changes.

**Comment by SerialG** [comment] 2015-08-20 08:17
Thanks for the reply and explainings! 

At the moment I fixed it with a workaround:
In the function isSharingDisabledForUser() in https://github.com/owncloud/core/blob/stable8/lib/private/util.php#L161

I changed the array_diff() to array_intersect() at Line 161
Now my function looks like this:

```php
public static function isSharingDisabledForUser() {
	if (\OC_Appconfig::getValue('core', 'shareapi_exclude_groups', 'no') === 'yes') {
		$user = \OCP\User::getUser();
		$groupsList = \OC_Appconfig::getValue('core', 'shareapi_exclude_groups_list', '');
		$excludedGroups = explode(',', $groupsList);
		$usersGroups = \OC_Group::getUserGroups($user);
		if (!empty($usersGroups)) {
			$result = array_intersect($usersGroups, $excludedGroups);
			if (empty($rresult)) {
				return true;
			}
		}
	}
	return false;
}
```

And it works! 
I'm aware it's not a "clean" workaround, because I will have to check for and after every update, but it actually works.

**Comment by PVince81** [comment] 2016-03-02 09:48
Closing since this is expected behavior as per https://github.com/owncloud/core/issues/15837#issuecomment-128681376

**Closed by PVince81** 2016-03-02 09:48 UTC
Labels: discussion, enhancement, feature:sharing
