### ISSUE TITLE
Code integrity check should have configurable white list for extra files/folders

### ISSUE THREAD

**Issue by DemoFreak** [owncloud/core#23977] opened 2016-04-13 14:41 UTC
### Steps to reproduce
1. Have a web server with some standard files or folders like /stats or /error, which are i.e. created by configuration tools like ISPConfig
2. Install (or upgrade to) OC9

### Expected behaviour
No complaining about code integrity check failures.

### Actual behaviour
The warning message disappears never, as this extra folders can't be deleted.

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- stats/hourly_usage_201511.png
		- stats/hourly_usage_201501.png
		- stats/ctry_usage_201601.png
		- stats/usage_201410.html
		- stats/daily_usage_201508.png
		- stats/ctry_usage_201504.png
		- stats/daily_usage_201502.png
		- stats/hourly_usage_201505.png
		- stats/.htpasswd_stats
		- stats/usage_201603.html
		- stats/hourly_usage_201604.png
		- stats/hourly_usage_201503.png
		- stats/daily_usage_201410.png
		- stats/usage_201506.html
		- stats/hourly_usage_201603.png
		- stats/hourly_usage_201507.png
		- stats/usage_201510.html
		- stats/daily_usage_201510.png
		- stats/usage_201508.html
		- stats/hourly_usage_201509.png
		- stats/daily_usage_201501.png
		- stats/usage_201512.html
		- stats/webalizer.hist
		- stats/ctry_usage_201511.png
		- stats/usage_201507.html
		- stats/daily_usage_201411.png
		- stats/daily_usage_201511.png
		- stats/daily_usage_201601.png
		- stats/usage_201504.html
		- stats/hourly_usage_201502.png
		- stats/ctry_usage_201410.png
		- stats/hourly_usage_201506.png
		- stats/daily_usage_201503.png
		- stats/ctry_usage_201412.png
		- stats/daily_usage_201506.png
		- stats/ctry_usage_201411.png
		- stats/daily_usage_201412.png
		- stats/ctry_usage_201509.png
		- stats/daily_usage_201507.png
		- stats/hourly_usage_201411.png
		- stats/hourly_usage_201510.png
		- stats/webalizer.current
		- stats/usage_201503.html
		- stats/usage.png
		- stats/usage_201509.html
		- stats/ctry_usage_201503.png
		- stats/hourly_usage_201601.png
		- stats/ctry_usage_201510.png
		- stats/usage_201604.html
		- stats/usage_201502.html
		- stats/.htaccess
		- stats/usage_201511.html
		- stats/ctry_usage_201508.png
		- stats/ctry_usage_201506.png
		- stats/ctry_usage_201604.png
		- stats/usage_201411.html
		- stats/daily_usage_201512.png
		- stats/ctry_usage_201512.png
		- stats/ctry_usage_201505.png
		- stats/ctry_usage_201602.png
		- stats/ctry_usage_201507.png
		- stats/usage_201601.html
		- stats/hourly_usage_201504.png
		- stats/usage_201602.html
		- stats/hourly_usage_201508.png
		- stats/daily_usage_201504.png
		- stats/hourly_usage_201602.png
		- stats/usage_201501.html
		- stats/hourly_usage_201512.png
		- stats/daily_usage_201505.png
		- stats/ctry_usage_201501.png
		- stats/usage_201505.html
		- stats/hourly_usage_201410.png
		- stats/daily_usage_201602.png
		- stats/index.html
		- stats/hourly_usage_201412.png
		- stats/ctry_usage_201603.png
		- stats/ctry_usage_201502.png
		- stats/daily_usage_201509.png
		- stats/usage_201412.html
		- stats/daily_usage_201603.png
		- stats/daily_usage_201604.png
		- stats/dns_cache.db
		- error/503.html
		- error/400.html
		- error/502.html
		- error/404.html
		- error/401.html
		- error/500.html
		- error/405.html
		- error/403.html

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [stats/hourly_usage_201511.png] => Array
                        (
                            [expected] => 
                            [current] => bfed174a92628fe23c9d599d36f574324f7bf45699c041ae96e81182a0b53e1a87b999104e64e936f920b3cf80620bc3b491cbf2ebdf0cde6741a8ebf32295d0
                        )

                    [stats/hourly_usage_201501.png] => Array
                        (
                            [expected] => 
                            [current] => b23366a510d5c2565a638af7367e6de45770f2fb822cccef74eefef7a616f908e9c6d3d5777de6108757bf06ebd48a60ef526b26ec399a2c872bd8f1ae812e1c
                        )

                    [stats/ctry_usage_201601.png] => Array
                        (
                            [expected] => 
                            [current] => 3e789987eb9436ba9867435c38b1dedbbb60c73a69b1ba57d9365a00222ba9502bd66b398ea547cf54354b8f6f06a2ea695cc1aa4978a22f7e88a53fe1dd8ac0
                        )

                    [stats/usage_201410.html] => Array
                        (
                            [expected] => 
                            [current] => 7ba10833fe167a6a3dcad6175e663bb43c58c228a96307b1b8e006ead39e44a6f69b3cdf48c1cb4d329531296d830db93f4a37db59f62dadd78c749d891283be
                        )

                    [stats/daily_usage_201508.png] => Array
                        (
                            [expected] => 
                            [current] => 286c41945007e1e7874a127757e326ab3be66819680c02a01dfdc5ab91f6a5b487cb7951f642bae97bd6c1a70cc5884aa254a15abdd219e2854f40bf3063c4e5
                        )

                    [stats/ctry_usage_201504.png] => Array
                        (
                            [expected] => 
                            [current] => 2d5b5e58e80a6e901299af8daa5a3a15e63efc9124f6cc43ae2a3c2c50a75760c2b55eba97bba810f3c70220bdc8437c2920d83633669ea20caf6873d4943f7e
                        )

                    [stats/daily_usage_201502.png] => Array
                        (
                            [expected] => 
                            [current] => 4e233fd161138d8ce0a3228581ef84bfbc2f80d4617b709149da0f5e57e6d93589775fc9eda5f8d11ba9a9c545f189eef134e86195447040dea079e4593077a9
                        )

                    [stats/hourly_usage_201505.png] => Array
                        (
                            [expected] => 
                            [current] => e1fc5f9558c2f4eac19798cae70ce3a2dff9e0f44a7f5faa860840cc5dbdd55215ed855891d4e660f0b3f47d04d5bb197eca1f8bbd921bfebcbe7463d90589c5
                        )

                    [stats/.htpasswd_stats] => Array
                        (
                            [expected] => 
                            [current] => 093923a6c2aab3256b64d1620c9811ecafab9f3be6e560a0930a92a94b1180f34ef8b57b70d8f2934cdb7bf06038577e060b0b72db727bafebb6197131c00075
                        )

                    [stats/usage_201603.html] => Array
                        (
                            [expected] => 
                            [current] => bdb44f2dc1df78e5294d38d8c22eb32282afa5fe2d74d7f4fe565f320ecc971a3cbbf37bc7f47b2c4d452b84fedcc6a074e12e5daa7a556d4c21c525f7d00696
                        )

                    [stats/hourly_usage_201604.png] => Array
                        (
                            [expected] => 
                            [current] => 07d0c1970abc59a372f036434ab2b4090f42589e351a58dca43d0f7818c0596b5b83bb085ed7f6da6437e6a9b093db054a1a260a8bc4cdc47d1f97f701678045
                        )

                    [stats/hourly_usage_201503.png] => Array
                        (
                            [expected] => 
                            [current] => 052f97085faefa6af95cdfdac2ee9bbc52cb822b73a0ab77fbcd6064a4c99a54602419af732c8066595d4b879e1db9f83bd121bc06b2d1f8837a66b633564a40
                        )

                    [stats/daily_usage_201410.png] => Array
                        (
                            [expected] => 
                            [current] => f61d58a1d3f6ecc6e217269aadc19312b889da28b59407f63a5ad36735f9f351608b3d239eb7fbb76a3df808d699ba057e64e5199faf752d1c63d6a160292b54
                        )

                    [stats/usage_201506.html] => Array
                        (
                            [expected] => 
                            [current] => 541cc814df232d7a9bb7349d1042ea8f0a299d172c104bf25a9890a8d23f3bb5ccac61497563771045ac1e7dfca9c1b424fb92abfd7f2ce30f279d7fd27fffaf
                        )

                    [stats/hourly_usage_201603.png] => Array
                        (
                            [expected] => 
                            [current] => af514a6aaec13d488ebb6f9de2d560d5fd29c80769599dfe20ac44a0b783165708694d3d670908610e6dafb9f8378517b28577c4e7126f894e983b59813e55bb
                        )

                    [stats/hourly_usage_201507.png] => Array
                        (
                            [expected] => 
                            [current] => 4c8bc8d6366d83f7e42f429dd9db58f8547f184e5e29882fa6d81c392480f165dd0d52f6fd6649df8a18549c2f95a03ed5337f9d2cba8683bcba78f446400234
                        )

                    [stats/usage_201510.html] => Array
                        (
                            [expected] => 
                            [current] => 17cdc2a658f7c76c9db38c212ebfaf3fcb4cbd7db7a7993d3cf54ab330a764b67e03733a4713685569de7bebfd9bb63c7884ae90bea2a4705bf4e043293402a0
                        )

                    [stats/daily_usage_201510.png] => Array
                        (
                            [expected] => 
                            [current] => 2a420fd7dc67f7eecb77f39b2ef9184d25075a35e77e7420eebc82352a900bf8328271f34c34f933cea88178d08dbfa499757e1917e6a2b146481a05ead12806
                        )

                    [stats/usage_201508.html] => Array
                        (
                            [expected] => 
                            [current] => 66f0b2685d7929a0ceeaac5cf1a456f487654c91f0b21b079e56ebdf00b94276caa7cb757b2660b55460182e0f59f31dcf89feb34b4f177c762ab5592ecbc59c
                        )

                    [stats/hourly_usage_201509.png] => Array
                        (
                            [expected] => 
                            [current] => 0ff1b074cc6b1d2f612b1f1db8b1f19421f3da7f3b388266dbb38f525cbba4d16a6b1d7aaf5ad6057517593a8ffe75c23e0beb497999da5f4bacd5794c2f81b8
                        )

                    [stats/daily_usage_201501.png] => Array
                        (
                            [expected] => 
                            [current] => 71d7eed35641cb765e9b36c9345070cb70eabfb26db746550f42644d2d822f63d8aa3e3b074c29091f5134395c9a83f26f203b11ebf172797c34b9b8695d72f9
                        )

                    [stats/usage_201512.html] => Array
                        (
                            [expected] => 
                            [current] => 07d84357c947c7b1e3b3de456a811491da757d0ae0ad98a8ebc0d04369a9c29ecf348f8825ee1405cad701d91b86a544d3fa1a541364fc704072eeffa0034b89
                        )

                    [stats/webalizer.hist] => Array
                        (
                            [expected] => 
                            [current] => 9bd91658292204b47e2a4f07adbd0a93ce7fc0b97ef2e0b5cceb768dd75700f6009a214c5881620ec668132ac4c7adfb479c72fbe8b865f57a2ff4e5209ddc9e
                        )

                    [stats/ctry_usage_201511.png] => Array
                        (
                            [expected] => 
                            [current] => b7c27a1c2dd406745b9764c081cb6e556675b940bbfd6888486b33b0188b9112c4d20ff60f3497ed10120a40f815cd7ec757ee360199a4108a67204aa63b084d
                        )

                    [stats/usage_201507.html] => Array
                        (
                            [expected] => 
                            [current] => ff1511740cce6c2a241d96f04cbf3056239de8dfe8e5451b9a6142f9f83ae56b6c8b00f0672f3418ae3b1924b08f3013ac9372f9ec6e24320ac8fe62c8947f30
                        )

                    [stats/daily_usage_201411.png] => Array
                        (
                            [expected] => 
                            [current] => 6f826387860af8ceaea8c58bb8dcaf76ca570fe5261502c3d8ac2fd84fc9fc5a542bb459a069bbb42cd5f95da42958e7e4e0ae7358c5d2f680798646729886c3
                        )

                    [stats/daily_usage_201511.png] => Array
                        (
                            [expected] => 
                            [current] => 54057d92a1e6cfa28396334cc136539362ccb134483e74450967b851fab0b8f1c1b0bc6128c1bd0aa3fa7b39cf77d673152d7cd4dc82ba39d2c0bc885e9d673e
                        )

                    [stats/daily_usage_201601.png] => Array
                        (
                            [expected] => 
                            [current] => 18d98132d167bf2137f46c59aaa468074fc4af06db7b874223b2a98c99e8bebd6dc10961ac01a9e0ddf3f59cf6db5280cea93e432b9f6be218d798f323266ad5
                        )

                    [stats/usage_201504.html] => Array
                        (
                            [expected] => 
                            [current] => 4e8d1565607ea82a4e37eb6e8379fe9d88cb37b62a706647b10ec3298cb26421248e29158d62ac863576c90596387925316f8f9c44754617261c2ff8c83c68dc
                        )

                    [stats/hourly_usage_201502.png] => Array
                        (
                            [expected] => 
                            [current] => b18c7fb322701930a35e931acb345b1652348bd2f8aa9dde88b29e06f5f8373c1c452423069fd303efb12ea5a87cb971c82daeb2849e783d8a7e92f92e89a838
                        )

                    [stats/ctry_usage_201410.png] => Array
                        (
                            [expected] => 
                            [current] => ef81369948ebbfcb5dc4841e9b9c01d598ab8a9735bd618a9c5f764bd5f3683d38242a8274a14bfc9f74770c060678d0d621ebc0687bc4466854163656a6785d
                        )

                    [stats/hourly_usage_201506.png] => Array
                        (
                            [expected] => 
                            [current] => 9f0805fd2d5058c9d3188f1db3c38e26fc3f432dda2830328363d7d3f4ea7dc9e2e7eda68a0e66979ba06328b18fcb166e1f0fd5a0c9cd19f9c55eeeed63d85e
                        )

                    [stats/daily_usage_201503.png] => Array
                        (
                            [expected] => 
                            [current] => dd9465d7228ae87c14175ef0cbf9dc7fefa43082397ac97bc51937743d740f2fffba15f4547aeb027f3c38b87f63cb86629f67d035c367fb7b2bd69f4b179d99
                        )

                    [stats/ctry_usage_201412.png] => Array
                        (
                            [expected] => 
                            [current] => 5581199f93fa4ee9808199f1325886a9da0652e34b0dec3f6ecbeb55b46ca4c0a2b55d501103e6046516711b0af9afab892002e3f6b740c9a68064c7f077d59e
                        )

                    [stats/daily_usage_201506.png] => Array
                        (
                            [expected] => 
                            [current] => 94f54c61f5e50948e289f5d9f21f4a3b6db41ed7a9fc7cacfc35b15c4a85e9c0bb44b20a8ee59c0657242661fc0bccc3e22ffc282f67349a2f77d05c16ac2f8a
                        )

                    [stats/ctry_usage_201411.png] => Array
                        (
                            [expected] => 
                            [current] => 15a5ef51fad4667d3d649ef5b7132411625af0f17b0324dfe18371eeb9dd324bd97b18118e5414afadabbb7cd08fed0e2198369d8f5bcf94c4ee069de9a1c846
                        )

                    [stats/daily_usage_201412.png] => Array
                        (
                            [expected] => 
                            [current] => 09675959d11971a2c337972eed03254570c30c51ad72b689496f4ac53aaa5ec0077d67672bb5be85c13e0d6b4f77d52111c179fbdbefa20859f8a406f60031d7
                        )

                    [stats/ctry_usage_201509.png] => Array
                        (
                            [expected] => 
                            [current] => 8a67c424a50d6503c91b3577e3bd7744352c8f7edf635298acf189c5b8d06501b2ef6fcd9b8ddcb8ff437e32ee0f38e10b989b085d74882e0081747cb96af08a
                        )

                    [stats/daily_usage_201507.png] => Array
                        (
                            [expected] => 
                            [current] => 71af355c225976f342bcb722d489537486f1ba67222ed038dd514039fbef85d2d093842ac7b3ae6f0e167e75aafbd36c70af58f1685b924f94f1112d6e4af399
                        )

                    [stats/hourly_usage_201411.png] => Array
                        (
                            [expected] => 
                            [current] => 24d7e97da799c0ef0d8b110d5dedf9507bcf0605bb8a20110529d5c1c74b844b14978b20a2fc8930e305365a1f351daa4e1fa8d6be918e6881e9ef3d29852b8a
                        )

                    [stats/hourly_usage_201510.png] => Array
                        (
                            [expected] => 
                            [current] => 75a6a72d6eb41d76b62524e6bbef3dde47111265c7f1bd93335182bf8b8408386f4dd7238a2deaf71ede610720ea80182197965591cff438eee27ef7eb572cee
                        )

                    [stats/webalizer.current] => Array
                        (
                            [expected] => 
                            [current] => d57b378208aef3b0240d4fcae28e0f5a16b32d6f31cf47e47927e4b561230fc55e3120cf1fb069251fa50eea21599eb22e78e68d0b8571ab04c8553d6cc54bcc
                        )

                    [stats/usage_201503.html] => Array
                        (
                            [expected] => 
                            [current] => dc7d0156935c0752f0886eae946adbcd4f31a4630b6f847533ab76d1ff743534330653527c7ce78d5e9e7e347716e2b4b77ef3bc703d07fce8e7812d4f63ea47
                        )

                    [stats/usage.png] => Array
                        (
                            [expected] => 
                            [current] => 293baf2d26518a445c9da5153f94ad8837406045cc706b4e6b7ba28740c5fd41e81ce15a8471d0719332dfb3089b0361abb04436c665254272e6a1819a0a593d
                        )

                    [stats/usage_201509.html] => Array
                        (
                            [expected] => 
                            [current] => 7a9d1b44fba5f160bc5c445a7e8cb36930686d9be93b64a99de61eda7776dc06db18598f9c942046d2a944c1cb53694ed3492c6aa74afdacd5af6b3223a43e70
                        )

                    [stats/ctry_usage_201503.png] => Array
                        (
                            [expected] => 
                            [current] => 956f7635a9b6d56db0c2c782eb5a570cc531e9f5f168b2f6698eb33890b1524af72c12d50e0145b15eafc7616ba7c08809489cec0397123035341bcccbd03341
                        )

                    [stats/hourly_usage_201601.png] => Array
                        (
                            [expected] => 
                            [current] => 17ee543f3e36987e24eefd331c077f089aac92f6a0184aa035fb21a9d4c91ad141ac52373a9ab0633a89c17fff3ae4be3af1a1bea346ebb3b4b705b0f205675c
                        )

                    [stats/ctry_usage_201510.png] => Array
                        (
                            [expected] => 
                            [current] => 746757aedb66d7da52cc936637a6a8a5c650bfbee2ef5cc55eae24883da6b8a9eb0a082deae8f940e16a6105cd384a6e3f74ff507a29bc7f8ad8f4e202c45957
                        )

                    [stats/usage_201604.html] => Array
                        (
                            [expected] => 
                            [current] => b53533570a747926e83a24646e8cfa2834957122f07e053ebc4cb635fadfd535bf8c05c8459d279381554368bd14a90d17118e298d9913e74fe9b47b96b305e8
                        )

                    [stats/usage_201502.html] => Array
                        (
                            [expected] => 
                            [current] => 2cf687036b15b1e72b2ca1bede60f1f83f1fcd0edb40c2ed4abca55e2e6fe6265a6a2db49d3dacdf670a170a30ffca50d7159d1c32d93b27e51a61f6361b6c62
                        )

                    [stats/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => ef635ba883700d2e940279341075288d1ee5a2978580c3ba9345423347cb6bae8e0111ca9b52e532b61405acc17f4e0b73ddb520d35eb7170c5ed7aeeddcb744
                        )

                    [stats/usage_201511.html] => Array
                        (
                            [expected] => 
                            [current] => 0983da34ad10dada9616f4796d60e7b0816f9fc96d02dfd1a7d2eb16d44aca0764afdfa44b1939408e0a57399f8170dbb56460a7d083db93e2e29f0ae8d49e2c
                        )

                    [stats/ctry_usage_201508.png] => Array
                        (
                            [expected] => 
                            [current] => 6783fac8b1e1956850eeb05f3992b42491b8c04e42c0bfb9fee8347dca51bfa7e3e7b62ae4ef76d7fdf7fd9c3cdff221662742729da546a4a7001a37c13911d6
                        )

                    [stats/ctry_usage_201506.png] => Array
                        (
                            [expected] => 
                            [current] => 444c02de713db1362d1ff6bd38c2bb2c7b2fbef94a6b1479b6411448cc8d143d5ea892d792b867f13ed88122ed22c42cce2b44c10cd50bbae359601a34abb5f7
                        )

                    [stats/ctry_usage_201604.png] => Array
                        (
                            [expected] => 
                            [current] => 1c1a3400454c8cbd191777560c4a6dce34a90a5700a9b6ddaa05c2e2533fd01804b2b00258209601c56101d40a14f935995990ee016f66f4f62fc4d524d140f4
                        )

                    [stats/usage_201411.html] => Array
                        (
                            [expected] => 
                            [current] => 981c61eef1e2b6b55c04e6f241bb24d4230def641819cac6009795fe8cb76f19a8ed1558f1e7c137a7a0b9225781bf9eb103d2d77c5ca3213b3db7a0f67cd03d
                        )

                    [stats/daily_usage_201512.png] => Array
                        (
                            [expected] => 
                            [current] => 71bcee1f07948acdad007b881b89e837612ff242e18f31688a68a76d64ce0eef1092916c5bd2527a45d63c2e5873fc9895a275f9a72b655d9c167fab7204c078
                        )

                    [stats/ctry_usage_201512.png] => Array
                        (
                            [expected] => 
                            [current] => 980001366009108306df1e2519fd0ac0a14cd03ee72a8e591565d74d413d12bc6dd3869a0cf2fa6c61c565d2ab68b93fe778be97037f69e2385bce1c3d64cfdc
                        )

                    [stats/ctry_usage_201505.png] => Array
                        (
                            [expected] => 
                            [current] => e04e78ba431692e21d23ae2208376f29a197cdef219640d07ccfdb0440c24d4af4f4aceb95de591d9fc8c627f050674b8c4e842b2fdb7aa322af3bf4b46353fd
                        )

                    [stats/ctry_usage_201602.png] => Array
                        (
                            [expected] => 
                            [current] => d6c65c7bc89cbd6dcf563d94d5b8dc950098f0a38e7dd08921b5e61bdbdbc6621eab908d5d1dd60a9576b18aa76a6428a5ea55acefce15f3a95dbc79d27d8a3a
                        )

                    [stats/ctry_usage_201507.png] => Array
                        (
                            [expected] => 
                            [current] => 8c6a8db43ad0e55a85707e7bc432b2da199764fb8abacda3e22ae3bb9ea54facf187fed9173c078d3fcf9b265d68eaf3fc88790a6c6c7a2c65e2a65bfd2c22ba
                        )

                    [stats/usage_201601.html] => Array
                        (
                            [expected] => 
                            [current] => 7eb7554e734001c327748021cfcedfcc867eb97c025bfdec5da902bf7a8036156bdd3529fa8a91931d7cbafdc6c795f130b9af2887de9bd572d240c59d0d3a4a
                        )

                    [stats/hourly_usage_201504.png] => Array
                        (
                            [expected] => 
                            [current] => 0d74f057b930907128a8f4225b5b3c4db47ddfa9159d7a5be8467c29fe6c8051780b78eadfc79e5a8e4595159f59164d5180f72f60d72c31e83028736840a4dd
                        )

                    [stats/usage_201602.html] => Array
                        (
                            [expected] => 
                            [current] => caf10c44bb86579718ed041ec6a35d8989afe00cec44979febc21da4177ee95a221b7dcbceb2ee255eec24e62af7bb2ccc88e73228fa23825426316e1aafc9b0
                        )

                    [stats/hourly_usage_201508.png] => Array
                        (
                            [expected] => 
                            [current] => 8e7a15da9895fc759b5ef853978f7c66b18d21da263dca6893361a757112d418469b14795aa67e804b8bf2e2fc2701a7d72e77df59efd70c2337c75bc7574b51
                        )

                    [stats/daily_usage_201504.png] => Array
                        (
                            [expected] => 
                            [current] => f368407306d2565e4451660e62d1e7c38d7bc19ccf29438515fb13d242866a16ca260eb0d1234b373572b1084eb76fc9370b80baa860d2b851b2df6e733331da
                        )

                    [stats/hourly_usage_201602.png] => Array
                        (
                            [expected] => 
                            [current] => be56c8a0f80759b4881024ab371940c24e813d088009fe9511b8f895241a536fb41fe909f3377e97c682e8baca230c277ceec73fda0956508d0a3432e426591a
                        )

                    [stats/usage_201501.html] => Array
                        (
                            [expected] => 
                            [current] => 10b5708dd3ec35a6f6dc92cd9ba523e71c0bee52ba44fa854edcb4e53727807324f731d720cd24647a256b8b7941a1a370b559e45a789d5011a4bd55ce79371b
                        )

                    [stats/hourly_usage_201512.png] => Array
                        (
                            [expected] => 
                            [current] => ff96ad5ef4b1c372421cff4002ef87a24eda6f7758cf42e1e6dc76a2edaf61208b80b79b7d4a798627b4e582f0e175033628232c21e6618b6f3bf427a16d15e2
                        )

                    [stats/daily_usage_201505.png] => Array
                        (
                            [expected] => 
                            [current] => db2084ac4259b25f427eef3dbdb5d7847792ff6416f5cbb2bfa052aa9c04638842ee578eacdd030b2789daaa023cccd0986f6b19e2d34f5c2e928eeced015ee9
                        )

                    [stats/ctry_usage_201501.png] => Array
                        (
                            [expected] => 
                            [current] => 34eea51078a4d69f41617608ff8edcf584f5e2510fb1914a8dda897e37e0d770527e66fea582d70e5410ef1f18936fb6635d502e26c753a6c1cd20d768fb7ba8
                        )

                    [stats/usage_201505.html] => Array
                        (
                            [expected] => 
                            [current] => d2c912210e67db0b8e57a83e883c40a513aa1c943ee63d1fec6c1f7b87a45c237b3a45b0f0d68c20209418a8d60adb7fea54bb1cf105ad9f6e7e64139743a89b
                        )

                    [stats/hourly_usage_201410.png] => Array
                        (
                            [expected] => 
                            [current] => 69cf5b878dbe3da33493aaa18ee0cd59f08e98bde0792e00a75d0435cf2f866e90b6f561e2799c268da1798a20210397ece9d946c9d02cb3d1b90b78daabd32e
                        )

                    [stats/daily_usage_201602.png] => Array
                        (
                            [expected] => 
                            [current] => 9292c2daae3f2fdc00f0426169c61b757fdfe48af0a2b606e1229e5ffc4de68bc8ecdcdd03fb11fa0eb90f5577663192d5a960c48aabe2fe854b773a6153d393
                        )

                    [stats/index.html] => Array
                        (
                            [expected] => 
                            [current] => f3b4440e094dd8c4410c0d02101638e0bf954248ef67e3a8130c88d1230eba1c02a7d99286f64bf4b09b1826952c934472d7cda6a1cfc0d10457afcf21cbce70
                        )

                    [stats/hourly_usage_201412.png] => Array
                        (
                            [expected] => 
                            [current] => 588d971c577ae0ecf94b5e683a36c835d669147469f5a8774ec1bb152629e458d2e13c5b25b4d3685b93147f2e8f483de28b311f87b313a9990c8d82721b0b50
                        )

                    [stats/ctry_usage_201603.png] => Array
                        (
                            [expected] => 
                            [current] => 8f2553d1f462952f080eab01ba188648d1f255666980d1e13220e2b3dc1cbe5729dfc7468651513d3c969cf9bd92e7515dae2e7ed86dba4e30c73eb702a21643
                        )

                    [stats/ctry_usage_201502.png] => Array
                        (
                            [expected] => 
                            [current] => 6bbf358c28d5048cf624a1f4a49ef6ca0480df9ea02f22c6e3886e051205771db4aa9594176ae844902b0cca7a47fd467a2e7e5521479343d5bfa72a2e6be70c
                        )

                    [stats/daily_usage_201509.png] => Array
                        (
                            [expected] => 
                            [current] => e61663573f4572bf58f925f2887180688acb2c5f32bf026e062c756f42547d7f7ff943b4981a7308016d4e5f7625c7d7a19f5f1a47b8bdc1db17f81b7122c1a0
                        )

                    [stats/usage_201412.html] => Array
                        (
                            [expected] => 
                            [current] => 3ebfa301f695e75e8dc97899123b7c1dc9c91821aa956ea27c711ffbea68400a211a170385f89d46dfa21541c2e0975f1734ba8f933572b8373c2757a036d1ac
                        )

                    [stats/daily_usage_201603.png] => Array
                        (
                            [expected] => 
                            [current] => 56c7e37ed476ecfe97f8e5eb3889d638d7c21002f4a862379bcc2e413b6d2b11312a768b609a2815e3ead0ad5356a13c86a41ac27b1a1dac1e73440b43e583a6
                        )

                    [stats/daily_usage_201604.png] => Array
                        (
                            [expected] => 
                            [current] => a4273f29437f97ff3c4f1396a45ce9e0ae3fa2b2139885d7df520a1850c049f6fdc1c36bbd99c6a5dd22acdd5ef9a95e3d4cf3310101a9bc24352c7dfb8645e3
                        )

                    [stats/dns_cache.db] => Array
                        (
                            [expected] => 
                            [current] => 3a561c79248d72bda0ddeda37f269aa756e0f9d90e583d5e6809f19ad1d5a805a63c0eb66e384cdd0f5a4247c9f64e649e9628670d3aa2add933e0c1c65f4de8
                        )

                    [error/503.html] => Array
                        (
                            [expected] => 
                            [current] => e06fbb0c14eeafc5e247a264714de766c839756bdc4946042584c0c1dc9caba3f15e47be532ac72f59872ffccaabcd376ff99ddb3b7d4e6af4436768083bb158
                        )

                    [error/400.html] => Array
                        (
                            [expected] => 
                            [current] => 3569e8939479b680d332aed3e9a1f7d978069f13d1514f6fd1d3ec9b13c83d83ae0b4def5f21d53fb0e07d3c7adfb7ae07802d3096aa5c4af67acfcb7c2a694b
                        )

                    [error/502.html] => Array
                        (
                            [expected] => 
                            [current] => e6e55ada4f0501a174b1b542816b3c6e3e373991056faf374867a778755fa2e0e34e1d57c0d758edf30e5df539e70685173ab17e1cdd9a228bf28d5daf307109
                        )

                    [error/404.html] => Array
                        (
                            [expected] => 
                            [current] => a9e36844697823a141aee250a1059d902d587e5801aa7d96bcc08d5a0f17de9dba59cd6c378f42b21e1d9780d58b1e18b3fa9bf0526d9c0727e1505ceb6005e2
                        )

                    [error/401.html] => Array
                        (
                            [expected] => 
                            [current] => e6ba03a8ccd6c5c97b29c91ac2ac41e0aef0ac3be00f7888dfc4bedff2260972d76d28068ef3786c4989990883ffa8d96316ec6b1fb0399c4f6794a2fad77c6e
                        )

                    [error/500.html] => Array
                        (
                            [expected] => 
                            [current] => f48893930f6d159a01a4bb144f5c89fadaad694ebb73a39363a8348fdf865b2315cde059f490781783733283701f3056fd540577506715a3a2454f97934e0b8f
                        )

                    [error/405.html] => Array
                        (
                            [expected] => 
                            [current] => 364e115ff7eaaa5ed77381553fa48409637cbc129cc1ce33bf3389b8beca7d0cf3c9c829fc19469b592aa6f832969495c83ea3e766d1dbaff86410309c243771
                        )

                    [error/403.html] => Array
                        (
                            [expected] => 
                            [current] => 2e6167149fe6d1d94d8f0e08ef0d567e087b567d530b6bf016b8d7c9d2d460171e24c8ef25fb23bd9e708a4e05877da8981e39d04a69dabc7f8f684f1f268495
                        )

                )

        )

)
```

A possibility to configure some extra files/folders should be added to config.php.

**Comment by LukasReschke** [comment] 2016-04-13 15:11
Technically this can cause problems with ownCloud as soon as we're adding files or folders called like that. Which is not super unlikely. Anyways, this is a dupe of an existing issue.

**Closed by LukasReschke** 2016-04-13 15:11 UTC

**Comment by LukasReschke** [comment] 2016-04-13 15:24
Dupe of https://github.com/owncloud/core/issues/23186
