### ISSUE TITLE
rmdir /tmp/XXX Directory not empty at /var/www/owncloud/lib/private/helper.php#XXX

### ISSUE THREAD

**Issue by valentin8709** [owncloud/core#24478] opened 2016-05-07 14:58 UTC
Hi! I've just upgraded to php 7.0.0 and oc 9.0.1 and tracked some errors, I can't find any solution for this one:
### Steps to reproduce
1. Just delete files via web interface
2.
3.

### Actual behaviour
Ecerything's seems to be okay, but the cache folders aren't deleted (server side)

### Server configuration
**Operating system**: Linux Mint 17.3

**Web server:** Apache 2

**Database:** Mysql

**PHP version:** 7.0.0

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** older

**Where did you install ownCloud from:** official archive

#### ownCloud log (data/owncloud.log)
Error 	PHP 	rmdir(/tmp/oc_tmp_0oiTQP-folder): Directory not empty at /var/www/owncloud/lib/private/helper.php#231 	2016-05-04T18:15:01+00:00
Error 	PHP 	rmdir(/tmp/oc_tmp_0oiTQP-folder/news): Directory not empty at /var/www/owncloud/lib/private/helper.php#225 	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_0oiTQP-folder/news/vendor): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_0oiTQP-folder/news/vendor/bin): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00
Error	PHP	unlink(): No such file or directory at /var/www/owncloud/lib/private/helper.php#227	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_4IEkmf-folder): Directory not empty at /var/www/owncloud/lib/private/helper.php#231	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_4IEkmf-folder/news): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_4IEkmf-folder/news/vendor): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_4IEkmf-folder/news/vendor/bin): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00
Error	PHP	unlink(): No such file or directory at /var/www/owncloud/lib/private/helper.php#227	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_OtCpAz-folder): Directory not empty at /var/www/owncloud/lib/private/helper.php#231	2016-05-04T18:15:01+00:00
Error	PHP	rmdir(/tmp/oc_tmp_OtCpAz-folder/news): Directory not empty at /var/www/owncloud/lib/private/helper.php#225	2016-05-04T18:15:01+00:00

**Comment by Xenopathic** [comment] 2016-05-07 16:40
What is the remaining file in /tmp/oc_tmp_*-folder/news/venor/bin ? `unlink()` is complaining it cannot remove a file due to 'No such file or directory', which assuming isn't actually the case, I'm guessing it's some kind of special file.

**Comment by RealRancor** [comment] 2016-05-07 17:04
@valentin8709 @Xenopathic Duplicate of https://github.com/owncloud/core/issues/24453

**Closed** 2016-05-07 20:12 UTC
Labels: bug, needs info

**Comment by ownclouders** [comment] 2017-12-21 01:10
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
