### ISSUE TITLE
Address remaining problems with new settings section.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27117] opened 2017-02-08 16:38 UTC
This ticket is a compilation to track problems found with the new settings sections.

Testing is tracked here https://github.com/owncloud/QA/issues/335
Now continuing using master.

When enabling a new app, it should create a new section instead of adding all of them in additional section.

@tomneedham

@davitol please add here the problems you find.

**Comment by SergioBertolinSG** [comment] 2017-02-08 16:44
I think admin and personal titles should be more clear, they are still looking like another section.

**Comment by davitol** [comment] 2017-02-08 17:00
Logs are not shown via webUI:

This PR:

![screen shot 2017-02-07 at 13 23 36](https://cloud.githubusercontent.com/assets/10596560/22691229/c8424672-ed39-11e6-96dc-78b852341769.png)

Previous versions:
![screen shot 2017-02-07 at 13 22 49](https://cloud.githubusercontent.com/assets/10596560/22691152/5da9051c-ed39-11e6-9da1-a3da7d3450a1.png)

Note: TypeError: 'OC.Log is undefined' is spotted in Firebug when we change 'what to log'

**Comment by davitol** [comment] 2017-02-08 17:05
@tomneedham 

* Clicking on setting menu, it spits the following logs in owncloud.log

```
{"reqId":"ofquu\/bHI\/mXaOSjJly+","remoteAddr":"82.159.139.58","app":"PHP","message":"Illegal offset type in isset or empty at \/opt\/owncloud\/lib\/private\/Cache\/CappedMemoryCache.php#41","level":3,"time":"2017-02-07T09:13:27+00:00","method":"GET","url":"\/index.php\/settings\/personal","user":"admin"}
{"reqId":"ofquu\/bHI\/mXaOSjJly+","remoteAddr":"82.159.139.58","app":"PHP","message":"Object of class OC\\User\\User could not be converted to string at \/opt\/owncloud\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2017-02-07T09:13:27+00:00","method":"GET","url":"\/index.php\/settings\/personal","user":"admin"}
{"reqId":"ofquu\/bHI\/mXaOSjJly+","remoteAddr":"82.159.139.58","app":"PHP","message":"Illegal offset type at \/opt\/owncloud\/lib\/private\/Cache\/CappedMemoryCache.php#49","level":3,"time":"2017-02-07T09:13:27+00:00","method":"GET","url":"\/index.php\/settings\/personal","user":"admin"}
```


* 'En' instead of 'English' in dropdown menu (same in other languages)

* Clicking on additional menu:

![screen shot 2017-02-07 at 10 19 17](https://cloud.githubusercontent.com/assets/10596560/22685072/2a949070-ed1f-11e6-98b8-258127de1291.png)

* IMHO if apps are going to be managed from the settings menu, the apps+ button should be removed from the left side

![screen shot 2017-02-07 at 10 22 52](https://cloud.githubusercontent.com/assets/10596560/22685166/97217c6c-ed1f-11e6-97e5-20317afdec0a.png)

* The following error keeps showing when clicking on any admin section

![screen shot 2017-02-03 at 14 47 15](https://cloud.githubusercontent.com/assets/10596560/22685424/88feb748-ed20-11e6-8a31-6b704b0dc8d6.png)

**Comment by DeepDiver1975** [comment] 2017-02-08 18:53
> Logs are not shown via webUI:

This was removed weeks back - this is intended

**Comment by DeepDiver1975** [comment] 2017-02-08 18:54
> I think admin and personal titles should be more clear, they are still looking like another section.

I guess it would be good to get @felixheidecke to have a look at this

**Comment by tomneedham** [comment] 2017-02-08 21:10
> When enabling a new app, it should create a new section instead of adding all of them in additional section.

Personally I think the current way is the best for backwards compatibility. Otherwise once someone upgrades they'd just get a section per app which was not really the idea here. Apps are free to join any of the sections or create their own if they believe that to be the best course of action.

**Comment by tomneedham** [comment] 2017-02-08 21:23
@davitol I am unable to reproduce the 3 error messages in the log when clicking on the settings menu. Are  you able to enable traces and send that to me so that I can try and work out where this is coming from? Do you have anything special setup caching wise?

**Comment by SergioBertolinSG** [comment] 2017-02-09 07:49
> Personally I think the current way is the best for backwards compatibility. Otherwise once someone upgrades they'd just get a section per app which was not really the idea here. Apps are free to join any of the sections or create their own if they believe that to be the best course of action.

With current approach they will have all of them hidden in 'Additional' section, while expecting to have a section per app. Look how the admin sidebar look in 9.1.4:

![screen shot 2017-02-09 at 08 47 09](https://cloud.githubusercontent.com/assets/9048796/22773835/8bbf3446-eea4-11e6-8a41-9ca5f1cfc7ce.png)

**Comment by DeepDiver1975** [comment] 2017-02-09 08:12
All the apps have to be ported to support the new approach

**Comment by SergioBertolinSG** [comment] 2017-02-09 11:24
OK, after talking with @tomneedham I understand how this works. I'll make a list of all apps which requires improvements to appear correctly.

**Comment by davitol** [comment] 2017-02-10 07:59
@tomneedham Apps section does not show tha apps enabled /disabled (master branch)

IMHO it has sev-1

![screen shot 2017-02-10 at 08 55 36](https://cloud.githubusercontent.com/assets/10596560/22818764/247e438c-ef6f-11e6-8501-96d26e5b4d40.png)
![screen shot 2017-02-10 at 08 55 27](https://cloud.githubusercontent.com/assets/10596560/22818767/282f54f8-ef6f-11e6-99a1-12d75800556c.png)

**Comment by felixheidecke** [comment] 2017-02-10 11:57
I am very fond of not nesting in too many levels. Having multiple categories might help flattening the structure. Showing and hiding disabled apps could be changed in **Apps** :arrow_right: **General**. Disabled apps in the list could be labeled to make it more clear. [Try this click-dummy](http://demo.uberspace.heidecke.me/owc_clickdummy/pages/settings.html) :point_left:

**Comment by davitol** [comment] 2017-02-10 12:01
@felixboehm Not sure if I got the idea, but showing all apps (enabled and disabled) in that menu, maybe it will be too long:

```
Enabled:
  - activity: 2.3.2
  - admin_audit: true
  - comments: 0.3.0
  - dav: 0.2.7
  - enterprise_key: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
  - windows_network_drive: 0.2.33
  - workflow: 0.2.3
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_drop
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_shibboleth
```
Just my opinion :fox_face:

**Comment by DeepDiver1975** [comment] 2017-02-10 12:23
> Apps section does not show tha apps enabled /disabled (master branch)

@davitol works for me - maybe related to the installed apps. Any error in the browser console? THX

**Comment by felixheidecke** [comment] 2017-02-10 12:35
@davitol I think you got the wrong person :wink: it's @felixheidecke

> maybe it will be too long:

There is a UX saying: _"horizonal space is expensive, vertical space is cheap"_
As of today, having long vertical sites is the most common way to display greater amounts of content. As of this moment, the current page is over 6000px in height, and you probably didn't have any trouble navigating the site. :wink: We navigate loooong pages everyday without noticing it because it comes natural to us.

As a general advice @all:
Trying to hide more and more stuff behind buttons that need to be found, identified and clicked is a pain in the butt. Keeping nesting to a healthy minimum, streamlining navigation of click-paths, thinking vertical increases good UX vastly.

**Comment by davitol** [comment] 2017-02-10 12:56
@DeepDiver1975 

> @davitol works for me - maybe related to the installed apps. Any error in the browser console? THX

![screen shot 2017-02-10 at 13 42 05](https://cloud.githubusercontent.com/assets/10596560/22827496/839e08b0-ef98-11e6-9d17-83cd1c494d1c.png)

Not sure if the 302 returned when listing the apps list is right. If you think is useful, do no hesitate to ping and i'll share my container credentials.

**Comment by DeepDiver1975** [comment] 2017-02-10 13:29
````
{"reqId":"aGoo00ui03Gb1z9z+jax","remoteAddr":"95.90.199.29","app":"no app in context","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"settings.AppSettings.viewApps\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(339): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('settings.AppSet...', Array, 1)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/URLGenerator.php(73): OC\\\\Route\\\\Router->generate('settings.AppSet...', Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(101): OC\\\\URLGenerator->linkToRoute('settings.AppSet...')\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(230): OC\\\\TemplateLayout->__construct('user', 'files')\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(894): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#11 \\\/opt\\\/owncloud\\\/index.php(46): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","level":3,"time":"2017-02-10T13:29:26+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"admin"}
{"reqId":"aGoo00ui03Gb1z9z+jax","remoteAddr":"95.90.199.29","app":"PHP","message":"strpos(): Empty needle at \/opt\/owncloud\/lib\/private\/TemplateLayout.php#101","level":3,"time":"2017-02-10T13:29:26+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"admin"}
{

**Comment by DeepDiver1975** [comment] 2017-02-10 13:41
LOL  - this PR killed too much code - https://github.com/owncloud/core/pull/26763

**Comment by SergioBertolinSG** [comment] 2017-02-15 08:51
Related - https://github.com/owncloud/core/issues/27158

**Comment by davitol** [comment] 2017-02-15 15:48
Related - https://github.com/owncloud/core/issues/27166

**Comment by davitol** [comment] 2017-02-21 12:21
> @davitol I am unable to reproduce the 3 error messages in the log when clicking on the settings menu. Are you able to enable traces and send that to me so that I can try and work out where this is coming from? Do you have anything special setup caching wise?

@tomneedham please ping me and I will give you the credentials of my testing environment

**Comment by davitol** [comment] 2017-02-21 12:52
https://github.com/owncloud/core/issues/27117#issuecomment-281330183

Fixed with https://github.com/owncloud/core/pull/27197

**Closed** 2017-02-24 12:26 UTC
Labels: bug, regression, settings:admin, settings:apps, settings:personal, sev1-critical
