### ISSUE TITLE
Renaming folder causes clients to loose files

### ISSUE THREAD

**Issue by swbartley** [owncloud/core#16567] opened 2015-05-26 14:21 UTC
I renamed a directory in my owncloud folder once it went to sync all of the sub directories and files of that renamed directory disappeared and I need to recover these files urgently. I'm hosting owncloud myself at a web hosting provider using version 8 and the desktop client 1.8.1.  

The files have been deleted but I can see them in the activity log on the server however it wont let me restore the old files. Under the deleted files there are only a couple files showing which I tried to restore but it did not restore all the files only a couple.

**Comment by PVince81** [comment] 2015-05-27 09:44
Check your "data" folder directly, it is very likely that the files are still there. You might be able to make them reappear by running "./occ files:scan --all" as web server user.

Closing as duplicate of https://github.com/owncloud/core/issues/13391

**Closed by PVince81** 2015-05-27 09:44 UTC
Labels: bug
