### ISSUE TITLE
Wrong folder size in webview / truncate oc_filecache corrupts share structure in db

### ISSUE THREAD

**Issue by deMattin** [owncloud/core#10036] opened 2014-07-29 22:17 UTC
First, sorry for my english ... ;)
The main problem is, that the folder size isn't calculated correct in OC 7 in webview.
And I need some help to repair this.
The try to repair this caused another problem that I only could "repair" with a restoring of my database backup.

### Steps to reproduce
I did the following steps:
1. activated encryption (don't know if this does matter)
2. deactivated encryption (don't know if this does matter)
3. folder size in webview is shown wrong/less (not systematic, sometimes the folder size is the size of a single file in the folder, sometimes calculated correct, sometimes a part of all files).
Filesize itself is always shown correct!
4. rescanned filesystem (/path/of/owncloud/console.php files:scan --all) -> nothing changed
5. truncated oc_filecache -> folder size now is shown correct but all shares are corrupt.
Some of my files are shown as shared by others, my shares link to other files that shouldn't have been shared, ...
The whole sharing structure is linked wrong in database with no chance to repair it in the webview.
There was NO dataloss (>10GB of Data)!

### Expected behaviour
Foldersize will show the sum of all files in the folder
AND
truncate filecache shouldn't corrupt shareing structure in database

### Actual behaviour
foldersize is shown wrong
"truncate oc_filecache;" corrupts database

### Server configuration
**Operating system**:
Debian 7
**Web server:**
Apache 2
**Database:**
MySQL 5.0
**PHP version:**
 5.4.4
**ownCloud version:** (see ownCloud admin page)
7.0.0.8
**Updated from an older ownCloud or fresh install:**
updated from well working 6.0.4
**List of activated apps:**
default
+videoviewer
**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '............',
  'passwordsalt' => '.........',
  'trusted_domains' => 
  array (
    0 => '192.168.192.210',
    1 => 'domain.tld',
  ),
  'datadirectory' => '/media/sf_Owncloud-Data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.8',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '......',
  'dbpassword' => '..................',
  'installed' => true,
  'forcessl' => true,
  "overwritehost" => "domain.tld",
  "overwriteprotocol" => "https",
  "overwritewebroot" => "owncloud",
  'trashbin_retention_obligation' => 180,
  'trashbin_auto_expire' => true,
  'loglevel' => '2',
  "remember_login_cookie_lifetime" => 60*60*24*30,
  'enable_previews' => true,
  'theme' => '',
  'maintenance' => false,
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
(but had activated it before)
### Client configuration
**Browser:**
Google Chrome
**Operating system:**
Windows 7
#### Web server error log
nothing special
#### ownCloud log (data/owncloud.log)
some errors like:
Error	PHP	Undefined offset: 2 at /var/www/owncloud/lib/private/share/share.php#1339	2014-07-29T20:48:18+00:00
Error	PHP	Undefined offset: 1 at /var/www/owncloud/lib/private/share/share.php#1339	2014-07-29T20:42:42+00:00
...
#### Browser log
nothing special

**Comment by PVince81** [comment] 2015-03-06 18:39
Size propagation has issues on OC 7.0.4 with shared folders: https://github.com/owncloud/core/issues/14596

@deMattin the encryption app normally calculates unencrypted_size during the initial encryption of every user. If you set it back to 0 it will only recompute it the next time the file is accessed/modified.
This is not a situation the encryption app was designed for, so not really a bug.

To recover from this particular situation, one idea is to reset the migration flag in the database for all users: `update oc_preferences set configvalue=0 where appid='files_encryption' and configkey='migration_status';`

The next time a user will login, the unencrypted_size should be recomputed.

Closing as duplicate of https://github.com/owncloud/core/issues/14596 (the size propagation ticket)

**Closed by PVince81** 2015-03-06 18:39 UTC
Labels: app:files_encryption, bug
