### ISSUE TITLE
Attempt to add existing Amazon S3 bucket fails

### ISSUE THREAD

**Issue by stayen** [owncloud/core#14131] opened 2015-02-12 00:19 UTC
### Steps to reproduce
1. Create an IAM user at AWS with full access to single S3 bucket only.
2. Attempt to add that bucket under the above user's credentials as external storage.
### Expected behaviour

External storage is expected to be added.
### Actual behaviour

It remains disconnected, "Pending" state.
### Server configuration

**Operating system**: Centos 6.5 x86_64

**Web server:**Nginx 1.4.1

**Database:** MariaDB 5.5.36

**PHP version:**5.5.21

**ownCloud version:** 8.0 (stable)

**Updated from an older ownCloud or fresh install:**fresh install

**List of activated apps:**Files, Activity, Pictures, Contacts, Booksmarks, Calendar

**The content of config/config.php:**

```
  'instanceid' => 'ocxwawj58ovn',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' => 
  array (
    0 => 'boyandin.ru',
  ),
  'datadirectory' => '/storage/owncloud/data',
  'overwrite.cli.url' => 'https://boyandin.ru',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'REMOVED',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REMOVED',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'boyandin.ru',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'email-smtp.us-east-1.amazonaws.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'REMOVED',
  'mail_smtppassword' => 'REMOVED',
```

**Are you using external storage, if yes which one:** Amazon S3

**Are you using encryption:** no
### Client configuration

**Browser:**Google Chrome Version 40.0.2214.111 (64-bit)

**Operating system:**Ubuntu 14.04 64-bit
#### Web server error log

```
No error messages related
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"6b3c14085c6941128579da6538a430b7","remoteAddr":"212.164.233.251","app"
:"files_external","message":"Exception: {\"Message\":\"Creation of bucket failed
. Your previous request to create the named bucket succeeded and you already own
 it.\",\"Code\":0,\"Trace\":\"#0 \\\/storage\\\/owncloud\\\/web\\\/apps\\\/files
_external\\\/lib\\\/amazons3.php(546): OC\\\\Files\\\\Storage\\\\AmazonS3->getCo
nnection()\\n#1 \\\/storage\\\/owncloud\\\/web\\\/apps\\\/files_external\\\/lib\
\\/config.php(457): OC\\\\Files\\\\Storage\\\\AmazonS3->test(true)\\n#2 \\\/storage\\\/owncloud\\\/web\\\/apps\\\/files_external\\\/lib\\\/config.php(539): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, true)\\n#3 \\\/storage\\\/owncloud\\\/web\\\/apps\\\/files_external\\\/ajax\\\/addMountPoint.php(25): OC_Mount_Config::addMountPoint('s3', '\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, 'user', 'Sentinel', true)\\n#4 \\\/storage\\\/owncloud\\\/web\\\/lib\\\/private\\\/route\\\/route.php(135) : runtime-created function(1): require_once('\\\/storage\\\/ownclo...')\\n#5 [internal function]: __lambda_func(Array)\\n#6 \\\/storage\\\/owncloud\\\/web\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func('\\\\x00lambda_70', Array)\\n#7 \\\/storage\\\/owncloud\\\/web\\\/lib\\\/base.php(763): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#8 \\\/storage\\\/owncloud\\\/web\\\/index.php(36): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/storage\\\/owncloud\\\/web\\\/apps\\\/files_external\\\/lib\\\/amazons3.php\",\"Line\":597}","level":4,"time":"2015-02-11T14:08:33+00:00"}
#### Browser log
```

Nothing related in browser logs

```
```

**Comment by mvdbos** [comment] 2015-03-17 21:44
I got the same error. After some googling, I found that this can be the case when the region is not set correctly. It defaults to eu-west-1. My region was eu-central-1. After setting that, everything worked (as long as I didn't enable SSL...)

**Comment by temmokan** [comment] 2015-03-19 08:35
Thanks, I'll see how to match region, if that's possible.

**Comment by PVince81** [comment] 2015-08-03 13:47
Are you still getting this issue with 8.0.5 or 8.1 ?

**Comment by temmokan** [comment] 2015-08-03 15:47
I haven't upgraded to 8.* yet, due to still existing compatibility issues with certain modules.

**Comment by lupinehorror** [comment] 2015-11-20 07:24
this is happening to me with an existing s3 mount after upgrading to 8.2.1 this morning. it was working fine before.

**Comment by PVince81** [comment] 2015-11-20 09:00
Disabling SSL ? Hmm, very strange. I'm not aware of any change that would affect that.
@lupinehorror from which OC version did you upgrade from ?

@Xenopathic any idea if the config API changes could have affected this ? Boolean issue ?

**Comment by PVince81** [comment] 2015-11-20 09:00
CC @icewind1991

**Comment by PVince81** [comment] 2015-11-20 09:02
@lupinehorror I also assume that when you say "this issue" you mean the exact same exception in the log like https://github.com/owncloud/core/issues/14131#issue-57399063 when you have SSL enabled ?

**Comment by lupinehorror** [comment] 2015-11-20 09:12
@PVince81 upgraded from the last stable version...can't remember the number. yes...the same as #14131

**Comment by PVince81** [comment] 2016-03-15 15:50
Are you guys all correctly setting the region field ?

**Comment by PVince81** [comment] 2016-07-18 15:16
Closing due to lack of feedback.

**Comment by mchybo** [comment] 2016-12-20 17:24
I have the same issue as guys above, setting proper region doesn't help.

I'm using S3-compatible storage as an endpoint but this shouldn't be a problem.

**Comment by canepan** [comment] 2017-01-08 06:52
The same is happening to me with 9.1.3.
I imported the mount.json of a previous 7.0 installation and I received thos error.

I resolved adding a '1' at the end of the bucket name.
I'm using eu-west-1, and the error was the same both specifying it or not.

**Comment by canepan** [comment] 2017-01-08 07:42
This actually creates a new bucket.
I tried starting from scratch (removed owncloud.db, config.php and log), with the same result.
Wit the proper accesd key, it's able to create a new bucket and use it, but not to use an existing one

**Comment by canepan** [comment] 2017-01-08 11:07
The problem looks like S3 lib is unable to verify bucket existence ( connectiin.doesBucketExist ).
Maybe a timeout?
Is there a wsy to force OwnCloud skip this check?

**Comment by canepan** [comment] 2017-01-08 23:11
Actually, removing the flag from 'enable path style' made it work for me

**Comment by macbobby** [comment] 2017-03-17 11:23
Still get this not working. It says that the bucket already exists.
Has anyone get this working?
Could you please paste your config for me?

**Comment by AukeTembrink** [comment] 2017-04-10 19:33
Got the same error. Still does not seem to work.

**Comment by Nyoroon** [comment] 2017-07-11 14:08
Any progress?

**Comment by AukeTembrink** [comment] 2017-07-11 15:01
@Nyoroon Can not really tell about a progress. Last time I tried to use it, it was still broke. Have given it up.

**Comment by stayen** [comment] 2017-07-11 15:03
@Nyoroon Same, no luck. As a result, I gave up using ownCloud, too much small problems preventing from efficiently using it. I can't rely on such a product.

**Comment by AukeTembrink** [comment] 2017-07-28 08:36
@stayen this was exactly my thought. But I did not really find another software. Any suggestions?

**Comment by hodyroff** [comment] 2017-07-28 09:20
Do I understand it correctly that creating a new bucket works. Right?
What does not work is using an existing bucket? Even after trying the suggestions from canepan above?

What is the use case for using an existing bucket? Please help me understand the why.

My understanding of the object storage implementation was that ownCloud will always be the exclusive user of such objects.

**Comment by mchybo** [comment] 2017-07-28 17:58
@hodyroff - I've got pretty big S3 bucket with let's say 10TB of data. I don't want to transfer my files from my existing bucket to the new one just to use owncloud with my data.

**Comment by canepan** [comment] 2017-07-28 19:09
Another example would be if you loose the configuration (or just the Mount json gets corrupted) and you want a new installation, using the old db.

Nicola

Il giorno 28 lug 2017, 18:58, alle ore 18:58, "Michał Chybowski" <notifications@github.com> ha scritto:

**Comment by PVince81** [comment] 2017-07-31 07:28
Please run `occ files:scan --path /$userid/files/path/to/mount -vvv` and check that the scanner is going into the S3 bucket.

If the bucket check is wrong, try commenting it out in the code. I'm not sure why it's there as I'm not familiar with this logic.

**Comment by canepan** [comment] 2017-07-31 07:48
The problem is, if I'm missing the mount.json entry, OwnCloud doesn't have the credentials to scan it

**Comment by dirigeant** [comment] 2017-08-09 15:19
I could reproduce same error with latest 9.1 version. I upgraded to 10 version and this issue is fixed.

After upgrade I got another error which is reported https://github.com/owncloud/core/issues/14893 here. Suggested solution helped.

So this issue still exists in 9.1 but it is fixed in 10.

**Comment by PVince81** [comment] 2017-12-12 16:21
Please try again with 10.0.4 and reopen if the issue persists.

Note that 10.0.4 also has the fix for https://github.com/owncloud/core/issues/14893 (signature v4)

**Closed by PVince81** 2017-12-12 16:21 UTC
Labels: app:files_external, bug, sev2-high
