### ISSUE TITLE
Upload txt file, File has Chinese, Garbled

### ISSUE THREAD

**Issue by lnsyyj** [owncloud/core#16229] opened 2015-05-11 09:38 UTC
When I upload txt file that contains Chinese when, after the online preview garbled, download files is garbled.

File contents:  传说中文会出现乱码
server：centos6.4
client：win7 chinese

**Comment by oparoz** [comment] 2015-05-11 17:18
Is this on 8.0 or 8.1?

**Comment by lnsyyj** [comment] 2015-05-12 01:18
oparoz:ownCloud 8.0.3 (stable)

**Comment by lnsyyj** [comment] 2015-05-12 14:48
@karlitschek 
#73
https://github.com/owncloud/files_texteditor/pull/73

**Comment by oparoz** [comment] 2015-05-12 16:25
@lnsyyj - Would it be possible for you to test this on 8.1 as well or provide a sample text file? The way text previews work has changed in 8.1

**Comment by lnsyyj** [comment] 2015-05-13 14:09
@oparoz 

ok,Thank you.
I can not upload txt file
File content can be:听说中文有乱码,看看好用吗？

**Comment by oparoz** [comment] 2015-05-13 14:10
The problem is that if I create it, it won't have the chinese charset.

**Comment by lnsyyj** [comment] 2015-05-13 14:22
@oparoz 
So I sent to you by email, my email is lnsyyj@hotmail.com

**Comment by oparoz** [comment] 2015-05-13 16:30
Thanks for the sample!

On 8.1, the preview is still garbled, but the file can be properly downloaded.

**Comment by PVince81** [comment] 2015-05-13 16:46
Yes, I think this is what I mentionned in the PR: https://github.com/owncloud/core/pull/15652#issuecomment-94407785

If I understand well it uses WebDAV to load the preview ?
We might still need to add a new app controller route then to load the properly converted file then.

**Comment by PVince81** [comment] 2015-05-13 16:50
Or find a library that does this in JS. But binary handling in JS... super extra tricky/hacky I guess.

**Comment by oparoz** [comment] 2015-05-13 16:50
Yes, on 8.1 it uses WebDAV for the preview. The OP has 2 issues, one of which is already fixed in 8.1 since the file can be downloaded with the proper charset.

I was about to file a new issue because I don't understand why the WebDAV endpoint always uses utf-8 headers. It should use the encoding of the file to serve it.

**Comment by PVince81** [comment] 2015-05-13 16:53
Hmmm not sure. I thought WebDAV would just blindly deliver the file as binary.
But if it does have a way to know encoding info, it could update the headers.

Currently this information is not known by the server, and I don't think we want to do on-the-fly detection as it would slow down downloads. At some point if we have more extended file metadata (metadata app?) that info might become available.

**Comment by PVince81** [comment] 2015-05-13 16:54
Well, even if it sets the proper header, it is not guaranteed that the Ajax call will automatically convert the characters to UTF-8 to be displayed. And I don't think you can have a DIV container with a different charset than the main page.

**Comment by oparoz** [comment] 2015-05-13 17:14
Ah, good point about the mixed encoding in HTML... That wouldn't work anyway...

I guess the best thing would then be to add 206 support to the PHP endpoint then, but I thought we wanted to use WebDAV as much as possible.

**Comment by PVince81** [comment] 2015-05-13 17:25
Ideally we should rely on WebDAV when possible (for regular downloads and other file operations).
But this here is clearly a case where we need another specialized endpoint.

The cool thing is that this new endpoint could then also be used by the text editor too.

**Comment by oparoz** [comment] 2015-05-13 18:17
This needs to be fixed to handle byte ranges
https://github.com/owncloud/core/blob/master/lib/private/files.php#L176

Not that difficult.

One problem will remain, any other storage location will send the full file as the preview...

**Comment by lnsyyj** [comment] 2015-05-14 14:57
Oh, why in my test it is easy to use it here.
Title forgot to say, client-side is chrome version 42.0.2311.135 m

**Comment by ownclouders** [comment] 2018-01-13 01:12
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by PVince81** [comment] 2018-01-15 10:21
Will likely require a separate endpoint for file previews with automatic encoding detection

**Comment by ownclouders** [comment] 2018-02-23 01:15
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Closed** 2021-09-23 08:58 UTC
Labels: Type:Bug
