### ISSUE TITLE
[master] Avatars not appearing in share panel

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33817] opened 2018-12-07 14:17 UTC
### Steps

1. Create two users user1 and user2 with `occ user:add`
1. Login as user1
1. Create a folder "test"
1. Share "test" with user2
1. Reload page and open share panel

### Expected result
Avatar "U" must appear for user2.

### Actual result
An "X" appears and errors in log:
```
42.jpeg:1 GET http://localhost/owncloud/remote.php/dav/avatars/user2/42.jpeg 404 (Not Found)
Image (async)
$.fn.avatar @ jquery.avatar.js?v=9d5f9fb12d0d2f39456653b0b248674a:131
(anonymous) @ activitytabview.js?v=9d5f9fb12d0d2f39456653b0b248674a:198
each @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:2
each @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:2
_postRenderItem @ activitytabview.js?v=9d5f9fb12d0d2f39456653b0b248674a:194
_onAddModel @ activitytabview.js?v=9d5f9fb12d0d2f39456653b0b248674a:190
triggerEvents @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:371
triggerApi @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:356
eventsApi @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:155
Events.trigger @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:346
_onModelEvent @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:1187
triggerEvents @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:372
triggerApi @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:357
eventsApi @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:155
Events.trigger @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:346
set @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:923
options.success @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:1050
i @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:2
fireWith @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:2
z @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:4
(anonymous) @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:4
load (async)
send @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:4
ajax @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:4
Backbone.ajax @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:1460
Backbone.sync @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:1443
sync @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:798
fetch @ backbone.js?v=9d5f9fb12d0d2f39456653b0b248674a:1055
setFileInfo @ activitytabview.js?v=9d5f9fb12d0d2f39456653b0b248674a:89
setFileInfo @ detailsview.js?v=9d5f9fb12d0d2f39456653b0b248674a:237
_updateDetailsView @ filelist.js?v=9d5f9fb12d0d2f39456653b0b248674a:539
_onClickFile @ filelist.js?v=9d5f9fb12d0d2f39456653b0b248674a:682
executeBound @ underscore.js?v=9d5f9fb12d0d2f39456653b0b248674a:762
(anonymous) @ underscore.js?v=9d5f9fb12d0d2f39456653b0b248674a:775
(anonymous) @ underscore.js?v=9d5f9fb12d0d2f39456653b0b248674a:122
dispatch @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:3
r.handle @ jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:3
jquery.min.js?v=9d5f9fb12d0d2f39456653b0b248674a:4 GET http://localhost/owncloud/remote.php/dav/avatars/user2/48.jpeg 404 (Not Found)
```

Avatar seems to work in the activity panel, so it might be specific to the share panel.

### Versions
OC master ac0f01b60f423a46464f3ee226b5c5190723feec

Works fine on stable10 59188c932f2292a55b8f7598cb402cd3a3f22859

This should be bisectable.

**Comment by phil-davis** [comment] 2018-12-07 14:30
Does it just happen when ``user2`` has never logged in yet? (no skeleton, no other setup happened for ``user2`` yet)

**Comment by ownclouders** [comment] 2018-12-07 14:44
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28558 (sharing-v1.feature fails in master), https://github.com/owncloud/core/issues/15657 (Remote user's avatar not updated in share dialog after avatar is modified), https://github.com/owncloud/core/issues/3519 (Shared folders do not appear in picture gallery), https://github.com/owncloud/core/issues/8428 ([master] Filesize appears as zero for share file after moving it), and https://github.com/owncloud/core/issues/25311 (Share indicator not appearing upon sharing, only after refresh).

**Comment by PVince81** [comment] 2018-12-10 08:51
@phil-davis I considered this, but then I logged in with "user2" and went back to "user1". The avatars did not appear either.

**Comment by JammingBen** [comment] 2021-09-23 10:53
Seems to be fixed meanwhile, I can't reproduce.

**Closed by JammingBen** 2021-09-23 10:53 UTC
Labels: Type:Bug, regression, p2-high
