### ISSUE TITLE
CalDAV & CardDAV URL broken after 8.2 upgrade

### ISSUE THREAD

**Issue by jfburdet** [owncloud/core#20173] opened 2015-10-30 10:17 UTC
CardDAV & CalDAV both appear to be broken again in ownCloud 8.2. The CardDAV URL returns the following; the CalDAV URL returns something similar:

```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>2.1.7</s:sabredav-version>
<s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "addressbooks/_user_/contacts"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/owncloud/remote.php/carddav/addressbooks/salfter/contacts
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>
```

**Comment by DeepDiver1975** [comment] 2015-10-30 10:46
duplicate of https://github.com/owncloud/core/issues/16387 - which is finally handled in https://github.com/owncloud/calendar/issues/782

**Closed by DeepDiver1975** 2015-10-30 10:46 UTC
