### ISSUE TITLE
Are there any planed features for "Secure" file displaying?

### ISSUE THREAD

**Issue by mr-gosh** [owncloud/core#16712] opened 2015-06-03 10:27 UTC
Some of our Customers ask for features like in http://www.netfiles.de
Something like "show documents for a small  time slot" without letting them copy or print it.

**Comment by RealRancor** [comment] 2015-06-03 10:53
Hi,

very likely not as there was a similar request to disable downloading of files here which was denied: https://github.com/owncloud/core/issues/16644

Your customer is probably looking for an IRM (Information Rights Management) tool.

**Comment by MorrisJobke** [comment] 2015-06-03 11:53
> Something like "show documents for a small time slot"

There is the expiry feature for link shares.

Regarding copy or printing: There is no way to do this properly. Take a screenshot and print it -> all the code to implement this feature then is useless.

**Comment by MorrisJobke** [comment] 2015-06-03 11:54
THis is a duplicate of #16644 and therefore I close this.

**Closed by MorrisJobke** 2015-06-03 11:54 UTC
