### ISSUE TITLE
OwnCloud 8.1.1 PHP Warning:  flock() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by JB1985** [owncloud/core#18222] opened 2015-08-12 06:27 UTC
I have upgrade my owncloud from oc8.1 to oc8.1.1 via apt-get.

Errors:
```
Vorbereitung zum Ersetzen von owncloud-server 8.1.0-3 (durch .../owncloud-server_8.1.1-1_all.deb) ...
owncloud-server: occ maintenance:mode --on
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 201
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:202
Stack trace:
#0 /var/www/owncloud/lib/private/config.php(61): OC\Config->readData()
#1 /var/www/owncloud/lib/base.php(134): OC\Config->__construct('/var/www/ownclo...')
#2 /var/www/owncloud/lib/base.php(524): OC::initPaths()
#3 /var/www/owncloud/lib/base.php(1115): OC::init()
#4 /var/www/owncloud/console.php(41): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#6 {main}Ersatz für owncloud-server wird entpackt ...

owncloud-server (8.1.1-1) wird eingerichtet ...
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 201
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:202
Stack trace:
#0 /var/www/owncloud/lib/private/config.php(61): OC\Config->readData()
#1 /var/www/owncloud/lib/base.php(134): OC\Config->__construct('/var/www/ownclo...')
#2 /var/www/owncloud/lib/base.php(524): OC::initPaths()
#3 /var/www/owncloud/lib/base.php(1121): OC::init()
#4 /var/www/owncloud/console.php(41): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#6 {main}owncloud-server: occ upgrade
PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 201
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:202
Stack trace:
#0 /var/www/owncloud/lib/private/config.php(61): OC\Config->readData()
#1 /var/www/owncloud/lib/base.php(134): OC\Config->__construct('/var/www/ownclo...')
#2 /var/www/owncloud/lib/base.php(524): OC::initPaths()
#3 /var/www/owncloud/lib/base.php(1121): OC::init()
#4 /var/www/owncloud/console.php(41): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#6 {main}PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/owncloud/lib/private/config.php on line 201
An unhandled exception has been thrown:
exception 'Exception' with message 'Could not acquire a shared lock on the config file /var/www/owncloud/config/config.php' in /var/www/owncloud/lib/private/config.php:202
Stack trace:
#0 /var/www/owncloud/lib/private/config.php(61): OC\Config->readData()
#1 /var/www/owncloud/lib/base.php(134): OC\Config->__construct('/var/www/ownclo...')
#2 /var/www/owncloud/lib/base.php(524): OC::initPaths()
#3 /var/www/owncloud/lib/base.php(1121): OC::init()
#4 /var/www/owncloud/console.php(41): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#6 {main}owncloud-config-apache (8.1.1-1) wird eingerichtet ...
[ ok ] Restarting web server: apache2 ... waiting .
```

**Comment by LukasReschke** [comment] 2015-08-12 07:21
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/core/blob/master/CONTRIBUTING.md

**Comment by LukasReschke** [comment] 2015-08-12 07:22
Also what FS do you use? Is it a NFS or network mount?

**Comment by JB1985** [comment] 2015-08-12 07:33
### Server configuration
**Operating system**: Debian 7

**Web server:** 

Server version: Apache/2.2.22 (Debian)
Server built:   Aug  1 2015 20:11:57
Server's Module Magic Number: 20051115:30
Server loaded:  APR 1.4.6, APR-Util 1.4.1
Compiled using: APR 1.4.6, APR-Util 1.4.1
Architecture:   64-bit


**Database:**

mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.2


**PHP version:**

PHP 5.4.41-0+deb7u1 (cli) (built: May 22 2015 12:49:18) 


**ownCloud version:** (see ownCloud admin page)

Oc8.1.1

**Updated from an older ownCloud or fresh install:**

Updated via apt-get from OC 8.1 to OC 8.1.1

**List of activated apps:**

bookmarks, calendar, contacts, external, tasks

**Are you using external storage,***

NO! 

/var/www/owncloud ext4


**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by LukasReschke** [comment] 2015-08-12 07:34
That's interesting. I suppose this is caused by the fact that a lock cannot be acquired due to the way the packages handle the update.

Mhm…

Does it work if you do it manually?

**Comment by DeepDiver1975** [comment] 2015-08-12 07:34
@jnweiger @rperezb related to packaging? Please have a look - THX

**Comment by JB1985** [comment] 2015-08-12 07:36
@LukasReschke 

I cant see any mistake on working with OC. But I got only the errors on updating oc.

**Comment by jnweiger** [comment] 2015-08-12 08:46
For me, package update on Debian_7.0 with Apache 2.2, Php 5.4.41, looks like this:

<pre>
Preparing to replace owncloud-config-apache 8.0.6~RC1-1 (using .../owncloud-config-apache_8.1.1-1_all.deb) ...
Unpacking replacement owncloud-config-apache ...
Preparing to replace owncloud-server 8.0.6~RC1-1 (using .../owncloud-server_8.1.1-1_all.deb) ...
owncloud-server: occ maintenance:mode --on
Maintenance mode enabled
Unpacking replacement owncloud-server ...
</pre>

Cannot reproduce the issue. I have no indication, why this should be related to packaging. Sorry. 

@LukasReschke He mentions an error message that we call flock() with wrong parameters. Is that a symptom, when a lock cannot be acquired?

**Comment by lsascha** [comment] 2015-08-12 11:31
Had the same issue. And i think it was the problem mentioned here:
https://github.com/owncloud/core/issues/17329#issuecomment-119248944
(since cronjobs where not working too.)

or just an owner issue that the files had not the correct owner set.

Doesn´t seem to have given me any issues that i had this error on updating from 8.1.0 to 8.1.1.
owncloud works normally.

**Comment by jnweiger** [comment] 2015-08-12 11:37
@lsascha your reference https://github.com/owncloud/core/issues/17329#issuecomment-119248944 points to APC issues. I don't see the connection with cronjobs or this issue.

**Comment by RealRancor** [comment] 2015-08-12 12:15
Have seen such problems if the permissions on either the /config/ folder or the /config/config.php file where wrong: https://github.com/owncloud/core/issues/15417

**Comment by lsascha** [comment] 2015-08-12 12:23
@jnweiger sorry. it was meant more like that these where the things i did to solve this error. I guess i had both the issue with the wrong permissions and the APC issue. So this is most likely only a permission error.

**Comment by Bullnados** [comment] 2015-08-18 20:55
Same issue here. Clean install 8.1 (done with webhoster-1click-software-installation)
Update with updater app

### Steps to reproduce
1. New 8.1
2. No apps disabled
3. Update with Updaterapp

### Expected behaviour
Update to 8.1.1

### Actual behaviour
 flock() expects parameter 1 to be resource, boolean given in 

### Server configuration
**Operating system**:
Linux dd8226 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 
**Web server:**
Apache
**Database:**
mySQL 5.6.24
**PHP version:**
5.5.26
**ownCloud version:** (see ownCloud admin page)
8.1.0
**Updated from an older ownCloud or fresh install:**
no
**List of activated apps:**
Apps shiped by default
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Comment by jnweiger** [comment] 2015-08-20 12:47
@Bullnados @lsascha @JB1985 can you please show us the output of

<pre>
ls -la /var/www/owncloud/config
</pre>
Please check, if you get the same error message, when you repeat this command:
<pre>
sudo -u www-data php /var/www/owncloud/occ maintenance:mode --off
</pre>

The code around https://github.com/owncloud/core/blob/master/lib/private/config.php#L194
tries to avoid some of these errors, but it is apparently incomplete.

**Comment by PVince81** [comment] 2015-08-25 11:45
I believe that @jnweiger merged many packages together, so the order of packages would not affect the update process any more. Not sure if this would fix that specific issue though.

**Comment by jnweiger** [comment] 2015-08-25 13:44
The merged package is likely to fix this and many other similar issues as long as the issue depends on package ordering.

Here I also suspect that somehow write permissions to config.php were lost. Not sure if this is related to install order.

**Comment by thomasfiala** [comment] 2015-08-26 08:00
I experience the same error. I have OC8.1.1 (stable) on shared web hosting (all-inkl.com). I upgraded from OC7 yesterday using php56-cgi (set through .htaccess).
The error occurred when changing to 5.5.26-nmm1 (module) by removing the AddHandler line in .htaccess.
Changing back to php56-cgi resolves this problem.

Please tell me if you need additional information.

**Comment by jnweiger** [comment] 2015-08-27 10:22
@thomasfiala @Bullnados @lsascha @JB1985 can you please show us the output of
<pre>
ls -la /var/www/owncloud/config
</pre>
Please check, if you get the same error message, when you repeat this command:
<pre>
sudo -u www-data php /var/www/owncloud/occ maintenance:mode --off
</pre>

**Comment by thomasfiala** [comment] 2015-08-27 10:29
I can't, I'm on shared hosting without ssh.

**Comment by jnweiger** [comment] 2015-08-27 11:25
okay. Hard to guess what what is wrong without seeing the files....

**Comment by Bullnados** [comment] 2015-08-29 20:06
Im in holidays and habe no OC access. Hope i can post it tomorow or monday

**Comment by Bullnados** [comment] 2015-09-05 20:35
For
```
ls -la /var/www/owncloud/config
```

drwxrwxrwx  2 ssh-xxx xxx   4096 Aug 18 21:21 .
drwxr-xr-x 14 ssh-xxx xxx   4096 Aug 18 22:08 ..
-rw-r--r--  1 ssh-xxx xxx 258423 Aug 18 21:21 ca-bundle.crt
-rw-r-----  1 ssh-xxx xxx    706 Aug 18 21:21 config.php
-rw-r--r--  1 ssh-xxx xxx  31335 Aug 18 21:21 config.sample.php
-rw-r--r--  1 ssh-xxx xxx    225 Aug 18 21:21 .htaccess

And second one i cant use. Webhosting package by all-inkl

**Comment by RealRancor** [comment] 2015-09-05 20:57
@Bullnados Until your webserver/php is running as the ssh-xxx user or xxx group the permissions are wrong and needs to be fixed accordingly to the documentation available here:

https://doc.owncloud.org/server/8.1/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions

**Comment by ArnaudFeld** [comment] 2015-09-05 22:08
I have the Same Problem. When i Change the Owner from the FTP-User to www-data it works again. So it seems for me a Problem with the rights.

Provider: all-inkl.com

**Comment by RealRancor** [comment] 2015-09-05 22:18
Yes, if you're uploading files via FTP/SSH and all-inkl. is using another user for this it should be obvious that the permissions are wrong here. Until you're using the packages there is nothing to fix here in my opinion.

**Comment by ArnaudFeld** [comment] 2015-09-05 22:23
But some Hours everything works! I change nothing.

So I switch fast the folder "config","data" & "lib" to www-data and then it works.

I look whats the Problem.

**Comment by ArnaudFeld** [comment] 2015-09-05 22:55
The Only Thing change today was a Update for a owncloud-client on OSX

**Comment by MorrisJobke** [comment] 2015-09-09 13:59
@jnweiger What is the state of this? Fixed or push to 8.1.3?

**Comment by jnweiger** [comment] 2015-09-09 14:22
We'll have improvement in 8.1.2 where the chance of corrupted permissions or missing files is reduced.

My current assumption what happens is: 
* user backups his config.php before upgrade. 
* user runs apt-get install  ... to upgrade.
* user manually uploads config.php with owner ftp-user instead of owner www-data.

If that assumption is correct, then there is little to be done from the packaging side.

**Comment by Bullnados** [comment] 2015-09-09 21:48
I did not manual backup config.php otherwise all- inkl dies automaticly. But i dont think.
cant run apt get installiert
I dont change permissions after install OC. So all files and folders should be www-data. And i dient upload something manual. Just installiert OC and than weit for update

**Comment by jnweiger** [comment] 2015-09-10 10:44
Thanks @Bullnados -- there goes my theory....

**Comment by Bullnados** [comment] 2015-09-10 21:42
:+1: 
I correct some Android tablet autocorrections. When I post on git i should switch language.

**Comment by chriscroome** [comment] 2015-09-17 12:52
I have hit this issue, see https://github.com/owncloud/core/issues/19124

I have ownCloud running on a Debian Jessie server with `apache2-mpm-itk` and the ownCloud VirtualHost runs as the `owncloud` user, not `www-data`. 

All the files in `/var/www/owncloud` were `root:root` apart from some directories which I had chowned to `owncloud:owncloud`.

After the latest update the (empty)  `assets` directory is owned by `www-data:www-data` and the `config` directory is as follows:

    ls -lah config/
    total 304K
    drwxr-xr-x  2 owncloud owncloud 4.0K Sep 17 12:12 .
    drwxr-xr-x 14 root     root     4.0K Sep 17 12:12 ..
    -rwxrwxr--  1 www-data www-data 253K Sep 10 15:34 ca-bundle.crt
    -rw-r-----  1 owncloud owncloud  805 Sep 17 12:17 config.php
    -rwxrwxr--  1 www-data www-data  32K Sep 10 15:34 config.sample.php
    -rwxrwxr--  1 www-data www-data  225 Sep 10 15:34 .htaccess

Am I correst in thinking that I simply need to chown these directores as follows and everything will be OK? Or might some updates to some config files not have been applied due to the ownerships?

    chown -R owncloud:owncloud config/
    chown -R owncloud:owncloud assets/

**Comment by jnweiger** [comment] 2015-09-17 12:59
@chriscroome Thanks for the details!
The root cause of your isues is -- as you say -- have ownCloud running on a Debian Jessie server with apache2-mpm-itk and the ownCloud VirtualHost runs as the owncloud user, not www-data.

The DEB packages do not know that. Files in the packages have an ownership and group defined at package creation time rather than at package installation time.
I am defining this as www-data:www-data -- which is the required setting for most other scenarios.

The updates are applied as root user, that should work regardless of your changes.
You can chown them back, but you will run into the same issue with the next update, I am afraid.

**Comment by chriscroome** [comment] 2015-09-17 13:11
@jnweiger thanks, I'll script the chowning and the deleting of the `/etc/apache2/conf-enabled/owncloud.conf` symlink (as I have another file for the ownCloud VirtualHost).

**Comment by cmonteroluque** [comment] 2015-10-07 14:52
@jnweiger ready to close?

**Comment by jnweiger** [comment] 2015-10-07 16:42
Closing here. Many related issues were resolved meanwhile, also setup issues were involved.
Please reopen, if reproducable with latest versions.

**Closed by jnweiger** 2015-10-07 16:42 UTC
Labels: packaging
