### ISSUE TITLE
Can´t login with user that has received a federated share after upgrade

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24909] opened 2016-05-31 07:32 UTC
### Steps to reproduce
After fixing the issue with upgrading from 9.0.2 with daily build (today), (https://github.com/owncloud/core/issues/24871) and fixing the SMB thing (https://github.com/owncloud/core/issues/24903), another issue raised.

Log on with the admin user works and everything is fine, but log on in with a local created user (username: user_x, no ldap ect), owncloud reports a technical issue and does not let the user login.

To be mentioned, user_x (standard user) has a connection to a federated share.
The admin user does not have a connectionion to a federated share.

All permissions and rights in the data folder ect have been checked.

### Expected behaviour
Log on with all users

### Actual behaviour
Log on only with the admin user, but not with other users

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.14

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 beta 1 (daily) Build:2016-05-30T03:09:20+00:00 c870e7754696d179a9ba8f84a1c1379e5ad1a274

**Updated from an older ownCloud or fresh install:**
This was a upgrade from 9.0.2, daily channel

**Where did you install ownCloud from:**
originally tar

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### owncloud.log
```
{"reqId":"fQBRZk4UEFzdkbpJjtUv","remoteAddr":"80.110.35.173","app":"core","message":"Exception when running cache gc: ","level":2,"time":"2016-05-31T08:43:11+02:00","method":"POST","url":"\/index.php\/login","user":"user_x"}

{"reqId":"L+A8y94reYSwtcFsP4+N","remoteAddr":"80.110.35.173","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(436): OC\\\\Share20\\\\Share->getNode()\\
n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(871): OC\\\\Share20\\\\DefaultShareProvider->move(Object(OC\\\\Share20\\\\Share), 'user_x')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(109): OC\\\\Share20\\\\Manager->moveShare(Object(OC\\\\Share20\\\\Share), 'user_x')\\
n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(94): OCA\\\\Files_Sharing\\\\SharedMount->updateFileTarget('\\\/Solutions (2)', Object(OC\\\\Share20\\\\Share))\\
n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(65): OCA\\\\Files_Sharing\\\\SharedMount->verifyMountPoint(Object(OC\\\\Share20\\\\Share), Array)\\
n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(78): OCA\\\\Files_Sharing\\\\SharedMount->__construct('\\\\OC\\\\Files\\\\Stora...', Array, Array, Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\
n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(76): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\
n#7 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\MountProvider))\\
n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(77): array_map(Object(Closure), Array)\\
n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(422): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\
n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(370): OC\\\\Files\\\\Filesystem::initMountPoints('user_x')\\
n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(225): OC\\\\Files\\\\Filesystem::init('user_x', '\\\/user_x\\\/files')\\
n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(865): OC_Util::setupFS()\\
n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\
n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":162}","level":3,"time":"2016-05-31T08:43:11+02:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"user_x"}

{"reqId":"SPpHOBnd5DjejewoljYM","remoteAddr":"80.110.35.173","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(436): OC\\\\Share20\\\\Share->getNode()\\
n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(871): OC\\\\Share20\\\\DefaultShareProvider->move(Object(OC\\\\Share20\\\\Share), 'user_x')\\
n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(109): OC\\\\Share20\\\\Manager->moveShare(Object(OC\\\\Share20\\\\Share), 'user_x')\\
n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(94): OCA\\\\Files_Sharing\\\\SharedMount->updateFileTarget('\\\/Solutions (2)', Object(OC\\\\Share20\\\\Share))\\
n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(65): OCA\\\\Files_Sharing\\\\SharedMount->verifyMountPoint(Object(OC\\\\Share20\\\\Share), Array)\\
n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(78): OCA\\\\Files_Sharing\\\\SharedMount->__construct('\\\\OC\\\\Files\\\\Stora...', Array, Array, Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\
n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(76): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\
n#7 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\MountProvider))\\
n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(77): array_map(Object(Closure), Array)\\
n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(422): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\
n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(370): OC\\\\Files\\\\Filesystem::initMountPoints('user_x')\\
n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(225): OC\\\\Files\\\\Filesystem::init('user_x', '\\\/user_x\\\/files')\\
n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(865): OC_Util::setupFS()\\
n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\
n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":162}","level":3,"time":"2016-05-31T08:43:12+02:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=c15d5df3ed685d6a6503ea4d8d2dab16","user":"user_x"}
```

#### webserver.log
There is no corresponding webserver error log

**Comment by PVince81** [comment] 2016-05-31 09:53
@mmattel can you create another local test user that has no incoming fed shares. Can that user log in ?

Like you said it seems related to unavailable fed shares.

**Comment by PVince81** [comment] 2016-05-31 09:53
@owncloud/sharing @owncloud/filesystem

**Comment by mmattel** [comment] 2016-05-31 12:38
Here is what I did:

- Logon as admin user
- Create a new user (user_x), no assignment to the group which acesses the federated share
- Logoff and logon as user_x

Logon as user_x worked

- Logoff and logon as admin user
- Assign the group to user_x to access the federated share
- Logoff and logon as user_x

Logon as user_x does not work
```
{"reqId":"RHy3iKXMEW5xJU+KK2dj","remoteAddr":"xx.xx.xx.xx","app":"core","message":
"","level":3,"time":"2016-05-31T13:21:25+02:00","method":"POST","url":"\/index.php\/login?user=user_x","user":"user_x"}
```
```
{"reqId":"RHy3iKXMEW5xJU+KK2dj","remoteAddr":"xx.xx.xx.xx","app":"PHP","message":"
Call to a member function getStorageCache() on a non-object at \/var\/www\/owncloud\/lib\/private\/Files\/Config\/LazyStorageMountInfo.php#50","level":3,"time":"2
016-05-31T13:21:25+02:00","method":"POST","url":"\/index.php\/login?user=user_x","user":"user_x"}
```

- Logon as admin user
- (Try) to change to the users screen. Hanging forever.
- Some errors like File with id \"701\ are logged for different id´s
```
{"reqId":"QmmNNLf3nDWHNjDIfMIc","remoteAddr":"xx.xx.xx.xx","app":"core","message":
"File with id \"701\" has not been found.","level":3,"time":"2016-05-31T13:22:11+02:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=&pattern=","user":"admin_user"}
```

Looking into the oc_filecache table and selecting the file with fileid=701, the file is related to a file or a folder of the federated share (oc_storages: shared::xxxxxxx)

**Comment by mmattel** [comment] 2016-05-31 12:52
**Note:** having a instance 9.0.2 with the same setup, no problems occur

**Comment by PVince81** [comment] 2016-05-31 15:09
> the group which acesses the federated share

One cannot create a federated share directly to a group, so I guess this is an indirect share ?
Is one user receiving the federated share and then resharing with a group ? Is the folder reshared directly or is its parent reshared ? (if that's even possible, I don't remember)

**Comment by mmattel** [comment] 2016-05-31 15:52
Ah, sorry did not mention, here is the exact user setup, but does not change the issue.
- ``admin`` allows resharing
- ``admin`` allows resharing with gropus
- ``admin`` restricts resharing within groups only (don´t know the English text exactly)
- ``admin`` allows users to recieve federated shares
- ``admin`` creates user ``user_group_admin``
- ``admin`` creates user ``user_x``
- ``admin`` creates 3 groups, ``g_1``, ``g_2``, ``g_3``
- ``admin`` grants ``user_group_admin`` to administer these 3 groups
- ``admin`` adds ``user_x`` to group ``g_1``
- ``user_group_admin`` recieves a invite to a federated share and accepts it
- ``user_group_admin`` grants access via group ``g_1`` (which contains ``user_x``) to some federated share folders 

The problem is now, that with 9.1.0 beta, logging on with any user that is granted to access the federated share is no longer possible, while any user that is not granted to access the federated share can logon on.

It does not matter if the user who can not logon anymore (or where owncloud troubles) is the ``user_group_admin`` (the federated share reciever) or ``user_x`` (granted via group).

When removing ``user_x`` via the ``admin`` from the group ``g_1`` (which has a grant to the federated share), he can now relogon again.

Under 9.0.2, all works.

**Comment by rullzer** [comment] 2016-06-01 08:24
Aaaah mmm seems we try to move a mountpoint (probabaly duplicated incomming shares). But we can't find the file the share points at... not good... we should do better error handling... I'll fix this

**Comment by rullzer** [comment] 2016-06-07 14:36
mmm I can't reproduce the setup. In 9.1 it is impossible to create the setup you describe since `user_group_admin` is not a member of `g1` so it can't share with that group.

**Comment by rullzer** [comment] 2016-06-07 14:42
And if `user_group_admin` is a member of `g1` all works as expected here...

**Comment by PVince81** [comment] 2016-06-10 09:57
> mmm I can't reproduce the setup. In 9.1 it is impossible to create the setup you describe since user_group_admin is not a member of g1 so it can't share with that group.

@rullzer is it possible to create that setup in older versions ? @mmattel mentioned that the problem happens after an upgrade

**Comment by PVince81** [comment] 2016-06-10 09:58
else it might need some database hacking to recreate this situations, which might have been created by older bugs and carried over when updating.

**Comment by rullzer** [comment] 2016-06-10 11:32
@PVince81 I tried with upgrade from 9.0 as well... all works here...
@mmattel can you recreat the issue on a docker container?

**Comment by mmattel** [comment] 2016-06-10 12:53
Will check, but takes time. Will be off about 1 month...

**Comment by rullzer** [comment] 2016-06-10 13:58
@PVince81 I even tried the manual DB thing... all still works over here... So no idea how to debug then...

**Comment by oparoz** [comment] 2016-06-10 23:14
I'm having the same symptoms, but without using federated sharing.

As soon as `Test\TestCase::loginAsUser` is called, I get:

```
PHP Fatal error:  Uncaught Error: Call to a member function getStorageCache() on null in /lib/private/Files/Config/LazyStorageMountInfo.php:50
Stack trace:
#0 /lib/private/Files/Config/UserMountCache.php(128): OC\Files\Config\LazyStorageMountInfo->getStorageId()
#1 /lib/private/Files/Config/UserMountCache.php(113): OC\Files\Config\UserMountCache->addToCache(Object(OC\Files\Config\LazyStorageMountInfo))
#2 /lib/private/Files/Config/MountProviderCollection.php(133): OC\Files\Config\UserMountCache->registerMounts(Object(OC\User\User), Array)
#3 /lib/private/Files/Filesystem.php(425): OC\Files\Config\MountProviderCollection->registerMounts(Object(OC\User\User), Array)
#4 ... in /lib/private/Files/Config/LazyStorageMountInfo.php on line 50
```

The user manager in the GUI is unreachable.

Code looks like this

```
if ($this->userManager->userExists($user)) {
	$this->userManager->get($user)
					  ->delete();
}
$user = $this->userManager->createUser($userId, $password);
Test\TestCase::loginAsUser($userId);
```

And is available here:
https://github.com/owncloud/gallery/blob/master/tests/_support/Helper/DataSetup.php#L232

**Comment by icewind1991** [comment] 2016-06-13 11:32
@oparoz can you try https://github.com/owncloud/core/pull/25076

**Comment by oparoz** [comment] 2016-06-13 11:44
Thanks @icewind1991 - That fixes the problem for me.
Looking at the patch, I'm still a bit worried, this seems to help select the proper storage for caching, but the impression I got when tracing the problem was that the cache was not properly cleared when a user was removed and when creating the user a 2nd time, he would get shared storage from a previous life which doesn't exist yet.
Does that make sense?

**Comment by icewind1991** [comment] 2016-06-13 11:46
https://github.com/owncloud/core/pull/25077 should at least prevent oc from dying with the original issue (cc @mmattel)

**Comment by icewind1991** [comment] 2016-06-13 11:48
@oparoz: hooks should clean up the user mount cache when a user is deleted, maybe these hooks aren't setup in the tests?

**Comment by oparoz** [comment] 2016-06-13 11:58
>maybe these hooks aren't setup in the tests?

@icewind1991 - That's very possible, but I'm calling `$this->userManager->get($user)->delete();` which fires events which should be captured by the filesystem class set up via the standard TestCase class.

**Comment by PVince81** [comment] 2016-06-21 10:26
Ok, so since there's a fix that mitigates this, downgrading severity to high.

**Comment by PVince81** [comment] 2016-06-21 10:27
@oparoz were you running master or 9.0.x ?

I just asked for a backport in the PR for more robustness, just in case.

**Comment by PVince81** [comment] 2016-08-19 10:58
Is this still happening with 9.1.1 RC1 ? There were some bigger fixes for shared storage.

**Comment by mmattel** [comment] 2016-08-19 11:40
@PVince81 
I installed 9.1.0 stable from scratch because all the updates of the old system "confused" the former instance. Running 9.1 stable, the error did not longer occur.

**Comment by PVince81** [comment] 2016-09-13 08:33
Closing then. If the error occurs again with 9.1.1RC2, please reopen.

**Closed by PVince81** 2016-09-13 08:33 UTC
Labels: bug, feature:federated-cloud-sharing, sev2-high
