### ISSUE TITLE
Temporary files not deleted

### ISSUE THREAD

**Issue by marbetschar** [owncloud/core#19995] opened 2015-10-23 09:19 UTC
It seems our ownCloud instance is not cleaning up the temporary directory on Ubuntu. As you can see on the following screenshot this grabs a huge amount of the available disk space:

<img width="1053" alt="bildschirmfoto 2015-10-23 um 11 16 08" src="https://cloud.githubusercontent.com/assets/392542/10688884/d2cbf886-7977-11e5-8752-68848042b228.png">

### Steps to reproduce
1. Sync huge files using OS X client

### Expected behavior
Automatic cleanup of the /tmp directory

### Actual behavior
The tmp dir is not cleaned.

### Server configuration
**Operating system**:
OSX El Capitan v10.11

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
5.6.14-1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'drive.mandelkind.pizza',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud.mandelkind.coffee',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => 'mandelkind'
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No - how to enable encryption?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by PVince81** [comment] 2015-10-26 11:12
The "/tmp" directory is not used when syncing files. Syncing works in the folder "/var/www/owncloud/data/$user/cache".

However I believe that "/tmp" is used for some external storages and some LDAP caches, but you seem to be using neither ?

**Comment by PVince81** [comment] 2016-03-01 21:51
Ah, and uploading over the web UI with POST makes PHP store temp files there before reaching them to OC. I thought it would delete them automatically.

Something to investigate.

**Comment by PVince81** [comment] 2016-07-04 16:01
I have just tested with 9.0.3 and I can see that the files disappear from the tmp folder as soon as the web UI upload has finished.

PHP should automatically delete the file as soon as the PHP request has finished.
Unless maybe there's something in your setup that is preventing the requests to finish ?

I'm closing this as "cannot reproduce" for now.
If you still have this issue with 8.2.6 or 9.0.3 and have double checked your PHP configs, feel free to reopen.

**Closed by PVince81** 2016-07-04 16:01 UTC
Labels: bug
