### ISSUE TITLE
No upates with the built-in Updater app (webhosted, no root access)

### ISSUE THREAD

**Issue by Haio11** [owncloud/core#35316] opened 2019-05-23 10:17 UTC
### Steps to reproduce
1.Built-in Updater (stable, production, beta) says: "Your version is up to date"
2.On daily-channel it shoes new version 100.0.0.0
3.

### Expected behaviour
Tell us what should happen
Update to a new version
### Actual behaviour
Tell us what happens instead
No updates found
### Server configuration
**Operating system**:
Linux
**Web server:**
Linux XXX.org 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64"
**Database:**
mysql 5.7.24
**PHP version:**
7.2.15
**ownCloud version:** (see ownCloud admin page)
10.0.10.4
**Updated from an older ownCloud or fresh install:**
10.0.10.3
**Where did you install ownCloud from:**
Built-in Updater app
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

[config_report_20190523.txt](https://github.com/owncloud/core/files/3211589/config_report_20190523.txt)

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 67
**Operating system:**
macOS 10.14.5
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment] 2019-06-21 20:21
@Haio11 10.2.0 was unlocked for beta channel this week but I suggest to wait 1-2 week and grab 10.2.1

closing as duplicate of https://github.com/owncloud/core/issues/34625

**Closed by VicDeo** 2019-06-21 20:21 UTC
