### ISSUE TITLE
[6.0.2RC1] File size/Quota misleading

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7424] opened 2014-02-26 14:18 UTC
When using External storage mounts, the file size of the mount is shown in the Files page of ownCloud.  At the bottom of the files page is the sum of all file sizes:

![page1](https://f.cloud.github.com/assets/5174383/2270634/719b2752-9ef0-11e3-987c-f4ba41ad3f2d.PNG)

However, since external storage mounts don't count towards the quota, the Quota bar on the Personal page shows the following:

![quota](https://f.cloud.github.com/assets/5174383/2270637/881bb910-9ef0-11e3-8143-3bc1101ebe45.PNG)

As these two numbers are different (63.7MB v 160K), the user may get confused.

Minor aesthetic issue, but something that should be addressed somehow to limit the confusion of the user who is unaware that:
1) External mounts exist
2) External mounts don't count toward quota size

**Comment by jancborchardt** [comment] 2015-03-23 12:15
Closing because it works as designed. It would be more confusing when leaving out the external storages in the list count.

**Closed by jancborchardt** 2015-03-23 12:15 UTC
Labels: app:files_external, Design, Quota
