### ISSUE TITLE
Error on update gentoo

### ISSUE THREAD

**Issue by ShinyPika** [owncloud/core#17360] opened 2015-07-02 17:44 UTC
If I try to update from version 8.0.2 to 8.0.4 it throws the following exception

An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_gz7dj6ky8n80d` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.

**Comment by LukasReschke** [comment] 2015-07-02 18:00
Duplicate of https://github.com/owncloud/core/issues/16008 which also contains the solution

**Closed by LukasReschke** 2015-07-02 18:00 UTC

**Comment by RealRancor** [comment] 2015-07-02 21:51
Also documented here: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html#troubleshooting
