### ISSUE TITLE
Apps can't activate

### ISSUE THREAD

**Issue by Owned67** [owncloud/core#13599] opened 2015-01-22 14:22 UTC
Hi,

App => Admin Dependency check 0.0.1 => Enable => L'application ne fournit pas de fichier info.xml (The application does not provide info.xml file)

In ../owncloud/apps2/admin_dependencies_chk/appinfo/info.xml:
```
<?xml version="1.0"?> 
<info>
	<id>admin_dependencies_chk</id>
	<name>ownCloud dependencies info</name>
	<licence>AGPL</licence>
	<author>Brice Maron (eMerzh)</author>
	<requiremin>4.93</requiremin>
	<shipped>true</shipped>
	<description>Display OwnCloud's dependencies informations (missings modules, ...)</description>
	<ocsid>166041</ocsid>
</info>
```

and same for others apps......

**Comment by MorrisJobke** [comment] 2015-01-22 14:33
@karlitschek Can we drop this app? Most dependency checks are already there and are listed in the install step with a help text.

**Comment by karlitschek** [comment] 2015-01-22 14:34
yes. we can drop this.

**Comment by Owned67** [comment] 2015-01-22 14:48
You are going to fix the bug?

**Comment by MorrisJobke** [comment] 2015-01-22 16:21
@Owned67 You don't need this app anymore. It is simply outdated and the functionality is now build into ownCloud.

**Comment by MorrisJobke** [comment] 2015-01-22 16:22
@Owned67 What other apps have this problem? Please also fill out this template https://github.com/owncloud/core/blob/master/issue_template.md

**Comment by DeepDiver1975** [comment] 2015-01-22 16:28
@MorrisJobke it's still interesting to know where this error is coming from - this has not been reported the first time - can you please investigate? THX

**Comment by MorrisJobke** [comment] 2015-01-22 16:32
@DeepDiver1975 I wait for the version details and then try to reproduce.

**Comment by Owned67** [comment] 2015-01-22 18:26
ok but all the apps are obsolete? (those present in the admin panel)

**Comment by MorrisJobke** [comment] 2015-01-22 20:06
@Owned67 Not just admin_dependencies_chk. Can you still fill out the issue template and describe the steps to reproduce this? Thanks

**Comment by Owned67** [comment] 2015-01-22 22:47
Connect to panel > Application > Select activity (for sample) > click for activate and same error...

Same for PDF Viewer etc......

**Comment by RealRancor** [comment] 2015-01-24 12:32
Hi,

this happens because the app is pulled from:

https://apps.owncloud.com/content/show.php/Admin+Dependency+check?content=166041

The appstore is providing an empty package with the version 0.0.1 where the version of this app shipped with OC is 0.0.2.

@Owned67 
Seems you have broken your apps configuration in some way.

**Comment by Owned67** [comment] 2015-01-24 12:58
lmao and how? 

I tested five setup (debian and ubuntu) and the result is the same.

**Comment by RealRancor** [comment] 2015-01-24 13:03
Hi,

please post the full issue template as already asked two times:

https://github.com/owncloud/core/blob/master/issue_template.md

**Comment by Owned67** [comment] 2015-01-24 17:16
Steps to reproduce

Connect to panel > Application > Select activity (for sample) > click for activate and same error...

Same for PDF Viewer etc......




Tell us what should happen: enable applications

Tell us what happens instead: L'application ne fournit pas de fichier info.xml

Server configuration

Operating system: Debian Wheezy x64

Web server: nginx 1.6.2

Database: mysql  Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (x86_64) using readline 6.2

PHP version: PHP 5.4.36-1~dotdeb.1 (cli) (built: Dec 19 2014 23:01:37)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

ownCloud version: Ownclod 7.0.4.2

Updated from an older ownCloud or fresh install: fresh install

List of activated apps: default

The content of config/config.php:

Insert your config.php content here
	
	$CONFIG = array (
	  'instanceid' => 'oc9e844ea45b',
	 'trusted_domains' => 
	  array (
		0 => 'mydomaine.net',
	  ),
	  'datadirectory' => '/home/serveur/data',
	  'overwrite.cli.url' => 'https://mydomaine.net/owncloud',
	  'dbtype' => 'mysql',
	  'version' => '7.0.4.2',
	  'dbname' => 'owncloud',
	  'dbhost' => 'localhost',
	  'dbtableprefix' => 'oc_',
	  'dbuser' => 'oc_Myusername',
	  'dbpassword' => 'my_password',
	  'installed' => true,
	  'loglevel' => '3',
	  'check_for_working_webdav' => false,
	  'forcessl' => true,
	  /* Added for enable apps2 folder */
	  'apps_paths' =>
	  array (
		0 =>
		array (
		  'path' => OC::$SERVERROOT.'/apps2',
		  'url' => '/apps2',
		  'writable' => false,
		)
		),

	);


Are you using external storage, if yes which one: local/smb/sftp/...: no

Are you using encryption: yes
Client configuration

Browser: Firefox 35 and Google Chrome (latest version)

Operating system: Windows 7 Ulimate x64

Logs
Web server access/error log
http://pastebin.com/kisDEDNZ

http://pastebin.com/tyPEpGzi

ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-24T16:58:45+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-24T16:59:04+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-24T17:00:10+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-24T17:00:25+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-24T17:00:25+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-24T17:09:56+00:00"}
{"app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2015-01-24T17:10:16+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-24T17:10:18+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-24T17:10:18+00:00"}
{"app":"PHP","message":"ZipArchive::extractTo(): Invalid or unitialized Zip object at \/home\/serveur\/www\/owncloud\/lib\/private\/archive\/zip.php#135","level":3,"time":"2015-01-24T17:11:15+00:00"}
{"app":"core","message":"L'application ne fournit pas de fichier info.xml","level":3,"time":"2015-01-24T17:11:15+00:00"}

Browser log: what?

**Comment by MorrisJobke** [comment] 2015-02-27 15:08
https://github.com/owncloud/core/blob/970b14d2979cb03d1e9ba96cbce3e43a52835333/lib/private/installer.php#L309

@Owned67 It look like something went wrong with your apps. It seems that ownCloud can't read the info.xml or the info.xml isn't present for the apps. Can you have a look into your apps folder: go then to a broken app. In there should be a folder `appinfo` with a file `info.xml`. Is this file readable by the webserver user? (full path for activity for example: `apps/activity/appinfo/info.xml`)

**Comment by karlitschek** [comment] 2015-03-26 13:19
I think this should be fixed by the latest improvements in the apps management. Specifically with 8.0.3
Please reopen if the error still exists

**Closed by karlitschek** 2015-03-26 13:19 UTC
Labels: bug, needs info

**Comment by Vskilet** [comment] 2015-05-04 21:24
I have the same issues  on a CentOS 7 virtual machine. I've just finished to install owncloud 8.0.3 but i've the beautifull message about the "info.xml".

**Comment by Owned67** [comment] 2015-05-20 19:02
hello, 

0.8.3 work fine and problem solved for me!
