### ISSUE TITLE
Shared Files Renaming

### ISSUE THREAD

**Issue by dubsflyt** [owncloud/core#8558] opened 2014-05-12 15:57 UTC
Steps to reproduce
1. User1 shares folder with other users
2. User1 renames folder through web interface (not sync or map drive)
3. Folder dissapears for all users but files are still in the data folder on server with the renamed name

Expected behaviour

File/Folder should be renamed as you would expect for all users. Or at least the rename button should be disabled for shared folders if this is broken.

Actual behaviour
Folder dissapears from map drive / sync client / website but still exist in their proper location on server

Server configuration
Operating System: CentOS 6.5

Web Server: Apache

Database : MySQL

PHP Version: tried with both 5.3 and 5.5.12 (current version)

OwnCloud Version: 6.0.3

@schiesbn

**Comment by PVince81** [comment] 2015-04-13 09:20
Do these folders contain a lot of files ? If yes, it could be a duplicate of https://github.com/owncloud/core/issues/13391

**Comment by PVince81** [comment] 2015-04-29 14:04
There was another issue about renaming the folder back to the original name would make it disappear: https://github.com/owncloud/core/issues/15340

@libasys your steps seem to be different. I you see an issue with these, please raise a separate ticket. Thanks

**Closed by PVince81** 2015-04-29 14:04 UTC
Labels: bug, needs info, sharing
