### ISSUE TITLE
LDAP users unable to login 

### ISSUE THREAD

**Issue by cburnard** [owncloud/core#17627] opened 2015-07-13 19:55 UTC
### Steps to reproduce
1.Unable to reproduce 
2.
3.

### Expected behaviour
LDAP configuration is green.  Users are shown in the 'users' page.  AD users should be able to login into oC 

### Actual behaviour
AD users attempting to login is sporadic and interment.  oC log file contains numerous LDAP errors 

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4

**Database:**  MariaDB 5.5

**PHP version:** 5.4

**ownCloud version:** 8.0.5

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** See report config on S3
https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17627
**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'supportedDatabases' => 
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
    3 => 'mssql',
  ),
  'instanceid' => 'abc123',
  'passwordsalt' => 'abc123',
  'secret' => '.abc123',
  'trusted_domains' => 
  array (
    0 => 'xxx.xxx.xxx.xxx',
    1 => 'xxx.xxx.org',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://xxx.xxx.xxx.xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.5.2',
  'dbname' => 'owncloud',
  'dbhost' => '10.0.xxx.xxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_oc-admin',
  'dbpassword' => 'xxx',
  'installed' => true,
  'license-key' => 'abc123',
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'ownCloud',
  'mail_domain' => 'abc123',
  'mail_smtphost' => '10.0.xx,xx',
  'debug' => '1',
);

```

**Are you using external storage, if yes which one:**  NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** ActiveDirectory...

#### LDAP configuration 

See report config on S3

#### ownCloud log (data/owncloud.log) See report config on S3
https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17627

@bboule @gig13 @MorrisJobke

**Comment by MorrisJobke** [comment] 2015-07-14 07:25
1419 times following:

```
{"reqId":"9ef6b207a030b5ecbdac5618a6d99282","remoteAddr":"1.2.3.4","app":"PHP","message":"Non-static method OCA\\user_ldap\\lib\\Helper::getServerConfigurationPrefixes() should not be called statically at owncloud\/apps\/files_ldap_home\/lib\/storage.php#71","level":3,"time":"2015-07-13T19:47:10+00:00"}
{"reqId":"9ef6b207a030b5ecbdac5618a6d99282","remoteAddr":"1.2.3.4","app":"PHP","message":"Argument 3 passed to OCA\\user_ldap\\User_Proxy::__construct() must implement interface OCP\\IConfig, none given, called in owncloud\/apps\/files_ldap_home\/lib\/ldapreader.php on line 30 and defined at owncloud\/apps\/user_ldap\/user_proxy.php#39","level":3,"time":"2015-07-13T19:47:10+00:00"}
{"reqId":"9ef6b207a030b5ecbdac5618a6d99282","remoteAddr":"1.2.3.4","app":"PHP","message":"Undefined variable: ocConfig at owncloud\/apps\/user_ldap\/user_proxy.php#43","level":3,"time":"2015-07-13T19:47:10+00:00"}
{"reqId":"9ef6b207a030b5ecbdac5618a6d99282","remoteAddr":"1.2.3.4","app":"PHP","message":"Argument 2 passed to OCA\\user_ldap\\USER_LDAP::__construct() must implement interface OCP\\IConfig, null given, called in owncloud\/apps\/user_ldap\/user_proxy.php on line 43 and defined at owncloud\/apps\/user_ldap\/user_ldap.php#45","level":3,"time":"2015-07-13T19:47:10+00:00"}
```

**Comment by bboule** [comment] 2015-07-14 19:51
@MorrisJobke @blizzz @cmonteroluque  Hey Guys could we get someone to take a closer look at this?  We have a deployment that is dead in the water just trying to sort out what might be happening.  It looks like sporadic failures and the above log message repeating over and over!!

**Comment by blizzz** [comment] 2015-07-15 10:37
Incompatibilities in user_ldap_home, needs https://github.com/owncloud/enterprise/pull/484

**Comment by gig13** [comment] 2015-07-15 12:08
@blizzz 
This is not the LDAP Home Connector, this is the User and Group Backend

**Comment by blizzz** [comment] 2015-07-15 12:36
> Non-static method OCA\\user_ldap\\lib\\Helper::getServerConfigurationPrefixes() **should not be called statically at owncloud\/apps\/files_ldap_home\/lib\/storage.php#71**

> Argument 3 passed to OCA\\user_ldap\\User_Proxy::__construct() must implement interface OCP\\IConfig, none given, called in **owncloud\/apps\/files_ldap_home\/lib\/ldapreader.php on line 30** and defined at owncloud\/apps\/user_ldap\/user_proxy.php#39

are about files_ldap_home.

@gig13 Or was files_ldap_home disabled and you still reproduce  it?

**Comment by blizzz** [comment] 2015-07-15 12:39
P.S.: and the others are too although it is not mentioned, but because files_ldap_home classes are based on those.

**Comment by cburnard** [comment] 2015-07-15 14:22
@blizzz 
    Disabling LDAP Home suppressed that error.  AD users unable to login.  New error popping up (was not there before and most likely unrelated ) is : 

     
 ...{"reqId":"0106e17d67d23282c9b587895f2671dc","remoteAddr":"50.241.102.21","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-07-15T14:08:23+00:00"}
{"reqId":"73d81a2db51ca339694cb13b60198787","remoteAddr":"50.241.102.21","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-07-15T14:08:24+00:00"}
{"reqId":"6fa3933230cdbf4b35900bb45325bd34","remoteAddr":"50.241.102.21","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-07-15T14:08:24+00:00"}
{"reqId":"4fb85de2eed59038be89d2b140db9683","remoteAddr":"50.241.102.21","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#254","level":3,"time":"2015-07-15T14:08:38+00:00"}

**Comment by blizzz** [comment] 2015-07-15 14:35
Do the users have the displayname attribute set in AD? If not switch user display name attribute to cn. Or can the users be seen on the Users page?

**Comment by cburnard** [comment] 2015-07-15 14:42
displayname is set in AD.  Tried switching to cn, same results.  Users are populated in the Users page.

**Comment by blizzz** [comment] 2015-07-15 15:06
And they are trying to log in using either their email or Windows/AD-Username?

Can they set the loglevel to everything, attempt one login  and send the resulting log, please?

**Comment by cburnard** [comment] 2015-07-15 16:21
Both email and ADusername fail.

Updated log file -vv on S3
https://s3.owncloud.com/owncloud/index.php/apps/files/?dir=%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F17627

**Comment by blizzz** [comment] 2015-07-15 16:40
@cburnard  Looks like the old stuff still, last updated 2 days ago, could you recheck?

**Comment by cburnard** [comment] 2015-07-15 17:02
@blizzz Sorry  sync client was point at another server.  Check now.

**Comment by cburnard** [comment] 2015-07-15 20:33
Users able to login now.  "Case insensitive LDAP server" was selected.  Un-Selecting this allowed AD users to login.  AD server is a 2008 and in 2008 mode.  

Chris

**Comment by blizzz** [comment] 2015-07-16 11:24
You will be delighted to hear that the  "Case insensitive LDAP server" is actually a dead setting that does not do anything at all anymore (if it ever did when i took it over). 

What might have happened when changing the settings that the cache was cleared, but as it's lifetime is configured to just 5s, that's highly unlikely.

The latest log entries are saying that the password was wrong.

**Comment by blizzz** [comment] 2015-07-16 11:40
Update on the nocase/ "Case insensitive LDAP server"  setting: it was introduced here  https://github.com/owncloud/core/commit/dd7a411f9aaceab1bf8eab551e5f95ff5feff6fb#diff-8f8c85e2bc7e4aea46a03f77c54622c7R119 end of Nov 11 and the only function it had was to lower name  attribute names returned from the LDAP server. For a long time we do it in general anyway, the user should not be confronted with that setting. What is left (the checkbox and reading and writing the setting) should be removed as well.

**Comment by blizzz** [comment] 2015-07-16 11:49
Closing as it is resolved.

**Closed by blizzz** 2015-07-16 11:49 UTC
Labels: app:user_ldap, bug, purple-ticket
