### ISSUE TITLE
Translations not working for ldap users.

### ISSUE THREAD

**Issue by EdwinOsterEmbeddedArt** [owncloud/core#23425] opened 2016-03-21 10:12 UTC
### Steps to reproduce
1. Install OC9 with ldap backend.
2. Have 2 users, 1 OC and 1 LDAP, both with any language other than english (in my example Swedish).
3. Open files.

### Expected behaviour
All text should be in chosen language regardless of user authentication.

### Actual behaviour
Some text from apps like sharing and trashbin is not translated for ldap users, but is translated for normal users. Left is a normal user and right is a ldap user.

![screenshot from 2016-03-18 10 29 42](https://cloud.githubusercontent.com/assets/16953943/13915306/328d6726-ef54-11e5-9267-1ebd30859fb5.png)

### Server configuration
**Operating system**:
linux mint 17.2
**Web server:**
apache/2.4.7 (Ubuntu)
**Database:**
sqlite3
**PHP version:**
PHP version: 5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
stable9 from git (382b18e)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
**Signing status (ownCloud 9.0 and above):**

Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

Enabled:
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - files_external
  - testing

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocujz0cibu78",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/html\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "sqlite3",
        "version": "9.0.0.19",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
    },
    "apps": {
        "backgroundjob": {
            "lastjob": "7"
        },
        "comments": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1458309997.1841",
            "lastupdatedat": "1458552595",
            "public_files": "files_sharing\/public.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "oc.integritycheck.checker": "{\"Application to check\":{\"EXCEPTION\":{\"class\":\"Exception\",\"message\":\"App not found\"}},\"file\":{\"EXCEPTION\":{\"class\":\"Exception\",\"message\":\"App not found\"}}}",
            "lastcron": "1458552824",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}"
        },
        "dav": {
            "installed_version": "0.1.5",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "0.0.4",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.4.4",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_sharing": {
            "installed_version": "0.9.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "0.8.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        },
        "user_ldap": {
            "installed_version": "0.8.0",
            "types": "authentication",
            "enabled": "yes",
            "ldap_host": "192.168.24.37",
            "ldap_port": "389",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_base": "dc=test,dc=com",
            "ldap_base_users": "dc=test,dc=com",
            "ldap_base_groups": "dc=test,dc=com",
            "ldap_dn": "cn=admin,dc=test,dc=com",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_display_name": "cn",
            "ldap_user_display_name_2": "",
            "ldap_userfilter_objectclass": "inetOrgPerson",
            "ldap_userfilter_groups": "",
            "ldap_userlist_filter": "(|(objectclass=inetOrgPerson))",
            "ldap_user_filter_mode": "0",
            "ldap_group_filter": "",
            "ldap_group_filter_mode": "0",
            "ldap_groupfilter_objectclass": "",
            "ldap_groupfilter_groups": "",
            "ldap_group_display_name": "cn",
            "ldap_group_member_assoc_attribute": "uniqueMember",
            "ldap_login_filter": "(&(|(objectclass=inetOrgPerson))(uid=%uid))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_loginfilter_attributes": "",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_email_attr": "",
            "ldap_cache_ttl": "600",
            "ldap_override_main_server": "",
            "ldap_configuration_active": "1",
            "ldap_attributes_for_user_search": "",
            "ldap_attributes_for_group_search": "",
            "ldap_experienced_admin": "0",
            "home_folder_naming_rule": "",
            "has_memberof_filter_support": "",
            "use_memberof_to_detect_membership": "1",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "last_jpegPhoto_lookup": "0",
            "ldap_nested_groups": "0",
            "ldap_paging_size": "500",
            "ldap_dynamic_group_member_url": "",
            "cleanUpJobOffset": "0"
        }

**Are you using external storage, if yes which one:** 
no
**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** 
ldap
#### LDAP configuration (delete this part if not used)
included in server config.

### Client configuration
**Browser:**
firefox, chrome
**Operating system:**
win7, linux mint
#### Web server error log
```
it's empty
```

#### ownCloud log (data/owncloud.log)
{"reqId":"VIC7rYkRCbS7wGZv9w8g","remoteAddr":"127.0.0.1","app":"PHP","message":"vsprintf(): Too few arguments at \/var\/www\/html\/core\/lib\/private\/l10n\/string.php#71","level":3,"time":"2016-03-21T09:31:19+00:00"}
{"reqId":"VIC7rYkRCbS7wGZv9w8g","remoteAddr":"127.0.0.1","app":"PHP","message":"Method OC_L10N_String::__toString() must return a string value at \/var\/www\/html\/core\/lib\/private\/l10n\/l10n.php#84","level":3,"time":"2016-03-21T09:31:19+00:00"}

#### Browser log
console log:
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost 'unsafe-eval'"). files
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by PVince81** [comment] 2016-03-21 15:25
AFAIK there is no distinction for translations between regular and LDAP users.

Was this observed on the same browser instance ? Log in as regular user, check. Log in as LDAP user in the same browser, check. ?

Because if this is on different machines, maybe the browser's cache needs to be cleared for new translations to be loaded ?

**Comment by PVince81** [comment] 2016-03-21 15:26
@EdwinOsterEmbeddedArt where is the locale defined ? Do every user specify the locale in their "Personal" page ? Or does the language come from the browser settings ?

@blizzz can you do a local test for this to confirm that this works ?

**Comment by EdwinOsterEmbeddedArt** [comment] 2016-03-21 15:32
I checked with both users with-and-without incognito mode in both firefox and chrome on 2 computers. 
I planted som debug code in l10n and its seems only the translations for the files app is loaded for LDAP users.

**Comment by PVince81** [comment] 2016-03-21 15:39
Hmm, weird. @EdwinOsterEmbeddedArt which locale is this ?
Is this set in the browser language or as setting in ownCloud ? (just to be able to check locally)

**Comment by SergioBertolinSG** [comment] 2016-03-21 15:39
Not happening to me:

![screen shot 2016-03-21 at 16 38 02](https://cloud.githubusercontent.com/assets/9048796/13924148/82eb3192-ef83-11e5-9123-636a5305591f.png)

**Comment by blizzz** [comment] 2016-03-21 22:18
> @blizzz can you do a local test for this to confirm that this works ?

Works for me. Even with Swedish :)

**Comment by EdwinOsterEmbeddedArt** [comment] 2016-03-22 07:38
I set the language in the personal page in owncloud.

**Comment by EdwinOsterEmbeddedArt** [comment] 2016-03-22 08:32
I did not know you could set a preferred language in the browser. If I switch it to Swedish there I it shows the missing translations, but if I now select English in owncloud I get the reverse:
![screenshot from 2016-03-22 09 29 03](https://cloud.githubusercontent.com/assets/16953943/13945822/a5f063dc-f010-11e5-8ebd-2740996a982f.png)

**Comment by SergioBertolinSG** [comment] 2016-03-22 09:58
Ok, I think I get what is the problem:

# Steps to reproduce
Using chrome do:
1. Go to personal page, put ownCloud in castellano. Wait to see it in spanish.
2. In personal page switch language to svenska. Wait to see it in swedish.

# Observed behaviour:

Not all strings are retranslated:
![screen shot 2016-03-22 at 10 55 19](https://cloud.githubusercontent.com/assets/9048796/13947817/e48ec4f6-f01c-11e5-971b-8d1f1ea6cd2b.png)

**Comment by DeepDiver1975** [comment] 2016-04-05 12:41
@nickvergessen is this fixed by #22695 ????

**Comment by nickvergessen** [comment] 2016-04-05 13:02
I can't test with ldap, but atleast the menu problem from Sergio should be

**Comment by PVince81** [comment] 2016-04-29 14:27
Closing as fixed then

**Closed by PVince81** 2016-04-29 14:27 UTC
Labels: bug, feature:l10n
