### ISSUE TITLE
  "users" page keeps on loading

### ISSUE THREAD

**Issue by varad-14** [owncloud/core#13230] opened 2015-01-10 07:38 UTC
Hi Team,

We have installed Owncloud 7.0.4.2 in the ubuntu server 14.04-amd64 and integrated with Active Directory for Authentication.We can login through AD users .

In our AD, we have around more then 1,00,000 users and more then 1000 groups. After enabled AD authentication, if you click "Users" option, page is keeps on loading and it's not displaying users page. If we verify logs,

```
{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter (&(objectClass=group)(objectsid=S-1-5-21-1783026939-2436384249-325622171-515)) base Array\n(\n [0] => OU=TS,OU=rr,DC=abc,DC=OR,DC=abc,DC=IN\n)\n attr Array\n(\n [0] => dn\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=dt16341,cn=computers,dc=eo,dc=corp,DC=abc,dc=in\n)\n attr Array\n(\n [0] => \n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"readAttribute: cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in found","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in\n)\n attr Array\n(\n [0] => sAMAccountName\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in\n)\n attr Array\n(\n [0] => primaryGroupID\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}
```
keeps on loading for past one week and in the "Users" page not at all displaying.

Also it's asking after a long time in the browser as,

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: https://owncloud.abc.com/core/js/jquery ... 1edf2998:4

Local system is completly hang.

Please let us know the solution for this ?

Regards,
Varad

**Comment by MorrisJobke** [comment] 2015-01-10 11:24
@blizzz Do you noticed something similiar? I don't see anything special in the logs.


@varad-14 Can I ask you to fill out the issue template to provide more information. Thanks

https://github.com/owncloud/core/blob/master/issue_template.md

**Comment by varad-14** [comment] 2015-01-10 13:03
Steps to reproduce
1. Configured ActiveDirectory for authentication and our AD have complex setup such as around 100000 users and 30000 groups.
2. Authentication working fine and click on the "Users" tab in the web interface.
Expected behaviour:

Once if you click the Users page, it shoul display all the users and groups

Actual behaviour:
1.Page is keeps on loading more then 2 days or a week
2.Users names are displaying special characters and the browser will be hang and suppose if you refresh the page, again it is keeps on loading page but no result

Server configuration

Operating system: Ubuntu 14.04 amd64 LTS

Web server: Apache-2.4.7-1ubuntu4.1

Database: Mysql-5.5.39-36.0

PHP version:5.5.9

ownCloud version: (see ownCloud admin page): 7.0.4.2

Updated from an older ownCloud or fresh install: Fresh install

List of activated apps:
CAS Authentication backend,Sharing, Enable LDAP Backend

The content of config/config.php:
<?php
$CONFIG = array (
  'instanceid' => 'oc83d4baf927',
  'trusted_domains' =>
  array (
    0 => 'owncloud.abc.com',
  ),
  'datadirectory' => '/apps/ww/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'forcessl' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  );


Are you using external storage, if yes which one: No

Are you using encryption:  https

Client configuration

Browser: Firefox,Chrome and IE

Operating system: Windows 7 and Ubuntu 14.04 Desktop
Logs:
Web server error log

only browser page is keeps on loading, that's all

ownCloud log (data/owncloud.log):
{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter (&(objectClass=group)(objectsid=S-1-5-21-1783026939-2436384249-325622171-515)) base Array\n(\n [0] => OU=TS,OU=rr,DC=abc,DC=OR,DC=abc,DC=IN\n)\n attr Array\n(\n [0] => dn\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=dt16341,cn=computers,dc=eo,dc=corp,DC=abc,dc=in\n)\n attr Array\n(\n [0] => \n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"readAttribute: cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in found","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in\n)\n attr Array\n(\n [0] => sAMAccountName\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"initializing paged search for Filter objectClass=* base Array\n(\n [0] => cn=amus,cn=computers,dc=eo,dc=or,DC=abc,dc=in\n)\n attr Array\n(\n [0] => primaryGroupID\n)\n limit 1 offset 0","level":0,"time":"2015-01-08T07:31:54+00:00","method":"GET","url":"\/index.php\/settings\/users"}

{"reqId":"54ae2978cd77f","app":"user_ldap","message":"Ready for a paged search","level":1,"

Note: The above type of logs are continously loading even in a two days or one week


Browser log:

Only blank page and sorry didn't get anyting.

Please let us know your further inputs ?

**Comment by varad-14** [comment] 2015-01-12 07:17
Hi Team,

Please let me know the update on my above issue ?

**Comment by blizzz** [comment] 2015-01-12 14:06
The User page will take time to load for the first time, because of the users count which takes some time with LDAP and this amount of users. Afterwards, it is cached (10 minutes by default). This actually was improved for 7.0.4, before there was no caching. Yet it is not ideal.

Also, all groups are loaded at once, as well, and with them connected information (user counts!). This is also known. 

There are few things you can do to improve it though, e.g. narrowing down the user and group  bases,  or even more restrictive filter for users and groups exclude those that you don't want to have in ownCloud anyway.

**Comment by varad-14** [comment] 2015-01-12 14:43
Blizz,

For first time means, it's running a week and whenever i click the "USERS", in the logs page keeps on going. Please find the below our LDAP server settings and let me know for any changes ?

LDAP Server Configuration:

Server:

ldaps://<server1 name> port:3269
cn=admin,,OU=exec ID,DC=abc,DC=OR,DC=abc,DC=IN
Basedn:
DC=abc,DC=OR,DC=abc,DC=IN
DC=bbc,DC=OR,DC=abc,DC=IN

check box enabled ==> Manually enter LDAP filters (recommended for large directories) 

User Filter:

(objectclass=person)

Login Filter:

(sAMAccountName=%uid)

Group Filter:

(objectClass=group)

ADVANCED:

Connection Settings:

Configuration Active : Enabled
Backup Host: ldaps://<Server2 name>
Backup port: 3269
Disable main server: unchecked (not enabled)
case insensitive LDAP server Windows: enabled
Turnoff ssl validation: enabled
Cache Time-to-Live: 600

Directory Settings:

User Display Name Field: cn
Base User Tree:
DC=abc,DC=OR,DC=abc,DC=IN
DC=bbc,DC=OR,DC=abc,DC=IN

User Search Attributes: sAMAccountName
Group Display Name Field: cn
Base Group Tree: OU=ST,OU=NNNNN,DC=abc,DC=OR,DC=abc,DC=IN
Group Search Attributes: member
Group-Member association: member (AD)
Nested Groups: enabled
Paging chunksize : 500

**Comment by blizzz** [comment] 2015-01-13 12:58
@varad-14 does it work better when you configure only one base DN each?

**Comment by varad-14** [comment] 2015-01-13 13:43
Hi Blizzz,
No and even if you specify single basedn also, we are facing same issue

**Comment by varad-14** [comment] 2015-01-16 11:03
Can anyone help us for the above issue please ?

**Comment by varad-14** [comment] 2015-01-19 08:03
Hi Team,

Anyone can update for solution and it's seriously affecting for us ?

Varad

**Comment by blizzz** [comment] 2015-03-24 13:05
What probably helps is to limit the number of groups, maybe you just whitelist some? At least to test. Too many groups yet are a performance trap as users are counted for every single of them.

**Comment by DeepDiver1975** [comment] 2015-03-24 17:30
@blizzz can we leverage the user experience by using some caching mechanism?

**Comment by blizzz** [comment] 2015-03-24 17:44
@DeepDiver1975 this will not help us, as it needs to be read initially. we need to improve user management. for example by loading only few groups and the rest by infinite loading. but i am not totally convinced by this. or reading groups counts only via ajax, if ensured that this is non-blocking for user events and actions, but this does ajax counts. Or we  count only up to so and so many users and display just > 500. Will still be bad with too many groups. Then we can see whether we can batch-read group members.

**Comment by blizzz** [comment] 2015-03-24 19:49
Another thought is that we indeed track group counts in the database and only refer to them, except the user count is not known. And also update it regularly using a background job.

**Comment by bboule** [comment] 2015-06-15 10:20
This issue I wonder if part of the issue is trying to consume the entire directory...  Are we effectively limiting things like computer accounts etc. to try and get down to a smaller subset of objects?  Thinking about solutions based on current code.

**Comment by butonic** [comment] 2015-06-19 09:35
AFAICT a workaround would be to not calculate the group member count. Try this patch which was proposed by @blizzz in a different context:
```diff
--- lib/private/group/metadata.php	2015-02-15 15:08:19.532831205 +0100
+++ fix-group-metadata.patch	2015-04-02 10:59:20.113237649 +0200
@@ -143,7 +143,7 @@
 		return array(
 				'id' => $group->getGID(),
 				'name' => $group->getGID(),
-				'usercount' => $group->count($userSearch)
+				'usercount' => 1
 			);
 	}
 ```

**Comment by blizzz** [comment] 2015-06-19 09:42
> This issue I wonder if part of the issue is trying to consume the entire directory... Are we effectively limiting things like computer accounts etc. to try and get down to a smaller subset of objects? Thinking about solutions based on current code.

This also depends on the LDAP structure that we cannot know or guess. Nevertheless, the admin can tune a few things herself: http://arthur-schiwon.de/5-performance-tips-using-ownclouds-ldap-backend

**Comment by PVince81** [comment] 2015-09-21 13:27
Any update?

**Comment by MorrisJobke** [comment] 2016-01-20 08:28
Most likely because of all groups loaded at once: Duplicate of https://github.com/owncloud/core/issues/9201

**Closed by MorrisJobke** 2016-01-20 08:28 UTC
Labels: app:user_ldap, bug
