### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by mbiebl** [owncloud/core#15291] opened 2015-03-28 06:06 UTC
Version: 8.0.2

I'm seeing a lot of those error messages in my ownCloud log

"Cannot modify header information - headers already sent by (output started at /www/htdocs/owncloud/lib/private/image.php:249) at /www/htdocs/owncloud/lib/private/appframework/app.php#100",

I think it's triggered by the ownCloud Android app when entering a folder with lots of images and the app tries to load the thumbnail previews.

**Comment by PVince81** [comment] 2015-03-28 10:23
@Raydiation @oparoz any idea ?

**Comment by Raydiation** [comment] 2015-03-28 11:20
Without looking at the code: The image class sends headers which conflict with the way the appframework works

**Comment by Raydiation** [comment] 2015-03-28 12:34
Yep, the image class prints data directly (including headers) which will conflict with other headers that need to be sent: https://github.com/owncloud/core/blob/stable8/lib/private/image.php#L249

**Comment by oparoz** [comment] 2015-03-28 12:35
Probably a duplicate of https://github.com/owncloud/core/issues/12712

**Comment by enoch85** [comment] 2015-03-28 12:43
Dup

**Closed** 2015-03-28 12:43 UTC
Labels: bug
