### ISSUE TITLE
updater shows major upgrade instead of minor update

### ISSUE THREAD

**Issue by tessus** [owncloud/core#14814] opened 2015-03-11 19:16 UTC
I'm running ownCloud 7.0.4 and I see this when I log in:

![screen shot 2015-03-11 at 15 09 01](https://cloud.githubusercontent.com/assets/223439/6604703/bd8f0a90-c800-11e4-804c-831c0b07e8be.png)

Then I opened the Update Center and see the following:

![screen shot 2015-03-11 at 15 07 22](https://cloud.githubusercontent.com/assets/223439/6604729/ed586e06-c800-11e4-96fb-076b1cc5c0e6.png)

I'm totally puzzled by this. According to the documentation, I cannot upgrade to a major release using the updater, yet the updater and the notification show me the major release.
Why wouldn't it show me what it can update? (e.g. in version 7 all 7.0.x and 7.x updates)

Can someone please clarify this for me? Unless I misunderstood something fundamentally there's a bug or inconsistency somewhere.

**Comment by DeepDiver1975** [comment] 2015-03-11 22:04
> According to the documentation, I cannot upgrade to a major release using the updater,

Hmmm ... I guess this is an inconsistency in the docs - major upgrades have always been possible

**Comment by tessus** [comment] 2015-03-11 22:10
Ok, so I can click on *Update* and my 7.0.4 will be upgraded to 8.0.2?

If yes, somebody should change the 2nd paragraph in the Manual - [Upgrading Yout ownCloud Server](https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html), which states the following:

*Upgrading your ownCloud server means upgrading to the next major ownCloud release. Major releases are indicated by the first and second digits. So 6.0, 7.0 and 8.0 are major releases. You may use the Updater app for staying current with new point releases (Server only), but not for upgrading to a major release.*

**Comment by DeepDiver1975** [comment] 2015-03-11 22:20
> Ok, so I can click on Update and my 7.0.4 will be upgraded to 8.0.2?

yes - :fingers_crossed:



> If yes, somebody should change the 2nd paragraph in the Manual - Upgrading Yout ownCloud Server, which states the following:

@carlaschroder can I ask you to have a look? THX

**Comment by carlaschroder** [comment] 2015-03-11 22:26
Ok, so here is the story of my life at ownCloud: I test as many of the steps for whatever I'm documenting as I can. Whatever I can't test myself I rely on you awesome devs to tell me how things work. It has been reinforced many times that updating and upgrading are two different things, and that the Updater app is not for upgrading to the next major release. If this is not so, then that is a major change so by gosh I want the authoritative story.

**Comment by carlaschroder** [comment] 2015-03-11 22:27
As everything at oC is a moving target, you may imagine the air quotes around "authoritative story" :)

**Comment by MorrisJobke** [comment] 2015-03-12 08:47
I thought the updater app isn't ready for major updates/upgrades. cc @VicDeo @karlitschek

**Comment by karlitschek** [comment] 2015-03-12 11:39
Hmm. The updater app did always offer major upgrades. We didn´t enable to for 8.0.0 because of the bugs in 8.0.0
But beside that this should work for major and minor upgrades.

**Comment by floeff** [comment] 2015-03-12 14:26
One drawback here is that on my Ubuntu 12.04 setup, the upgraded offered me to go from 7.0.4 to 8.0.2, downloaded it, just to tell me then my PHP is too old. :-)

**Comment by RealRancor** [comment] 2015-03-12 15:24
@floeff 
Have a look at announcements like:

https://owncloud.org/blog/what-is-coming-in-owncloud-server-8-0-for-system-administrators/
https://doc.owncloud.org/server/8.0/admin_manual/whats_new_admin.html
https://doc.owncloud.org/server/8.0/admin_manual/release_notes.html

before doing major upgrades to avoid such situations.

**Comment by carlaschroder** [comment] 2015-03-12 16:22
I'm not writing a word until someone buys me some really good beer.

**Comment by floeff** [comment] 2015-03-12 16:24
Easy deal, I'm right here in beautiful Allgäu, with lots of breweries around. :-)

**Comment by tessus** [comment] 2015-03-12 16:45
Good thing I asked. It seems I'm not the only one who's puzzled about it.

@RealRancor I agree that a major upgrade should be done manually anyway and has to be planned; thus reading the docs make sense. BUT, this is not the stone age. A simple check to make sure the pre-reqs are met, before giving someone a button to click on, is not too much to ask. Unless you don't care about UI design, but in that case we don't need a web interface either.

@DeepDiver1975 I'm still a bit afraid of upgrading. I've been following several bugs concerning 7 -> 8 upgrade (e.g.: #14398, #14084)

@carlaschroder Beer is always a good idea. Unfortunately I'm not in the area.

@karlitschek Got it, so unless deactivated (for what reason ever), I can always use the updater to update/upgrade my installation. To answer my original question: documentation is wrong.

Thanks to all of you for clarifying it.

**Comment by RealRancor** [comment] 2015-03-12 16:56
@tessus 
> BUT, this is not the stone age. A simple check to make sure the pre-reqs are met, before giving someone a button to click on, is not too much to ask. Unless you don't care about UI design, but in that case we don't need a web interface either.

Just request this at:

https://github.com/owncloud/updater/issues

**Comment by tessus** [comment] 2015-03-12 17:00
@RealRancor it's fine. I just think you dismissed @floeff's concern/experience too quickly.

**Comment by RealRancor** [comment] 2015-03-12 17:01
Don't dismiss anything. Its just that this check is there in the core installer/updater but not in the updater app which is an separate issue here.

**Comment by phxyz12** [comment] 2015-03-16 21:03
Hi all
just a litte additional question: I am using  7.0.4 and would llike to update to 7.0.5, not 8.0.x. How to do this with the updater app? Assumed, that the updater app is indeed intended to offer also upgrades to major releases - should't there be a choice of versions then?

**Comment by VicDeo** [comment] 2015-03-16 21:07
it has nothing to do with core in the first place https://github.com/owncloud/appstore-issues/issues/4 is already here

**Comment by RealRancor** [comment] 2015-03-16 21:08
https://github.com/owncloud/updater/issues/95 for an option to skip major versions in the updater app.

**Comment by carlaschroder** [comment] 2015-03-16 23:04
Um...there is a core installer/updater, and a separate Updater app? Really? I am still utterly baffled how to document this.

**Comment by VicDeo** [comment] 2015-03-16 23:15
@carlaschroder core performs database migrations when database version changed
Updater app takes a new core and places it instead of an old core. :fast_forward:

**Comment by carlaschroder** [comment] 2015-03-16 23:54
How is the owncloud admin supposed to know if they're running the core updater, or the Updater app?

**Comment by carlaschroder** [comment] 2015-03-17 00:00
I am fabulously happy to correct the documentation if some kind soul can explain what the oC admin sees when it's the core updater, and when they're seeing the Updater app in action, and how are they supposed to choose which one, and how.

**Comment by VicDeo** [comment] 2015-03-25 19:31
Related to https://github.com/owncloud/updater/pull/100

**Comment by VicDeo** [comment] 2015-03-25 19:43
And duplicate of https://github.com/owncloud/updater/issues/95

@carlaschroder 
It works in the following order:
Updater app (master branch) ![](https://cloud.githubusercontent.com/assets/991300/6783442/cdff8d58-d18a-11e4-89a4-a7dc3256383a.png)
 - replaces old OC files with new files

Core starts DB upgrade:
![](https://cloud.githubusercontent.com/assets/476060/6782938/5e32a7e8-d177-11e4-85c7-8a54c98f1958.png)

**Comment by carlaschroder** [comment] 2015-04-24 18:55
forgot to update this thread; docs have been updated so I am closing this
https://github.com/owncloud/documentation/pull/959

**Closed by carlaschroder** 2015-04-24 18:55 UTC
Labels: enhancement
