### ISSUE TITLE
[Experimental files locking] If redis-server is down, owncloud can't be used.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#16898] opened 2015-06-12 09:04 UTC
### Steps to reproduce

Having a server with experimental files locking enabled and redis too, working correctly do:
 
1. Stop redis-server.
2. Try to access owncloud server. 

### Expected behaviour
You can use owncloud, but experimental files locking is disabled. 
A warning should appear telling the user that redis is down, at least for the admin users.

### Actual behaviour
Owncloud cannot be accessed.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Experimental files locking.
External storage.

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP.

**Are you using encryption:** 
No.

**Logs**
```

```

### Client configuration

**browser**
Chrome 43

**Comment by LukasReschke** [comment] 2015-06-12 09:07
Duplicate of https://github.com/owncloud/core/issues/16809

**Closed by LukasReschke** 2015-06-12 09:07 UTC
Labels: bug, feature:locking, sev2-high

**Comment by SergioBertolinSG** [comment] 2015-07-02 11:11
Working as expected. Fails hard when stopping redis and it is written in the logs.

Perhaps a more clear log would be interested to be added in 8.2:

```
{"reqId":"OFQFaZ8hareHElTzfHY9","remoteAddr":IP_HIDDEN,"app":"index","message":"Exception: {\"Exception\":\"RedisException\",\"Message\":\"read error on connection\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php(61): Redis->select(0)\\n#1 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/factory.php(102): OC\\\\Memcache\\\\Redis->__construct('a3ebae308af44ad...')\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(431): OC\\\\Memcache\\\\Factory->createLocking('lock')\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(96): Pimple\\\\Container->offsetGet('LockingProvider')\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(940): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('LockingProvider')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(98): OC\\\\Server->getLockingProvider()\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(317): OC\\\\Files\\\\View->__construct()\\n#8 \\\/opt\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(96): Pimple\\\\Container->offsetGet('HttpClientServi...')\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(810): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('HttpClientServi...')\\n#11 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(309): OC\\\\Server->getHTTPClientService()\\n#12 \\\/opt\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(112): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#13 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(96): Pimple\\\\Container->offsetGet('HTTPHelper')\\n#14 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/server.php(783): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('HTTPHelper')\\n#15 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/app.php(656): OC\\\\Server->getHTTPHelper()\\n#16 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/app.php(632): OC_App::getAppInfo('\\\/opt\\\/owncloud\\\/a...', true)\\n#17 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/app.php(615): OC_App::getAppVersionByPath('\\\/opt\\\/owncloud\\\/a...')\\n#18 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/app.php(968): OC_App::getAppVersion('files_locking')\\n#19 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(1445): OC_App::shouldUpgrade('files_locking')\\n#20 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/util.php(559): OC_Util::needUpgrade(Object(OC\\\\AllConfig))\\n#21 \\\/opt\\\/owncloud\\\/lib\\\/base.php(607): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#22 \\\/opt\\\/owncloud\\\/lib\\\/base.php(1115): OC::init()\\n#23 \\\/opt\\\/owncloud\\\/index.php(38): require_once('\\\/opt\\\/owncloud\\\/l...')\\n#24 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/redis.php\",\"Line\":61}","level":4,"time":"2015-07-02T11:06:39+00:00"}
```
