### ISSUE TITLE
sharing notification by email not working for never logged on users

### ISSUE THREAD

**Issue by CaptionF** [owncloud/core#17362] opened 2015-07-02 19:38 UTC
### Steps to reproduce
1. have ldap connection setup
2. share file with user (from LDAP) that has never logged on yet
3. select notifiy by email (email address also from LDAP) 

### Expected behaviour
ownCloud send email to the email address, also when this person has not yet logged into ownCloud.
This is important to introduce the new service all employees quickly!

### Actual behaviour
ownCloud warns the share creator, that no email can be sent!

![sharing-notification-for-non-active-accounts](https://cloud.githubusercontent.com/assets/10551219/8486033/2d230186-2102-11e5-8fab-eef427f2d560.png)

### Server configuration
**Operating system**:
sles 12
**Web server:**
apache 2.4
**Database:**
Oracle Rac
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
8.0.3
**Updated from an older ownCloud or fresh install:**
7.0.5
**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
MS AD

### Client configuration
Firefox **Browser:**

**Operating system:**
Win 7

There is no ownCloud log entry for the warning in in the image picture above!

**Comment by DeepDiver1975** [comment] 2015-07-03 12:59
@blizzz

**Comment by bboule** [comment] 2015-07-09 21:16
@blizzz would it be possible to have a look and let us know what you think?

**Comment by blizzz** [comment] 2015-07-10 10:32
I have a look

**Comment by blizzz** [comment] 2015-07-10 11:02
Ok, I confirmed, but when attempting to send the notification again (by unchecking and rechecking that box again) it works also without logging in. Some bad timing? Investigating.

**Comment by blizzz** [comment] 2015-07-10 11:31
The update of user info is triggered by userExists check. However, when we fetch users from LDAP, they are being cached as existing, so it won't be done until the cache invalidates (and my cache TTL is short for dev purposes). The propper solution is to read all necessary values when fetching the users and storing them at that time.

There is an PR in preparation (and was a bit forgotten :cry:) that would lay the foundations to it: https://github.com/owncloud/core/pull/12943 

It needs to be extended to read the attributes also on searches and set them there as well.

**Comment by MTRichards** [comment] 2015-07-21 16:54
@blizzz How big a change is this, and how likely to break things?

**Comment by blizzz** [comment] 2015-07-21 21:02
@MTRichards what's already there touches 4 source files and a test one. Ca. 160 new lines, and 60 removed. So the changeset is not that big yet, but many files are included, so it's a bit more complex.  This will increase with the missing bits however. Additionally, it needs to be rebased first and conflicts resolved, as the code evolved.

I would not feel to comfortable to backport it. Down to OC 8.1 at most, with enough development and testing time (i.e. not 8.1.1).

**Comment by MTRichards** [comment] 2015-07-22 16:40
@cmonteroluque If we can't get it back to 8.0, we need to discuss given the priority of this from @CaptionF

**Comment by CaptionF** [comment] 2015-07-23 12:44
@MTRichards @cmonteroluque Checked with prospect: Early September (so 8.1.2 ?) would be just in time! Later would be really bad.

**Comment by MTRichards** [comment] 2015-07-23 13:31
Ok, but 8.1 is ok then. Great. @cmonteroluque for folding into 8.1.2.

**Comment by bboule** [comment] 2015-07-23 18:10
Hey guys just for tracking can we assign this the needed milestone?

**Comment by MTRichards** [comment] 2015-07-23 18:36
mentioned it, but didn't apply milestone. Doh!

**Comment by cmonteroluque** [comment] 2015-07-23 18:38
@MTRichards thanks for adding the milestone. I only just saw the last few exchanges

**Comment by MorrisJobke** [comment] 2015-08-18 12:28
@blizzz The PR is still WIP and 8.1.2 is not that far away. Can I somehow help you?

**Comment by blizzz** [comment] 2015-08-19 11:36
i squeeze it in today

**Comment by blizzz** [comment] 2015-08-20 23:06
Since the ldap code diverged too much I opened a new PR – propper rebasing was not possible. It goes here: https://github.com/owncloud/core/pull/18469

**Comment by blizzz** [comment] 2015-08-25 13:34
Testing/Review needed. If it is good and we get it #18469 into master, I can do the  backport.

**Comment by MorrisJobke** [comment] 2015-08-26 12:37
@blackm How like is it that this will make it into 8.1.2? See https://github.com/owncloud/core/issues/17362#issuecomment-124083659 :confused:

**Comment by MorrisJobke** [comment] 2015-08-26 12:45
@blackm Sorry. Wrong autocomplete :disappointed: I meant @blizzz :)

**Comment by blizzz** [comment] 2015-08-26 12:52
@MorrisJobke depends on reviews, in one week there was just one brief one, from  tkaufm. no i need to rebase anyway.

**Comment by CaptionF** [comment] 2015-09-22 10:10
@MorrisJobke please ensure to have this in 8.1.4

**Comment by davitol** [comment] 2015-09-24 16:02
@blizzz PR https://github.com/owncloud/core/pull/18469 does not fix this issue for me :disappointed: 
I've set an ldap mail in Admin > Advanced > Special Attributes but following the steps to reproduce I got the same error.
Feel free to ping or contact me about my test

**Comment by blizzz** [comment] 2015-09-24 19:11
@davitol tried it as well, works for me. Did you do it against master or 8.1? The PR is against master. Is there a possibility that cache played into it (did you look up the user before applying the patch)?

**Comment by davitol** [comment] 2015-09-25 08:12
@blizzz :-1:  I tried against master ownCloud Enterprise Edition 8.2 beta1 (daily) Build:2015-09-25T03:08:40+00:00 e7bc2a10e3ffd16cda8d15ff06dcbc870e34a627
No possibility that cache played into it. Maybe I forgot some conf step, but test email settings worked.

So let's wait for another reviewers in order to clarify if it works

**Comment by blizzz** [comment] 2015-09-25 08:28
@davitol is sending mail configured properly (does a test mail arrive)? If this as well, could we do a screenshare to figure it out?

**Comment by davitol** [comment] 2015-09-25 08:44
@blizzz yes, test mail arrived. Let's IRC and date an screenshare. Thanks a lot for your help

**Comment by davitol** [comment] 2015-09-25 11:44
:+1: It works. Thank you so much @blizzz for the screenshare and for the help.

**Comment by CaptionF** [comment] 2015-09-25 11:46
great!

**Comment by cmonteroluque** [comment] 2015-09-25 21:39
please advise if this should still be open.

**Closed by cmonteroluque** 2015-09-25 21:39 UTC
Labels: app:user_ldap, approved by qa, blue-ticket, bug, green-ticket, triage

**Comment by MorrisJobke** [comment] 2015-10-22 09:59
Backport to 8.1.x is in https://github.com/owncloud/core/pull/19427

**Comment by MorrisJobke** [comment] 2015-10-27 13:10
> @MorrisJobke please ensure to have this in 8.1.4

@CaptionF It is in 8.1.4

**Comment by dtwilliamson** [comment] 2015-12-18 21:16
Running 8.2.1, I'm having a similar problem. When sharing with an LDAP user who has not logged in yet (not using an email link - just a regular share) when the user logs in and tries to access the file they get an error "Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you." I didn't enter a separate issue since this is so similar.

**Comment by blizzz** [comment] 2015-12-18 21:59
@dtwilliamson this is unrelated, please open a new bug report and use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). Thank you!
