### ISSUE TITLE
Share links do not scroll for IE11 with long file list

### ISSUE THREAD

**Issue by gig13** [owncloud/core#22797] opened 2016-03-02 21:00 UTC
### Steps to reproduce
1. Create a folder with 100 files
2. Create a Share link for this folder
3. Open the Share link in IE11

### Expected behaviour
When opening the Share link, the user should be able to scroll down and see all of the files in the shared folder.

### Actual behaviour
The scrollbar is limited to close to the actual page size and the last thumbnail image shown is cut off. This only allows the users to see a fraction of the entire folder.

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 8.2.2

**Updated from an older ownCloud or fresh install:** Fresh Install

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LNO

### Client configuration
**Browser:** IE11

**Operating system:** Windows 7

Looks similar to https://github.com/owncloud/core/issues/21842

@MorrisJobke

**Comment by MorrisJobke** [comment] 2016-03-02 21:23
> Looks similar to #21842

Let me cite the comment there:

> @tsbatista Very likely a duplicate of #21373, #21203, #21675 and #21809 which gets fixed with the upcoming 8.2.3

It's a bug in PDF viewer: https://github.com/owncloud/files_pdfviewer/pull/91 

Please try to disable the PDF viewer app and check if it is then working. If this is not the case then reopen this ticket.

**Comment by MorrisJobke** [comment] 2016-03-02 21:23
Fix will be in 9.0.0 and 8.2.3

**Closed by MorrisJobke** 2016-03-02 21:23 UTC
Labels: blue-ticket

**Comment by RealRancor** [comment] 2016-03-02 21:25
If disabling the files_pdfviewer is not solving this then its a duplicate of #22289, #20044, #22303 and a lot of more where #20044 contains an upcoming fix.

**Comment by MorrisJobke** [comment] 2016-03-02 21:26
> If disabling the files_pdfviewer is not solving this then its a duplicate of #22289, #20044, #22303 and a lot of more where #20044 contains an upcoming fix.

Thanks https://github.com/owncloud/core/issues/20044 is the ticket I searched for too, but didn't found. 

:+1:

**Comment by gig13** [comment] 2016-03-07 15:52
Disabling the files_pdfviewer does not solve this.

**Comment by MorrisJobke** [comment] 2016-03-07 15:55
> Disabling the files_pdfviewer does not solve this.

Then 8.2.3 will solve it - https://github.com/owncloud/core/pull/22548

@gig13 You could try to patch this file. It shouldn't cause any issues, because it is only one removed line in a CSS file. Could you test with this change applied? Thanks :)
