### ISSUE TITLE
Group-enable setting not preserved on app settings page

### ISSUE THREAD

**Issue by mirekys** [owncloud/core#26638] opened 2016-11-15 15:55 UTC
### Steps to reproduce
1. Restrict some app (e.g Gallery) to be available only for certain groups (e.g. "gallery-users")
2. Reload the App settings page (you can see app's allowed groups in group_select field)
3. Reload the App settings page again (group restrictions are now gone/not visible)
4. Check the Groups-enable checkbox (it will clear all previous group restrictions even from database)

### Expected behaviour
App's group restriction  visible on App Settings page should always
correspond to what is being saved in DB appconfig table.

### Actual behaviour
App's group restriction disappeared from the App Settings page after the second reload.
However, it was still stored correctly in database:
```
owncloud=# SELECT * FROM oc_appconfig WHERE appid='gallery' AND configkey ='enabled';
  appid  |     configkey     |    configvalue    
---------+-------------------+-------------------
 gallery | enabled           | ["gallery-users"]
(3 rows)
```

I've found the problem is being caused by this code:
https://github.com/owncloud/core/blob/v9.0.6/settings/controller/appsettingscontroller.php#L282-L286
```
			// fix groups
			$groups = array();
			if (is_string($app['groups'])) {
				$groups = json_decode($app['groups']);
			}
			$app['groups'] = $groups;
```

- On the first page reoad, the **$app['groups']** is being decoded from string to Array, and then saved to **$this->cache**.

- On the second page reload, the **$app['groups']** is being pulled from cache as Array of groups. The code above then incorrectly assigns an empty array to **$app['groups']** and caches it.

I would suggest a following fix:
```
			// fix groups
			$groups = array();
			if (is_string($app['groups'])) {
				$groups = json_decode($app['groups']);
+			} elseif (is_array($app['groups'])) {
+                              $groups = $app['groups'];
+                       }
			$app['groups'] = $groups;
```

### Server configuration
**Database:**
PostgreSQL 9.2
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0.6
**Updated from an older ownCloud or fresh install:**
Updated from 8.2.9
**Where did you install ownCloud from:**
official tar package

**Comment by PVince81** [comment] 2016-11-30 08:49
@mirekys mind sending your fix as a PR ? Thanks

**Comment by PVince81** [comment] 2016-12-01 11:39
I couldn't reproduce the issue but you mentioned a cache, so it's probably memcache ?
Trying that now

**Comment by PVince81** [comment] 2016-12-01 11:40
Indeed, reproduceable with redis as local  memcache.

**Comment by PVince81** [comment] 2016-12-01 11:47
Fixed in https://github.com/owncloud/core/pull/26748

**Closed by PVince81** 2016-12-01 11:47 UTC
Labels: bug, regression, sev2-high
