### ISSUE TITLE
non existing folder in "skeletondirectory" setting results in endless loop

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#27854] opened 2017-05-11 05:20 UTC
### Steps to reproduce
1. in config.php set the skeletondirectory setting to a folder that does not exist
2. create a new user
3. login as new user

### Expected behaviour
Error reported that the skeleton folder does not exist

### Actual behaviour
webserver goes in a loop
no action on the webUI

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache 2.2
**Database:**
sqlite
**PHP version:**
PHP 7.0.7-5
**ownCloud version:** (see ownCloud admin page)
10.0.0.12
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc150y5qiolb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.0.0.12",
        "logtimezone": "UTC",
        "skeletondirectory": "\/tmp\/not-existing",
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - testing
  - theme-example
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Debian

#### ownCloud log (data/owncloud.log)
```
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"opendir(\/tmp\/not-existing): failed to open dir: No such file or directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#409"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"readdir() expects parameter 1 to be resource, boolean given at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#410"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"Uninitialized string offset: 0 at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Node\/Node.php#290"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/tmp\/not-existing\/): failed to open stream: No such file or directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#417"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/home\/artur\/www\/owncloud-core\/data\/user1\/files): failed to open stream: Is a directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Storage\/Local.php#276"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"stream_copy_to_stream() expects parameter 1 to be resource, boolean given at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#417"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"readdir() expects parameter 1 to be resource, boolean given at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#410"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"Uninitialized string offset: 0 at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Node\/Node.php#290"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/tmp\/not-existing\/): failed to open stream: No such file or directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#417"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/home\/artur\/www\/owncloud-core\/data\/user1\/files): failed to open stream: Is a directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Storage\/Local.php#276"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"stream_copy_to_stream() expects parameter 1 to be resource, boolean given at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#417"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"readdir() expects parameter 1 to be resource, boolean given at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#410"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"Uninitialized string offset: 0 at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Node\/Node.php#290"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/tmp\/not-existing\/): failed to open stream: No such file or directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/legacy\/util.php#417"}
{"reqId":"kJh8Slv52kMu8BLTr4uz","level":3,"time":"2017-05-11T05:18:50+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"POST","url":"\/owncloud-core\/index.php\/login","message":"fopen(\/home\/artur\/www\/owncloud-core\/data\/user1\/files): failed to open stream: Is a directory at \/home\/artur\/www\/owncloud-core\/lib\/private\/Files\/Storage\/Local.php#276"}
..........
```

**Comment by phil-davis** [comment] 2017-05-12 08:33
Or if the input folder specified for the skeletondirectory does not exist, then the system could just "assume" that there are no files required as initial defaults for the user, and quietly give the user an empty start.
Take your pick of "expected behavior".

**Comment by IljaN** [comment] 2017-10-11 10:44
@Gandolf90 Please look in to this

**Comment by phil-davis** [comment] 2017-10-29 01:42
Related PRs:
master #29367 
stable10 #29379

**Comment by sharidas** [comment] 2018-01-04 13:09
Guess we have PR's available, so can we close this issue?

**Comment by phil-davis** [comment] 2018-01-05 01:57
If the skeleton dir does not exist, the new user gets empty files and the problem is logged:
```
{"reqId":"uDb1BoDP6VSozAWRBYVr","level":3,"time":"2018-01-05T01:54:46+00:00","remoteAddr":"127.0.0.1","user":"t123","app":"no app in context","method":"POST","url":"\/index.php\/login","message":"The skeleton folder \/home\/phil\/core\/tests\/integration\/skeleton-not-exists is not accessible"}
```

Works

**Closed by phil-davis** 2018-01-05 01:57 UTC
Labels: bug, junior job, sev3-medium

**Comment by phil-davis** [comment] 2018-01-05 06:28
Note: if the skeleton folder exists, but the web server does not have read access to it, PHP also goes into a recursive loop. See issue #30017
