### ISSUE TITLE
oc 8.2.4 Federated Cloud Sharing disable checkox

### ISSUE THREAD

**Issue by focparty** [owncloud/core#24589] opened 2016-05-12 08:19 UTC
Being in admin mode section Federated Cloud Sharing:
The checkox "Allow users on this server to send shares to other servers" can't be disabled.
When you deselect either field, on return to admin mode both checkoxes are always enabled.

Actual behaviour:
On shares you get a input field for adding shares.

Server configuration
Web server: OVH Hosting
Database: MySQL
PHP version: 5.6
ownCloud version: 8.2.4
Updated from an older ownCloud: upgrade from 8.2.3, there you could disable either checkboxes
ownCloud log: no log entry
apps aktiv: Share Files 0.7.0

**Comment by PVince81** [comment] 2016-05-12 08:40
Duplicate of https://github.com/owncloud/core/issues/24547

**Closed by PVince81** 2016-05-12 08:40 UTC
