### ISSUE TITLE
Failure during upgrade to 9.0

### ISSUE THREAD

**Issue by rotfussl** [owncloud/core#23238] opened 2016-03-14 16:59 UTC
### Steps to reproduce

The upgrade process via Ubuntu-Package to 9.0 failed with the following message in the web interface:

Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_notifications' already exists

**Comment by RealRancor** [comment] 2016-03-14 17:29
Duplicate of https://github.com/owncloud/core/issues/23194

**Closed** 2016-03-15 14:26 UTC

**Comment by pipiche38** [comment] 2016-03-19 19:49
+1
