### ISSUE TITLE
Disable synchronisation for certain directories

### ISSUE THREAD

**Issue by RobinMcCorkell** [owncloud/core#7909] opened 2014-03-27 10:02 UTC
Would it be possible to disable synchronisation on certain directories within the user's filesystem, but still allow them to be accessed through the web interface? Failing a general solution, is it possible to disable synchronisation for certain mounted shares?

For example, a user may want to mount several different shares for access through the web interface, but only wants their home share to be synchronised with any clients. This is useful in cases where a large multi-user share is available, and the user wants to be able to manage files in it, but doesn't want to pull down GBs of data, most of which may be useless to them.

**Comment by MorrisJobke** [comment] 2015-10-12 15:34
I think this is properly implemented on client side now. New directories are only synced if they are below a threshold -> closing

**Comment by mmattel** [comment] 2015-10-12 16:23
@MorrisJobke I completely disagree in closing this and stating that this has been solved by a treshold on the client side. It is a major difference if I disallow syncronisation from the clientside or from the server side. As an admin, I for sure have the need to disallow certain directories or mount points from syncing. And this is not a client decision ! NEVER

**Comment by MorrisJobke** [comment] 2015-10-12 20:52
And how to we then differentiate between "this is a sync operation" and this is a "download just because I want to browse this file" operation? This can't be enforced on server side ...otherwise we would need to disallow file download, which is quite useless for file sync and share solution.

cc @MTRichards @dragotin @DeepDiver1975 ^

**Comment by mmattel** [comment] 2015-10-13 06:56
The diffrence is IMHO that a disallow sync from the server side means preventing an automatism for getting everything from that folder or mount beeing in sync with a client while beeing at the same time able to browse and manualy up/download files. If I eg have a huge picture store, I for sure want to be able to access it normally by the client but as an admin I do not want to get hundreds of GB or TB to be synced preventing problems. 

From my POV, two things have to be seen from the admin side:
- marker to disable to be viewed by webdav
- marker to disable to be synced but beeing viewed by webdav

**Comment by MorrisJobke** [comment] 2015-10-13 07:14
> From my POV, two things have to be seen from the admin side:

But we will switch to WebDAV in the web frontend too. So there is no difference if the client browses the files or the web UI :(

**Comment by PVince81** [comment] 2015-10-13 08:05
A flag or tag could be set on the folders in the web UI, then the sync client could recognize the tag and skip these directories.

**Comment by PVince81** [comment] 2015-10-13 08:06
(Webdav properties)

**Comment by MorrisJobke** [comment] 2015-10-13 08:09
> A flag or tag could be set on the folders in the web UI, then the sync client could recognize the tag and skip these directories.

But this is also just an opt-in ... clients can simply ignore that. For me this is not an "enforcement" of this feature...it's just a dump client that can still do that. I think this doesn't really solve an issue, that isn't solved already. The sync client already is that smart to not download huge directories. Adding another setting doesn't help here from my PoV

**Comment by mmattel** [comment] 2015-10-13 08:22
@PVince81 this would be a good startinpoint for a solution

@MorrisJobke yes I agree that someone can just not use our client and because of webdav we can not strictly enforce a disablement of syncronistaion. But to be honest, this is not a government high security environment and we can at least support admins at this step when using our client sw. Onyl a view people will write their own sync client just to get a full sync done. For the others disable sync tagging would be a enormous help...

**Comment by MorrisJobke** [comment] 2015-10-13 08:52
> For the others disable sync tagging would be a enormous help...

But it is already done in the client automatically without any need for a setting. I simply don't get why we want another setting for something that is already solved in a more elegant way.

cc @dragotin @jancborchardt

**Comment by jancborchardt** [comment] 2015-10-13 09:10
Sorry, I don’t see the use-case for this. It seems to be an anti-feature.

**Comment by mmattel** [comment] 2015-10-13 09:11
This is not a matter of elegance but of hierarchy. First admin, then client.
I also would like to add @karlitschek to see his pov.

**Comment by Xenopathic** [comment] 2015-10-13 09:24
I was discussing with the guys here at Cambridge who run the [Student Run Computing Facility](http://www.srcf.net/), and who also use ownCloud. They expressed a desire for the ability to archive  files into ownCloud, having them stored safely on the server but with synchronisation disabled by default. This feature would implement that, with certain directories (specified by the user in the web UI) being default no-sync, which the client would pick up on and (by default) not synchronise those directories, in a similar way to how it will require manual activation for new large folders, but more explicit. Of course, the client *can* be set to synchronise such folders, but by default it won't.

**Comment by dragotin** [comment] 2015-10-13 09:32
Ever considered to NOT sync the entire cloud (and remove syncs later) but only some directories of the cloud? That could solve this since day one.
@MTRichards

**Comment by karlitschek** [comment] 2015-10-13 14:21
i can see a use case for that but in most cases this can be solved with selective sync on the client. not high on the list imho. everyone is welcome to send PRs for server and client of course.
what do you think? @mtrichards

**Comment by MTRichards** [comment] 2015-10-13 20:18
The biggest use case for this is on external storage, where people don't want to allow recipients of a share folder to sync a folder at all, for example. Or a windows network drive can't be synced, but it can be viewed in the mobile. These cases, though, are not consistent. It is a nice to have to me at this time.

**Comment by marvelloard** [comment] 2015-10-30 23:11
This is exactly what I'm looking for. I'd like (as admin user) be able to add a local/samba/... share to a bunch of users and exclude it from client sync (but still show it in the webinterface of course).

**Comment by mgbowman** [comment] 2016-02-12 11:58
Toss another vote for this feature!

I just attached a samba share as external storage to my OC instance and realized that all the clients will try and synchronize it. The problem is the share contains well over 500GB of photos and no client workstation or laptop has that amount of space available. Not to mention, if someone were to setup the OC client on their own machine (at home for example), it would start sync'ing as well. It would be nice if I could control this on the server side and just make the external storage available via the web UI and mobile apps.

**Comment by marvelloard** [comment] 2016-02-16 09:48
Same here, photos, videos, audio material, software. This shouldn't be synchronised but accessible via the web interface. Urgently needed!

**Comment by MorrisJobke** [comment] 2016-02-16 12:29
> Same here, photos, videos, audio material, software. This shouldn't be synchronised but accessible via the web interface. Urgently needed!

The current client doesn't sync folder bigger than 500MB by default. You need to actively enable the sync for those folders.

**Comment by marvelloard** [comment] 2016-02-16 12:39
Yeah, that was my first thought too. But in those shares added are folders smaller than 500MB, and those will be synced automatically.
Also, in our usage cases you would like to be able to exclude certain kind of folders regardless the size.

**Comment by PVince81** [comment] 2016-10-10 14:10
Add webdav property to tell sync client to not sync an entry: #26311

**Comment by mkormendy** [comment] 2019-02-06 06:51
PING! This is still a much needed feature.

**Comment by jfarjona** [comment] 2021-04-02 04:22
My vote for this feature as well.  In my case I want to avoid users to sync a few folders that have sensitive information.  I don't want this to be stored by default in their computers (it is an unnecessary exposure).  I have no problem that they download the file(s) they need by hand from the web interface, in which case they are aware that these files are on their computers.  Would be great to have this feature.

**Comment by micbar** [comment] 2021-09-16 09:25
We have the "decline/accept shares"  feature.
We also have some redundancy with the new Virtual Files Feature in the desktop client.
In ownCloud infinite scale we will have also spaces to treat large "data buckets" as optional sync targets.

**Closed by micbar** 2021-09-16 09:25 UTC
Labels: enhancement, app:files, discussion, enhancement-PM

**Comment by mmattel** [comment] 2021-09-20 17:41
@micbar this is not about client, but server settings...
