### ISSUE TITLE
Preview errors in log when accessing .jpg files

### ISSUE THREAD

**Issue by pako81** [owncloud/core#29017] opened 2017-09-15 10:24 UTC
### Steps to reproduce
1. trying to access some .jpg files
2. files can be accessed but log file is reporting the errors below 

### Expected behaviour
Tell us what should happen

Log file should not contain any related errors

### Actual behaviour
Tell us what happens instead

See above

### Server configuration
**Operating system**:

Ubuntu 16.04

**Web server:**

Apache 2.4

**Database:**

MySQL 10.0.31

**PHP version:**

7.0.22

**ownCloud version:** (see ownCloud admin page)

10.0.2

**Updated from an older ownCloud or fresh install:**

fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

#### ownCloud log (data/owncloud.log)
```
{ [-] 
app: PHP 
level: 3 
message: imagecreatefromstring(): Empty string or invalid image at /var/www/html/owncloud/lib/private/legacy/image.php#572 
method: GET 
remoteAddr: xxxxxxxx 
reqId: WbuSsjcc4xxMRM81mkgGXQAAAAE 
time: 2017-09-15T10:43:30+02:00 
url: /index.php/core/preview.png?file=%2F20170824_160509.jpg&c=616442cbd2aa130adb9a9131137aac54&x=40&y=40&forceIcon=0 
user: xxxx 
}

{ [-] 
app: PHP 
level: 3 
message: file_get_contents(/data/xxxx/files/var/www/html/owncloud/core/img/filetypes/image.svg): failed to open stream: No such file or directory at /var/www/html/owncloud/lib/private/Files/Storage/Local.php#208 
method: GET 
remoteAddr: xxxxxxxx
reqId: WbuSskdcCA5U1wDGWSA9yQAAAAQ 
time: 2017-09-15T10:43:30+02:00 
url: /index.php/core/preview.png?file=%2F20170824_160506.jpg&c=67279154c405f9c5ff3704da910e8e44&x=40&y=40&forceIcon=0 
user: xxxx
}
```

This seems to be the part of the code causing the log entries. It is related to generating previews: 

https://github.com/owncloud/core/blob/03dd2c7f89299c7a6ca0f54187ce94299753db7f/lib/private/Preview.php#L1175-L1185 

@DeepDiver1975

**Comment by kdslkdsaldsal** [comment] 2017-09-16 13:48
Closing as a duplicate of https://github.com/owncloud/core/issues/29017 where the logentries are completely matching the posted ones in here.

**Closed by kdslkdsaldsal** 2017-09-16 13:48 UTC
