### ISSUE TITLE
Upgrade from 8.1.x to 8.2.9 gives null-reference in javascript

### ISSUE THREAD

**Issue by VincentSC** [owncloud/core#26693] opened 2016-11-22 21:54 UTC
Context: wanted to upgrade from 8.1.x to 9.2.x. This did not work well.

### Steps to reproduce
1. Upgrade to 8.1.11
2. Upgrade to 8.2.9
3. Getting error 500: errors on redefined functions (forgot which). Tip was to turn off all plugins, without access to web.
4. SQL: update oc_appconfig set configvalue='no' where configkey='enabled';
5. SQL turn on appid 'files'.
6. Upgrade to 9.0.0

### Expected behaviour
After upgrade all should work as usual after step 2. Step 3 was unexpected, Step 4 made all worse, as core-plugin files was in that same table. Step 5 was expected to make it work again. As I thought the error could maybe be fixed in 9.0, I tried upgrading to 9.0.0. 

### Actual behaviour
No files can be seen in the webinterface after step 5. 

The javascript-console error with 9.0.0. is:
filelist.js?v=26510bc…:2829 Uncaught TypeError: Cannot read property 'FileInfo' of undefined
    at filelist.js?v=26510bc…:2829
    at filelist.js?v=26510bc…:2832
(anonymous) @ filelist.js?v=26510bc…:2829
(anonymous) @ filelist.js?v=26510bc…:2832

js.js?v=26510bc…:2183 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ js.js?v=26510bc…:2183
(anonymous) @ backgroundjobs.js?v=26510bc…:26
c @ jquery.min.js?v=26510bc…:4
fireWith @ jquery.min.js?v=26510bc…:4
ready @ jquery.min.js?v=26510bc…:4
q @ jquery.min.js?v=26510bc…:4

favoritesfilelist.js?v=26510bc…:28 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at favoritesfilelist.js?v=26510bc…:28
    at HTMLDocument.<anonymous> (favoritesfilelist.js?v=26510bc…:100)
    at c (jquery.min.js?v=26510bc…:4)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=26510bc…:4)
    at Function.ready (jquery.min.js?v=26510bc…:4)
    at HTMLDocument.q (jquery.min.js?v=26510bc…:4)
(anonymous) @ favoritesfilelist.js?v=26510bc…:28
(anonymous) @ favoritesfilelist.js?v=26510bc…:100
c @ jquery.min.js?v=26510bc…:4
fireWith @ jquery.min.js?v=26510bc…:4
ready @ jquery.min.js?v=26510bc…:4
q @ jquery.min.js?v=26510bc…:4

app.js?v=26510bc…:67 Uncaught TypeError: OCA.Files.FileList is not a constructor
    at Object.initialize (app.js?v=26510bc…:67)
    at app.js?v=26510bc…:229
    at underscore.js?v=26510bc…:768

**It seems not all javascrips are included**:
							<script src="/index.php/core/js/oc.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/jquery/jquery.min.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/jquery-migrate/jquery-migrate.min.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/underscore/underscore.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/moment/min/moment-with-locales.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/handlebars/handlebars.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/blueimp-md5/js/md5.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/bootstrap/js/tooltip.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/backbone/backbone.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/es6-promise/dist/es6-promise.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/davclient.js/lib/client.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/placeholders.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/compatibility.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/jquery.ocdialog.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/oc-dialogs.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/js.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/l10n.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/octemplate.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/eventsource.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/config.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/search/js/search.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/oc-requesttoken.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/apps.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/mimetype.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/mimetypelist.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/snapjs/dist/latest/snap.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/backbone/backbone.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/oc-backbone.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/placeholder.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/jquery.avatar.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/backgroundjobs.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/app.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/file-upload.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/jquery.iframe-transport.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/jquery.fileupload.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/jquery-visibility.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/filesummary.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/breadcrumb.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/filelist.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/search.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/favoritesfilelist.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/tagsplugin.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/favoritesplugin.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/vendor/handlebars/handlebars.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/files/fileinfo.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/files/client.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/fileactions.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/files.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/navigation.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/apps/files/js/keyboardshortcuts.js?v=26510bcf886c368706c0ea3823f90be4"></script>
					<script src="/core/js/integritycheck-failed-notification.js?v=26510bcf886c368706c0ea3823f90be4"></script>

In viewcontroller.php it seems that after loading script favouritesplugin a few files are skipped.

                \OCP\Util::addScript('files', 'favoritesfilelist');
                \OCP\Util::addScript('files', 'tagsplugin');
                \OCP\Util::addScript('files', 'favoritesplugin');

// these 5 are not included:

                \OCP\Util::addScript('files', 'detailfileinfoview');
                \OCP\Util::addScript('files', 'detailtabview');
                \OCP\Util::addScript('files', 'mainfileinfodetailview');
                \OCP\Util::addScript('files', 'detailsview');
                \OCP\Util::addStyle('files', 'detailsView');

                \OC_Util::addVendorScript('core', 'handlebars/handlebars');

                \OCP\Util::addscript('files', 'fileactions');
                \OCP\Util::addscript('files', 'fileactionsmenu');
                \OCP\Util::addscript('files', 'files');
                \OCP\Util::addscript('files', 'keyboardshortcuts');
                \OCP\Util::addscript('files', 'navigation');

Javascript files do exist.

$ ls -l ./apps/files/js/
total 324
-rw-r--r-- 1 www-data www-data   699 Mar  8  2016 admin.js
-rw-r--r-- 1 www-data www-data  6114 Mar  8  2016 app.js
-rw-r--r-- 1 www-data www-data  7015 Mar  8  2016 breadcrumb.js
-rw-r--r-- 1 www-data www-data   981 Mar  8  2016 detailfileinfoview.js
-rw-r--r-- 1 www-data www-data  6957 Mar  8  2016 detailsview.js
-rw-r--r-- 1 www-data www-data  2122 Mar  8  2016 detailtabview.js
-rw-r--r-- 1 www-data www-data  2669 Mar  8  2016 favoritesfilelist.js
-rw-r--r-- 1 www-data www-data  3411 Mar  8  2016 favoritesplugin.js
-rw-r--r-- 1 www-data www-data 22858 Mar  8  2016 fileactions.js
-rw-r--r-- 1 www-data www-data  3764 Mar  8  2016 fileactionsmenu.js
-rw-r--r-- 1 www-data www-data  2018 Mar  8  2016 fileinfomodel.js
-rw-r--r-- 1 www-data www-data 83018 Mar  8  2016 filelist.js
-rw-r--r-- 1 www-data www-data 13615 Mar  8  2016 files.js
-rw-r--r-- 1 www-data www-data  6849 Mar  8  2016 filesummary.js
-rw-r--r-- 1 www-data www-data 20283 Mar  8  2016 file-upload.js
-rw-r--r-- 1 www-data www-data 57307 Mar  8  2016 jquery.fileupload.js
-rw-r--r-- 1 www-data www-data 10048 Mar  8  2016 jquery.iframe-transport.js
-rw-r--r-- 1 www-data www-data  2545 Mar  8  2016 jquery-visibility.js
-rw-r--r-- 1 www-data www-data  4757 Mar  8  2016 keyboardshortcuts.js
-rw-r--r-- 1 www-data www-data  6765 Mar  8  2016 mainfileinfodetailview.js
-rw-r--r-- 1 www-data www-data  2984 Mar  8  2016 navigation.js
-rw-r--r-- 1 www-data www-data  6593 Mar  8  2016 newfilemenu.js
-rw-r--r-- 1 www-data www-data  5494 Mar  8  2016 search.js
-rw-r--r-- 1 www-data www-data  6953 Mar  8  2016 tagsplugin.js
-rw-r--r-- 1 www-data www-data   388 Mar  8  2016 upload.js

### Server configuration
**Operating system**:
Ubuntu 15.04
**Web server:**
Nginx

**Database:**
Mysql 14.14

**PHP version:**
5.6.4

**ownCloud version:** (see ownCloud admin page)
9.0.0.19

**Updated from an older ownCloud or fresh install:**
update

**Where did you install ownCloud from:**
See above

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- owncloud.log
		- core/ajax/owncloud.log
- templateeditor
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- encryption
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- gallery
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- user_ldap
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_pdfviewer
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_versions
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- firstrunwizard
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_texteditor
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- user_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_sharing
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- activity
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- files_trashbin
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [owncloud.log] => Array
                        (
                            [expected] => 
                            [current] => 3786ed9a0995b68b79bf9a2979a77d3d2b308b25723b626b07853b23aee5608f1395096dbf63c6e1964bbc7503d8b78eeb7c6fe5fb9b945a812a9cd5038cff81
                        )

                    [core/ajax/owncloud.log] => Array
                        (
                            [expected] => 
                            [current] => f855f03822263210970a39520cfe320c4b2e0dd9007473cf1a2f47bf1f361a3d887ef0f2984aef542cd4148888468996396ee2f2bd35ed93d721d2dce996dc27
                        )

                )

        )

    [templateeditor] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_external] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [encryption] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [gallery] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [user_ldap] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [external] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_pdfviewer] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_versions] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [firstrunwizard] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_texteditor] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [user_external] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_sharing] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [activity] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [provisioning_api] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [files_trashbin] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
**List of activated apps:**

See above: none

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
-> PHP Fatal error:  Call to undefined method OC_User::getManager() in /var/www/sites/owncloud/apps/files/appinfo/register_command.php on line 23

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
-> PHP Fatal error:  Call to undefined method OC_User::getManager() in /var/www/sites/owncloud/apps/files/appinfo/register_command.php on line 23
or 
Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

  'version' => '9.0.0.19',
  'installed' => true,
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbhost' => 'localhost',
  'forcessl' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'theme' => '',
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'knowledgebaseurl' => 'http://api.apps.owncloud.com/v1',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpauthtype' => 'LOGIN',
  'trashbin_retention_obligation' => 180,
  'allow_user_to_change_display_name' => true,
  'appcodechecker' => '',
  'updatechecker' => true,
  'log_type' => 'owncloud',
  'logfile' => 'owncloud.log',
  'loglevel' => 0,
  'remember_login_cookie_lifetime' => 1296000,
  'custom_csp_policy' => 'default-src \'self\'; script-src \'self\' \'unsafe-eval\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:',
  'maintenance' => false,
  'debug' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/sites/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{imap.gmail.com:993/imap/ssl}INBOX',
      ),
    ),
  ),
  'customclient_desktop' => '',
  'customclient_android' => '',
  'customclient_ios' => '',

**Are you using external storage, if yes which one:** local/smb/sftp/...
turned off

**Are you using encryption:** yes/no
no

**Comment by RealRancor** [comment] 2016-11-23 07:08
@VincentSC This is most likely caused by a wrong done upgrade (assuming that because of your shown integrity issues. A correct upgrade path would be:

8.1.x -> 8.1.11 -> 8.2.9 -> 9.0.6 (not 9.0.0 as you did)

Important: In between the steps make sure that you're deleting all files and folders except /data/ and /config/ as you can't just copy over the new files over the old files.

**Comment by VincentSC** [comment] 2016-11-23 07:28
In that case it would have been impossible to upgrade from 8.2.9 to 9.0.0, when it was released. What you describe is the quickest way.

For some reason those 5 file were not included, and I assume it's a database-problem:

            \OCP\Util::addScript('files', 'detailfileinfoview');
            \OCP\Util::addScript('files', 'detailtabview');
            \OCP\Util::addScript('files', 'mainfileinfodetailview');
            \OCP\Util::addScript('files', 'detailsview');
            \OCP\Util::addStyle('files', 'detailsView');

**Comment by RealRancor** [comment] 2016-11-23 07:33
> 8.2.9 to 9.0.0

Some people and environments are hitting bugs not everyone is hitting. Thats why you really need to upgrade to the latest released version of the branch. Please do the following upgrade path as explained above.

**Comment by RealRancor** [comment] 2016-11-23 07:38
Ah, and as you're on Nginx make sure that you're using a current nginx config provided here (exactly this, not any own modifications and includes!!):

https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_examples.html

I guess this is either an upgrading issue due to a wrong done upgrade as explained above or an issue within your environment / nginx config.

**Comment by VincentSC** [comment] 2016-11-23 08:03
I think you're misunderstanding: 
- 5 files are not put in the html-code. 
- the problem already started with 8.2.9.

**Comment by RealRancor** [comment] 2016-11-23 08:12
Yes, and that might be caused by your broken environment. Especially e.g.:

> PHP Fatal error: Call to undefined method OC_User::getManager() in /var/www/sites/owncloud/apps/files/appinfo/register_command.php on line 23

and the integrity errors are showning that your environment has a serve problem. Again, please:

1. remove all files and folders except /data/ and /config/
2. Download 9.0.6
3. Extract the new files into your installation folder
4. Run upgrade routine on command line

**Comment by VincentSC** [comment] 2016-11-23 09:04
Ok, let's focus on the the app:list-error. I think it's related anyway.

This is what I did:
1. tar -xvjf owncloud-9.0.6.tar.bz2
2. copied data and config from 9.0.0-backup
3. sudo chown -Rh www-data:www-data .
4. sudo su -s /bin/sh www-data  -c "./occ upgrade"
5. sudo su -s /bin/sh www-data  -c "./occ app:list"

1-4 were successful, 5 is not.
PHP Fatal error:  Call to undefined method OC_User::getManager() in /var/www/sites/owncloud/apps/files/appinfo/register_command.php on line 23

So something is not enabled. I really think it's a DB-issue, but I could not find lists of default values.

mysql> select * from oc_appconfig where appid='core';
+------------------------+-----------+-------------+
| appid                  | configkey | configvalue |
+------------------------+-----------+-------------+
| core  | OC_Channel                | stable                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | core  | backgroundjobs_step       | queued_tasks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | core  | backgroundjobs_task       | OC_Files_Antivirus_BackgroundScanner-check                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | core  | global_cache_gc_lastrun   | 1432706690                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | core  | installedat               | 1360781720.614                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | core  | lastcron                  | 1479891030                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | core  | lastupdateResult          | []                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | core  | lastupdatedat             | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | core  | oc.integritycheck.checker | [....]
| core  | public_caldav             | calendar/share.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | core  | public_calendar           | calendar/share.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | core  | public_documents          | documents/public.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | core  | public_files              | files_sharing/public.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | core  | public_gallery            | gallery/public.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | core  | public_webdav             | files_sharing/publicwebdav.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | core  | remote_ampache            | media/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | core  | remote_caldav             | calendar/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | core  | remote_calendar           | calendar/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | core  | remote_carddav            | contacts/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | core  | remote_contacts           | contacts/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | core  | remote_contactthumbnail   | contacts/thumbnail.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | core  | remote_core.css           | /core/minimizer.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | core  | remote_core.js            | /core/minimizer.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | core  | remote_files              | files/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | core  | remote_filesync           | files/appinfo/filesync.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | core  | remote_mozilla_sync       | mozilla_sync/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | core  | remote_webdav             | files/appinfo/remote.php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | core  | repairlegacystoragesdone  | yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | core  | shareapi_allow_links      | yes    

mysql> select * from oc_appconfig where configkey='enabled';
+------------------------+-----------+-------------+
| appid                  | configkey | configvalue |
+------------------------+-----------+-------------+
| 154637                 | enabled   | no          |
| 154679                 | enabled   | no          |
| 154784                 | enabled   | no          |
| 155546                 | enabled   | no          |
| 157439                 | enabled   | no          |
| activity               | enabled   | no          |
| admin_dependencies_chk | enabled   | no          |
| admin_migrate          | enabled   | no          |
| appframework           | enabled   | no          |
| bookmarks              | enabled   | no          |
| calendar               | enabled   | no          |
| contacts               | enabled   | no          |
| documents              | enabled   | no          |
| external               | enabled   | no          |
| files                  | enabled   | yes         |
| files_antivirus        | enabled   | no          |
| files_archive          | enabled   | no          |
| files_external         | enabled   | no          |
| files_imageviewer      | enabled   | no          |
| files_locking          | enabled   | no          |
| files_mv               | enabled   | no          |
| files_odfviewer        | enabled   | no          |
| files_pdfviewer        | enabled   | no          |
| files_sharing          | enabled   | no          |
| files_texteditor       | enabled   | no          |
| files_trashbin         | enabled   | no          |
| files_versions         | enabled   | no          |
| files_videosPlayer     | enabled   | no          |
| files_videoviewer      | enabled   | no          |
| firstrunwizard         | enabled   | no          |
| gallery                | enabled   | no          |
| impress                | enabled   | no          |
| imprint                | enabled   | no          |
| internal_messages      | enabled   | no          |
| journal                | enabled   | no          |
| media                  | enabled   | no          |
| mozilla_sync           | enabled   | no          |
| news                   | enabled   | no          |
| notes                  | enabled   | no          |
| ocDashboard            | enabled   | no          |
| provisioning_api       | enabled   | no          |
| roundcube              | enabled   | no          |
| search_lucene          | enabled   | no          |
| storage_charts         | enabled   | no          |
| tal                    | enabled   | no          |
| tasks                  | enabled   | no          |
| templateeditor         | enabled   | no          |
| updater                | enabled   | no          |
| user_external          | enabled   | no          |
| user_ldap              | enabled   | no          |
| user_migrate           | enabled   | no          |
| user_openid            | enabled   | no          |
| user_photo             | enabled   | no          |

(during the install of 9.0.x all but 'files' were put to 'no')

**Comment by RealRancor** [comment] 2016-11-23 09:12
Hi,

> PHP Fatal error: Call to undefined method OC_User::getManager() in /var/www/sites/owncloud/apps/files/appinfo/register_command.php on line 23

there is no such call in a recent oC 9.0.6 register_command.php as seen here:

https://github.com/owncloud/core/blob/v9.0.6/apps/files/appinfo/register_command.php

This is a leftover from oC 8.2 and below:

https://github.com/owncloud/core/blob/v8.2.9/apps/files/appinfo/register_command.php#L23

**Comment by VincentSC** [comment] 2016-11-23 10:16
That's a hint, because my reaction was "That's impossible". Then I noticed the reference to /var/www/sites/owncloud/, while it has been installed under /var/www/owncloud/ - all is configured outside the public www.

Changed in config.php:

>  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/sites/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),

to
>  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),

It seems that this configuration mistake has been there for some time, but miraculously never gave a problem. It now works. Hopefully the upgrading of the plugins-entries in the database does not give problems, when I'm turning it on.

Many thanks for your support! 

Is there a command that shows all configured directories (data, apps), so a quick sanity check can be done?

**Comment by RealRancor** [comment] 2016-11-23 10:24
Hi,

> Changed in config.php:

this should be completely removed as well as a complete clean-up of your config.php should be done as advised above. A sane default config.php could be something like shown in:

https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html#default-config-php-examples

It is highly dis-encouraged to add stuff from the config.sample.php without any need as advised there:

> The installer creates a configuration containing the essential parameters. Only manually add configuration parameters to config/config.php if you need to use a special value for a parameter. Do not copy everything from config/config.sample.php . Only enter the parameters you wish to modify!

**Comment by VincentSC** [comment] 2016-11-23 10:53
Ok, will cleanup the config.php.

**Comment by RealRancor** [comment] 2016-11-23 11:47
@VincentSC You can also close this issue here. This is obviously an environmental configuration problem rather then a bug in ownCloud. If you need further support please jump over to https://central.owncloud.org/

**Closed** 2016-11-23 13:44 UTC
