### ISSUE TITLE
[Favorite] Favorite star turns grey after renaming a file or folder.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#13266] opened 2015-01-12 11:34 UTC
### Steps to reproduce

1. Make a file/folder favorite
2. Rename it

### Expected behaviour
Favorite star keeps activated.

### Actual behaviour
Star gets deactivated. File/Folder is still favorited, just the star colour is wrong.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.0.0.1","versionstring":"8.0 alpha 1","edition":""}

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
none

**The content of config/config.php:**

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes

### Client configuration
**Browser:**
Chrome, Firefox

**Comment by SergioBertolinSG** [comment] 2015-01-12 11:40
cc @PVince81

**Comment by PVince81** [comment] 2015-01-12 11:47
Duplicate of https://github.com/owncloud/core/issues/13215

@dttpy has raised a few issues related to favorites, you might want to search github before raising new issues :smile:

**Closed by PVince81** 2015-01-12 11:47 UTC

**Comment by SergioBertolinSG** [comment] 2015-01-12 12:26
Ok thanks
