### ISSUE TITLE
Make it easy to distinguish users in the share list and autocomplete

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#22652] opened 2016-02-25 16:19 UTC
Followup to https://github.com/owncloud/core/issues/20291

Ref 00004123

![screen shot 2015-11-04 at 11 23 01](https://cloud.githubusercontent.com/assets/1846927/10935515/eb528dd4-82e6-11e5-9e55-c28ff628be7d.png)

We should probably return proper user information and let the client side to decide what to display (only show full email addresses when there are duplicate display names for example).

@rullzer already proposed to return the full user information in theses cases (which allows the client side implementation of the view): https://github.com/owncloud/core/issues/20291#issuecomment-155847404

> Assume we have 3 users:
> 
> id: user1, email: user1@foo.com, displayName: Bar
> id: user2, email: user2@foo.com, displayName: Bar
> id: user3, email: , displayName: Bar
> And I share with all those users it whould show up as
> 
> Bar (user1@foo.com)
> Bar (user2@foo.com)
> Bar (user3)

@owncloud/designers for the UX part of this.

@schiesbn @PVince81 @rullzer for the API part.

**Comment by MorrisJobke** [comment] 2016-02-25 16:20
This was partially resolved by showing the internal username on hover: https://github.com/owncloud/core/pull/22611

**Comment by MorrisJobke** [comment] 2016-02-25 16:20
cc @cmonteroluque @MTRichards For the user story planning

**Comment by nickvergessen** [comment] 2016-02-26 07:58
> We should probably return proper user information

That is done: type, id and display value are sent via the api. So all information should be available.

**Comment by rullzer** [comment] 2016-02-26 08:08
@nickvergessen the issue is more about using information that means something to users. In big organisation the username might be totally meaningless to me, or at least I have no idea what the username is of that `John Doe` in the department on the other side of town. But I might know his e-mail because we have had several mail exchanges etc.

**Comment by MorrisJobke** [comment] 2016-02-26 08:31
> That is done: type, id and display value are sent via the api. So all information should be available.

What about the email address?

**Comment by butonic** [comment] 2016-04-18 12:18
An Idea and several questions:

Idea: Can we reuse and improve the dialog we have for selecting users to share external storages with?

![user selection](https://cloud.githubusercontent.com/assets/956847/14603539/9ad179c8-056e-11e6-9b28-5f499a855ca8.PNG)

How do the iOS, Android and desktop clients handle this? I think they should show the same information: An avatar, the displayname and the email address, or ... if it isn't set but two users need to be distinguished - only as a last resort - the internal uid. But honestly, the internal uid won't help with ldap users ... there it is a long id string that does not help end users distinguish share recipients. Email at least is familiar.

What is the status there?
- Do the frontends show a spinner when searching for users?
  - [ ] Web
  - [ ] iOS
  - [ ] Android
  - [ ] Desktop
- Do they show the displayname?
  - [ ] Web
  - [ ] iOS
  - [ ] Android
  - [ ] Desktop
- Do they show a second unique attribute? Which one?
  - [ ] Web
  - [ ] iOS
  - [ ] Android
  - [ ] Desktop
- [ ] Can the second display name be configured? 
- Do they show an avatar?
  - [ ] Web
  - [ ] iOS
  - [ ] Android
  - [ ] Desktop

**Comment by butonic** [comment] 2016-04-18 12:31
Pinging @dragotin and @rperezb for input on what the clients do when searching for users in the share dialog.

**Comment by butonic** [comment] 2016-04-18 12:31
cc @michaelstingl

**Comment by jancborchardt** [comment] 2016-04-18 13:46
@butonic oooh this is perfect, also for federated sharing! Yes, we should definitely reuse that. The only 2 things we need to adjust design-wise is:
- when there’s no email address, the name should be vertically centered with the avatar
- we need to adjust the select2 styles (use the same as we do for the tags dropdown)

**Comment by dragotin** [comment] 2016-04-18 13:54
should be doable on desktop - if there is an API providing all the data (Email, Avatar, ....)

**Comment by dragotin** [comment] 2016-04-18 13:54
@rullzer fYI

**Comment by DeepDiver1975** [comment] 2016-04-19 05:56
System addessbook will hold all information about the user including avatar, User Name, Email, displayname, Cloud ID and with 9.1 further Personal Informationen like phone numbers address and so on

**Comment by butonic** [comment] 2016-04-19 18:48
@dragotin and what is the current status? How does the desktop client determine what to display in the list of search results? Does it show a spinner when search is in progress?

**Comment by dragotin** [comment] 2016-04-19 19:17
I dont know. @rullzer?

**Comment by rullzer** [comment] 2016-04-19 19:38
Uhm... let me have a more detailed look tomorrow...

**Comment by nickvergessen** [comment] 2016-04-20 07:53
just tested:
It shows **no** spinner while the request is out, and it shows the display name in the dropdown

**Comment by rullzer** [comment] 2016-04-20 13:37
Thanks @nickvergessen

**Comment by butonic** [comment] 2016-04-21 14:39
@blizzz there now is a way to configure the way the display name is assembled?

**Comment by blizzz** [comment] 2016-04-21 23:40
@butonic LDAP only, you can specify a second attribute that shows up in brackets after the first value.

**Comment by nasli** [comment] 2016-04-26 17:09
In mobile clients (Android, iOS) the list shown only the displayname, except when there are duplicated displaynames, in that case it is shown as: displayname (username).

For remote users it is shown as:
displayname (server) 
and for duplicated remote users
displayname (username@server)

In the web the list shown only the displayname and on hover each displayname you can see the username.

**Comment by nasli** [comment] 2016-04-26 17:13
Related remotes server discussion https://github.com/owncloud/core/issues/23696

**Comment by PVince81** [comment] 2017-01-31 09:08
Web autocomplete will show an avatar in 10.0: https://github.com/owncloud/core/pull/25976.

**Comment by PVince81** [comment] 2017-04-07 15:17
closing as fixed through https://github.com/owncloud/core/pull/25976

**Closed by PVince81** 2017-04-07 15:17 UTC
Labels: blue-ticket, design, dev:ocs, enhancement, feature:federated-cloud-sharing, feature:sharing
