### ISSUE TITLE
Apache sending mail because of "PHP Fatal error:  Call to undefined method OfflineUser::processAttributes()"

### ISSUE THREAD

**Issue by tps800** [owncloud/core#20319] opened 2015-11-05 06:59 UTC
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. You will receive mail send by apache:
```
PHP Fatal error:  Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() in /var/www/html/owncloud/apps/user_ldap/lib/access.php on line 709
```
Because function OfflineUser::processAttributes() is undefined.

### Expected behaviour
no mail from apache

### Actual behaviour
Mail is send all 10 minutes:
```
PHP Fatal error:  Call to undefined method OCA\user_ldap\lib\user\OfflineUser::processAttributes() in /var/www/html/owncloud/apps/user_ldap/lib/access.php on line 709
```
Because code is executed holding an undefined function error.

### Client configuration
**Operating system:** Ubuntu 14.04.3 LTS

**OwnCloud Client:** 2.0.1

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 2.0.1, 2.0.2b1 (build 5464)

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.14-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.1.4-12.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Web server log
```

#### ownCloud log (data/owncloud.log)
```
ownCloud log
```

#### Browser log
```
Browser log
```

**Comment by MorrisJobke** [comment] 2015-11-05 08:16
Duplicate of #20090 and fixed with https://github.com/owncloud/core/pull/20192

**Closed by MorrisJobke** 2015-11-05 08:16 UTC
