### ISSUE TITLE
Login page in ie8 doesn't look good.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#18937] opened 2015-09-09 16:30 UTC
### Steps to reproduce

Using internet explorer 8 do:
1. Open login screen.

### Expected behaviour
Big logo, wide fixed textboxes.

### Actual behaviour
![screen shot 2015-09-09 at 17 53 35](https://cloud.githubusercontent.com/assets/9048796/9767893/c8126444-5720-11e5-89da-4d8384be5af6.png)

### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones.

Are you using external storage, if yes which one: local/smb/sftp/...
No.

Are you using encryption: 
No.

### Client configuration
Internet Explorer 8

**Comment by LukasReschke** [comment] 2015-09-10 07:50
@jancborchardt

**Comment by jancborchardt** [comment] 2015-09-17 22:30
Duplicate of https://github.com/owncloud/core/issues/18619

**Closed by jancborchardt** 2015-09-17 22:30 UTC
Labels: bug, design, sev4-low
