### ISSUE TITLE
[enc2] Empty reply from server on download

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15631] opened 2015-04-15 09:37 UTC
### Steps to reproduce
1. Setup OC master (1a2475227b6777e016ec931ddae533437bfbb2dd)
2. Enable encryption app and enable encryption in the admin page
3. Log out then log in again
4. In the web UI, create a file "new.txt" with some contents, I used "abc"
5. On the CLI, use curl to download the file: `curl http://root:admin@localhost/owncloud/remote.php/webdav/new.txt`

### Expected result
File can always be downloaded

### Actual result
90% of the time, getting:
```
curl: (52) Empty reply from server
```
Nothing in the log.

### Versions
ownCloud master (1a2475227b6777e016ec931ddae533437bfbb2dd)
openSUSE Factory
php5-5.6.7-1.1.x86_64
apache2-2.4.12-2.1.x86_64

@MorrisJobke can you try with your PHP 5.6 and see if you also get this issue ? (in case it's related to PHP 5.6)

The issue doesn't appear if encryption is not enabled.

@schiesbn could not reproduce it with an older PHP version, so I'll try and debug it.

**Comment by PVince81** [comment] 2015-04-15 10:03
Something might be wrong with feof.
Even thought the file is small and contains only 3 bytes ("abc"), stream_read is called twice. The first call returns "abc" and the next one returns an empty block.
I'd expect the caller to find out that the file is finished (when calling feof()), but it still calls an empty block. Maybe it messes it up.

Note: the caller is `file_put_contents()` from Sabre that puts the stream result into the PHP output.

I tried with bigger files: it seems that if the file is bigger than 8k, download works fine.
Files with sizes 4096 bytes or 6000 bytes also return empty content.

**Comment by PVince81** [comment] 2015-04-15 10:05
I tried with another file that is 8193 bytes big:
```
dd if=/dev/urandom of=8193.dat count=1 bs=8193
```

When I download it with curl + webdav, it tells me that there is one byte remaining that wasn't sent.
The Content-Length header is correct.

This means that our code closed the connection to early and didn't deliver the last byte.

Something seems to be wrong with that loop.
Would be good to improve the unit tests to test different sizes.

**Comment by PVince81** [comment] 2015-04-15 10:06
Note: my test files were uploaded with the web UI.
Except the text file: I created it using the text editor.

**Comment by PVince81** [comment] 2015-04-15 10:08
@schiesbn @DeepDiver1975 can you guys have a look ?

**Comment by DeepDiver1975** [comment] 2015-04-15 10:13
Let me have a look at this ....

**Comment by DeepDiver1975** [comment] 2015-04-15 10:39
according to https://github.com/owncloud/core/pull/15633 no issue with the plain stream wrapper

**Comment by PVince81** [comment] 2015-04-16 09:50
also CC @jknockaert in case you have an idea

**Comment by jknockaert** [comment] 2015-04-16 18:14
@PVince81 There seems to be an issue left with the correct handling of the unencrypted filesize. #15636 was created by @schiesbn to handle an issue that should not occur when unencryptedSize gets correctly initialised upon write. If the initialisation is wrong, it will also write a wrong value to the filesystem cache upon close after write. Then when opening again, things go wrong unless some process corrected the unencrypted filesize in between (which may explain why things don't always go wrong). There's actually more pointing towards incorrect unencryptedSize values, including the need to comment out a line that should be harmless https://github.com/owncloud/core/commit/8b657270450bffac88390b67b177ce0a3622447d (motivated here: https://github.com/owncloud/core/commit/334d144dc0e714189fceaefa8309bca9c67727d6#commitcomment-10547255 my reaction: https://github.com/owncloud/core/pull/14472#issuecomment-88946253). My intuition is that there's something odd going on with the handling of the unencrypted filesize.

**Comment by jknockaert** [comment] 2015-04-20 11:06
In the process of fixing #15636 been studying the stream wrapper. There's a bug with header handling after the pointer is moved back to position 0. Not sure if it correlates with this PR, but I will anyway fix the wrapper code tonight.

**Comment by PVince81** [comment] 2015-04-20 16:43
Note: this error seems to have disappeared on master (3e8f6cdba95690a12de4f8d6b99c59f7a823fbb0)

It seems the problem has fixed itself or was fixed in between.
If no one else can reproduce it I suggest to close this ticket.

**Comment by schiesbn** [comment] 2015-04-22 09:32
Just tried it again on master and still can't reproduce it. We merged a lot of bug fixes in the meantime. So I assume that it is fixed if noone can reproduce it any longer.

**Closed by schiesbn** 2015-04-22 09:32 UTC
Labels: app:encryption, bug, sev1-critical
