### ISSUE TITLE
I don't see the contacts from the web panel

### ISSUE THREAD

**Issue by riccardopirani** [owncloud/core#29634] opened 2017-11-20 15:37 UTC
### Expected behaviour
owncloud web panel does not charge me contacts on the web panel

### Server configuration
Operating system Ubuntu 16.04.3 LTS
 Web server:  Apache

**Database:** MariaDB

**PHP version:** 7.0.22

**ownCloud version:** 10.0.3(stable)

**Updated from an older ownCloud or fresh install:** updated from older

**Where did you install ownCloud from:** from owncloud.org

**List of activated apps:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/redis.so' - /usr/lib/php/20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
An unhandled exception has been thrown:
OCP\AppFramework\QueryException: Could not resolve CardDavBackend! Class CardDavBackend does not exist in /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php:98
Stack trace:
#0 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(113): OC\AppFramework\Utility\SimpleContainer->resolve('CardDavBackend')
#1 /var/www/owncloud/apps/dav/appinfo/register_command.php(36): OC\AppFramework\Utility\SimpleContainer->query('CardDavBackend')
#2 /var/www/owncloud/lib/private/Console/Application.php(114): require('/var/www/ownclo...')
#3 /var/www/owncloud/console.php(105): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')

**Are you using encryption:** no

### Client configuration
**Browser: Chrome**

**Operating system: Windows**

**Comment by kdslkdsaldsal** [comment] 2017-11-20 15:47
Closing as a duplicate of https://github.com/owncloud/core/issues/29544 and https://github.com/owncloud/core/issues/28068 until the reason and all of it's side-effects of this "Could not resolve CardDavBackend" message are known.

**Closed by kdslkdsaldsal** 2017-11-20 15:47 UTC
Labels: bug
