### ISSUE TITLE
Recursive shares

### ISSUE THREAD

**Issue by tpinkowski** [owncloud/core#17861] opened 2015-07-25 08:56 UTC
Steps to reproduce

Share a folder over a link.
Try to get the subfiles for a shared folder over the REST API.

Expected behaviour
Share the subfolders and subfiles recursively in a way that they are also shared over a link and available over the REST API.

Actual behaviour

Only a share link for the shared folder without considering the subfiles.
Subfolders aren't traversed over the REST API.

Operating system:

Windows 7

Web server:

Apache

Database:

mysql

PHP version:

PHP 5.5

ownCloud version: (see ownCloud admin page)

8.0.1

Updated from an older ownCloud or fresh install:

no

List of activated apps:

Activity, Calendar, Contacts, Deleted Files, First Run Wizard, Share Files, Text Editor, Updater, Versions

Are you using external storage, if yes which one: local/smb/sftp/...

no

Are you using encryption: yes/no

no

Are you using an external user-backend, if yes which one:

no

**Comment by PVince81** [comment] 2015-07-28 10:13
@schiesbn @rullzer is this a bug or was it intended ?

**Comment by rullzer** [comment] 2015-07-28 10:57
This is expected behaviour. Basically what we do if the subfiles argument is provided is is that check for each file and directory in the given path see if we have shares for that item.

So traversing all the way down could (in deep folder structures) can easily lead to a PHP timeout.

**Comment by rullzer** [comment] 2015-07-28 10:58
So you should see 1 level of shares... let me double check...

**Comment by rullzer** [comment] 2015-07-28 11:03
Works here.

root
-- dir
 |-- dir_a
 |-- dir_b
 |-- file_c
 |-- file_d

If I share dir and all the files and folders in dir. If I do a

```../shares```  I get them all
```../shares?path=dir``` I get only the share for dir
```../shares?path=dir&subfiles=1``` I get the shares for the subfiles and directories

**Comment by rullzer** [comment] 2015-07-28 11:05
Having said that we could probably switch (for sharing 2.0) to a filter based on the file name path. So first collect all shares and then apply the filter.

This is probably even faster than traversing all the files and dirs in a directory.

**Comment by PVince81** [comment] 2015-09-22 09:16
What's the next step ? @rullzer's suggestion sounds like an enhancement.

@tpinky did @rullzer's info help you ?

**Comment by tpinky** [comment] 2015-09-22 09:35
@PVince81
I think the filter based approach would be ok.
I haven't implemented it yet. But maybe someone else did.
I didn't checked it at that time:)

**Comment by PVince81** [comment] 2015-09-22 09:39
Switching from "bug" to "enhancement" then

**Comment by rullzer** [comment] 2016-02-07 17:48
So after now implementing the share provider. My suggested enhancement here will not scale. Since you need to fetch all shares before you can do any filtering. So if you want this info you'll either have to do a lot of individual requests (traverse yourself).

Or request all shares and then filter yourself...r

**Comment by PVince81** [comment] 2016-02-12 10:31
Something to look into maybe for 9.1 ?

**Comment by PVince81** [comment] 2016-12-08 14:16
Moving to backlog for now. The discussion can continue nevertheless.

**Comment by PVince81** [comment] 2017-12-15 15:17
Considering that this doesn't scale, closing

**Closed by PVince81** 2017-12-15 15:17 UTC
Labels: enhancement, feature:sharing
