### ISSUE TITLE
update to 8.1.3 failed during database update

### ISSUE THREAD

**Issue by lazyzero** [owncloud/core#19232] opened 2015-09-21 20:28 UTC
Hi, I get this message when I updated one of my owncloud instances. In this instance I use the Calendar. The other instances updated without a problem
Here is the Log:
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "calendar_index" as such route does not exist.

**Comment by RealRancor** [comment] 2015-09-22 05:23
Dup of https://github.com/owncloud/core/issues/18350, https://github.com/owncloud/core/issues/18334, https://github.com/owncloud/core/issues/18333, https://github.com/owncloud/core/issues/18317, https://github.com/owncloud/core/issues/18329, https://github.com/owncloud/core/issues/18296, https://github.com/owncloud/core/issues/18224, https://github.com/owncloud/core/issues/19192 and many more...

https://github.com/owncloud/core/issues/19145 contains the ongoing discussion. A workaround is to run the upgrade routine again.

**Comment by PVince81** [comment] 2015-09-22 14:42
Closing as duplicate of https://github.com/owncloud/core/issues/19145

**Closed by PVince81** 2015-09-22 14:42 UTC
