### ISSUE TITLE
[QA] recursive folder delete does not respect suffix or size based trashbin skips

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38952] opened 2021-07-07 21:50 UTC
## Seen in 10.8.0 beta2

* Add the following to config.php:
```
  'trashbin_skip_extensions' => [  'mp3',  ],
  'trashbin_skip_size_threshold' => "180MB",
```

* upload a 200MB zip file, upload a 30 MB.mp3 file
* select both files in the web UI, and click the trashcan to delete. 
* deleted without adding to trashcan. OK.
```
{"reqId":"KCkatgLKIo5dUAVPQRWY","level":1,"time":"2021-07-07T21:44:39+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/30MB.mp3","message":"Path 30MB.mp3 skipped the trashbin and has been deleted immediately due to the trashbin_skip_extensions config .mp3"}
{"reqId":"KCkatgLKIo5dUAVPQRWY","level":1,"time":"2021-07-07T21:44:39+00:00","remoteAddr":"172.17.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/200MB.zip","message":"Path 200MB.zip skipped the trashbin and has been deleted immediately due to the trashbin_skip_size_threshold config 180MB"}
```

* upload a 200MB zip file, upload a 30 MB.mp3 file into the Documents folder
* delete the Documents folder.
* both the 200MB zip file and the 30 MB.mp3 end up in the trashcan. BAD

![image](https://user-images.githubusercontent.com/1108546/124833018-d311d780-df7d-11eb-88e9-caa43e49da5a.png)

Expected behaviour: Suffix and size based skips are honored always.

**Comment by phil-davis** [comment] 2021-07-08 03:23
I added tests that demonstrate this issue - PR #38958

**Comment by phil-davis** [comment] 2021-07-08 03:26
Also I observed that `trashbin_skip_extensions` is case sensitive. So if you want to skip all `iso` `ISO` `Iso`... extensions then you have to list all the combinations of upper-lower case individually.

@pmaier1 Is that the intended way the feature works?

**Comment by micbar** [comment] 2021-07-08 08:01
@JanAckermann  Can you check?

**Comment by JanAckermann** [comment] 2021-07-08 08:38
> Also I observed that trashbin_skip_extensions is case sensitive. So if you want to skip all iso ISO Iso... extensions then you have to list all the combinations of upper-lower case individually.

Nope this is bad design should not be like this.

**Comment by phil-davis** [comment] 2021-07-08 08:45
> @phil-davis
> 
> > Also I observed that trashbin_skip_extensions is case sensitive. So if you want to skip all iso ISO Iso... extensions then you have to list all the combinations of upper-lower case individually.
> 
> Nope this is bad design should not be like this.

Test Scenario https://github.com/owncloud/core/commit/9ee57a09c33e16a4ec4076687b608f634df460cf#diff-005bdfaa1441eadf24db7cb0090cc4036b509d4f38b6879073049f317331e1edR44 demonstrates the current case-sensitive behavior of `trashbin_skip_extensions`

You will need to adjust that so it demonstrates the opposite, and then adjust the server code to make it pass.

**Comment by JanAckermann** [comment] 2021-07-08 08:52
@phil-davis can you rebase them into the release branch as https://github.com/owncloud/core/pull/38960 will also follow it ?

**Comment by phil-davis** [comment] 2021-07-08 08:58
> @phil-davis can you backport them into the release branch as #38960 will also follow it ?

What will be the process for the next 10.8.0betan?

If the release branch will be rebased, then we can keep working in `master`

If you are making a PR to `release-10.8.0` then it might be easiest if you just cherry-pick the commit from master into your PR. Then make commit(s) to adjust the tests and code.

**Comment by micbar** [comment] 2021-07-08 09:14
We should not rebase at this stage, that would invalidate the testing.

Make only changes on the Release branch.

**Comment by JanAckermann** [comment] 2021-07-08 09:14
@jvillafanez any idea how to overcome this issue, the TrashbinStorage does not obey single files in a folder, just the folder itselfs

**Comment by phil-davis** [comment] 2021-07-08 10:00
It only needs to bother traversing down the tree if trashbin skip for file size or file extension is enabled. For performance, that could be checked, and do the existing "old" code if those things are not enabled.

That would mean almost no impact for installations that do not set these trashbin skip options.

**Comment by hodyroff** [comment] 2021-07-08 10:27
The described behaviour is correct. When a folder is deleted it must be available for restore completely.
This avoids accidental deletes.
Expected behaviour above is wrong.

**Comment by micbar** [comment] 2021-07-08 10:30
Fine, thanks @hodyroff

**Comment by JanAckermann** [comment] 2021-07-08 10:34
Closing this issue after #38960 since this solves the case sensitive file extenstion issue @phil-davis mentioned

**Comment by phil-davis** [comment] 2021-07-08 11:08
Summary of the requirement, which is also what is implemented:

1) If a single file is deleted, and its extension case-insensitive-matches any of the `trashbin_skip_extensions` then the file does not go in the trashbin. This is true both for a file in the "root" directory, and for a file in a sub-directory.

2) If a single file is deleted, and its size is greater than or equal to `trashbin_skip_size_threshold` then the file does not go in the trashbin. This is true both for a file in the "root" directory, and for a file in a sub-directory.

3) If a top-level directory is deleted, and it is in `trashbin_skip_directories` then NONE of its contents go in the trashbin.

4) If a top-level directory is deleted, and it is NOT in `trashbin_skip_directories` then ALL of its contents go in the trashbin. (including any files that could have matched `trashbin_skip_extensions` or `trashbin_skip_size_threshold` - i.e. those other file-based rules are not applied to the files inside the deleted folder tree)

Correct?

**Comment by jvillafanez** [comment] 2021-07-08 11:33
Traversing the directory recursively could end up being a big performance issue. You can assume there will be millions of files to check one by one, and even if we can check them in the DB (we might still need to access the storage) it's bound to be slow.

Taking into account the `trashbin_skip_directories` option, the idea would be use that option to provide a folder whose contents will be deleted immediately.
For example, the admin could set `'trashbin_skip_directories' => ['/SFTP/ocHole', '/SMB/ocHole']` (does setting 'ocHole' works for all the mounts?) so if the user wants to delete contents ignoring the trashbin, the user can move the content there (a move within the storage should be "fast") and then delete the contents from that directory.
@JanAckermann it might be a good idea to check if it can work with external storages, and provide an example in the config.php file of how it could work.

Does the size skip works with directories? In theory it could work, but all the oc backends I've checked so far report 0 as size for the folder, so it won't work.

The extension skip should also work with the directory itself, but not its content. If a folder called "folder.iso" is deleted, it will skip the trashbin. If this is the case, we might also warn in the config.php file about this behaviour (or change it). It isn't common, but there could be folders ending with ".conf" or ".d"

**Comment by JanAckermann** [comment] 2021-07-08 12:07
@phil-davis all assumptions are correct :+1:

**Closed** 2021-07-08 12:12 UTC
