### ISSUE TITLE
Renaming a folder deletes all subfolders (!)

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#11898] opened 2014-11-01 00:14 UTC
Ouch! Yesterday I renamed my folder containing lots of subfolders (~ 200 GB) from `michael.heuberger` to `michael-heuberger` and after that, all subfolders are gone, lost.

I renamed it through the stable owncloud user interface, version 7.0.2. The icon I clicked to initiate the rename action was the pencil icon `rename.svg`. After the renaming process the link became `https://(hidden)/index.php/apps/files?dir=/M1/home/michael-heuberger` - when I clicked on it, no subfolders are shown. Before the rename process I had four subfolders with more than 200 GB of data.

When I SSH into the server, I can still see the subfolders! But not on the user interface. Somehow owncloud does not recognize this.

Looks like a bug. Make sure you have tests to check renaming won't mess up with the files.

And tell me, how can I fix this? I do not want to re-upload 200 GB of data over again.

**Comment by PVince81** [comment] 2015-04-13 09:10
Likely duplicate of https://github.com/owncloud/core/issues/13391

**Closed by PVince81** 2015-04-13 09:10 UTC
Labels: bug, needs info
