### ISSUE TITLE
contact_birthdays shows only year, not the age

### ISSUE THREAD

**Issue by fireba11** [owncloud/core#24217] opened 2016-04-23 10:16 UTC
### Steps to reproduce
1. add a birthday to a contact
2. look at calendar

### Expected behaviour
calendar shows the age of the person celebrating their birthday (it did so in 8.2)
showing age(year) or something might be a good idea too, maybe make it configurable?

### Actual behaviour
calendar shows the birth year

### Server configuration
**Operating system**:
debian 8.3
**Web server:**
apache 2.4.10-10+deb8u4
**Database:**
mysql 14.14
**PHP version:**
5.6.17-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated (removed everythin except config.php and data folder, then installed with web installer
**Where did you install ownCloud from:**
https://download.owncloud.com/download/community/setup-owncloud.php
**Signing status (ownCloud 9.0 and above):**
Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini
**List of activated apps:**
Enabled:

    activity: 2.2.1
    calendar: true
    comments: 0.2
    contacts: true
    dav: 0.1.5
    federatedfilesharing: 0.1.0
    federation: 0.0.4
    files: 1.4.4
    files_external: 0.5.2
    files_pdfviewer: 0.8
    files_sharing: 0.9.1
    files_texteditor: 2.1
    files_trashbin: 0.8.0
    files_versions: 1.2.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 14.5.0
    notifications: 0.2.3
    provisioning_api: 0.4.1
    systemtags: 0.2
    templateeditor: 0.1
    updatenotification: 0.1.0
	
Disabled:
    encryption
    external
    user_external
    user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/clients\/client1\/web43\/web\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "c1owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "check_for_working_webdav": false,
        "theme": "",
        "trusted_domains": [
            "owncloud.somedomain.com",
            "owncloud.somedomain.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "somedomain.com",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,90",
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
FF 45.0.1
**Operating system:**
Win10

**Comment by RealRancor** [comment] 2016-04-23 10:30
@fireba11 Please re-open in https://github.com/owncloud/calendar/issues where the issue tracker of the calendar is located.

**Comment by fireba11** [comment] 2016-04-23 10:36
Oh, they still got a seperate tracker? sorry ...

**Comment by RealRancor** [comment] 2016-04-23 10:39
> Oh, they still got a seperate tracker? sorry ... 

Yes :-) The calendar and contacts apps are non-shipped / community maintained apps. Only apps shipped within the owncloud-9.0.x.tar.bz2 are handled in the core issue tracker.

**Comment by DeepDiver1975** [comment] 2016-04-24 07:26
The birthday calendar is generated and provided by the DAV backen living in core.
The issue is valid in here.

**Comment by DeepDiver1975** [comment] 2016-04-25 09:04
From what I can tell it is not possible. The birthday event is stored as one recurring event in the calendar and there is no possibility to tell any CalDAV client to adjust the title.

**Comment by RealRancor** [comment] 2016-04-25 12:11
What about handling this on client side (calendar app)? The calendar app could know that the event is coming from the birthday calendar and could parse and calculate the age based on the year?

**Comment by DeepDiver1975** [comment] 2016-04-25 12:13
well - could be done - but then there is no consistency in visualization of data across clients.

**Comment by fireba11** [comment] 2016-04-25 13:01
There is a gazillion calendar clients out there ...
What about changing the event title as apropriate? Every client should sync it at least once a day, and it's read-only anyway.
Or just create one event per year up untill today + 10years so we don't get buckload of single events?

**Comment by DeepDiver1975** [comment] 2016-04-25 13:09
> Or just create one event per year up untill today + 10years so we don't get buckload of single events?

No - we should not pollute the database that way

**Comment by DeepDiver1975** [comment] 2016-05-02 10:16
I'm closing this - there is no way to get this implemented in the caldav core - we might add some magic to the calendar app - no idea

**Closed by DeepDiver1975** 2016-05-02 10:16 UTC
Labels: app:dav, enhancement

**Comment by RealRancor** [comment] 2016-05-03 05:59
@DeepDiver1975 Then it could make sense to re-open https://github.com/owncloud/calendar/issues/490

**Comment by Joe6832** [comment] 2016-11-07 13:36
Would be nice to implement that. There is a app called EboBirthday, which doesnt work anymore (dev not available too). But this app creates for every year a new entry in calendar with the actual age. So you could do this here the same way
