### ISSUE TITLE
Deleting user with provisioning API can take a long time

### ISSUE THREAD

**Issue by christopheg** [owncloud/core#21249] opened 2015-12-17 07:52 UTC
When deleting a user via an API call, the answer from API can take a very long time.
Current situation:
1) An API call to https://my_owncloud/ocs/v1.php/cloud/users/my_username (DELETE) 
2) The server deletes the data of this user (can take a very long time if the user has 200GB of small files)
3) An answer is sent via API

Better would be:
1) An API call to https://my_owncloud/ocs/v1.php/cloud/users/my_username (DELETE) 
2) The server marks the user as 'deleted'. The account will be blocked (no login possible)
3) An answer is sent via API
4) A cleanup via Cron is performed in the background

**Comment by PVince81** [comment] 2015-12-17 09:31
@christopheg ownCloud version ?

**Comment by PVince81** [comment] 2015-12-17 09:31
What you described under "Better would be" was implemented in OC >= 8.1.
The slow behavior was in OC < 8.1.

**Comment by PVince81** [comment] 2015-12-17 09:38
Ref https://github.com/owncloud/core/pull/14644

**Comment by gerryd** [comment] 2015-12-18 16:20
Hi Vincent,

I'm afraid it isn't fixed. I think you might have misunderstood the description. I'll try to explain it in another way. :)

The ownCloud version used is 8.1.4.

The problem is that deleting a user who has many files in his/her account takes a long time. It would be better if the actual "delete" operation was a background task and the API would immediately return an OK. See the examples below.

# User with just a few files
```
[me@host ~]$ time curl -X DELETE --user username:password https://my.owncloud.install/ocs/v1.php/cloud/users/foo
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>

real	0m0.133s
user	0m0.010s
sys	0m0.000s
```

# User with many files
```
[me@host ~]$ time curl -X DELETE --user username:password https://my.owncloud.install/ocs/v1.php/cloud/users/bar
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

real	6m0.046s
user	0m0.010s
sys	0m0.013s
```

**Comment by PVince81** [comment] 2015-12-18 16:26
Ah, that's more clear.
When I saw "DELETE" I directly thought Webdav DELETE.
I'll adjust the subject.

**Comment by hodyroff** [comment] 2017-03-28 20:25
Since we now have disable I would think that it should be put on disable first and then be deleted - so what you wanted is now reachable without changing code. Closing, please comment/reopen if I am wrong.

**Closed by hodyroff** 2017-03-28 20:25 UTC
Labels: app:provisioning_api, bug, sev3-medium
