### ISSUE TITLE
Cron & PHP-CLI : SCRIPT_FILENAME and SCRIPT_NAME undefined

### ISSUE THREAD

**Issue by marktamis** [owncloud/core#11551] opened 2014-10-13 16:13 UTC
### Steps to reproduce
1. Set up cron to use <your_owncloud_dir>/cron.php
2. Check mailbox where cron log messages are sent
3. see owncloud cronjob output in email

### Expected behaviour
No email error message sent

### Actual behaviour
Email contains the following information:
Cron <root@xxxxxxxx> php -f /var/www/owncloud/cron.php
PHP Notice:  Undefined index: SCRIPT_FILENAME in /var/www/owncloud/lib/base.php on line 107
PHP Notice:  Undefined index: SCRIPT_NAME in /var/www/owncloud/lib/private/request.php on line 168

As the cronjob runs every 15 minutes, this rapidly fills up the inbox

### Server configuration
Ubuntu 14.04.4

**Web server:**
nginx 1.7.6

**Database:**
10.0.14-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 5.5.17-2+deb.sury.org~trusty+1 (cgi-fcgi)

**ownCloud version:** (see ownCloud admin page)
7.0.2

**Updated from an older ownCloud or fresh install:**
7.0

**Are you using encryption:** yes/no
yes

### Client configuration
php command line (php-cli)

### Quick fix
php-cli does not have access to $_SERVER variables needed by the two php files that are mentioned in the output of the email

in line 48 of cron.php, I have added the following lines in cron.php at line 48 so that php-cli does have access to these variables:

	$_SERVER["SCRIPT_FILENAME"] = "/var/www/owncloud/cron.php";
    	$_SERVER["SCRIPT_NAME"] = "/cron.php";

A better way would be to wrap this to check whether these variables are already set to accomodate for calling this from crontab or not

**Comment by jakobsack** [comment] 2015-01-24 21:48
This bug could be caused by using php-cgi instead of php.

@marktamis could you please try to figure out which php binary really is called? For example, on my system "/usr/bin/php" is a symlink to "/etc/alternatives/php" which is a symlink pointing to "/usr/bin/php5":

```
root@localhost:/var/www/owncloud/current# which php
/usr/bin/php
root@localhost:/var/www/owncloud/current# ls -lha /usr/bin/php
lrwxrwxrwx 1 root root 21 Jul 28 18:37 /usr/bin/php -> /etc/alternatives/php
root@localhost:/var/www/owncloud/current# ls -lha /etc/alternatives/php
lrwxrwxrwx 1 root root 13 Jul 28 18:37 /etc/alternatives/php -> /usr/bin/php5
root@localhost:/var/www/owncloud/current# ls -lha /usr/bin/php5
-rwxr-xr-x 1 root root 8,7M Jan  8 20:04 /usr/bin/php5
```

**Comment by marktamis** [comment] 2015-01-26 09:09
/usr/bin/php -> /etc/alternatives/php
/etc/alternatives/php -> /usr/bin/php-cgi
/usr/bin/php5

I think it may be due to the code checking variables contained in $_SERVER,
which is not available in within the context of the cron job (from cli).
What do you think?

**Comment by cyberic99** [comment] 2015-01-28 08:14
I have the same problem on a cpanel installation. Using php-cli instead of php fixes the problem for me.

**Comment by nickvergessen** [comment] 2015-03-24 12:18
Duplicate of #7715

**Closed by nickvergessen** 2015-03-24 12:18 UTC
Labels: bug
