### ISSUE TITLE
Unlock button should be disabled after a click

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34218] opened 2019-01-22 14:06 UTC
### Steps to reproduce

1. Lock a file
2. Via webUI check the file is locked
3. via WebUI, browse to the sidebar and unlock the file clicking twice

### Expected behaviour

The lock icon/button should be get disabled after the 1st click

### Actual behaviour

It is possible to click several times

![unlock](https://user-images.githubusercontent.com/10596560/51539543-93f67700-1e54-11e9-877d-ed375c7374ee.gif)

![screen shot 2019-01-22 at 14 47 11](https://user-images.githubusercontent.com/10596560/51540306-5f83ba80-1e56-11e9-914b-000d5622fafe.png)

### Server configuration
Ubuntu 16.0.4. LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.1

**Where did you install ownCloud from:**
https://download.owncloud.org/community/testing/owncloud-10.1.0beta.tar.bz2

**Comment by individual-it** [comment] 2019-01-23 08:49
cannot reproduce it on stable10 nor on master, was it fixed?

**Comment by individual-it** [comment] 2019-01-24 04:20
OK, the problem is, that the LOCK only disappears after the "UNLOCK" request was successful. If the user manages to click multiple times before the response comes back from the server, the server receives multiple "UNLOCK" requests and shows the documented error.
Some kind of a loading-indicator would be nice

To reproduce:
1. install the testing app
1. slow down the UNLOCK request `curl -u admin:admin -X PUT http://localhost/owncloud-core/ocs/v2.php/apps/testing/api/v1/davslowdown/UNLOCK/10`
1. LOCK the file
1. try to UNLOCK it multiple times from the webUI

to delete the slowdown again: `./occ config:system:delete dav.slowdown`

**Comment by JanAckermann** [comment] 2021-09-27 12:17
This only is happening in very slow networks, it is known that triggering an action twice might lead to conflicts. 
I think unfortunately we need to say "won't fix" here.

**Closed by JanAckermann** 2021-09-27 12:17 UTC
Labels: Type:Bug, feature:persistent-locking
