### ISSUE TITLE
rename/post_rename not fired for files_encryption

### ISSUE THREAD

**Issue by semirke** [owncloud/core#17877] opened 2015-07-26 12:59 UTC
Hi, 

  I happened to realize that when moving files around (files_mv) OC wont move their keys. 
  Files_mv uses core's move function, which emmits preRename|preWrite and postRename|postWrite. However, the connected Hook in files_encryption is not being run. (Tested with log writing.) 
  On delete post_delete hook works. 

  Files_encryption hooks in OC_Filesystem rename and post_rename. Checked, connectHook returns success.

  Im using OC 8.0.4 with files_encryption 0.7.1 .

I see no reason in it :|

Thanks,
Semirke

**Comment by karlitschek** [comment] 2015-07-26 16:20
Hmm. This should actually work
@schiesbn any idea?

**Comment by PVince81** [comment] 2015-07-28 10:18
@semirke which core move function does it use ? `$view->rename()` or the node API ?
Do you have a link to its source code maybe ?

**Comment by semirke** [comment] 2015-07-28 10:21
Hi, 
  this is the files move app: https://github.com/eotryx/oc_files_mv
  and here it does it's magic: https://github.com/eotryx/oc_files_mv/blob/master/controller/movecontroller.php#L85

Thanks!

**Comment by schiesbn** [comment] 2015-07-28 10:41
Which version of the files_mv app do you use?

**Comment by schiesbn** [comment] 2015-07-28 11:10
I think the problem is the files node app. It emits the rename signal with the class '\OC\Files' while the rename operation in the view emits the rename signal with the 'OC_Filesystem' class (https://github.com/owncloud/core/blob/master/lib/private/files/node/file.php#L144).
 
At the same time shouldEmitHooks() (https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L1075) evaluate to false, so the view doesn't trigger its hooks. This happens because the fakeRoot is '' and the defaultRoot is '/schiesbn/files' if I move a file from the root to testfolder/ as user schiesbn. -> ````strlen($this->fakeRoot) > strlen($defaultRoot)```` is false so shouldEmitHooks() returns false.

@icewind1991 can you have a look. I think you can decide better what's the best way to fix it.

**Comment by semirke** [comment] 2015-07-28 13:09
Thank you for looking into it!

**Comment by schiesbn** [comment] 2015-07-28 13:36
@semirke it is already (almost) fixed in 8.1. With this follow up fix it should be fixed completely https://github.com/owncloud/core/pull/17932

**Comment by semirke** [comment] 2015-07-28 14:24
Ah, thanks! I'll try it out as soon as I can.

**Comment by cmonteroluque** [comment] 2015-08-18 10:16
@schiesbn Can the unit tests be fixed for the PR to be merged and we can close this one?

**Comment by DeepDiver1975** [comment] 2015-08-26 15:01
#17948 has just been postponed to 8.0.8 -> this moves as well

**Comment by cmonteroluque** [comment] 2015-10-14 21:21
@schiesbn @DeepDiver1975 can this be resolved for 8.0.9 now

**Comment by schiesbn** [comment] 2015-10-15 13:04
I debugged it once more because I wasn't sure what the exact problem was, which lead me again back to https://github.com/owncloud/core/issues/18590

The problem is that we move a file from ````/files/...```` to ````files_trashbin/...```` at the beginning of the rename we just check the condition for the source path if a hook should be called or not. At the end, for the post-hook we check the source and the target path. For the target path the check will return false because it is outside of the files folder and so the variable "$disanbleTrash" will never be reseted.

I think we should really start to discuss https://github.com/owncloud/core/issues/18590 and fix this general behavior for master. I tend to not apply such a change to 8.0. Instead I would recommend to update to 8.1 or newer if you use the 3rdparty app file_mv

**Comment by MorrisJobke** [comment] 2015-10-21 12:56
@cmonteroluque @schiesbn What is the decision here? If this is a won't fix please also close #17948

**Comment by schiesbn** [comment] 2015-10-21 13:31
The changes are to large for 8.0, I'm sure @semirke already updated to 8.1 or newer where it is fixed -> close

**Closed by schiesbn** 2015-10-21 13:31 UTC
Labels: app:files_encryption, bug
