### ISSUE TITLE
Paths get cut off in activity stream/email

### ISSUE THREAD

**Issue by flimmbing** [owncloud/core#22436] opened 2016-02-16 15:44 UTC
All file names and paths will get cut off in the activity stream and the desktop client as well (although the links behind work).

Example:

instead of: "my-share/my-folder/my-file.xls" I get: "ile.xls" (or similar, see screenshots)

Reproduce error:

1. An external storage is added by user "admin", as local type on the same server: "/var/www/clients/client1/cloud.my-site.com/web/owncloud/data/shareddata/"

2. This storage is shared by admin with members of the group "users". Now all members get access (read/write/share) and the changes appear in the acitivity stream and works fine, except for the described problem.

See the screenshots for reference.

cut off (looks the same in OC): https://www.dropbox.com/s/o6r01ivpml1ik ... 6.png?dl=0
not cut off in protocol: https://www.dropbox.com/s/o59l4p8jhauwk ... 8.png?dl=0

Apart from that this error seems only to apply for the shared resource. Any ideas?

Environment:
Apache/2.4.10 (Debian)

Server: 
Debian GNU/Linux 8.2 (jessie)

Database: 
MySQL

Client: 
?

OC-Version:
8.2.2 (stable)

PHP-Version:
5.6.13-0+deb8u1

**Comment by PVince81** [comment] 2016-02-17 09:29
@nickvergessen

**Comment by nickvergessen** [comment] 2016-02-17 09:52
Duplicate of https://github.com/owncloud/core/issues/15858

**Closed by nickvergessen** 2016-02-17 09:52 UTC
Labels: bug, feature:activity, sev3-medium
