### ISSUE TITLE
Cannot login with the Android APP

### ISSUE THREAD

**Issue by CarlosSanchiz** [owncloud/core#14456] opened 2015-02-24 11:19 UTC
I cannot login to owncloud with the Android APP

If I change the password to a non complex one: (1234567) it works but if I use a corporate password it fails.

**Comment by PVince81** [comment] 2015-02-24 13:03
Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

If the password contains special characters (for example letters with accents), then this is a duplicate of https://github.com/owncloud/core/issues/7894

**Comment by CarlosSanchiz** [comment] 2015-02-24 14:15
### Steps to reproduce

1. Just create a user with a complex password, with spaces and symbols.

2.

3.

 

### Expected behaviour

Login....

 

### Actual behaviour

The user is not able to login.

 

### Server configuration

**Operating system**:

Red Hat Enterprise Linux Server release 6.6 (Santiago)

 

**Web server:**

Server version: Apache/2.2.15 (Unix)

Server built:   Aug 15 2014 03:02:07

 

**Database:**

Server version: 5.1.73 Source distribution

**PHP version:**

PHP 5.4.16 (cli) (built: Nov 19 2014 10:21:23) 

Copyright (c) 1997-2013 The PHP Group

Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

 

**ownCloud version:** (see ownCloud admin page)

8.0 

**Updated from an older ownCloud or fresh install:**

Updated from 7.0.4

 

**List of activated apps:**

Files, Activity, Pictures, Contacts

 

**The content of config/config.php:**

 

[root@tel-share-01 config]# cat config.php 

<?php

$CONFIG = array (

  'instanceid' => 'occe5165f7cf',

  'trusted_domains' => 

  array (

    0 => 'share.aquanima.com',

  ),

  'datadirectory' => '/ownCloud-Data',

  'overwrite.cli.url' => 'https://share.aquanima.com',

  'dbtype' => 'mysql',

  'version' => '8.0.0.7',

  'dbname' => 'owncloud',

  'dbhost' => 'localhost',

  'dbtableprefix' => 'oc_',

  'dbuser' => 'owncloud',

  'installed' => true,

  'forcessl' => true,

  'mail_smtpmode' => 'smtp',

  'mail_from_address' => 'owncloud',

  'mail_domain' => 'aquanima.com',

  'mail_smtphost' => '10.100.10.210',

  'mail_smtpport' => '25',

  'proxy' => '10.100.11.32:8080',

  'ldapIgnoreNamingRules' => false,

  'preview_libreoffice_path' => '/usr/bin/libreoffice4.4',

  'enabledPreviewProviders' => 

  array (

    0 => 'OC\\Preview\\Image',

    1 => 'OC\\Preview\\MP3',

    2 => 'OC\\Preview\\TXT',

    3 => 'OC\\Preview\\MarkDown',

  ),

  'theme' => 'aquanima',

  'maintenance' => false,

  'loglevel' => '0',

);

 

**Are you using external storage, if yes which one:** local/smb/sftp/...

Local

 

**Are you using encryption:** yes/no

No

 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

 

#### LDAP configuration (delete this part if not used)

LDAP://tel-dc-01.aquanima.corp

CN=LDAP,CN=Users,DC=aquanima,DC=corp

```

run: sqlite3 data/owncloud.db

then execute:  select * from oc_appconfig where appid='user_ldap';

 

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```

 

### Client configuration

**Browser:**

It is a Android APP

 

**Operating system:**

5.0.2

 

### Logs

#### Web server error log

```

Insert your webserver log here

```

 

#### ownCloud log (data/owncloud.log)

```

Insert your ownCloud log here

```

 

#### Browser log

```

Insert your browser log here, this could for example include:

 

a) The javascript console log

b) The network log 

c) ...

```

**Comment by karlitschek** [comment] 2015-02-24 15:00
Can you post A password that doens´t work? Doesn´t have to be your real one but we need a bit more details than _complex_  thanks

**Comment by CarlosSanchiz** [comment] 2015-02-24 15:04
“3sto es una P@wd c0mPlex”

**Comment by karlitschek** [comment] 2015-02-24 15:06
@LukasReschke What do you think?

**Comment by LukasReschke** [comment] 2015-02-24 15:14
That is interesting, `3sto es una P@wd c0mPlex` should work as it contains only ASCII characters and thus evaluates to the same string when base64 encoding this independent whether UTF-8 or ASCII encoding is used.

To debug this more properly we need some more troubleshooting steps:

1. Are you sure your password does not contain non-ascii characters? (for example éàäö etc…)
2. If you authenticate with your browser at domain.tld/remote.php/webdav does the login work? (with complex and without  complex password?)
3. Can you create a user at demo.owncloud.org with a complex password and then try to login to that account with your Android app? Does that work?
4. Is by any chance the user with strong password using LDAP and the other one a locally stored ownCloud user? – Then this could be a red herring and you could try if https://github.com/owncloud/core/pull/14423 fixes the problem.

Thanks for testing!

**Comment by blizzz** [comment] 2015-07-31 20:52
@CarlosSanchiz does the issue still exist for you?

**Comment by CarlosSanchiz** [comment] 2015-08-01 07:06
Hi

I have move to iphone and didnt test it

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, Jul 31, 2015 at 1:52 PM -0700, "blizzz" <notifications@github.com<mailto:notifications@github.com>> wrote:


@CarlosSanchiz<https://github.com/CarlosSanchiz> does the issue still exist for you?

-
Reply to this email directly or view it on GitHub<https://github.com/owncloud/core/issues/14456#issuecomment-126809712>.

************************************DISCLAIMER************************************
This message is private and confidential and it is intended exclusively for the addressee. If you receive this message by mistake, you should not disseminate, distribute or copy this e-mail. Please inform the sender and delete the message and attachments from your system. No confidentiality nor any privilege regarding the information is waived or lost by any mistransmission or malfunction. Any views or opinions contained in this message are solely those of the author, and do not necessarily represent those of Aquanima, unless otherwise specifically stated and the sender is authorized to do so. E-mail transmission cannot be guaranteed to be secure, confidential, or error-free, as information could be intercepted, corrupted, lost, destroyed, arrive late, incomplete, or contain viruses. Aquanima does not accept responsibility for any changes in the contents of this message after it has been sent.

************************************AVISO LEGAL************************************
Este mensaje es privado y confidencial y solamente para la persona a la que va dirigido. Si usted ha recibido este mensaje por error, no debe revelar, copiar, distribuir o usarlo en ningún sentido. Le rogamos lo comunique al remitente y borre dicho mensaje y cualquier documento adjunto que pudiera contener. No hay renuncia a la confidencialidad ni a ningún privilegio por causa de transmisión errónea o mal funcionamiento. Cualquier opinión expresada en este mensaje pertenece únicamente al autor remitente, y no representa necesariamente la opinión de Aquanima, a no ser que expresamente se diga y el remitente esté autorizado para hacerlo. Los correos electrónicos no son seguros, no garantizan la confidencialidad ni la correcta recepción de los mismos, dado que pueden ser interceptados, manipulados, destruidos, llegar con demora, incompletos, o con virus. Aquanima no se hace responsable de las alteraciones que pudieran hacerse al mensaje una vez enviado.

**Comment by blizzz** [comment] 2015-08-03 09:55
OK, I close it as not reproducible. If someone sees this as well and can provide information, please reopen.

**Closed by blizzz** 2015-08-03 09:55 UTC
Labels: bug - not reproducible, needs info
