### ISSUE TITLE
space in the directory name

### ISSUE THREAD

**Issue by ddeenniiss** [owncloud/core#22845] opened 2016-03-04 09:10 UTC
Hi,

Windows seems to refuse the spaces at the end of a directory, considering them invalid.

If a directory is created on Mac or Linux, they will not be synchronized on Windows machines.

**Comment by aspdye** [comment] 2016-03-04 09:19
Please keep in mind our Contributing and Issue Submitting Guidelines according to: 
https://github.com/owncloud/core/blob/master/CONTRIBTING.md ;)

**Comment by LukasReschke** [comment] 2016-03-04 10:02
Dupe of https://github.com/owncloud/core/issues/22534

**Closed by LukasReschke** 2016-03-04 10:02 UTC
