### ISSUE TITLE
Spinner in sharing operation has a white background (not transparent)

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#22788] opened 2016-03-02 17:02 UTC
### Steps to reproduce

1. Share a file from user1 to user2 using the sidebar dropdown.

### Expected behaviour
spinner with transparent background.

### Actual behaviour
Not transparent background:
![sharing_spinner](https://cloud.githubusercontent.com/assets/9048796/13467870/700be2c0-e0a0-11e5-8c16-1776d441782b.gif)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.0.16","versionstring":"9.0.0 RC1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**
Chrome

**Comment by MorrisJobke** [comment] 2016-03-02 21:25
Nothing we could fix in the graphics - we need to switch to a CSS only spinner - duplicate of https://github.com/owncloud/core/issues/19091

**Closed by MorrisJobke** 2016-03-02 21:25 UTC
Labels: bug, design, sev4-low
