### ISSUE TITLE
"Could not get node for path"

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#30841] opened 2018-03-20 12:40 UTC
### Steps to reproduce
1. setup ownCloud (tested with 10.0.4 and 10.0.7) 
2. login and delete the manual pdf
3. look in owncloud.log

### Expected behaviour
The log should be clean of errors

### Actual behaviour
An error occurs:

10.0.7:

```
"level":2,

"time":"2018-03-20T12:28:41+00:00",

"remoteAddr":"172.42.16.215",

"user":"admin",

"app":"dav",

"method":"DELETE",

"url":"\/remote.php\/webdav\/ownCloud%20Manual.pdf",

"message":"Could not get node for path: \"ownCloud Manual.pdf\" : 

File with name ownCloud Manual.pdf could not be located"

```

10.0.4

```
"level":2,
"time":"2018-03-20T12:23:14+00:00",
"remoteAddr":"172.42.16.215",
"user":"admin","app":"dav",
"method":"DELETE",
"url":"\/remote.php\/webdav\/ownCloud%20Manual.pdf",
"message":"Could not get node for path: \"ownCloud Manual.pdf\" : {$message}"}

```

### Server configuration
**Operating system**: docker / ubuntu

**Web server:** apache2

**Database:** mariadb

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page)
10.0.4 / 10.0.7
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
owncloud.org

**The content of config/config.php:**

```
root@owncloud:/# cat /var/www/owncloud/config/config.php
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '172.42.16.186',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '10.0.7.2',
  'dbname' => 'owncloud',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

**Comment by phil-davis** [comment] 2018-03-20 12:46
Like issue #30762 ?

**Comment by ownclouders** [comment] 2018-03-20 12:48
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22180 (Could not get node for path), https://github.com/owncloud/core/issues/30762 ('Could not get node for path' messages in log file when deleting a file/folder), https://github.com/owncloud/core/issues/7699 (Upload failed. Could not get file info.), https://github.com/owncloud/core/issues/6508 (OC\Files\Cache\Scanner gets wrong path), and https://github.com/owncloud/core/issues/23117 (GET / not working).

**Comment by PVince81** [comment] 2018-03-26 07:07
closing as duplicate of https://github.com/owncloud/core/issues/30762

**Closed by PVince81** 2018-03-26 07:07 UTC
Labels: bug, server
