### ISSUE TITLE
Syncing 1GB file from Dropbox to the desktop crashes Apache and the server.  Restart forced.

### ISSUE THREAD

**Issue by hnaparst** [owncloud/core#23598] opened 2016-03-26 22:34 UTC
### Steps to reproduce
1.   Install Owncloud 9.0.
2.   Link to Dropbox
3.   Attempt to sync a 1GB file.

### Expected behaviour
File should sync to the desktop

### Actual behaviour
First Apache runs out of memory, then the server crashes.  Any ssh sessions become unresponsive.

### Server configuration
Linux foobar 4.1.15-gentoo-r1 #2 SMP Fri Feb 19 07:59:35 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

**Web server:**
Apache 2.4.18

**Database:**
Mariadb 10.0.23

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
Gentoo repository

**Signing status (ownCloud 9.0 and above):**
Wot?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 5e26947c6350e499cad559198879ee054acb0bb1dc244d02655c9f6d824276ac52c15ff913490ed670b1216ce012b3bdf8307a88b16e0da009fa0641261378d9
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => f5f88f2834b032e504c3447bcd7aafb4611895d4e43cb5795e56696c1e525e68535888ded947322f5520ae973484aa740f27f173a7a260176f62dd7d59e6ac90
                        )

                )

        )

)
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
foobar owncloud # 

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocFoxNewsRocksmg',
  'passwordsalt' => 'BMMegynKellyIsAWitchcGJSMmW',
  'secret' => '2B84juDonaldTrumpListensToHimselfMostlyLlj+iW1jjq+LXn',
  'trusted_domains' => 
  array (
    0 => 'owncloud.ilovechdeapdomains.com',
  ),
  'datadirectory' => '/var/ocdata',
  'overwrite.cli.url' => 'https://owncloud.ilovecheapdomains.com',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'ocdb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin3',
  'dbpassword' => 'MargaretThatcheris110%sexy',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'ilovecheapdomains.com',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "ocFoxNewsRocksmg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.ilovecheapdomains.com"
        ],
        "datadirectory": "\/var\/ocdata",
        "overwrite.cli.url": "https:\/\/owncloud.ilovecheapdomains.com",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "ilovecheapdomains.com"
    }
}
or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                                  

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
Google Chrome

**Operating system:**
Linux amarkin 4.5.0-ck #1 SMP PREEMPT Fri Mar 25 08:08:32 UTC 2016 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux

#### Web server error log
```
[Sat Mar 26 06:54:47.143392 2016] [core:error] [pid 14236] [client xxx.xxx.xxx.xxxx:47741] AH00126: Invalid URI in request \xbc\xb9\xac\xbcCFSCsYyy\xa8\xab\x0e\xc2~&\x9a\xc6\x90W\xf1\x95S4S0\xcc\xb1"\xa3\x1\
0\xe4\xa0\x17\xae\b\x90\xa9\x0c\x818\xd6`\xce\xb9<\xbc-Z

[Sat Mar 26 14:29:27.870928 2016] [:error] [pid 9499] [client xxx.xxx.xxx.xxx:42132] PHP Fatal error:  \
Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368760 bytes) in /var/www/localhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112                 
[Sat Mar 26 14:29:45.541590 2016] [:error] [pid 14236] [client xxx.xxx.xxx.xxx:42362] PHP Fatal error: \
 Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368768 bytes) in /var/www/localhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112                
[Sat Mar 26 14:33:28.933001 2016] [:error] [pid 23966] [client xxx.xxx.xxx.xxx:42364] PHP Fatal error: \
 Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368760 bytes) in /var/www/localhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112                
[Sat Mar 26 14:33:40.288881 2016] [:error] [pid 14532] [client xxxx.xxx.xxx.xxx:42366] PHP Fatal error: \
 Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368768 bytes) in /var/www/loc\
alhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112                
[Sat Mar 26 14:51:26.452978 2016] [:error] [pid 1202] [client xxx.xxx.xxx.xxx:43072] PHP Fatal error:  \
Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368760 bytes) in /var/www/localhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112                 
[Sat Mar 26 14:51:37.049141 2016] [:error] [pid 1203] [client xxx.xxx.xxxx.xxx:43074] PHP Fatal error:  \
Allowed memory size of 536870912 bytes exhausted (tried to allocate 531368768 bytes) in /var/www/localhost/htdocs/owncloud/apps/files_external/3rdparty/Dropbox/OAuth/Curl.php on line 112 
Insert your webserver log here

```xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:49:33 -0700] "GET /remote.php/webdav/Dropbox/Gentoo/Gentoo.zip\
 HTTP/1.1" 500 -
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:01 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 417
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:07 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 374
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:29 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 373
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:31 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 417
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:31 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2593
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:32 -0700] "PROPFIND /remote.php/webdav/Dropbox HTTP/1.1" 20\
7 45438
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:33 -0700] "PROPFIND /remote.php/webdav/Dropbox/Gentoo HTTP/\
1.1" 207 8960
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:33 -0700] "PROPFIND /remote.php/webdav/Dropbox/Keepass HTTP\
/1.1" 207 2698
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:59 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2593
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:52:59 -0700] "PROPFIND /remote.php/webdav/Dropbox HTTP/1.1" 20\
7 45438
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:01 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 417
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:01 -0700] "PROPFIND /remote.php/webdav/Dropbox/Keepass HTTP\
/1.1" 207 2698
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:04 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2593
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:04 -0700] "PROPFIND /remote.php/webdav/Dropbox HTTP/1.1" 20\
7 45438
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:06 -0700] "PROPFIND /remote.php/webdav/Dropbox/Keepass HTTP\
/1.1" 207 2698
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:31 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 417
xxx.xxx.xxx.xxx - hclinton [26/Mar/2016:14:53:43 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 374


#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
http://bit.ly/1UTDy8D

#### Browser log
Not applicable.  The error occurs using the desktop client version 2.1.1 to sync.

**Comment by Xenopathic** [comment] 2016-03-26 22:42
Duplicate of #4040, it has been fixed in 9.1 with #23272, Dropbox will now use streaming instead of copying the whole file into memory.

If the memory situation is managing to crash your entire server however, then you need to put better limits on your processes. Your init system can leverage cgroups to limit the overall memory available to Apache, preventing the system from being starved of RAM.

**Closed by Xenopathic** 2016-03-26 22:42 UTC

**Comment by hnaparst** [comment] 2016-03-26 22:45
Can I get access to 9.1 or the git sources to verify that the issue is fixed, please?

**Comment by Xenopathic** [comment] 2016-03-26 23:02
9.1 is the next version that will be released (so isn't finished yet), the current git sources are available here.

**Comment by hnaparst** [comment] 2016-03-26 23:07
Do you mean 9.0.1, or 9.1?  I only see 9.0.1beta as the latest tag.

**Comment by Xenopathic** [comment] 2016-03-26 23:10
...because it isn't finished yet. If you really want to use the code (at your own risk) use git master.

**Comment by hnaparst** [comment] 2016-03-26 23:46
Instead of cgroups, I just put the line 

> RLimitMEM 256000000 512000000

in httpd.conf.    This resulted in the directory containing the large files syncing, but without the large files.    The desktop client even shows a green checkmark.  The client tries repeatedly to sync the large files without success.  But at least the server doesn't crash.

**Comment by hnaparst** [comment] 2016-03-27 17:26
With today's git snapshot, the files still do not sync, but the software in general seems to be behaving better than 9.0.0.   The messages in the log are as follows, with the last message generated immediately before the desktop client gives a message saying it couldn't sync the particular large file:

{"reqId":"VvgVGX8AAAEAAAtlAyMAAAAB","remoteAddr":"xxx.xxx.xxx.xxx","app":"files_external","message":"cURL error 23: Failed writing body (1225 != 16384)","level":3,"time":"2016-03-27T17:21:10+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/{"reqId":"VvgWg38AAAEAAAupL9MAAAAI","remoteAddr":"73.240.233.16","app":"files_external","message":"cURL error 23: Failed writing body (1225 != 16384)","level":3,"time":"2016-03-27T17:21:10+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.vdi.xz","user":"harold"}
{"reqId":"VvgWg38AAAEAAAupL9MAAAAI","remoteAddr":"7xxx.xxx.xxx.xxx","app":"PHP","message":"fread() expects parameter 1 to be resource, boolean given at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#823","level":3,"time":"2016-03-27T17:21:10+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.vdi.xz","user":"harold"}
{"reqId":"VvgWg38AAAEAAAupL9MAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/files\/storage\/wrapper\/encryption.php#824","level":3,"time":"2016-03-27T17:21:10+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.vdi.xz","user":"harold"}
{"reqId":"VvgWkn8AAAEAABvRgbAAAAAJ","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/log\/owncloud.php#155","level":3,"time":"2016-03-27T17:21:22+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"harold"}
{"reqId":"VvgWmX8AAAEAAB22g-MAAAAL","remoteAddr":"73.240.233.16","app":"PHP","message":"Trying to get property of non-object at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/log\/owncloud.php#155","level":3,"time":"2016-03-27T17:21:29+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"harold"}
{"reqId":"VvgWg38AAAEAAAupL9MAAAAI","remoteAddr":"xxx.xxx.xxx.xxx","app":"files_external","message":"cURL error 23: Failed writing body (1225 != 16384)","level":3,"time":"2016-03-27T17:22:36+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.vdi.xz","user":"harold"}
{"reqId":"VvgWg38AAAEAABqq76cAAAAG","remoteAddr":"xxx.xxx.xxx.xxx","app":"files_external","message":"cURL error 23: Failed writing body (1217 != 16384)","level":3,"time":"2016-03-27T17:22:36+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.zip","user":"harold"}
{"reqId":"VvgVGX8AAAEAAAujQjQAAAAF","remoteAddr":"xxx.xxx.xxx.xxx","app":"files_external","message":"cURL error 23: Failed writing body (13505 != 16384)","level":3,"time":"2016-03-27T17:22:36+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Gentoo\/Gentoo.zip","user":"harold"}
{"reqId":"VvgWg38AAAEAABqq76cAAAAG","remoteAddr":"xxx.xxx.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/localh...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":306,\"User\":\"harold\"}","level":4

**Comment by RealRancor** [comment] 2016-03-27 18:53
@hnaparst I think for such stuff its better to create a new issue providing more info. Especially as "master" is a work in progress / still in development.

**Comment by hnaparst** [comment] 2016-03-27 19:47
I will do that if it would be helpful for you.  I thought that filing bugs reports on the git tree would not be appreciated.

**Comment by RealRancor** [comment] 2016-03-27 22:08
I would say go for a new report as testing for new features during the development is always helping to test a new functionality before it is released as a final.

**Comment by hnaparst** [comment] 2016-03-29 14:32
I feel more comfortable waiting for the developers to commit some code where they claim to stream large files from Dropbox.   Filing a bug report on a feature that hasn't even been committed seems premature in my humble opinion.  Especially when that bug already exists and has been marked as extremely serious.
