### ISSUE TITLE
Array to string conversion at :

### ISSUE THREAD

**Issue by raykai** [owncloud/core#20971] opened 2015-12-06 09:59 UTC
im using serverpilot  with digitalocean ubuntu Droplet. 
https://serverpilot.io
https://www.digitalocean.com

when uploading im getting a error on files bigger then 200 MB

"PHP","message":"Array to string conversion at /owncloud\/lib\/private\/template\/functions.php#36","level":3

more ppl with same bug :https://forum.owncloud.org/viewtopic.php?f=36&t=31808&p=102783#p102783

php max file size is 1gb

**Comment by RealRancor** [comment] 2015-12-06 11:36
Please fill out the issue template as asked in https://github.com/owncloud/core/blob/master/CONTRIBUTING.md#short-version (Thats linked in the yellow box when creating a new issue).

Up to know its even unclear which version of oC you're using.

**Comment by raykai** [comment] 2015-12-07 00:22
### Steps to reproduce
1. upload a file of 200 + MB in size


### Expected behaviour
Tell us what should happen

The file should upload and be displayed in the list of files.

### Actual behaviour
Tell us what happens instead

the file  starts uploading to about 1/4th % of it then it restarts form 0% looping the upload after doing this about 4-5 times it stops uploading and gives a error a yellow box appear to the top of the page but no text in it. 

### Server configuration
**Operating system**:
Ubuntu Server 14.04 LTS
**Web server:**
Apache (serverpilot) https://serverpilot.io/
**Database:**
MySQL (serverpilot) https://serverpilot.io/
**PHP version:**
PHP 5.6 all so tried 7.0
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.1 (stable)
**Updated from an older ownCloud or fresh install:**
fresh install
**List of activated apps:**
Only the default apps are activated

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocj5us68y9o3',
  'passwordsalt' => 'zQ9Wpe5lk7RBD5PJmQ2kQ9lydT6lYY',
  'secret' => 'TrqYcUe4CnMkPVjc9W4L7/lbV545GfKZ7P0oVnF7X6FhhKNG',
  'trusted_domains' => 
  array (
    0 => 'www.raykai.tk',
  ),
  'datadirectory' => '/srv/users/serverpilot/apps/raykai/public/owncloud/data',
  'overwrite.cli.url' => 'http://www.raykai.tk/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'PRIVET',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'PRIVET',
  'dbpassword' => 'BgvyrMGadK2pQqYqQvHxdScF0s7WzY',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
 Chrome, Firefox, Edge, Internet Explorer 11
**Operating system:**
Windows 10
### Logs
#### Web server error log
```
Insert your webserver log here
```
no error there
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here

{"reqId":"H4cRlZYefAn0XzdMrPdH","remoteAddr":"216.246.250.202","app":"PHP","message":"touch(): Unable to create file \/srv\/users\/serverpilot\/apps\/raykai\/public\/owncloud\/data\/owncloud.log because No such file or directory at \/srv\/users\/serverpilot\/apps\/raykai\/public\/owncloud\/lib\/private\/log\/owncloud.php#53","level":3,"time":"2015-12-07T00:12:52+00:00"}
{"reqId":"aHf8zGYNvH7j85nOAsAf","remoteAddr":"216.246.250.202","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_raykai\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user '887bc7482f73'@'localhost' for table 'user'","level":3,"time":"2015-12-07T00:14:01+00:00"}
{"reqId":"aHf8zGYNvH7j85nOAsAf","remoteAddr":"216.246.250.202","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `raykai-tk_owncloud` . * TO '887bc7482f73'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user '887bc7482f73'@'%' to database 'raykai-tk_owncloud'","level":3,"time":"2015-12-07T00:14:01+00:00"}
{"reqId":"aHf8zGYNvH7j85nOAsAf","remoteAddr":"216.246.250.202","app":"PHP","message":"Undefined offset: 0 at \/srv\/users\/serverpilot\/apps\/raykai\/public\/owncloud\/lib\/private\/setup\/mysql.php#45","level":3,"time":"2015-12-07T00:14:01+00:00"}
```
#### Browser log
```
Insert your browser log here, this could for example include:

a) inspect element console
Failed to load resource: net::ERR_CONNECTION_RESET /owncloud/index.php/apps/files/ajax/upload.php

```

**Comment by ele0s** [comment] 2015-12-07 05:56
I hope that you will change quickly your passwordsalt, secret, and DB password... now that they are available on internet

**Comment by raykai** [comment] 2015-12-07 07:27
that was a test install i removed it and reinstalled with other pass and DB 
but im still having the same prob with serverpilot

**Comment by PVince81** [comment] 2015-12-07 14:11
Possible duplicate of https://github.com/owncloud/core/issues/17468

**Comment by PVince81** [comment] 2016-03-01 15:54
Closing as duplicate

**Closed by PVince81** 2016-03-01 15:54 UTC
Labels: bug, needs info
