### ISSUE TITLE
Owncloud 9.0.0 not working after upgrade

### ISSUE THREAD

**Issue by moi90** [owncloud/core#23596] opened 2016-03-26 21:04 UTC
### Steps to reproduce
1. Log in. Seems to fail. The same login page is displayed again, but without notice that something went wrong. No error in server or owncloud log.
2. Go to index.php/apps/files/. A blank page appears. owncloud.log says:

        {"reqId":"8\/4cKKNbefy\/M7jPlOKC","remoteAddr":"86.103.221.68","app":"PHP","message":"Call to undefined method OC\\Security\\CSP\\ContentSecurityPolicy::set() at \/var\/www\/movi\/htdocs\/owncloud\/lib\/private\/security\/csp\/contentsecuritypolicymanager.php#67","level":3,"time":"2016-03-26T20:20:05+00:00"}

### Expected behaviour
Login works and files are visible.

### Actual behaviour
See above.

### Server configuration
**Operating system**: Ubuntu 14.04.4 LTS

**Web server:** nginx version: nginx/1.4.6 (Ubuntu)

**Database:** mysqld  Ver 5.6.28-0ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))

**PHP version:** HipHop VM 3.12.0 (rel)
Compiler: tags/HHVM-3.12.0-0-g440e6a096b2db8a449b9690a72f2f1792530e86a
Repo schema: 033b8dedf4af99b892f2488b103a8d67a58ff816

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** 8.1.3 -> 8.1.6 -> 8.2.3 -> 9.0.0

**Where did you install ownCloud from:** tar.bz2

**Signing status (ownCloud 9.0 and above):**

index.php/settings/integrity/failed  is a blank page.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - firstrunwizard
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "octq9k1msqq8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "movi2.nerdluecht.de",
            "movi.nerdluecht.de"
        ],
        "datadirectory": "\/var\/www\/movi\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/movi.nerdluecht.de\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45.0

**Operating system:** Ubuntu 14.04.4 LTS

#### ownCloud log (data/owncloud.log)
```
{"reqId":"8\/4cKKNbefy\/M7jPlOKC","remoteAddr":"86.103.221.68","app":"PHP","message":"Call to undefined method OC\\Security\\CSP\\ContentSecurityPolicy::set() at \/var\/www\/movi\/htdocs\/owncloud\/lib\/private\/security\/csp\/contentsecuritypolicymanager.php#67","level":3,"time":"2016-03-26T20:20:05+00:00"}
```

**Comment by RealRancor** [comment] 2016-03-26 22:11
Hi,

> HipHop VM 3.12.0 (rel)

ownCloud is unsupported on HHVM according to https://github.com/owncloud/core/issues/22631#issuecomment-188312929

**Comment by Xenopathic** [comment] 2016-03-26 22:17
https://github.com/owncloud/core/blob/master/lib/private/security/csp/contentsecuritypolicymanager.php#L60

Holy mother of god that's a magical hacky line of code... Probably why it breaks on HHVM too (which sometimes misses on the fine print of the, frankly ludicrous at times, PHP specification). Specifically the bit about converting objects to arrays. @LukasReschke :see_no_evil: :see_no_evil: :see_no_evil: :see_no_evil:

**Comment by moi90** [comment] 2016-03-29 10:02
Are there intentions to support HHVM in the future? Owncloud is quite a complex software that needs much time to execute on a small virtual server.

**Comment by LukasReschke** [comment] 2016-03-29 11:49
Dupe of https://github.com/owncloud/core/issues/10837 then due to not compliance with HHVM.

> Are there intentions to support HHVM in the future?

Same as in https://github.com/owncloud/core/issues/10837#issuecomment-170383880 applies :-)

**Closed by LukasReschke** 2016-03-29 11:49 UTC
Labels: bug, sev3-medium
