### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by interbiznw** [owncloud/core#26471] opened 2016-10-25 07:13 UTC
Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for activity can be updated (this can take a long time depending on the database size)
Checking whether the database schema for files_sharing can be updated (this can take a long time depending on the database size)
Checking whether the database schema for files_trashbin can be updated (this can take a long time depending on the database size)
Checking whether the database schema for notifications can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Updated "files_pdfviewer" to 0.8.1
Updated "files_texteditor" to 2.1
Updated "gallery" to 14.5.0
Updated "files" to 1.4.4
Updated "activity" to 2.2.1
Updated "files_sharing" to 0.9.1
Updated "files_trashbin" to 0.8.0
Updated "files_versions" to 1.2.0
Updated "notifications" to 0.2.3
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by DeepDiver1975** [comment] 2016-10-25 09:01
Update from which version to which version?
Database?

**Comment by RealRancor** [comment] 2016-10-25 11:28
Duplicate of https://github.com/owncloud/core/issues/23988 ?

**Closed** 2016-12-06 17:44 UTC
Labels: needs info
