### ISSUE TITLE
Problem with Email Notification about activity

### ISSUE THREAD

**Issue by Naucum** [owncloud/core#13244] opened 2015-01-10 15:29 UTC
Hello, hope you can give me a hint were to look or which info do you need to resolve my problem!

Case: Update from 7.0.3 to 7.0.4
Issue: After update when i get notification about activity instead of the edited things i get
*Array

Example:
--------------------------------------------------------------------
Estimado/a David :

Está recibiendo este mensaje porque durante el
último día han pasado las siguientes cosas en
http://mydomain/owncloud/

* Array
* Array

--
Expertos en Software de Gestion para Hosteleria
-----------------------------------------------------------------------
Array stays for every change/activity which were done. 1 Array for every activity done

I proceeded like in documentation how to make update (or so i think i did)

Configuration:
Windows 7 Ultimate x64
MySQL 5.6
MySQL Workbench 6.0
PHP 5.3
My files are outside owncloud folder
IIS 7.5

The php files which are edited to give owncloud a more personal touch are:
config.php
layout.guest.php
htaccess.php 
defaults.php

I would highly appreciate any help because all other things are working well as before. To be honest and due to the fact that i m not expert or programmer i dont exclude the option that i forget to backup an important php file to copy back into new folder when setting up 7.0.4. So any kind of help or hint will be welcome!

Thx a lot in advance

**Comment by karlitschek** [comment] 2015-01-10 15:33
@nickvergessen can you please have alook?

**Comment by nickvergessen** [comment] 2015-01-12 13:42
Works on master:
```
* Usted ha eliminado ltversion.m4 - Hoy, 14:30:11
* Usted ha eliminado welcomefu.txt - Hoy, 14:30:14
```

will check stable7 soon

**Comment by Naucum** [comment] 2015-01-12 13:45
Thx for info!!

**Comment by nickvergessen** [comment] 2015-01-12 13:57
> Estimado/a NickV7:
>
> Está recibiendo este mensaje porque durante la
última hora han pasado las siguientes cosas en
>http://localhost/ownCloud/Stable7/
>
>* Usted ha eliminado welcome.txt - Hoy 13:51:31


works on stable7 aswell. The language you selected is Castellano right?

My current advice would be to ensure to reupload the files of the activity app, and otherwise see whether it was fixed somehow in 7.0.5 which should be coming soon.

//Closing since I can't reproduce

**Comment by Naucum** [comment] 2015-01-12 14:02
Hello....thank for info and test.

a question: when u say : "reupload the files of the activity app" do u mean to online download the folder app in \inetpub\wwwroot\owncloud and copy it to same place  to test it if resolves the problem?

thx you

**Comment by nickvergessen** [comment] 2015-01-12 14:10
No, I mean download a fresh copy from owncloud.org unzip it and just upload apps/activity to your server again

**Comment by Naucum** [comment] 2015-01-12 14:16
thx nickvergessen...i will try this..do you need info about this after test?

**Comment by Naucum** [comment] 2015-01-12 16:54
Did not solved the problem. Is there any other way to find out where the problem is? I already tried in owncloud forum but no answers since my post from 8 of january.

**Comment by nickvergessen** [comment] 2015-01-12 16:56
Can you try switching the language to english? So we know it's a problem of the language or something else.

**Comment by Naucum** [comment] 2015-01-12 16:58
on th way..result in 1 hour

**Comment by Naucum** [comment] 2015-01-12 18:21
Same result...not a lang issue :(

**Comment by nickvergessen** [comment] 2015-01-12 18:33
Hmm, are you using a custom template/style/theme or did you modify the email template in the administration section or somewhere else manually?

**Comment by nickvergessen** [comment] 2015-01-12 18:37
Because that is the only way I can see this happening:
Your template file (`apps/activity/template/email.notification.php`) is missing the following change:
https://github.com/owncloud/activity/commit/5fc335419202d506306be5371b0c227474378ac7#diff-1

Can you check, whether your file contains:
```php
print_unescaped($l->t('* %1$s - %2$s', $activityData));
```
or
```php
print_unescaped($l->t('* %s', array($activity)));

**Comment by Naucum** [comment] 2015-01-12 18:42
1.No, in fact let it one time with
![1](https://cloud.githubusercontent.com/assets/8770484/5708579/af44ff76-9a92-11e4-8015-3f2bc23b8f86.jpg)
and second time with
![2](https://cloud.githubusercontent.com/assets/8770484/5708584/b6b30424-9a92-11e4-9d7c-993d177a5060.jpg)
and pushed save.
In both cases with same result.
2. complete email.notification.php
<?php
/** @var OC_L10N $l */
/** @var array $_ */
$l = $_['overwriteL10N'];

print_unescaped($l->t('Hello %s,', array($_['username'])));
p("\n");
p("\n");

if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_HOURLY) {
	p($l->t('You are receiving this email because in the last hour the following things happened at %s', array($_['owncloud_installation'])));
} else if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_DAILY) {
	p($l->t('You are receiving this email because in the last day the following things happened at %s', array($_['owncloud_installation'])));
} else {
	p($l->t('You are receiving this email because in the last week the following things happened at %s', array($_['owncloud_installation'])));
}
p("\n");
p("\n");

foreach ($_['activities'] as $activityData) {
	print_unescaped($l->t('* %1$s - %2$s', $activityData));
	p("\n");
}
p("\n");

**Comment by Naucum** [comment] 2015-01-12 18:45
BTW...the email notification after changing interface lang is still in spanish. i changed the lang in personal settings. is this correcto?

**Comment by nickvergessen** [comment] 2015-01-12 18:58
Can you change the line to

```php
print_unescaped('issue ' . $l->t('* 13244 %1$s - %2$s', $activityData));
```
As a debugging step?

**Comment by Naucum** [comment] 2015-01-12 19:13
ok...trying....

**Comment by Naucum** [comment] 2015-01-12 19:19
1. copied email.notification.php to another place
2. changed the file as proposed in the original file
3. uploaded files to get activity notification
4. waiting for mail

**Comment by Naucum** [comment] 2015-01-12 20:26
unfortunately the same....

* Array
* Array
* Array

**Comment by nickvergessen** [comment] 2015-01-12 23:05
okay, last try:
```php
print_unescaped('DEBUG#' . serialize($activityData));
```

**Comment by Naucum** [comment] 2015-01-13 11:34
changed at 9am...no mail since then

**Comment by Naucum** [comment] 2015-01-13 11:43
i will do another test....curiosly....on admin site it said.....
Error	Activity	A problem occurred while sending the e-mail. Please revisit your settings.	2015-01-13T08:29:48+00:00
Error	mail	SMTP Error: Could not connect to SMTP host.	2015-01-13T08:29:48+00:00
Error	PHP	stream_socket_enable_crypto(): SSL: crypto enabling timeout at C:\inetpub\wwwroot\owncloud\3rdparty\phpmailer\phpmailer\class.smtp.php#273	2015-01-13T08:29:48+00:00

but when i use "Send message" the test mail message arrives correct. 

i upload now again files

**Comment by nickvergessen** [comment] 2015-01-13 11:57
To increase the email speed you can do the following two changes:
1. Update the `notify_setting_batchtime` value from `3600` to `1` in the oc_preferences database table for your user
2. in `apps/activity/lib/backgroundjob/emailnotification.php` change
```php
$this->setInterval(15 * 60);
```
to
```php
$this->setInterval(1);
```

however, don't forget to change this back, since it increases the load on your server and might even get you spam listed at some point.

**Comment by Naucum** [comment] 2015-01-13 12:47
Thanks for this hint....i was handling another thing  to close 2014 ;)

No changes in the text..but email arrived!! Seems to be there is no hope for my case....

**Comment by nickvergessen** [comment] 2015-01-13 14:15
```php
print_unescaped('DEBUG#' . serialize($activityData));
```
this still outputs `* Array` ?

**Comment by Naucum** [comment] 2015-01-13 14:17
yes..i checked again...here the complete source code

<?php
/** @var OC_L10N $l */
/** @var array $_ */
$l = $_['overwriteL10N'];

print_unescaped($l->t('Hello %s,', array($_['username'])));
p("\n");
p("\n");

if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_HOURLY) {
	p($l->t('You are receiving this email because in the last hour the following things happened at %s', array($_['owncloud_installation'])));
} else if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_DAILY) {
	p($l->t('You are receiving this email because in the last day the following things happened at %s', array($_['owncloud_installation'])));
} else {
	p($l->t('You are receiving this email because in the last week the following things happened at %s', array($_['owncloud_installation'])));
}
p("\n");
p("\n");

foreach ($_['activities'] as $activityData) {
	print_unescaped('DEBUG#' . serialize($activityData));
	p("\n");
}
p("\n");

**Comment by nickvergessen** [comment] 2015-01-13 15:02
Can you remove 
```php
foreach ($_['activities'] as $activityData) {
    print_unescaped('DEBUG#' . serialize($activityData));
    p("\n");
}
```
just to be sure we are in the right file

**Comment by Naucum** [comment] 2015-01-13 15:07
On the way...the file is in 
wwwroot\owncloud\apps\activity\templates
just in case of doubts...but i change it now just in case

btw..in case it is importante..the activities can be seen in my account what was uploaded/deleted

**Comment by Naucum** [comment] 2015-01-13 15:09
Like this?

<?php
/** @var OC_L10N $l */
/** @var array $_ */
$l = $_['overwriteL10N'];

print_unescaped($l->t('Hello %s,', array($_['username'])));
p("\n");
p("\n");

if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_HOURLY) {
	p($l->t('You are receiving this email because in the last hour the following things happened at %s', array($_['owncloud_installation'])));
} else if ($_['timeframe'] == \OCA\Activity\UserSettings::EMAIL_SEND_DAILY) {
	p($l->t('You are receiving this email because in the last day the following things happened at %s', array($_['owncloud_installation'])));
} else {
	p($l->t('You are receiving this email because in the last week the following things happened at %s', array($_['owncloud_installation'])));
}
p("\n");
p("\n");

}
p("\n");

**Comment by nickvergessen** [comment] 2015-01-13 15:14
yes

**Comment by nickvergessen** [comment] 2015-01-13 15:14
no, the last `}` has to be removed aswell

**Comment by Naucum** [comment] 2015-01-13 15:16
done....waiting for mail

**Comment by Naucum** [comment] 2015-01-13 17:27
```
* Array
* Array
* Array
* Array
* Array
* Array
* Array
* Array
```
grummel!!!

**Comment by nickvergessen** [comment] 2015-01-13 17:34
Okay, so we have been in the wrong file all the time, since we remove the stuff that creates the `* xyz` lines.
Are you sure you don't use a custom theme in owncloud?

**Comment by Naucum** [comment] 2015-01-13 17:48
As i said before the following files were definitely modified by myself
config.php
layout.guest.php
htaccess.php
defaults.php

Also said that the templates on admin site are the ones where i send you the pictures. Like i said before i m not programmer neither expert and i only edit files to give owncloud a more personal touch with the information that i found in the forum or in github. Also downloaded with your advice a fresh copy of ownlcoud and only put in folder apps/activity. But i dont exclude the posibility that i didnt have edit another php file. As far as i understood it is a file related to a template......so what i can do is to search any php file which incorporate the name template (like templateeditor/templates). That small things which i considered to change (which were not much) could be easy to find. Or if you can give me another info in which php i need to search would be no problem at all. But i have modified just a few things as far as i remember. 
And i only downloaded owncloud from official owncloud website.

**Comment by Naucum** [comment] 2015-01-13 18:14
when i go into admin panel of ownlcoud i see this in Mail Templates
![1](https://cloud.githubusercontent.com/assets/8770484/5726019/680c6646-9b58-11e4-9f95-3e3bb36a522c.jpg)
does this means that there is no custom template in use?

**Comment by Naucum** [comment] 2015-01-13 18:34
If you say the wrong file do you mean that there is another php file called email.notification.php ?

**Comment by Naucum** [comment] 2015-01-13 20:39
ok...Now i think i have the right one..(i guess) because now happens what you looked for.
it was confusesing..because u said the path is
apps/activity/template/email.notification.php
and i think you mean:
\owncloud\apps\activity\templates

but it is:
owncloud\themes\default\apps\activity\templates

And NOW all what you expected happend after trying a first step.

i remove as you said:
´´´
foreach ($_['activities'] as $activityData) {
    print_unescaped('DEBUG#' . serialize($activityData));
    p("\n");
}
´´´´
And i get an empty email with only the standard text but nothing else
OMG......
Well, as you can see....i try also my best :)

**Comment by Naucum** [comment] 2015-01-13 20:48
Testing now with
´´´
foreach ($_['activities'] as $activityData) {
    print_unescaped('DEBUG#' . serialize($activityData));
	p("\n");
}

´´´

**Comment by Naucum** [comment] 2015-01-13 21:52
´´´
Hello David,

You are receiving this email because in the last hour the following things happened at http://mydomain.com/owncloud/

DEBUG#a:2:{i:0;O:14:"OC_L10N_String":4:{s:7:"
´´´
This is the email which i get ...finally something different and..btw..in english instead of spanish

**Comment by nickvergessen** [comment] 2015-01-14 09:29
Okay, so lets start at https://github.com/owncloud/core/issues/13244#issuecomment-69620380 again :)

**Comment by Naucum** [comment] 2015-01-14 09:37
running test with edite lines to

foreach ($_['activities'] as $activityData) {
    print_unescaped($l->t('* %1$s - %2$s', $activityData));
	p("\n");

thanks for your patience :)

**Comment by Naucum** [comment] 2015-01-14 10:47
````
You are receiving this email because in the last day the following things happened at http://mydomain.com/owncloud/

* You deleted Dibujo.JPG - Today 09:35:06
* You deleted 2.jpg - Today 09:35:34
* You created Dibujo.JPG - Today 09:39:42
* You created 1.jpg - Today 09:39:45
* You created 2.jpg - Today 09:39:49
* You created ANCERT.docx - Today 09:39:51
* You created Logo ABAT vectoritzat.PDF - Today
09:40:24
* You created ABAT LOGO - Today 09:48:41
* You created ABAT LOGO/Logo ABAT vectoritzat (2)_001.jpg - Today 09:50:24
* You created ABAT LOGO/Logo ABAT vectoritzat (3)_001.jpg - Today 09:50:27
```
Nickvergessen.....thumbsup...100%. Thank you very much!!!!!
Last thing: 
How to get back to spanish message? Only setting up lang in admin panel to Castellano again?

**Comment by nickvergessen** [comment] 2015-01-14 11:06
yes, changing the language in the personal settings should be enough

**Closed by nickvergessen** 2015-01-14 11:06 UTC
Labels: bug

**Comment by tuminik** [comment] 2019-07-08 19:44
Hi, it's not not get any activity email in my owncloud? i have 10.2 with activity 2.5
