### ISSUE TITLE
Edit link does not open collaborative document editor

### ISSUE THREAD

**Issue by dhsc19** [owncloud/core#20341] opened 2015-11-05 17:01 UTC
I've updated to the latest version 8.2 and I can go to the Documents app and open documents to edit from there. However, from the "Files" app, if I go to a document file and select "edit" from the menu.  It does not open the document editor, just brings me back to the files list.

![image](https://cloud.githubusercontent.com/assets/10291198/10975428/c3500266-839b-11e5-819f-6b0093191e98.png)

**Comment by RealRancor** [comment] 2015-11-05 18:51
@dhsc19 Looks to me like a duplicate of https://github.com/owncloud/documents/issues/564

**Comment by LukasReschke** [comment] 2015-11-06 00:50
> @dhsc19 Looks to me like a duplicate of owncloud/documents#564

Good point. Closing as such. Thanks @RealRancor.

**Closed by LukasReschke** 2015-11-06 00:50 UTC
