### ISSUE TITLE
Sharing files with users (or by link) is very slow [with encryption]

### ISSUE THREAD

**Issue by duelle** [owncloud/core#18145] opened 2015-08-08 17:59 UTC
I am running owncloud 8.1 with activated file encryption on Debian 7 (wheezy) and have some issues when sharing folders with more than a few files. <br/>It takes a very long time to share files with other users (or by link) using the web frontend. After having added a user to the list, the loading icon spawns and I have to wait until it finishes (takes more than a few minutes - if there are about 400 files with ~1 MB per file it takes more than 30 minutes).<br/>
Although the server itself seems not to be under load, I can't really surf the owncloud web frontend in a normal manner as it is very very slow too.<br/>
If there is any further information that is needed to investigate the issue, just ask.

### Steps to reproduce
1. Click the share icon for a folder that contains many files (in my case about 500 files totalling 200mb)
2. Click on the share button of the folder in the web frontend.
3. Select another user (or share link) to share the folder with him/her.
4. The loading icon begins rotating.
5. This process takes a very long time

### Expected behaviour
The sharing process should complete much faster.

### Actual behaviour
The sharing process takes a long time (about 30 min for the example with 500 files at 200mb).
In addition it is not possible to use the web frontend until the sharing process has finished.
The server isn't under high load during this time (neither by other "sources" nor by apache2 or php).

### Server configuration
**Operating system**: Debian 7 (Wheezy)

**Web server:** Apache 2.2.22

**Database:** MySQL Ver 14.14 Distrib 5.5.44

**PHP version:** 5.4.41-0+deb7u1

**ownCloud version:** 8.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - encryption: 1.0.0
 - files: 1.1.9
 - files_antivirus: 0.7.0.1
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'myinstanceid',
  'passwordsalt' => 'mypasswordsalt',
  'secret' => 'mysecret',
  'trusted_domains' => 
  array (
    0 => 'owncloud.mydomain.de',
  ),
  'datadirectory' => '/home/owncloud-data',
  'overwrite.cli.url' => 'https://owncloud.mydomain.de',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'myuser',
  'dbpassword' => 'mypassword',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'mydomain.de',
  'theme' => '',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Firefox 39.0.3

**Operating system:** Linux

#### Web server error log
```
Nothing for the time the sharing process ran
```

#### ownCloud log (data/owncloud.log)
```
Nothing for the time the sharing process ran
```

**Comment by karlitschek** [comment] 2015-08-09 19:16
@schiesbn

**Comment by PVince81** [comment] 2015-08-10 09:41
Thanks for the detailed report.
I see you have encryption enabled, so I suspect that the encryption code is taking a long time to create the share keys for the recipients. But the delay seems quite long for only 500 files.

This is similar to https://github.com/owncloud/core/issues/10959

**Comment by PVince81** [comment] 2015-10-08 12:41
Idea would be a background job for sharing to avoid running into timeouts @schiesbn @rullzer

**Comment by IKevin90** [comment] 2015-10-13 10:48
Same problem here. Encryption on. Sharing 1,3GB folder via link. Takes much time. OC 8.1.3.0

**Comment by schiesbn** [comment] 2015-10-13 12:18
duplicate of: https://github.com/owncloud/core/issues/18359 Please follow up here, we will address it for oC9.0

**Closed by schiesbn** 2015-10-13 12:18 UTC
Labels: app:encryption, bug, sharing
