### ISSUE TITLE
Files cannot be opened / downloaded

### ISSUE THREAD

**Issue by armaccloud** [owncloud/core#14067] opened 2015-02-10 18:40 UTC
Hi,

After upgrading ownCloud from version 7.04 to 8.0 (stable), none of my files can be opened / downloaded anymore. When clicking any file to open or download, I either get a page from the browser saying the files doesn't exist:

![file not found](https://cloud.githubusercontent.com/assets/9272078/6133549/f868d9a0-b15a-11e4-8247-a488e46e2c65.JPG)

or the the Documents app just hangs on 'loading'
![document_loading](https://cloud.githubusercontent.com/assets/9272078/6133772/98101170-b15c-11e4-95d4-66f1bb126515.JPG)

Encryption was enabled in OC7. After the upgrade when I found out I couldn't open my files, took a look at the encryption app; it was enabled in the app-section, but not in the admin section. So I enabled it, but it has no effect. Also enabling it in my personal user section didn't do anything.

OC is running on Ubuntu Server 14.04.

Anything I can do to get this working? Thanks.

**Comment by philsaunders** [comment] 2015-02-10 19:52
Same problem here (Ubuntu 14.04.1, Server OC 8.0).
The upgrade to OC 8.0 destroyed all files. Oops!

**Comment by sarunasb** [comment] 2015-02-10 23:31
After an upgrade from 7 to 8 on Ubuntu 14.04 files can not be downloaded. Encryption was enabled. Corresponding log entry ob admin web interface:

Encryption key not found for "/xxxxxxxxxxxxx" during attempted read via stream

**Comment by mcladyz** [comment] 2015-02-19 09:30
### Steps to reproduce
1. Click "Download" -button of any file in Files-application (Note: Downloading directories works)

### Expected behaviour
The save file dialog should open

### Actual behaviour
HTTP code 404 is returned. Looks like the datadirectory -parameter is not used as a absolute path but as relative instead, see the webserver's log below.

### Server configuration
**Operating system**:  Linux - Debian 7 (64bit)

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 5.4.36

**ownCloud version:** 8

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**

activity
calendar
contacts
files_trashbin
documents
external
files_locking
firstrunwizard
user_ldap
templateeditor
files_pdfviewer
gallery
provisioning_api
sharing
texteditor
updater
files_versions
videoviewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'someserver.net',
  ),
  'datadirectory' => '/data/owncloud',
  'overwrite.cli.url' => 'someserver.net/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 2,
);

```

**Are you using external storage, if yes which one:** /data/owncloud

**Are you using encryption:** no

### Client configuration
**Browser:** Iceweasel 31.4.0

**Operating system:** Linux - Debian 7 (64bit)

### Logs
#### Web server error log
```
2015/02/19 11:11:02 [error] 30203#0: *11536 open() "/srv/www/owncloud/data//owncloud/317c32b4-c309-48f6-893e-bbe0b936c665/files//text.txt" failed (2: No such file or directory), client: xxx.xxx.xxx.xx, server: localhost, request: "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=test.txt HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "someserver.net", referrer: "https://someserver.net/owncloud/index.php/apps/files"

```

#### ownCloud log (data/owncloud.log)
```
```

#### Browser log
```
"NetworkError: 404 Not Found - https://jugfullasun.net/services/index.php/apps/files/ajax/download.php?dir=%2F&files=ars.ics"
```

**Comment by mcladyz** [comment] 2015-02-22 13:49
This seems to occur when serving static files. In my case, Owncloud is not served from web server root and Owncloud doesn't append the path from the url to the static file request (See Web server error log above).

*Workaround*: Disable serving static files (Remove **fastcgi_param MOD_X_ACCEL_REDIRECT_ENABLED on**, in Nginx)

**Comment by PVince81** [comment] 2015-03-06 10:07
Ok so you guys are all on nginx ?

Please double check your nginx config and compare against the docs, I believe there have been some changes: https://doc.owncloud.org/server/8.0/admin_manual/installation/nginx_configuration.html

CC @josh4trunks

**Comment by josh4trunks** [comment] 2015-03-06 15:14
for anyone with x-accel enabled there was a regression introduced in OC8.0.0
this should be fixed soon
https://github.com/owncloud/core/pull/14125
a work around is to temporarily disable x-accel

as for the encryption problems, that must be something different. if encryption is enabled x-accel is never used.

**Closed** 2015-07-17 22:51 UTC
Labels: nginx
