### ISSUE TITLE
users cannot login and files:scan does not complete

### ISSUE THREAD

**Issue by holgerengels** [owncloud/core#26293] opened 2016-10-07 06:09 UTC
### Steps to reproduce
1. updated installation from 8.x to 9.1.0
2. sharing activated
3. users and groups in ldap
4. users and groups had been deleted and recreated in ldap
   (its a school .. hundreds of students come and go every schoolyear, all students change class/groups)

### Expected behaviour
all users should be able to login.
files:scan should report about files and folders for all users

### Actual behaviour
most people can log in, many can't
files:scan works for most people .. for some it just stops without reporting files

### Server configuration
**Operating system**:
ubuntu 14.04

**Web server:**
apache 2.4.7

**Database:**
mysql 5.5.52

**PHP version:**
php 5.5.9

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/

**Signing status (ownCloud 9.0 and above):**
- core
	- EXTRA_FILE
		- Release.key
		
**List of activated apps:**

Enabled:
  - comments: 0.3.0
  - dav: 0.2.5
  - documents: true
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - activity
  - encryption
  - federation
  - files_antivirus
  - files_external
  - user_external
  

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc0or2ahuorl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.1.1.23",
            "10.1.1.4",
            "www.enteredu.de",
            "enteredu.de",
            "cloud.valckenburgschule.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.valckenburgschule.de\/owncloud\/",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "ownCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 3,
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updatechecker": false,
        "theme": "",
        "allow_user_to_change_display_name": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)

| hasMemberOfFilterSupport      | 1                                                                                                                                   |
| hasPagedResultSupport         |                                                                                                                                     |
| homeFolderNamingRule          | attr:cn                                                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                                                                   |
| ldapAgentName                 | cn=Administrator,cn=users,dc=musterschule,dc=schule,dc=paedml                                                                       |
| ldapAgentPassword             | ***                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                     |
| ldapAttributesForUserSearch   | displayName;cn                                                                                                                      |
| ldapBackupHost                |                                                                                                                                     |
| ldapBackupPort                |                                                                                                                                     |
| ldapBase                      | dc=musterschule,dc=schule,dc=paedml                                                                                                 |
| ldapBaseGroups                | ou=Active Directory,ou=Sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml                                                       |
| ldapBaseUsers                 | ou=VBS,ou=Lehrer,ou=Benutzer,dc=musterschule,dc=schule,dc=paedml;ou=VBS,ou=Schueler,ou=Benutzer,dc=musterschule,dc=schule,dc=paedml |
| ldapCacheTTL                  | 600                                                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                                                   |
| ldapDynamicGroupMemberURL     |                                                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                                                |
| ldapExperiencedAdmin          | 1                                                                                                                                   |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                  |
| ldapExpertUUIDUserAttr        | cn                                                                                                                                  |
| ldapExpertUsernameAttr        | cn                                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                                                           |
| ldapGroupFilterGroups         |                                                                                                                                     |
| ldapGroupFilterMode           | 1                                                                                                                                   |
| ldapGroupFilterObjectclass    | group                                                                                                                               |
| ldapGroupMemberAssocAttr      | member                                                                                                                              |
| ldapHost                      | ***                                                                                                                            |
| ldapIgnoreNamingRules         |                                                                                                                                     |
| ldapLoginFilter               | (&(objectClass=person)(cn=%uid))                                                                                                    |
| ldapLoginFilterAttributes     |                                                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                                                   |
| ldapLoginFilterMode           | 1                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                   |
| ldapNestedGroups              | 1                                                                                                                                   |
| ldapOverrideMainServer        | 0                                                                                                                                   |
| ldapPagingSize                | 500                                                                                                                                 |
| ldapPort                      | 389                                                                                                                                 |
| ldapQuotaAttribute            |                                                                                                                                     |
| ldapQuotaDefault              |                                                                                                                                     |
| ldapTLS                       | 0                                                                                                                                   |
| ldapUserDisplayName           | displayname                                                                                                                         |
| ldapUserDisplayName2          |                                                                                                                                     |
| ldapUserFilter                | (&(|(objectclass=person)))                                                                                                          |
| ldapUserFilterGroups          |                                                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                                                   |
| ldapUserFilterObjectclass     | person                                                                                                                              |
| ldapUuidGroupAttribute        | auto                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                   |

### Client configuration
many different .. doesn't matter

### Log from files:scan
sudo -u www-data php -e -f occ files:scan schueler1

{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=schueler2,ou=vbs,ou=schueler,ou=benutzer,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=g_schueler_tablet_1,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Requested attribute memberof not found for cn=g_schueler_tablet_1,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=g_schueler_vbs_vbs_gym1-7g_2016,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Requested attribute memberof not found for cn=g_schueler_vbs_vbs_gym1-7g_2016,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=g_schueler_vbs,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Requested attribute memberof not found for cn=g_schueler_vbs,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=g_internet,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Requested attribute memberof not found for cn=g_internet,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"initializing paged search for  Filter objectClass=* base Array\n(\n    [0] => cn=g_schueler,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eq8U3XxYWO0b1Ayn7aDC","remoteAddr":"","app":"user_ldap","message":"Requested attribute memberof not found for cn=g_schueler,ou=active directory,ou=sicherheitsgruppen,dc=musterschule,dc=schule,dc=paedml","level":0,"time":"2016-10-07T06:03:45+00:00","method":"--","url":"--","user":"--"}

sudo -u www-data strace php -e -f occ files:scan schueler1
.. lots of output ..
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7ffdcb859d60} ---
+++ killed by SIGSEGV (core dumped) +++

**Comment by RealRancor** [comment] 2016-10-07 06:53
> ownCloud version: (see ownCloud admin page) 9.1.0

From the issue template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

This avoids that you're creating bugreports for issues already fixed in newer versions.

In your case both issues here mentioned should be already fix in 9.1.1

**Comment by PVince81** [comment] 2016-10-07 07:13
Duplicate of https://github.com/owncloud/core/issues/25557

Please upgrade to 9.1.1.
If the problem persists, please reopen.

**Closed by PVince81** 2016-10-07 07:13 UTC

**Comment by holgerengels** [comment] 2016-10-08 05:11
damn it! sorry!

I thought, I was on the most current release already, as I made an update right before .. though I didn't realize, that I had to change the package source :-/

.. files:scan is working now with ubuntu 16.04, php7 and owncloud 9.1.1 :-) .. thanks!
