### ISSUE TITLE
Public link buttons dimensions broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#15916] opened 2015-04-28 13:10 UTC
![public-link-button-size](https://cloud.githubusercontent.com/assets/277525/7370177/7c4ab920-edb8-11e4-93c9-6e2f4b0c531a.png)

@jancborchardt can you have a look ?
It happens since https://github.com/owncloud/core/pull/15875

(use this branch https://github.com/owncloud/core/pull/15915 if master is still broken)

**Comment by MorrisJobke** [comment] 2015-04-29 13:46
It's the `display: inline-block;` of the `.button` class.

**Comment by MorrisJobke** [comment] 2015-04-29 13:48
This was caused by #15875

**Comment by MorrisJobke** [comment] 2015-04-29 13:48
@jancborchardt Can you have a look?

**Comment by jancborchardt** [comment] 2015-04-29 15:55
Fixed with the revert, please review: https://github.com/owncloud/core/pull/15942

**Closed** 2015-04-30 06:25 UTC
Labels: bug, design, regression
