### ISSUE TITLE
Integrity check fails [OC 9.0 pre-alpha]

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#22151] opened 2016-02-05 09:47 UTC
Using debian 8 with apache and owncloud nightly:
`deb https://download.owncloud.org/download/repositories/nightly/Debian_8.0/ /`
version.php
````
$OC_Version = array(9,0,0,9);
$OC_VersionString = '9.0 pre alpha';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-02-03T20:53:44+00:00 da0462015507053c4424f62c32a4a182301fae22';
````
(OC_Channel = 'stable' is a bit misleading for a pre-alpha version)

Owncloud itself seems to be working fine, but on the admin-interface, I get an error "there were problems with the code integrity check", when I click on more details, I can get a list of the files:
````
Results
=======
- core
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- user_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- dav
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- templateeditor
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_trashbin
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_sharing
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_versions
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- notifications
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_antivirus
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- gallery
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_texteditor
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- documents
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_videoviewer
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_external
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- federation
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- user_ldap
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- encryption
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- activity
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- systemtags
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- files_pdfviewer
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
- firstrunwizard
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
````

**Comment by LukasReschke** [comment] 2016-02-05 09:51
That's because this nightly has been build before https://github.com/owncloud/core/pull/22111 has been merged. Can you try with the one from https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2 or wait for the tomorrow one?

**Comment by LukasReschke** [comment] 2016-02-05 09:53
… let's keep this open until the new nightly is out for the packages and confirmed to be working :smile:

**Comment by tflidd** [comment] 2016-02-06 22:49
I updated today, there is still a problem, it seems that the certificates are missing:
`file_get_contents(/var/www/owncloud/resources/codesigning/root.crt): failed to open stream: No such file or directory at /var/www/owncloud/lib/private/integritycheck/helpers/fileaccesshelper.php#38 `

The version in the admin panel shows this.
`ownCloud 9.0 pre alpha (daily) Build:2016-02-06T04:44:01+00:00 6ccd5ecb0704a8c34ce3704f5105f34beea30c9f`

When I get the current daily-master.tar.bz2 from owncloud.org, it contains the codesigning certificates, the version.php shows as well:
`$OC_Build = '2016-02-06T04:44:01+00:00 6ccd5ecb0704a8c34ce3704f5105f34beea30c9f'`

debian puts owncloud in /var/www/owncloud, I extracted the archive in /tmp/owncloud, there is a difference:
````
diff -q -r /tmp/owncloud /var/www/owncloud | grep -v apps
Only in /tmp/owncloud/3rdparty: .gitignore
Only in /var/www/owncloud: assets
Only in /var/www/owncloud/config: config.php
Files /tmp/owncloud/config/config.sample.php and /var/www/owncloud/config/config.sample.php differ
Only in /var/www/owncloud: data
Only in /tmp/owncloud: ocs-provider
Only in /tmp/owncloud/resources: codesigning
Files /tmp/owncloud/resources/config/ca-bundle.crt and /var/www/owncloud/resources/config/ca-bundle.crt differ
Only in /tmp/owncloud/resources/config: mimetypealiases.dist.json
Only in /tmp/owncloud/resources/config: mimetypemapping.dist.json
Only in /tmp/owncloud: updater
Only in /tmp/owncloud: .user.ini
````
I was not sure, if I put one day the resources/config/ca-bundle.crt manually and maybe blocked the folder for the package manager. So I removed owncloud from the system and cleaned out the `/var/www/owncloud/`-directory completely (I made a backup of the `data/` and `config/` folder). 

Then installed owncloud again.
Before restoring the backup or running it via webbrowser, I did a diff again:
````
Only in /tmp/owncloud/3rdparty: .gitignore
Only in /var/www/owncloud: assets
Files /tmp/owncloud/config/config.sample.php and /var/www/owncloud/config/config.sample.php differ
Only in /var/www/owncloud: data
Only in /tmp/owncloud: ocs-provider
Only in /tmp/owncloud: resources
Only in /tmp/owncloud: updater
Only in /tmp/owncloud: .user.ini
````
Still, the `resources`-folder is missing.

So the `resources/`-folder seems not to be part of the owncloud-repo. Now I copied the `resources/`-folder manually into the `/var/www/owncloud`-path, the error with the missing *.crt files disappears but I still get an error with a failed integrity check???

**Comment by tflidd** [comment] 2016-02-06 22:55
I just verified and created a new installation from the .tar.bz2-archive, there I have no error at all. So there is something wrong with the packaging. @jnweiger

**Comment by LukasReschke** [comment] 2016-02-07 10:45
@jnweiger @karlitschek How can we make sure that all required folders are bundled?

**Comment by LukasReschke** [comment] 2016-02-07 10:45
@tflidd Thanks a lot for your debugging. :rocket:

**Comment by karlitschek** [comment] 2016-02-07 12:56
Argh. @jnweiger @dragotin Can we please make sure that always all files and folder that are in the tar file are packaged?

**Comment by PVince81** [comment] 2016-02-12 13:32
Hmm, what happens with things like the new updater apps: https://github.com/owncloud/core/issues/22257

**Comment by jnweiger** [comment] 2016-02-12 14:53
Nightly package builds are failing. I'll port packaging code from 9.0-beta1 once it works there.

**Comment by PVince81** [comment] 2016-02-17 17:21
Any update ?

**Comment by jnweiger** [comment] 2016-02-18 14:12
https://download.owncloud.org/download/repositories/nightly/ 
has a successful nightly build from yesterday with the old packaging code.

And
https://obs.int.owncloud.com/package/show/ce:nightly/owncloud 
https://obs.int.owncloud.com/package/show/ce:nightly/owncloud-files

now represent the now packaging, it should hit the download mirror tomorrow moring.

It should be on the

**Comment by PVince81** [comment] 2016-02-23 09:36
Any update, does the check pass now ? @tflidd

**Comment by tflidd** [comment] 2016-02-23 10:01
I'm still blocked due to this packaging issue #22374

**Comment by tflidd** [comment] 2016-02-23 21:23
@PVince81 I managed to update to the latest nightly build and it looks better. There is still a message:
````
Results
=======
- core
	- FILE_MISSING
		- .user.ini
	- EXTRA_FILE
		- etc/owncloud-config-apache.conf.default
````
For the `user.ini`, I never touched this, so I don't know why this file is missing. I am not sure about the `etc/owncloud-config-apache.conf.default`, I have modified the default `/etc/apache2/conf-available/owncloud.conf` because I installed a second owncloud from the zipped-package manually. But I never placed a file in `/var/www/owncloud/etc`.
Could this be my fault? I haven't tried on a fresh system.

**Comment by jnweiger** [comment] 2016-02-24 12:05
Many fixes went into the packaging between Beta1 and Beta2. I believe integrity checks should be covered now.

We no longer split away any sub packages, so all folders will be automatically included. We had issues with updater and resources here. I've checked them in Beta2, all there.

The .user.ini file is included.
The  owncloud-config-apache.conf.default is the template for what goes into /etc/apache2. It is now moved to /usr/share/... where the checker does not check.

@tflidd did you download from https://download.owncloud.org/download/repositories/nightly/ ?
These were fixed Monday evening. I wonder why you did not see them when you tried yesterday.
dpkg -l owncloud-files should print now:
ii    owncloud-files                  9.0.0~beta2.20160224-1.1

With Ubuntu14.04 from ce:nighlty I currently get no integrity warnings.

**Comment by tflidd** [comment] 2016-02-24 17:37
Yes it was https://download.owncloud.org/download/repositories/nightly/
Today I updated to the latest daily, re-run the integrity checker and all warnings disappeared ;-)

**Comment by jnweiger** [comment] 2016-02-24 18:01
Great news. Thanks for testing!

**Closed by jnweiger** 2016-02-24 18:01 UTC
Labels: bug, packaging, sev1-critical

**Comment by nazar-pc** [comment] 2016-04-13 02:55
Got an update today from 8.2.3 to 9.0.1:
```
{"reqId":"***","remoteAddr":"172.17.0.1","app":"PHP","message":"file_get_contents(\/usr\/share\/nginx\/html\/owncloud\/apps\/provisioning_api\/appinfo\/signature.json): failed to open stream: No such file or directory at \/usr\/share\/nginx\/html\/owncloud\/lib\/private\/integritycheck\/helpers\/fileaccesshelper.php#38","level":3,"time":"2016-04-13T02:52:59+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=***","user":"--"}
```

**Comment by nazar-pc** [comment] 2016-04-13 03:39
And eventually:
```
Results
=======
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
```

Looks like regression.

**Comment by lupinehorror** [comment] 2016-04-13 06:51
# @nazar-pc 
exactly the same thing happened when i upgraded this morning.

Results
=======
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by tflidd** [comment] 2016-04-13 06:53
How did you upgrade (packet manager, manually)? And what kind of system?

**Comment by lupinehorror** [comment] 2016-04-13 07:03
@tflidd 
i updated from within owncloud not using a package manager. it's ubuntu 14.04 64bit running php 5.9.

**Comment by tflidd** [comment] 2016-04-13 07:38
As a workaround you can do the manual upgrade procedure:
https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html

If the upgrade path via the updater app failed, you could create a topic on the updater-bugtracker:
https://github.com/owncloud/updater/issues

**Comment by nazar-pc** [comment] 2016-04-13 08:00
For me it was using Updater app.

**Comment by tflidd** [comment] 2016-04-13 08:41
A new topic might be better. I don't know if they pay so much attention to closed issues, furthermore you will have the issue template (https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) with detailed information about your setup and your upgrade procedure. They need to reproduce the error and know what happened (there are many ways to upgrade and a large number of possible systems).

**Comment by HenkUyttenhove** [comment] 2016-04-13 10:47
@tflidd 
I also confirm the problem of the provisioning_api signature data not found after using the updater from within OC.  The manual procedure may resolve this, but prefer to use the build-in updater as console access is not always possible.

**Comment by jnweiger** [comment] 2016-04-13 11:00
Please open a new issue. 
the original report had this error: Certificate is not valid.
You now have another one: Signature data not found.

I've never seen a system with php 5.9, it probably needs some hacking to make the ubuntu 14.04 packages work with php-5.9 -- we need someone from the server team to review the new issue. It is not a simple packaging bug.
I

**Comment by qhaz** [comment] 2016-04-13 11:25
Confirming the same problem here using the updater app - running on RasPi.  I concur with HenkUyttenhove, updater from within OC is preferred option as my RasPi has no monitor attached.

System: Linux chazpi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l 
PHP Version 5.6.19-0+deb8u1

Results
=======
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by jnweiger** [comment] 2016-04-13 11:46
Definitly not a packaging issue then. There are nor RasPi packages.

**Comment by gajet5** [comment] 2016-04-18 12:27
Same problem after the upgrade.

`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- provisioning_api
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [provisioning_api] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)`
