### ISSUE TITLE
Add request header to cancel previous upload transactions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9676] opened 2014-07-16 14:39 UTC
As discussed with @ogoffart here https://github.com/owncloud/core/issues/9513#issuecomment-49170234

To avoid having stray chunks from aborted uploads in the cache folder, the sync client could send an extra header with the previous transaction id so that the server knows what chunks to clean up.

CC @icewind1991 @DeepDiver1975

**Comment by MorrisJobke** [comment] 2016-01-19 00:24
Duplicate of https://github.com/owncloud/core/issues/14646 which also has the better solution proposed.

**Closed by MorrisJobke** 2016-01-19 00:24 UTC
Labels: enhancement
