### ISSUE TITLE
Owncloud synced encrypted folder can't handle directory structure changes / folder rename

### ISSUE THREAD

**Issue by kaplandani** [owncloud/core#19201] opened 2015-09-20 19:05 UTC
This is a bad issue submission, but I have to report it. 
I'm not going to use owncloud in production any more b/c of this. 

I used to have a 8.0.4 server with 2 users. 1 had a 16GB folder tree, and it was sync to a 2nd user. 
encryption was on. 
The 2nd users decided to "re-arrange" the folder tree. moving folder, renaming them and moving file in between them. 

The result was 450 MB folder in the 2nd computer and 750 MB folder in the original computer. 
I don't know how - but most of the files were lost in this process.

I've once requested some kind of warning mechanism when the server decides to mass-erase content on the client and I was told that it is not important or even bad idea. I'm sorry to see I was right about this request, and I hope it will be implement in the future. 

I will move this office to a commercial tool, that has more reliability at the moment. 

While trying to salvage some of the data, I've found files that are located on the server - but the encryption key is missing. maybe it's another problem, maybe it was part of the problem. 
it might also be folder path length issues, I don't know.

**Comment by RealRancor** [comment] 2015-09-20 20:50
Hi,

i think sentences like:

> I will move this office to a commercial tool, that has more reliability at the moment

can be skipped in such reports as no one of the oC contributors is bringing your data in danger on purpose.

If you want to achieve something with your report you might want to fill out the issue template here:

https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

so that someone with the knowledge can have a look.

Additional it could be useful to always use the latest stable version of oC (which is currently 8.0.8 for the 8.0.x branch). It seems you're currently some versions behind and it could be that this issue was already fixed.

**Comment by kaplandani** [comment] 2015-09-20 21:46
@RealRancor I've tried to upgrade, but I had to revert back b/c of a new bug introduced in the new version (I think I've reported it as well, something with concurrency #17887) . I'm sure everyone are doing their best. The mass-delete warning was a major reliability issue in my opinion - and was opposed by other contributors. I won't be able to reproduce this bug, I think it is something you must consider adding to future version (already found products that implemented this exact feature) 
I will check if I can get some logs out of this server.  regarding the sync of folders with encryption - It's will require a team effort to debug I guess. there are too many factors that might have caused this mess.

**Comment by RealRancor** [comment] 2015-09-21 07:44
Hi,

this "mass deletion warning" is a thing of the client which should be already implemented according to https://github.com/owncloud/client/issues/2483

The problem of the deletion of files/folders after a rename is not necessarily related to encryption and could be the problem discussed here: https://github.com/owncloud/core/issues/13391

When reading that issue correctly it should be already fixed in oC 8.1 when files locking is enabled.

**Comment by kaplandani** [comment] 2015-09-21 07:49
I have another owncloud instance. I will upgrade it to the latest server/client version, and I might be able to test it again.

**Comment by blizzz** [comment] 2016-03-01 14:31
I am closing this, because necessary information is missing for a while now. Please reopen, when the required details are known and the issue is still valid.

**Closed by blizzz** 2016-03-01 14:31 UTC
Labels: needs info
