### ISSUE TITLE
Encryption of thumbnails

### ISSUE THREAD

**Issue by Messinger** [owncloud/core#14780] opened 2015-03-10 16:03 UTC
On my owncloud instance I have encryption enabled. 

For some tests I'd checked the thumbnails generated by owncloud and saw - them aren't encrypted, too.

I think, this is real wrong - them should encrypted, too if encryption is enabled.

**Comment by RealRancor** [comment] 2015-03-10 17:11
Hi,

that is the expected behaviour:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/encryption_configuration.html#files-not-encrypted

If you want to request the encryption of thumbnails you probably need to do this at the issue tracker of the gallery app:

https://github.com/owncloud/gallery/issues

**Comment by LukasReschke** [comment] 2015-03-10 18:25
Duplicate of https://github.com/owncloud/core/issues/11790

**Closed by LukasReschke** 2015-03-10 18:25 UTC
Labels: Enhancement
