### ISSUE TITLE
Need better error handling when the redis server is down and files_locking is configured

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#16809] opened 2015-06-08 18:13 UTC
### Steps to reproduce

1. Install 8.1
2. Do not start a redis server 
2. Enable and configure file locking in config.php

### Expected behaviour

ownCloud properly handles the redis server being unavailable

### Actual behaviour

If redis hasn't been started when the server tries to come up, the following error is thrown:

```

An unhandled exception has been thrown:
exception 'RedisException' with message 'Redis server went away' in /var/www/html/owncloud/lib/private/memcache/redis.php:74
Stack trace:
#0 /var/www/html/owncloud/lib/private/memcache/redis.php(74): Redis->get('f22602eb09d8b1e...')
#1 /var/www/html/owncloud/lib/autoloader.php(114): OC\Memcache\Redis->get('OC\Log\ErrorHan...')
#2 [internal function]: OC\Autoloader->load('OC\Log\ErrorHan...')
#3 /var/www/html/owncloud/lib/base.php(575): spl_autoload_call('OC\Log\ErrorHan...')
#4 /var/www/html/owncloud/lib/base.php(1112): OC::init()
#5 /var/www/html/owncloud/console.php(40): require_once('/var/www/html/o...')
#6 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#7 {main}An unhandled exception has been thrown:
exception 'RedisException' with message 'Redis server went away' in /var/www/html/owncloud/lib/private/memcache/redis.php:74

```

If redis goes down after the server has been properly started, the admin user gets a white screen when navigating in the UI.

In either case, is it possible to disable files_locking and display some type of message?

### Server 1 Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration:

ownCloud Enterprise Edition 8.1 beta 2 (daily) Build:2015-06-08T03:08:20+00:00 35421487610462b12e3600954f23a777c54abee3

**Comment by DeepDiver1975** [comment] 2015-06-08 18:34
> In either case, is it possible to disable files_locking and display some type of message?

We shall not automatically degrade the system - if a required system component is not available we shall stop operations.

required system components:
- web server
- database
- session storage (what ever is configured)
- ldap server
- what ever else setup auth backend (imap server/smb/shib/....)
- memcache service ()
- redis for locking

**Comment by PVince81** [comment] 2015-06-09 09:51
Okay, so if I understand well this means no fallback on the "Null" Memcache if memcache is not available. It should log an error and fail hard, showing an exception in the web UI ?

**Comment by DeepDiver1975** [comment] 2015-06-09 10:08
> It should log an error and fail hard, showing an exception in the web UI ?

yes - which is basically already the case if I understand this correctly

**Comment by PVince81** [comment] 2015-06-09 10:09
No it doesn't fail hard currently.
If either the redis PHP module is missing or the redis server is not reachable, it silently falls back to using the "Null" memcache that does nothing.

**Comment by PVince81** [comment] 2015-06-09 10:10
also if you forget to add:
`'memcache.locking' => '\\OC\\Memcache\\Redis',`
even though filelocking is enabled, it will also silently use the "Null" memcache.

**Comment by DeepDiver1975** [comment] 2015-06-09 10:13
This is true - so as soon as file locking is enabled it either works or fails hard - sounds reasonable to me.

@karlitschek objections?

**Comment by PVince81** [comment] 2015-06-09 10:21
Reread @jnfrmarks's report. So there seems to be at least one situation that would show an exception.
Now I don't know why that exception isn't shown in the web UI, maybe because it happens much too early in base.php ...

**Comment by DeepDiver1975** [comment] 2015-06-09 10:23
> #0 /var/www/html/owncloud/lib/private/memcache/redis.php(74): Redis->get('f22602eb09d8b1e...') #1 /var/www/html/owncloud/lib/autoloader.php(114): OC\Memcache\Redis->get('OC\Log\ErrorHan...') #2 [internal function]: OC\Autoloader->load('OC\Log\ErrorHan...') #3 /var/www/html/owncloud/lib/base.php(575): spl_autoload_call('OC\Log\ErrorHan...')

the exception is thrown in the autoloader - far to early to render any thing reasonable

**Comment by PVince81** [comment] 2015-06-09 10:28
Hmm, this error doesn't even seem related to file locking but to the regular redis memcache.
@jnfrmarks did you configure redis also for local caching ?

The stack trace shows that something is trying to get the Log error handler from memcache: `OC\Memcache\Redis->get('OC\Log\ErrorHan...')`.
From what I heard, some classes might be cached in memcache to avoid having to reload them from disk ? In such case it is impossible to show a proper error message in the UI.

Let's split this issue in two:
1) In the case of file locking, fail hard if redis/memcache for **locking** isn't setup properly. Show exception in UI, this should be possible as it happens later.

2) Unrelated to file locking: if redis or any memcache is used for caching PHP classes, there is nothing that can be done.

So let's focus only on fixing 1)

**Comment by PVince81** [comment] 2015-06-09 10:29
@jnfrmarks when testing file locking, please only set "memcache.locking" and leave the other memcache settings disabled to avoid confusion, as they are not related at all with locking.

**Comment by PVince81** [comment] 2015-06-09 13:27
Closing as duplicate of https://github.com/owncloud/core/issues/16696

**Closed by PVince81** 2015-06-09 13:27 UTC
Labels: sev2-high
