### ISSUE TITLE
Detect chunked upload timeouts and retry

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#30770] opened 2018-03-13 15:21 UTC
With IE uploads sometimes get stuck. Very important issue for the next server release.

**Comment by ownclouders** [comment] 2018-03-13 15:29
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25480 (Detect DB connection timeout and retry connection), https://github.com/owncloud/core/issues/16278 (Problems with Chunked upload), https://github.com/owncloud/core/issues/5326 (web dav chunked upload tasks), https://github.com/owncloud/core/issues/14603 (Disable / detect mod_reqtimeout to avoid upload problems), and https://github.com/owncloud/core/issues/17996 (Prevent uploading the same chunk twice).

**Comment by butonic** [comment] 2018-03-13 19:37
hm https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#resuming-file-uploads & https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads#automatic-resume look promising. I already have the test code that aborts the stalled upload. It should be possible to customize these snippets to automatically resume the upload at the right chunk if we can get the current chunk or the number of uploaded bytes from the server.

@PVince81 IIRC you wanted to get rid of blueimp ...

**Comment by PVince81** [comment] 2018-03-14 09:04
blueimp is not fully compatible with our way of doing chunking, so it might be rather tricky to make it resume. still worth a try ?

**Comment by felixboehm** [comment] 2018-03-27 13:10
If a upload breaks for any reason, ideally we can just continue that upload.
Yet, on client side the state for "currently uploading fileXYZ" is lost, when the page is reloaded.
Does it make sense to store this state on the server to retry on stalled uploads?
@PVince81 @butonic

**Comment by PVince81** [comment] 2018-03-27 13:26
At some point in the future we can consider saving upload state on the server, out of scope for this fix as it involves a lot of changes in the server to make the upload stateful. Additionally we'd need to make sure that the file being resume is exactly the same as the one we just started.

For the scope of this fix the goal is to make it resume without reloading the page as the state information is still there in some form.

**Comment by felixboehm** [comment] 2018-03-27 13:35
ok, when the reason for the failing uploads is not needing a reload.

**Comment by PVince81** [comment] 2018-03-27 15:34
In Phoenix let's experiment with resumable.js: https://github.com/owncloud/phoenix/issues/67.

If it turns out that it works well we could consider backporting...

**Comment by butonic** [comment] 2018-04-04 07:39
- [ ] disable trace

**Comment by PVince81** [comment] 2018-04-18 10:52
the fix is causing trouble now on stable10 / v10.0.8RC2, reverting https://github.com/owncloud/core/pull/31185 for the release

**Comment by PVince81** [comment] 2018-05-28 16:41
needs rescheduling

**Comment by PVince81** [comment] 2018-07-26 13:32
bringing back the old PR where work will continue: https://github.com/owncloud/core/pull/32170

**Comment by PVince81** [comment] 2018-07-26 13:50
from the changelog, this is what did not work while testing:

> when simulating chunk failure, the upload finishes with error about sum of chunks sizes not matching

**Comment by PVince81** [comment] 2018-07-27 14:24
ok, seems the problem is solved: the PR itself was ok but the code that simulated failure wasn't behaving correctly and was returning success instead of an error code on timeout.

I've adjusted the "patch that simulates timeout" here: https://gist.github.com/PVince81/2978ed02a21876fd9e58f74beda7e5c0

In the future it would be nice to have something in the testing app so one would only need to set some oc_appconfig settings, see the idea here: https://github.com/owncloud/core/issues/32183

**Comment by PVince81** [comment] 2018-08-01 08:53
PR was merged, will be in 10.0.10. closing

**Closed by PVince81** 2018-08-01 08:53 UTC
Labels: blue-ticket, bug, p2-high, server, sev2-high
