### ISSUE TITLE
Uploading large files in browser with PUT and chunks.

### ISSUE THREAD

**Issue by macdabby** [owncloud/core#25181] opened 2016-06-19 20:11 UTC
My current environment, Nginx with PHP FPM - although the same issue is present in apache and other php configurations.

Currently if I want to upload a 10gig file, i would be required to change the max file size in nginx to 10G, as well as the max file size in PHP-FPM, as well as the memory requirement in PHP-FPM. The memory requirement one is the worst because I only have 4G on the server.

In HTML5, there is now an option to read a file into chunks and upload using separate requests, as implemented in this JS library:

https://github.com/23/resumable.js

It would be great to implement this into the web interface, as well as the app to be able to upload large files in smaller chunks, so that the size and memory of the web server and php server are irrelevant. even with an external storage system, if the file were written to a temp directory, it could be moved to an external storage system (or standard data storage location) once it's complete.

**Comment by tflidd** [comment] 2016-06-20 12:53
There is also an app claiming to upload large files:
https://apps.owncloud.com/content/show.php/FlowUpload?content=174536

**Comment by PVince81** [comment] 2016-06-21 11:00
Partially discussed in https://github.com/owncloud/core/issues/4380 which is the first step.

But there is no dedicated ticket for PUT chunking in the browser, so reusing this one.

**Comment by PVince81** [comment] 2016-10-07 14:24
Okay, there is indeed an older ticket. Closing as duplicate of https://github.com/owncloud/core/issues/8955

**Closed by PVince81** 2016-10-07 14:24 UTC
Labels: app:files, enhancement
