### ISSUE TITLE
onedrive storage app

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#30527] opened 2018-02-19 11:14 UTC
I know, has already been asked years ago...

Is it intended to create a onedrive app?
Could work similar to the dropbox app with oAuth2

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth

At the bottom of: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_list_children
Link to: https://github.com/krizalys/onedrive-php-sdk

**Comment by PVince81** [comment] 2018-02-19 11:16
duplicate of https://github.com/owncloud/core/issues/14478

**Comment by DeepDiver1975** [comment] 2018-02-19 11:16
The onedrive app is part of the enterprise edition - so technically this ticket is closed from the perspective of ownCloud GmbH

**Closed by PVince81** 2018-02-19 11:16 UTC

**Comment by PVince81** [comment] 2018-02-19 11:18
in general I wonder if we should ask app requests to be open in https://central.owncloud.org/c/apps because this is not the kind of functionality we would want to add directly to core.

remember that we want to move out external storage backends to apps here: https://github.com/owncloud/core/issues/27049

**Comment by mmattel** [comment] 2018-02-19 11:52
I was searching the marketplace before writing this issue.
There is no mentioning about a onedrive app at all, only sharepoint...
ok to close, but confusing with respect that this is not made clear.

If there is an extra app for onedrive, name it
If the sharepoint app is used to access onedrive, name it. (at least for me, sp and od are different things)

**Comment by PVince81** [comment] 2018-02-19 11:54
the enterprise onedrive app hasn't been released yet, I think it's in pending QA

**Comment by mmattel** [comment] 2018-02-19 12:08
A / The onedrive would have eased my life ... :cry:
