### ISSUE TITLE
Favoriting a "San Franciso.jpg" fails

### ISSUE THREAD

**Issue by szepeviktor** [owncloud/core#23173] opened 2016-03-12 01:13 UTC
It is not possible to favorite a file with a space in its name.

### Actual behaviour
"An error occurred while trying to update the tags" by JS.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** Apache 2.4/PHP-FPM 5.6

**Database:** MariaDB

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Where did you install ownCloud from:** tar

**List of activated apps:** 
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.10
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4

**Comment by LukasReschke** [comment] 2016-03-12 21:00
> "An error occurred while trying to update the tags" by JS.

Can you provide the system logs as well as the response received by ownCloud in your browser? Thanks a lot.

(use your browsers' network console for that)

**Comment by szepeviktor** [comment] 2016-03-14 10:21
Excuse me, I don't use OC.
It was a test install in 10 minutes.

**Comment by PVince81** [comment] 2016-03-14 11:28
Works for me.

Possibly the php5-fpm issue, closing as duplicate of: https://github.com/owncloud/core/issues/14930

**Closed by PVince81** 2016-03-14 11:28 UTC
Labels: needs info

**Comment by szepeviktor** [comment] 2016-03-14 12:02
All other files cloud be favorited.

**Comment by PVince81** [comment] 2016-03-14 12:43
Without more information from your setup's browser network console, javascript console and others it will be difficult to reproduce or debug locally.

On all setups I tried this on it works fine.
