### ISSUE TITLE
external storage does not mount, no usable feedback

### ISSUE THREAD

**Issue by dronus** [owncloud/core#13504] opened 2015-01-20 11:34 UTC
While creating an external storage mount to another owncloud instance, I encountered the mount not working, the GUI showing a red rectangle. 

Despite the login data is perfectly correct, I can imagine dozens of reasons for failure.

The owncloud log also does not mention anything related to external storage.

How should one ever get this working (despite it may be a real owncloud bug) without any usable feedback?

While a green rectangle is some kind of intuitive, a red rectangle is extremely useless.

**Comment by karlitschek** [comment] 2015-01-20 16:14
@PVince81

**Comment by PVince81** [comment] 2015-01-20 16:29
Duplicate of https://github.com/owncloud/core/issues/11796

**Closed by PVince81** 2015-01-20 16:29 UTC
Labels: bug
