### ISSUE TITLE
Initial remote share of a photo does not show up in pictures app

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/core#13566] opened 2015-01-21 16:08 UTC
### Steps to reproduce

1. Install owncloud on two systems
2. on system one, create a directory and upload a photo inot it.
3. Remote share the directory with a user on system 2
3. on system two, log in and accept the share
4. on system two, go to the pictures app
5. the newly shared photo is not there
6. as a different user on system two, share another photo with user 1
7. as user 1 on system two, go to the pictures app
8. both the remote shared and the local shared photos show up

### Expected behaviour

The photo is present in step 5

### Actual behaviour

The version numbers are different

The photo is not present in step 5.

### Server Host info:

Ubuntu 14.04
PHP 5.5.9

### Server configuration

ownCloud Enterprise Edition 8.0 beta 1 (daily) Build:2015-01-21T04:13:37+00:00

**Comment by schiesbn** [comment] 2015-01-21 18:47
can't reproduce it, works fine on master.

**Comment by schiesbn** [comment] 2015-01-21 19:34
Both @jnfrmarks and I can't reproduce this issue anymore so we agreed to close it for now.

**Comment by jnfrmarks** [comment] 2015-01-21 21:33
I figured it out: The share has to be of a directory containing a picture.  Before, we were sharing the photo itself.  I'll fix the directions above.

**Comment by jnfrmarks** [comment] 2015-05-05 18:41
I just retested with 8.1.  With 8.1 the UI hangs; it's stuck on the spinner and the server log file has file_locking errors.  I think we need to resolve the thumbnails issue (files_locking/issues/#23) and then retest this.

@DeepDiver1975

**Comment by DeepDiver1975** [comment] 2015-05-07 09:28
@jnfrmarks mind retesting this? owncloud/files_locking#23 was merged

**Closed** 2015-05-15 15:56 UTC
Labels: bug, feature:federated-cloud-sharing, needs info, sev1-critical
