### ISSUE TITLE
8.2.1 - users tab with 1,000+ users does not load all users at once

### ISSUE THREAD

**Issue by oniled** [owncloud/core#20936] opened 2015-12-03 23:14 UTC
### Steps to reproduce
1. Enable LDAP and connect to Active Directory with over 1,000 users
2. Go to Users page
3. See x number of users but not all.  Scroll down to load more.  Repeat several times to see all users

### Expected behaviour
All users load at once (https://github.com/owncloud/core/issues/1068 - this closed issue says it was fixed in version 7.  I'm using 8.2.1 and error continues.  I've looked at that closed issue but the fixes described do not apply in version 8)

### Actual behaviour
Some users load, not all.  To load all users I need to scroll down several times

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.6

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** fresh

**List of activated apps:**

```
activity
encryption
files
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_videoviewer
notifications
provisioning_api
templateeditor
user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc2qmzeln94o',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'mysql',
  'default_language' => 'en_GB',
  'version' => '8.2.1.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'America/Los_Angeles',
  'installed' => true,
"config.php" 40L, 1182C

```

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)

```

+-------------------------------+----------------------------------------------------+
| Configuration                 |                                                    |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                  |
| hasPagedResultSupport         |                                                    |
| homeFolderNamingRule          |                                                    |
| lastJpegPhotoLookup           | 0                                                  |
| ldapAgentName                 | ownCloud                                           |
| ldapAgentPassword             | ***                                                |
| ldapAttributesForGroupSearch  |                                                    |
| ldapAttributesForUserSearch   |                                                    |
| ldapBackupHost                |                                                    |
| ldapBackupPort                |                                                    |
| ldapBase                      | dc=xxx,dc=edu                                      |
| ldapBaseGroups                | dc=xxx,dc=edu                                     |
| ldapBaseUsers                 | dc=xxx,dc=edu                                     |
| ldapCacheTTL                  | 600                                                |
| ldapConfigurationActive       | 1                                                  |
| ldapEmailAttribute            |                                                    |
| ldapExperiencedAdmin          | 0                                                  |
| ldapExpertUUIDGroupAttr       |                                                    |
| ldapExpertUUIDUserAttr        |                                                    |
| ldapExpertUsernameAttr        | sAMAccountName                                     |
| ldapGroupDisplayName          | cn                                                 |
| ldapGroupFilter               |                                                    |
| ldapGroupFilterGroups         |                                                    |
| ldapGroupFilterMode           | 0                                                  |
| ldapGroupFilterObjectclass    |                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                       |
| ldapHost                      | 256.256.256.256                                    |
| ldapIgnoreNamingRules         |                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                    |
| ldapLoginFilterEmail          | 0                                                  |
| ldapLoginFilterMode           | 0                                                  |
| ldapLoginFilterUsername       | 1                                                  |
| ldapNestedGroups              | 1                                                  |
| ldapOverrideMainServer        |                                                    |
| ldapPagingSize                | 0                                                  |
| ldapPort                      | 389                                                |
| ldapQuotaAttribute            |                                                    |
| ldapQuotaDefault              |                                                    |
| ldapTLS                       | 0                                                  |
| ldapUserDisplayName           | displayName                                        |
| ldapUserFilter                | (&(|(objectclass=person)))                         |
| ldapUserFilterGroups          |                                                    |
| ldapUserFilterMode            | 0                                                  |
| ldapUserFilterObjectclass     | person                                             |
| ldapUuidGroupAttribute        | auto                                               |
| ldapUuidUserAttribute         | auto                                               |
| turnOffCertCheck              | 0                                                  |
| useMemberOfToDetectMembership | 1                                                  |
+-------------------------------+----------------------------------------------------+


```

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10 / Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VmDISgbdFeW-GANMl8JptQAAAAg","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T14:55:06-08:00"}
{"reqId":"VmDIXFA9FOHBiGLIyvb7UwAAAAM","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T14:55:24-08:00"}
{"reqId":"VmDIaAKA2keq2KNkQHIplwAAAAk","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T14:55:36-08:00"}
{"reqId":"VmDJVhQ4@szJ7zo6RW742gAAAAg","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T14:59:34-08:00"}
{"reqId":"VmDJnprdc8gQiuVLHSo9pQAAAAE","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T15:00:46-08:00"}
{"reqId":"VmDKUnPdc0yfL0WdaLio5QAAAAI","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T15:03:46-08:00"}
{"reqId":"VmDPCi@KMDBz7@83W@aGVwAAAAA","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T15:23:54-08:00"}
{"reqId":"VmDPfoyDEQdzCsEAc31ISwAAAAQ","remoteAddr":"130.191.67.149","app":"PHP","message":"ldap_read(): Search: Invalid DN syntax at \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/ldap.php#257","level":3,"time":"2015-12-03T15:25:50-08:00"}

```

**Comment by LukasReschke** [comment] 2015-12-03 23:16
@owncloud/ldap Thoughts?

**Comment by oniled** [comment] 2015-12-03 23:35
Made a video if that helps.  https://youtu.be/BNjv3Q4VMC0

**Comment by blizzz** [comment] 2015-12-04 00:05
Works as intended. What do you want to achieve?

**Comment by oniled** [comment] 2015-12-04 00:11
Ah.  

Is there a way so that when I click the Users page it loads all the users so I don't need to scroll?  I tried looking for the values specified in that old issue but the settings/users.php functions differently in 8 versus 7.  the "fixes" done in the past issue don't seem to apply

**Comment by PVince81** [comment] 2015-12-04 10:38
The problem with loading all users is that it will delay the whole page, especially with a big number of users. That's why the scrolling was added.

Now you might be able to increase the page size with this patch https://github.com/owncloud/core/pull/20108

Or you can use the search field on the top right to search for given users.

**Comment by oniled** [comment] 2015-12-04 16:19
That patch is perfect and the search works great.  This is resolved.  Thanks so much guys.

**Comment by PVince81** [comment] 2015-12-04 16:21
Glad to her. I'll close this.

**Closed by PVince81** 2015-12-04 16:21 UTC
Labels: app:user_ldap, triage, won' t fix
